string DLG_TEXT[58] = {
"Você tem mercadorias para trocar ou só precisa de alguns itens pessoais, capitão?",
"Mostre-me o que você tem para negociar em mercadorias de carga, gostaria de ver seus preços.",
"Gostaria de negociar itens pessoais, se os preços forem bons.",
"Não negociaremos neste momento. Desejo-te um bom dia.",
"Bem cumprido, ",
". Minha humilde loja está ao seu serviço.",
"Obrigado, meu nome é ",
".",
"Ora, na verdade! Meu querido ",
". Feliz em ver você. Vamos negociar?",
"O que você quer desta vez, capitão?",
"Ah, capitão! Ore, o que posso fazer por você?",
"Deixe-nos ver o que você tem.",
"Primeiro, gostaria de falar com você.",
"Adeus.",
"Muito prazer em te conhecer, ",
". Eu sou ",
". Espero que este seja o início de um forte relacionamento comercial.",
"Bem, ",
", vamos ver o que você tem para negociar.",
"Eu gostaria de falar com você, ",
".",
"Bom dia.",
"É sempre um prazer conversar com você, capitão.",
"Eu estou ouvindo.",
"Pediram-me para entregar uma carga para você.",
"Você, por acaso, precisaria de um capitão, senhor? Tenho um navio excelente e posso entregar qualquer carga, onde você quiser.",
"Não tenho tempo para conversar agora.",
"Não, não preciso dos seus serviços. Pelo menos enquanto você estiver afundando navios #snation_desc#.",
"Nesse caso, bom dia para você.",
"Sinto muito, mas não tenho nada para você no momento.",
"Tentarei voltar mais tarde, então.",
"Sinto muito, mas seu navio não tem capacidade para a tarefa que tenho em mente.",
"Tentarei voltar mais tarde, então.",
"Oh! Eu só ia pedir que você me fizesse um favor. Veja, preciso entregar alguma carga para ",
", e o mais rápido possível! Se você conseguir fazer isso dentro de um mês, receberá ",
" ouro quando você chegar! O que você acha desta oferta?",
"Eu certamente gosto disso!",
"Temo não poder aceitar isso.",
"Já te disse hoje que não tenho nada para você.",
"Ah, que verdade. Perdão.",
"Você parece ter se lembrado de sua tarefa um pouco tarde demais, não acha? Vou levar a mercadoria de qualquer maneira, mas não espere ser pago. Preste mais atenção na próxima vez! Bom dia.",
"Infelizmente, eu estava muito atrasado. Adeus.",
"Oh! Estou esperando por isso há tanto tempo! Aqui está sua recompensa, jovem ",
"!",
"Sempre bem-vindo.",
"Como quiser, ",
".",
"Deixe-nos ver o que você tem em mãos.",
"Obrigado pela ajuda. Te verei em breve.",
"Infelizmente ",
", os franceses confiscaram a maior parte dos meus bens e munições e proibiram-me de vender o resto até o fim da guerra.",
"Maldita sorte!",
"Recuso-me a negociar com uma pessoa com a sua reputação e relações. Agora saia, ",
", antes de chamar os guardas.",
"Muito bem.",
"Porque sim! Aguardo #squantity#cwt de #scargo#. Você tem?",
"Hum... algumas delas parecem ter sido extraviadas. Não se preocupe, vou repor o que foi perdido e trazer para você!",
};
