string DLG_TEXT[117] = {
"Ah, uma cara nova na minha taberna! Bem-vindo querido ",
"!",
"Prazer em te conhecer. Meu nome é ",
".",
"Guarde sua cortesia para outra pessoa. EU, ",
", não precisa disso.",
"Você é um verdadeiro cavalheiro. Coisa rara por aqui. Meu nome é ",
". O que te traz aqui?",
"Se você não gosta tanto do meu sorriso, talvez eu o leve para outro lugar. ",
"Estritamente negócios.",
"Bem, não estamos impressionados com nós mesmos? Só lamento não ter tempo para te reduzir ao tamanho.",
"Negócios? Você se encontra na melhor taberna do nosso arquipélago! Deixe esse olhar severo para a porta e tome uma bebida!",
"Eh. Seu negócio é seu negócio. A menos que eu possa pegar uma bebida para você?",
"Muito bem. Sirva-me um pouco do seu melhor vinho.",
"Quero vinho, mas não a água de lavar louça que você vende aos seus clientes regulares.",
"Infelizmente, não posso perder tempo. Adeus.",
"Beber aquele veneno que você passa para seus convidados? Eu valorizo demais minha saúde. Bom dia!",
"Por apenas um ouro você pode conseguir o melhor vinho que já provou na vida!",
"2 de ouro e verei o que posso fazer por você.",
"Tudo bem, estou com vontade de jogar. Mas quero mais do que vinho por este ouro. Também vou precisar de algumas informações.",
"Aqui está o seu dinheiro, mas fique com o seu vinho. Prefiro que você apenas responda algumas perguntas para mim.",
"Parece que não posso comprar nada da sua adega. Que tal um pouco de rum?",
"Estou surpreso que você tenha a coragem de pedir dinheiro por essa lavagem. Apenas me traga um pouco de rum!",
"Rum também custa 1 ouro. Você não tem dinheiro, isso não é problema meu.",
"O quê, você ainda está aqui? Você também não pode pagar os 2 ouros por rum...",
"Tudo bem, traga seu vinho. Então você pode me responder algumas perguntas...",
"Droga, é um assalto à luz do dia! Traga o vinho e responda às minhas perguntas.",
"Muito ruim.",
"Tenho certeza de que viverei mais um dia sem o seu vinho.",
"Então o que posso fazer por você?",
"Eu gostaria de falar de negócios com você. Negócio muito importante...",
"Você tem um quarto livre? Eu gostaria de ficar aqui por algum tempo",
"Você ainda tem algum quarto nesta taverna pulga?",
"Preciso de algumas informações sobre esta cidade.",
"Eu tenho um quarto. Quanto tempo você vai precisar?",
"Só até de manhã.",
"Só preciso de um lugar para descansar os olhos até esta noite.",
"Vai custar 5 moedas.",
"Aqui está o seu dinheiro.",
"Bem, parece que o luxo de uma cama confortável está fora do meu alcance neste momento. Vou passar a noite na taverna",
"Para que?! Todo este edifício? Esqueça. Vou passar a noite na taverna",
"Tudo bem, vou pensar sobre isso.",
"Vai custar 5 moedas de ouro.",
"Aqui está o seu dinheiro.",
"Bem, parece que o luxo de uma cama confortável está fora do meu alcance neste momento. Vou passar a noite na taverna",
"O quê, é um quarto king-size? Não, obrigado. Vou sentar-me no salão da taberna",
"Tudo bem, vou pensar sobre isso.",
"Gostaria de lhe fazer algumas perguntas.",
"Não conheço muito bem a cidade. Pode me ajudar?",
"Estou procurando contratar uma equipe.",
"Preciso encontrar a loja local.",
"Meu navio precisa de reparos...",
"Sou todo ouvidos, ",
".",
"Qual é a fofoca aqui?",
"Eu preciso de algum trabalho. Você não conhece nenhum garoto rico nesta ilha que tenha medo de viajar sozinho?",
"Obrigado. Preciso ir agora.",
"Se existir tal pessoa, ela pode preferir evitar atrair a atenção de tantas consortes - como eu espero que você saiba.",
"Sim, esqueci. Tudo bem, voltarei mais tarde, quando tiver menos navios, ha-ha.",
"Não quero ajudá-lo, com todo o mal que você causou ao meu país.",
"Basta olhar para este patriota. Bem adeus.",
"Suas mãos estão cobertas de sangue. Você acha mesmo que alguém vai viajar na sua companhia?",
"Você está certo, todo mundo tem medo de mim! Ha-ha!",
"Você chegou bem na hora. Um comerciante aqui estava procurando navegar na companhia dos companheiros certos. É melhor você falar com ele. Aqui está ele, entrando na taverna.",
"Eu farei isso.",
"Não, não há ninguém no momento. Talvez na próxima vez.",
"Hum. Então vou esperar.",
"Eu tenho mais algumas perguntas.",
"Olá, ",
", muito tempo sem ver. Como vai?",
"Bem bem. Importa-se se eu lhe fizer algumas perguntas?",
"Nenhum de seus negócios. Eu farei as perguntas.",
"Estou pensando em adicionar alguns marinheiros à minha tripulação.",
"Apenas me indique a ralé mais desagradável em busca de trabalho. Preciso de alguns assassinos para o meu navio.",
"Você tem um quarto para mim? Eu gostaria de ficar aqui.",
"Você tem um quarto livre neste poço?",
"Você conhece minha regra - você não pede, não faz perguntas.",
"Não, não gosto disso, não vou pagar.",
"Aqui está o seu dinheiro.",
"Obrigado, você foi de grande ajuda.",
"O que você está falando?! Eu não tenho nada a ver com isso!",
"Muito ruim. Vou ter que procurar em outro lugar.",
"Desculpe, ",
", mas não posso mais ajudá-lo. Experimente os trabalhadores do porto.",
"Obrigado, vou tentar.",
"Sim, ele realmente deve algum dinheiro. 500 ouro.",
"Eu vejo. Eu estava pensando. Adeus.",
"Eu quero pagar a dívida dele.",
"Não vejo por que ",
", ele não é um homem muito bom.",
"Talvez você esteja certo. Vou seguir seu conselho.",
"Eu gosto dele. Bruto, mas estou acostumado com isso. Eu pagarei a dívida dele.",
"De jeito nenhum! É sempre um prazer ajudá-lo.",
"Até a próxima!",
"Como quiser, mas não diga que não avisei. Ele me deve 500 ouro.",
"Sim, bem, você pode estar certo. Deixa para lá.",
"Aqui está o seu dinheiro.",
"Muito bem. E aqui está seu I.O.U. É seu para fazer o que quiser.",
"Adeus!",
"O que você está falando? Todos estão em casa. É meio da noite. Se eu fosse você, esperaria até de manhã. Talvez você queira alugar um quarto?",
"Você tem um quarto livre?",
"Não, vamos falar de outra coisa.",
"Desculpe, capitão. Não tenho nada para você. Capitão ",
"Pare com esse ultraje imediatamente ou terei que chamar os guardas!",
"Tudo bem, tudo bem! Estou indo embora!",
"Até amanhã ",
"Quero dar rum grátis aos tripulantes de um navio chamado 'Arabella' esta noite. Serão cerca de cem homens. Quanto ouro preciso lhe dar para organizar isso?",
"Por uma noite inteira e essa quantidade de homens, posso cobrar nada menos que 1000 moedas de ouro.",
"Muito bem então. Não diga a eles que eu organizei isso para eles. Quero fazer uma surpresa para eles. Se perguntarem, diga que sua filha vai se casar amanhã e que você quer comemorar.",
"Hum. Isso é bastante. Eu voltarei.",
"Está tão bom quanto feito. Eu gostaria que tivéssemos clientes como você todos os dias!",
"Não conte comigo fazendo coisas assim todos os dias. Esta é uma exceção que ocorre uma vez na vida, então aproveite o momento.",
"Você sabe se #svillain# esteve aqui?",
"Se #spronoun# esteve em #sPointe a Pitre#, #spronoun# não esteve nesta taberna.",
"Então você sabe se o '#sship#' esteve no porto?",
"Sim. É um dos tripulantes dela. Ei você! Esta #sperson# quer falar com você!",
"Obrigado.",
};
