string DLG_TEXT[46] = {
"O que alguém pode fazer por um?",
"Er, nada. Desculpe incomodá-lo.",
"Capitão. Você está aqui antes de mim, e ",
"Mateus Santos",
" ainda está vivo e bem. Você decepciona um. Terrivelmente!",
"Mantenha sua camisa, sua camisa feminina grande e fofa com babados...",
"Capitão, o que você está fazendo aqui? Pelo que se sabe ",
"Mateus Santos",
" ainda está vivo.",
"Sim, bem, o vento mudou, meu amigo, e a maré mudou. ",
"Mateus Santos",
" me fez uma... oferta mais convincente. Você pode orar antes de morrer, mas seja rápido. Sou um #sgender# ocupado.",
"Sim, e você me enganou. O trabalho acabou por ser tudo menos simples. Esse ",
"Mateus Santos",
" Acontece que não é um alvo fácil. Na verdade, ele me ofereceu um bom dinheiro em troca da sua pele mentirosa.",
"Capitão, você poderia dispensar um por um momento? Alguém tem uma tarefa que requer um #sgender# de suas habilidades únicas e...reputação.",
"Estou ouvindo, mas não por muito tempo...",
"Se você me conhece de reputação, então já sabe que não tolero tolos de bom grado.",
"Como você fará, mas nunca se pensou que veria o dia em que outro recusaria um bom dinheiro por um empreendimento tão insignificante.",
"Quão insignificante e quanto dinheiro? Você tem toda a minha atenção.",
"Você ainda está falando? Já basta!",
"Ah, é a própria simplicidade, se alguém tiver estômago para isso, e suspeito que você tenha. Há um sujeito que está ameaçando alguém e esse alguém quer que isso pare. Já ouvimos dizer que você é o tipo de #sgender# que consegue convencer as pessoas de quase tudo.",
"Alguém já está meio convencido, mas teria que ver a cor do ouro antes de poder reunir qualquer sentimento de convicção real ou duradouro.",
"Ah, entendi agora. Um trabalho simples, para quem não se importa com dinheiro sangrento. Entretanto, desculpe mas não é minha linha de trabalho.",
"Alguém pagaria com prazer 1.500 ouro por este serviço trivial. Requer que você faça uma visita a ",
"Mateus Santos",
"Mateus Santos",
" de #sIsla Muelle#. A casa dele fica ao lado do estaleiro, logo à direita. (Tosse, tosse) É claro que, se a saúde delicada de alguém permitisse, ele mesmo lidaria com esse patife. \nDizem que ele é um covarde, um covarde devoto, religioso nisso!",
"Sua adoração não deve se preocupar mais com esse assunto. Onde devo encontrá-lo para relatar o resultado desta tarefa?",
"Você deve estar brincando. Não respiro por esse tipo de dinheiro. Já vivi o suficiente para saber que não devo fazer o trabalho de um assassino.",
"A pessoa tem se escondido, ou melhor, fica no seu iate, que mantém perto da costa em #sisland_Conceicao#. Alguém encontrará você em terra, perto do acampamento dos contrabandistas.",
"Descobriremos que não devemos esperar muito para ouvir as notícias que queremos ouvir.",
"Capitão, eu imploro - poupe minha vida! Os 1.500 de ouro que prometi a você são tudo que tenho. Pegue, mas por favor não mate!",
"Desculpa amigo. Negócio é negócio e ",
"Mateus Santos",
" paga mais.",
"Bem... sempre fui um fanático por moedas. Dê o dinheiro a um e vá embora.",
"Não quero o seu ouro, seu idiota. Apenas pare de chorar e corra antes que eu mude de ideia!",
"Não é nada comparado à vida de alguém. Pegue, e eu irei",
"Apenas faça e seja rápido!",
"Seu idiota patético. Não acredito que você caiu nessa! Você é muito estúpido para viver!",
"Você me deixaria ir, simplesmente assim? Eu... eu... não dá para acreditar!",
"Tente muito. E faça isso em outro lugar, antes que eu mude de ideia.",
"Sim, é bom demais para ser verdade, não é? Talvez seja porque eu menti. Faça suas orações e faça-as rapidamente!",
"Então esse é realmente o tipo de #sgender# que você é? Bem, alguém pode não ser o melhor espadachim, mas você descobrirá que um homem que luta por sua vida não é um desafio fácil. En garde!",
"Vou matar você com a consciência limpa, tendo lhe dado uma chance justa. Isso é mais do que você me deu quando me armou com o Santos.",

};
