string DLG_TEXT[26] = {
"Vamos cortar alguém em pedaços, capitão?",
"Certamente. Em pedacinhos...",
"Bem, o que temos aqui? Um espadachim pela sua aparência, talvez ",
"Mateus Santos",
" me envia seus cumprimentos novamente.",
"Duvido, ele descreveu você para mim como seu inimigo pessoal.",
"Você ficaria surpreso em saber que eu também trabalhei para ",
"Mateus Santos",
", como você, aparentemente, faz agora, e não há muito tempo. Como estudante da lâmina, vi me tornar um duelista como um meio ideal de aperfeiçoar meu ofício; um suprimento inesgotável de oponentes contra os quais eu poderia me testar. Infelizmente, nunca consegui encontrar um adversário que pudesse igualar a minha habilidade, mas surpreendentemente isso teve um efeito colateral estranho, pois ",
"Mateus Santos",
" passou a me temer. E um homem como ele só conhece uma maneira de lidar com o medo: eliminar sua fonte. Desde então, uma série de bravos foi designada para me desafiar. Será você, eu me pergunto, quem se mostrará um adversário digno?",
"Estranhamente, parece que você é indiferente se cumpre o papel de caçador ou de caça.",
"Existe realmente uma diferença tão grande entre esses papéis? Entre espadachins, quero dizer. Permita-me uma advertência antes de medirmos nossas lâminas; se você provar ser um oponente digno e for capaz de me derrotar, sem dúvida assumirá meu lugar e então se tornará o caçado.",
"Saúdo sua generosidade por ter oferecido este conselho, como você me aconselharia a prosseguir daqui?",
"Vá embora.",
"Você me aconselha mal, prepare-se para morrer.",
"Isso não deveria ser surpresa para você, mas essa foi a primeira lição que meu mestre de esgrima me ensinou. Acho que nunca entendi verdadeiramente essa lição até este momento.",
"Se eu tivesse aprendido antes, poderia ter evitado o destino que agora é meu. Pouco importa onde eu vá os homems de ",
"Mateus Santos",
" sempre me encontrarão. Meu único desejo é que eu caia em um duelo honesto, e não através da traição de um assassino.",
"Então, me despedirei de você, expressando agradecimento pela lição que você me ensinou aqui. É fácil perceber porque você é considerado o melhor espadachim do arquipélago. Boa sorte.",
"Você me daria a honra de cruzar espadas comigo? Maldita seja a minha missão, mas apenas um de nós pode sair deste lugar. En Garde, senhor!",
"Você estaria disposto a considerar uma alternativa que eu sugiro? Junte-se a mim e à minha tripulação a bordo do meu navio como oficial e deixe os homens do nosso antigo empregador tentarem encontrá-lo lá. Posso assegurar-lhe que na minha profissão primária raramente fico sem adversários, dignos ou não.",
"Acho que há mérito em sua sugestão, capitão. Considere minha espada como sua. Não sei aconselhar em relação ao Santos, mas por mim tenho certeza que terei uma vida melhor com ele pensando que estou morto. Você ainda deve procurar Santos para receber seu pagamento, ou ele pode suspeitar que algo está errado.",
"Estou satisfeito em ouvir isso. Bem-vindo à minha tripulação.",
"Bem, o que temos aqui? Uma espadachim pela sua aparência, talvez ",

};