string DLG_TEXT[46] = {
"Eu vi sua briga com nosso boné. Bem, de acordo com a nossa lei, agora você é nosso novo capitão, e o navio pertence a você.",
"Onde posso encontrá-lo?",
"Ah, fica perto, na baía de Palm Beach. Vire à esquerda ao sair da aldeia e logo você a verá.",
"Perfeito! Comigo por perto, vocês saberão o que significa ser verdadeiros cães do mar, rapazes!",
"Eca. Você deve ser aquele capitão de quem Artois estava falando. Você está atrasado... Unghh... Se você tivesse chegado apenas cinco minutos antes, eu não teria essa adaga enfiada no meu peito. Ungh...",
"Droga! Alguém esfaqueou este rapaz!",
"Desaparece, otário!",
"Com prazer. Mas não até eu descobrir por que um dos meus homens está inconsciente na grama, e na sua companhia.",
"Este é o seu último erro! Rapazes, peguem #spronoun2#!",
"Experimentem, hienas imundas!",
"Receio que seu homem não esteja bem. Ele pegou uma bala no pulmão e precisa de um cirurgião.",
"Quanto isso vai me custar?",
"Bastante. Peço 2.000 ouro pelos meus serviços.",
"Negócio. A vida do meu oficial é mais importante do que o brilho opaco do ouro.",
"Com preços assim, prefiro deixá-lo morrer!",
"E mais uma coisa. Seu oficial está delirando ele disse que os ataques podem continuar. Sua recuperação levará duas semanas. Talvez você devesse colocar alguém para protegê-lo durante esse período?",
"Hm... Na verdade, esta não é a primeira tentativa de Artois. Eu mesmo vou protegê-lo.",
"Duas semanas?! De jeito nenhum, vou embora!",
"Sinto muito, capitão, mas não vou mais navegar com você. Você é muito sanguinário para mim. Até a próxima.",
"Desaparece, otário!",
"Estou farto de navegar com um verme covarde como você. Adeus, vou procurar alguém sanguinário o suficiente!",
"Como quiser!",
"O que você quer?",
"Quero que você se junte a mim em minhas jornadas.",
"Muito bem, mas tome cuidado para não repetir o que me fez te abandonar da última vez.",
"Bom.",
"Ouvi dizer que você está procurando emprego.",
"Algo parecido. E ouvi dizer que você está procurando alguém para guiar você e seu navio.",
"Você está certo. Acho que você é exatamente o #sgender# que procuro. Você gostaria de navegar comigo?",
"Quanto dinheiro você vai me pagar?",
"Eu preciso que você me siga até a ilha ",
" e eu vou te pagar ",
" moedas de ouro.",
"Concordo.",
"Eu recuso sua proposta.",
"Obrigado, sinto que meu destino está em boas mãos. Aqui está o seu dinheiro.",
"Obrigado.",
", devo estar em um lugar chamado ",
", para o ",
"Obrigado pela sua ajuda, capitão. Me sinto muito mais seguro com meu navio na sua companhia.",
"Você é muito bem-vindo. Vou levá-lo ao seu destino assim que puder.",
"Justamente quando pensei que chegaríamos em segurança, fomos atacados! Obrigado por me defender. Você merece um bônus no seu pagamento.",
"Isso é muito apreciado. Agora estou quase feliz por termos encontrado alguma oposição ao longo do caminho! Haha.",
"Estamos entrando em águas perigosas. Para evitar ser atacado, hastearei uma bandeira falsa.",
"Ah, obrigado por me contar! Eu teria ficado muito assustado se visse isso sem saber de antemão.",
"Você pode ser tentado a fugir! Ou atacar meu navio! Melhor evitar tais mal-entendidos.",

};
