string DLG_TEXT[58] = {
"Bem-vindo à minha taverna, estranho. Meu nome é ",
". O que o traz ao meu humilde estabelecimento? \nVocê precisa de um lugar para descansar?",
"Obrigado. Meu nome é ",
". Eu estou aqui a negócios.",
"Meu nome é ",
", e você pode poupar sua hospitalidade. Eu estou aqui a negócios.",
"Bem-vindo, #ssir#! O que você quer?",
"Preciso de algumas informações e acho que o estalajadeiro local geralmente é a pessoa certa para perguntar.",
"Estou procurando contratar alguns marinheiros para meu navio.",
"Aponte-me os clientes aqui que podem estar procurando emprego. Preciso aumentar minha equipe e não me importo se eles forem assassinos.",
"Você tem um quarto? Eu gostaria de ficar aqui por um tempo",
"Você tem uma cama grátis neste casebre?",
"Não tenho nenhum negócio com você agora. Adeus.",
"Isso é verdade. Eu ouço quase tudo. O que você quer saber?",
"Eu preciso de um emprego. Você não conhece nenhum garoto rico nesta ilha que tenha medo de viajar sozinho?",
"Não tenho perguntas no momento. Vamos falar sobre outra coisa.",
"Talvez eles tenham. Existem muitos rumores por aí.",
"Pressa. Sou um homem ocupado.",
"É um pouco tarde para encontrar bons marinheiros. Eles já estarão todos dormindo ou desmaiados. Volte de manhã - ou você pode passar a noite aqui na taverna.",
"Tudo bem. Você tem um quarto?",
"Não preciso de um quarto no momento. Vamos falar sobre outra coisa.",
"Eu tenho uma vaga. Quanto tempo você vai ficar?",
"Durante a noite.",
"Só até escurecer.",
"Certo. Serão 5 peças de ouro.",
"Tudo bem. Aqui você vai.",
"Infelizmente, acho que não posso pagar nada melhor do que uma noite no salão da taverna.",
"O que isso vem com uma equipe pessoal? Eu vou passar.",
"Vou pensar sobre isso.",
"Certo. Serão 5 peças de ouro.",
"Tudo bem. Aqui você vai.",
"Infelizmente, acho que não posso pagar nada melhor do que uma noite no salão da taverna.",
"Isso é demais. Eu vou ficar no salão da taverna",
"Vou pensar sobre isso.",
"Caros visitantes! Por favor, pare com essa indignação! Não me obrigue a chamar os guardas!",
"Tudo bem, tudo bem! Eu já fui!",
"Se for, eles preferem navegar com menos satélites, você sabe disso",
"Sim, esqueci. Tudo bem, voltarei mais tarde, quando tiver menos navios, ha-ha.",
"Eu não quero ajudar você. Você causou muitos problemas ao meu país.",
"Basta olhar para este patriota. Bem adeus.",
"Suas mãos estão cobertas de sangue. Você não acha seriamente que alguém viajaria com você, não é?",
"Você está certo, todo mundo tem medo de mim! Ha-ha!",
"Você chegou bem na hora. Um comerciante aqui estava procurando a companhia certa para viajar. Você deveria falar com ele. Lá está ele, acabando de entrar na taverna.",
"Eu farei isso.",
"Não, não há ninguém assim no momento, Talvez da próxima vez.",
"Hmm, então vou esperar.",
"Pode me ajudar com algo? Procuro a fragata francesa 'La Foudre'. Ela deveria ligar aqui.",
"Quase não tem havido navios aqui ultimamente. Tínhamos um comboio para aparecer, mas ela não apareceu.",
"Eu sei. Estou investigando seu desaparecimento.",
"Bem, desejo-lhe boa sorte em sua busca #ssir#.",
"Obrigado.",
"Você pode me dizer se #svillain#, ou qualquer outra pessoa do '#sship#', esteve em #sMarigot# recentemente?",
"Sim, alguns marinheiros do '#sship#' estiveram aqui algumas noites atrás. Eles estavam conversando sobre o que fariam no bordel em #sPointe a Pitre#.",
"Então eles estão indo para #sisland_Guadeloupe# a seguir?",
"Isso parece ser verdade, sim. Vou lhe contar mais uma coisa\nDa próxima vez que você estiver no porto, olhe para o mar e verá um grande navio de guerra. Esse é o '#swarship#.'",
"Quão grande é esse navio?",
"Grande o suficiente para que nenhuma das chamadas potências da Aliança tenha algo no Caribe que se compare a ela. Ela limpará esses mares dos inimigos da França sozinha, veja só!",
"É bom saber. Bem adeus. <Pensa: a marinha inglesa provavelmente pagaria bem para saber disso. Se sim, eu poderia tentar a sorte na base naval em #sisland_Antigua#.>",
};
