string DLG_TEXT[124] = {
"Desejo que você, #ssir#, baixe sua voz para um nível discreto. Um .. (tosse) meu convidado está descansando na sala adjacente. Exausto por... (tosse) eventos sociais. Então, qual é o seu desejo, #ssir#?",
"Oh, sinto muito por perturbar seu caso... (tosse) assuntos sociais, quero dizer. É melhor eu me despedir.. discretamente, claro.",
"Eu sou ",
", e desejo perguntar se você tem alguma tarefa para mim e meu navio de combate. ",
"?? Você é conhecido como inimigo da Coroa! GUARDAS!! PRENDA ESTE ESPIãO!!",
"Ah, que chato. Mais um corsário que pensa que o Caribe está cheio de navios-prêmio gordos esperando apenas por ele. #ssir#, tenho todo o esquadrão das Ilhas Leeward a meu critério, e todo comandante naval está ansioso para fazer um cruzeiro. Você realmente acredita que eu daria alguma missão lucrativa a você em vez de aos meus cron.. (tosse) seguidores leais?",
"Então você me dá as tarefas servis que seus comparsas chamativos menosprezam? Não, obrigado. Prefiro os mercadores INIMIGOS.. aqueles cheios de ouro e pilhagem.",
"Bem, é melhor que uma missão de escolta não seja tarefa alguma... especialmente se eu puder servir a Vossa Senhoria.",
"Hum, minha secretária acabou de me passar um bilhete informando que você já tem mais navios em sua frota do que consegue controlar.",
"Você está certo, mais de quatro navios tornam um esquadrão bastante pesado. Vou me livrar de um imediatamente.",
"Hum, minha secretária acabou de me passar um bilhete informando que você já tem um contrato de acompanhante com outro comerciante.",
"Obrigado por me lembrar, afinal prometi a ele toda a minha atenção e uma escolta rápida. Deveria zarpar com ele imediatamente!",
"Que feliz coincidência, pois neste exato momento aquele chato de mascate entra no meu escritório para me importunar mais uma vez... AH, ENTRE MEU QUERIDO! Que bom ver você de novo, estou sempre ansioso por nossos bate-papos aconchegantes. Sentirei muita falta da sua companhia, mas este herói arrojado aqui irá acompanhá-lo para longe de mim: Comodoro ",
" é meu melhor oficial e já realizou inúmeras tarefas ousadas e vitais para a Marinha.",
"TOSSE.. Parece que você deve ser um bom ator para fazer carreira na Marinha..",
"Com prazer, #ssir#. #sSt John's# não é um porto comum, mas sim uma base naval, na verdade uma das mais importantes do Caribe, devido à sua posição estratégica perto da passagem principal entre as Ilhas de Barlavento e Sotavento, e as fortificações são inexpugnáveis! \nTodo o porto é uma área militar, então você encontrará poucos civis aqui. Além daqueles ladrões ou sabotadores! Portanto, fique atento se vir alguma figura suspeita. Falando em ladrões, há um pequeno assentamento civil em frente ao portão da estação naval: uma favela com tabernas baratas onde marinheiros são saqueados e agredidos, e comerciantes trapaceiros que vendem à você o que os assaltantes tiraram de você antes...",
"Parece que vou aproveitar a minha estadia aqui. Obrigado pelas dicas, adeus.",
"Se me permite incomodar Vossa Senhoria com uma humilde pergunta: onde posso conseguir provisões para meu navio?",
"Bem, o escritório do estaleiro naval fica no final do cais. O grande edifício perto do cais é a revista do Agente-Victualler. \nMas como #São João# não é um porto comum, mas sim uma base naval, as suas instalações são normalmente reservadas aos navios da nossa marinha. Nossos corsários serão abastecidos se pagarem por isso, mas todos os outros navios não receberão provisões ou reparos aqui no porto. \nComo último recurso, você pode tentar os comerciantes civis nos arredores do porto, e talvez também possa contratar alguns homens lá. Mas cuidado, há muita escória e assassinos por aí.",
"Me faz sentir em casa... Obrigado pelas dicas, adeus.",
"Interessante, e você pode me contar um pouco sobre este porto em geral?",
"Não há realmente nada que eu possa fazer por você?",
"Bom, há um favor que você poderia me fazer - e acredite, quem me faz um favor está sendo favorecido neste porto. Sempre há capitães mercantes irritantes que exigem navios para escoltá-los. Ah, como esses comerciantes comuns me aborrecem, nada além de mascates, eles simplesmente não têm estilo. Muito tímidos para navegar por conta própria, muito mesquinhos para tripular e armar seus navios para autodefesa. Um desses comerciantes se tornou uma verdadeira praga, sempre ligando de manhã quando um cavalheiro educado deveria estar deitado nos braços de sua névoa.. (tosse) Morfeu, sempre me importunando por falta de zelo, ameaçando destruir minha carreira por por meio de sua influência na corte.. Eu ficaria muito grato se você pudesse me livrar desse incômodo, escoltando-o - o mais longe possível de mim.",
"Receio que você não possa me prestar nenhum serviço possível. Se você realmente deseja prestar serviço, junte-se à marinha #snation_desc# ou pelo menos obtenha uma Carta de Marca #snation_desc#.",
"Bem, não gosto de todas as regras e regulamentos da vida naval, mas vou providenciar a obtenção daquela Carta de Marca.",
"Eu te desejo, ",
", para abaixar sua voz para um nível discreto. Um .. (tosse) meu convidado está descansando na sala adjacente. Exausto por... (tosse) eventos sociais. Então, qual é o seu desejo, #ssir#?",
"Oh, sinto muito por perturbar seu caso... (tosse) assuntos sociais, quero dizer, senhor. É melhor eu me despedir.. discretamente, claro.",
"O seu navio não está designado para nenhuma tarefa? Muito bem, tenho uma tarefa para você. Um comerciante está me importunando, exigindo que eu forneça uma escolta para seu navio. Exigente, de fato! E não tenho outros navios disponíveis para fornecer essa escolta.\nMuito bem. Como você está disponível, suas novas ordens são para escoltar este comerciante e seu navio para onde ele desejar ir.",
"Uma missão de escolta? Você não consegue encontrar uma tarefa mais interessante - er, que valha a pena - para meu navio, senhor?",
"O que você pensa que é, um freebooter? Eu te dei uma ordem. Você vai obedecer!",
"Desculpe senhor. É claro que obedecerei às suas ordens.",
"Receio que você não possa me prestar nenhum serviço possível. Se você realmente deseja servir, junte-se à marinha #snation_desc# ou pelo menos obtenha uma Carta de Marca #snation_desc#.",
"DLG_TEXT[33]",
"DLG_TEXT[34]",
"DLG_TEXT[35]",
"DLG_TEXT[36]",
"DLG_TEXT[37]",
"DLG_TEXT[38]",
"DLG_TEXT[39]",
"DLG_TEXT[40]",
"DLG_TEXT[41]",
"DLG_TEXT[42]",
"DLG_TEXT[43]",
"DLG_TEXT[44]",
"DLG_TEXT[45]",
"DLG_TEXT[46]",
"DLG_TEXT[47]",
"DLG_TEXT[48]",
"DLG_TEXT[49]",
"DLG_TEXT[50]",
"DLG_TEXT[51]",
"DLG_TEXT[52]",
"DLG_TEXT[53]",
"DLG_TEXT[54]",
"DLG_TEXT[55]",
"DLG_TEXT[56]",
"DLG_TEXT[57]",
"DLG_TEXT[58]",
"DLG_TEXT[59]",
"DLG_TEXT[60]",
"DLG_TEXT[61]",
"DLG_TEXT[62]",
"DLG_TEXT[63]",
"DLG_TEXT[64]",
"DLG_TEXT[65]",
"DLG_TEXT[66]",
"DLG_TEXT[67]",
"DLG_TEXT[68]",
"DLG_TEXT[69]",
"DLG_TEXT[70]",
"DLG_TEXT[71]",
"DLG_TEXT[72]",
"DLG_TEXT[73]",
"DLG_TEXT[74]",
"DLG_TEXT[75]",
"DLG_TEXT[76]",
"DLG_TEXT[77]",
"DLG_TEXT[78]",
"DLG_TEXT[79]",
"DLG_TEXT[80]",
"DLG_TEXT[81]",
"DLG_TEXT[82]",
"DLG_TEXT[83]",
"DLG_TEXT[84]",
"DLG_TEXT[85]",
"DLG_TEXT[86]",
"DLG_TEXT[87]",
"DLG_TEXT[88]",
"DLG_TEXT[89]",
"DLG_TEXT[90]",
"DLG_TEXT[91]",
"DLG_TEXT[92]",
"DLG_TEXT[93]",
"DLG_TEXT[94]",
"DLG_TEXT[95]",
"DLG_TEXT[96]",
"DLG_TEXT[97]",
"DLG_TEXT[98]",
"DLG_TEXT[99]",
"DLG_TEXT[100]",
"Posso dizer pelo seu rosto que você tem uma pergunta a me fazer.",
"Como você adivinhou? Estou procurando uma fragata enviada aqui pelo governador #sisland_Cayman#.",
"O 'Relâmpago' atracou aqui recentemente. Por que você pergunta?",
"Procuro a filha do governador Shaw. Ela saiu de #sisland_Antigua# há dois meses e...",
"Não diga mais. O capitão da fragata já explicou tudo.",
"Acho que o governador Shaw se preocupa demais.",
"Não seja tão precipitado em dizer isso. Parece que está acontecendo mais do que apenas a filha desaparecida do governador. Na costa de #sisland_Hispaniola# o capitão do Relâmpago encontrou os destroços do comboio. Eles foram apanhados por uma violenta tempestade, durante a qual apareceu um navio pirata e afundou todo o comboio.",
"Os detritos por si só não são suficientes para justificar uma suposição tão absurda. Um navio pirata afundando um comboio inteiro? Isso parece altamente improvável.",
"Esta história veio de três tripulantes sobreviventes que estavam com medo de ter que falar sobre este navio pirata quando o capitão da fragata perguntou sobre isso.",
"Isso parece um tanto preocupante. Então o que fez o capitão da fragata?",
"Ele decidiu perseguir este navio pirata imediatamente. Eu argumentei contra isso. Achei que ele deveria ficar aqui alguns dias e preparar uma frota. Mas não consegui convencê-lo e ele partiu imediatamente para #sPhilipsburg#.",
"#sPhilipsburg#, hein? Também irei lá e verei o que posso descobrir. Obrigado pela ajuda.",
"Você novamente? Alguma sorte?",
"É Davy Jones! Ele fez isso! Você pode me poupar alguns navios?",
"Receio que não.",
"Caramba!",
"Almirante, acho que você subestima minhas habilidades como Capitão. Eu insisto.. Deixe-me provar que posso REALMENTE trabalhar para você.",
"Humm.. Como quiser. Você conhece o 'Belleville'?",
"Não. É um navio?",
"Sim, um pinnace francês. Recentemente, ela estava em #sisland_Antigua# atacando os navios mercantes. Uma situação que não posso tolerar, é claro. Eu estava pensando em enviar um dos meus navios para afundá-lo, mas vendo que você parece motivado a trabalhar sob meu comando, eu lhe dou esta tarefa.",
"Obrigado, almirante. Onde posso encontrá-la?",
"Ela deve estar fora de #sisland_Guadeloupe#. Na verdade, o navio pertence ao Governador daquela ilha.",
"Dentro de alguns dias, o navio será afundado. Adeus Almirante.",
};
