string DLG_TEXT[52] = {
"Não perca meu e seu tempo, #ssir#, não lidamos com civis aqui. A única exceção são os corsários leais com uma Carta de Marca.",
"Eu não poderia provar minha lealdade e compromisso com o esforço de guerra com uma... err... contribuição financeira para você... err... quero dizer, o baú de guerra da Coroa? Deixe-me ver.. Quanto posso poupar.. considerando o estado da minha banheira.. Digamos.. ",
" Ouro? Não se preocupe com um recibo, espero que você não guarde uma única moeda para si..(WINK)",
"Mas TENHO uma Carta de Marca..",
"Ei, você não me conhece mais? Eu já te paguei antes..",
"Nossa, você parece ser um homem muito ocupado e importante. Qual é exatamente o seu trabalho.. err.. dever?",
" Que pena.. Bem, parece que meu carpinteiro terá que consertar meu navio sozinho. Adeus, cabeça de bronze.",
"Sou o Comissário do Estaleiro Naval. O Conselho da Marinha me enviou para supervisionar os principais oficiais do estaleiro. Ter um estaleiro naval aqui no Caribe é de vital importância porque, sem reparos constantes, nosso esquadrão das Ilhas Leeward logo ficaria imobilizado pela podridão, pelo verme Taredo e pelos danos do furacão.\n Os navios a vela se deterioram tão rapidamente em águas tropicais que sempre ficamos sem suprimentos e mão de obra. Portanto, devo pedir-lhe que me deixe em paz agora, não podemos poupar nenhum dos nossos recursos para navios civis. A única exceção são os corsários leais com uma Carta de Marca, porque eles, por sua vez, nos fornecem provisões capturadas e prêmios.",
"Você, #ssir2#, não passa de um impostor! Sua relação com a Coroa certamente NãO é boa o suficiente para uma Carta de Marca. Mestre de Armas, prenda esse trapaceiro!",
" Você está muito bem informado sobre meus RELACIONAMENTOS. Bem, pessoas que sabem demais devem ser mortas. Talvez o seu sucessor seja menos intrometido..",
"Realmente? Bem, quem se importa, é apenas um pedaço de papel de qualquer maneira. Bem, só me lembro que a doca seca mesmo em frente a este escritório ficou vazia esta manhã e não estará ocupada durante uma semana. Coloque seu navio lá e pedirei ao Atendente Mestre que a incline e revise. Depois do horário normal de trabalho, é claro.",
"Claro. Conhecendo o serviço público aposto que seus trabalhadores ainda terão energia suficiente após o trabalho oficial..",
"Ah, entendo! Bem, acabei de lembrar que o cais ficou vago esta manhã e não será ocupado por uma semana. Coloque seu navio lá e pedirei ao Atendente Mestre que a incline e revise. Você só terá que pagar ",
" para o material.",
"Agora, se isso não é uma pechincha! Eu seria burro se recusasse tal oferta.",
"Eu nego categoricamente isso, você me ouviu, #ssir#? Porque isso teria sido um procedimento irregular. Nunca nos conhecemos antes! VOCÊ ENTENDE? (PISCAR)",
"Ah, não, comigo não! Você apenas finge que não nos conhecemos antes para poder extorquir outro suborno...",
"Ah, ah, sim, eu entendo. (piscadela) Deve ter confundido você com outro policial, não é de admirar... esses uniformes parecem todos iguais para mim. Um bom dia para você, querido senhor.",
" Idiotas indiscretos devem ser silenciados.. ALARME!! ISSO É UM SABOTADOR! #sGENDERSubj# TEM UMA BOMBA, MATA #sGENDERObj# NO LOCAL!!!",
" Esses idiotas navais dificilmente acreditarão em um corsário acusando seu superior.",
"Shhh!! Caro #ssir2#, seja mais discreto, eu imploro! A Diretoria da Marinha já suspeitou da minha... Ah, deixa pra lá, mas se você não fizer barulho eu lhe darei acesso a um cais que ficou vago esta manhã e não será ocupado por uma semana. Coloque seu navio lá e pedirei ao Atendente Mestre que a incline e revise. Depois do horário normal de trabalho, é claro.",
"Inchar! Veja, com os argumentos certos pode-se convencer até mesmo os idiotas navais..",
"#ssir#, você está tentando corromper um oficial da orgulhosa Marinha de Sua Majestade Real? Minha honra, não comigo! Mestre de Armas, prenda esse vilão vil!",
"Centenas de funcionários corruptos aqui, e devo encontrar o único justo. Bem, talvez seu substituto seja mais suscetível. Porque VOCÊ será mandado para casa em breve.. em um caixão de chumbo cheio de rum!",
"Ah, obrigado.. err.. em nome da Coroa! Agora, se isso não é uma prova de sua lealdade... Esses assuntos honestos merecem, é claro, o apoio de todos os oficiais da Marinha! Bem, só me lembro que o cais ficou vago esta manhã e não será ocupado por uma semana. Coloque seu navio lá e pedirei ao Atendente Mestre que a incline e revise. Depois do horário normal de trabalho, é claro.",
"Ah, capitão, você é do homem das Índias Orientais que vi no porto. Estou certo, confio?",
"Sim senhor, correto como sempre, aqui estão meus documentos. Estou precisando de alguns reparos.",
"Sim Sim. Assinado pelo próprio Lord Beckett! Tudo está em ordem. Leve seu navio para a doca seca no porto. Começaremos a trabalhar imediatamente. Vou cobrar os custos na conta do Almirantado.",
"Muito obrigado senhor, muito obrigado. Vou transmitir uma boa palavra sobre você a sua senhoria.",
"Bom dia, ",
". Qual é o seu negócio aqui?",
"Meu navio sofreu alguns danos. Desejo que seja consertado.",
"Certamente, #ssir#. Se você transferir seu navio para nosso cais, pedirei ao Atendente Mestre que o incline e revise. Você só terá que pagar ",
"Obrigado. Colocarei meu navio nas mãos capazes de seu Atendente Mestre imediatamente.",
"Estou apenas dando uma olhada neste porto. Bom dia.",
"Sou o Comissário do Estaleiro Naval. O Conselho da Marinha me enviou para supervisionar os principais oficiais do estaleiro. Ter um estaleiro naval aqui no Caribe é de vital importância, pois sem reparos constantes nosso esquadrão das Ilhas Leeward logo ficaria imobilizado pela podridão, pelo verme Taredo e pelos danos do furacão.\nIsso, é claro, inclui seu navio. Se ela foi danificada pela ação inimiga ou por uma tempestade, podemos consertá-la e deixá-la totalmente pronta para a batalha.",
"DLG_TEXT[36]",
"DLG_TEXT[37]",
"DLG_TEXT[38]",
"DLG_TEXT[39]",
"DLG_TEXT[40]",
"DLG_TEXT[41]",
"DLG_TEXT[42]",
"DLG_TEXT[43]",
"DLG_TEXT[44]",
"DLG_TEXT[45]",
"DLG_TEXT[46]",
"DLG_TEXT[47]",
"DLG_TEXT[48]",
"DLG_TEXT[49]",
"DLG_TEXT[50]",
"DLG_TEXT[51]",

};
