string DLG_TEXT[101] = {
"Não perca meu e seu tempo, #ssir#, não lidamos com civis aqui. A única exceção são os corsários leais com uma Carta de Marca.",
"Eu não poderia provar minha lealdade e compromisso com o esforço de guerra com uma... err... contribuição financeira para você... err... quero dizer, o baú de guerra da Coroa? Digamos.. ",
" Ouro? Não se preocupe com um recibo, espero que você não guarde uma única moeda para si..(WINK)",
"Mas TENHO uma Carta de Marca..",
"Ei, você não me conhece mais? Eu já te paguei antes..",
"Nossa, você parece ser um homem muito ocupado e importante. Qual é exatamente o seu trabalho.. err.. dever?",
" Que pena.. Bom, parece que terei que visitar aqueles assassinos da periferia. Adeus, cabeça de bronze.",
"Sou o Agente-Vitualista da Estação Naval das Ilhas Leeward. O Conselho de Abastecimento da Marinha me encarregou de manter o esquadrão das Ilhas Leeward totalmente abastecido em todos os momentos, então não posso dispensar uma única bala de canhão para civis como você. A única exceção são os corsários leais com uma Carta de Marca, porque eles, por sua vez, nos fornecem provisões capturadas. Aqueles podem conseguir alimentos se me pagarem.. err.. a Coroa para eles.",
"Você, #ssir#, não passa de um impostor! Sua relação com a Coroa certamente NãO é boa o suficiente para uma Carta de Marca. Mestre de Armas, prenda esse trapaceiro!",
" Você está muito bem informado sobre meus RELACIONAMENTOS. Bem, pessoas que sabem demais devem ser mortas. Talvez o seu sucessor seja menos intrometido..",
"Realmente? Bem, quem se importa, é apenas um pedaço de papel de qualquer maneira. Fique à vontade para comprar o que nosso armazém tem em estoque. E se você puder dispensar algum suprimento, a frota os aceitará com prazer. O Victualling Board lhe enviará o preço normal de mercado.",
"Em dinheiro, espero, e não em títulos do governo..",
"Ah, entendo! Bem, então você pode obter lojas de nosso estoque a taxas governamentais baixas. E se você puder dispensar algum suprimento, a frota os aceitará com prazer. O Victualling Board lhe enviará o preço normal de mercado.",
"Eu nego categoricamente isso, você me ouviu, #ssir#? Porque isso teria sido um procedimento irregular. Nunca nos conhecemos antes! VOCÊ ENTENDE? (PISCAR)",
"Ah, não, comigo não! Você apenas finge que não nos conhecemos antes para poder extorquir outro suborno...",
"Ah, ah, sim, eu entendo. (piscadela) Deve ter confundido você com outro policial, não é de admirar... esses uniformes parecem todos iguais para mim. Um bom dia para você, querido senhor.",
" Idiotas indiscretos devem ser silenciados.. ALARME!! ISSO É UM SABOTADOR! #sGENDERSubj# TEM UMA BOMBA, MATA #sGENDERObj# NO LOCAL!!!",
" Esses idiotas navais dificilmente acreditarão em um corsário acusando seu superior.",
"Shhh!! Caro #ssir#, seja mais discreto, eu imploro! O Conselho de Abastecimento já suspeitou da minha... Ah, não importa, mas se você não fizer barulho, eu lhe concederei acesso às nossas lojas a preços baixos do governo. E se você puder dispensar algum suprimento, a frota os aceitará com prazer. O Victualling Board lhe enviará o preço normal de mercado.",
"Inchar! Veja, com os argumentos certos pode-se convencer até mesmo os idiotas navais..",
"#ssir#, você está tentando corromper um oficial da orgulhosa Marinha de Sua Majestade Real? Minha honra, não comigo! Mestre de Armas, prenda esse vilão vil!",
" Centenas de funcionários corruptos aqui, e devo encontrar o único justo. Bem, talvez seu substituto seja mais suscetível. Porque VOCÊ será mandado para casa em breve.. em um caixão de chumbo cheio de rum!",
"Ah, obrigado.. err.. em nome da Coroa! Agora, se isso não é uma prova de sua lealdade... Esses assuntos honestos merecem, é claro, o apoio de todos os oficiais da Marinha! Você pode obter lojas de nosso estoque a taxas governamentais baixas. E se você puder dispensar algum suprimento, a frota os aceitará com prazer. O Victualling Board lhe enviará o preço normal de mercado.",
"Minhas desculpas capitão ",
", Eu não te reconheci sob esta luz.",
"Não é um problema. Podemos começar a trabalhar?",
"Claro, #ssir#, claro. Disseram-nos para esperar por você.",
"De fato? E como isso foi conseguido, posso perguntar?",
"Uma fragata rápida chegou aqui há cerca de um dia com uma carta sobre você de Sir Cutler Beckett. A propósito, aqui está um pacote de documentos que você deve devolver a ele",
"Ele certamente tem as coisas bem organizadas, devo admitir. Ele parece estar sempre um passo à frente de mim!",
"Oh sim! Não é um homem com quem se possa brincar. Mas para os negócios, seu navio será carregado imediatamente, temos a lista do que é necessário. O pagamento destas mercadorias já foi efetuado. Você precisa de mais alguma coisa?",
"Eu sou Capitão ",
", da East India Trading Company. Aqui estão meus papéis.",
"Sim, eu poderia fazer com algumas lojas.",
"Não, acho que terminei.",
"Ah! Claro capitão, que bom vê-lo novamente. Você quer que carreguemos você com carga ou você só precisa de lojas?",
"Sim, carregue-me com carga. O mais rápido que puder, estou ansioso para ir para o mar.",
"Mal dito e feito, capitão. Os alegres barcos estão partindo agora. Essa viagem será toda ou você precisa de mais alguma coisa?",
"Gostaria de ver o que tenho em estoque?",
"Claro. Vamos dar uma olhada.",
"Mais tarde. Agora preciso conversar.",
"Em alguma outra hora.",
"Vamos fazer um acordo ou você só quer comprar alguns suprimentos?",
"Eu quero vender alguns produtos.",
"Eu gostaria de comprar alguns equipamentos.",
"Nada, obrigado. Tchau!",
"Sobre o que você quer falar?",
"Estou ouvindo.",
"Pediram-me para entregar uma carga para você.",
"Você precisa de um capitão, senhor? Tenho um navio excelente e posso entregar qualquer carga, onde você quiser.",
"Não tenho tempo para conversar agora",
"Não, não preciso dos seus serviços. Não enquanto você estiver afundando navios #snation_desc#.",
"Nesse caso, adeus.",
"Sinto muito, mas não tenho nada para você no momento.",
"Voltarei mais tarde então.",
"Sinto muito, mas seu navio não é grande o suficiente para que você possa fazer o trabalho que tenho em mente.",
"Voltarei mais tarde então.",
"Oh! Eu só ia pedir que você me fizesse um favor. O problema é que preciso que uma carga seja entregue em ",
", e o mais rápido possível. Se você conseguir fazer isso dentro de um mês, receberá ",
" ouro quando você chegar. Isso parece justo?",
"Eu definitivamente gosto disso.",
"Eu não posso aceitar isso.",
"Já te disse hoje que não tenho nada para você.",
"Oh, desculpe.",
"Você se lembrou da sua tarefa um pouco tarde demais, não acha? Vou levar a mercadoria de qualquer maneira, mas não espere ser pago. Preste mais atenção na próxima vez! Adeus.",
"Até a próxima.",
"Oh! Estou esperando por isso há muito tempo. Aqui está sua recompensa, meu bem ",
"Sempre bem-vindo.",
"Bem-vindo, ",
". O que posso fazer para você?",
"Estou aqui para fazer uma compra para meu navio.",
"Sou o Agente-Vitualista da Estação Naval das Ilhas Leeward. O Conselho de Abastecimento da Marinha me encarregou de manter o esquadrão das Ilhas Leeward totalmente abastecido em todos os momentos. Como você faz parte desse esquadrão, você está autorizado a abastecer seu navio aqui.",
"Ah sim. Disseram-me para esperar uma entrega de #squantity# cwt de #scargo#. Você tem?",
"Hum... algumas delas parecem ter sido extraviadas. Não se preocupe, vou repor o que foi perdido e trazer para você!",
"DLG_TEXT[74]",
"DLG_TEXT[75]",
"DLG_TEXT[76]",
"DLG_TEXT[77]",
"DLG_TEXT[78]",
"DLG_TEXT[79]",
"DLG_TEXT[80]",
"DLG_TEXT[81]",
"DLG_TEXT[82]",
"DLG_TEXT[83]",
"DLG_TEXT[84]",
"DLG_TEXT[85]",
"DLG_TEXT[86]",
"DLG_TEXT[87]",
"DLG_TEXT[88]",
"DLG_TEXT[89]",
"DLG_TEXT[90]",
"DLG_TEXT[91]",
"DLG_TEXT[92]",
"DLG_TEXT[93]",
"DLG_TEXT[94]",
"DLG_TEXT[95]",
"DLG_TEXT[96]",
"DLG_TEXT[97]",
"DLG_TEXT[98]",
"DLG_TEXT[99]",
"DLG_TEXT[100]",

};
