string DLG_TEXT[290] = {
"Ah, uma rosto nova na minha taberna! Bem-vindo querido ",
"!",
"Prazer em te conhecer. Meu nome é ",
".",
"Guarde sua cortesia para outra pessoa. EU, ",
", não precisa disso.",
"Você é um verdadeiro #snoble#. Coisa rara por aqui. Meu nome é ",
". O que te traz aqui?",
"Se você não gosta tanto do meu sorriso, talvez eu o leve para outro lugar. ",
"Estritamente negócios.",
"Bem, não estamos impressionados com nós mesmos? Só lamento não ter tempo para te reduzir ao tamanho.",
"Negócios? Você se encontra na melhor taberna do nosso arquipélago! Deixe esse olhar severo para a porta e tome uma bebida!",
"Eh. Seu negócio é seu negócio. A menos que eu possa pegar uma bebida para você?",
"Muito bem. Sirva-me um pouco do seu melhor vinho.",
"Quero vinho, mas não a água de lavar louça que você vende aos seus clientes regulares.",
"Infelizmente, não posso perder tempo. Adeus.",
"Beber aquele veneno que você passa para seus convidados? Eu valorizo demais minha saúde. Bom dia!",
"Por apenas um ouro você pode conseguir o melhor vinho que já provou na vida!",
"2 de ouro e verei o que posso fazer por você.",
"Tudo bem, estou com vontade de jogar. Mas quero mais do que vinho por este ouro. Também vou precisar de algumas informações.",
"Aqui está o seu dinheiro, mas fique com o seu vinho. Prefiro que você apenas responda algumas perguntas para mim.",
"Parece que não posso comprar nada da sua adega. Que tal um pouco de rum?",
"Estou surpreso que você tenha a coragem de pedir dinheiro por essa lavagem. Apenas me traga um pouco de rum!",
"Rum também custa 1 ouro. Você não tem dinheiro, isso não é problema meu.",
"O quê, você ainda está aqui? Você também não pode pagar os 2 ouros por rum...",
"Tudo bem, traga seu vinho. Então você pode me responder algumas perguntas...",
"Droga, é um assalto à luz do dia! Traga o vinho e responda às minhas perguntas.",
"Muito ruim.",
"Tenho certeza de que viverei mais um dia sem o seu vinho.",
"Então, como posso ajudá-lo?",
"Gostaria de falar de negócios com você. Negócio muito importante...",
"Você tem um quarto livre? Eu gostaria de ficar aqui por algum tempo",
"Você ainda tem algum quarto nesta taverna pulga?",
"Preciso de algumas informações sobre esta cidade.",
"Sinto muito, mas o quarto já está ocupado pelo capitão ",
"Amiel Berangere",
".",
"Droga! Tenho que dormir em algum lugar!",
"Eu tenho um quarto. Quanto tempo você vai precisar?",
"Só até de manhã.",
"Só preciso de um lugar para descansar os olhos até esta noite.",
"Vai custar 5 moedas.",
"Aqui está o seu dinheiro.",
"Bem, parece que o luxo de uma cama confortável está fora do meu alcance neste momento. Vou passar a noite na taverna",
"Para que?! Todo este edifício? Esqueça. Vou passar a noite na taverna",
"Tudo bem, vou pensar sobre isso.",
"Vai custar 5 moedas de ouro.",
"Aqui está o seu dinheiro.",
"Bem, parece que o luxo de uma cama confortável está fora do meu alcance neste momento. Vou passar a noite na taverna",
"O quê, é um quarto king-size? Não, obrigado. Vou sentar-me no salão da taberna",
"Tudo bem, vou pensar sobre isso.",
"Gostaria de lhe fazer algumas perguntas.",
"Não conheço muito bem a cidade. Pode me ajudar?",
"Estou procurando contratar uma equipe.",
"Preciso encontrar a loja local.",
"Meu navio precisa de reparos...",
"Sou todo ouvidos, ",
".",
"Ouvi dizer que aquele marujo ali lhe deve algum dinheiro.",
"O que você pode me contar ",
"Teodoro Fernandez",
"Teodoro Fernandez",
"?",
"Há rumores de que alguns produtos raros chegaram à cidade recentemente...",
"Gostaria de saber sua opinião sobre um certo cavalheiro chamado ",
"Baldewyn Coffier",
"Baldewyn Coffier",
".",
"Tentei falar com aquele senhor que você apontou, mas ele recusou.",
"Estou procurando uma pessoa chamada ",
"Amiel Berangere",
"Amiel Berangere",
". Ele é o capitão do brigue 'Le Requin'",
"Disseram-me que você iniciou uma guerra com os ingleses.",
"Procuro um homem chamado ",
"Raoul Rheims",
"Raoul Rheims",
". Você o viu?",
"Qual é a fofoca aqui?",
"Preciso de algum trabalho. Você não conhece nenhum garoto rico nesta ilha que tenha medo de viajar sozinho?",
"Obrigado. Preciso ir agora.",
"Se existir tal pessoa, ela pode preferir evitar atrair a atenção de tantas consortes - como eu espero que você saiba.",
"Sim, esqueci. Tudo bem, voltarei mais tarde, quando tiver menos navios, ha-ha.",
"Não quero ajudá-lo, com todo o mal que você causou ao meu país.",
"Basta olhar para este patriota. Bem adeus.",
"Suas mãos estão cobertas de sangue. Você acha mesmo que alguém vai viajar na sua companhia?",
"Você está certo, todo mundo tem medo de mim! Ha-ha!",
"Você chegou bem na hora. Um comerciante aqui estava procurando navegar na companhia dos companheiros certos. É melhor você falar com ele. Aqui está ele, entrando na taverna.",
"Eu farei isso.",
"Não, não há ninguém no momento. Talvez na próxima vez.",
"Hum. Então vou esperar.",
"Todo mundo sabe disso ",
".",
"Você tem razão. Estão falando sobre isso por todo o arquipélago, mas não é isso que quero dizer.",
"Então, o que você quer dizer?",
"Estou procurando trabalho. Tenho meu próprio navio e vários homens fortes que passaram pelo fogo e pela água comigo.",
"Receio que você não terá muita sorte ",
". Nosso governador não quer que vocês participem deste conflito.",
"Meu tipo? Ele é sempre tão exigente? ",
"Não é exigente, não. Ele só está preocupado com traição. A única exceção é ",
"Amiel Berangere",
"  ",
"Amiel Berangere",
", e isso porque ele é um francês de sangue puro. Na verdade, sua missão é muito importante: ele é entregar munições e armas à nossa frota que capturou #sOxbay#!",
"Bem, parece que terei dificuldade em encontrar trabalho, a menos que... talvez isto ",
"Amiel Berangere",
" colocaria uma boa palavra para mim. Você sabe onde posso encontrá-lo?",
"É a primeira vez que ouço falar dele.",
"É uma pena. Bem, vamos falar sobre outra coisa.",
"Isso é uma tragédia ",
". A questão é que ele era um comerciante de sucesso nesta ilha, até cair na armadilha preparada por ",
"Arnaud Matton",
", o atual proprietário da loja. Ele foi levado à ruína.",
"Ele é um homem honesto, não é? A situação dele é realmente tão desesperadora que ele não consegue pagar a dívida?",
"Infelizmente ",
", sua situação financeira é verdadeiramente sombria. Ele tem esposa e dois filhos para alimentar. ",
"Baldewyn Coffier",
" trabalha o máximo que pode, mas ninguém se dispôs a ajudá-lo desde que seu negócio deu certo.",
"Obrigado pela informação.",
"Então é isso que você quer dizer! Você foi contratado por ",
"Arnaud Matton",
", para arruinar completamente este homem honesto?!",
"Fácil agora. Eu só quero entender o que está acontecendo aqui.",
"Você tem razão. E acredite em mim quando digo que isso me trará um grande prazer.",
"Entender? Eu sei o que o seu 'entendimento' realmente significa... Tudo bem, tudo bem. Ele realmente não tem dinheiro e precisa sustentar sua esposa e dois filhos...",
"Obrigado pela ajuda.",
"Você sabe, ",
", já vi muitos canalhas na minha vida, mas você... Essa conversa acabou, #ssir#. Bom dia!",
"Vou lembrar que você disse isso.",
"Para chegar à loja, vire à direita ao sair da taberna e passe pelos portões. Você verá isso imediatamente...",
"Obrigado. Tenho mais algumas perguntas para você...",
"Obrigado, isso é tudo que eu queria saber.",
"Então você vai precisar do estaleiro. Fica em frente à minha taverna, logo à sua esquerda quando você sai.",
"Obrigado. Tenho mais algumas perguntas para você...",
"Obrigado, isso é tudo que eu queria saber.",
"Nunca ouvi esse nome antes.",
"Muito ruim. Desculpe incomodá-lo.",
"Aqui está uma peça de ouro brilhante. Ouvi dizer que essas coisas fazem maravilhas na memória...",
"Tu podes estar certo. Como você disse que ele era?",
"Um espanhol com uma cicatriz no rosto.",
"Isso dificilmente o restringe. Mas agora que você mencionou, havia um sujeito estranho aqui há cerca de quatro dias, pode ser quem você está procurando. Mas ele se autodenominava Jerônimo Elcano.",
"Interessante! O que ele estava fazendo aqui?",
"Ele alugou um quarto, passou uma noite e foi embora.",
"Ele saiu? Ele falou com alguém?",
"Na verdade, ele fez. Eu o vi conversando com um sujeito local chamado ",
"Lucien Bescanceny",
"Lucien Bescanceny",
". Eles conversaram em sussurros por um tempo e depois se separaram.",
"Onde é que encontro esse ",
"Lucien Bescanceny",
"Lucien Bescanceny",
"?",
"Eu não aconselharia você a lidar com ele ",
", ele é um homem perigoso.",
"Relaxar. Eu só quero saber onde ele mora.",
"Tudo bem, mas é o seu funeral, talvez literalmente, se você não tomar cuidado. Se você ainda quiser vê-lo, saia da taverna e vá para a direita até chegar aos portões da outra parte da cidade, passe pelo outro portão e procure por ele em uma das cabanas de lá.",
"Obrigado, acredito que irei visitá-lo.",
"Eu tenho mais algumas perguntas.",
"Olá, ",
", muito tempo sem ver. Como vai?",
"Bem bem. Importa-se se eu lhe fizer algumas perguntas?",
"Nenhum de seus negócios. Eu farei as perguntas.",
"Estou pensando em adicionar alguns marinheiros à minha tripulação.",
"Apenas me indique a ralé mais desagradável em busca de trabalho. Preciso de alguns assassinos para o meu navio.",
"Você tem um quarto para mim? Eu gostaria de ficar aqui.",
"Você tem um quarto livre neste poço?",
"Você conhece minha regra - você não pede, não faz perguntas.",
"Não, não gosto disso, não vou pagar.",
"Aqui está o seu dinheiro.",
"É contrabando? É o assunto da cidade, mas o chefe do porto não faz nada a respeito.",
"Acho que você sabe do que estou falando...",
"Para que serve essa conversa, ",
"?",
"Preciso colocar minhas mãos em algumas dessas coisas, mas não sei com quem contatar. Eu pensei, talvez você pudesse me ajudar",
"Fale baixo, pelo amor de Deus! Estás a ver aquele português sentado à mesa aí? Suponho que ele possa ajudá-lo.",
"Obrigado, você foi de grande ajuda.",
"O que você está falando?! Eu não tenho nada a ver com isso!",
"Muito ruim. Vou ter que procurar em outro lugar.",
"Desculpe, ",
", mas não posso mais ajudá-lo. Experimente os trabalhadores do porto.",
"Obrigado, vou tentar.",
"Sim, ele realmente deve algum dinheiro. 500 ouro.",
"Eu vejo. Eu estava pensando. Adeus.",
"Quero pagar a dívida dele.",
"Não vejo por que ",
", ele não é um homem muito bom.",
"Talvez você esteja certo. Vou seguir seu conselho.",
"Gosto dele. Bruto, mas estou acostumado com isso. Pagarei a dívida dele.",
"De jeito nenhum! É sempre um prazer ajudá-lo.",
"Até a próxima!",
"Como quiser, mas não diga que não avisei. Ele me deve 500 ouro.",
"Sim, bem, você pode estar certo. Deixa para lá.",
"Aqui está o seu dinheiro.",
"Muito bem. Aqui está o reconhecimento de dívida dele. É seu para fazer o que quiser.",
"Adeus!",
"Alguém chamado ",
"Amiel Berangere",
"Amiel Berangere",
" alugou um quarto comigo. Para falar a verdade, não sei se ele é capitão, mas tem modos de oficial.",
"Perfeito! Onde posso encontrá-lo?",
"Ele subiu. Acho que ele não saiu do quarto desde então.",
"Obrigado.",
"Céu misericordioso! Você o matou!",
"Não tive escolha. Ele não quis ouvir a razão.",
"Sim... sinto muito por isso.",
"O que aconteceu aqui? Por que você o matou?!",
"Ele me contradisse. Eu não ligo para isso. Mais alguma pergunta?",
"O que fazemos agora? ",
", O que devo fazer com ele ?",
"Eu não importo.",
"Pense um momento. Sempre há uma solução.",
"Não tenho nada a ver com isso ",
", foi você quem o matou! Posso apenas chamar os guardas!",
"Veja este papel que encontrei no corpo dele. Você sabe o que é isso?",
"Isso seria um erro. Um erro fatal.",
"Acalmar. Vamos inventar alguma coisa.",
"É melhor você arranjar algum ouro. Vou precisar dele para pagar os carregadores para se livrarem desse homem e ficarem calados sobre isso!",
"Chantagista!",
"Você pode lidar com isso como quiser, mas não vou lhe dar nenhum dinheiro.",
"Você pirata! Como você ousa me ameaçar?!",
"Você viveu muito tempo neste mundo",
"Tudo bem, tudo bem. Quanto ouro será necessário?",
"Como estou resolvendo seu problema para você, não precisarei de menos que ",
" ouro.",
"Acho que será mais fácil se eu cortar sua garganta.",
"Aqui está o seu ouro! Mas não vou esquecer isso!",
"Espere! Eu cuidarei disso, apenas mantenha essa lâmina embainhada!",
"Veja sua língua! Lembre-se com quem você está falando!",
"Desculpe, ",
". Só que não lido com esse tipo de coisa todos os dias.",
"Então, estamos quadrados?",
"Sim Sim, ",
", claro. Você pode sair e ficar tranquilo que eu vou cuidar dessa bagunça.",
"Então te vejo em breve, ",
".",
"Maravilhoso. Mas da próxima vez que você decidir matar um dos meus convidados, me avise com antecedência.",
"Não se preocupe. Você saberá. Especialmente se você for o próximo.",
"Haha, ",
" isso é uma piada, certo? Certo?",
"Verei você, estalajadeiro. Enquanto isso, tente decidir se pareço um curinga.",
"Hmm... mesmo que eu saiba, vou precisar de dinheiro para limpar isso.",
"Conte sobre este documento e eu pagarei o quanto você precisar.",
"Agora estamos fazendo negócios! Este documento é uma ordem ao chefe do porto para permitir que você e o navio que você está escoltando partam. Parece pobre ",
"Amiel Berangere",
" ia dar ao chefe ",
"Turpin Cabanel",
" antes de zarpar.",
"Ah, entendi. Obrigado. Até a próxima!",
"Olha, pense em como se livrar dessa bagunça. Quanto vai custar?",
"Ei! Que tal algum dinheiro? Eu te contei tudo...",
"Diga mais uma palavra sobre dinheiro e eu vou enfiá-la de volta na sua garganta!",
"Pense em como consertar isso. Quanto vai custar?",
"O que você está falando? Todos estão em casa. É meio da noite. Se eu fosse você, esperaria até de manhã. Talvez você queira alugar um quarto?",
"Você tem um quarto livre?",
"Não, vamos falar de outra coisa.",
"Desculpe, capitão. Não tenho nada para você. Capitão ",
"Amiel Berangere",
" deve partir amanhã, mas até lá não consigo tirá-lo do quarto.",
"Quem é ",
"Amiel Berangere",
"?",
"E para onde ele vai?",
"Até recentemente, ele comandava um navio mercante local. Depois comprou seu próprio navio e agora trabalha por conta própria. Provavelmente transportando contrabando, caso contrário, onde ele conseguiria o dinheiro? \nEle não está muito bem ultimamente. Ele tem que se contentar com qualquer trabalho que encontrar.",
"A propósito, que tipo de trabalho um capitão pode encontrar em #sisland_Falaise de Fleur#?",
"Não tenho certeza, mas ouvi dizer que ele foi contratado ",
" pelo governador para escoltar um barco de guerra cheio de suprimentos para #sOxbay#. Você já deve saber que estamos em guerra com seus compatriotas.",
"Entendo... Bem, onde posso passar a noite então?",
"Ah, todo tipo de trabalho: transportar cargas, entregas especiais, perseguir piratas. E ",
"Amiel Berangere",
" foi contratado para escoltar um navio de guerra.",
"Hmm.... Que tipo de navio?",
"Parecia um navio de abastecimento. Provavelmente estão entregando comida à frota francesa. É uma guerra, você sabe, então eles o contrataram para ter certeza de que não iria parar no fundo do mar. Também pode estar carregando pólvora ou bombas.",
"Entendo... Então, onde posso passar a noite?",
"Não sei. Talvez você pudesse conversar com ele. Ele não parece um mau sujeito. Talvez ele esteja disposto a dividir o quarto com você.",
"Hmm.... Espero que tenha duas camas.",
"Pare com esse ultraje imediatamente ou terei que chamar os guardas!",
"Tudo bem, tudo bem! Estou indo embora!",
"Mas enquanto você resolve problemas",
"por que você não fala com o pobre Patric, o comerciante de rua? Ele está do lado de fora da porta e em estados terríveis...",
"Você poderia me dizer se alguém de 'La Fougueuse' está na sua taberna?",
"Não, e isso seria impossível.",
"Por que?",
"Desde ontem, a tripulação está confinada no navio e não pode estar na cidade. Eu sei que o navio deve levantar âncora depois de amanhã.",
"Você também conhece o destino dela?",
"Não. Mesmo os poucos tripulantes que conheci nos primeiros dias de estadia não conheciam sua missão. Acho que só o capitão e o nosso governador sabem disso.",
"Sim, claro, o Governador deveria ter recebido comunicações da França com o navio, eles já se encontraram?",
"Pouco depois de sua chegada, o Governador teve um jantar formal com o capitão de 'La Fougueuse', eles me pediram o melhor vinho.",
"Aurelien Bergerat é o nome daquele capitão, certo?",
"Na verdade, um oficial brilhante pelo que ouvi... Aliás, por que tantas perguntas sobre aquele navio?",
"Eu queria trabalhar neste belo navio francês, ele levará muitos belos navios premiados e informações sempre ajudam a conseguir uma posição melhor... Mas parece que é tarde demais. Obrigado pela ajuda.",
};
