string DLG_TEXT[51] = {
"Alegria do dia para você, capitão. Por favor, entre na minha enfermaria.",
"Por que Olá. Você é um boticário?",
"Desculpe, não posso ficar. Tenho coisas para fazer.",
"Dou-lhe alegria pelo seu retorno, capitão. Como posso aplicar meu humilde conhecimento médico ao seu caso mais particular?",
"Eu me submeteria a quase qualquer procedimento agora, se você pudesse restaurar minhas forças, querido doutor.",
"Já que estamos no tema da medicina contemporânea, você poderia prescrever algo para aumentar o poder, a resistência e a resiliência?",
"Eu gostaria de comprar alguns frascos de remédio para levar comigo, por favor.",
"Meu caro Steven! Você foi muito gentil, mas temo que devo deixá-lo agora. Desejo a todos boa sorte em suas atividades científicas.",
"Capitão, percebo que você foi envenenado! Você deve me permitir sangrar imediatamente. Apenas fique parado aí e eu aconselho você a desviar o olhar. Conheço muitos marinheiros barulhentos que estão mais do que dispostos a derramar o sangue de outra pessoa, mas que desmaiam ao ver o seu próprio...",
"Oog, sim, por favor, se apresse...",
"Se você decidir usar um termo tão grosseiro, então sim, estou na profissão de desmembrar os pedaços ossificados de meus semelhantes. Com uma reverência posso me apresentar como ",
", seu humilde servo.",
"Heh, desmembrando. Você gostaria, esse é o meu trabalho também. Conte-me sobre sua lojinha aqui... por exemplo, por que as cores são tão perturbadoras?",
"Quanto ao esquema cromático, a ciência tem demonstrado que tons como esses acalmam o paciente, auxiliando tanto na recuperação quanto na digestão. Sou boticário de profissão e, como você pode perceber pela coleção zoológica, sou um pouco naturalista amador. Se você tiver alguma necessidade médica, estará seguro em minhas mãos mais capazes.",
"Esplêndido: preciso dos seus serviços para recuperar todas as minhas forças.",
"Uma pequena sangria ou a aplicação de sanguessugas, combinada com um poderoso enema, levantará o ânimo e a saúde de qualquer marinheiro grisalho. E cobro apenas 200 moedas. Vamos prosseguir?",
"Parece perfeitamente emocionante, mal posso esperar.",
"Não sei bem o que é isso, mas tudo parece extremamente desagradável. Se não importa para você, Steven, continuarei ferido.",
"Ah, bom, vejo que você tem os constituintes químicos que especifiquei. Acredito que não foi difícil encontrar todos eles.\nPara quem deveria ser a receita?",
"Para mim pessoalmente.",
"Para meu oficial ",
".",
"Temo que deva insistir contra tal atitude, considerando o tempo e as despesas. Talvez outra hora.",
"Sim, posso fazer uma coisa dessas. Somente você deve me trazer os ingredientes que preciso para um bordado tão saudável e que prolongue a vida, já que eles não fazem parte do meu estoque comum. Isto é o que é necessário: encontre uma garrafa de acetum saturninum, um dracma de confectio Damocritis, uma onça de láudeno e vários grãos de turpeth. Você consegue se lembrar de tudo isso? Você pode encontrá-los em barris e caixas por todo o arquipélago... apenas capitão, por favor, não recorra ao roubo.",
"Nunca na vida, meu bom doutor. Reunirei sua lista de compras rapidamente e retornarei para cumprir meu destino como um #sgender# mais forte.",
"Capitão, por favor, diga, essa é uma espécie de albatroz que eu espio em sua posse? Como adoro os queridos e estúpidos pássaros - na minha qualidade de naturalista amador, fiz do tipo deles o objeto principal do meu estudo. Devo lhe dar este pote de sanguessugas curativas em troca disso?",
"Bom, não sei se quero me desfazer de um exemplar tão magnífico... mas muito bem, vamos trocar.",
"Certamente não, doutor. Por um lado, passei a gostar bastante deste nobre pássaro... nem um pote de criaturinhas pegajosas e moles é atraente como troca por ele. Desculpe.",
"Certamente, é claro. Meus armários de remédios guardam a melhor e mais eficaz panaceia que você encontrará em todo o reino dos Caribes. Em primeiro lugar, posso sugerir um pote com essas criaturinhas maravilhosas aqui, essas sanguessugas? Eles são universalmente elogiados entre os homens da minha profissão, altamente recomendados para a remoção de maus humores. Eu pessoalmente juro por eles. 300 moedas, por favor #ssir#, é um preço modesto.",
"Muito bem. Acredito que posso acreditar em qualquer recomendação sua, meu caro cirurgião. Um frasco, por favor.",
"Ughk, o que são aquelas coisinhas pegajosas naquele pote?! Você realmente me faria TOCAR em um? Perdoe um assassino melindroso, mas não, obrigado!",
"Lá vamos nós - os maus humores deixaram você, e apenas sangue limpo e fresco permanece. Na verdade, a ciência moderna é uma maravilha!",
"Concordo plenamente - chegamos muito longe da barbárie dos tempos antigos. Obrigado.",
"Pensar nada disso; sua boa saúde é minha alegria. E agora só resta a questão da conta.",
"Hm, tinha que ser uma pegadinha. 100 tortas? Um preço justo pela minha vida, suponho. Aí está você.",
"Vários procedimentos bastante desagradáveis depois",
"você recuperou bastante sua saúde,",
"se não o seu espírito.",
"Após os tratamentos ",
" parece que ",
" pode suportar golpes mais fortes",
"e geralmente vivem um pouco mais.",
"+ ",
" HP máximo",
"Receio ter de insistir em cobrar pelo procedimento (meras ",
" moedas), e quanto a você, você deve passar a noite em 'patos secos', como dizem vocês, marinheiros, embora eu não tenha a menor ideia do porquê, já que as poças d'água, como convém ao seu nome, são mais frequentemente molhadas.\nVamos começar?",
"Por favor comece.",
"Eu mudei de idéia.",
"Adquiri um pouco de ópio, mas me pergunto o que ele faz. Você pode me esclarecer?",
"Sim, eu sei disso. Uma substância arriscada, de fato! Pode envenená-lo ou deixá-lo mais fraco do que antes, embora também haja uma chance de você adquirir novos conhecimentos e experiências dessa maneira não convencional. Mas mesmo na melhor das hipóteses, o usuário ficaria doente depois. O efeito desaparece depois de alguns dias, mas pode afetar suas habilidades de esgrima. Pisar com cuidado!",
"Isso responde muito bem à minha pergunta. Obrigado pelo conselho!",
};
