string DLG_TEXT[32] = {
", querido visitante! Eu sou ",
", proprietário do estaleiro local.",
"E eu sou ",
", capitão do navio '",
".'",
", ",
". Você precisa dos serviços do meu estaleiro, ",
"?",
"Na verdade, preciso que você conserte alguns buracos de granadas e conserte algumas velas.",
"Agora só preciso falar com você.",
"Não, só pensei em passar por aqui.",
"Bem, estou muito feliz em conhecê-lo. Se você é capitão, meu estaleiro está sempre ao seu serviço.",
"Perfeito, ",
". Vamos começar com esses reparos.",
"Obrigado. Mas primeiro vamos conversar.",
"Da próxima vez, talvez. Eu tenho que ir embora.",
"No que exatamente você está interessado ",
"?",
"Não, eu não acredito que sim.",
"Eu vejo. Você precisa de mais alguma coisa, ",
"?",
"Gostaria de colocar alguns remendos na velha banheira que me trouxe até aqui!",
"É só isso, obrigado. Até a próxima!",
"O que exatamente você precisa?",
"Preciso consertar meu navio - embora eu possa considerar apenas desmantelá-lo e comprar um novo.",
"Preciso instalar novas armas na meu navio.",
"Nada, obrigado.",
"Recuso-me a negociar com uma pessoa com a sua reputação e relações. Agora saia, ",
", antes de chamar os guardas.",
"Muito bem.",
"Tudo bem, meu cais ao lado do forte está disponível para você. Se você quiser, direi ao meu chefe das docas para rebocar seu navio até lá. Só então poderei avaliar os danos e dizer quanto tempo e dinheiro serão necessários. ",
"DOCA AO LADO DO FORTE?? Uhh... só me lembro que tenho... eeh... outro assunto urgente que preciso resolver primeiro. Adeus.",

};
