string DLG_TEXT[72] = {
"Nunca interrompa um francês quando ele estiver bebendo, seu idiota!",
"Mas eu...",
"Se alguém não cortou suas orelhas, eu mesmo farei isso!",
"Ei! Acalme-se!",
"O que é que você quer?!",
"Meu nome é ",
".",
"Vá para o diabo, seu rude... Ach! Seu nome não significa nada para mim! Agora volte para os embornais fedorentos de onde você saiu e deixe-me beber em paz.",
"Você deve ser Armand Delacroix, o pirata incrivelmente charmoso que roubou o coração de uma...certa señorita.",
"...Oh......Pardonnéz moi......Você carrega uma carta, ",
"?",
"Ah, então agora o bêbado grosseiro e detestável de repente é educado.",
"Cuidado com a língua, você...... Alors, non, você tem meu pingente! Onde você... peço desculpas ",
". A bebida, a tristeza, a preocupação, tudo sobe à minha cabeça e me torno uma fera desprezada. Receio que seja um fardo terrível que carrego. Minha linda Mademoiselle Estrella deve ter te mandado, oui?",
"Sim, Dona Estrella me deu este pingente, que é igual a este que você tem no pescoço. Ela disse que me ajudaria a identificar você, e eu a mim. Suponho que ela pensou que você me mataria, caso contrário.",
"Ah, sim, e bem, talvez eu tivesse feito isso. Eu fiz estes pingentes para nós enquanto estava sentado aqui, mantendo este banco aquecido e afogando minhas angústias. Que mensagem você carrega, #ssmarmy#? Notícias da minha bela e ardente mademoiselle? Por favor, sente-se e tome uma bebida por minha conta. (Para o taverneiro)...Dois rum para nós aqui, Madame Inês!",
"Você é pelo menos um anfitrião gentil, Capitão Delacroix. Obrigado.",
"...E a senhora e eu... Bem... Ela lhe contou.",
"Então você senta aqui e bebe?",
"Ah, ",
", um homem poderia fazer pior. Já fiz pior. Na verdade estou sentado tentando planejar um movimento ousado para resgatar meu lindo amor.... O rum liberta as ideias.",
"Estou vejo. É por isso que você está aqui há tanto tempo, bebendo até cair em um estupor lamentável?",
"#sfriend#, você tem um... jeito delicado com as palavras.... Mas sim... Geralmente eu sento e bebo, e rego esta mesa com minhas lágrimas. Não consigo imaginar uma maneira de tirá-la daquela ilha amaldiçoada!",
"A marinha espanhola está atrás de você?",
"São muitos, e só tenho um navio, que roubei daqueles imbecis franceses a quem servi. Ela é grande e poderosa, mas precisa de muitos homens para navegar. Às vezes acho que deveria vendê-la e comprar uma escuna rápida, mas ah, não posso. A Rainha do Voodoo, ela é uma coisa bela e poderosa.",
"Parece que você tem dois amores.",
"Mon Dieux, você está tão certo!",
"O que você quer fazer, Armand? Velejar ou estar com sua senhora?",
"Ambos, #ssmarmy#. Ambos. A Rainha Voodoo tem uma cabine onde eu poderia manter minha adorável senhora, e poderíamos navegar para outro arquipélago, outras ilhas. Eu não poderia fazer tal viagem em um navio menor e manter minha linda mademoiselle confortável.",
"A senhora fica enjoada?",
"Alors, sim! Ela estava tão doente naquele galeão espanhol quando eu a resgatei! A Rainha Voodoo pode ser grande, mas é estável e lida com mares agitados com facilidade. Precisamos que ela saia deste arquipélago com segurança e conforto.",
"Eu vejo. Bem, Armand, provavelmente eu deveria voltar para meu navio. Doña Estrella aguarda minha notícia de que você ainda vive.",
"Espere! ...Mon capitaine! VOCÊ tem um navio!",
"Delacroix, correndo o risco de levar uma surra forte, você está MUITO bêbado!",
"Você não vê, vai ficar perfeito! Ninguém precisa saber que você está aí ",
"! Ah, suas façanhas contra aqueles cães espanhóis serão cantadas até as vigas das tavernas de todo o mundo, ha HAAA!",
"Armand! Você está muito bêbado e louco. Encontre alguém tolo para ajudá-lo. Posso estar muitas coisas, inclusive bêbado, mas não sou bobo. Não.",
"Mon capitaine......#ssmarmy#... Eu sei que estou bêbado, mas posso ver que você é um #sgender# honesto. Não posso confiar nesses bandidos ao nosso redor. Eu te imploro... Por favor, ajude-nos.",
"Abra seus ouvidos, cara! Não!",
"Por favor. Eu vou te pagar generosamente! E eu tenho um plano infalível!",
"Armand, não. Não posso lutar contra a marinha espanhola por você.",
"Pshhht, um pouco de timing, um pouco de estratagema, os espanhóis podem ser enganados, #sfriend#! Mas só por pouco tempo. Por favor, precisamos da sua ajuda.",
"Armand...",
"Mas ",
", pense na senhora! Ela é tão linda e tão trágica! Ela vive sem amor. Como não ajudar a incomparável e requintada Mademoiselle Estrella?",
"... Err, ahhhh você me pegou aí, maldito seja! Tudo bem. Vou te ajudar.",
"Pela última vez, não. Estou saindo agora, Armand.",
"Você é um príncipe entre os homens, mon capitaine!",
"Nããão, apenas um idiota com um coração mole e uma bolsa leve. Quanto é 'bonito', Armand?",
"Cinco mil... Espere, não, DEZ mil! Haverá riscos.",
"Sem brincadeira... Bem, que plano 'infalível' surgiu na superfície da sua imaginação encharcada de rum?",
"Navegue para #sisland_Isla Muelle# até Oyster Beach. Atravesse a ilha a pé, encontre minha senhora, espere até o anoitecer e atravesse a ilha de costas para a baía. É a única maneira de tirá-la de lá.",
"Ah. Os guardas não vão se opor a ela sair da cidade à noite?",
"Daí os riscos, capitão ",
".",
"Hum. Talvez um disfarce ajudasse.",
"Vamos dar um passeio, #sfriend#. Preciso limpar minha cabeça.",
"Eu também. E eu realmente deveria voltar para meu navio.",
"...Bebam, meus queridos, yo ho! ...Heeeee, estou tonto com a ideia de que isso finalmente vai acontecer!",
"Você está tonto de bebida, Armand.",
"Ahhhh, isso é verdade, #sfriend#. Mas meu coração está mais leve; Agora posso navegar alto com as aves marinhas novamente!\nNão sei como te agradecer!",
"Pagar-me seria bom.",
"Ah, sim, mas não estou tão bêbado a ponto de ser um idiota! Pagarei quando nos encontrarmos na enseada se você tiver minha adorável dama pronta para escapar. Agora vá para #sisland_Isla Muelle#, e estarei esperando em Oyster Beach no Voodoo Queen.",
"Justo.",
"Navegação tranquila e ventos favoráveis, mon capitaine.",
"E sorte para você, Armand, por escapar da marinha espanhola. Vejo você em #sisland_Isla Muelle#.",
"Mon Dieu, é você, minha linda Estrella? E que trabalho de espada! Nenhum homem ousaria contrariar você, minha ousada e corajosa mademoiselle!",
"Armand, você terá tempo para isso mais tarde, deveria zarpar enquanto o mar ainda está livre dos espanhóis!",
"Ah, você está certo ",
", #sfriend#. Você tem nossa mais profunda gratidão. Devemos a você mais do que apenas esta recompensa. Procure uma carta na Pousada #sQuebradas Costillas# em #sisland_Quebradas Costillas#! Venha, Estrella minha querida, vamos zarpar!",
"Ventos bons e mares calmos! E uma navegação tranquila!",
"Você é uma rainha entre os mendigos, mon capitaine!",

};
