string DLG_TEXT[327] = {
"Vá embora antes que eu chame os guardas!",
"Como quiser.",
"Não há necessidade de gritar. Estou indo embora!",
"O que posso fazer para você, ",
"?",
"Como posso ajudá-lo, ",
"?",
"O que você quer comigo, capitão?",
"Eu gostaria de ver seus produtos.",
"Eu devo ir embora. Adeus.",
"Eu gostaria de fazer negócios com você...",
"Trouxe o dinheiro conforme combinado. Onde é ",
"Sabine Matton",
"?!",
"Meus homens a trarão aqui. Mostre-me o dinheiro.",
"Certo. Os meus rapazes vão trazê-la. Enquanto isso, mostrem-me o ouro.",
"Por que não fico com a garota E o ouro?",
"Você trouxe, hein? Bem, entregue-o e vá embora. A menina fica comigo.",
"Vá embora! Não tenho nada a ver com você!",
"Como quiser.",
"Hmph!",
"Você viu minha filha? Ela está desaparecida. Dizem que ela foi vista pela última vez no porto.",
"Não, eu não a vi.",
"Talvez ela tenha fugido com algum rapaz.",
"Sim, tenho algumas informações sobre isso.",
"Claro que eu a vi. Posso até te dizer onde ela está.",
"Sim, o quê posso fazer por você?",
"Estou precisando de ouro agora e estou procurando trabalho. Posso ajudá-lo em alguma coisa?",
"Estou ouvindo.",
"Pediram-me para entregar uma carga para você.",
"Você, por acaso, precisaria de um capitão, senhor? Tenho um navio excelente e posso entregar qualquer carga, onde você quiser.",
"Falei com o seu devedor. Ele simplesmente não tem ouro para pagar você.",
"Seu devedor simplesmente não tem ouro para pagar você.",
"Seu devedor se recusa a pagar. Se você quiser seu dinheiro de volta, acho que terá que recorrer a...outros métodos.",
"Seu devedor, este ",
"Baldewyn Coffier",
", recusa-se a pagar.",
"Seu devedor me disse que hoje lhe trará o dinheiro que deve.",
"Sorriso. Convenci o seu devedor a pagar. Ele prometeu trazer o dinheiro hoje.",
"Cumpri a tarefa que você me deu. Aqui está o seu dinheiro.",
"Aqui está o seu dinheiro. Já fiz a minha parte no nosso acordo.",
"Um homem chamado ",
"Baldewyn Coffier",
"Baldewyn Coffier",
" me pediu para te dar esse dinheiro.",
"Alguém chamado ",
"Baldewyn Coffier",
" tive a gentileza de entregar este ouro para você.",
"Falei com o seu devedor. Acho que você o está pressionando demais. Dê-lhe tempo para começar seu próprio negócio e ele certamente pagará de volta.",
"Seu devedor, ",
"Baldewyn Coffier",
" é um bom homem. Não o pressione, e ele lhe pagará de volta mais cedo ou mais tarde.",
"Entreguei sua carga em #sRedmond#.",
"Sua carga está em #sRedmond#, ",
".",
"Preciso falar com você sobre aquela carga que você queria que fosse entregue em #sRedmond#.",
"Bem, você vê... a carga que você queria que eu entregasse em #sRedmond#...",
"Eu peguei sua carga de ",
"Thomas O'Reily",
"Thomas O'Reily",
" no meu domínio.",
"Thomas O'Reily",
" me contratou para entregar alguma carga para você.",
"Levei sua filha para onde você me pediu para levá-la. Eu também tenho esta carta para você.",
"Levei sua filha para onde você me pediu para levá-la.",
"Levei sua filha para onde você me pediu para levá-la.",
"Sua garota agora está segura em #sIsla Muelle#.",
"Tenho novidades sobre sua filha.",
"Você sabe, eu estive pensando. Você é um comerciante rico e um pai amoroso. Por que você não me paga alguns milhares em ouro em troca da garota?",
"Desculpe, tenho que ir embora.",
"Como ela está? Onde ela está? Por favor, diga-me, eu imploro!",
"Sua filha fugiu. Ela está no meu navio neste momento",
"Sua garota fugiu. Ela está no meu navio.",
"Sua filha está no meu navio agora. Tenho certeza que você ficará feliz em me pagar 5.000 ouro para vê-la novamente.",
"Sua garota está em minhas mãos. Se você não quiser que ela seja prejudicada, você me pagará 5.000 ouro.",
"Ela fez o que?! Vou lhe dar uma lição quando colocar minhas mãos nela!",
"Eu acalmaria minha raiva se fosse você e pensaria nas razões pelas quais sua filha sentiu que não poderia mais viver com você.",
"Isso vai ensiná-la a não desafiar os pais! Ela queria aventura, ela conseguiu!",
"Você está certo e eu sei o que vou fazer!",
"Tudo bem, vou trazer sua filha até você.",
"Ordenarei aos meus homens que tragam a sua filha para terra. Então ela é seu problema novamente",
"Você vai se arrepender disso!",
"Você pode estar certo, mas a vida é um risco e acho que ela será uma excelente oficial em minha tripulação.",
"Você não é o primeiro a me ameaçar assim, mas sua filha ainda se torna oficial do meu navio.",
"Aqui está o dinheiro - exatamente 5.000 ouro. Agora, onde está minha filha?",
"Fique calmo. Ela estará com você em breve",
"Acalmar! Eu já lhe disse que meus homens a trarão em breve!",
"Eu mudei de ideia. Vou pegar o dinheiro e a garota",
"Ha! Agora que tenho o dinheiro, você nunca mais verá sua filha!",
"Meu querido, você está bem?! Esse rufião não te machucou?",
"Há uma bela visão. Uma reunião de família. Vou deixar você com isso.",
"Poupe-me do terno reencontro, ou posso simplesmente mudar de ideia.",
"Então, você está mantendo minha filha prisioneira a bordo de seu navio. Quanto você quer pela liberdade dela?",
"Não é muito para um pai amoroso pagar. Apenas 5.000 ouro.",
"Eu quero 5.000 ouro. O que você diz?",
"Tudo bem. Traga minha filha aqui e você terá seu dinheiro.",
"Como quiser.",
"Muito bem. Ela estará aqui em breve.",
"Não. Nos encontraremos fora da cidade, na praia. É mais seguro assim.",
"Que tipo de idiota você me considera? Você levará o dinheiro para a praia fora da cidade em duas horas, e então talvez eu deixe você ficar com sua filhinha!",
"...Tudo bem. Em duas horas, na praia fora da cidade.",
"E não tente nada tolo!",
"E não tente me armar, ou você pode dar um beijo de adeus na sua garotinha!",
"Que tolo você é! Guardas, Guardas!",
"Explodir você! Bem, vou me despedir antes que os guardas cheguem, mas essa é a última vez que você verá sua filha, ela se juntará aos meus oficiais de boa vontade.",
"Vejo que você executou sua tarefa de maneira admirável. Agora que minha filha está segura e você ganhou minha confiança, podemos conversar sobre negócios reais.",
"Que negócio seria esse?",
"Bem, cuspa então!",
"Sinto muito, tenho outras preocupações no momento.",
"Talvez mais tarde. Preciso de uma folga de você e de suas tarefas: enforcar alguns homens, derramar um pouco de sangue. Conversaremos novamente.",
"Não vou cair nos seus truques. Você exigiu um resgate pela minha amada filha! Saia, escória pirata!",
"Isso é uma vergonha. Adeus.",
"Você pode ter dinheiro, mas não é melhor que eu!",
"...",
"Não tenho nenhum trabalho para você no momento, mas gostaria de lhe pedir um favor.",
"Que tipo de favor?",
"Eu tenho uma filha. Acredito que você já a conheceu.",
"Sim eu fiz. Ela parece uma boa garota. Mas o que exatamente você quer de mim?",
"Desde que a mãe dela foi embora, tem sido difícil criá-la sozinha.",
"Certamente um comerciante rico como você não precisa da minha simpatia?",
"Não, mas #sSabine# está numa idade em que o toque de uma mulher em sua vida é essencial.",
"Talvez sim, mas novamente, o que isso tem a ver comigo?",
"Quero que você a conduza até onde decidi que ela receberá a orientação de que precisa.",
"Eu não administro um serviço de acompanhantes. Por que você mesmo não a leva?",
"Não não. Não posso sair da minha loja... ou correria o risco de perder meu negócio, mas desde que você a conheceu, pensei que você poderia encontrar uma maneira de me ajudar.",
"Talvez, mas eu precisaria saber mais detalhes antes de poder decidir.",
"Especificamente, quero que você a leve para #sIsla Muelle#, para sua madrinha ",
"Sylvie Bondies",
"Sylvie Bondies",
".",
"Tudo bem. Farei isso como um favor para você.",
"E quanto você me pagaria por isso?",
"Desculpe, não posso fazer isso.",
"Bem, eu esperava que você fizesse isso como um favor para mim. Mas já que você mencionou o pagamento, suponho que 1.500 moedas de ouro seria mais do que justo.",
"Acordado. Dê-me o dinheiro e considere isso feito.",
"Não. Receio não poder fazer isso.",
"Aqui está o seu dinheiro. Mantenha minha filha segura até que ela chegue a #sIsla Muelle#.",
"Você tem minha palavra nisso.",
"Como eu disse, leve minha filha para a madrinha dela, que mora em #sisland_Isla Muelle#. O nome dela é ",
"Sylvie Bondies",
"Sylvie Bondies",
". \nEla é francesa, mas mora na ilha há vários anos. Dê a ela esta carta quando você chegar lá.",
"Como vou encontrar esta mulher numa cidade tão grande?",
"Ah, é bem simples. Ao entrar na cidade, desça as escadas à sua direita e siga em frente até ver outra escada. \nEscale-o e o seguinte e vire à esquerda. Siga em frente até ter uma casa à sua frente. A porta que você procura é a da direita.",
"Bom, vou embora imediatamente então. Diga a sua filha para esperar por mim no meu navio, '",
".",
"Muito bem. Terei que encontrar outra pessoa então.",
"Adeus.",
"Há outra coisa que gostaria de discutir.",
"Vejo que você lidou bem com isso. Aqui está a sua parte.",
"Você não parece muito feliz com isso. Por que é que?",
"Por que o olhar azedo?",
"Peço desculpa, mas tenho de ir agora.",
"Você sabe algo? Eu não poderia estar menos interessado. Faça-me um favor e espere até eu sair daqui para bater suas gengivas.",
"Posso fazer algumas perguntas?",
"Quero falar com você.",
"Finalmente! Eu pensei que ele nunca me pagaria de volta",
"Com licença, mas tenho que ir agora",
"Agora que seus assuntos estão resolvidos, vou cuidar dos meus. Adeus.",
"Posso fazer algumas perguntas?",
"Quero falar com você.",
"Sim, sim, ele já trouxe o dinheiro.",
"Se isso for verdade, quero a minha recompensa.",
"Mas você não parece feliz. Por que?",
"Porque eu o odeio! Eu o odeio completamente e quero arruiná-lo. Ele estava quase em meu poder - tudo o que restava era colocá-lo na prisão por suas dívidas. Mas de alguma forma ele deslizou livre...",
"O que ele fez para que você o odiasse tanto?",
"Isso não é da minha conta. Adeus.",
"Não é da sua conta!",
"Tudo bem, tudo bem, acalme-se. Estou indo embora.",
"Vamos mudar de assunto. Posso fazer algumas perguntas?",
"Claro, aqui está o seu dinheiro. Mereceste.",
"Preciso ir agora.",
"Posso fazer algumas perguntas?",
"Você sabe, ",
", Não consigo ver como isso é da sua conta.",
"Como você deseja, mas pensei que você fosse um homem melhor do que isso.",
"Realmente? E eu pensei que a velha raposa via a tensão entre #snationR# e #snationF# como sua chance de me enganar.",
"Como você pode ver, ele não o fez. Vamos descarregá-lo - não quero ficar aqui mais tempo do que o necessário.",
"Claro, ",
". Não deve demorar muito.",
"Eu espero que você esteja certo.",
"Bem, terminamos ",
". Obrigado pela entrega segura. Boa sorte para você.",
"Adeus.",
"Sim?",
"Entreguei sua carga em #sRedmond#.",
"Sinto muito, mas não consegui entregar sua carga em #sRedmond#.",
"Não, não preciso dos seus serviços. Pelo menos enquanto você estiver afundando navios #snation_desc#.",
"Nesse caso, adeus.",
"Sinto muito, mas não tenho nada para você no momento.",
"Voltarei mais tarde então.",
"Sinto muito, mas seu navio não tem capacidade para a tarefa que tenho em mente.",
"Voltarei mais tarde então.",
"Oh! Eu só ia pedir que você me fizesse um favor. O problema é que preciso que uma carga seja entregue em ",
", e o mais rápido possível. Se você conseguir fazer isso dentro de um mês, receberá ",
" ouro quando você chegar. O que você acha desta oferta?",
"Eu definitivamente gosto disso.",
"Eu não posso aceitar isso.",
"Já te disse hoje que não tenho nada para você.",
"Oh, desculpe.",
"Você se lembrou da sua tarefa um pouco tarde demais, não acha? Vou levar a mercadoria de qualquer maneira, mas não espere ser pago. Preste mais atenção ao tempo da próxima vez! Adeus.",
"Até a próxima.",
"Oh! Estou esperando por isso há muito tempo. Aqui está sua recompensa.",
"Sempre bem-vindo.",
"Não, não tenho nenhum trabalho para você no momento.",
"Voltarei mais tarde então.",
"Eu já te dei um emprego. Não vou te dar outro até que você me mostre que pode terminar o que começou.",
"Desculpe. Você está certo, é claro.",
"Você deveria ter vergonha de si mesmo! ",
"Thomas O'Reily",
" me enviou uma carta que descreve claramente como você tentou enganá-lo.",
"Espere! Posso explicar tudo.",
"Sim eu sei. ",
"Thomas O'Reily",
" já me enviou uma carta e me informou que você tentou me roubar.",
"Por favor! Eu posso explicar tudo!",
"Guarde sua explicação. Vejamos: como resultado de suas maquinações perdi 1.500 ouro. Compense-me pela minha perda e esquecerei esse infeliz incidente - desta vez.",
"Eu não tenho tanto dinheiro!",
"Tudo bem, aqui está o seu dinheiro. Sou honesto o suficiente para pagar pelo meu erro e juro que não vou repeti-lo.",
"O que?! Saia antes que eu chame os guardas! Nunca mais farei negócios com você.",
"Ha! Estou tão preocupado com isso!",
"Talvez você seja mais sábio do que eu pensava. Cuide para que isso não aconteça novamente.",
"Claro que não ",
".",
"Ah, você chegou bem na hora! Tenho uma carga que precisa estar em #sRedmond#. O pagamento é de 600 ouro.",
"Espere. A Inglaterra não está em guerra com a França?",
"É um acordo, ",
".",
"Sinto muito, mas não tenho espaço suficiente no meu porão para aceitar o trabalho.",
"Tudo bem, voltarei mais tarde.",
"Meu negócio não pode esperar pela guerra. Acredite, esta viagem não será mais arriscada do que o normal.",
"Qual é a carga?",
"Isso é fácil para você dizer, seguro em terra firme. Os riscos são muito maiores do que o normal. Naturalmente, vou querer um pagamento maior.",
"Você é mais esperto do que meus parceiros habituais... Tudo bem. Suponho que posso aumentar seu pagamento para 800 ouro, mas não mais.",
"Tudo bem. Que tipo de carga é essa?",
"Não não não. Já enviei navios para #sRedmond# antes e tudo correu bem. 600 é minha oferta final.",
"Tudo bem, é justo. Qual é a carga?",
"Desculpe. O dinheiro não vale o risco. Adeus.",
"Bem, já que agora somos parceiros, deixe-me apresentar-me. Meu nome é ",
".",
"Meu nome é ",
".",
"Bem, já que agora somos parceiros, deixe-me apresentar-me. Meu nome é ",
".",
"Meu nome é ",
".",
"A carga é de 100 toneladas de cacau. Entregue para Thomas O'Reily, o lojista em #sRedmond#.",
"Eu vou fazer isso.",
"Você tem mercadorias para vender ou só precisa de alguns itens pessoais, capitão?",
"Gostaria de vender a carga que trouxe.",
"Quero comprar algumas coisas para mim.",
"Não negociaremos de jeito nenhum. Adeus.",
"Excelente, excelente! Para ser honesto, eu não tinha certeza se conseguiria levar essa carga até a temida guerra...",
"Você não esqueceu alguma coisa?",
"Ah, sim, o dinheiro. Claro. Aqui você vai. Espero que possamos trabalhar juntos no futuro.",
"Veremos sobre isso. Por enquanto, tenho que ir. Adeus.",
"Sim, tenho alguns problemas que gostaria de resolver o mais rápido possível.",
"Que tipo de problemas?",
"Você vê, ",
", Às vezes empresto dinheiro para pessoas que precisam.",
"Então você é um comerciante E um agiota.",
"Agiota é um termo tão desagradável. Não vejo nada de errado com o que faço. Então - um homem chamado ",
"Baldewyn Coffier",
"Baldewyn Coffier",
" pegou um empréstimo de 2.500 de ouro comigo há algum tempo e agora é hora de pagar,\nmas ele afirma que não pode me pagar porque está falido!\nTenho certeza de que ele tem o dinheiro. Ele simplesmente não quer me pagar. Na verdade, ouvi dizer que ele tentou atrair um rapaz para um empreendimento obscuro, prometendo pilhas de ouro.\nGraças a Deus ele não conseguiu, mas quem sabe quantos tolos desavisados ele já enganou?",
"Eu entendo, eu entendo. Eu vou arrancar o dinheiro dele agora mesmo...",
"Não tão rápido, ",
". Se você conseguir recuperar meu dinheiro, receberá sua parte. Digamos, vinte por cento...",
"Isso chegaria a 500 ouro? Nada mal para um trabalho tão simples. É um acordo.",
"Apenas 500 ouro? Com respeito ",
", Não acho que isso seja particularmente generoso.",
"Bem, tudo bem. Vou te dar trinta por cento. Isso daria 750 ouro.",
"Negócio.",
"Pelo contrário, acho que é MUITO generoso para uma tarefa tão servil, e não vou pagar mais!",
"Com a sua reputação, você deveria ficar feliz em receber o que estou oferecendo. Uma pessoa como você poderia facilmente pegar meu dinheiro e desaparecer. 500 ouro, não mais!",
"Tudo bem então. Mas tenha em mente que esta será a última vez que trabalharei por uma taxa tão pequena.",
"Ridículo. Não abro os olhos pela manhã por uma taxa tão lamentável. Adeus.",
"Como quiser. Vou encontrar outra pessoa. Há muitos capitães gratuitos por aqui.",
"Adeus.",
"Sim, bem... você sabe, acho que vou aceitar o trabalho, afinal - cada moeda de ouro conta!",
"Excelente! Agora vá e encontre aquele canalha. Ele geralmente está vagando pela cidade ou à espreita na taverna, procurando o próximo simplório que possa trapacear.",
"Voltarei em breve - não creio que demore muito.",
"Muito bem. Você não me deixa outra escolha a não ser fazer uma reclamação oficial e vê-lo preso por suas dívidas!",
"Esse é o seu problema. Faça como quiser.",
"Por que você não fez isso em primeiro lugar? Por que essa música e dança sobre recuperar seu dinheiro?!",
"Espere, não vá ainda!",
"O que?",
"Desculpe. Tenho outros assuntos para tratar e não tenho mais tempo para conversar com você. Adeus.",
"Bem, veja bem... para fazer uma reclamação oficial, ela precisa ser assinada pela parte lesada - sou eu - e pelo menos uma testemunha.",
"E você quer que eu seja essa testemunha? Esqueça. Eu não vou fazer parte disso.",
"O quê tem pra mim? O meu testemunho não é gratuito.",
"Você receberá o mesmo dinheiro que prometi para cobrar a dívida.",
"Bem, essa é uma oferta decente por uma coisa pequena. Concordo.",
"Dobre o dinheiro e talvez possamos conversar.",
"Bem, isso é muito ruim. Eu estava contando com você.",
"Adeus, ",
".",
"Eu tenho algumas perguntas para você.",
"Excelente. Já escrevi a reclamação. Se você apenas assinar aqui...",
"Feito. Agora me dê meu dinheiro e eu vou embora",
"Feito. Agora tenho algumas perguntas para você.",
"Tudo bem, vou dobrar o dinheiro. Isso daria certo ",
" ouro. Já resolvi a reclamação, por isso, por favor, assine aqui...",
"Feito. Agora me dê meu dinheiro e eu vou embora",
"Feito. Agora tenho algumas perguntas para você.",
"Isso é ruim. Achei que poderíamos fazer negócios.",
"Adeus, ",
".",
"Espere! Eu concordo com sua oferta.",
"E no que exatamente você está pensando?",
"Isso parece ameaçador para ela. O que você está pensando?",
"Realmente? Achei que nunca veria isso!",
"Acabei de capturar esta ratoeira, então se você quiser manter a cabeça fria, não importa sua loja, é melhor cuidar de suas maneiras",
"É claro é claro. Basta dar uma olhada no meu estoque. Fique a vontade.",
"Achei que a velha raposa via a tensão entre #snationR# e #snationF# como sua chance de me enganar.",
"Antes que você comece ",
"Ela já está aprendendo lições no meu navio.",
"O que você quer dizer com isso?",
"Simplesmente ela crescerá rápido no meu navio e eu farei dela oficial.",
"Bem, está tudo bem e me isenta de qualquer responsabilidade.",
"Exatamente. Então está combinado.",
"Mas eu tenho sua carga de ",
"Sim, estou esperando #squantity# cwt de #scargo#. Você tem?",
"Hum... algumas delas parecem ter sido extraviadas. Não se preocupe, vou repor o que foi perdido e trazer para você!",
"Realmente? E eu pensei que a velha raposa via todos os ataques piratas aos navios #snation# como uma chance de me enganar.",
"Achei que a velha raposa via todos os ataques piratas aos navios #snation# como uma chance de me enganar.",
"Mas outra pessoa tem negócios com você. Pediram-me para entregar alguma carga aqui.",
};
