string DLG_TEXT[33] = {
"Obrigado, #stitle#. Nigel Blythe sempre foi rápido nas punições. Se você não tivesse intervindo naquele momento, eu certamente estaria morto agora.",
"Sim, percebi que você teve algumas dificuldades com ele.",
"Sim, percebi que você teve algumas dificuldades com ele.",
"É verdade. Eu era navegador no navio de Nigel. Ele próprio não era um grande marinheiro, para ser franco. \nNão faz muito tempo, embarcamos uma carga enorme, com destino a uma ilha que nenhum de nós tinha visto antes. O navio acabou encalhado por uma tempestade. \nEscapamos, mas a embarcação e a carga foram destruídas. Nigel me culpou por tudo.",
"E agora você não tem capitão",
"Ainda não fomos apresentados. Eu sou ",
". ",
"Meu nome é Artois Voisey e realmente estou de castigo. Ficarei feliz em servir com você, se você me considerar digno.",
"Obrigado, mas já tenho um navegador.",
"É um acordo. Mas por favor, tente não afundar o meu navio.",
"O que posso fazer por você, capitão?",
"O que?",
"Apenas de passagem.",
"À vontade.",
"Capitão, estes homens mataram o meu amigo... um velho amigo, e queriam matar-me também...",
"Okay, certo. Agora me diga - por que eles atacaram você em primeiro lugar?",
"Receio que seja um segredo, #stitle#, e não seja meu para contar. Estou vinculado ao código de Morgan e Bartholemew.",
"Pode ser, mas você não é exatamente um pirata e eu sou seu capitão. E se você não quer que sua vida acabe tão cedo, você vai me contar tudo agora mesmo!",
"Você é um homem de honra, Artois. Eu respeito isso. Guarde o seu segredo.",
"Você tem razão, #stitle#. Vou te contar tudo que sei. \nDe alguma forma, Nigel Blythe soube de um navio que encalhou perto de #sisland_Conceicao#, carregando um tesouro em seu porão. Estávamos indo para lá quando naufragamos. \nQuando você matou Nigel, eu me tornei o único homem vivo que conhece o caminho para esse tesouro. É por isso que a antiga equipe de Blythe está atrás de mim. \nEu nunca contaria a eles o que sei - mas direi a você, porque acredito que você é um #sgender# honesto. Mais ou menos. O tesouro está localizado em #sisland_Douwesen#. Você pode encontrar o caminho para o navio naufragado sob a cachoeira.",
"Agora estamos nos entendendo!",
"Obrigado, capitão. Eu sabia que poderia contar com você.",
"De nada. Fico feliz em ver você vivo e bem.",
"Algo mais está incomodando você?",
"Sim, caí em desgraça com as autoridades locais por causa desta comoção...",
"Ah, não se preocupe, acho que posso resolver esse problema.",
"Sim, talvez você possa, você... heh-heh... testemunhou tudo isso sozinho.",
"Obrigado, capitão! Você salvou minha vida mais uma vez.",
"Naturalmente. Não perderei um dos meus oficiais se puder evitar.",
"Agora acho que posso lhe contar meu segredo. \nDe alguma forma, Nigel Blythe soube de um navio que encalhou perto de #sisland_Conceicao#, carregando um tesouro em seu porão. Estávamos indo para lá quando naufragamos. \nQuando você matou Nigel, eu me tornei o único homem vivo que conhece o caminho para esse tesouro. É por isso que a antiga equipe de Blythe está atrás de mim. \nEu nunca contaria a eles o que sei - mas direi a você, porque acredito que você é um #sgender# honesto, mais ou menos. O tesouro está localizado em #sisland_Douwesen#. Você pode encontrar o caminho para o navio naufragado sob a cachoeira.",
"Obrigado, Artois, não esquecerei sua ajuda.",
"Apenas um pedido, capitão. Jurei que se eu saísse vivo desta aventura, doaria 4.000 ouro para a igreja em #sRedmond#.",
"Claro, nós faremos isso! Agora vamos seguir nosso caminho.",

};
