string DLG_TEXT[9] = {
"Uma caixa simples, meio enterrada no chão. Serve como obstrução e pode ser armadilhada por meio de uma granada.",
"Essa coisa é apenas um incômodo inútil. Contramestre! Limpe isso. E coloque as tábuas em nossa loja.",
"O lugar certo para uma armadilha. Uma granada com uma pederneira presa à tampa será uma boa surpresa para qualquer cara curioso. E dificilmente alguém resistirá à tentação...",
"É melhor eu deixar essa coisa em paz...",
"Ei, você aí na frente do teclado! Este é um edifício que VOCÊ criou, então que tal criar seu próprio diálogo também? Basta usar o Bloco de Notas para abrir o arquivo program\dialogs\ ",
"e substituir este texto pelo seu. Em seguida, siga as instruções nos comentários.",
"Substitua isso pelo texto do diálogo do NPC.",
"Texto do diálogo do jogadoroption link.l1 que encerra o diálogo.",
"Texto do diálogo do jogadoroption link.l2 que leva a outra troca.",
};
