string DLG_TEXT[43] = {
", forças hostis avistadas. Formar para defesa.",
", movimentos inimigos em nosso setor! Batam para os quartéis!",
", movimentos suspeitos em nosso perímetro, postos de batalha de homens!",
"Um relatório detalhado, fuzileiro naval, AGORA.",
"Deixe-me em paz com isso, esse é SEU trabalho! Afinal, foi para isso que o contratei: como bucha de canhão... er... alimentador de canhões. De qualquer forma, não tenho tempo: preciso voltar correndo para minha casa branca segura, vestir minha jaqueta de bombardeiro e fazer algumas piadas duras para o eleitorado...",
"Relatório",
"tripulado e pronto para a batalha, ",
"tudo quieto neste setor.",
"Nós nos retiramos desta posição. Desmantelemos isso",
", carreguemos as tábuas em nosso porão e reportemos ao sargento dos meus fuzileiros navais para tarefas navais.",
"Esta fortificação pareceria muito mais formidável com um canhão. Sem mencionar o aumento do poder de fogo. Aqui, Marine, pegue essas 5000 de ouro e obtenha uma arma para sua posição.",
"Marine, tenho uma tarefa especial para você: Aqui, pegue esta granada, e se o inimigo quebrar e invadir esta posição...",
"Só de passagem...",
"Muito bem, Marine, continue.",
"Soldado, esta fortificação não é muito baixa e muito fraca para impedir um ataque?",
"Ei, por que você está aqui tão imóvel? ",
"Você engoliu um cabo de vassoura...",
"Vamos, relaxe um pouco... À VONTADE!",
"Espero um pouco mais de atividade dos meus marines, ouviu?",
"Ei, você aí na frente do teclado! Este é um edifício que VOCÊ criou, então que tal criar seu próprio diálogo também? Basta usar o Bloco de Notas para abrir o arquivo program\dialogs\ ",
"e substituir este texto pelo seu. Então siga as instruções nos comentários.",
"Sobrescreva isso com o texto do diálogo do NPC.",
"Texto do player dialogoption link.l1 que encerra o diálogo.",
"Texto do player dialogoption link.l2 que leva a outra troca.",
"...Eu vou explodi-los para o reino vindouro. Eu sei do meu dever, Comandante!",
"Esse é o espírito, Fuzileiro! Com seu senso de dever, você logo se tornará cabo. (...se você viver tanto tempo...)",
"Sim, ",
", Eu conheço muito bem o sargento-mestre da revista local. Por 5000 de ouro, ele venderia toda a sua artilharia. Só me dê algumas horas.",
"Esse é o espírito, Fuzileiro! Com sua compreensão de logística, você logo se tornará cabo. (...se você viver tanto tempo...)",
"Canibais Akellani selvagens se aproximando, ",
"! Ah, se tivéssemos mais desses bastiões, paliçadas, minas e canhões...",
"Atenção, soldado! Mantenha essa posição aconteça o que acontecer. Continue atirando, não deixe o inimigo te atrair para o combate corpo a corpo. Eu cuidarei do trabalho com lâminas...",
"Francisco Pizarro, o Jovem, e sua horda de conquistadores saqueadores se aproximando, ",
"! Desejando sangue, pilhagem e estupro... Ah, se tivéssemos mais desses bastiões, paliçadas, minas e canhões...",
"Muito baixo? Parece que você tem as mesmas visões antiquadas sobre arquitetura militar como aqueles pedreiros russos que constroem todas aquelas muralhas medíocres e fortes arranha-céus por aqui. Mas a invenção da pólvora tornou os muros altos com ameias obsoletos. O perfil baixo deste bastião oferece à artilharia de cerco um alvo menor. Não importa que a infantaria inimiga possa escalar canhoneiras baixas, enquanto nossa artilharia continuar a atirar, eles não viverão muito.",
"Hum, bem, toda madeira decente vai para os estaleiros, então tivemos que construir esta paliçada com troncos quebradiços e madeira flutuante. É verdade, há brechas largas o suficiente para que um inimigo possa passar. Mas enquanto nossa artilharia continuar a atirar, eles não viverão muito depois.",
"Então a artilharia é a chave para tudo? Como posso posicionar meus canhões da melhor maneira?",
"Agrupe várias fortificações com canhões para que possam apoiar umas às outras, mas não tão perto que todas sejam atacadas ao mesmo tempo. Na linha de frente, um bastião forte que receba o impacto do ataque e, atrás dele, paliçadas mais baratas que podem atirar nos atacantes ocupados com o bastião. Mas tome cuidado para que nenhum dos seus homens entre na linha de fogo. A longa distância, nossos projéteis matam todos perto do alvo. Fique completamente fora da luta ou fique perto dos canhões, onde nossa mira é melhor.",
"Hum, não tenho certeza se posso pagar por isso... Mas obrigado pela palestra sobre fortificações do século XVII.",
"Nós sempre ficamos em posição de sentido na presença de um superior. Esse é o exercício, e o exercício é tudo.",
"Estou de olho em um alvo suspeito, e não quero perdê-lo muito. 'Mantenha sua mira, nunca vacile, nunca pisque', nosso sargento instrutor costumava dizer.",
"Primeira regra da camuflagem: movimento atrai atenção. Então nunca se mova se não for necessário.",
"Tudo bem, eu entendo... Continue.",
};
