string DLG_TEXT[34] = {
", querido visitante. Eu sou ",
", proprietário do estaleiro local.",
"E eu sou ",
", capitão do '",
".",
", ",
". Você precisa dos serviços do meu estaleiro, ",
"?",
"Sim, meu navio deveria ser consertado.",
"Na verdade, prefiro conversar.",
"Não, obrigado.",
"Bem, estou feliz em conhecê-lo. Se você é capitão, então veio ao lugar certo.",
"Perfeito, ",
". Vamos começar com esses reparos.",
"Obrigado. Mas deixe-me perguntar uma coisa primeiro.",
"Talvez na próxima vez. Eu tenho que ir.",
"No que exatamente você está interessado ",
"?",
"Não, não no momento.",
"Eu vejo. Você precisa de mais alguma coisa, ",
"?",
"Sim. Gostaria de utilizar os serviços do seu estaleiro.",
"Por enquanto é tudo, obrigado. Até a próxima!",
"O que exatamente você precisa?",
"Preciso consertar meu navio ou talvez considere comprar um novo.",
"Quero instalar novas armas no meu navio.",
"Nada, obrigado.",
"o mestre carpinteiro deste quintal.",
"Recuso-me a negociar com uma pessoa com a sua reputação e relações. Agora saia, ",
", antes de chamar os guardas.",
"Muito bem.",
"Tudo bem, meu cais ao lado do forte está disponível para você. Se você quiser, direi ao meu chefe das docas para rebocar seu navio até lá.",
"DOCA AO LADO DO FORTE?? Uhh... só me lembro que tenho... eeh... outro assunto urgente que preciso resolver primeiro. Adeus.",
"Tudo bem, vamos ver o que sua jarda tem a oferecer.",

};
