string DLG_TEXT[20] = {
"Olá, ",
". Você é ",
"?",
"Você é o responsável por carregar a carga no meu navio?",
"Sim. Quem é você? O mestre de carga?",
"Sim o que você quer?",
"Você está aqui para carregar mercadorias no meu navio?",
"Tudo bem, meu amigo. Veja bem, decidimos ensinar aquele malandro, cujo nome é ",
"Thomas O'Reily",
", uma lição. Ele recusou nossos serviços e você também verá como é quando alguém fica no nosso caminho..",
"O que você quer dizer?",
"O que você está falando?",
"Sim, eu sou o chefe desses caras. Onde está seu navio? Não podemos começar a carregar sem ele.",
"Meu navio está no porto. Resolvi verificar tudo antes de navegar para cá.",
"Sem problemas. Voltarei ao porto agora e darei ordem ao meu povo para navegar aqui até esta baía.",
"Não importa. Vamos lá rapazes! Obtenha #spronoun#!",
"Droga!",
"Espere! Eu sabia que algo suspeito estava acontecendo aqui. Deixe-me ajudar vocês.",
"Humm... eu gosto de você! Você não pode ajudar, apenas navegue para longe. Nós cuidaremos das coisas.",
"OK",
};
