string DLG_TEXT[18] = {
"SIM! Tenho o melhor rum e vinho do arquipélago.",
"Vou acreditar na sua palavra! quanto?",
"Duvido seriamente disso...",
"Você com certeza vai querer uma bebida para acompanhar suas mulheres!",
"Bebida e mulheres proporcionam bons momentos.",
"Acho que preferiria mulheres hoje...",
"Compre uma bebida para mim, amigo, a melhor que você já provou.",
"Por que diabos não!",
"Eu pareço um bêbado para você?",
"Eu tenho um segredinho para vocês, essas bebidas são tão boas que alguns dizem que podem curar em batalha!",
"Com certeza me faz sentir seguro estando intoxicado enquanto luto...",
"Como vou engolir uma caneca de rum no calor da batalha? Eu vou passar.",
"Bem, por apenas 1.000 Gold você pode tomar uma caneca de rum de #sRedmond# (não derrame, isso tira a tinta do seu casaco!) ou uma garrafa do melhor Chardonnay 'Chateau Scharlatan', um dernier cru, denominação Grande Enxaqueca!",
"Rum para mim, não aquela água de lírio para maricas francesas!",
"Vinho seria bom.",
" 1000 ouro? Não, obrigado, conheço maneiras mais baratas de perder a visão.",
"Ei, vocês dois! A patroa aqui tem alguns amigos que você não quer conhecer. Mais problemas e você os encontrará!",
"Tudo bem, tudo bem! Eu já fui!",
};
