string DLG_TEXT[42] = {
"Não tenho tempo para falar com você",
"Deixa para lá.",
"O que você quer, estranho?",
"Eu sou ",
"E eu sou ",
". O que você quer?",
"Agora o que você quer ",
"O que você pode me dizer sobre esse lugar?",
"É um acampamento de bucaneiros. É para bucaneiros. Se você é um bucaneiro, você deveria saber disso.\nSe não... ei, você é algum tipo de espião do governo?",
"Não! Er... eu vou embora agora.",
"Preciso de ajuda para me orientar por aqui.",
"Meu dia não foi tão bom, então você nos poupará muitos problemas se puder me dizer como encontrar...",
"Só preciso me orientar, só isso.",
"O que sou eu, um guia turístico? Tudo bem, onde você precisa estar?",
"Conhece bem este lugar, eu conheço. Mas você está prestes a me conhecer, mesmo que continue batendo demais... cara.",
"Oh? E onde posso orientá-lo?",
"Onde fica o bar local?",
"Onde fica a taberna? E não tente me mandar para fora do portão de novo!",
"Onde posso vender minhas coisas ou comprar coisas novas?",
"Fácil. Basta passar pelo grande portão.",
"OK.",
"Compre coisas? Eu não faço isso. Tente perguntar a #sother#.",
"Obrigado, eu acho...",
"É o seguinte. Compre-me uma caneca de rum e eu lhe direi onde fica a taberna.",
"Mas... se eu comprar uma caneca de rum... então já terei encontrado a taberna!",
"Okay, certo. Se eu comprei uma caneca de rum, então eu mesmo vou beber!",
"Muito útil.",
" Mas tenho outra pergunta.",
"Gostaria da sua opinião sobre alguém aqui.",
"Oh? Quem é que queres dizer?",
", o lojista.",
", o taverneiro.",
"Quanto você está disposto a pagar?",
"Pagar? Esqueça!",
"Que tal 1 moeda brilhante?",
"Estou me sentindo generoso hoje, então aqui está uma sacola com 100 moedas de ouro.",
" está me pagando muito mais do que isso para dizer a todos que ele é tão honesto quanto o dia é longo e pode vender o que você quiser a preços realmente bons.",
"Obrigado! O que você quer que eu diga a você e a todos os outros sobre ele?",
"Eu só quero saber sua opinião honesta.",
"Honesto? De um bucaneiro que acabou de roubar 100 moedas de ouro de vocês?\nEi, pessoal - temos outro idiota aqui!",
"Reze para que eu não encontre você sozinho em um beco escuro ",
"Ele é um bom homem com uma garrafa de rum. Aliás, ele também é um bom homem com uma garrafa vazia, então não crie problemas na taverna!",
}
