string DLG_TEXT[23] = {
"Olá! Eu sou ",
", proprietário do estaleiro.",
"Prazer em conhecê-lo. Meu nome é ",
".",
"Posso ajudar, ",
"?",
"Sim, preciso dos seus serviços.",
"Estou procurando ganhar algum dinheiro. Talvez você possa me ajudar a encontrar um emprego?",
"Nada, desculpa. Estou indo embora.",
"Não me desculpe. Não tenho nenhum trabalho para você agora.",
"Justo. Talvez você possa responder algumas perguntas para mim, então.",
"Bem, obrigado de qualquer maneira. Até a próxima.",
"O que exatamente você precisa?",
"Preciso consertar meu navio ou talvez considere comprar um novo.",
"Preciso instalar novas armas na meu navio.",
"Nada. Obrigado.",
"Recuso-me a negociar com uma pessoa com a sua reputação e relações. Agora saia, ",
", antes de chamar os guardas.",
"Muito bem.",
"Tudo bem, meu cais ao lado do forte está disponível para você. Se você quiser, direi ao meu chefe das docas para rebocar seu navio até lá. Só então poderei avaliar os danos e dizer quanto tempo e dinheiro serão necessários.",
"DOCA AO LADO DO FORTE?? Uhh... só me lembro que tenho... eeh... outro assunto urgente que preciso resolver primeiro. Adeus.",
"Após fechar esta caixa de diálogo, pressione ENTER para abrir a interface de mudança de vela.",
"Saída",

};
