string DLG_TEXT[22] = {
"Diga-me, o que você está fazendo no meu navio?!",
"Eu estou aqui a negócios.",
"Estou aqui em nome do governador.",
"O que? Este não é o meu navio?! Desculpe meu erro!",
"O quê, aquele cachorro que se considera um nobre?",
"Sim, esse é o cachorro que quero dizer. Ele me ordenou que revistasse seu navio, já que você é suspeito de um sequestro.",
"Procurar meu navio?! Vou mandar içá-lo pela quilha e você poderá procurar cracas no casco quando sairmos do porto!",
"Podes tentar. Mas sinto que é justo dizer-lhe que as tripulações dos canhões do forte têm ordens de não deixar o seu navio sair do porto.",
"Eu acho que não, ",
"Corentin Lucay",
"! A garota é minha! E ninguém vai me dizer o que fazer!",
"...",
"Eu vou matar você!",
"...",
"Que negócio é esse? Você quer que eu escolte seu navio para algum lugar?",
"Não. Estou investigando o destino de uma certa garota...",
"O que? Aquele cachorro mandou você roubar a vadia dele de volta?!",
"Voce^pesca rápido! É mais ou menos isso.",
"Farei uma oferta amigável, marinheiro, já que você parece não saber com quem está lidando. Você deixa seu dinheiro, armas e roupas aqui no meu navio, e eu deixo você sair inteiro.",
"É uma proposta intrigante, mas minha lâmina e eu temos uma contraproposta. En garde!",
"É você de novo! Certamente você não veio aqui para ser morto de novo?",
"De jeito nenhum. Desta vez será você quem visitará as águas negras do Estige.",

};
