string DLG_TEXT[52] = {
"Hmm, qual é o seu problema ",
"? Quem está atrás da sua cabeça?",
"O que?",
"Olá. Quem é você?",
"Eu sou ",
". E preciso da sua ajuda.",
"Desculpe, estou enganado.",
"Então você está precisando da minha ajuda de novo?",
"Essa é a vida de pirata...",
"Graças a Deus, não. Essa ajuda é muito cara.",
"Então você está com problemas com os piratas?",
"De fato. Gostaria de normalizar as relações com meus irmãos do litoral.",
"Espanha.",
"Portugal.",
"Holanda.",
"França.",
"Acabei de mudar de ideia.",
"Você precisa fazer as pazes com nossa comunidade?",
"Receio não entender",
"Talvez você esteja interessado em meus serviços?",
"Não sei, o que você tem a oferecer?",
"Eu ajudo as pessoas a resolverem seus problemas.",
"Como?",
"Bem... Digamos que durante suas viagens você participe de alguns navios piratas gordos. Antes que você perceba, toda a comunidade pirata está atrás de você e a vida se torna difícil. Se você vier até mim, posso ajudar a restaurar as relações entre você e os piratas.\nÉ claro que esse serviço não é fácil e, para mim, organizar essas coisas pode custar uma quantia considerável. Mas você poderá visitar portos e cidades piratas e negociar lá novamente.",
"Que garantias você oferece de que minhas 'relações' seriam restauradas?",
"Sou o governador de #sTortuga#. Minhas decisões são respeitadas.",
"Tudo bem, gostaria de usar seus serviços.",
"Isso vai custar ",
" ouro.",
"Acordado.",
"Demais.",
"Isso vai custar ",
" ouro.",
"Acordado.",
"Isso é demais para mim. Adeus!",
"Negócio. Isso vai custar ",
" ouro.",
"Acordado.",
"Demais.",
"Isso vai custar ",
" ouro.",
"Acordado.",
"Demais.",
"Isso vai custar ",
" ouro.",
"Acordado.",
"Demais.",
"Com licença, você não tem ouro suficiente. Sem acordo.",
"Argh! Talvez eu volte quando tiver mais a oferecer.",
"Você pode zarpar agora. Tudo será resolvido o mais rápido possível.",
"Obrigado. Tomar cuidado.",
"Isso não é tudo.",

};
