string DLG_TEXT[388] = {
"Ah é você, ",
". O que você está fazendo aqui?",
"Nenhum de seus negócios ",
". E eu poderia fazer a mesma pergunta - mas estou muito ocupado para isso.\nEntão encontre um lugar para sentar e me deixe em paz.",
"Eu não esperava ver você aqui!",
"Fico feliz em ver você também ",
". Disseram-me que hoje em dia você gasta seu tempo livre salvando pessoas idosas.",
"Agora é minha vez de interrompê-lo. Onde você encontrou um rapaz tão útil ",
"?",
"Esse é o meu segredo ",
". Mas você ouviu o que ele tinha a dizer. Então agora podemos trabalhar juntos, como ofereci antes.",
"Fico feliz em ver que você esperou por mim. Agora podemos ir juntos.",
"Claro. Assim que ",
"Vicente Bethune",
" aqui nos diz para onde estamos indo.",
"É uma emboscada! Vá para a casa dele e tranque-se.\nVou segurá-los o máximo que puder.",
"Cuide-se!",
"O que esta acontecendo aqui?!",
"Ah. ",
"Vicente Bethune",
" me contou sobre você. Você é ",
"Robert Christopher Silehard",
"é garoto de recados!",
"Finalmente acordado, não é?",
"O que aconteceu?",
"Chegou a hora de fazer uma visita ao governador e fazer-lhe algumas perguntas pontuais.",
"Estou certo com você. Vamos.",
"Ótimo, mas não podemos invadir a residência em plena luz do dia. Vamos esperar na taberna até a noite cair",
"Pensamento inteligente. E eu poderia tomar uma bebida.",
"Olha, quanto mais cedo obtivermos algumas respostas do governador, mais cedo poderemos confiar uns nos outros novamente.",
"Sim. Suponho que você esteja certo.",
"Em primeiro lugar, vamos sair desta cidade.",
"Acordado.",
"Devíamos nos separar aqui. Podemos ter mais problemas assim.\nVocê rastreia aquele rapaz que copiou a lenda e eu irei atrás do ídolo.",
"Isso funciona para mim. Podemos nos encontrar no farol, onde mora o velho.",
"??? O que você está fazendo aqui?!",
"Eu estava procurando por você! Como pude ser tão estúpido?!",
"Bem, veja o que a maré trouxe. Pensei que tínhamos combinado de nos encontrar no farol.",
"Cansei de esperar.",
"Bem, acho que você concordará que a espera valeu a pena. Encontrei um diário de bordo. Vamos ver, agora... espere... Caramba! Não há nada aqui sobre onde encontrá-lo! Espere - quieto! Juro que ouvi uma porta ranger. Alguém está vindo!",
"Então? Agora posso encontrar aquele corsário espanhol que supostamente sequestrou a garota.",
"Vá para o navio pirata.",
"Ainda não. Não é hora para isso.",
"Agora preciso procurar aquela garota. Se ela não estiver por aqui em algum lugar, estou em apuros.",
"...",
"Eu mal consegui escapar daqueles fanáticos! Este negócio está ficando mais quente do que eu pensava.",
"Eu deveria relatar isso ao Padre Domingues. Mas quem é esse?",
"Os sequestradores de Lucas exigiram que o resgate fosse trazido para esta taverna, mas eles próprios não parecem estar aqui.\nAha, aqueles dois no bar parecem estar esperando por alguém...",
"Não há necessidade de perder tempo. Eles provavelmente são os que eu preciso. (Mostre-lhes o sinal.)",
"Talvez eu devesse escutar um pouco a conversa deles primeiro? (Escutar a conversa.)",
"A sorte sorri para mim hoje. ",
"Pepino Bertillon",
"O navio está atracado, então seu capitão deve estar em algum lugar por perto. A única coisa que resta a fazer é encontrá-lo e fazer alguns buracos em seu peito.\nMas primeiro preciso ter certeza de que é ele que estou matando - os habitantes locais são um bando violento e um erro pode me causar um monte de problemas.",
"...",
"Não se preocupe com isso. Não acredito que você perca tempo, então...\nSuponho que você esteja aqui por causa de um rapaz chamado ",
"Raoul Rheims",
". Goste ou não, eu vou com você",
"Certo, ",
", você pode me acompanhar.",
"Quanto tempo devemos esperar?",
"Investigador",
" disse que poderia levar dias.",
"Já faz uma semana. Eu preciso de ação!",
"Estamos falando de centenas de quilos de ouro. Não vale a pena esperar uma semana?",
"Para você, talvez. Não aguento mais isso. Eu preciso estar em movimento. Por que ele não consegue terminar a tradução no navio?",
"Você sabe, eu nunca pensei nisso.",
"Sim, acho que um pirata não gosta muito de bom senso, não é? Então, que uso você tem para o ouro ",
"?",
"O que?",
"Devo falar mais devagar? O que. Vai. Você. Fazer. Com. Sua parte do tesouro?",
"Comprarei uma ilha inglesa, suponho, e estabelecerei minhas próprias regras. Ou talvez eu me torne um colega inglês. Isso poderia ter suas recompensas. E você?",
"Isso é segredo.",
"Tudo bem. Seja desse jeito.",
"Você vai se opor à frota regular?",
"Não. Vou quebrá-lo!",
"Eu comandarei o forte! Cuidado com o canhão!",
"Basta acertar o que você mira!",
"Nós ganhamos! Eles vão escrever músicas sobre essa batalha, ou eu sou uma velha bruxa do mar! Poderíamos conquistar todo o arquipélago juntos! Ou todo o Caribe!",
"Claro que poderíamos. Mas pode fazer mais sentido conversar com ",
"Investigador",
" primeiro.",
"Ouvir você, ",
"! Você deveria ter vergonha de si mesmo, destruindo os sonhos de uma doce garota com sua lógica chata!",
"O tesouro sempre vem em primeiro lugar, minha querida. Depois, se você ainda quiser conquistar o Caribe, já estarei com você. Considere isso uma promessa.",
"Espero que o estudioso tenha tido tempo suficiente para examinar esses rabiscos. Duvido que possamos resistir a um segundo ataque.",
"Não tenho certeza se o governador tem mais navios de guerra.",
", o templo parece estar situado em algum lugar no interior. Vamos dar um passeio!",
"Certo, mas não queremos chamar atenção para nós mesmos. Devíamos deixar a tripulação aqui até verificarmos este templo com nossos próprios olhos.",
"Não acredito que conseguimos! É apenas uma questão de tempo até que estejamos rolando em ouro antigo!",
"Se houver algum ouro lá",
"Não diga isso! Não poderíamos ter chegado tão longe por nada!",
"Veremos.",
"Há três passagens aqui, e qualquer uma pode ser a correta. Para onde devemos ir?",
"Não sei. Esta poderia ser a armadilha ",
"Investigador",
" estava falando.",
"Então deveríamos nos separar. Cobriremos mais terreno dessa forma. Vou pegar a passagem da esquerda para mim e veremos quem encontra o tesouro primeiro!",
"Ei, espere...",
"Parece que podemos ir para #sisland_Khael Roa# agora!",
"Não tenho certeza se será tão fácil.",
"Talvez devêssemos ir em frente e revistar o templo enquanto ele lê aqueles rabiscos.",
"Não sem alguma ideia de para onde estamos indo! O próprio diabo poderia se perder naquele labirinto!",
"Faça do seu jeito, mas vou dar um passeio. Oh! Eu já vejo algo! Tenha em mente que encontrei primeiro!",
"O que?",
"Essa deve ser a alcova ",
"Investigador",
" estava falando. Mas onde está o tesouro?",
"Não sei. Mesmo que arrancássemos todo o ouro das paredes, não seria muito...",
"Não podemos perder muito mais tempo procurando ",
". Eles vão capturar a cidade!",
"Só quero ter certeza de que você não me afundará também, depois de cuidarmos da frota inglesa.",
"Agora, isso realmente dói ",
".",
"Brincando! Estou brincando. Boa sorte!",
"Bom Deus! O que é que foi isso?",
"Não sei!",
"Três mil demônios ",
"! Ninguém poderia sobreviver a isso! Meu tesouro! Poderíamos apenas tentar fazer parte disso? Só um pouquinho?",
"Não sei. Suponho que não seja o único tesouro do mundo.",
"Qual é a diferença? Oh, esta é uma perda tão amarga!",
"De alguma forma, tenho a sensação de que você não está tão desapontado quanto finge estar.",
"Eu não deveria voltar para lá. Preciso sair de #sRedmond# e rápido!",
"Essa foi difícil, não? Você ainda está inteiro?",
"Bem, acho que não vou morrer hoje, de qualquer maneira.",
"Fico feliz em ouvir isso - embora eu não tenha certeza se a Morte geralmente se importa com o que pessoas como nós pensam.",
"Vamos primavera ",
"Investigador",
" da prisão.",
", Uma coisa de cada vez. Vamos primeiro salvar o pobre velho",
"Qualquer coisa que você diga.",
"O que devemos fazer agora? Não poderemos encontrar o tesouro se não conseguirmos traduzir essa lenda. E temo que o velho...",
"Já nos opusemos ao #sGovernor# e à coroa inglesa. O que temos a perder se simplesmente capturarmos aquela cidade miserável e libertarmos Aurentius?",
"Não sabia que você tinha tendências suicidas. Mas se você está falando sério sobre isso, então vamos nos divertir um pouco!",
"Agora você está falando! E estou me sentindo um verdadeiro pirata. Eu atacarei o forte pelo mar, e você e seus homens poderão sitiar a cidade por terra. O que você diz?",
"Eu digo que criei um monstro ",
". Mas estou pronto quando você estiver!",
"Acalmar! O que aconteceu?",
"O que aconteceu? Disseram-me que você estava morto! Naveguei para #sGreenford# para descobrir o que realmente aconteceu. O dono da taverna me disse que não tinha visto você. Então um rapaz se aproximou de mim do nada e disse que sabia onde você estava. E eu caí nessa como um tolo!",
"Relaxar. Está tudo bem agora. O que aconteceu então?",
"Naveguei até aqui para #sIsla Muelle# com aquele cachorro mentiroso. Ele disse que nos encontraríamos com os piratas que o mantêm prisioneiro. Ele me levou para a selva - e depois fugiu quando fui atacado por dois amigos dele. Quando terminei com eles e voltei para a costa, ele já havia partido. E o meu navio também!",
"Você passou por tudo isso por mim? A fria e arrogante Danielle correu em meu resgate sem pensar duas vezes!",
"Continue falando e você estará resmungando em torno do meu sabre!",
"Eu terminei! Nem mais uma palavra, eu prometo! Então...as placas estão completamente perdidos para nós?",
"Você realmente acha que sou apenas uma garota tola, não é? Não, eu os guardei comigo.",
", minha querida, eu já te disse que você é a pirata mais inteligente que eu conheço?",
"Não. Pelo que me lembro, você ficou extasiado principalmente com minha 'língua afiada incomparável'. Agora me diga: como você chegou aqui?",
"Depois de capturar o navio que foi enviado para entregar o ídolo ao #sGovernor#, estabeleci um rumo para o nosso local de encontro. Mas enfrentei um mau tempo e fui levado ao mar como um marinheiro de água doce. Eu tinha certeza de que estava morto, mas aconteceu que fui levado à costa perto de #sisland_Douwesen#.",
"Sim. A fortuna favorece os tolos.",
"Fácil, agora! Passei por momentos difíceis. Quando recuperei o juízo, entrei cambaleando em #sDouwesen# e consegui um pequeno navio. Não muito tempo depois, acabei aqui. Você pode imaginar como fiquei surpreso ao ver meu antigo navio no porto de #sIsla Muelle#. Ela ainda estava sendo consertada depois daquela tempestade.",
"Incrível! A sorte favorece os tolos, mas nem você é tolo o suficiente para ter tanta sorte!",
"Bem, nesse caso... eu inventei tudo. Sim! Apenas uma história complicada para entretê-lo. De qualquer forma, aqui estou.",
"E aqui estou eu. E agora temos o ídolo. Deveríamos navegar juntos para #sisland_Oxbay# e conversar com Aurentius sobre a tradução dessa lenda.",
"Ah, não ousei sonhar que você diria isso! Navegar juntos - parece tão... fofo!",
", querido, cale a boca!",
"Sim, estou trabalhando para ele.",
"Seu demônio! E você armou uma emboscada para mim no portão da cidade?!",
"eu não...",
"Morrer!",
"Ainda está jogando duro para conseguir, não é? Justo...",
"Apenas fique quieto ",
", você poderia?",
"Parece engraçado para você? Eu gostaria de ver você rindo com uma pilha de gravetos aos seus pés!",
"Então ele estava falando sério? Achei que você o ajudou a carregar comida ou algo assim.",
"Sério, porém - o que você está fazendo aqui?",
"Estou tentando encontrar alguém, mas quanto mais perto chego, mais difíceis as coisas ficam para mim.",
"Também tenho tido muitos problemas.\nE tudo por causa de um rapaz. Ele também é capitão, por acaso. Atende pelo nome de ",
"Raoul Rheims",
"Raoul Rheims",
".",
"Você está falando sério? Procuramos o mesmo homem! Mas por que você está atrás dele?",
"Ouro, é claro! Um homem muito poderoso quer falar com aquele demônio e me prometeu uma boa quantia se eu o prender.",
"Eu vejo. Talvez pudéssemos procurá-lo juntos.",
"Sou totalmente a favor disso, mas vou te dizer desde já que não tenho ideia de onde ele está.",
"Estamos empatados, então - nem eu.",
"Bem, não podemos fazer nada pior juntos do que fizemos separados. E deve ser algum tipo de destino, nosso encontro assim.\nQuando iremos procurar nosso 'amigo' em comum?",
"Bem, eu tenho alguns negócios para resolver aqui...",
"Sem problemas. Na verdade, eu mesmo tenho algumas pontas soltas para resolver.",
"Certo. Vamos nos encontrar aqui em uma semana. O que você diz?",
"Perfeito. Vejo você então.",
"Boa sorte!",
"Você não se lembra de nada?",
"Minha cabeça está dividida ",
". Não me pressione. Por que você não explica o que está fazendo aqui?",
"Ei, se alguém deveria estar bravo, deveria ser eu! Pegar aquela adaga onde peguei não foi a coisa mais agradável que já me aconteceu!",
"Você merece isso! Eu sei que você está me caçando para o governador inglês. Vamos resolver isso agora. Desenhe sua lâmina!",
"Estabeleça-se, ",
". Você entendeu tudo errado. Eu não estou caçando você de jeito nenhum. Eu nem sabia disso ",
"Robert Christopher Silehard",
" queria você morto.",
"Não me venha com isso ",
"! Você sempre disse que faria qualquer coisa por dinheiro!",
"Oh vamos lá, ",
"! Eu estava brincando! Você esperava que eu fosse um canalha. Você gosta de canalhas! Eu não poderia te decepcionar.",
"O que você está falando?! Sempre te considerei um homem honesto!",
"Oh não! Durante todo esse tempo nos conhecíamos e estávamos sempre em desacordo.",
"Isso é verdade! Você estava sempre tentando arrancar os melhores empregos debaixo do meu nariz!",
"Mas quando foi que eu fiz alguma coisa com você? De onde estou, parece que sempre salvei sua pele!",
"Talvez. Mas você ainda está trabalhando para um homem que me quer morto!",
"Sim, eu estava, ",
". Recentemente... me aposentei. Mas ",
"Robert Christopher Silehard",
" ainda não sabe disso.",
"O quê, ele não te pagou o suficiente?",
"Dinheiro não é o problema. Não dessa vez. Acabei de decidir que não queria mais trabalhar para um homem como ele.",
"O que você está dizendo? Você é um #sgender# livre? Então me deixe em paz!",
"Certo! Vejo que você está tão teimoso como sempre. Boa sorte com os três cadáveres que você tem em mãos.",
"?!",
"O que mais você quer?",
"...",
"Você tem mais alguma coisa a dizer ou posso ir?",
"...Obrigado pela ajuda, ",
". Eu estaria morto se não fosse por você",
"Esqueça. Posso ir?",
"Espere, ",
"! O que você vai fazer agora?",
"Vou fazer algumas perguntas a um certo governador sujo.",
"Espere um minuto, sim? Você não pode ir lá sozinho. Isso é suicídio! Se ",
"Robert Christopher Silehard",
" suspeitar de alguma coisa, ele vai te matar só por segurança!",
"Obrigado, mas vou arriscar!",
"Não sem mim, você não vai!",
"Por que? Eu ficarei bem sozinho.",
"Em primeiro lugar, tenho minhas próprias perguntas para fazer a ele. E em segundo lugar - ",
"O que?",
"Conheço um bom lugar para lançar âncora em #sisland_Redmond#, onde ninguém estará esperando por nós.",
"Tudo bem, tudo bem. Vamos unir forças por enquanto.",
"Certo! Mas se você me enganar mais uma vez ",
", eu vou te matar, eu juro!",
"O que está acontecendo? Aqueles soldados estavam tentando nos matar!",
"Não sei, ",
", mas você deveria sair da cidade - é perigoso aqui.",
"Então... onde ele poderia guardar aquele papel? Vamos ver.",
"(Comece a pesquisar)",
"A cidade inteira está em pânico! Estão gritando que o porto está pegando fogo. Não podemos ir por esse caminho.",
"Eu tenho uma ideia. Diremos que há tropas francesas na cidade. Grite a plenos pulmões! Isso vai confundir os guardas!",
"Parece que vejo a figura de Nigel Blythe bem à frente. Interessante. Para onde ele poderia estar indo?",
"...",
"Hm...Talvez eu esteja errado, mas parece que um dos meus tripulantes - Artois Voysey - acabou de entrar na cidade.",
"...",
"O oficial Edgar Attwood acabou de deixar meu navio sem minha permissão.",
"...",
"Inferno! Alguém atirou em Artois! Devo levá-lo a uma taberna e encontrar um médico para ele!",
"...",
"Snorri: ...já estou neste buraco há duas semanas e ainda não há ouro! E você nos disse que o velho certamente pagará!",
"...",
"Billy: Ele vai pagar, com certeza vai. Mas reunir tanto ouro não é uma coisa tão rápida de se fazer.",
"...",
"Snorri: E se ele simplesmente não der a mínima para seu maldito filho?! E se em vez de ouro vier aqui um galeão cheio de espanhóis sedentos de sangue?!",
"...",
"Billy: Já chega! Você já viu um pai que abandonaria o filho numa situação como essa? Não se preocupe, o almirante pagará o resgate. Ele realmente não tem escolha.",
"Já ouvi o suficiente. Estes são os que eu preciso. (Mostre-lhes o sinal)",
"Agora vamos libertar o Padre Domingues!",
"As celas estão à direita. Vamos.",
"(Vejo um pequeno monte de pedras)",
"Aposto que há algo enterrado aqui. Eu vou cavar.",
"(Dez minutos depois)",
"Que espada linda! Mas há um nome gravado na lâmina...",
"PETER! ONDE VOCÊ ESTÁ INDO???",
"Hmm... Ele parece não me ouvir mais. É melhor eu segui-lo. Ele parece estar correndo para a loja.",
"(Uma tempestade repentina está rugindo)",
"Estranho. De onde veio esta tempestade de repente? É melhor eu sair deste lugar rapidamente.",
"(Outra tempestade repentina está rugindo)",
"Outra tempestade repentina? Eu não gosto disso.",
"(Os espanhóis detectam sua presença)",
"MOOOVEEEE!!!!! IRMãOS DA COSTA!!!",
"(Você vê o soldado do porto)",
"É ele de novo! Vamos pegá-lo!",
"(Barbossa conversando com sua equipe)",
"Senhores, chegou a hora! Nosso tormento está chegando ao fim! Durante dez anos fomos testados e experimentados. E cada homem aqui moveu sua coragem cem vezes e cem vezes novamente. Punidos éramos todos nós, desproporcionalmente ao nosso crime. Aqui está! O tesouro amaldiçoado do próprio Cortés. Cada pedaço que se extraviou, nós devolvemos. Economize para isso!",
"Talvez você seja imortal, mas ainda posso nocautear você, idiota! Agora, tenho que me juntar à minha tripulação para inverter a situação na meu navio.",
"Capitão ",
"Você é acusado de crimes contra a Coroa. Os referidos crimes são numerosos em quantidade e de natureza sinistra. Os mais flagrantes deles serão citados aqui: pirataria, contrabando, navegação sob cores falsas, incêndio criminoso, sequestro, saque, caça furtiva, banditismo, furto, depravação, depredação e ilegalidade geral. Por esses crimes, você é condenado a ser enforcado pelo pescoço até morrer. Que Deus tenha piedade de sua alma.",
"... parece que não! ...",
"Ah bem! ... eu mesmo terei que fazer a nobre ação.",
"[A moeda amaldiçoada no colar em volta do pescoço de Elizabeth chama-se #scursed_ship#]",
"Hmm... não foi um dos meus melhores dias!",
"Agora, há um navio que pode me dar alguma vantagem. Eu deveria ir e dar uma olhada mais de perto.",
"(Vejo que a areia foi movida)",
"Alguém enterrou algo aqui.",
"(Dois minutos depois)",
"UM MAPA! Aposto que o ouro está lá.",
"(Oito caixas de ouro estão na caverna)",
"Encontrei o ouro... mas apenas uma pequena parte do ouro roubado em Aguadilla. Onde está o resto?",
"(Alguns dias depois)",
"Chegou a hora de ver novamente meu informante. Esperemos que ele tenha encontrado alguma coisa.",
"(Dois dias depois na taberna)",
"Esta noite, tenho de ver o tesouro.",
"(Você ouve a conversa desses soldados)",
"Eles pertencem à Frota de Prata... Devo avisar Elting que eles instalaram um acampamento fortificado em frente ao forte.",
"(À noite, você ouve alguém andando)",
"Quem está aqui?",
"(Seu navio está levantando âncora)",
"Desgraçado! Ele vai pagar por isso.",
"(Algumas horas depois)",
"Esta muito quente! Preciso beber água rapidamente, caso contrário morrerei nos próximos dois dias.",
"(Você terminou de cavar um buraco na areia)",
"Caramba! Não há água na ilhota.",
"(O dia seguinte)",
"Sim!! está chovendo. Obrigado Deus! Finalmente ÁGUA!",
"(Muitos dias se passaram)",
"Eu deveria explorar a ilhota para saber se ninguém esteve aqui antes de mim e deixar alguma coisa.",
"(Você encontra uma adaga)",
"Excelente! Eu poderia usá-lo com um pedaço de pau para matar os peixes ao redor da ilhota.",
"(Você vê um navio se aproximando)",
"Venha aqui! Me ajude!!!",
"(Você vê uma bela jovem.)",
"[Pensa] que vou falar com ela. Ela parece sozinha.",
"(Você vê um galeão de guerra no porto.)",
"[Pensa] Que navio lindo! Ela tem muitos canhões. Eu poderia usá-la para a operação de desvio. Falarei sobre isso com meus companheiros esta noite. Agora, devo me juntar ao Governador em sua residência.",
"(Você ouve uma briga no jardim da residência.)",
"[Pensa] O quê?! Mas é a filha do Governador discutindo... Vou conversar com ela para entender o que está acontecendo.",
"(Conversando com todos)",
"Senhores, chegou a hora de explicar qual é o meu plano. No início da noite serão realizadas 4 operações. Eu e a minha tripulação iremos capturar um navio espanhol no porto. É o 'San Martin': um navio de guerra de 56 canhões. Duas razões sobre isso. Primeiro, quero evitar que o navio atire no forte durante o nosso ataque. A segunda é mais pessoal, perdi o 'Santiago' com o motim e vendo que preciso de um novo quando a missão for cumprida, também tenho este.",
"Acho que todo mundo sabe o que tem que fazer. Então boa sorte!",
"(Conversando com sua tripulação)",
"Lute contra os soldados, mas deixe o capitão comigo!",
"Estranho, tive a sensação de que -",
"-........",
"(Você vê as forças holandesas preparando o ataque)",
"[Pensa] Bom! Capitão Dierman e Elting estão prontos para atacar. Vamos informar o Capitão Queiroz.",
"Deixe-me ver. Por onde começar a procurar. Todo capitão tem um diário de bordo. Poderia estar na caixa ali...",
"Ufa! Sinto como se estivesse dormindo há uma semana, e a barba por fazer no queixo confirmou isso. Agora que me lavei e arrumei, devo procurar Hunter.",
"Finalmente uma boa noite de descanso. Agora, para encontrar o Sr. Bush.",
"Eu tenho a chave do diretor! Agora é sair daqui...",
"Nada que valha a pena ter no momento. Eu deveria passar algum tempo na taverna e tentar novamente mais tarde. Além disso, preciso ver se a loja pode me vender um mapa das águas de #sisland_Cuba#.",
"Parece que a tripulação caiu nessa. Agora, para pegar o navio antes que eles percebam que foram enganados",
"Os papéis do navio deveriam estar em algum lugar por aqui - aha, peguei! Navio 'Tonina' - que tipo de nome é esse, precisaremos mudá-lo! O capitão é - ou melhor, era - Alférez de Navío Esteban Rovapera.",
"Tanto para comprar um mapa de #sisland_Cuba#. Mas há um bem na janela. Terei que voltar quando escurecer",
"Tanto para comprar um mapa de #sisland_Cuba#. Mas há um bem na janela. E está escuro agora...",
"Espere um momento... é melhor que essa corda esteja bem amarrada!",
"Tentando espionar nosso momento íntimo, não é? Desapareça ou você conhecerá intimamente minha espada!",
"Boa segurança! A prisão fica bem ao lado do portão da cidade. Eu deveria levar o navio para a praia, então sair da prisão será muito mais fácil.",
"O que temos aqui? Parecem planos para uma invasão - #sRedmond#, a menos que eu erre o palpite. O almirante de #sisland_Antigua# provavelmente pagaria bem. Mas qual é o papel do #vilão# nisso, eu me pergunto?",
"Parece uma porta dos fundos para a residência do governador. Será que consigo abrir a porta?",
" Melhor tentar à noite, no entanto.",
"Isso deve servir bem - algum tipo de documento bom e longo, e a assinatura do governador no final dele!",
"Agora preciso resgatar minha tripulação do forte. Eu poderia simplesmente tentar entrar e sair lutando.\nComo alternativa, ouvi dizer que um falsificador mora no acampamento dos bucaneiros.\nEle provavelmente vai querer uma amostra da caligrafia do governador se for falsificar um documento de liberação para meu equipe. Então vou precisar de um.",
"O que temos aqui? Parecem planos para uma invasão de #sSantiago#, a menos que eu erre o palpite. Exatamente o que o governador queria!",
"Chega de #sproposer#. Mas talvez eu mesmo possa roubar o governador de #sDouwesen#. É claro que isso arruinaria as minhas relações com a Holanda e poderia significar que nunca mais poderei pôr os pés em #sDouwesen#.",
"Eu quero tentar de qualquer maneira.",
"Esqueça, não quero ter problemas com a Holanda.",
"Beber: a arte sutil de espalhar a maior parte do rum por todo o lugar, e não dentro de você. É por isso que ele está no chão e eu estou de pé.",
"Agora, para pegar seu uniforme. Mas ele é apenas um soldado comum, enquanto eu preciso do uniforme de oficial - de capitão, talvez. Um alfaiate deve ser capaz de fazer as alterações necessárias.",
"Hmm... a carta é realmente do Almirantado. A Espanha é agora aliada da Grã-Bretanha, o que faz de Don Julian nosso inimigo.",
"E eu dei a ele um dos navios de guerra mais poderosos destas águas...",
"Não serei capaz de mover aquela pedra sozinho. Parece que estou preso aqui...",
"O '",
" não está no porto! Capitão ",
" já devia estar impaciente e já partiu para #sHavana#.",
"Eu mesmo terei que navegar até lá e espero alcançá-lo.",
"Os sequestradores provavelmente estão naquela caverna com #senvoy#. Se eu atacar, eles podem matá-la, ou ela pode ser morta acidentalmente na luta.",
"Se eu jogar uma garrafa de éter ali, seu efeito deverá ser maior em um espaço tão confinado.",
"Terei que entrar com cuidado e tentar negociar sua libertação.",
"É melhor esperar que o ar clareie. Não quero me nocautear tão bem quanto os sequestradores, não é?",
"Perfeito! Todos os sequestradores estão inconscientes. #senvoy# também, então talvez eu precise me desculpar mais tarde.",
"Mas, por enquanto, preciso tirá-la daqui antes que os sequestradores acordem.",
"(Você vê dois soldados ingleses mortos)",
"Humm... Bandidos? Contrabandistas cometeram esse crime? Este local é mais perigoso do que eu pensava...",
"(Você vê um acampamento militar francês)",
"Caramba! Um acampamento de soldados franceses. O que eles estão fazendo aqui? Suponho que estejam preparando um ataque a #sConceicao#. Agora entendo porque vi aqueles soldados ingleses mortos na praia. Eles devem ter sido emboscados quando patrulhavam a costa. Eu não tenho escolha. Se quiser encontrar alguma coisa na mansão dos Bartolomeu, devo aproximar-me do acampamento e evitar os guardas.",
"Caramba! Um acampamento de soldados franceses. O que eles estão fazendo aqui? Suponho que estejam preparando um ataque a #sConceicao#. Agora entendo porque vi aqueles soldados ingleses mortos na praia. Eles devem ter sido emboscados quando patrulhavam a costa. Eu deveria voltar para a praia e esperar um momento melhor.",
"(Você olha para o baú)",
"Este deve ser o baú que Fernando encontrou no diário de Bartolomeu. Isso é estranho, há uma pequena chave dentro. Por que Fernando não aceitou. Ele deve ter pensado que era inútil... Talvez eu possa abrir algo com isso. Mas, aqui só vejo paredes e nenhuma porta... Será que a chave poderia abrir uma caixa enterrada na mansão?",
"Parece a parte principal do comboio prateado.",
"Espere até que todos estejam à vista antes de atacar.",
"A prata é nossa!",
"Agora, para levá-lo de volta ao navio",
"O que? Esse é o meu navio partindo - sob uma bandeira pirata! Maldito seja, pardal!",
"Pelo menos ele me deixou algo para navegar",
"A porta não está trancada mas não posso passar -",
"- estou condenado para sempre a andar por aqui?",
"Agora que cheguei ao porão, é melhor encontrar um lugar para me esconder.",
"Talvez atrás daquelas caixas ali.",
"Bem, isso é inconveniente. Agora preciso me livrar do corpo. Não posso arrastá-lo para o convés, é quase certo que serei visto.",
"Com um pouco de sorte, posso enfiá-lo em uma dessas caixas.",
"Pronto, isso servirá até que o navio chegue aonde quer que esteja indo. Agora, de volta ao esconderijo...",
"Cheguei muito cedo. Devo voltar aqui amanhã à noite.",
"Mas não depois! Se eu chegar tarde demais, o contrabandista irá embora sem mim e talvez eu nunca consiga sair desta ilha.",
"Oh garoto! Essa festa é booooooring! Preciso fugir, ou pelo menos encontrar algo interessante para fazer!",
"...",
"Ops! Desculpe! Que vergonha! Eu posso ser tão desajeitado às vezes! Sinto muito! Eu coloquei de volta, entendeu? Desculpe...",
"[PENSA:] Por que havia uma chave no vaso? Bem, ninguém vai notar!",
"Que perda de tempo! No momento em que a festa estava ficando mais animada, aquela maluca do batedor de tapete teve que aparecer!",
"Bem, meu negócio aqui está resolvido. É melhor eu voltar ao navio para me encontrar com os outros.",
"Bem, isso foi alguma coisa. Espero poder ajudar aquele jovem. Mas o mais importante é que tenho dinheiro para o rum. Agora eu realmente deveria voltar para o navio e conhecer os outros. Beatrice já deve estar preocupada!",
"...",
"Bom, eu posso ser o saco de pancadas, mas você, Chico, você é o bainha!",
"Eu deveria pegar o dinheiro e sair daqui. A pequena Bea já deve estar furiosa.",
};
