string DLG_TEXT[32] = {
"Capitão...(tosse)...Você deve me ajudar... Preciso chegar a #sRedmond#!",
"#sRedmond#? Por que?",
"Tenho uma mensagem para o Governador de Sua Majestade, Silehard. Mas não consegui sair desta ilha por causa da guerra...",
"Uma mensagem urgente, presumo?",
"Urgente, claro... (tosse)... preciso chegar a #sRedmond# o mais rápido possível. Estou mortalmente doente... se não chegar logo ao governador, temo que a mensagem nunca chegue.",
"Mortalmente doente? Com o que?",
"É uma febre do pântano, Deus me salve... Não sei por quanto tempo poderei continuar a combatê-la. Você vai me levar a bordo?",
"Vai contra o meu melhor julgamento embarcar com um homem nas suas condições, mas... tudo bem. Prometa manter distância e eu te levarei. Meu navio está atracado no porto de #sGreenford#. O nome dela é '",
".",
"Devemos zarpar imediatamente, capitão ",
"! Minha força... diminui a cada minuto que passa.",
"Não tenho certeza se quero carregar uma carga de febre do pântano em meu navio, se não importa para você. Você poderia simplesmente me confiar sua mensagem.",
"Economize seu fôlego e sua força. Estaremos lá em breve!",
"Não não! É... altamente secreto... confiado a mim. Devo entregá-lo sozinho!",
"Muito bem.",
"Não tenho certeza se você sobreviveria à viagem. Talvez devêssemos levá-lo primeiro a um médico.",
"Não! Os médicos locais apenas me cobririam de sanguessugas e me mandariam para o leito de morte! A mensagem... deve passar.",
"Eu entendo. Não posso dizer que gosto, mas entendo.",
"Capitão...",
"Aproxima-te. Escute-me. Estou morrendo... mas minha mensagem deve ser entregue... a qualquer custo.",
"Apenas me diga, rapidamente. Vou repassar ao governador e a mais ninguém. Você tem minha palavra!",
"Não... eu tenho uma carta. Pegue. Coloque-o nas mãos do governador. O governador e nenhum outro! Entender? Ninguém mais pode colocar os olhos nele!",
"Relaxar, ",
".",
"Tesouro... o tesouro espera lá...",
"Raoul Rheims",
", ele tinha tanta certeza disso! ...Mas não tem como...",
"Ele está delirando. Temo que o estejamos perdendo.",
"...Tempestade...tempestade. Nada que pudéssemos fazer a não ser ancorar no... porto pirata em #sisland_Quebradas Costillas#. Agora, a guerra...",
"Do que ele está falando?",
"A mensagem! Mensagem... para o governador. E eles esperam... em #sisland_Quebradas Costillas#. Sim! Oh Deus, tanto gol...",
"Ouro? Você quer dizer ouro? Faz sentido. Fala!",

};
