string DLG_TEXT[60] = {
"Bem-vindo à minha taverna, estranho. Meu nome é ",
". O que o traz ao meu humilde estabelecimento? Você precisa de um lugar para descansar?",
"Obrigado. Meu nome é ",
". Eu estou aqui a negócios.",
"Meu nome é ",
", e você pode poupar sua hospitalidade. Eu estou aqui a negócios.",
"Bem-vindo, #ssir#! O que você quer?",
"Preciso de algumas informações e acho que o estalajadeiro local geralmente é a pessoa certa para perguntar.",
"Estou procurando contratar alguns marinheiros para meu navio.",
"Aponte-me os clientes aqui que podem estar procurando emprego. Preciso aumentar minha equipe e não me importo se eles forem assassinos.",
"Você tem um quarto? Eu gostaria de ficar aqui por um tempo",
"Você tem uma cama grátis neste casebre?",
"Não tenho nenhum negócio com você agora. Adeus.",
"Isso é verdade. Eu ouço quase tudo. O que você quer saber?",
"Eu preciso de um emprego. Você não conhece nenhum garoto rico nesta ilha que tenha medo de viajar sozinho?",
"Não tenho perguntas no momento. Vamos falar sobre outra coisa.",
"Talvez eles tenham. Existem muitos rumores por aí.",
"Pressa. Sou um homem ocupado.",
"É um pouco tarde para encontrar bons marinheiros. Eles já estarão todos dormindo ou desmaiados. Volte de manhã - ou você pode passar a noite aqui na taverna.",
"Tudo bem. Você tem um quarto?",
"Não preciso de um quarto no momento. Vamos falar sobre outra coisa.",
"Eu tenho uma vaga. Quanto tempo você vai ficar?",
"Durante a noite.",
"Só até escurecer.",
"Certo. Serão 5 peças de ouro.",
"Tudo bem. Aqui você vai.",
"Infelizmente, acho que não posso pagar nada melhor do que uma noite no salão da taverna.",
"O que isso vem com uma equipe pessoal? Eu vou passar.",
"Vou pensar sobre isso.",
"Certo. Serão 5 peças de ouro.",
"Tudo bem. Aqui você vai.",
"Infelizmente, acho que não posso pagar nada melhor do que uma noite no salão da taverna.",
"Isso é demais. Eu vou ficar no salão da taverna",
"Vou pensar sobre isso.",
"Caros visitantes! Por favor, pare com essa indignação! Não me obrigue a chamar os guardas!",
"Tudo bem, tudo bem! Eu já fui!",
"Se for, eles preferem navegar com menos satélites, você sabe disso",
"Sim, esqueci. Tudo bem, voltarei mais tarde, quando tiver menos navios, ha-ha.",
"Eu não quero ajudar você. Você causou muitos problemas ao meu país",
"Basta olhar para este patriota. Bem adeus.",
"Suas mãos estão cobertas de sangue. Você não acha seriamente que alguém viajaria com você, não é?",
"Você está certo, todo mundo tem medo de mim! Ha-ha!",
"Você chegou bem na hora. Um comerciante aqui estava procurando a companhia certa para viajar. Você deveria falar com ele. Lá está ele, acabando de entrar na taverna.",
"Eu farei isso.",
"Não, não há ninguém assim no momento, Talvez da próxima vez.",
"Hmm, então vou esperar.",
"Com licença, mas você tem um primo chamado Sven?",
"O que é isso? Uma espécie de código secreto?",
"Não, mas uma vez tive um barbeiro chamado Dominique.",
"Bugrit! Bugrit! Mão e Camarão do Milênio.",
"Eu sou borracha, você é cola!",
"Ah, bem... deixa pra lá, ",
"Você poderia parar de falar bobagens e voltar ao assunto sério, por favor?",
"Bem, perto o suficiente. Como você parece ser um membro da Irmandade Secreta do Macaco de Três Cabeças, vou lhe mostrar o mapa das Grandes Riquezas Além da Imaginação. Se você estiver interessado, claro.",
"Claro que estou, irmão.",
"Já vi? Já vi? Está bem abaixo da cabeça do macaco, dizem. Infelizmente ninguém sabe onde a ilha está localizada, mas ela está em algum lugar. Eu posso sentir isso. A origem da Irmandade Secreta do Macaco de Três Cabeças reside aí.",
"Juntamente com as Grandes Riquezas Além da Imbecilidade, eu acho?",
"Imaginação! Grandes riquezas além da imaginação. De qualquer forma - se você descobrir mais, me avise e poderemos iniciar uma expedição.",
"Parece, er... interessante. Você por acaso conhece alguém - outro irmão - que possa fornecer mais detalhes?",
"Você poderia tentar procurar o Grão-Mestre da Irmandade, se estiver pronto para as Três Provações. Não me pergunte quem é o Grão-Mestre. Mesmo se eu soubesse que não te contaria",
};
