string DLG_TEXT[28] = {
"Peço-lhe que saia da minha casa neste instante. Estou ocupado.",
"...",
"Então, Governador ",
"Robert Christopher Silehard",
" me envia seu #sgender# da mão direita. O que ele quer de mim, #sboy#?",
"Quem disse que trabalho para ele?",
"O que te faz pensar que estou aqui por ordem do governador?",
"Peço perdão, mas pareço o idiota da aldeia? No momento em que descobri que alguém estava me procurando, fiz perguntas\nVocê me olharia nos olhos e negaria que trabalhou para ele nos últimos meses?",
"Ok, digamos que você esteja certo e o governador me enviou. Que diferença isso faz? Você se recusaria a falar com um representante do governador?",
"Olha, já estou farto deste gato e rato. Você vai conversar comigo ou prefere escolher qual das suas pernas quer manter?",
"Capitão, gostaria de saber se sabe com quem está falando. Você deve confiar em mim quando digo que se eu não quisesse falar com você, você não estaria aqui.",
"Ah, não há necessidade de violência física, #sboy#. Vou falar com você porque estou curioso: o que aquela velha raposa, o governador, quer de mim?",
"Certo. Preciso saber onde posso encontrar um cavalheiro chamado ",
"Raoul Rheims",
". Eu sei que ele está escondido em algum lugar desta ilha.",
"Suas informações estão desatualizadas, jovem #sgender#. ",
"Raoul Rheims",
" realmente passei alguns dias aqui. Praticamente nunca saiu de casa\nMas ele já zarpou novamente e manteve seu destino em segredo até de mim. Claramente, ele estava preocupado com alguma coisa, mas eu não sabia dizer o quê.",
"Ele tem uma casa aqui? Onde posso encontrá-lo?",
"Tem barraco aqui na ilha, não é? Cadê?",
"Só um momento, #sboy#. Você pode muito bem ser um enviado do governador inglês, mas isso não lhe dá permissão para invadir a casa de outro homem e vasculhar seus pertences. Fui muito claro?",
"Peço-lhe que abra uma exceção para mim, senhor. Devo descobrir onde ",
"Raoul Rheims",
" estava navegando, e logo!",
"Ah, venha agora. Você é um contrabandista, conhecido em todo o arquipélago pela sua falta de princípios. Você vai me contar sobre a lei?",
"Posso ver que você não escuta a razão. Se não conseguir convencê-lo a ficar longe daquela casa, simplesmente ordenarei aos meus homens que a vigiem e atirem assim que avistarem. Tenho certeza de que até você consegue entender uma pista de uma bala de mosquete. Agora vá!",
"Adeus.",
"Isso não acabou!",

};
