string DLG_TEXT[24] = {
"O que você quer? Prefiro não falar com estranhos.",
"Eu posso ver isso. Se você quer que eu te deixe em paz - diga-me para onde Blythe foi?",
"Nigel?",
"Sim. Não finja que não o conhece.",
"E o que isso tem a ver com alguma coisa? Suma daqui!",
"Esse rapaz está trabalhando para mim...",
"Trabalhando para você? Ele não disse nada sobre trabalhar para ninguém.",
"Tudo bem, ele estava trabalhando para mim. Até que um dia ele desapareceu com um dos meus navios.",
"Heh heh. Que surpresa infeliz...",
"Ei, não vejo nada de engraçado nisso! E rir pode ser prejudicial à saúde!",
"Tudo bem, tudo bem... Alguns podem pagar muito para manter em segredo um segredo tão embaraçoso. '#spronoun1# navio foi roubado debaixo do nariz de #spronoun2#?' Meu Deus, um segredo como esse vale nada menos que cinco mil ouro, eu acho.",
"Que tal eu colocar alguns gramas de chumbo na sua cabeça?",
"Não tente me ameaçar. Todo mundo sabe que você é do tipo gentil e bondoso que ajuda viúvas e aleijados. Heh heh!",
"Tudo bem, tudo bem, eu concordo.",
"Tudo tem seu fim, você não sabe disso?",
"Ótimo. Agora fale.",
"Isso mesmo, mas...",
"Sem 'mas', seu porco! Já estou sem paciência!",
"Tudo bem, tudo bem. Estou falando agora. Então, você disse - Nigel. Ele foi para #sisland_Quebradas Costillas# para buscar seus ex-companheiros de tripulação.",
"Pelo que?",
"Ele falou sobre seu navio perdido preso em um banco de areia em algum lugar, mas eu não pedi detalhes.",
"Eu entendi. Até a próxima.",
"Não estou com vontade de conversar com um mollycoddle de pulso fraco.",
"E quem você acha que está chamando de 'mollycoddle de pulso fraco'?",

};
