string DLG_TEXT[57] = {
"Seu avô matou meu bisavô. Prepare-se para morrer.",
"Eu nem sei quem foi meu pai, muito menos meu avô, então o que quer que ele tenha feito, eu não tive nada a ver com isso. Eu irei agora. Se estiver tudo bem para você",
"Meu nome, na sua língua, é ",
". Quem é você?",
"Eu sou ",
"Por quê você está aqui?",
"Er... porque seus guerreiros me atacaram e me trouxeram aqui?",
"Não finja ser um tolo! Embora você não tenha visto nosso povo, nosso povo está observando você. Você busca algo. O que?",
"Nada em particular. Estou só dando uma olhada.",
"Estou procurando uma caveira de cristal âmbar. Disseram-me que uma tribo de caribenhos nesta ilha pode tê-lo. Se for você, você estaria disposto a negociar por isso?",
"Repito: não finja ser um tolo e não me confunda com um! Desta vez, diga a verdade ou morra! Por quê você está aqui?",
"Ah, o crânio antigo. É nosso, mas não o temos.\nQuando nossos ancestrais viveram na grande terra do õeste, eles tiraram o crânio de seus inimigos. Quando eles se mudaram para essas ilhas, eles se estabeleceram em Madinina.\nQuando seu povo expulsou o meu de Madinina, fomos forçados a nos mudar para cá. Não pudemos trazer a caveira ou seu pessoal poderia tê-la encontrado. Então nós escondemos isso.",
"Madina? Eu não conheço esse nome. Cadê?",
"Na sua língua, Madinina significa 'Terra das Flores'. A partir daqui é para o sul. É uma ilha gêmea.",
"Ilha gêmea? Isso seria #sisland_Falaise de Fleur#, que fica ao sul daqui.",
" Mas isso é #snationdesc#. Eu não sou #snationdesc#!",
"Vocês são do outro lado do mar, assim como aqueles que nos expulsaram de Madinina.",
"E para nós, você se parece com o Arawak -",
"Você ousa comparar os Caribenhos aos Arawak! Você vai morrer por tal insulto!",
"Não, de jeito nenhum. Para nós, você se parece com Arawak, mas não é Arawak. Para você eu apareço #snationdesc# mas não sou #snationdesc#.",
"Ah, então seu povo tem tribos diferentes, assim como nosso povo tem tribos diferentes.\n",
"Você conhece Madinina? Então você nos ajudará a recuperar o que é nosso.\nVocê viajará para a ilha. ",
" irá com você. Ele irá guiá-lo até o esconderijo da caveira. Você o trará de volta para nós.\n",
"Manteremos um de seus companheiros como refém. Se você nos devolver o crânio dentro de dois meses, seu companheiro será devolvido ileso.",
"As flechas que atingiram você carregam um veneno poderoso, mas lento. Se a morte não te encontrar antes, o veneno te matará em dois meses. Traga a caveira para nós antes disso e nós lhe daremos o antídoto.",
" E se você nos devolver a caveira, receberá uma recompensa.",
"Não tenho muita escolha, não é? Se o seu povo puder me levar de volta ao local onde me encontraram, retornarei ao meu navio e navegarei para #sisland_Falaise de Fleur# o mais rápido possível.",
" não está com você? Onde ele está?",
" tentei roubar a caveira de cristal de mim e fui forçado a matá-lo para me defender.",
" morreu lutando bravamente para defender o crânio, e a mim, do nosso inimigo. Em sua memória, eu trouxe a caveira de cristal para você.",
"Você mente! ",
" sabia onde o crânio estava escondido. Ele teria encontrado. Talvez tenha sido você quem roubou dele!\nOu talvez ele tenha confiado em você para carregar a caveira. Ele só atacaria você se pensasse que você traiu essa confiança.\nDe qualquer forma, você morre agora!",
"Isso combina comigo. Eu posso matar você, pegue ",
"meu oficial",
"o antídoto",
" e mantenha o crânio.",
"A perda de ",
" é uma tragédia para o nosso povo. Mas você mostra respeito e suas palavras honram. Se você me der a caveira de cristal, eu irei ",
"solte seu companheiro.",
"te dou o antídoto.",
"Certamente. Aqui está sua caveira de cristal.",
"Não há acordo. eu vou levar ",
" e eu ficarei com a caveira para mim.",
"Você se mostrou uma #sperson# de honra. Você pode agora ter ",
"seu companheiro de volta",
"Obrigado, ",
"Há mais. Quando você concordou em nos trazer a caveira de cristal, eu prometi uma recompensa. Espere aqui. Eu vou buscá-lo.",
"Muito bem, vou esperar.",
"Verme mentiroso! Meus guerreiros agora vão esmagar você!",
"Eles não têm botas grandes o suficiente.",
"Bem-vindo a casa, ",
"! Como foi a busca pela caveira de cristal?",
" fala bem de você! Se você me der a caveira de cristal, ficarei feliz em fazê-lo. ",
"Você demonstrou paciência ao esperar. Agora você receberá sua recompensa.",
"Tenho certeza que valerá a pena esperar.",
"Esta machadinha está em nossa tribo há muitos anos. Foi usado pelo nosso grande chefe Águia Ambulante quando conduziu o nosso povo à vitória contra os primeiros invasores brancos de Madinina. Poucos rostos brancos o viram e até hoje nenhum sobreviveu.\nMas você devolveu nossa relíquia mais sagrada. A honra exige um grande presente em troca. E então eu apresento esta machadinha para você. Leve-o com honra.",
"Obrigado! É realmente uma honra receber uma arma tão boa. E agora devo ir embora. Adeus.",
}
