string DLG_TEXT[185] = {
". O que é, ",
"?",
"Posso te ajudar, ",
"?",
"Esta é sua primeira vez em nossa cidade, ",
"? Eu não te vi antes",
"Eu sou ",
", capitão e proprietário do navio'",
".' Eu tenho algumas perguntas se você tiver um momento.",
"Meu nome é ",
". Gostaria de lhe fazer algumas perguntas.",
"Você pode me chamar de capitão ",
". Eu só gostaria de algumas informações.",
"Olá, capitão ",
". O que traz você à nossa colônia?",
"Ah, capitão ",
". ",
", é você de novo. Espero que sua jornada tenha sido agradável. O que há de novo?",
"Olá, ",
". Como posso ajudá-lo?",
"Perdi alguma coisa enquanto estive fora?",
"Aconteceu alguma coisa interessante enquanto eu estive fora?",
"Que histórias os velhos cães-do-mar estão trocando por causa do rum hoje em dia?",
"Qual é a agitação nas tabernas?",
"Procuro fofocas, boatos, histórias fantásticas...qualquer coisa que eu não saiba pode ser útil.",
"Me conte algumas de suas fofocas mais recentes, amigo. Pode haver aventura ou dinheiro até mesmo no menor detalhe.",
"Ainda não consigo encontrar...",
"É impossível encontrar alguma coisa neste labirinto! Onde é...",
"Estou tão perdido quanto um navegador bêbado. De novo!",
"Você parece um morador local. Diga-me onde posso encontrar...",
"Por favor me diga como chegar a...",
"Tive um dia péssimo, então você nos salvará da dor se apenas me disser como encontrar...",
"Gostaria da sua opinião sobre um cidadão local.",
"Preciso saber o que você pode me contar sobre alguém que mora aqui na cidade.",
"O que você pode me contar sobre...",
"Conte-me tudo o que puder sobre um sujeito...",
"Espero que você possa me contar algo sobre uma pessoa que talvez conheça.",
"Este lugar não é muito grande  aposto que você conhece todo mundo que mora aqui. Vamos conversar.",
"Conte-me sobre #sCartagena#.",
"O que você pode me dizer sobre esse lugar esquecido por Deus?",
"Gostaria de saber mais sobre esta bela colônia.",
"Qual é a história desta cidade e arredores?",
"Você sabe alguma coisa interessante sobre #sCartagena#?",
"...",
"Desculpe. Pensei que você fosse outra pessoa.",
"Estou apenas de passagem. Então fique de lado ou seja empurrado.",
"O que você gostaria de saber, ",
"?",
"O que lhe interessa, capitão?",
"O que você quer de mim?",
"Cidades como esta estão sempre nadando em fofocas. Dê-me os destaques.",
"Aconteceu alguma coisa interessante por aqui ultimamente?",
"Só quero saber o que está acontecendo na vizinhança. Alguém enganou um amigo? Alguém foi morto? O estalajadeiro é mesmo uma mulher? Você me entende.",
"Como posso chegar a...",
"Você pode me ajudar a me orientar aqui na cidade?",
"Onde posso encontrar...",
"Você pode me falar sobre alguém em quem estou interessado?",
"Gostaria de algumas informações sobre um colega local. Você pode ajudar?",
"Estou me perguntando o que as pessoas na cidade têm a dizer sobre uma determinada pessoa...",
"O que você pode me dizer sobre #sCartagena#?",
"Gostaria de conhecer a história da sua cidade.",
"Gostaria de obter algumas informações sobre esta colônia.",
"Estou apenas andando aqui. Vejo você mais tarde.",
"Obrigado. Tem mais uma coisa...",
"Foi bom conversar com você. Contanto!",
"O que mais lhe interessa, capitão ",
"?",
"Vamos ouvir isso, ",
".",
"Estou ouvindo, ",
".",
"Qual é o assunto da cidade hoje em dia?",
"Que histórias os velhos cães-do-mar estão trocando por causa do rum hoje em dia?",
"Já faz muito tempo que não ponho os pés nestas praias. O que eu perdi?",
"Você poderia me dar algumas instruções?",
"Fiquei completamente perdido nestas ruas.",
"É minha primeira vez nesta cidade e gostaria de algumas orientações.",
"Gostaria da sua opinião sobre um cidadão local.",
"Preciso saber o que você pode me contar sobre alguém que mora aqui na cidade.",
"Você poderia me dar algumas informações sobre os habitantes locais?",
"Conte-me sobre #sCartagena#.",
"O que você pode me dizer sobre esta colônia?",
"Gostaria de saber algo sobre #sCartagena#.",
"Acabei de perceber que preciso estar em algum lugar. Adeus.",
"Quem é que queres dizer,",
"?",
"Você está perguntando sobre alguém específico?",
"Sobre quem exatamente você quer saber?",
"Quero dizer, o governador.",
"Estou interessado no dono da taberna.",
"O dono do estaleiro.",
"Estou falando do comerciante local.",
"Ninguém. Deixa para lá.",
"Ele faz o seu trabalho, ele faz o seu trabalho.",
"Eu vejo. Eu tenho outra pergunta para você.",
"Obrigado tchau tchau.",
"Bem, o que devo dizer? Ele é um cara amigável, mas isso se chama requisito do trabalho, não é?",
"Eu vejo. Eu tenho outra pergunta para você.",
"Obrigado tchau tchau.",
"É certamente o melhor construtor naval de todo o arquipélago. Todos os navios militares espanhóis construídos no Caribe são construídos sob sua supervisão.",
"Eu vejo. Eu tenho outra pergunta para você.",
"Obrigado tchau tchau.",
"Bem.. Ele veio há alguns anos com a armada espanhola para #sCartagena#, o que não foi barato, eu acho. Ele já era um rico lojista na Espanha, e a maioria das pessoas pensa que ele quer aumentar sua fortuna aqui no Caribe.",
"Eu vejo. Eu tenho outra pergunta para você.",
"Obrigado tchau tchau.",
"Onde você está indo, ",
"?",
"Não é um problema, capitão. Onde você precisa estar?",
"Fico feliz em orientá-lo ",
". Mas para onde você quer ir?",
"Como posso chegar à taberna?",
"Onde fica o estaleiro?",
"Onde posso vender os produtos que trouxe comigo?",
"Hum. Você sabia que #sCartagena# tem duas tabernas? Vou levá-lo até a taverna para onde a maioria dos marinheiros está indo. Se atracarem aqui, será mais fácil. Ao entrar na cidade, basta ir até a primeira praça principal, onde fica a grande residência. A taberna é a casa grande com varanda, à esquerda. Caso tenha interesse, o outro fica no centro, na esquina ao lado da loja.",
"Certo. Obrigado pelo seu tempo.",
"Onde fica o estaleiro?",
"Onde posso conseguir um preço decente pelos produtos finos que trouxe para a cidade?",
"Dirija-se ao centro da cidade #sCartagena#, isto é, vire à esquerda na praça principal da residência e desça as escadas. Se você chegou ao centro, o estaleiro é o casarão à esquerda. A porta principal costuma estar trancada, pois é a entrada dos almirantes da marinha espanhola. Mas a porta lateral deveria estar aberta para capitães particulares. ",
"Eu vejo. E a taberna?",
"Onde posso conseguir um preço decente pelos produtos finos que trouxe para a cidade?",
"Eu acho que isso é tudo. Obrigado pela ajuda.",
"A loja fica no centro. Você pega o caminho certo e segue até o cruzamento. Vire à direita e você deverá ficar em frente à loja. ",
"Onde posso encontrar o estaleiro local?",
"Como faço para chegar à taberna?",
"Eu vejo. Obrigado pela informação.",
"Não sei por que você estaria interessado, mas por que não?",
"No que exatamente você está interessado ",
"?",
"Claro, ",
". Felizmente, é uma história bastante curta.",
"Estou interessado na história da colônia...",
"Conte-me sobre a colônia.",
"Há alguma coisa por aqui fora da cidade?",
"Tenho mais algumas perguntas para você, se não se importa.",
"#sCartagena# é uma das ou talvez a maior cidade de todo o Caribe. Foi fundada em 1533 como uma das primeiras cidades espanholas no continente. Nossa cidade tem um rápido crescimento econômico.",
"Obrigado. Deixe-me fazer mais algumas perguntas.",
"Sabe, eu realmente pensei que seria mais interessante. Deixe-me perguntar outra coisa.",
"Isso é tudo que preciso. Obrigado.",
"Obrigado pelo seu tempo. Até a próxima.",
"Na verdade. Além de algumas plantações, não há muito além de selva impenetrável por aí.",
"O que mais você pode me contar sobre a colônia?",
"O que mais você pode me dizer?",
"#sCartagena# é um porto na rota da armada espanhola, que comercializa armas, cavalos e ferramentas da Europa em troca de ouro e prata.",
"Eu vejo. O que mais?",
"Não. Você encontrará algumas plantações e casas na selva, ou talvez um assentamento nativo. Mas não há muito mais a uma curta distância.",
"Nesse caso, talvez você possa me contar mais sobre a colônia.",
"Entendi. Deixe-me perguntar outra coisa.",
"Você conhece um contramestre chamado Fred Bob?",
"O que você pode me dizer sobre o capitão do porto?",
"Ah, Fred Bob? Ele não é um amotinado, isso eu lhe garanto! Ele é um bom marinheiro e um homem forte para ter ao seu lado quando você está em menor número. Pena pela sua prisão. Todos esperamos que o governador o liberte, porque ninguém, exceto aquele pomposo primeiro oficial, acredita que ele é culpado.",
"Interessante. Ah, eu tenho outra pergunta para você.",
"Muito obrigado, adeus.",
"Não sei como ele faz isso, mas o nosso capitão do porto faz questão de conhecer todos os marinheiros do arquipélago.",
"Eu vejo. Mais uma pergunta, se não se importa, por favor?",
"Obrigado pelo seu tempo. Tchau.",
"Fred Bob? O contramestre? Ele é muito difícil de entender, mas meu irmão o conhece bem. Ele não é um amotinado. Esse oficial entendeu tudo errado. Todos esperamos que o governador o liberte. Ele pertence a um navio, não a uma paliçada.",
"Bom homem, excelente marinheiro. Não acredito nem por um minuto que ele ameaçou um motim.",
"Ehm... eu esqueci quem eu ia perguntar. Apenas me dê um segundo e isso voltará para mim...",
"Quem dirige a ferraria aqui?",
"Isso seria #sname#. #sfullname#. Ele começou como escravo trabalhando no fole, pelo que ouvi. Então o velho ferreiro fez dele um aprendiz e deixou-o fazer pequenas coisas. Pouco antes de morrer, ele concedeu a #sname# sua liberdade e deixou a ferraria para ele.",
"Isso é uma história e tanto. Agora eu gostaria de saber outra coisa.",
"Ele parece ter muita experiência. Terei que ver o que ele consegue fazer com minhas armas!",
"Minha melhor espada favorita do mundo aqui ficou um pouco chata ultimamente. A quem posso confiar isso?",
"Nosso ferreiro espanhol fica no centro, na rua certa. É a casa com a bandeira espanhola à esquerda.",
"Perfeito! Parece que finalmente posso polir minha espada desgastada!",
"Onde fica o estaleiro?",
"Onde posso conseguir um preço decente pelos produtos finos que trouxe para a cidade?",
"A quem posso confiar minha espada? Sua borda antes fina ficou um pouco embotada.",
" Temos uma população de ",
" cidadãos.",
"Procuro um Mosteiro.",
"Temos três Mosteiros aqui em #sCartagena#. Em qual você está interessado?",
"Uhh...ehrr.. quais estão aí?",
"Existe o Claustro, o Claustro Novo e a Abadia.",
"Por favor, conte-me mais sobre eles.",
"No Claustro existe uma ordem de monges muito silenciosa. Não tenho certeza sobre o Novo Claustro, mas ouvi dizer que a Abadia é para freiras.",
"Sim! É uma freira que estou procurando. Como chego à Abadia?",
"Do Porto vire à esquerda. Na próxima parte da cidade, vire à direita.",
"OK. Porto - esquerda - direita e lá está a Abadia.",
"Hum, não exatamente. Primeiro você encontrará o Claustro...",
"Sim..?",
"A Abadia encontra-se além do Claustro. Você tem que passar por isso de alguma forma",
"No Claustro existe uma ordem de monges muito silenciosa. A Abadia, ouvi dizer, é para freiras, mas só pode ser acessada em 'WoodesRogers'. O Claustro Novo possui uma Biblioteca muito famosa.",
"Sim! É a Biblioteca que estou procurando. Como chego ao Claustro Novo?",
"Do Porto vire à esquerda. Na próxima parte da cidade em frente. Passe pela Residência e você encontrará o portão.",
};
