string DLG_TEXT[172] = {
"Eu te dou as boas-vindas ",
". Meu nome é ",
". Qual o seu nome?",
"Olá, ",
"! Eu sou ",
". Posso saber o seu nome?",
"Sim, ",
". O que você quer? A propósito, meu nome é ",
". E o seu?",
"Eu sou ",
", um capitão e proprietário do navio '",
".",
"Meu nome é ",
".",
"Você pode me chamar de capitão ",
".",
"Olá. Um oficial deixou meu navio. O nome dele é",
"Nigel Blythe",
"Nigel Blythe",
". Sua cidade é pequena o suficiente para que talvez você já tenha ouvido algo sobre ele.",
", um capitão de '",
".",
"Ah, é o capitão ",
" #syourself#! O que você quer descobrir desta vez?",
"Olá, ",
". Você quer alguma coisa?",
"Que tipo de histórias de galo e touro você ouviu aqui na taverna ultimamente?",
"O que há de novo neste canto do mundo?",
"O que está acontecendo por aqui?",
"Você poderia, por favor, me dizer como chegar a um lugar?",
"Não consigo encontrar o caminho para um lugar...",
"Você poderia me dizer o caminho...?",
"Gostaria de saber o que as pessoas dizem sobre uma pessoa em particular.",
"Você pode me dizer o que as pessoas estão dizendo sobre alguém em particular?",
"Gostaria de obter algumas informações sobre os habitantes locais.",
"Conte-me sobre sua colônia.",
"O que você sabe sobre #sCharlestown#?",
"Gostaria de obter algumas informações sobre #sCharlestown#.",
"Bem, não há nada que eu precise no momento. Até a próxima!",
"Sim, acho que ouvi dizer que seu amigo estava em nossa taverna",
"Obrigado.",
"Estou feliz em conhecê-lo, capitão ",
".",
"Prazer em conhecê-lo, ",
".",
"Prazer em conhecê-lo, capitão ",
". Suponho que você não esteja apenas curioso sobre meu nome...",
"Estou feliz em conhecê-lo, capitão ",
".",
"Prazer em conhecê-lo, ",
".",
"Prazer em conhecê-lo, capitão ",
". Suponho que você não esteja apenas curioso sobre meu nome...",
"Que tipo de histórias de cachorros-marinhos você ouviu na taverna local ultimamente?",
"O que há de novo aqui neste canto do mundo?",
"Como vão as coisas por aqui?",
"Você poderia me dizer o caminho para um lugar específico?",
"Não consigo encontrar o caminho para um lugar...",
"Você poderia me dizer o caminho...?",
"Você sabe o que as pessoas estão dizendo sobre essa pessoa em particular?",
"Você poderia me dizer alguma coisa sobre um homem?",
"Gostaria de obter algumas informações sobre os habitantes locais.",
"Conte-me sobre sua colônia.",
"O que você sabe sobre #sCharlestown#?",
"Gostaria de obter algumas informações sobre #sCharlestown#.",
"Estou apenas curtindo os pontos turísticos da cidade. Vê você.",
"Entendo.... Há mais uma coisa.",
"Obrigado pela informação. Até a próxima.",
"É sempre bom ter uma companhia tão agradável ",
". Diga-me.",
"Sim, ",
"?",
"Você gosta de conversar, capitão, não é? Bem, eu também...",
"É sempre bom ter uma companhia tão agradável ",
". Eu estou ouvindo você.",
"Sim, ",
"?",
"Você gosta de conversar, capitão, não é? Bem, eu também...",
"Que tipo de histórias de cachorros-marinhos você ouviu na taverna local ultimamente?",
"O que há de novo aqui neste canto do mundo?",
"Como vão as coisas por aqui?",
"Você poderia me dizer o caminho para um lugar específico?",
"Não consigo encontrar o caminho para um lugar...",
"Você poderia me dizer o caminho...?",
"Você sabe o que as pessoas dizem sobre essa pessoa em particular?",
"Eu gostaria de saber o que as pessoas estão dizendo sobre uma pessoa.",
"Gostaria de obter algumas informações sobre os habitantes locais.",
"Conte-me sobre sua colônia.",
"O que você sabe sobre #sCharlestown#?",
"Gostaria de obter algumas informações sobre #sCharlestown#.",
"Não importa... mudei de ideia. Adeus.",
"Quem atraiu seu interesse, ",
"?",
"A quem você quer dizer, capitão?",
"Há muitas pessoas em #sCharlestown#. Sobre quem exatamente você quer saber?",
"Quero saber sobre o governador da colônia.",
"Estou interessado no taverneiro ",
"Peter Manchester",
"Peter Manchester",
".",
"Conte-me sobre o dono do estaleiro, ",
"Hugh Chadman",
"Hugh Chadman",
".",
"Quero saber sobre o comerciante chamado ",
"James Griffith",
"James Griffith",
".",
"Eu mudei de ideia. Esqueça isso.",
"Bem, #sCharlestown# tem um governador militar, ele está aqui para colocar algumas coisas em ordem, o nome dele é ",
"Thomas Modiford",
". Ele não gosta de pessoas que não o ouvem com atenção suficiente e tem um temperamento muito explosivo, então fique atento.",
"Eu vejo. Eu tenho uma pergunta.",
"Obrigado, adeus.",
"Dizem que você pode contar com ele. Por outro lado, ouvi dizer que ele não gosta de correr riscos desnecessários e sempre faz seus negócios com prudência. Eu também não acho que ele esteja envolvido em nenhum negócio obscuro.",
"Eu vejo. Eu tenho uma pergunta.",
"Obrigado, adeus.",
"Um ótimo rapaz. Sempre pronto para ajudar. Devo dizer que para um remanso como este, ele é um ótimo construtor naval.",
"Eu vejo. Eu tenho uma pergunta.",
"Obrigado, adeus.",
"Ele não tem muito sucesso. Ele negocia e negocia, mas sempre parece acabar mais pobre. Muitas vezes os itens estão fora de estoque. E ele está sempre endividado.",
"Eu vejo. Eu tenho uma pergunta.",
"Obrigado, adeus.",
"Onde você quer chegar ",
"?",
"Tenho esta cidade na ponta dos dedos, capitão, então me diga onde você quer chegar.",
"Você pode contar comigo, ",
".",
"Como posso chegar à taberna?",
"Onde fica o estaleiro?",
"Onde posso vender os produtos finos que trouxe comigo?",
"Nossa taverna é a segunda casa à esquerda da ponte de desembarque. Espero que você saiba ler inglês. Há um sinal ali.",
"Eu vejo. Obrigado. Adeus.",
"E onde fica o estaleiro?",
"Onde posso vender os produtos finos que trouxe comigo?",
"Você verá o estaleiro se olhar direito. O prédio do outro lado do rio é isso. Você deve passar pela pequena ponte de madeira para chegar lá.",
"Eu vejo. E como posso chegar à taberna?",
"Onde posso vender os produtos que trouxe comigo?",
"Obrigado pela ajuda. Isso é tudo que preciso saber.",
"Ah, isso é fácil ",
"! vire à esquerda após a ponte de desembarque e depois à direita no primeiro cruzamento. Agora você deve ficar na frente da loja.",
"Onde fica o estaleiro nesta cidade?",
"Como posso chegar à taberna?",
"Eu vejo. Isso é tudo que preciso saber.",
"Para ser sincero, não sei muito sobre isso, mas posso lhe contar o que sei.",
"O que você quer saber sobre nossa colônia?",
"Com prazer. O que exatamente você quer saber?",
"Gostaria de saber a história da colônia...",
"Existe mais alguma coisa além da cidade nesta ilha?",
"Você sabe alguma coisa sobre o forte que protege a cidade?",
"Vamos falar sobre outra coisa.",
"Nossa colônia foi construída há cerca de 40 anos. A ilha é bem pequena, mas tem um solo muito fértil e há algumas baías convenientes.\nNovas seções estão sendo desenvolvidas e o comércio aumentou. O primeiro assentamento foi um pequeno posto avançado do outro lado da ilha, um lugar difícil que, pelo que sei, ainda pode estar lá. Mais tarde, um assentamento maior foi fundado aqui, que eventualmente se tornou #sCharlestown#.",
"Continuar...",
"Isso está claro. Vamos falar sobre outra coisa ",
"Então os bucaneiros tornaram-se visitantes frequentes aqui, então construíram o forte para proteger a cidade.",
"Eu vejo. Vamos encerrar nossa conversa sobre esse assunto e mudar de assunto.",
"A maior parte da ilha já está desenvolvida. É difícil desenvolver-se ainda mais porque é difícil limpar a selva densa e não temos gente suficiente aqui para fazer isso...",
"Tudo bem, me diga outra coisa.",
"Não há nada de especial na nossa ilha. Todas as ilhas são mais ou menos iguais neste arquipélago.",
"Eu vejo. Continuar...",
"Temos selva, pedras e praias desertas... e acho que é isso. Bem, há também o assentamento pirata aqui, é claro.",
"Eu vejo. Continuar...",
"Eu vejo. Vamos encerrar nossa conversa sobre esse assunto e mudar de assunto.",
"Eu não sei de nada.",
"Isso é ruim. Conte-me mais sobre a colônia.",
"Não há nada de especial no forte. Possui paredes grossas, canhões de longo alcance e há 1.000 soldados na guarnição.",
"Eu vejo. Continuar...",
"Por que você quer saber, capitão? Não é muito inteligente da minha parte conversar sobre o forte com qualquer estranho. Como posso saber o que você tem em mente?",
"Bem, se o forte é um assunto tão delicado para você, então não vamos falar sobre isso. Conte-me sobre a colônia.",
"Eu vejo. Vamos encerrar nossa conversa sobre isso e mudar de assunto.",
" Temos uma população de ",
" cidadãos.",
};
