string DLG_TEXT[137] = {
"Bem-vindo, ",
". Considere-se em casa, meu amigo - e pense em mim como uma família!",
"Uh... sim. Obrigado. Eu sou ",
".",
"Ei, ",
"! ",
".",
"Bem, agora - veja quem foi levado pela maré! Estou feliz em ver você ",
".",
"É maravilhoso ter você aqui ",
". O que posso te oferecer hoje?",
"Preciso de alguns homens fortes para ajudar no meu navio. Prefiro o inteligente, mas contento-me com o silêncio.",
"Espero que você tenha um momento para conversar.",
"Eu preciso de um quarto. Um limpo.",
"Tem uma pilha de palha grátis neste celeiro?",
"Desculpe. Eu estava de saída ",
". Eu te vejo por aí.",
"Oh, você mesmo se certificará disso, senhor ",
". Meu nome é ",
". Eu sou o dono desta humilde taberna.",
"Preciso contratar uma equipe ",
".",
", vamos conversar...",
"Você tem um quarto que eu possa usar? ",
"Eu gostaria de ficar aqui por um tempo",
"Posso fazer-te uma visita mais tarde.",
"Certamente. Sobre o que você gostaria de falar, capitão ",
"?",
"Um sujeito amigável como você certamente ouvirá muitos rumores interessantes. Eu gostaria de saber o que está acontecendo hoje em dia.",
"Há algo em minha mente...",
"Sim?",
", um homem chamado ",
"Ewan Glover",
"Ewan Glover",
" disse que esperaria por mim aqui.",
"Eu preciso de algum emprego. Você não conhece nenhum garoto rico nesta ilha que tenha medo de viajar sozinho?",
"Bom dia. Como posso ajudá-lo?",
"Procuro um jovem espanhol. O nome dele é Lucas Da Saldanha. Talvez você o tenha visto.",
"Você sabe, ",
", Te encontro em outra hora.",
"Se for ele prefere navegar com menos satélites, você sabe disso.",
"Sim, esqueci. Tudo bem, voltarei mais tarde, quando tiver menos navios, ha-ha.",
"Eu não quero ajudar você, cara, você causou muitos problemas ao meu país",
"Basta olhar para este patriota. Bem adeus",
"Suas mãos cobertas de sangue. Você não pensa seriamente que alguém viajará com você",
"Você está certo, todo mundo tem medo de mim! Ha-ha!",
"Você chegou na hora certa, um comerciante aqui estava procurando a companhia certa para viajar, é melhor você falar com ele. Aqui está ele, entrando na taverna agora.",
"Eu farei isso.",
"Não, não há ninguém naquele momento, Talvez da próxima vez.",
"Hm, então vou esperar.",
"Interessante. A propósito, estou procurando adicionar algumas costas fortes à minha equipe.",
"Gostaria de falar com você, se tiver um momento",
"Desculpe, estou saindo, ",
". Tenho certeza que te verei novamente.",
"Por favor, a qualquer momento.",
"Preciso adicionar algumas costas fortes à minha equipe.",
"Você tem um momento para conversar?",
"Desculpe, eu estava de saída ",
". Eu vou te ver.",
"Sim, na verdade, ele esteve aqui. ",
"Ewan Glover",
" recentemente saiu com uma senhora ou outra. Se você puder ficar ",
", tenho certeza que ele estará de volta em breve.",
"Obrigado. Eu esperarei aqui.",
"Oh, este lugar geralmente está cheio de homens dispostos a navegar no navio certo. Mas agora é tarde. Eles começarão a aparecer pela manhã \nTalvez você queira alugar um quarto e esperar?",
"Tudo bem. Você tem um quarto livre?",
"Talvez eu faça isso, mas tenho algumas outras perguntas primeiro.",
"Eu tenho um quarto ou dois. Quanto tempo você espera ficar?",
"Até de manhã.",
"Só até esta noite.",
"Bem bem. Serão 5 piastras.",
"Justo. Aqui você vai.",
"Isso é muito rico para o meu sangue. Acho que vou passar a noite no salão comunal com os outros indigentes e mesquinhos.",
"O que eu ganho por ser minha dançarina? Deixa para lá. Não será a primeira vez que passo uma noite numa taberna.",
"Vou pensar sobre isso.",
"Vai custar 5 moedas de ouro.",
"Tudo bem, aqui está o seu dinheiro",
"Isso é mais do que gostaria de pagar por uma noite de hospedagem. Se for preciso, descansarei a cabeça em uma das mesas aqui da taverna.",
"O que eu ganho com isso? Minha própria dançarina? Deixa para lá. Não será a primeira vez que passo uma noite numa taberna.",
"Vou pensar um pouco. Vamos falar sobre outra coisa.",
"Senhores, por favor! Pare com isso imediatamente, ou chamarei o guarda!",
"Tudo bem. Relaxar. Estou indo embora.",
"Sim, eu me lembro dele. Bom sujeito e um bom cliente - ele sempre pagava caro.",
"Você sabe onde ele está agora?",
"Não tenho certeza para onde ele foi, mas é possível que eu possa lhe dizer por que ele foi...",
"Por favor faça. É vital que eu saiba!",
"Bem, há rumores de que o jovem espanhol tentou arranjar tempo com a filha do governador. Não sei o que aconteceu, mas ele veio aqui depois com o pior humor. Na manhã seguinte, ele e seu iate desapareceram e ninguém aqui o viu desde então.",
"A filha do governador? O homem tem bom gosto, não é? Alguma chance de eu poder falar com ela, ou o pai dela a observa muito de perto?",
"Ah, você pode ter certeza que quando ele não está cuidando dela, alguém com seu salário está fazendo isso por ele. Bem, ele tem seus motivos, não é? Ela é uma garota bonita. Ela ocasionalmente dá um passeio fora da cidade, mas sempre é escoltada por vários guardas.",
"Esses guardas não devem ser um problema - não pretendo sequestrá-la nem nada, apenas faça algumas perguntas. Obrigado, Charles, você foi de grande ajuda.",
"Eh, para onde eles foram?",
"Desculpe, você pode ser um pouco mais específico.",
"Você viu o governador aposentado e sua filha Caroline?",
"Por aqui capitão, tenho certeza que eles estão esperando por você.",
"Obrigado Charles, estou a caminho!",
"Eh, uh, não consigo encontrá-los. Você tem que me dar uma dica aqui, Charles.",
"Bem, hehe, há um atalho para a residência de Woodes Rogers, por favor, fique atrás do balcão, capitão.",
"Cuidado com essa sua risadinha Windem...",
"Você de novo, o que está fazendo no meu quarto privado? Você não os encontrou apesar das minhas instruções?",
"Pela última vez, cuidado com a língua, velho, e abra a porta dos quartos do Governador!",
"Essa porta está fechada por algum motivo e além disso um pouco de educação seria bem-vinda.",
"Por que razão e você poderia por favor (ou eu te mato em 2 segundos) abrir a porta?",
"Eles vão começar alguns reparos em toda a casa hoje. E não, senhor, a esta hora do dia tenho que descansar um pouco do trabalho na taverna.",
"Talvez um pouco de ouro possa compensar você desse problema terrível",
"Serão 5 ouros então.",
"Aqui está, corra e destranque a porta agora!",
"Hmm, parece que não tenho moedas no momento, mas pagarei mais tarde com certeza.",
"Estou administrando alguns negócios aqui, capitão. Dê-me o dinheiro ou a porta permanece fechada!",
"------",
"Você tem garrafas vazias sobrando na taverna?",
"Garrafas vazias? Não tem problema, capitão, pegue isso!",
"Obrigado Windem.",
"Garrafas vazias? Não tem problema, capitão, mas primeiro você precisa de um armário de remédios.",
"Eu volto em breve.",
"O que é isso que ouvi sobre algum #skid# rico local se casando com alguém da nobreza espanhola?",
"É verdade! ",
", filho",
", filha",
" do comerciante ",
", está comprometido com ",
"a filha",
"o filho",
" do governador de #sSantiago#.",
"Onde ",
" ao vivo? Gostaria de dar os meus parabéns pessoalmente, talvez também oferecer os meus serviços.",
"Basta passar pelo portão para a próxima parte da cidade e você estará olhando diretamente para a casa. Grande, olhando por cima do muro para a nossa prefeitura - você não pode perder.",
"Obrigado!",
"Você já ouviu alguma coisa sobre uma #sperson#, especificamente #sromance#, sendo trazida para esta cidade por uma gangue armada?",
"Não! Na verdade, #sromance# foi recentemente casado com #svillain#.",
"Casado!",
"Sim. Eu tinha a função de fornecer comida e bebida para a recepção. Veja bem, no meu trabalho eu posso dizer a diferença entre um sorriso genuíno e um sorriso forçado, e se #sromance# foi feliz, então comerei o chapéu de alguém.",
"Sim, isso provavelmente explicaria por que #spronoun# teve que ser trazido aqui por uma gangue.",
"Tem acontecido alguma coisa interessante em #sRedmond# ultimamente?",
"Bem, houve o casamento de #sromance# com #svillain#. O casamento aconteceu em #sSantiago# mas houve uma festa de recepção aqui também.",
"Deve ter sido uma festa e tanto!",
"Sim, #svillain# trouxe um monte de vinho francês. Não me pergunte como #spronoun# conseguiu isso, com a guerra.\nMas por causa da guerra, muitas pessoas patriotas não tocaram nele, o que foi bom para mim porque eles vieram aqui para beber.\nTalvez você poderia comprar o vinho barato e vendê-lo em outro lugar.",
"Idéia interessante. Vou ter que ver isso. Obrigado!",
};
