string DLG_TEXT[30] = {
"Encontrei este livro estranho e pensei que você pudesse saber o que é.",
"Deixe-me ver, #schild#. Hummm... isso é muito especial! Acho que sei o que você tem aqui, meu #schild#, mas não me sinto confortável em falar sobre isso com você. Talvez você possa primeiro me mostrar um sinal de boa fé?",
"O que você diria se eu doasse algum dinheiro para a igreja?",
" Eu sei que você já deu muito, mas há mais uma coisa que eu posso lhe pedir.",
"O que você precisa?",
"Como você notou, o Caribe ainda está cheio de todo tipo de coisas pagãs. Algumas das tribos que vivem nas ilhas estão até possuídas por demônios. Portanto, nossos exorcistas têm um trabalho difícil para eles. Mas nem todos voltam para casa em segurança.",
"Você está me pedindo para fazer um exorcismo?",
"Não, claro que não meu #schild#. Fazer isso leva anos de prática. Tenho algo mais simples para você em mente. Precisamos de uma Santa Cruz para realizar um exorcismo, mas estamos com pouca quantidade e levará pelo menos mais alguns meses até que um novo suprimento chegue do Vaticano. No entanto, também os vi sendo vendidos em mercados e lojas por todo o Caribe. Você poderia me trazer uma dessas?",
"Isso não deve ser um problema.",
"Sinto muito, mas pensei que você tinha um trabalho de verdade para mim. Tchau!",
"Oh, muito obrigado! Por favor, devolva a cruz o mais rápido possível. Deus te abençoe nesta jornada.",
"Estarei de volta antes que você perceba!",
"Eu trouxe o item que você pediu.",
"Muito obrigado, isso poderia realmente salvar a vida das pessoas aqui. Como recompensa especial, receba este item. Devo admitir que não sei o que isso realmente faz. Um dos nossos melhores exorcistas mandou fazê-lo depois de encontrar alguns desenhos nos cofres do Vaticano. Dizem que é uma invenção de alguém que viveu em Florença há muitos anos. Se quiser saber mais sobre este item, deverá localizar esse exorcista pessoalmente.",
"Onde eu poderia encontrá-lo?",
"Ele foi visto pela última vez em ",
" então acho que você deveria dar uma olhada no local. Normalmente você pode encontrá-lo se procurar coisas estranhas e perigosas, pois é trabalho dele lidar com isso. Ele pode não gostar que eu tenha lhe dado este item, já que foi feito para ele. Mas faremos outro para ele quando ele precisar.",
"Muito obrigado. Com certeza vou dar uma olhada no local.",
"Bem, encontrei um livro com coisas estranhas que ainda não descobri.",
"Ah, eu sei o que é isso! Este livro contém todos os tipos de exorcismos. Parece que nosso corajoso senhor Winchester finalmente encontrou seu par. Até agora eu também descobri o que faz o  item que te dei. É uma mira telescópica. Acople-a ao rifle que nosso querido senhor Winchester carregava. Isso deve permitir que você mire melhor com ele. Espero que você tenha encontrado a arma dele também, caso contrário, você pode querer voltar e olhar um pouco mais de perto.",
"Muito obrigado pela informação.",
"Não, claro que não é meu #schild#. O livro que você segura contém todos os tipos de encantamentos para exorcismo. Reconheço este livro, parece que nosso corajoso senhor Winchester finalmente encontrou seu par. Espero que você tenha encontrado a arma especial dele, caso contrário, você pode querer voltar e olhar um pouco mais de perto. No entanto, é necessária uma cruz sagrada para realizar um exorcismo, estamos ficando sem elas, mas poderia ter uma com o livro.",
"O livro do exorcismo é de pouca ou nenhuma utilidade para você, mas inestimável para a igreja. Você estaria preparado para trocá-lo por uma quantidade de raiz que conhecemos como tampa de São Tomás?",
"Sim, estou, embora não tenha ideia do que seja, mas não pode ser tão inútil para mim quanto o livro.",
"Talvez houvesse, por acaso tenho uma cruz comigo.",
"Talvez, mas eu não tenho um, talvez eu possa encontrar um para você.",
"Talvez, mas não tenho um, então só tem o livro.",
"Muito obrigado, isso poderia realmente salvar a vida das pessoas aqui. Como recompensa especial, receba este item. Acredito que esteja relacionado à arma do senhor Winchester.",
"Muito obrigado, pode ser útil.",
"Tenho uma cruz desta! Aqui esta ela.",
};