string DLG_TEXT[30] = {
"Vá em frente, faça o meu dia!",
"Você precisa se perguntar uma coisa: 'Sinto-me com sorte?' Bem, sim, punk?",
"Ah, o bom, o ruim e o feio! Você veio fazer negócios, certo? Não tenho tempo para desperdiçar tempo. Então por que você não vai em frente e faz o meu dia?",
"Tudo bem, posso ter algumas joias de interesse. Mas primeiro gostaria de algumas informações.",
"Agora o que você quer?",
"A mulher Brinkley foi morta. Então, o que você saberia sobre isso?",
"Você quer dizer uma joia por outra?",
"Algo parecido.",
"Mostre-me uma amostra do que você tem então.",
"Olhe para esses diamantes.",
"É isso? Já vi mais brilho nos olhos do dono do bar numa manhã de segunda-feira!",
"Oh! vamos lá, seja razoável.",
"Eu tentei ser razoável, uma vez.. Eu não gostei",
"Quer dizer, você não fará negócios comigo?",
"Hum! Você tem alguns belos diamantes aí. Afinal, poderíamos fazer negócios. O que é que voce quer saber?",
"Estou procurando Annabella Brinkley, você a viu?",
"Ela entrou naquela cabana há um tempo atrás. Não a vi sair desde então.",
"Obrigado. Eu vou dar uma olhada.",
"Eu saberia que ela foi muito descuidada, não acha?",
"Isso é tudo que você tem a dizer sobre o assunto?",
"Tudo o que sei é que eu estava aqui e você estava lá. Agora, quem tem maior probabilidade de superá-la, eu ou você?",
"[Sputtering] Mas acabamos de chegar! e o corpo está frio.",
"Frio? Isso me lembra, e o gelo que você está carregando?",
"Diamantes! Diamantes! Isso é tudo que você consegue pensar? E a mulher morta aí dentro!",
"Eu não quero comprá-la. Não há muita necessidade de cadáveres por aqui.",
"Quero dizer... Quem poderia ter feito isso?",
"Eu te direi uma coisa. Você me vende seis desses diamantes por 20.000 peças de ouro e eu lhe direi quem acho que pode tê-la matado, e mais uma informação que você achará de grande interesse, além de acrescentar parte de um mapa do tesouro como um bônus.",
"OK. É um acordo. Olha Você aqui. Agora, quem eu preciso encontrar? E onde eles estão?",
"Um homem chamado Brock era seu parceiro. Se eu fosse você, procuraria em Speightstown. Essa é a base de operação dele. Ele também tinha alguns prisioneiros com ele quando partiu.",
"Prisioneiros! Ah! Obrigado. Estaremos a caminho agora.",


};
