string DLG_TEXT[32] = {
"Tenho a sensação de que algo ilegal está acontecendo aqui.",
"De jeito nenhum, oficial. Meus amigos e eu estamos apenas fazendo um piquenique à beira-mar.",
"Estou apenas dando ouro. Isso é ilegal?",
"Isto não é da sua conta, soldado. Continue andando.",
"Você me decepcionou, capitão ",
"! Quem imaginaria que um #sgender# tão decente e respeitado como você negociaria com contrabando?",
"Você está certo, é claro. Vejo o erro dos meus caminhos, agora.",
"Você ficará pior do que desapontado quando eu te cortar!",
"Bem, considerando as coisas boas que ouvi sobre você no passado, estou disposto a chamar isso de primeira ofensa. Apenas fique longe de tais negócios no futuro. Quanto a esses canalhas, vou acolhê-los agora mesmo!",
"Obrigado, oficial. Você não vai se arrepender disso!",
"Não me venha com isso - não sou cego! Você está preso e seus bens foram confiscados!",
"Não sem luta!",
"De jeito nenhum... contanto que você tenha o suficiente para todos. Quanto você estava planejando me dar?",
"Eu deveria pensar que ",
" o ouro seria generoso o suficiente.",
"Como é que ",
" som de ouro?",
"Para você, oficial? Que tal ",
" ouro?",
"Você está tentando me subornar? Você descobrirá que minha honra não pode ser comprada! Venha conosco!",
"Desculpe desapontá-lo, mas você não vai a lugar nenhum!",
"Ah, obrigado por entregar esta... eh... peça de evidência para mim. Graças à sua cooperação podemos agora prender esses contrabandistas.",
"Que mal... Ah, sim, entendo... Sim, eu atraí aqueles contrabandistas para uma armadilha. Agora faça a sua parte e prenda-os! TRÊS VIVAS AOS NOSSOS GUARDAS COSTEIROS HERÓICOS! ",
"Mas... mas devo prender você!",
"Você ainda esta aqui?! Você está tão cansado de viver?",
"Eu... vou relatar isso. Você não vai escapar impune!",
"Hmph!",
"Você foi longe demais! Você vai morrer nesta costa!",
"Veremos isso!",
"Por favor, olhe para isso.",
"Muito bom, #ssir#. Terei que aproveitar isso para adicionar ao meu próprio relatório, é claro. Agora, siga em frente!",
"Obrigado, agora, por favor, vá embora rapidamente",
};
