string DLG_TEXT[185] = {
", ",
". Meu nome é ",
". Posso saber o seu?",
"Olá, ",
". Eu sou ",
". Para quem tenho a honra de falar?",
"Eu sou ",
". Então o que posso fazer por você, ",
"?",
"Eu sou ",
", capitão e proprietário do navio'",
".",
"Meu nome é ",
".",
"Você pode me chamar de capitão ",
".",
"Olá. Você já ouviu alguma coisa sobre um oficial chamado ",
"Artois Voysey",
"Artois Voysey",
"? Ele escapou recentemente do meu navio e deve estar em algum lugar da sua cidade.",
"Olá, você ouviu alguma coisa sobre um oficial chamado ",
"Nigel Blythe",
"Nigel Blythe",
"? Ele escapou recentemente do meu navio e deve estar em algum lugar da sua cidade.",
"Desculpe. Podemos conversar mais tarde, após o término do culto?",
"Tudo bem.",
"Olá novamente, capitão ",
".",
"Ah, é você ",
". O que te traz aqui?",
"Bem, olha quem é! Bem-vindo, ",
"!",
"Você pode me dizer o que as pessoas têm falado na cidade ultimamente?",
"Que tipo de histórias fantásticas você está ouvindo na taverna esta semana?",
"Estive no mar, então qualquer notícia é nova para mim. Qual é o burburinho?",
"Estou à procura de alguém. Talvez você possa me ajudar a encontrá-lo.",
"Você conhece bem a cidade?",
"Você poderia me dar algumas instruções?",
"Gostaria da sua opinião sobre alguém. Você tem um momento?",
"Tenho uma pergunta sobre alguém que talvez você conheça.",
"Você poderia me contar um pouco sobre os habitantes locais?",
"Conte-me sobre sua colônia.",
"O que você sabe sobre #sConceicao#?",
"Gostaria de algumas informações sobre #sisland_Conceicao#.",
"Olá. Você já ouviu alguma coisa sobre um oficial chamado ",
"Artois Voysey",
"Artois Voysey",
"? Ele escapou recentemente do meu navio e deve estar em algum lugar da sua cidade.",
"Olá, você ouviu alguma coisa sobre um oficial chamado ",
"Nigel Blythe",
"Nigel Blythe",
"? Ele escapou recentemente do meu navio e deve estar em algum lugar da sua cidade.",
"Sinto muito, mas tenho que ir. Até mais.",
"Acho que sua melhor chance de encontrar seu oficial é perguntar sobre ele na taverna - as pessoas de lá definitivamente sabem mais do que eu sobre o que está acontecendo por aqui.",
"Obrigado.",
"Bem, agora que nos conhecemos um pouco melhor, o que você quer de mim?",
"Prazer em conhecê-lo. Há algo que você precisa ",
"?",
"Maravilhoso, capitão. Mas você dificilmente me parou só para se apresentar, não é?",
"Só estou me perguntando quais são os últimos rumores em #sConceicao#.",
"Aconteceu alguma coisa digna de nota ultimamente?",
"Estou procurando me atualizar sobre as últimas fofocas.",
"Você poderia me dar algumas instruções?",
"Estou procurando um lugar específico na cidade, mas não sei como chegar lá.",
"Eu preciso de uma pequena ajuda. Não conheço muito bem a cidade.",
"Gostaria de saber a sua opinião sobre alguém, se me permite.",
"Tenho uma pergunta sobre alguém que você talvez conheça.",
"Você poderia me contar um pouco sobre os habitantes locais?",
"Conte-me sobre sua colônia.",
"O que você sabe sobre #sConceicao#?",
"Gostaria de algumas informações sobre #sisland_Conceicao#.",
"Estou apenas aproveitando os pontos turísticos da cidade. Obrigado.",
"Entendo.... Há mais uma coisa.",
"Obrigado pela informação. Até a próxima.",
"O que mais você gostaria de saber, ",
"?",
"Sim Sim, ",
"? O que é?",
"Então, por suposto ",
", pergunte-me.",
"Estou interessado no que os moradores locais estão falando atualmente.",
"Aconteceu alguma coisa digna de nota ultimamente?",
"Estou procurando me atualizar sobre as últimas fofocas.",
"Você poderia me dar algumas instruções?",
"Estou procurando um lugar específico na cidade, mas não sei como chegar lá.",
"Eu preciso de sua ajuda. Não conheço a cidade.",
"Gostaria de saber sua opinião sobre alguém.",
"Tenho uma pergunta para você sobre uma pessoa que você talvez conheça.",
"O que você pode me dizer sobre os cidadãos locais?",
"Conte-me sobre sua colônia.",
"O que você sabe sobre #sConceicao#?",
"Gostaria de algumas informações sobre #sisland_Conceicao#.",
"Acho que sei tudo o que preciso por enquanto. Até mais.",
"Qual cidadão chamou sua atenção, ",
"?",
"Claro, ",
", De quem você está falando?",
"Quem despertou sua curiosidade então ",
"?",
"Estou falando do cavalheiro governador.",
"O dono da taberna ",
"Duarte Correja",
"Duarte Correja",
".",
"O proprietário do estaleiro, ",
"Humberto de Paiva",
".",
"Estou interessado no comerciante, ",
"Martinho Guterres",
"Martinho Guterres",
".",
"Ninguém. Deixa para lá.",
"O senhor governador é um perfeito cavalheiro. Enquanto ele está aqui, não tivemos problemas sérios. A única coisa que posso dizer sobre ele é... hmm... ele é um pouco... econômico demais. Mas talvez seja para melhor.",
"Eu vejo. Eu tenho uma pergunta.",
"Obrigado. Adeus.",
"Eu não deixaria esse homem lidar com seu dinheiro. Dizem que ele está de alguma forma ligado a contrabandistas e piratas.",
"Eu vejo. Eu tenho uma pergunta.",
"Obrigado. Adeus.",
"Ele faz bons navios... eu realmente não o conheço. Ele vive uma vida bastante humilde. Eu acho que ele não é uma pessoa má ",
"Eu vejo. Eu tenho uma pergunta.",
"Obrigado. Adeus.",
"Ele é o principal fornecedor do nosso governador, então aproveita as oportunidades. Mas devo dizer que ele é um homem honesto. Pelo menos não ouço ninguém dizer o contrário.",
"Eu vejo. Eu tenho uma pergunta.",
"Obrigado. Adeus.",
"Conheço bem esta cidade.",
"Eu vou te ajudar com prazer, ",
". Onde você está indo?",
"A cidade é tão grande que você pode se perder aqui, ",
". Mas se eu puder ajudá-lo, senhor, farei isso com prazer.",
"Como posso encontrar a taberna.",
"E onde fica o estaleiro?",
"Onde posso vender os produtos que trouxe comigo?",
"",
"Duarte Correja",
"Duarte Correja",
"A taberna está situada na cidade, perto dos portões do porto. Uma casa à esquerda.",
"Eu vejo. Obrigado e adeus.",
"E onde fica o estaleiro?",
"Onde posso vender os produtos que trouxe comigo?",
"Você pode encontrar o escritório do estaleiro na praça central. Está localizado em frente à residência do governador. Lá está pendurada uma placa 'Estaleiro Naval' - que significa 'estaleiro' em português.",
"Como posso chegar à taberna?",
"Onde posso vender os produtos que trouxe comigo?",
"Obrigado pela dica. Isso é tudo que eu precisava saber.",
"À direita dos portões do porto, mesmo em frente à taberna, encontrará o que procura.",
".",
"E onde fica o estaleiro?",
"Como posso chegar à taberna?",
"Eu vejo. Isso é tudo que eu precisava saber.",
"Eu nem sei o que te dizer...",
"Sobre o que você quer falar?",
"Por favor.",
"O que você sabe sobre a história da colônia...",
"Existe alguma coisa interessante além da cidade nesta ilha?",
"Você sabe alguma coisa sobre o forte que protege a cidade?",
"Vamos mudar de assunto.",
"Você está realmente interessado? Excelente! Nossa colônia foi estabelecida há apenas 40 anos,\nmas devido à sua boa localização, os fundadores abriram rotas comerciais e rapidamente construíram a cidade.\nAgora é uma das colônias de crescimento mais rápido em nosso arquipélago.",
"Continuar...",
"Então é a história de sempre. Vamos esquecer a história por enquanto.",
"Eles tiveram que construir um forte poderoso para proteger a colônia. Às vezes, porém, parece inútil para mim, já que ninguém jamais tentou atacar nossa colônia.",
"Eu vejo. Vamos tomar outro rumo, certo?",
"Não estou muito familiarizado com a paisagem. Não há nada aqui além de praias desertas, montanhas e selva, que começa nos arredores da cidade. Dizem que há algumas pequenas baías convenientes por aí, onde você pode atracar com segurança e ninguém notará você do mar... Hmm, acho que é tudo o que temos aqui.",
"Tedioso. Diga-me outra coisa.",
"Apenas uma parte da ilha foi explorada até agora. Mas quem precisa disso, afinal? Aproveite a natureza intocada. Dizem que os contrabandistas construíram para si um pequeno esconderijo em algum lugar por aí.",
"Eu vejo. Continuar...",
"Há um assentamento de contrabandistas na selva. Ouvi dizer que eles abriram um belo caminho até uma das baías isoladas da ilha.",
"Eu vejo. Vamos ouvir mais...",
"Eu vejo. Deixe-me perguntar outra coisa.",
"Não estou muito interessado nisso, capitão.",
"Muito ruim. O que mais você pode me dizer?",
"A aristocracia local pagou generosamente pela construção do forte, por isso está em muito bom estado. As riquezas da nossa cidade são bem conhecidas,\nentão o número de soldados guarnecidos aqui aumentou. Já são mil.",
"Eu vejo. Continuar...",
"Não tenho certeza se deveria estar tagarelando sobre isso. Eu não te conheço muito bem. Eu tenho certeza que você entende.",
"Não se preocupe com isso. Não é importante.",
"Eu vejo. Deixe-me perguntar-lhe outra coisa, se me permite.",
"Seu ferreiro, qual é a cara dele.",
"Diego Uargo? Não é tão difícil dizer - repita comigo. 'Di-e-go U-a-rrrgo.' No que diz respeito aos ferreiros, ele não é ruim. Por que você pergunta?",
"Sem motivo. Nova pergunta...",
"Ah, não é importante. Obrigado e vou embora.",
"Esta espada não é tão afiada quanto eu gostaria. Conhece alguém que poderia afiar a lâmina para que até minha mãe pudesse raspar os bigodes com ela?",
"*estremecimento* uh... bela imagem mental aí... de qualquer forma, a casa de Diego é perto dos portões do porto; à esquerda enquanto você entra na cidade. A porta dele fica de frente para a parede.",
"Eu e minha querida mãe europeia agradecemos.",
"E onde fica o estaleiro?",
"Onde posso vender os produtos que trouxe comigo?",
"Temos uma população de",
"cidadãos.",

};
