string DLG_TEXT[37] = {
".....",
".....",
"#ssir#, por que você está me perturbando? Espero que isso seja muito importante.",
"Bonjour monsieur, estou aqui para visitar a Governadora - Madame de Cussy.",
"Bonjour monsieur, sinto muito por interrompê-lo, mas desejo uma audiência.",
"Sinto muito #ssir#, mas não sou o governador. Eu sou o Contre-Amirale César Beauregard, fui enviado por Luís XIV para ajudar o nosso Governador a pôr ordem nestas águas piratas. Agora me diga, por que você me incomodou?",
"Trabalhar. Procuro ajudar a França nos seus esforços aqui.",
"Eu estou ouvindo.",
"Nas minhas viagens, ouvi dizer que os espanhóis tratam os cidadãos franceses com o maior desrespeito.",
"Os espanhóis são conhecidos pela sua falta de respeito pelos nossos compatriotas. É bem conhecido.",
"Estou preparado para ajudá-lo. Tenho um navio sólido e uma boa tripulação e não gosto dos espanhóis.",
"Então você procura alguma operação secreta?",
"Oui!",
"Seg Deus!!! Pareço uma Madame?",
"Minhas desculpas, senhor. Vou deixar você agora.",
"Talvez possamos usar você. Mas ninguém pode saber que você está trabalhando para mim.",
"E ninguém o fará. O que você tem em mente para mim?",
"Não, é tudo muito arriscado para mim. Talvez em outra ocasião, quando eu tiver um navio maior e mais tripulação.",
"Corre o boato de que um contrabandista holandês está a caminho de #sSanto Domingo#, carregado de munições. Dizem que os espanhóis planejam retomar #sRedmond#. Mas por que a França deveria interferir nisso?",
"Por que, por favor, diga-me Contre-Amirale.",
"#sPort au Prince# é cercada por assentamentos espanhóis. Se houvesse uma guerra, #sPort au Prince# seria invadida por tropas espanholas num instante. Portanto, precisamos manter o status quo, por assim dizer. Então, preciso que você intercepte o contrabandista holandês.",
"Eu assumirei a missão. Haverá uma recompensa se eu tiver sucesso?",
"5.000 de ouro, 2.500 agora e 2.500 quando você tiver sucesso. Uma boa soma, não?",
"O que você ouviu sobre este navio holandês?",
"O navio se chama 'Vogelstruijs' e partirá de #sisland_Douwesen# em 10 dias, para buscar a munição em #sisland_Curacao#.",
"Eu irei embora imediatamente!",
"Ah, você voltou!",
"Sim, com boas notícias Contre-Amirale! Não só tenho informações sobre os planos do contrabandista, como também trouxe a carta original dos espanhóis!",
"Isso é realmente uma notícia muito boa. Isso é mais do que eu esperava! Aqui está o resto do dinheiro, como prometido. Agora, deixe-me ver esta carta.",
"Voilá, aqui está.",
"Um mensageiro após a chegada... Uma das patrulhas avistou um Dutch Pinnace esta manhã, ancorando em Boca de Yuman. Temos que agir rapidamente antes que os espanhóis cheguem para descarregar a carga!",
"Navego agora para Buca de Yuman.",
"Boa viagem e um rápido retorno.",
"Ah, espero que você seja portador de boas notícias!",
"Sim, eu sou Contre-Amirale! Embarquei com sucesso no 'Vogelstruijs'. Eu mesmo acendi o paiol dela. Quem disse que avestruzes não podem voar!",
"Ha ha, você é um brincalhão. Aqui estão os outros 2.500 que prometi a você. Você está livre para ir agora, não tenho mais missões por enquanto.",
"Obrigado, senhor!",
};
