string DLG_TEXT[66] = {
"O que você acha da nossa última luta? Não me lembro de nada parecido!",
"Sim! Houve uma carnificina gloriosa! E o que você terá que ver no futuro!!! Esta é a nossa vida, meu amigo.",
"Se você quiser lutar de novo, preciso que alguns homens desembarquem comigo na próxima vez!",
"Você precisa de um uniforme melhor.",
"Devo fornecer armas ao nosso grupo de embarque.",
"Sim capitão, e quantos homens você quer com você?",
"1 homem será suficiente!",
"2 homens. Tenho alguns negócios na cidade e não quero problemas!",
"3 homens. Preciso de uma escolta mais próxima!",
"4 homens. Devemos estar cientes.",
"5 homens. Esta ilha pode ser perigosa.",
"6 homens. Talvez tenhamos que atravessar selvas perigosas nesta ilha.",
"7 homens. Teremos que atravessar selvas perigosas.",
"8 homens. Eu não gosto desta ilha amaldiçoada!",
"9 homens. Esta ilha parece muito perigosa e provavelmente teremos que lutar aqui!",
"10 homens e prepare-os para um ataque!",
"Sim capitão. Apenas um homem irá segui-lo até terra!",
"Sim capitão. Dois homens irão segui-lo até terra!",
"Sim capitão. Três homens irão segui-lo até terra!",
"Sim capitão. Quatro homens irão segui-lo até terra!",
"Sim capitão. Cinco homens irão segui-lo até terra!",
"Sim capitão. Seis homens irão segui-lo até terra!",
"Sim capitão. Sete homens irão segui-lo até terra!",
"Sim capitão. Oito homens irão segui-lo até terra!",
"Sim capitão. Nove homens irão segui-lo até terra!",
"Sim capitão. Dez homens irão segui-lo até terra!",
"Bom!",
"Eu mudei de ideia.",
"Preciso de um pouco de prática de esgrima. Vamos cruzar espadas, amigavelmente, #slad#.",
"Você quer que eu pegue leve com você, Capitão?",
"Sim, estou um pouco enferrujado. Mostre-me o básico.",
"Não, estou pronto para você. Traga-o, marinheiro!",
"Pronto quando você estiver, Capitão.",
"Não mijem nas calças, pessoal.",
"Sim, amigo. Vamos lá então.",
"Desculpe por isso, capitão. Você precisa de tempo para recuperar o fôlego?",
"Uau, você me surpreendeu daquela vez, capitão. Posso fazer uma pausa?",
"Claro. Podemos dançar outra hora. Vá descansar agora.",
"Não. Um pouco mais, por favor. Preciso estar em boa forma para a próxima abordagem.",
"Você poderia me dar algumas informações?",
"Claro que posso, capitão. O que você precisa saber?",
"Eu gostaria de saber que horas são.",
"Não importa, acabei de lembrar. Pode seguir.",
"#ssir#, é ",
" agora. Você quer que esperemos um pouco?",
"Não, agora é um momento tão bom quanto qualquer outro. Vamos!",
"Sim, devemos esperar mais 1 hora.",
"Sim, devemos esperar mais 8 horas.",
"Sim, vamos esperar até um horário específico.",
"Muito bem, até quando devemos esperar? [hmm]",
"Você quer que esperemos até ",
", #ssir#?",
"Sim está certo.",
"Não, mudei de ideia. Vamos agora!",
"Eu não entendo. Até quando devemos esperar?",
"Deixe-me dizer isso novamente.",
"Deixa para lá. Vamos agora",
"Sim, devemos esperar mais 3 horas.",
"Levantar âncora, rumo ao horizonte.",
"Nova bandeira ao vento já!",
"Qual bandeira capitão?",
"Içar bandeira ",
" capitão?",
"Sim. Agora mesmo.",
"Esqueça isso, mudei de ideia.",
};
