string DLG_TEXT[50] = {
", o que traz você à nossa tribo?",
"Estou apenas explorando.",
"Saudações. Disseram-nos que alguém nos traria remédios. Isso é você?",
"Foi, mas não tenho remédio suficiente.",
"Foi, mas não tenho remédio.",
"Primeiro, você me levará até onde eu possa atacar os espanhóis. Quando eu voltar aqui com a prata, descarregaremos o remédio ao mesmo tempo que carregamos a prata.",
"Então meu povo terá que encontrar outra maneira de conseguir remédios. E você não encontrará a prata espanhola.",
"Adeus.",
"Não foi isso que foi acordado.",
"Não fui eu quem fez o acordo. Meu negócio é que você receba o remédio quando eu conseguir a prata. É pegar ou largar.",
"Embora eu não confie em você, nossa aldeia irá perecer sem o remédio, então não tenho escolha. Vou levá-lo até onde você lutará contra os espanhóis. Me siga.",
"Sim. Eu tenho o remédio que você precisa. Em troca, você deverá me levar até onde eu possa atacar os espanhóis e sua prata.",
"Foi isso que também nos disseram. Se você descarregar o remédio, os outros daqui vão levar para a nossa aldeia. E eu vou te levar para onde você vai lutar contra os espanhóis.",
"Acordado. Começaremos a descarregar imediatamente.",
"Obrigado por nos trazer remédios. Agora nossa aldeia viverá. Os outros estão tomando o remédio lá agora. E honrarei o acordo. Me siga.",
"Tudo bem vamos.",
"Descanse um pouco! Não se mova.",
"O que aconteceu?",
"Você foi picado por uma cobra particularmente desagradável. Consegui reanimá-lo, mas ainda não consegui curá-lo completamente.",
" Seu antídoto não irá ajudá-lo.",
"\nMas posso curá-lo combinando nossos próprios remédios com os remédios que você traz para nossa aldeia. Se você pedir que o remédio seja trazido para cá, posso começar.",
"Muito bem.",
"Eu não tenho nenhum remédio.",
"Eu só tenho ",
" unidades de medicina.",
"Sem o remédio, em breve morreremos de doença.",
" E sua traição também condenou você. Verdadeiramente nossos deuses são justos.",
"...",
"Isso não é suficiente para salvar a nossa aldeia da doença.",
"Isso não é suficiente para salvar todos nós, mas a aldeia sobreviverá.\n",
"Também não é o valor prometido, mas você viverá. No entanto, não somos mais obrigados a ajudá-lo contra os espanhóis.",
"No entanto, se você me der ",
" em ouro, posso dar aos nossos amigos da cidade e eles podem comprar mais remédios para salvar toda a nossa aldeia.",
"Tudo bem, eu posso pagar isso. Aqui está o dinheiro.",
"Isso é muito!",
"Eu não tenho tanto dinheiro.",
"Então, desde que você nos dê o remédio que você tem, eu irei curá-lo. Mas já não somos obrigados a ajudá-lo contra os espanhóis.",
"Obrigado por poupar alguns remédios para me salvar.",
"\nMas combinando nossos próprios remédios com os remédios que você trouxe para nossa aldeia, posso curá-lo. Ao nos salvar, você salvou a si mesmo. Verdadeiramente nossos deuses são justos.",
"Enviarei um dos nossos à cidade com este dinheiro para se encontrar com os nossos amigos. Por enquanto, você enviará o remédio que tiver e eu irei curá-lo.",
"Vou levá-lo de volta à selva. De lá, você poderá encontrar o caminho de volta para o seu navio.",
"Bom, vamos.",
"É aqui que eu deixo você. Você não conseguirá encontrar nossa aldeia novamente, então não tente.",
"Obrigado por me trazer até aqui. Adeus.",
"Você se recuperou bem. Ainda dá tempo de você ir encontrar os espanhóis. Agora vou te levar lá.",
"Obrigado. Vá em frente!",
"É aqui que eu deixo você. Por nos trazer os remédios que precisamos, você será sempre bem-vindo se retornar à nossa aldeia.",
"Obrigado. Posso muito bem visitar sua aldeia novamente. Adeus.",
"Onde está o remédio? Eu não vejo o seu navio.",
"Está atracado em outro lugar. Vou trazer o navio para cá. Até logo.",
}
