string DLG_TEXT[17] = {
"",
"! Como vai você?",
"Por que você esteve ausente tanto tempo?",
"Achei que você nunca mais voltaria",
"Certo. Mas não, graças a você.",
"Quem era ela?",
"Você conhece ela?",
"Achei que era o único para você. Que é aquele?",
"Quem?",
"O que você está falando?",
"Quem é que queres dizer?",
"Quem eram eles?",
"Você conhece eles?",
"Achei que era o único para você. Quem são eles??",
"QUEM?",
"Do que diabos vocês estão falando?",
"Eu não conheço nenhum deles. E eu também não te conheço.",
};
