string DLG_TEXT[34] = {
", amigo. Eu sou",
", Eu administro o estaleiro local.",
"Prazer em conhecê-lo. Eu sou ",
", o capitão do '",
".",
", ",
". Então o que posso fazer por você, ",
"?",
"Só estou tentando tapar alguns buracos e remendar minhas velas. Sem perguntas.",
"No momento estou mais interessado em informações.",
"Não, estou apenas matando o tempo. Pensei que poderia matar alguns dos seus enquanto estou nisso.",
"Bem, se você é capitão, meu estaleiro está ao seu serviço.",
"Excelente, ",
". Vamos dar uma olhada no meu navio e ver o que precisa ser consertado.",
"Eu agradeço. No momento, porém, gostaria apenas de fazer algumas perguntas.",
"Talvez na próxima vez. Não preciso dos seus serviços agora.",
"No que exatamente você está interessado ",
"?",
"No momento não, não.",
"Há mais alguma coisa que eu possa fazer por você ",
"?",
"Se você puder colocar alguns remendos na minha banheira, irei embora!",
"Obrigado, é isso. Até a próxima!",
"O que exatamente você precisa?",
"Meu navio precisa de reparos. Ou talvez eu compre um novo se o preço estiver bom.",
"Estou sentindo necessidade de um pouco mais de poder de fogo. Talvez você possa ajudar.",
"Eu estou bem, obrigado.",
"Recuso-me a negociar com uma pessoa com a sua reputação e relações. Agora saia, ",
", antes de chamar os guardas.",
"Muito bem.",
"Tudo bem, meu cais ao lado do forte está disponível para você. Se você quiser, direi ao meu chefe das docas para rebocar seu navio até lá. Só então poderei avaliar os danos e dizer quanto tempo e dinheiro serão necessários.",
"DOCA AO LADO DO FORTE?? Uhh... só me lembro que tenho... eeh... outro assunto urgente que preciso resolver primeiro. Adeus.",
"Após fechar esta caixa de diálogo, pressione ENTER para abrir a interface de mudança de vela.",
"Saída",

};
