string DLG_TEXT[20] = {
"Você perdeu alguma coisa, capitão?",
"O que você quer dizer e quem é você?",
"Você não se lembra de um certo governador perdendo a filha?",
"Como você sabe disso?",
"É melhor deixar como está ou meu capitão se envolverá. Entendeu?",
"Acho que não, a menos que você me diga quem é seu capitão.",
"É Davy Jones, claro.",
"Dave Jones?! Agora eu entendo.",
"Bem, já perdi tempo demais com você. Então, desista ou você pode acabar num baú no Fundo do Mar!",
"Em outras circunstâncias, você provaria minha lâmina, mas como não estou interessado em me encontrar no baú de Davy Jones, estou me despedindo.",
"Olá capitão. Eu não gostaria de estar na sua situação. Davy Jones está esperando por você. Vá encontrá-lo!",
"Confesso que nunca gostei desse tipo de reunião familiar.",
"Pensou que poderia fugir de nós, Sparrow? Como você estava errado... Agora siga-nos!",
"Acho que não tenho opção.",
"Davy Jones está esperando por você na costa. Vá conhecê-lo!",
"Confesso que nunca gostei deste tipo de reunião familiar...",
"Bem, bem... Olha quem temos aqui! Visitando o covil do próprio rei do mar, não é? Ele está esperando por você em sua cabana lá em cima!",
"Na verdade, eu estava procurando uma audiência com o Sr. Jones... por assim dizer.",
"Você não parece pertencer a este lugar. Talvez depois de algumas centenas de anos...",
"Não pretendo ficar tanto tempo!",
};
