string DLG_TEXT[258] = {
"Skull mandou você? Se não, você vai parecer muito engraçado tentando colocar o cérebro de volta na cabeça.",
"Você beija sua mãe com essa boca? Skull diz para ficar longe de seu estoque de Snakebite.",
"Então, Governador ",
"Robert Christopher Silehard",
" me envia seu #sgender# da mão direita. O que ele quer de mim, #sdiminutive#?",
"Quem disse que trabalho para ele?",
"O que te faz pensar que estou aqui por ordem do governador?",
"Peço perdão, mas pareço o idiota da aldeia? No momento em que descobri que alguém estava me procurando, fiz perguntas\nVocê me olharia nos olhos e negaria que trabalhou para ele nos últimos meses?",
"Ok, digamos que você esteja certo e o governador me enviou. Que diferença isso faz? Você se recusaria a falar com um representante do governador?",
"Olha, já estou farto deste gato e rato. Você vai conversar comigo ou prefere escolher qual das suas pernas quer manter?",
"Capitão, gostaria de saber se sabe com quem está falando. Você deve confiar em mim quando digo que se eu não quisesse falar com você, você não estaria aqui.",
"Ah, não há necessidade de violência física, #sdiminutive#. Vou falar com você porque estou curioso: o que aquela velha raposa, o governador, quer de mim?",
"Entendido! Preciso saber onde posso encontrar um cavalheiro chamado ",
"Raoul Rheims",
". Fui informado que ele está escondido em algum lugar desta ilha.",
"Suas informações estão desatualizadas, amigo. ",
"Raoul Rheims",
" de fato passou alguns dias aqui, praticamente nunca saiu de casa, mas já zarpou novamente e manteve seu destino em segredo até de mim. Claramente, ele estava preocupado com alguma coisa, mas não saberei dizer o quê.",
"Ele tem uma casa aqui? Onde posso encontrá-la?",
"Tem barraco aqui na ilha, não é? Onde fica?",
"Só um momento, #sdiminutive#. Você pode muito bem ser um enviado do governador inglês, mas isso não lhe dá permissão para invadir a casa de outro homem e vasculhar seus pertences. Fui muito claro?",
"Peço humildemente que abra uma exceção para mim, senhor. Devo descobrir onde ",
"Raoul Rheims",
" estava navegando, e o mais rápido possível!",
"Ah, venha agora. Você é um contrabandista, conhecido em todo o arquipélago pela sua falta de princípios. Você vai me contar sobre a lei?",
"Posso ver que você não escuta a razão. Se não conseguir convencê-lo a ficar longe daquela casa, simplesmente ordenarei aos meus homens que a vigiem e atirem assim que te avistarem. Tenho certeza de que até você consegue entender uma pista de uma bala de mosquete. Agora, suma!",
"Adeus.",
"Isso não acabou!",
"Por favor, saia da minha casa. Estou ocupado e não tenho tempo para falar com você.",
"...",
"Vejo que você respondeu ao meu pedido. Estou muito feliz por isso...",
"Espero que todo esse espetáculo de convite não seja feito para me vingar por ter invadido a casa de Reims!",
"Você voltou para me informar que decidiu aceitar minha oferta?",
"Sim, acho que combina comigo.",
"Não, ainda estou pensando nisso.",
"Bem vamos ver. Não, você ainda não pode levar a bordo a quantidade de carga necessária.",
"Ok, vou levar isso em consideração.",
"Bom! Vejo que você conseguiu descarregar a retenção e pode prosseguir com minha tarefa.",
"Estou ansioso para isso.",
"Onde você esteve todo esse tempo, ",
"?!",
"Tentando encontrar uma embarcação mais espaçosa...",
"Feliz por ter você de volta. Espero que tudo tenha corrido bem? Embora. pela sua expressão, não acho que estou tendo muitas esperanças.",
"Infelizmente, não tenho nada para lhe contar. O negócio foi concretizado, mas antes de Maginot me entregar o dinheiro, ele foi preso pelos soldados.",
"Vejo que você voltou. Espero que você tenha trazido dinheiro e boas notícias?",
"Sim, embora aquele bastardo do Jean tenha armado uma grande armadilha para mim.",
"Vejo que você voltou. Espero que você tenha trazido dinheiro e boas notícias?",
"Infelizmente. Mas tenho provas de que Jean realmente escondeu a mercadoria.",
"Vejo que você voltou. Espero que você tenha trazido dinheiro e boas notícias?",
"Eu não trouxe o dinheiro porque aquele bastardo do Jean pediu um adiamento e depois mandou assassinos para me matar!",
"Vejo que você voltou. Espero que você tenha trazido dinheiro e boas notícias?",
"Não, Jean está à beira da falência e não pode pagar pela nossa carga, que foi confiscada.",
"Vejo que você voltou. Espero que você tenha trazido dinheiro e boas notícias?",
"Sim, embora aquele bastardo, Jean, tenha mandado assassinos para me matar.",
"Bem, bem, bem... Quem eu vejo! Por que você está aqui tão cedo? Você poderia ter ficado longe por mais dois ou três anos...",
"Fui pego por uma tempestade! Não... quase fui comido por um tubarão!",
"Você chegou bem na hora, meu amigo. Agora vamos falar com o chefe dos piratas. Por favor, não interfira a menos que seja necessário.",
"Tudo bem, vou manter minha boca fechada",
"Caramba! Esperava que todos os assuntos fossem resolvidos durante a reunião, mas há ainda mais!",
"O que vamos fazer a seguir?",
"Posso ver pela sua expressão que você não voltou de mãos vazias.",
"E você está certo que eu não fiz isso! Aqui está a escritura da loja.",
"Você parece um pouco desgrenhado, #sNathaniel#. Algo está errado?",
"(Você relata o incidente no #sMarigot# para Beltrop, intercalado com especulações sobre o pedigree de Jean Maginot).",
"Você parece um pouco desgrenhado, #sNathaniel#. Algo está errado?",
"(Você conta o incidente no #sMarigot# para Beltrop em detalhes, embelezando-o um pouco para não parecer um completo idiota aos olhos de seu empregador).",
"Seu olhar sombrio me diz que você voltou sem nada.... Diga-me o que aconteceu.",
"(você conta a Beltrop os detalhes de sua aventura fracassada).",
"Seu olhar sombrio me diz que você voltou sem nada. Diga-me o que aconteceu.",
"(Você conta a Beltrop os detalhes de sua falha).",
"Você voltou tão rápido? Você realmente cumpriu minha missão?",
"Ainda não, mas tenho novidades para você. Notícias muito desagradáveis.",
"Feliz por ter você de volta. Tenho tudo pronto para ir. E podemos começar.",
"Boa Sorte Vá com Deus.",
"Bem, você é um mestre em organizar uma luta espetacular. Eu mesmo vi tudo, é um espetáculo para ser visto",
"Obrigado.",
"Lamento dizer isso, mas ao matar o Barracuda, você perdeu toda a credibilidade comigo.",
"",
"Não importa Reims, não estamos falando dele. Mas foi a sua ousada intrusão na casa dele que me levou a ter esta conversa.",
"Aham... Vá em frente.",
"Você gostaria de se juntar à nossa irmandade? Meus homens arriscam a cabeça, mas também ganham um bom dinheiro\n E você, com seus talentos, é perfeitamente capaz de se tornar meu assistente... no futuro. O que você diz?",
"É uma oferta tentadora. Acho que vou aceitar.",
"Acho que não estou interessado.",
"Isso é ruim. Mas sou um homem paciente, então se você mudar de ideia, estarei disposto a repetir minha oferta novamente.",
"O tempo vai dizer. Adeus.",
"Isso é bom. Então vamos ao que interessa. Não me importa qual bandeira você hasteia ou com quem você luta. O importante é que você cumpra minhas ordens...",
"Parece um rapaz de recados.",
"Sem ofensa, meu amigo. Mas para ser meu assistente você terá que trabalhar muito. E esse trabalho nem sempre será agradável.",
"Eu já entendi... Bem, o que você queria que eu fizesse?",
"Para entregar contrabando, meu amigo. E não sorria, eu imploro\nVocê pode ter usado contrabando antes, mas este é um pouco diferente.",
"Desculpe, não pude resistir. Realmente, o que mais os contrabandistas fariam senão entregar contrabando?",
"Você está enganado e logo verá isso. Nem todas as minhas tarefas são tão frustrantemente monótonas\nMas talvez devêssemos voltar ao trabalho, afinal.",
"Sim, acredito que essa seria a melhor forma de continuarmos nossa conversa.",
"Não sejamos sarcásticos ",
"! Sua natureza falante está começando a me entediar!",
"Foi você quem me ofereceu esse emprego, então se me quiser, terá que tolerar meu jeito de falar também.",
"Ahem... Contudo... Parece que já estou começando a me arrepender da minha oferta...",
"Deus tenha piedade! Você se importa como eu falo enquanto estou fazendo suas tarefas?",
"Considerarei suas palavras à vontade, mas enquanto isso, vamos voltar ao que interessa. Agora, seu trabalho é entregar um carregamento de sândalo em #sisland_Saint Martin# ao lojista de #sMarigot#, Jean Maginot. Não se preocupe, ele foi avisado e você não corre um risco maior do que o normal. Eu lhe darei sua recompensa quando você retornar.",
"Hmm... Tudo bem, onde quer que estejamos!",
"Hum. No entanto, o seu navio não é grande o suficiente para fazer negócios sérios. Libere espaço no porão e volte, talvez o transporte do sândalo ainda seja relevante.",
"Eu vou. Até mais.",
"Hmm... então... seu porão acomodará facilmente toda a carga...",
"Isso é ótimo! Quando posso sair?!",
"Não tenha tanta pressa ",
". Deixe-me lembrá-lo novamente do que você deve fazer. Então, #sMarigot# na ilha de #sisland_Saint Martin#, lojista Jean Maginot, gorjeta na chegada.",
"#sMarigot# na ilha de #sisland_Saint Martin#, Maginot, dinheiro. Eu ouvi você certo?",
"Você está sendo irônico... Boa sorte, meu amigo.",
"Como se costuma dizer na nevada Moscóvia, onde vivem os ursos: 'Para o inferno com isso.'",
"Apenas se apresse! Posso dar este trabalho a outra pessoa.",
"Voltarei assim que puder.",
"Poderíamos navegar para a Europa - há uma grande seleção de navios finos com carga suficiente para qualquer viagem...",
"Aha, presumo que outra pessoa levou o sândalo para #sMarigot#?",
"Sim, eu simplesmente não conseguia esperar mais. Cada remessa, você sabe, tem seus próprios prazos.",
"Hmm... O que devo fazer agora? É isso, estou livre?",
"Não, não, não tenha pressa! Talvez eu tenha exagerado um pouco ao gritar com você, mas... De qualquer forma, tivemos alguns problemas com esso sândalo...",
"Ha! O que eles são?",
"O negócio não deu certo... Quando meu homem descarregou o sândalo para Maginot e foi até sua loja para receber o dinheiro, soldados franceses invadiram. Meu homem foi obrigado a fazer uma retirada apressada, fingindo ser um cliente comum, mas ele viu pela janela que os soldados haviam encontrado o sândalo escondida e prenderam Jean.",
"E o que eu posso fazer?",
"Hmm... Por que você não me conta mais sobre esse incidente?",
"(Você conta a ele exatamente o que aconteceu na loja de Jean Maginot.)",
"Não é sua culpa não ter concluído esta tarefa até o fim. Aqui está sua recompensa.",
"Ah, você é muito generoso. Mas talvez haja algo que eu possa fazer para remediar a situação.",
"Bem, você acertou em cheio e vou pedir que você volte para #sMarigot# mais uma vez.",
"Ahem... Certo, eu não... O que é isso? Você tem algum tipo de plano?",
"Acho que há algo errado aqui. Maginot já foi tortuoso antes, e é isso que me preocupa.",
"Você quer dizer que esse mascate está fazendo um show para não pagar você?!",
"Sim, tenho essa suspeita. Cabe a você descobrir se é verdade.",
"Não por um 'obrigado', claro?!",
"Esqueceste-te? Eu lhe disse que recompenso generosamente meus homens.",
"Eu não esqueci, mas você vai. Você é ainda mais escorregadio que Maginot, infelizmente.",
"Eu perguntaria a você ",
"! Não se esqueça com quem você está falando!",
"Tudo bem, tudo bem. Prepare o dinheiro, vou arrancar tudo que puder desse malandro.",
"Quero sândalo ou dinheiro, lembre-se disso. Eu não me importo como você consegue um ou outro",
"OK.",
"Hum. Então ele decidiu brincar comigo... Mas você tem certeza de que ele é culpado?",
"Tenho cem por cento de certeza! O bastardo plantou o anel em mim e depois alegou que eu o roubei.",
"Hmm... Tudo bem, vou pensar em uma maneira de dar uma lição naquele malandro... Mas você me devolveu meu dinheiro?",
"Sim, aqui está.",
"Ótimo, e aqui está sua porcentagem do negócio. Agora eu gostaria de lhe dar mais uma coisa para fazer.",
"Estou ouvindo.",
"Bem, isso também é um resultado, agora conte mais sobre isso.",
"(Você conta a Beltrop em detalhes a história de sua captura e feliz libertação).",
"Hum. Bem, vou pensar em uma maneira de ensinar uma lição àquele malandro... Enquanto isso, gostaria de confiar a você mais um assunto.",
"Estou ouvindo.",
"Hmm... Você tem alguma prova de que esses homens estavam agindo sob as ordens de Maginot?",
"Quem mais poderia querer se livrar de mim!",
"Eu não sei sobre isso. Ok, vou pensar um pouco sobre a situação e tenho uma nova tarefa para você.",
"Estou ouvindo.",
"E presumo que você não fez nenhuma investigação sobre isso? Tal credulidade não lhe honra.",
"Mas, se me permite!",
"Cale a boca... Vou mandar outra pessoa para verificar esse malandro e tenho outra tarefa para você.",
"Estou ouvindo você.",
"Conte-me mais sobre o que aconteceu.",
"(Você conta para Beltrop o que aconteceu com você em #sMarigot#.)",
"Bom. Vou pensar no que pode ser feito com esse malandro, mas enquanto isso tenho uma nova tarefa para você.",
"Estou ouvindo.",
"Eu preciso de sua ajuda. O fato é que as relações entre nós e os piratas de #sisland_Quebradas Costillas# têm ficado um pouco tensas ultimamente....",
"E?",
"... e marquei um encontro com o chefe dos piratas, chamado ",
"Isenbrandt Jurcksen",
"...",
"Ah, sim, e tenho que estar presente para garantir sua segurança?!",
"Segurança?! Você está brincando, #sNathaniel#? Não, preciso de você como figurante ou comitiva, é somente para ter mais credibilidade, por assim dizer.",
"Aham. Eu vejo. Bem, para agradar a todos, isso é para agradar a todos. Agora me conte mais sobre isso.",
"OK. Então, você está saindo para o mar e rumo a #sisland_Douwesen#. É onde nos encontraremos na baía conhecida como 'Crab Cliffs'. Ah, e não se atrase, o encontro é em duas semanas.",
"Vai fazer.",
"Vocês estão todos brincando?! A propósito, eu não estava brincando! Você quase arruinou minha negociação, então esteja avisado, mais um deslize e terei que terminar com você.",
"Entendo.",
"Acho que você passou todo esse tempo na casa da prostituta do porto. De qualquer forma, você falhou nas duas tarefas anteriores e na terceira. Você não iria para o diabo?",
"O que?! Como ousa falar assim comigo, seu desgraçado!",
"Sinto muito pelo que aconteceu.",
"Você responderá a esse insulto, meu jovem! Defenda-se!",
"Uma missa, você diz, uma escolta.... Agora vou te mostrar tanto a escolta quanto a missa! Agrgh!",
"Da mesma maneira. E quais esperanças você tinha. Até a próxima.",
"Até a próxima.",
"Pensamento. Estou pensando e tenho uma nova tarefa para você.",
"O que é?",
"Se você se lembra, tivemos um problema com Jean Maginot.",
"Pode apostar que sim! Aquele bastardo me fez sangrar muito",
"Você se lembra de Jean Maginot? Depois que você não devolveu meu dinheiro, enviei outro homem para aquele mascate\n E como fui informado hoje, esse homem foi executado.",
"Diabo! Então o mascate realmente não estava limpo!",
"Precisamos lhe ensinar uma boa lição. Ou seja, faça com que ele venda sua loja para meu homem. \nNão me importo como exatamente fará isso, Apenas faça!",
"Fique tranquilo, estou à altura da tarefa.",
"Você me fez um grande favor, meu amigo. Aqui está sua recompensa e tenho uma nova tarefa para você.",
"O que é?",
"Sinto muito por ouvir isso. Terei que contratar outra pessoa para comprar a loja, o que envolverá despesas adicionais.",
"Fiz o meu melhor, mas aquele cara foi mais fácil de matar do que persuadir.",
"Receio que seja o fim da nossa cooperação, #sNathaniel#.",
"Para o inferno com você! Quase perdi a cabeça e você ainda está preocupado com alguma loja!",
"Sinto muito pelo que aconteceu.",
"Não se sinta mal, todos nós cometemos deslizes. Agora, de volta aos negócios, tenho uma nova tarefa para você.",
"O que é?",
"Por favor! Afinal, você não está falando com um estivador!",
"É isso! Estou cansado de suas palestras! Você já está farto disso!",
"Da mesma maneira. E quais esperanças você tinha. Adeus.",
"Adeus.",
"Sério, #sNathaniel#, você se superou. Terei que enviar outra pessoa para resolver este assunto e tenho uma nova tarefa para você.",
"O que é?",
"Como você se lembra, temos tido problemas com os piratas, com ambos os chefes dos piratas negando qualquer envolvimento...",
"Sim, eu me lembro de tudo.",
"Temos um problema com piratas... Ou melhor, com pessoas que hasteiam a bandeira pirata, mas não são membros da Irmandade Costeira.",
"Prossiga.",
"Consegui descobrir que o governador local é o culpado pelo que está acontecendo, que equipou uma flotilha de 5 navios de guerra para lutar contra meus homens...",
"Você quer que eu lide com essa flotilha?",
"Isso mesmo. Além disso, reforçarei sua flotilha com meu próprio homem.",
"Mas, deixe-me dizer, eu posso fazer isso sozinho.",
"Receio que isso esteja fora de questão. Agora deixe-me apresentar-lhe o seu companheiro.",
"...",
"Bem, não perca tempo, conte-me o que você descobiu.",
"Temos um traidor em nossas fileiras.",
"Bem bem. conte-meo que mais sabe.",
"(Você conta a Beltrop o que descobriu na taverna).",
"Diabo! Ok, eu cuidarei disso e você continuará com a tarefa em questão.",
"OK. Mas eu gostaria de propor um plano.",
"Estou ouvindo.",
"Preciso que você conte ao seu pessoal sobre um grande negócio que está por vir.",
"Eu entendo. Um traidor informará o governador e ele tentará fazer com que um esquadrão punitivo intercepte meus homens?",
"Exatamente!",
"Esse é um bom plano. Mas levarei pelo menos uma semana para implementá-lo.",
"Eu posso esperar. Prepare seus homens.",
"Não seja modesto, #sNathaniel# - estou emocionado com o que você fez, mas agora precisamos ter uma conversa séria.",
"Sim, estou ouvindo.",
"Você cumpriu honrosamente todas as minhas atribuições e, como prometi, pode assumir o lugar de meu assistente.",
"Aceito sua oferta, chefe.",
"Acho melhor eu tomar o seu lugar, seu cachorro!",
"Eu prometi que faria de você meu assistente, mas tenho que decepcioná-lo...",
"Seu desgraçado! Então tenho trabalhado para você por nada? Não, isso não vai funcionar! Defenda-se!",
"É uma pena que você tenha feito ESSA escolha. Tente me matar, mas saiba que meu povo ainda não aceitará você.",
"Quem se importa?!",
"É uma pena que você tenha feito ESSA escolha. Tente me matar, mas saiba que meu povo ainda não aceitará você.",
"Quem se importa?!",
"Estou feliz com isso. Bem, boa sorte para você.",
"Se precisar de alguma coisa, de nada.",
"(Para ambos): Ok, parem de xingar. Quer você goste ou não, vocês estão trabalhando juntos agora.",
"Isso é sorte, muita sorte...",
"Então, sua missão é descobrir onde está agora o esquadrão dessa escória e destruí-lo. E eu imploro a você, durante esta missão, esqueça suas brigas.",
"Tudo bem. Mas se ele me disser mais uma palavra, então não serei responsável por mim mesmo!",
"(Para Barracuda): Barracuda, estou pedindo para você ficar de boca fechada. (Para você): O mesmo vale para você, ",
"OK. Podemos começar?",
"Continuar.",
"...",
"Hmm... Prossiga assim que houver lugar para Barracuda em seu esquadrão.",
"Oh, realmente, não há lugares! Mas vou pensar em algo agora e avisar ao Barracuda quando ele puder se juntar a mim.",
"A propósito, você pode querer mover seus navios para Leviathan Rock. Meus navios se juntarão a você lá. Não queremos que o forte se junte à luta.",
"Certamente não! A frota do governador provavelmente será perigosa o suficiente sem o forte apoiá-la.",
"Bem, #sNathaniel#, onde está sua frota agora?",
"Ainda no porto. Obrigado por me lembrar. Vou voltar para a cidade e mudá-lo agora",
"Em Sunny Haven. Envie seus navios para lá para encontrar os meus.",
"Em Linda Prais. Seus navios também deveriam ir para lá.",
"Em Leviathan Rock, esperando por seus navios.",
"Por quê você está aqui, ",
"? Meu associado relatou que você não estava interessado no que eu queria lhe dizer.",
"Peço desculpas. Eu tinha muita coisa em mente naquela época. A última coisa que eu precisava era de outra tarefa.",
"Isso é compreensível. E aceito suas desculpas. Agora tenho uma oferta para você.",
"Estou ouvindo.",
"Senhor Beckett",
};
