string DLG_TEXT[23] = {

"Sim, #ssir#?",
"Você é um oficial?",
"Eu sou. O que você quer?",
"Pois bem, sou comerciante e enquanto navegava pela costa para visitar esta cidade para vender as minhas mercadorias, vi alguns homens descarregando mercadorias na Bahia de Moa.",
"Podem ser alguns contrabandistas. Vou dar uma olhada. Obrigado pela ajuda.",
"É meu dever ajudar as autoridades espanholas.",
"Ei! O que você está fazendo aqui? E onde estão aqueles homens de quem você estava falando?",
"Eles não existem. Inventei essa história para trazer você para cá sozinho, longe da cidade.",
"E por que isto? Sou um oficial espanhol honesto, então não perca meu tempo, por favor. Minha paciência tem limites.",
"Você entenderá em alguns momentos. Parece que seu governador está preparando algum tipo de ação contra os piratas em #sisland_Turks# e você vai me dizer exatamente o que e quando.",
"Eu entendo, tudo bem. Você é um pirata E um #sgender# estúpido. Você realmente achou que eu viria aqui sozinho? Guardas! Mate esse #sgender#!",
"Má decisão! Você vai se arrepender disso.",
"Pare! Eu me rendo.",
"Ah. Afinal, você é razoável! Agora que você não conseguiu me matar, você vai me dizer o que eu quero saber. A menos que você queira que eu te mate. E não vou falhar como você falhou. Você pode ter certeza disso.",
"Muito bem então. \nMeu governador não está satisfeito com os piratas em #sisland_Turks# e quer capturar a ilha para reduzir a ameaça pirata aos comboios espanhóis.",
"Isso parece uma operação arriscada.",
"Eu sei. Mas nosso governador é uma pessoa ambiciosa e se tiver sucesso, nosso rei irá recompensá-lo com o governo de #sisland_Turks# também.",
"Um governador espanhol na bela ilha pirata de #sisland_Turks#? Isso parece horrível! Quando ocorre a operação?",
"Durante os próximos dias. O governador informará apenas as tropas um dia antes da partida.",
"Ah. Precisarei voltar correndo para #sisland_Turks# então. E você vem comigo. Não vou te matar, mas não posso arriscar que o governador descubra que os piratas da #sisland_Turks# foram avisados de que ele está vindo. Vou deixar você ir assim que esta situação for resolvida.",
"...",
"...",

};
