string DLG_TEXT[114] = {
"Disseram-me que você fez um grande esforço para solicitar uma audiência. Meu nome é ",
". Agora, por favor, diga-me o propósito da sua visita ",
".",
"Meu nome é ",
".",
"Ah, é você de novo. O que traz você aqui desta vez? ",
"Eu gostaria de conversar com você sobre alguns negócios.",
"Sinto muito, mas há coisas que preciso fazer.",
"Então, por que você me distrai dos assuntos de estado muito importantes?",
"Gostaria de falar com você sobre um pequeno negócio.",
"Só estou aqui para prestar meus respeitos. Nada mais, ",
"Nesse caso, por favor, saia do meu escritório e deixe-me voltar para assuntos mais importantes.",
"Sim claro. Desculpe por ter incomodado você.",
"Estou ouvindo, ",
".",
"Estou aqui para receber minha recompensa pela morte de Dirty Garry.",
"Sinto muito, mas não tenho nada para conversar agora",
"Oh, ouvi sobre o que você fez. Da face de toda a colônia eu lhe mostrarei o nosso apreço.",
"Isso mesmo, gostaria de ver uma recompensa.",
"Você é um brincalhão. Ha ha. Aqui está o seu dinheiro.",
"Obrigado, sou seu humilde servo.",
"Então, sobre a aposta que você fez... depois de obter a aprovação do nosso departamento fiscal, vejo que temos... deixe-me ver... seis mil.",
"O que?! O negócio foi de 10 mil!",
"Eu não posso te ajudar. No futuro, tente ficar mais calmo.",
"O que quer que você diga, senhor. Porco sujo....",
", você está ciente de que é acusado de assassinato? Você foi encontrado junto ao corpo da vítima. O que você diz em defesa desta acusação?",
"Não tem nada a ver comigo. O homem já estava morto quando entrei no quarto! Disseram-me que ele estava apenas ferido e que poderia ter algumas informações importantes para mim.",
", Acabei de saber que um homem foi capturado quando tentava deixar a cidade com uma faca manchada de sangue em sua posse. Ele confessou o assassinato de que você foi acusado. Você será liberado imediatamente.",
"Obrigado. Eu sabia que poderia confiar na justiça aqui na #sConceicao#.",
"Desejo desertar para Portugal.",
"De fato? Muito bem, agora você é cidadão português.",
"Agradeço sua infinita gentileza, senhor.",
"Oh sim? Tenho uma proposta para você, capitão.",
"De fato?",
"Vi que você concluiu a tarefa com sucesso; meus parabéns, capitão! Aqui está sua recompensa.",
"Meus agradecimentos; Foi um prazer ajudá-lo.",
"Você deve destruir o ",
" navio ",
"missão pirata",
" ameaçando o envio ",
". Se você afundá-la, vou recompensá-lo com uma boa quantia de ",
" ouro. O que você diz, capitão?",
"Você não ouvirá falar dela novamente, isso eu prometo.",
"Receio não poder ajudá-lo.",
"Anseio por perdão, Excelência.",
"Estou interessado em aprender sobre as relações inglesas com outras nações.",
"Estou procurando uma Carta de Marca.",
"Ah, ",
", que bom que você passou por aqui. Eu gostaria de apresentar meu ",
". Ela virá assim que terminarmos os negócios.",
"Ouvi dizer que estou pronto para uma promoção.",
"Não posso mais servir ",
", vossa Excelência.",
"Cansei de servir ",
"Como garantia de que você é um capitão competente e para recompensar meu tempo apresentando seu caso a ",
", devo te pedir ",
" ouro.",
"Sem chance.",
"Muito bem.",
" tem sempre o prazer de aceitar novos capitães ao seu serviço. ",
"Estamos atualmente em guerra com ",
"",
"nenhum grande poder, mas ",
". Claro, ",
"Os piratas devem sempre ser afundados à primeira vista.",
" À luz do seu serviço anterior ",
" concede a você a classificação de ",
"Vou deixá-lo orgulhoso, Excelência.",
"Você prejudicou ",
", e ",
" não esquece seus inimigos. Saia imediatamente, ou os guardas vão te jogar fora!",
"...",
"Você causou ",
" grande dano, capitão, mas ",
" está disposto a ignorar suas transgressões passadas... por um preço: ",
"Muito bem, senhor. Aceito.",
"É um prazer lidar com você, ",
"E você, Excelência.",
"Você é realmente! Excelente trabalho. Sua nova classificação é ",
". Além disso, você é premiado ",
" hectares de terra por ordem de ",
"Obrigado, senhor.",
"Tem certeza, ",
" lamentaremos perder seu serviço.",
"Sim eu sou.",
" não gosta de vira-casacas ",
"Uh, não importa.",
"Muito bem. Mas espero que você reconsidere, com o tempo...",
"Adeus, ",
"Huh?",
"Difícil.",
"Bem, eu tenho uma missão se você estiver interessado.",
"Talvez. O que é isso exatamente?",
"Há dois meses, um comboio de navios mercantes britânicos partiu de #sisland_Antigua# para navegar para #sisland_Cayman#. Minha filha, Elizabeth, estava a bordo de um dos navios, a fragata 'Relâmpago'. O comboio nunca chegou. Depois de um mês, enviei meu melhor capitão para procurá-la. Mas não ouvi nenhuma notícia do 'Relâmpago' desde então.",
"Então você quer que eu procure a fragata e o comboio? Por que você não envia outro navio seu?",
"Infelizmente não tenho recursos militares para poupar outro dos meus navios. Sendo #sisland_Cayman# uma pequena colônia, eu seria desprezado pelo meu povo se comprometesse a segurança da colônia por uma causa pessoal.",
"Muito bem, senhor. Então agora vamos às coisas que importam. Quanto você vai me pagar se eu trouxer sua filha de volta?",
"Não posso pagar mais do que 40.000 moedas de ouro.",
"Isso parece muito bom para mim. Eu aceito sua oferta. Espere ouvir minhas novidades em breve.",
"Sinto muito, Governador, mas tenho que recusar. Não posso desperdiçar o tempo necessário para tal empreendimento.",
"Muito obrigado! Por favor, faça com que encontrar minha filha seja sua maior prioridade, capitão.",
"Farei o meu melhor, senhor.",
"Eu entendo, capitão. Espero encontrar outro corsário disposto a fazer o trabalho.",
"Boa sorte, governador.",
"Graças a Deus! Você trouxe minha filha de volta!",
"De fato Governador, mas o pirata que sequestrou sua filha também veio para cá!",
"Um oficial me informou da chegada do navio pirata há alguns minutos. Por favor, capitão, ajude meus soldados a repelir o inimigo. Enquanto você luta contra eles, vou esconder Elizabeth em um quarto secreto da residência.",
"Decisão sábia, senhor. Estou indo para o porto agora mesmo!",
"Parabéns Capitão! você fez um trabalho fantástico.",
"Obrigado senhor, essa foi uma missão perigosa.",
"De fato! Elizabeth falou comigo sobre Davy Jones. Esse pirata parece ser o diabo. Felizmente, graças a você, ele não voltará tão cedo.",
"Espero que sim Governador. Agora que a missão está cumprida, tenho outras coisas para fazer, mas primeiro poderíamos falar sobre a recompensa que foi prometida.",
"Sim claro. Conforme combinado, aqui estão as 40.000 moedas de ouro! Obrigado mais uma vez e adeus capitão.",
"Adeus Governador.",

};
