string DLG_TEXT[179] = {
", ",
". Meu nome é ",
". E o seu?",
"Bom dia para você, ",
"! Eu sou ",
". Posso saber o seu nome?",
"Sim Sim, ",
"! O que você quer? Meu nome é ",
".",
"Eu sou ",
", capitão do navio '",
".",
"Meu nome é ",
".",
"Você pode me chamar de capitão ",
".",
"Fico feliz em vê-lo novamente, capitão ",
".",
"Ah. É você de novo ",
". Você tem mais perguntas?",
"Saudações, ",
"!",
"Fico feliz em vê-lo novamente, capitão ",
".",
"Ah, é você ",
". O que você precisa?",
"Saudações, ",
"!",
"Quais são as novidades por aqui?",
"Alguma coisa interessante acontecendo ultimamente?",
"Você poderia me acompanhar nas notícias locais?",
"Você conhece bem a cidade?",
"Não conheço muito bem a cidade. Você poderia me ajudar?",
"Preciso de algumas orientações.",
"Eu gostaria de perguntar sobre alguém que você talvez conheça.",
"Você poderia me contar sobre um dos cidadãos?",
"O que você pode me dizer sobre os habitantes locais?",
"Conte-me sobre sua colônia.",
"O que você sabe sobre #sEleuthera#?",
"Gostaria de algumas informações sobre #sEleuthera#.",
"Nada. Adeus.",
"Você queria perguntar uma coisa, capitão?",
"Prazer em te conhecer. Como posso ajudar, ",
"?",
"Então, capitão... O que posso fazer por você?",
"O que há de novo por aqui?",
"Aconteceu alguma coisa digna de nota ultimamente?",
"Eu só gostaria de ouvir as últimas fofocas.",
"Você poderia me mostrar o caminho para...",
"Eu sei onde preciso ir, mas não tenho certeza do caminho",
"Preciso de ajuda para me locomover pela cidade.",
"Estou interessado em um dos locais.",
"Estou à procura de alguém. Talvez você o conheça?",
"Você poderia me contar sobre um dos habitantes locais?",
"Conte-me sobre a colônia.",
"O que você sabe sobre #sEleuthera#?",
"Eu gostaria de perguntar sobre #sEleuthera#.",
"Apenas olhando por aí. Adeus.",
"Eu vejo. Deixe-me perguntar outra coisa.",
"Obrigado. Adeus.",
"Estou ouvindo, ",
".",
"Sim, ",
"?",
"Você gosta de conversar, né ",
". Bem, pergunte.",
"O que há de novo por aqui?",
"Alguma coisa interessante acontecendo ultimamente?",
"Você poderia me acompanhar nas notícias locais?",
"Não conheço muito bem a cidade. Você poderia me ajudar?",
"Preciso de algumas orientações.",
"Você poderia me mostrar como chegar a...",
"Você poderia me contar sobre um dos habitantes locais?",
"Estou interessado em um certo cidadão que você talvez conheça.",
"Conte-me sobre os habitantes locais.",
"Conte-me sobre sua colônia.",
"O que você sabe sobre #sEleuthera#?",
"Deixe-me perguntar uma coisa sobre #sEleuthera#.",
"Deixa para lá. Adeus.",
"Quem é que queres dizer, ",
"?",
"Então, sobre quem você quer saber?",
"Gostaria de saber quem poderia atrair sua atenção em #sisland_Elethera#, capitão ",
"?",
"O governador, ",
"Cole Arkwright",
"Cole Arkwright",
".",
"O estalajadeiro, ",
"Brian Armstrong",
"Brian Armstrong",
".",
"O proprietário do estaleiro, ",
"Philippe",
"Philippe",
".",
"Um comerciante chamado ",
"Fox Ratter",
"Fox Ratter",
".",
"Deixa para lá. Desculpe incomodá-lo.",
"Infelizmente, embora o nosso governador seja realmente um bom homem, falta-lhe força de vontade. Um governador mais enérgico faria a nossa colónia sentir-se mais segura e os nossos mercadores poderiam negociar em condições mais lucrativas. Além disso, nosso forte precisa de reparos.",
"Eu vejo. Tenho outra pergunta, se não se importa.",
"Obrigado. Adeus.",
"O que posso dizer sobre ele? Ele é um pouco covarde e não tão inteligente. Além disso ele é muito ganancioso! Embora ele sempre saiba todas as novidades.",
"Eu vejo. Tenho outra pergunta, se não se importa.",
"Obrigado. Adeus.",
"Ele é um bom homem, embora digam que ele é muito duro. Dizem que ele troca de funcionários com frequência. Mas ele realmente conhece seus navios.",
"Eu vejo. Tenho outra pergunta, se não se importa.",
"Obrigado. Adeus.",
"Apenas me diga onde você precisa ir ",
".",
"Tudo bem, ",
". Onde você quer ir?",
"Fico feliz em ajudar ",
".",
"Onde fica a taberna?",
"Onde fica o estaleiro?",
"Onde posso vender meus produtos?",
"Pegue a rua à direita das duas que começam no portão do porto e logo você verá a taberna.",
"Obrigado. Adeus.",
"E onde fica o estaleiro?",
"Onde posso vender meus produtos?",
"O escritório do estaleiro fica bem em frente ao portão do porto ",
". Você não pode perder.",
"Obrigado. E como encontro a taberna?",
"Onde posso vender meus produtos?",
"Obrigado pela dica. Isso é tudo que eu precisava.",
"Vá para a direita do portão do porto. Você não pode perder. ",
"Fox Ratter",
"Fox Ratter",
"A loja fica perto da taverna.",
"Como posso encontrar o estaleiro?",
"Como posso encontrar a taberna?",
"Eu vejo. Obrigado.",
"Bem, eu não sei... O que você quer ouvir?",
"O que lhe interessa em particular, capitão?",
"O que você gostaria de saber, ",
"?",
"Conte-me sobre a história da colônia.",
"Existem outras cidades nesta ilha?",
"Você sabe alguma coisa sobre o forte que protege a cidade?",
"Deixe-me perguntar outra coisa.",
"Você veio até aqui só para aprender a história local? Bem, tudo bem. A colônia foi fundada há 54 anos.\nEles encontraram ricos depósitos minerais na ilha, e a cidade cresceu gradualmente. Estamos indo muito bem atualmente.",
"Por favor continue.",
"De fato. Deixe-me perguntar outra coisa.",
"Nunca foi exatamente pacífico por aqui. Esta terra lembra mais do que a sua cota de batalhas.",
"Eu vejo. Posso te perguntar outra coisa?",
"Ouvi rumores de que algum nobre comprou uma casa na selva, e ninguém viu esta casa, nem viu este nobre.",
"Me diga mais.",
"Toda a ilha está coberta por uma densa selva. As costas são rochosas e existem muitos recifes. Porém, também temos outra cidade bem pequena nesta ilha, #sAlice#, eu fui lá uma vez, estava tudo bem, eu acho...",
"Eu vejo. Me diga mais.",
"Não há muito mais para contar além de #sAlice#, que na verdade não é uma cidade grande. Selva e rochas - assim como todas as outras ilhas. Tudo o que vale a pena está dentro das muralhas da cidade.",
"Continuar...",
"Eu vejo. Deixe-me perguntar-lhe outra coisa, se me permite.",
"Para ser sincero, capitão, não sei nada sobre o forte local.",
"Bem, deixe-me fazer outra pergunta, se não se importa.",
"Nosso forte foi construído em tempos mais prósperos, e eles realmente fizeram isso direito. Mesmo agora, é uma estrutura formidável, embora tenha passado por muita coisa. A guarnição também é bastante impressionante - cerca de 1.500 homens.",
"Eu vejo. Me diga mais.",
"Não tenho certeza se deveríamos estar falando sobre o forte. E se você for um pirata e planeja atacá-lo?",
"Tudo bem. Vamos falar de outra coisa então.",
"Eu vejo. Vamos tentar outro assunto então.",
"Existe um ferreiro nesta cidade?",
"Não #ssir#, peço desculpas.",
"E outra coisa, #ssir2#.",
"Hum, isso é tudo, pessoal.",
"Esta minha lâmina não serve para arrancar marcas do traseiro de um macaco cego. Conhece alguém que poderia trazer isso à tona?",
"Desculpe, não há ferreiro aqui...",
"Esplêndido. Muito.",
"E onde fica o estaleiro?",
"Onde posso vender meus produtos?",
"Temos uma população de",
"cidadãos.",
"? Eh, ele é um homem recluso. Não sei muito sobre ele...",
"Existe algum lugar onde eu possa pedir emprestado ou economizar algum dinheiro?",
"Sim, #susurer# é o agiota local, mas me disseram que ele é um sujeito decente.",
"Por enquanto é tudo, obrigado.",
"Ah, a taberna. Sim, você sobe e passa pela porta que dá para a cidade.\nVire-se e você deverá estar olhando diretamente para a porta da taverna.",
"Um cara sábio, hein? Adeus!",
};
