string DLG_TEXT[18] = {
".....",
".....",
"Quando navegaremos para #sPhilipsburg#?",
"Nunca.",
"O que?! Mas esse assassino me disse que você estava me levando para #sPhilipsburg#.",
"Você não parece gostar de Davy Jones.",
"Você está brincando? Eu nunca vou amá-lo.",
"Facilmente adivinhado.. Na verdade, estou trabalhando para seu pai e estou aqui para resgatar você.",
"DEUS TE RECOMPENSE!",
"Neste caso, será seu pai. Mas não devemos perder tempo, precisamos navegar para #sisland_Cayman# o mais rápido possível. Eu não acho que seu 'amante' desistirá de você tão facilmente.",
"Finalmente você acordou.",
"Sim, mas o que aconteceu?",
"Você não se lembra?",
"OOOhhh sim, Davy Jones atirou em mim.",
"Na verdade, mas a bala, felizmente, apenas arranhou sua cabeça e você desmaiou.",
"Compreendo...e Davy Jones?",
"Ele rapidamente deixou a ilha. E pouco depois a guarnição do forte chegou ao porto e viu você estirado. Agora você parece estar recuperado, você deveria ir à prefeitura e falar com meu pai. Ele tem sua recompensa esperando por você.",
"Isso é uma boa notícia!",

};
