string DLG_TEXT[63] = {
"....",
"....",
"Olá, capitão! Prazer em conhecê-lo.",
"Olá, Srta. Swann. Desculpe-me por lhe dizer, mas parece que já ouvi seu nome.",
"Talvez você tenha conhecido meu pai, Weatherby Swann, no passado. Ele era governador de #sRedmond# antes da chegada de Lord Cutler Beckett.",
"e o que a filha de um governador faz em #sTortuga#?",
"Will e eu tivemos que fugir de #sisland_Redmond# para não sermos presos por Lord Beckett. Ele injustamente acusou a nós e meu pai de traição.",
"Ok, eu entendo.",
"Capitão, seria melhor não perder mais tempo. Você pode ir para seu navio. Nós nos juntaremos a você.",
"Muito bem.",
"Agora, sabemos que a ilha não está deserta.",
"Sim, e parece ser perigoso. Temos que estar atentos. Vamos continuar nossa caminhada.",
"O porto parece estar calmo. Até a frota espanhola não tem tripulação no momento.",
"Realmente estranho... A única coisa que temos certeza é que o comboio prateado não chegou...",
"A prata está carregada, capitão.",
"Ótimo! Vamos navegar para #sTortuga#. Temos negócios a fazer lá.",
"Capitão, fiquei feliz em trabalhar com você. Talvez nos encontremos novamente...",
"Talvez. Adeus, Srta. Swann.",
"Pirata sem Deus Barbossa!",
"Essa é a segunda vez que vejo aquele homem tomar meu navio.",
"Você ficou abandonada aqui uma vez antes. Podemos escapar da mesma forma.",
"Para que ponto e propósito, jovem senhorita? O #scursed_ship# se foi. A menos que você tenha muitas velas escondidas naquele corpete - improvável - o jovem Turner estará morto muito antes que você possa alcançá-lo.",
"Mas, você é o capitão ",
"E o quê?",
"Muito bem, em vez de brigar, deveríamos explorar esta pequena ilha, certo?",
"Como você quiser! Agora, temos tempo.",
"Foi uma luta difícil!",
"De fato. Como você veio parar aqui? Pensei que você ficaria a bordo do Dauntless?",
"Eu fugi logo depois que você deixou o navio. Não pude deixar Will sozinho.",
"Obrigado por me resgatar. Meu pai ficará tão grato quanto eu.",
"Seu colar, é um design tão incomum. Onde você o conseguiu?",
"Oh! Eu... er... peguei em algum lugar, não me lembro.",
"Interessante...",
"Assim como é meu lugar com Will.",
"[Will] Oh! ... Elizabeth... (suspiro!)",
"Oh! ... Will... (suspiro!)",
"Oh, arrume um quarto!",
"Bem... pelo menos consegui ajudar. Fiz uma fogueira do outro lado da ilha, com o rum que você tinha, e a fumaça disso atrairá a frota inglesa.",
"O QUÊ! MEU RUM! O que você está fazendo, mulher! Temos que ir lá, rápido!",
"James Norrington. O que o mundo fez com você?!",
"Elizabeth?! Senhor Gibbs, esconda o rum... Venha se juntar à minha tripulação, moça? Bem-vinda a bordo.",
"Estou aqui para encontrar o homem que amo... Quer dizer, William Turner, Capitão Sparrow.",
"Isso é legal e tudo, mas vamos mudar essa conversa para algum lugar mais privado... como meu navio, oh, e trazê-lo também... [Olha para James Norrington no chão]",
"Jack, ainda preciso de respostas.",
"Sabe, essas roupas não lhe favorecem em nada. Deveria ser um vestido ou nada.",
"Eu sei que Will veio para encontrá-la. Onde ele está?.",
"Querida, estou realmente infeliz por ter que lhe contar isso, mas... por uma série infeliz e *totalmente* imprevisível de circunstâncias que não têm nada a ver comigo, o pobre William foi forçado a entrar na equipe de Davy Jones...",
"Jack. Tudo o que eu quero é encontrar Will.",
"Você tem certeza? É isso que você realmente mais quer?",
"Claro.",
"Porque eu acho que você gostaria de encontrar uma maneira de *salvar* Will ao máximo.",
"E você tem uma maneira de fazer isso?",
"Bem, há um baú... Um baú de tamanho e origem desconhecidos. Que contém o coração ainda batendo de Davy Jones. E quem possui esse baú possui a alavanca para comandar Jones a fazer o que ele ou ela quiser, incluindo... salvar o bravo William de seu destino sombrio.",
"Como o encontramos?",
"Com isso. Minha bússola... é única.",
"Única aqui tem o significado de quebrada?",
"Verdade. Esta bússola não aponta para o norte.",
"Para onde ela aponta?",
"Ela aponta para a coisa que você mais quer neste mundo.",
"Oh Jack! Você está dizendo a verdade?",
"Cada palavra, amor. E o que você mais quer neste mundo é encontrar o baú de Davy Jones, não é?",
"Salvar Will?",
"Encontrando o baú de Davy Jones.",
};
