string DLG_TEXT[62] = {
"Parar! Larguem suas armas! Levante-se e entregue-se, ou morra!",
"Ei, viajante! Desacelerar! Queremos dar uma olhada na sua bolsa!",
"Pare, você! Pague o pedágio se quiser passar!",
"O que é esse absurdo?",
"O que é?",
"O que você quer dizer?",
"Bandidos! Bem, o crime deve ser punido. Às armas!",
"Não tenho estômago para salteadores comuns, especialmente os desleixados. En garde!",
"Vou arrancar seu coração por sua insolência!",
"Ah, #spronounsubj# não entende! É simples: você nos dá todo o seu ouro e nós deixamos você viver!",
"Você nunca ouviu falar em 'despesas de viagem'? Bem, somos nós. Agora separe seu ouro, ou separe sua cabeça!",
"Vou traduzir para os marinheiros estúpidos: Dê-nos todo o seu dinheiro, amigo! Adoramos os dobrões e as peças de oito!",
"Seus malditos sarnentos! Eu tenho apenas ",
" ouro.",
"Não vou entregar meu ouro sem lutar!",
"Ei, não fique animado! Eu estava apenas brincando. Vá em frente, agora!",
"Nesse caso, mudamos de ideia. Você pode ir.",
"Você é um #sgender# corajoso, então vamos deixar você ir! Mas não nos deixe pegar você de novo",
"Bem, até logo, então!",
"Você deveria parar com esse negócio imundo. Você não é muito bom nisso. Adeus!",
"Você tomou uma decisão sábia. Adeus!",
"Agora é tarde demais para desistir - você tem um encontro marcado com seu criador!",
"Tornando-se covardes, rapazes? Mas não posso deixar você ir agora!",
"Não vou a lugar nenhum até terminar isso.",
"Tudo bem. Você teve sua chance. Agora você vai morrer!",
"Ok, agora você me deixou bravo. Morrer!",
"O que?! Teremos coragem para ligas!",
"Tente!",
"Tudo bem! Dê-me eles e você pode ir!",
"Bem, hoje é o suficiente para comprar a sua vida. Você pode ir.",
"Deixe-me dar um conselho grátis: se você é um alvo tão fácil, não deveria ficar vagando pela selva! Fique no porto e beba seu rum. Você viverá mais.",
"Explodir todos vocês!",
"Você me parece um #sgender# mais rico do que isso. Mas está tudo bem. Quando terminarmos com você, vamos virar você de cabeça para baixo e ver o que acontece!",
"Maldição!",
"Você novamente?! Você deveria estar correndo como se o diabo estivesse te perseguindo! Caso contrário, poderemos mudar de ideia sobre deixá-lo ir.",
"Você veio compartilhar mais ouro conosco? Que gentileza sua!",
"Só direi uma vez: saia da minha frente antes que eu te derrube!",
"Sim Sim! Estou de saída.",
"Não quero mais problemas com vocês, terríveis rufiões - então decidi me livrar de vocês!",
"O que você quer de nós? Nós deixamos você ir!",
"Deixe-nos em paz, #slad#. Nós temos o nosso negócio; você tem o seu. Vamos deixar tudo em paz.",
"Desaparece, #slad#! Você realmente quer se desfazer do seu dinheiro?",
"Tudo bem. Vou.",
"Eu decidi puni-lo por suas más ações!",
"Me deixe em paz!!! Sair!!! Eu quero viver!!!",
"Me ajude!!! #spronounsubj# é um maníaco!!! Não me mate!!!",
"Me poupe! Eu sou apenas um ladrão modesto! Sou muito jovem para morrer!",
"Se você ficasse em casa, viveria mais!",
"Por que você desperdiça seu tempo e talento assaltando viajantes sem dinheiro como eu? Você poderia ganhar muito mais ouro saqueando grandes navios mercantes. Junte-se à minha tripulação corsária e em breve você estará nadando no mar... eh.. em ouro, quero dizer.",
"Má sorte para você, deixei todo o meu dinheiro no meu navio. Você pode conseguir um pouco disso, mas apenas se me fizer um favor em troca: preciso desesperadamente de pranchas para meu navio e estou disposto a pagar um preço alto. Por que você não derruba algumas daquelas árvores para mim? Será mais fácil do que derrubar-me, porque as árvores dificilmente resistem.",
"Bem, um cruzeiro pelo Caribe seria uma boa mudança nesta selva infestada de febre. Está combinado, vamos nos juntar a você, e aposto que alguns de nossos... eh... colegas certamente vão gostar de se juntar a você também.",
"Quanto mais melhor. E agora fique animado, pegue seu material e seus.. eh.. colegas e me encontre em meu navio, o ",
". Até mais, amigos! (Bem, com essa escória a bordo, o moral da tripulação certamente despencará. Mas um pouco de broca e ouro resolverão isso.)",
"O que? Você está sugerindo seriamente que estragamos nossa reputação fazendo um trabalho honesto? Hmm... Por outro lado, se você pagar e prometer não contar a ninguém sobre nossa desgraça...",
"Vamos fingir que você corta árvores apenas para praticar cerca com machado. E agora fique animado, corte um pouco de madeira e entregue no meu navio, o ",
". TIMMBEEEER, lenhadores!",
"Você é um cara muito durão. Quer saber, ensinaremos um pequeno truque se você nos deixar ir. ",
"Bem, isso salvará sua pele desta vez.",
"Acho que esta lâmina precisa de um pouco mais de prática e acabei de encontrar um objeto legal para praticar.",
"Mas isso vai custar-lhe",
"moedas de ouro",
"Você é uma garota muito durona. Quer saber, ensinaremos um pequeno truque se você nos deixar ir. ",
};
