string DLG_TEXT[52] = {
"Ei, ",
", seu desgraçado! Finalmente consegui você! Lembre-se de como você uma vez teve minha pele açoitada por 'insolência'... Agora vou te dar insolência!",
", você não escapará da minha vingança desta vez. Você vai se arrepender de ter cortado minhas bolas por estuprar aquela freira... Eu já a matei e agora vou matar você!",
"Ha, o #sgender# que eu mais odeio - Capitão ",
"! Você sabe o que me manteve vivo na rocha desolada em que você me abandonou? O desejo de te matar um dia... ESTE dia!",
"Eu deveria ter matado você naquela época, quando você era uma presa fácil..",
"Aí vem o castigo severo pelos pecados da minha juventude...",
"Um feio inimigo de um passado feio...",
" velho companheiro! Finalmente encontrei você! Har, os bons e velhos tempos.. A diversão que tivemos! Lembre-se de como amarramos aquele comerciante gordo ao pátio principal.. com as próprias entranhas da barriga dividida.. HARHARHAR",
" amigo antigo! Prazer em conhecê-lo mais uma vez. Ah, se pudéssemos navegar juntos mais uma vez e nos divertir como nos bons velhos tempos. Lembra como forçamos aquele padre a ceder o tesouro de sua igreja? Como usamos suas próprias pinturas de mártires torturados como exemplos para torturá-lo.. HARHARHAR",
"Agora, se esse não é meu antigo companheiro de bordo ",
"! Senti sua falta, nunca me diverti tanto como quando navegamos juntos. Lembra como invadimos as muralhas de Puerto Bello enquanto usávamos aquelas freiras purificadas como escudos vivos? Como os Dons atiraram em nós de qualquer maneira, mas a maioria das balas ficou presa nessas irmãs sagradas.. HARHARHAR",
"Ah, sim.. BRUHAHAHA Foi uma piada hilariante.. Não éramos um bando de brincalhões, hehe? Devíamos escrever um livro sobre as nossas acrobacias.",
"Sim, eu me lembro... e essa lembrança me faz estremecer de vergonha! Mas, ao contrário de você, mudei minha vida maligna para melhor: hoje em dia eu luto contra piratas!",
"Com licença, senhor, nunca o vi antes e NUNCA fiz nada parecido. Bom dia.",
"O que? EU navegando com você? Nunca! Sou um comerciante honesto e nem vou FALAR com sua espécie!",
"Umm.. err.. você deve me confundir com outra pessoa. Tenho CERTEZA que NUNCA nos conhecemos antes!",
" Então lutaremos, porque não desprezo nada mais do que um traidor hipócrita!",
"Então você não aprendeu nada com seus erros? Então terei que te ensinar uma lição agora...",
"Sou apenas um escrivão do comandante.",
"Não vou estragar o fio da minha espada nos ossos de um escriturário. Aposto que vou precisar desesperadamente de uma lâmina bem afiada atrás da próxima porta...",
"Um escriturário, hein? Suas roupas parecem muito caras para um balconista. Você provavelmente tem acesso ao baú de guerra da guarnição, hein? Bem, entregue-me ou estragarei seu casaco... COM CLERKSBLOOD!",
"Oh, temo que não seria um livro popular. As pessoas têm tantas ilusões românticas sobre a pirataria que provavelmente não querem ouvir que os piratas estavam mais ocupados com estupro e tortura do que com lutas heróicas\nFalando nisso, você tem trabalho para um lutador? Estou meio desempregado no momento. Para um velho amigo como você, eu até perderia a recompensa de contratação habitual.",
"Umm.. desculpe, meu navio está absolutamente abarrotado de homens no momento.. Mas talvez em outra hora.. Manteremos contato, até então!",
"Eu ficaria muito feliz em ter um cara durão como você comigo. Pegue seu material e junte-se a mim.",
"DLG_TEXT[25]",
"DLG_TEXT[26]",
"DLG_TEXT[27]",
"DLG_TEXT[28]",
"DLG_TEXT[29]",
"DLG_TEXT[30]",
"DLG_TEXT[31]",
"DLG_TEXT[32]",
"DLG_TEXT[33]",
"DLG_TEXT[34]",
"DLG_TEXT[35]",
"DLG_TEXT[36]",
"DLG_TEXT[37]",
"DLG_TEXT[38]",
"DLG_TEXT[39]",
"DLG_TEXT[40]",
"DLG_TEXT[41]",
"DLG_TEXT[42]",
"DLG_TEXT[43]",
"DLG_TEXT[44]",
"DLG_TEXT[45]",
"DLG_TEXT[46]",
"DLG_TEXT[47]",
"DLG_TEXT[48]",
"DLG_TEXT[49]",
"DLG_TEXT[50]",
"DLG_TEXT[51]",

};
