string DLG_TEXT[100] = {
"Bem-vindo à minha humilde casa. Eu sou ",
"Ah, um visitante! Entre, entre. Meu nome é ",
"Entre e sente-se perto do fogo. Você veio para a casa de ",
"Obrigado e olá. Eu sou ",
"e tenho o prazer de conhecê-lo",
"Bem cumprido, ",
"Olá de novo, ",
". O que te traz aqui?",
"Estou ferido. Pode me ajudar?",
"Eu adoraria conversar um pouco...",
"Estou com vontade de conversar. Você tem tempo para bater um papo?",
"Tenho algum tempo livre e gostaria de gastá-lo em companhia amigável.",
"Ah, já é tão tarde? Eu tenho que ir, adeus.",
"Ah, você está horrível! Hmm, febre, membros inchados, escurecimento ao redor dos ferimentos... Você está com gangrena! Bem, essa é uma doença bastante comum entre os marinheiros hoje em dia. Não é de admirar, dadas as nossas condições sanitárias, e o clima tropical também não ajuda. Como todos sabem, todas as doenças são transmitidas pelo ar poluído e pelos vapores. E desses temos muitos aqui. Bem, basta aceitar a doença como um facto da vida do século XVII e rezar para que...",
"Não preciso de uma palestra médica sobre gangrena, preciso de uma cura para ela, e rápido!",
"Ei, espere, velho tagarela! Já lhe ocorreu que estou prestes a morrer? ME AJUDE!",
"Uma maldição para o capitão do sofá que trouxe esta doença para cá! Mas, caramba, todo infortúnio pode ser transformado em uma vantagem se você aceitar o desafio com o espírito certo. Não vamos perder um minuto choramingando, mas procuremos alguma cura. IMEDIATAMENTE!",
"Você é um convidado bem-vindo e eu adoraria ouvir as histórias de um marinheiro...",
"E eu gostaria de ouvir sobre os últimos escândalos da cidade...",
"Então vamos abrir esta garrafa e nos acalmar....",
"Ah, que terrível! Limparei e tratarei suas feridas, e então você ficará na cama até amanhã. Você precisa de um descanso, acredite",
"Obrigado, você é muito gentil. Droga, estou cansado, acho que vou dormir já...",
"Fascinante! Por favor, continue...",
"Mais interessante! Me diga mais...",
"Eu não acho que posso esperar tanto tempo. Obrigado, mas devo ir embora.",
"Calma, ainda tenho o armário de remédios da minha falecida mãe. Aqui, olhe para todos aqueles frascos: algo certamente irá curá-lo, mas não tenho ideia do que significam todos esses nomes estranhos. Você deve decidir o que colocarei em suas feridas gangrenosas!",
"Felizmente comprei recentemente um armário de remédios. Foi uma verdadeira pechincha, pertenceu a um cirurgião espanhol que morreu de... eh, ehem... gangrena. Mas não importa, existe uma variedade tão impressionante de frascos com nomes científicos que um deles certamente será adequado para tratamento de feridas. Mas qual deles?",
"Bem, no ano passado comprei um armário de remédios, mas nunca o usei. Esqueci que não sei ler... Mas com certeza você conseguirá escolher o remédio certo. Aqui, dê uma olhada nos rótulos...",
"28",
"Fora! Fora, eu digo, antes que você deixe a casa fedorenta! Não teremos piratas aqui...",
"Seria difícil piorar o fedor. Mas eu vou embora.",
"Ei, o que VOCÊ está fazendo aqui? Este não é lugar para corsários de má reputação. Sair!",
"Bah, eu não ficaria neste barraco fedorento de qualquer maneira.",
"Ah, é VOCÊ! Sua reputação não é das melhores. Tire sua bunda da minha casa!",
"Relaxar! Estou indo embora. Talvez você seja mais sensato depois...",
"Você passou a noite bem cuidado e se sente melhor.",
"Mas seu anfitrião parece cansado. Você deveria se despedir agora!",
"Você conversa por horas e aprende muito sobre a cidade.",
"Pegue o etanol.",
"Use o isopropil.",
"vinagre é isso.",
"Vamos tentar o mercúrio.",
"Hamamelis Virginia parece bom.",
"Experimente Cera Alba.",
"Use o potássio.",
"Chamberlye é.",
"Que tal sódio.",
"Maldito seja seu lixo de remédios charlatães! Antes de morrer, prefiro tentar minha própria mistura médica! ",
"Boa ideia! Deite-se agora e deixe-me cuidar de seus ferimentos, e pela manhã você estará apto para massacrar esqueletos piratas às dúzias novamente. ",
"Esqueletos piratas? Bah, você está tentando me acalmar com contos de fadas? Não se preocupe, já estou dormindo... ",
"Espero não acordar como esqueleto pirata... ",
"Espero que você saiba o que está fazendo...",
"Você tem uma casa tão linda aqui, seria uma pena se ela pegasse fogo esta noite, não é, né? E as casas queimam tão facilmente, certo? Bastaria um fósforo minúsculo como este aqui para transformar sua casa em uma pilha de cinzas, ou até mesmo em sua própria pira, entendeu? Mas não se preocupe, você só precisa me pagar 1000 gold e eu me certificarei de que nada acontecerá com você, entendeu?",
"Mas eu não entendo por que pagar Ouro para você me protegeria de tal acidente?",
"Você fala em enigmas, cara! O que minha segurança tem a ver com você?",
"Mas sempre tomo muito cuidado com o fogo, tenho certeza que nada vai acontecer.",
"Você é realmente tão burro? Se você não me pagar, sua casa vai pegar fogo. Tenho agora?",
"Estou falando de um acidente MANMADE, idiota! Para não dizer PRIVATEERmade.",
"Escute, você não pode vigiar sua casa o tempo todo, enquanto eu poderia voltar A QUALQUER MOMENTO...",
"Ah, entendi! Você quer extorquir dinheiro de proteção de mim! Bem, por que você não disse isso em palavras claras, tais demandas são comuns aqui. Bem, estou disposto a pagar, embora não tenha 1000 Gold. Mas você pode pegar tudo que encontrar no meu peito, certo?",
"Hmm, bem, antes que eu perca mais tempo chantageando alguém que é burro demais para ter medo, vou pegar o que você tem...",
"O QUE? Você está tentando me ameaçar? Não, você não vai extorquir nada de mim, mesmo que me mate! E farei com que todos aqui saibam em breve o RASCAL que você é!",
"SUSPIRAR! Eu desisto, você é burro demais para ser ameaçado.",
"Ainda não vejo como você poderia me proteger do fogo. Você está no mar a maior parte do tempo.",
"Oh, você está realmente me confundindo, cara. Você é o novo inspetor de incêndio ou o quê?",
", você ainda não me convenceu totalmente da conexão lógica entre a potencial perda de valor do meu imóvel e a obtenção de um subsídio financeiro não insubstancial em benefício de sua pessoa... Ah, agora você vê que discurso confuso significa!",
"Grrr... VOCÊ NãO PAGA CASA FINITO!",
"Ah, por favor, você não lê nenhum romance mafioso? Eu devo fazer uma ameaça velada e vaga e você deve fazer uma cara de horror e pagar.",
"Lembre-se de que esses incêndios geralmente começam embaixo da cama do proprietário. Mas aposto que seu idiota nem acordaria",
"Tenho um problema com os guardas da cidade...",
"Ah, sim, os guardas São um problema... Eles não passam de um bando de preguiçosos e covardes corruptos. Apenas a pior escória dos exércitos europeus se oferece como voluntária para servir nestas colónias esquecidas por Deus. Costumam fechar os olhos se houver briga, só interferem se algum cidadão influente estiver sendo atacado. Mas se eles se sentem ameaçados, eles contra-atacam com medo cego e atacam qualquer um que empunhe uma lâmina, muitas vezes confundindo amigos e inimigos em seu pânico. Mas qual é exatamente o seu problema com eles?",
"Ah deixa pra lá! Resolverei meus problemas do meu jeito",
"Eu gostaria que eles me protegessem daqueles criminosos de rua importunos que enxameiam as ruas hoje em dia. Eles se tornaram uma verdadeira praga ultimamente, maldito capitão de sofá que os trouxe aqui... E os guardas não levantam um dedo para me ajudar!",
"Eles parecem pensar que sou um criminoso. Eles continuam atrás de mim.",
"Bem, o que você espera? Você é um estrangeiro para eles e parece um malandro... Mas conheço muito bem o comandante da guarda municipal, acho que posso fazer algo por você. Se você me der 100 Gold eu passo para ele, e isso certamente melhorará sua relação com os guardas.",
"Obrigado, mas não quero ser um trapaceiro. Posso me dar bem com aquele bando de militares idiotas sem desperdiçar meu dinheiro em subornos. ",
"Ah, sim, por favor, vá falar com o comandante. Os guardas podem ser incompetentes, mas são tantos... Vou esperar aqui até você falar com ele.",
"Tudo bem, eu poderia convencer o comandante de que você é um cidadão honesto e digno de proteção. Mas você não deve causar qualquer agitação e luta, e se estiver envolvido nos esquemas de algum poder hostil, será tratado como qualquer outro traidor.",
"Ah, fico muito grato pela sua mediação. Obrigado e adeus.",
"79 ",
"Você tem um emprego para um espadachim competente?",
"Você sabe como alguém com boas habilidades de luta poderia ganhar algum dinheiro?",
"Já te disse que sou o melhor guarda-costas da cidade? Você conhece alguém que precisa de proteção?",
"Que bom que você pergunta. Recentemente houve casos de assaltos no bairro. Alguém invadiu várias casas levantando telhas do telhado e subindo no sótão. Você protegeria minha casa esta noite? Amanhã você receberá uma bela recompensa pelo café da manhã.",
"Eu certamente dormiria melhor se você guardasse minha casa esta noite. Os tempos não são seguros e esses guardas estúpidos são incapazes de manter a ordem. Ainda ontem uma multidão ateou fogo ao sótão de uma casa no beco porque o proprietário se recusou a pagar o dinheiro da proteção. Você protegeria minha casa esta noite? De manhã eu vou recompensá-lo generosamente.",
"Bem, você poderia me proteger esta noite contra uma multidão de bandidos que aterrorizam a vizinhança. Você acredita, há duas noites eles subiram pelo telhado e atingiram a janela do quarto do pobre pároco William, espancaram-no e abusaram de sua esposa. Tempos terríveis! Sua presença me faria dormir muito melhor, e pagarei pelo seu esforço.",
"É claro que protegerei um amigo em perigo. Fique tranquilo, você estará perfeitamente seguro esta noite.",
"Não se preocupe, passarei a noite e você estará perfeitamente seguro.",
"Nenhum bandido ou ladrão se atreverá a entrar nesta casa enquanto eu estiver aqui. Tenha uma boa noite.",
"Bem, já está amanhecendo. Obrigado por ficar comigo a noite toda.",
"Ah, o céu já está ficando cinza. Parece que conseguimos passar a noite. Sua presença foi um grande conforto, muito obrigado.",
"Finalmente é de manhã! Sua presença parece ter salvaguardado minha propriedade. Você é um excelente guarda-costas.",
"Ah, não mencione isso. Eu teria guardado sua casa mesmo se você não tivesse me prometido uma RECOMPENSA.",
"Ah, isso me lembra, eu prometi a você uma recompensa... Eh... Receio não ter dinheiro suficiente para pagar um guarda-costas. Mas pegue esta joia. Pertenceu à minha falecida mãe, e eu meio que me apego a ele, mas você certamente merece uma recompensa por arriscar sua vida por mim.",
"Ah, isso me lembra, eu te prometi uma recompensa... Eh... Ei, por que os cachorros estão fazendo tanto barulho? Há alguém no jardim? Ou mesmo no telhado?",
"Ah, sim, sua recompensa, que tal... Espere! Aquele barulho no sótão é alto demais para ser dos ratos...",
" Ei, que som é esse? Este arranhão, como um pé-de-cabra na madeira... as tábuas do telhado...",
"O que? ONDE?",
"Muito obrigado. Manterei essa joia em honra e alta estima como um símbolo de nossa amizade de armas. (Eu me pergunto quanto dinheiro isso renderá no junkman...) ",
"Ah, eu simplesmente não posso tirar a lembrança da sua família. Fique com isso, foi um prazer ajudá-lo.",

};
