string DLG_TEXT[71] = {
"Ele, o que VOCÊ está fazendo nesta fortificação secreta do Exército! Você é um espião?",
"Por favor, poupe minha vida, eu imploro! Eu sou um civil!",
"Me deixe em paz! Eu não pertenço a esses brutos de uniforme!",
"Apenas fique quieto e se perca!",
"Cale-se! Devo seguir antes que os reforços cheguem!",
"Saia do meu caminho! Tenho alguns homens de verdade para lutar!",
"Shhh! Você parece um sujeito inteligente para mim, cara. Você e eu vamos saquear lojas e baús deste lugar, hein? . *PISCAR*",
"Eu vou te cortar em pedaços se você der o alarme! Faça o que eu digo e você ficará inteiro",
"Faça o que eu quiser ou você morrerá!",
"Só pouparei sua vida miserável se você cooperar!",
"Calma, amigo! Pareço alguém que prejudica civis? Confie em mim, vamos nos dar bem.",
"Tudo bem, tudo bem! O que você quer?",
"Acredite em mim, não farei nada precipitado se você também não fizer isso. Mas o que você está fazendo?",
"Entendi! Então o que vem depois?",
"Você certamente não parece um soldado. Quem é você?",
"Diga-me, o que um civil está fazendo neste forte tão secreto?",
"Eu só quero saber, qual é o seu negócio aqui?",
"Sou um enviado do Secretário da Guerra de Sua Majestade e estou aqui para inspecionar essas fortificações.",
"Portanto, seja MEU enviado agora e diga ao governador que exijo a rendição imediata e incondicional da cidade, ou irei bombardeá-la com essas mesmas armas. Tenho excelentes artilheiros em minha tripulação, e eles transformarão a prefeitura em um monte de escombros.",
"Deixo você viver se me mostrar onde sua bolsa está escondida... Sim, é um bom menino.. eh, enviado.",
"Ah, meu senhor, tenho o prazer de conhecer uma pessoa de tão alta posição e importância, embora sob tais... ehem... um pouco incomuns e, temo, circunstâncias desagradáveis. Por favor, aceite minhas mais humildes desculpas por este infeliz acidente que, garanto-lhe, é apenas o resultado de um mal-entendido. Na verdade vim aqui em busca de paz e amizade. Para provar minhas boas intenções, não vou mais molestá-lo com minha presença, enquanto você certamente me concederá uma carta de aviso em troca... Sim, nós, diplomatas, nos entendemos, não é? Estou muito grato a você, meu bom Senhor.",
"Esteja avisado, jovem #sgender#, e preste atenção às graves implicações de um ato tão atrevido E imprudente: uma exigência tão insolente pode provocar uma retaliação violenta. E a conquista desta cidade poderá perturbar o equilíbrio de poder no Arquipélago. (ou seja, bagunçar a missão principal ;-))",
"Bah, não temo qualquer retaliação. E sempre posso restaurar o equilíbrio de poder devolvendo a cidade ao seu atual governante. Não importa as implodações, vá e diga ao governador que exijo nada menos que a chave desta cidade!",
"Hmm... seria menos imprudente se eu apenas pegasse sua bolsa. Embora você ainda ache isso insolente, hein? Aqui está meu aviso para você, velho: preste atenção nas graves implicações da minha lâmina em sua barriga e me dê seu ouro.",
"Sua honorável senhoria, vejo que você é um homem de diplomacia e sabedoria. Sim, o equilíbrio de poder também é muito caro ao meu coração. Portanto, procuro boas relações com a sua orgulhosa nação. Vamos chegar a um acordo equilibrado: eu poupo a cidade, e você, em troca de uma anistia e de uma carta de letreiro... Sim, nós, diplomatas, nos entendemos, não é? Estou muito grato a você, meu bom Senhor.",
"Eu não confio em você! ALARME! LEVANTE A MILÍCIA!",
"Não vou colocar meu destino nas SUAS mãos! ALARME! Chame as patrulhas!",
"Não pode haver acordo com alguém como você! ALARME! Chame a guarda municipal!",
"... Bah, vou lutar contra todos eles até a cidade se render. E da próxima vez vou te tratar diferente, acredite!",
"Sua ousadia foi recompensada... DESTA vez. O Governador preferirá render-se a arriscar um ataque a este forte inexpugnável. Quais são os seus termos?",
"Pouparei você e a cidade se jurar lealdade a Portugal.",
"Jure lealdade às Províncias Unidas dos Países Baixos. laranja boven...",
"Jure lealdade à Grã-Bretanha. Governe, Britannia, governe as ondas... E esta cidade...",
"Jure lealdade à França. Três vivas para ",
", o novo governante desta cidade...",
"Jure lealdade à Espanha. Vida longa ",
", que restaurará esta cidade à verdadeira crença...",
"Jure lealdade aos Estados Unidos da América. Liberdade, justiça e o jeito americano...",
"Jure lealdade à Suécia. Todos saudam ",
", que agora governará esta cidade...",
"Acima do Jolly Roger, abaixo dos tiranos! Esta é agora uma cidade pirata. Arr...",
"Estou interessado apenas em ouro e mercadorias. Entregue todos os seus pertences em meu navio e eu te deixarei em paz novamente.",
"... Parece que não tenho escolha a não ser te dar o meu ",
"... Mas não pode ser ajudado. Suspiro Adeus, meu amado ",
"... Tudo bem, tudo bem, aqui estão ",
" Ouro.",
"Não xingue, graças a Deus você ainda está vivo e se perde!",
"Muito obrigado, foi um prazer fazer negócios com você. Até a próxima.",
"Bom menino! E agora saia do meu caminho! Tenho alguns homens de verdade para lutar!",
"Sou apenas um escrivão do comandante.",
"Não vou estragar o fio da minha espada nos ossos de um escriturário. Aposto que vou precisar desesperadamente de uma lâmina bem afiada atrás da próxima porta...",
"Um escriturário, hein? Suas roupas parecem muito caras para um balconista. Você provavelmente tem acesso ao baú de guerra da guarnição, hein? Bem, entregue-me ou estragarei seu casaco... COM CLERKSBLOOD!",
"Sou um inspetor do Royal Ordinance Board e estou aqui para inspecionar os estoques deste arsenal.",
"Não deixe que eu o afaste do seu trabalho. E assim que conquistar este forte espero um relatório perfeito sobre minhas lojas. Demitido, continue.",
"Eu poderia fazer alguma ordenança real. Entregue um carregamento de bombas ao meu navio, e não perca tempo, ou você pode inspecionar seus intestinos... deitados diante de sua barriga cortada!",
"Nesse caso você certamente pode me dar algumas dessas novas armas especiais. Vamos, entregue, ou deixo você inspecionar barris de pólvora abertos... com uma tocha acesa amarrada nas mãos!",
"Sou um agente de recrutamento e acabei de chegar com um carregamento de... eh... voluntários recém-chegados de Pris... eh... famílias nobres, quero dizer.",
"Quer dizer que você é um crimpador que vende tolos ingênuos e restos de guarnições guarnições caribenhas, hein? Onde a maioria vai morrer de febre amarela nos primeiros meses, para que sempre haja demanda para o seu comércio, né? Eu desprezo sanguessugas como você. Desaparece antes que eu te prenda para o serviço no bordel de Verruckt!",
"Esses pobres rapazes estarão muito melhor em meu navio principal do que em algum quartel infestado de insetos. Então leve seus 'voluntários' para minha embarcação imediatamente. E se você não cooperar eu vou 'recrutá-lo' também: como 'menino de cabine' para suas ex-vítimas!",
"Ninguém deveria lucrar com a venda de homens para serviços semelhantes aos de escravos! Então me dê seu dinheiro... AGORA!",
"Sou fornecedor e comprei um contrato para fornecer a esta guarnição grãos para os cavalos, bebidas alcoólicas para tratamento de feridas, madeira para paliçadas e lona para tendas. Eu estava prestes a pedir ajuda para descarregar minha carroça.",
"Bah, coisa chata. Vá alimentar seus cavalos, Chandler.",
"Hmm, talvez eu pudesse usar essas coisas para propósitos ligeiramente alterados? Chandler, suba na sua carroça e dirija até meu navio. Lá você terá ajuda para descarregar, hehe. E se você não chegar farei seu coração falhar também, acredite! Vá e entregue! AGORA!",
"Você comprou o contrato? E provavelmente você trapaceia e entrega coisas de qualidade inferior, né? Bem, esse é o caminho da parceria público-privada do século XVII. Mas isso inclui também subornos e dinheiro de proteção para todos que poderiam interromper o seu comércio, não é? Como EU, que poderia cortar também a sua cabeça...",
"Quero me tornar alferes deste regimento e vim aqui para comprar um posto. Mas eles não me aceitaram, apesar de eu ter oferecido uma quantia considerável. Velho demais, disseram. Os cretinos...",
"Você deveria estar grato, se eles tivessem aceitado você, eu já teria matado você. Se perca, ou você terá sua primeira aula de esgrima... e a última também.",
"Uma soma considerável, hein? Dê-me isso e eu lhe garantirei um bom posto de oficial. Tenho muita influência neste regimento... Muito obrigado.",
"Não desperdice seus talentos no Exército, eles não oferecem nada além de pés doloridos e quartéis infestados de insetos. Mas o mar oferece aventura e prêmios em dinheiro. Junte-se à Marinha, torne-se MEU oficial!",
"Aventura? PRÊMIO EM DINHEIRO? Parece bom! Estou pronto para segui-lo em um momento, só preciso pegar meu material primeiro. Encontro você atrás do próximo portão.",
"Ótimo, posso fazer com reforços. Bem-vindo à tripulação! E agora pareça animado com sua carga. Até mais!",
"Quer dizer que você é um crimpador que vende tolos pressionados e restos de gols para guarnições caribenhas, hein? Onde a maioria vai morrer de febre amarela nos primeiros meses, para que sempre haja demanda para o seu comércio, né? Eu desprezo sanguessugas como você. Desapareça antes que eu o prenda para o serviço nas minas #sisland_Oxbay#!",
};
