string DLG_TEXT[23] = {
"Ajuda! Ajuda! Eles vão me amarrar, por favor me ajude!",
"Ah! Por favor me ajude, #ssir#! Tire esses bastardos de mim!",
"Por favor, #ssir#, tenha piedade e me ajude a escapar desses bandidos! Eu te imploro!",
"O que está acontecendo aqui?",
"Do que se trata esse negócio?",
"Qual é o problema?",
"Eu costumava fazer parte de uma gangue com eles... Mas percebi meus erros e quero viver uma vida honesta da qual possa me orgulhar. Mas esses bastardos preferem me ver morto do que livre!",
"Esses bandidos... Já fui ladrão, mas encontrei fé e só quero me estabelecer e viver uma vida honesta. Tentei fugir, mas eles me viram e agora vão me arrastar de volta e me torturar! Por favor me ajude!",
"Em nome de Deus, #ssir#, você tem que me ajudar! Quero sair desta vida de crime, mas agora meus antigos 'amigos' não vão parar por nada para me fazer sofrer, para fazer de mim um exemplo!",
"Ah, agora eu entendo.",
"Atenciosamente, #ssir2#, não posso agradecer o suficiente pela sua ajuda!",
"A honestidade prevalece! Muito obrigado por me ajudar a sair desta vida perversa, nunca esquecerei o que você fez por mim hoje.",
"Graças a Deus você estava aqui! Eu nunca teria esperado que alguém defendesse um estranho assim. Bom saber que ainda existem almas bondosas e valentes neste mundo.",
"Uma alma redimida vale dez destes cretinos.",
"Ganhei essa #sgem# no meu primeiro trabalho, guardei como lembrança. Mas quero deixar essa vida para trás, então gostaria que você a tivesse.",
"Obrigado. Certifique-se de ficar longe desse tipo de vida de agora em diante.",
"Vou contar a todos o que você fez por mim hoje! Eles saberão que você é um #sgentleman# corajoso e gentil.",
"Obrigado. Que você tenha boa sorte no futuro.",
"Estas costumavam ser as ferramentas do meu 'comércio', mas não precisarei mais delas. Talvez você possa usá-los melhor ou simplesmente se livrar deles.",
"Obrigado. Esperamos que você encontre um verdadeiro comércio e adquira algumas ferramentas honestas.",
"Ei, você é ",
", não é? Não ouvi nada além de bom sobre você, e o que você fez aqui prova isso. Talvez haja uma maneira de retribuir.",
"O que você tem em mente?",
};
