string DLG_TEXT[230] = {
"Talvez você precise de um oficial, capitão?",
"Um oficial? E o que você pode fazer?",
"Não, tenho oficiais suficientes por enquanto.",
"Bem, as pessoas dizem que eu sou um bom ",
". Contrate-me para o seu navio, capitão, e você verá por si mesmo.",
"Quanto você pergunta?",
"Infelizmente, eu já tenho um ",
".",
"Você mudou de ideia, capitão? Decida que pode ser útil contratar um novo ",
"?",
"Sim, talvez. Quanto você quer?",
"Você está errado. Adeus!",
"Acho que vamos concordar ",
" ouro.",
"Isso não é demais para você?",
"Concordo. Considere-se contratado.",
"Você não vale tanto. Até a próxima.",
"Tudo bem. Acho então que posso concordar ",
" ouro. Como é isso?",
"Isso é melhor. Sejam bem-vindos à minha tripulação.",
"Ainda acho que isso é demais. Até a próxima.",
"Infelizmente, capitão, tenho certeza que valho o que estou pedindo. Se for muito caro para você - encontre alguém que peça menos.",
"Bem... Você está contratado.",
"Isso é exatamente o que farei. Adeus.",
"Obrigado, capitão. Você não vai se arrepender desse ouro quando me ver em ação.",
"Espero que sim.",
"Ei, parece que você está sem dinheiro! Desculpe, capitão, mas não trabalho por crédito.",
"Droga!",
"Deixe-me terminar minha bebida primeiro, capitão. Mas fique tranquilo: estarei a bordo antes de partirmos.",
"Tudo bem. Se eu tiver que esperar por você, você estará esfregando o convés. Sozinho!",
"A seu serviço, ",
"Não, fique à vontade.",
"Você está demitido. Eu não preciso dos seus serviços!",
"Como você diz, capitão! Mas olhe: se você me despedir, nunca mais voltarei ao seu navio. Então você decide.",
"Bem. Eu mudei de idéia. Eu ainda preciso de você.",
"Ótimo! Suma daqui!",
"Eu lhe disse, capitão, não voltarei. Eu tenho meu próprio orgulho.",
"E eu também não preciso de você!",
"Da próxima vez que embarcarmos, você vem comigo.",
"Por que você não fica de fora no próximo embarque?",
"Pode apostar!",
"Então está claro.",
"Tudo bem, vou me manter ocupado perseguindo ratos no porão.",
"Fique aqui!",
"Siga-me e torne-o rápido!",
"OK.",
"Bom, hein? Que bom?",
"Impressionado, não é?",
"Muito bem, direi à tripulação para içar ",
" cores.",
"Obrigado.",
"Estou pronto para segui-lo em um momento, só preciso pegar meu material primeiro. Encontro você atrás do próximo portão.",
"Ótimo, posso fazer com reforços. Bem-vindo à tripulação!",
"Atualmente fornecemos rações alimentares ",
" e rações de rum ",
". Temos comida suficiente para ",
" dias e rum suficiente para ",
" dias, com nossas rações atuais. Você quer mudar as rações?",
"Sim, forneceremos rações alimentares completas e rações normais de rum.",
"Sim, forneceremos meia ração alimentar e rações normais de rum.",
"Sim, forneceremos rações completas e rações duplas de rum.",
"Sim, forneceremos meia ração alimentar e rações duplas de rum.",
"Muito bem, agora forneceremos rações completas de comida e rações normais de rum.",
"Muito bem, agora forneceremos meia ração de comida e rações normais de rum.",
"Muito bem, agora forneceremos rações completas de comida e rações duplas de rum.",
"Muito bem, agora forneceremos meia ração de comida e rações duplas de rum.",
"Você precisará dividir o saque primeiro, capitão ",
"Ah, não importa.",
"Um salário!? Tem certeza, #ssir#? Não foi para isso que a tripulação se inscreveu.",
"Sim eu tenho certeza. E não me importa quantos desertos!",
"Assinar artigos!? Tem certeza, #ssir#? Não foi para isso que a tripulação se inscreveu.",
"Sim eu tenho certeza. E não me importa quantos desertos!",
"Muito bem, vou informar a tripulação. Mas esteja avisado: alguns deles podem desertar.",
"Muito bem, vou informar a tripulação. Mas esteja avisado: alguns deles podem desertar.",
"Que cores devemos voar, capitão?",
"Nosso atual ",
"Cores piratas.",
"Sobre o navio e a tripulação...",
"Sobre mim...",
"Sobre você...",
"Sim?",
"Deixa para lá.",
"Qual é a situação das nossas provisões?",
"Terminamos com o corsário. Agora todos vocês receberão um salário.",
"Vamos assinar artigos.",
"Derrubar nossas cores; estamos hasteando uma nova bandeira.",
"Qual é o status dos nossos navios parados?",
"Parece que não me encaixo muito bem neste mundo...",
"Preciso trocar de roupa.",
"Você precisa de um uniforme melhor.",
"Amigo, infelizmente não preciso mais dos seus serviços. Vou mandar trazer seu baú para a costa para você!",
"...",
"Tem certeza, capitão? Eu gostaria de ficar, se você me aceitar!",
"Sim eu tenho certeza. Mas, nunca se sabe, eu gostaria de poder te encontrar se precisar de você de novo!",
"Que possamos nos encontrar novamente em breve, então. Bons ventos e mares agitados, capitão!",
"E para você.",
"Que tipo de pirata você é, capitão? No momento você é conhecido como ",
" e atualmente não informamos sobre avistamentos, a menos que tenhamos a chance de derrotá-los.",
" e atualmente informamos sobre todos os navios que localizamos.",
"Quero mudar as ordens permanentes em relação às poderosas embarcações inimigas.",
"Muito bem.",
" Agora não vamos incomodá-lo com avistamentos muito poderosos.",
" Agora vamos falar sobre todos os avistamentos.",
"a",
"Um ",
"A ",
"um ",
"a ",
"Certo, como você deseja. E devemos acrescentar alguns móveis, acessórios ou equipamentos? Isso pode ser necessário para permitir que o edifício desempenhe uma função adequada.",
"Não, apenas faça a construção como está.",
"Acalme tudo isso, tenho que inspecionar o terreno de construção mais uma vez.",
"Sim, boa ideia!",
"Então vamos erguer um ",
" com um ",
"Certo, vá em frente!",
"Err, desculpe, não tenho certeza se esse é um bom design para este lugar. E o que você disse sobre nossos recursos?",
"Levante-se ",
"Minhas próprias cores.",
"Bem aqui na sua frente, sim? Sim, nós temos ",
"unidades de prancha e tijolo, respectivamente, e ",
" ouro para comprar outros materiais. E devo lembrá-lo que você deve destacar alguns de nossos ",
" marinheiros para proteger e manter cada edifício? Então, o que você gostaria de erguer?",
"Uma caixa semienterrada (como barricada improvisada ou esconderijo para uma armadilha; 2 tábuas, 100 G, 0 mãos)",
"Uma paliçada de madeira(fortificação simples; 10 tábuas, 1000 G, 5 mãos)",
"Um bastião de pedra (equipado com um canhão, uma fortificação formidável; 30 tábuas, 10.000 G, 15 mãos)",
"Uma fortaleza (fortaleza para salvaguardar seus tesouros; 30 tábuas, 20.000 G, 15 mãos)",
"Uma casa (para abrigo e recreação, paga aluguel; 20 plankunits, 4.000 ouro e 3 mãos necessárias)",
"Uma oficina (base para joalheria, fundição, estaleiro, destilaria; 20 plankunits, 4.000 ouro e 3 mãos necessárias)",
"Uma fazenda (para abrigo, produz trigo e café; 30 tábuas, 5.000 G, 10 mãos)",
"Uma floresta (produz tábuas e ébano; 0 tábuas, 1000 G, 5 mãos)",
"Uma mansão renascentista (pode ser transformada em sua sede ou boudoir; 30 tábuas, 20.000 G, 5 mãos)",
"Uma mansão renascentista (pode ser transformada em sua sede; 30 tábuas, 20.000 G, 5 mãos)",
"Um observatório (pode ser transformado em sua sede; 30 pranchas, 20.000 G, 5 mãos)",
"*** Espaço em branco para suas criações, não use agora!! . ('rende'; 20 pranchas, 4000 G, 5 mãos)",
"Hum, eu entendi você certo? Você construirá qualquer prédio que eu queira? Bem aqui? Isso faz sentido?",
"Aguarde isso, tenho que inspecionar o terreno de construção mais uma vez.",
"Se isso faz sentido depende inteiramente de você. VOCÊ é o arquiteto deste edifício, o criador deste assentamento. Se você gosta de um estaleiro em uma montanha, uma floresta em uma prefeitura ou um bordel em uma igreja: seguirei suas ordens e construirei. Mas não me culpe se você desperdiçar seu dinheiro em uma ruína perdida. Só há uma limitação: não podemos erguer mais de 15 construções num só local. E se espremermos muitas casas em uma cidade já lotada, ela pode ficar superpovoada e certos personagens podem não aparecer mais.",
"Hmm... hmm.. um bordel em uma igreja? Quem sabe, pode ser uma ideia lucrativa.. Mas agora vamos prosseguir com a construção aqui.",
"Tudo bem, e vamos armar esta fortificação?",
"Tudo bem, e vamos armar esta posição?",
"Então, o que você gostaria de adicionar ao seu prédio?",
"Uma torre sinuosa de poço de mina (transforma uma oficina em uma mina de joias; 10 pranchas, 4000 G, 5Crw)",
"Uma fundição de bala de canhão (transforma uma oficina em uma fundição; 10 pranchas, 4000 G, 5Crw)",
"Uma destilaria de rum (transforma uma oficina em destilaria; 10 tábuas, 4000 G, 5Crw)",
"Uma carenagem (transforma uma oficina em estaleiro; 10 pranchas, 4000 G, 5Crw)",
"Um canhão (para armar uma fortificação; 0 pranchas, 5000 G, 3Crw)",
"Uma barraca de mercado (transforma a casa em entreposto comercial, dobra o aluguel; 5 tábuas, 5.000 G, 3 mãos)",
"Móveis luxuosos (aumenta a chance de sucesso no tratamento de feridas em casas e fazendas; 5 tábuas, 1000 G, 1 Crw)",
"Etablissement for Gentlemen's Entertainment de Madame Monique (rende 'dividendos', atrai marinheiros que podem ser frisados; 5 pranchas, 1000 G, 1 Crw)",
"Um escritório (como sede; para receber agentes e contratar oficiais; 5 pranchas, 1000 G, 1 Crw)",
"Hum, desconsidere tudo depois de 'Bom dia', tenho que revisar os esboços mais uma vez.",
"*** Espaço em branco para suas criações, não use agora!! (; pranchas, G, Crw)",
"Hum, #ssir#, a ",
" requer ",
" pranchas e tijolos, respectivamente ",
" Ouro e ",
" homens. Mas, como eu disse, temos apenas ",
" unidades de prancha, ",
" G e ",
" mãos...",
"Opa... Um pequeno... Err... Maldito arquiteto, o cretino me deu os planos errados! Você acreditaria... Não importa, fique à vontade enquanto eu repasso os esboços mais uma vez...",
"Traga algumas mãos com pás e machados, quero erguer um prédio. Aqui e agora!",
"#ssir#, precisamos adicionar algo a este prédio para que ele tenha alguma utilidade!",
"Deixe-me examinar os planos e decidir o que quero.",
"Deixe minhas próprias cores.",
" com um ",
"Estou mudando seu papel no navio",
"Sim capitão, onde você precisa de mim?",
"Estou colocando você no comando da tripulação, Contramestre.",
"Equipe as armas!",
"Agora você está encarregado de traçar nosso curso, Navegador.",
"Estou promovendo você a primeiro imediato!",
"Assuma o gerenciamento diário do navio como o novo contramestre.",
"Preciso que você seja o novo carpinteiro.",
"Preciso de suas habilidades como cirurgião.",
"Preciso do seu braço forte como um dos meus durões.",
"Pensando bem, fique como está.",
"Aye Aye capitão!",
"Continue então.",
"Amigo, infelizmente não preciso mais dos seus serviços. Vou trazer seu baú para terra, e aqui está o ",
" ouro eu te devo.",
"Conte-me sobre as finanças do navio.",
"Sim #ssir#! Atualmente devemos à tripulação ",
" ouro, e os oficiais ",
". Com base na tripulação que temos hoje, estamos pagando ",
" ouro por mês para a tripulação, e ",
" ouro por mês para seus oficiais.",
"? Algum pedido?",
"Eu tenho uma coisa muito especial, dizem para te ajudar. Você poderia, por favor, pegar?",
"Sobre...",
"Estamos fazendo uma operação de contrabando agora e preciso saber o cronograma de patrulha da guarda costeira.",
"Você sempre pode perguntar a alguns dos guardas da taverna, eles podem revelar a informação. Mas eu também poderia dar uma olhada para você e informar quando for o melhor momento.",
"Vou tentar a sorte com os guardas.",
"Eu gosto do seu pensamento! Pergunte por aí, discretamente, explore a costa, faça o que fizer, e apresente um relatório aqui em um dia. E tenha cuidado.",
"Desculpe, não consegui descobrir o melhor horário para o contrabando. Havia muitos guardas.",
"Então esperei um dia inteiro por nada? Bem, acho que você fez o melhor que pôde.",
"Consegui reunir algumas informações e acho que o melhor momento para contrabandear seria ",
"Ok, voltarei amanhã.",
"Só preciso recolher meu material. Vá em frente, entrarei em contato com você o mais rápido possível.",
"É hora de espalhar um pouco de alegria entre os homens e dividir o saque ",
".",
"Sinto-me honrado por me permitir servi-lo, capitão. Se você ainda não vendeu os navios de seus oficiais, e todos os seus bens e canhões, você deveria fazê-lo primeiro e voltar para mim. Tal como está, a parte de cada tripulante será ",
" ouro - tenho certeza que serão ",
"--e sua parte será ",
" ouro. O capital inicial para seu próximo empreendimento será ",
". Você terá que começar a recrutar sua tripulação novamente. Tem certeza de que deseja dividir o saque, capitão?",
"Sim.",
"Não.",
"Muito bem. Tenho certeza que a tripulação estará ",
" com suas ações. Boa sorte na sua próxima expedição!",
"Obrigado.",
"Sim, capitão. Suponho que neste momento você só quer dividir o ouro?",
"Sim, apenas divida o ouro, por favor. A tripulação deverá ser paga independentemente da nossa situação atual.",
"É hora de traçar um limite nesta viagem e começar a planejar uma nova aventura, eu acho.",
"Muito bem. ",
"Tal como está, a parte de cada tripulante será ",
" ouro - tenho certeza que serão ",
"--e sua parte será ",
" ouro. ",
"Você também terá ",
" sobra de ouro para despesas imediatas. Deseja prosseguir com a divisão, capitão?",
"Como desejar, capitão. Se você ainda não vendeu os navios de seus oficiais, e todos os seus bens e canhões, você deveria fazê-lo primeiro e voltar para mim. Tal como está, a parte de cada tripulante será ",
"Muito bem. Tenho certeza que a tripulação estará ",
" com suas ações.",
"Obrigado pela ajuda.",
"Acho que é hora de revisar seu salário.",
"Obrigado Capitão, tenho tentado melhorar minhas habilidades.",
"Você está indo bem, mas ainda não chegou lá.",
"Você merece a recompensa de um aumento salarial, então continue com o bom trabalho.",
"De agora em diante você receberá um salário como o resto dos meus oficiais.",
};
