string DLG_TEXT[36] = {
"Tosse-tosse... tempo terrível! Meu nome é ",
", e eu sou o melhor construtor naval destas ilhas.",
"Discordo: acho que o tempo está maravilhoso. Meu nome é ",
".",
"Chega de gemer! Meu nome é ",
". Presumo que você já ouviu falar de mim.",
"Oh, é você de novo, com seus problemas... tosse-tosse!",
"Você pode não estar com saúde, mas sua memória está boa. Agora vamos ao que interessa.",
"Isso mesmo, sou eu de novo e você está tão cansativo como sempre. Vamos apenas conversar sobre negócios.",
"Desculpe incomodá-lo. Eu devo ir.",
"Você sabe, já ouvi o suficiente de suas reclamações sobre a vida. Adeus.",
"Vocês, jovens, são tão desrespeitosos hoje em dia! Você tem paixão e força, o que mais você precisa?",
"Você também já deve ter sido jovem. Tenha um pouco de paciência.",
"Sim, e acho que sua juventude faleceu há tanto tempo que você nem consegue se lembrar.",
"Mostre algum respeito pelos mais velhos, filhote!",
"Por favor, não levante sua voz para mim novamente. Podemos simplesmente começar a trabalhar?",
"Cuidado com sua língua enrugada, velho, ou acabarei com seu sofrimento! Se você for inteligente, fechará a boca e pensará nos negócios.",
"Desculpe. Vejo que não adianta falar com você.",
"Isso é conversa fiada suficiente para mim! Adeus.",
"Sim, sim - tudo bem! Então, o que você quer de mim, ",
"?",
"Gostaria de utilizar os serviços do seu estaleiro.",
"Preciso dos serviços do seu estaleiro. ",
"Desculpe - eu tenho que ir.",
"Tenho assuntos urgentes em outro lugar. Estou indo agora.",
"O que exatamente você precisa?",
"Preciso consertar meu navio - embora eu possa considerar apenas desmantelá-lo e comprar um novo.",
"Preciso instalar novas armas na meu navio.",
"Nada, obrigado.",
"Recuso-me a negociar com uma pessoa com a sua reputação e relações. Agora saia, ",
", antes de chamar os guardas.",
"Muito bem.",
"Tudo bem, meu cais ao lado do forte está disponível para você. Se você quiser, direi ao meu chefe das docas para rebocar seu navio até lá. Só então poderei avaliar os danos e dizer quanto tempo e dinheiro serão necessários.",
"DOCA AO LADO DO FORTE?? Uhh... só me lembro que tenho... eeh... outro assunto urgente que preciso resolver primeiro. Adeus.",
"Após fechar esta caixa de diálogo, pressione ENTER para abrir a interface de mudança de vela.",
"Saída",

};
