string DLG_TEXT[23] = {
"Pare, #ssir#! O que você está fazendo aqui?",
"Você prendeu um homem há poucos minutos no bordel.",
"Sim. E daí?",
"Eu quero falar com ele. Isso é possível?",
"Claro que não! Você pode tentar libertá-lo! Eu não confio nele e também não confio em você.",
"Quanto você quer?",
"O que você quer dizer?",
"Excelente. Agora estamos chegando a algum lugar. Aqui estão suas 500 moedas de ouro. Agora deixe-me entrar.",
"É muito ouro que você quer. Voltarei mais tarde.",
"Muito bem. Eu vou deixar você entrar. Mas não fique aí muito tempo.",
"Sem problemas. Não pretendo permanecer numa prisão tão sombria como esta por mais tempo do que o necessário.",
"Adeus e obrigado pela sua visita. Farei bom uso do seu ouro quando o bordel abrir novamente.",
"Na verdade, queria saber se você poderia me fazer mais um favor. Você ganhará mais 500 moedas se me ajudar.",
"Por favor, diga-me que não quer que eu liberte o prisioneiro. Eu não farei isso. Nem mesmo por 50.000 moedas de ouro. O governador mandaria me prender imediatamente. E executado também, provavelmente.",
"Isso é uma vergonha. Era exatamente isso que eu ia te perguntar. Então você sabe como posso libertar o prisioneiro?",
"...",
"...",
"Então você está pronto para me dar o dinheiro agora?",
"Sim. Aqui está. Agora deixe-me entrar.",
"Você sabe muito bem o que quero dizer.",
"Hum. Se você me der 500 moedas de ouro, isso pode me convencer de sua confiabilidade.",
"A única pessoa com esse poder é o governador. Fale com ele sobre isso. Mas não espere que seja barato.",
"Obrigado. Vou fazer-lhe uma visita então.",

};