string DLG_TEXT[27] = {
"Sair! ",
"Desmond Ray Beltrop",
" deu ordens estritas para manter todos fora daqui.",
"...",
"Você é o terceiro homem que tenta entrar nesta casa! O que vocês estão procurando?",
"Espere um minuto. O que você está dizendo?",
"Que você está morto, amigo.",
"Isso ainda está para ser visto.",
"Justo. <Pensa: Talvez haja algo interessante aqui e uma maneira sorrateira de entrar e descobrir...>",
"Justo. <Pensa: Talvez haja algo interessante aqui, e talvez eu possa encontrar uma maneira sorrateira de entrar à noite para descobrir...>",
"Quem é você?",
"Eu sou ",
". Quem diabos é você?",
"Eu sou ",
". Estou tentando encontrar alguém chamado Raoul Rheims. Você não o viu, viu?",
"Não. Ei, espere um minuto. Que ano é este?",
", claro. Por que você pergunta?",
"Porque para mim deveria ser ",
".",
"Algo estranho deve estar acontecendo. ",
"Se alguém estava contando com você para estar em algum lugar em um determinado horário, provavelmente você está atrasado agora. ",
"De qualquer forma, se você não se importa, vou procurar para ver se há alguma pista de para onde foi Reims. Afinal, esta é a casa dele.",
"Eu não me importo. Na verdade, farei uma pequena pesquisa por conta própria. Se eu encontrar alguma coisa sobre Reims, eu darei a você. Qualquer outra coisa que eu encontrar é minha.",
"Ainda não encontrei nada sobre Reims. E você?",
"Nada sobre Reims, não.",
"Nunca escutei dele.",
"Bem, se não se importa, vou procurar para ver se há alguma pista sobre para onde foi Reims. Afinal, esta é a casa dele.",
};
