string DLG_TEXT[166] = {
"Bem-vindo bem vindo, ",
". Você encontrará tudo o que seu coração deseja na taverna de Everard Gordon. Se não tiver, sei onde conseguir!",
"Obrigado pela recepção calorosa. Eu sou ",
".",
"Bem-vindo meu querido ",
". Estou tão feliz em ver você novamente na minha taverna",
"! O que posso te oferecer?",
"Por que Olá, ",
".",
"Estou querendo reforçar minha equipe.",
"Eu gostaria de falar com você, se tiver um momento",
"Eu ficaria aqui por um tempo",
"Tem um berço sobrando nesse barraco?",
"Estarei a caminho agora ",
". Até a próxima.",
"O que posso fazer pelo meu amigo ",
"?",
"Preciso contratar alguns cães-do-mar para minha tripulação - de preferência mais espertos que os cães reais.",
", vamos conversar.",
"Estou preso aqui um pouco.",
"Tem cama grátis nesse lixão?",
"Te vejo em breve, ",
". Até a próxima.",
"Acontece que tenho alguns quartos. Quanto tempo você planeja ficar?",
"Até de manhã. Eu poderia usar o resto.",
"Só até esta noite.",
"Vai custar 5 peças de ouro.",
"Eu acho que você pode se safar quando você é o único jogo na cidade. Aqui está o seu ouro.",
"É uma pena. Minhas costas doloridas querem uma cama limpa, mas minha bolsa diz que estou dormindo no salão da taverna.",
"Cinco?! O quê, você tiraria o próprio governador da cama por mim? Esqueça. Vou economizar meu dinheiro e dormir na sala comunal.",
"Tudo bem, vou ter que pensar sobre isso.",
"Vai custar 5 peças de ouro.",
"Certo. Aqui está o seu dinheiro.",
"Isso é mais do que posso gastar no momento. Suponho que terei que passar a noite na sala comunal - com o resto dos plebeus.",
"Por esse dinheiro, eu esperaria uma cama, um banho e uma refeição de sete pratos! Esqueça. De repente, a sala comunal parece muito melhor para mim.",
"Vou ter que pensar sobre isso. Enquanto isso, responda outra pergunta para mim.",
"Certamente. O que você quer saber, capitão ",
"?",
"Gostaria de saber o que os cidadãos locais sentem em relação aos soldados franceses guarnecidos aqui.",
"Qualquer fofoca que valha a pena repetir.",
"Há alguns assuntos que gostaria de discutir com você...",
"Negócios? Agora estamos nos entendendo!",
"Você sabe, agora que penso nisso, não temos nada para conversar.",
"Você viu um homem por aqui chamado ",
"Counterspy",
"?",
"Você se lembra do oficial francês com quem falei da última vez que estive aqui?",
"Parece que a frota francesa recebeu uma nova adição recentemente.",
"Seu barco está pronto ",
"?",
"Preciso de qualquer informação que você possa me dar sobre um cavalheiro que você deve ter visto por aqui. Você dificilmente sentiria falta dele - ele sempre usa uma túnica vermelha e atende apenas pelo nome de 'Professor'.",
"Eu preciso de um emprego. Você não conhece nenhum garoto rico nesta ilha que tenha medo de viajar sozinho?",
"Se existir tal pessoa, ela pode preferir evitar atrair a atenção de tantas consortes - como eu espero que você saiba.",
"Sim, esqueci. Tudo bem, voltarei mais tarde, quando tiver menos navios, ha-ha.",
"Eu não quero ajudar você. Você causou muitos problemas ao meu país.",
"Bastante patriota, não é? Bem, adeus então.",
"Suas mãos estão cobertas de sangue. Você não acha seriamente que alguém viajaria com você, não é?",
"Você está certo, todo mundo tem medo de mim! Ha-ha!",
"Você chegou bem na hora. Um comerciante aqui estava procurando a companhia certa para viajar. É melhor você falar com ele - aqui está ele agora, entrando na taverna.",
"Eu farei isso.",
"Não, não há ninguém assim no momento, talvez da próxima vez.",
"Hmm, então vou esperar.",
"Sim, eu me lembro dele. O tolo foi preso em #sGreenford#. Dizem que ele tentou iniciar uma revolta. Se você precisar falar com ele, tenho certeza que o encontrará na prisão de #sGreenford#.",
"Obrigado. Eu aprecio sua ajuda.",
"Interessante. A propósito, estou querendo aumentar minha equipe.",
"Eu gostaria de conversar com você.",
"Vou me despedir de você agora ",
". Até a próxima.",
"Como desejar, capitão. Como quiser.",
"Obrigado. Isso pode ser útil no futuro. Entretanto, preciso de uma tripulação.",
"Eu gostaria de conversar com você.",
"Te vejo na próxima vez, ",
". Até a próxima.",
"Olhe ao seu redor, capitão! Quem você contrataria? Todos os homens fisicamente aptos foram levados pelos franceses para trabalhar em seus navios.",
"Eu vejo. Uma pena. Talvez você possa me ajudar com outra coisa então.",
"Se você me perdoa, eu irei agora ",
". Boa sorte para você.",
"O francês? Como você acha que nos sentimos em relação a eles? \nEles prometeram que não fariam mal a ninguém e então saquearam metade da cidade! \nPobre ",
"Mildred Backer",
" teve que fugir para salvar sua vida. \nE o pai dela foi abatido como um animal quando resistiu!",
"É pior do que eu pensava. Diga-me, ",
", você gostaria de ver a bandeira inglesa hasteada sobre #sOxbay# novamente?",
"É terrível, capitão! Os franceses pegaram nosso forte de surpresa e o capturaram quase sem perdas para o seu lado. Depois declararam que estávamos sob a proteção da Coroa Francesa. Proteção, eles disseram! E logo depois disso, eles começaram a saquear! Enchendo seus porões com suprimentos às nossas custas.",
"É justo, então, dizer que você não está satisfeito com a forma como os franceses o 'protegem'?",
"Capitão, rezo pelo dia em que estes invasores sejam finalmente atirados daqui para o mar. Eles bebem litros do meu melhor rum e cerveja, e tenho medo até de perguntar sobre o pagamento!",
"Então você pode ficar satisfeito em saber que venho até você por ordem de Sir Robert Christopher Silehard.",
"O governador de #sRedmond#? Sua Alteza Sereníssima sabe do ataque, então? Por que ele não sai de seu...trono bem acolchoado...e recaptura a colônia?!",
"Tudo em bom tempo. Por enquanto, estou coletando informações sobre os planos da França.",
"Entendo, sim. Se houver algo que eu possa fazer para ajudar sua missão, é só me avisar.",
"O que está acontecendo agora na cidade?",
"Praticamente nada. A maior parte da população está escondida, seja em suas casas ou na selva. Os franceses colocaram guardas no portão da cidade, mas todos os dias vários cidadãos conseguem passar por eles e sair da cidade. \nQuanto aos soldados franceses, eles parecem ver esta ocupação como o seu próprio partido louco. A maioria deles está bêbada o tempo todo. \nAlém disso, eles estão com falta de pessoal. Os comandantes da frota contratam cada vez mais marinheiros. O salário deles é muito bom, segundo me disseram\nMas, direto ao ponto, ",
", este pode ser um bom momento para enviar um emissário aos franceses.",
"Um bom barman ouve muito. Talvez você tenha conseguido algumas informações sobre os franceses e seus planos?",
"Bem, agora... isto pode não significar nada, mas... outra noite, dois oficiais franceses bêbados estavam falando sobre um navio que estavam esperando, fortemente carregado de munição. \nEles pareciam esperar que demorasse para vir aqui, para que pudessem continuar a aproveitar a festa que estão dando às custas da nossa cidade! \nParece-me provável que, assim que este carregamento de munições chegar, a frota levante âncora e passe para a próxima etapa do seu plano de batalha, seja ele qual for.",
"Obrigado. Esse é exatamente o tipo de informação que preciso.",
"Estou satisfeito em ouvir isso. Se eu 'ouvir' qualquer outra coisa útil, avisarei você imediatamente! \nQuando esses porcos ficam bêbados, eles falam como um círculo de costura. Se não pagarem pela minha cerveja com ouro, pagarão com informação, quer saibam disso ou não!",
"Então um soldado francês bêbado é tão bom quanto um espião, não é?",
"Essa é uma maneira muito boa de colocar isso ",
"! Se você pudesse ouvir o que acontece aqui à noite!",
"Talvez eu possa ouvir um pouco, com a sua ajuda.",
"Você tem uma ideia? Estou ao seu serviço!",
"Meu plano é bem simples: você vê aquele francês aí? Você conhece ele?",
"Certamente. Ele é um oficial da fragata francesa. Mas não é muito oficial - ele passa a maior parte do tempo aqui.",
"Perfeito. E você está pronto para gastar algum ouro para a libertação de #sOxbay#?",
"Ouro? ",
", Receio que você tenha me perdido.",
"É muito simples. Vou sentar-me com este homem e você vai dar-lhe tudo o que ele quiser. Vinho, cerveja, rum... vamos embebedá-lo e vou pescar qualquer informação útil que ele possa ter na cabeça.",
"Mas, ",
", já estou indo à falência! Quem vai pagar por todas essas bebidas? Estou pronto e disposto a contribuir para a libertação de #sOxbay#, mas cite um preço que eu possa pagar!",
"Ouça, o governador Silehard terá prazer em reembolsá-lo por suas despesas - e ele oferecerá algo extra pelo seu trabalho!",
"Que preço você colocaria na sua própria liberdade?",
"Você realmente acha que ele vai me recompensar, #ssir#? Tudo bem então. Vamos ao que interessa!",
"Eu sabia que você veria as coisas do meu jeito. Apenas se apresse e traga as bebidas!",
"Sinto muito, mas não posso viver de uma promessa do homem do governador, posso? Não, aquele francês bebe como um peixe. Uma baleia! Não posso dar-lhe todas as bebidas de graça.",
"Você deve estar brincando. Você mesmo disse que ele já não está pagando pelo que bebe. Que tipo de patriota você é?",
"Certo! Se o dinheiro é tão importante para você, diga-me quanto você quer.",
"Só um momento...deixe-me pensar... ",
" peças de ouro. E nem um a menos! Olha, eu sei que é muito ouro, mas estamos em tempo de guerra, não é?",
"De onde eu venho chamamos isso de especulação! Aqui está o seu ouro. E traga-me o que quer que o francês esteja comendo, mas não se esqueça de diluir o meu. Vou querer a cabeça limpa para isso!",
"Everard, olha, não tenho dinheiro.",
"Eu me acalmaria se fosse você. Há olhos e ouvidos franceses por toda parte. Ameace-me e eu te entregarei!",
"Ladrão! Quanto você quer?",
"Não se preocupe, ",
", tudo correrá como você planejou!",
"Bem.",
"Sem dinheiro? Bem, suponho que não tenho escolha, então, a não ser confiar nas boas graças do governador. Vou lembrar o que você prometeu",
"Obrigado, Everardo!",
"Não é do gosto deles?! Eles vêm à minha taverna todos os dias e bebem litros de cerveja e rum, e tenho medo até de mencionar o pagamento a eles quando saem cambaleantes pela manhã!",
"E se eu disser...",
"Sem problemas. Você pode conseguir um quarto por apenas 10 peças de ouro.",
"Isso é demais!",
"Certo. Aqui está o seu dinheiro.",
"Hardouin Beauvallet",
"Hardouin Beauvallet",
"? Claro, ele é outro frequentador da minha taverna. Ele vem aqui todas as noites e bebe duas garrafas do meu melhor vinho. De graça, naturalmente!",
"Vou esperar por ele aqui, então.",
"Na verdade, um navio de guerra francês entrou no porto há um ou dois dias. Se se tratar de uma batalha naval direta, ela enviará muitos ingleses para a morte por afogamento.",
"Então deveríamos destruir aquele navio antes de qualquer batalha começar, você não acha?",
"Uma boa ideia. Mas não sei como você conseguiria isso. Não era possível chegar lá pelo mar - não com o porto tão fortemente defendido. E abordá-lo por terra seria suicídio. A menos que... Sim! A maior parte da tripulação do navio está na cidade no momento - eles receberam licença para terra firme. Apenas uma tripulação mínima está a bordo agora",
"O que você quer chegar?",
"É quase impossível que um único barco, vindo da costa à noite, consiga chegar ao navio. Se alguns homens corajosos decidissem tentar, tenho certeza de que encontraria o barco adequado.",
"Encontre aquele barco, então ",
"!",
"Traga aquele barco para o porto, então. Estaremos esperando lá.",
"Bom Bom. O anoitecer ainda falta algumas horas. Você pode descansar em um dos meus quartos até então. Por conta de casa! Hoje, seu dinheiro não serve aqui.",
"Sim, é uma boa ideia. Agradeço sua hospitalidade.",
"Está na hora, ",
"! O barco está pronto. Você encontrou seus voluntários?",
"Sim. Esta noite o barco deve estar perto do cais.",
"Eu estarei lá...",
"Vamos esperar até escurecer, então",
"Por favor, alugue um quarto na minha taverna. De graça, desta vez.",
"Obrigado, ",
".",
"Fique quieto! Ele está sentado lá em cima. Ele estará vestido com um uniforme francês, mas isso faz parte do plano dele.",
"Obrigado.",
"Você não terá muita sorte agora. Está escuro e todos estarão em casa. \nSe eu fosse você, esperaria até de manhã. Talvez você queira alugar um quarto?",
"Você tem vaga?",
"Ainda não. Deixe-me ter mais um momento do seu tempo.",
"Pare com isso! Pare com essa loucura imediatamente, ou serei forçado a chamar os guardas!",
"Tudo bem, tudo bem. Estou indo embora!",
"Você sabe se um comboio inglês esteve aqui recentemente?",
"Sim, há cerca de uma semana. Foi um bom dia para negócios. Eles estavam trazendo uma carga de seda do outro lado do Atlântico e há muito tempo não viam comida ou bebida decente.",
"Alguma ideia de para onde eles foram a seguir?",
"Sim, um dos policiais estava bêbado o suficiente para deixar escapar que mal podia esperar até que eles carregassem a prata e se dirigissem para #sCartagena#, pois tem um hotel e duas tabernas. Quase me fez sentir inadequada com esse lugarzinho! Você é amigo de um dos capitães?",
"Eu certamente gostaria de conversar com um deles, sim. Obrigado!",
};
