string DLG_TEXT[43] = {
"Bem-vindo à igreja, #saddr#.",
"Você não é meu pai. Não me fale assim novamente",
"Bom dia, padre.",
"Ora, seu pagão desrespeitoso! Sair! Você contamina a casa de Deus com a sua presença!",
"De qualquer forma, eu não estava planejando ficar muito tempo.",
"Que Deus abençoe você e suas ações. Você veio até mim com algum propósito?",
"Eu gostaria de fazer uma doação.",
"Estou aqui para me confessar",
"Desculpe. Eu devo ir.",
"Oh! Esta é uma grande ação que você fez, #saddr#. Fico feliz em conhecer um jovem marinheiro que não se afunda no pecado como os outros.",
"Sinto muito, padre. Acontece que não tenho dinheiro.",
"Aqui estão 100 ouro pelo seu bom trabalho.",
"Eu deveria pensar que o Senhor olharia gentilmente para 1.000 moedas de ouro.",
"Estou indo bem atualmente, então darei 5.000 ouro.",
"A decisão é sua, #saddr#. Nunca é tarde para mudar - e tenha em mente que suas boas obras serão levadas em consideração no momento de sua morte.",
"Minha morte ainda está muito distante, se Deus quiser! Vamos falar sobre outra coisa.",
"Desculpe, padre. Eu tenho que ir.",
"Agradeço-lhe o seu presente em nome da Santa Igreja, #saddr#.",
"Preciso falar com você, padre.",
"Sinto muito, padre, mas tenho que ir",
"Agradeço-lhe o seu presente em nome da Santa Igreja, #saddr#.",
"Preciso falar com você, padre.",
"Sinto muito, padre, mas tenho que ir",
"Agradeço-lhe o seu presente em nome da Santa Igreja, #saddr#.",
"Preciso falar com você, padre.",
"Sinto muito, padre, mas tenho que ir",
"Claro, #saddr#. Estou ouvindo.",
"Eu mudei de ideia. Talvez outra hora.",
"Eu pequei, santo padre...",
"É da natureza do homem pecar, #saddr#. Mas pedir perdão é divino.",
"Sim, mas eu... saqueei navios e mandei alguns para o fundo do oceano. Eu saquei minha espada com raiva e tirei vidas....",
"Mas não havia #snation# entre eles, havia?",
"Claro que não, padre.",
"Sim, santo padre. Mesmo #snation#.",
"Então Deus perdoa seus pecados, #saddr#.",
"Obrigado padre. Estou indo agora.",
"O que?! Deus nunca perdoará tal pecado! Saia de Sua casa imediatamente!",
"Adeus, padre.",
"Estou com medo ",
" ouro é tudo o que posso pagar agora.",
"Eu deveria pensar que o Senhor olharia com bondade ",
" peças de ouro.",
"Estou bem ultimamente, então vou dar ",

};
