string DLG_TEXT[87] = {
", #saddr#! Como este servo de Deus pode ajudá-lo?",
"Eu sou ",
", capitão do '",
".",
"Eu te dou as boas-vindas ",
", #saddr#! Estou feliz que seu tempo no mar não tenha feito você esquecer sua fé.",
"Olá, ",
". Então, conte-me sobre seus pecados.",
"Estou feliz em vê-lo e estou pronto para aceitar sua confissão, #saddr#.",
", Gostaria de dar um presente à Igreja.",
"Eu só preciso falar com você, #sFather#.",
"Obrigado. Talvez na próxima vez.",
"Estou muito feliz em dar as boas-vindas a um novo membro na congregação. Eu sou ",
". ",
"Maravilhoso, então espero que você aceite meu presente para a Igreja.",
"Posso falar com você, #sFather#?",
"Obrigado, #sFather#, mas preciso ir.",
"Isto diz respeito à sua fé?",
"Na verdade, diz respeito à sua fé.",
"Na verdade, isso diz respeito a você.",
"Sinto muito, mas reuni evidências que provam que você quebrou seus votos como padre.",
"Não. E vamos falar de outra coisa.",
"O que você quer dizer?",
"Fui enviado aqui para saber se os rumores que difamavam o seu nome eram verdadeiros.",
"Rumores? Que rumores?",
"Acho que você está se declarando inocente. Infelizmente, tenho cartas que dizem que você é culpado.",
"Realmente?! Que letras? Juro que não fiz nada!",
"Aqui estão eles. Você também pode desistir de agir, #sFather#.",
"Mas eu nunca vi isso antes.",
"Eles estão com sua letra, #sFather#. E eles mostram o quadro completo da sua degradação.",
"Ainda não sei do que você está falando!",
"Estou falando de cartas de amor que você escreveu para uma certa jovem.",
"Juro para você que não escrevi essas cartas! Mas querido Deus, quem vai acreditar em mim quando vir isso?!",
"Hum. Ou você é um ótimo ator, #sFather#, ou você realmente não escreveu essas cartas. Estou feliz que não cabe a mim tomar essa decisão.",
"Não se desespere, #sFather#. Posso ver agora que você está dizendo a verdade. Ainda há esperança.",
"Ter esperança? Minha reputação está destruída!",
"Você sabe, eu poderia simplesmente 'perder' essas cartas.",
"O que eu poderia fazer para convencê-lo a entregá-los para mim?",
"Acho que 2.000 moedas de ouro podem me distrair o suficiente para deixá-las aqui.",
"Não! Não vou suborná-lo com o ouro da Igreja. Por favor, apenas saia.",
"Como quiser.",
"Tudo bem. Aqui está o seu dinheiro.",
"E aqui estão suas cartas.",
"Obrigado. E agora eu vou. E vou levar as cartas comigo",
"O que?! Achei que tínhamos concordado!",
"Você pensou errado. Eu estava testando sua história. Um homem inocente não tentaria comprar uma saída para os problemas. Agora eu sei que você é culpado",
"O que você quer dizer com #saddr#?",
"Fui enviado por ",
"Father Bernard",
"Father Bernard",
", para verificar alguns rumores desagradáveis sobre você.",
"Que tipo de rumores? Eu não tenho ideia do que você está falando.",
"Você está me dizendo que é inocente de trair seus votos como padre? E você não sabe quem colocaria esses rumores em movimento?",
"Meu Deus, não! Não tenho ideia de quem iria querer me difamar assim.\nPergunte a qualquer pessoa da cidade. Pergunte ao meu assistente! Todos dirão que não fiz nada de errado.",
"Talvez seja uma boa ideia.",
"Bem, tudo bem. Mas devo dizer que tal desrespeito não adiantará nada.",
"Eu percebo isso. Aceite meu presente para a Igreja.",
"Sinto muito, #sFather#, mas tenho que ir.",
"Claro, #saddr#. Quanto você quer doar?",
"Sinto muito, #sFather#, mas não posso fazer uma doação agora.",
"Receio que 100 moedas de ouro sejam tudo o que posso pagar agora.",
"Eu deveria pensar que o Senhor olharia com bondade para 1000 moedas de ouro.",
"Estou bem ultimamente, então darei 5.000 moedas de ouro.",
"A decisão é sua, #saddr#. Nunca é tarde para mudar - e tenha em mente que tudo será levado em conta no momento da sua morte.",
"Minha morte ainda está muito distante, se Deus quiser! Vamos falar sobre outra coisa.",
"Desculpe, #sFather#. Eu tenho que ir.",
"Agradeço-lhe o seu presente em nome da Santa Igreja, #saddr#.",
"Preciso falar com você, #sFather#.",
"Sinto muito, #sFather#, mas preciso ir.",
"Agradeço-lhe o seu presente em nome da Santa Igreja, #saddr#.",
"Preciso falar com você, #sFather#.",
"Sinto muito, #sFather#, mas preciso ir.",
"Agradeço-lhe o seu presente em nome da Santa Igreja, #saddr#.",
"Preciso falar com você, #sFather#.",
"Sinto muito, #sFather#, mas preciso ir.",
"Estou com medo ",
" ouro é tudo o que posso pagar agora.",
"Eu deveria pensar que o Senhor olharia com bondade ",
"Estou bem ultimamente, então vou dar ",
" moedas de ouro.",
"Estamos hoje aqui reunidos para celebrar, em plena guerra, a união destas duas pessoas apaixonadas. Se houver alguém aqui que tenha uma causa justa para explicar por que esses dois não deveriam se casar, deixe-o falar agora ou cale-se para sempre.",
"Você, #sgroom#, aceita esta mulher como sua esposa, para amá-la, honrá-la e cuidar dela enquanto vocês dois viverem?",
"Eu faço.",
"E você, #sbride#, aceita este homem como seu marido, para amá-lo, honrá-lo e cuidar dele enquanto vocês dois viverem?",
"Na verdade, é minha doação, mas também em nome do boticário local.",
"Ah! Uma alma em perigo, de fato. Isso de alguma forma ajuda a redimi-lo.",
"Esse é certamente o seu desejo.",
};
