string DLG_TEXT[106] = {
"Disseram-me que você fez um grande esforço para solicitar uma audiência. Meu nome é ",
". Agora, por favor, diga-me o propósito da sua visita ",
".",
"Meu nome é ",
".",
"Ah, é você de novo. O que traz você aqui desta vez? ",
"Eu gostaria de conversar com você sobre alguns negócios.",
"Sinto muito, mas há coisas que preciso fazer.",
"Então, por que você me distrai dos assuntos de estado muito importantes?",
"Gostaria de falar com você sobre um pequeno negócio.",
"Só estou aqui para prestar meus respeitos. Nada mais, ",
"Nesse caso, por favor, saia do meu escritório e deixe-me voltar para assuntos mais importantes.",
"Sim claro. Desculpe por ter incomodado você.",
"Estou ouvindo, ",
".",
"Estou aqui para receber minha recompensa pela morte de Dirty Garry.",
"Sinto muito, mas não tenho nada para conversar agora",
"Oh, ouvi sobre o que você fez. Da face de toda a colônia eu lhe mostrarei o nosso apreço.",
"Isso mesmo, gostaria de ver uma recompensa.",
"Você é um brincalhão. Ha ha. Aqui está o seu dinheiro.",
"Obrigado, sou seu humilde servo.",
"Então, sobre a aposta que você fez... depois de obter a aprovação do nosso departamento fiscal, vejo que temos... deixe-me ver... seis mil.",
"O que?! O negócio foi de 10 mil!",
"Eu não posso te ajudar. No futuro, tente ficar mais calmo.",
"O que quer que você diga, senhor. Porco sujo....",
", você está ciente de que é acusado de assassinato? Você foi encontrado junto ao corpo da vítima. O que você diz em defesa desta acusação?",
"Não tem nada a ver comigo. O homem já estava morto quando entrei no quarto! Disseram-me que ele estava apenas ferido e que poderia ter algumas informações importantes para mim.",
", Acabei de saber que um homem foi capturado quando tentava deixar a cidade com uma faca manchada de sangue em sua posse. Ele confessou o assassinato de que você foi acusado. Você será liberado imediatamente.",
"Obrigado. Eu sabia que poderia confiar na justiça aqui em Conceição.",
"Desejo desertar para Portugal.",
"De fato? Muito bem, agora você é cidadão português.",
"Agradeço sua infinita gentileza, senhor.",
"Oh sim? Tenho uma proposta para você, capitão.",
"De fato?",
"Vi que você concluiu a tarefa com sucesso; meus parabéns, capitão! Aqui está sua recompensa.",
"Meus agradecimentos; Foi um prazer ajudá-lo.",
"Você deve destruir o ",
" navio ",
"missão pirata",
" ameaçando o envio ",
". Se você afundá-la, vou recompensá-lo com uma boa quantia de ",
" ouro. O que você diz, capitão?",
"Você não ouvirá falar dela novamente, isso eu prometo.",
"Receio não poder ajudá-lo.",
"Anseio por perdão, Excelência.",
"Estou interessado em saber mais sobre as relações da Espanha com outras nações.",
"Estou procurando uma Carta de Marca.",
"Ah, ",
", que bom que você passou por aqui. Eu gostaria de apresentar meu ",
". Ela virá assim que terminarmos os negócios.",
"Ouvi dizer que estou pronto para uma promoção.",
"Não posso mais servir ",
", vossa Excelência.",
"Cansei de servir ",
"Como garantia de que você é um capitão competente e para recompensar meu tempo apresentando seu caso a ",
", devo te pedir ",
" ouro.",
"Sem chance.",
"Muito bem.",
" tem sempre o prazer de aceitar novos capitães ao seu serviço. ",
"Estamos atualmente em guerra com ",
"",
"nenhum grande poder, mas ",
". Claro, ",
"Os piratas devem sempre ser afundados à primeira vista.",
" À luz do seu serviço anterior ",
" concede a você a classificação de ",
"Vou deixá-lo orgulhoso, Excelência.",
"Você prejudicou ",
", e ",
" não esquece seus inimigos. Saia imediatamente, ou os guardas vão te jogar fora!",
"...",
"Você causou ",
" grande dano, capitão, mas ",
" está disposto a ignorar suas transgressões passadas... por um preço: ",
"Muito bem, senhor. Aceito.",
"É um prazer lidar com você, ",
"E você, Excelência.",
"Você é realmente! Excelente trabalho. Sua nova classificação é ",
". Além disso, você é premiado ",
" hectares de terra por ordem de ",
"Obrigado, senhor.",
"Tem certeza, ",
" lamentaremos perder seu serviço.",
"Sim eu sou.",
" não gosta de vira-casacas ",
"Uh, não importa.",
"Muito bem. Mas espero que você reconsidere, com o tempo...",
"Adeus, ",
"Huh?",
"Difícil.",
"Capitão Elting, o vice-almirante contou-me os seus feitos. Resolvi entregar-lhe a medalha da Ordem de Santiago como recompensa pela sua dedicação ao reino de Espanha.",
"Capitão, eu lhe dei uma medalha há alguns meses.",
"Sim, governador. Eu lembro.",
"Eu tenho um novo para você. Nunca um não espanhol recebeu este no passado, você é o primeiro.",
"Estou impressionado, Governador.",
"Em nome do meu Rei, Carlos II, aceite esta recompensa, Capitão Elting.",
"Obrigado Governador. É uma honra.",
"Ao receber esta medalha, você obtém um novo direito.",
"Que tipo de certo?",
"Sua liberdade.",
"O que? Posso parar de trabalhar como mercenário?",
"Sim capitão. Você está livre de agora em diante. Você não precisa mais trabalhar para o vice-almirante Benavides. É isso que você quer?",
"Sim, governador. Quero ter uma vida mais tranquila e talvez me tornar um simples comerciante.",
"Eu entendo. Desejo-lhe boa sorte para sua nova vida. Adeus, capitão.",
"Adeus, Governador.",
};
