string DLG_TEXT[40] = {
"Ei, capitão! Esta é sua primeira vez em #sisland_Quebradas Costillas#?",
"Por quê você se importa?",
"Não, amigo. Encontre outra pessoa com quem conversar.",
"Bem, eu poderia te mostrar o local...por um preço.",
"Quanto?",
"Não, obrigado. Posso encontrar o meu caminho.",
"Não preciso de ouro, capitão. Mas você pode me conceder um desejo algum dia",
"Um desejo? Tem certeza de que sua ajuda é digna de tal promessa?",
"Você não está fazendo sentido, rapaz. Vá embora.",
"Bem, eu sei quase tudo sobre quase todo mundo por aqui.\nSe você deseja negociar, posso conseguir um preço favorável. E se você procura algo mais interessante, meus contatos podem ser úteis.",
"Tudo bem. Mas se o seu desejo ofende a minha honra...",
"Eu me viro sozinho. Você pode ir.",
"Não desejo morrer jovem, capitão. Meu desejo não tem nada a ver com você pessoalmente. Então... o que te traz a #sQuebradas Costillas#?",
"Procuro um certo homem",
"Tente perguntar sobre ele na taverna. Se ele apareceu por aqui",
"Inês Diaz",
" deveria saber algo sobre ele.",
"Esse conselho não parece digno da promessa que te fiz.",
"Bem, eu mesmo posso tentar descobrir algo sobre esse homem, se você estiver disposto a me dizer o nome dele.",
"O nome dele é ",
"Raoul Rheims",
". Obtenha-me algumas informações úteis sobre ele e você realizará seu desejo.",
"Você não precisa saber disso.",
"É um acordo, ",
". E se você estiver indo para a cidade, basta seguir esse caminho e virar à direita.",
"Obrigado.",
"Justo, ",
". A propósito, se você estiver indo para a cidade, basta seguir esse caminho e virar à direita.",
"Obrigado.",
"Não, capitão. Não temos mais nada para conversar.",
"Eu vejo.",
"Capitão, espere! Consegui aprender alguma coisa!",
"Realmente?",
"Raoul Rheims",
" realmente esteve aqui! Ele chegou ao porto para reparos, mas depois partiu novamente.",
"É isso? Isso é tudo que você tem para mim?",
"Não, isso não é tudo. Acontece que eu sei para onde ele estava indo! Ele foi para #sisland_Conceicao#. Parece que ele tem alguns assuntos a tratar com o chefe dos contrabandistas daquela ilha.",
"Agora é mais parecido! Eu irei para lá imediatamente.",
"Não se esqueça do meu desejo, capitão!",
"Claro! Eu sempre mantenho minha palavra.",

};
