string DLG_TEXT[47] = {
", caro cliente, eu sou ",
", o proprietário do estaleiro local.",
"Eu sou ",
", capitão do '",
".",
", ",
". Como posso te ajudar, hoje, ",
"?",
"Meu navio precisa ser consertado.",
"Eu só quero conversar.",
"Eu devo ir.",
"Bem, é um prazer conhecê-lo. Meu estaleiro está ao seu serviço então.",
"Ótimo, ",
". Vamos ver o que sua jarda tem a oferecer.",
"Eu só quero conversar.",
"Eu devo ir. Obrigado.",
"Sobre o que exatamente você quer falar ",
"?",
"Nada no momento.",
"Hmm... você precisa de mais alguma coisa ",
"?",
"Sim, gostaria de utilizar os serviços do seu estaleiro.",
"Obrigado. Até a próxima!",
"O que exatamente você precisa?",
"Vamos ver o que sua jarda tem a oferecer.",
"Eu gostaria de instalar armas novas em meu navio.",
"Eu devo ir. Obrigado.",
"Recuso-me a negociar com uma pessoa com a sua reputação e relações. Agora saia, ",
", antes de chamar os guardas.",
"Muito bem.",
"Tudo bem, meu cais ao lado do forte está disponível para você. Se você quiser, direi ao meu chefe das docas para rebocar seu navio até lá. Só então poderei avaliar os danos e dizer quanto tempo e dinheiro serão necessários.",
"DOCA AO LADO DO FORTE?? Uhh... só me lembro que tenho... eeh... outro assunto urgente que preciso resolver primeiro. Adeus.",
"Após fechar esta caixa de diálogo, pressione ENTER para abrir a interface de mudança de vela.",
"Saída",
"As pessoas dizem que você recebeu um grande pedido. Acho que você precisa de alguns suprimentos então?",
"Sim, na verdade estou precisando de alguns suprimentos. A loja está toda esgotada. Você poderia me buscar ",
" Vou te pagar ",
" moedas de ouro.",
"Eu sou seu homem. Você terá esses suprimentos em pouco tempo.",
"Desculpe não estou interessado",
"Para pior, vou encontrar outra pessoa então",
"Parece que 'essas pessoas' estão tentando enganá-lo ou talvez você devesse perguntar mais. Não recebi nenhuma oferta... gostaria de ter.",
"Eu trouxe os materiais que você precisava",
"Muito obrigado. Aqui está o seu dinheiro.",
"De nada",
"Alguém chegou aqui antes de você, então já tenho tudo que preciso. Talvez a loja queira seus produtos",
};
