string DLG_TEXT[41] = {
"Capitão! É realmente você?",
"Sou eu, amigo! Na carne.",
"É um milagre! Como você conseguiu se salvar?",
"Acalme-se! Eu lhe fiz uma pergunta.",
"Desculpas, capitão. Estamos muito felizes em ver você são e salvo.",
"E estou feliz em ser visto. Mas a questão permanece: O que te trouxe aqui?",
"Bem, depois de você ter sido levado ao mar, fomos atirados pela tempestade por mais algumas horas. Quando a tempestade finalmente acalmou, descobrimos que a terra seca mais próxima era #sisland_Isla Muelle#. O navio ficou muito danificado, por isso recorremos aos serviços do estaleiro espanhol de lá. Demorou bastante, mas agora '",
"ship storage",
" está em muito bom estado.",
"Isso é uma boa notícia. Mas como você pagou pelos reparos?",
"Reunimos nosso ouro. Alguns de nós ficaram menos felizes em contribuir do que outros... mas os seus cortes e hematomas irão sarar. Afinal de contas, este também é o nosso navio - embora a tripulação fique satisfeita em saber que o nosso capitão está de volta!",
"Bem, estou grato a todos vocês.",
"Isso exige uma celebração! Por que não vamos para a taverna?",
"Melhor ainda, vamos levar a taverna aos homens. Mandarei enviar dez barris de rum para o navio. Deixe-os beber à minha gratidão!",
"Viva o capitão! Deus o abençoe, ",
"!",
"Agradeço a todos.",
"É realmente um milagre você ter sobrevivido! Deus deve estar com você, capitão!",
"Eu gostaria de pensar assim, embora às vezes me pergunte...",
"...ou o demônio do mar! Ouvi dizer que ele vê com bons olhos os marinheiros ousados e os mantém protegidos do perigo!",
"Não acredito que já tenha ouvido essa história antes.",
"Que história? Jovannie Speckled, do brigue 'Ardent', me disse que viu o próprio demônio do mar!",
"Viu o diabo? No fundo de uma garrafa de rum, aposto.",
"Não, capitão. Ele jurou que não tinha tocado numa gota.",
"Esperem por mim aqui, homens!",
"Não, capitão! Me leve com você! Você não deveria entrar sozinho na cova dos leões!",
"Não sou uma garotinha que precisa de acompanhante, meu amigo.",
"Claro que não, capitão. Mas... acabamos de resgatar você dos mortos! Faça isso para minha paz de espírito.",
"Não não. Uma grande empresa só atrairia problemas.",
"Mas o que faremos enquanto você estiver fora?",
"Você vai gostar do rum. Ah, e peça a alguns marinheiros que esperem por mim perto da saída de #sOxbay#.",
"Você acha que pode ter que sair correndo da cidade?",
"Espero que não. Mas você nunca sabe!",
"Não há como fazê-lo mudar de ideia, capitão? Dois sujeitos fortes poderiam facilmente ajudá-lo a lidar com qualquer problema que possam atrair.",
"Então deixe-os ajudar a proteger o navio. Estarei de volta antes que você perceba que fui embora",
"Tudo bem. Esperamos por você aqui, capitão! Se algo der errado, volte aqui o máximo que puder. Nós vamos cobrir você!",
"Eu acredito nisso. Mas não se mostre antes disso!",
"Vamos levá-lo para o navio, capitão. Estou feliz que tudo tenha terminado tão bem.",
"Tem? Vá agora. Te seguirei em breve!",

};
