string DLG_TEXT[25] = {
"...",
"...",
"O que você quer?",
"Você é François Moulin?",
"Sim, como você me conhece?",
"Falei com sua filha. Ela está bastante preocupada com o seu súbito desaparecimento há duas semanas.",
"É apenas uma situação temporária. Vou deixar a ilha hoje no 'Amsterdam', o navio que vocês veem ali na água. O capitão Pieter Boelen prometeu me levar para uma ilha segura. Eu arrisco a vida da minha filha e a minha própria se permanecer nesta ilha por mais tempo.",
"Mas e sua filha? Você vai deixá-la para sempre sem contar o que está acontecendo? E por que é tão perigoso para você ficar nesta ilha?",
"Claro que não vou esquecer da minha filha. Enviarei uma mensagem a ela quando chegar a uma ilha segura. Devo deixar este lugar. Eu sei demais. Um oficial, #sAntoineChamfort#, desvia o dinheiro das autoridades e mata qualquer um para manter isso em segredo.",
"Então #sChamfort# está tentando te matar porque você sabe demais? E agora você também me contou, então ele provavelmente estará tentando me matar também. Parece que não tenho escolha a não ser tentar fazer algo em relação a esse oficial. Como você sabe disso? E como você pode ter tanta certeza de que ele vai te matar?",
"Meu melhor amigo, que trabalhava no forte, me contou. Poucos dias depois ele foi encontrado, assassinado enquanto dormia. Tenho certeza que #sAntoineChamfort# fez isso.",
"E você tem medo de que #sChamfort# tenha descoberto que seu amigo lhe contou sobre as atividades dele?",
"Exatamente! #sChamfort# tem espiões por toda parte. Esta ilha não é segura para mim. Eu queria partir antes, mas o capitão Boelen é o primeiro capitão disposto a levar um fugitivo como eu com ele.",
"Isso é muito gentil da parte dele. Mas por que você não falou com o governador? Tenho certeza de que ele ficaria muito interessado em ouvir sobre um oficial seu desviando seu dinheiro.",
"Não tenho nenhuma evidência. Seria pura loucura!",
"Eu vejo. Mas você não deveria precisar sair da ilha. Vou falar com #sChamfort# e resolver tudo isso. Onde posso encontrá-lo?",
"Tome cuidado. Ele é um covarde, mas um covarde perigoso. Ele nunca lutará com você em uma luta justa. Ele vai te matar enquanto você dorme ou te atacar com muitas outras pessoas para apoiá-lo.",
"Então agora ele pensa que está seguro com seus amigos soldados no forte, certo? Como ele está errado! Vou visitá-lo, com ou sem soldados. Só há uma maneira de tratar a escória assim! Espere por mim no acampamento do Bucaneiro.",
"Aí está você! Eu estava começando a ficar preocupado. Como foi?",
"Você estava certo. Eu blefei tendo evidências de seu suborno e ele tentou me matar quando lhe virei as costas.",
"Mas você ainda está vivo. Posso presumir que #sChamfort# está morto então?",
"Você pode realmente assumir isso com segurança. Agora me siga, vamos avisar Angelique. Ela já está preocupada há muito tempo.",
"Muito obrigado por sua ajuda. Por favor, aceite este diamante e este diário antigo como agradecimento pela sua ajuda. Estes me foram dados por um velho pirata moribundo durante minha estada no acampamento dos Buccaneers. Por favor, mantenha-os em agradecimento pela sua ajuda.",
"Muito obrigado. Mas não preciso de um diário antigo. Você fica com ele. Ou entregue-o ao Capitão Boelen por sua ajuda.",
"Isso é muito amigável da sua parte. Muito obrigado. Adeus a vocês dois. E não se esqueça de dar os meus cumprimentos ao Capitão Boelen.",

};
