string DLG_TEXT[154] = {
"É bom ver você, ",
". Meu nome é ",
", e estou inteiramente a seu serviço.",
"E meu nome é ",
". Sou o capitão de um belo navio.",
"É bom ver você de novo, ",
".",
"É você de novo? Eu esperava nunca mais vê-lo aqui.",
"E boa saúde para você ",
".",
"Você não pode esperar, mascate.",
"Gostaria de inspecionar minhas mercadorias?",
"Isso seria legal. Mostre-me o que você tem.",
"Mais tarde, mas agora tenho uma coisa para falar com você.",
"Outra hora quando eu voltar aqui.",
"Vamos negociar muito ou você quer as coisas pequenas, capitão?",
"Quero vender a carga que trouxe.",
"Quero comprar algumas coisas para mim pessoalmente.",
"Não vamos fazer isso de jeito nenhum. Tenha um bom dia.",
"Estou ouvindo você, sobre o que você quer falar?",
"Estou ouvindo você.",
"Fui instruído a entregar uma remessa para você.",
"Você não precisa de um capitão, senhor? Eu tenho um ótimo navio e posso levar qualquer carga para onde você quiser.",
"Shh... Shh. Eu sou de ",
"Ah, é você de novo! Você está tentando me colocar em mais problemas?",
"Pague apenas pelo sândalo que entreguei a você e você não me verá mais.",
"Quero falar com você sobre uma carga de sândalo entregue a você há pouco tempo e o dinheiro que você teve que pagar por ela...",
"O quê? É você?!",
"Você não esperou, idiota?!",
"É você de novo?!",
"Me reconhece? Agora vamos falar sério. Muito sério. Tão sério, na verdade, que recomendo que você tranque a loja para não sermos incomodados.",
"O que posso fazer por você, monsieur?",
"Preciso falar com você. Então tranque a loja para evitar mal-entendidos - vai ser uma longa conversa.",
"O quê? É você?!",
"Sim... E tenho uma oferta para você que você não pode recusar.",
"Você me arruinou! Agora eles vão confiscar minha loja e me mandar para as minas!",
"Se você passar a loja para #sBeltrop#, eu vou falar bem de você.",
"Mas não há tempo para conversar agora.",
"Não, você não tem. Pelo menos não enquanto você estiver afundando #snation_desc# navios.",
"Nesse caso, adeus.",
"Sinto muito, mas não tenho nada para você agora.",
"Ok, passo por aí mais tarde.",
"Sinto muito, mas sua embarcação não é tão espaçosa para cumprir a missão que desejo lhe dar.",
"Bem, então vou até aí mais tarde.",
"Oh! Eu estava prestes a lhe pedir um favor. O problema é que preciso entregar uma remessa para ",
", o mais rápido possível. Se você puder fazer isso em um mês, receberá quando chegar ao local ",
"piastras de recompensa. Que tal?",
"Eu concordo.",
"Não funciona para mim.",
"Eu disse a você mais cedo hoje que não tenho nada para você.",
"Oh, sinto muito.",
"Você se lembrou do seu caso atribuído tarde demais, não acha? Já consegui tudo o que queria. Adeus.",
"Tenha um bom dia.",
"Oh! Eu estava esperando por isso há muito tempo. Aqui está sua recompensa, jovem ",
"De nada.",
"Não preciso de seus serviços neste momento.",
"Que pena. Então vamos falar de outra coisa.",
"Oh! Você deve ter trazido a carga de sândalo que estou esperando há tanto tempo?",
"Exatamente. Talvez seus homens possam lidar com o descarregamento?",
"Claro! Enquanto isso, você descansa no quarto lá em cima.",
"Essa é uma boa sugestão, acho que vou aceitar.",
"Está feito, só posso imaginar o lucro que terei vendendo esse contrabando, ahaha... Oh, quem é esse?!",
"O quê?!",
"(Para os soldados): Este é apenas meu visitante, cavalheiros. (Para você): Saia daqui e não tente resistir a eles. Isto é um teste, venha me ver em duas horas e resolveremos as coisas.",
"(Para os soldados): Uh. Vejo que estou incomodando você... Bem, devo ir?",
"Que sândalo, que dinheiro! Do que você está falando!",
"Ha! Você decidiu negar o fato de que a carga foi entregue a você?",
"Não, não, mas eu não tenho essa carga! Ela foi confiscada, tive que pagar uma multa enorme e estou à beira da ruína!",
"Que interessante. E #sBeltrop#, por algum motivo, tem certeza de que é tudo culpa sua e me pediu para investigar o assunto.",
"Deus me livre! Você acha que eu quero fazer um inimigo na forma de um homem tão poderoso quanto #sDesmondRay#?!",
"Acho que preciso de dinheiro seu, escrivão de impostos, e o mais rápido possível!",
"Tenha misericórdia! Tenho uma família, uma filha para preparar para o casamento! Dê-me pelo menos um adiamento!",
"Pela última vez, dinheiro no barril!",
"Ok, quantos dias você precisa para levantar o dinheiro?",
"Tudo bem, tudo bem. Vou relatar seus problemas para #sBeltrop#.",
"Onde vou conseguir? Estou à beira da ruína!",
"Não é problema meu. #sBeltrop# precisa do dinheiro, e se eu fosse você, não insistiria.",
"Ok, ok, aqui está seu dinheiro.",
"Oh, seu bastardo! Então você tinha dinheiro!",
"Eu disse a você - este é o dote da minha filha! Como vou casá-la agora?",
"Pare de choramingar. Espero não vê-lo novamente. Adeus.",
"Oh, não muito! Só alguns dias, não mais! Você fica com um quarto na taverna por enquanto, e eu o encontrarei lá assim que juntar o dinheiro.",
"Fechado.",
"Obrigado, você é tão gentil comigo, monsieur.",
"Guarde seus agradecimentos para si mesmo.",
"Do que você está falando?! Se for sobre dinheiro, então eu... Eu ainda não o coletei, espere um pouco mais.",
"Você não o coletou, disse?! E para os assassinos, então, havia ouro?!",
"Do que você está falando! Eu não ousaria, eu não ousaria, eu lhe asseguro!",
"É, eu até acreditaria se você não estivesse tremendo tanto e não fedesse a suor de medo.",
"Eu só tenho malária! É por isso que estou tremendo, estou doente, #smonsieur#, essa é a explicação!",
"Pare de explicar! Eu preciso do dinheiro. AGORA!",
"Mas eu já te disse antes...",
"Ou eu dou um tiro na sua testa ou você me dá o dinheiro.",
"Ahem... Ok, só, pelo amor de Deus, não me mate! Aqui... Aqui está o valor total.",
"Ótimo. E considere-se sortudo, negociante de arrendamento.",
"O que você está insinuando?!",
"#sBeltrop# não gosta que você distorça as cartas, negociador. Na verdade ele odeia isso...",
"O quê?! Você ousa me ameaçar, cachorrinho?!",
"Eu? Não, não sou eu quem está te ameaçando, mas sim #sBeltrop#, e eu só estou trabalhando para ele.",
"Filhote?! Você pensou duas vezes antes de dizer isso?! Vou enfiar essas palavras de volta na sua garganta!",
"E o que esse sanguessuga quer de mim?!",
"Venda sua loja...",
"O que há de errado com você? Diga ao seu #sBeltrop# que não vou vender minha loja!",
"Então terei que te matar.",
"Tudo bem. Vou embora, mas #sBeltrop# provavelmente enviará alguém menos paciente no meu lugar.",
"Você não vai me intimidar, e eu posso ficar com minha loja!",
"O tempo dirá. (Tente colocar discretamente seu anel no bolso dele).",
"O tempo dirá. (Sair).",
"Sim, sim, claro!",
"Mas ",
"(Você conseguiu distrair #sshopkeeper# com uma conversa e silenciosamente jogou para ele alguns de seus anéis, assim como uma bolsa de dinheiro com suas iniciais bordadas).",
"...",
"Ei! Tire suas mãos do meu bolso, seu canalha!",
"Ok, ok, eu estou indo embora agora.",
"Essa foi a gota d'água! Quem você está chamando de canalha? Eu vou te dar de comer para os tubarões!",
"Você está blefando! A cidade está cheia de soldados, e se você encostar um dedo em mim, você será enforcado!",
"Olha só! Argh!",
"Você está certo, arriscando seu pescoço pelo prazer de ver seu cadáver...",
"É! Eu sabia! Você não tem coragem suficiente!",
"É isso! Você me irritou!",
"Grite ou berre, babar não vai ajudar a causa. Como eu disse, estou aqui sob as ordens de #sBeltrop#.",
"Seu cachorro #snation#! Não tenho medo de você! Guardas!",
"Diga olá ao diabo quando o encontrar!",
"Saia daqui! Não quero ter nada a ver com você!",
"Sua palavra é minha lei. Posso imaginar o quão chateada Susanne ficará...",
"S... Susanne?! O que você fez com ela?!",
"Nada ainda, mas tenho alguns negócios com ela... Mas podemos chegar a um acordo.",
"Qualquer coisa, deixe-a ir!",
"Agora essa é uma conversa diferente! Venda sua loja.",
"Eu não entendi...",
"quer que você venda sua loja. Ou melhor, entregue-a para mim, e ele colocará seu homem aqui.",
"Você está louco?!",
"Bem, já que não concordamos, vou deixar minha equipe se divertir com sua filha...",
"Espere! Tudo bem! Vou arrumar minhas coisas e ir embora hoje. Apenas liberte minha filha.",
"Ótimo. Encontre-me na taverna em três horas, eu vou reservar um quarto. Quando você me entregar as chaves, eu te darei Susanne.",
"Adeus, eu vou para a Europa.",
"Tenha uma boa navegação.",
"Você vai apodrecer no inferno!",
"Saia!",
"Maldito seja! Aqui... só um minuto... aqui estão seus papéis. Agora você é o dono desta loja, agora me deixe em paz, eu preciso arrumar minhas coisas!",
"É um prazer fazer negócios com você.",
"Eu cumpri o que combinamos. Aqui estão as chaves da loja e os papéis necessários.",
"Muito bem. Eu também manterei minha palavra - vá para o porto, lá você verá sua filha.",
"Agora vá embora. Eu vou ficar com sua filha, ha-ha!",
"O quê? Isso é absurdo! Eu sou completamente inocente!",
"Ah, tudo bem! Olha, depende de você!",
"Eu não sou culpado! Fui enganado!",
"N-n-não... Não sei como consegui...",
"me enviou uma mensagem dizendo que eu deveria esperar 300 de sândalo. Você só trouxe ",
". Onde está o resto?",
"Err... parte deve ter caído no mar em uma tempestade. Vou comprar mais em algum lugar para completar a carga completa.",
"Bem, ",
"? Você tem a carga completa com 300 de sândalo agora?",
"Sim, vou esperar lá em cima novamente enquanto seus homens descarregam.",
};
