string DLG_TEXT[28] = {
"Para onde quer que você vá, estranho, apenas vá",
"Espere, estranho! Não me mate.",
"Desculpe! Eu disse que te levaria para sair, e vou cumprir essa promessa",
"O que você quer?",
"É bom te ver de novo. Você finalmente decidiu me contratar?",
"Eu tenho. Quanto você está pedindo pelos seus serviços?",
"Vejo você na próxima vez.",
"Eu não quero brigar com você. Tenho mais bom senso do que lutar contra aqueles que são mais fortes do que eu.",
"Você está se tornando covarde? Você está tão acostumado com amadores que não quer um desafio de verdade?",
"Isso é sensato. Então o que você quer?",
"Para servir você! Ninguém nunca me venceu em uma luta direta antes. Só você.",
"Desculpe, mas não preciso dos seus serviços agora.",
"Bem, então - bem-vindo à minha tripulação.",
"Estou feliz em atendê-lo, capitão. Meu nome é ",
".",
"E o meu é ",
". Vamos falar sobre o seu salário.",
"Suponho que 2.000 peças de ouro por mês serão suficientes.",
"Aqui está o seu dinheiro.",
"O problema é que estou sem dinheiro agora. Meu navio e tripulação desapareceram na tempestade. Eu não posso te pagar agora",
"Não, isso é demais para mim.",
"Isso não é um problema. Vou esperar o tempo que for preciso.",
"Pois bem, vamos considerar isso um acordo. ",
"Isso não vai funcionar, infelizmente. Mas volte quando tiver dinheiro.",
"Tudo bem.",
"Isso é ruim. Bem, estarei aqui se você mudar de ideia.",
"Vejo você por aí.",
"Eu não acho que você terá que esperar. Eu vou te matar!",

};
