string DLG_TEXT[24] = {
"Bem-vindo à casa do Senhor, #saddr#. Como posso ajudá-lo?",
"Em nada, preciso ir",
"Gostaria de fazer algumas perguntas sobre o padre chamado ",
"Father Jerald",
"Father Jerald",
".",
"Ah! Você deve ser o inquisidor. Meus pedidos finalmente produziram resultados!",
"Vamos revisar alguns detalhes. Pelo que entendi, você afirma que o padre leva uma vida de gula e depravação.",
"Sim, e não faço tal acusação levianamente. Eu tenho provas. ",
"Que tipo de prova?",
"Tenho em minha posse cartas de amor que ele escreveu a uma certa jovem.",
"isso é chocante! Posso pegá-los emprestadas?",
"Claro. Aqui estão eles.",
"Você vai me perdoar, mas tenho que perguntar: como você os conseguiu?",
"A jovem me deu-os na esperança de que eu pudesse ajudá-la a acabar com as atenções indesejadas do padre.",
"Eu vejo. Terei que falar com ela, claro, para confirmar a veracidade das suas acusações. Você pode me dizer o nome dela e onde posso encontrá-la?",
"Certamente. O nome dela é ",
"Greenford_officiant",
"Greenford_officiant",
". Ela trabalha na taberna.",
"Tudo isso é muito interessante. Mas sinto que é justo dizer-lhe que já determinei que o padre é inocente e foi falsamente acusado.",
"Obrigado pela ajuda.",
"Inocente? Em quem você vai acreditar? Esses moradores locais, que ouviram a história do padre enquanto ele estava bêbado como um gambá - ou eu, que te dou a prova que você pode segurar nas mãos?",
"Ainda não decidi. Mas investigarei sua história - e você pode ter certeza de que os culpados neste assunto serão punidos.",
};
