string DLG_TEXT[80] = {
"Olá, ",
". E qual é seu nome?",
"Posso saber o seu nome, ",
"?",
"Para quem tenho a honra de falar?",
"Eu sou ",
", capitão do ",
".",
"Olá de novo, ",
"Ah, ",
"! Muito bom te ver.",
"Olá querido ",
". Estou tão feliz que você veio!",
"Olá, querido! Estou tão feliz que você veio. Parece que faz uma eternidade desde a última vez que te vi!",
"É um prazer vê-lo, como sempre. Mas tenho de ir embora.",
"...",
"Mas eu preciso ir.",
"((( Fazer conversação )))",
"((( Propor casamento )))",
"Então, me diga, o que está acontecendo por aqui?",
"Quanto a mim, meu amor. Mas vamos... nos reapresentar... em particular.",
"Ah, então você deve estar cheio de... coisas para me contar. Então vamos.",
"Eu sou ",
". Prazer em conhecê-lo, ",
"Ah, meu nome é ",
", e estou muito feliz em conhecê-lo",
"! Ah, estou muito feliz em conhecê-lo! Ora, todo mundo já ouviu falar de suas façanhas arrojadas!",
"O prazer é todo meu, senhora.",
"((( Você mantém uma conversa agradável com a #slady#. )))",
"...",
"(((A ",
" do governador fica impressionada com sua inteligência e charme. #spronoun# concorda em coletar informações para você no tribunal do governador. )))",
"E eu também conheço o lugar!",
"Vá em frente!",
"Você conquistou meu coração ",
", mas meu pretendente é um #sman# muito ciumento. Tenho certeza que #spronoun# irá desafiá-lo para um duelo...",
"Muito bem. Nosso amor um pelo outro me protegerá...",
"Ah. Então tenho medo de me retirar...",
"Oh! Isso é muito simpático, ",
", mas vamos falar de outras coisas...",
"Desculpe, mas devo me despedir...",
"((( Sua ",
" te diz isso ",
"nada de muito importante aconteceu. )))",
"...",
"Ah, muito bem, meu amor!",
"Seu amor foi para mim um escudo mais forte que qualquer aço...",
"Agora, vamos para a igreja!",
"Vá em frente, meu amor.",
"Um maravilhoso dia - e noite! - passa...",
"! eu amor é só para mim, senhor! En garde!",
"Só me restam duas palavras: en garde!",
"Você me superou em um combate justo ",
". Desejo felicidades a ambos e vou me despedir.",
"Você foi um oponente honrado; Eu desejo você bem.",
"Minha senhora, temo que o mar me chame e eu não possa estar em terra o suficiente para ser o marido que você merece.",
"Que bom conhecer você, mas estou indo para coisas melhores.",
"Se você precisa ir, você deve; mas sempre me lembrarei do nosso tempo juntos.",
"Ora, que atrevimento! Como você ousa me tratar assim!",
"Assim como eu.",
"...",
"Eu faço.",
"[Sacerdote] Então, pelo poder que me foi conferido por esta paróquia e pelo bom Senhor, declaro-vos agora marido e mulher. Pode agora beijar a noiva.",
"X",
"Sim.",
"Eu vou.",
"Er... sim, eu vou.",
", tome este anel como um sinal do meu amor e fidelidade. Em nome do Pai, e do Filho, e do Espírito Santo.",
"Arrr!",
"Bem, não sei se isso lhe interessará, mas ouvi uma conversa entre meu pai e um enviado espanhol. O comboio da prata, que transporta toda a prata das colônias espanholas na América do Sul, está a caminho de #sCartagena#.",
"Você sabe como os espanhóis reúnem toda a prata de suas colônias sul-americanas e a enviam para casa em uma grande frota? Essa frota foi avistada a caminho de #sCartagena#. Então a prata provavelmente também está a caminho.",
"Algo interessante surgiu na conversa depois do jantar ontem à noite. O comboio da prata está a caminho de #sCartagena# neste momento, transportando toda a prata das colônias espanholas na América do Sul!",
"Obrigado, minha querida! Isso certamente é interessante. Precisarei fazer meus próprios preparativos para aquele comboio prateado!",
"O comboio prateado certamente estará bem guardado e duvido que consiga pegá-lo. Mas obrigado por me contar de qualquer maneira.",
"Prefiro não fazer da Espanha um inimigo tentando atacar seu comboio prateado.",
"Talvez eu tenha esquecido de contar, mas mantenho a posição de ",
" com a Espanha. Você deveria ter mais cuidado com os segredos deles, minha querida!",
"O prazer é todo meu, bom senhor.",
"Seu amor é só para mim, senhora! En garde!",
"Bom senhor, temo que o mar me chame e não possa estar em terra o suficiente para ser a esposa que você merece.",
};
