string DLG_TEXT[194] = {
"Disseram-me que você fez um grande esforço para solicitar uma audiência. Meu nome é ",
". Agora, por favor, diga-me o propósito da sua visita ",
".",
"Meu nome é ",
".",
"Ah, é você de novo. O que traz você aqui desta vez? ",
"Eu gostaria de conversar com você sobre alguns negócios.",
"Sinto muito, mas há coisas que preciso fazer.",
"Então, por que você me distrai dos assuntos de estado muito importantes?",
"Gostaria de falar com você sobre um pequeno negócio.",
"Estou aqui apenas para prestar meus respeitos, #saddr#. Nada mais.",
"Nesse caso, por favor, saia do meu escritório e deixe-me voltar para assuntos mais importantes.",
"Sim claro. Desculpe por ter incomodado você.",
"Sinto muito, mas não tenho nada para conversar agora.",
"Oh sim? Existem alguns hostis em nossas águas.",
"Esses hostis parecem interessantes.",
"Vi que você concluiu a tarefa com sucesso; meus parabéns, capitão! Aqui está sua recompensa.",
"Meus agradecimentos; Foi um prazer ajudá-lo.",
"Você deve destruir o ",
" navio ",
"missão pirata",
" ameaçando o envio ",
". Se você afundá-la, vou recompensá-lo com uma boa quantia de ",
" ouro. O que você diz, capitão?",
"Você não ouvirá falar dela novamente, isso eu prometo.",
"Receio não poder ajudá-lo.",
"Anseio por perdão, Excelência.",
"Você pode me falar sobre as relações internacionais no Caribe, Excelência?",
"Estou procurando uma Carta de Marca para legalizar minhas ações em nome da nação #sgov_nation#.",
"Ouvi dizer que estou pronto para uma promoção.",
"Não posso mais servir ",
", vossa Excelência.",
"Cansei de servir ",
"Devido à sua posição junto à nossa nação e para recompensar meu tempo apresentando seu caso a ",
", devo te pedir ",
" ouro.",
"Sem chance.",
"Muito bem. Esse é um pequeno preço para garantir que não serei considerado um pirata pelas minhas ações.",
"#sgov_nation# tem sempre o prazer de aceitar novos capitães ao seu serviço. ",
"Estamos atualmente em guerra com ",
"",
"nenhum grande poder, mas ",
". Claro, ",
"Os piratas devem sempre ser afundados à primeira vista.",
" À luz do seu serviço anterior ",
" concede a você a classificação de ",
"Vou deixá-lo orgulhoso, Excelência.",
"Você prejudicou ",
", e ",
" não esquece seus inimigos. Saia imediatamente, ou os guardas vão te jogar fora!",
"...",
"Você causou ",
" grande dano, capitão, mas ",
" está disposto a ignorar suas transgressões passadas... por um preço: ",
"Muito bem, Excelência. Aceito.",
"É um prazer lidar com você, ",
"E você, Excelência.",
"Você é realmente! Excelente trabalho. Sua nova classificação é ",
". Além disso, você é premiado ",
" hectares de terra por ordem de ",
"Obrigado, Excelência.",
"Tem certeza, ",
" lamentaremos perder seu serviço.",
"Sim eu sou.",
" não gosta de vira-casacas ",
"Uh, não importa.",
"Muito bem. Mas espero que você reconsidere, com o tempo...",
"Adeus, ",
"Huh?",
"Difícil.",
"Quais são suas ordens, #saddr1#?",
"Devo administrar esta colônia.",
"Você precisa de alguma ajuda, #saddr2#?",
"Há coisas que tenho que fazer.",
"Você receberá 50 porcento do valor de qualquer navio que vender como sua parte do prêmio em dinheiro. Além disso, há um preço fixo para qualquer navio premiado legítimo vendido por aqueles que estão a meu serviço.",
"Parece lucrativo! E nenhuma negociação sobre preços será certamente bem-vinda ",
"Obrigado, ",
". Você tem algum pedido para mim?",
"Não deixe de ler este livro 'Arte da Guerra'. Eu não gostaria que você fosse a causa de um incidente internacional!",
"Prometo que estudarei isso com atenção.",
"Você poderia me aconselhar sobre como evitar ser considerado pirata, excelência?",
" Também ",
"Tenho um problema com contrabandistas.",
"Eu gostaria de ouvir sobre os contrabandistas.",
"Ultimamente, mais e mais contrabandistas estão aparecendo aqui. Quero pedir que você investigue isso. Você receberá uma carga adequada. Por favor, infiltre-se em suas fileiras e relate suas descobertas para mim. Como recompensa por qualquer coisa que você denunciar, você receberá uma parte do dinheiro que os contrabandistas pagam por essa carga.",
"Isso parece um trabalho para mim!",
"Não acho que este seja um bom trabalho para mim.",
"Muito bem. Você receberá #samount# #scargo#. Esteja avisado, não tente fugir com a carga ou o dinheiro dos contrabandistas! Além disso, lhe darei um documento que comprova que você está ao meu serviço. Isso pode ajudá-lo em alguns casos. Mas cuidado, não deixe os contrabandistas verem isso. Se o fizerem, negarei tudo.",
"Obrigado, #saddr#!",
"Eu tenho algo que você vai querer ver",
"Isso é muito interessante, você fez um trabalho muito bom.",
" Como recompensa eu te pagarei ",
" Mas acho que você mal arranhou a superfície, então, por favor, continue e tente descobrir mais!",
"Bom trabalho! Esperávamos que houvesse uma lista como esta, mas nunca conseguimos encontrá-la!",
"Ah! Então é assim que eles fazem! Obrigado pela informação.",
"Você já teve tempo de olhar os relatórios que fiz?",
"Na verdade, eu fiz. E acho que você nos forneceu todas as informações que precisávamos. Talvez precisemos de mais informações mais tarde. Mas por enquanto isso servirá. Como forma de gratidão, aceite este pequeno presente.",
"Ok #saddr#, quando precisar de mim novamente, por favor me avise.",
"Parece que alguns dos comandantes do seu forte disparam contra mim à primeira vista, embora eu não seja um inimigo.",
"Um mal-entendido, hein? Apenas me pague a modesta quantia de ",
" ouro e garantirei que isso seja resolvido imediatamente.",
"Até mesmo para um dos amigos da nossa nação? Garantirei que isso seja resolvido imediatamente!",
"Você poderia provar sua lealdade a #sgov_nation# através de sua ajuda.",
"Parece que perdi meu navio, #saddr#. Mas não posso causar muitos danos aos nossos inimigos sem um.",
"Isto não é motivo de risada! Você tem sorte de precisarmos de todos os capitães disponíveis. Darei a você um novo comando em vez de arrastá-lo para uma corte marcial, mas não espere uma promoção tão cedo!",
"Não vou decepcionar você, #saddr#. Isso eu prometo!",
"Você é uma vergonha para minha grande nação! Você está dispensado do serviço de forma desonrosa. Saia da minha frente!",
"Eu deveria ter previsto isso, suponho. Poderemos nos encontrar novamente no futuro, embora provavelmente seja em circunstâncias diferentes. E você pode não gostar!",
"A propósito, preciso que você devolva aquele documento que lhe dei. Não será mais válido.",
"Claro, #saddr#.",
"Agora, vá para #sGreenford# Naval HQ, por favor. #sbriefing_officer# espera você lá com suas novas ordens, eu acredito.",
"Muito bom, #saddr#. Irei navegar para #sGreenford# imediatamente.",
"O que os outros piratas estão dizendo sobre mim atualmente?",
"Eles ouviram falar de suas recentes façanhas! Eles estão ligando para você ",
"Seu ataque não passou despercebido entre os Irmãos da Costa. Eles começaram a se referir a você como ",
"Esse último saque foi o assunto da taverna por dias! Você está sendo chamado ",
"Normalmente isso seria verdade. Suas façanhas deveriam ter lhe rendido uma promoção.\nNo entanto, recebi a notícia de que você tem executado prisioneiros de guerra. Isso viola os regulamentos que você deve seguir.\nPior, se nossos inimigos souberem disso, eles poderão, em represália, executar nossos homens que são seus prisioneiros.\nComo você talvez não saiba disso, estou inclinado a clemência desta vez. Sua promoção está bloqueada, mas nenhuma ação adicional será tomada.",
"Obrigado pela sua misericórdia, Excelência.",
"Esteja avisado, no entanto. Você não tem mais a desculpa da ignorância. Se eu souber de novas execuções de sua parte, você será demitido do nosso serviço.",
"\nAlém disso, entendo que você possui Cartas de Marca de outras nações. Escreverei aos seus embaixadores para informá-los de tudo isto. Seus governadores também não aceitarão bem a execução de prisioneiros de guerra.",
"Eu entendo, Excelência. Adeus.",
"Você precisaria entrar em contato com os contrabandistas locais, para isso eu lhe forneceria uma carga adequada. Infelizmente, seu navio não tem espaço para essa carga.",
"Muito bem, voltarei quando tiver mais espaço no meu porão.",
"Desejo informar que fui eu quem prendeu os contrabandistas. Você pode ler os detalhes completos em meu relatório.",
"Muito bom, #saddr#!",
" Agora, sobre a #samount# #scargo# que você recebeu. Isso é propriedade do Estado e deve ser devolvido. ",
"Está sendo descarregado do seu navio agora.",
"Justo.",
"Você não parece mais ter isso. Você tem um mês para recuperá-lo. Se você não fizer isso, presumirei que você roubou a carga e será declarado fora da lei.",
"Não se preocupe, eu devolverei sua carga para você, de uma forma ou de outra!",
" Agora, você recebeu a quantia de #smoney# dos contrabandistas em troca da carga que o Estado lhe forneceu, então esse dinheiro também pertence ao Estado. Por favor, devolva-o.",
"Em seguida, você recebeu a quantia de #smoney# dos contrabandistas em troca da carga que lhe foi fornecida pelo Estado, de modo que esse dinheiro também pertence ao Estado. Por favor, devolva-o.",
"Certamente, Excelência.",
"Umm... eu não tenho tanto agora.",
"De fato. Então você tem um mês para arrecadar #smoney# e voltar aqui. Se você não fizer isso, presumirei que você roubou o dinheiro e será declarado fora da lei.",
"Então é melhor eu sair imediatamente para recuperar seu dinheiro!",
"E agora a sua recompensa. ",
"Para entrar em contato com os contrabandistas e relatar suas atividades, você receberá ",
"Por prender você mesmo os contrabandistas, você receberá ",
" por cento do valor da carga. Isso equivale a ",
" ouro.",
"um pagamento básico de ",
" ouro, pois a carga não valia muito.",
"Você está pronto para substituir o #samount# #scargo# que foi fornecido para sua missão de contrabando?",
"Sim, estou com sua carga.",
"Não, ainda não consegui substituí-lo.",
"Isso é bom. A carga agora será descarregada do seu navio. ",
" Agora, saia da minha frente!",
"Você tem o #smoney# que deve da sua missão de contrabando?",
"Sim, tenho o suficiente para retribuir.",
"Não, ainda não tenho o suficiente para retribuir.",
"Muito bem. Então não haverá mais punição, mas isso ficará em seu registro.",
" Agora saia!",
"Então vá embora e não volte até receber o que me deve. Lembre-se que minha paciência é limitada!",
"Adeus, #saddr#.",
" Além disso, ",
"Tenho uma missão especial para alguém com seus talentos particulares.",
"Uma missão especial? Isso parece intrigante.",
"Você deve investigar o '",
", a ",
" no porto de ",
"sobre ",
".",
"Você quer que eu sabote o '",
"?",
"Não. Este navio em si tem pouca importância, mas acreditamos que ele se juntará a uma força maior em outro lugar. Sua missão é encontrar essa força maior e depois reportar aqui.\nTambém seria útil se você pudesse descobrir os planos do inimigo para essa força maior.",
"Eu entendo. Eu navegarei para ",
" assim que eu puder. Adeus, Excelência.",
"Isso parece um pouco complicado para mim, Excelência. Talvez quando eu tiver mais experiência me sentirei digno de tal missão. Até então, adeus.",
"Ah, você voltou. Você completou sua missão?",
"Sim, Excelência. Consegui embarcar no '",
", que partiu de ",
" para ",
". Lá consegui invadir a prefeitura, onde descobri os planos do inimigo. Aqui está uma cópia que fiz. Deixei o original onde estava para que o inimigo não saiba que o encontrei.",
"Muito esperto! Você tem feito um excelente trabalho. ",
"Agora que sabemos o que é ",
" frota pretende fazer, podemos enviar nossos próprios navios para preparar uma surpresa para eles. Aqui ésta o seu pagamento.",
"Como você deve saber, enquanto esteve fora ",
" e ",
" assinaram um tratado de paz. Mas os planos que você trouxe mostram que ",
" provavelmente pretende quebrar o tratado. Quando o fizerem, estaremos prontos para eles. Aqui ésta o seu pagamento.",
"Há mais uma coisa, Excelência. Tive que alugar um navio para me trazer de volta aqui. Eu não tinha dinheiro suficiente para pagar ao capitão, então prometi o dobro da tarifa quando chegasse aqui. Posso reivindicar a tarifa como despesa?",
"Quanta despesa você quer dizer?",
"Eu devo ",
" ouro, Excelência.",
"Você já foi pago ",
", e agora você quer mais! Mas não sou irracional. Você não deve ficar sem dinheiro depois de tal serviço.\nMuito bem, você pode ter um extra ",
". Isso, mais o que você já recebeu, cobrirá sua dívida e ainda lhe deixará uma recompensa.",
"Obrigado, Excelência.",
"Bem? O que você tem a relatar sobre sua missão?",
"Excelência, lamento informar que não consegui encontrar o ",
".",
"Pode ser do seu interesse saber que, embora você não conseguisse encontrar o ",
", ela estava saqueando outro de nossos navios. Ela agora escapou. Esta falha será anotada em seu registro.",
};
