string DLG_TEXT[31] = {
"Desculpe. Eu tenho que ir.",
"...",
"Eu imploro a você, ",
"! Por favor me ajude!",
"O que está acontecendo aqui?",
"Eles querem matar o velho!",
"Então, onde estão os soldados? É trabalho deles manter a ordem nesta cidade, não meu.",
"Os soldados têm que morar aqui - você não! E você parece um sujeito decente - por favor, salve aquele pobre velho? Esses bárbaros vão queimá-lo!",
"Por que? O que ele fez?",
"Você vai ficar aqui me questionando enquanto eles o matam?",
"A multidão está apenas preparando o fogo. Você não tem muito tempo para responder às minhas perguntas.",
"Como você pode estar tão calmo?!",
"Chame isso de requisito de trabalho. Agora estão amarrando o velho na estaca. Você pode querer falar antes que seja tarde demais.",
"Tudo bem! Ele é acusado de feitiçaria - mas acredite, ele é apenas um homem normal. Ele mora sozinho no farol e nunca incomoda ninguém!",
"Então, por que a multidão está tão interessada em assá-lo? E por que você é a única pessoa que quer salvá-lo?",
"Ele é um maluco inofensivo. Ele sempre tem alguma invenção nova, e a maioria não funciona da maneira que deveria - então irrita muitas pessoas.",
"Sim - eles parecem bastante irritados.",
"Bem, algo explodiu em seu farol esta manhã, e o vento carregou uma nuvem fedorenta sobre toda a cidade.",
"Deve ter havido alguma nuvem, para justificar queimá-lo na fogueira. Mas, novamente - por que só você quer salvá-lo?",
"Certa vez, minha filha adoeceu mortalmente e ninguém pôde ajudá-la. Mas ",
"researcher", // não traduzir
" encontrou uma cura para ela em um antigo manuscrito indiano!",
"Bem, parece que vale a pena salvá-lo. Farei o que puder. Como você disse que era o nome dele? ",
"researcher", // não traduzir
"?",
"Essa é uma história muito comovente. Mas não tenho certeza se é tocante o suficiente para me levar contra uma multidão assassina.",
"Ah, Deus te abençoe! Você está fazendo uma coisa muito boa!",
"Farei o meu melhor.",
"Você não tem coração, #ssir#?! Você não é melhor do que aqueles assassinos que acendem o fogo!",
"Sem coração?! Eu tenho um coração de baleia! Se eu tiver que provar isso para você, eu o farei!",
"Posso ser cruel, mas não posso ficar parado e ver isso acontecer. Eu ajudarei o velho se puder",

};
