string DLG_TEXT[68] = {
"Que negócio traz você aqui?",
"Governador ",
"Robert Christopher Silehard",
"Robert Christopher Silehard",
" confiou-me a entrega desta carta a você e a custódia de um prisioneiro.",
"Governador ",
"Robert Christopher Silehard",
" me enviou para recuperar o ídolo sagrado inca para ele.",
"Trago ordens para libertar um dos seus prisioneiros.",
"Preciso falar com um prisioneiro.",
"Vá em frente, então. Fale com ele.",
"Bom.",
"Estou só de passagem.",
"Bem, geralmente não permitimos visitantes...",
"Mas este é um negócio vital do Estado!",
"Que negócio? O que você está falando?",
"Você deve ter ouvido falar sobre os sequestros de crianças e outras coisas estranhas que acontecem em todo o arquipélago. Bem, acredito que seu prisioneiro pode me ajudar a descobrir tudo isso!",
"Por favor - preciso falar com esse homem!",
"Tudo bem. Não vai doer para você falar com ele, suponho. Nós o enforcamos à tarde de qualquer maneira.",
"Bom. Obrigado.",
"Você está desperdiçando seu tempo. Embora... se você pudesse me fazer um favor...",
"Que favor?",
"Meu filho vai se casar em breve. Eu gostaria que ele tivesse um casamento adequado. Então, se você quiser falar com o prisioneiro, isso lhe custará 5.000 ouro.",
"Aqui está o seu dinheiro.",
"Eu não acho que isso vai acontecer. Posso oferecer outra solução?",
"Você me cansa. Por favor saia. Você não vai falar com ninguém!",
"Sinto muito que tenha chegado a esse ponto, mas temo que você não me deixe escolha...",
"Tudo bem. Mas eu voltarei.",
"O que...",
"Você vai me escoltar até o prisioneiro agora, ou eu vou passar por você!",
"Você vai pagar por isso!",
"Provavelmente, mas não hoje. Hoje você é meu prisioneiro, e eu quero falar com o seu.",
"Tudo bem! Você pode falar com ele.",
"...",
"Deixe-me ver isso. Hmm... o próprio Professor, não é? Tudo bem, você pode levá-lo.",
"Bom.",
"Tudo bem. Mas deixe-me ver os pedidos primeiro.",
"Você está falando sério? Você sabe que trabalho diretamente para o governador e você me pede para lhe mostrar um pedaço de papel?!",
"Sinto muito, mas tenho minhas próprias ordens. Devo enviar o ídolo através de um navio de guerra para #sRedmond#, e devo prender qualquer um que tente levá-lo sem os documentos adequados. Guardas!",
"Maldição!",
"Receio não poder lhe entregar o prisioneiro neste momento.",
"O que você quer dizer com não pode dá-lo para mim?",
"Diga ao governador que o prisioneiro... escapou ontem à noite e ainda não conseguimos encontrá-lo.",
"Ah, você pode ter certeza que vou contar a ele. E se eu fosse você, encontraria aquele canalha!",
"Você pode ter vencido esta batalha em particular. Mas você não terá que esperar muito",
"é vingança.",
"Enquanto isso, vou reivindicar esta cidade para mim.",
"O que você quer?",
"Preciso levar o prisioneiro, Thomas Wolfe.",
"Aqui, você precisará assinar este documento de liberação.",
"...",
"Isso parece estar em ordem. Você pode levar Wolfe.",
"Obrigado.",
"Algum tipo de nativo matou um dos meus tripulantes sem provocação! Você pode fazer alguma coisa sobre isso?",
"Sinto muito, capitão. Notamos a presença deles aqui, mas não os pegamos fazendo nada de errado. Sem provas sólidas, não podemos prendê-los. Se você souber de mais alguma coisa, por favor, informe-me.",
"Parece que eu esperava muito dos militares mais uma vez...",
"Algum tipo de nativo tentou matar um dos meus tripulantes sem provocação! Você não pode fazer nada sobre isso?",
"Já vi um desses nativos entrar no armazém perto do forte. Parece que eles não estão tramando nada de bom.",
"Obrigado por relatar isso. Agora que sabemos onde eles estão localizados, ficaremos de olho neles para garantir que não se tornem perigosos para as pessoas.",
"Prazer em ajudar.",
"Ouvi alguns desses nativos falando sobre o comércio ilegal que realizam aqui. Você não deveria fazer algo sobre isso?",
"Você tem mais alguma prova disso além da sua palavra?",
"Não, desculpe, não tenho. Mas sei que eles estão trabalhando no armazém perto do forte. E parece que esta noite eles vão fazer uma negociação na praia.",
"Isso não será suficiente para prendê-los instantaneamente. Mas vamos ficar de olho neles. Obrigado pela informação.",
"Encontrei alguns dos bens que eles estavam escondendo.",
"Obrigado por relatar isso. As poções são realmente ilegais. Nós os tiraremos de vocês agora e prenderemos esses índios o mais rápido possível. Obrigado por relatar isso.",
"Espere! Voltarei com informações",
};
