string DLG_TEXT[178] = {
", ",
". Meu nome é ",
". E qual é o seu nome?",
"Olá, ",
"! Eu sou ",
". Posso saber o seu nome?",
"Sim Sim, ",
". O que você quer? Meu nome é ",
".",
"Eu sou ",
", capitão do '",
".",
"Meu nome é ",
".",
"Você pode me chamar de capitão ",
".",
"Olá novamente, capitão ",
".",
"É você de novo ",
"! É sempre bom ver você.",
"Que prazer conhecer o Capitão ",
" #shimself#!",
"Dou-lhe as boas-vindas novamente, capitão ",
".",
"Ah, é você ",
". Tenho o prazer de conversar com você novamente.",
"É uma honra conhecer o Capitão ",
" #shimself#!",
"Então, qual é a conversa na cidade?",
"Estou interessado nas notícias locais.",
"Do que as pessoas estão falando aqui hoje em dia?",
"Você poderia me dar algumas instruções?",
"Estou confuso com estas ruas...",
"Eu gostaria de chegar...",
"Eu gostaria de algumas informações sobre alguém.",
"Gostaria da sua opinião sobre uma pessoa que você talvez conheça.",
"Você poderia compartilhar algumas informações sobre os habitantes locais comigo?",
"Conte-me sobre esta colônia.",
"O que você sabe sobre #sGreenford#?",
"Espero que você possa me contar algo sobre #sGreenford#.",
"Obrigado. Até a próxima!",
"Você quer algo de mim, capitão?",
"Prazer em conhecê-lo, ",
".",
"É um prazer conhecê-lo também, capitão ",
". Como posso ajudá-lo?",
"Qual é a conversa na taverna hoje em dia?",
"Você pode compartilhar alguma notícia local comigo?",
"Estou procurando me atualizar sobre os últimos rumores.",
"Você poderia me dar algumas instruções?",
"Eu gostaria de chegar a algum lugar...",
"Eu preciso de ajuda. Não conheço muito bem a cidade.",
"Preciso saber sobre um certo cavalheiro.",
"Gostaria de saber sua opinião sobre alguém aqui da cidade.",
"Você poderia me dar algumas informações sobre os habitantes locais?",
"Conte-me sobre sua colônia.",
"O que você sabe sobre #sGreenford#?",
"Gostaria de saber qualquer coisa que você possa me dizer sobre #sGreenford#.",
"Só estou tomando um pouco de ar fresco. Talvez possamos conversar mais tarde.",
"Eu vejo. Tem mais uma coisa.",
"Obrigado pela informação. Até a próxima.",
"Eu ficaria feliz em conversar com você novamente ",
". Diga-me o que você está pensando",
"Sim, ",
"?",
"Estou ouvindo. O que você quer?",
"Do que falam os frequentadores da taberna?",
"Preciso ficar por dentro das últimas notícias.",
"É sempre útil acompanhar os rumores locais. Ouvi alguma coisa boa ultimamente?",
"Já faz um tempo que não estou em terra firme e parece que estou um pouco perdido...",
"Você poderia me dizer como chegar a algum lugar?",
"Eu poderia usar algumas instruções.",
"Eu gostaria de ouvir o que você sabe sobre um cidadão local. ",
"Você poderia me dar sua opinião sobre um certo cavalheiro?",
"O que você pode me dizer sobre os habitantes locais?",
"Conte-me sobre sua colônia.",
"O que você sabe sobre #sGreenford#?",
"Gostaria de saber algo sobre #sGreenford#.",
"Deixa para lá. Estou apenas dando um passeio. Até a próxima.",
"Quem exatamente você quer dizer ",
"?",
"A quem você quer dizer, capitão?",
"Certamente, ",
". Diga-me qual dos cidadãos de #sGreenford# atraiu sua atenção e tentarei ajudar.",
"Estou falando do governador da colônia.",
"Estou interessado no taverneiro, ",
"Simon Hanpool",
"Simon Hanpool",
".",
"O proprietário do estaleiro, ",
"David Fairweather",
"David Fairweather",
".",
"Estou perguntando sobre o comerciante chamado ",
"João Filberto",
"João Filberto",
".",
"Deixa para lá. Desculpe por ter incomodado você. ",
"Não temos nosso próprio governador, porque estamos sob a jurisdição do governador de #sRedmond#. Ele raramente vem aqui, então não sei muito sobre ele. Suas leis são duras, mas não posso dizer que sejam injustas. Porém, nosso forte precisa de reparos e, em vez de consertar, ele gasta dinheiro em várias expedições.",
"Eu vejo. Deixe-me fazer outra pergunta.",
"Obrigado. Adeus.",
"Ele é muito interessante. Às vezes penso que ele seria melhor empregado como espião. É simplesmente fascinante o quanto ele sabe.",
"Eu vejo. Deixe-me fazer outra pergunta.",
"Obrigado. Adeus.",
"Ele é muito bem educado. Dizem que ele estudou na Inglaterra e na Holanda. Mas então, de alguma forma, ele teve alguns problemas com as autoridades e veio para cá.",
"Eu vejo. Deixe-me fazer outra pergunta.",
"Obrigado. Adeus.",
"Não posso dizer nada de ruim sobre ele. Ele é muito honesto. Ele é humilde e compassivo, e não ouvi uma palavra ruim sobre ele de ninguém.",
"Eu vejo. Deixe-me fazer outra pergunta.",
"Obrigado. Adeus.",
"Para onde você está indo ",
"?",
"Estou impressionado - é muito difícil se perder em nossa cidade. Então, para onde você quer ir?",
"Ficarei feliz em ajudá-lo ",
".",
"Diga-me onde você precisa estar ",
".",
"Estou impressionado - é muito difícil se perder em nossa cidade. Então, para onde você quer ir?",
"Ficarei feliz em ajudá-lo ",
".",
"Como posso chegar à taberna?",
"Onde fica o estaleiro?",
"Onde posso vender os produtos que trouxe comigo?",
"Se você vem do porto, basta virar à direita na entrada da cidade e verá a taberna. Tem um grande sinal.",
"Eu vejo. Obrigado. Adeus.",
"E onde fica o estaleiro?",
"Onde posso descarregar parte da carga que tenho no porão por um preço decente?",
"O escritório do gerente do estaleiro fica no final da rua lateral que segue à esquerda do portão do porto.",
"Entendi. E como posso chegar à taberna?",
"Onde posso vender alguns dos meus produtos?",
"Obrigado pela ajuda. Isso é tudo que preciso por agora.",
"Se você for direto do porto pela entrada da cidade, chegará à loja.",
"Onde fica o estaleiro da cidade?",
"Como posso chegar à taberna?",
"Eu vejo. Obrigado pelo seu tempo.",
"Essa é uma questão geral. O que você quer saber?",
"O que exatamente você quer saber?",
"O que você quer saber, ",
"?",
"Gostaria de saber a história da colônia.",
"Existe alguma coisa nesta ilha fora da cidade?",
"Você sabe alguma coisa sobre o forte que protege a cidade?",
"Deixe-me perguntar outra coisa.",
"Fico feliz em saber que você está interessado nisso, capitão. Poucas pessoas se preocupam com o passado nesta era moderna. A colônia foi fundada há cerca de 40 anos.\nA ilha não é grande, mas seu solo é bastante fértil e há algumas baías muito aconchegantes. Novas áreas se desenvolveram gradativamente, assim como a própria cidade.",
"Prossiga.",
"Eu vejo. Tenho outra pergunta, se estiver tudo bem.",
"À medida que a colônia cresceu, tornou-se um alvo maior para os piratas - então o forte foi construído para proteger a cidade. Desde então, tornou-se mais pacífico aqui.",
"Eu vejo. Deixe-me perguntar-lhe outra coisa, se me permite.",
"A maior parte da ilha está desenvolvida agora e apoia muito bem os cidadãos. Mas qualquer desenvolvimento futuro será difícil, graças à densa selva.",
"Por favor me conte mais.",
"Não há nada realmente especial nesta ilha em particular. Eles são todos bastante semelhantes no arquipélago.",
"Eu vejo. Continue.",
"Não há nada de interessante para contar. Apenas selva, pedras e praias desertas. A terra é muito fértil e traz colheitas ricas, então é claro que existem fazendas e pastagens.",
"Prossiga.",
"Eu vejo. Deixe-me perguntar-lhe outra coisa, se me permite.",
"Eu não estou realmente interessado nisso.",
"Isso é ruim. Bem, me diga outra coisa.",
"Aqueles que construíram o forte fizeram muito bem o seu trabalho. Não é grande, mas é bastante avançado em seu design. E é o lar de 800 soldados em tempo integral.",
"Eu vejo. Continuar...",
"O comandante da guarnição poderia mandar me decapitar por lhe contar sobre o forte. Desculpe, capitão, mas talvez seja melhor falarmos de outra coisa.",
"Tudo bem. ",
"Eu vejo. Deixe-me fazer outra pergunta.",
"É um holandês morando aqui que eu gostaria de encontrar. Yedam Kinne.",
"Ah, Kinne, sim. Um homem útil para se conhecer, por muitas razões que eu... ahh... provavelmente não deveria mencionar. Mora atrás da taberna.",
"Obrigado. Adeus.",
" Temos uma população de ",
" cidadãos.",
"Quando os primeiros colonos ingleses desembarcaram nesta ilha descobriram que ela era desabitada. Depois de fazerem alguma exploração do terreno descobriram vestígios de que alguns nativos habitavam de facto o local onde actualmente se encontra #sGreenford#.",
"Essas pessoas, Arawaks, abandonaram a ilha, mas deixaram uma ponte primitiva - assim, embora esta construção não seja vista aqui, a cidade foi portanto chamada de '#sGreenford#'.",
"Em 1536, o explorador português Pedro a Campos desembarcou em #sisland_Oxbay# quando navegava para o Brasil. Ele chamou a ilha de 'Los Barbados', que significa 'os barbudos', depois de ver figueiras locais, que têm longas raízes aéreas que lembram uma barba\n#sisland_Oxbay# foi reivindicada para a Inglaterra pelo capitão John Powell em 1625, e pelos primeiros colonos foi trazido aqui por seu irmão, o capitão Henry Powell. Depois da chegada de mais colonos, no final de 1628, cerca de 2.000 pessoas viviam aqui\nDesde o início, os colonos plantaram aqui tabaco, que hoje é um dos principais produtos de exportação da ilha.",
"Por acaso você viu um religioso passando por aqui recentemente?",
"Agora você mencionou isso, de fato eu mencionei. Mas já faz um bom tempo. Acredito que ele foi à velha igreja nos fundos da cidade. Não acredito que ele tenha sido visto desde então. Talvez as histórias sobre aquele lugar ser assombrado sejam realmente verdadeiras...",
"Obrigado pela informação.",
"Ouvi dizer que você tem um boticário na cidade. Você sabe alguma coisa sobre ele?",
"Na verdade, nós temos. A loja dele não fica longe da igreja, fica no último andar da casa com a escada do lado de fora.",
"Obrigado! Ele certamente parece valer a pena visitá-lo.",
"O que mais você pode me dizer sobre ele?",
"Bem, ele é um grande naturalista e coleciona espécimes de aves selvagens.\nE às vezes precisa de ajuda para encontrar ingredientes para seus remédios.",
};
