string DLG_TEXT[201] = {
"Disseram-me que você fez um grande esforço para solicitar uma audiência. Meu nome é ",
". Agora, por favor, diga-me o propósito da sua visita ",
".",
"Meu nome é ",
".",
"Ah, é você de novo. O que traz você aqui desta vez? ",
"Eu gostaria de conversar com você sobre alguns negócios.",
"Sinto muito, mas há coisas que preciso fazer.",
"Então, por que você me distrai dos assuntos de estado muito importantes?",
"Gostaria de falar com você sobre um pequeno negócio.",
"Estou aqui apenas para prestar meus respeitos, #saddr#. Nada mais.",
"Nesse caso, por favor, saia do meu escritório e deixe-me voltar para assuntos mais importantes.",
"Sim claro. Desculpe por ter incomodado você.",
"Sinto muito, mas não tenho nada para conversar agora",
"Oh sim? Tenho uma proposta para você, capitão.",
"De fato?",
"Vi que você concluiu a tarefa com sucesso; meus parabéns, capitão! Aqui está sua recompensa.",
"Meus agradecimentos; Foi um prazer ajudá-lo.",
"Você deve destruir o ",
" navio ",
"missão pirata",
" ameaçando o envio ",
". Se você afundá-la, vou recompensá-lo com uma boa quantia de ",
" ouro. O que você diz, capitão?",
"Você não ouvirá falar dela novamente, isso eu prometo.",
"Receio não poder ajudá-lo.",
"Anseio por perdão, Excelência.",
"Estou interessado em aprender sobre as relações de #sgov_nation# com outras nações.",
"Estou procurando uma Carta de Marca.",
"Ouvi dizer que estou pronto para uma promoção.",
"Não posso mais servir ",
", vossa Excelência.",
"Cansei de servir ",
"Como garantia de que você é um capitão competente e para recompensar meu tempo apresentando seu caso a ",
", devo te pedir ",
" ouro.",
"Sem chance.",
"Muito bem.",
"#sgov_nation# tem sempre o prazer de aceitar novos capitães ao seu serviço. ",
"Estamos atualmente em guerra com ",
"",
"nenhum grande poder, mas ",
". Claro, ",
"Os piratas devem sempre ser afundados à primeira vista.",
" À luz do seu serviço anterior ",
" concede a você a classificação de ",
"Vou deixá-lo orgulhoso, Excelência.",
"Você prejudicou ",
", e ",
" não esquece seus inimigos. Saia imediatamente, ou os guardas vão te jogar fora!",
"...",
"Você causou ",
" grande dano, capitão, mas ",
" está disposto a ignorar suas transgressões passadas... por um preço: ",
"Muito bem, senhor. Aceito.",
"É um prazer lidar com você, ",
"E você, Excelência.",
"Você é realmente! Excelente trabalho. Sua nova classificação é ",
". Além disso, você é premiado ",
" hectares de terra por ordem de ",
"Obrigado, senhor.",
"Tem certeza, ",
" lamentaremos perder seu serviço.",
"Sim eu sou.",
" não gosta de vira-casacas ",
"Uh, não importa.",
"Muito bem. Mas espero que você reconsidere, com o tempo...",
"Adeus, ",
"Huh?",
"Difícil.",
"Bem vindo a #sCartagena#, #ssir#. Sou Don Gregorio Montavez, o governador desta cidade. É um prazer ver aqui um alto representante da nobreza. Você teve uma boa viagem?",
"Sim, obrigado. Como você sabe, sou Don Guillermo de la Rosa, Enviado de nosso Rei.",
"Eu sabia. Sua chegada era esperada...",
"Disseram-me que #sCartagena# era a cidade mais bonita do Caribe e é verdade. Só o porto já impressiona com este grande forte guardando a entrada.",
"É San Felipe, Excelência. Pode resistir ao ataque de qualquer navio de guerra.",
"Eu acredito. Espero visitá-lo.",
"Claro, amanhã te mostrarei o forte de San Felipe se você aceitar.",
"Excelente, de qualquer forma, verificar as defesas do #sCartagena# é um dos objetivos da minha visita. Por favor, leia esta carta escrita pelo nosso Rei para entender melhor o propósito da minha vinda.",
"Entendo... Devo lhe dar todos os detalhes da situação de #sCartagena#: forças e fraquezas e qual é a minha estratégia para desenvolver a cidade. É um longo relatório que você deve preparar.",
"Não se preocupe; Terei o tempo necessário para este trabalho. Devo ficar aqui por duas semanas antes de visitar as outras colônias espanholas do Caribe.",
"Muito bem, mas primeiro deixe-me preparar uma festa. Esta noite você será o convidado de honra de #sCartagena#. Para o jantar, toda a aristocracia da minha cidade estará com você. E não esqueci que você terá um quarto na minha residência, mais confortável que uma cabine de navio para sua estadia.",
"Obrigado por esse convite, Governador.",
"Você me seguirá para que eu possa lhe mostrar um pouco da cidade?",
"Eu gostaria, mas não posso agora. Devo falar com o Capitão do meu navio para lhe dar algumas instruções para a estadia.",
"Eu entendo. Não chegue muito tarde à minha residência esta noite.",
"Claro, não quero perder minha própria festa, ha ha!",
"Dom Guilherme, entre! Deixe-me apresentar algumas pessoas boas de #sCartagena#.",
"Claro, Governador.",
"Como eu disse, deixe-me apresentar algumas pessoas da minha cidade. O primeiro é o almirante da minha cidade, Lorenzo Delgado.",
"Espero que gostem desta festa.",
"Obviamente, Excelência. No entanto, eu não gostaria de descansar muito tarde esta noite.",
"Isso é compreensível. Assim que você estiver cansado, fale com meu manobrista, ele lhe mostrará seu quarto.",
"Muito obrigado.",
"Dom Guillermo de la Rosa! Você descansou o suficiente ontem à noite?",
"Sim, governador. O quarto da residência é muito melhor que a cabine de um navio para dormir.",
"Ha! ah! Eu previ isso. Então você está pronto para visitar #sCartagena#?",
"Absolutamente. Estou acima de tudo impaciente para visitar o forte de San Felipe.",
"O forte mais forte do Caribe como você conhece. Comecemos pelo forte se quiser, Dom Guillermo...",
"Como você pode ver, a fortaleza está localizada em uma localização estratégica, dominando os acessos à cidade por terra ou mar.",
"Na verdade, a localização não poderia ser melhor.",
"Embora a fortaleza seja antiga visto que a construção começou no ano de 1536, há alguns anos, foi ampliada.",
"Você poderia me explicar sua arquitetura?",
"Naturalmente, a fortificação consiste numa série de paredes, largas na base e estreitas em direcção ao parapeito, formando um formidável padrão de bunkers. As baterias e os parapeitos protegem-se mutuamente, tornando praticamente impossível levar uma bateria sem levar todo o sistema de defesa. Os canhões do castelo comandam toda a baía, para que qualquer embarcação suspeita que tente atracar possa ser atacada.",
"Impressionante...",
"A fortaleza chama a atenção por sua entrada grandiosa e seu complexo labirinto de túneis. Em suma, é o mais formidável complexo defensivo dos militares espanhóis no Caribe.",
"O que você quer dizer com o termo labirinto complexo de túneis? Existe alguma diferença com as outras fortificações espanholas?",
"O número de túneis é maior do que qualquer outro forte espanhol no Caribe. Isto permite aos soldados moverem-se rapidamente de um ponto a outro e isto é uma vantagem se o forte estiver sob ataque.",
"Certamente...",
"Mas os túneis não se limitam à fortaleza.",
"Eu não entendo, Governador.",
"Existe até um túnel que liga o forte à cidade. Assim, a fortaleza pode receber as guarnições da cidade caso seja atacada.",
"Isto aumenta drasticamente o número de soldados que podem defender a fortaleza...",
"Sim. É por isso que considero San Felipe inexpugnável.",
"Humm... Só por curiosidade onde fica a saída do túnel na cidade?",
"Não se preocupe, está no Gabinete do Almirante. O local mais protegido da cidade HAHA!",
"Tudo parece estar bem pensado. Nosso Rei ficará feliz em saber como a cidade está bem protegida.",
"Obrigado, Dom Guilherme. Mas siga-me, ainda há algo que quero lhe mostrar.",
"Aqui estamos, no topo do forte.",
"A vista é fantástica sobre a baía.",
"De fato. Mas siga-me até esta cabana bem na sua frente. Acho que você gostaria de outra visão.",
"Olha essa reserva de pólvora.",
"Que quantidade impressionante de barris você tem!",
"Barris de pólvora e balas de canhão. Poderíamos lutar contra uma armada de navios, se necessário.",
"Certamente, Governador. Já achava que San Felipe era um forte impressionante, mas agora noto que suas defesas e sua organização são as melhores que já vi. Minha visita a #sCartagena# ainda não terminou, mas devo dizer que minhas primeiras impressões são muito boas.",
"Obrigado por estas palavras encorajadoras, Don Guillermo. Mas vejo que já é meio dia, talvez você queira almoçar comigo em minha residência antes de continuar sua visita.",
"Obrigado Governador pelo convite mas desde ontem à tarde não vi minha tripulação e preciso falar com eles para saber se está tudo bem no meu navio. Então, almoçarei com eles no navio.",
"Como quiser, esperarei por você esta tarde em minha residência para que possamos continuar a visita.",
"Estarei lá às 2 horas.",
"Ah! Dom Guilherme,",
"Governador, acabei de falar com sua filha na frente de sua residência e ela me disse que você tem um problema com os holandeses.",
"Infelizmente sim. Um de seus navios de guerra atacou muitos navios mercantes espanhóis nos últimos meses na rota entre #sCartagena# e #sisland_Isla Muelle#. Por um de nossos espiões, soube há uma hora que um navio de guerra atraca em #sWillemstad# e fica lá mais uma semana para ser reparado e abastecido. Decidi atacá-la com minha própria frota nos próximos dias.",
"Então não posso continuar a visita à cidade com vocês esta tarde?",
"É verdade, Dom Guillermo. Preciso de muitos dias para terminar esta operação e levantarei âncora hoje. Você quer me acompanhar durante a missão.",
"Humm... prefiro continuar meu dever aqui, Governador. Também tenho uma missão a cumprir e tenho certeza que poderia preparar meu relatório conversando com seus subordinados.",
"Claro, Dom Guillermo. O pessoal de #sCartagena# lhe dará toda a ajuda necessária durante minha ausência.",
"Obrigado, Governador. Chegou a hora de deixar você em paz. Você deve preparar sua licença e não quero mais atrasar isso.",
"Não se preocupe, daqui a alguns dias estarei de volta trazendo boas notícias.",
"O nosso rei apreciará a sua lealdade à Espanha. Tenha uma boa jornada.",
"Dom Guilherme! Eu estava prestes a enviar um homem para o seu navio. Eu estava com pressa de falar com você",
"É sobre a missão? Você conseguiu?",
"Bem... Na verdade não, infelizmente. Os holandeses repeliram o nosso ataque. Tive a sensação de que eles estavam esperando por nós.",
"Como isso é possível?",
"Não sei. #sWillemstad# estava preparado para o ataque e não nos beneficiámos do efeito surpresa. De qualquer forma, encontrarei outra maneira de afundar a frota deles. Mas, não era sobre a missão que eu queria ver você.",
"Não?",
"Soube que você lutou com Don Sebastian Ortega.",
"Foi apenas um desentendimento.",
"Você chama o desentendimento de duelo?! Don Sebastian é uma das pessoas mais importantes da minha cidade. É a sua maneira de agradecer minha hospitalidade?",
"Sinto muito, Governador. Isso não vai acontecer mais.",
"Espero que sim, porque caso contrário eu deveria denunciar seu comportamento ao nosso Rei. Não tenho certeza, ele aprecia. De qualquer forma, há outro problema. Eu sabia o motivo desse duelo. Parece que você quer cortejar minha filha.",
"Temos muitas afinidades...",
"E não posso aceitar esta situação. Prometi a mão da filha aos pais do Ortega. Quero reunir nossas famílias com o casamento.",
"Governador, sua filha não ama Don Sebastian Ortega.",
"Não é problema seu, Don Guillermo. Isso é algo que devo resolver entre mim e minha filha. Com o tempo, ela mudará de ideia sobre Don Sebastian.",
"Mas...",
"Pare, Dom Guilherme. Nossa discussão sobre minha filha acabou. Até sua saída, minha filha ficará no claustro de #sCartagena# e você está proibido de vê-la novamente. Estamos de acordo?",
"[PENSA: Vá em frente!] Como desejar, Governador.",
"Excelente, eu sabia que você era um #sgender# razoável. Caso contrário, você ainda precisa da minha ajuda para finalizar seu relatório?",
"Só preciso ver o seu almirante.",
"Ah! Ele já deve estar em seu escritório a esta hora. A tarefa foi difícil para ele durante a missão, mas ele é um homem corajoso e não desiste mesmo depois de um fracasso.",
"Bom de se ouvir. Estou indo para o escritório dele agora. Tenha um bom dia, Governador.",
"Dom Guilherme! Como vai?",
"Estou bem, Governador Montavez. Apenas dois dias antes da minha partida",
"Há um fim para tudo.",
"De fato. Isso é estranho...",
"O que é estranho?",
"Há uma hora, eu estava conversando com um guarda e soube que um pirata foi preso no Claustro. Pirata, Claustro... Qual é o link?",
"Eu confirmo e sabemos o nome dele. Esse é Johan Elting, um traidor. Ele foi reconhecido por um dos meus capitães que liderava uma patrulha noturna. Este capitão trabalhou muitos anos em Havana antes de ser transferido para cá.",
"Um traidor??",
"Sim, ele trabalhou para a Espanha. Na verdade, para o ex-vice-almirante de #sHavana# antes de traí-lo e matá-lo.",
"Isso é horrível! Não podemos confiar em nenhum holandês.",
"Você tem razão. Infelizmente, o Vice-Almirante cometeu este erro. Mas, comigo, ele não terá nenhuma chance. Ele será enforcado em breve.",
"Bom. Ele deve estar trancado na prisão.",
"Não.",
"Não??",
"Ele está trancado, é claro, mas em um lugar secreto. Eu queria ter certeza de que nenhum membro da tripulação ou amigo dele tentaria libertá-lo antes de sua morte.",
"Boa iniciativa. Eu não sabia que você tinha outra prisão na cidade...",
"É uma caverna secreta sob a Igreja. Ninguém poderia pensar em um local assim HAHA!!",
"HAHA! Que engenhosidade! Reconheço o espírito espanhol! Então ele vai ser enforcado hoje?",
"Não amanhã. Quero saber por que ele estava no claustro. Acho que ele estava tentando sequestrar minha filha para um resgate futuro, mas não tenho certeza. É por isso que ele será torturado para obter uma confissão.",
"[PENSA: Tortura!?] Poderia ser inútil, um pirata como ele deve ter muita vontade. Ele poderia resistir a qualquer tipo de tortura.",
"Veremos. Mas não perca muito tempo falando sobre a vida de pirata. Caso contrário, você ainda precisa da minha ajuda antes de partir?",
"Não particularmente. Ordenei à minha tripulação que preparasse a licença comprando os suprimentos necessários e amanhã à tarde esta tarefa estará cumprida.",
"E qual será sua próxima missão?",
"Devo visitar #sHavana# e Santiago de Cuba como fiz aqui antes de retornar à Espanha.",
"Bom. Você poderia me apresentar antes de partir as conclusões de seu relatório sobre #sCartagena#, Don Guillermo?",
"Eu farei. Vejo você novamente amanhã à tarde para o relatório. Tenha um bom dia, Governador.",
"Boa tarde, Dom Guilherme.",
"Boa tarde, Excelência. Quando eu estava atravessando a cidade notei que havia mais soldados patrulhando.",
"Na verdade, uma ordem minha. Ontem à noite, o holandês Elting foi libertado. Estamos tentando encontrá-lo.",
"Inacreditável, como isso foi possível?",
"Alguém o ajudou... O mais curioso é que não entendo como ele sabia que Elting estava escondido na Igreja.",
"Talvez alguns de seus homens estivessem espionando na cidade e tenham visto seus soldados levando-o para a Igreja.",
"Você deve estar certo. Eu disse a eles para levarem Elting discretamente, mas parece que ainda há algumas pessoas incompetentes na minha guarda. Eu lidarei com eles mais tarde.",
"Bem, caso contrário, acho que você pediu para apresentar meu relatório hoje.",
"Você tem razão. Você pode começar seu discurso.",
"Obrigado, Dom Guilherme. Pelo que você disse, parece que você gostou de como a cidade é administrada e protegida.",
"Exatamente. Nosso rei ficará satisfeito com meu relatório sobre #sCartagena#. Espero ver o mesmo nível de exigência em Cuba.",
"Eu penso que sim. Conheço os governadores de #sSantiago# e #sHavana# e eles não poupam esforços para proteger suas cidades",
"Isso é perfeito, Excelência. É hora de voltar ao meu navio e confirmar que todos os preparativos para minha viagem a Cuba estão prontos.",
"É claro é claro. Faça isso, amanhã de manhã estarei no porto para me despedir.",
"Obrigado vejo você amanhã.",
};
