string DLG_TEXT[37] = {
"Ola, capitao, prazer em conhece-lo. Sou o ferreiro local.",
"Ferreiro, hein? Entao, o que exatamente voce faz? Pode consertar alguma coisa para mim?",
"Ah, sim, claro que posso. ",
"! Posso consertar qualquer espada ou arma que voce me trouxer. Basta equipar os itens que precisam de conserto e eu conserto para voce. O preco varia para cada tipo de espada ou arma e nivel de dano, mas posso consertar tudo em um dia.",
"Otimo, vamos ao que interessa!",
"Obrigado, vou me lembrar disso! Adeus.",
"Entao, o que voce quer consertar?",
"Acho que minha lamina precisa de um conserto.",
"Esta arma lhe parece boa? Porque para mim, com certeza nao parece.",
"E. Pensando bem, eu realmente nao preciso de conserto no momento.",
"O que exatamente voce quer que eu faca com essa antiguidade enferrujada!?!? Receio que nenhum ferreiro em todo o Caribe consiga conserta-la.",
"Obrigado, vou me lembrar disso! Adeus.",
"Nossa, sua ",
"esta em pessimas condicoes! TENHO que conserta-la!",
"Quero que voce faca desta a melhor espada do arquipelago, mesmo que isso me custe. ",
"Faca dela uma lamina da qual se orgulhe, eu te dou. ",
"Uma espada decente e tudo que preciso. Voce pode conserta-la por, digamos ",
"Estou com pouco dinheiro, entao de uma escovada rapida nela por... ",
"Isso e muito caro, deixa pra la.",
"Hmm, sua ",
"esta em pessimo estado. Quer que eu conserte?",
"Bem, sua ",
"esta em condicoes razoaveis, mas voce pode causar muito mais danos com ela depois que eu consertar!",
"Legal! ",
"! Eu diria para afia-la um pouco mais, poli-la... O que voce me diz?",
"Ha! E o que exatamente voce gostaria que eu fizesse com sua ",
"? Brincadeira, posso poli-la para voce, se quiser.",
"... Isso ",
"e incrivel! Uma verdadeira obra-prima! Eu nao ousaria fazer nada com ela, com medo de destrui-la!",
"Se quiser meus servicos, equipe uma lamina, uma lamina de verdade, antes de falar comigo!",
"Ai esta, terminei. Espero ve-lo novamente quando precisar dos meus servicos.",
"Obrigado, saberei onde encontra-lo!",
"Quero que voce faca desta a melhor arma do Arquipelago, mesmo que isso me custe ",
"Faca dela uma arma da qual se orgulhe, eu te darei ",
"Uma arma decente e tudo que preciso. Voce pode conserta-la por, digamos,... ",
"Estou com pouco dinheiro, entao de uma olhada rapida nela por... ",
"Se quiser meus servicos, equipe uma arma, uma arma de verdade, antes de falar comigo!",
};