string DLG_TEXT[132] = {
"Ei, #slad#, você parece um cachorro-do-mar experiente! Compre-me uma caneca de rum, sim?",
"Não estou me sentindo particularmente caridoso no momento.",
"Claro. E eu vou me juntar a você.",
"Ei! Você quer jogar dados? Recentemente voltei de uma expedição de muito sucesso, então tenho dinheiro a perder!",
"Realmente? Você não parece.",
"Não me distraia da minha bebida!",
"...",
"Nem olhe na minha direção! Você tem a reputação de ser o melhor jogador de dados destas ilhas. Não estou arriscando.",
"Justo.",
"Dizem que você é um ótimo jogador de dados. Quer brincar um pouco?",
"Por que não? Vamos jogar.",
"Não agora.",
"Ei! Quer brincar um pouco? Eu li em seu rosto - você tem sorte no jogo.",
"Oh! Feliz em te ver, ",
". Você quer jogar alguns dados? Rolar os ossos velhos?",
"Tudo bem, claro. Vamos jogar.",
"Talvez outra hora.",
"Já perdi uma fortuna, mas ainda tenho algo para apostar!",
"E o que seria aquilo? Seu casaco comido pelas traças?",
"Não, não, não - ainda tenho algum saque sobrando. Olhe aqui!",
"Tudo bem - vamos ver o que você está escondendo.",
"Bem... não posso te mostrar aqui. Mas aluguei um quarto aqui perto. Vamos lá.",
"Não, obrigado. Em alguma outra hora.",
"OK. Provavelmente vou me arrepender disso, mas você me deixou curioso. Vamos dar um passeio. ",
"Estalajadeiro! Mantenha esta mesa livre até voltarmos!",
"Ninguém vai aceitar. Vamos.",
"Vê essa beleza? Eu a ganhei em um jogo de cartas. Vou hospedá-la agora, se você me der a chance de ganhar parte do seu dinheiro.",
"Bem, ela é linda...",
"Muito certo, ela está! Mas um jogo é um jogo.",
"Tudo bem. Vamos jogar.",
"Como você ousa fazer tal aposta?!",
"Ah bom! Jogamos de acordo com as regras padrão! 100 peças de ouro por rodada!",
"Tudo bem, você aposta a garota contra os meus 100, mas vamos fazer isso aqui. Você tem os dados?",
"Eu faço. Eu vou rolar primeiro... ",
"!!!",
"Minha vez. Eu obtive... ",
"! Você perde, rapaz!",
"Exploda-o! O que aconteceu com a minha sorte? Tudo bem, pegue a garota e vá!",
"Com prazer.",
"O que?",
"Seu porco imundo! Você não merece viver!",
"Você está tentando me enganar? Bem, não vai funcionar!",
"Você está procurando problemas? Você encontrou!",
"Vamos fazê-lo! Eu aposto ",
"Eu vou apoiar isso. Jogue seus dados.",
"Eu não vou jogar.",
"Suficiente! Eu não estou mais brincando com você",
"Como quiser. Vou procurar outra pessoa para brincar",
"! Já vi lances melhores. Sua vez.",
"! Não é o melhor lance, mas vamos ver como você se sai.",
"! Nada mal nada mal! Você precisará fazer melhor, no entanto.",
"! Estou com calor hoje!",
"Dá-me os dados.",
"! ",
"Você perdeu, rapaz!",
"Pegue. Mas aposto que desta vez vou ganhar!",
"Tudo bem, você venceu. Mas não estou mais jogando",
"! ",
"Você ganhou! Arrase tudo! Tudo bem, mais uma vez.",
"Experimente, você não vai ganhar de qualquer maneira",
"Não dessa vez.",
"Hum. Um desenho. Eu odeio empates. Mais uma vez?",
"Claro. Jogue os dados.",
"Não, não quero abusar da sorte.",
"Agora, isso eu gosto! Então, você vai me comprar uma caneca de rum?",
"Certamente. Estalajadeiro! Rum!",
"Você é um verdadeiro amigo! Felicidades para nós!",
"Uau. Coisas fortes!",
"À sua saúde e à sua generosidade!",
"Tosse-tosse-tosse... Isso é suave! Bem, eu tenho que seguir em frente. Vejo você por aí.",
"Vamos tomar mais uma caneca.",
"Torça meu braço! Ok, por que não?",
"Estalajadeiro! Mais rum!",
"Você... você está tentando me embebedar e roubar meu dinheiro!",
"Estabeleça-se! Eu sou seu amigo, lembra?",
"Cale a boca, rato, antes que eu acabe com você!",
"Escute, você é um bom #sgender#. Talvez você possa me ajudar com...uma determinada situação?",
"Não. Eu tenho que ir.",
"Claro! Somos amigos, certo?",
"...E então eu peguei a lâmina de sua espada e...",
"...e ela me diz, ela diz...",
"Saúde! Ah, quem é esse?!",
"Huh? O que? Onde?",
"A questão é que um dos soldados me insultou... sim!",
"Soldados? Não não. Acho que vou passar.",
"Insultado?! Onde ele está? Leve-me até ele!",
"Você não é meu amigo! Não! Você quer... você quer me matar! Isso mesmo - para me matar!",
"Tudo bem, vejo que você já teve o suficiente por hoje. Contanto!",
"O que? Eu não quero te matar! Pare de dizer isso ou corto sua cabeça!",
"Ajuda! Tire-o de cima de mim!",
"Relaxe, isso não vai doer!",
"Argh! Vou massacrar você como um porco!",
"Veremos sobre isso!",
"Você é tão teimoso! Venha aqui, ou reclamarei com seu mestre e você estará na rua!",
"Você está bêbado, seu porco! Você tem sorte, eu não quero sujar as mãos te ensinando uma lição!",
"O que?! Sou eu quem vou te expulsar!",
"Onde você conseguiu uma espada? Eu vou te mostrar!",
"A única coisa que você pode mostrar a alguém é como fazer papel de bobo! Levante-se dessa cadeira e veremos se você aguenta comigo!",
"Eu não jogo por TãO pouco. Levante-o.",
"O que estamos apostando?",
"Eu mudei de ideia...",
"Eu tenho ",
"! Hmm... Vamos dar uma olhada nas suas cartas...",
"... Excedente. Talvez na próxima vez. Vamos tentar de novo...",
"... A sorte está uma puta esta noite. Vamos brincar mais uma vez...",
"... Abra seus cartões...",
"... Homem de sorte.",
"... ah! Excedente para você. Talvez você devesse reduzir o albatroz?",
"O que estamos jogando?",
"No entanto...",
"Se você sempre joga assim, eu ficaria feliz em ir para uma revanche! Você gosta da minha bolsa, não é, moedas? Sim, você quer! Haha!",
"Você não terá tanta sorte da próxima vez",
"Você é um ótimo jogador. Cardsharp, talvez... não me importo... terei mais cuidado com você no futuro...",
"Ha! Aprendemos com nossos erros... Boa sorte...",
"Você é um bom jogador. Você tem uma memória afiada... Com você - brincarei com prazer a qualquer hora aqui.",
"Obrigado pelo jogo... Boa sorte.",
"Então você está dobrando! Sim, me dê um cartão e vamos ver se isso te traz sorte!",
"Infelizmente, não tenho dinheiro suficiente para dobrar",
"! Você perde, moça!",
"Você perdeu, moça!",
"... Garota de sorte.",
"Quer aumentar a sua aposta ou devemos revelar as nossas cartas?",
"Isso é suficiente. Vamos mostrar essas cartas!",
"Bem, só me resta uma coisa de valor para apostar.",
"O que é desta vez?",
"Um convite transferível para o torneio de pôquer em #sGrand Turk#.",
"Já ouvi falar do evento, claro, mas quanto vale realmente o convite?",
"Para jogadores como nós, não tem preço, não apenas testar suas habilidades, mas talvez ganhar o prêmio em dinheiro e o cobiçado troféu!",
"OK. Estou no jogo então, jogue os dados novamente.",
"Certo e que a sorte finalmente esteja do meu lado...",
" você perde novamente. Aceito o convite, não acho que a competição fosse adequada para você de qualquer maneira.",
"Não, já estou farto disto. Apenas saia da sala enquanto pode e deixe a garota aqui.",
};
