string DLG_TEXT[101] = {
"Disseram-me que você fez um grande esforço para solicitar uma audiência. Meu nome é ",
". Agora, por favor, diga-me o propósito da sua visita ",
".",
"Meu nome é ",
".",
"Ah, é você de novo. O que traz você aqui desta vez? ",
"Eu gostaria de conversar com você sobre alguns negócios.",
"Sinto muito, mas há coisas que preciso fazer.",
"Então, por que você me distrai dos assuntos de estado muito importantes?",
"Gostaria de falar com você sobre um pequeno negócio.",
"Estou aqui apenas para prestar meus respeitos, #saddr#. Nada mais.",
"Nesse caso, por favor, saia do meu escritório e deixe-me voltar para assuntos mais importantes.",
"Sim claro. Desculpe por ter incomodado você.",
"Sinto muito, mas não tenho nada para conversar agora",
"Oh sim? Tenho uma proposta para você, capitão.",
"De fato?",
"Vi que você concluiu a tarefa com sucesso; meus parabéns, capitão! Aqui está sua recompensa.",
"Meus agradecimentos; Foi um prazer ajudá-lo.",
"Você deve destruir o ",
" navio ",
"missão pirata",
" ameaçando o envio ",
". Se você afundá-la, vou recompensá-lo com uma boa quantia de ",
" ouro. O que você diz, capitão?",
"Você não ouvirá falar dela novamente, isso eu prometo.",
"Receio não poder ajudá-lo.",
"Anseio por perdão, Excelência.",
"Estou interessado em aprender sobre as relações de #sgov_nation# com outras nações.",
"Estou procurando uma Carta de Marca.",
"Ouvi dizer que estou pronto para uma promoção.",
"Não posso mais servir ",
", vossa Excelência.",
"Cansei de servir ",
"Como garantia de que você é um capitão competente e para recompensar meu tempo apresentando seu caso a ",
", devo te pedir ",
" ouro.",
"Sem chance.",
"Muito bem.",
"#sgov_nation# tem sempre o prazer de aceitar novos capitães ao seu serviço. ",
"Estamos atualmente em guerra com ",
"",
"nenhum grande poder, mas ",
". Claro, ",
"Os piratas devem sempre ser afundados à primeira vista.",
" À luz do seu serviço anterior ",
" concede a você a classificação de ",
"Vou deixá-lo orgulhoso, Excelência.",
"Você prejudicou ",
", e ",
" não esquece seus inimigos. Saia imediatamente, ou os guardas vão te jogar fora!",
"...",
"Você causou ",
" grande dano, capitão, mas ",
" está disposto a ignorar suas transgressões passadas... por um preço: ",
"Muito bem, senhor. Aceito.",
"É um prazer lidar com você, ",
"E você, Excelência.",
"Você é realmente! Excelente trabalho. Sua nova classificação é ",
". Além disso, você é premiado ",
" hectares de terra por ordem de ",
"Obrigado, senhor.",
"Tem certeza, ",
" lamentaremos perder seu serviço.",
"Sim eu sou.",
" não gosta de vira-casacas ",
"Uh, não importa.",
"Muito bem. Mas espero que você reconsidere, com o tempo...",
"Adeus, ",
"Huh?",
"Difícil.",
"De fato? E quem é seu companheiro?",
"Este é Bonifacius del Agave, um agente especial. Nós acreditamos que ",
", um navio actualmente atracado no seu porto, implicado no rapto de ",
". Normalmente nossas próprias tropas revistariam o navio e prenderiam sua tripulação, mas como ele está no seu porto, achamos mais apropriado pedir sua ajuda.",
"Claro, qualquer coisa para ajudar nossos aliados. Precisarei de ver alguma prova de sua autoridade, é claro.",
"Hum. Há pessoas na corte espanhola, entre elas o governador de la Vega, que gostariam de ver a Holanda mais uma vez uma dependência da Espanha. Se eu relatar que você não cooperou, os navios de guerra que ele enviará provavelmente mostrarão nossa autoridade.",
"Eu vejo. Você pode dizer ao Governador de la Vega que as coisas mudaram ao longo dos anos, e se ele enviar navios de guerra, eles serão calorosamente recebidos por nosso forte. Agora saia!",
"Er...",
"Bem, você certamente é mais eloqüente que seu companheiro. Mas o mesmo ponto se aplica. Você pode fornecer prova de sua autoridade?",
"Agora isso muda completamente as coisas. É claro que terei prazer em ajudar o seu governador neste assunto. Sargento! Reúna seus homens. Encontre esses senhores no porto e ajude-os em sua busca.",
"Obrigado, Excelência. Apresentarei um relatório quando a operação for concluída.",
"Bem? Presumo que a pesquisa foi bem-sucedida?",
"Sim, Excelência. E quero pedir desculpas pelo acesso de raiva anterior.",
"Bem, os soldados normalmente não são contratados para a sua diplomacia. E estou agradavelmente surpreso com seu pedido de desculpas. Mas onde está seu companheiro?",
"Ele tem um prisioneiro para interrogar. Deixo os detalhes para sua imaginação. Mais uma vez obrigado pela sua ajuda, Excelência.",
"O sargento aqui me contou como você encontrou #Scaptive#. O que você fará com o navio e o capitão?",
"O navio será apreendido e levado para #sSantiago#. Deixaremos a bandeira inglesa hasteada por enquanto para não perturbar outros navios ingleses em #sWillemstad#. Uma vez liberado, hastearemos nossa própria bandeira e voltaremos para casa.",
"Por favor, transmita os meus cumprimentos ao Governador de la Vega. Foi uma honra ajudar no resgate de seu #srelative#.",
"Farei isso, Excelência. Será uma honra relatar o quão importante foi sua assistência no resgate.",
"De fato? Mas você parece familiar de alguma forma. Você já me visitou antes?",
"Não, Excelência. Esta é minha primeira vez em #sWillemstad#.",
"Hmm... tenho certeza de que já vi seu rosto em algum lugar antes.",
"Esse é um presente muito generoso. Por favor, dê ao seu pai meus mais sinceros agradecimentos por isso.",
"Deixe-me ver... hmm... isso parece bastante justo. Serão necessárias mais negociações sobre detalhes como preços e tarifas e irei, sem dúvida, trocar várias cartas com ",
" no futuro próximo. Mas por enquanto, por favor, volte a #sSantiago# e diga-lhe que, pelo menos em princípio, concordo com a sua proposta.",
"Obrigado pelo seu tempo, Excelência. Vir, ",
", devemos retornar ao seu pai com esta boa notícia.",
"Não sei quem realmente é, mas tentar fazer-se passar por um oficial, mesmo que seja espanhol, é uma ofensa grave. Saia agora ou instruirei o sargento aqui para prendê-lo!",
"Ops! <Pensa: é melhor eu colocar meu uniforme de volta se quiser que ele acredite que sou um soldado.>",
"Por que você ainda esta aqui? Saia e volte para o seu próprio governador!",
"Eu acredito que ",
};
