string DLG_TEXT[33] = {
"Bom dia, ",
".",
"Você sabe quem sou?",
"Olá de novo! Obrigado por negociar comigo.",
"Não, obrigado! Quero minha personalidade de volta!",
"Obrigado! As mulheres me amarão com meu novo visual!",
"Voltou para mais, não é?",
"De jeito nenhum. Apenas prestando meus respeitos à sua Maldição.",
"Sim, eu tenho. Me dê me dê!",
"Claro. Eu pareço uma pessoa comum para você?",
"Agora você mencionou isso; não, não parece.",	
"Sou o capitão ",
". Talvez você já tenha ouvido falar de mim.",
"Recordo-me de ter ouvido que você era o capitão do Flying Dutchman. Mas e Davy Jones então?",
"Ah; até mesmo um velho capitão pirata amaldiçoado como eu pode querer se aposentar em algum momento.",
"Então você deu seu navio para esse personagem de Davy Jones? Bem desse jeito?",
"Eu não a entreguei. Sempre há um preço a ser pago por um navio especial como esse. Posso oferecer o mesmo a você.",
"O que exatamente você quer dizer?",
"Você está disposto a pagar o que for preciso?",
"Obviamente!! Agora, que tal aqueles seus navios tão especiais?",
"Bem... de qualquer maneira, geralmente perco meus melhores navios devido a tempestades desagradáveis. Então não faz sentido, realmente.",
"Hum. Pensando melhor; Não, na verdade não. Eu tenho que ir para outro lugar. Tchau.",
"Já que você é um cliente esplêndido, farei um acordo: dê outra olhada em meu estoque.",
"Que bem isso vai me fazer?",
"E se eu pudesse lhe oferecer um antídoto para as tempestades? Por assim dizer, é isso. Admito que comecei a gostar bastante dele, mas vou vendê-lo para você se o preço for justo. O que você acha de 1.000.000 de moedas de ouro?",
"Oh, seu velho brincalhão! Você não pode estar falando sério sobre isso. Heim? Você é serio? Uhm... Vou lhe enviar minha resposta pelo novo 'Express Bottle Messaging System' patenteado pelos piratas. É conhecido como 'E-Bottle', abreviadamente. De qualquer forma, hora de ir agora!",
"É realmente uma quantia considerável! Mas acontece que tenho essa quantia em dinheiro. Então vou pegar agora mesmo, você não precisa embrulhar.",
"E hoje tem oferta especial! Compre um Tridente por 1.000.000 de suas moedas de ouro e você receberá um dos meus em troca. Garantia de meia hora incluída.",
"Dois pelo preço de um, não é? Parece que estou com sorte! QUERO ISSO!!!",
"Mas... Esta moeda parece misteriosa. Parece exalar uma aura de grande poder antigo! Eu não quero isso!",
"Desculpe, sem backsies. Agora! CAIA FORA!!!",
"Mas eu quero dizer isso! Eu realmente NÃO quero essa moeda. Só esse Trident servirá.",
"Eu entendo a mensagem. Eu irei agora... (Para mim mesmo: Oh querido! No que eu me meti dessa vez?)",

};
