string DLG_TEXT[32] = {
"Olá.",
"Adeus.",
"¡Meu Supremo! ¡Meu Supremo! Tenha um navio a curta distância ao certo, que vem em nossa direção! ¡Creo que é a Natividade!",
"Todos saudam El Supremo!",
"Ah, bem, e agora, por favor, com licença.",
"Sinal do ponto, senhor. 'Natividad' aconteceu. Mais uma volta e ela estará na foz do porto.",
"Muito bem, Tenente.",
"O vigia informa que 'Natividad' ancorou, senhor.",
"Aconchegado durante a noite, hein?",
"Senhor, era eu quem estava lá de vigia. Eu vi uma pequena aldeia não muito longe daqui. Você vai querer evitar isso, estou pensando.",
"Na verdade iremos, Sr. ",
". Você viu o caminho que devemos seguir?",
"Sim, senhor. A primeira curva à esquerda vai para aquela aldeia, por isso saltamos essa. A próxima curva fica à esquerda de um pequeno morro com uma grande árvore e é essa que queremos.",
"Obrigado MR. ",
"¡Rendios! ¡Rendios, Españoles! ¡Rendios!",
"Você pode manter sua espada, capitão.",
"Mas nós nos rendemos! Existem regras de guerra.",
"Acredite, senhor capitão, se Don Julian o vir no próximo dia, ele mandará matar todos vocês. Essas são as suas 'regras de guerra'.",
"Há mulheres a bordo! O que esses espanhóis estão fazendo?",
"É melhor você preparar a tipoia",
"E isso não é tudo, senhora. Ele é tão gentil e caloroso como qualquer homem que já navegou para o rei.",
"<Grito de cima> SR. OLDROYD!",
"Como está a situação de Sua Senhoria, Sr. Oldroyd?",
"Ela está lá embaixo cuidando dos feridos, senhor!",
"O QUE?",
"Ela insistiu em ajudar, senhor. São tantos, senhor.",
"Ela está lá embaixo em toda aquela bagunça?",
"Não há como impedi-la, senhor. Ela apenas vestiu uma jaqueta de contramestre e foi trabalhar.",
"Bem, vá lá embaixo, cara, e ajude-a!",
"Sim, sim, senhor!",
"Que bom ver você, senhor. Os almirantes estão lá em cima.",
"Obrigado, Tenente.",
}
