string DLG_TEXT[22] = {
"*O nativo olha fixamente para você*",
"O que você está fazendo aqui?",
"Quem é você?",
"Tchau.",
"Não me siga!",
"O que você estava fazendo na taverna?",
"Ei, o que você está fazendo aqui? Saia agora!",
"Se você insiste...",
"Existe alguma maneira de eu conseguir aquele arco que você está carregando?",
"Prefiro conseguir sem te matar.",
"Eu poderia pagar por isso, se você quiser.",
"Vale mesmo a pena morrer por um arco?",
"O que você diria se eu lhe pagasse 100 pelo seu arco?",
"*O nativo balança a cabeça lentamente*",
"Ok, aqui está",
"*O nativo olha para você com muita raiva e saca uma arma*",
"Ah, estou tentando coletar alguns arcos, mas vejo que você não tem um. Deixa para lá",
"*O nativo ainda olha fixamente para você*",
"Pare de me seguir",
"Você estava nos espionando",
"Você está me espionando",
"Ok, faça do seu jeito!",
};
