string DLG_TEXT[170] = {
"O que você está olhando? Não esperava que uma mulher estivesse no comando aqui, não é? Bem, esta velha ",
", pode mostrar que ela ainda tem um pouco de pólvora no barril!",
"Ei, de onde você tira suas boas maneiras ",
"?",
"Estou certo? Seu nome é?",
"Aprendi-os onde nasci numa cabana suja nos arredores de Lisboa. Eles eram bons o suficiente e não vejo razão para mudá-los.",
"Crianças hoje em dia... É justo - aja como um cachorro-do-mar, se quiser, mas preste atenção ao meu conselho e lembre-se de com quem você usa esse tom!",
"Bem, meu nome é ",
".",
"Guarde seu conselho para você mesmo ",
".",
"O que você precisa? Você veio aqui para molhar o apito?",
"Diga-me - como você se tornou dono de uma taverna?",
"Eu quero saber uma coisa.",
"Eu só quero encontrar alguns tripulantes para o meu navio.",
"Você não disse que tinha um quarto vago?",
"Tem cama grátis na sua pousada?",
"Desculpe. Eu tenho que ir.",
"Sim, de fato. Seu navegador estava com malária, então Rheims não pôde levá-lo junto.",
"Ele ainda está na ilha?",
"Não não. Ele se recuperou há muito tempo. Então Rhino o chamou. Eles tiveram uma longa conversa e então o navegador saiu.",
"Isso é tudo que você sabe? Onde ele foi?",
"Bem, eu o ouvi dizer algo sobre #sGreenford#. Disse que tem uma casa lá. Provavelmente uma mentira... mas talvez não. \n Se você está procurando por ele, peça ",
"Giraldo Figuiera",
"Giraldo Figueira",
" em #sisland_Greenford#.",
"Obrigado.",
"Eu tenho um quarto... mas quanto tempo você planeja ficar?",
"Até de manhã.",
"Só até escurecer.",
"Certo. Vai custar 5 peças de ouro.",
"Tudo bem. Aqui está o seu dinheiro.",
"Muito? Acho que minha carteira e eu dormiremos debaixo de uma mesa aqui na taverna.",
"Se for esse o preço, eu passo. Sempre posso dormir na sala comunal.",
"Vou pensar sobre isso.",
"Vai custar 5 peças de ouro.",
"OK. Aqui você vai.",
"Muito? Acho que minha carteira e eu dormiremos debaixo de uma mesa aqui na taverna.",
"Se for esse o preço, eu passo. Sempre posso dormir na sala comunal.",
"Talvez mais tarde. Vamos falar sobre outra coisa.",
"Oh, bom senhor! Já contei esta história centenas de vezes!",
"Tenho certeza que você está cansado de contar a todos a história da sua vida. Mas estou realmente interessado. Talvez você possa abrir uma exceção para mim?",
"Então conte pela centésima vez! Não finja que você não é sua matéria favorita.",
"Bem, você não é um demônio eloquente?",
"Que tal se você apenas me contar sua história?",
"Não interrompa os mais velhos, filhote! Estou chegando lá. Aconteceu há cerca de 30 anos... eu ainda era uma menina bastante jovem. \n Passei a maior parte do tempo pensando no som das ondas, no cheiro do mar, nas noites estreladas...meninos....",
"Prossiga.",
"Tudo bem. Já ouvi o suficiente. Vamos ao que interessa.",
"Um dia, um jovem marinheiro apareceu. Ele me virou minha cabeça, \n Me convenceu a navegar para um país fabuloso onde ele disse que qualquer um poderia ficar rico rapidamente e viver feliz para sempre.",
"Ele quis dizer o Novo Mundo?",
"Ok, acho que entendi a essência. Vamos conversar sobre negócios.",
"Você é muito esperto, não é? Sim, ele quis dizer o Novo Mundo. Como eu disse, eu era jovem e tola. Então eu fui com ele.",
"Mas como um marinheiro comum trouxe você a bordo de um navio da Marinha? Isso é contra os regulamentos!",
"Acho que posso descobrir o resto. Vamos falar sobre negócios.",
"Sim, era contra as regras, mesmo naquela época. Então ele me ajudou a esconder-me no porão - bem ao lado dos biscoitos!",
"E você ficou lá o tempo todo?",
"Tudo bem. Já ouvi o suficiente. Vamos ao que interessa.",
"Bem não. Fui encontrada, é claro. Acontece que eu não era um boa marinheira naquela época. \n Tive um enjôo horrível, foi isso que aconteceu. Meia hora no mar e pensei que estava morrendo! Comecei a gritar por socorro. \n O que mais eu poderia fazer?",
"Então o que aconteceu?",
"Ok, acho que entendi a essência. Vamos conversar sobre negócios.",
"Meu adorável marinheiro foi executado por quebrar as regras do navio, e eles decidiram me jogar ao mar para alimentar os tubarões. \n Eles também teriam feito isso se um navio com bandeira negra não tivesse aparecido no horizonte naquele momento.",
"Da frigideira para o fogo, hein?",
"Acho que posso descobrir o resto. Vamos falar sobre negócios.",
"Esse é o tamanho disso. Eles me trancaram em uma cabana enquanto lutavam contra os piratas. Acho que eles pensaram que decidiriam o que fazer comigo mais tarde. \n Para minha sorte, os piratas venceram.",
"Então você caiu nas mãos do pirata e isso foi sorte?!",
"E o resto é história, né? OK. Vamos ao que interessa.",
"Algo assim, sim. A porta da minha cabine foi aberta por um homem muito jovem. Ah, ele era tão lindo! \nEsqueci todos os meus medos quando o vi ali na porta.",
"O que aconteceu depois?",
"Acho que posso descobrir o resto. Vamos falar sobre negócios.",
"Bem, agora, você não gostaria de saber? Até uma velha tem que guardar alguns segredos para si mesma!",
"Desculpe! Eu não queria...",
"É realmente possível envergonhar você? Não aja como uma garota boba!",
"Justo. Guarde seus segredos e vamos ao que interessa.",
"Ha! Você não queria! Olhe para você - nunca vi um marinheiro corar antes!",
"Você não é inteligente? Talvez você ainda faça algo de si mesmo - se não morrer primeiro.",
"Por que você não me conta o que aconteceu depois que você se encontrou na praia?",
"Vamos. Conte-me o resto da história ",
".",
"Tudo bem. Já ouvi o suficiente. Vamos ao que interessa.",
"Tudo bem, tudo bem. Lá, no navio, conheci um homem que hoje atende pelo nome de ",
"Isenbrandt Jurcksen",
"Isenbrandt Jurcksen",
". Naquela época, ele era apenas um grande pedaço de homem de olhos azuis. \nE acho que ele também gostou de mim. Ele duelou com o capitão do navio por minha causa - e acabou assumindo o cargo de capitão.",
"Quem é ",
"Isenbrandt Jurcksen",
"?",
"Acho que posso descobrir o resto. Vamos falar sobre negócios.",
"Você nunca ouviu falar dele? Como é possível que você não saiba nada sobre o capitão pirata mais famoso do arquipélago, comandante da escória da sociedade durante estes trinta anos?",
"Ok, agora eu sei. Conte-me mais sobre aqueles primeiros dias.",
"Ok, acho que entendi a essência. Vamos conversar sobre negócios.",
"Bem, navegamos juntos por um tempo e passei a amar esse tipo de vida. Mas um dia tivemos uma discussão acalorada por nada. Eu já tinha meu próprio dinheiro, então saí e equipei meu próprio navio.",
"Você se tornou capitã de um navio pirata?",
"Tudo bem. Já ouvi o suficiente. Vamos ao que interessa.",
"Sim, droga! Tornei-me uma capitã muito boa! Todos os mercadores destas águas tinham medo de mim. Tinha a cabeça a preço, mas sempre consegui enganar os meus perseguidores ou destruí-los.",
"Então, o que aconteceu a seguir?",
"Essa é uma ótima história. Deixe-me perguntar sobre outra coisa.",
"Fui gravemente ferida ao embarcar numa corveta inglesa comandada por um sujeito persistente que me perseguia há vários meses. Quase morri. Depois de me recuperar disso, decidi que era hora de me aposentar. \nDe repente, uma vida tranquila em terra firme me pareceu boa. Então eu abri esta taberna.",
"Isso é uma história. Obrigado por contar isso. Agora deixe-me perguntar sobre outra coisa.",
"Você é uma ótima contadora de histórias, velha! Você quase me fez acreditar em você. Mas vamos ao que interessa agora.",
"Certo. O que você quer?",
"Estou procurando um homem chamado ",
"Raoul Rheims",
"Raoul Rheims",
".",
"Você pode me dizer se um navio negro chamado 'Mefisto' entrou na baía?",
"Nada. Vamos falar sobre outra coisa.",
"Ah, aqueles malucos?! Sim, estiveram aqui, mas os deixaria em paz se fosse você. Um malandro aqui brigou com eles, eles o mataram sem pestanejar.",
"Obrigado pelo aviso, mas preciso encontrá-los.",
"Não se preocupe eu posso cuidar de mim mesmo. Você poderia me dizer onde posso encontrá-los?",
"Desculpe, #sladlass#, mas não posso ajudá-lo nisso. Eles partiram e não tenho idéia para onde.",
"Eles conversaram com alguém antes de partirem?",
"Não que eu saiba. Você pode perguntar por aí. Talvez alguém possa te ajudar.",
"Obrigado. Eu farei isso.",
"O que faz você pensar que posso ajudá-lo? Como pode uma velha estalajadeira saber onde está algum canalha?",
"Eu perguntei por aí. Dizem que o cara que procuro ficou aqui na sua pousada.",
"Ouvi um boato de que ele estava no porto. Achei que a estalajadeira local provavelmente saberia algo sobre isso.",
"Quem se importa com o que essas fofocas dizem? Eu não sei de nada!",
"Por que tenho a sensação de que você está escondendo alguma coisa?",
"Olha... eu só não quero causar mais problemas para um homem bom do que ele já tem!",
"Eu prometo que não vou trazer mais problemas para ele do que ele mesmo causou.",
"Eu não vou causar problemas a ele. Acabei de ter negócios importantes com ele.",
"Olha, eu te disse que não sei de nada. Isso significa que não sei de nada! Agora saia!",
"Tudo bem, tudo bem. Você não sabe de nada. Vou perguntar a outra pessoa.",
"Se você não estivesse cercado de canalhas que pensam que você pendurou a lua, eu convenceria um pouco com minha espada...",
"O que isso deveria significar?",
"Nada especial. É que tenho a missão de encontrar esse homem e trazê-lo para #sRedmond#.",
"Para #sRedmond#, hein? Talvez você esteja dizendo a verdade, afinal. ",
"Raoul Rheims",
" uma vez disse que precisava chegar a #sRedmond#, mas teve algumas dificuldades para fazer isso. Talvez você possa ajudá-lo.",
"Essas são exatamente minhas ordens: trazê-lo para #sRedmond# vivo e seguro.",
"Tudo bem. Então ouça. Como eu disse, ele próprio estava navegando para lá para tratar de algum assunto importante, mas alguém disparou um tiro em sua proa e o forçou a mudar de planos.",
"E para onde os seus novos planos o teriam levado?",
"Ele falou algo sobre #sisland_Conceicao#. Ele tem um amigo lá: Desmond Ray Beltrop, chefe dos contrabandistas locais.",
"Obrigado pela informação. Você me ajudou muito.",
"Você acredita em tudo que as pessoas dizem? Eu não sei de nada. Não me incomode de novo!",
"Tudo bem, acho que terei que perguntar a outra pessoa.",
"Oh, somos tão importantes, não é? E o que poderá ser esse negócio?",
"Eu preciso... trazer para ele uma carta de um amigo.",
"Tudo bem, #sladlass#. Eu vou te dizer para onde ele foi",
"Então onde está?",
"Uma carta, hein? Posso ver isso? Ou você está mentindo?",
"Eu não posso mostrar para você. É... ultrassecreto.",
"Mentiroso! Saia antes que os rapazes te expulsem!",
"Tudo bem, vou embora. Mas você vai se arrepender disso.",
"É um pouco tarde para isso. Volte pela manhã e este lugar estará cheio de tripulantes em potencial. Ou, melhor ainda, apenas fique aqui esta noite.",
"Você tem um quarto vago?",
"Talvez mais tarde. Deixe-me perguntar outra coisa.",
"Eu tenho um quarto. Quanto tempo você precisa disso?",
"Até de manhã.",
"Só até escurecer.",
"Certo. Vai custar 5 peças de ouro.",
"Tudo bem. Aqui está o seu dinheiro.",
"Muito? Acho que minha carteira e eu dormiremos debaixo de uma mesa aqui na taverna.",
"Se for esse o preço, eu passo. Sempre posso dormir na sala comunal.",
"Vou pensar sobre isso.",
"Vai custar 5 peças de ouro.",
"Certo. Aqui está o seu dinheiro.",
"Muito? Acho que minha carteira e eu dormiremos debaixo de uma mesa aqui na taverna.",
"Se for esse o preço, eu passo. Sempre posso dormir na sala comunal.",
"Tudo bem. Vou pensar sobre isso.",
"Pare com essa indignação agora mesmo, ou você será expulso daqui!",
"Bem bem. Eu estava saindo.",
"Eu só preciso te fazer algumas perguntas.",
"Por que é que todo mundo pensa que o estalajadeiro sempre sabe tudo?",
"Bem, você deve saber se alguém está hospedado na sua pousada, certo?",
"Que eu possa saber. Caso contrário, vá procurar uma biblioteca. Quem você acha que está hospedado aqui?",
"Ah, sim, nosso lindo e charmoso francês bêbado. Ele está ali na mesa da escada, nadando num barril de rum, o idiota. Muito elegante, grande chapéu vermelho, pena.",
"Veja, isso não foi tão difícil.",
"Isso deveria ser divertido. Ele é tão capaz de matá-lo quanto de falar com você. Ou ambos, ha ha!",
"Ummm....Fico feliz em poder ajudar.",
};
