string DLG_TEXT[66] = {
"Não sei quem você é, mas se você for embora agora, não terei que te dar de comer aos tubarões!",
"...",
"Por que você está procurando ",
"Raoul Rheims",
"?",
"Isso não é da sua conta.",
"Silehard me disse que você viria. Ele me pediu para lhe enviar sua cabeça.",
"Bem, aqui está, bem em cima dos meus ombros. Você é bem-vindo para tentar pegá-la!",
"Ah! É o valente ",
", amigo e herói das massas oprimidas! O que leva um nobre #sgender# como você a procurar um pirata vilão como eu?",
"Ah! É você, ",
", cuja reputação cruel e sanguinária ameaça superar até a minha! O que o traz até mim?",
"Vim entregar-te esta carta.",
"Você é mais palhaço do que eu esperava. Apenas pegue esta carta que trouxe para você, para que eu possa seguir meu caminho.",
"Sinto que deveria estar familiarizado com você, #slad#... mas não consigo imaginar o porquê. Quem é você?",
"Meu nome é ",
", e estou aqui a negócios. Trouxe uma carta para você.",
"Uma carta, você disse? Eu gostaria de saber de quem.",
"Por que diabos tem que saber quem a enviou? Por que não lê você mesmo? Ou você precisa que eu leia para você?",
"Cuidado com a língua, #schild#, ou eu vou tomar sua cabeça como um troféu!",
"Bem, isso responde à minha pergunta... Tudo bem, se você quer saber, a carta é do governador inglês, ",
"Robert Christopher Silehard",
".",
"Robert Christopher Silehard",
"? Então, a velha raposa quer minha ajuda de novo? Muito interessante. Agora, por que você ainda está parado aí? Você entregou a carta, então vá embora!",
"...",
"Deixe-me explicar onde você está errado, #slad#. Esta cidade é minha. Esta ilha é minha. E tudo o que acontece aqui acontece porque eu quero.",
"Então você é o quê - um chefe pirata?",
"Prefiro pensar que sou governador de uma colônia independente. Mas ainda estou esperando sua resposta.",
"Que tipo de civilização você tem aqui, onde uma pobre garota está apenas tentando encontrar seu amante e todos imediatamente começam a gritar!",
"Amante? Haha, você não disse isso! Milagres ainda acontecem neste mundo! Por que ele te deixou?",
"Diga-me, ele estava aqui? Quando? Para onde ele foi?",
"Ele estava aqui... fazendo reparos depois de uma tempestade. Mas não sei para onde ele navegou. Ele não contou. Tudo bem, vá embora agora.",
"...",
"Ahoy, companheiro! Bem, envie-me para o armário de Davy Jones se você não tem a aparência de um verdadeiro pirata.",
"Essa é uma ideia interessante, com certeza. E devo admitir que está ficando muito cansativo ter seu bando de bandidos me perseguindo por todo o Caribe!",
"Eu faço questão de evitar familiaridade com piratas. Adeus.",
"Você é bem-vindo para se juntar à nossa nobre Irmandade. Mas esteja avisado que você será odiado por todas as pessoas comuns, assim como o resto de nós!",
"Naturalmente. Nós roubamos dos ricos. E dos pobres. E guardamos para nós mesmos. Não posso esperar fazer muitos amigos fazendo isso. Mas isso faz parte da diversão!",
"O quê? Mas eu não sou ESSE tipo de pirata! Eu sou do tipo LEGAL que dá doces para crianças pequenas. Adeus, seu canalha de coração negro!",
"Nesse caso, por favor, permita que eu seja o primeiro a recebê-lo na Irmandade, meu #slad#!",
"ARRRRRRRRRRRRR!!!!!!!!!!",
"Estou ocupado.",
"O que o traz até mim?",
"Nada, sério.",
"(Para Beltrop): Ha! Vejo que você está com medo de aparecer sozinho? Você trouxe um jovem #sgender# com você!",
"(Beltrop para o chefe dos piratas): Calma, vamos falar de negócios.",
"Eu não sei quem você é, mas se você não for embora agora, eu vou te dar de comer para os tubarões!",
"...",
"(Se dirigindo a você): Bah, você é o #slad# que afundou o 'Black Pearl'!",
"E daí?",
"(Para Beltrop): Sobre negócios, então sobre negócios, o que você tem a ver comigo?",
"(Beltrop para o chefe dos piratas): O que você quer dizer com o quê?! Acho que é o seu povo que está me impedindo de cuidar dos meus negócios em paz!",
"Eu poderia usar um cara como você. E eu vou pagar mais do que Beltrop. O que você acha?",
"Ha! Essa é a melhor oferta que já recebi! Claro que vou aceitar!",
"Não estou à venda, lembre-se disso!",
"Lealdade é uma boa qualidade, mas vamos lá, é meu negócio oferecer, seu negócio recusar. Nada pessoal, como dizem. Heh-heh.",
"(Beltrop para o chefe dos piratas): Pare de tirar meus homens de mim! E vamos voltar aos negócios! Por que diabos seu povo atrapalharia meus negócios?",
"(Para Beltrop): Meu povo? Interferir com você? Você é louco? Perderíamos mais com isso, porque nós mesmos usamos seus serviços de vez em quando e você aceita os produtos de nós sem fazer perguntas.",
"(Beltrop para o chefe dos piratas): Hmm... Então quem está afundando meus navios? Tenho certeza de que a Irmandade Costeira é a culpada.",
"(Para Beltrop): Já lhe ocorreu que esses caras poderiam ser de #sisland_Douwesen#?",
"(Beltrop para o chefe dos piratas): Já falei com eles, eles também negam a culpa.",
"(Para Beltrop): Então não sei. Mas meus homens não têm nada a ver com isso, então procure seus 'piratas' em outro lugar.",
"(Beltrop para o chefe dos piratas): Certo... Desculpe por mantê-lo ocupado.",
"(Para Beltrop): Está tudo bem. Adeus.",
"(Beltrop para o chefe dos piratas): Adeus.",
};
