string DLG_TEXT[145] = {
", ",
", a que devo a honra desta visita?",
"Posso ajudar, ",
"?",
"É sua primeira vez em nossa cidade ",
"? Eu não te vi aqui antes",
"Eu sou ",
", capitão e proprietário do navio'",
".' Tenho algumas perguntas para você.",
"Meu nome é ",
", e preciso de algumas respostas.",
"Você pode me chamar de capitão ",
". Eu gostaria de algumas informações.",
"Olá, capitão ",
". O que traz você ao nosso canto do mundo?",
"Ah, capitão ",
". ",
"! É você de novo! Como tem sido a navegação - tranquila, eu confio?",
"Olá, ",
", posso ajudar?",
"Quais são as últimas novidades?",
"O que está acontecendo por aqui ultimamente?",
"Sobre o que falam os bebedores locais hoje em dia?",
"Estou procurando me atualizar sobre as últimas notícias, rumores, histórias fantásticas... tudo o que você tiver.",
"Já estive no mar - estou interessado em tudo que ainda não conheço.",
"Me conte alguns rumores; talvez haja alguma notícia que eu possa transformar em ouro.",
"Preciso de algumas orientações.",
"Não estou muito familiarizado com a cidade. Eu poderia usar algumas instruções.",
"Preciso estar em algum lugar e gostaria de receber algumas instruções.",
"Você parece um morador local para mim. Você pode me dizer como chegar a...",
"Eu poderia usar algumas instruções.",
"Não há tempo para conversar. Apenas me diga como encontrar...",
"Eu gostaria de perguntar sobre alguém que você talvez conheça.",
"Preciso de algumas informações sobre um dos moradores locais.",
"Você pode me contar sobre um dos habitantes locais?",
"Gostaria que você me contasse o que sabe sobre um certo sujeito...",
"Estou curioso sobre um dos cidadãos. Você pode me preencher?",
"Aposto que você conhece todo mundo que mora aqui, não é? Eu tenho algumas perguntas.",
"Desculpe. Pensei que você fosse outra pessoa.",
"Estou apenas de passagem. Será mais fácil se você se afastar",
"O que você quer saber, ",
"?",
"Posso ajudá-lo, capitão?",
"O que você quer de mim?",
"Tenho certeza de que esta terra está repleta de rumores. Diga-me alguns dos mais suculentos.",
"Aconteceu alguma coisa interessante ultimamente?",
"Eu só quero saber o que está acontecendo na vizinhança - assassinatos, fraudes... qualquer coisa interessante.",
"Como posso chegar a...",
"Você pode me ajudar a me orientar aqui na cidade?",
"Ainda não consigo encontrar...",
"Você pode me contar sobre alguém em particular?",
"Eu gostaria de perguntar sobre alguém que você talvez conheça.",
"Preciso de algumas informações sobre um dos moradores locais.",
"Nada! Só de passagem.",
"Obrigado. Mais uma coisa...",
"Legal conversar com você. Até mais!",
"Qualquer outra coisa, capitão ",
"?",
"Me diga o que você precisa, ",
".",
"Estou ouvindo, ",
".",
"Quais são as últimas novidades?",
"O que está acontecendo por aqui ultimamente?",
"Estou procurando me atualizar sobre as últimas notícias, rumores, histórias fantásticas... tudo o que você tiver.",
"Preciso de algumas orientações.",
"Não estou muito familiarizado com a cidade. Eu poderia usar algumas instruções.",
"Preciso estar em algum lugar e gostaria de receber algumas instruções.",
"Eu gostaria de perguntar sobre alguém que você talvez conheça.",
"Preciso de algumas informações sobre um dos moradores locais.",
"Você pode me contar sobre um dos habitantes locais?",
"Talvez na próxima vez. Até a próxima.",
"De quem você precisa, ",
"?",
"Você quer saber sobre alguém específico?",
"Quem exatamente você quer dizer?",
"Quero dizer, o cavalheiro governador.",
"Estou interessado no dono da taberna...",
"Estou me perguntando sobre o dono do estaleiro.",
"Estou interessado no comerciante local.",
"Vamos voltar a isso mais tarde.",
"Nosso governador é relativamente jovem. Dizem que ele não é muito capaz e é filho de um conde espanhol. Ele não está aqui há muito tempo e não realizou nada de interessante",
"Eu vejo. Eu tenho outra pergunta para você.",
"Obrigado. Contanto.",
"O que posso dizer. ele é apenas um homem. Ele é dono de uma taverna, então sabe tudo o que está acontecendo nesta ilha.",
"Eu vejo. Eu tenho outra pergunta para você.",
"Obrigado. Contanto.",
"Ele não é bom, esse velho. Ele sempre reclama quando alguém quer comprar um navio novo e só sonha com o passado.",
"Eu vejo. Eu tenho outra pergunta para você.",
"Obrigado. Contanto.",
"Ele é conhecido por sua honestidade e pela qualidade de seus produtos.",
"Eu vejo. Eu tenho outra pergunta para você.",
"Obrigado. Contanto.",
"Onde você está indo, ",
"?",
"Não é um problema, capitão. Aonde você quer ir hoje?",
"Fico feliz em ajudar ",
". Para onde exatamente você quer ir?",
"Onde fica a taberna?",
"Onde posso encontrar o estaleiro?",
"Preciso encontrar alguém que me dê um preço justo pelos meus produtos.",
"Vá direto do portão marítimo pela ponte. Você verá uma placa no prédio bem à sua frente - essa é a taverna.",
"Entendi. Obrigado.",
"Onde fica o estaleiro?",
"Onde posso vender os produtos finos que trouxe comigo?",
"O escritório do gerente do estaleiro fica à esquerda da praça do mercado. Siga em frente pela ponte que sai do portão marítimo da cidade e vire à esquerda. Em seguida, caminhe mais um pouco e logo após uma pequena escada você verá a placa do estaleiro.",
"Eu vejo. E como posso chegar à taberna?",
"Preciso encontrar alguém que me dê um preço justo pelos meus produtos.",
"Obrigado pela ajuda. Isso é tudo que preciso por enquanto.",
"Saindo da porta marítima da cidade, pegue a primeira rua à direita. Desça aquela rua até o fim e depois desça. Lá você encontrará a loja.",
"Onde posso encontrar o estaleiro local?",
"Como posso chegar à taberna?",
"Obrigado pela ajuda. Isso é tudo que preciso por enquanto.",
"Bem, tudo bem ",
" - mas não sei o que há de tão interessante aqui.",
"Claro, contarei a você com prazer, capitão.",
"Você é sempre bem-vindo! Adoro conversar! Então relaxe e ouça",
".",
"Estou interessado na história desta colônia...",
"Existe alguma coisa além da cidade nesta ilha?",
"Vamos mudar de assunto.",
"A história da nossa ilha? Bem, ela foi estabelecida há não muito tempo, mas como a ilha se revelou muito rica e fértil, ela cresceu muito rapidamente. \nAgora é uma das melhores colônias do nosso arquipélago.",
"Prossiga.",
"Sim, é o que todos dizem. Deixe-me perguntar sobre outra coisa.",
"Naturalmente, eles enviaram um governador do continente e construíram um poderoso forte para proteger a colônia. Eu acredito que é o melhor, realmente. Eu gosto da vida pacífica.",
"Entendi. Deixe-me perguntar sobre outra coisa.",
"Não, não há mais nada nesta pequena pedra além de praias desertas, montanhas e selva selvagem.... A selva começa bem fora da cidade, na verdade. Vários caminhos levam até lá, mas só um louco se aventuraria lá sem um bom motivo. Além dos animais predadores, também existem homens predadores - bandidos que ali vivem.",
"Parece perigoso. O que mais você pode me dizer?",
"Bem, de modo geral, a ilha ainda é selvagem e subdesenvolvida. Limpar toda a selva que cerca a cidade é uma proposta assustadora. Mas a terra é muito fértil e as poucas plantações aqui construídas produzem colheitas ricas. Aos poucos, as plantações substituirão a selva e a ilha será coberta de fazendas, campos e estradas. Por enquanto, só há uma cidade portuária.",
"Eu vejo. Algo mais?",
"Bem, há um cume de montanha maravilhoso... uma selva selvagem deslumbrante... quilômetros de praias desertas... e não muito mais. Toda a ação real está na cidade.",
"Prossiga.",
"Eu vejo. Vamos abordar um novo assunto, certo?",
"O que faz daquele seu ferreiro um fliberdegibbet tão viril?",
"Deixe-me colocar desta forma: VOCÊ já deixou cair um lingote derretido no pé?",
"Oh, eu vejo. Vamos mudar de assunto, certo?",
"Ai. É o bastante.",
"Minha lâmina está quase enferrujando e desaparecendo... alguém nesta cidade pode consertá-la?",
"Sim, capitão. Você encontrará o ferreiro no outro extremo da cidade, no ponto mais alto, em frente aos portões de saída para a selva. Tenha em mente que ele é do tipo rabugento...",
"Entendi. Obrigado.",
"Onde fica o estaleiro?",
"Onde posso vender os produtos finos que trouxe comigo?",
" Temos uma população de ",
" cidadãos.",
"Conte-me sobre a colônia.",
};
