string DLG_TEXT[38] = {
"Você não vê que estou de plantão? Não me incomode!",
"Tudo bem, tudo bem.",
"Você queria denunciar algum crime?",
"Claro que não. Afinal, sou capitão. Vejo que você não está ouvindo.",
"Lembre-se: não permitimos brigas nas ruas! Você só pode lutar se alguém te atacar.",
"Certo. Vou considerar essa informação.",
"Esse tempo, e eu tenho que ficar aqui. Você não vai acreditar em mim, mas a única forma de entretenimento que tenho é lutar com as moscas que tentam pousar na minha cabeça.",
"Desculpe, mas não posso ajudá-lo. Afinal, é o seu trabalho.",
"Se você quiser conversar, encontre outra pessoa. Tenho um trabalho a fazer e não posso falar com você.",
"Eu só estava me perguntando se você está vivo ou não. Você está aqui como uma estátua",
"Você acha que é fácil proteger nossa cidade? De jeito nenhum! É um trabalho muito importante e perigoso. Lembro-me de uma vez...",
"diga-me outra hora, tenho que ir",
"Siga em frente e pare de me incomodar.",
"Como você diz, soldado.",
"Ei! Você não vai me trazer uma caneca de rum da taverna?",
"Se eu fizer isso, vão me enforcar por transformar um soldado em bêbado! Não...espere até você sair de serviço e então você pode beber o quanto quiser.",
"Por que apenas marinheiros rudes como você estão tentando falar comigo?! Há alguma mulher bonita nesta cidade?",
"Você chama isso de 'servir' a cidade? Você nem consegue reconhecer um criminoso perigoso... como eu! Ha ha!",
"Você parece muito saudável. Por que você não se junta ao nosso exército? Temos muito espaço no quartel, comida boa, cachaça de graça...",
"Parece bom, mas temo que terei que recusar. Não aguento a disciplina do exército.",
"Este calor...daria tudo o que pudesse para regressar à minha querida Espanha.",
"Sim, este clima não parece concordar com você.",
"Você...*hic!*...seu vira-lata com escorbuto! Você machucou meu...*hic!*...meu amigo!",
"Que amigo? Você está sozinho aqui ",
".",
"O que? Ele estava... aqui há um minuto. Eu irei encontrá-lo. Você...*hic!*...você espera aqui se quiser levar uma surra!",
"Como ousa me contradizer! Eu vou te estrangular!",
"... ",
"Só um minuto agora, onde você pensa que vai tão tarde?",
"Vou levar o irmão aqui para colher ervas curativas.",
"Ervas curativas? No escuro, ",
"?",
"Ele precisa de cogumelos especiais que só saem à noite.",
"Isto é muito incomum. Você não sabe que é perigoso lá fora depois de escurecer?",
"Sim, é perigoso lá fora, com macacos raivosos e Akellani selvagens. Estamos armados, como você pode ver, mas nos sentiríamos muito mais seguros se você consentisse em nos escoltar e nos proteger de perigos.",
"Macacos raivosos? Escolta? Ah... Ahhhh não, não ",
", eu... não posso sair do meu posto. Você pode ir, mas lembre-se, se você for morto, eu avisei.",
"Err, ah, obrigado. Vou tentar lembrar.,.",

};
