string DLG_TEXT[230] = {
"Disseram-me que você fez um grande esforço para solicitar uma audiência. Meu nome é ",
". Agora, por favor, diga-me o propósito da sua visita ",
".",
"Meu nome é ",
".",
"Ah, é você de novo. O que traz você aqui desta vez? ",
"Eu gostaria de conversar com você sobre alguns negócios.",
"Sinto muito, mas há coisas que preciso fazer.",
"Então, por que você me distrai dos assuntos de estado muito importantes?",
"Gostaria de falar com você sobre um pequeno negócio.",
"Estou aqui apenas para prestar meus respeitos, #saddr#. Nada mais.",
"Nesse caso, por favor, saia do meu escritório e deixe-me voltar para assuntos mais importantes.",
"Sim claro. Desculpe por ter incomodado você.",
"Estou ouvindo, ",
".",
"Estou aqui para receber minha recompensa pela morte de Dirty Garry.",
"Sinto muito, mas não tenho nada para conversar agora",
"Oh, ouvi sobre o que você fez. Da face de toda a colônia eu lhe mostrarei o nosso apreço.",
"Isso mesmo, gostaria de ver uma recompensa.",
"Você é um brincalhão. Ha ha. Aqui está o seu dinheiro.",
"Obrigado, sou seu humilde servo.",
"Então, sobre a aposta que você fez... depois de obter a aprovação do nosso departamento fiscal, vejo que temos... deixe-me ver... seis mil.",
"O que?! O negócio foi de 10 mil!",
"Eu não posso te ajudar. No futuro, tente ficar mais calmo.",
"O que quer que você diga, #saddr#. Porco sujo...",
", você está ciente de que é acusado de assassinato? Você foi encontrado junto ao corpo da vítima. O que você diz em defesa desta acusação?",
"Não tem nada a ver comigo. O homem já estava morto quando entrei no quarto! Disseram-me que ele estava apenas ferido e que poderia ter algumas informações importantes para mim.",
", Acabei de saber que um homem foi capturado quando tentava deixar a cidade com uma faca manchada de sangue em sua posse. Ele confessou o assassinato de que você foi acusado. Você será liberado imediatamente.",
"Obrigado. Eu sabia que poderia confiar na justiça aqui na #sConceicao#.",
"Desejo desertar para Portugal.",
"De fato? Muito bem, agora você é cidadão português.",
"Agradeço sua infinita gentileza, senhor.",
"Oh sim? Tenho uma proposta para você, capitão.",
"De fato?",
"Vi que você concluiu a tarefa com sucesso; meus parabéns, capitão! Aqui está sua recompensa.",
"Meus agradecimentos; Foi um prazer ajudá-lo.",
"Você deve destruir o ",
" navio ",
"missão pirata",
" ameaçando o envio ",
". Se você afundá-la, vou recompensá-lo com uma boa quantia de ",
" ouro. O que você diz, capitão?",
"Você não ouvirá falar dela novamente, isso eu prometo.",
"Receio não poder ajudá-lo.",
"Anseio por perdão, Excelência.",
"Estou interessado em aprender sobre as relações de #sgov_nation# com outras nações.",
"Estou procurando uma Carta de Marca.",
"Ah, ",
", que bom que você passou por aqui. Eu gostaria de apresentar meu ",
". Ela virá assim que terminarmos os negócios.",
"Ouvi dizer que estou pronto para uma promoção.",
"Não posso mais servir ",
", vossa Excelência.",
"Cansei de servir ",
"Como garantia de que você é um capitão competente e para recompensar meu tempo apresentando seu caso a ",
", devo te pedir ",
" ouro.",
"Sem chance.",
"Muito bem.",
"#sgov_nation# tem sempre o prazer de aceitar novos capitães ao seu serviço. ",
"Estamos atualmente em guerra com ",
"",
"nenhum grande poder, mas ",
". Claro, ",
"Os piratas devem sempre ser afundados à primeira vista.",
" À luz do seu serviço anterior ",
" concede a você a classificação de ",
"Vou deixá-lo orgulhoso, Excelência.",
"Você prejudicou ",
", e ",
" não esquece seus inimigos. Saia imediatamente, ou os guardas vão te jogar fora!",
"...",
"Você causou ",
" grande dano, capitão, mas ",
" está disposto a ignorar suas transgressões passadas... por um preço: ",
"Muito bem, senhor. Aceito.",
"É um prazer lidar com você, ",
"E você, Excelência.",
"Você é realmente! Excelente trabalho. Sua nova classificação é ",
". Além disso, você é premiado ",
" hectares de terra por ordem de ",
"Obrigado, senhor.",
"Tem certeza, ",
" lamentaremos perder seu serviço.",
"Sim eu sou.",
" não gosta de vira-casacas ",
"Uh, não importa.",
"Muito bem. Mas espero que você reconsidere, com o tempo...",
"Adeus, ",
"Huh?",
"Difícil.",
"Oh sim? Me diga o que você quer.",
"Ouvi dizer que você gostaria de prender um pirata.",
"Na verdade, como você sabe disso?",
"Um capitão em #sRedmond# me contou.",
"Você é um capitão?",
"Sim, governador. O meu nome é Bartolomeu, vim de Portugal há algum tempo.",
"Um compatriota. Você já teve alguma experiência no arquipélago?",
"Sim, já lutei contra os espanhóis em #sSantiago#.",
"Excelente! Nossa pequena colônia precisa de capitães como você. Por causa da guerra com a Espanha, tudo o que enfraquece o inimigo nos ajudará a conquistar a independência.",
"O pirata está trabalhando para os espanhóis?",
"Não. Ele é inglês, mas não sei se trabalha para os britânicos ou para os espanhóis.",
"O que fez ele, contra a colónia ou contra Portugal?",
"Atacou muitos navios portugueses e ainda teve a audácia de atacar agricultores fora da cidade.",
"Você sabe onde posso encontrar esse desgraçado arrogante?",
"Eu não faço ideia. Já tentamos prendê-lo muitas vezes, ele sempre consegue escapar da nossa frota. Na verdade, ele tem um navio rápido - um novo modelo de caravela.",
"Esta parece ser uma tarefa difícil... capturá-lo, quero dizer.",
"É por isso que serei muito generoso se você tiver sucesso.",
"Quão generoso, exatamente?",
"Você receberá 40.000 moedas de ouro e os agricultores fornecerão muitos produtos de nossas plantações.",
"Essa é realmente uma recompensa generosa para um capitão!! Estou disposto a ajudá-lo. O único problema é que não tenho ideia de como começar minha pesquisa.",
"Bem, a última vez que ele foi perseguido por um dos meus navios, ele fugiu para #sisland_Oxbay#.",
"Quando isto aconteceu?",
"Apenas um mês atrás.",
" A trilha ainda está quente, por que seu capitão não tentou capturá-lo ali?",
"Ele não poderia, ordens você vê. Temos um acordo com as autoridades britânicas. Nenhum dos nossos navios de guerra pode atracar nesta ilha, a menos que esteja em perigo.",
"Então você não sabe se esse pirata atracou em #sisland_Oxbay#, ou não?",
"Não. No entanto, enviei um diplomata para lá poucos dias depois, mas os britânicos não estavam interessados em nos ajudar.",
"Estranho, os britânicos protegendo um pirata!! Você acha que isso nos diz alguma coisa?",
"Como já disse, não posso confirmar se ele trabalha para eles ou não, mas há indícios de que sim. Meu diplomata só pôde informar que não viu o navio em nenhum porto da ilha.",
"Só mais uma pergunta. Seu capitão danificou o navio pirata ou apenas o perseguiu?",
"Conseguiu danificar ligeiramente a caravela. Mas o pirata ainda conseguiu escapar. Por que você pergunta?",
"Eu irei para #sisland_Oxbay#. Talvez eu possa obter mais informações do que o seu diplomata.",
"Tudo bem, capitão. Faça o seu melhor. Já estou impaciente para que você encontre uma pista.",
"Obrigado, Governador. Vejo você em breve!",
"Capitão! olha Você aqui. Parabéns pela prisão de Charles Baxter. É o nome dele, não é?",
"Sim, governador. Mas essa foi uma missão perigosa para capturá-lo.",
"Eu acredito nisso. Onde você o encontrou?",
"Em #sCharlestown#. Ele foi protegido pelo próprio Governador.",
"Como pode ser! As relações entre Portugal e Inglaterra são amigáveis. É injusto que um governador britânico proteja um pirata que ataca minha colônia.",
"Ele era corrupto e Charles era muito generoso.",
"Enviarei um despacho ao nosso Rei, ele avisará a Coroa Britânica. Talvez o rei deles deponha o governador de #sCharlestown#.",
"Na verdade, isso poderia ser uma solução.",
"De qualquer forma, como prometido, vamos falar da sua recompensa. Primeiro, o dinheiro, 40.000 moedas de ouro, como prometido, e eu já dei a ordem para carregar algumas mercadorias em seu navio.",
"Obrigado Governador. Foi um prazer atendê-lo.",
"Isso não é tudo, quero lhe dar um item especial.",
"O que é? Estou curioso.",
"Como gratidão pela sua coragem e valor, deixe-me dar-lhe esta espada. Usei-o quando era um jovem oficial no Brasil. Está um pouco desgastada, mas acredite, ainda é uma espada excelente. Você parecerá um espadachim profissional.",
"Que lâmina linda! Você me honra com este presente.",
"Você é sempre bem-vindo em nossa bela colônia. Obviamente você tem outros planos agora, com bolsa cheia e carga para vender. Ficarei feliz em cumprimentá-lo novamente no futuro.",
"Então eu faço. Adeus, Governador!",
"Sim?",
"Seu enviado me disse que você tem uma missão para mim.",
"Na verdade, capitão. Mas é uma história triste que tenho para contar.",
"Por que triste?",
"O meu irmão veio de Portugal há um ano. Ele me ajudou na guerra contra os espanhóis comandando a Marinha de #sisland_Conceicao#. Ele venceu muitas batalhas contra nossos inimigos, mas infelizmente foi morto durante um embarque de um capitão espanhol há algumas semanas.",
"Por favor, aceite minhas condolências Governador. Mas a morte do seu irmão tem alguma relação com a missão?",
"Sim capitão. Eu quero minha vingança. Eu sei que você tem muita experiência na luta contra os espanhóis. Eu pagarei a você 50.000 moedas de ouro se você encontrar e matar o assassino dele.",
"Uma grande recompensa. Você sabe quem matou seu irmão?",
"Sim, graças a um espião, agora sei o nome dele. É o capitão Arturo Campos. Ele costumava patrulhar #sTortuga# e San Salvador.",
"Então essa é a chave, navegarei para essas ilhas em busca dele.",
"De fato. Mas desta vez você terá a ajuda da minha Marinha.",
"É necessário, Governador?",
"Os soldados e marinheiros que serviram sob o comando do meu irmão pediram voluntariamente para participar desta missão. Meu irmão era muito respeitado.",
"Quantos homens me acompanharão?",
"Na verdade, vou te emprestar uma Fragata Latina para a missão. Você não terá que usar seu navio. Seus homens podem ficar aqui até você cumprir a missão.",
"Aquele navio já não tem capitão?",
"Sim, Capitão Queiroz. Ele será seu oficial durante a missão. Você pode encontrá-lo lá fora... Esperando por você.",
"Tudo bem. Preciso falar com meu oficial, Emilio Soares, antes de sair da ilha.",
"Isso é compreensível. Faça como quiser, só quero que você consiga matar Arturo Campos.",
"Considere-o um homem morto andando. Até breve, Governador.",
"Olha Você aqui! O que aconteceu? Você encontrou Campos?",
"Sim, governador. Nós o conhecemos em #sisland_Turks#. Ele foi morto durante uma luta entre seus soldados e os espanhóis.",
"Parabéns Capitão! Finalmente, a morte do meu irmão foi vingada. Você não sabe o quão importante foi. Pegue essas 50.000 moedas de ouro conforme prometido.",
"Obrigado, Governador.",
"No entanto, tenho uma má notícia para você. Você conheceu sua tripulação antes de vir para cá?",
"Não. Há algo de errado com eles?",
"Quando você estava cumprindo a missão, seu navio foi abordado pelo inimigo.",
"O inimigo? Quem se atreveu a atacar meu navio?!",
"Um mercenário trabalhando para os espanhóis, de acordo com sua tripulação. Ele embarcou secretamente no seu navio à noite com seus homens. Eles atacaram tão silenciosamente que os soldados do forte que protegia o porto nem perceberam.",
"Mas ele não roubou meu navio, eu o vi atracado no porto hoje.",
"Ele não estava interessado em roubar seu navio, ele só estava procurando por você.",
"Humm.. Outro mercenário espanhol querendo ganhar uma recompensa substancial pela minha captura, ha ha, grandes chances eles têm.",
"Acredito que foram os espanhóis.",
"Esqueça-o, Governador. Ele vai procurar por muito tempo antes de me encontrar.",
"Mas, você não entende, quando saíram do seu navio levaram o seu oficial, Emílio Soares.",
"Filho da bunda do macaco! Ele vai pagar caro por isso, assim como fez Pedro Rivera, mas não tão rápido. Agora, isso muda tudo. Não deixarei Emilio nas mãos do seu captor. Eu o encontrarei.",
"Se quiser ajuda, basta pedir. Você precisa de um navio ou de alguns soldados para ajudar em sua busca?",
"Não, governador. Só preciso saber o nome do mercenário. Minha tripulação sabe disso?",
"Eu perguntei, mas eles não sabem.",
"Sem o nome dele, a busca será mais difícil.",
"Talvez eu possa te ajudar. Há um espanhol que trabalha para mim como informante. Graças a ele descobri que foi Campos quem matou meu irmão.",
"Interessante. Onde posso encontrá-lo?",
"O informante mora em #sIsla Muelle#. Pegue esta carta que explica que você trabalha para mim. Caso contrário, ele irá tratá-lo como um inimigo.",
"Obrigado, Governador. Devo sair de #sConceicao# e encontrar meu oficial - quanto mais cedo melhor.",
"Claro, Capitão, tenha cuidado, você estará em solo inimigo. Boa sorte e bons ventos.",
"Adeus, Excelência.",
"Capitão Bartolomeu! Faz muito tempo que não te conheço. É sempre um prazer revê-lo.",
"Obrigado, Governador. Infelizmente, tive alguns problemas recentemente. Gostaria de saber se você poderia me ajudar.",
"Claro. Mas o que houve?",
"A minha tripulação amotinou-se devido ao comportamento de um oficial. Eles capturaram meu navio, me abandonaram, atacaram um navio de guerra inglês e afundaram na Jamaica.",
"Notícia triste, de fato.",
"Preciso ganhar dinheiro rápido o suficiente. Talvez você pudesse me dar uma missão como fez no passado.",
"Na verdade, capitão, você veio no momento certo. Tenho uma missão muito importante.",
"O que é isso exatamente?",
"Deixe-me explicar. Há duas semanas, uma pequena frota portuguesa capturou ao largo de #sisland_Isla Muelle# um navio de guerra espanhol vindo de Espanha.",
"Então?",
"A bordo estava um enviado do Rei que deveria ir a Cartagena em missão. Ele tinha consigo uma carta do próprio rei. Sua missão era verificar as defesas recentemente melhoradas da cidade e conhecer a real situação de Cartagena em muitos aspectos.",
"Onde ele está?",
"Na prisão com a tripulação do navio de guerra.",
"Que ajuda você deseja?",
"Gostaria que você fosse a Cartagena sendo levado para o enviado. A ideia é fazer primeiro algum serviço de inteligência. Quero saber se um pequeno grupo de soldados consegue fazer uma operação espectacular para atingir a moral espanhola na região mas também para impulsionar a moral portuguesa na Europa na guerra contra os espanhóis.",
"Bem, eu gosto disso. Devo ir agora para Cartagena?",
"Ainda não. Como sabem, as nossas relações com a Holanda são amigáveis. Ambos os países têm o mesmo inimigo: a Espanha. Acho que seria interessante se eu pudesse encorajar os holandeses a participarem numa operação futura.",
"Eu poderia ser útil para isso. Conheço um capitão holandês que vive em Bonaire. Ele poderia obter a ajuda de seu governador.",
"Excelente! Vou escrever uma carta explicando minhas intenções. Você o entregará ao Governador depois de conversar com seu amigo.",
"Eu farei.",
"Volte aqui assim que tiver uma resposta.",
"Certamente, Governador. Estarei no porto esperando a carta",
"Aqui está, Capitão Bartolomeu! Você tem alguma boa notícia?",
"Sim, Excelência. O governador holandês concordou em nos ajudar numa operação militar.",
"Ótimo! Agora você pode começar sua missão. Como disse em nossa última conversa, quero que você vá a Cartagena sendo levado para o enviado. Então, você usará o navio dele que capturamos durante a prisão.",
"Onde ela está?",
"No porto neste momento. Tivemos que consertá-la nos últimos dias, mas agora ela está em perfeitas condições. Também lhe forneci uma nova tripulação para substituir a espanhola. Parte da tripulação é composta por soldados que participarão de uma possível operação militar.",
"Quem é o capitão deles?",
"Você o conhece. É Augusto Queiroz.",
"É claro que eu me lembro. Ele me ajudou quando tive que matar o capitão espanhol Arturo Campos na ilha turca.",
"Exato. Ele e seus soldados ficarão escondidos no navio até você iniciar a operação militar. Lembre-se Capitão! você só iniciará a operação depois que eu aceitar. Não quero iniciativas pessoais sem o meu acordo. Você entende?",
"Sim, Excelência. Enviarei alguém aqui para obter sua concordância sobre os detalhes do ataque que quero liderar.",
"Good. Before leaving #sisland_Conceicao#, take this letter written by the Spanish King which the envoy had. You'll give it to the Governor of Cartagena. Remember, your name now is Guillermo de la Rosa.",
"I won't forget. Goodbye Excellency!",
"Ha! Captain. I'm so happy to see you again and Captain Queiroz already explained the mission has been a success. No doubt, I'm proud of you!",
"Thank you, Excellency. The Cartagena's fort was partially damaged. The Spanish will need many weeks to have the fort operational again.",
"Wonderful, I must say. It's a hard hit in their confidence. So, how could I reward you for that? I know... I give you some land in #sisland_Conceicao#. Thus, you'll regularly earn some gold from the cultivation of them.",
"Thank you again Governor for your generosity. You always helped me when I needed.",
"And you deserve anyway. In Portugal, people already know about your exploits in the Caribbean. Even our King knows as you fight the Spanish. It wouldn't be surprising that one day the King invites you to visit him in Lisbon.",
"It would be a pleasure to return to my country one day.",
"Indeed. Well, I know you have more to do now in my town so have a good day, Captain Bartolomeu.",
"You too, Governor.",
"Thats understandable. Do as you like, I just want you to succeed in killing Arturo Campos. And seeing you are working for me now, you should take this Letter of Marque to legalize your actions on my behalf.",
};
