string DLG_TEXT[48] = {
"Prazer em conhecê-lo, ",
". Eu sou ",
", e estou ao seu serviço.",
"Eu sou o capitão ",
".",
"Bom te ver de novo, ",
".",
"É você! Eu esperava nunca mais ver seu rosto por aqui.",
"Bom dia para você também, ",
".",
"Acho que não é seu dia de sorte ",
"Gostaria de ver o que tenho em estoque?",
"Claro. Vamos dar uma olhada.",
"Mais tarde. Agora preciso conversar.",
"Em alguma outra hora.",
"Vamos fazer um acordo ou você só quer comprar alguns suprimentos?",
"Eu quero vender alguns produtos.",
"Eu gostaria de comprar alguns equipamentos.",
"Nada, obrigado. Tchau!",
"Sobre o que você quer falar?",
"Estou ouvindo.",
"Pediram-me para entregar uma carga para você.",
"Você precisa de um capitão, senhor? Tenho um navio excelente e posso entregar qualquer carga, onde você quiser.",
"Não tenho tempo para conversar agora",
"Não, não preciso dos seus serviços. Não enquanto você estiver afundando navios #snation_desc#.",
"Nesse caso, adeus.",
"Sinto muito, mas não tenho nada para você no momento.",
"Voltarei mais tarde então.",
"Sinto muito, mas seu navio não é grande o suficiente para que você possa fazer o trabalho que tenho em mente.",
"Voltarei mais tarde então.",
"Oh! Eu só ia pedir que você me fizesse um favor. O problema é que preciso que uma carga seja entregue em ",
", e o mais rápido possível. Se você conseguir fazer isso dentro de um mês, receberá ",
" ouro quando você chegar. Isso parece justo?",
"Eu definitivamente gosto disso.",
"Eu não posso aceitar isso.",
"Já te disse hoje que não tenho nada para você.",
"Oh, desculpe.",
"Você se lembrou da sua tarefa um pouco tarde demais, não acha? Vou levar a mercadoria de qualquer maneira, mas não espere ser pago. Preste mais atenção na próxima vez! Adeus.",
"Até a próxima.",
"Oh! Estou esperando por isso há muito tempo. Aqui está sua recompensa, meu bem ",
"Sempre bem-vindo.",
"Infelizmente, não preciso de seus serviços no momento.",
"Sinto muito por ouvir isso. Vamos discutir outra coisa então.",
"Recuso-me a negociar com uma pessoa com a sua reputação e relações. Agora saia, ",
", antes de chamar os guardas.",
"Muito bem.",
"Sim, estou esperando #squantity# cwt de #scargo#. Você tem?",
"Hum... algumas delas parecem ter sido extraviadas. Não se preocupe, vou repor o que foi perdido e trazer para você!",
};
