string DLG_TEXT[52] = {
"Bem vindo a minha loja, ",
". Meu nome é ",
".",
"Prazer em conhecê-lo. Eu sou ",
", um capitão livre do meu próprio destino.",
"Meu nome é ",
". Sou o capitão e proprietário de um belo navio.",
"Bem vindo a minha loja. Você não encontrará nada melhor. E se você fizer isso, não se esqueça de me dizer e meu marido cuidará deles ",
".",
"Agradeço sua cortesia, mas preciso falar de negócios com você agora.",
"Cada um de vocês, lojistas, diz a mesma coisa: Bem-vindo, capitão! Bem vindos! Bom dia! Willkommen! Existe alguma escola que todos vocês frequentam? Enquanto você quebra a cabeça em busca de uma resposta original, gostaria de conversar sobre negócios.",
"Sim, sim, vamos de fato...",
"Apenas me mostre o que você tem em estoque.",
"Mostre-me quais produtos você tem para oferecer.",
"Eu gostaria de algumas informações.",
"Estou mais interessado em informação do que em troca.",
"Sinto muito, mas devo me despedir de você.",
"Gostei da nossa pequena conversa, mas agora preciso tratar de negócios em outro lugar.",
"Você tem alguns... produtos... (piscadela) para vender, ou você só precisa de alguns itens pessoais de corte?",
"Gostaria de vender a carga que trouxe.",
"Quero comprar algumas coisas para mim.",
"Não negociaremos de jeito nenhum. Adeus.",
"Certamente, seu escorbuto #slad#. Mas o que exatamente você quer?",
"Estou ouvindo.",
"Pediram-me para entregar uma carga para você.",
"Certamente você deve ter algum trabalho que gostaria de fazer. Ficarei feliz em lhe emprestar meus serviços mediante o pagamento de uma taxa.",
"Não posso falar agora.",
"Não, não vou precisar dos seus serviços... Você acha que por ser mulher não consigo lidar sozinha?",
"Desculpe ter ofendido você. Caramba, as mulheres são dramáticas.",
"Sinto muito, mas não tenho nada para você no momento. Você é um #slad# bom demais para se intrometer em negócios piratas.",
"Voltarei mais tarde então.",
"Sinto muito, mas seu navio não tem capacidade para realizar a tarefa que tenho em mente.",
"Voltarei mais tarde então.",
"Oh! Eu só ia pedir que você me fizesse um favor. O problema é que preciso que uma carga seja entregue em ",
", e o mais rápido possível. Se você conseguir fazer isso dentro de um mês, receberá ",
" ouro quando você chegar. E se não... Bem, digamos apenas que nenhum dono de loja lhe dará outro emprego. Ou algum dia será capaz! O que você acha dessa oferta?",
"Não me assusto facilmente, senhora. Gosto do som de um pouco de perigo numa corrida mercantil.",
"Eu estava apenas pedindo uma pequena carga para transportar para você, não um acordo de vida ou morte. Acho melhor ir embora...",
"Já te disse hoje que não tenho nada para você.",
"Oh, desculpe.",
"Você lembrou da sua entrega um pouco tarde demais, não acha? Eu poderia ter contraído escorbuto quando você decidiu aparecer. Você é indigno de se chamar capitão! Adeus.",
"Até a próxima.",
"Oh! Estou esperando por isso há muito tempo. Aqui está seu dinheiro. Então você já pensa em gastá-lo? Se não, tenho uma sugestão ou duas...",
"Sempre bem-vindo.",
"Desculpe. Só não estou com vontade de ajudar você agora.",
"É uma pena. Talvez você responda algumas perguntas, então.",
"História da minha vida. Que tal algumas informações, então?",
"Sair, ",
", antes de me chamar de marido e seus companheiros de bebida.",
"Muito bem, eu não gostaria de perturbar a festa de grogue dele.",
"Sim, #sladlass#. Estou esperando #squantity# cwt de #scargo#. Você tem?",
"Hum... algumas delas parecem ter sido extraviadas. Não se preocupe, vou repor o que foi perdido e trazer para você!",
};
