string DLG_TEXT[52] = {
"Bem vindo a minha loja, ",
". Meu nome é ",
".",
"Prazer em conhecê-lo. Eu sou ",
", um capitão livre do meu próprio destino.",
"Meu nome é ",
". Sou o capitão e proprietário de um belo navio.",
"Bem vindo a minha loja, ",
".",
"Agradeço sua cortesia, mas preciso falar de negócios com você agora.",
"Cada um de vocês, lojistas, diz a mesma coisa: Bem-vindo, capitão! Bienvenidos! Bienvenue! Willkommen! Existe alguma escola que todos vocês frequentam? Enquanto você quebra a cabeça em busca de uma resposta original, gostaria de conversar sobre negócios.",
"Sim Sim claro. Como posso ajudá-lo?",
"Apenas me mostre o que você tem em estoque.",
"Mostre-me quais produtos você tem para oferecer.",
"Eu gostaria de algumas informações.",
"Estou mais interessado em informação do que em negócios.",
"Sinto muito, mas devo me despedir de você.",
"Gostei da nossa pequena conversa, mas agora preciso tratar de negócios em outro lugar.",
"Você tem mercadorias para vender ou precisa apenas de alguns itens pessoais?",
"Gostaria de vender a carga que trouxe.",
"Quero comprar algumas coisas para mim.",
"Não negociaremos de jeito nenhum. Adeus.",
"Certamente, #ssir#. Mas o que exatamente você quer?",
"Estou ouvindo.",
"Pediram-me para entregar uma carga para você.",
"Certamente você deve ter algum trabalho que gostaria de fazer. Ficarei feliz em lhe emprestar meus serviços mediante o pagamento de uma taxa.",
"Não posso falar agora.",
"Não, não precisarei dos seus serviços... pelo menos não enquanto você estiver afundando navios #snation_desc#.",
"Nesse caso, adeus.",
"Sinto muito, mas não tenho nada para você no momento.",
"Voltarei mais tarde então.",
"Sinto muito, mas seu navio não tem capacidade para realizar a tarefa que tenho em mente.",
"Voltarei mais tarde então.",
"Oh! Eu só ia pedir que você me fizesse um favor. O problema é que preciso que uma carga seja entregue em ",
", e o mais rápido possível. Se você conseguir fazer isso dentro de um mês, receberá ",
" ouro quando você chegar. O que você acha desta oferta?",
"Eu definitivamente gosto disso.",
"Eu não posso aceitar isso.",
"Já te disse hoje que não tenho nada para você.",
"Oh, desculpe.",
"Você lembrou da sua entrega um pouco tarde demais, não acha? Vou levar a mercadoria de qualquer maneira, mas não espere ser pago. Preste mais atenção na próxima vez! Adeus.",
"Até a próxima.",
"Oh! Estou esperando por isso há muito tempo. Aqui está sua recompensa, meu bem ",
"Sempre bem-vindo.",
"Desculpe. Não tenho nada para você agora",
"É uma pena. Talvez você responda algumas perguntas, então.",
"História da minha vida. Que tal algumas informações, então?",
"Recuso-me a negociar com uma pessoa com a sua reputação e relações. Agora saia, ",
", antes de chamar os guardas.",
"Muito bem.",
"Sim, estou esperando #squantity# cwt de #scargo#. Você tem?",
"Hum... algumas delas parecem ter sido extraviada. Não se preocupe, vou repor o que foi perdido e trazer para você!",
};
