string DLG_TEXT[93] = {
"Disseram-me que você fez um grande esforço para solicitar uma audiência. Meu nome é ",
". Agora, por favor, diga-me o propósito da sua visita ",
".",
"Meu nome é ",
".",
"Ah, é você de novo. O que traz você aqui desta vez? ",
"Eu gostaria de conversar com você sobre alguns negócios.",
"Sinto muito, mas há coisas que preciso fazer.",
"Então, por que você me distrai dos assuntos de estado muito importantes?",
"Gostaria de falar com você sobre um pequeno negócio.",
"Estou aqui apenas para prestar meus respeitos, #saddr#. Nada mais.",
"Nesse caso, por favor, saia do meu escritório e deixe-me voltar para assuntos mais importantes.",
"Sim claro. Desculpe por ter incomodado você.",
"Sinto muito, mas não tenho nada para conversar agora.",
"Oh sim? Tenho uma proposta para você, capitão.",
"De fato?",
"Vi que você concluiu a tarefa com sucesso; meus parabéns, capitão! Aqui está sua recompensa.",
"Meus agradecimentos; Foi um prazer ajudá-lo.",
"Você deve destruir o ",
" navio ",
"missão pirata",
" ameaçando o envio ",
". Se você afundá-la, vou recompensá-lo com uma boa quantia de ",
" ouro. O que você diz, capitão?",
"Você não ouvirá falar dela novamente, isso eu prometo.",
"Receio não poder ajudá-lo.",
"Anseio por perdão, Excelência.",
"Estou interessado em aprender sobre as relações de #sgov_nation# com outras nações.",
"Estou procurando uma Carta de Marca.",
"Ouvi dizer que estou pronto para uma promoção.",
"Não posso mais servir ",
", vossa Excelência.",
"Cansei de servir ",
"Como garantia de que você é um capitão competente e para recompensar meu tempo apresentando seu caso a ",
", devo te pedir ",
" ouro.",
"Sem chance.",
"Muito bem.",
"#sgov_nation# tem sempre o prazer de aceitar novos capitães ao seu serviço. ",
"Estamos atualmente em guerra com ",
"",
"nenhum grande poder, mas ",
". Claro, ",
"Os piratas devem sempre ser afundados à primeira vista.",
" À luz do seu serviço anterior ",
" concede a você a classificação de ",
"Vou deixá-lo orgulhoso, Excelência.",
"Você prejudicou ",
", e ",
" não esquece seus inimigos. Saia imediatamente, ou os guardas vão te jogar fora!",
"...",
"Você causou ",
" grande dano, capitão, mas ",
" está disposto a ignorar suas transgressões passadas... por um preço: ",
"Muito bem, senhor. Aceito.",
"É um prazer lidar com você, ",
"E você, Excelência.",
"Você é realmente! Excelente trabalho. Sua nova classificação é ",
". Além disso, você é premiado ",
" hectares de terra por ordem de ",
"Obrigado, senhor.",
"Tem certeza, ",
" lamentaremos perder seu serviço.",
"Sim eu sou.",
" não gosta de vira-casacas ",
"Uh, não importa.",
"Muito bem. Mas espero que você reconsidere, com o tempo...",
"Adeus, ",
"Huh?",
"Difícil.",
"Parabéns, capitão! Estávamos esperando por você. Esta operação foi um duro golpe para os espanhóis. De agora em diante, eles não poderão mais subestimar os corsários.",
"Na verdade, Governador. No entanto, precisamos ser cautelosos. Os espanhóis estão orgulhosos, podem retaliar a qualquer momento.",
"Eu sei. Não se preocupe, vou me preparar para qualquer ataque espanhol. Suponho que você, Morgan e meu parceiro queiram compartilhar o saque do El Morro agora.",
"Sim, Governador.",
"Muito bem. Não se esqueça de gastar seu dinheiro na minha cidade. As pessoas vão gostar!",
"Lembrarei. Adeus, Excelência.",
"Excelência, tenho motivos para acreditar que os franceses atacarão esta cidade por terra. ",
" providenciará para que o portão terrestre seja aberto à noite, permitindo que os franceses ataquem a cidade por trás.",
"Que absurdo total! O ",
" A família é muito respeitada nesta cidade. ",
"E você não é. Agora, saia antes que eu prenda você por difamação!",
"Lamento não poder convencê-lo. Se você não prestar atenção ao aviso, pouco mais posso fazer. Adeus.",
"E você é um inimigo conhecido da Coroa. Guardas! Prenda esse criminoso e leve #spronoun# para a prisão!",
"Erro seu, Excelência. Quando os franceses chegarem, você provavelmente acabará na cela ao meu lado!",
"Você tem muita sorte, capitão ",
"É isso que você chama de 'afortunado'? Ser preso por tentar avisá-lo sobre um ataque à sua cidade?",
"Não, você tem sorte de ter havido tal tentativa de ataque.\nEmbora eu não pudesse acusar o #vilão# sem provas, fiz com que o exército conduzisse exercícios noturnos no cemitério da igreja. Eles emboscaram os homens do #vilão# e os impediram de abrir o portão. Com o muro seguro, os franceses foram facilmente rechaçados.\nComo recompensa pelo seu aviso oportuno, tenho o prazer de lhe oferecer anistia por todos os seus crimes passados contra a Inglaterra.",
"Parece que lhe devo desculpas, capitão. ",
" - e os agradecimentos desta cidade! Mesmo depois de ter duvidado de você, sua ação nos salvou da invasão francesa sobre a qual nos alertou. Como recompensa, aceite 20.000 moedas de ouro.",
"Obrigado, Excelência.",
"Há outro serviço que você poderia realizar. ",
" agora é um traidor conhecido. Se você trouxer #spronoun#, vivo ou morto, a recompensa será substancial.",
"Mais interessante. Estou ansioso para descobrir o quão substancial.",
};
