string DLG_TEXT[52] = {
"Você não é um pirata, #slad# e vai se arrepender de sua intrusão",
"...",
"Olá, ouvi dizer que você é um capitão competente e, assim como eu, é um inimigo da coroa espanhola!",
"Sua informação está correta, capitão!",
"Você não é um capitão bom o suficiente para estar aqui na minha frente. Saia se quiser viver!",
"Tudo bem. Vou voltar mais tarde.",
"Meu nome é John Coxon. Sou o capitão da Rainha Virgem, um lindo Corvette!",
"De fato?",
"Talvez pudéssemos associar nossos navios e fazer expedições juntos. Com nossos dois navios, poderíamos realizar grandes coisas e nos tornar uma boa força de ataque!",
"Isso é uma pegadinha? Continue falando.",
"Não estou interessado. Desculpe.",
"Bem! Aqui estão os termos! Você não terá que fornecer mercadorias para minha tripulação durante nossa associação, mas poderá assumir os reparos do meu navio em portos amigos, se quiser. Certo?",
"Terei que pagar salário para você e sua tripulação?",
"Não, claro e minha tripulação não será alimentada com suas rações, mas... Siga meu anúncio! Quando você encerrar nossa parceria, todo o saque será dividido em duas partes iguais e se todo o saque não for igual a ",
"Acalmar. você duvida da minha lealdade? Sua proposta parece boa para mim, cara. Quando vamos ver?",
"Desculpe, mas acho que consigo fazer expedições sem parceiro!",
"O mais breve possível! Quero sentir rapidamente o lindo perfume de pó e sangue! Ah, ah!",
"Bem, mas se eu precisar falar com você ou interromper nossa parceria? Como proceder?",
"Nos encontraremos no porto de #sTortuga#. É uma boa proteção contra nossos inimigos. Você não poderia fornecer pranchas, lonas e munições para meu navio, mas cada vez que passarmos alguns dias aqui, minha tripulação reabastecerá automaticamente meu navio!",
"Sim! Espero que a nossa associação permaneça gravada na memória das nações como um dos piores mares do Caribe!",
"Aqui está uma boa ancoragem segura. Se passarmos alguns dias aqui, reabastecerei meu navio e farei alguns reparos!",
"Seria bom passar dias aqui",
"Não podemos ficar aqui! Devíamos partir!",
"Chegou a hora de encerrarmos nossa parceria, meu amigo",
"Quantos dias passaremos aqui?",
"1 dia será suficiente",
"5 dias passados em local seguro serão muito bons para a moral da nossa tripulação!",
"Eu mudei de ideia!",
"Neste caso, acho que chegou a hora de dividir o nosso ouro em 2 partes iguais!",
"Está na hora, meu capitão!",
"Você sabe, acho que vou ficar com todo o saque para mim!",
"Mudei de ideia..Por que temos que nos separar, afinal!",
". Você é meu irmão capitão e estarei sempre aqui para você se você navegar comigo novamente!",
"Vou pensar nisso meu amigo. Espero ver você novamente um dia!",
"Degolador! você já está morto!",
"Vamos ver",
"Meu velho amigo! Que prazer ver você vivo! Que vento bom te traz nessas águas?",
"Apenas uma visita amigável para discutir com meu velho amigo!",
"Quero organizar uma nova expedição com você capitão! Tenho muitos inimigos nessas águas então seu navio e sua experiência serão de ajuda!",
"Com os mesmos termos da expedição anterior #slad#? Cinquenta e cinquenta com um saque de ",
"Claro. Você está duvidando da minha fidelidade para com você?",
"considerando todas as coisas, será para outro momento. eu vou pensar sobre isso",
"Olá meu amigo! Vamos tomar uma bebida na nossa nova expedição! Comecei a enferrujar neste porto!",
"Vamos beber ao nosso ouro!",
"Você tenta abusar de mim, meu amigo! Você escondeu um pouco de ouro do meu visual? Se é tudo o que você tem para compartilhar, acho que vou ficar com todo o saque para mim e matar você imediatamente!",
"Você acredita que vai me matar tão facilmente, capitão?",
"Todos os espanhóis vivos neste mundo são meus inimigos e ouvi dizer que você é amigo da coroa espanhola! Você tem sorte de estar em terra #slad#! Enquanto você for aceito nos portos espanhóis, não teremos que fazer nada juntos, capitão!",
" Sim! Um dia talvez!",
" Mínimo de ouro, vou cortar sua garganta, irmão!",
" Para você e ",
" para mim",
" mínimo de ouro para ser compartilhado!",

};
