string DLG_TEXT[54] = {
"Pare! Quem vai lá? Amigo ou inimigo?",
"Amigo. Definitivamente amigo.",
"Pare! Você é ",
", não é? Você está preso. E você - qual é o seu nome? Você também está preso sob suspeita de ajudar um criminoso conhecido.",
"Criminoso, oficial? Eu não sei nada sobre isso. Este homem pagou uma quantia razoável pelo transporte para #sRedmond#.",
"Não tente bancar o inocente comigo ",
"! Sabemos tudo sobre o seu esquema para vender títulos governamentais falsos.",
"Pode ser que seja verdade, oficial, mas não tive nada a ver com tal esquema. Eu realmente acreditei ",
" ser um passageiro honesto. Agora, posso ir, por favor? Eu gostaria de navegar na próxima maré",
"Muito bem. Se você realmente não tinha conhecimento das atividades criminosas de ",
" então você tem sorte. Se ele não estava envolvendo você em algum tipo de fraude, então provavelmente pretendia roubar você do seu navio.",
"Então eu realmente tive sorte que você o pegou. Bom dia, oficial.",
"Eu poderia até acreditar nisso se você não estivesse tentando sair pelo portão que dá para terra. Mas se o seu navio estiver atracado em alguma praia em algum lugar, então ele é suspeito - talvez um pirata ou contrabandista? Ou um espião inimigo?",
"Eu lhe digo, sou um capitão do mar cumpridor da lei. Aqui está o dinheiro ",
" me deu como tarifa.",
"Você não estaria tentando me subornar, estaria? Nesse caso, isso será adicionado às suas cobranças.",
"De jeito nenhum! É uma evidência - como eu disse, é a tarifa ",
" me pagou. Claro... o que você faz com essas evidências depende de você.",
"Oh, bem, isso é diferente, então. Você está cooperando com nossa investigação. A evidência será muito útil. E já que você tem sido tão cooperativo, não há razão para suspeitar que você tenha feito algo errado, então você pode ir.",
"Obrigado, oficial. Adeus.",
"Alguma ordem, senhor?",
"Apenas me siga, soldado. Você receberá seus pedidos em breve.",
"Para onde vamos, senhor?",
"Para a prefeitura. Qual é o seu nome, soldado?",
"Corporal ",
", senhor.",
"É o seu dia de sorte. Você vai me ajudar a prender o governador, corporaal ",
"O governador, senhor?",
"Sim. Ele será acusado de corrupção. Ele é acusado de desviar recursos públicos para suas próprias contas. Você deve me seguir até a prefeitura.",
"Espero que não tenhamos problemas por isso. Quero dizer, prender o governador, senhor!",
"Não somos nós que estamos em apuros, corporação. Somos nós que prendemos. Agora, você está pronto para isso, ou devo encontrar um soldado mais corajoso?",
"Não senhor! Se vai prender o governador, quero estar lá para ver a cara dele, senhor!",
"Bom homem. Agora, siga-me.",
"Korporaal, por favor, testemunhe isso. Estou prestes a confiscar o livro de contas e o caixa como prova.",
"Sim senhor. Vou testemunhar que você está coletando as evidências.",
"Tudo bem. Agora, corporação, partirei para reunir mais soldados para proteger este edifício adequadamente e para escoltar o governador até o quartel. Enquanto isso, você deve manter guarda nesta porta. Ninguém deve sair sem minha permissão.",
"Eu entendo, senhor.",
"Ninguém deve sair daqui sem a sua permissão, senhor!",
"Muito bom, corporaal. Eu me dou permissão para sair.",
"Pare! Você é ",
". Você está preso por se passar por oficial do exército holandês, prisão injusta de nosso governador e roubo de fundos públicos.",
"Posso ver seus documentos de comissionamento? Caso contrário, pode ser você quem está se passando por um oficial do exército holandês.",
"Cada soldado aqui sabe muito bem quem eu sou - Kapitein ",
". E se você me causar mais problemas, você será baleado aqui mesmo.",
"Muito bem, irei em silêncio.",
"Isso não foi problema. Isso é um problema!",
"Sim, Excelência. Essa #sperson# alegou ser um amigo enquanto eu estava de folga em uma taverna, depois me atraiu para um quarto e me forçou a ficar bêbado. Então #spronoun# roubou meu uniforme.",
"Não é verdade. Não houve forçamento envolvido.",
"Sim, Excelência...",
"Levante-se, você! Sua Excelência, ",
" quer ver você.",
"Diga a ele que ele pode vir aqui. Não vou a lugar nenhum por alguns anos.",
"Pare com sua insolência! Você pode andar ou ser arrastado, e essa é toda a escolha que você tem.",
"Tudo bem, eu vou. Eu poderia fazer algum exercício de qualquer maneira.",
}
