string DLG_TEXT[35] = {
"Ohhh... Minha cabeça!",
"O que aconteceu? Você se sente bem?",
"Você não é espanhol?! Quem é você? O que você está fazendo nesta ilha?",
"Não se preocupe! Não somos espanhóis. Estamos procurando uma mina. Haveria prata em #sisland_Battle Rocks#.",
"Você tem razão. Como você sabe disso? Os espanhóis garantem que esta informação permaneça secreta.",
"Parece que eles falharam. E você? Você também está procurando a mina?",
"Essa maldita mina! Foi a origem do meu infortúnio! Quase perdi minha saúde lá..",
"Você poderia explicar melhor?",
"Bem, os espanhóis encontraram a mina há dois anos. Claro, a mina antes pertencia aos índios. Após a descoberta, os espanhóis deportaram dezenas de prisioneiros de suas colônias para trabalharem aqui como escravos. O destino deles é morrer nesta ilha. E acredite que alguns meses desta vida são suficientes para matá-los.",
"Então, você escapou dos espanhóis.",
"Na verdade, ontem à noite. Mas eles não foram os únicos. Pouco depois encontrei um grupo de índios e embora também tenha conseguido escapar deles, eles me feriram levemente.",
"Humm...Esse pode ser o grupo que lutamos há pouco tempo. Você poderia nos levar para a mina?",
"Você realmente quer ir para lá? A mina é bem defendida por um acampamento militar. E você pode esperar encontrar muitos soldados.",
"Ok, concordo em levar você até lá, mas com a condição de que você libere meus amigos na mina.",
"Claro, teríamos feito isso de qualquer maneira.",
"Neste caso, siga-me!",
"Muito estranho! Eu esperava mais soldados no acampamento.",
"Mais uma razão para ter cuidado. Diga-me agora onde fica a mina para libertar seus amigos.",
"Está perto do acampamento. Siga-me novamente!",
"Quem é você! O que você está fazendo aqui! Seu nome agora!",
"Meu nome é: VÁ PARA O INFERNO!",
"Ei! Konrad Kulczycki está de volta! Você veio nos libertar?",
"Acertou! O tempo para trabalhar nesta mina acabou. Mas eu pensei que vocês fosse mais numerosos...",
"E somos! No entanto, muitos de nós foram com os soldados ao porto.",
"Que porto?",
"O porto onde a prata é carregada a bordo dos navios, é claro.",
"O que?! Há um comboio prateado passando pelo porto?",
"Sim, eles deixaram o acampamento há uma hora.",
"Agora entendo por que lutamos com poucos soldados. Bem, você e seus companheiros vão para a costa leste. Tentarei alcançar o comboio",
"Espere capitão! Conheço um atalho pela selva para chegar ao porto. Ainda é possível juntar-se a eles.",
"Excelente! Vamos agora.",
"Graças a Deus! Finalmente, estamos livres! Eu sabia que Konrad Kulczycki nos ajudaria depois de escapar do acampamento.",
"É verdade, seu pesadelo terminou. Agora, precisamos sair desta ilha. Sempre que mais espanhóis possam desembarcar.",
"Obrigado por tudo! Nunca esquecerei o que você fez por mim e por meus amigos.",
"Foi um prazer. Este ouro será um bom começo para uma nova carreira. Até mais, Konrad Kulczycki!",

};
