string DLG_TEXT[29] = {
"Sim, capitão, e quantos dias ficaremos em terra?",
"1 dia, não há necessidade de mais do que uma parada rápida nesta viagem. Passe a palavra para os rapazes.",
"5 dias serão suficientes. Não quero que vocês, rapazes, percam as pernas do mar!",
"Não há tempo a perder, navegamos com a maré. Certifique-se de manter os homens longe do grogue!",
"Sim capitão",
". O segredo da Ilha do Diabo ainda está seguro, Capitão. Esta ilha ainda é um bom cais onde podemos consertar nosso navio.",
"Sim, amigo",
"!",
", ",
". Se tivermos tábuas e lonas, podemos passar alguns dias em terra aqui para fazer reparos",
".",
"Bem, quais são as suas ordens, capitão ",
"?",
"Capitão, estamos aguardando ordens. Devo canalizar para todos?",
"Bom! ficaremos aqui por alguns dias para fazer reparos em nosso navio.",
"",
"Fique à vontade, amigo.",
"Sim capitão? Temos pranchas e lonas para consertar nosso navio? ",
"E quantos dias você vai querer ficar, para reparos e tudo mais ",
"Bem",
", talvez pudéssemos passar alguns dias aqui.",
"",
".",
"Agora não, cara, por favor!",
"10 dias, rapazes, isso deve nos dar tempo para reabastecer o navio com água e fazer alguns reparos leves.",
"Um mês deveria ser tempo suficiente para inclinar o casco do navio e colocar um pouco de alcatrão, sebo, enxofre e vidro para afastar os vermes teredo. Certifique-se de definir vigias para navios inimigos.",
"Recuso-me a negociar com uma pessoa com a sua reputação e relações. Agora saia, ",
", antes de chamar os guardas.",
"Muito bem.",

};
