string DLG_TEXT[27] = {
"Bem-vindo à biblioteca, como posso ajudá-lo?",
"Desculpa, eu tenho que ir.",
"Estou procurando alguns livros que me ensinarão novas habilidades.",
"Ah, você veio ao lugar certo! Tenho livros sobre luta com espadas, tiroteio, combate naval e tenho um livro sobre o uso de canhões. Você está interessado em algum desses?",
"O livro sobre a luta com espadas parece bom.",
"O livro sobre o tiroteio parece bom.",
"O livro sobre o combate naval parece bom.",
"O livro sobre o uso de canhões parece bom.",
"Não importa, eu deveria ir.",
"Ok, eu aceito.",
"Esse livro é um dos meus favoritos, boa escolha!",
"Esses livros parecem ser bastante populares atualmente.",
"Eu ainda não li, mas outras pessoas dizem que é muito bom!",
"[espaço reservado]",
"[espaço reservado]",
"[espaço reservado]",
"[espaço reservado]",
"[espaço reservado]",
"[espaço reservado]",
"[espaço reservado]",
" Mas não posso dar isso a você de graça. Você pode tê-lo pelo pequeno preço de ",
". Isso parece bom para você?",
"Ok, aqui está. Aproveite o livro!",
"Muito obrigado.",
"Parece que você não tem dinheiro suficiente para comprar este livro.",
"Ah... voltarei mais tarde quando tiver o dinheiro",
};
