string DLG_TEXT[21] = {
"Estou para sempre em dívida com você, #ssir#!",
"De jeito nenhum. Recebi um bom dinheiro pela sua salvação.",
"Mas quem é você? Por que você me salvou?",
"Vamos levar isso para fora.",
"Por favor, me diga quem você é. Por que você me salvou?",
"Conversamos depois. Por enquanto, vamos sair daqui. Não tenho vontade de conversar com um guarda francês.",
"De qualquer modo, quem é você?",
"Eu sou ",
". Seu pai ficou muito preocupado com o seu desaparecimento e me enviou para te encontrar.",
"Eu vejo. Eu estava indo vê-lo quando me deparei com o problema do qual você acabou de me resgatar. Devo-te a minha vida.",
"Não me agradeça. Fui bem pago pelos meus esforços.",
"Mesmo assim, você salvou minha vida e sou grato a você. Agora talvez possamos ver meu pai?",
"Sim. Não vamos perder mais tempo.",
"Capitão, não tenho palavras para expressar minha gratidão. Talvez você me deixe servir como parte de sua tripulação. Não sou um mau espadachim e conheço bem um navio.",
"Sempre há espaço para um homem capaz  especialmente um homem leal. Bem-vindo à minha tripulação.",
"Agradeço sua oferta, mas não posso aceitá-la no momento.",
"Eu entendo. Mas, mais uma vez, obrigado, capitão. Muitas vezes sou encontrado na residência do governador - procure-me lá se mudar de ideia.",
"Vou manter isso em mente. Boa sorte!",
"Capitão, estou feliz em vê-lo! Ainda estou feliz em servir em sua tripulação, se você mudou de ideia.",
"Na verdade, sim. Eu poderia usar um tripulante competente.",
"Vou manter isso em mente. Boa sorte!",

};
