string DLG_TEXT[40] = {
"Oi...",
"Ei, ",
", seu bêbado! Levantar! Nós precisamos conversar!",
"Como é possível ficar tão bêbado? Você tem uma perna oca?",
"...hic...ronco...",
", levante-se, eu disse! Estou aqui a negócios de Geronimo!",
"Gerônimo? Por que você não disse isso em vez de tentar afundar minhas costelas com sua bota?",
"Sim, sim - por que você não toma outra bebida? Talvez você esqueça que eu te chutei. Agora levante-se e vamos conversar",
"Falar de quê? Não devo me encontrar com Geronimo até amanhã. Esse era o acordo. ",
"Cara, você realmente está bêbado, não é? Você consegue se lembrar do seu próprio nome?",
"Olha, não há nada de errado com a minha memória. Deveríamos nos encontrar amanhã. Ele nos dará o resto do dinheiro e nós lhe daremos aquelas estatuetas que roubamos do armazém do comerciante.",
"Muito impressionante - exceto por um pequeno detalhe. Houve uma mudança de planos. A reunião é hoje.",
"Ouvir, ",
". Você acabou de confessar tudo. Agora vamos ver se não conseguimos chegar a um acordo amigável...",
"Se ele quer se encontrar hoje, por que ele mesmo não vem me contar?",
"Você não entende nada, não é, bêbado? Todo mundo na cidade está falando sobre o roubo. Geronimo quer se manter discreto.",
"Ele está com medo, não é? Eu sabia que ele era um covarde quando o conheci!",
"Não me importo com o que você pensa dele, e tenho certeza de que ele não se importa. Agora levante-se e vamos embora",
"Onde?",
"Onde você acha? Para o lugar onde você escondeu aquelas estatuetas! Presumo que nem você seja tolo o suficiente para mantê-los aqui.",
"Uh...na verdade...na verdade...eu os mantive aqui.",
"Brilhante. Bem, pelo menos não precisamos ir a lugar nenhum por causa deles.",
"Ouvir, ",
". Você acabou de confessar tudo. Agora vamos ver se não conseguimos chegar a um acordo amigável...",
"Espere um segundo! E Gerônimo?",
"Para falar a verdade, não conheço nenhum Geronimo. Dê-me as estatuetas imediatamente.",
"Você quer lutar, não é? OK.",
"O que você quer dizer?",
"Dê-me as estatuetas, ou vou arrastá-lo até o primeiro guarda que encontrar e contar a ele o que você acabou de me contar - e você terá que devolvê-las ao homem de quem as roubou. De qualquer forma, você perde as estatuetas. Do meu jeito, você não vai para a cadeia",
"Talvez eu te mate e encontre as estatuetas sozinho.",
"Ah, seu rato!",
"Você tem algum tipo de desejo de morte?!",
"Você pode garantir que ficarei livre? ",
"Eu te dou minha palavra.",
"Tudo bem. Eu vou confiar em você. Eu vou te contar tudo.",
"É um acordo.",
"Sua palavra?! Você acabou de mentir para mim! Agora você está me chantageando! E você quer que eu acredite na sua palavra?",
"Bem, eu sempre poderia te derrubar onde você está",
"Geronimo me contratou para roubar aquelas estatuetas para ele. Prometeu-me 5.000 ouro pelo trabalho. Eu deveria me encontrar com ele amanhã fora da cidade.",
"Perfeito! Agora, se me der licença, vou procurar um guarda para que você possa contar a ele o que acabou de me contar. Se você valoriza sua vida, ficará quieto enquanto eu te amarro.",

};
