string DLG_TEXT[68] = {
"Olá companheiro de viagem. Parece que você está procurando por algo, algo precioso. Talvez eu possa ajudá-lo com isso. Pelo preço certo, claro....",
"O que você vende?",
"Eu vendo histórias, minha querida. Você está interessado em uma de minhas histórias?",
"Eu gostaria de ouvir uma história.",
"Qual história você gostaria de ouvir? Só custará 10 moedas. Esse é um preço justo, certo?",
"Morte, a querida",
"Feliz Boz",
"[espaço reservado]",
"[espaço reservado]",
"...",
"Desculpe, não tenho dinheiro agora.",
"Afinal, não estou interessado.",
"Era uma vez uma linda jovem, sem marido, sem pai, sem mãe, sem irmãos, sem parentes: todos estavam mortos e desaparecidos. Ela morava sozinha numa cabana no final da aldeia; e ninguém se aproximava dela, e ela nunca se aproximava de ninguém. Certa noite, um belo andarilho veio até ela, abriu a porta e gritou: 'Sou um andarilho e estive longe no mundo. Aqui vou descansar; Não posso mais ir. A donzela disse: 'Fique aqui, vou te dar um colchão para dormir e, se quiser, comida e bebida também.'",
"O bom andarilho logo se deitou e disse: 'Agora, mais uma vez, durmo; já faz muito tempo que não dormi:' 'Quanto tempo?' perguntou a garota; e ele respondeu: 'Querida empregada, durmo apenas uma semana em mil anos.' A garota riu e disse: 'Você está brincando, certo? você é um sujeito malandro.' Mas o andarilho estava dormindo.",
"Na manhã seguinte, ele se levantou e disse: 'Você é uma linda jovem. Se quiser, ficarei aqui mais uma semana inteira.' Ela concordou de bom grado, pois já amava o bom andarilho. Então, uma vez eles estavam dormindo, e ela o acordou e disse: 'Querido homem, tive um sonho tão maligno. Sonhei que você estava frio e branco, e viajamos em uma linda carruagem, puxada por seis pássaros brancos.",
"Você tocou uma trombeta poderosa; então pessoas mortas apareceram e foram conosco  você era o rei deles.' Então respondeu o bondoso andarilho: 'Esse foi um sonho maligno.' Imediatamente ele se levantou e disse: 'Amado, devo ir, pois nenhuma alma morreu há tanto tempo em todo o mundo. Preciso ir, deixe-me ir. Mas a menina chorou e disse: 'Não vá embora; fique comigo. 'Devo ir', ele respondeu, 'Deus te guarde.'",
"Mas, quando ele estendeu a mão para ela, ela disse soluçando: 'Diga-me, querido homem, quem você é então.' 'Quem sabe que morre', disse o andarilho, 'você pergunta em vão; Eu não te digo quem eu sou.' Então a menina chorou e disse: 'Vou sofrer tudo, só me diga quem você é.' 'Bom', disse o homem, 'então você vem comigo. Eu sou morte.' A menina estremeceu e morreu.",
"Esse é o fim da história, espero que tenham gostado.",
"Obrigado, foi uma história maravilhosa.",
"Não estou interessado.",
"Certa vez, havia um romano, e seu nome era Happy Boz'll, e ele tinha um carrinho de mão de prata alemã, e costumava colocar sua esposa e seu filho no topo, e ele costumava ir tão rápido ao longo do caminho ele venceu todos os treinadores.",
"Então ele achou que aquele carrinho de moer era muito pesado e desajeitado para ser carregado, e ele o cortou e fez dele varas de tenda. E então o seu burro fugiu, e ele não sabia para onde foi; e um dia ele estava passando pela tenda e disse para si mesmo: 'Abençoada seja minha alma, onde foi que aquele burro foi parar?' E havia uma árvore perto, e o burro gritou e disse: 'Estou aqui, meu Feliz, pegando um pedaço de pau para você fazer uma fogueira.' Bom, o burro desceu com um monte de gravetos, e ele estava há uma semana subindo na árvore, pegando lenha.",
"Pois bem, Happy tinha um cachorro e um dia ele saiu, o cachorro de um lado da cerca e ele do outro. E então ele viu duas lebres. O cachorro correu atrás dos dois; e enquanto atravessava o campo, ele se cortou com uma foice; e então metade correu atrás de uma lebre e a outra metade atrás da outra. Então as duas metades do cachorro pegaram as duas lebres; e então o cachorro bateu de novo; e ele disse: 'Bem, eu os peguei, meu feliz'; e então o cachorro morreu.",
"E Happy tinha um buraco no joelho da calça, e cortou um pedaço da pele do cachorro, depois que ele morreu, e costurou no joelho da calça. E naquele dia, doze meses, seu joelho se abriu e latiu para ele. E então esse é o fim de Happy Boz'll.",
"Estou tendo sonhos estranhos com uma serpente gigante emplumada. Achei que talvez você pudesse me contar mais sobre essa criatura.",
"Oh! Você está vendo Quetzalcoatl em seus sonhos? Isso é muito interessante. Mas não posso te contar nada sobre ele.",
"Por que você não parece saber do que estou falando?",
"Não posso te contar, mas posso te mostrar!",
"Mostre-me? Como?",
"Acho que você é afetado por ele de alguma forma, então, quando o colocarmos em um bom transe, você deverá ser capaz de encontrar dentro de si as respostas que procura.",
"E como podemos fazer isso?",
"Bem... visto que você precisa da minha ajuda com isso, isso vai custar caro.",
"Quanto?",
"Bem, primeiro você precisará me reunir um pouco de ópio para entrar no transe certo. Parece haver um cara no Acampamento de Contrabandistas desta ilha que tem alguns. Diga a ele que eu mando você e ele venderá para você.",
"Isso é tudo?",
"Bem, claro que não. Você também precisará me pagar pelos meus serviços. Isso vai custar muito mais do que as histórias normais. Digamos 500, parece certo. Encontre-me aqui quando tiver tudo o que precisa.",
"OK",
"Tenho tudo o que você me pediu para reunir. Agora você pode me mostrar o que esses sonhos estranhos significam?",
"Sim, parece que você tem tudo que precisamos. Vou levar o ópio agora, o dinheiro virá depois que terminarmos. Isso vai levar algum tempo para me preparar. Você pode me encontrar na taverna em 3 dias?",
"Ah, você conseguiu! Bom, já arrumei o quarto lá em cima então vamos lá! Espere, você ainda tem o dinheiro, certo?",
"Claro, mas você vai me explicar o que vai acontecer?",
"Sim, sim, mas não aqui. Agora vamos lá.",
"Ok, agora é hora de dizer o que vai acontecer. Eu criei uma poção com o ópio que você me deu. Esta poção fará você dormir profundamente. Se as histórias forem verdadeiras, você terá alguns sonhos estranhos. Esses sonhos devem lhe dar uma ideia do que está acontecendo.",
"Você tem certeza de que isso é seguro?",
"Meus ancestrais já faziam coisas assim há muito tempo. A maioria das pessoas acordou.",
"Maioria? Você quer dizer que nem todos eles?",
"Alguns se perderam nos sonhos e nunca mais voltaram. Mas tenho certeza que você vai acordar. Enquanto isso, ficarei aqui para garantir que você esteja seguro.",
"Ok, vamos acabar com isso.",
"Oh! Você finalmente acordou! Comecei a me preocupar. Você está dormindo há quase 12 horas!",
"O QUE! pareceram apenas alguns minutos!",
"Você viu alguma coisa?",
"Sim, vi Quetzalcoatl, ele estava em Cartagena e tentou me entregar um livro. Mas não consegui segurar o livro e ele caiu no chão.",
"Hmmmm..... Talvez você devesse ir até lá. Não tenho certeza do bem que isso lhe trará, mas pode lhe dar algumas respostas.",
"Parece um plano razoável. Obrigado pela ajuda.",
"São apenas negócios. Acredito que concordamos em 500, certo?",
"Na verdade, nós fizemos, aqui está.",
"Eu sinto que isso é mais do que apenas negócios. Não parece certo simplesmente te dar o dinheiro e ir embora.",
"Então não sou o único que tem essa ideia? É tão bom ouvir isso. Capitão, eu não tinha certeza de quanto tempo levaria, então reservei o quarto para o dia inteiro. Isso significa que ainda temos meio dia. Você se importaria de passar aquele dia com essa garota solitária?",
"Eu adoraria também",
"Me desculpe, não era isso que eu tinha em mente. Vamos apenas manter isso como uma relação comercial. Aqui está o dinheiro.",
"Você esqueceu de trazer o dinheiro? Você é estúpido? Vou esperar aqui, pegar o dinheiro o mais rápido possível!",
"Capitão, é hora de ir. Obrigado por este dia maravilhoso. Mas você realmente deveria ir agora. Não acho que esses sonhos sejam bons. Eles devem significar alguma coisa.",
"Você não quer ir comigo?",
"Não capitão, eu tenho minha vida e você tem a sua. Tudo bem, realmente é. Eu não me importo que você vá embora, apenas me prometa que quando tudo isso acabar você vem me visitar novamente.",
"Eu vou! Isso é uma promessa!",
"Ah meu amor, você voltou. Você quer ouvir uma de minhas histórias?",
"Eu adoraria contar uma história para você. Qual história você gostaria de ouvir",
};
