string DLG_TEXT[82] = {
"Olá, ",
".",
"Prazer em conhecê-lo. Meu nome é ",
".",
"Bom te ver, ",
". Meu nome é ",
"Marc Blacque",
"Marc Blacque",
".",
"Marc Blacque",
"? Conheço uma família com esse nome - eles moram em #sFalaise de Fleur#.",
"Seu nome me parece muito familiar, mas não consigo entender por quê! Lamento não ter tempo para saber mais. Outra hora, talvez.",
"Você os conhece?! Eles estão bem?",
"Então, você está relacionado a eles. Foi bem o que pensei. Você é o filho que desapareceu há vários anos?",
"Sim, sou eu. Mas por favor, ",
", diga-me como eles são.",
"Receio ter más notícias para você. Sua irmã morreu e seu pai enlouqueceu de tristeza quando perdeu você.",
"Receio ter más notícias para você. Seu pai enlouqueceu de tristeza quando perdeu você.",
"Raquel Blacque",
"?! Não! Como isso aconteceu? Diga-me a verdade, por favor!",
"Sua irmã foi morta por um trabalhador portuário. Quanto ao seu pai, ele está vivo, mas às portas da morte.",
"Como isso pode ser? Minha família precisa muito de mim e não posso ajudá-los em nada.",
"Por que você não pode ajudá-los agora? Por que você os deixou acreditar que você estava perdido todos esses anos?",
"Essa é uma história muito longa ",
".",
"Desculpe, não tenho tempo para longas histórias. Talvez eu te veja mais tarde",
"Eu não estou indo a lugar nenhum. Conte-me sua história.",
"Há cinco anos, eu tinha meu próprio navio mercante. Não era muito grande, apenas um saveiro comum, mas ganhei um bom dinheiro entregando mercadorias por todo o arquipélago. \nEntão tive problemas - meu navio caiu nas mãos de piratas e eles me venderam como escravo. Eu trabalhava nas plantações há quase cinco anos quando finalmente consegui escapar... mas eles me pegaram. Aqueles demônios iriam me chicotear até a morte como exemplo para os outros, mas felizmente fui resgatado por #sThomas O'Reily#. \nNaturalmente, não pude enviar notícias aos meus parentes enquanto estava escravizado. E desde que #sO'Reily# me libertou, tem havido uma guerra entre #snationR# e #snationF#. \nEntão, você pode ver por que não consegui enviar um bilhete para minha família. Mas talvez você possa fazer isso por mim...",
"Posso entregar sua carta.",
"Você pode fazer melhor do que uma carta. Eu posso levar você até eles.",
"Você deve aprender a contar histórias mais curtas. Eu tenho que ir.",
"Oh, muito obrigado! Pegue, por favor - eu escrevi assim que #sThomas# me comprou, e esperava poder enviá-lo para alguém.",
"Tudo bem, entregarei esta carta à sua família assim que voltar ao #sFalaise de Fleur#.",
"Espere um segundo - o que ganho pela minha gentileza?",
"Diga ao meu pai que estou bem e logo pagarei meu resgate e voltarei para ele.",
"Até a próxima.",
"Acabei de ser libertado de anos de escravidão. Eu não tenho dinheiro nenhum!",
"Lamento ouvir isso. Adeus.",
"Não, claro que você não faria isso. Dê-me sua carta de qualquer maneira - eu a entregarei de graça.",
"Você é muito gentil, ",
", mas não posso ir para casa até pagar meu resgate de 3.000 ouros para #sThomas#. Até agora, economizei apenas 500.",
"Eu ajudaria você se pudesse pagar. Talvez na próxima vez.",
"Isso não é um problema. Pagarei o resto do dinheiro e te levarei para casa.",
"Ah, obrigado!",
"Não me agradeça até que eu te leve para casa inteiro. Agora, diga-me onde posso encontrar #sThomas#.",
"Ele não é difícil de rastrear. Ele é o dono da loja aqui na cidade.",
"Bom. Dê-me suas 500 moedas e espere por mim aqui.",
", ",
". Você conversou com #sThomas#?",
"Ainda não. Voltarei quando tiver.",
", ",
". Você conversou com #sThomas#?",
"Eu fiz. Mas, você sabe... ele se recusou a deixar você ir. Até a próxima...",
", ",
". Você conversou com #sThomas#?",
"Sim. Você está livre para ir agora. Meu navio está no porto ",
". Te espero lá.",
".",
"Entreguei a carta ao seu pai. Seu ânimo melhorou milagrosamente.",
".",
"Agora não - estou muito ocupado.",
"Posso entregar a carta para você.",
"Posso ajudá-lo a voltar para sua família.",
"Ah, obrigado pela sua ajuda ",
"!",
"Muito obrigado pela sua ajuda, ",
"! Deus lhe deu um coração bondoso e generoso.",
"Deixe-me agradecer ",
", pelo que você fez por mim.",
"Não mencione isso. Estou feliz por poder ajudar.",
"Espere! E o dinheiro que te dei?",
"Ah, sim - aqui está. Pegue.",
"Que dinheiro?",
"Sou grato a você por tirar esse grande peso do meu coração.",
"De nada, é claro. Até a próxima.",
"Posso ajudá-lo a voltar para sua família.",
"Ei, você esqueceu?! Eu te dei 500 ouro!",
"Você deve ter me confundido com outra pessoa. Contanto!",
"Capitão, eu tenho um pedido... preciso de um cargo se você estiver disposto a me aceitar...",
"A sua experiência não diminuiu o seu desejo pelo mar, então? Sim, posso oferecer-lhe um cargo de oficial.",
"Desculpe #sMarc#, acho que você deveria ficar aqui em terra firme e cuidar de sua irmã e seu pai... Eles precisam de um homem por perto para protegê-los.",
"Há cinco anos, eu tinha meu próprio navio mercante. Não era muito grande, apenas um saveiro comum, mas ganhei um bom dinheiro entregando mercadorias por todo o arquipélago. \nEntão tive problemas - meu navio caiu nas mãos de piratas e eles me venderam como escravo. Eu trabalhava nas plantações há quase cinco anos quando finalmente consegui escapar... mas eles me pegaram. Aqueles demônios iriam me chicotear até a morte como exemplo para os outros, mas felizmente fui resgatado por #sThomas O'Reily#. \nNaturalmente, não pude enviar notícias aos meus parentes enquanto estava escravizado. E desde que #sO'Reily# me libertou, muitos piratas têm atacado navios de #snation#. \nEntão, você pode ver por que não consegui enviar um bilhete para minha família...",
};
