string DLG_TEXT[25] = {
"Ei você aí! Você me parece suspeito. Quem diabos é você? Mostre-me seus papéis!",
"Quem diabos é você? Identifique-se e seja rápido!",
"Pare! Nunca te vi antes, mas você tem cara de pirata! Você pode provar que não é ninguém?",
"Eu sou ",
" , e aqui estão minha comissão e os documentos do navio para provar isso. Isso foi rápido o suficiente para o seu temperamento explosivo?",
"Ah, sim, claro, senhor! Aqui, minha identificação está nesta bolsa, logo abaixo dos 200 Gold. *PISCAR*",
"Se você não se perder imediatamente eu vou te mostrar o quão rápido eu sou... com minha lâmina!",
"Não se atreva a se dirigir a um superior dessa maneira novamente, seu mercenário insolente! Você não me conhece? Sou o Inspetor Real dos Regimentos Caribenhos de Sua Majestade e acabo de chegar com o último navio para inspecionar nossas tropas aqui! Agora não me moleste mais, ou você terá que explicar ao seu comandante por que perdi o encontro com ele!",
"Ah, sim, a imagem nas moedas identifica você como um #sgender# que gosta de guardas mal pagos, hehe. Tudo bem, vou deixar você passar, mas só desta vez. E comporte-se!",
"Claro! Quem você acha que eu sou? Um ladino? *PISCAR*",
"Eu não confio em você! ALARME! LEVANTE A MILÍCIA!",
"Boa tentativa marujo, mas comigo não cola! ALARME! Um espião! Soeem o alarme e avise a todos!",
"O que é isso? ALARME! Um pirata!",
" Parece que minhas HABILIDADES foram insuficientes para ESSA abordagem. Ou foi apenas azar? Bem,",
", Espero que minha esgrima tenha mais sucesso do que minha atuação...",
"Ah, entendo... Desculpe por ter incomodado você, #ssir#, mas devemos estar muito vigilantes aqui. A cidade está sitiada e a maioria dos soldados defende as muralhas. Então a lei e a ordem vão para os cães, espiões e saqueadores em todos os lugares.. Ora, quase todos os dias alguma loja ou taverna está sendo roubada..",
"Bem, agora que nos conhecemos, você poderia me contar um pouco sobre esta ilha.",
"Você certamente pode me dizer onde posso conseguir provisões para meu navio.",
"Com prazer, #ssir#. #sisland_Saint Martin# é dividida em uma parte holandesa em torno de #sPhilipsburg# e uma parte francesa em torno de #sMarigot#, e há lutas constantes entre as duas. \nEntão, se você tentar entrar ou sair de uma das cidades, provavelmente entrará em alguma batalha, e os sitiantes atacarão qualquer um que tentar cruzar as linhas. Para passar, você deve passar cuidadosamente pelas sentinelas e posições de artilharia. \nEmbora... também deva haver alguma passagem secreta para esta cidade, porque às vezes grupos de ataque holandeses aparecem de repente bem no meio desta cidade.",
"Grupos de invasão? Ummm.. isso explicaria por que aquela multidão ali usa uniformes holandeses..",
"O quê.. O quê? Onde?",
" ALARME! OS HOLANDESES ESTãO NA CIDADE!",
" Entrar ou não na luta...",
"Claro, loja, taverna e estaleiro estão todos perto do porto. Além do bairro portuário, a vila possui apenas algumas minas de sal e salinas no vale que conduz ao forte. \nE cuidado, há muita escória e assassinos que tentam explorar a situação tensa desta cidade sitiada.",
"Obrigado pelo aviso, e você pode me contar um pouco sobre esta ilha em geral?",

};
