string DLG_TEXT[38] = {
"Bem-vindo à minha taverna, estranho. Meu nome é ",
", e pela sua aparência, acho que você não está aqui para beber.",
"Meu nome é ",
", e você está certo. Eu estou aqui a negócios.",
"Meu nome é ",
", e definitivamente não estou interessado no que você está servindo. Eu quero algumas respostas.",
"Como posso ajudá-lo?",
"Eu preciso de informações.",
"Estou procurando contratar alguns marinheiros para minha tripulação.",
"Aponte-me para a multidão à procura de trabalho. Preciso de alguns assassinos que não façam muitas perguntas.",
"Você tem um quarto livre? Eu gostaria de ficar aqui por um tempo",
"Preciso de um quarto limpo com uma cama limpa. Nada chique.",
"Não preciso de nada no momento. Adeus.",
"Eu tenho um quarto disponível. Quanto tempo você planeja ficar?",
"Até de manhã.",
"Só até o anoitecer.",
"Vai custar 5 ouro.",
"Certo. Aqui você vai.",
"Infelizmente, parece que o luxo de dormir em uma cama de verdade está fora do meu alcance no momento. Vou passar a noite aqui na taberna",
"Não, obrigado. Se esse for o preço, vou dormir aqui na sala comunal.",
"Vou pensar sobre isso.",
"Vai custar 5 ouro.",
"Certo. Aqui você vai.",
"Infelizmente, parece que o luxo de dormir em uma cama de verdade está fora do meu alcance no momento. Vou passar a noite aqui na taberna",
"Não, obrigado. Se esse for o preço, vou dormir aqui na sala comunal.",
"Vou pensar sobre isso.",
"Não estou surpreso que você tenha vindo até mim. Um homem obtém muitas informações no meu ramo de trabalho. O que você quer saber?",
"Não tenho nenhuma pergunta para você no momento. Vamos falar sobre outra coisa.",
"Nesta hora? Todos os marinheiros estarão em casa ou desmaiados em algum lugar. \nSe você pretende contratar, espere até de manhã. Você pode alugar um quarto aqui enquanto isso.",
"Você tem um quarto vago?",
"Talvez mais tarde. Deixe-me perguntar sobre outra coisa.",
"Senhores, por favor! Pare com essa loucura imediatamente, ou terei que chamar os guardas!",
"Não se preocupe. Eu estava saindo.",
"Você conhece alguém que produza documentos?",
"Muitos, embora estejam todos em #sDouwesen#.",
"Não, estou pensando mais em alguém que não é tão oficial, não faz perguntas e provavelmente quer muito dinheiro para não perguntar.",
"Ah, entendo o que você quer dizer. Não, não há ninguém assim por aqui. Mas ouvi dizer que recentemente alguém nesse sentido quase foi pego e se refugiou no acampamento de bucaneiros em #sisland_Hispaniola#.",
"Obrigado. Vou ver se consigo encontrá-lo.",
};
