string DLG_TEXT[52] = {
"Ei, este não é lugar para um civil, está me ouvindo? Olhe ao seu redor, até pássaros e borboletas fugiram desta zona de guerra. Somente os ratos florescem aqui.. em cadáveres! Saia deste campo de matança enquanto ainda tiver todas as pernas!",
"O que está acontecendo aqui?",
"E por que VOCÊ não sai daqui, para trás das muralhas da cidade? Não seria muito mais seguro ficar ATRÁS da sua artilharia em vez de ficar aqui na zona de fogo?",
"Não há como sair daqui?",
"Sou um mensageiro do seu comandante e preciso transmitir uma mensagem importante através das linhas inimigas. Você deve abrir o caminho para mim!",
"Ratos? Ratos! Seguirei o exemplo das borboletas antes que haja outro ataque. Como aquele que está se formando ali em cima, por exemplo..",
"Você não ouviu que os holandeses nos cercam? Todas as nossas tentativas de fuga fracassaram nos tiros de canhão de seus cercos, e seus soldados e geuzen matam todos que tentam passar furtivamente por suas linhas. \nIsso é.. QUASE todo mundo: de vez em quando algum mensageiro corajoso e sortudo passa... uhh.. UGH! Está vendo aquele grupo de caça holandês reunido em seu acampamento? Parece que os holandeses pensam que VOCÊ é outro mensageiro..",
"MEU? Não, isso é um mal-entendido! Não há necessidade de me caçar, você me ouviu...",
"Você está me dizendo! Diga isso ao nosso comandante! Em sua sabedoria, ele nos ordenou que escaramuçássemos aqui: mantivesse seus batedores e mineiros longe de nossas fortificações \napoie os mensageiros que tentam se esgueirar pelas linhas, assediar o campo de cerco holandês com ataques de bater e fugir.. A.. Um ataque?? ALARME! Os holandeses atacam!",
"Umm.. Bater ou correr, essa é a questão agora...",
"Apenas um muito estreito e perigoso: você deve escapar das patrulhas holandesas e dos geuzen. Mas o pior perigo é a artilharia holandesa nas fortificações ao lado do seu acampamento. \nDê uma olhada nas posições deles... Caramba, o que está acontecendo aí.. Muita atividade.. Um ataque?? ALARME! Os holandeses atacam!",
"Será ESSA a saída daqui?",
"Oh, ótimo, mais uma tentativa de fuga suicida? Suspiro Bem, não tem jeito, ordens são ordens. Tudo bem, vamos fingir um ataque, os holandeses com certeza contra-atacarão, muitos homens bons morrerão e você PODERÁ passar se explorar a confusão geral.",
"Vamos lá, não reclame, a vida no exército é assim: 99% de espera chata e 1% de confusão sangrenta. Vamos então.",
"DLG_TEXT[14]",
"DLG_TEXT[15]",
"DLG_TEXT[16]",
"DLG_TEXT[17]",
"DLG_TEXT[18]",
"DLG_TEXT[19]",
"DLG_TEXT[20]",
"DLG_TEXT[21]",
"DLG_TEXT[22]",
"DLG_TEXT[23]",
"DLG_TEXT[24]",
"DLG_TEXT[25]",
"DLG_TEXT[26]",
"DLG_TEXT[27]",
"DLG_TEXT[28]",
"DLG_TEXT[29]",
"DLG_TEXT[30]",
"DLG_TEXT[31]",
"DLG_TEXT[32]",
"DLG_TEXT[33]",
"DLG_TEXT[34]",
"DLG_TEXT[35]",
"DLG_TEXT[36]",
"DLG_TEXT[37]",
"DLG_TEXT[38]",
"DLG_TEXT[39]",
"DLG_TEXT[40]",
"DLG_TEXT[41]",
"DLG_TEXT[42]",
"DLG_TEXT[43]",
"DLG_TEXT[44]",
"DLG_TEXT[45]",
"DLG_TEXT[46]",
"DLG_TEXT[47]",
"DLG_TEXT[48]",
"DLG_TEXT[49]",
"DLG_TEXT[50]",
"DLG_TEXT[51]",

};
