string DLG_TEXT[118] = {
"Capitão, enquanto a sua missão permanecer viva, não temos absolutamente nada para discutir. Lembre-se que valorizo ??a presteza e o tempo está se esgotando.",
"Encomende flores para sua viúva, Santos, o sino toca e o ponteiro obsceno do mostrador está na ponta do meio-dia.",
"Aqui estão os 3.000 ouro que combinamos, Capitão, e fui informado que o corpo de Bricenos está na costa da #sisland_Conceicao#.",
"Sim, pode-se dizer que ele está todo acabado.",
"Obrigado, mas esta experiência convenceu-me de que a maré está a acabar na nossa associação,... e estou navegando nela.",
"Ah, capitão! Muito bem - você certamente ganhou seus 4.500 de ouro. Espero que tudo tenha corrido bem?",
"Sim, ",
"Geffrey Bampfylde",
"s contas estão acertadas. Estou interessado em tornar o saldo da minha própria conta um pouco mais saudável. Você tem outra tarefa?",
"Acertar essa conta me deixou desequilibrado, não tenho gosto para isso e, se para você não importa, vou voltar atrás na conta. Até a próxima.",
"Capitão, você nunca deixa de me surpreender! Para ser honesto, eu não tinha certeza se você conseguiria lidar com isso. ",
"Pepin Bertillon",
". Por favor, aceite minhas desculpas por duvidar de você. Junto com seus 7.000 de ouro, conforme combinado.",
"O que posso dizer? Ele tentou contrabandear minha lâmina em sua caixa torácica e foi pego com seu contrabando.",
"Infelizmente, esta experiência convenceu-me de que já não posso contrabandear este tipo de trabalho para além da minha consciência. Nossa associação terminou.",
"Capitão, realmente você superou todas as expectativas. Aqui estão seus 10.000 de ouro e me diga como você conseguiu derrotar ",
"Amerigo Vieira",
"? Ele escapou dos meus melhores homens durante vários anos!",
"Prefiro não discutir esta tarefa específica com você, Santos.",
"Não importa como eu fiz isso. Está feito. E já estou farto desse tipo de trabalho.",
"Capitão, você me fez um grande favor ao me livrar do italiano! Infelizmente, você também aprendeu demais. Você terá que levar esse conhecimento para a morte prematura. Sinto muito, capitão.",
"Então, ",
"Vito Leone",
" estava certo sobre sua traição! Eu deveria ter acreditado na palavra dele. Por favor, expresse minhas desculpas a ele quando você o vir no Inferno!",
"Capitão, o que você está fazendo aqui?!",
"Descobri que você pode aprender muito com velhos ditados e somente agora entendi o significado; não atire no mensageiro vem à mente, como Don ",
"Vito Leone",
" me contou muitas coisas interessantes sobre a maneira como você faz negócios. Em particular, ele me disse que seus parceiros têm tendência a morrer jovens...",
"Ah, meu querido capitão ",
"! Eu queria saber quando você finalmente nos agraciaria com sua presença. Você certamente não estava com muita pressa para terminar o trabalho, estava?",
"Você tem vantagem sobre mim, senhor, pois parece ter consciência de minhas intenções antes de eu expressá-las a você.",
"Pode-se dizer que faço questão de saber o que acontece a meu respeito e das partes envolvidas. ",
"Então cumprirei a minha comissão e tentarei dissuadi-lo de irritar ainda mais as partes a que se refere. ",
"Ah, ousadia, admiro isso, mas certamente não pode ter passado despercebido ao seu conhecimento de que tenho sete homens me atendendo, que, como eu, não estão convencidos do seu esforço.",
"Enquanto eu, por outro lado, começo a me sentir persuadido pela força da sua lógica.",
"Oh, estes são seus homens, não é? Eu temia estar interrompendo uma reunião de família,... a família Suína.",
"Ousadia e discrição, você me domina, #ssir#. Eu tinha ouvido rumores, mas estou encantado em descobrir por mim mesmo o que há de verdadeiro neles. ",
"Ambroz Bricenos",
" armou para você, capitão, por favor, deixe sua discrição guiar seu valor inquestionável em sua próxima resposta. Meu tempo é precioso e você já desperdiçou dez minutos dele.",
"Então, para ser discreto, desejo-lhe um bom dia e peço desculpas por qualquer perturbação que causei. Confio que não terei que lutar para sair?",
"(Olha o relógio) Na verdade, já disperdicei quinze minutos do seu tempo e temo não sobrou nenhum. Vamos dançar?!",
"Não será necessário, capitão, não me ofendo - a gente se acostuma com esse tipo de coisa no meu ramo de trabalho. Na verdade, se você estiver interessado, eu poderia propor um trabalho verdadeiramente lucrativo...",
"O que posso dizer? Considere-me um público cativo.",
"Obrigado pela oferta, mas este encontro desviou meu interesse deste tipo de trabalho.",
"As condições são muito simples. Primeiro: você tem três meses para terminar o trabalho - não mais. Se o trabalho for feito dentro do prazo, a recompensa estará esperando por você pelo tempo que você levar para vir buscá-la.",
"...",
"Segundo: você nunca deixa uma testemunha. Nenhuma exceção será tolerada.",
"...",
"E terceiro: ao receber sua recompensa, você aceita uma nova missão imediatamente. Você pode recusar, mas não permitirei vacilações.",
"...",
"Essas são as condições. Se você violar apenas um deles - ou se recusar a aceitar um emprego - não trabalharemos mais juntos. Na verdade, seria imprudente falar comigo novamente.",
"Posso trabalhar nessas condições. Qual seria meu primeiro trabalho?",
"Eu vejo. Obrigado pela oferta, mas não sou um assassino.",
"Tenho certeza que você já imaginou isso, elimine ",
"Ambroz Bricenos",
"  ",
"Ambroz Bricenos",
". Isso provará sua lealdade a mim e lhe renderá 3.000 ouro.",
"Içar seu próprio petardo, hein? A ironia me atrai, eu farei isso",
"Hmmm, por mais tentadora que seja sua oferta, devo recusá-la.",
"Perfeito. Não se esqueça, você tem exatamente três meses para fazer isso.",
"Eu lembro.",
"Então não vou atrasá-lo mais, capitão. E se você decidir fazer uma visita ",
"Ambroz Bricenos",
", bem - não se preocupe. Ele não será encontrado,...vivo.",
"Entendido. Adeus.",
"Que pena - foi um prazer trabalhar com você. Adeus, meu querido capitão.",
"Adeus.",
"Você não deveria ter dito isso, capitão. Simplesmente não posso tolerar grosseria. Prepare-se para morrer, meu amigo!",
"Para ser seu amigo eu teria que ser estúpido!",
"Meus parabéns. Agora, seu próximo alvo é um banqueiro comercial chamado ",
"Geffrey Bampfylde",
"Geffrey Bampfylde",
". A casa dele fica em #sGreenford#, do outro lado da rua e logo à esquerda da taverna. A taxa para esta tarefa é de 4.500 ouro.",
"Um banqueiro, hein? Hora de uma execução hipotecária e uma retirada.",
"Já perdi o interesse, matar um banqueiro leva-o à falência. Até a próxima.",
"Não tenho certeza sobre qual aspecto da sua personalidade aprecio mais: sua eficiência implacável ou sua inteligência mórbida. Atenda-me, pois você precisará de toda a sua inteligência para esta próxima tarefa.",
"Parece intrigante, conte-me sobre isso.",
"Parece mais problema do que vale a pena. Estou fora do jogo.",
"O alvo é um contrabandista chamado ",
"Pepin Bertillon",
"Pepin Bertillon",
". Tem sido muito difícil rastreá-lo, só sabemos que seu navio visita frequentemente #sisland_Quebradas Costillas#.",
"A ilha pirata, hein? Conveniente - sem soldados para lidar...",
"Parece mais problema do que vale a pena. Estou fora do jogo.",
"Não há soldados, é verdade. Mas existem assassinos, e muitos deles. Eles são estúpidos, mas armados e perigosos. Então ",
"Pepin Bertillon",
" não é provável que apareça lá sem guarda-costas. Considerando o perigo, a recompensa por este trabalho é 7.000 ouro.",
"Por esse tipo de dinheiro, você pode considerar isso feito.",
"Parece mais problema do que vale a pena. Estou fora do jogo.",
"Considerando a extensão de suas habilidades, tenho certeza de que você está subestimando suas realizações, porém, o próximo trabalho será bastante difícil, até mesmo para você.",
"Eu dou conta disso.",
"Nesse caso, eu passo.",
"Espero que consiga, porque desta vez o alvo é meu inimigo mais pessoal. O nome dele é ",
"Amerigo Vieira",
"Amerigo Vieira",
". Ele mora na #sisland_Conceicao#, em uma casa à direita da residência do governador, no andar superior.",
"E quanto vale para você esse trabalho perigoso?",
"Parece mais problema do que vale a pena. Estou fora do jogo.",
"10.000 ouro. Mas lembre-se: ele é o melhor espadachim do arquipélago. Conto com você, capitão. ",
"Amerigo Vieira",
" me traiu, e não posso ficar tranquilo enquanto ele estiver vivo.",
"Se ele for algum tipo de espadachim, logo o resolverei.",
"Parece mais problema do que vale a pena. Estou fora do jogo.",
"Não tenho certeza se aprecio seu tom, apesar de suas habilidades invejáveis, porém, tenho uma nova tarefa que sinto que só você seria capaz de realizar.",
"De alguma forma, tive a sensação de que você diria algo nesse sentido.",
"Já estou farto dos seus trabalhos. De agora em diante, faça você mesmo.",
"Há pouco tempo, um mensageiro do continente chegou ao arquipélago. Ele deve morrer, e o mais rápido possível. A notícia que ele traz é muito perigosa.",
"Talvez o velho ditado de que nenhuma notícia é uma boa notícia soe verdadeiro. Quanto você está disposto a pagar para descobrir?",
"Já estou farto dos seus trabalhos. Estou fora desta raquete.",
"Verdadeiramente uma soma real - 20.000 ouro. Este trabalho é muito importante para mim.",
"De repente, tornou-se muito importante para mim também. Como faço para encontrar essa pessoa?",
"Cansei de ouvir sua voz. Eu desisto!",
"Isso pode ser um problema. Não sabemos sua localização exata, nem mesmo seu nome. Sabemos apenas que ele é um velho italiano e que está em algum lugar da #sisland_Conceicao#. Então você terá que ir lá e encontrá-lo você mesmo.",
"Não há muito o que dizer, mas quantos lugares existem na #sisland_Conceicao# para se esconder?",
"Parece mais problema do que vale a pena. Estou fora deste jogo.",
"Eu deveria saber que você teria uma conversinha com Leone em vez de simplesmente matá-lo! Eu deveria ter feito o trabalho sozinho. Bem, ele receberá o que merece em breve. E você receberá o seu agora mesmo!",
"Você está delirando, mas ficarei feliz em colocá-lo de volta no caminho certo e estreito. En garde!",

};
