string DLG_TEXT[22] = {
".",
".",
"Bem, senhores, isso nos deixa tempo para uma partida de whist. Você aceitaria o acordo, Sr. Longley?",
"Sim, sim, senhor.",
"Sr. Longley, gostaria de se juntar a mim para uma caminhada noturna e nadar?",
"Nadar, senhor?",
"Sim. O outro lado desse ponto é Punta de Maisi. Fui informado pelo 'almirante' Hernandez que o caminho da costa é patrulhado pelos espanhóis, mas a esta hora da noite, eles provavelmente não se aventurarão longe de #sHavana#.",
"Estamos nadando em terra, senhor?",
"Não, Sr. Longley, pegaremos o barco como sempre. Depois podemos caminhar até Punta de Maisi. Não deveria estar longe. Mas não podemos levar o barco até lá, então nadaremos até a 'Natividad'.",
"Para que lado vamos, senhor?",
"Punta de Maisi não pode estar longe. Pelos meus cálculos, se formos um pouco para o interior e depois virarmos à esquerda, chegaremos lá em breve. Se virmos alguma tropa espanhola, então seguimos pelo caminho errado.",
"Acorde-os, Sr. Longley!",
"Que diabo é isso, Sr. ",
"Não tenho certeza, senhor.",
"Senhor. ",
", Lady Wellesley se mudará para minha cabana.",
"Esteja um pouco lotado, senhor!",
"Leve minhas coisas para a cabine do Sr. Bush, leve as dele para a sala dos oficiais.",
"Eu... voltei para você, mãe... não foi? Eu te prometi que voltaria",
"Você está com saudades de mim?",
"Beije-me como você costumava fazer, mãe. Quando eu era muito pequeno. Você não poderia? Só uma vez.",
"Isso mesmo, mãe. Boa noite. <Morre>",
}
