string DLG_TEXT[28] = {
"Diga-me, ",
"? Não é aquele o 'Cleópatra' perdido entre as ondas além-mar?",
"Não senhor. Esse é o '",
", Meu navio.",
"Já viste com o Cleópatra em alguma de tuas viagens além mar?",
"Não, nunca vi nenhum navio com esse nome pelos mares.",
"Isso é ruim. Se algum dia você o vir, por favor diga ao seu capitão - meu filho - que estou esperando por ele.",
"Se eu tiver a oportunidade, certamente o farei. Adeus, capitão.",
"Com licença, ",
". Você conheceu meu filho, capitão do 'Cleópatra' em suas viagens?",
"Encontrei-o senhor. E tenho comigo esta carta do seu filho para você.",
"Não apenas conheci seu filho, senhor - trouxe-o comigo até aqui.",
"Seu filho? Aquele idiota que nem consegue cuidar de si mesmo? Eu o trouxe comigo. Ele chegará em um minuto, se não se perder no caminho.",
"Não senhor, não conheci seu filho, senhor.",
"Você já me perguntou isso muitas vezes, meu velho - e a resposta ainda é não.",
"Uma carta?! De #sMarc#? Você não mentiria para um velho marinheiro, não é?",
"Eu poderia. Mas não desta vez. Aqui está a carta. Espero que você veja seu filho muito em breve.",
"#sMarc#? Pode ser?! Os céus ouviram minhas orações e trouxeram você de volta para mim!",
"Tudo bem. Não vou incomodá-lo mais. Até a próxima!",
"Seus pais podem estar orgulhosos de você pelo que você fez ",
".",
"Obrigado, senhor. Mas agora tenho que ir - tenho muito que fazer",
"Olá meu bom capitão, espero que você esteja bem?",
"Sim #sMilon#, esquivando-se e tecendo... esquivando-se e tecendo. Como vai sua família agora que vocês estão todos juntos de novo?",
"#sRachel# está bem. #sMarc# agora está se sentindo deprimido porque precisa de trabalho.",
"Que bom saber que #sRachel# está bem. #sMarc# é um bom oficial; Talvez eu possa usá-lo. Onde ele está?",
"#sMarc# pode ser encontrado na loja - ele está tentando encontrar trabalho com um comerciante.",
"Bom, eu tenho que ir agora.",

};
