string DLG_TEXT[17] = {
"Bem-vindo ao meu bordel! Meu nome é ",
" e eu administro este estabelecimento. Existe algo em que eu possa ajudá-lo?",
"Na verdade, sim, estou querendo pegar uma vadia.",
"Não, este é o lugar mais sujo do Caribe! Bem, hum, fiquei permanentemente incapacitado, se é que você me entende. Veja, eu encontrei minha incapacitação nas mãos de um tubarão. Acredito que fosse um Great White, sim. De qualquer forma, não há nada aqui para mim, porque 'isso' foi substituído por uma estaca de madeira.",
"Hum, você poderia me contar um pouco sobre esse lugar, senhora?",
"Bom, quando essa cidade foi formada eu comecei esse lugarzinho, desde então ele cresceu e se tornou o melhor Bordel de todo o arquipélago, era só isso que você queria saber?",
"Bem, não, eu só estava curioso, vamos falar de assuntos mais 'importantes'...",
"Sim, obrigado pela informação, com certeza nos veremos por aí.",
"Tenho algumas garotas abertas, você ainda está interessado?",
"Sim, senhora, acredito que sim",
"Sim, senhora, acredito que sim",
"Então você quer uma garota, hein? bem, isso vai custar 50 ouro. Talvez um pouco íngreme, mas não é negociável.",
"Esse é um preço perfeito, estou dentro!",
"Me desculpe, não terei condições de pagar por isso...",
"Então você quer uma garota, hein? bem, isso vai custar 50 ouro. Talvez um pouco íngreme, mas não é negociável.",
"Esse é um preço perfeito, estou dentro!",
"Me desculpe, não terei condições de pagar por isso...",
};
