string DLG_TEXT[89] = {
"Torta Iesu Domine..Dona aeis réquiem. BATIDO. (O monge se esmurra com um livro pesado em um ato de arrependimento..) Eheh? Não interrompa minha procissão de um homem só! ... ",
"Por favor, me perdoe, mas você não se parece exatamente com o que um monge comum deveria ser...",
"Sinto muito padre, por favor aceite minhas desculpas e estes 100 ouro para os pobres do arquipélago.",
"Hmm, como deveria ser um monge?",
"Um pouco menos autoconfiante, um pouco mais suplicante e definitivamente muito menos perigoso.",
"Não sei, mas definitivamente... bem, pensei que você fosse um saco ambulante de batatas, sabe, com aquela capa boba parecida com um saco e tudo. Sua cabeça parecia uma grande batata podre e atingida pelo escorbuto",
"Você não é um monge! Você é um espião! Talvez até um maluco disfarçado de saco de batatas! Você não deveria estar em Bedlam?",
"Foi bom conversar com você, mas preciso ir agora. Talvez possamos nos encontrar novamente quando você for um pouco mais específico...",
"Adeus, Padre, ou seja lá o que for...",
"Ah, você de novo, você tem outra resposta para mim? Como estou?",
"Eu não sei o que você é, mas você não é como os outros monges, eu sei, simplesmente não consigo me livrar da sensação de que você é muito idiota.",
"Espião? Espião! Sou monge, vivo piedosamente, obedeço aos mais velhos, faço as minhas orações e sou quase completamente casto. Por favor, cale a boca %&$#s_hash_#@, seu pirata %&$#s_hash_#@!!!",
"Ok, acalme-se. Eu não quero ter nenhum problema. Estou indo embora.",
"Ei, você está desarmado. Você não deveria ter um pouco mais de cuidado ao falar dessa maneira com um homem armado?",
"Ah, você de novo, não aprendeu a lição?",
"Por favor, aceite minhas desculpas. Foi muito gentil me deixar viver. Nenhum espião teria feito isso de bom grado.",
"OK. Aqui estão suas armas. Vou fazer minha pergunta novamente: como deve ser a aparência de um monge?",
"Quem te disse que estou desarmado?",
"Não consigo ver nenhuma arma!",
"E agora não consigo mais ver sua arma. Acho que esta é uma lição que você precisa aprender: nunca julgue um homem apenas com base nas aparências.",
"Ai... como você fez isso? Onde estão minhas armas?",
"Interessante. Poderia ser? Talvez. Agora vou te fazer uma pergunta: O que é mais forte, uma espada fina ou uma pena?",
"A espada. Já tentou lutar contra uma espada balançando em torno de uma pena?",
"A pena, não numa luta, mas a longo prazo poderia matar mais homens do que todas as espadas juntas.",
"Nem, depende da mente que domina a espada ou a pena!",
"Parabéns! Tenho certeza que você vencerá muitas lutas com sua espada, mas finalmente perderá, pois quem vive pela espada morrerá pela espada.",
"Eu não entendo do que você está falando. Estou indo embora...",
"O que? Você passou algum tempo pensando na minha pergunta novamente? OK! Vamos ouvir a sua resposta: O que é mais forte, uma espada fina ou uma pena?",
"Nada mal, mas por que você está carregando uma espada e não uma pena? Não tenho certeza se esta é realmente sua resposta.",
"Eu também quero sobreviver no curto prazo. Adeus... seu maldito piedoso saco de batatas.",
"Você está agindo com sabedoria, não é? Você pode provar que é realmente tão inteligente?",
"Espero que sim. O que você tem em mente?",
"Ofereço-vos estas três relíquias, cada uma com poderes especiais, mas todas com um grande fardo... ",
"Por favor, seja um pouco mais específico!",
"Se você pegar um, não poderá sair do arquipélago - e poderá voltar e continuar de onde parou - a menos que tenha encontrado santuário em terreno consagrado ou até que o entregue a um membro específico da minha ordem.",
"E os poderes?",
"Veremos se você é tão inteligente quanto pode ser! É você quem escolhe! Ah, e estou sem granadas de mão sagradas, então não se preocupe em perguntar.",
"Vou pegar a cruz que aumentará minhas habilidades de combate.",
"Estou fraco demais para ser um verdadeiro espadachim, vou pegar aquele que vai dobrar minha saúde.",
"A terceira cruz me ajudará no comércio e no comércio, seja legítimo ou ilícito? Eu preciso disso!",
"O fardo é muito alto e eu estava procurando uma granada de mão sagrada. Aparentemente você não tem nenhum.",
"Se você sentir necessidade de sair do arquipélago - e poder retomar de onde parou, quando voltar, devolva a relíquia ao membro da minha ordem ",
"Tenho certeza que o encontrarei quando quiser sair do arquipélago. Obrigado e adeus!",
"Volte se mudar de ideia. OU se você se sentir drasticamente sobrecarregado, você pode tentar destruí-lo no fogo de uma certa Montanha da Perdição, isso funcionaria. ",
"Você é muito gentil comigo. Adeus!",
"É você de novo. Você quer aceitar o desafio? Veremos se você é a mente que domina os poderes com sabedoria! É você quem escolhe!",
"Meu pedido me contou sobre você. Quer aceitar o desafio agora? Veremos se você é a mente que domina os poderes com sabedoria! É você quem escolhe!",
"Sinto a aura do fardo que você carrega. É difícil carregar uma de nossas relíquias, não é? Você deseja abrir mão da cruz e poder sair do arquipélago e ainda assim retomar de onde parou, quando voltar? ",
"Sim, já é hora de ir, mas... VOLTAREI!!!",
"Não, continuarei carregando o fardo... e aproveitando seus poderes também!",
"Sinto a aura do fardo que você carrega. Você quer se livrar disso? Você tem que encontrar o membro da minha ordem... ",
"Espero sobreviver até lá!",
"Se você quiser aceitar o desafio novamente, fale comigo ou com outro membro da minha ordem.",
"Não cabe a nós decidir como será o futuro! Talvez nos encontremos novamente, talvez não.",
"Aceito o desafio novamente, quando voltar!",
"O fardo é demais para mim, não acho que nos encontraremos novamente. Adeus!",
"Que surpresa! Que surpresa! Se não for Capitão ",
"Eu conheço essa voz! Lorde Beckett... é você, não é?",
"Fale baixo. Muitos ouvidos neste lugar. Sente-se, sente-se e conversaremos",
"Tudo bem, mas você me deve uma explicação, eu acho. Quem é você? Conheci o verdadeiro Lord Beckett, e na residência do Governador, então? ...",
"É sim. Mas estou tendo um grande problema em saber quem você é.",
"Em primeiro lugar, sou Lord Beckett, ou um deles... Lord Cuthbert Ulysses Beckett.",
"Cuthberto! Você disse que seu nome era Cutler!",
"Esse é meu irmão, Lord Cutler Oswald Beckett.",
"Isso está indo muito devagar, meu senhor... Suponho que deveria chamá-lo assim de novo... O que está acontecendo aqui?",
"Tudo bem, tudo bem capitão ",
", eu devo isso a você. Meu irmão e eu somos os filhos gêmeos mais novos do duque de Middlesex. Nosso irmão mais velho herdará o título ducal, então meu irmão e eu buscamos fortuna no comércio.",
"Há mais de você! Não tenho certeza se devemos continuar esta conversa.",
"Paciência, paciência meu caro amigo. Somos apenas Culter e eu nestas águas. Ambos trabalhávamos para a Honorável Companhia das Índias Orientais e as coisas correram bem até ouvirmos uma história sobre o Baú de Cortez. Isso virou a cabeça do meu irmão e ele está decidido a encontrá-lo.",
"O que há de errado com isso. Um local de caça ao tesouro é o que nos interessa, certamente?",
"Isso se tornou desgastante para ele, a ponto de ele remover qualquer um que ele acha que possa estar se aproximando dele... inclusive eu. E estou chegando perto de algumas das informações que encontrei.",
"Você quer dizer os documentos que estou conseguindo para você, não é? Eles têm algo a ver com isso, não é?",
"Você é muito inteligente, capitão, e, aliás, foi por isso que o escolhi em primeiro lugar. Eu envolvi você para tentar frustrar os planos do meu irmão e, sim, os documentos são partes de um mapa para o tesouro. Quando concluído, a localização é revelada.",
"E há quatro partes... certo, meu senhor?",
"Tão afiado como sempre, capitão. Sim, quatro partes. Acredito que você tem uma parte e eu tenho outra, então estamos na metade do caminho. Vou lhe dar a minha parte, aqui está, acredito que os homens do meu irmão estão no meu encalço, daí o disfarce, então não é seguro comigo. Você pode me devolver os dois quando nos encontrarmos novamente. Mantenha eles salvos.",
"Encontre-se novamente, meu senhor, e onde e quando será isso?",
"Não se preocupe, eu vou te encontrar. Tenho certeza de que você tem outras coisas que precisa fazer. Então vou me despedir de você por enquanto, capitão, espero que alguém me encontre aqui. Mantenha os documentos seguros. Entretanto vou retomar o meu disfarce.",
"Er... Sim, senhor... Adeus por enquanto.",
"Assim está melhor, podemos ver alguém se aproximando agora.",
"Pode ser, mas ainda preciso dessa explicação.",
"Nos encontramos novamente, senhor. Sua voz está se tornando bastante familiar. O que você está fazendo nesta ilha?",
"Vim colecionar alguns ídolos, mas acredito que você chegou antes de mim. Então pensei em sentar aqui e ver quem entrava e saía",
"Ah! A inteligência de Vossa Senhoria está tão atualizada como sempre.",
"De fato, de fato. Mas direto ao ponto. É hora de provar nossa confiança mútua. Eu sei que meu irmão enviou você para pegar os ídolos e preciso estragar os planos dele. Então, capitão, deixe-me dar uma olhada na carga de ídolos, só preciso saber o que há lá antes que ele o faça e isso vai tirar o fôlego de suas velas.",
"Eu não sei, senhor. Isso parece muito arriscado... para mim.",
"Como assim? Como assim? Ele nunca saberá que alguém apenas 'olhou' para ele. Só tenho a sensação de que uma das caixas está vazia e quero ter certeza.",
"Muito bem, senhor, confiarei em você. Dê uma olhada.",
"Obrigado capitão. Obrigado. Isso certamente alterará seus planos. Pegue esse dinheiro para cobrir seu inconveniente. Você deveria ir agora, mas não tenha medo de nos encontrarmos novamente.",
"Tenho certeza que sim, senhor. Tenho certeza que iremos.",

};
