string DLG_TEXT[46] = {
"Ei, hoje está um tempo quente na cidade velha, não é?!",
"Sim",
"O que você quer? Se você não vai participar da emoção, não a interrompa.",
"Você acha isso divertido, sua fera escamosa?",
"Excitação? Parece que você está prestes a queimar alguém.",
"Então você decidiu não interferir? Essa é uma escolha sábia. Agora sai daqui!",
"Você está procurando problemas?",
"Eu disse para sair, a menos que você queira se juntar ao velho!",
"Olha, todo mundo viu você me bater primeiro",
"E daí? Você acha que alguém vai correr em seu auxílio? Vejo muitos amigos meus aqui - não vejo nenhum dos seus, estranho.",
"Não precisarei de amigos quando os soldados aparecerem.",
"Sim? Onde eles estão agora? O que te faz pensar que eles te ajudariam?",
"O mais importante é que eles não nos incomodem.",
"Claro, junte-se a nós! Onde mais você pode ver um show desses?",
"Mostrar? Você chama isso de show quando um homem está sendo consumido pelas chamas?",
"Ei, é melhor do que trabalhar no porto!",
"Sim, posso dizer que vocês estão morrendo de tédio.",
"Você sabe, é graças a vocês que esta colônia é considerada a mais bárbara de todo o arquipélago. Governador ",
"Robert Christopher Silehard",
" ele mesmo reclamou comigo sobre isso muitas vezes.",
"Certo. Vocês, bestas de carga sem cérebro, não conseguem inventar nenhum outro entretenimento para si mesmos.",
"Talvez eu possa lhe oferecer algo mais emocionante?",
"Você não prefere tomar uma bebida... ou seis? Eu estou comprando.",
"Nenhum homem de verdade ficaria parado vendo um velho cavalheiro ser queimado vivo.",
"O próprio governador? Você está brincando!",
"Pareço que estou brincando? Ele me enviou aqui para ver o quão ruim as coisas estavam. Ele não vai se importar com o meu relatório.",
"Você está mentindo. Você consegue adivinhar o que fazemos com os mentirosos por aqui? Suma daqui.",
"Você consegue adivinhar o que eu faço com os homens que falam assim comigo, escória?",
"Tudo bem, tudo bem! Eu não quero problemas.",
"Relatório? Não me faça rir! Todo o arquipélago está nadando na pirataria!",
"Pode ser, mas os velhos não estão ardendo em todas as colônias. Você informou a Igreja sobre seus planos de queimar este homem?",
"Não há necessidade. Acredito que a Igreja aprovará nossas ações.",
"Bem bem. Qual você disse que era seu nome?",
"Você está estragando tudo, sabia disso? Basta pegar o velho e ir!",
"Agora estamos nos entendendo.",
"Você sabe quanto meus amigos e eu podemos beber. O que faz você pensar que pode pagar por todos nós?",
"Tenho 2.000 de ouro que dizem que posso. Todos vocês poderiam beber até ficar inconscientes com esse tipo de dinheiro.",
"Não, suponho que não tenha tanto dinheiro, agora que você mencionou. Mas você pode realmente ver essa execução como apenas um pouco de diversão?",
"Parece bom para mim! Mas talvez devêssemos queimar o velho primeiro...",
"Deixe-o por mim. Eu cuidarei dele.",
"Quem você chamou de fera?!",
"Então você é surdo além de estúpido? Eu te chamei de fera. Só um animal poderia achar divertido um espetáculo como este.",
"O que você está fazendo aqui? Você quer problemas? Bem, isso pode ser arranjado com bastante facilidade!",
"O que? Você se esconderia atrás de seus amigos, não é? Eu deveria ter esperado isso do tipo de covarde que queimaria um velho só de rir.",
"Você acha que tenho medo de você? Ficarei feliz em corrigir esse erro!",
"Vamos lá, animal!",

};
