string DLG_TEXT[53] = {
"Sim? Como posso ajudá-lo?",
"Posso visitar a Capela?",
"Eu ouvi sobre a Cripta. Está aberto para visitantes?",
"Posso entrar no Claustro?",
"Deveria haver um antigo círculo de pedras aqui. Isso é verdade?",
"Estou procurando um túmulo. Você pode me mostrar o caminho para o Cemitério?",
"Quero ver a famosa Biblioteca - Onde encontro?",
"Ah, estou apenas olhando em volta",
"Claro - mas lembre-se que não é um museu.",
"Obrigado pai.",
"Não, ainda não está aberto. Talvez no futuro. Está reservado a Bartolomeu o Português.",
"Eu vejo.",
"Sim, por favor visite o pátio interno. A varanda no andar de cima também está aberta.",
"Obrigado pai.",
"Sim, é verdade. Este local era sagrado (de alguma forma) antes mesmo da construção do Claustro. Você o encontrará no outro extremo do jardim.",
"Isso será interessante.",
"Claro. Vá para o pátio interno e de lá a porta verde leva ao Cemitério.",
"Obrigado pai, entendi.",
"Você encontrará a porta azul da Biblioteca no pátio interno.",
"A Biblioteca concentra-se na ciência e está aberta apenas para engenheiros.",
"Espero que você aproveite sua visita aqui então.",
"Os licores aqui produzidos são conhecidos em todo o mundo. Posso ver a Destilaria?",
"Claro. Você o encontrará no jardim perto da construção da cripta. Mas testar os produtos não é permitido aqui...",
"Eu vejo. Obrigado pai.",
"Huh?",
"Não se atreva a pegar nenhum livro da minha biblioteca!!",
"(engole em seco - É o bibliotecário?!) Claro que não, senhor.",
"Desculpe, mas por acaso você é engenheiro, capitão?",
"De fato, eu sou. Ao seu serviço, Padre.",
"Você conhece a pesquisadora Sakharine?",
"Sim, tenho - ele é um conhecido profissional meu.",
"Sinto muito, mas - eh, você pode provar isso?",
"O que!? Na verdade posso, tenho esta carta de Ivan Sakharine. Veja por si mesmo.",
"Muito bom. O inventor me pediu para entregar este Mapa da Biblioteca a você em troca de sua Carta.",
"Ok... Preciso de um mapa para me orientar na Biblioteca?",
"Acho que é uma ideia muito boa, capitão.",
"É assim mesmo. O que mais você pode me dizer sobre a Biblioteca, Padre.",
"Se me permite dar um conselho  há muitos livros valiosos aqui, mas por favor não tente roubar nenhum deles. O Bibliotecário não deve ser enganado!",
"(Hmm, isso é uma ideia) Claro que não, vou apenas procurar meu amigo. (e não tenho muito medo de um bibliotecário!)",
"Então... você pegou TODOS os livros valiosos. Lembre-se que eu te avisei!",
"Ehh... (isso não parece nada bom)",
"Afinal, é bastante impressionante, então vou lhe dar uma recompensa.",
"Ok... (ele não vai me matar?)",
"Você pode ficar com todos os livros.",
"Obrigado. (existe um mas...?)",
"Você também é imortal a partir de agora!",
"É realmente verdade? (isso está muito além de qualquer coisa que eu poderia ter imaginado)",
"Sim, isso vem com sua nova tarefa - ou devo dizer profissão.",
"Huh, o que pode ser isso? (Eu tenho um mau pressentimento)",
"A única pessoa que pode levar todos esses livros é a Bibliotecária.",
"Sim..? (aqui vem)",
"Parabéns, você é o novo bibliotecário!",
"---",

};
