string DLG_TEXT[23] = {
"Precisa de algo?",
"Não senhor, estou de sáida.",
"Sim, #ssir#?",
"Você é Octave Fabre?",
"Eu sou de fato.",
"Tenho uma pergunta a fazer a você. Dizem que você sabe muito sobre este arquipélago.",
"Isso é verdade. Passei a maior parte da minha vida navegando pelos sete mares e adquiri muito conhecimento dessa forma. Mesmo no que diz respeito a alguns aspectos, digamos, mais misteriosos do mar.",
"Excelente. É exatamente disso que preciso! Um pescador em #sPhilipsburg# afirma ter visto um navio sendo atacado por um... polvo gigante.",
"Um polvo gigante, você disse? Isso foi durante uma tempestade, por acaso? E depois um misterioso navio pirata pareceu emergir do próprio mar?",
"Sim, isso mesmo! Como você sabia?",
"As histórias deste mítico monstro marinho sempre foram contadas entre os marinheiros. Eu era jovem e tolo e não acreditei nelas. Até que um dia fomos apanhados por uma tempestade assim.",
"No entanto, você... está sentado aqui vivo? O que aconteceu?",
"Nós tivemos sorte. O Kraken estava atrás de outro navio e por acaso estávamos por perto. Mudamos nossa direção para longe da cena o mais rápido que pudemos. Depois disso, passei a maior parte da minha vida tentando descobrir o que eu tinha visto.",
"Então, o que você descobriu?",
"Diz-se que este polvo gigante é o animal de estimação de um homem chamado Davy Jones. Eu realmente não deveria chamá-lo de homem. Todos os relatos que ouvi o descrevem como sendo tão cruel quanto seu monstro com um rosto horrível demais para ser descrito.",
"Então é ele quem está por trás de todos esses acontecimentos? Então é ele quem devo tentar encontrar.",
"Saiba no que você está se metendo. Isso não é algo para ser considerado levianamente. Se Davy Jones decidir matar você, não há como escapar.",
"Obrigado pelo aviso. Tomarei cuidado.",
"(Há alguns destroços e um pequeno baú na areia próximo ao corpo)",
"Vamos dar uma olhada no que há neste baú.",
"(Há alguns papéis dentro)",
": 'O navio está afundando. Estamos sendo arrastados para o fundo do mar. Agora nunca encontraremos a senhorita Shaw. Meu governador ficará muito desapontado. - Capitão Thomas Boulden Thompson",
": 'O navio está afundando. Estamos sendo arrastados para o fundo do mar. Agora nunca encontraremos Miss le Moigne. Meu governador ficará muito desapontado. - Capitão Fabion le George",

};
