string DLG_TEXT[128] = {
"É bom ver uma pessoa neste buraco esquecido por Deus que se veste bem. Meu nome é ",
", e eu sou o dono deste estabelecimento.",
"Você fala sobre como estou vestido, mas não consegue nem manter esse chiqueiro limpo? Bem, vejo que você é um bom taverneiro.",
"Claro, como você diz ",
". Como posso ajudá-lo?",
"Preciso contratar alguns marinheiros para minha tripulação.",
"Minha tripulação está desgastada pela batalha e quero contratar alguns marinheiros jovens e inexperientes que estão procurando emprego.",
"Tenho uma proposta de negócio para você.",
"Você tem um quarto livre? Eu gostaria de ficar aqui por algum tempo",
"Você tem um quarto livre neste chiqueiro?",
"Não tenho mais perguntas para você. Bye Bye.",
"Eu descobri tudo o que queria saber. Até a próxima.",
"Então vamos falar de negócios. Então o que você quer?",
"Obrigado, não. Preciso do navegador de Reims.",
"Estou procurando uma pessoa. É uma garota cujo nome é ",
"Danielle",
"Danielle",
", talvez você saiba algo sobre ela?",
"Gostaria de confessar os meus pecados, mas dizem que o próprio padre local está enterrado em pecados. Isso é verdade?",
"Você sabe, parece que você estava errado sobre o padre.",
"Aquele holandês era simplesmente louco, então tive que matá-lo. Você descobriu alguma coisa com a garçonete?",
"Aquele holandês recusou-se a falar comigo. Talvez você tenha conseguido aprender algo com seus servos?",
"Descobri que essas cartas são realmente falsas. O que você descobriu?",
"Gostaria de saber os detalhes sobre a morte da pessoa citada ",
"Giraldo Figueira",
"Giraldo Figueira",
".",
"Gostaria de saber se chegou uma fragata negra ao porto.",
"Diga-me, tem um homem chamado ",
"Chama",
"Chama",
" apareceu ultimamente? Ele é um capitão. É difícil sentir falta dele.",
"Preciso sair da cidade, discretamente. Talvez você possa me ajudar a fazer isso? Por, digamos, 1 moeda de ouro?",
"Preciso de informações sobre um certo homem. Ele está sempre vestindo uma túnica vermelha e se autodenomina 'Professor'.",
"Eu preciso de algum trabalho. Você não conhece nenhum garoto rico nesta ilha que tenha medo de viajar sozinho?",
"Nada no momento.",
"Se existir tal pessoa, ela pode preferir evitar atrair a atenção de tantas consortes - como eu espero que você saiba.",
"Sim, esqueci. Tudo bem, voltarei mais tarde, quando tiver menos navios, ha ha.",
"Eu não quero ajudar você. Você já fez muito mal ao meu país",
"Basta olhar para este patriota. Bem adeus",
"Sua cabeça está coberta de sangue. Você não acha seriamente que alguém viajaria com você?",
"Você está certo  todo mundo tem medo de mim! Ha ha!",
"Você chegou bem na hora. Um comerciante aqui estava procurando a companhia certa para viajar. É melhor você falar com ele. Aqui está ele, entrando na taverna.",
"Eu farei isso.",
"Não, não há ninguém naquele momento, Talvez da próxima vez.",
"Hm, então vou esperar.",
"Ah! Você terá que ir ao diretor da prisão! Este rapaz foi preso há alguns dias  ele estava incitando as pessoas à rebelião.",
"Ah, que bom, você me ajudou muito.",
"Aliás, algum navegador mora não muito longe daqui. Talvez ele seja quem você está procurando?",
"Obrigado! Acho que vou visitá-lo...",
"Eu não acho. Mas se você me pagar 50 moedas de ouro...",
"Negócio. Aqui estão suas moedas.",
"Isto é um simples roubo!",
"Vamos para a sala dos fundos, vou te dar uma roupa nova para você não ser reconhecido.",
"Ótimo!",
"Não Recentemente. Ele geralmente aparece aqui de vez em quando, mas já faz muito tempo que não o vejo.\n Dizem que ele afundou com seu navio durante aquela tempestade há uma semana.",
"Eu ouvi isso...",
"Uma fragata negra? Deixe-me pensar... Não, tenho certeza de que não havia nenhuma fragata negra em nosso porto. \Conheço um sujeito que já viu isso antes.",
"E? Como posso encontrar essa pessoa?",
"Lá está ele na mesa mais próxima. Se não me engano o nome dele é ",
"Balltesar Figueiredo",
"Balltesar Figueiredo",
".",
"Bom, vou falar com ele.",
"Sim, aquela mulher confessou que nunca ninguém lhe escreveu tais cartas e contou todas aquelas mentiras por ordem do ajudante do padre.",
"Excelente, obrigado. Sua ajuda foi inestimável.",
"Você está errado! Essa pessoa é inocente e todos esses rumores são infundados.",
"Bem, como apareceram essas letras então?",
"Eu acho que eles são falsos. Vi recentemente o assistente do padre conversando com um holandês chamado ",
"Yedam Kinne",
"Yedam Kinne",
"\n Todo mundo sabe que além de muitas outras coisas duvidosas que esse sujeito pode fazer, ele também pode falsificar documentos e caligrafias.",
"Hmm...Bom, vou tentar descobrir os detalhes. Enquanto isso você deveria conversar com a garçonete. Talvez ela também lhe conte algo importante.",
"Oh! Você veio até a pessoa certa. Esse acidente foi discutido por muitas pessoas várias noites seguidas em minha casa.",
"Então o que você sabe sobre a pessoa que o matou?",
"Dizem que foi uma garota maluca quem fez isso. Ele era seu amante ou seu ponce. \nDizem que ela é uma garota linda e muito inteligente. Ela até conseguiu escapar da prisão! Você consegue imaginar isso? \nVocê sabe por que ela o matou? Uma estatueta de ouro foi encontrada na casa do assassinado e pesava cerca de 5 quilos! \nSeria interessante saber de onde aquele cara tirou aquela estatueta, hein!",
"Sim, por um lado ele teve sorte de ter uma coisa tão boa, mas por outro lado se não fosse por aquela estatueta ele estaria vivo. Onde está agora? É possível dar uma olhada nesse milagre?",
"Ha! Você está tentando planejar como obtê-lo? \nVocê não será capaz de fazer isso! O ídolo está com o chefe da guarnição e não vai dar para ninguém. \nHavia 3 caras que tentaram mexer com ele... suas cabeças ainda estão penduradas nos portões da cidade.",
"Então você diz que o ídolo está com o chefe da guarnição? Isso é bom.",
"Você está falando sobre ",
"Padre Jerald",
"Padre Jerald",
"? Não dê ouvidos a essas mentiras perversas ",
"! \nSim, às vezes ele pode beber uma ou duas taças de vinho, mas ele é e sempre foi um homem muito devoto. \nAcredito que você não deveria ter medo de ir até ele para a confissão.",
"Oh! Obrigado por tirar todas as minhas dúvidas sobre ele.",
"Sim, ouvi falar dela.",
"Sim com certeza?! O que exatamente você ouviu sobre ela? Quando ela veio aqui da última vez?",
"Você me dá uma moeda de ouro ",
", e vou te contar tudo o que sei.",
"Pegue esta moeda.",
"Ha! Por esse dinheiro eu mesmo te diria qualquer coisa.",
"Ela esteve aqui não muito antes da libertação de #sOxbay# mas não ficou aqui. Lembro-me dela porque algum trabalhador tentou fazer uma proposta para ela, mas ela o colocou no lugar dele.",
"Ah, você não sabe muito. Diga-me, por favor, você já ouviu alguma coisa sobre as tábuas de barro que foram encontradas nas minas?",
"Pague-me mais uma moeda de ouro ",
" e eu vou te contar. ",
"Skinflint! Aqui está, pegue.",
"Eh, não, vou tentar descobrir algo sozinho então.",
"Tábuas de barro, você diz? Sim, eu sei sobre eles. Havia um sujeito que morava na minha casa há vários anos e ele teve muitos problemas com aquelas placas. Eles não deixaram que ele os levasse das minas, então ele trabalhava ali mesmo e costumava dizer que as placas o tornariam rico e famoso.",
"Eu vejo. Então, onde ele está agora?",
"Só Deus sabe. Estou lhe dizendo que não o deixaram pegar aquelas placas das minas, embora não entenda por quê. Então, aquele sujeito ficou sem dinheiro e saiu daqui e desde então nunca mais o vi.",
"Tudo bem, acho que terei que ir para as minas. Onde é esse lugar?",
"Você deveria sair da cidade e então verá as minas. Há um farol atrás deles. Tenho certeza que você os encontrará facilmente.",
"Bom.",
"Normalmente tenho muitos homens aqui que gostariam de se tornar marinheiros, mas agora é tarde demais. Eles começarão a aparecer apenas pela manhã\nPor que você não aluga um quarto e espera por eles?",
"Muito bem. Você tem algum quarto livre?",
"Não preciso de um quarto agora. Vamos mudar de assunto.",
"Tenho quartos disponíveis. Quanto tempo você vai ficar aqui?",
"Até amanha.",
"Até a noite.",
"Vai custar 5 peças de ouro.",
"Aqui está o seu dinheiro.",
"Infelizmente, parece um luxo, pois dormir em uma cama não é para mim e para minha carteira. Vou dormir no salão da taverna",
"Você tem um quarto king-size para alugar? Não, obrigado...por esse preço dormirei na taberna.",
"Vou pensar sobre isso.",
"Vai custar 5 ouro.",
"Aqui está o seu dinheiro.",
"Infelizmente, parece um luxo, pois dormir em uma cama não é para mim e para minha carteira. Vou dormir no salão da taverna",
"Você tem um quarto king size para alugar? Não, obrigado, por esse preço dormirei na taberna.",
"Vou pensar sobre isso.",
"Caros visitantes! Por favor, pare com esse ultraje na minha taverna ou chamarei os guardas!",
"Tudo bem. Eu já estou saindo.",
"Lembra quando você me disse para falar com o diretor sobre um prisioneiro? Bem, agora eu matei o bastardo sujo, então o que devo fazer agora?",
"Bem, já que o diretor morreu, eu digo para ir falar com o prisioneiro. Não é como se alguém fosse te impedir",
"Eu farei isso. Obrigado.",
"Ah! Este rapaz foi preso há poucos dias  ele estava incitando as pessoas à rebelião. Já que o diretor foi morto, sugiro que você vá até a prisão e converse com o sodomita.",
};
