string DLG_TEXT[52] = {
"Ei, minha mãe! Ah! Woooaahh... ei, rapaz ou moça (não consigo ver direito, hee hee), parece que você precisa de um pouco de endurecimento. Que tal você me deixar gravar uma imagem bonita em sua carne, como todos os outros marinheiros estão querendo?",
"Bem, minha pele parece um pouco nua... Quase me sinto nua ao lado de alguns dos demônios escuros que encontrei. Por que não.",
"Obrigado, não. Gosto da minha pele tal como ela é - limpa e não crua.",
"Então, o que você tem em mente, amigo? Minhas habilidades artísticas não são tão extensas (e admito que minhas ferramentas não são tão limpas), mas você deve encontrar algo para agradar a si mesmo se me der um dia para trabalhar.",
"Tenho em mente o padrão de um antigo guerreiro tribal, descendo pelo braço, para que eu possa desfrutar da mesma vantagem assustadora em um duelo. 400 é um preço justo.",
"O problema é que há uma moça especial da qual eu gostaria de ser lembrada toda vez que estou no mar e olho para meu peito nu e robusto. Vou te dar 500 iguais.",
"Algo inspirador, para encher meus homens de admiração e, bem, inspiração sempre que eles olham para meus bíceps nus e ondulantes. Aqui estão 600.",
"Uma âncora clássica, com um navio - tenho certeza que você receberá muitos pedidos para isso. Ficaria esplêndido em meu ombro bronzeado e poderia encorajar os homens a lutar um pouco mais para defender seu navio. 700 não é pedir muito, ouso dizer.",
"Vamos realmente à moda antiga aqui, amigo - eu vi esta foto uma vez, veja, deste desenho fantástico e realmente ornamentado que alguma antiga seita religiosa conseguiria para invocar a proteção divina... 800 deveria ser um roubo!",
"Bem... Na verdade... não consigo mais pensar em nada que você possa fazer. Já estou tatuado de cima a baixo...",
"Não, nada disso agrada, e nem deixar você enfiar uma agulha em mim. Além disso, minha mãe me mataria se descobrisse!",
"Agora, fique confortável aqui na minha sala e não se importe com os gritos que você possa ouvir... esses são apenas seus.",
"Nossa, que emocionante! Espere, vou mostrar isso aos homens! Eles vão ficar com muuuuito ciúmes!",
"Espere, eu... mudei de ideia. Acabei de lembrar que tenho... alergia a agulhas... E além disso, isso não está coberto no meu orçamento.",
"Apenas fique confortável na minha sala aqui, e não se importe com quaisquer gritos que possa ouvir... esses são apenas seus.",
"DLG_TEXT[15]",
"DLG_TEXT[16]",
"DLG_TEXT[17]",
"DLG_TEXT[18]",
"DLG_TEXT[19]",
"DLG_TEXT[20]",
"DLG_TEXT[21]",
"DLG_TEXT[22]",
"DLG_TEXT[23]",
"DLG_TEXT[24]",
"DLG_TEXT[25]",
"DLG_TEXT[26]",
"DLG_TEXT[27]",
"DLG_TEXT[28]",
"DLG_TEXT[29]",
"DLG_TEXT[30]",
"DLG_TEXT[31]",
"DLG_TEXT[32]",
"DLG_TEXT[33]",
"DLG_TEXT[34]",
"DLG_TEXT[35]",
"DLG_TEXT[36]",
"DLG_TEXT[37]",
"DLG_TEXT[38]",
"DLG_TEXT[39]",
"DLG_TEXT[40]",
"DLG_TEXT[41]",
"DLG_TEXT[42]",
"DLG_TEXT[43]",
"DLG_TEXT[44]",
"DLG_TEXT[45]",
"DLG_TEXT[46]",
"DLG_TEXT[47]",
"DLG_TEXT[48]",
"DLG_TEXT[49]",
"DLG_TEXT[50]",
"DLG_TEXT[51]",

};
