string DLG_TEXT[19] = {
"*olhar vazio e de vaca*... ",
"Ei... amigo... você quer uma dose?",
"Estrelas, cara, eu posso ver estrelas! É tão... cósmico!",
"... eu entendi! Posso ver tão claramente agora, é tudo tão simples! O segredo da vida... do universo... e de tudo! É... *cai imóvel* zzzz...",
"Ei, amigo... poupar um centavo?",
"Tem uma senhora simpática andando por aqui em algum lugar com um ótimo suco, cara!",
"Mais um cliente satisfeito, pelo que vejo.",
"Ooh, obsceno.",
"Uh... quem deixou esses lagartos entrarem aqui?",
"Eu gostaria de comprar o que você está tendo.",
"Sim, amigo. Esteja avisado, muitas pessoas não comprarão essas coisas. Isso vai te custar ",
" por peça.",
"Ok, vou comprar 1.",
"Ok, vou comprar 12.",
"Ok, vou comprar 72.",
"Não importa, não estou no mercado",
"Aqui você vai. Se eu fosse você, ficaria longe dos guardas enquanto você carrega isso e ficaria escondido por um tempo. Eles podem vir atrás de você se te virem com isso.",
"Obrigado Eu acho.",
};
