string DLG_TEXT[176] = {
"Olá, ",
". Eu ouvi você conversando com aquele velho maluco. ",
"Milon Blacque",
".",
"Isso não é da sua conta e, de qualquer forma, não tenho tempo para explicar.",
"O que faz você chamá-lo de louco? Ele parece são o suficiente para mim.",
"Você poderia me dizer, ",
", cuja banheira está rolando ali na praia?",
"Esse é aquele chamado '",
",' correto?",
"Sim está certo.",
"Tenha algum respeito quando falar do meu navio!",
"Oh, desculpe. Não sabia que aquela era a sua banheira!",
"Meça suas palavras!",
"Desculpe, ",
". Só estou zombando de você um pouco. Meu nome é ",
". Eu trabalho no porto.",
"Meu nome é ",
", e eu sou o capitão do '",
".'",
"Sim, eu descobri isso ",
".",
"Bem, já que você é um sujeito tão inteligente, talvez possa responder algumas das minhas perguntas.",
"Com prazer - estou com pouco dinheiro no momento.",
"O que? Não vou pagar para você ficar aqui e falar comigo.",
"Você quer dinheiro, não é? Tudo bem, aqui está uma moeda de ouro pelo seu tempo.",
"Desculpe, ",
". Acabei de lembrar que tenho assuntos urgentes em outro lugar.",
"Até a próxima.",
"Espere! Aqui está uma moeda de ouro.",
"O que você quer saber, ",
"?",
"Primeiro, conte-me as últimas notícias locais e partiremos daí...",
"Uma grande remessa de produtos proibidos apareceu recentemente no porto. \nO inspetor do porto ",
"Turpin Cabanel",
"Turpin Cabanel",
" correu as pernas tentando encontrar quem o contrabandeou para a cidade.",
"Nada de tão incomum nisso. Estou começando a me perguntar se sua conversa vale o dinheiro que paguei.",
"Realmente? Onde posso encontrá-lo?",
"Não se apresse ainda - tenho mais alguns rumores novos para você.",
"Vamos ouvi-los. Espero que sejam mais interessantes que o primeiro.",
"Não, obrigado, ",
". Acho que já ouvi o suficiente.",
"Bem, alguns piratas vieram para a cidade recentemente. Eles têm bebido e farreado por toda a cidade...",
"Piratas bebendo?! Isso é ainda menos interessante do que a sua história chocante de contrabando.",
"Piratas, você diz? Onde posso encontrá-los?",
"Tenho certeza de que a maioria deles ainda está na taverna, embora me tenham dito que planejam deixar a cidade em breve.",
"Obrigado. Eu tenho que ir - tempo é dinheiro.",
"Tudo bem. Você tem mais alguma coisa para mim?",
"Naquela casa perto do cais.",
"Obrigado pela informação.",
"Você pode me dizer mais alguma coisa de interesse?",
"Bem, há uma coisa ",
". Parece que ",
"Milon Blacque",
" tem vindo ao cais todos os dias para encontrar seu filho....",
"O que há de tão incomum nisso?",
"Todo mundo sabe que o filho e seu navio desapareceram há muitos anos.",
"Então um velho enlouqueceu de tristeza? Não vejo o que isso tem a ver comigo.",
"Por que ele ainda está aqui e não em algum asilo?",
"Um asilo, aqui? Você deve estar brincando, capitão. Mesmo assim, ele é cuidado.",
"Cuidado?",
"Sim. Ele tem uma filha adotiva ",
"Rachel Blacque",
", que cuida dele. \nEla é uma boneca viva, mas tão fria quanto o Mar do Norte. Mesmo assim, um dia vou conquistá-la.",
"Poupe-me de ficar pensando em alguma garota local. Isso não me interessa.",
"Posso dizer que você está bem informado sobre tudo o que acontece por aqui. Você se importa de responder algumas das minhas perguntas?",
"Olá, ",
". Eu ouvi você conversando com aquele velho maluco. ",
"Milon Blacque",
".",
"Isso não é da sua conta e, de qualquer forma, não tenho tempo para explicar.",
"O que faz você chamá-lo de louco? Ele parece são o suficiente para mim.",
"Bons ventos para você ",
".",
"Ah é você! Aconteceu alguma coisa nova?",
"Disseram-me que você não irá embora ",
"Rachel Blacque",
" e seu pai sozinho.",
"Olá, ",
". Faz muito tempo que não te vejo.",
"Você se lembra de me contar algo sobre contrabandistas?",
"Você me contou algo sobre contrabandistas recentemente - lembra dos detalhes?",
"Vamos conversar depois. Negócios mais urgentes me ligam.",
"Claro que eu faço, ",
". Todo mundo na cidade está falando sobre isso.",
"Eu vejo. Você poderia me dizer mais alguma coisa?",
"Conte-me mais, então. Posso dizer, olhando para você, que você está de alguma forma envolvido nesse negócio.",
"O que você está falando? Eu só trabalho aqui no porto.",
"Você está me dizendo que não sabe o que está acontecendo na cidade? No porto onde você trabalha todos os dias?",
"É por isso que tenho certeza de que você sabe mais do que diz.",
"Como eu iria saber?!",
"Eu sei como são os trabalhadores portuários. Eles adoram fofocar sobre o navio que acabou de ser descarregado, que tipo de mercadorias eles carregavam e que pessoas eles viram!",
"Não jogue. Mesmo que você não tenha ajudado pessoalmente a descarregar aquele contrabando, certamente sabe quem o fez.",
"Certo. Provavelmente estou enganado. Desculpe.",
"Desculpe. Provavelmente estou errado sobre você. Não tenho sido eu mesmo ultimamente.",
"Tudo bem, vejo que não há raciocínio com você. Adeus.",
"Eu vejo onde isso está indo. Quanto custará para reavivar sua memória?",
"Bem, é claro que depende de você. Você não precisa falar comigo. Você sempre poderia falar com minha espada.",
"Eu acho que 500 ouro é uma quantia justa ",
".",
"Você tem um acordo. Pegue o dinheiro e converse. ",
"Não seja ridículo. Eu não tenho tanto dinheiro.",
"Então eu não posso te ajudar ",
".",
"Exorto você a reconsiderar. Ou você gostaria de ter.",
"Isso é ",
"Raoul Calmes",
"Raoul Calmes",
" quem está por trás de tudo isso. Isso é tudo que eu sei. Agora deixe-me voltar ao trabalho.",
"Obrigado pela ajuda.",
"Não me faça rir! Se você tentar algo aqui, os soldados o pegarão.",
"Quando os soldados chegarem aqui, terei sacado e atirado. E você não estará por perto para vê-los me pegar. Ainda assim, depende de você.",
"Você não faria isso - seria uma loucura!",
"Vá em frente e me teste.",
"Diabo! Tudo bem, tudo bem - vou te contar tudo.",
"Esse é um garoto inteligente. Estou ouvindo.",
"Bem, estou fora daqui.",
"O que você está falando, ",
"? Sou um homem respeitável!",
"Não importa seus jogos. É muito simples: deixe-os em paz, ou farei com que você deseje ter feito isso.",
"Não se preocupe em mentir para mim. Consigo ver a verdade na tua cara.",
"Maldita seja essa garota! Quando eu terminar com ela, ela não poderá reclamar com mais ninguém!",
"Você é surdo? Se você tocá-la novamente... se você olhar para ela de lado... eu terei coragem de usar ligas.",
"Eu não estou mentindo para você, ",
"!",
"Claro que você é. Eu lido com mentirosos melhores do que você todos os dias. Apenas entenda isto: se você tocá-la novamente, farei com que você se arrependa pelo resto de sua curta vida. Você entende?",
"Relaxar. Só quero saber por quanto tempo você vai aguentar as bobagens dela.",
"O que você quer dizer?",
"Quero dizer, é hora de você colocar isso ",
"Rachel Blacque",
" no lugar dela. Seja um homem!",
"Claro, ",
". Eu vou, uh... eu só vou fazer isso. Claro.",
"É isso mesmo, é hora de mostrar àquela puta o que ela realmente vale.",
"Espera espera! Mais uma coisa.",
"Isto é um pesadelo! ...Vá em frente, o que é isso?",
"Não, obrigado, ",
". Acho que já ouvi o suficiente. Adeus.",
"Oh nada. Só que se eu ouvir mais alguma coisa, com certeza lhe direi... Contanto que você tenha ouro, claro.",
" Você é um verme tão pequeno! Adeus!",
"Bem, você é um capitão, certo?",
"Vá direto ao ponto, Orable!",
"E pensar que realmente paguei um bom dinheiro por uma visão tão brilhante? Adeus!",
"Você precisa de um bom contramestre?",
"Ele sabe que você o está recomendando? Um elogio seu não é exatamente confiável, você sabe.",
"Não acredito que você conheça um bom contramestre. Até a próxima.",
"Você me feriu, #ssir#!",
"Tudo bem, tudo bem. Onde ele está?",
"A vida é dura, filho. Adeus!",
"Ele está na praia sul. Use a passagem pelas rochas passando pelo escritório da Capitania do Porto.",
"E esse sujeito tem nome?",
"Não sei por que acho difícil acreditar em qualquer um dos seus rumores, Orable. Voltarei para pegar aquela moeda se tudo isso for besteira.",
"Bem, ele será fácil de encontrar, ele é um homem corpulento e seu nome é Fred Bob. Porém, uma palavra de cautela: ele é um pouco difícil de entender.",
"O que você quer dizer com isso?",
"É melhor que não seja porque ele está bebendo um pouco do seu veneno caseiro!",
"Você verá, só não se deixe enganar, ele é realmente um marinheiro muito astuto. Há rumores de que ele tem um mapa do tesouro para um maravilhoso esconderijo de ouro.",
"É assim mesmo? E você não está fora de uma parte disso? Isso soa suspeitamente como um problema.",
"Ah, eu tento não me colocar em perigo ",
". Eu tenho um trabalho importante aqui, você vê.",
"Acabei de pagar uma boa moeda por essa bobagem?",
"Você e seu dinheiro são sempre bem-vindos, Capitão!",
"Saia do sol, Orable!",
"É um prazer conhecer seu ouro, Capitão!",
"Enquanto o seu ouro for bom, capitão, estarei aqui com rumores.",
"Foi sempre um prazer, Orable, foi... Horrível. Não se afaste muito, caso eu decida voltar para torcer seu pescoço magro.",
"Volte para debaixo daquela rocha que você chama de lar, Orable!",
"Eu sei onde você pode encontrar um bom contramestre ",
".",
"Já contratei um contramestre que você recomendou, Orable, e desde então o demiti.",
"Você deveria contratá-lo de volta, capitão ",
".",
"Hmmm, talvez eu devesse. Você sabe onde ele está?",
"Por que eu iria querer fazer isso? Não importa, bom dia!",
"Ouvi dizer que ele foi contratado por um navio mercante espanhol. Experimente #sIsla Muelle#.",
"Mercador espanhol? Parece chato. Bem adeus.",

};
