string DLG_TEXT[93] = {
", querido cliente! Eu sou ",
", proprietário do estaleiro local.",
"Eu sou ",
", capitão do '",
".",
", ",
". Você precisa dos serviços do meu estaleiro, ",
"?",
"Sim, por favor, atraque meu navio.",
"Não, eu só quero conversar",
"Não, estou apenas de visita.",
"Bem, é um prazer conhecê-lo. Se você é capitão, meu estaleiro está disponível para sua alfândega.",
"Ótimo, ",
". Preciso do seu conhecimento especializado.",
"Obrigado. Mas primeiro vamos conversar.",
"Da próxima vez, talvez. Eu tenho que ir embora.",
"No que exatamente você está interessado ",
"?",
"Nada por enquanto.",
"Sobre aquele baú que você me pediu para levar para #sRedmond#....",
"Posso ajudá-lo com mais alguma coisa ",
"?",
"Sim, preciso dos serviços do seu estaleiro.",
"Obrigado. Isso é tudo. Até a próxima!",
"O que você precisa?",
"Preciso que seus artesãos verifiquem meu navio, embora eu possa considerar apenas trocá-lo e comprar um novo.",
"Preciso instalar novas armas na meu navio.",
"Nada, obrigado.",
"O que você está pensando, ",
"? Você realmente acha que os franceses me deixarão consertar seu navio bem debaixo de seus narizes? Eles colocaram guardas em cada deslizamento do meu estaleiro!",
"Isso é uma vergonha.",
"O que aconteceu? Algo está errado?",
"Precisamos nos esconder. Os soldados franceses estão atrás de nós!",
"Por que?",
"Não sei. Olha, podemos discutir isso mais tarde. Os soldados estarão aqui a qualquer minuto!",
"Tudo bem, vou esconder você. E não se preocupe - vou afastá-los do seu cheiro se aparecerem aqui.",
"Obrigado.",
"Mostrei a porta aos soldados. Então, talvez agora você possa me contar o que aconteceu?",
"Parece que os franceses suspeitam de ",
"Counterspy",
".",
"E eles decidiram pegá-lo primeiro e perguntar depois?",
"Sim, esta parece ser a forma deles lidarem com isso. Obrigado pela ajuda.",
"Não mencione isso. Talvez você pudesse me fazer um favor em troca. Preciso levar algo para #sRedmond#, mas só levantarei suspeitas se eu mesmo levar lá.",
"E isso é algo que você não poderia enviar da maneira usual?",
"Não. O conteúdo deste baú é extremamente importante. Não posso confiar em algum estranho - mas confio em você ",
"\nÉ por isso que peço que você entregue em #sRedmond#, se estiver disposto.",
"Depois do que você fez por mim, como posso recusar?",
"Obrigado. Por favor, leve este baú para ",
"Charles Windem",
"  ",
"Charles Windem",
". Ele é o dono da taverna #sRedmond#. Diga a ele que veio de mim e ele entenderá. Bons ventos para você ",
".",
"E para você. Até a próxima.",
"Sim? Você entregou?",
"Receio que não. Alguém atrapalhou. Ou alguma coisa.",
"Algo?!",
"Dois homens que não podiam ser mortos com uma lâmina",
"Bom Deus! Então é verdade...",
"O que é verdade? Há algo que você gostaria de me dizer?",
"Oh, não... não, não é nada. É uma pena que você tenha sido atacado....",
"Desembucha ou derrame seu sangue. Faça a sua escolha.",
"Espere! Vou te contar o que sei. Há uma história sobre um pirata horrível. Ele saqueou e afundou navios, não teve misericórdia... E um dia ele fez algo tão terrível que Deus o abandonou para sempre. \nEsse pirata se tornou algo indescritível... os mortos-vivos! Dizem que ele e sua tripulação ainda caçam e saqueiam navios, mas agora ninguém pode resistir a eles - porque não podem ser mortos! Dizem que ele está procurando por algo... moedas antigas ou tesouros perdidos aqui no arquipélago.",
"Isso é uma loucura! Uma história para assustar as crianças.",
"É isso? Você viu aqueles piratas sombrios com seus próprios olhos! Enviei aquele baú para meu antigo inimigo ",
"Charles Windem",
", na crença de que continha o tesouro que procuravam. Eu esperava que eles pudessem encontrá-lo e matá-lo eventualmente. Você tem que acreditar em mim - nunca pensei que eles iriam te alcançar primeiro!",
"Onde você conseguiu esse baú?",
"Um homem vendeu para mim. Ele pediu muito pouco em troca e prometeu que eu poderia me livrar do meu antigo rival simplesmente enviando-o para ele.",
"Onde posso encontrar este homem?",
"Ele mora em #sisland_Falaise de Fleur#, perto do porto! É com ele que você quer conversar - ele sabe muito mais sobre aquele baú do que eu!",
"Se eu não fosse um #sgender# de honra, faria você pagar por me colocar em tal perigo!",
"Recuso-me a negociar com uma pessoa com a sua reputação e relações. Agora saia, ",
", antes de chamar os guardas.",
"Muito bem.",
"Tudo bem, meu cais ao lado do forte está disponível para você. Se você quiser, direi ao meu chefe das docas para rebocar seu navio até lá. Só então poderei avaliar os danos e dizer quanto tempo e dinheiro serão necessários.",
"DOCA AO LADO DO FORTE?? Uhh... só me lembro que tenho... eeh... outro assunto urgente que preciso resolver primeiro. Adeus.",
"Após fechar esta caixa de diálogo, pressione ENTER para abrir a interface de mudança de vela.",
"Saída",
"As pessoas dizem que você recebeu um grande pedido. Acho que você precisa de alguns suprimentos então?",
"Sim, na verdade estou precisando de alguns suprimentos. A loja está toda esgotada. Você poderia me buscar ",
" Vou te pagar ",
" moedas de ouro.",
"Eu sou seu homem. Você terá esses suprimentos em pouco tempo.",
"Desculpe não estou interessado",
"Para pior, vou encontrar outra pessoa então",
"Parece que 'essas pessoas' estão tentando enganá-lo ou talvez você devesse perguntar mais. Não recebi nenhuma oferta... gostaria de ter.",
"Eu trouxe os materiais que você precisava",
"Muito obrigado. Aqui está o seu dinheiro.",
"De nada",
"Alguém chegou aqui antes de você, então já tenho tudo que preciso. Talvez a loja queira seus produtos",
};
