string DLG_TEXT[28] = {
"Você não vê que estou de plantão? Não me incomode!",
"Tudo bem, tudo bem.",
"Você queria denunciar algum crime?",
"Não, claro que não. Afinal, sou um capitão... mas vejo que você não está ouvindo.",
"Lembre-se: não permitimos brigas nas ruas. Você pode se defender, é claro, se alguém te atacar.",
"Certo, vou considerar essa informação.",
"Um tempo tão insuportável... e eu tenho que ficar aqui nele. Você pode não acreditar, mas meu único passatempo é lutar contra as moscas que tentam pousar no meu rosto.",
"Isso é muito lamentável, mas não posso ajudá-lo. É seu dever.",
"Se você quiser conversar, encontre outra pessoa. Tenho o meu dever a cumprir e não é meu dever falar contigo.",
"Eu só estava me perguntando se você está vivo ou não. Você está aqui como uma estátua",
"Você acha que é fácil proteger nossa cidade? De jeito nenhum! É um trabalho muito importante e perigoso. Lembro-me de uma vez...",
"Conte-me em outra hora. Eu tenho que ir.",
"Vá embora, não me incomode",
"Como você diz, soldado.",
"Ei! Você pode me trazer uma caneca de rum da taverna?",
"Talvez. Mas não vão me enforcar por ajudar um soldado a ficar bêbado em serviço? Não, espere até eles trocarem a guarda, e então você poderá beber o quanto quiser.",
"Por que deve ser um marinheiro rude como você tentando falar comigo?! Não há mulheres bonitas nesta cidade?",
"E você chama isso de cumprir seu dever? Olha, você não gostaria de perder a captura de um criminoso perigoso como eu, não é? Ha-ha!",
"Você parece muito saudável. Você não quer se juntar ao nosso exército? Temos muito espaço no quartel, boa comida, rum de graça.",
"Parece bom, mas terei que recusar sua oferta. A disciplina do exército não combina comigo.",
"Este calor.... Eu daria tudo para voltar para a Inglaterra.",
"Sim, parece que este clima não combina com você.",
"O que você quer?",
"Seu... hic... seu vira-lata com escorbuto! Você machucou meu...hic...meu amigo!",
"Que amigo? Você está sozinho aqui ",
".",
"O que? Ele estava... aqui há um minuto. Eu irei encontrá-lo. Você...hic...você vai esperar aqui mesmo se quiser levar uma surra....",
"Como ousa me contradizer! Eu vou te estrangular!",


};
