string DLG_TEXT[40] = {
"Sim? Por que você interrompe meu trabalho?",
"Desculpe, estava vendo quem mora aqui. Eu irei agora.",
"Vá embora! Estou ocupado.",
"Não há necessidade de ser assim. Vou!",
"Feche a porta antes que o vento espalhe meus papéis! Agora, o que você quer?",
"Meu nome é #sname#. Disseram-me que você é a pessoa que deve consultar sobre documentos não oficiais, por assim dizer.",
"Você terá que ser mais específico do que isso, #sladlass#! Que tipo de documento você deseja?",
"Minha tripulação está atualmente prisioneira no forte #sPort au Prince# e quero tirá-los de lá. Você pode fornecer algo para ajudar com isso?",
"Hmm... um simples formulário de transferência de prisioneiro deve ser suficiente. A primeira coisa que preciso é de uma cópia da assinatura do governador - tudo o que tenho no momento é uma assinatura do governador anterior, o que não vai enganar ninguém.",
"Eu vim preparado. Isso servirá?",
"Vou ter que voltar à cidade para pegar isso. Adeus.",
"Ah, é você de novo. Você conseguiu a assinatura do espécime?",
"Sim, dê uma olhada nisso.",
"Ainda não. É hora de outra caminhada de volta à cidade, suponho.",
"Excelente! Discutiremos a taxa mais tarde, mas isso será ajuda suficiente para trabalhos futuros, pois pagará metade dela.\nVocê precisará de um uniforme francês para que isso funcione, pois o formulário é para a transferência de prisioneiros de um oficial para outro. outro. Você tem uniforme?",
"Sim, tomei um há algum tempo.",
"Eu realmente tenho que usá-lo novamente? Os uniformes são projetados para homens e são quase dolorosos de usar.",
"Bom, então vou começar. Volte amanhã. A taxa para esse tipo de trabalho normalmente seria #sfullprice# ouro, mas o autógrafo do governador paga metade, então você me deve #shalfprice# se quiser seu formulário.",
"Não é um problema. Aqui está o seu dinheiro e até amanhã",
"Eu não tenho tanto. Voltarei quando o fizer.",
"Ah, a #sperson# que quer comprar meu trabalho e não conseguiu pagar nem metade do preço. Você tem o ouro #shalfprice#?",
"Sim, aqui está o dinheiro. Certifique-se de ter a papelada pronta até amanhã!",
"Não, ainda não encontrei alguém que possa... 'doar' tanto.",
"Nesse caso, eu poderia tentar um formulário de requisição de trabalho escravo. Será mais caro, no entanto. O que você quer, a transferência de prisioneiros ou a requisição de escravos?",
"Posso tolerar usar o uniforme novamente. Dá-me a transferência do prisioneiro.",
"Não me importo de pagar um pouco mais para ficar fora desse maldito uniforme! Eu terei a requisição de escravos.",
"Muito bem. Você fará o papel de um proprietário de terras que deseja que os prisioneiros trabalhem - construindo algo, talvez.",
" O ideal seria que você estivesse com um vestido mais chique do que esse, mas com o que você está vestindo, os guardas estarão olhando... bem, digamos apenas que eles não prestarão tanta atenção ao documento.",
"Eu posso viver com isso.",
"Voltou para pegar seu documento, não é? Olha Você aqui. A encenação necessária para usá-lo com sucesso depende de você. Adeus!",
"Voltou para pegar seu documento, não é? Olha Você aqui. Não se esqueça de vestir seu uniforme! Adeus.",
"Obrigado e adeus.",
"Lembre de mim? Eu sou #sname#. Preciso de sua ajuda novamente.",
"De fato? E o que você precisa desta vez?",
"Encomendando documentos que provam que sou um Kapitein na guarnição de #sDouwesen#.",
"Ah, documentos militares? Você veio ao homem certo, então. Precisarei de alguns dias para descobrir qual unidade está estacionada em #sDouwesen#, mas os documentos em si devem ser bastante simples.\nEntão, volte aqui em três dias com 3.000 em ouro e você receberá seus documentos. ",
"Muito bem, vejo você em três dias.",
"Você está de volta, então. Você tem o dinheiro?",
"Sim, 3.000 ouro como você pediu.",
"E aqui estão seus papéis - Kapitein ",
}
