string DLG_TEXT[56] = {
"Olá, #saddr#. O que o traz ao seio da Igreja? Você veio para se confessar ou talvez para fazer uma doação?",
"Preciso falar com você, Padre.",
"Gostaria de fazer uma doação, Padre.",
"Só dando uma olhada. Eu tenho que ir.",
"Estou ouvindo, #saddr#.",
"Não tenho nenhum negócio com você agora.",
"Claro, #saddr#. Quanto você quer dar?",
"Sinto muito, Padre, mas não posso fazer uma doação agora.",
"Receio que 100 ouro seja tudo o que posso pagar agora.",
"Eu deveria pensar que o Senhor olharia gentilmente para 1.000 moedas de ouro.",
"Estou bem ultimamente, então darei 5.000 piastras de ouro.",
"A decisão é sua, #saddr#. Nunca é tarde para mudar - e tenha em mente que tudo será levado em conta no momento da sua morte.",
"Minha morte ainda está muito distante, se Deus quiser! Vamos falar sobre outra coisa.",
"Desculpe, padre. Eu tenho que ir.",
"Agradeço-lhe o seu presente em nome da Santa Igreja, #saddr#.",
"Preciso falar com você, Padre.",
"Sinto muito, Padre, mas tenho que ir.",
"Agradeço-lhe o seu presente em nome da Santa Igreja, #saddr#.",
"Preciso falar com você, Padre.",
"Sinto muito, Padre, mas tenho que ir.",
"Agradeço-lhe o seu presente em nome da Santa Igreja, #saddr#.",
"Preciso falar com você, Padre.",
"Sinto muito, Padre, mas tenho que ir.",
"Estou com medo ",
" ouro é tudo o que posso pagar agora.",
"Eu deveria pensar que o Senhor olharia com bondade ",
" peças de ouro.",
"Estou bem ultimamente, então vou dar ",
"Neste dia alegre, celebramos a união destas duas pessoas no sagrado matrimônio. ",
", vocês vieram aqui livremente e sem reservas para se entregarem em casamento?",
"Sim.",
"Aham. <Olha atentamente para você.> Vocês honrarão um ao outro como marido e mulher pelo resto de suas vidas?",
"Eu vou.",
"Você aceitará os filhos de Deus com amor e os criará de acordo com a lei de Cristo e de sua Igreja?",
"Er... sim, eu vou.",
"Que o Senhor abençoe estes anéis que este homem e esta mulher estão prestes a dar um ao outro.",
"#sgroom#, você aceita #sbride# como sua esposa? Você promete ser fiel a ela nos bons e nos maus momentos, na doença e na saúde, amá-la e honrá-la todos os dias da sua vida?",
"Eu faço.",
"#sbride#, você aceita #sgroom# como seu marido? Você promete ser fiel a ele nos bons e nos maus momentos, na doença e na saúde, amá-lo e honrá-lo todos os dias da sua vida?",
"...",
"Cada um de vocês declarou seu consentimento para se entregar ao outro e para receber esse presente com o amor com que ele é dado. Que o Senhor abençoe e cuide deste casal que se uniu aqui hoje à Sua vista. O que Deus uniu, os homens não devem dividir.",
"Arrr!",
"Quem é você e por que interrompe esse processo?",
"Ah, #vilão#. Sim, lembro-me de ter lido sobre você. Você realmente era casado com #sromance#, mas o casamento foi sem ",
"dele",
"dela",
" consentimento. O Santo Padre em Roma decretou que o casamento foi anulado e #sromance# está novamente livre para casar.",
"Não! Não deve haver derramamento de sangue nesta igreja!",
"Então me perdoe, pai, porque estou prestes a pecar.",
"O que é que você fez? Sangue foi derramado. Este lugar sagrado está profanado!",
"Eu queria que a luta fosse lá fora, mas #vilão# não me deixou escolha.",
"Sou leal à Espanha, mas sou leal primeiro à Igreja. E a minha primeira preocupação é com a Igreja, Excelência. Nenhuma outra cerimônia pode ser realizada aqui até que este edifício seja reconsagrado.",
"Você é... muito persuasivo, Excelência. Muito bem, então. Continuaremos. Er... onde estávamos?",
"Estávamos no meio da troca de promessas, padre.",
"Ah sim. Aham. ",
" e ",
};
