string DLG_TEXT[145] = {
"Olá, #saddr#. O que o traz ao seio da Igreja? Você veio para se confessar ou talvez para fazer uma doação?",
"Preciso falar com você, Padre.",
"Gostaria de fazer uma doação, Padre.",
"Só dando uma olhada. Eu tenho que ir.",
"Estou ouvindo, #saddr#.",
"Preciso de acesso à biblioteca da igreja, Padre.",
"Eu tenho aqueles papéis que foram roubados de você.",
"Os papéis que você me enviou para encontrar agora estão no fundo do mar - junto com quem os roubou.",
"Pediram-me para entregar esta carta a você.",
"Pediram-me para entregar esta carta a você.",
"Receio não ter conseguido cumprir sua missão. Quando cheguei à ilha, o 'Montanez' já estava em combate com dois navios piratas, e eles o afundaram.",
"Eu executei sua tarefa. O navio que você me pediu para escoltar está atracado no porto.",
"Não tenho nenhum negócio com você agora.",
"Você se saiu bem, #saddr#! Sua viagem correu bem?",
"Não inteiramente. Quando finalmente encontrei a barca, ela havia sido atacada por dois navios piratas empenhados em afundá-la a qualquer custo.",
"Agradeço ao Senhor por você ter viajado com segurança! Mais alguma coisa?",
"Sim, havia outra coisa. O capitão do navio deixou algum passageiro em #sisland_Oxbay#...",
"Sim, eu sei disso. Na verdade, esse era o objetivo de todo o empreendimento. A chegada deste homem ao arquipélago é muito importante para a Igreja. Acredito que um dia você o conhecerá",
"Entendo. Padre, isso tem alguma coisa a ver com as crianças desaparecidas?",
"Ah, entendo. Pois bem, aqui está sua recompensa - e se você quiser, permita-me propor uma nova missão para você.",
"Obrigado, Padre. E qual é essa nova tarefa?",
"Meu Senhor - esta é realmente uma notícia grave! Alguém obviamente conhece nossos planos e está se opondo ativamente a eles. Rezo para que haja sobreviventes que chegaram à costa e escaparam de serem capturados.",
"Sinto muito, Padre.",
"Nada disso, #saddr#. Você fez tudo o que pôde e acho que seria injusto não lhe pagar por sua tentativa de ajudar a Santa Igreja.",
"Obrigado.",
"Agora, você concordaria em realizar outra missão para mim?",
"Primeiro, gostaria que algumas perguntas fossem respondidas, se não se importa.",
"Nada de extraordinário. Basta levar esta carta para #sFatherBernard# em #sisland_Redmond#. E por favor tenha cuidado - certifique-se de que ninguém veja além dele! Agora tenho motivos para acreditar que temos um traidor entre nós.",
"Parece que sim. Eu irei agora, se puder",
"Sim, e que o bom Deus esteja com você, #saddr#.",
"Amém, Padre.",
"Deixe-me ver. Sim... sim, é exatamente como pensei! Você se saiu bem, mas deixe-me fazer algumas perguntas.",
"Claro. O que você gostaria de saber?",
"Deixe-me ver. Sim... sim, é exatamente como pensei! Mas quem abriu a carta?",
"Ninguém abriu, Padre! Você acha que eu faria uma coisa dessas?",
"Você percebeu isso, não é? Eu sabia que isso não iria acabar bem.",
"Então, quem abriu?",
"Eles estavam me esperando na baía quando desembarquei. Não tive escolha a não ser deixá-los ver a carta. Homens de túnica vermelha...era como se soubessem que eu iria atracar ali!",
"Eu vejo. Isso é facilmente perdoado, #saddr# - especialmente porque previmos isso e escrevemos a carta em código. Você realmente nos ajudou a enganar nosso inimigo. Tenho o prazer de lhe pagar a quantia que prometi.",
"Obrigado.",
"É claro que você não sente remorso pelo que fez. A escolha é sua, é claro. Mas vou pedir-te que saias desta igreja!",
"Como quiser.",
"Não, espere! Sinto muito, padre. Foi errado da minha parte.",
"Você teve algum problema em sua jornada?",
"Bem, ",
"Father Bernard",
", me pediu para atracar em uma baía isolada para escapar de problemas - mas eles estavam me esperando lá...",
"Fale claramente na casa do Senhor, #saddr#. Você está sugerindo que...",
"Não estou sugerindo nada. Não tenho provas suficientes para acusar ninguém. Você tem que concordar, porém, que isso é muito suspeito. Na baía, três homens de túnica vermelha esperavam por mim e estavam bastante interessados na carta. Tão interessado, na verdade, que fui forçado a matá-los.",
"Vejo que ",
"Father Bernard",
" não foi imprudente em dar-lhe esta missão.",
"Tem mais, Padre. Quando revistei os corpos dos meus agressores, encontrei um estranho medalhão no pescoço de cada um.",
"Você tem um desses medalhões? Sim... Este é realmente um emblema satanista... Isto não é um bom presságio. Mas vamos voltar aos negócios. Aqui está sua recompensa.",
"Obrigado.",
"Tenho outra missão para você, se estiver interessado. E a recompensa será muito mais generosa desta vez.",
"O que você gostaria que eu fizesse?",
"Um navio chegará da Europa em breve, transportando algumas pessoas que são vitais para a nossa causa. Tenho todos os motivos para acreditar que o navio será atacado, então sua tarefa é encontrá-lo perto de #sisland_Oxbay# e escoltá-lo até nosso porto.",
"Diga-me o nome do navio e farei tudo o que puder.",
"É uma barca chamada 'Montanez', sob o comando de ",
"Mergildo Hurtado",
", um oficial espanhol.",
"Tudo bem. Essa deve ser toda a informação que preciso. Partirei o mais rápido possível - quanto mais rápido eu estiver a caminho, maiores serão minhas chances de sucesso.",
"Sinto muito por ouvir isso. Esses papéis eram muito importantes para a igreja.",
"Você deveria estar feliz por seus inimigos não serem capazes de usá-los contra você, Padre.",
"Isso é verdade. Mas ainda é uma pena perdê-los.",
"Desculpe. Isso significa que não posso ter acesso à biblioteca?",
"Talvez devesse - mas você me parece uma #sperson# que encontraria um caminho de qualquer maneira.",
"Então, posso entrar?",
"Sim, você pode. Você tem o dia inteiro para ler. Mas é estranho - você é a segunda pessoa que queria tanto entrar lá.",
"Obrigado, Padre.",
"Perfeito! Por favor, dê-me eles agora mesmo.",
"Aqui estão eles.",
"Não tão rápido, Padre!",
"O que você quer dizer com #saddr#?",
"Eu descobri que tipo de papéis são esses - então, naturalmente, o preço deles subiu.",
"Você está me chantageando?!",
"Você achava que suas vestes sacerdotais o tornavam imune a uma pequena extorsão honesta? Se você não quer que esses papéis caiam em mãos erradas, você me dará acesso à biblioteca e 5.000 em dinheiro.",
"Você não tem medo do Senhor? Onde posso encontrar esse dinheiro?",
"Bem, vamos apenas verificar essas notas, certo? Sim, aqui está: '...17.000 ouro foram dados para equipar o navio e contratar marinheiros....' O que estou pedindo é apenas uma fração dessa quantia.",
"Suficiente! Podemos ser ouvidos. Aqui está o seu dinheiro. Agora me dê esses papéis!",
"Eles são todos seus. Agora, que tal a biblioteca?",
"Você fez um ótimo trabalho para o bem da Igreja, #saddr#. Você será recompensado.",
"E a biblioteca? Posso entrar lá?",
"Oh sim. Eu tinha esquecido disso. Claro que você pode entrar. Mas é estranho - você é a segunda pessoa que queria tanto entrar lá.",
"Obrigado, Padre.",
"Receio que isso não seja possível. A biblioteca está fechada para leigos.",
"Talvez você possa abrir uma exceção para mim. Olha, eu tenho meu próprio navio e tripulação. Talvez se você me ajudar com meu problema, eu possa ajudar com alguns dos seus.",
"Você é um capitão? Então talvez você realmente possa ajudar a mim e à Igreja espanhola.",
"Ótimo! O que você gostaria que eu fizesse?",
"Alguns papéis muito importantes foram roubados da igreja há vários dias. Eu suspeito que eles foram levados por ",
"Ferro Cerezo",
"Ferro Cerezo",
". Infelizmente, não tenho nenhuma evidência concreta contra ele.",
"Então, você quer que eu descubra se ele tem os papéis e os traga de volta para você se tiver?",
"Sim. São documentos muito importantes. Não deixe pedra sobre pedra em sua busca por eles.",
"Onde posso encontrar este homem?",
"Consegui descobrir que ele tem seu próprio navio. É um saveiro, se não me engano. E ele é frequentemente visto na cidade de #sConceicao# - provavelmente está envolvido com contrabando.",
"Eu vou encontrá-lo. Você me permitirá acesso à biblioteca se eu devolver os papéis?",
"Certamente. Você poderá passar um dia inteiro lá, embora eu não entenda por que um marinheiro se interessaria por isso.",
"Abençoe-me então, Padre, e irei embora.",
"Claro, #saddr#. Quanto você quer dar?",
"Sinto muito, Padre, mas não posso fazer uma doação agora.",
"Receio que 100 ouro seja tudo o que posso pagar agora.",
"Eu deveria pensar que o Senhor olharia gentilmente para 1.000 moedas de ouro.",
"Estou bem ultimamente, então darei 5.000 piastras de ouro.",
"A decisão é sua, #saddr#. Nunca é tarde para mudar - e tenha em mente que tudo será levado em conta no momento da sua morte.",
"Minha morte ainda está muito distante, se Deus quiser! Vamos falar sobre outra coisa.",
"Desculpe, padre. Eu tenho que ir.",
"Agradeço-lhe o seu presente em nome da Santa Igreja, #saddr#.",
"Preciso falar com você, Padre.",
"Sinto muito, Padre, mas tenho que ir.",
"Agradeço-lhe o seu presente em nome da Santa Igreja, #saddr#.",
"Preciso falar com você, Padre.",
"Sinto muito, Padre, mas tenho que ir.",
"Agradeço-lhe o seu presente em nome da Santa Igreja, #saddr#.",
"Preciso falar com você, Padre.",
"Sinto muito, Padre, mas tenho que ir.",
"Sim, acreditamos que sim. Você está investigando isso sozinho?",
"Estou agindo em nome das mães dessas crianças.",
"É muito gentil da sua parte estar tão preocupado, #saddr#.",
"Bem, também sou uma pessoa prática, Padre. O que quer que coloque ouro na minha bolsa.",
"Responderei o que puder, #saddr#.",
"Isso tem alguma coisa a ver com as crianças desaparecidas?",
"Sim, acreditamos que sim. Você está investigando isso sozinho?",
"Estou agindo em nome das mães dessas crianças.",
"Ah, entendo. É evidente que será benéfico para ambos se trabalharmos juntos nisso, para que possamos ser mais fortes juntos diante deste mal.",
"Muito bem, Padre. Qual é a sua próxima missão para mim?",
"Capitão! Graças a Deus! Que luta horrível!",
"Você está bem, Padre?",
"As crianças!",
"Onde elas estão?",
"Eles estão segurando as crianças em seu navio! Você deve ir atrás deles!",
"Muito certo. Aqui estão as chaves que encontrei no líder. Depois de lidar com o navio, vou levá-lo de volta à igreja.",
"Vou orar por você, #saddr#.",
"Vai ser uma grande luta, Padre. Ore por todos nós.",
"Tenha cuidado, capitão. Seu líder é astuto. Há uma sala atrás daquele trono.",
"Hum...",
"Estou com medo ",
" ouro é tudo o que posso pagar agora.",
"Eu deveria pensar que o Senhor olharia com bondade ",
" peças de ouro.",
"Estou bem ultimamente, então vou dar ",
"Muito obrigado por salvar a mim e às crianças, capitão.",
"Devo levar as crianças de volta aos pais e ir ver #sFatherBernard#. Adeus, Padre.",

};
