string DLG_TEXT[170] = {
". O que é, ",
"?",
"Posso te ajudar, ",
"?",
"Esta é sua primeira vez em nossa cidade, ",
"? Eu não te vi antes",
"Eu sou ",
", capitão e proprietário do navio'",
".' Eu tenho algumas perguntas se você tiver um momento.",
"Meu nome é ",
". Gostaria de lhe fazer algumas perguntas.",
"Você pode me chamar de capitão ",
". Eu só gostaria de algumas informações.",
"Olá, capitão ",
". O que traz você à nossa colônia?",
"Ah, capitão ",
". ",
", é você de novo. Espero que sua jornada tenha sido agradável. O que há de novo?",
"Olá, ",
". Como posso ajudá-lo?",
"Perdi alguma coisa enquanto estive fora?",
"Aconteceu alguma coisa interessante enquanto eu estive fora?",
"Que histórias os velhos cães-do-mar estão trocando por causa do rum hoje em dia?",
"Qual é a agitação nas tabernas?",
"Procuro fofocas, boatos, histórias fantásticas...qualquer coisa que eu não saiba pode ser útil.",
"Me conte algumas de suas fofocas mais recentes, amigo. Pode haver aventura ou dinheiro até mesmo no menor detalhe.",
"Ainda não consigo encontrar...",
"É impossível encontrar alguma coisa neste labirinto! Onde é...",
"Estou tão perdido quanto um navegador bêbado. De novo!",
"Você parece um morador local. Diga-me onde posso encontrar...",
"Por favor me diga como chegar a...",
"Tive um dia péssimo, então você nos salvará da dor se apenas me disser como encontrar...",
"Gostaria da sua opinião sobre um cidadão local.",
"Preciso saber o que você pode me contar sobre alguém que mora aqui na cidade.",
"O que você pode me contar sobre...",
"Conte-me tudo o que puder sobre um sujeito...",
"Espero que você possa me contar algo sobre uma pessoa que talvez conheça.",
"Este lugar não é muito grande  aposto que você conhece todo mundo que mora aqui. Vamos conversar.",
"Conte-me sobre #sPointe a Pitre#.",
"O que você pode me dizer sobre esse lugar esquecido por Deus?",
"Gostaria de saber mais sobre esta bela colônia.",
"Qual é a história desta cidade e da ilha?",
"Você sabe alguma coisa interessante sobre #sPointe a Pitre#?",
"...",
"Desculpe. Pensei que você fosse outra pessoa.",
"Estou apenas de passagem. Então fique de lado ou seja empurrado.",
"O que você gostaria de saber, ",
"?",
"O que lhe interessa, capitão?",
"O que você quer de mim?",
"Cidades como esta estão sempre nadando em fofocas. Dê-me os destaques.",
"Aconteceu alguma coisa interessante por aqui ultimamente?",
"Só quero saber o que está acontecendo na vizinhança. Alguém enganou um amigo? Alguém foi morto? O estalajadeiro é mesmo uma mulher? Você me entende.",
"Como posso chegar a...",
"Você pode me ajudar a me orientar aqui na cidade?",
"Onde posso encontrar...",
"Você pode me falar sobre alguém em quem estou interessado?",
"Gostaria de algumas informações sobre um colega local. Você pode ajudar?",
"Estou me perguntando o que as pessoas na cidade têm a dizer sobre uma determinada pessoa...",
"O que você pode me dizer sobre #sPointe a Pitre#?",
"Gostaria de conhecer a história da sua cidade.",
"Gostaria de obter algumas informações sobre esta colônia.",
"Estou apenas andando aqui. Vejo você mais tarde.",
"Obrigado. Tem mais uma coisa...",
"Foi bom conversar com você. Contanto!",
"Qualquer outra coisa, capitão ",
"?",
"Vamos ouvir isso, ",
".",
"Estou ouvindo, ",
".",
"Qual é o assunto da cidade hoje em dia?",
"Que histórias os velhos cães-do-mar estão trocando por causa do rum hoje em dia?",
"Já faz muito tempo que não ponho os pés nestas praias. O que eu perdi?",
"Você poderia me dar algumas instruções?",
"Fiquei completamente perdido nestas ruas.",
"É minha primeira vez nesta cidade e gostaria de algumas orientações.",
"Gostaria da sua opinião sobre um cidadão local.",
"Preciso saber o que você pode me contar sobre alguém que mora aqui na cidade.",
"Você poderia me dar algumas informações sobre os habitantes locais?",
"Conte-me sobre #sPointe a Pitre#.",
"O que você pode me dizer sobre esta colônia?",
"Gostaria de saber algo sobre #sPointe a Pitre#.",
"Acabei de perceber que preciso estar em algum lugar. Adeus.",
"Quem é que queres dizer,",
"?",
"Você está perguntando sobre alguém específico?",
"Sobre quem exatamente você quer saber?",
"Quero dizer, o governador.",
"Estou interessado no dono da taberna.",
"O dono do estaleiro.",
"Estou falando do comerciante local.",
"Ninguém. Deixa para lá.",
"Hmm... Você sabe, ele veio recentemente para nossa colônia. Ele é jovem e empreendedor, por isso tornou nossa colônia próspera.",
"Eu vejo. Eu tenho outra pergunta para você.",
"Obrigado tchau tchau.",
"Você sabe, ele é um homem legal, tem senso de humor e sua taverna é limpa. O mais importante é que ele sempre mantém a paz em sua taverna.",
"Eu vejo. Eu tenho outra pergunta para você.",
"Obrigado tchau tchau.",
"Eu realmente não o conheço bem. Dizem que ele é um sujeito chato. Pelo menos ninguém o vê na taverna. Alguém disse que está sonhando em construir um navio magnificamente grande.",
"Eu vejo. Eu tenho outra pergunta para você.",
"Obrigado tchau tchau.",
"Ele é muito ganancioso. Alguns dizem que ele era assistente de Baldewin Coffier, mas quando a loja faliu, ele a comprou por um preço baixo. Não sei a qualidade ou o preço de seus produtos, mas ele não parece ser uma pessoa muito... boa.",
"Eu vejo. Eu tenho outra pergunta para você.",
"Obrigado tchau tchau.",
"Onde você está indo, ",
"?",
"Não é um problema, capitão. Onde você precisa estar?",
"Fico feliz em orientá-lo ",
". Mas para onde você quer ir?",
"Como posso chegar à taberna?",
"Onde fica o estaleiro?",
"Onde posso vender os produtos que trouxe comigo?",
"Isso é une esprit, capitão? Você não consegue ver a placa à direita?",
"Certo. Obrigado pelo seu tempo.",
"Onde fica o estaleiro?",
"Onde posso conseguir um preço decente pelos produtos finos que trouxe para a cidade?",
"Logo após a ponte de pouso, vá para a direita e siga para a casa no final.",
"Eu vejo. E a taberna?",
"Onde posso conseguir um preço decente pelos produtos finos que trouxe para a cidade?",
"Eu acho que isso é tudo. Obrigado pela ajuda.",
"Todos vocês saíram depois da ponte de desembarque, ao lado da grande casa da esquerda.",
"Onde posso encontrar o estaleiro local?",
"Como faço para chegar à taberna?",
"Eu vejo. Obrigado pela informação.",
"Não sei por que você estaria interessado, mas por que não?",
"No que exatamente você está interessado ",
"?",
"Claro, ",
". Felizmente, é uma história bastante curta.",
"Estou interessado na história da colônia...",
"Conte-me sobre a colônia.",
"Existe alguma coisa na ilha além da cidade?",
"Tenho mais algumas perguntas para você, se não se importa.",
"Pois bem, a nossa colónia foi fundada há cerca de 50 anos, um dos primeiros assentamentos do arquipélago. Mas a colônia original ficava do outro lado da ilha; naquela época, os nativos viviam onde estamos agora.\nVários meses depois de ter sido estabelecido, o assentamento original foi destruído pelos espanhóis. Foi reconstruído aqui 10 anos depois.\nO forte foi construído para proteger a colônia, e não demorou muito para que nos enviassem nosso governador.",
"Obrigado. Deixe-me fazer mais algumas perguntas.",
"Sabe, eu realmente pensei que seria mais interessante. Deixe-me perguntar outra coisa.",
"Isso é tudo que preciso. Obrigado.",
"Obrigado pelo seu tempo. Até a próxima.",
"Na verdade. Além de algumas plantações, o resto da ilha está completamente deserto.",
"O que mais você pode me contar sobre a colônia?",
"O que mais você pode me dizer?",
"Não há mais nada para contar, na verdade. Nada aqui além da cidade. Eles tentaram construir minas em determinado momento, mas não funcionou.",
"Eu vejo. O que mais?",
"Não. Você encontrará algumas plantações e casas nesta parte da ilha, mas ela é praticamente subdesenvolvida.",
"Nesse caso, talvez você possa me contar mais sobre a colônia.",
"Entendi. Deixe-me perguntar outra coisa.",
"Você conhece um contramestre chamado Fred Bob?",
"O que você pode me dizer sobre o capitão do porto?",
"Ah, Fred Bob? Ele não é um amotinado, isso eu lhe garanto! Ele é um bom marinheiro e um homem forte para ter ao seu lado quando você está em menor número. Pena pela sua prisão. Todos esperamos que o governador o liberte, porque ninguém, exceto aquele pomposo primeiro oficial, acredita que ele é culpado.",
"Interessante. Ah, eu tenho outra pergunta para você.",
"Muito obrigado, adeus.",
"Não sei como ele faz isso, mas o nosso capitão do porto faz questão de conhecer todos os marinheiros do arquipélago.",
"Eu vejo. Mais uma pergunta, se não se importa, por favor?",
"Obrigado pelo seu tempo. Tchau.",
"Fred Bob? O contramestre? Ele é muito difícil de entender, mas meu irmão o conhece bem. Ele não é um amotinado. Esse oficial entendeu tudo errado. Todos esperamos que o governador o liberte. Ele pertence a um navio, não a uma paliçada.",
"Bom homem, excelente marinheiro. Não acredito nem por um minuto que ele ameaçou um motim.",
"Ehm... eu esqueci quem eu ia perguntar. Apenas me dê um segundo e isso voltará para mim...",
"Onde posso encontrar um ferreiro para polir minha espada?",
"Não temos ferreiro aqui.",
"Nenhum ferreiro? Que tipo de cidade é essa? Bem, gostaria de lhe perguntar outra coisa.",
"Nesse caso terei que levar minha espada para outro lugar para consertá-la.",
"Minha melhor espada favorita do mundo aqui ficou um pouco chata ultimamente. A quem posso confiar isso?",
"Não temos ferreiro aqui.",
"Maldito coelho! Você não pode estar falando sério. Onde diabos está um ferreiro para minha 'lâmina' quase inexistente?",
"Onde fica o estaleiro?",
"Onde posso conseguir um preço decente pelos produtos finos que trouxe para a cidade?",
"A quem posso confiar minha espada? Sua borda antes fina ficou um pouco embotada.",
" Temos uma população de ",
" cidadãos.",

};
