string DLG_TEXT[123] = {
"Desculpe! Eu não vi você aí. Perdoe-me.",
"Sem problemas. Essas coisas acontecem. Como estão as vendas?",
"O que? Vendas? Oh, eles estão...bem...",
"Você está bem?",
"Posso ver que você está ocupado. Vou deixar você voltar ao seu trabalho.",
"Desculpe. Você disse alguma coisa?",
"O que há de errado com você, #ssir#?",
"Nada importante. Acabei de dizer adeus.",
"Sim Sim, ",
", Estou bem.",
"Você é o homem que alguns moradores locais dizem que é louco, não é?",
"Eu vou indo, então.",
"Espere - não sei seu nome...",
"Meu nome é ",
".",
"Prazer em conhecê-lo. E eu sou ",
".",
"O que te incomoda ",
"?",
"É um prazer conhecê-lo, mas preciso ir. Talvez eu te veja mais tarde.",
"Não é nada, ",
". Sou um homem pequeno com pequenos problemas. Eles não são dignos de sua atenção.",
"Por que você não me deixa decidir o que merece minha atenção?",
"Você sabe, essa é a coisa mais sensata que ouvi de alguém em algum tempo. Você está certo - tenho meus próprios problemas para resolver. Os seus não são da minha conta.",
"Bem, eu não sei....",
"Qual é o mal em apenas me contar seus problemas? Talvez eu até consiga ajudar.",
"Bem, é problema seu, claro. Eu vou deixá-lo sozinho.",
"Tudo bem, eu vou te contar. Há algum tempo, um homem que se autodenominava ",
"Teodoro Fernandez",
"Teodoro Fernandez",
" veio até mim. Ele me pediu para comprar para ele algumas estatuetas indianas que haviam aparecido recentemente no arquipélago.\nMas eu não tinha dinheiro - esse ouro puro é muito caro nos tempos modernos....",
"Eles eram feitos de ouro?",
"Sim, eles eram. Disseram-me que pertenciam a um colecionador que os encontrou na selva daqui e decidiu levá-los para a Europa.",
"Mas ele não conseguiu fazer isso?",
"Acho que nos desviamos do caminho aqui. Vamos ouvir o resto da sua história.",
"Não, ele não fez isso. Seu navio foi capturado por piratas.",
"Eu vejo. E qual é exatamente o seu problema?",
"Oh sim. Bem, ",
"Teodoro Fernandez",
" ofereceu-me o dinheiro para adquirir essas estatuetas, e eu concordei.",
"Ele pagou adiantado? Isso não lhe pareceu suspeito?",
"Sim... mas eu estava ganhando 10.000 de ouro com o negócio. Como eu poderia recusar?",
"Não tenho certeza se estou acompanhando. ",
"Teodoro Fernandez",
" te enganou de alguma forma?",
"Parece-me que sua ganância colocou você em apuros ",
". Você terá que encontrar sua própria saída.",
"Bem, para ser honesto - eu não sei.",
"Você não sabe? Você tem um problema ou não?",
"O problema é este: aquelas estatuetas foram roubadas de mim ontem à noite. E ",
"Teodoro Fernandez",
" estará aqui em dois dias. Terei que devolver o dinheiro a ele.",
"Então você dá a ele o dinheiro dele. Qual é o problema?",
"Você não vê? Foi ele quem roubou aquelas estatuetas! Dessa forma, ele os obtém de graça.",
"Desculpe, ",
", mas você me perguntou...",
"Relaxar. Vou encontrar esse sujeito que te roubou.",
"Eu não pedi a história da sua vida!",
"Ah, obrigado! Você dá esperança a um homem desesperado.",
"Bom saber. Agora vamos falar sobre o dinheiro que você vai me pagar pela minha ajuda.",
"Você provavelmente está certo. Estou inclinado a acreditar nisso também. Mas não tenho provas.",
"Obteremos as evidências, se existirem. A única coisa que resta determinar é quanto receberei pela minha ajuda.",
"Não tenho muito dinheiro agora. Que tal 3.000?",
"Você acabou de me dizer que ganhou 10.000 adiantados - e só me oferece 3.000? Precisarei de pelo menos 50 porcento para meus serviços.",
"Eu acho que você poderia poupar mais, mas suponho que seja um acordo.",
"Bem, se você não me ajudar, não ganho nada. Então suponho que seja justo.",
"Então temos um acordo. A propósito, me descreva como ",
"Teodoro Fernandez",
" se parece?",
"Não, não posso concordar com isso.",
"Por que não? Sem mim você perde tudo!",
"Não tenho certeza se precisarei de sua ajuda. Falei com um guarda mais cedo e ele prometeu me ajudar.",
"Então acho que não temos um acordo. Muita sorte.",
"Tudo bem então. 3000 é.",
"Estarei aguardando novidades, ",
".",
"Espere, como era esse homem?",
"Ele é um espanhol alto, com longos cabelos pretos e uma cicatriz no rosto.",
"Tudo bem. Te vejo em breve.",
"Saudações, ",
".",
"Olá.",
"Saudações, ",
", como vai a missão?",
"Ainda não há resultados, mas estou trabalhando nisso.",
"Eu vi ",
"Teodoro Fernandez",
"! Ele entrou naquela casa à esquerda da igreja!",
"Bom. Fique aqui. Vou visitá-lo",
"O tempo está bom hoje, não está?",
"Como sempre. Deixe-me ver o que você tem.",
"Talvez seja. Estou muito ocupado para notar. Se você me der licença, irei embora.",
"Obrigado, mas preciso ir agora.",
"Você pode me contar algo sobre a cidade?",
"Oh, ",
"! Obrigado! Um guarda esteve aqui há poucos minutos e me disse que você ajudou a encontrar as estatuetas e a prender Teodoro.",
"Estou feliz por poder ajudar.",
"Bem, como vai? Teodoro estará aqui em breve!",
"Desculpe; Eu não pude te ajudar.",
"Encontrei as estatuetas - e o ladrão. ",
"Nesse caso, suponho que terei que fechar as portas para sempre. Eu estava realmente contando com você, capitão.",
"Adeus.",
"Então, aconteceu que ",
"Teodoro Fernandez",
" era o ladrão?",
"Foi ele quem contratou os ladrões. Mas eles não estão por perto para contar sobre isso agora",
"Você é um aliado formidável, capitão! Obrigado pela ajuda. Aceite este dinheiro como um sinal de minha gratidão.",
"Até a próxima.",
"Inversão de marcha. A taverna está logo atrás de você ",
".",
"Obrigado. Tenho mais algumas perguntas.",
"Obrigado. Isso é tudo que eu queria saber.",
"Para encontrar a loja, você precisa passar pelo portão à direita da minha barraca.",
"Obrigado. Tenho mais algumas perguntas.",
"Obrigado. Isso é tudo que eu queria saber.",
"Então você precisa visitar o escritório do estaleiro. Fica à esquerda da minha barraca, perto dos portões. Vê aquele prédio de dois andares? Basta subir aquelas escadas.",
"Obrigado. Tenho mais algumas perguntas.",
"Obrigado. Isso é tudo que eu queria saber.",
"Você é um aliado formidável, capitão! Obrigado pela ajuda. Porém, conte a um guarda ou oficial sobre isso, por favor - não posso abandonar minha barraca e não quero que nenhum descontentamento caia sobre você por lidar com #sLucien#. Acho que vejo um andando por aí...",
"Você é muito bem-vindo. Deixe-me ir procurá-lo.",
"Como quiser. Gostaria de ver o que tenho à venda?",
"Certamente. Talvez você tenha algo que eu queira.",
"Agora não, obrigado. Estou bastante ocupado, então se você não se importa, irei embora.",
};
