string DLG_TEXT[23] = {
"Siga em frente! Limpem as ruas!",
"...",
"Ei você aí! Você me parece suspeito. Quem diabos é você? Mostre-me seus papéis!",
"Quem diabos é você? Identifique-se e seja rápido!",
"Pare! Nunca te vi antes, mas você tem cara de pirata! Você pode provar que não é ninguém?",
"Eu sou ",
", e aqui estão minha comissão e os documentos do navio, para provar isso. Isso foi rápido o suficiente para o seu temperamento explosivo?",
"Ah, sim, claro, senhor! Aqui, minha identificação está nesta bolsa, logo abaixo dos 200 Gold. *PISCAR*",
"Se você não se perder imediatamente eu vou te mostrar o quão rápido eu sou... com minha lâmina!",
"Não se atreva a se dirigir a um superior dessa maneira novamente, seu mercenário insolente! Você não me conhece? Sou o Inspetor Real dos Regimentos Caribenhos de Sua Majestade e acabo de chegar com o último navio para inspecionar nossas tropas aqui! Agora não me moleste mais, ou você terá que explicar ao seu comandante por que perdi o encontro com ele!",
"Ah, sim, a imagem nas moedas identifica você como um #spronoun# que gosta de guardas mal pagos, hehe. Tudo bem, vou deixar você passar, mas só desta vez. E comporte-se!",
"Claro! Quem você acha que eu sou? Um ladino? *PISCAR*",
"Eu não confio em você! ALARME! LEVANTE A MILÍCIA!",
"Boa tentativa marujo, mas comigo não cola! ALARME! Um espião! Soeem o alarme e avise a todos!",
"O que é isso? ALARME! Um pirata!",
" Parece que minhas HABILIDADES foram insuficientes para ESSA abordagem. Ou foi apenas azar? Bem",
" Espero que minha esgrima tenha mais sucesso do que minha atuação...",
"Hum... err... entendo. Desculpe por ter incomodado você, #ssir#. Adeus.",
"Tudo bem, continue, e uma vigília tranquila para você.",
"Você não leu as placas de 'PROIBIDO ENTRADA' no portão? Esta é uma fortificação ultrassecreta do Exército, e apenas soldados da Brigada Costeira de elite podem entrar. Qualquer outra pessoa será considerada um espião! Especialmente certos capitães corsários!",
"Sinal? Desculpe, não consigo ler. E eu tenho um compromisso urgente com o inspetor real... eh, quero dizer, eu sou o inspetor e tenho...",
"Algum pedido, #ssir#?",
"Nada por enquanto.",

};
