string DLG_TEXT[67] = {
"Bem-vindo à minha taverna, estranho. Meu nome é ",
". O que o traz ao meu humilde estabelecimento? Você precisa de um lugar para descansar?",
"Obrigado. Meu nome é ",
". Eu estou aqui a negócios.",
"Meu nome é ",
", e você pode poupar sua hospitalidade. Eu estou aqui a negócios.",
"Bem-vindo, #ssir#! O que você quer?",
"Preciso de algumas informações e acho que o estalajadeiro local geralmente é a pessoa certa para perguntar.",
"Estou procurando contratar alguns marinheiros para meu navio.",
"Aponte-me os clientes aqui que podem estar procurando emprego. Preciso aumentar minha equipe e não me importo se eles forem assassinos.",
"Você tem um quarto? Eu gostaria de ficar aqui por um tempo",
"Você tem uma cama grátis neste casebre?",
"Não tenho nenhum negócio com você agora. Adeus.",
"Isso é verdade. Eu ouço quase tudo. O que você quer saber?",
"Eu preciso de um emprego. Você não conhece nenhum garoto rico nesta ilha que tenha medo de viajar sozinho?",
"Não tenho perguntas no momento. Vamos falar sobre outra coisa.",
"Talvez eles tenham. Existem muitos rumores por aí.",
"Pressa. Sou um homem ocupado.",
"É um pouco tarde para encontrar bons marinheiros. Eles já estarão todos dormindo ou desmaiados. Volte de manhã - ou você pode passar a noite aqui na taverna.",
"Tudo bem. Você tem um quarto?",
"Não preciso de um quarto no momento. Vamos falar sobre outra coisa.",
"Eu tenho uma vaga. Quanto tempo você vai ficar?",
"Durante a noite.",
"Só até escurecer.",
"Certo. Serão 5 peças de ouro.",
"Tudo bem. Aqui você vai.",
"Infelizmente, acho que não posso pagar nada melhor do que uma noite no salão da taverna.",
"O que isso vem com uma equipe pessoal? Eu vou passar.",
"Vou pensar sobre isso.",
"Certo. Serão 5 peças de ouro.",
"Tudo bem. Aqui você vai.",
"Infelizmente, acho que não posso pagar nada melhor do que uma noite no salão da taverna.",
"Isso é demais. Eu vou ficar no salão da taverna",
"Vou pensar sobre isso.",
"Caros visitantes! Por favor, pare com essa indignação! Não me obrigue a chamar os guardas!",
"Tudo bem, tudo bem! Eu já fui!",
"Se for, eles preferem navegar com menos satélites, você sabe disso",
"Sim, esqueci. Tudo bem, voltarei mais tarde, quando tiver menos navios, ha-ha.",
"Eu não quero ajudar você. Você causou muitos problemas ao meu país",
"Basta olhar para este patriota. Bem adeus.",
"Suas mãos estão cobertas de sangue. Você não acha seriamente que alguém viajaria com você, não é?",
"Você está certo, todo mundo tem medo de mim! Ha-ha!",
"Você chegou bem na hora. Um comerciante aqui estava procurando a companhia certa para viajar. Você deveria falar com ele. Lá está ele, acabando de entrar na taverna.",
"Eu farei isso.",
"Não, não há ninguém assim no momento, Talvez da próxima vez.",
"Hmm, então vou esperar.",
"Bem-vindo, capitão! Eu sou ",
". Tome uma bebida grátis graças ao nosso governador!",
"Eu sou ",
". Por que tanta generosidade?",
"Sua filha",
"O filho dele",
" acabou de ficar noivo de ",
"o filho",
"a filha",
" de algum inglês rico em #sRedmond#. Assim, todos ganham uma bebida grátis, desde que levantem suas taças para o casal feliz.",
"Bem, nesse caso, vida longa e felicidade para os dois - felicidades!",
"Estou trabalhando para Lady Carranza. Quero falar com Abel Barco. Você conhece ele?",
"Na verdade. Ele apenas me pagou para informá-lo quando alguém que trabalha para Lady Carranza perguntasse por ele. E para te dizer, amanhã ele te esperará fora da cidade.",
"Tudo bem, diga a ele que estarei lá.",
"Por acaso você já viu uma Bíblia espalhada por aí em algum lugar?",
"Sim, esta linda Bíblia aqui foi levada aos 'achados e perdidos'. Um marinheiro deixou-o em cima da mesa.",
"Maravilhoso! Deixe-me devolvê-lo ao legítimo proprietário.",
"Devo pedir desculpas, mas o Capitão Torres reservou todos os meus quartos para ele e seus oficiais.",
"Vou ficar no salão da taverna, então.",
"Infelizmente, isso também não será possível. Um guarda municipal acabou de me aconselhar a não deixar as pessoas beberem aqui a noite toda, porque muitas vezes elas causam problemas. Ele não está errado. Você deveria ter visto esse marinheiro esta noite, ele mal conseguia sair pela porta. Aposto minhas botas que ele não foi muito longe...",
"Tudo bem então, não durma para mim! [PENSA:] Talvez eu não devesse dormir agora! Alguns dos marinheiros ainda estão soltos!",
};
