string DLG_TEXT[32] = {
"Eu tenho que trabalhar, você sabe!",
"Desculpe.",
"Se houver algo errado, fale com o mestre...",
"Não, não há.",
"Quando esse dia vai acabar!?",
"Em breve, tenho certeza...",
"Um clima tão insuportável... e eu tenho que trabalhar duro nele! Considere-se o #sgender# mais sortudo do mundo!",
"Desculpe, não posso ajudá-lo. Não sou seu chefe, infelizmente",
"Não posso falar agora, tenho muito trabalho a fazer e não é meu dever interagir com sua espécie....",
"Calma, vou te deixar em paz agora...",
"Você acha que é fácil fazer isso o dia todo? De jeito nenhum! É um trabalho inútil e pouco gratificante. Estou farto.",
"Meu amigo, vou tentar o meu melhor para te ajudar, sério... vou!",
"Vá embora! Não me incomode.",
"Como você diz, escravo.",
"Ei! Você pode me trazer um pouco de rum?",
"Não tenho permissão para ajudar um trabalhador escravo enquanto ele trabalha. Não, espere até terminar, se algum dia terminar... E então você pode beber o quanto quiser.",
"Não há pessoas dispostas a me salvar nesta cidade?",
"Continue com seu trabalho. Olha, você não gostaria de deixar de impressionar seu dono, não é?",
"Você vai me ajudar?",
"Você parece bem em forma. Junte-se ao exército! Você poderia até sair deste inferno!",
"Esse calor e umidade....! Eu daria tudo para voltar para casa, para a África.",
"Eu sinto sua dor.",
"O que você quer?",
"Estou aqui pelo café que você tem cultivado. Onde posso retirá-lo?",
"Está tudo nos celeiros no fundo dos campos. Tem muito disso também!",
"Obrigado.",
"Nossas vidas são difíceis. Não somos respeitados o suficiente pelo trabalho que fazemos!",
"Bem, vocês são escravos...",
"Você se juntará a nós, se tornará um de nós e nos ajudará a escapar!?",
"Não é uma má ideia, eu vou te ajudar!",
"Obrigado #ssir# por matar os guardas.",
"Saia daqui, você está livre!",

};
