string DLG_TEXT[39] = {
"Vamos receber seu convite para verificar se é autêntico.",
"Bem, eu ganhei jogando dados, então espero que seja real. Como eu poderia verificar?",
"Deveria ser, você me deu no último torneio",
"Acho que você quer dizer que meu irmão fez isso, mas ainda preciso verificar se é genuíno.",
"Duvido que alguém falsifique um, meu irmão ficaria muito chateado e levaria isso para o lado pessoal, não é algo que qualquer pessoa sã gostaria de arriscar, mas...",
"(gole)",
"Você conhece o seu próprio negócio, suponho.",
"O torneio dura três dias, você enfrenta os outros três competidores, um em cada dia.",
"Você inicia um concurso com 10.000 fichas. Cada disputa dura no máximo 50 mãos e se esse limite for atingido, ganha quem tiver a maior pilha naquele momento. Caso contrário, se você perder ou ganhar todas as fichas antes disso, é claro que esse será o resultado.",
"O campeão geral é o jogador com mais vitórias individuais em três dias. Eles ganham 60.000 e o troféu até o próximo torneio. É claro que cuidamos do troféu para eles e lhes damos uma pequena réplica para guardarem.",
"É um bom ganho para mim e meu irmão, então não queremos que ninguém mexa com isso ou conosco. Entender?",
"Parece bastante simples.",
"Meu irmão e eu somos os árbitros finais em todos os assuntos  portanto, nunca há problemas que não possamos resolver. Capiche?",
"Claro como cristal.",
"Certo, está tudo em ordem, você pode entrar na sala de jogos e sentar-se agora.",
"O que nem é uma 'boa sorte'?",
"Essa é a sua primeira luta, volte amanhã para a próxima.",
"Tudo bem, eu poderia fazer uma pausa.",
"Bem vindo ao segundo dia do torneio, seu oponente está esperando. Então, se você estiver pronto para sentar-se",
"Então ainda nem um 'boa sorte'!",
"Só mais uma rodada para você amanhã.",
"Sim, parece um Deja Vu.",
"Oh, finalmente é você, todos nós estávamos esperando! Vá em frente. Sente-se para o terceiro dia.",
"É evidente que você ganhou dinheiro com este evento agora.",
"Parabéns ao nosso digno vencedor.",
"Obrigado pela oportunidade de competir.",
"Todos os quatro competidores recebem um convite para o próximo torneio em seis meses. Eles são seus para mantê-los até então, se quiser tentar a sorte novamente, negociar ou vender. No entanto, estaremos acompanhando seu progresso com interesse.",
"Eu voltarei.",
"Você chegou tarde demais e perdeu o concurso, o dinheiro da sua aposta e qualquer participação futura. Você também está proibido de entrar nessas instalações. Agora saia.",
"Desculpe, fui emboscado. Ah bem.",
"Sente-se agora, suas fichas estão na mesa e o primeiro dia do torneio pode começar.",
"Você não me parece um tipo de jogo.",
"Eu não acertei você de jeito nenhum, cara. Afinal, não queremos uma briga feia!",
"Quem você está chamando de feio? Talvez eu devesse chamar meu irmão.",
"Por que? Você se acha mais bonita que ele?",
"Olha, quem quer que seja, fale com o meu homem lá.",
"Ok, foi apenas um mal-entendido, suponho.",
"Comiserações a um galante perdedor.",
"Aqui está o seu prêmio em dinheiro e a miniatura do troféu.",
};
