string DLG_TEXT[17] = {
"Este clube é propriedade privada. Casa do torneio Grand Turk Poker.",
"Me desculpe, eu só queria dar uma olhada",
"Não há entrada na sala de jogos. Somente para membros e competidores em dias de torneio.",
"É uma pena que talvez eu comece a jogar no futuro.",
"Tentando espionar a localização, hein? Bem, não há entrada na sala de jogos. Somente para membros e competidores em dias de torneio.",
"Estou de saída.",
"Talvez você retorne para o próximo torneio, mas por enquanto, como não é membro, Push Off.",
"OK, estou a caminho.",
"Volte amanhã! Tenho que fazer você sair do local?",
"Não, eu posso encontrar minha própria saída.",
"Você tem um convite e uma taxa de torneio? São 20.000, você sabe",
"Sim, tenho os dois aqui.",
"Recebi o convite, mas estou com falta de honorários.",
"Esta não é uma empresa de caridade que você conhece. Volte apenas quando você tiver os dois, enquanto isso, scram!",
"Basta ir até a sala de jogos para a competição.",
"Você chegou tarde demais e perdeu o concurso, o dinheiro da sua aposta e qualquer participação futura. Você também está proibido de entrar nessas instalações. Agora saia.",
"Desculpe, fui emboscado. Ah bem.",

};
