string DLG_TEXT[26] = {
"Basta jogar todas as mãos, você não pode perder todas.",
"Um par de bolas vence tudo!",
"É moralmente errado deixar um otário ficar com o seu dinheiro.",
"No longo prazo não há sorte no pôquer, mas o curto prazo é mais longo do que a maioria das pessoas pensa.",
"Você mostra sua coragem pelas mãos que você desiste e não pelas mãos que você joga.",
"Poker é guerra. As pessoas fingem que é um jogo.",
"O pôquer é uma maneira difícil de ganhar uma vida fácil.",
"O que há de bonito no pôquer é que todos pensam que podem jogar.",
"Se você perder a cabeça, perderá todas as suas fichas.",
"O pôquer é 100% habilidade e 50% sorte.",
"Quando um jogador com dinheiro encontra um jogador com experiência, o jogador com experiência sai com o dinheiro e o jogador com dinheiro sai com experiência.",
"O pecado capital no pôquer é envolver-se emocionalmente.",
"Não desafie jogadores fortes, desafie os fracos. É para isso que eles existem.",
"Quem cunhou a frase um homem tem que jogar a mão que lhe foi dada foi certamente um pobre blefador.",
"O pôquer é muito parecido com sexo. Todo mundo pensa que é o melhor, mas a maioria não tem ideia do que está fazendo.",
"Os antigos jogadores de cartas nunca morrem, apenas embaralham.",
"A regra é esta: você vê o que um homem diz, você não diz uma palavra.",
"Ninguém é sempre um vencedor, e quem diz que é, ou é mentiroso ou não joga pôquer.",
"O pôquer é uma aventura fascinante, maravilhosa e complexa nos altos mares da natureza humana.",
"Um coração fraco nunca preencheu um flush de espadas.",
"Os cães são péssimos jogadores de pôquer. Quando conseguem uma boa mão, abanam o rabo.",
"O que eu sei sobre pôquer cabe em um dedal com espaço sobrando, mas estou aprendendo.",
"Certo, err, OK.",
"Errado, certo, ok.",
"Não deixe isso afetar você.",
"E?",
}
