string DLG_TEXT[80] = {
"Vá embora, não me incomode",
"...",
"Ah, vamos lá, querido capitão. Eu sei o que lhe interessa.",
"Com licença, capitão, mas tenho algumas informações que podem lhe interessar. Coisas que podem ajudá-lo.",
"O que pode ser isso?",
"E o que você poderia ter que me interessasse?",
"Ah! Hee-hee. Não se precipite, capitão. Primeiro, vamos discutir o pagamento. Eu prometo que você não conseguirá descobrir nada sem mim.",
"Está aqui para fechar um acordo, capitão? Um punhado de moedas em troca de alguma informação sobre o Sr. Rheims?",
"Lembre-me. Quanto você quer?",
"Você é ",
"?",
"Talvez. Você sabe alguma coisa sobre bugigangas indianas?",
"Sim, sim, #ssir#. E um pouco mais sobre o assunto, se você me entende.",
"Posso lhe mostrar o caminho, mas guiá-lo por esses caminhos traiçoeiros lhe custará algum dinheiro. Se preferir ir sozinho, eu lhe mostrarei o caminho e você poderá seguir sozinho.",
"É melhor você vir comigo e me mostrar como chegar lá",
"Diga-me como chegar lá, e eu irei sozinho",
"Não se preocupe, capitão, estaremos aí em breve.",
"É melhor...",
"Você está ficando para trás, capitão. Mantenha o ritmo.",
"Isto é ridículo. Acho que é melhor você me dizer onde estamos",
"Oh, não tente me segurar. Eu sei o que você está fazendo. Talvez eu mesmo pegue todo o seu dinheiro",
"O que?",
"Não tão rápido, ",
", custará 100 ouro.",
"Justo. Aqui está o seu dinheiro.",
"Você quer demais! Apenas me dê instruções e eu mesmo encontrarei.",
"Ha! Você é barato ou estúpido, talvez ambos. Tudo bem, ouça. Vá fundo na selva agora até ver a bifurcação.\nUm caminho vai para a esquerda e outro direto. Escolha aquela que segue em frente.\nMais tarde você verá outra bifurcação e deverá continuar em frente novamente.\nQuando chegar à terceira bifurcação, vire à esquerda, você estará exatamente onde deveria estar.",
"Isso é muito para lembrar. Espero não me perder.",
"Ótimo, vamos agora.",
"Mostre-me o caminho, mas sem truques. Ficarei de olho em você o tempo todo. ",
"Sim. Vamos em frente, há muitos que gostariam de nos espionar.",
"E para onde você propoe que vamos? Eu não sou...",
"Calma, não vou te machucar. Vamos apenas dar um passeio.",
"Tudo bem, mas lembre-se que sei me defender.",
"Claro, claro, acalme-se, posso dizer que você é um #sgentleman# capaz. Venha agora, chega de papo, vamos em frente.",
"Lidere o caminho.",
"Aqui estamos. E já que tenho coisas para fazer, vou te deixar agora",
"Adeus.",
"Deixe-me ser claro. Me dê o seu dinheiro!",
"Eu te avisei, sou capaz de me defender. Você está prestes a descobrir o quão capaz eu realmente sou.",
"Eu sei quem você está procurando. Posso te ajudar.",
"Eu sei quem você está procurando. Posso te ajudar.",
"O que você sabe?",
"Diga-me o que você sabe.",
"Ei, vamos discutir o pagamento primeiro. Você acha que vou lhe dar essas informações de graça?",
"Hmm... acho que mereço uma recompensa pelos meus serviços.",
"Quanto você quer?",
"Bem, de quanto você precisa?",
"Dê-me 1.500 ouro e eu lhe contarei tudo o que sei.",
"Nada demais... apenas 1.500 ouro.",
"Pegue o seu dinheiro.",
"Aqui, pegue. Agora me conte tudo o que você sabe sobre esse sujeito.",
"Isso é uma quantia considerável. E talvez não valha tanto para mim...",
"Você não acha que isso é demais?",
"Você tem um bom talento para extorsão. Mas você já pensou no que aconteceria se eu não quisesse pagar tanto ouro?",
"Sem dinheiro - sem informação. Volte quando puder me pagar",
"Se for importante para você, mais cedo ou mais tarde você terá que me pagar.",
"Pegue o seu dinheiro.",
"Aqui, pegue. Agora me conte tudo o que você sabe sobre esse sujeito.",
"Então retornarei se ainda precisar dessa informação.",
"Por que eu deveria acreditar que você é o único fanfarrão que pode me dizer o que preciso saber?",
"Isso é uma quantia considerável. E talvez não valha tanto para mim...",
"Troquei algumas palavras com um marinheiro da tripulação daquele sujeito, e ele me disse que eles estavam indo para #sisland_Conceicao#.\nEle disse que eles tinham alguns negócios com o chefe dos contrabandistas locais chamado Desmond Ray Beltrop.",
"Ótimo! Agora afaste-se agora, estou com pressa.",
"Vou dar uma olhada. Se esta sua informação for inútil, retornarei e não serei tão educado. Está claro?",
"O que você quer dizer?",
"Deixe-me ser claro. Você quer viver? Agora você me entende?",
"Eu não tenho tanto dinheiro!",
"Tudo bem, então me dê tudo o que você tem e me diga o que você sabe.",
"Eu não acredito nisso, você, você... você está me ameaçando?",
"Parece a coisa apropriada a fazer. Agora me dê seu dinheiro agora e me conte tudo o que você sabe",
"Inacreditável. Eles estavam certos sobre você, duro como pregos. Aqui, pegue. Isso é tudo o que eu tenho.",
"Bem, isso certamente não é muito. Espero que suas informações sobre o rumo que Reims estava tomando valham mais.",
"Raoul Rheims",
"Tudo bem, tudo bem, acalme-se. Vou te contar tudo agora mesmo.",
"Se apresse!",
"Ah, seu porco imundo! Vou fazer você lamber minhas botas para limpar!",
"Você não acha que isso está indo longe demais?",
"...",
"...",

};
