 string DLG_TEXT[27] = {
"Você deveria saber, já faz muito tempo que não faço esse tipo de coisa.",
"Espero que isso não afete sua capacidade de lutar.",
"Muito pelo contrário, estou ansioso por isso.",
"Bem, não fique muito ansioso para desenhar aço, já existe risco suficiente.",
"Está muito quieto aqui. Isso significa problemas.",
"Para o inimigo, talvez...para nós, o silêncio é nosso aliado.",
"Mas e se formos capturados, capitão?",
"Eles vão nos enforcar, eu acho. Ou nos decapite. Ou queimar...",
"Me poupe. O que vamos fazer, capitão?",
"Você viu o encouraçado francês ancorado aqui?",
"Sim, eu a vi. Um navio temível, de fato.",
"Nós vamos capturá-la.",
"Você está brincando, ",
"? E como você propoe que façamos isso? Não seremos nem capazes de nos aproximar dela - uma salva daquelas armas e estaremos perdidos.",
"Ah, mas a tripulação do navio recebeu licença para desembarcar e agora está em terra, desfrutando de comida e bebida. A única tripulação a bordo é o vigia.",
"Eu vejo! Podemos subir a bordo, pegar o navio e nos juntar à esquadra inglesa! Ah, com certeza haverá tesouros e honras. Você será um herói, jovem rapaz.",
"Bem, esse não é exatamente o plano. Duvido que possamos navegar nela. Somos muito poucos para tripular um navio como esse.",
"Então o que vamos fazer?",
"O porão do navio está carregado de pólvora. Vamos explodi-lo em pedaços!",
"Oh meu Deus! E se explodirmos com ela? E mesmo que não estejamos, uma explosão a bordo daquela besta acordará todos na cidade!",
"Se você está com medo - você pode ficar aqui",
"Ah não, eu vou com você! Ninguém me chama de covarde!",
"Vamos então.",
"À sua disposição, capitão.",
"Então, você está pronto para ser voluntário?",
"Sim, iremos acompanhá-lo.",
"Tudo bem então vamos.",

};
