string DLG_TEXT[36] = {
"É você quem está pedindo ",
"Desmond Ray Beltrop",
"?",
"Sim. Eu gostaria de falar com ele.",
"É assim mesmo? Você deveria saber ",
"Desmond Ray Beltrop",
" não é fácil conversar",
"Obrigado pela dica, mas a menos que você marque um encontro com ele, irei embora.",
"Digamos que eu seja associado de ",
"Desmond Ray Beltrop",
" e se você quiser uma audiência com ele, terá que falar comigo.",
"Bem, minha conversa com ele não é para seus ouvidos. Leve-me ao seu chefe ou afaste-se. Posso encontrá-lo sozinho, sem a sua ajuda.",
"Nesse caso, tenho uma ideia: leve-me ao seu chefe ou eu te acompanho.",
"Posso levar você até ele, mas você precisa entregar sua espada e sua arma.",
"Você se acha durão? Um estalar de dedos e não sobrará nada de você!",
"Vou com minhas armas, ou não vou, e vou encontrar ",
"Desmond Ray Beltrop",
" sem a sua ajuda.",
"Depois que eu atirar em seu fígado, você viverá talvez algumas horas e morrerá com uma dor terrível.",
"Você quer falar com ",
"Desmond Ray Beltrop",
" ou não? Dê-me suas armas ou trocaremos golpes!",
"Se você atirar em mim, você mesmo morrerá.... Então acho que você está blefando.",
"Eu disse tudo o que direi. Leve-me até ",
"Desmond Ray Beltrop",
", ou deixe-me encontrá-lo sozinho.",
"Então me leve para ",
"Desmond Ray Beltrop",
", ou você terá que lidar com meu aço.",
"Vamos, mas eu te aviso que ",
"Desmond Ray Beltrop",
" não vai gostar nem um pouco disso.",
"Calma, vou te levar para ",
"Desmond Ray Beltrop",
", e então o problema é seu.",
"Agora estamos falando. Conduza-me.",

};