string DLG_TEXT[60] = {
"Você não vê que estou de serviço! Não me incomode.",
"Tudo bem, tudo bem.",
"Quem é você?!",
"Eu... bem... é...",
"Espere um minuto, senhor, temos algumas perguntas para você.",
"Sim?",
"Você é ",
"Sou eu, qual é exatamente o problema?",
"Gostaríamos de revistá-lo porque você é suspeito de roubo.",
"Sério, é até engraçado! Mas se você insiste, então, por favor, reviste.",
"Para algum soldado vasculhar meus bolsos?! Você está louco?!",
"Obrigado pela sua cooperação. Então... hmm... hmm... sim... e essa coisa também pertence a você?!",
"Isto? O anel? Ahem... Não tenho ideia de como ele foi parar no meu bolso.",
"Bem, então, sugiro que você venha conosco.",
"O que?! Tudo bem, tudo bem, não peguem suas espadas, eu obedecerei, sou inocente.",
"De jeito nenhum! Isso tudo é uma armação e eu não vou a lugar nenhum com vocês!",
"Ok, agora entreguem suas armas, por favor.",
"Aqui está, não tenho nada a temer.",
"Minha espada? Você não quer muito?!",
"Obrigado, agora venha...",
"Estou seguindo você.",
"Nesse caso, teremos que detê-los à força.",
"Ha! Tente!",
"É que alguém quer você morto. Diga olá ao diabo, otário.",
"Diabo!",
"Uh. Vejo que estou incomodando... Bem, devo ir?",
"Quero denunciar um roubo, policial.",
"(Para Jean Maginot): Você é suspeito de contrabando e roubo de propriedade pessoal deste homem.",
"(Para Jean Maginot): Você é suspeito de roubar propriedade pessoal desta pessoa.",
"Bah! Que audácia! Você foi declarado inimigo do estado, uma recompensa foi colocada em sua cabeça, e você quer me informar sobre o roubo?! Guardas!",
"Diabo... Eu não pensei...",
"O que isso tem a ver comigo? Vá a um juiz civil.",
"Eu, o capitão, devo apelar a um juiz civil? Bem, você tem ordem aqui!",
"Oh, desculpe, eu não sabia... esse fato muda o assunto e estou ouvindo você com atenção, monsieur.",
"De vez em quando eu lido com Jean Maginot, o dono da loja... Não me entenda mal, nada ilegal...",
"Por favor, continue.",
"Então, dessa vez, parei para perguntar o que ele tinha de novo e ele se ofereceu para me vender um pouco de sândalo!",
"Mas o problema é que não nos damos muito bem, e ele está sempre tentando me enganar.",
"Você tem certeza sobre isso?!",
"Mais do que isso, oficial! E quando eu disse a ele que era contra a lei, ele ficou realmente bravo comigo. Nós discutimos, e quando saí da loja, descobri que meu anel e minha carteira tinham sumido.",
"Vamos com você até a loja para resolver a situação na hora.",
"Estou seguindo você, policial.",
"Continue...",
"Em geral, nós brigávamos muito, e quando saí, descobri que alguns dos meus pertences pessoais tinham sumido.",
"Vamos com você até a loja para resolver a situação na hora.",
"Estou seguindo você, policial.",
"(Para Jean Maginot): É isso que vamos verificar. Se importa se eu revistar seus pertences e as dependências da loja?",
"(Jean): Eu protesto! Por que eu deveria ser submetido a tal humilhação?",
"(Para Jean Maginot): Sua falta de cooperação não joga a seu favor, monsieur. Goste ou não, vou revistar você e esta loja.",
"(Jean): Ah, tudo bem! Olha, depende de você!",
"(Algum tempo depois, para Jean Maginot): Bem, bem, bem... Estes são os itens pertencentes ao #snoble# que veio comigo, e há contrabando no seu porão.\nSinto muito desapontá-lo, mas até que a investigação oficial seja concluída, estou fechando a loja e pedirei que você venha comigo.",
"(Jean): Eu não sou culpado! Fui enganado!",
"O tribunal resolverá tudo. E agora vou pedir a você, Jean, para vir comigo, e você, #ssir#, vou pedir que saia da loja.",
"Ok...",
"(Para Jean Maginot): Vamos verificar isso agora... então... o que é isso? Isto é seu?",
"(Jean): N-n-não... Não sei como consegui...",
"(Para Jean Maginot): Bem... roubo... é, no mínimo, confisco de propriedade e trabalho duro...",
"(Você, interrompendo o oficial): Uh-uh! Trabalho duro? Talvez possamos fazer um acordo com ele. A pedreira é uma punição muito dura.",
"Bem... Não vejo razão para incomodá-lo.",
"Obrigado, oficial.",
};
