string DLG_TEXT[95] = {
"Olá, ",
", sinto muito, mas estou com pressa e não posso falar com você.",
"Com licença, isso só levará um momento. Você tem um irmão cujo nome é #sMarc#?",
"Mas espere! Tenho novidades sobre o seu irmão.",
"Olá, ",
", eu queria que você soubesse disso ",
"Orável Caron",
"Orável Caron",
" não vou incomodá-lo novamente.",
"Tudo bem, você pode ir. Não vou te atrasar mais.",
"Qual é a pressa?",
"Espere! Eu quero ajudar você. Eu entendo que você tem um problema.",
"Não tenho muito tempo. Meu pai, ",
"Milon Blacque",
"Milon Blacque",
", não está bem. Não posso deixá-lo sozinho por muito tempo",
"Ah, ele é o velho que mora perto do cais?",
"O que há de errado com ele?",
"Espero que ele se recupere. Adeus.",
"Sinto muito, ",
", mas eu realmente preciso ir.",
"Sua garota teimosa! Tudo bem, vá embora com você.",
"Sim, ele é meu pai.",
"Ouvi dizer que ele não está em seu juízo perfeito. Isso é verdade?",
"É uma pena o que aconteceu com seu pai. Dizem que ele é louco e estou inclinado a concordar.",
"Ele não me pareceu doente.",
"Se você está tão interessado em meu pai, pergunte a quem gosta de abanar a língua.",
"Sinto muito. Eu não queria te ofender.",
"Até a próxima, ",
". Como eu disse, estou ocupado e preciso ir agora.",
"Então vá. Vá antes que ele queime a casa ou coma areia! Não se pode confiar em pessoas loucas para cuidar de si mesmas!",
"Acho que você ouvirá essa história mais cedo ou mais tarde. Agora com licença, tenho que ir.",
"E não me atrevo a atrasar você.",
"Quem não tem problemas ",
"?",
"De qualquer forma, você sabe o que quero dizer.",
"Você tem razão. Todo mundo tem problemas, suponho. ",
"Turpin Cabanel",
" estava enganado sobre você.",
"Não me faça contar sobre isso ",
".",
"Posso ver que você não quer falar sobre isso. Até a próxima.",
"Eu só quero ajudar você. Confie em mim.",
"Não, não tenho ideia do que você está falando.",
"Adeus então.",
"Turpin Cabanel",
"? Oh! Ele é um homem muito bom.",
"Então ele estava certo? Você tem alguns problemas ou não?",
"Eu não acho que posso falar sobre isso ",
".",
"Posso ver que você não quer falar sobre isso. Até a próxima.",
"Eu só quero ajudar você. Confie em mim.",
"Para me ajudar? Acho que dificilmente você vai ajudar uma pobre menina que ainda não tem dinheiro para comprar comida...",
"Diga-me o que aconteceu com você.",
"Ah, esse é o seu problema? Dinheiro? Aqui, pegue isso. Isso deve ser suficiente por um tempo.",
"Tudo está bem, ",
".",
"Bem, se você não quer me contar - adeus.",
"Isso é um hematoma no seu rosto? Alguém bateu em você?",
"Oh, deixe-me em paz, já tenho abusos suficientes ",
"Orável Caron",
"Orável Caron",
", então ter você me atormentando com suas perguntas...",
"Tudo bem, não direi uma palavra de agora em diante.",
"Orável Caron",
"Orável Caron",
"? Terei uma conversa com ele.",
"Ah, por favor, não! Não quero machucar ninguém.",
"Relaxe, não vou machucar ninguém. Vou conversar um pouco com ele.",
"Oh, ",
", muito obrigado! Como posso retribuir-te?",
"Não se preocupe com isso. Fico feliz em ajudá-lo.",
"Obrigado, ",
".",
"De nada. Adeus.",
"Eu tinha um irmão. Ele morreu há 5 anos...",
"Hmm... isso é estranho... se ele morreu, então como ele poderia me dar uma carta?",
"Uma letra? De #sMarc#? Ele está vivo? Onde ele está?",
"Ei, ei, acalme-se. Entreguei a carta ao seu pai. Ele parecia muito feliz em saber que seu filho estava são e salvo.",
"Onde ele está? Por que ele não escreve há tanto tempo? Por que ele não veio aqui?",
"Entreguei a carta ao seu pai maluco, e se você quiser saber como está seu irmão, suponho que poderia ir para casa e lê-la lá.",
"É uma longa história, pensei que você estava com pressa?",
"Não, meu negócio pode esperar. Diga-me como está meu irmão.",
"Quando ele partiu, há 5 anos, caiu nas mãos de um pirata e só recentemente conseguiu se libertar. Ele mora em #sRedmond# e agora está economizando dinheiro para voltar para casa. Os pensamentos dele estão em você e no pai dele. Você pode descobrir por si mesmo lendo a carta dele - aquela que dei ao seu pai.",
"Obrigado, ",
", você tem razão. Vou correndo para casa. Você não pode imaginar o quanto estou grato. Você devolveu a esperança ao meu pai.",
"Adeus.",
"Sim, sou todo ouvidos, espero que você não esteja brincando.",
"Não estou. Seu irmão está conversando bem com seu pai no porto agora...",
"E por que eu deveria acreditar em você? Tudo isso faz parte de uma piada cruel!",
"Não me considere tão bruto! Talvez você devesse ver por si mesmo antes de fazer tais comentários. Adeus.",
"Oh meu Deus! #sMarc# está de volta depois de todos esses anos?!",
"Sim, ele está de volta. Agora vá e veja por si mesmo.",
"Olá Capitão, é sempre um prazer vê-lo. Como você tem estado?",
"#sRachel#, você fica mais linda cada vez que te vejo.",

};
