string DLG_TEXT[158] = {
", ",
". Meu nome é ",
". Qual o seu nome?",
"Olá, ",
"! Eu sou ",
". Posso perguntar seu nome?",
"Sim Sim, ",
". Então o que você quer? Eu sou ",
".",
"Eu sou ",
", capitão do '",
".",
"Meu nome é ",
".",
"Você pode me chamar de capitão ",
".",
"Olá novamente, capitão ",
".",
"Ah, é você de novo ",
". O que discutiremos?",
"Meus olhos me enganam?! Capitão ",
" em pessoa!",
"Bem-vindo novamente, capitão ",
".",
"Ah, é você de novo ",
". O que discutiremos?",
"Meus olhos me enganam?! Capitão ",
" em pessoa!",
"Quais são as novidades?",
"Estou interessado nos rumores locais.",
"O que as pessoas têm falado na cidade?",
"Você poderia, por favor, me dizer como encontrar um determinado lugar?",
"Estou um pouco perdido pelas ruas locais...",
"Eu gostaria de ir a algum lugar, mas não sei o caminho...",
"Você sabe onde está Natanael?",
"Gostaria que você me contasse o que sabe sobre um certo sujeito...",
"Estou curioso sobre um dos cidadãos. Você pode me preencher?",
"Aposto que você conhece todo mundo que mora aqui, não é? Eu tenho algumas perguntas.",
"Conte-me sobre sua colônia.",
"O que você sabe sobre #sGreenford#?",
"Gostaria de obter algumas informações sobre #sGreenford#.",
"Bem, nada. Boa sorte!",
"Você quer alguma coisa de mim, capitão?",
"Prazer em conhecê-lo, ",
".",
"Prazer em conhecê-lo também, capitão ",
". Como posso ajudá-lo?",
"Me conte alguns rumores; talvez haja alguma notícia que eu possa transformar em ouro.",
"O que está acontecendo por aqui ultimamente?",
"Quero saber os últimos rumores.",
"Preciso de algumas orientações.",
"Eu gostaria de chegar a algum lugar...",
"Não estou familiarizado com a cidade. Eu poderia usar algumas instruções.",
"Você sabe onde está Natanael?",
"Gostaria que você me contasse o que sabe sobre um certo sujeito...",
"Estou curioso sobre um dos cidadãos. Você pode me preencher?",
"Aposto que você conhece todo mundo que mora aqui, não é? Eu tenho algumas perguntas.",
"Conte-me sobre esta colônia.",
"O que você sabe sobre #sGreenford#?",
"Gostaria de obter algumas informações sobre este lugar.",
"Lamento perturbá-lo. Adeus.",
"Entendo... E se puder fazer mais uma pergunta.",
"Obrigado pela informação. Até a próxima.",
"Ficarei feliz em falar com você novamente, ",
". Diga-me.",
"Sim, ",
"?",
"Estou ouvindo.",
"Quero saber os últimos rumores.",
"O que está acontecendo por aqui ultimamente?",
"Quero saber os últimos rumores.",
"Estou perdido. Eu poderia usar algumas instruções.",
"Estou perdido. Eu poderia usar algumas instruções.",
"Eu gostaria de chegar a algum lugar...",
"Não estou familiarizado com a cidade. Eu poderia usar algumas instruções.",
"Gostaria que você me contasse o que sabe sobre um certo sujeito...",
"Estou curioso sobre um dos cidadãos. Você pode me preencher?",
"Conte-me sobre esta colônia.",
"O que você sabe sobre #sGreenford#?",
"Gostaria de obter algumas informações sobre este lugar.",
"Lamento perturbá-lo. Adeus.",
"Quem você tem em mente ",
"?",
"A quem você quer dizer, capitão?",
"Diga-me, ",
", posso conhecê-los.",
"Quero saber sobre o governador.",
"Estou interessado em ",
"Simon Hanpool",
"Simon Hanpool",
"o taberneiro.",
"Gostaria de saber mais sobre o dono do estaleiro, ",
"David Fairweather",
"David Fairweather",
".",
"O que você sabe sobre o comerciante chamado ",
"John Filberto",
"John Filberto",
"?",
"Desculpe, mudei de ideia, esqueça isso.",
"Eu vejo. Eu tenho uma pergunta.",
"Obrigado, adeus.",
"Eu vejo. Eu tenho uma pergunta.",
"Obrigado, adeus.",
"Posso saber onde você quer chegar ",
"?",
"É muito difícil se perder nesta cidade, capitão. Onde você quer ir?",
"Ficarei feliz em ajudá-lo ",
".",
"Posso saber onde você quer ir ",
"?",
"É muito difícil se perder nesta cidade, capitão. Onde você quer ir?",
"Ficarei feliz em ajudá-lo ",
".",
"Como posso chegar à taberna?",
"Onde fica o estaleiro?",
"Onde posso vender minha carga?",
"Do porto, passe pelo portão da cidade e vire à direita. A taverna fica ao longo do beco. Não posso perder. Há uma grande placa bonita nele.",
"Obrigado.",
"E onde fica o estaleiro?",
"Onde posso vender os produtos finos que trouxe comigo?",
"Do porto, passe pelo portão da cidade e vire à esquerda. O escritório do estaleiro fica naquele beco.",
"Eu vejo. E como posso chegar à taberna?",
"Onde posso vender minha carga?",
"Obrigado pela ajuda. Isso era tudo que eu queria saber.",
"Do porto, passe pelo portão da cidade e siga o caminho reto até encontrar a placa do lojista.",
"Onde fica o estaleiro?",
"Como posso chegar à taberna?",
"Obrigado. Isso era tudo que eu precisava saber.",
"Bem, eu não sei... sobre o que você quer ouvir?",
"O que exatamente você quer saber, capitão?",
"O que você gostaria de saber sobre ",
"?",
"Gostaria de saber a história da colônia...",
"Existe mais alguma coisa além da cidade nesta ilha?",
"O que você sabe sobre o forte?",
"Vamos falar sobre outra coisa.",
"Ah, você está interessado nisso, não é? Aí está um bom homem. As pessoas geralmente não se importam com essas coisas. Infelizmente, não sou especialista nessas coisas, mas direi o que sei. Esta colônia foi construída há cerca de 40 anos. A ilha é bastante pequena, mas tem solo fértil e há algumas baías convenientes para navegação e pesca.\nDesde que novas colônias surgiram, o comércio e nossa cidade cresceram tremendamente.",
"Continuar...",
"Bom. Agora vamos falar sobre outra coisa.",
"Ah sim. O forte. Bem, não faz muito tempo, bucaneiros e piratas eram um problema frequente, com saques e pilhagens da cidade. O forte foi construído para proteger a cidade. Agora as coisas estão muito mais seguras.",
"Eu vejo. Agora, se pudermos mudar de assunto...",
"A ilha é bastante bem domesticada e há muitos produtos, água e colheitas. Embora o desenvolvimento tenha sido difícil por causa da densa selva ao redor da cidade. É difícil desmatar terras e não temos gente suficiente para fazer isso...",
"Tudo bem, me diga outra coisa.",
"Não há nada de especial na ilha. A maioria das ilhas são semelhantes nestas águas.",
"Eu vejo. Continuar...",
"Você tem sua selva, pedras - algumas praias desertas aqui e ali. É isso mesmo. No entanto, a terra oferece colheitas ricas, então você encontrará muita variedade.",
"Eu vejo. Continuar...",
"Eu vejo. Agora, se pudermos mudar de assunto.",
"Não estou realmente interessado nisso.",
"Que pena, então. Diga-me outra coisa.",
"Nestas águas, os fortes são um mal necessário. Embora este seja bastante pequeno, é uma maravilha - muito bem construído e muito forte. Os engenheiros deveriam estar muito orgulhosos. Existem 800 soldados em serviço.",
"Eu vejo. Continuar...",
"Eu não deveria dizer mais nada. O comandante me examinaria se descobrisse que eu estava falando sobre o forte, com segredo militar e tudo. Talvez seja melhor conversarmos sobre outra coisa.",
"Tudo bem...",
"Eu vejo. Agora vamos mudar de assunto.",
"Não sei nada sobre ele, sinto muito, senhorita ",
"Bem, obrigado ",

};
