string DLG_TEXT[101] = {
"Diga, eu não te conheço? Você é ",
", certo? Má escolha de companheiro de carreira, odeio piratas!",
"Ei! Diga, tenho ouvido falar de suas façanhas por aqui #ssir# e queria saber se você poderia ter a gentileza de me dar uma parte de sua glória?",
"Tenho procurado servir a coroa, mas a Marinha não me aceita. Tem um lugar para mim no seu navio?",
"Bem, porque não. Bem vindo a bordo.",
"Desculpe, cara, mas eu prefiro o tipo de marinheiro mais em condições de navegar.",
"Hoje não, cara, o navio está cheio. Talvez em outra hora.",
"(O homem olha para você, ameaçadoramente) Você deveria ter pensado melhor antes de aparecer aqui, capitão.",
"Eu vou onde eu quiser, você ",
" vagabundo.",
"DLG_TEXT[10]",
"DLG_TEXT[11]",
"Espere um minuto, você não olha ",
" para mim. Um tanto furtivo ",
" espião!",
"Isso explodiu ",
" vagabundo! Senhores das armas, fomos reconhecidos!",
"Como você ousa hastear essa bandeira e vir aqui? Você sabe muito bem que estamos em guerra com eles!",
"Não é por isso que eu...! Ah, esqueça.",
"Estou ocupado cara, vá embora.",
"Acho que você poderia chamar isso de ocupado.",
"DLG_TEXT[21]",
"DLG_TEXT[22]",
"Obrigado cara! Err, #ssir#. Capitão. Sim. Então, quais são suas ordens #ssir#?",
"Eu gostaria que você me seguisse pela cidade aqui um pouco. Sempre poderia usar a ajuda extra.",
"Apresente-se ao intendente assim que puder e não me faça partir sem você.",
"Por suas ordens, capitão!",
"Bom.",
"Você não vai!",
"E o que você vai fazer sobre isso?",
"Bom dia. Eu vi você chegando ao porto há um tempo... Você estaria interessado em mais tripulação? Como em mim?",
"DLG_TEXT[31]",
"DLG_TEXT[32]",
"DLG_TEXT[33]",
"DLG_TEXT[34]",
"DLG_TEXT[35]",
"DLG_TEXT[36]",
"DLG_TEXT[37]",
"DLG_TEXT[38]",
"DLG_TEXT[39]",
"DLG_TEXT[40]",
"DLG_TEXT[41]",
"DLG_TEXT[42]",
"DLG_TEXT[43]",
"DLG_TEXT[44]",
"DLG_TEXT[45]",
"DLG_TEXT[46]",
"DLG_TEXT[47]",
"DLG_TEXT[48]",
"DLG_TEXT[49]",
"DLG_TEXT[50]",
"DLG_TEXT[51]",
"DLG_TEXT[52]",
"DLG_TEXT[53]",
"DLG_TEXT[54]",
"DLG_TEXT[55]",
"DLG_TEXT[56]",
"DLG_TEXT[57]",
"DLG_TEXT[58]",
"DLG_TEXT[59]",
"DLG_TEXT[60]",
"DLG_TEXT[61]",
"DLG_TEXT[62]",
"DLG_TEXT[63]",
"DLG_TEXT[64]",
"DLG_TEXT[65]",
"DLG_TEXT[66]",
"DLG_TEXT[67]",
"DLG_TEXT[68]",
"DLG_TEXT[69]",
"DLG_TEXT[70]",
"DLG_TEXT[71]",
"DLG_TEXT[72]",
"DLG_TEXT[73]",
"DLG_TEXT[74]",
"DLG_TEXT[75]",
"DLG_TEXT[76]",
"DLG_TEXT[77]",
"DLG_TEXT[78]",
"DLG_TEXT[79]",
"DLG_TEXT[80]",
"DLG_TEXT[81]",
"DLG_TEXT[82]",
"DLG_TEXT[83]",
"DLG_TEXT[84]",
"DLG_TEXT[85]",
"DLG_TEXT[86]",
"DLG_TEXT[87]",
"DLG_TEXT[88]",
"DLG_TEXT[89]",
"DLG_TEXT[90]",
"DLG_TEXT[91]",
"DLG_TEXT[92]",
"DLG_TEXT[93]",
"DLG_TEXT[94]",
"DLG_TEXT[95]",
"DLG_TEXT[96]",
"DLG_TEXT[97]",
"DLG_TEXT[98]",
"DLG_TEXT[99]",
"DLG_TEXT[100]",

};
