string DLG_TEXT[101] = {
"Seu nome é ",
", certo? Você parece muito familiar. Nos encontramos antes?",
"Eu não acho. Mas eu deveria ir agora.",
"Não vou demorar. Apenas o tempo suficiente para fazer uma pergunta rápida.",
"E que pergunta seria essa?",
"Veja, quero levar uma jovem para um belo piquenique à beira-mar, se você me entende. Achei que você saberia qual a melhor hora para isso.",
"Ah, entendo! Boa sorte com isso, #slad#; Eu nem recebi um beijo dela. Eu sugiro que você vá ",
"PARE! Você #ssir#, capitão ",
", estão presos por serem",
"Você não deveria estar de folga!?",
" espião!",
", estão presos por pirataria!",
". Esse seria o melhor momento para ter um pouco de privacidade, eu acho. ",
"Muito obrigado. Contarei a ela sobre suas boas ações. Talvez possa ser de algum benefício para você também.",
"Você acha que eu sou estúpido? Essa garota nunca irá com você. Vá embora agora, antes que eu esqueça que estou de folga e te prenda!",
"Espere! Talvez possamos arranjar outra coisa? Posso comprar algo para você beber?",
"Você deveria considerar ingressar na Marinha.",
"Eu vou pensar sobre isso.",
"Deixe-me em paz, estou de folga",
"Ah, não se preocupe comigo",
"Bem... Se você realmente deseja esta informação, você poderia me pagar, digamos ",
" 'acidentalmente' contar tudo e esquecer que essa reunião aconteceu.",
"Parece-me um acordo justo.",
"Você sabe o que? Vou te pagar uma bebida e você simplesmente esquece que isso aconteceu. Como é isso?",
"O que aconteceu? Como eu disse, deixe-me em paz!",
"Sua melhor chance é ",
". Não deveria haver muitos guardas naquele momento. ",
"Muito obrigado. Não vou mais te incomodar.",
"Você parece o tipo de cara que gosta de apostar. Quero saber quando a praia estará vazia. Tenho muito ouro para oferecer.",
"Estou pronto para uma aposta se você apostar ",
"Ok, você está ligado!",
"Desculpe, mudei de ideia.",
" inimigo!",
"Você não me conhece, mas sou amigo da Holanda. E só para mostrar essa amizade, por que você não divide uma garrafa daquela coisa boa comigo?",
"Aguentar! Podemos ser inimigos enquanto estamos de serviço, mas hoje estou aqui para tratar de assuntos inteiramente pacíficos e legais. Que tal partilharmos uma garrafa do melhor que a casa tem para oferecer e trocarmos histórias?",
"Bem, se você vai ser tão generoso...",
"Esse é o espírito! Falando em espírito... Ei, barman! Traga-nos uma garrafa do seu melhor rum! E me dê as chaves do quarto, não quero que nossa festa seja estragada por bêbados aleatórios.",
"Isso é jeito de falar com um oficial superior?",
"Você é cego? Você é um idiota? Ou você quer mesmo passar o resto do ano limpando as latrinas?",
"Desculpe senhor. Eu confundi você com outra pessoa.",
"Não, não sou cego e você acabou de adicionar 'representar um oficial holandês' à sua lista de crimes.",
"Ótimo, agora adicione 'resistência à prisão'!",
"Isso é melhor. Agora, preciso de você para uma missão especial. Me siga.",
"Ah, isso explica por que nunca consegui nem um beijo dela. Boa sorte, moça. Eu sugiro que você vá ",
"O governador obviamente não se importa, então as patrulhas são poucas e raras. ",
"As patrulhas estão como sempre. ",
"A segurança é rigorosa, então boa sorte. ",
"O governo tem colocado todos os homens na guarda costeira ultimamente, mas é seu pescoço se você for lá de qualquer maneira. ",
"Deixei cair uma lembrança da minha falecida amante na praia, mas tenho um medo mortal de ser confundido com um contrabandista e levado para a forca. Posso dizer que você é uma alma gentil e gentil. Por favor, você poderia me dizer quando é seguro?",
"#snpcsir#, tenho uma proposta que tenho certeza que você apreciará. Há um tesouro substancial enterrado na costa. Não quero ser visto desenterrando isso, como tenho certeza que você entende. Dividirei metade com você se me disser quando for seguro.",
"Esses contrabandistas certamente enfrentam dificuldades aqui, aposto que não há uma única brecha nas patrulhas.",
"Adoro observar as tartarugas marinhas na costa, mas hoje em dia elas estão sempre assustadas, com todas as patrulhas da guarda costeira.",
"Isso é terrível! Você deveria tentar #spatroltime#, as margens deveriam estar vazias então. Boa sorte, #slad#! ",
"*Ele olha por cima do ombro e se inclina em sua direção de forma conspiratória* Tente #spatroltime#. *Ele pisca* ",
"Você poderia pensar, mas #spatroltime# as costas estão totalmente vazias. ",
"Eu sei o que você quer dizer, amigo! Se eu fosse você, tentaria #spatroltime#. As praias devem estar vazias para você observar as tartarugas com tranquilidade. ",
"O governo tem colocado todos os homens na guarda costeira ultimamente, então tome cuidado. ",
"O governo tem colocado todos os homens no serviço de guarda costeira ultimamente, então eles teriam que ser muito bons ou muito estúpidos para tentar. ",
"A segurança é rigorosa, então eles teriam que ser precisos. ",
"Obrigado, #snpcsir#, você não sabe o que isso significa para mim!",
"*Você pisca de volta e teatralmente se vira e sai*",
"Hah, nada é perfeito, parece! Contanto que os contrabandistas não descubram, isso não deverá ser um problema. Bem, tenho que ir! ",
"Obrigado pela dica, que bom que encontrei um colega entusiasta de tartarugas! Fique seguro! ",
"Azar. Você acha que sou tão estúpido a ponto de apenas lhe contar o horário da patrulha? Saia antes que eu esqueça que estou de folga e prenda você! ",
"Eu pareço um otário para você? Desapareça antes que eu faça um turno extra aqui e agora e arraste você para a cadeia! ",
"Você tem razão. ",
"Tartarugas marinhas? Eu pareço tão idiota? É melhor você incomodar outra pessoa antes que eu fique realmente irritado. ",
"Você está procurando problemas? Desaparece, #sdiminutive#!",
"DLG_TEXT[68]",
"DLG_TEXT[69]",
"DLG_TEXT[70]",
"DLG_TEXT[71]",
"DLG_TEXT[72]",
"DLG_TEXT[73]",
"DLG_TEXT[74]",
"DLG_TEXT[75]",
"DLG_TEXT[76]",
"DLG_TEXT[77]",
"DLG_TEXT[78]",
"DLG_TEXT[79]",
"DLG_TEXT[80]",
"DLG_TEXT[81]",
"DLG_TEXT[82]",
"DLG_TEXT[83]",
"DLG_TEXT[84]",
"DLG_TEXT[85]",
"DLG_TEXT[86]",
"DLG_TEXT[87]",
"DLG_TEXT[88]",
"DLG_TEXT[89]",
"DLG_TEXT[90]",
"DLG_TEXT[91]",
"DLG_TEXT[92]",
"DLG_TEXT[93]",
"DLG_TEXT[94]",
"DLG_TEXT[95]",
"DLG_TEXT[96]",
"DLG_TEXT[97]",
"DLG_TEXT[98]",
"[Sucesso na persuasão!] ",
"[Persuasão falhou!] ",

};
