string DLG_TEXT[101] = {
"Ei, capitão ",
"! Imagine que você se juntaria a nós, lobos do mar, hein?",
"Sim, amigos, sim. Juntos somos fortes.",
"Essa bandeira não está me enganando, seu desgraçado! Você NãO está conosco!",
"Ah, ratos!",
"Calma, seu idiota! Não me denuncie!",
"Entendo o seu jogo, Capitão... fingir ser um pirata neste porto para tentar farejar qualquer um de nós que possa estar escondido lá. Bem, eu te digo, você vai se arrepender de nos encontrar!",
"Eu não tinha ideia de que você estaria TãO ansioso para ser descoberto.",
"(O indivíduo malandro dá um sorriso conspirativo)",
"(Companheiros piratas, sem dúvida. Provavelmente procurando contatos de contrabandistas)",
"Esse não vale a pena, rapazes, deixem-no.",
"O que? Estou quase insultado.",
"Bem, imagine isso. Um cão marinho resistente, nos agraciando com sua presença. Que tal passarmos na taverna para uma caneca e uma aposta?",
"Hoje não, senhores, não tenho tempo. Bons ventos, e mantenham-se fora do meu alcance.",
"DLG_TEXT[14]",
"DLG_TEXT[15]",
"DLG_TEXT[16]",
"DLG_TEXT[17]",
"O que você está olhando?",
"Apenas comparando chapéus, companheiro, siga em frente.",
"Arrr, o famoso capitão ",
"! Bolsos cheios de ouro e nenhum navio para nos deter! Vamos jantar ricos esta noite, rapazes!",
"Exploda-o! Não há lugar seguro contra esses bastardos?",
"DLG_TEXT[23]",
"DLG_TEXT[24]",
"DLG_TEXT[25]",
"DLG_TEXT[26]",
"DLG_TEXT[27]",
"DLG_TEXT[28]",
"DLG_TEXT[29]",
"DLG_TEXT[30]",
"DLG_TEXT[31]",
"DLG_TEXT[32]",
"DLG_TEXT[33]",
"DLG_TEXT[34]",
"DLG_TEXT[35]",
"DLG_TEXT[36]",
"DLG_TEXT[37]",
"DLG_TEXT[38]",
"DLG_TEXT[39]",
"DLG_TEXT[40]",
"DLG_TEXT[41]",
"DLG_TEXT[42]",
"DLG_TEXT[43]",
"DLG_TEXT[44]",
"DLG_TEXT[45]",
"DLG_TEXT[46]",
"DLG_TEXT[47]",
"DLG_TEXT[48]",
"DLG_TEXT[49]",
"DLG_TEXT[50]",
"DLG_TEXT[51]",
"DLG_TEXT[52]",
"DLG_TEXT[53]",
"DLG_TEXT[54]",
"DLG_TEXT[55]",
"DLG_TEXT[56]",
"DLG_TEXT[57]",
"DLG_TEXT[58]",
"DLG_TEXT[59]",
"DLG_TEXT[60]",
"DLG_TEXT[61]",
"DLG_TEXT[62]",
"DLG_TEXT[63]",
"DLG_TEXT[64]",
"DLG_TEXT[65]",
"DLG_TEXT[66]",
"DLG_TEXT[67]",
"DLG_TEXT[68]",
"DLG_TEXT[69]",
"DLG_TEXT[70]",
"DLG_TEXT[71]",
"DLG_TEXT[72]",
"DLG_TEXT[73]",
"DLG_TEXT[74]",
"DLG_TEXT[75]",
"DLG_TEXT[76]",
"DLG_TEXT[77]",
"DLG_TEXT[78]",
"DLG_TEXT[79]",
"DLG_TEXT[80]",
"DLG_TEXT[81]",
"DLG_TEXT[82]",
"DLG_TEXT[83]",
"DLG_TEXT[84]",
"DLG_TEXT[85]",
"DLG_TEXT[86]",
"DLG_TEXT[87]",
"DLG_TEXT[88]",
"DLG_TEXT[89]",
"DLG_TEXT[90]",
"DLG_TEXT[91]",
"DLG_TEXT[92]",
"DLG_TEXT[93]",
"DLG_TEXT[94]",
"DLG_TEXT[95]",
"DLG_TEXT[96]",
"DLG_TEXT[97]",
"DLG_TEXT[98]",
"DLG_TEXT[99]",
"DLG_TEXT[100]",

};
