string DLG_TEXT[71] = {
"Sair!",
"Estou indo embora, não precisa gritar!",
"O que você está fazendo na minha casa?! SAIA!",
"Você vai me responder primeiro! Onde está ",
"Teodoro Fernandez",
"?",
"Nós temos você agora! Esperamos por você há muito tempo. Sabemos que você está espionando para o capitão do porto! Você não vai sair daqui vivo!",
"Como quiser.",
"O que você está fazendo aqui?",
"Fui enviado aqui por um homem na taverna.",
"Não conheço nenhum ",
"Teodoro Fernandez",
"! Saia! Agora!",
"Ei, por que vocês estão tremendo? Você não está escondendo nada de mim, está?!",
"Saia, ou eu vou...",
"Ou o que? Deixe-me adivinhar, você vai chamar os guardas? Bem, desculpe desapontá-lo, mas eles também estão procurando ",
"Teodoro Fernandez",
".",
"O que você quer de mim?",
"Só quero saber o que aconteceu com o homem que veio aqui há dez minutos.",
"Ele saiu pela porta dos fundos. Eu não acho que você vai pegá-lo agora",
"Então talvez você possa me dizer o que ele queria?",
"Deixe-me em paz! Eu te contei o que sei!",
"Eu vejo. Então o que há nesses papéis que você esconde nas costas?",
"Não é da sua conta! É só uma carta de... eh, minha sobrinha!",
"Deixe-me ver, vou ler em voz alta para você!",
"Como você ousa! Quem diabos você pensa que é?!",
"Eu sou ",
", meu próprio capitão e não estou acostumado a receber ordens, e se você não me entregar essa carta agora, estarei mexendo em suas entranhas com minha lâmina.",
"Um pirata?!",
"Você acertou o prego na cabeça! Então, vou contar até três. Um...",
"Pegue, maldito, só não me machuque!",
"Ah, vamos ver... Uma sobrinha, você disse?",
"Deixe-me já!",
"Não tão rápido. Vejo que você está comprando contrabando aqui. Esse é um caminho escorregadio para a perdição.",
"O que eu faço não é da sua conta!",
"Não fique muito animado. Você não ficará foragido por muito tempo. Acho que as autoridades ficarão bastante interessadas nesses documentos.",
"Ah, ",
"Andre Juliao",
"!",
"Certo, era ele.",
"Na verdade, ele não se apresentou.",
"Saia agora!",
"O que está errado?",
"Agora, eu disse! Antes de chamar os guardas!",
"Como quiser.",
"Experimente e você vai se arrepender!",
"Ele nunca faz isso, he-he... Certo, vamos ao que interessa.",
"Devíamos ter feito isso há muito tempo.",
"Então você precisa de uma determinada mercadoria específica, capitão?",
"Sim.",
"Posso perguntar para quê?",
"Bom... ainda não sei, mas não vai doer comprar mesmo assim, né?",
"Pediram-me para comprá-lo.",
"Por quem?",
"Você realmente acha que eu diria o nome do meu empregador?",
"Tudo bem, eu acredito em você. Mas, isso vai custar caro... Argh... eu sempre esqueço esses números.",
"Hmph!",
"Ah, não se preocupe, eu tenho isso aqui. Só preciso dar uma olhada nos meus papéis.",
"Deixe-me dar uma olhada neles também.",
"Ei! O que você está fazendo?!",
"Coloque os papéis na mesa e afaste-se, ou...",
"O que?! Quem é você?!",
"Eu sou ",
", nada menos que capitão de um navio pirata. Deixe-me simplificar. Se você não me der esses papéis agora, talvez eu tenha que recorrer a medidas menos cavalheirescas.",
"Um pirata?! Oh não!",
"Isso mesmo, você já ouviu as histórias, né? Bom. Então, seja gentil e faça o que você manda.",
"Pegue os papéis, só não me machuque!",
"Isso é melhor. Hmm, vejo que você não tem apenas problemas com números, você tem tudo anotado, inclusive nomes...",
"Você vai se arrepender disso!",
"Acho que você será o único a se arrepender quando eu mostrar esses papéis aos funcionários.",

};
