string DLG_TEXT[161] = {
", ",
". Meu nome é ",
". Posso saber quem você é?",
"Olá, ",
"? Eu sou ",
". Com quem tenho a honra de lidar?",
"Como posso ajudá-lo? Oh sim! Eu sou - ",
". Então o que posso fazer por você, ",
"?",
"Eu sou ",
", um capitão e proprietário do navio '",
".",
"Meu nome é ",
".",
"Você pode me chamar de capitão ",
".",
"Olá novamente, capitão ",
".",
"Oh, ",
", capitão. Como tem sida suas viagens? Tranquilas, eu espero.",
"Oh, quem eu vejo! Eu te dou as boas-vindas",
"!",
"Quais são as últimas novidades?",
"O que está acontecendo por aqui ultimamente?",
"Já estive no mar - estou interessado em tudo que ainda não conheço.",
"Eu poderia usar algumas instruções.",
"Você conhece bem a cidade?",
"Eu poderia usar algumas instruções.",
"Eu gostaria de perguntar sobre alguém que você talvez conheça.",
"Preciso de algumas informações sobre um dos moradores locais.",
"Você pode me contar sobre um dos habitantes locais?",
"Conte-me sobre #sRedmond#.",
"O que você sabe sobre #sRedmond#?",
"Gostaria de saber algo sobre #sRedmond#.",
"Ah, desculpe-me, mas agora não. Vê você.",
"Bem. Agora que nos conhecemos um pouco melhor, o que você queria?",
"Prazer em conhecê-lo. Agora, vamos ao que interessa. Você quer algo de mim ",
"?",
"Muito bem, capitão. Mas você dificilmente está aqui apenas para apresentações, não é?",
"O que está acontecendo por aqui ultimamente?",
"Quais são as últimas novidades?",
"Estou procurando me atualizar sobre as últimas notícias, rumores, histórias fantásticas... tudo o que você tiver.",
"Você conhece bem a cidade?",
"Eu poderia usar algumas instruções.",
"Eu preciso de ajuda. Não conheço muito bem a cidade.",
"Eu gostaria de perguntar sobre alguém que você talvez conheça.",
"Preciso de algumas informações sobre um dos moradores locais.",
"Você pode me contar sobre um dos habitantes locais?",
"Conte-me sobre #sRedmond#.",
"O que você sabe sobre #sRedmond#?",
"Gostaria de saber algo sobre #sRedmond#.",
"Entendi. Obrigado.",
"Entendo.... Há mais uma coisa.",
"Obrigado pela ajuda. Isso é tudo que preciso por enquanto.",
"O que mais você gostaria de saber,",
"?",
"Sim Sim, ",
"?",
"Então me pergunte ",
", por favor. Manda brasa.",
"Quais são as últimas novidades?",
"O que está acontecendo por aqui ultimamente?",
"Já estive no mar - estou interessado em tudo que ainda não conheço.",
"Você conhece bem a cidade?",
"Eu poderia usar algumas instruções.",
"Preciso de ajuda - não conheço bem a cidade.",
"Preciso de algumas informações sobre um dos moradores locais.",
"Você pode me contar sobre um dos habitantes locais?",
"Eu gostaria de perguntar sobre alguém que você talvez conheça.",
"Conte-me sobre #sRedmond#.",
"O que você sabe sobre #sRedmond#?",
"Gostaria de saber algo sobre #sRedmond#.",
"Acho que mudei de ideia. Até mais.",
"Essa pessoa tem nome?",
"?",
"Eu gostaria de saber, ",
", de quem você está falando.",
"Quem te deixou curioso com o comportamento deles,",
"? Até eu fico um pouco curioso...",
"O governador.",
"O estalajadeiro, Charles Windem.",
"O proprietário do estaleiro, Murray.",
"O lojista, Thomas O'Reily.",
"Ninguém. Falaremos sobre isso mais tarde.",
"Umm... Nada... não posso dizer nada de ruim sobre ele.",
"Eu vejo. Eu tenho uma pergunta.",
"Obrigado, adeus.",
"Ele herdou a taverna de seu pai. O pai dele tinha uma taberna não muito longe daqui, noutro arquipélago, numa pequena ilha chamada Highrock. Aí o pai dele veio aqui, construiu uma nova taverna, e agora o filho a administra.",
"Eu vejo. Eu tenho uma pergunta.",
"Obrigado, adeus.",
"Ele era um condenado em nossa colônia, até descobrir que tinha talento para construir navios. Depois que dois magníficos brigs foram construídos sob sua direção no estaleiro #sRedmond#, todas as suas transgressões foram perdoadas e ele se tornou um membro pleno de nossa sociedade.",
"Eu vejo. Eu tenho uma pergunta.",
"Obrigado, adeus.",
"Ah, ninguém sabe muito sobre ele. Ele se mudou para cá recentemente e abriu sua loja imediatamente. Ele parece negociar de forma justa e também não se envolve com contrabando.",
"Eu vejo. Eu tenho uma pergunta.",
"Obrigado, adeus.",
"Tenho esta cidade na ponta dos dedos.",
"Isso não é um problema, ",
". Aonde você quer chegar?",
"É difícil se perder em nossa cidade ",
". Mas vou te ajudar com prazer.",
"Como posso encontrar a taberna?",
"Onde fica o estaleiro?",
"Onde posso vender meus produtos?",
"A taverna de Windem fica na praça principal, do outro lado da rua da residência do governador.",
"Obrigado! Adeus.",
"Como posso encontrar o estaleiro?",
"Onde posso vender meus produtos?",
"O escritório do estaleiro, ",
", fica à esquerda dos portões da cidade. Há um sinal ",
", então você verá imediatamente...",
"Eu vejo. E como encontro a taberna?",
"Onde posso vender meus produtos?",
"Obrigado pela dica. Adeus.",
"Do portão da cidade, você precisa pegar a rua central, ",
", e quando chegar à praça, olhe para a direita.\nLá você encontrará o que precisa.",
"Onde fica o estaleiro da cidade?",
"Como posso chegar à taberna?",
"Eu vejo. Adeus.",
"Não consigo pensar em nada para te contar...",
"O que exatamente você gostaria de saber?",
"Por favor.",
"Gostaria de saber mais sobre a colônia...",
"Existe alguma coisa nesta ilha além da cidade?",
"Você sabe alguma coisa sobre o forte que protege a cidade?",
"Vamos mudar de assunto.",
"A história de #sRedmond#? Hmm... A colônia foi fundada há cerca de vinte e cinco anos.\nA ilha é rica e fértil, e a colônia cresceu rapidamente.\nAgora é o maior e mais próspero assentamento de todo o arquipélago.",
"Mais...",
"Soa familiar. Vamos falar sobre outra coisa.",
"Naturalmente, um governador do continente foi enviado e um poderoso forte foi construído para proteger a colônia. É tudo para melhor - você não pode confiar que os piratas cuidarão de suas boas maneiras.",
"Vamos falar sobre outra coisa.",
"Não há mais nada... exceto algumas praias desertas e hectares de selva.\nA selva começa nos arredores da cidade e alguns caminhos foram abertos, mas não há razão para se aventurar por lá. Além das feras, também há condenados e assassinos escondidos por aí.",
"Apavorante! Me diga mais.",
"Limpar a selva é um trabalho árduo. É por isso que ainda é um pouco difícil fora da cidade.\nMas o solo é fértil e temos excelentes colheitas. \nCom o tempo, creio que as plantações substituirão a selva e a cidade será cercada por fazendas, estradas e campos.",
"Mais...",
"Hm.... Há uma cordilheira magnífica... selva que não serve para ninguém.\n Praias de areia desoladas... e é isso. A emoção está dentro das muralhas da cidade.",
"Me diga mais.",
"Eu vejo. Vamos falar sobre outra coisa agora.",
"Duvido que seja capaz de lhe contar alguma coisa sobre isso - não estou muito interessado em exércitos e guerras.",
"Diga-me outra coisa.",
"Oh, o forte é uma obra-prima! O tesouro não foi mesquinho na alocação de fundos para isso.\nEles até trouxeram um arquiteto de Edimburgo para construí-lo.\nDizem que o poder e o poder deste forte podem ser comparados aos fortes da Europa, e ao número de tropas que ele abriga é mais de 1000!",
"Eu vejo. Continuar...",
"Hmm... acho que não devo contar a você sobre isso. E se você se tornar um pirata?\nNossa colônia pode estar ameaçada só porque eu lhe contei sobre alguns pontos fracos do forte.",
"Você parece um pouco paranóico. Ah, bem, não importa.",
"Estou cansado dessa conversa. Eu gostaria de perguntar outra coisa.",
"O governador, certo?",
"Aquela sua lendária ferraria.",
"O velho Mortimer pensa que é o maior artesão que já empunhou um martelo e uma pinça, ele acha. Mas se você me perguntar, o cara cobra muito alto e demora muito para empunhá-los.",
"Justo. E agora para algo completamente diferente:",
"Ah, sim. Humm. Uhuh. Me desculpe, o que foi isso mesmo? Demônios, estou com fome...",
"Disseram-me que você tem um excelente ferreiro nesta ilha. Onde posso encontrá-lo?",
"Oh, ele é realmente um ótimo capitão. Embora ele cobre um bom dinheiro e como não lhe faltam clientes, você terá que esperar alguns dias pelo trabalho dele. Você verá suas fogueiras acesas perto da prefeitura - no mesmo lado da rua, apenas uma porta abaixo, perto dos portões do distrito comercial.",
"Terei isso em mente. Bom dia.",
"Como posso encontrar o estaleiro?",
"Onde posso vender meus produtos?",
" Temos uma população de ",
" cidadãos.",
"No início, a colônia de #sRedmond# foi fundada pelos espanhóis, mas em 1655 o assentamento caiu em boas mãos inglesas: as casas foram construídas em torno de um forte estrategicamente localizado na entrada da baía. Essas mãos tomaram a cidade dos espanhóis, é verdade, mas não eram fortes o suficiente para protegê-la contra um possível ataque espanhol ou francês - então o governador confiou na 'ajuda' dos piratas...",
"Assim, durante trinta anos #sRedmond# foi abrigo para piratas e bandidos; a situação era tão drástica que a cidade foi chamada de Sodoma do Novo Mundo. Havia tantos bucaneiros e outros assassinos por causa da localização de #sisland_Redmond# no Caribe: a ilha situada no centro do Main espanhol era muito confortável para atacar a navegação espanhola e saquear cidades controladas pela Espanha. Essa foi a razão pela qual o famoso pirata Henry Morgan teve sua base aqui e liderou ataques ao Panamá, Portobello e Maracaibo a partir desta cidade.",
"Mas desde 1687, quando as leis antipirataria foram estabelecidas, o período de dominação cruel acabou, e agora a colónia é rica e próspera, uma das duas mais importantes colónias britânicas nas Índias Ocidentais.",
"...",

};
