string DLG_TEXT[47] = {
"Você não vê que estou de plantão! Não me incomode.",
"Tudo bem, tudo bem.",
"Você queria denunciar algum crime?",
"Não, claro que não. Afinal, sou um capitão... mas vejo que você não está ouvindo.",
"Lembre-se: não permitimos brigas nas ruas. Você pode se defender, é claro, se alguém te atacar.",
"Certo, vou considerar essa informação.",
"Um tempo tão insuportável... e eu tenho que ficar aqui nele. Você pode não acreditar, mas meu único passatempo é lutar contra as moscas que tentam pousar no meu rosto.",
"Isso é muito lamentável, mas não posso ajudá-lo. É seu dever.",
"Se você quiser conversar, encontre outra pessoa. Tenho o meu dever a cumprir e não é meu dever falar contigo.",
"Eu só estava me perguntando se você está vivo ou não. Você está aqui como uma estátua",
"Você acha que é fácil proteger nossa cidade? De jeito nenhum! É um trabalho muito importante e perigoso. Lembro-me de uma vez...",
"Conte-me em outra hora. Eu tenho que ir.",
"Vá embora, não me incomode",
"Como você diz, soldado.",
"Ei! Você não vai me trazer uma caneca de rum da taverna?",
"Talvez. Mas não vão me enforcar por ajudar um soldado a ficar bêbado em serviço? Não, espere até eles trocarem a guarda, e então você poderá beber o quanto quiser.",
"Por que deve ser um marinheiro rude como você tentando falar comigo?! Não há mulheres bonitas nesta cidade?",
"E você chama isso de cumprir seu dever? Olha, você não gostaria de perder a captura de um criminoso perigoso como eu, não é? Ha-ha!",
"Você parece muito saudável. Você não quer se juntar ao nosso exército? Temos muito espaço no quartel, boa comida, rum de graça.",
"Parece bom, mas terei que recusar sua oferta. A disciplina do exército não combina comigo.",
"Com este calor... eu daria tudo para voltar à minha Inglaterra natal.",
"Sim, parece que este clima não combina com você.",
"Onde você está indo? Volte!",
"Acalme-se, soldado. Tenho que falar com o nosso governador.",
"Sobre o que?",
"Sobre um assunto muito importante. Tenho que contar ao governador que os soldados franceses tomaram #sOxbay#! Posso ir agora?",
"Que novidade! Mas de qualquer forma, você terá que esperar por Sua Excelência até de manhã! Você pode alugar um quarto na taverna.",
"Que inconveniente...",
"Que novidade! Por que você não me contou antes? Vá direto para dentro.",
"Assim está melhor!",
"O que você quer?",
"Seu... hic... seu vira-lata com escorbuto! Você machucou meu...hic...meu amigo!",
"Que amigo? Você está sozinho aqui ",
".",
"O que? Ele estava... aqui há um minuto. Eu irei encontrá-lo. Você...hic...você vai esperar aqui se quiser levar uma surra!",
"Como ousa me contradizer! Eu vou te estrangular!",
"Desculpe, mas tenho ordens para não deixar ninguém visitar o governador.",
"Por que?",
"Sua Excelência nos deu as ordens ",
".",
"Mas você terá que abrir uma exceção neste caso. Tenho que contar ao governador uma notícia muito importante. Aqui está a carta que vai explicar tudo.",
"Claro. Você pode entrar direto. Sozinho.",
"Demonios! Claro. Pessoal, esperem por mim no navio. Eu já volto.",
"tudo bem, vamos ver... Bem, parece que você tem ordens do governador para deixá-lo entrar.",
"Então posso entrar?",
"Sim. Espero que você esteja sozinho? Caso contrário, devo parar seus amigos aqui.",
"Não se preocupe, estou sozinho",

};
