string DLG_TEXT[52] = {
"Hmm, qual é o seu problema ",
"? Quem está atrás da sua cabeça?",
"O que?",
"Olá. Quem é você?",
"Eu sou ",
". E preciso da sua ajuda.",
"Desculpe, estou enganado.",
"Então você está precisando da minha ajuda de novo?",
"Essa é a vida de pirata...",
"Graças a Deus, não. Essa ajuda é muito cara.",
"Com quem você entrou em conflito desta vez?",
"Inglaterra.",
"Espanha.",
"Portugal.",
"Holanda.",
"França.",
"Acabei de mudar de ideia.",
"Então, com quem você precisa fazer as pazes neste momento? Espanhóis? Francês? Inglês?",
"Receio não entender",
"Ah, pensei que você fosse um dos meus clientes. Talvez você esteja interessado em meus serviços?",
"Não sei, o que você tem a oferecer? Não vejo nenhuma mercadoria por aí.",
"Eu não negocio mercadorias em si. Eu ajudo as pessoas a resolverem seus problemas. Veja bem, a maioria dos habitantes locais leva uma vida menos honesta e precisa de ajuda de vez em quando.",
"Como?",
"Bem... Digamos que, durante suas viagens, você participe de alguns navios mercantes gordos. Antes que você perceba, toda a frota espanhola está atrás de você e a vida se torna difícil. Se você vier até mim, posso ajudar a restaurar as relações entre você e os espanhóis.\nÉ claro que esse serviço não é fácil e, para mim, organizar essas coisas pode custar uma quantia considerável. Mas você poderá visitar portos e cidades espanholas e negociar lá novamente.",
"Que garantias você oferece de que minhas 'relações' seriam restauradas?",
"Sem garantias. Mas fique à vontade para perguntar a quem utiliza meus serviços. Eu não engano meus clientes.",
"Tudo bem, gostaria de usar seus serviços.",
"Isso vai custar ",
" ouro.",
"Acordado.",
"Demais.",
"Isso vai custar ",
" ouro.",
"Acordado.",
"Isso é demais para mim. Adeus!",
"Negócio. Isso vai custar ",
" ouro.",
"Acordado.",
"Demais.",
"Isso vai custar ",
" ouro.",
"Acordado.",
"Demais.",
"Isso vai custar ",
" ouro.",
"Acordado.",
"Demais.",
"Com licença, você não tem ouro suficiente. Sem acordo.",
"Argh! Talvez eu volte quando tiver mais a oferecer.",
"Você pode zarpar agora. Tudo será resolvido o mais rápido possível.",
"Obrigado. Tomar cuidado.",
"Isso não é tudo.",

};
