string DLG_TEXT[107] = {
"Disseram-me que você fez um grande esforço para solicitar uma audiência. Meu nome é ",
". Agora, por favor, diga-me o propósito da sua visita ",
".",
"Meu nome é ",
".",
"Ah, é você de novo. O que traz você aqui desta vez? ",
"Eu gostaria de conversar com você sobre alguns negócios.",
"Sinto muito, mas há coisas que preciso fazer.",
"Então, por que você me distrai dos assuntos de estado muito importantes?",
"Gostaria de falar com você sobre um pequeno negócio.",
"Estou aqui apenas para prestar meus respeitos, #saddr#. Nada mais.",
"Nesse caso, por favor, saia do meu escritório e deixe-me voltar para assuntos mais importantes.",
"Sim claro. Desculpe por ter incomodado você.",
"Sinto muito, mas não tenho nada para conversar agora",
"Oh sim? Tenho uma proposta para você, capitão.",
"De fato?",
"Vi que você concluiu a tarefa com sucesso; meus parabéns, capitão! Aqui está sua recompensa.",
"Meus agradecimentos; Foi um prazer ajudá-lo.",
"Você deve destruir o ",
" navio ",
"missão pirata",
" ameaçando o envio ",
". Se você afundá-la, vou recompensá-lo com uma boa quantia de ",
" ouro. O que você diz, capitão?",
"Você não ouvirá falar dela novamente, isso eu prometo.",
"Receio não poder ajudá-lo.",
"Anseio por perdão, Excelência.",
"Estou interessado em aprender sobre as relações de #sgov_nation# com outras nações.",
"Estou procurando uma Carta de Marca.",
"Ouvi dizer que estou pronto para uma promoção.",
"Não posso mais servir ",
", vossa Excelência.",
"Cansei de servir ",
"Como garantia de que você é um capitão competente e para recompensar meu tempo apresentando seu caso a ",
", devo te pedir ",
" ouro.",
"Sem chance.",
"Muito bem.",
"#sgov_nation# tem sempre o prazer de aceitar novos capitães ao seu serviço. ",
"Estamos atualmente em guerra com ",
"",
"nenhum grande poder, mas ",
". Claro, ",
"Os piratas devem sempre ser afundados à primeira vista.",
" À luz do seu serviço anterior, ",
" concede a você a classificação de ",
"Vou deixá-lo orgulhoso, Excelência.",
"Você prejudicou ",
", e ",
" não esquece seus inimigos. Saia imediatamente, ou os guardas vão te jogar fora!",
"...",
"Você causou ",
" grande dano, capitão, mas ",
" está disposto a ignorar suas transgressões passadas... por um preço: ",
"Muito bem, senhor. Aceito.",
"É um prazer lidar com você, ",
"E você, Excelência.",
"Você é realmente! Excelente trabalho. Sua nova classificação é ",
". Além disso, você é premiado ",
" hectares de terra por ordem de ",
"Obrigado, senhor.",
"Tem certeza, ",
" lamentaremos perder seu serviço.",
"Sim eu sou.",
" não gosta de vira-casacas ",
"Uh, não importa.",
"Muito bem. Mas espero que você reconsidere, com o tempo...",
"Adeus, ",
"Huh?",
"Difícil.",
"O que você quer, capitão?",
"Eu gostaria de falar sobre seu novo prisioneiro.",
"Você deve estar falando do homem preso ontem no bordel.",
"Deixe-me ir direto ao ponto então. Preciso tirá-lo da prisão. De forma legal, é claro.",
"A punição por suas ações é uma pena de prisão de duas semanas. Por que você não espera até que ele seja liberado?",
"Esperar duas semanas não é uma opção. Eu preciso tirá-lo imediatamente.",
"Ele não cometeu um crime muito sério, então se você estiver pronto para me pagar 10.000 moedas de ouro, eu o libertarei imediatamente.",
"Isso é bastante, não acha, governador?",
"É muito, sim, mas preciso ter certeza de que é importante para você tirá-lo da prisão. Se você estiver pronto para pagar essa quantia, isso prova que é importante para você e se for importante para você, você provavelmente garantirá que ele não acabe na prisão novamente.",
"Eu não tenho escolha. Aqui está o dinheiro.",
"Eu preciso pensar sobre isso. Voltarei mais tarde.",
"Obrigado. Vá para o quartel. Meus soldados irão libertá-lo. Por favor, mantenha-o longe de problemas. Se eu precisar colocá-lo na prisão novamente, não o libertarei. Não terei desordeiros na minha cidade.",
"Vou ficar de olho nele. Você tem minha palavra.",
"Eu vim pagar as 10.000 moedas de ouro para o prisioneiro.",
"Exatamente, governador. Ele atacou uma das senhoras lá dentro e...",
"(*Interrompe*) Você não precisa me contar a história. Estou muito ciente do que está acontecendo na minha cidade.",
"Eu gostaria de um passe para visitar um prisioneiro ",
"Esse homem é um #scrime# condenado, capitão. Se você é um associado dele, provavelmente se juntará a ele na prisão hoje e na forca em breve.",
"Não, Excelência. Mas eu o conheci há muito tempo, quando éramos meninos, e ainda mantenho contato com seus pais. A mãe dele não pode viajar para cá e me pediu para levar uma mensagem para ele.",
"Eu vejo. Bem, posso permitir essa visita. Mas você precisará pagar 10.000 ouro como garantia.",
"Isso é muito para uma simples visita.",
"É segurança. Se você for realmente um visitante compassivo, então você pode retornar aqui, devolver o passe e 9.000 ouro serão reembolsados, então o custo total será de apenas 1.000.",
"Muito bem. Aqui estão os 10.000.",
"Mesmo assim, 10.000 é muito dinheiro e não tenho tanto comigo. Se eu conseguir arrecadar essa quantia, retornarei.",
"E aqui está o seu passe.",
"Obrigado, Excelência.",
"Você foi imprudente em voltar aqui, capitão. Eu sei da sua pequena escapada na prisão. Guardas! Prenda esta #sperson#!",
"Uh-oh...",
"Você não, prisioneiro! Você, #stitle# ",
" - por que você trouxe essa #sperson# diante de mim?",
"Você está ciente de que o prisioneiro ",
", será enforcado como um #scrime#?",
"Eu protesto! Tenho uma Carta de Marca válida e quaisquer ações que tomei contra a França foram atos legais de guerra!",
"É verdade, mas você já era um #scrime# antes de adquirir aquela Carta de Marca. Para isso você pode pendurar.",
"Sim, gosto dessa ideia! Muito bem, você pode pegar ",
" com você. Estou ansioso para ouvir o que você fará com #spronoun#.",
"Ou o que eu faço com ",
};
