string DLG_TEXT[179] = {
"Ouvi dizer que você quer me ver. Então, que negócio você tem para mim?",
"Eu gostaria de oferecer meus serviços.",
"Você é um capitão? Qual o seu nome?",
"Meu nome é ",
", capitão do '",
".",
"Bom, vou lembrar seu nome. Agora me diga o que fez você vir até mim",
"Eu gostaria de conversar sobre negócios com você.",
"Nada. Vou me despedir, se você me permitir",
"Você pode sair. Mas não desapareça completamente, é possível que eu tenha planos para você.",
"Como você diz, #saddr#.",
"Sou todo ouvidos. O que fez você vir até mim?",
"Negócios #saddr#.",
"Estou indo embora.",
"Então vamos falar de negócios.",
"Estou aqui em nome daquelas mulheres que estão à sua entrada.",
"Sua missão é um sucesso. As crianças desaparecidas foram devolvidas aos seus pais",
"Quero falar sobre um homem que encontra o favor de sua graça.",
"Sua missão está cumprida, #saddr#.",
"Não tenho nada para discutir com você no momento, #saddr#",
"Sim, eu já sei disso, aqui está sua recompensa. Espero que no futuro possa utilizar seus serviços.",
"A qualquer momento, #saddr#",
"Então, sobre quem você quer discutir.",
"Um bucaneiro, #sBernardo Gamboa#, #saddr#.",
"",
"",
"Ah. Aquele homem?! E o que você quer que eu diga? Pelo que eu sei, a reputação dele é imaculada...",
"Você estaria errado. Pelo que sei, ele sequestrou uma garota da sua cidade.",
"Ah, ah, ah. Você tem certeza sobre isso? Não quero insultá-lo injustamente.",
"Se você não se importa, investigarei isso em particular. Ninguém saberá do seu envolvimento. Se ele não sequestrasse essa garota, seu relacionamento com ele permaneceria intacto; se ele o fizesse, você mostraria a todos o quão justo e poderoso você é.",
"Hmmm... Isso não é irracional. Na verdade, não arrisco nada neste caso. Você pode descobrir o que está acontecendo. Se sua missão terminar com sucesso, eu recompensarei você. Mas, como esta é uma iniciativa sua, será uma quantia modesta.",
"Obrigado, #saddr#.",
"Lembre-me, o que estávamos discutindo?",
"Estávamos falando sobre uma garota sequestrada.",
"Ah, sim, eu me lembro. Pelo que entendi, ela realmente foi sequestrada.",
"Sim. O canalha não quis devolver a garota e foi massacrado por seus próprios homens.",
"Bem, não há pirata - não há problema. Aqui está sua recompensa. Você pode sair do meu quarto agora...",
"Como queira.",
"Ah, era isso que você queria discutir...",
"Não entendo por que você não leva isso mais a sério. Não é sua responsabilidade garantir a segurança dos cidadãos da colônia?",
"Capitão, vou perdoar sua crítica a mim desta vez. Não faça isso de novo se quiser ser favorecido neste escritório. \nQuanto a essas mulheres... Posso dizer que você é uma #sperson# inteligente, então vou lhe contar uma coisa.",
"Sou todo ouvidos.",
"Dois soldados foram encontrados mortos hoje. Um deles tinha um pedaço de tecido carmesim na mão. \nVárias horas antes de serem descobertos, um navio estranho foi avistado navegando para longe da ilha com velas cheias.",
"E isso interrompe sua investigação?",
"Bem... É óbvio que as crianças sequestradas foram levadas da ilha. Nessas circunstâncias, a busca não vale o dinheiro que será gasto nessa expedição. \nAlém disso, eles poderiam estar em qualquer lugar. Você deveria entender isso capitão. O mar oferece muitos lugares para se esconder. \nDe qualquer forma, se você está tão emocionado com a dor dessas mulheres, ofereço-lhe o desafio de encontrar seus filhos. \nPrometo que se a busca for bem-sucedida, mostrarei minha gratidão a você.",
"Tudo bem, concordo, mas primeiro gostaria de saber onde posso encontrar uma testemunha que viu o navio.",
"Não, não quero perder meu tempo com essas bobagens.",
"Você aceita? Perfeito! Você pode encontrar a testemunha na taverna. Foi um capitão mercante quem avistou aquele navio.",
"Obrigado, posso me despedir agora.",
"Desejo servir a Holanda, Excelência.",
"A Holanda sempre tem prazer em aceitar novos capitães ao seu serviço. ",
"Nós somos",
"não",
" atualmente em guerra com ",
"o ",
"qualquer nação",
". Claro,",
" mas",
" Os piratas devem sempre ser afundados à primeira vista.",
"Vou deixá-lo orgulhoso, Excelência.",
"Como estou, senhor?",
"Você afundou ",
" Navios franceses ",
" navios piratas, um total de ",
" navios.",
"Obrigado.",
"Espero que você não tenha problemas com meu serviço, senhor.",
"Na verdade não, capitão! Na verdade, é um prazer conceder-lhe uma comissão na Marinha de Sua Alteza Real. Como oficial, você será recompensado por cada navio que afundar a serviço da Holanda.",
"Sinto-me honrado, Excelência, e esforçar-me-ei por corresponder à confiança que Sua Alteza Real deposita em mim.",
"Eu gostaria de receber meu salário, senhor.",
"Bem, você afundou ",
" Navios franceses ",
" Navios piratas, ",
" navios totais. Seus salários atuais são ",
", então um total de ",
"Obrigado senhor.",
"Escória traidora! Afunde os navios dos seus compatriotas, sim? Você está dispensado do serviço militar e seu nome é retirado da lista; e nunca mais quero ver a tua cara nesta cidade!",
"...",
" desde a última vez, aqui está ",
" ouro",
"Ouvi dizer que estou pronto para uma promoção.",
"De fato é isso mesmo! Excelente trabalho. Sua nova classificação é ",
"Obrigado senhor.",
" Navios espanhóis ",
" Navios ingleses, e ",
"Oh sim? Tenho uma proposta para você, capitão.",
"De fato?",
"Vi que você concluiu a tarefa com sucesso; meus parabéns, capitão! Aqui está sua recompensa.",
"Meus agradecimentos; Foi um prazer ajudá-lo.",
"Você deve destruir o ",
" navio ",
"missão pirata",
" ameaçando o comércio ",
". Se você afundá-la, vou recompensá-lo com uma boa quantia de ",
" ouro. O que você diz, capitão?",
"Você não ouvirá falar dela novamente, isso eu prometo.",
"Receio não poder ajudá-lo.",
"Anseio por perdão, Excelência.",
"Estou interessado em aprender sobre as relações de #sgov_nation# com outras nações.",
"Estou procurando uma Carta de Marca.",
"Ah, ",
", que bom que você passou por aqui. Eu gostaria de apresentar meu ",
". Ela virá assim que terminarmos os negócios.",
"Não posso mais servir ",
", vossa Excelência.",
"Cansei de servir ",
"Como garantia de que você é um capitão competente e para recompensar meu tempo apresentando seu caso a ",
", devo te pedir ",
" ouro.",
"Sem chance.",
"Muito bem.",
" À luz do seu serviço anterior, ",
" concede a você a classificação de ",
"Você prejudicou ",
", e ",
" não esquece seus inimigos. Saia imediatamente, ou os guardas vão te jogar fora!",
"...",
"Você causou ",
" grande dano, capitão, mas ",
" está disposto a ignorar suas transgressões passadas... por um preço: ",
"Muito bem, senhor. Aceito.",
"É um prazer lidar com você, ",
"E você, Excelência.",
". \nAlém disso, você é premiado com ",
" hectares de terra por ordem de ",
"Tem certeza, ",
" lamentaremos perder seu serviço.",
"Sim eu sou.",
" não gosta de vira-casacas ",
"Uh, não importa.",
"Muito bem. Mas espero que você reconsidere, com o tempo...",
"Adeus, ",
"Huh?",
"Difícil.",
"Capitão, qual é o objetivo da sua vinda?",
"Excelência, estou trabalhando para o governador de #sisland_Conceicao#. Devo entregar-lhe esta carta e saber sua resposta sobre o pedido do meu Governador.",
"Tudo bem, me dê a carta.",
".......",
"(Alguns minutos depois) Cartagena? Uma ação militar contra aquela cidade bem defendida... Seria muito perigoso mesmo que nossas nações unissem esforços.",
"Na verdade, esta operação não tem como objetivo a captura da cidade. Sabemos que não temos forças suficientes para isso. A ideia seria fazer uma ação rápida e espetacular para desmoralizar os espanhóis no Caribe e talvez em todo o mundo.",
"Eu entendo melhor... Continue.",
"De qualquer forma, precisaríamos apenas de um pequeno número de soldados experientes. Claro, antes de iniciar a operação, irei lá para confirmar que temos condições de fazer tal operação.",
"Esse parece um projeto mais realista.",
"Gostaria de informar ao meu governador que você aceita participar de uma possível operação.",
"Sim, se você puder me garantir que não será uma missão suicida. Não aceitarei perder meus soldados numa operação desastrosa.",
"Eu entendo. Todos os cuidados serão tomados. Informarei você nas próximas semanas.",
"Não se preocupe, escolherei os melhores homens da minha guarnição para a operação.",
"Obrigado, Excelência. O Governador de #sisland_Conceicao# ficará feliz em saber sua resposta.",
"Você também precisa da minha ajuda para mais alguma coisa.",
"Para a primeira fase da minha missão em Cartagena, gostaria que o Capitão Elting me acompanhasse. Trabalhamos com sucesso no passado e ele poderia facilitar minha tarefa.",
"Claro, leve-o. Não tenho nenhuma missão para o Capitão Elting no momento.",
"Obrigado e até breve, senhor.",
"Sim, capitão? Por quê você está aqui?",
", você está preso. A acusação é de corrupção, especificamente de que você está retirando fundos do cofre público e colocando-os para seu próprio uso.",
"Absurdo! Com que autoridade você pretende me prender?",
"Pela autoridade deste uniforme e, na falta disso, pela autoridade desta espada. A menos que você queira desafiar essa autoridade, por favor, mostre-me seu livro de contas e caixa.",
"Muito bem, mas primeiro saberei o seu nome. Quando isso passar, pode ter certeza que responderá por esse ultraje!",
"Sou Kapitein Mart-jan van de Weg, 3rd Foot Company. E agora, o livro de contas e o caixa, por favor.",
"Muito bem. Eles estão naquele baú ali.",
"Obrigado.",
"Oh? Você não parece o tipo de pessoa que prende alguém, muito menos um governador! Soldado! Prenda esta #sperson#. Podemos começar com a calúnia e depois avançar até à traição.",
"Ops...",
", você está aqui sob a acusação de se passar por oficial do exército holandês, prisão injusta, calúnia e remoção de fundos públicos por meios fraudulentos.",
"Não sei nada sobre nada disso, Excelência. Entrei em sua cidade com a intenção de conduzir negócios legais e fui imediatamente atacado por soldados e trazido para cá.",
"Então você nega? Então chamarei minha primeira testemunha. ",
", esta é a #sperson# que roubou seu uniforme?",
"No entanto, estabelecemos que você roubou o uniforme deste soldado. Você então evidentemente o decorou com a insígnia de um Kapitein. E agora chamo minha próxima testemunha. ",
", esta é a #sperson# a quem você ajudou na ação ultrajante de #spronoun2# neste mesmo salão?",
"Tudo bem, eu admito. Sim, fui eu quem pegou seu dinheiro. Mas ",
" não é o culpado. Ele acreditava que eu era um Kapitein e que estava cumprindo ordens. Ele não recebeu nenhum dinheiro. Assumo total responsabilidade por minhas ações.",
"Muito bem. Isso é para seu crédito, pelo menos. No entanto, tendo em conta a gravidade dos seus crimes, condeno-o a quinze anos de prisão. Guardas! Leve o prisioneiro embora.",
"Quinze anos!",
"Ah, ",
", recebi um documento bastante peculiar a seu respeito.",
"Que tipo de documento? Por que é peculiar?",
"Aparentemente, ninguém menos que o próprio Stadtholder leu sobre seus atos. Por razões que ele mesmo conhece, ele aparentemente achou o relato divertido.\nDeixe-me ver... 'canalha amável'... 'mostra o quanto o uniforme de um dos meus oficiais é respeitado'... bem, você não' Não demonstre muito respeito pelo uniforme!\nDe qualquer forma, a conclusão é que ele ordenou que você fosse perdoado.",
"Perdoado? Você quer dizer que eu vou ser libertado?",
"Sim, é isso que quero dizer. Tenha certeza de que sua surpresa com isso não será menor que a minha. Tenha também a certeza de que, se cometer mais algum crime enquanto estiver na minha cidade, Sua Excelência não terá tempo de ler sobre isso antes que eu o enforque. Agora, saia da minha frente!",
"Obrigado, Excelência. E, por favor, transmita meus agradecimentos ao Stadtholder.",
};
