string DLG_TEXT[51] = {
"Prazer em conhecê-lo ",
". Meu nome é ",
", e estou ao seu serviço.",
"Obrigado. Eu sou ",
".",
"Que bom ver você de novo ",
".",
"Você! Eu esperava que você nunca mais escurecesse minha porta",
"Bom dia, ",
".",
"Desculpe por isso, ",
"Você quer ver meus produtos?",
"Claro. Mostre-me o que você tem em estoque.",
"Não agora. Vamos conversar.",
"Não, obrigado. Talvez na próxima vez.",
"Você está querendo comprar ou vender?",
"Tenho alguns produtos que quero vender.",
"Eu gostaria de comprar alguns equipamentos.",
"Nenhum dos dois, obrigado. Contanto.",
"Sou todo ouvidos. O que está em sua mente?",
"Estou procurando trabalho para meu navio e tripulação.",
"Receio não precisar dos seus serviços agora.",
"Isso é ruim. Vamos falar sobre outra coisa.",
"Recuso-me a negociar com uma pessoa com a sua reputação e relações. Agora saia, ",
", antes de chamar os guardas.",
"Entendido!",
"Pediram-me para entregar uma carga para você.",
"Certamente você deve ter algum trabalho que gostaria de fazer. Ficarei feliz em lhe emprestar meus serviços mediante o pagamento de uma taxa.",
"Não posso falar agora.",
"Não, não precisarei dos seus serviços... pelo menos não enquanto você estiver afundando navios #snation_desc#.",
"Nesse caso, adeus.",
"Sinto muito, mas não tenho nada para você no momento.",
"Voltarei mais tarde então.",
"Sinto muito, mas seu navio não tem capacidade para realizar a tarefa que tenho em mente.",
"Voltarei mais tarde então.",
"Oh! Eu só ia pedir que você me fizesse um favor. O problema é que preciso que uma carga seja entregue em ",
", e o mais rápido possível. Se você conseguir fazer isso dentro de um mês, receberá ",
" ouro quando você chegar. O que você acha desta oferta?",
"Eu definitivamente gosto disso.",
"Eu não posso aceitar isso.",
"Já te disse hoje que não tenho nada para você.",
"Oh, desculpe.",
"Você lembrou da sua entrega um pouco tarde demais, não acha? Vou levar a mercadoria de qualquer maneira, mas não espere ser pago. Preste mais atenção na próxima vez! Adeus.",
"Até a próxima.",
"Oh! Estou esperando por isso há muito tempo. Aqui está sua recompensa ",
"Sempre bem-vindo.",
"Desculpe. Não tenho nada para você agora",
"É uma pena. Talvez você responda algumas perguntas, então.",
"História da minha vida. Que tal algumas informações, então?",
"Sim, estou esperando #squantity# cwt de #scargo#. Você tem?",
"Hum... algumas delas parecem ter sido extraviadas. Não se preocupe, vou repor o que foi perdido e trazer para você!",
};
