string DLG_TEXT[52] = {
"Você não é um pirata, #sladlass#, e vai se arrepender de sua intrusão",
"...",
"Bom dia, rapaz! Aqui está meu covil! Ouvi dizer que você é um capitão competente e, assim como eu, é um inimigo da coroa espanhola!",
"Suas informações são precisas, capitão!",
"Você não é um capitão bom o suficiente para estar aqui na minha frente. Saia se quiser viver!",
"Tudo bem. Vou voltar mais tarde.",
"Meu nome é Robert LeNoir. Sou o capitão do Trompe Mort, um bom Shnyava. Desculpe-me pelo meu péssimo inglês, capitaine!",
"Não importa, capitão!",
"Talvez pudéssemos associar nossos navios e fazer expedições juntos. Com nossos dois navios, poderíamos fazer grandes coisas e nos tornar uma boa força de ataque!",
"Isso é uma pegadinha? Continue falando.",
"Não estou interessado. Desculpe.",
"Bem! Aqui estão os termos! Você não terá que fornecer mercadorias para minha tripulação durante nossa associação, mas poderá assumir os reparos do meu navio em portos amigos, se quiser! Certo?",
"Terei que pagar um salário mensal para você e sua tripulação?",
"Não, claro, e minha tripulação não usará suas rações no mar, mas... Siga meu anúncio! Quando você encerrar nossa parceria, todo o saque será dividido em duas partes iguais e se todo o saque não for igual ",
"Acalmar. você duvida da minha lealdade? Sua proposta parece boa para mim, cara. Quando vamos ver?",
"Desculpe, mas acho que consigo fazer expedições sem companheiro!",
"O mais breve possível! Quero sentir logo o lindo perfume de pólvora e sangue! Ah, ah!",
"Bem, mas se eu precisar falar com você ou encerrar nossa parceria? Como proceder?",
"Nos encontraremos aqui em meu covil. Este lugar é tranquilo e você ficará em casa aqui pelo tempo que quiser, seja meu amigo. Você não terá que fornecer pranchas, lonas e munições para meu navio, mas cada vez que passarmos alguns dias aqui, minha tripulação reabastecerá automaticamente meu navio!",
"Sim! Espero que a nossa associação permaneça gravada na memória das nações como um dos mais temíveis mares do Caribe!",
"Aqui está uma boa ancoragem segura. Se passarmos alguns dias aqui, reabastecerei meu navio e farei alguns reparos!",
"Seria bom passar dias aqui",
"Não podemos ficar aqui! Deveríamos ter que partir!",
"Chegou a hora de nos separarmos e encerrarmos nossa parceria, meu amigo",
"Quantos dias passaremos aqui?",
"1 dia será suficiente",
"5 dias passados em um local seguro e escondido serão muito bons para a moral da nossa tripulação!",
"Eu mudei de ideia!",
"Neste caso, acho que chegou a hora de dividir o nosso ouro em 2 partes iguais!",
"Está na hora, meu capitão!",
"Você sabe, acho que vou ficar com todo o saque para mim!",
"Mudei de ideia..por que temos que navegar em caminhos separados, afinal?",
". Você é meu companheiro capitão e sempre estarei aqui para ajudá-lo se você navegar comigo novamente! Bon vent à toi!",
"Vou pensar nisso, meu amigo. Espero ver você novamente um dia!",
"Degolador! você já está morto!",
"Veremos",
"Meu velho amigo! Que prazer ver você vivo! Que vento bom te traz nessas águas?",
"Apenas uma visita amigável para discutir com meu irmão mais velho!",
"Quero organizar uma nova expedição com você, meu #sladlass#! Tenho muitos inimigos nessas águas então seu navio e sua experiência serão de ajuda!",
"Com os mesmos termos da expedição anterior, #sladlass#? Cinquenta e cinquenta com um saque de ",
"Claro. Você está duvidando da minha fidelidade para com você?",
"Considerando tudo isso, ficará para outro momento. Eu vou pensar sobre isso",
"Olá meu amigo! Vamos tomar uma bebida na nossa nova expedição! Comecei a enferrujar nesta casinha!",
"Vamos dar um drink para a moça do #sTortuga#!",
"Você tenta me enganar, meu amigo! Você escondeu algum ouro de mim? Se é tudo o que você tem para compartilhar, acho que vou ficar com todo o saque para mim e matar você imediatamente!",
"Você acredita que vai me matar tão facilmente, meu #sladlass#?",
"Todos os espanhóis vivos neste mundo são meus inimigos e ouvi dizer que você é amigo da coroa espanhola! Você tem sorte de estar em terra, #sladlass#! Enquanto você for bem-vindo nos portos espanhóis, não teremos que fazer nada juntos, capitão!",
" Sim! Um dia talvez!",
" mínimo de ouro, vou cortar sua garganta, capitão!",
" Para você e ",
" para mim",
" mínimo de ouro para ser compartilhado!",

};
