string DLG_TEXT[63] = {
"Ah! Um novo visitante na minha taverna! Bem-vindo, ",
"! A melhor hospitalidade do arquipélago está à sua disposição!",
"Olá. Meu nome é ",
".",
"Obrigado. Meu nome é ",
".",
"Você é muito bem-vindo. Por favor, sente-se, beba um bom rum, experimente uma das minhas especialidades! Você ficará feliz por ter feito isso.",
"Que bom te ver novamente, ",
". Pegue qualquer uma das mesas livres e descanse.",
"Ah é você! Não vejo você há séculos. Posso começar com uma taça de vinho para molhar o apito?",
"Se não se importar, gostaria de ir direto ao assunto.",
"O tempo é curto, amigo, e tenho assuntos sérios para discutir.",
"Desculpe. Estou muito ocupado para hospitalidade no momento.",
"Estabeleça-se. Acabei de passar para ver quem estava aqui; Eu já estou saindo.",
"Prazer em conhecê-lo, ",
". Meu nome é ",
".",
"Claro, ",
", você é o chefe. Como posso ajudá-lo?",
"Estou querendo aumentar minha equipe. Você poderia me indicar alguém que possa estar procurando trabalho?",
"As batalhas recentes me deixaram com falta de pessoal. Preciso encontrar alguns rapazes que estejam procurando emprego.",
"Eu gostaria de falar de negócios.",
"Você tem um quarto disponível? Eu gostaria de ficar aqui por um tempo",
"Estou procurando um quarto limpo com uma cama limpa. Nada mais nada menos.",
"Não tenho tempo para conversar agora. Eu passo por aqui mais tarde.",
"Desculpe, estou ocupado agora. Mas voltarei para conversar quando estiver livre.",
"De fato! E que negócio é esse?",
"Eu preciso de algum trabalho. Você não conhece nenhum garoto rico nesta ilha que tenha medo de viajar sozinho?",
"Você sabe, agora que penso nisso, não tenho nenhum negócio.",
"É um pouco tarde para isso. Você terá mais sorte se voltar pela manhã. Ou talvez você queira passar uma noite na taverna.",
"Talvez eu fizesse isso. Você tem um quarto livre?",
"Talvez eu vá. Mas deixe-me perguntar uma outra coisa primeiro.",
"Eu tenho um quarto disponível. Quanto tempo você pretende ficar?",
"Até de manhã.",
"Só até o anoitecer.",
"Certo. Vai custar 5 moedas de ouro.",
"Tudo bem. Aqui você vai.",
"Nesse caso, temo que minha carteira e eu passaremos uma noite no salão comum.",
"Não, obrigado. Se esse for o preço, economizarei algumas moedas e passarei uma noite no salão comum.",
"Talvez mais tarde. Deixe-me perguntar sobre outra coisa.",
"Certo. Vai custar 5 moedas de ouro.",
"Tudo bem. Aqui você vai.",
"Nesse caso, temo que minha carteira e eu passaremos uma noite no salão comum.",
"Não, obrigado. Se esse for o preço, economizarei algumas moedas e passarei uma noite no salão comum.",
"Vou pensar sobre isso. Obrigado.",
"Por favor! Pare com essa loucura de uma vez! Não me faça chamar os guardas!",
"Tudo bem! Vou.",
"Se existir tal pessoa, ela pode preferir evitar atrair a atenção de tantas consortes - como eu espero que você saiba.",
"Sim, esqueci. Tudo bem, voltarei mais tarde, quando tiver menos navios, ha-ha.",
"Não quero ajudá-lo, com todo o mal que você causou ao meu país.",
"Basta olhar para este patriota. Bem adeus.",
"Suas mãos estão cobertas de sangue. Você realmente acha que alguém viajará com você?",
"Você está certo. Todo mundo tem medo de mim. Que divertido.",
"Você veio na hora certa. Um comerciante aqui estava procurando a companhia certa para viajar. Você deveria falar com ele. Aqui está ele, entrando na taverna.",
"Eu farei isso.",
"Não, não há ninguém em quem eu possa pensar no momento. Talvez na próxima vez.",
"Hum. Então vou esperar.",
"Procuro alguém que conheça a selva, que talvez tenha encontrado um antigo templo.",
"Ah sim! O Maurício Juradu ali falou alguma coisa sobre como ele mal conseguiu sair de um templo cercado de índios.",
"Obrigado! Ele parece que poderia ajudar.",
"Procuro um homem que parece se chamar Marcel Jauri. Você já ouviu falar dele?",
"Nome estranho. Hmm, infelizmente não posso ajudá-lo aqui, isso não me lembra nada.",
"Oh céus! Como vou encontrar esse sujeito?",
};
