string DLG_TEXT[173] = {
"Olá, ",
". Infelizmente, não tive a honra de conhecê-lo antes, mas posso dizer que você é o capitão daquele navio no porto.",
"E daí? Não tenho tempo para conversar com marinheiros.",
"Eu sou ",
". De que navio você está falando exatamente?",
"O '",
". Ele é seu, não é? ",
"?",
"Como você adivinhou?",
"Esse pode realmente ser o meu navio. Mas realmente não é da sua conta. Vá embora.",
"Não foi difícil ",
". Eu vi você chegando em terra. Eu sou ",
".",
"Certo. Bem, foi bom conversar com você.",
"Você não tem algo mais interessante para fazer do que observar os navios entrando e saindo do porto?",
"Infelizmente, fui dispensado de funções por violar as regras do navio.",
"Isso é ruim. Você não pode fazer algo sobre isso?",
"Isso é lamentável. Bem, boa sorte e bom dia!",
"Bem... talvez se um capitão respeitado falasse comigo ao capitão do porto... ah, mas quem se importa comigo ",
"?",
"Hmm... vou tentar fazer algo a respeito.",
"Eu poderia falar com o capitão do porto, mas precisaria de algo seu para fazer isso.",
"Desculpe, não posso te ajudar.",
"Realmente, ",
"?! Bem, capitão, se você puder me ajudar, prometo que não esquecerei.",
"Vamos lá, não é isso que estou procurando",
"Bem, na verdade, não tenho tempo para ajudá-lo.",
"Oh. Então, sua generosidade tem um preço quando se trata de seu próximo ",
". Mas tenho algo a oferecer.",
"Bem, vamos ouvir então ",
"Improvável. Eu não acho.",
"Ei, não, capitão. Você vai me ajudar e eu retribuirei o favor, sou assim!",
"Deixe-me primeiro falar com o capitão do porto.",
"A propósito, onde posso encontrar o capitão do porto?",
"Pois bem, não há muito que eu possa fazer, exceto apenas observar os navios entrando e saindo do porto. Adeus, capitão!",
"Adeus.",
"Conheço alguém que pagará um bom dinheiro a qualquer um que possa dispensá-lo de certas tarefas. \nSe você me ajudar, vou apresentá-lo a ele. Ele confia em mim e tenho certeza que você combina perfeitamente com ele.",
"Hmm... isso é interessante. Tudo bem, vou tentar te ajudar.",
"A propósito, onde posso encontrar o capitão do porto?",
"Talvez ele esteja naquele prédio em frente aos portões da cidade ",
"Ah, obrigado.",
"Oh, ",
"! Olá, ",
".",
"Olá, ",
". Pensei que nunca mais nos encontraríamos...",
"Ah, é você de novo ",
". Estou feliz em ver você são e salvo.",
"Então, ninguém decidiu te ajudar ",
"?",
"Olá. E adeus! Estou ocupado.",
"Exatamente, ",
". Terei que me despedir do mar.",
"Tudo bem, eu vou te ajudar.",
"O quê tem pra mim?",
"Não é culpa de ninguém, apenas sua. Até a próxima.",
"Realmente, ",
"?! Bem, capitão, se você puder me ajudar, prometo que não esquecerei.",
"Vamos lá, não é isso que estou procurando",
"Bem, na verdade, não tenho tempo para ajudá-lo.",
"Oh. Então, sua generosidade tem um preço quando se trata de seu próximo ",
". Mas tenho algo a oferecer.",
"Bem, vamos ouvir então",
"Improvável. Eu não acho.",
"Ei, não, capitão. Você vai me ajudar e eu retribuirei o favor, sou assim!",
"Deixe-me primeiro falar com o capitão do porto.",
"A propósito, onde posso encontrar o capitão do porto?",
"Pois bem, não há muito que eu possa fazer, exceto apenas observar os navios entrando e saindo do porto. Adeus, capitão!",
"Adeus.",
"Conheço alguém que pagará um bom dinheiro a qualquer um que possa dispensá-lo de certas tarefas. \nSe você me ajudar, vou apresentá-lo a ele. Ele confia em mim e tenho certeza que você combina perfeitamente com ele.",
"Hmm... isso é interessante. Tudo bem, vou tentar te ajudar.",
"A propósito, onde posso encontrar o capitão do porto?",
"Olá, sou ",
"! Olá, ",
".",
"Olá, ",
". Nunca pensei que nos encontraríamos novamente algum dia...",
"Ah é você, ",
". Estou feliz em ver você são e salvo.",
" Você teve algum sucesso?",
"Estou indo para o capitão do porto agora",
"Ainda não. Me desculpe, vamos conversar mais tarde.",
"A propósito, onde posso encontrar o capitão do porto?",
"Oh, me desculpe, não quero apressar você ",
". Estou tão cansado de estar aqui em terra!",
"Você não vai ficar aqui por muito tempo. Eu cuidarei disso.",
"Ouça, tenho algumas perguntas para você. Você é um marinheiro experiente, não é?",
"Gostaria de perguntar sobre navegação.",
"Espero que sim, ",
". Eu adoraria te pagar uma bebida, mas você é um capitão e eu sou apenas um marinheiro.",
"Ha! Ofereça-me isso antes de sair para o mar.",
"Mas um marinheiro pode beber com um capitão!",
"Você terá dificuldade em encontrar um marinheiro melhor do que eu aqui e #sisland_Redmond#, ",
"!",
"Então compartilhe sua experiência comigo.",
"Hmm, bem, tudo bem, vejo você mais tarde.",
"Dificilmente posso lhe dar conselhos sobre navegação ou manobras, já que não sou oficial. \n Mas quanto a outras coisas ficarei feliz em ajudá-lo.",
"Perfeito. O que você pode me dizer sobre o que o capitão deveria saber?",
"Como devo tratar minha tripulação?",
"Que tal algumas dicas de navegação?",
"Hmm, não posso falar sobre navegação ou comércio, mas algumas coisas são vitais para nós, marinheiros. É por isso que precisamos aprendê-los nós mesmos para não sermos pegos de calças abaixadas!",
"O que você quer dizer?",
"O primeiro e o mais importante é a defesa. Se um capitão não conseguir organizar adequadamente sua tripulação em um navio,\nentão o fogo pesado cobrirá o convés de sangue\nQuanto melhor a defesa, menos vítimas.",
"Continue, estou ouvindo você..",
"Entendo, obrigado por esclarecer isso para mim.",
"Nunca negligencie sua tripulação, a menos que você esteja com vontade de encalhar ou ficar à deriva. A tripulação é o coração de um navio, e o capitão não será capaz de comandar seu navio sozinho. \n Se você não tiver pessoas suficientes em sua equipe, o navio ficará tão estranho quanto um cachalote.",
"Os marinheiros também são pessoas. Ninguém duvida disso.",
"Acho que vou lhe dar alguns conselhos sábios para jovens capitães, que muitas vezes correm de cabeça para a batalha e podem ser pegos por números esmagadores.\nQuando você estiver tentando escapar, lembre-se, é melhor perder a carga do que a cabeça.",
"Eu vejo. Algo mais?",
"Adeus, obrigado pelo seu conselho.",
"A próxima coisa que você precisa saber é um pouco de esgrima. Alguns dizem que apenas um capitão deveria saber fazer isso, mas os marinheiros também têm um pouco de conhecimento sobre isso.",
"Ótimo! Eu gosto do som disso.",
"Acho que isso é informação suficiente para mim por hoje. Até a próxima.",
"O moral também é muito importante para sua tripulação. Se a tripulação não estiver satisfeita com seu capitão, o motim não ficará muito atrás.",
"Vamos mudar de assunto.",
"Obrigado, falaremos sobre isso em outro momento. Adeus.",
"Eu digo, ",
". Nunca lute com os guardas da cidade. Eles nunca lutam de forma justa. \n Eles atacarão você de uma só vez e amarrarão suas mãos e pés. É melhor lutar com 3 piratas do que com um bando de guardas.",
"Vamos mudar de assunto.",
"Obrigado, falaremos sobre isso em outro momento. Adeus.",
"Mais uma coisa importante é como abordar seu inimigo. Sua tripulação precisa aprender a lançar garras e cordas em um navio que você deseja embarcar. Eles precisarão ser capazes de fazer isso em velocidades e distâncias variadas.",
"Isso é engraçado, quando você está dando conselhos, você não o faz.",
"Obrigado, falaremos sobre isso em outro momento. Adeus.",
"Desculpe, ",
". Me deixei levar pelo momento",
"Tudo bem. Vamos mudar de assunto.",
"Bem, obrigado pela informação. Adeus.",
"Ah, ",
"! Olá, ",
".",
"Olá, ",
". Eu não pensei que nos encontraríamos novamente...",
"Ah, é você de novo ",
". Estou feliz em ver você são e salvo.",
" Há algum resultado?",
"Infelizmente ",
". Não consegui fazer nada.",
"Ainda não, me desculpe, vamos conversar mais tarde.",
"Isso é uma pena, mas de qualquer forma, obrigado pela sua ajuda,",
".",
"Não fique chateado ",
". Vou levá-lo para o meu navio",
"Ouça, tenho algumas perguntas para você. Você é um marinheiro experiente, não é?",
"Eu gostaria de perguntar sobre navegação marítima.",
"Bem, como estou, capitão?",
"Você pode me pagar uma bebida, Rys.",
"Ainda não resolvi esse problema.",
"É realmente tão ruim ",
"?",
"Acho que não, pelo contrário, você pode trabalhar em um navio...",
"Ah, obrigado, capitão! Para dizer a verdade no fundo do meu coração, eu não acreditei que você seria capaz de fazer isso!",
"Hmm, você subestimou meus talentos.",
"Boa sorte, ",
"! Eu vou te ver.",
"Eu admito que sim Então, o que posso fazer por você ",
"? Deixe-me mostrar-lhe minha gratidão.",
"Obrigado, ",
", mas não preciso de nada. Até a próxima.",
"A propósito, pensei - talvez você se junte à minha tripulação como meu oficial?",
"Bem, acho que mais uma palestra não faria mal.",
"É perfeito para mim.",
"! Preciso de uma quantia de dinheiro para terminar meu negócio aqui.",
"Quanto você precisa.",
"500 ouro. Eu entendo que é muito dinheiro.",
"Combinado, aqui está o dinheiro.",
"Realmente, é uma grande soma. Não posso permitir isso agora.",
", capitão. É bom ver você e que bom que você ainda está vivo. É perigoso ser capitão hoje em dia.",
"Ouvir, ",
", você poderia me contar o que torna um bom capitão mais uma vez?",
"A propósito, pensei - talvez você se junte à minha tripulação como meu oficial?",
"Bem, acho que sei disso. Adeus.",
"Quais serão as ordens, capitão.",
"Nenhum.",

};
