string DLG_TEXT[74] = {
"Olá meu nome é ",
", mas meus amigos me ligam ",
".",
"É um prazer conhecer-te, ",
", meu nome é ",
". Sinto muito, mas tenho negócios a tratar, vamos conversar outra hora.",
"Olá, linda, meu nome é ",
", mas para você eu sou apenas ",
". Vejo você mais tarde.",
"Olá! A julgar pelo seu nome você é filha do dono desta loja, não é?",
"Ei, linda, não é o seu pai parado aí no balcão?",
"Estou tão feliz em ver você ",
"!",
" Todo mundo na cidade está falando sobre você e suas façanhas!",
"Sim, sim, mas estou com pressa agora.",
"Agora não! Desculpe, posso ser um pouco rude às vezes, mas conheço muito bem meu trabalho. Tenho coisas para fazer agora, mas falo com você mais tarde.",
"...",
"...",
"...",
"...",
"...",
"Eu ouvi muito sobre você, ",
". Todo mundo diz que você é a única mulher pirata...",
"As pessoas estão enganadas, não sou um pirata, sou um capitão honesto.",
"Por favor, não se dirija a mim tão sem cerimônia. Lembre-se que eu sou capitão ",
", e não me ligue de outra forma em público. Você me entende?!",
"Você não mudou de ideia, não é? Por favor, me tire daqui!",
"Por favor, não se dirija a mim tão sem cerimônia. Lembre-se que sou um capitão. ",
"Já lhe pedi para não se dirigir a mim tão sem cerimônia em público. Lembre-se que eu sou capitão ",
", e não me ligue de outra forma?!",
"Ah, me desculpe ",
".",
"Quer conversar comigo sobre algo em particular ou está apenas perdendo meu tempo?",
"Você está testando minha paciência com essa conversa fiada. Você tem algum negócio para mim ou não?",
"Eu tenho negócios para você. Você é minha última esperança!",
"A julgar pelo tom de sua voz, você está planejando algum empreendimento obscuro e quer que eu esteja envolvido nele.",
"Uau! Sério! Eu sou sua 'última esperança'? Isso é interessante! Tudo bem, descreva que tipo de negócio você tem para mim.",
"Sinto muito, mas não tenho tempo para resolver seus problemas.",
"Isso é bobagem, peça ajuda ao seu papai e não me impeça de fazer meus negócios.",
"Obrigado por concordar em me ouvir. O problema é que não posso mais ficar com meu pai. Ele não é uma boa pessoa e quer me casar com alguém.",
"O que há de errado nisso para uma garota como você?",
"Então, o que há de errado em se casar. Depois de colocar as mãos em seu marido, você pode torcê-lo no dedo mínimo.",
"Ele quer casar você com alguém contra a sua vontade? Isso não é justo e entendo por que você está bravo com ele, mas como posso ajudá-lo?",
"Sem perguntar se você concorda ou não? Que pai! Esses pais deveriam ser amarrados em uma verga! Mas ainda assim, não consigo entender o que você quer de mim.",
"Por quê! Achei que você me entenderia com certeza. Eu não quero casar com ninguém! Quero ser independente e livre!",
"Eu diria que você tem desejos muito estranhos por uma jovem, mas o que você quer de mim?",
"O que posso dizer? Fuja de casa então. Não vejo o que isso tem a ver comigo.",
"Tire-me daqui, eu imploro! Quero navegar contigo no teu navio e admirar o mar e...",
"Espere, espere, espere! Você quer que eu basicamente sequestre você do seu pai?",
"Ei! Espere um segundo! Você quer que eu arrisque minha vida para resolver seus problemas mesquinhos?",
"Não, não farei isso. Você é uma garota jovem e inexperiente. Você logo se arrependerá dessa decisão.",
"Aha, como se eu não tivesse mais nada para fazer a não ser ajudar você, tenho meus próprios problemas para resolver.",
"Bem, quando te vi pensei que você poderia me ajudar, mas se você acha que isso é 'mesquinho'...",
"Acalmar. Você realmente prefere navegar ao conforto de uma boa casa?",
"Pare de choramingar! Quer mesmo sair de casa e daquela vida tranquila para uma vida em alto mar?",
"Bem, eu entendo você muito bem, mas não acho que tenha o direito de me intrometer na sua vida. Viva como todo mundo vive e seja feliz.",
"Você está certo, seus desejos são apenas caprichos mesquinhos de uma garota mimada e mimada.",
"Sim, há anos que sonho em viajar. Quero conhecer muitos lugares interessantes diferentes, conhecer novas pessoas e não me esconder nas costas do meu pai e deixá-lo decidir o que devo fazer da minha vida.",
"Tudo bem, posso levá-lo comigo, mas por favor não pense que navegar é sempre despreocupado.",
"Tudo bem, tudo bem. Meu navio está no porto e informarei minha tripulação para permitir que você embarque, mas se reclamar de alguma coisa durante a viagem, darei comida aos tubarões.",
"Você está errado. Quando você viaja, você não apenas vê lugares novos e interessantes, mas muitas vezes se vê em situações perigosas. Seria melhor você ficar em casa.",
"Bem, então não se esconda nas costas do seu pai. Apenas viva sua vida, aproveite e faça o que quiser, dane-se a opinião do seu pai! ",
"Oh, muito obrigado, capitão ",
", Vou arrumar minhas coisas agora e depois irei para o seu navio.",
"Tudo bem, mas não se atrase, vamos zarpar em breve.",
"Nem pense em levar todas as suas roupas, leve apenas o necessário.",
"Você provavelmente está certo, obrigado.",
"Deixa para lá. Agora deixa-me ocupar-me com as minhas coisas.",
"Como você diz, ",
". Não me atrevo mais a atrasá-lo.",
"Claro que você não ousa. Não se faça de arrogante, garota.",
"Sim, eu gostaria que meu pai fosse capitão para poder navegar com ele e ficar sob as velas brancas como a neve que ondulam na brisa do mar...",
"Um belo sonho, mas não podemos escolher nossos pais. Tudo bem, tenho algumas coisas para fazer.",
"Garota boba! Uma mulher no navio traz azar, então fique seco em terra.",

};
