string DLG_TEXT[115] = {
"Disseram-me que você fez um grande esforço para solicitar uma audiência. Meu nome é ",
". Agora, por favor, diga-me o propósito da sua visita ",
".",
"Meu nome é ",
".",
"Ah, é você de novo. O que traz você aqui desta vez? ",
"Eu gostaria de conversar com você sobre alguns negócios.",
"Sinto muito, mas há coisas que preciso fazer.",
"Então, por que você me distrai dos assuntos de estado muito importantes?",
"Gostaria de falar com você sobre um pequeno negócio.",
"Só estou aqui para prestar meus respeitos. Nada mais, ",
"Nesse caso, por favor, saia do meu escritório e deixe-me voltar para assuntos mais importantes.",
"Sim claro. Desculpe por ter incomodado você.",
"Estou ouvindo, ",
".",
"Estou aqui para receber minha recompensa pela morte de Dirty Garry.",
"Sinto muito, mas não tenho nada para conversar agora",
"Oh, ouvi sobre o que você fez. Da face de toda a colônia eu lhe mostrarei o nosso apreço.",
"Isso mesmo, gostaria de ver uma recompensa.",
"Você é um brincalhão. Ha ha. Aqui está o seu dinheiro.",
"Obrigado, sou seu humilde servo.",
"Então, sobre a aposta que você fez... depois de obter a aprovação do nosso departamento fiscal, vejo que temos... deixe-me ver... seis mil.",
"O que?! O negócio foi de 10 mil!",
"Eu não posso te ajudar. No futuro, tente ficar mais calmo.",
"O que quer que você diga, senhor. Porco sujo....",
", você está ciente de que é acusado de assassinato? Você foi encontrado junto ao corpo da vítima. O que você diz em defesa desta acusação?",
"Não tem nada a ver comigo. O homem já estava morto quando entrei no quarto! Disseram-me que ele estava apenas ferido e que poderia ter algumas informações importantes para mim.",
", Acabei de saber que um homem foi capturado quando tentava deixar a cidade com uma faca manchada de sangue em sua posse. Ele confessou o assassinato de que você foi acusado. Você será liberado imediatamente.",
"Obrigado. Eu sabia que poderia confiar na justiça aqui em Conceição.",
"Desejo desertar para Portugal.",
"De fato? Muito bem, agora você é cidadão português.",
"Agradeço sua infinita gentileza, senhor.",
"Oh sim? Tenho uma proposta para você, capitão.",
"De fato?",
"Vi que você concluiu a tarefa com sucesso; meus parabéns, capitão! Aqui está sua recompensa.",
"Meus agradecimentos; Foi um prazer ajudá-lo.",
"Você deve destruir o ",
" navio ",
"missão pirata",
" ameaçando o envio ",
". Se você afundá-la, vou recompensá-lo com uma boa quantia de ",
" ouro. O que você diz, capitão?",
"Você não ouvirá falar dela novamente, isso eu prometo.",
"Receio não poder ajudá-lo.",
"Anseio por perdão, Excelência.",
"Estou interessado em saber mais sobre as relações da Espanha com outras nações.",
"Estou procurando uma Carta de Marca.",
"Ah, ",
", que bom que você passou por aqui. Eu gostaria de apresentar meu ",
". Ela virá assim que terminarmos os negócios.",
"Ouvi dizer que estou pronto para uma promoção.",
"Não posso mais servir ",
", vossa Excelência.",
"Cansei de servir ",
"Como garantia de que você é um capitão competente e para recompensar meu tempo apresentando seu caso a ",
", devo te pedir ",
" ouro.",
"Sem chance.",
"Muito bem.",
" tem sempre o prazer de aceitar novos capitães ao seu serviço. ",
"Estamos atualmente em guerra com ",
"",
"nenhum grande poder, mas ",
". Claro, ",
"Os piratas devem sempre ser afundados à primeira vista.",
" À luz do seu serviço anterior, ",
" concede a você a classificação de ",
"Vou deixá-lo orgulhoso, Excelência.",
"Você prejudicou ",
", e ",
" não esquece seus inimigos. Saia imediatamente, ou os guardas vão te jogar fora!",
"...",
"Você causou ",
" grande dano, capitão, mas ",
" está disposto a ignorar suas transgressões passadas... por um preço: ",
"Muito bem, senhor. Aceito.",
"É um prazer lidar com você, ",
"E você, Excelência.",
"Você é realmente! Excelente trabalho. Sua nova classificação é ",
". Além disso, você é premiado ",
" hectares de terra por ordem de ",
"Obrigado, senhor.",
"Tem certeza, ",
" lamentaremos perder seu serviço.",
"Sim eu sou.",
" não gosta de vira-casacas ",
"Uh, não importa.",
"Muito bem. Mas espero que você reconsidere, com o tempo...",
"Adeus, ",
"Huh?",
"Difícil.",
"O Vice-Almirante Benavides disse que você precisa de ajuda para encontrar o enviado do Rei.",
"Excelente! Eu sabia que poderia contar com ele. Há quanto tempo você trabalha para o vice-almirante?",
"Trabalho para ele há muitos meses. Ele disse que você já iniciou a busca.",
"De fato. Infelizmente, não tenho navios suficientes para minha busca. Neste momento, os meus homens estão a terminar a busca ao longo da costa sul da ilha e também enviei um navio para #sIsla Muelle# para verificar se o navio afundou ou está avariado.",
"Você acha que o navio foi ultrapassado pela tempestade?",
"Eu penso que sim. É uma forte possibilidade.",
"Como posso ajudar então, Governador?",
"Primeiramente, gostaria que você pesquisasse ao longo da costa norte de #sisland_Hispaniola#. Há uma possibilidade remota de que o navio tenha se desviado do curso durante a tempestade; se for esse o caso, há uma pequena chance de encontrá-lo lá.",
"Sim, governador. Vale a pena verificar isso, mesmo que apenas para limitar as possibilidades.",
"Encontrei o navio, Governador. O soldado comigo é o único sobrevivente. O navio foi atacado por piratas.",
"E eles sequestraram o enviado...",
"Só então. Como você sabe disso?!",
"Acabei de receber uma carta do sequestrador. O enviado só será libertado mediante o pagamento de um grande resgate. Meu Rei ficará chateado porque nós, no Caribe, não fomos capazes de proteger seu enviado, cabeças rolarão.",
"Talvez eu pudesse intervir e encontrar Roche Brasiliano e depois resgatar o enviado.",
"Roche Brasiliano é o sequestrador?",
"O Pirata não assinou a carta de resgate?",
"Não, claro que não. Ele obviamente queria permanecer anônimo.",
"Finalmente uma pausa, agora temos vantagem sobre ele. Ele acha que não sabemos quem ele é.",
"Se você conseguir libertar o enviado, será generosamente recompensado.",
"O problema é que não sei por onde começar minha busca por ele.",
"E não posso ajudá-lo em sua busca. Não tenho informações sobre esse pirata.",
"O vice-almirante Benavides está sempre bem informado, acho que voltarei para #sHavana#. Ele deve ter algumas informações úteis sobre a Roche Brasiliano.",
"Você está certo, capitão, faça isso. Você pode deixar o soldado aqui, cuidaremos de seus ferimentos e ele será empregado em minha guarnição.",
"Obrigado, Governador.",
};
