string DLG_TEXT[182] = {
". Olá?, ",
"?",
"Posso te ajudar, ",
"?",
"Esta é sua primeira vez em nossa cidade, ",
"? Eu não te vi antes",
"Eu sou ",
", capitão e proprietário do navio'",
". Eu tenho algumas perguntas se você tiver um momento.",
"Meu nome é ",
". Gostaria de lhe fazer algumas perguntas.",
"Você pode me chamar de capitão ",
". Eu só gostaria de algumas informações.",
"Olá, capitão ",
". O que traz você à nossa colônia?",
"Ah, capitão ",
". ",
", é você de novo. Espero que sua jornada tenha sido agradável. O que há de novo?",
"Olá, ",
". Como posso ajudá-lo?",
"Perdi alguma coisa enquanto estive fora?",
"Aconteceu alguma coisa interessante enquanto eu estive fora?",
"Que histórias os velhos cães-do-mar estão trocando por causa do rum hoje em dia?",
"Qual é a agitação nas tabernas?",
"Procuro fofocas, boatos, histórias fantásticas...qualquer coisa que eu não saiba pode ser útil.",
"Me conte algumas de suas fofocas mais recentes, amigo. Pode haver aventura ou dinheiro até mesmo no menor detalhe.",
"Ainda não consigo encontrar...",
"É impossível encontrar alguma coisa neste labirinto! Onde é...",
"Estou tão perdido quanto um navegador bêbado. De novo!",
"Você parece um morador local. Diga-me onde posso encontrar...",
"Por favor me diga como chegar a...",
"Tive um dia péssimo, então você nos salvará da dor se apenas me disser como encontrar...",
"Gostaria da sua opinião sobre um cidadão local.",
"Preciso saber o que você pode me contar sobre alguém que mora aqui na cidade.",
"O que você pode me contar sobre...",
"Conte-me tudo o que puder sobre um sujeito...",
"Espero que você possa me contar algo sobre uma pessoa que talvez conheça.",
"Este lugar não é muito grande  aposto que você conhece todo mundo que mora aqui. Vamos conversar.",
"Conte-me sobre #sSantiago#.",
"O que você pode me dizer sobre esse lugar esquecido por Deus?",
"Gostaria de saber mais sobre esta bela colônia.",
"Qual é a história desta cidade e da ilha?",
"Você sabe alguma coisa interessante sobre #sSantiago#?",
"...",
"Desculpe. Pensei que você fosse outra pessoa.",
"Estou apenas de passagem. Então fique de lado ou seja empurrado.",
"O que você gostaria de saber, ",
"?",
"O que lhe interessa, capitão?",
"O que você quer de mim?",
"Cidades como esta estão sempre nadando em fofocas. Dê-me os destaques.",
"Aconteceu alguma coisa interessante por aqui ultimamente?",
"Só quero saber o que está acontecendo na vizinhança. Alguém enganou um amigo? Alguém foi morto? O estalajadeiro é mesmo uma mulher? Você me entende.",
"Como posso chegar a...",
"Você pode me ajudar a me orientar aqui na cidade?",
"Onde posso encontrar...",
"Você pode me falar sobre alguém em quem estou interessado?",
"Gostaria de algumas informações sobre um colega local. Você pode ajudar?",
"Estou me perguntando o que as pessoas na cidade têm a dizer sobre uma determinada pessoa...",
"O que você pode me dizer sobre #sSantiago#?",
"Gostaria de conhecer a história da sua cidade.",
"Gostaria de obter algumas informações sobre esta colônia.",
"Estou apenas andando aqui. Vejo você mais tarde.",
"Obrigado. Tem mais uma coisa...",
"Foi bom conversar com você. Contanto!",
"Qualquer outra coisa, capitão ",
"?",
"Vamos ouvir isso, ",
".",
"Estou ouvindo, ",
".",
"Qual é o assunto da cidade hoje em dia?",
"Que histórias os velhos cães-do-mar estão trocando por causa do rum hoje em dia?",
"Já faz muito tempo que não ponho os pés nestas praias. O que eu perdi?",
"Você poderia me dar algumas instruções?",
"Fiquei completamente perdido nestas ruas.",
"É minha primeira vez nesta cidade e gostaria de algumas orientações.",
"Gostaria da sua opinião sobre um cidadão local.",
"Preciso saber o que você pode me contar sobre alguém que mora aqui na cidade.",
"Você poderia me dar algumas informações sobre os habitantes locais?",
"Conte-me sobre #sSantiago#.",
"O que você pode me dizer sobre esta colônia?",
"Gostaria de saber algo sobre #sSantiago#.",
"Acabei de perceber que preciso estar em algum lugar. Adeus.",
"Quem é que queres dizer,",
"?",
"Você está perguntando sobre alguém específico?",
"Sobre quem exatamente você quer saber?",
"Quero dizer, o governador.",
"Estou interessado no dono da taberna.",
"O dono do estaleiro.",
"Estou falando do comerciante local.",
"Ninguém. Deixa para lá.",
"Ouvi dizer que ele trabalha em estreita colaboração com o governador de #sHavana#. Mas isso faz sentido, eu acho. Algumas pessoas dizem que ele tem medo de uma invasão de #sRedmond#.",
"Eu vejo. Eu tenho outra pergunta para você.",
"Obrigado tchau tchau.",
"Às vezes ele está ainda mais bêbado do que alguns de seus convidados. Isso é realmente irritante! Mas na maioria das vezes ele é um cara legal.",
"Eu vejo. Eu tenho outra pergunta para você.",
"Obrigado tchau tchau.",
"Ganhou muito dinheiro, por causa do importante nó comercial, não muito longe daqui. Os comerciantes são frequentemente atacados por piratas e bucaneiros. Acho que ele não obteve todo esse lucro se as pessoas não estivessem convencidas de seu trabalho.",
"Eu vejo. Eu tenho outra pergunta para você.",
"Obrigado tchau tchau.",
"Não vou muito à loja, gosto mais das bancas do mercado, então não conheço ele.",
"Eu vejo. Eu tenho outra pergunta para você.",
"Obrigado tchau tchau.",
"Onde você está indo, ",
"?",
"Não é um problema, capitão. Onde você precisa estar?",
"Fico feliz em orientá-lo ",
". Mas para onde você quer ir?",
"Como posso chegar à taberna?",
"Onde fica o estaleiro?",
"Onde posso vender os produtos que trouxe comigo?",
"OK. Começaremos em frente à mansão do governador. Vire as costas para a mansão para enfrentar uma praça. A taberna fica no extremo esquerdo, tem uma pequena escadaria.",
"Certo. Obrigado pelo seu tempo.",
"Onde fica o estaleiro?",
"Onde posso conseguir um preço decente pelos produtos finos que trouxe para a cidade?",
"O estaleiro fica na zona portuária. É um edifício de três andares perto do portão de saída da cidade. ",
"Eu vejo. E a taberna?",
"Onde posso conseguir um preço decente pelos produtos finos que trouxe para a cidade?",
"Eu acho que isso é tudo. Obrigado pela ajuda.",
"Você tem que caminhar um pouco! Passe pela casa do governador até chegar ao grande edifício em arco. A partir daí vire à direita e procure um grande edifício castanho com toldos nas janelas.",
"Onde posso encontrar o estaleiro local?",
"Como faço para chegar à taberna?",
"Eu vejo. Obrigado pela informação.",
"Não sei por que você estaria interessado, mas por que não?",
"No que exatamente você está interessado ",
"?",
"Claro, ",
". Felizmente, é uma história bastante curta.",
"Estou interessado na história da colônia...",
"Conte-me sobre a colônia.",
"Existe alguma coisa na ilha além da cidade?",
"Tenho mais algumas perguntas para você, se não se importa.",
"Fundado a 25 de Julho, #sSantiago# foi e ainda é um importante porto da Armada Espanhola.",
"Obrigado. Deixe-me fazer mais algumas perguntas.",
"Sabe, eu realmente pensei que seria mais interessante. Deixe-me perguntar outra coisa.",
"Isso é tudo que preciso. Obrigado.",
"Obrigado pelo seu tempo. Até a próxima.",
"Bem, temos #sHavana# do outro lado desta ilha. Também esta é a maior ilha do arquipélago. Eu ainda não examinei todas as partes, então não posso lhe dar muitas informações sobre isso.",
"O que mais você pode me contar sobre a colônia?",
"O que mais você pode me dizer?",
"#sSantiago# também é um grande porto para o comércio de escravos.",
"Eu vejo. O que mais?",
"Não. Você encontrará algumas plantações e casas nesta parte da ilha, mas ela é praticamente subdesenvolvida.",
"Nesse caso, talvez você possa me contar mais sobre a colônia.",
"Entendi. Deixe-me perguntar outra coisa.",
"Você conhece um contramestre chamado Fred Bob?",
"O que você pode me dizer sobre o capitão do porto?",
"Ah, Fred Bob? Ele não é um amotinado, isso eu lhe garanto! Ele é um bom marinheiro e um homem forte para ter ao seu lado quando você está em menor número. Pena pela sua prisão. Todos esperamos que o governador o liberte, porque ninguém, exceto aquele pomposo primeiro oficial, acredita que ele é culpado.",
"Interessante. Ah, eu tenho outra pergunta para você.",
"Muito obrigado, adeus.",
"Não sei como ele faz isso, mas o nosso capitão do porto faz questão de conhecer todos os marinheiros do arquipélago.",
"Eu vejo. Mais uma pergunta, se não se importa, por favor?",
"Obrigado pelo seu tempo. Tchau.",
"Fred Bob? O contramestre? Ele é muito difícil de entender, mas meu irmão o conhece bem. Ele não é um amotinado. Esse oficial entendeu tudo errado. Todos esperamos que o governador o liberte. Ele pertence a um navio, não a uma paliçada.",
"Bom homem, excelente marinheiro. Não acredito nem por um minuto que ele ameaçou um motim.",
"Ehm... eu esqueci quem eu ia perguntar. Apenas me dê um segundo e isso voltará para mim...",
"Como está aquele velho metalúrgico Tomas hoje em dia?",
"Você quer dizer Tomasina, não é comandante gobeur? O velho Tomas morreu há pouco tempo, e agora é sua esposa presidindo a bigorna. Também não posso dizer que ela faz um mau trabalho.",
"Nossa... ela não fica irritada com frequência nessa profissão? Deixa para lá; para coisas mais felizes.",
"Bem. Uma viúva elegível que pode consertar uma lâmina? Terei que prestar meus respeitos imediatamente...",
"Minha melhor espada favorita do mundo aqui ficou um pouco chata ultimamente. A quem posso confiar isso?",
"Nosso ferreiro trabalha ao ar livre. Comece na prefeitura e siga em direção ao grande edifício em arco. Pouco antes do primeiro conjunto de pequenos passos, procure uma barraca à sua esquerda.",
"Uma barraca aberta como um comerciante, então? Espero que ele consiga manter sua fornalha quente quando o tempo estiver frio!",
"Onde fica o estaleiro?",
"Onde posso conseguir um preço decente pelos produtos finos que trouxe para a cidade?",
"A quem posso confiar minha espada? Sua borda antes fina tornou-se um pouco opaca.",
"Existe alfaiate em algum lugar de #sSantiago#?",
"Procure o grande edifício em arco. Você pode vê-lo no caminho para a loja. A alfaiataria fica ao lado, perto da muralha da cidade.",
" Temos uma população de ",
" cidadãos.",
"Meu vizinho trabalha na residência do governador. Ela diz ",
" não está nem um pouco ansioso pelo casamento, pensa o ",
" é cruel e arrogante. Pobre coisa! Quase te deixa feliz por ser pobre, pelo menos você pode casar com quem você ama.",
"sua filha",
"o filho dele",
"Você perdeu a emoção. Houve algum tiroteio!",
"O que aconteceu?",
"Não muito, na verdade. Ouvi o tiro, olhei de onde veio, mas não vi corpo. A arma do soldado deve ter disparado acidentalmente.",
"Então foi um soldado quem disparou?",
"Sim. Estranho, no entanto. Ele não carregava um mosquete como todos os outros soldados.",
};
