string DLG_TEXT[18] = {
"Há rumores de que você precisa de ajuda para conseguir alguns recursos, é verdade?",
"Sim, na verdade estou precisando de alguns suprimentos. O lojista diz que não terá nenhum desses suprimentos tão cedo. Você poderia me buscar ",
" Vou te pagar ",
" moedas de ouro. Por favor, pegue antes ",
"Sou seu #sgender#. Você terá esses suprimentos em pouco tempo.",
"Desculpe, não posso ajudá-lo ainda.",
"Que pena, vou precisar dos suprimentos antes ",
"Tenha um bom dia.",
"Muito obrigado. Só para avisar, se você não entregar no prazo, não poderei finalizar este pedido. Então terei que cancelá-lo e também não poderei pagá-lo.",
"Farei o meu melhor por você.",
"Trouxe os produtos que você pediu.",
"Me desculpe. Infelizmente não consegui entregar a mercadoria para você a tempo.",
"...",
"Como prometido, aqui está o seu pagamento. Muito obrigado por entregar esses produtos.",
"Não consegui entregar toda a sua carga de uma só vez, então aqui está a primeira parte.",
"Ah, muito obrigado. Por favor, pegue o resto o mais rápido possível. Já vou utilizar esses recursos, então se você não entregar o restante ainda terei que cancelar o pedido, mas também não posso devolver esses recursos, só para você saber.",
"Quer saber, vou mantê-los comigo até ter tudo",
"Hoje é seu dia de sorte, tenho o que você precisa no porão do meu navio.",
};