string DLG_TEXT[92] = {
"Bom dia, ",
". Você tem algo a relatar?",
"Bom Dia senhor. Nada a relatar, senhor.",
"Quem é você?",
"Eu sou ",
", senhor.",
"Ah, ",
", é bom ver você novamente.",
"Parabéns pela sua promoção para ",
"Obrigado, senhor.",
"Por que você ainda esta aqui? Você conhece o seu dever - cumpra-o!",
"Er, sim, senhor.",
"Tenho ordens para você. Você deve pegar uma remessa de mosquetes e munições e entregá-los a um rebelde chamado ",
". Ele assumiu o forte em Playa de Sabana.",
"Conheço aquele forte, senhor. Nós explodimos tudo para evitar que um bando de rebeldes assumisse o controle. Se me permite perguntar, senhor, por que os estamos ajudando agora?",
" está lutando contra os espanhóis, que são nossos inimigos. O velho ditado O inimigo do meu inimigo é meu amigo se aplica. Aparentemente ",
" reparou o forte. E eu aconselharia você a não mencionar sua parte na destruição. Ele é conhecido por ser um homem de temperamento violento.",
"Se me permite perguntar, senhor, por que estamos ajudando um bando de rebeldes?",
" está lutando contra os espanhóis, que são nossos inimigos. O velho ditado O inimigo do meu inimigo é meu amigo se aplica. Mas tenha cuidado ao lidar com ",
" já que ele é conhecido por ser um homem de temperamento violento.",
"Entendo, senhor. Esperançosamente, esse temperamento será desabafado sobre os espanhóis.",
"Essa é a ideia geral, sim. Agora, as armas já estão sendo carregadas em seu navio. Termine de abastecê-la e navegue para Playa de Sabana o mais rápido possível.",
"Sim senhor.",
"Essa é a ideia geral, sim. Mas fui informado que o seu navio já está muito carregado. Libere algum espaço em seu porão e volte aqui. Então ordenarei que a munição seja carregada a bordo do ",
"Sim senhor. Vou à loja agora.",
"Você ainda não tem espaço suficiente para o pó que vai levar. Libere mais espaço, ",
"Muito bom, ",
". Já dei ordens para que a munição fosse transferida para o ",
". Você deve partir para Playa de Sabana o mais rápido possível.",
"Muito bem, senhor. Partirei para Playa de Sabana assim que estiver a bordo do ",
"Agora, os franceses enviaram uma esquadra de quatro navios de linha para #sisland_Hispaniola#. Eles provavelmente irão ancorar em #sPort au Prince#.\nVocê se juntará ao meu esquadrão. Bloquearemos #sPort au Prince# e engarrafaremos a força francesa no porto.",
"Desculpe, senhor, mas e se a esquadra francesa ancorar em #sSanto Domingo#?",
"Hum. O que você sugere, ",
"Talvez eu pudesse pegar o ",
" para #sSanto Domingo# para ver se os franceses estão lá.",
"De fato. Eu li sobre sua carreira ",
". Muito propenso a tomar medidas individuais. Depois do prêmio em dinheiro para você, o quê?",
"Certamente não, senhor!",
"Hum. Muito bem. Quando nos aproximarmos de #sisland_Hispaniola#, você deverá se separar do meu esquadrão. Você irá para #sSanto Domingo# e verificará se os navios franceses estão lá.\nSe estiverem, você deverá se juntar a mim em #sPort au Prince#. Em vez disso, bloquearemos #sSanto Domingo#.\nEm nenhuma circunstância você deverá enfrentar a frota francesa sozinho. Isso é entendido ",
"Entendido, senhor.",
" ao seu serviço, senhor.",
"Lady Barbara Wellesley está a bordo, não está?",
"Ela foi informada da sua chegada, senhor.",
"Suas façanhas no mar, ",
", tornaram você bastante famoso. Na verdade, quando você fizer seu relatório ao QG Naval, provavelmente descobrirá que tem algo melhor para comandar do que este pequeno ",
"-artilheiro.",
"Fiz pouco para merecer isso, senhor.",
"Claro, acredito pessoalmente que você teve muita sorte em derrotar a 'Natividad', tendo primeiro a entregado, como fez, por sua própria iniciativa.",
"Parecia a melhor coisa a fazer naquele momento, senhor.",
"O capitão de uma fragata normalmente não decide a política do Almirantado.",
"Não havia como consultar o Almirantado, ou eu o teria feito.",
"Mas sério, Hornblower - dando um prêmio de 60 armas para um louco!",
"Eu estava pronto para responder pelas minhas ações, senhor.",
"Se você estivesse servindo sob meu comando, você teria respondido por isso, tudo bem! Uma corte marcial pode ter considerado sua ação irresponsável.\nAlém disso, isso fez com que você arriscasse a vida da irmã do duque de Wellington.",
"Peço desculpas por isso, senhor.",
"Teria sido muito difícil para você ",
", se alguma coisa tivesse acontecido com ela. Eu também valorizo muito Lady Barbara. Vamos nos casar.",
"Sim, foi o que Lady Barbara me contou, senhor.",
"Suponho que um navio deste tamanho seja bastante confinado e as confidências provavelmente serão mais livres do que em circunstâncias normais.",
"Aqui está você, finalmente, minha querida. Você não tem ideia de como estou preocupado com o seu bem-estar.",
"Devemos ir? Sua família espera impacientemente por você em Londres, e depois disso, minha família na Irlanda.",
"Capitão ",
", estamos no mar há mais de um mês",
", e ainda assim não parecemos estar perto de #sisland_Saint Martin#. Tendo sido informados de que é um bom navegador e conhece estas águas, podemos assumir que não é por acaso. Você tem algo a dizer em sua defesa?",
"Não tenho desculpa, senhor.",
"O Almirante Pellew deu-me ordens secretas, senhor.",
"Mentir não vai te ajudar, Hornblower. Eu poderia ter acreditado nisso se você tivesse pedido para se separar do esquadrão para seguir sozinho essas supostas ordens. O mais provável é que, uma vez que sou eu quem comando este esquadrão, Sir Edward Pellew teria pelo menos a cortesia de me informar que você estava sob ordens, mesmo que fossem tão secretas que ele escondeu os detalhes de mim.",
"Não tenho mais nada a dizer, senhor.",
"Então me parece que, na melhor das hipóteses, você tem usado os navios de Sua Majestade para perseguir seus próprios objetivos, que são o motim; ou você atrasou deliberadamente a nossa viagem para permitir que os franceses entrassem no Caribe sem impedimentos, o que é alta traição. Uma corte marcial determinará a acusação exata, mas para você isso não faz diferença.\nA pena para ambos é a suspensão. A sentença será executada imediatamente.",
"Bem, senhores, agora que finalmente estamos todos reunidos, tenho algumas notícias bastante surpreendentes que acabaram de me ser enviadas por Cutter. Os franceses quebraram o bloqueio de McCartney em #sMarigot#. O velho supostamente tinha os navios de Napoleão presos lá. Uma névoa de sopa de ervilha se instalou por 48 horas. Quando levantou, quatro navios da linha haviam escapado.",
"Alguma ideia do curso que eles tomaram, senhor?",
"O único lugar para onde eles poderiam ir é #sisland_Hispaniola#. Portanto, se continuarmos a partir da nossa posição aqui, iremos interceptá-los a caminho de #sPort au Prince#. Quatro contra quatro, o resultado é óbvio.",
"Aham... aham...",
"Você não parece concordar, capitão ",
". Posso perguntar para onde mais eles iriam, exceto para #sPort au Prince#?",
"Submeto senhor, a #sSanto Domingo#.",
"O extremo sul de #sisland_Hispaniola#? Absurdo! Por que deveriam? De #sPort au Prince# eles podem contra-atacar os rebeldes em #sisland_Cuba#.",
"Mas se eu fosse o comandante francês, senhor, consideraria a possibilidade de um ataque contra #sisland_Redmond#.",
"Os franceses nunca arriscariam quatro navios em uma aposta selvagem contra o forte de #sRedmond#.",
"Eles poderiam, se conseguissem destruir nossa base mais próxima de #sisland_Cuba# antes de atacar aquela ilha. Afirmo com muita urgência, senhor, que em vez de nos concentrarmos em #sPort au Prince#, nos movamos ao longo da costa sul de #sisland_Hispaniola#.",
"Seria muito difícil pagar com o Almirantado se os franceses fossem para o norte e chegassem a #sPort au Prince# ininterruptamente.",
"Pode haver o diabo a pagar se eles atacarem #sRedmond#.",
"Talvez pudéssemos cuidar de ambas as possibilidades com uma implantação ampla. Três de nós nos concentramos na abordagem norte de #sPort au Prince# e um navio costeiro cobrindo o sul.",
"Boa ideia, ",
"! Veja, não tenho nenhuma objeção a uma sugestão prática. Eu acolho isso, na verdade. Temos uma guerra para vencer.\nMuito bem, então, quem vai para o litoral sul? Qual dos nossos navios tem o calado mais raso?",
"O 'Sutherland', senhor. Construído francês.",
"Oh, agora vejo o que estava influenciando você ",
". A perspectiva de ganhar um prêmio ou dois, hein?",
"De jeito nenhum, senhor!",
"Bem, vou me certificar disso. Eu sei como você gosta de agir por sua própria iniciativa. Estou ordenando que você não arrisque seu navio de forma alguma, por qualquer motivo. Não quero nada estúpido. Se você avistar os navios inimigos, você me trará a notícia e nós os destruiremos juntos. Está claro?",
"Perfeitamente claro, senhor.",
"Mesmo assim, coloque por escrito.",
}
