string DLG_TEXT[95] = {
"Olá! Eu sou ",
"E eu sou ",
"É um prazer conhecê-lo. Sou um tipo de pesquisador de artefatos antigos - estatuetas, esculturas, esse tipo de coisa. E caveiras de cristal. Tenho uma coleção considerável - de fato, até poderia me desfazer de algumas delas, pela quantia certa de dinheiro. Mas há uma caveira em particular que é muito rara - acredito que possa haver apenas uma. Como você parece ser um tipo de #sperson#, talvez estaria disposto a me ajudar a adquiri-la?",
"Bem vindo de volta, ",
"! Você está interessado em encontrar a caveira indescritível que falta na minha coleção ou gostaria de comprar um dos tipos mais comuns?",
"Conte-me mais sobre esse crânio desaparecido.",
"Que caveiras você tem à venda?",
"Crânios? Er... hoje não, obrigado.",
"Os crânios são todos feitos de cristal. Pelo que descobri, parece que foram criados pelos maias para algum tipo de ritual.\nOs que posso vender são de cristal vermelho, branco ou azul.",
"Eu gostaria de comprar uma caveira de cristal branco.",
"Você poderia me dar uma caveira de cristal vermelho?",
"A caveira de cristal azul é a que me interessa.",
"Pensando bem, não estou muito interessado em comprar uma caveira. Mas aquele que falta parece interessante.",
"Na verdade, acho que não estou interessado em comprar uma caveira, afinal. Adeus.",
"Posso deixar você ficar com uma caveira vermelha ",
"A caveira branca só vai te custar ",
"A caveira azul é a mais rara e a mais cara. Eu só posso deixar isso passar ",
" moedas de ouro.",
"Nós temos um acordo. Aqui está o seu dinheiro.",
"Eu não tenho tanto. Talvez outra hora.",
"Não estou disposto a pagar tanto por uma bugiganga!",
"Foi um prazer fazer negócios com você, ",
"Como quiser. Talvez possamos fazer negócios outro dia. Até então, adeus ",
"Adeus.",
"Como todas as caveiras de cristal, a caveira de âmbar que procuro foi feita pelos maias. Mas pelo que descobri, parece que o crânio foi roubado pelos índios caribenhos.\nOs caribenhos viviam originalmente no continente antes de migrarem para o mar que leva o seu nome. Uma das tribos que se estabeleceram entre estas ilhas é a que levou a caveira de âmbar.",
"Você sabe onde essa tribo pode ser encontrada?",
"Todas as minhas pesquisas sobre este assunto apontam para #sisland_Guadeloupe#. Mas esteja avisado! Os caribenhos não são como os pacíficos Arawaks que você pode ter conhecido em outros lugares. Eles são mais propensos a serem hostis.",
"Então eles são selvagens?",
"Até certo ponto. Eles fazem guerra com outras tribos, mas nós também fazemos guerra com outras nações.\nMas há algumas evidências de que os caribenhos praticam o canibalismo ritual.\nNa verdade, porém, a principal razão pela qual pensamos nos caribenhos como 'selvagens' é simplesmente porque eles são mais eficazes do que os Arawaks na resistência à nossa intrusão nas suas terras.",
"E o que eu ganho se eu lhe trouxer esta caveira âmbar?",
"O que mais? Ouro, e muito, para um item tão único!",
"Muito bem. Tenho certeza de que posso persuadir os caribenhos a entregá-lo, seja por comércio ou pela força. Navegarei para #sisland_Guadeloupe# o mais rápido possível.",
"Ouro não adianta se você não estiver vivo para gastá-lo! Não vou arriscar enfrentar uma tribo inteira de índios hostis.",
"Excelente! Estou ansioso para ver a caveira ocupar seu lugar na minha coleção. Até a próxima, ",
"Justo. Avise-me se mudar de ideia - mas não demore muito, pois pode haver outros aventureiros mais ansiosos para aceitar o trabalho. Adeus.",
"Bem, ",
"? Você reconsiderou minha proposta? Ou você deseja comprar um dos meus outros crânios?",
"Na verdade, reconsiderei sua proposta. E eu decidi aceitar.",
"Como vai sua busca pela caveira âmbar ",
"Ainda não encontrei a tribo em #sisland_Guadeloupe#.",
"Bem-vindo de volta, Capitão ",
"! Você trouxe a caveira de âmbar?",
"Não, não consegui trazer para você.",
"Não, eu dei aos caribenhos.",
"Sim. Agora, sobre o ouro que você prometeu em troca?",
"Isso é uma pena. Então provavelmente não teremos mais assuntos a discutir.",
"Errado. Fale-me sobre ",
"Realmente? Conte-me tudo, por favor. Se não posso ficar com a caveira, talvez pelo menos possa ficar com a sua história?",
"<Você diz ",
" sobre suas aventuras.>",
"E então você deu a caveira de cristal ao chefe caribenho? Talvez seja melhor assim - afinal, era deles.",
"O chefe sentiu-se obrigado pela honra a me dar algo em troca - esta machadinha.",
"Verdadeiro. E eu ",
"recuperei o meu oficial ileso.",
"recebeu o antídoto para o seu veneno.",
" E agora é hora de eu ir. Adeus, ",
"Deixe-me ver... Que arma magnífica! Essa é uma machadinha cerimonial - muito eficaz em batalha, tenho certeza, mas é muito mais. O chefe não teria dado algo assim levianamente.\nVocê estaria disposto a vendê-lo? Estou disposto a oferecer 15.000 moedas de ouro por isso. Você receberia talvez um décimo disso de qualquer pessoa que não conheça seu valor cultural.",
"Não, acho que vou segurar. Nunca mais vou conseguir nada parecido.",
"15.000, você diz? Muito tentador. Tudo bem, temos um acordo.",
"Para algo tão importante como você diz, tenho certeza de que você poderia fazer melhor do que isso. Faça uma rodada de 20.000 e teremos um acordo.",
"Você barganha muito bem! Mas preciso daquela machadinha. Muito bem, são 20.000.",
"Foi bom fazer negócios com você.",
"Primeiro, como você conseguiu a caveira de cristal?",
"Os caribenhos me emboscaram. Eles ",
"tomaram um dos meus oficiais como refém e disseram q a caveria estava em Martinica.",
"disse que as flechas que me atingiram estavam revestidas com um veneno que levaria dois meses para me matar.",
" Mas posso conseguir oficiais substitutos com bastante facilidade na taverna.",
" Mas eu não acredito neles. Um veneno mata você ou não. Não espera dois meses.",
" Então fui junto buscar a acaveira. Depois, quando voltamos para os caribenhos, lutei contra eles e fiquei com a caveira.",
"Estou feliz por não ser um de seus oficiais, se você os sacrifica tão prontamente! Mas estou disposto a oferecer 20.000 moedas de ouro pela caveira.",
"Não tenha tanta certeza. Os Caribenhos não são bons em blefar, mas são bons com venenos. Se eles disserem que te atingiram com um veneno que te mataria em dois meses, você deveria acreditar neles. E isso significa que nosso acordo muda.",
"Muito astuto! Quanto ao pagamento, estou disposto a oferecer 20.000 moedas de ouro pela caveira.",
"Parece um preço justo pelo que foi necessário para obter a caveira. Muito bem.",
"Você está mudando o acordo? Como exatamente?",
"Você tem algo que eu quero: aquela caveira. Tenho algo que você deseja: o antídoto para o seu veneno. Então proponho uma troca simples.",
"Parece que não tenho escolha. Aqui está o crânio. Agora me dê o antídoto!",
"Ainda não estou convencido. Eu quero o ouro que você prometeu!",
"Espere aqui. Vou buscá-lo no meu depósito.",
"Eu não estou indo a lugar nenhum. Nem você, se tentar me trair.",
"Não adiantará muito se você morrer antes de poder gastá-lo. E imagino que a maior parte dos seus dois meses já se passaram.",
"E agora, há mais alguma coisa que eu possa fazer por você?",
"Sim. Você pode me contar sobre ",
". Como ele sabia onde me encontrar?",
"? Eu usei seus serviços no passado. Ele é... bom em adquirir coisas.",
"Foi bom, você quer dizer. Pretérito. Ele é comida de tubarão agora. Mas isso não responde à minha pergunta. Como ele sabia sobre o crânio? Você decidiu mandá-lo também?",
"Não não! Eu já tinha lhe dado o trabalho - não faria sentido enviar outra pessoa também!\nMas confesso que discuti a caveira com um dos meus colegas. Provavelmente foi ele quem decidiu enviar ",
" para conseguir a caveira de cristal para ele. Talvez ele pretendesse vendê-lo para mim, ou talvez pretendesse reivindicar o crédito pela minha pesquisa. De qualquer forma, terei uma conversa com ele, você pode ter certeza disso!",
"Eu preferiria ter uma discussão aguçada com esse 'colega'. Quem é ele?",
"Sua 'discussão aguçada' provavelmente envolve suas armas. Não posso tolerar tal ato. Mas tenha certeza, depois que eu terminar com ele, ele estará completamente arruinado. Se, na sua próxima visita a esta cidade, você vir um mendigo na cidade, pode ser ele.",
"Muito bem, suponho que seja uma vingança adequada. Bem, adeus por enquanto.",
"Isto é o que preparei, com base na minha pesquisa sobre os venenos caribenhos. Beba tudo, de preferência de uma só vez. Tem um gosto horrível, mas deve curar você.",
"Deve? Você não pode dar uma garantia melhor do que essa?",
"Ninguém nunca relatou que não funcionou.",
"Bem não. Se não funcionasse, eles não funcionariam, não é mesmo? Mas se isso não funcionar, alguns membros da minha tripulação garantirão que você não sobreviva a mim por muito tempo.",
"! Você gostaria de comprar um dos tipos mais comuns de caveira de cristal?",
}
