string DLG_TEXT[97] = {
"O que você quer, capitão?",
"Eu sou ",
".",
"Eu sou ",
", dono do '",
".",
"O que você tem para mim, capitão?",
"Alguns produtos para vender.",
"Nada. Adeus.",
"Como posso ajudá-lo, capitão?",
"Eu quero vender algo.",
"Você não pode. Adeus.",
"Hm... receio que você esteja enganado. Vá até a loja - eles comprarão com prazer o que você tem.",
"Receio que uma loja não possa me ajudar.",
"Obrigado pelo conselho. Adeus.",
"É assim mesmo?",
"Tenho algo que nenhum comerciante comprará.",
"Talvez você devesse terminar um negócio antes de começar outro?",
"Acho que você está certo.",
"Ah, aí está você de novo! Espero que você saiba o que está fazendo e esteja disposto a correr riscos, pois os navios e soldados da guarda costeira nem sempre trabalham juntos. Só estou avisando que embora você possa evitar o primeiro, os outros ainda poderão pegá-lo. Meus amigos vão esperar alguns dias no lugar chamado ",
"Hmm... talvez eu possa te ajudar. Vou encontrar um cliente para você. Mas você deve tomar cuidado com a guarda costeira! Eles não gostam que ajudem as pessoas pobres da cidade como nós. Você deveria descobrir mais sobre suas patrulhas pela ilha. ",
"Ok, obrigado.",
". Por favor, não os faça esperar muito. ",
"Ok, estou a caminho. Afinal, você tem que correr riscos se quiser ficar rico.",
" Aqui está uma coisinha para ajudá-lo.",
"Me avisa quando você estiver pronto. ",
"A guilda dos contrabandistas proibiu você. Parece que você não fez bem à nossa causa. Mas se você pagar ",
" moedas de ouro esqueceremos que isso aconteceu.",
"Esqueça, vou tentar a sorte em outro lugar.",
"Sinto muito pelo que fiz. Aqui está o seu dinheiro.",
"Obrigado. Este dinheiro apoiará a nossa causa. Por favor, permita-me um momento para anotar isso para que eu não esqueça.",
"Eu queria saber se você pode estar interessado em uma determinada substância peculiar.",
"Vejo que você tem um pouco de ópio! ",
"Certamente estamos interessados em opiáceos. Alguns de nossos irmãos os contrabandeiam para vários clientes espalhados por todo o Caribe.",
"Posso obter uma lista desses clientes?",
"Aqui você vai. Para ajudá-lo, incluí também um livro para explicar como funciona esse contrabando de ópio.",
"Muito obrigado.",
"Eu sugiro que você tente conversar com um soldado nesta taverna, a maioria deles são bêbados crédulos e vão te contar qualquer coisa, principalmente se você untar um pouco a palma da mão deles. Se não houver soldados aqui, passe algum tempo na sala da taverna, ou vá fazer outra coisa e volte para a taverna mais tarde, eles certamente aparecerão.",
"Eu vejo.",
"Ou se algum de seus oficiais estiver se sentindo corajoso ou imprudente, você pode conversar com ele e pedir-lhe que vá buscar informações para você. Contudo, pode ser perigoso se as patrulhas forem intensas. Se você tiver alguém com boa sorte, uma língua de ouro e, se as coisas derem errado, um braço de espada forte e, finalmente, alguma experiência de contrabando, essa pessoa provavelmente terá mais chances de encontrar o que você precisa.",
"Sim, eu poderia fazer isso, não poderia? Alguns deles têm mais coragem do que bom senso e se voluntariam para qualquer coisa.",
"Depois de fazer isso, volte e fale comigo. Você também deve fazer isso se não souber os horários das patrulhas da guarda costeira. Então podemos discutir o que fazer a seguir.",
"Ok, vou ver o que posso descobrir.",
"Lembre-se, volte e fale comigo aconteça o que acontecer.",
"Sim, sim, eu entendo.",
"Você conhece os efeitos dessa coisa de ópio aqui?",
"Nossos compradores parecem apreciar muito seus efeitos. Alguns dizem que isso os ajuda a ver as coisas melhor. Usei apenas uma vez e me deixou muito doente. Você pode consultar alguém com um conhecimento mais profundo de medicina.",
"Entendido. Tenho certeza de que poderia encontrar uma pessoa assim se quisesse. Obrigado pela ajuda.",
"Sinto muito, tudo isso parece muito arriscado para mim. Receio ter que cancelar o negócio.",
"Muito bem então. Estarei de volta em um minuto.",
"Agora, o que você estava perguntando antes?",
"Então é o seu navio que eles estão vigiando, hein?",
"Huh, do que você está falando?",
"Aqueles nativos irritantes apareceram hoje e não conseguimos descobrir o que eles procuravam. Mas agora vemos que eles estão vigiando o seu navio.",
"E por que isso deveria te incomodar?",
"Bem, isso está dificultando um pouco o nosso... uhm... negócio legítimo. Mas também pode nos oferecer algumas oportunidades. Se você estiver interessado em tais oportunidades, venha falar comigo na taverna. Mas não espere muito, senão a chance terá passado.",
"Ok, vou pensar sobre isso.",
"Você disse algo sobre oportunidades. Estou interessado em ouvir mais.",
"Ah! Bem, você vê que há alguém que conhecemos que está muito interessado nos povos nativos que você verá por aí. Principalmente nas armas que carregam. Ele nos pediu para lhe fornecer 10 arcos. Normalmente isso seria muito difícil porque esses nativos mantêm distância e não querem se desfazer de suas armas. Mas agora nós os vemos por toda a cidade, então talvez você possa conseguir essas armas deles?",
"Isso não parece muito difícil. O quê tem pra mim?",
"Isso parece muito suspeito, acho que vou passar.",
"Ok, vamos encontrar outra pessoa para fazer isso...",
"OK.",
"O colecionador prometeu um preço muito bom se você conseguir entregá-los antes de dois meses. Depois de reuni-los, fale comigo novamente e eu lhe darei informações sobre onde entregá-los.",
"Ok, voltarei antes que você perceba.",
"Reuni todas as armas necessárias.",
"Excelente, agora leve-os para ",
" no ",
" sobre ",
" então concluirá o negócio. Lá você também receberá seu pagamento.",
"Obrigado, estou a caminho.",
"Percebi que você está tendo alguns problemas com esse cara, Thomas O'Reily. Eu o vi também lidando com povos nativos. Achei que você poderia estar interessado em saber disso.",
"O'Reily! Oh sério? Aceite nossos agradecimentos e esta garrafa velha pelo seu trabalho. Não é muito, mas tenha certeza de que lembraremos de sua ação aqui. Nós cuidaremos disso com ele.",
"Obrigado, é um prazer.",
"As patrulhas têm sido negligentes ultimamente, então isso deve ser bastante simples. ",
"A guarda costeira tem patrulhado normalmente ultimamente, então esta deve ser uma troca de rotina. ",
"A segurança tem sido rigorosa, então tome cuidado. ",
"A ilha tem estado infestada de homens da guarda costeira ultimamente, por isso tome muito cuidado. ",
"As patrulhas estão escassas no momento, mas mesmo assim, fique atento.",
"Como eu disse, as patrulhas têm sido bastante padronizadas, então isso não deve ser nada fora do comum, mas tenha cuidado mesmo assim.",
"Lembre-se, as patrulhas têm aumentado ultimamente, então fique atento.",
"Patrulhas têm estado por toda parte ultimamente, então tome muito cuidado",
"Preciso comprar passagem para ",
".",
"Não operamos um serviço de passageiros. Vá e encontre um capitão de navio em algum lugar",
"É provável que nenhum capitão honesto queira me ajudar.",
"Eu vejo. Bem, transportar coisas que não deveriam ser transportadas é o nosso negócio, e suponho que isso também poderia se estender a pessoas que não deveriam ser transportadas. Você está com problemas para onde está indo?",
"Não, mas estou com problemas aqui.",
"Muito bem. Então providenciarei para que um de nossos capitães encontre você em ",
" amanhã à noite. Não se atrase. Ele não vai esperar, e você não terá outra chance",
"Obrigado pela ajuda.",
"Não tão rápido. Primeiro há a questão da sua tarifa. ",
" ouro, pagável antecipadamente, aqui e agora.",
"Muito bem, aqui está o seu dinheiro.",
"Eu não tenho tanto. Mas posso pagar-te o dobro quando chegarmos onde vamos.",
"Dobro? Tudo bem, podemos aceitar isso. No entanto, certifique-se de não tentar evitar o pagamento. Você não viverá para se arrepender",
"Não se preocupe com isso. Pagarei tudo bem - afinal, talvez um dia precise usar seus serviços novamente.",
};
