string DLG_TEXT[76] = {
"O que você está fazendo aqui?",
"Relaxe, eu trouxe a mercadoria!",
"O que você acha? Eu trouxe a mercadoria!",
"Olha, saia daqui! Se você estragar o negócio, nós te mataremos!",
"Você se atreve a me ameaçar?",
"Você vai engasgar com essas palavras, canalha!",
"Acalmar. Estarei à caminho. Adeus.",
"Suponho que você os tenha em seus bolsos? Vamos, onde está seu navio e as mercadorias?",
"Eu queria ter certeza de que tudo estava bem primeiro.",
"Eu não queria arriscar meu navio. Queria primeiro verificar se estava tudo bem.",
"O negócio acabou!",
"Não vamos enganar você. Vamos, traga seu navio e fique atento às patrulhas costeiras.",
"Tudo bem. Espere por mim aqui.",
"O que? Você está brincando?",
"Estou falando sério.",
"Você não pode nos enganar assim! Você vai pagar por isso com a cabeça!",
"Eu duvido!",
"Você vai se arrepender disso!",
"Vão uivar para outro lugar, cães com escorbuto!",
"Você vai se arrepender disso!",
"Vão uivar para outro lugar, cães com escorbuto!",
"AHA bom. Então...",
". O preço é ",
". Assim será ",
" total. Negócio?",
"Negócio.",
"Não há acordo. Vou procurar outro comprador.",
"O que você está fazendo aqui? Você não tem nada para vender! Não é isso que queremos. Tudo o que você tem podemos comprar na cidade!",
"Sem sorte.",
"Fico feliz em ouvir isso. Devemos continuar? ",
". O preço é ",
". Assim será ",
" total. Negócio?",
"Negócio.",
"Não há acordo. Vou procurar outro comprador.",
"Bem...",
". O preço é ",
". Assim será ",
" total. Bom o bastante?",
"Claro.",
"Não. Acho que vou procurar outro comprador.",
"E finalmente...",
". O preço é ",
". ",
" total. Está tudo bem?",
"Sim.",
"Não há acordo. Vou procurar outro comprador.",
"Sem sorte? Você marca uma reunião e depois diz 'sem sorte'? Saia daqui. Seria sensato honrar seus negócios no futuro!",
"Você esperava honra entre ladrões? É engraçado.",
"A soma total é ",
" ouro. Seu dinheiro, nossos produtos!",
"Negócio!",
"Demais! Sem acordo!",
"Aqui está o seu dinheiro. Agora vamos descarregar as coisas...",
"Minha equipe já o jogou na praia. Eu não queria esperar a guarda costeira aparecer.",
"Você não irá a lugar nenhum daqui. Agora que tenho seu dinheiro, ficarei com a mercadoria também. E para escapar da ira dos seus irmãos contrabandistas, direi que a guarda costeira matou você e confiscou o contrabando. É claro que não deve haver testemunhas, o que significa...",
"Inchar. Adeus então.",
"Até a próxima.",
"Espere um minuto! Estou com um pouco de falta de provisões para meu navio. Por acaso você tem essas coisas naquela pilha de mercadorias ali?",
"Essa pilha contém, de fato, provisões, retiradas... eh... resgatadas de um navio que... umm... sofreu um infeliz acidente perto desta praia. Mas estávamos prestes a queimar tudo, não podemos nos preocupar com coisas tão pouco lucrativas e não devemos deixar evidências... eh... lixo nesta linda praia. Você pode comprá-lo, tudo ou nada, por 1000 G.",
"Adoro comprar pacotes surpresa! Aqui está o dinheiro, jogue tudo no meu porão. Foi um prazer fazer negócios com você, adeus.",
"1000 ouro por um monte de trigo encharcado e velas rasgadas? Não, obrigado e adeus.",
"Eu gostaria de pular isso, se você não se importa.",
"Muito bem.",
"Vamos continuar, certo?",
"Você pulou tudo! Eu pareço um idiota com quem você pode brincar?",
"Como você conseguiu afastar aqueles guardas? Isso foi muito fácil! Você vai nos trair, não é? En Garde!",
"Não... Não... ESPERE!",
"Por ordem do governador, você está preso. Larguem suas armas e sigam para o barco!",
"E ser levado para ser enforcado? Não é provável! Peguem #sperson#, rapazes!",
"Obrigado. Agora que vocês provaram que são contrabandistas, estão presos!",
"Um agente do governo! Matem #sperson#, amigos!",
"Então morra como os cães criminosos que você é!",
"Por quê você está aqui? Disseram-nos para esperar #samount# de #scargo#. Por que você não tem isso?",
"Por que você ainda esta aqui? Não temos mais negócios com você. Saia agora!",
"Tudo bem, estou indo.",
};
