string DLG_TEXT[21] = {
"Bom dia, senhor.",
"Bom Dia senhor.",
", Capitão da Marinha de Sua Majestade Católica. ",
"Sim.",
"Oh, graças a Deus, encontramos você a tempo ",
"! Você pode ter caído em desgraça com nosso navio 'Natividad' antes que eu pudesse lhe trazer a notícia maravilhosa!",
"Notícias?",
"#srank#, dou as boas-vindas a você como novo aliado da Espanha! Há semanas que o seu país e o meu têm sido irmãos de armas contra Napoleão. Juntos, com a ajuda de Deus, iremos destruí-lo!",
"...",
"Oh, talvez você pense que é bom demais para ser verdade! Aqui está uma carta do seu Almirantado.",
"Er... obrigado. Er... com licença. Senhor Bush!",
"No mês passado, Napoleão raptou o nosso rei e colocou o seu próprio irmão no trono de Espanha. Nosso governo no exílio concluiu imediatamente uma aliança com Sua Majestade Britânica. Você entende agora meu medo de ter encontrado a 'Natividad'. Seu Capitão também ignora a nova aliança.",
"Acontece... er... acontece, senhor, que na semana passada encontramos a 'Natividad'.",
"Ha ha ha! Você foi sábio em mostrar seus calcanhares ",
". Ela tem o dobro da sua força. Ho ho, imagine o que teria acontecido! Madre de Deus!",
"Nós... er... capturamos a 'Natividad', senhor.",
"That? Ah, ah, ah, ah! Impossível! Você está brincando!",
"Nunca estive tão sério na minha vida.",
"Oh Capitão, Capitão, não pode ser verdade! Você... você deu a 'Natividad' ao rebelde Don Julian? Mas há uma semana vocês já eram nossos aliados! Santa Maria! Você percebe o que fez? Não temos outro navio perto de #sisland_Cuba#! Eles vão queimar os nossos portos, saquear todas as nossas cidades!",
"Estou bem ciente da situação.",
"#sname#! ... Se quiser ultrapassar 'Natividad', devo pedir-lhe que saia imediatamente. Adeus, senhores. Senhor Bush, pode mostrar a estes senhores o lado de fora?",
}
