string DLG_TEXT[48] = {
"Olá, meu nome é ",
".",
"É muito bom conhecê-la, ",
", meu nome é ",
". Sinto muito, mas tenho negócios a tratar, vamos conversar em outra hora.",
"Olá, gata, meu nome é ",
", mas para você sou apenas ",
". Vejo você mais tarde.",
"Estou tão feliz em vê-la, ",
"!",
"Todo mundo na cidade está falando sobre você e suas façanhas!",
"Sim, sim, mas estou com pressa agora.",
"Agora não! Ah, desculpe, às vezes posso ser um pouco rude, mas conheço muito bem meu trabalho. Tenho coisas a fazer agora, mas falo com você mais tarde.",
"...",
"...",
"Olá, estranho. Você é o capitão, não é? A julgar pelo seu cheiro - Capitão! Ah, eu amo tanto o mar\nQueria que meu pai fosse capitão, eu navegaria com ele, pegando o spray das ondas, mas ele é apenas um comerciante... Diga-me como é navegar, sentir o convés sob meus pés...",
"Pare, pare, pare! Vamos um pouco mais devagar! ",
"Olá de novo, ",
"!",
"Olá, ",
". É bom ver você de novo. ",
"Pelo que entendi, você é filha de Jean Maginot",
".",
", e seu nome é...",
"Oh, eu não me apresentei! Estou tão distraída. Meu nome é ",
", e você adivinhou o nome do meu pai... Você o conhece?",
"Oh! Você conhece meu pai, então?",
"Claro que eu sei! Posso dizer que sou a confidente do seu pai!",
"Se eu o conheço ou não, não faz diferença para você? Agora saia do meu caminho, moça.",
"Ugh! Que cara rude! Meu pai definitivamente não vai mexer com pessoas como você!",
"Seu pai?! Ha! Receio que você não saiba muito sobre ele! E em geral - saia do caminho.",
"Estranho, mas ele não me contou nada sobre você...",
"Ha! Você acha que ele vai te contar todos os seus casos?!",
"Veja, os pais nem sempre iniciam seus filhos em seus planos e nem sempre os apresentam aos amigos...",
"Você está errado! Meu pai sempre me conta sobre todos os seus conhecidos e casos!",
"Como você é equivocado, baby, ha-ha.",
"Você pode estar certo, mas...",
"Vejo que você não acredita em mim... Talvez este anel faça você mudar de ideia?",
"O anel do papai?! Como você conseguiu?!",
"Veja bem... Ele está tendo problemas com alguns contrabandistas e está preocupado que você possa ser sequestrada...",
"Papai está com problemas?!",
"Sim, mas não se desespere, tudo ficará bem. Enquanto isso, ele me pediu para te esconder em algum lugar privado.",
"Ah! E ele te deu um anel para que eu acreditasse em você! Que pai inteligente!",
"Pronto, inteligente. Mas precisamos nos apressar. Corra para minha nave, a tripulação foi avisada e eu vou terminar alguns negócios aqui.",
"E minhas coisas? Que tal dizer adeus ao papai?!",
"Não temos tempo para isso!",
"Ok, tanto faz.",
"Vejo você na nave.",

};
