string DLG_TEXT[93] = {
"O que você está fazendo na minha casa ",
"?",
"Não se preocupe, já estou saindo.",
"Isso não é da sua conta, velha bruxa. Se você disser mais uma palavra, vai se arrepender de ter vindo ao mundo. Embora na verdade... eu não quero sujar minhas mãos ou minha espada com você, então vou embora.",
"Olá estranho, a que devo o prazer de recebê-lo em minha humilde morada?",
". ",
"Sabine Matton",
" sob minha proteção. Ela gosta de tagarelar mais do que qualquer outra pessoa que conheço. Você é madrinha dela?",
"Eu entendo que você é ",
" e ",
"Sabine Matton",
" quem eu trouxe aqui é sua afilhada?",
"Eu tenho a infelicidade de ter ",
"Você sabe, eu acho que há algo errado. ",
"Sabine Matton",
" sua afilhada pensa que a estou trazendo para você por causa do pai, mas tenho ideias diferentes.",
"Cale a boca, sua velha bruxa. ",
"Sabine Matton",
" sua afilhada está sob minha 'proteção' e serei eu quem decidirá o que fazer com ela.",
"O que aconteceu com minha afilhada?! O que você fez com ela?!",
"Não se preocupe tanto. Sua filha está no meu navio e ela está bem.",
"Apenas cale a boca. Não me irrite com seu choro. A garota está viva, mas é da minha conta o que eu faço com ela.",
"Ah, comecei a entender. O que você exige para sua libertação? Dinheiro, suponho?!",
"Você é bastante perspicaz. Eu realmente quero pagar para libertá-la.",
"Você está certo, é claro. O tilintar das moedas de ouro sempre foi música para os meus ouvidos.",
"Ah, me desculpe! Que bom que você me lembrou! Eu queria tirar um tiro dela o mais rápido possível.",
"Que ",
"Sabine Matton",
" me entediou até a morte com sua tagarelice incessante sobre as ondas e o céu. Leve a garota e boa viagem.",
"A garota fica comigo então eu realmente não tenho nada para conversar com você.",
"Você deve se acalmar, já que vou ficar com a menina comigo por enquanto, mais tarde veremos.",
"Quanto você quer, seu malandro, libertar minha garota?!",
"Quanto você pode oferecer, senhora?",
"Quanto ela vale para você? Diga-me o seu preço e depois veremos.",
"Eu te daria tudo o que tenho - 2.000 ouro.",
"Você tem um acordo. Dê-me o dinheiro e libertarei meu 'passageiro'.",
"Ah, você também é muito astuto e faz uma barganha difícil. Bem, dá-me o ouro e eu deixo a rapariga ir.",
"Tudo bem, acho que vou aceitar o dinheiro, mas ",
"Sabine Matton",
" vai ficar comigo também.",
"Ha! Tudo o que tenho que fazer é pegar o seu dinheiro e manter a garota comigo!",
"Aqui está o seu ouro, e espero que você se engasgue com ele!",
"Meu Deus, que rude! Mesmo assim, mantenho minha palavra de que aqui é sua afilhada. Adeus.",
"Você não é o primeiro a me desejar esse destino. Então dá-me o teu dinheiro, aqui está a tua miúda.",
"Não, você não pode fazer isso conosco! Por favor não ",
", tenha pena de nós!",
"Não se preocupe tanto, ou você pode estragar sua digestão... Dê-me seu dinheiro e diga adeus.",
"Por que não? Você não pode me impedir. E se você decidir chamar o guarda, então será muito difícil para sua afilhada.",
"Pegue seu dinheiro e vá embora. Você não é um capitão honrado, você é um monstro!",
"Adeus, senhora.",
"Oh, por favor, pare de gritar",
"Ah, você é tão gentil ",
"! Vejo que você tem um coração bondoso, embora faça o papel do pirata cruel.",
"Você está completamente errada, querida. Estou desesperadamente cansado da sua afilhada e dos seus sonhos sentimentais. Quanto tempo alguém aguenta navegar preso com uma garota assim?",
"Você não entende nada, velha. Sua filha simplesmente me cansou com todos os seus devaneios, agora o leve prazer que eu poderia obter de sua companhia não se compara ao aborrecimento sem fim que ela me causa.",
"Receio que você esteja enganada, senhora. Sou oportunista...",
"Não pense melhor nas pessoas do que elas merecem. Uso qualquer situação a meu favor",
"Vejo agora que fui muito gentil com você. Você é um verdadeiro ladino de coração negro!",
"Estou satisfeito por você finalmente me estimar pelo meu verdadeiro valor, mas eu realmente tenho outros compromissos, então terei que interromper esta conversa.",
"Estou bem acostumado com essas palavras... mas se você não quer que nada aconteça com você ou sua garota, sugiro que guarde-as para você!",
"Não me importo com o que você pensa. Não sou uma jovem impressionável e posso ver a verdade.",
"Como desejar, senhora, mas agora deixe-me despedir-me de você.",
"Bem, estou feliz que você pense que pode ver a verdade, velha, mas de qualquer forma eu realmente preciso ir.",
"Por que? O que você vai fazer com ela?",
"Não se preocupe. Vou manter sua afilhada bem e segura.",
"Calma, agora. Sou eu quem decide o que fazer com a garota, e acredite em mim, vou encontrar uma utilidade para ela.",
"Bem, ",
", provavelmente ",
"Sabine Matton",
" não sabia sobre as verdadeiras intenções de seu pai. Ela pode até estar melhor com você. ",
"Obrigado pela admissão relutante... e agora devo me despedir de você.",
"Na verdade, eu deveria trazer sua afilhada para você... então se você tem um lugar para ela, aqui está ela, e deixe-me me despedir de você.",
"Desejo-lhe um bom vento, ",
"!",
"Até a próxima.",
"O que?! Como você se atreve a dizer essas coisas! Você é um vilão de coração negro ",
"!",
"Não vou ouvir seus insultos. Voltarei ao meu navio e manterei a garota a bordo. Se você tentar me impedir ou me atrapalhar, juro por Deus que vou cortar sua garganta!",
"Não, minha garota não, por favor, deixe-a ir!",
"Sem chance, velha.",
"Sim. E estou muito grato a você pelo que fez por nós.",
"Deixa para lá. Por falar nisso ",
"Arnaud Matton",
" me pediu para lhe entregar esta carta.",
"Obrigado, deixo uma recompensa justa ao seu julgamento. Se você tiver um pouco de ouro sobrando, eu não diria não e, a propósito, tenho uma carta para você.",
"Agradeço novamente. Espere um segundo! Escrevi algumas linhas para ",
"Arnaud Matton",
", e se não for muito incômodo, por favor, entregue esta carta na próxima vez que o encontrar.",
"Adeus. Espero que tudo corra bem com você.",
"Até a próxima.",
"Certamente, certamente! Aqui está tudo que posso dispensar. Há 800 ouros lá e só espero que seja suficiente para cobrir suas despesas.",
"Oh. Sim. Sim, de fato. ",
"Por que você está na minha casa? Não tenho mais nada a dizer para você.",

};
