string DLG_TEXT[113] = {
", Como posso ajudá-lo?",
"Estou feliz em ver você aqui ",
". Você precisa dos meus serviços?",
"Olá, ",
". Não creio que tenha tido a honra de uma apresentação...",
"Meu nome é ",
".",
"Capitão ",
" está ao seu serviço.",
"Eu sou ",
".",
"Fico feliz em vê-lo, capitão ",
". Se você precisar dos meus serviços, estou pronto para prestá-los agora mesmo.",
". Você está a negócios aqui?",
"Olá, ",
"Olhe ao redor, o que você quer ver?",
"Mudei de idéia, não quero comprar roupas agora.",
" ouro : ",
"Olhe para mim! Eu mesmo coloquei para dar uma ideia de como ficará. Você quer comprar isso?",
"Não, eu não gosto disso. Mostre-me outra coisa.",
"Oh, eu não posso pagar por isso. Você se importaria de me mostrar algo diferente?",
"Na verdade eu gosto disso. Dê-me isso agora mesmo.",
"Mudei de ideia, não quero comprar roupas agora!",
"Posso me apresentar, meu nome é ",
". A seu serviço, ",
"Ouvi dizer que você é o melhor alfaiate da cidade. O que você tem para oferecer?",
"Isto é uma alfaiataria? Sinto muito, estou procurando algo completamente diferente. Adeus.",
", É bom ver você novamente. Você precisa do meu serviço hoje?",
"Sim, ",
", você tem algo especial para oferecer?",
"Desculpe ",
", estou em busca de algo completamente diferente. Apenas portas confusas, adeus.",
". Bem vindo de volta. Deixe-me ver se consigo encontrar mais alguma coisa em meu estoque.",
"Isso é ótimo, ",
". Talvez eu encontre algo do meu agrado neste lote.",
"Preciso ir em outro lugar ",
". Por favor, dê-me licença.",
"Não me mostre o estoque médio, sei que você pode oferecer mais! E faça isso rápido!",
"Mhmmm, vamos ver... para quem você quer comprar uma roupa nova?",
"Para mim pessoalmente...",
"Para meu oficial Sr. ",
"Isso será ",
" ouro. Você gostaria disso agora, ou devo empacotá-lo?",
"Agora mesmo.",
"Empacote.",
"Mudei de ideia, não quero comprar roupas agora.",
"Próximo",
"Anterior",
"Mude a direção",
"Atribuir este modelo!",
"Suficiente! Pare com isso!",
"eu ia	: ",
" não atribuÃ­do",
"Reiniciar",
"A direção mudou!",
"Continuar!",
"Você entendeu, o que faremos agora?",
"Continue modificando!",
"Pare de modificar!",
".",
"Me dê a famosa coleção de roupas piratas! (10.000 ouro)",
"Sim #ssir#, uma excelente escolha, se assim posso dizer.",
"É, e você pode.",
"DLG_TEXT[63]",  // El Rapido: always subtract 2 from the actual line in the dialog.h file to get the DLG_TEXT[NUMBER] and don't forget the , after the last "
"Pelo poder de El Rapido! Redefina as habilidades e habilidades do personagem principal e/ou dos 3 oficiais designados.",
"Você realmente deseja redefinir as habilidades e habilidades do personagem principal e/ou dos 3 oficiais designados?",
"Não, eu não quero isso.",
"Sim! Redefina apenas as habilidades e habilidades dos 3 OFICIAIS atribuídos - e faça isso rapidamente!",
"Por favor, redefina apenas as habilidades e habilidades do PERSONAGEM PRINCIPAL.",
"Yarr, amigo! Redefina as habilidades e habilidades do PERSONAGEM PRINCIPAL E dos 3 OFICIAIS atribuídos agora.",
"Pelo poder de El Rapido! Redefinir as vantagens do personagem principal e/ou dos 3 oficiais designados.",
"Você realmente deseja redefinir as VANTAGENS do personagem principal e/ou dos 3 oficiais designados?",
"Não, eu não quero isso.",
"Sim! Redefina apenas as 3 vantagens atribuídas aos OFICIAIS - e faça isso rapidamente!",
"Por favor, redefina apenas as VANTAGENS do PERSONAGEM PRINCIPAL.",
"Yarr, amigo! Redefina os PERSONAGENS PRINCIPAIS E os 3 BENEFÍCIOS atribuídos aos OFICIAIS agora.",
"Pelo poder de El Rapido! Preciso CONTRATAR UM OFICIAL agora mesmo.",
"Qual TIPO DE OFICIAL você gostaria de contratar, Capitão?",
"Um primeiro imediato.",
"Um contramestre.",
"Um artilheiro.",
"Um navegador.",
"Um Intendente.",
"Um carpinteiro.",
"Um cirurgião.",
"Um Mestre de Armas.",
"Eu mudei de ideia. Não quero contratar um oficial agora.",
// -- Scheffnow -- 2004-01-25 -- AppereanceMod -- end -----------------
"Meu tio rico comprou ",
"meu",
"Meu irmão",
" uma comissão como Kapitein. Você pode fazer os ajustes necessários neste uniforme?",
"Certamente, ",
". Se você me der os documentos de comissionamento, começarei imediatamente.",
"Documentos de comissionamento?",
"Sim. Não duvido da sua palavra, é claro. Mas é política padrão exigir que os documentos de comissionamento evitem que qualquer soldado aleatório tente obter um uniforme que não tem direito a usar.",
"Claro. Aqui estão eles. <brinque de olhar no bolso> Ah. Espero que ainda estejam no quartel, caso contrário um batedor de carteiras se serviu deles e terei que substituir os papéis. Voltarei quando os tiver.",
"Aqui estão os papéis.",
"Obrigado. Sim, estes são documentos válidos para um Kapitein que acaba de ser comissionado na 3rd Foot Company. Tenho as insígnias necessárias em estoque. Volte amanhã e terei o uniforme pronto para você.",
"Obrigado.",
"Estou aqui para perguntar sobre o uniforme que encomendei.",
"Sim, estive esperando por você. O uniforme agora está pronto. Isso custará 4.000 ouro, por favor.",
"Aqui está o dinheiro.",
"Não tenho tanto dinheiro comigo. Voltarei quando tiver.",
"E aqui está o uniforme. Estou ansioso para ver ",
"você",
"seu irmão",
" usando-o no serviço.",
"Obrigado. Na verdade, não demorará muito para que você veja ",
"meu",
"Meu irmão",
" fazendo bom uso do uniforme.",
"Certamente posso ajustar seu uniforme. Mas não enquanto você estiver usando!",
"Bom ponto. Vou vestir outra coisa primeiro.",
};