string DLG_TEXT[22] = {
"Procuro um tipo específico de oficial.",
"O que exatamente você está procurando?",
"Preciso de um contramestre para me ajudar a cuidar da minha tripulação.",
"Um canhoneiro seria bem-vindo. A minha tripulação continua a errar os alvos.",
"Diz-se que os contramestres ajudam a lidar com os comerciantes.",
"Você conhece aquelas rochas incômodas no mar? Eu realmente poderia usar um navegador para me ajudar a evitá-los.",
"Meu navio é tão grande que tenho dificuldade em gerenciar tudo ao mesmo tempo. Preciso de um imediato para me ajudar.",
"Buracos na meu navio. Sempre buracos no meu navio! Ah, como eu gostaria de ter um bom carpinteiro para consertá-los quando eu entrar em outra batalha naval.",
"As baixas após uma batalha são sempre um desperdício. Preciso de um médico para me ajudar a manter meus companheiros vivos.",
"Não é realmente um oficial em si; Eu só preciso de alguns músculos!",
"Não importa, vou ver o que posso encontrar sozinho.",
"A menos que eu esteja muito enganado, acho que alguém acabou de entrar.",
"Que golpe de sorte! E que coincidência também. Bem, você não vai me ouvir reclamar se der certo...",
"Quais são as últimas fofocas da cidade? Alguma notícia das outras colônias?",
"Quais são as últimas novidades?",
"Alguma novidade?",
"Eu só precisaria disso por algumas horas, tudo bem?",
"Não somos um bordel! Se você só precisa esperar, você pode fazer isso aqui. Basta sentar e desfrutar de uma bebida!",
"Ok, será uma caneca de rum e 1 hora de diversão.",
"Ok, será uma caneca de rum e 3 horas de diversão.",
"Ok, será uma caneca de rum e 8 horas de diversão.",
"Não importa, vou passar meu tempo em outro lugar",
};
