string DLG_TEXT[153] = {
"Fora com você! Não estou com vontade de falar com estranhos",
"Você não quer me comprar um pouco de rum?",
"No seu caminho. Estou ocupado.",
"...",
"O que?",
"Estou procurando um homem chamado ",
"Raoul Rheims",
"Raoul Rheims",
". Ele é um capitão. Você o viu?",
"Sim! Sim! Eu o vi com meus próprios olhos! Mas seria melhor perguntar àquela estalajadeira. Ela o conhece muito melhor do que eu. Se você entende o que quero dizer, senhor.",
"Entendo. Obrigado.",
"Fora com você! Não estou com vontade de falar com estranhos.",
"Ah, amigo, me compre um pouco de rum?",
"Estou ocupado amigo, vá embora.",
"De todos os ",
" pessoas nesta ilha, tive que encontrar vocês...",
"...",
"Espere aí, amigo. Só preciso de algumas informações sobre sua bela colônia aqui. Pode haver um pouco de rum para você, se você quiser ajudar.",
"O que?",
"Estou procurando um homem chamado ",
". Ele é um capitão. Você o viu?",
"Sim, #smistah#! Vi-o comigo com os meus próprios olhos! Mas você precisa perguntar à velha Ines, a estalajadeira - ela a conhece muito bem. Se você me entende, amigo.",
"Entendo. Obrigado.",
"*suspiro* Pergunte - mas seja rápido, amigo.",
"Apresse-se - eu trouxe um bom grogue, jóias brilhantes e algumas donzelas cheirosas esperando por mim na minha cabine.",
"É melhor ir rápido, amigo, antes que o bom ânimo do rum passe.",
"Ouvi dizer que havia um navio negro atracado aqui por um tempo. O Mefisto.",
"Por menor que seja a sua aldeia, ainda preciso de algumas orientações.",
"Só preciso me orientar, só isso.",
"Você poderia fazer a gentileza de me dizer onde encontrar...",
"O que você pode me dizer sobre esta sua colônia ilustre e totalmente legítima?",
"Um dos seus adoráveis cidadãos me interessa...",
"Vim aqui para saber de alguém na cidade.",
"Seja querido e me conte sobre alguém? Pode ser um companheiro seu.",
"Ugh, quase posso ver uma coroa de linhas de fedor para combinar com aquele seu cheiro de pústula. Deixa para lá.",
"Quem você tem em mente, hein #smistah#? *arranhar*",
"Eh? *peidar*",
"Ora, todos os meus amigos, eles são - cada um desses canalhas, ha! *arrotar*",
"Quem governa vocês, muitos indisciplinados?",
"Seu distribuidor de cerveja, barman, como você quiser chamá-lo.",
"Aquele cavalheiro que pretende consertar navios de alto mar - ah, me desculpe, minhas palavras são grandes demais para você?",
"Aquele que vende as velas e, uh, outras coisas.",
"Aquele funileiro esquisito e de olhos arregalados fora da cidade.",
"A senhorita que governa o bordel...",
"Deixa para lá; ninguém vale a pena conhecer nesta rocha. Mas eu gostaria de saber outra coisa.",
"Arne? Evvan é um pirata, esse gato é torto. E ele estava sempre fazendo um barulho sujo, quando ele tinha sua forja aqui atrás das estacas - então nós meio que... uh... MUDOU a bunda dele para FORA.",
"Muito bem. Outra coisa...",
"Obrigado, isso é tudo.",
"Isenbrandt? Um sujeito severo, esse. Mas ele tem tudo para manter as coisas em ordem aqui. Escolhido por unanimidade para nos levar cães.",
"Terei que fazer-lhe uma visita. Mas sobre outro assunto...",
"Obrigado. Contanto.",
"Nosso barman é um pássaro forte e agressivo com uma língua afiada, amigo. Boa e velha Inês. Ela cuida muito bem de nós, garotos desordeiros. Sabe dispensar o que nos agrada, tipo.",
"Desculpe mantê-lo, mas há outra coisa...",
"Não 'ele', 'ela'. O velho Peter Blowhorn aposentou-se há anos. Sua filha Kate administra a loja agora. Não te trai como o velho Pete fez - bem, ela não quer que você leve seus negócios para #sCharlestown#, não é?",
"Entendo. Eu tenho outra pergunta para você.",
"Bom de se ouvir. Feliz.",
"Heh, entendo aonde você está indo com isso, amigo - seguindo seu arco-íris até um porto amigável, tipo, hein? Uma pequena cutucada, piscadela, piscadela, hein #smistah#? heh... De qualquer forma, Celestine - pois esse é o nome da 'espetável amante' - mantém um ótimo estábulo de lindas potras, ela tem. Purdy e atrevido.",
"Certo. Você vai suportar mais uma pergunta?",
"Certo, e agora?",
"Conheço esta ilha melhor do que ninguém, por isso é melhor perguntar-me.",
"Conhece bem esse lugar, Ah conhece. Mas você está prestes a me conhecer, mesmo que continue batendo demais... marujo.",
"Ei, eu venderia meu navio, minha querida mãe E minha alma se ao menos pudesse pegar uma bebida...",
"Um belo conjunto de vazamentos me trouxe aqui - quem pode me arranjar um navio para preencher as lacunas?",
"Tem um comerciante aqui que NãO É um trapaceiro?",
"Alguém nesta rocha miserável pode consertar minha maldita espada?",
"Um sujeito tem necessidades... se é que você me entende. Onde eles podem ser encontrados?",
"Arne - ele está lá, mas do lado de fora, de frente para os portões - ele é um buggah nervoso e saltitante, e ele cobra muito arranhão, E ele demora muito ... Ah, inferno, #smistah#, melhor, não ambos são altos.",
"Vou arriscar, obrigado.",
"E a sua pobre desculpa para um estaleiro?",
"Quem vai comprar a porcaria velha do meu domínio?",
"Ines tem uma caneca esperando por você do lado mais próximo da grande rocha que fica no meio da cidade.",
"Muito obrigado, meu amigo rude e fedorento.",
"E onde posso consertar meu navio?",
"Supondo que eu queira negociar algum comércio totalmente legal?",
"Minha lâmina está quase enferrujando e desaparecendo... alguém nesta cidade pode consertá-la?",
"Passando pelos portões, o casebre do consertador de navios está na plataforma - não, à esquerda. Porto, né? Eu sempre confundo a dose dois. Não adianta usar termos doseados e desajeitados, certo?",
"Mas o mais importante: onde fica sua cervejaria?",
"Preciso encontrar alguém que me dê um preço justo pelos meus produtos.",
"Você foi muito útil; isso é tudo.",
"Quem serve como ferreiro para vocês?",
"Um dos barracos do meio do porto, de frente para as pedras bonitas no meio da cidade. Isso é ... uh, à esquerda, enquanto você entra na cidade.",
"Onde fica o seu estaleiro?",
"Que tal a taberna?",
"Isso é tudo que posso suportar da sua companhia, obrigado.",
"E se eu lhe dissesse que minha espada não é afiada o suficiente para abrir um melão maduro?",
"Não tenho certeza se estou te seguindo, #smistah#...",
"Você sabe - certas necessidades, que um #sgender# possui de vez em quando... Um #sgender# há muito tempo no mar, apenas com a companhia de #spronoun3# companheiros, que, por mais bonitos que sejam, não vão um longo caminho para extinguir certos fogos que ardem nos #spronoun3# lombos?",
"O que é isso? Queimando lombos? Você precisa visitar o doktah den, amigo... Não há ninguém aqui, com certeza, doh.",
"Deixe-me explicar para você, COMPANHEIRO: Onde vocês guardam suas malditas putas?!",
"Meu cavalo? Tenho um cavalo, #smistah#. Não vejo o que isso tem a ver com lombos queimados, hein?",
"*suspiro* Esqueça... parece que está de volta ao #sonanism# para este marinheiro solitário.",
"A propósito, capitão, jes' entre nós dois: 'Não há pomada ou mangueiras aqui, mas você pode gostar de dar uma passada no bordel, do outro lado da pedra, bem ao lado da casa do nosso governador. Eles organizam um ótimo jogo de dados aqui. E diga à pequena Lucie um olá para mim, se você quiser... *corar... arrotar*",
"*suspirar*",
"Sim, #smistah#? Somos malandros aqui, mas somos mais amigáveis - até certo ponto. (Uma ponta afiada e de aço, sabe.) Seja rápido.",
"Certo, qualquer coisa que você queira saber - exceto onde Ah me mantém escondido, ho ho!",
"Realmente isso está interessado, hein? O Mos visita aqui, o Jes meio que sai correndo, se você sabe...",
"Eu gostaria de saber a história da famosa ilha pirata - muito célebre, com certeza.",
"O que há nesta rocha desolada além da sua aldeia?",
"Não, pelo contrário, outro tópico servirá, certo?",
"Sim, ela é célebre: uma bela 1história de sangue e coragem1. Mas nós, marinheiros liberais - nos autodenominamos 'Caribenhos Bucaneiros', se quiserem - cuide bem de nossa própria espécie, e enquanto você estiver voando com a caveira e os ossos, você é um companheiro nosso.",
"Fascinante... faça o favor e me conte mais.",
"Perfeitamente intrigante. Mas tenho outras coisas em mente agora",
"#sisland_Quebradas Costillas# sejam mantidas primeiro pelos espanhóis, depois por muitos esquisitos. Nós roubamos essa pedra dos franceses na última vez, já faz uns vinte anos, e desde então ninguém foi homem o suficiente para tentar recuperá-la. Jurcksen vê isso, ele vê! Todos os governos estão tremendo com suas botas, ha ha!",
"Realmente uma história e tanto. Eu gostaria de saber mais sobre o estado atual das coisas agora.",
"Não, não há mais nada para ser encontrado aqui... Meus pequenos bandidos e canalhas. E seja cuidadoso com quem você pergunta sobre o quê, se você me entende, #smistah#.",
"Hmhm... devidamente anotado. Mais alguma coisa que você sabe sobre sua ilha?",
"Bem... do outro lado da ilha, através de alguns trechos da selva, você pode tropeçar em uma boa surpresa. Mas eu mantenho-me calado sobre isso, veja bem.",
"Que adorável. Eu gostaria de saber mais, se você me tolerar.",
"Você não ouviu isso de mim, amigo, mas... Uma bela mansão, lá está, ele está em um lugar na selva ali. Está quase vazia há muitos anos, mesmo cheia de ganhos como ela está, mas todos nós temos medo de tocá-la, diminuir o que é legítimo, voltar - um homem muito medroso, todos nós sabemos .",
"Oh sim?",
"Você foi inesperadamente, mas deliciosamente útil. Você poderia me responder outra, marujo?",
"** estremecer ** Doze demônios vestidos de vermelho mataram meu mano sem dizer uma palavra.",
"Foi seu irmão que eles mataram?",
"Sim. Meu mano se envolveu com eles depois que ele fez alguns favores para o padre em #sRedmond#.",
"Entendo. Há mais alguma coisa que você possa me contar sobre eles?",
"Por que ocê tá perguntando deles, #smistah#? Eles num traz nada além de problema.",
"Há algumas crianças desaparecidas e todas as evidências parecem apontar para elas.",
"Doze demônios são muito ruins, camarada. Você realmente vai atrás deles?",
"Há dinheiro nisso.",
"Eles mataram meu mano, #smistah# capitão. Odeio mais do que qualquer coisa, mas não iria atrás deles por todo o ouro do Caribe. Mas se você estiver disposto a morrer por ouro, camarada, então vá falar com #sFatherBernard# na cidade de #sRedmond#. Ele não é um bom homem, mas pode saber onde estão os demônios.",
"Obrigado.",
"Sim, Jakob Nickerson. Acabei de me mudar para a cidade há pouco tempo. Ele faz um bom trabalho consertando barcos, além de ter uma pontuação para vender.",
"Bom. Algo mais?",
"Procuro uma jovem...",
"Quem não é?",
"Esta é uma garota que os piratas sequestraram.",
"Que piratas?",
"Ah, vamos lá, você parece um jovem muito observador e inteligente. Talvez você tenha notado uma garota alta sendo levada como refém para esta cidade?",
"Tudo bem, eu os vi trazendo uma nova garota, uma morena, para o assentamento.",
"O que aconteceu com ela, onde posso encontrá-la?",
"Acho que eles a venderam.",
"Como um escravo? A quem?",
"Use sua imaginação viajante...",
"Ok marujo, não posso passar o dia todo conversando com você. (Más notícias - acho que seria o Bordel!!)",
"Eu não sei de nada.",
"Talvez haja algum ouro se você tiver informações úteis.",
"De quanto ouro estamos falando?",
"Bem, digamos 40, e isso só se você souber de algo de valor para mim.",
"Você parece muito ansioso, capitão, por que não chegar aos 60?",
"Pirata ganancioso? Eu te dou 50 mesmo que seja demais.",
"São 30 ou nada, seu ladrãozinho patético!",
"Pegue seu ouro então e comece a falar ou eu...",
"Se você sabe de alguma coisa - cuspa ou vou te machucar muito!",
"Tenho que repetir capitão, não sei do que você está falando!",
"Não tenho medo de você, jovem!",
"Saia da minha vista agora.",
"Entregue-os, capitão.",
"polindo a joia",
"limpando o convés de proa",
"batendo na bigorna de Vênus",
"espancando a prancha",
"tocando violino",
"sacudindo o velho bacalhau",
};
