string DLG_TEXT[34] = {
"Vá embora.",
"Estou indo embora.",
"A menos que você esteja aqui para doar mais do seu dinheiro, é melhor você ir embora. Ha ha ha ha!",
"Vou lembrá-lo para você.",
"Nos encontramos novamente, capitão.",
"Ah, pensei ter sentido um cheiro desagradável.",
"Venha, junte-se a mim.",
"Agora não. Talvez outra hora.",
"Com prazer. Você vai me pagar uma bebida?",
"! Você pagou minha dívida! Obrigado!",
"De nada. Aqui, pegue seu recibo.",
"Você ainda não me pagou, não é?",
"Não, espere mais um pouco.",
"*Suspiro!* Como você se atreve a falar assim comigo!",
"Quem é você para me ensinar boas maneiras? Falo do jeito que eu quiser, não gostou saque sua espada e farei cócegas no seu fígado.",
"Você tem sorte de haver guardas por perto, caso contrário eu estaria com minha lâmina na sua garganta...",
"Você estaria morto antes que sua arma saísse da bainha.",
"Capitão, se eu pudesse ser tão ousado... você poderia me pagar uma bebida? Já acumulei uma conta considerável, receio...",
"Quanto você deve?",
"Oh, sinto muito, mas eu realmente preciso ir...",
"500 ouro.",
"Isso é uma grande dívida. Boa sorte para pagar.",
"Apenas 500? Isso não é tão ruim. Talvez eu possa pagar por você.",
"Oh! Obrigado! Muito obrigado!",
"Não, espere. Eu não tenho dinheiro agora.",
"Isso é tudo? Sem problemas. Eu vou pagar por você agora",
"Oh, capitão, obrigado mais uma vez!",
"Estarei de volta em pouco tempo.",
"Ha! Que tolo! Guardião da taverna! Traga-me um pouco de vinho!",
"Espere... você disse que não tem dinheiro.",
"Acho que sim, não foi? Talvez você devesse ter mais cuidado com quem você confia, hein? Agora sai daqui.",
"Você... seu ladrão! Devolva meu dinheiro!",
"Ah, mas você foi enganado de forma justa, meu amigo! Agora saia da minha vista... a menos que você prefira que eu te espete até a morte?",
"Hoje nao!",

};
