string DLG_TEXT[38] = {
"Obrigado novamente pelo que você fez, ",
".",
"Não mencione isso.",
"Ah, me deixe em paz! Se você está procurando companhia, fale com outra pessoa!",
"Como quiser.",
"Qual é o seu problema? Eu não fiz nada para você!",
"O que você quer?!",
"Nada.",
"Vamos falar sobre sua filha.",
"Ah, obrigado! Obrigado! Finalmente vi minha filha! Me desculpe, não tenho nada com que recompensá-lo... Espere, você pode pegar essa espada!",
"É bastante incomum. Onde você conseguiu essa coisa?",
"Quando eu era mais jovem, tinha desejo por tesouros e fui a muitas ilhas. Embora muitos não tivessem nada de valor, consegui encontrar um pequeno refúgio deserto. Dizem que foi a casa de um famoso capitão do mar. A espada estava lá.",
"Eu vejo. Bem, obrigado pelo presente.",
"Realmente?! Vocês são chacais, festejando com os ossos dos outros!",
"Acalme-se! Você realmente deveria sentar-se sozinho por um tempo.",
"O que você quer dizer com isso?",
"Você! Todos vocês! Piratas, corsários, contrabandistas! Vocês são todos demônios, todos vocês!",
"O que aconteceu que te transformou assim?",
"Talvez seja um erro lhe contar tudo isso, mas você parece uma pessoa melhor do que o resto daqueles bastardos...",
"Estou lisonjeado, mas por favor, continue.",
"Não é da sua conta! Olhe para você! Indigno de confiança e vil. Você navega pelos mesmos mares que aqueles répteis!",
"Faça como quiser. Se você não quer me contar - não conte",
"Minha filha, ",
"Tanneken Oremans",
", uma garota gentil e confiante...",
"Deixe-me adivinhar: isso tem algo a ver com piratas?",
"Sim! Um dos piores ",
"Bernardo Gamboa",
". Ele seduziu minha filha! \nEu disse a ela que me opunha ao namoro deles, mas ela não quis me ouvir e há 3 dias ela desapareceu! \nTenho certeza que esse espanhol a sequestrou!",
"Por que você não pede ajuda aos guardas?",
"Recorrer aos guardas? Oh, querido #schild#, você está enganado. A cobra que levou minha filha conta com o Governador entre seus amigos!",
"Entendo. Bem, espero que haja um final feliz para sua história.",
"Talvez eu possa ajudar. Onde posso encontrar esse pirata?",
"Seu navio está no porto. Você não terá problemas em encontrá-lo.",
"Verei o que posso fazer.",
"Vá embora, eu já te contei tudo! Não me atormente com suas perguntas!",
"Muito bem, vá em frente, beba seu rum e espere que sua filha volte para você.",
"Fácil fácil. Diga-me onde posso encontrar o homem que sequestrou sua filha.",

};
