string DLG_TEXT[180] = {
". O que é, ",
"?",
"Posso te ajudar, ",
"?",
"Esta é sua primeira vez em nossa cidade, ",
"? Eu não te vi antes",
"Eu sou ",
", capitão e proprietário do navio'",
".' Eu tenho algumas perguntas se você tiver um momento.",
"Meu nome é ",
". Gostaria de lhe fazer algumas perguntas.",
"Você pode me chamar de capitão ",
". Eu só gostaria de algumas informações.",
"Olá, capitão ",
". O que traz você à nossa colônia?",
"Ah, capitão ",
". ",
", é você de novo. Espero que sua jornada tenha sido agradável. O que há de novo?",
"Olá, ",
". Como posso ajudá-lo?",
"Perdi alguma coisa enquanto estive fora?",
"Aconteceu alguma coisa interessante enquanto eu estive fora?",
"Que histórias os velhos cães-do-mar estão trocando por causa do rum hoje em dia?",
"Qual é a agitação nas tabernas?",
"Procuro fofocas, boatos, histórias fantásticas...qualquer coisa que eu não saiba pode ser útil.",
"Me conte algumas de suas fofocas mais recentes, amigo. Pode haver aventura ou dinheiro até mesmo no menor detalhe.",
"Ainda não consigo encontrar...",
"É impossível encontrar alguma coisa neste labirinto! Onde é...",
"Estou tão perdido quanto um navegador bêbado. De novo!",
"Você parece um morador local. Diga-me onde posso encontrar...",
"Por favor me diga como chegar a...",
"Tive um dia péssimo, então você nos salvará da dor se apenas me disser como encontrar...",
"Gostaria da sua opinião sobre um cidadão local.",
"Preciso saber o que você pode me contar sobre alguém que mora aqui na cidade.",
"O que você pode me contar sobre...",
"Conte-me tudo o que puder sobre um sujeito...",
"Espero que você possa me contar algo sobre uma pessoa que talvez conheça.",
"Este lugar não é muito grande – aposto que você conhece todo mundo que mora aqui. Vamos conversar.",
"Conte-me sobre #sTortuga#.",
"O que você pode me dizer sobre esse lugar esquecido por Deus?",
"Gostaria de saber mais sobre esta bela colônia.",
"Qual é a história desta cidade e da ilha?",
"Você sabe alguma coisa interessante sobre #sTortuga#?",
"...",
"Desculpe. Pensei que você fosse outra pessoa.",
"Estou apenas de passagem. Então fique de lado ou seja empurrado.",
"O que você gostaria de saber, ",
"?",
"O que lhe interessa, capitão?",
"O que você quer de mim?",
"Cidades como esta estão sempre nadando em fofocas. Dê-me os destaques.",
"Aconteceu alguma coisa interessante por aqui ultimamente?",
"Só quero saber o que está acontecendo na vizinhança. Alguém enganou um amigo? Alguém foi morto? O estalajadeiro é mesmo uma mulher? Você me entende.",
"Como posso chegar a...",
"Você pode me ajudar a me orientar aqui na cidade?",
"Onde posso encontrar...",
"Você pode me falar sobre alguém em quem estou interessado?",
"Gostaria de algumas informações sobre um colega local. Você pode ajudar?",
"Estou me perguntando o que as pessoas na cidade têm a dizer sobre uma determinada pessoa...",
"O que você pode me dizer sobre #sTortuga#?",
"Gostaria de conhecer a história da sua cidade.",
"Gostaria de obter algumas informações sobre esta colônia.",
"Estou apenas andando aqui. Vejo você mais tarde.",
"Obrigado. Tem mais uma coisa...",
"Foi bom conversar com você. Contanto!",
"Qualquer outra coisa, capitão ",
"?",
"Vamos ouvir isso, ",
".",
"Estou ouvindo, ",
".",
"Qual é o assunto da cidade hoje em dia?",
"Que histórias os velhos cães-do-mar estão trocando por causa do rum hoje em dia?",
"Já faz muito tempo que não ponho os pés nestas praias. O que eu perdi?",
"Você poderia me dar algumas instruções?",
"Fiquei completamente perdido nestas ruas.",
"É minha primeira vez nesta cidade e gostaria de algumas orientações.",
"Gostaria da sua opinião sobre um cidadão local.",
"Preciso saber o que você pode me contar sobre alguém que mora aqui na cidade.",
"Você poderia me dar algumas informações sobre os habitantes locais?",
"Conte-me sobre #sTortuga#.",
"O que você pode me dizer sobre esta colônia?",
"Gostaria de saber algo sobre #sTortuga#.",
"Acabei de perceber que preciso estar em algum lugar. Adeus.",
"Quem é que queres dizer,",
"?",
"Você está perguntando sobre alguém específico?",
"Sobre quem exatamente você quer saber?",
"Quero dizer, o governador.",
"Estou interessado no dono da taberna.",
"O dono do estaleiro.",
"Estou falando do comerciante local.",
"Ninguém. Deixa para lá.",
"Nosso governador é francês, mas tem contato direto com os dois senhores piratas daqui.",
"Eu vejo. Eu tenho outra pergunta para você.",
"Obrigado tchau tchau.",
"Ele tem o melhor rum para ficar bêbado. Agora que você mencionou, acho que estou voltando para a taverna. Além disso, ele não é tão chato a ponto de interromper aquelas brigas engraçadas de taverna! ",
"Eu vejo. Eu tenho outra pergunta para você.",
"Obrigado tchau tchau.",
"Ele funciona bem, eu acho. Se ele estiver sóbrio...",
"Eu vejo. Eu tenho outra pergunta para você.",
"Obrigado tchau tchau.",
"Ele é muito ganancioso. Alguns dizem que ele era assistente de Baldewin Coffier, mas quando a loja faliu, ele a comprou por um preço baixo. Não sei a qualidade ou o preço de seus produtos, mas ele não parece ser uma pessoa muito... boa.",
"Eu vejo. Eu tenho outra pergunta para você.",
"Obrigado tchau tchau.",
"Onde você está indo, ",
"?",
"Não é um problema, capitão. Onde você precisa estar?",
"Fico feliz em orientá-lo, ",
". Mas para onde você quer ir?",
"Como posso chegar à taberna?",
"Onde fica o estaleiro?",
"Onde posso vender os produtos que trouxe comigo?",
"Ao entrar na cidade, mantenha-se à esquerda e siga o cais.",
"Certo. Obrigado pelo seu tempo.",
"Onde fica o estaleiro?",
"Onde posso conseguir um preço decente pelos produtos finos que trouxe para a cidade?",
"Após o pouso você vai para a direita. O estaleiro fica um pouco antes do caminho para a cidade alta.",
"Eu vejo. E a taberna?",
"Onde posso conseguir um preço decente pelos produtos finos que trouxe para a cidade?",
"Eu acho que isso é tudo. Obrigado pela ajuda.",
"Vá para a cidade alta. Na praça da forca fica a nossa loja.",
"Onde posso encontrar o estaleiro local?",
"Como faço para chegar à taberna?",
"Eu vejo. Obrigado pela informação.",
"Não sei por que você estaria interessado, mas por que não?",
"No que exatamente você está interessado ",
"?",
"Claro, ",
". Felizmente, é uma história bastante curta.",
"Estou interessado na história da colônia...",
"Conte-me sobre a colônia.",
"Existe alguma coisa na ilha além da cidade?",
"Tenho mais algumas perguntas para você, se não se importa.",
"Cara, estou bêbado demais e acho que nem consigo lembrar do meu nome e você está me perguntando sobre a história desse maldito ninho?",
"Obrigado. Deixe-me fazer mais algumas perguntas.",
"Sabe, eu realmente pensei que seria mais interessante. Deixe-me perguntar outra coisa.",
"Isso é tudo que preciso. Obrigado.",
"Obrigado pelo seu tempo. Até a próxima.",
"Bem, #sTortuga# fica em uma pequena ilha que pertence a Hispaniola. Temos apenas algumas plantações aqui.",
"O que mais você pode me contar sobre a colônia?",
"O que mais você pode me dizer?",
"Você acabou de ouvir? Eu estou bêbado.",
"Eu vejo. O que mais?",
"Não. Você encontrará algumas plantações, mas elas são praticamente subdesenvolvidas.",
"Nesse caso, talvez você possa me contar mais sobre a colônia.",
"Entendi. Deixe-me perguntar outra coisa.",
"Você conhece um contramestre chamado Fred Bob?",
"O que você pode me dizer sobre o capitão do porto?",
"Ah, Fred Bob? Ele não é um amotinado, isso eu lhe garanto! Ele é um bom marinheiro e um homem forte para ter ao seu lado quando você está em menor número. Pena pela sua prisão. Todos esperamos que o governador o liberte, porque ninguém, exceto aquele pomposo primeiro oficial, acredita que ele é culpado.",
"Interessante. Ah, eu tenho outra pergunta para você.",
"Muito obrigado, adeus.",
"Não sei como ele faz isso, mas o nosso capitão do porto faz questão de conhecer todos os marinheiros do arquipélago.",
"Eu vejo. Mais uma pergunta, se não se importa, por favor?",
"Obrigado pelo seu tempo. Tchau.",
"Fred Bob? O contramestre? Ele é muito difícil de entender, mas meu irmão o conhece bem. Ele não é um amotinado. Esse oficial entendeu tudo errado. Todos esperamos que o governador o liberte. Ele pertence a um navio, não a uma paliçada.",
"Bom homem, excelente marinheiro. Não acredito nem por um minuto que ele ameaçou um motim.",
"Ehm... eu esqueci quem eu ia perguntar. Apenas me dê um segundo e isso voltará para mim...",
"Como está aquele velho metalúrgico Tomas hoje em dia?",
"Você quer dizer Tomasina, não é comandante gobeur? O velho Tomas morreu há pouco tempo, e agora é sua esposa presidindo a bigorna. Também não posso dizer que ela faz um mau trabalho.",
"Nossa... ela não fica irritada com frequência nessa profissão? Deixa para lá; para coisas mais felizes.",
"Bem. Uma viúva elegível que pode consertar uma lâmina? Terei que prestar meus respeitos imediatamente...",
"Minha melhor espada favorita do mundo aqui ficou um pouco chata ultimamente. A quem posso confiar isso?",
"Receio que ninguém aqui possa ajudá-lo com isso.",
"Ah, isso é muito ruim. Terei que tentar a sorte em outro lugar",
"Onde fica o estaleiro?",
"Onde posso conseguir um preço decente pelos produtos finos que trouxe para a cidade?",
"A quem posso confiar minha espada? Sua borda antes fina ficou um pouco embotada.",
"Tem alfaiate em #sTortuga#?",
"Claro. Os alfaiates estão numa grande casa azul na cidade baixa. Perto do poço.",
"Ouvi falar de alguns cirurgiões que moram aqui em #sTortuga#. Isso é verdade?",
"Onde posso encontrar o armeiro?",
"Você pode me mostrar o caminho para o veleiro?",
"Claro. Um deles mora em uma pequena casa de madeira - em frente à prefeitura.",
"O armeiro está na casa de pedra atrás da taverna.",
"Procure a bandeira no cais. Ali está a entrada.",
"Como faço para chegar à torre? Está bloqueado por uma grade.",
"Ah, mas a entrada é pela prefeitura.",
"Deveria haver uma carruagem em algum lugar de Tortuga. Você sabe onde?",
"Sim, há um ao lado do cirurgião na cidade alta.",
};
