string DLG_TEXT[102] = {
", de ",
", se não me engano?",
"Não, você não está enganado... mas como você sabe disso?",
"Essa é minha profissão saber tudo sobre todos. A propósito, meu nome é ",
".",
"Estou feliz em conhecê-lo. Tenho algumas perguntas para você.",
", ",
".",
" Tenho algumas perguntas para você.",
"Acredito ter algumas informações que lhe interessarão. Conheço quem vende contrabando na sua cidade.",
"Eu sei quem vende contrabando na sua cidade.",
"Eu sei quem lida com contrabando aqui na sua cidade, Mocie.",
"Você checou aquela informação que eu te dei?",
"Sou capitão de um navio que irá escoltar a barca 'Oiseau' até #sOxbay#.",
"Sim, estou ouvindo.",
"Gostaria de obter algumas informações sobre a cidade.",
"Ouvi dizer que você tem alguns problemas com os contrabandistas.",
"Acredito ter algumas informações que lhe interessarão. Conheço quem vende contrabando na sua cidade.",
"Eu sei quem vende contrabando na sua cidade.",
"Sou capitão do navio que foi contratado para escoltar a barca 'Oiseau' até #sOxbay#.",
"O que? Todo mundo na cidade já está fofocando sobre isso? Eu gostaria de saber onde eles descobriram tudo isso.",
"Bem, por exemplo, soube disso pela boca dos homens do porto.",
"Bom, se todo mundo já sabe, não adianta negar. Sim, tenho alguns problemas com os contrabandistas. Por quê você se importa?",
"Bem, eu só estava curioso sobre isso. Vamos falar sobre outra coisa.",
"A verdade é que eu gostaria de ajudá-lo... mas é claro, não sem uma compensação.",
"Que tipo de ajuda você pode me oferecer?",
"Encontro esses contrabandistas para você, e recebo 5.000 moedas pelo serviço. Simples assim.",
"Bem, se você sabe onde encontrá-los, por que não chamo os guardas, e assim você me conta tudo que sabe... e sem cobrar nada por isso.",
"Possivelmente porque você não pode ter certeza de que eu realmente sei alguma coisa ainda, e tampouco pode ter certeza de que conseguirá o que deseja dessa forma.",
"Tente a sorte, meu amigo, e verei a cor do sangue que pulsa em seu coração.",
"Hum. Vamos supor que eu acredito em você... então como você vai encontrar os contrabandistas?",
"Bem, esse é o meu problema, não é?",
"Tudo bem. Se você encontrar os contrabandistas, você receberá 5.000 de ouro... mas tenha em mente que se você tentar me enganar...",
"Do que está falando? Não pretendo te enganar. Estou sendo franco com você.",
"Você tem alguma evidência?",
"Acontece que sim. Aqui, dê uma olhada nessas cartas.",
"Você tem alguma evidência?",
"Acontece que sim. Aqui, dê uma olhada nessas cartas.",
"Você está certo. Esses documentos lançam luz sobre essa transação obscura. O que você deseja pelos seus serviços?",
"Prestei-lhe o serviço de forma absolutamente gratuita e não quero nada de você, exceto sua gratidão.",
"Suponho que 500 moedas de ouro seriam uma compensação justa para mim.",
"Não, não deveria ser assim. Aqui estão 1.500 de ouro pela sua ajuda... junto com minha gratidão a você.",
"Não me atrevo a te atrasar mais.",
"Bom. Aqui está o seu dinheiro. E agora, se me perdoar, tenho trabalho a fazer.",
"Não me atrevo a te atrasar mais.",
"Você está certo. Esses documentos lançam luz sobre essa transação obscura. Aqui está o seu dinheiro. E agora, se me perdoar, tenho trabalho a fazer.",
"Não me atrevo a te atrasar mais.",
"Realmente? Quem é esse?",
"Isso é ",
"Raoul Calmes",
"Raoul Calmes",
".",
"Eu não posso acreditar nisso! ",
"Raoul Calmes",
" é um homem muito respeitado.",
"Bem, você mesmo pode ter certeza disso, senhor, e eu esperarei por você.",
"Sim, acho que é uma boa ideia ",
". Você será o único culpado se estiver errado.",
"Não tenho nada a temer.",
"Ótimo. Então peço que me espere na entrada da residência. Vou verificar suas informações e, se forem verdadeiras, você receberá seu dinheiro.",
"Bom, vou seguir seu conselho, senhor.",
"Sim, descobriu-se que você está certo. Aqui está sua recompensa. E agora sinto muito, estou com pressa, mas o senhor governador vai me dar uma audiência.",
"Estou sempre feliz em ajudá-lo.",
"O que você quer saber? Devo dizer-lhe desde já para não perder meu tempo com perguntas sobre direções...Não sou um pescador ocioso.",
"Hum. Então não vou te atrasar mais",
"Gostaria de saber sobre a história de ",
"Raquel Blacque",
"é família. Pelo que entendi, você os conhece muito bem.",
"Sim você está certo. Eu os conheço, mas essa é uma história muito triste.",
"Sim, eu ouvi aquele velho ",
"Milon Blacque",
", está perturbado pela dor.",
"Infelizmente, essa é a verdade. A morte de seu único filho o chocou muito.",
"O que aconteceu com ele?",
"Na verdade, isso é muito triste... mas eu realmente preciso ir.",
"Com o filho? Há cinco anos, ele navegou para #sRedmond# em seu navio e ninguém o viu desde então.",
"Sim, isso é trágico.. mas talvez ele ainda esteja vivo?",
"Eu não acho. Cinco anos já se passaram. Ele teria enviado uma mensagem se estivesse vivo.",
"Talvez você esteja certo. Ouvi dizer que o velho não está sozinho. A filha adotiva dele está cuidando dele, é verdade?",
"Raquel Blacque",
"? Ela é uma boa garota. Ela se sacrifica muito para cuidar do velho e, além disso, tem seus próprios problemas.",
"Obrigado. Você foi uma grande ajuda.",
"Essa é a minha profissão: saber tudo sobre quem chega ao meu porto. A propósito, meu nome é ",
".",
"Prazer em conhecê-lo. Tenho algumas perguntas para você.",
"Ah, sim, fui avisado sobre isso. Tem certeza de que seu navio está bem preparado para garantir a segurança na viagem? E você já conversou com ",
"Não, ainda tive o prazer de não conhecê-lo.",
"Sim, ele vai terminar o carregamento em breve.",
"Ele deveria estar aqui em algum lugar. Na verdade, assim que você chegar a um acordo com ele, você poderá zarpar.\nNão vou verificar nada. Tenho muitas outras coisas com que me preocupar.",
"Aí vem ele. Você pode ver ele? Ele está com um colete azul escuro. Na verdade, assim que você chegar a um acordo com ele, você poderá zarpar.\nNão vou verificar nada. Tenho muitos outros problemas com que me preocupar.",
"Obrigado, ",
".",
"Tudo bem, então me dê sua escritura e, assim que estiver pronto, você poderá zarpar.\nNão vou verificar nada. Tenho muitos outros problemas com que me preocupar.",
"Obrigado pela sua gentileza ",
".",
"Virgile Boon",
"",
"Capitão ",
", como você pode ouvir, sua reputação o precedeu. Aquele pirata estava realmente prejudicando nossas rotas comerciais, tenho certeza de que você receberá uma recepção calorosa aqui, onde quer que vá.",
"Obrigado gentilmente senhor. Você por acaso sabe do paradeiro de um Capitão Barbossa?",
"Capitão Barbossa.. hmm.. Ora, sim, eu faço o que acontece. Você o encontrará em Octopus Bay. Disseram-me que é o seu local de pesca favorito. Você pode chegar lá passando pela cidade, atravessando um pequeno pedaço de selva e você está lá.",
"Obrigado senhor. Eu vou te dizer adeus.",
};
