string DLG_TEXT[24] = {
"Então, você descobriu alguma coisa? Como estão nossos filhos?!",
"Não sei muito agora, mas o Governador me pediu para investigar. Isso pode demorar um pouco, então é melhor vocês, senhoras, irem para casa até que eu volte com novidades.",
"O que você está olhando? Você veio rir junto com o resto deles?",
"Acalme-se. Qual é o problema?",
"Desculpe. Eu não posso te ajudar.",
"Você descobriu alguma coisa?",
"Eu devolvi seus filhos. Eles estão sendo transferidos para a costa neste momento.",
"Ah, obrigado, obrigado, você é muito gentil",
"Adeus.",
"Ah, aqui está outro! Ele acha que não há problema em rir e zombar de nós!",
"Eu não entendo o que está acontecendo aqui, talvez você possa me dizer?",
"Nossos filhos foram sequestrados ontem à noite e nosso Governador nem levantou um dedo!",
"Espere, o que você quer dizer com eles foram sequestrados? Quem fez isso?",
"Não sei! Quando adormeci, meu bebê estava no berço. Acordei e olhei no berço mas meu bebê não estava lá!",
"Isso é terrível! E os seus maridos, eles estão procurando?",
"Ele não vai sair e mostrar a cara! Ele está com medo! Um covarde!",
"Por favor, tente se acalmar. Vou tentar falar com o Governador.",
"Deus te abençoe, te abençoe!",
"Aguarde, eu voltarei.",
"Não descansaremos até ouvirmos algumas novidades. Estaremos aqui quando você voltar. E abençoe você por ajudar, gentil #stitle#.",
"Bem, vou ver o que posso fazer.",
"Nossos maridos estão no mar, capitão.",
"Ah. E vocês mesmos tentaram falar com o Governador?",
"Ah, aqui está outro! Ela acha que não há problema em rir e zombar de nós!",

};
