string DLG_TEXT[171] = {
", Como posso ajudá-lo?",
"Estou feliz em ver você aqui ",
". Você precisa dos meus serviços?",
"Olá, ",
". Não creio que tenha tido a honra de uma apresentação...",
"Meu nome é ",
".",
"",
" está ao seu serviço.",
"Eu sou ",
".",
"Feliz em te ver, ",
". Se você precisar dos meus serviços, estou pronto para prestá-los agora mesmo.",
". Você está a negócios aqui?",
"Olá, ",
". Como posso ajudá-lo. Posso fazer transações em qualquer moeda.",
"Quero pedir dinheiro emprestado.",
"Preciso urgentemente de um pouco de ouro.",
"Que tal me dar um pouco de crédito?",
"Eu gostaria de colocar algum dinheiro com uma taxa de retorno favorável.",
"Posso guardar algum saque de pirata?",
"Posso deixar um pouco de ouro aqui para um dia chuvoso?",
"Adeus, ",
".",
",",
", você veio pagar suas dívidas? Ah, sim... você me deve ",
" ouro.",
"Olá, capitão. Estou feliz em ver você em dia. Você está pronto para me pagar ",
" aqueles...ouro que você me emprestou?",
"Eu te dou as boas-vindas ",
". Espero que sua viagem tenha sido um sucesso e que você tenha trazido meu dinheiro e os juros que me deve.",
" ouro.",
"Estou pronto para devolver seu dinheiro.",
"Posso pagar-te uma dívida.",
"É hora de pagar uma dívida.",
"Infelizmente, não posso fazer isso agora.",
"Próxima vez, ",
".",
"Infelizmente, não. Voltarei quando encontrar o dinheiro.",
"...",
"Estou contente por te ver, ",
". Se precisar dos meus serviços, estou pronto para ajudá-lo.",
". Você está a negócios aqui?",
"Olá, ",
". Como posso ajudá-lo? Posso fazer transações em qualquer moeda.",
"Gostaria de sacar meu depósito.",
"É hora de recuperar o dinheiro que você está guardando para mim.",
"Quero meu ouro de volta e meus juros.",
"Adeus, ",
".",
"...",
"Prazer em conhecê-lo. Eu sou ",
". Minha ocupação é emprestar dinheiro a juros.",
"Meu nome é ",
". Eu sou um agiota. Se você precisar de algum dinheiro, ficarei feliz em ajudá-lo.",
"Você provavelmente já sabe que meu nome é ",
". Sou bastante conhecido aqui... Bem, vamos ao que interessa. Você precisa dos meus serviços?",
"Quero pedir dinheiro emprestado.",
"Preciso urgentemente de um pouco de ouro.",
"Que tal me dar um pequeno crédito?",
"Eu gostaria de colocar algum dinheiro com uma taxa de retorno favorável.",
"Posso guardar meu espólio de pirata?",
"Posso deixar um pouco de ouro aqui para um dia chuvoso?",
"Adeus, ",
".",
"Ah, claro, por favor. Quanto você precisa?",
"Não muito.",
"Bastante.",
"Quanto mais melhor.",
"Ótimo! É sempre mais fácil trabalhar com pouco dinheiro. É menos arriscado. Eu posso te dar ",
" ouro.",
"Isso é um acordo. Com que interesse?",
"Infelizmente, isso não é bom para mim. Podemos fazer algo sobre isso?",
"Acho que prefiro não me endividar. Adeus.",
"Isso não é um problema. Eu espero que ",
" o ouro ajudará a resolver seus problemas. É uma boa soma.",
"Você tem um acordo. Com que interesse?",
"Infelizmente, isso não é bom para mim. Podemos fazer algo sobre isso?",
"Acho que prefiro não me endividar. Adeus.",
"Hum. Sim, isso é arriscado, mas... tudo bem, posso lhe emprestar dinheiro no valor de ",
" ouro. Espero que você entenda, capitão, é realmente uma quantia grande. Quero que você leve isso a sério.",
"Você tem um acordo. Com que interesse?",
"Infelizmente, isso não é bom para mim. Podemos fazer algo sobre isso?",
"Acho que prefiro não me endividar. Adeus.",
"%% por mês. Considerando o que sei sobre você, não posso oferecer condições melhores.",
"Por mim está tudo bem. Só precisamos discutir os termos.",
"Acho que prefiro não me endividar. Adeus.",
"Considerando o que ouvi sobre você ",
", estarei aguardando o reembolso dentro de ",
" meses. E então, como você vai perceber, terei que tomar medidas para cobrar.",
"Bem, aceito seus termos e seu dinheiro com prazer.",
"Infelizmente, você não tem um acordo. Adeus.",
"Estou muito feliz, mas deixe-me avisá-lo. Estou neste negócio há muito tempo e sei como recuperar meu dinheiro. Então, se você tiver alguma ideia sobre embolsar meu dinheiro, esqueça!\nNão quero ofendê-lo...é apenas um aviso amigável.",
"Ah, entendi. Bem adeus.",
"Bem, cuidado! Os juros estão se acumulando e, além disso, você está com pouco tempo.",
"Não se preocupe. Eu vou te ver.",
"Oh! É simplesmente maravilhoso! Sempre que você precisar de dinheiro, estou à sua disposição.",
"Obrigado. É tão bom lidar com um empresário que paga sua dívida em dia. Você sabe, tudo pode acontecer...",
"Oh, eu estava certo quando fui tão positivo sobre você ",
"! Espero que esta não seja a última vez que você usa meus serviços!",
"Quero pedir dinheiro emprestado.",
"Preciso urgentemente de um pouco de ouro.",
"Que tal me dar um pequeno crédito?",
"Eu gostaria de colocar algum dinheiro com uma taxa de retorno favorável.",
"Posso guardar meu espólio de pirata?",
"Posso guardar algum ouro aqui para um dia chuvoso?",
"Adeus, ",
".",
"Eu vejo um #sgender# inteligente! Então, quanto dinheiro você gostaria de investir?",
"Tudo bem. Tenha certeza de que esse dinheiro estará são e salvo aqui e que você também receberá juros. A propósito, quanto você vai me dar?",
"Posso dizer que você sabe o como e o porquê das coisas. Quanto você deseja depositar?",
"Um quarto da minha riqueza - ",
" ouro.",
"Metade da minha riqueza - ",
" ouro.",
"Tudo o que tenho - ",
" ouro.",
" Bom. Posso oferecer a você...hmm...digamos... juros por essa quantia em dinheiro, ",
"%%. Claro, essa é a taxa por mês.",
"Eu estou bem com isso.",
"É melhor eu mudar a quantidade de dinheiro, então.",
"Acho que prefiro não investir neste momento. Até a próxima.",
" Bom. Posso oferecer a você...hmm...digamos... juros por essa quantia em dinheiro, ",
"%%. Claro, essa é a taxa por mês.",
"Eu estou bem com isso.",
"É melhor eu mudar a quantidade de dinheiro, então.",
"Acho que prefiro não investir neste momento. Até a próxima.",
" Bom. Posso oferecer a você...hmm...digamos... juros por essa quantia em dinheiro, ",
"%%. Claro, essa é a taxa por mês..",
"Eu estou bem com isso.",
"É melhor eu mudar a quantidade de dinheiro, então.",
"Acho que prefiro não investir neste momento. Até a próxima.",
"Agora você pode ter certeza de que aconteça o que acontecer, você não ficará sem dinheiro. Se decidir sacar um depósito, você pode vir a qualquer momento.",
"Tudo bem. Boa sorte.",
"Considerando os juros que combinamos da última vez e considerando o tempo que se passou, acho que devo a você ",
" ouro... Tem certeza que deseja sacar esse dinheiro agora?",
"Absolutamente. Me dê isto.",
"Você sabe, acho que você está certo. Não vou sacar meu depósito agora. Até a próxima.",
"Oh. É uma pena. Eu estava me acostumando a ter essas moedas por perto... he-he. Bem, volte algum dia.",
"Se eu precisar, irei, é claro. Até a próxima.",
"Você ainda esta vivo? E agora você volta para me pagar meu dinheiro? Não se preocupe - eu já perdi tanto que você nunca poderá me pagar! E agora não ficarei satisfeito até te ver morto!",
"Você pode morrer por palavras tão descuidadas!",
"Saia da minha casa! Não quero te ver nunca mais!",
"...",
"Eu gostaria de dividir o saque",
"Sinto-me honrado por me permitir servi-lo, capitão. Se você ainda não vendeu os navios de seus oficiais, e todos os seus bens e canhões, você deveria fazê-lo primeiro e voltar para mim. Tal como está, a parte de cada tripulante será ",
" ouro - tenho certeza que serão ",
"--e sua parte será ",
" ouro. O capital inicial para seu próximo empreendimento será ",
". Você terá que começar a recrutar sua tripulação novamente. Tem certeza de que deseja dividir o saque, capitão?",
"Sim.",
"Não.",
"Muito bem. Tenho certeza que a tripulação estará ",
" com suas ações. Boa sorte na sua próxima expedição!",
"Obrigado.",
"Sinto-me honrado por me permitir servi-lo, capitão. Agora você quer apenas dividir seu ouro ou está planejando uma expedição totalmente nova?",
"Apenas divida o ouro, por favor. A tripulação deverá ser paga, após o que quero voltar ao mar imediatamente.",
"É hora de traçar um limite nesta viagem e começar a planejar uma nova aventura, eu acho.",
"Muito bem. Se quiser maximizar o pagamento, lembre-se de vender todos os navios dos seus oficiais, todos os seus bens e canhões. ",
"Tal como está, a parte de cada tripulante será ",
" ouro - tenho certeza que serão ",
"--e sua parte será ",
" ouro. ",
"Você também terá ",
" sobra de ouro para despesas imediatas. Alguns membros da sua tripulação podem decidir pegar o dinheiro e ir embora, então você pode precisar recrutar substitutos. Deseja prosseguir com a divisão, capitão?",
"Como desejar, capitão. Se você ainda não vendeu os navios de seus oficiais, e todos os seus bens e canhões, você deveria fazê-lo primeiro e voltar para mim. Tal como está, a parte de cada tripulante será ",
"Muito bem. Tenho certeza que a tripulação estará ",
" com suas ações. Volte aqui quando precisar compartilhar sua riqueza novamente, capitão!",
"Obrigado pela ajuda.",
"Três quartos da minha riqueza - ",
" ouro.",
};
