string DLG_TEXT[51] = {
"Me deixe em paz!",
"...",
"Presumo que você vai me reivindicar agora?",
"Isso mesmo. Agora pare de discutir! Ordenarei aos meus homens que o acompanhem até ao meu navio.",
"Não, você está errado. Você é livre.",
"Pensando bem - desisti de tudo por esse canalha! Que tolo eu fui! O que eu deveria fazer agora?!",
"O melhor seria voltar para casa.",
"Suponho que você esteja certo. Você poderia me acompanhar até o governador desta colônia?",
"Receio que não possa. Se eu aparecer na residência do governador, seus soldados vão me prender.",
"Não vejo razão para recusar.",
"Ah, mas não se preocupe! Você está sob minha proteção! Sei que parece bobagem, mas tenho certeza de que, quando descobrirem quem eu sou, deixarão você ir livremente. Eles terão medo de irritar meu pai.",
"Isso pode funcionar, mas não vou correr nenhum risco.",
"Tudo bem, se você diz. Esperemos que você esteja certo.",
"Pena... gostaria de poder convencê-lo. Mas, obrigado pela sua ajuda. Boa sorte.",
"Boa sorte para você também. Espero que você não tenha mais problemas no caminho para casa.",
"Não acredito que ainda existam pessoas nobres nestes tempos!",
"Não tenho certeza sobre nobres, mas há pessoas gentis por aí. Aliás, como você conseguiu se encontrar nessa situação?",
"Meu nome é ",
" e eu sou de uma família influente...",
"Realmente? Por que você está aqui então? E como você caiu nas mãos desse canalha?",
"Receio que seja uma longa história...",
"Não estou com pressa...",
"Amor. A culpa é do amor.... Como filha de um funcionário da corte francesa, ousei me apaixonar por um homem simples. Um capitão...",
"Prossiga.",
"Meu pai descobriu e me proibiu de me encontrar com meu amado, que havia ido para o Novo Mundo. Ah, eu senti tanta falta dele, tanta!",
"E você decidiu segui-lo?",
"Sim. Incógnito, comprei passagem para um navio que vinha para cá, mas piratas nos atacaram. Você sabe o resto da historia.",
"Uma história triste. Talvez eu possa ajudar a encontrar seu noivo para você?",
"Bem. Vou deixar você procurar seu ente querido. Até a próxima.",
"Ah, você não deveria, você já fez tanto por mim...",
"Ouça, eu quero ajudar você. De que outra forma você espera encontrá-lo?",
"Você é tão gentil comigo!",
"Diga-me, qual é o nome do seu amado? E onde posso encontrá-lo?",
"O nome dele é ",
"Raymond Bouchez",
" e ele foi visto pela última vez em uma das colônias #snation#, eu acredito. Parece-me que foi em #sisland_Falaise de Fleur#.",
"Então vamos seguir nosso caminho. A propósito, minha cabine será inteiramente para suas necessidades...",
"(Para Raymond) - Meu amor, finalmente te encontrei! Mas...quem é essa mulher ao seu lado?!",
"...",
"(Para Raymond) - O quê?! Ela é uma prostituta comum! Foi assim que você passou seu tempo enquanto eu te procurava? Enquanto eu estava sofrendo?!",
"...",
"Ah! Por favor, não deve haver derramamento de sangue. Vamos embora. Não quero mais ver essa criatura nojenta!",
"Suponho que você esteja certo. Não adianta subir na lama para chafurdar com porcos. Ele não vale a pena.",
"Como você ousa falar assim comigo?! Não sou apenas um plebeu, venho de uma família influente! Meu nome é ",
"!",
"Sim, e eu sou Netuno, Rei do Mar. Apenas fique quieto e espere pelos meus homens.",
"Ah, então me desculpe. Eu deveria cuidar da minha língua. Nesse caso, o que você está fazendo aqui?",
"Meu Deus! ...",
"Muito a tempo...",
"Você me ligou, capitão?",
"Sim. Pegue essa doce garota e tranque-a em um compartimento de carga. E, a propósito, diga aos colegas - não toquem com as mãos... Bha-ha-ha-ha...",

};
