string DLG_TEXT[61] = {
"Capitão, você ainda está aqui? ",
"Mateus Santos",
" é improvável que você se surpreenda se você demorar muito para atacá-lo.",
"...",
"O que posso fazer para você?",
"É o seu nome ",
"Vito Leone",
"Vito Leone",
"?",
"Você se saiu muito bem, capitão! Aqui estão seus 10.000 ouro. Espero que você tenha encontrado minha filha bem? Ela é linda ela não é? Bem, é melhor eu ir e deixá-la sair daquela cela. Ouça, se você precisar... planejar um funeral para alguém, avise-nos, forneceremos o melhor serviço - com um desconto decente. Venham vocês dois, temos muito o que fazer.",
"Obrigado e adeus.",
"Sim, sou eu. E você deve ser ",
". Ouvi muito sobre o seu sucesso realizando certos... trabalhos.",
"Você chegou há uma semana e já sabe quem eu sou e o que tenho feito? Por que?",
"No meu ramo de trabalho, a falta de informação é muito mais perigosa do que qualquer bala ou espada. Vejo que você está surpreso - ",
"Mateus Santos",
" não te contou quem eu sou, certo?",
"Você sabe tudo, não é? Sim, ",
"Mateus Santos",
" me disse que você é um mensageiro, e a notícia que você trouxe é muito perigosa.",
"Um mensageiro? Muito brincalhão, esse ",
"Mateus Santos",
". Capitão, não sou um mensageiro. Represento uma organização que um filisteu poderia chamar de guilda dos assassinos. E não venho trazer novidades, mas condenar um impostor.",
"É assim mesmo? E quem é esse impostor?",
"Nosso estimado senhor ",
"Mateus Santos",
", como você deve ter adivinhado. Há dois anos, ele apareceu do nada, matou o chefe da filial local da nossa organização e assumiu o seu lugar.",
"...",
"Em teoria, poderíamos fechar os olhos a esse atrevimento, se ele nos mostrasse algum respeito. Mas ele não apenas matou nosso representante, como também parou de compartilhar os lucros com a guilda. Isso, como você pode entender, não poderíamos perdoar.",
"...",
"Tentamos nos livrar ",
"Mateus Santos",
" com a ajuda de mercenários locais, mas ele é um homem engenhoso e conseguiu frustrar todos os atentados contra sua vida. Além de tudo isso, ele roubou algo muito precioso para mim e estou determinado a vê-lo devolvido. Por todas essas razões a guilda decidiu enviar seu próprio homem para lidar com o problema.",
"E ",
"Mateus Santos",
" me prometeu uma grande recompensa pela cabeça de seu suposto assassino - você.",
"Claro que sim! Agora que as coisas estão realmente sérias, ele entende com quem está lidando e ficou com medo. Mas, minha morte não mudará nada agora - ",
"Mateus Santos",
" vai morrer, muito em breve.",
"Então, isso não vai me impedir de matar você e receber minha recompensa.",
"Ah, você poderia me matar... mas provavelmente receberá uma bala como recompensa por seus esforços. Você pensa seriamente que ",
"Mateus Santos",
" deixará você viver depois de falar comigo? Receio que este seja o seu último trabalho, capitão.",
"Hmm... mas se for como você descreveu, o que você sugere?",
"Você me acha um tolo? Você quer viver e dirá qualquer coisa para se salvar. Eu vou te matar e receber minha recompensa!",
"Vejo duas opções para você nesta situação. O primeiro, deixe-me viver e siga seu próprio caminho. A segunda, ajude-me a eliminar ",
"Mateus Santos",
". A última opção lhe renderá uma quantia considerável de dinheiro.",
"Hmm... não tenho nenhuma objeção ao dinheiro... e as coisas que aprendi sobre ele através de outras pessoas estão dando alguma credibilidade à sua história. Mas como você está planejando matar ",
"Mateus Santos",
"? A casa dele é bem guardada, para dizer o mínimo...",
"De jeito nenhum, lide com ",
"Mateus Santos",
" por si só! Estou fora disso. Adeus.",
"Você me acha um tolo? Você quer viver e dirá qualquer coisa para se salvar. Eu vou te matar e receber minha recompensa!",
"Suas atividades recentes mantiveram seu empregador preocupado e, equanto a atenção dele estava focada em você, ele não percebeu que dois de seus subordinados de maior confiança foram subornados. Eles garantirão que quando você atacar a casa dele, não haja mais guardas ao seu redor do seu alvo, então seu caminho até ele estará livre. Agora vá para a casa dele, depois de matá-lo, vasculhe a residência. Qualquer tesouro que você encontrar por lá poderá tomá-lo para si, com exceção do objeto precioso que reivindico como meu, estarei esperando por você nas proximidades e então pagarei seus 10.000 de ouro.",
"Neste ponto, não tenho certeza em quem confiar, exceto na minha espada e pistola. Eu vou matá-lo, mas se você mentiu para mim, tenha certeza de que estará lidando com os dois, e informação não será a única coisa que lhe faltará.",
"De jeito nenhum, lide com ",
"Mateus Santos",
" por si só! Não terei nenhuma participação nisso. Adeus.",
"10.000 ouro é tentador, mas me ofereceram 20.000 ouro para você. Faça as pazes com seu criador, porque a licitação acabou.",

};
