string DLG_TEXT[22] = {
"Você pode me fazer sentir sujo a qualquer momento, grandalhão.",
"Garanto que vou!",
"Uau, você parecia um barco com um mastro grande e alto!",
"Contanto que esse mastro tenha lugar no seu porto, toots.",
"Você disse que me amava!",
"Ah, querido, isso foi apenas conversa de travesseiro.",
"Você quer a verdade? Você não consegue lidar com a verdade!",
"Mostre-me o dinheiro!",
"olá amor, quer uma queda?",
"Awww, onde você estava há dois dias, quando eu tinha tempo e dinheiro?",
"Vou te dar um desconto.",
"Essa é a coisa mais romântica que qualquer mulher já me disse!",
"Então você é o novo grumete, hein?",
"Veja este gancho? Velocidade variável com cinco acessórios alternativos, baby!",
"Fale sujo comigo!",
"Avast, eu sou lindo! Golpeie sua calcinha e prepare-se para ser abordado!",
"Vamos fazer isso de novo, coisa gostosa...",
"Arrrrrrre você está livre no sábado?",
"Vejo-te em breve.",
"Minha caveira e ossos cruzados não são a única coisa que pretendo criar esta noite!",
"Que sorriso lindo você tem!",
"Isso não é tudo, minha linda!",
};
