string DLG_TEXT[35] = {
"Você parece um oficial da Marinha. Normalmente eu adoraria comprar uma bebida para alguém que serve #spronoun# country com tanta coragem, mas infelizmente estou esperando por um amigo.",
"Obrigado. Espero que seu amigo chegue logo.",
"Você parece o tipo de #sperson# que está disposta a correr riscos por dinheiro e provavelmente disposta a quebrar algumas regras, certo? Tenho uma proposta para você. Você está interessado?",
"Isso depende da proposição.",
"Desculpe, você deve ter me confundido com outra pessoa.",
"Então siga-me lá em cima. Isso é melhor discutido em particular.",
"Vá em frente, então!",
"Você sabe como são os governadores, certo? Pegar o dinheiro das pessoas, chamar-lhe impostos, e depois presentear-se com bons navios e boa comida? Você gostaria de colocar as mãos no dinheiro de um governador?",
"Presumivelmente, o governador não vai simplesmente dar isso a você, mas se você tiver um plano, estou interessado.",
"O mais provável é que acabássemos como hóspedes na prisão do referido governador pelo resto da nossa curta vida. Não conte comigo.",
"Na verdade, eu tenho um plano. Vamos nos disfarçar de soldados. Então simplesmente marchamos até a prefeitura, alegamos que estamos prendendo o governador sob a acusação de fraude, confiscamos seu caixa como prova e deixamos a cidade antes que alguém perceba o que aconteceu.",
"Simplesmente 'está certo! Se é tão simples, por que ninguém tentou antes?",
"Tudo fica simples depois que alguém faz isso pela primeira vez. Mas esse é o ponto. É preciso coragem para fazer isso, mas é tão flagrante que eles nunca suspeitarão que é um blefe.",
"OK, você me convenceu. Quando chegamos à prefeitura?",
"Existe o simples e o estúpido, e isso parece estúpido. Encontre outra pessoa.",
"Não esta cidade. #sDouwesen# é um prêmio muito mais rico. Só precisamos encontrar um navio.",
"É o seu dia de sorte, então. Eu tenho um navio. Me siga.",
"Bom dia.",
"Adeus.",
"Isso é verdade, oficial. Eu não estava fazendo nada de errado. Esta #sperson# tem um navio e eu paguei #spronoun# pela passagem.",
"Eu não vou lá! Horrível, viscoso...",
"O que - o túnel ou as pessoas nele?",
"Ambos. Se você insiste em entrar lá, então é aqui que nos separamos.",
"Como quiser.",
"Olá, ",
"! Então eles pegaram você também?",
"Sim. O que eles pegaram você fazendo?",
"Foi um pouco bobo, na verdade. Fui multado por algo trivial, então tentei invadir o caixa do tribunal para recuperar o dinheiro.",
"O que aconteceu?",
"Fugir foi mais difícil do que invadir. Uma patrulha de guarda apareceu no momento em que eu estava saindo pela janela. Por que você está aqui?",
"Lembra daquela sua ideia de roubar o governador se passando por oficial e prendendo-o? Depois que nos separamos, decidi tentar. Embebedei um soldado, roubei seu uniforme, consegui alguns documentos falsos dizendo que havia sido contratado e paguei ao alfaiate para ajustar o uniforme. Depois fiz uma pequena visita ao governador.",
"Eles não caíram nessa?",
"Oh, eles caíram nessa, certo. Eu provavelmente teria escapado se tivesse ficado longe de #sDouwesen# depois.",
"Essa é uma história maravilhosa. Você se importaria se eu escrevesse um livro sobre isso? Parece que tenho muito tempo para escrever.",
"De jeito nenhum. Afinal, a ideia foi sua.",
}
