string DLG_TEXT[164] = {
"Nunca! O #scursed_ship# atacou a cidade e capturou Elizer...er, a filha do Governador.",
"Parece-me que ela é mais do que 'a filha do governador' para você! E quem foi que me nocauteou?",
"Eu,... eu não sei o que você quer dizer, é só que você é um pirata e eles disseram que você estava falando sobre o #scursed_ship#, então você pode saber para onde ela está indo, para que possamos ir resgatar Eliz.. ., er, a filha do governador.",
"Agora, por que eu deveria fazer isso? Parece que todo mundo aqui quer que eu seja enforcado. Agora você me pede para arriscar meu pescoço",
"Eu poderia tirar você daqui. Eu construí essas células, são dobradiças de meio pino, com a alavancagem certa e a aplicação adequada de força, a porta se levantará livremente.",
"Construiu as células, rapaz, alavancagem de fato. Muito engenhoso. Você me parece muito familiar, qual seria o seu nome então?",
"William Turner, em homenagem ao meu pai. A maioria das pessoas me chama de Will.",
"De fato, de fato. Agora sei por que conhecia seu rosto. Você por acaso tem uma 'Moeda da Sorte'?",
"Eu lutaria com qualquer um por ela, até morreria por ela.",
"Ah, ótimo! não se preocupe então. Abra a porta e vamos indo.",
"O que nós vamos fazer?",
"Comande um navio.",
"Roube um navio! Eu não posso fazer isso!",
"Dois segundos atrás você estava preparado para matar e morrer, agora você está ficando um pouco exigente em relação a pegar um navio emprestado. Você quer recuperá-la ou não?",
"Claro que eu faço.",
"Então decida-se. Temos um acordo ou não?",
"Sim, temos um acordo.",
"Bom, abra esta porta, me dê uma espada e vamos para o porto. Precisamos de um navio e depois de uma tripulação. Mas uma coisa de cada vez, o navio primeiro.",
"O que fazemos agora?",
"Vá para o Dauntless o mais rápido que pudermos, então embarcaremos e enviaremos sua pequena tripulação de volta ao porto. O Interceptor chegará ao mar logo depois de nós. Devemos atraí-la para nos embarcar. Enquanto eles revistam o navio, vamos, digamos, 'trocar de navio' e depois partir para #sTortuga#... experiente?",
"Isso muda as coisas que estou pensando. Olha, se você me tirar daqui e me ajudar a conseguir um navio, eu o levarei ao #scursed_ship# e ajudarei a trazer sua senhora de volta. Até onde você iria para salvá-la?",
"Eu tive. A mãe disse que o meu pai me enviou. Usei-o como um colar, mas o navio em que eu estava foi afundado por piratas no caminho para cá. Fui nocauteado, então não me lembro de muita coisa. Fui resgatado por um navio inglês, mas perdi o colar em algum momento.",
"Então o que fazemos agora?",
"Vou procurar um velho amigo: Sr. Gibbs. Ele nos ajudará a contratar alguns marinheiros. Enquanto isso, aproveite para apreciar #sTortuga#. Como já disse antes, se todas as cidades fossem como esta, nenhum homem jamais se sentiria indesejado.",
"Um melhor",
"Um melhor!?",
"Aquele (Will apontando o navio)",
"Qual? Aquele? ... Sim, aquele.",
"Ainda não! Esperamos o momento oportuno.",
"Quando é isso? quando é de maior lucro para você?",
"Posso te perguntar uma coisa? Já lhe dei motivos para não confiar em mim? Faça-nos um favor. Eu sei que é difícil para você, mas por favor fique aqui e tente não fazer nada estúpido.",
"Desculpe ",
"Você está bem.?",
"Sim, o que aconteceu durante a luta?",
"Eu tinha uma moeda amaldiçoada coberta com meu sangue que joguei no tesouro.",
"Por causa disso a tripulação de Barbossa perdeu a imortalidade, então o Comodoro Norrington deve ter vencido a luta.",
"Eu penso que sim. Mas duvido que isso seja uma boa notícia para mim. Ele não gosta de piratas, principalmente este.",
"Fuja enquanto pode! O #scursed_ship# está esperando por você em Rocky Shore.",
"E você? O que você vai fazer? Venha comigo!",
"Impossível, não quero deixar Elizabeth. Não perca tempo, tem uma corda na parede. Use-o para entrar no navio. Enquanto isso, atrasarei a chegada dos soldados.",
"Obrigado Will. Nós nos encontraremos de novo.",
"O que você está fazendo na minha casa?",
"Desculpe, mas sou ",
", capitão do navio '",
". Ouvi dizer que você esta preparando uma expedição e precisa de um parceiro.",
"Isso é verdade, e você quer participar disso?",
"Talvez. Mesmo assim, gostaria de saber mais detalhes sobre esta expedição.",
"Bem, sei que os espanhóis descobriram uma grande jazida de prata no arquipélago há dois anos...",
"Nunca ouvi essa informação. Como você sabe disso?",
"Capturei um galeão espanhol há algumas semanas. A bordo estava um funcionário de #sSantiago# que concordou em me dar esta informação em troca de sua libertação.",
"E você acreditou nele?! Talvez ele só tenha inventado essa história para que você o deixasse ir. ",
"Claro que não. Não o libertei. Ele está preso em #sTortuga# e só vou soltá-lo depois de confirmar a informação.",
"E onde está o depósito de prata?",
"Bem, ele me disse que era numa ilha deserta no meio do arquipélago.",
"Poderia ser #sisland_Battle Rocks#...",
"Você sabe como chegar lá?",
"Sim, eu poderia te levar até lá. Nunca visitei esta ilha. Parece ser muito inóspito e será difícil encontrar um local para atracar. A costa é irregular.",
"Se os espanhóis colonizaram a ilha, acho que podemos atracar lá, não é?",
"Sim claro. E se o seu prisioneiro estiver certo, e quanto ao saque?",
"A prata roubada será vendida em #sTortuga# e dividiremos os lucros de forma justa. o que você acha?",
"É verdade, podemos ganhar muito. Ok, concordo em ser seu parceiro. Quando saímos de #sTortuga#?",
"Tenho a sensação de que a expedição é muito arriscada. Você deve procurar outra pessoa.",
"Bem, capitão, talvez um dia eu o veja novamente",
"Talvez. Adeus.",
"Excelente! Já fiz os preparativos para que possamos ir agora. Mas antes, deixe-me apresentar-lhe minha noiva, Srta. Elizabeth Swann. Ela será útil durante esta expedição. Na verdade, ela é uma boa lutadora!",
"Finalmente, encontramos uma costa.",
"Na verdade, eu estava certo quando disse que a costa é irregular. Vamos para a selva ver se os espanhóis colonizaram a ilha.",
"Eu também não!",
"Agora estamos tão perto da meta que não estou disposto a desistir.",
"Vá em frente! Ele escapou.",
"NADA DE BOM! Agora ele vai avisar o comboio...",
"Não temos outra opção a não ser atacar o comboio o mais rápido possível.",
"Eu penso que sim. Vamos.",
"Eu verifiquei. As caixas estão cheias de prata.",
"Adoro receber notícias como essa! Vamos para os navios. Quero a prata sob a proteção dos nossos canhões.",
"A venda da prata rendeu 150 mil moedas de ouro. Normalmente, seriam 75.000 para cada um. Mas seria justo dar uma parte a Konrad Kulczycki e seus companheiros, certo?",
"Exatamente, Capitão Turner. Eles merecem isso. A ajuda deles foi decisiva. O que você acha de 30.000 moedas de ouro para eles?",
"Concordo. Então, serão 60.000 para cada um.",
"Excelente! Esta expedição foi muito lucrativa.",
"Você nos trouxe sob uma bandeira pirata. Eu não sou um pirata!",
"Você é agora! E você acha que eles teriam nos deixado navegar aqui sem impedimentos se voássemos com as cores do rei?",
"Você. Você é quem eles estão caçando. O pirata.",
"Você parece um tanto familiar. Já te ameacei antes?",
"Faço questão de evitar familiaridade com piratas.",
"Ah, bem, então seria uma pena colocar uma marca negra em sua ficha. Então, se você me der licença... eu vou indo.",
"Você ameaçou a senhorita Swann.",
"Só um pouco... quer dizer, eu tive que tirá-la da água, não foi?",
"Você a insulta! Desembainhe sua espada!",
"Se você insiste! Mas eu sou muito bom, você sabe",
"Bem, como você pode ver, eu também estou bem. Eu não apenas faço essas espadas, mas pratico três horas por dia.",
"Você precisa encontrar uma garota, cara! Ou talvez a razão pela qual você pratica três horas por dia seja porque você é um eunuco. Você é?",
"Pratico três horas por dia para poder matá-lo quando encontrar um pirata! De qualquer forma, os guardas estão aqui agora, então a brincadeira acabou.",
"Oh querido, oh querido! E eu estava começando a me divertir",
"ESPERE! Isto não é justiça!",
"Gosto do seu estilo, Will. Muito dramático!",
"Este homem ajudou a Coroa, não a traiu.",
"Continue, continue. Estou gostando cada vez mais.",
"O que fazemos agora?",
"Vamos para a caverna do Barbossa... Sr. Gibbs, dê uma olhada na praia e depois fique no navio. E lembre-se... guarde o Código.",
"ESPERE! Sou eu quem você quer. Meu nome é Will Turner, meu pai era Bootstrap Bill Turner, o sangue dele corre em minhas veias.",
"Agora Will, não vamos fazer nada estúpido aqui.",
"Minhas condições para minha rendição são que você deixe Elizabeth e a tripulação do Interceptor irem, e er, ",
" também. Você deve libertá-los, ou eu pularei no mar e me perderei no armário de Davy Jones e a maldição nunca será suspensa.",
"Que bom que você se lembrou de mim lá, rapaz.",
"Eu ouvi tudo isso. Você não receberá dinheiro para mim, pirata! Não sou filho de um nobre.",
"Calma rapaz. Eu sei quem você é. Você é filho de William Turner da Inglaterra. Você está fugindo porque roubou o Interceptor para navegar atrás de Elizabeth Swann, que atualmente é prisioneira no #scursed_ship#. Sábio?",
"Como você sabia de tudo isso? E por que você fez o que acabou de fazer?",
"Conheço seu pai, rapaz, e ele me pediu para cuidar de você. É isso que estou fazendo. Então precisamos chegar em #sTortuga# e depois do #scursed_ship#, e sua Elizabeth.",
"Meu pai nunca conheceria um pirata! O que você fez com ele?",
"Olha rapaz, seu pai e eu somos muito antigos. Ele te mandou uma moeda estranha, certo? E você perdeu, certo? Seu pai e eu nos ajudamos de vez em quando, e desta vez sou eu quem o ajuda, ajudando você, Savvy?",
"Bem, suponho que sim, se você sabe disso. Então você vai me ajudar a resgatar Elizabeth, sim?",
"Uma coisa de cada vez, #sTortuga# primeiro, precisaremos de uma equipe e sei que podemos conseguir uma lá. Então vamos embarcar, antes que o querido Oswald realmente pense nisso? E volta para você.",
"Você. ",
"Sim.",
"Você conhece esse navio - o #scursed_ship#?",
"Já ouvi falar disso.",
"Onde ele atraca?",
"Onde ele atraca? Você não ouviu as histórias? O capitão Barbossa e sua tripulação de malfeitores partem da temida Isla de Muerta. É uma ilha que só pode ser encontrada por quem já sabe onde está.",
"O navio é bastante real. Portanto a sua ancoragem deve ser um lugar real. Cadê?",
"Por que me perguntar?",
"Porque você é um pirata.",
"E você quer virar pirata, é isso?",
"--",
"--",
"Lá vem eles.",
"O que você está fazendo com a minha cara?",
"Jack? Jack Sparrow! Posso dizer honestamente que estou feliz em ver você! Como você veio parar aqui?!",
"William? Eu poderia muito bem fazer a mesma pergunta! Quanto a mim, eles pensam que sou algum tipo de deus, e muito provavelmente tentarão *libertar-me* do meu corpo mortal em breve... Queimando-me naquele fogo bem ali...",
"Jack! O compasso! É tudo que preciso, Elizabeth está em perigo. Fomos presos por tentar ajudá-lo. Ela enfrenta a forca! Fui te encontrar e fui capturado!",
"Ah... a Bússola, entendo, mas como você deve ter notado, não estou em posição de ajudá-lo agora.",
"Ainda temos as nossas lâminas Jack, juntos podemos escapar!",
"Diabo... eu sabia que você diria algo assim! Bem, este parece um plano tão bom quanto qualquer outro agora!",
"Conseguimos! Mas mais deles poderiam ter nos ouvido, temos que sair daqui!",
"Não poderia estar mais de acordo, cara!",
"Jack. Elizabeth está em perigo!",
"Você já pensou em ficar de olho mais atento nela? Talvez apenas trancá-la em algum lugar",
"Ela ESTÁ trancada, em uma prisão, condenada à forca por ajudar VOCÊ!",
"Chega um momento em que é preciso assumir a responsabilidade pelos próprios erros...",
"Preciso daquela sua bússola, Jack. Devo trocá-lo pela liberdade dela.",
"William... trocarei a Bússola com você, se você me ajudar... a encontrar isto. [Tira o pano com a marca da chave.]",
"Você quer que eu encontre isso?",
"Não. VOCÊ quer que você encontre isso. Porque a descoberta disso faz com que você encontre e/ou localize de forma incapaz e você descubra a detecção de uma maneira de salvar sua boneca..dotty..belle ol'...qual é a cara dela. Inteligente?",
"Isso... vai salvar Elizabeth?",
"Quanto você sabe sobre Davy Jones?",
"Hum, não muito...",
"Sim, isso vai salvar Elizabeth.",
"Jack, já está ficando tarde, estamos caminhando nesta selva há horas! Suficiente! Nunca salvaremos Elizabeth se não nos apressarmos, estou liderando o caminho agora!",
"Não! Vai! Parar! Caramba... atrás dele!",
"Sinto muito, Jack, minhas emoções tomaram conta de mim, por favor, mostre o caminho...",
"Então, parece que não sou o único que está se metendo em algumas situações bastante indesejáveis, posso ver que você se importa muito com aquela moça, vamos voltar e virar na primeira curva à esquerda!",
"Aí está, nós encontramos! Devemos ter cuidado agora Jack...",
"Não esquenta, parceiro. Tia Dalma e eu nos conhecemos há muito tempo. Grosso como ladrões. Quase inseparáveis somos. Eram. Foi. Antes.",
"Você me conhece?",
"O que irrita todos os homens?",
"Uma mulher.",
"Você sabia disso.",
"Eu não. Eu não sabia onde estava a chave. Mas agora nós fazemos. Então tudo o que resta é subir a bordo do Flying Dutchman, pegar a chave, voltar para Port Royal e salvar sua bela moça, ei!",
"Parece... que precisamos encontrar o Holandês Voador..",
"Esse é o Holandês Voador? Ela não parece muito.",
"Nem você. Não a subestime. [Jack dá uma cotovelada em Gibbs]",
"Vou remar e revistar o navio até encontrar a maldita chave. .",
"Então esse é o seu plano? E se houver tripulantes?",
"Eu derrubei qualquer um no meu caminho.",
"Eu gosto disso. Simples, fácil de lembrar. Seu barco espera por você, senhor!",
};
