string DLG_TEXT[28] = {
"Soluço... Gosto do vinho local.",
"Suínos.",
"Ouvi dizer que você está procurando ",
"Raoul Rheims",
".",
"E suponho que você sabe onde ele está agora?",
"Claro! Mas... minha garganta está tão seca... que é difícil falar. Sabe o que eu quero dizer?",
"Eu faço. Talvez se eu cortar sua garganta...",
"Taverneiro, traga-nos um pouco de rum!",
"Não tenho dinheiro para pagar as bebidas.",
"Só perguntando. É isso.",
"Então me conte tudo, e sem truques",
"Ouça, seu idiota inútil! Eu poderia te derrubar aqui mesmo.\nVá embora.",
"...(Terei que vir aqui novamente.)",
"Uma companhia tão adorável.",
"Conte-me tudo.",
"Então não poderemos conversar",
"...",
"Bem, não sei muito sobre ele, mas sei que seu patrono é o governador de #sRedmond#, ",
"Robert Christopher Silehard",
" ele mesmo.",
"Então, o que há de incomum nisso?",
"O Governador é um aliado poderoso e um inimigo igualmente poderoso. Reims pode ter se encontrado do lado errado de Silehard e está pagando por isso agora.",
"É uma história e tanto, mas ainda não me diz onde ele está.",
"Ele foi atacado recentemente no mar.\nDepois disso, ouvi dizer que ele saiu para se juntar aos contrabandistas em #sisland_Conceicao# porque se sente seguro lá.\nEu me sentiria seguro se fosse guardado por ",
"Desmond Ray Beltrop",
" ele mesmo.",
"Obrigado. Agora eu sei onde procurar.",

};
