string DLG_TEXT[99] = {
", ",
".",
", ",
".",
"Ei, amigo, você não pode parar um minuto para conversar um pouco?",
"Olá Olá. Posso dizer que você é um verdadeiro cachorro-do-mar como eu, então por que não conversamos um pouco?",
"Sinto muito, mas estou com pressa. Vamos conversar depois.",
"Me deixe em paz. Estou cansado de você. Adeus.",
"Quem é você? Não me importo de conversar um pouco, claro, mas gostaria de saber pelo menos o seu nome.",
"Meu nome é ",
", e eu sou o capitão do '",
".",
"Quantas vezes tenho que me repetir! Eu sou ",
", e eu sou o capitão do '",
".",
"Sinto muito, mas estou com pressa e não tenho tempo para falar com você.",
"Não desejo revelar minha identidade e, além disso, não tenho tempo para conversa fiada. Então, vá embora.",
"Oh! Capitão?! Então, aquele é o seu navio ali? Nada mal, nada mal...não há comparação com a nossa banheira.",
"Você não se importa se eu perguntar qual é o seu nome?",
"Qual é o seu nome, companheiro?",
"Oh, sinto muito, capitão. Eu sou ",
" do 'Juno'.",
"Ótimo, ",
", e agora que fomos apresentados, tenho algumas perguntas para você.",
"Agora, quando você sabe meu nome e eu sei o seu, você pode finalmente responder às minhas perguntas ou vai continuar se fazendo de bobo?",
"Sinto muito, tenho que ir agora.",
"Vamos encerrar nossa conversa com essa nota.",
"Estou ouvindo você, capitão.",
"O que há de interessante acontecendo na cidade?",
"Vamos acabar com essa conversa fiada e começar a trabalhar.",
"O que é interessante...? Bem, eu nem sei o que te contar. Cada um tem os seus próprios interesses - um comerciante está interessado numa coisa, um marinheiro noutra. Bem, eu sei disso ",
"Claire Larrouse",
"Claire Larrouse",
" chegou à cidade recentemente. \nDizem que ela está formando uma tripulação para sua nova expedição.",
"Hmm, nunca ouvi esse nome antes.",
"Eu não me importo com isso. Vamos conversar sobre negócios.",
"Isso é tudo que eu queria saber.",
"Obrigado. Isso é tudo que eu queria saber.",
"Só isso? Esses rumores você pode ouvir em cada esquina. Bom dia.",
"Vamos falar de coisas mais sérias agora..",
"Fofoca, fofoca. Agora é hora de uma conversa séria ",
".",
"Capitão, você caiu da lua ou o quê? Ela é uma espadachim e capitã muito famosa e tem muita sorte.",
"Bem, ela é famosa para alguns, mas não para mim. Onde você diz que posso encontrá-la?",
"Ha! Já ouvi falar de muitos supostos espadachins que massacrariam um homem durante o sono e se considerariam grandes. Bem, onde você diz que ela está hospedada?",
"Onde mais? É claro que ela está na taverna ou em algum outro lugar da cidade. Se eu fosse você, iria para a taverna. se Claire não estiver lá, ela virá em breve.",
"Obrigado. Agora quero falar de negócios com você.",
"Já chega desse absurdo. Vamos ao que interessa.",
"Obrigado. Eu tenho que ir agora.",
"Eu irei conversar com aquele sujeito. Até a próxima.",
"Sobre o que você quer falar?",
"Há quanto tempo você veio aqui para #sIsla Muelle#?",
"Há quanto tempo o seu navio está neste porto?",
"Como foi a nossa vela?",
"Bem, você gostou de navegar sob minha proteção?",
"Como está o seu negócio?",
"Então, você gosta de ser comerciante?",
"Por favor, lembre-me do seu problema com bandidos.",
"Você me contou uma vez sobre seu problema com bandidos. Você pode refrescar minha memória sobre isso?",
"Alguns daqueles bandidos que estavam matando seus animais estão mortos, mas havia muitos deles no acampamento\nNão se preocupe, vou acabar com eles.",
"Ninguém vai mais incomodar você ou seus animais.",
"Não, nada. Até a próxima.",
"Deus o abençoe! Você me ajudou muito! Não posso agradecer o suficiente. Porém, pegue esta luneta. Encontrei-o há muito tempo num naufrágio de um galeão. Serviu-me bem no mar e porque não vou precisar dele em terra quero que você fique com ele!",
"Seu presente é muito bem-vindo! Não se preocupe. Se precisar de alguma coisa no futuro, é só me perguntar.",
"Alguns bandidos apareceram recentemente na ilha e estão constantemente matando meus animais. Reclamei com as autoridades locais, mas elas não prestam atenção.\nPosso me comportar bem para um homem da minha idade, mas acho que são cerca de cinco, então não consigo cuidar de todos.",
"Acho que posso ajudá-lo. Você sabe onde acampam esses bandidos?",
"Apenas cinco pessoas? Você dá muita importância a esse problema. Vou lhes ensinar uma lição com facilidade! Você sabe onde acampam esses bandidos?",
"Que pena! As autoridades não fazem nada para proteger os seus cidadãos? Espero que o assunto seja resolvido em breve.",
"Cinco pessoas? Isso é demais para mim.",
"Para falar a verdade, as coisas não vão bem, capitão.",
"Qual é o problema? Você investiu dinheiro em algum negócio não lucrativo?",
"Está tudo bem com isso, capitão. Decidi não abrir uma loja, mas sim comprar uma fazenda de gado. Sabe, eu cresci na fazenda, então sei cuidar dos animais.",
"Isso é bom, mas qual é o problema?",
"Ser pastor de gado? Esse é o sonho da sua vida? Bem, bem... Então, qual é o seu problema?",
"No começo tudo estava bem, mas depois apareceram alguns bandidos na ilha e matavam meus animais constantemente.\nTentei reclamar com as autoridades locais, mas elas não prestaram atenção.\nPosso me comportar bem para um homem da minha idade , mas acho que há cerca de cinco deles, então não consigo lidar com todos eles.",
"Acho que posso ajudá-lo. Você sabe onde acampam esses bandidos?",
"Apenas cinco pessoas? Você dá muita importância a esse problema. Vou lhes ensinar uma lição com facilidade! Você sabe onde acampam esses bandidos?",
"Que pena! As autoridades não fazem nada para proteger os seus cidadãos? Espero que o assunto seja resolvido em breve.",
"Então, você quer que eu vá e mate aqueles canalhas? Em que tempos vivemos!",
"Bem, quem sabe? Acho que em algum lugar na selva. Você realmente quer me ajudar? Então quero retribuir sua gentileza. Para ser honesto, não tenho muito dinheiro,\nmas perderei mais dinheiro se continuarem matando meu gado. Quando você os mata; volte para mim. Boa sorte!",
"Ei, não há problema. Por que não ajudar um homem necessitado?",
"Vou te ajudar. De qualquer forma, preciso de um pouco de exercício, e se acontecer de você ter um pouco de ouro sobrando, tudo bem também...",
"Isso é maravilhoso, ",
"! Não faz muito tempo, eu me sentia seguro aqui, e meus amigos também.",
"Ah, não é nada. A propósito, onde está o seu 'Juno'?",
"Ela já embarcou e eu já economizei algum dinheiro para abrir meu próprio negócio em terra.",
"Eu vejo. Bem, boa sorte. Espero ver-te de novo.",
"Então você decidiu se tornar um comerciante? Bem bem. Tudo bem, boa sorte.",
"Boa sorte para você também, capitão, e agora é hora de eu partir.",
"Até a próxima.",
"Ontem entregamos uma carga de papel da colônia francesa. Nosso capitão prefere o comércio a todas as outras formas de ganhar dinheiro, por isso navegamos de um lado para outro neste arquipélago.",
"E os piratas? Eles te incomodam?",
"Então, como vai? Você tem medo dos piratas?",
"Bem, às vezes somos. Da última vez, escapamos por pouco do brigue pirata, então agora nosso capitão está procurando uma escolta. Nosso navio está carregado, lento e não manobrável.",
"Você diz que precisa de um navio de escolta? Quanto você pagaria por este serviço?",
"Um navio de escolta, você diz... Bem, quantas moedas colocarei no bolso se concordar em escoltar seu navio?",
"O que? Não sei. É melhor você perguntar ao capitão sobre isso. Ele deveria estar na loja agora.",
"Vou perguntar ao seu capitão. Obrigado pela ajuda.",
"Tudo bem, vou falar com o seu capitão.",

};
