string DLG_TEXT[35] = {
"Desculpe, #smister#, não consigo parar para conversar.",
"Justo. Vou deixar você continuar com seu trabalho.",
"Desculpe, se precisar de alguém para carregar ou descarregar seu navio, você terá que encontrar outra pessoa. Estou ocupado.",
"Sim, você olha. Qual navio você está carregando?",
"O '",
"'. Capitão ",
" é um verdadeiro escravo. Se eu não carregar o navio logo, não serei pago.",
"Você parece desgastado. Por que você não vai até a taverna tomar uma bebida e me deixa assumir o controle por um tempo? Eu sou pago por hora, então não importa qual navio eu carrego.",
"Ah, você trabalha aqui? Eu nunca te vi antes",
"Acabei de ser contratado. De qualquer forma, como eu disse, sou pago por hora, então posso assumir aqui ou posso procurar outro trabalho se você não quiser uma folga.",
"Tudo bem, vou deixar você com isso. Lembre-se de avisar ao guarda no convés que você está trabalhando para o capitão ",
", caso contrário você não poderá embarcar.",
"Lembrarei. E você aproveita sua pausa!",
"Obrigado por assumir o meu lugar. Mas é melhor você começar a trabalhar ou estaremos ambos em apuros!",
"Sim, vou começar a movimentar a carga agora.",
"Posso te ajudar, #smiss#?",
"Talvez. Que navio é esse aí?",
"Obrigado, eu estava procurando o '",
"'. Vou embarcar agora.",
"Ei, você não pode embarcar em nosso navio!",
"Capitão ",
" está me esperando. Mas não se preocupe, não vou contar a ele como você o chamou. Adeus e obrigado novamente pela sua ajuda!",
"Foi bom conversar com você, #smadam#.",
"Obrigado. E obrigado também por apontar Capitão ",
"é enviado para mim.",
"Quem é você? Eu não esperava ver mais ninguém aqui.",
"Ainda bem que estou aqui. Você não seria capaz de mover isso sozinho. Me ajude com isso, sim?",
"Ufa! Certamente é pesado. O que há nele - balas de canhão?",
"Ou talvez um corpo - ha ha!",
"Oi, oi! Mas você está certo, eu não conseguiria levantá-lo sozinho. Tudo bem... um, dois, três, HEAVE!",
"Certo... vamos lá... para o convés...",
"Afinal! Finalmente tiramos a coisa do navio.",
"Obrigado pela ajuda. Não sei quanto a você, mas estou exausto - é hora de uma pausa, eu digo.",
"Isso não é uma má ideia. Vejo você de volta ao navio em dez minutos.",
"Não espere por mim se eu chegar atrasado!",
}
