string DLG_TEXT[45] = {
"Pare! Quem vai lá?",
"Meu.",
"Pare! Quem é você e o que está fazendo a bordo deste navio?",
"Sou um dos estivadores daqui. Acabei de ser contratado pelo Capitão ",
" ajudar ",
" com o carregamento do navio.",
"Isso não me surpreende. ",
" está sempre se esquivando e correndo para tomar uma bebida. Tudo bem, vá em frente.",
"Capitão ",
" está me esperando. Talvez você queira dizer a ele que sua amiga chegou? E então você pode explicar por que estou atrasado. Ele realmente estava ansioso pela minha visita.",
"ER não. Não haverá nenhum atraso. Vá em frente, ",
".",
"Obrigado, senhor.",
"Tudo bem, vejo você - saia daí!",
"O que está errado?",
"Eu vou te dizer o que há de errado. Falei com o capitão. ",
"Ele não contratou nenhum novo estivador ultimamente.",
"Ele não espera nenhuma companhia feminina.",
" Isso significa que você provavelmente é um espião. Renda-se agora e talvez eu deixe você viver o suficiente para conhecer o capitão pessoalmente.",
"Não, acho que vou ficar aqui. E você também!",
"Parar! Temos razões para acreditar que há um espião a bordo. Quem é você e o que está fazendo?",
"Sou estivador descarregando carga.",
"Deixe-me ver seus documentos de autorização.",
"Aqui está minha autorização!",
"Se admitirmos que somos espiões, podemos passar algum tempo na prisão? Seria mais fácil do que carregar carga o dia todo.",
"Seus preguiçosos! Volta para o trabalho!",
"E boa sorte para capturar os verdadeiros espiões, se houver algum.",
"Tenho visitado o capitão.",
"Eu já perguntei sobre isso. Ele não recebeu visitantes do sexo feminino.",
"Claro que ele negou para você! Ele provavelmente terá problemas se seus superiores descobrirem, e foi por isso que me escondeu no porão. Estou prestes a gritar e avisar a cidade inteira que estou aqui! E capitão ",
" provavelmente garantirá que você também tenha problemas!",
"Tudo bem, não há necessidade de ser assim. Se o capitão está maltratando você, talvez eu possa fazer as pazes mais tarde?",
"É muita gentileza da sua parte. Talvez eu aceite sua oferta se você tiver tempo em terra. Agora, se você ficar de lado, vou deixar o navio, por favor.",
"Esta aqui é a casa do nosso chefe. Somos seus guarda-costas. Isso significa que somos responsáveis pelo corpo dele. Não somos responsáveis pelo seu corpo, então leve-o embora antes que seja danificado.",
"Tudo bem, estou indo. De qualquer forma, eu não estava interessado no corpo do seu chefe.",
"Ah bom! Você ainda não foi embora.",
"Quem é você?",
"Eu sou ",
". Meu trabalho é fornecer equipamentos para agentes como você quando eles partem em missão. Quase senti sua falta. Você deve ser ",
".",
"Você sabe quem eu sou e o que estou fazendo?",
"Sim. Saber das coisas é problema nosso, não é? Agora, quanto à sua missão. Você pode precisar se livrar dos inimigos sem chamar a atenção, então aqui estão algumas facas de arremesso envenenadas. Não os desperdice.\nE aqui está uma coisinha para ajudá-lo a entrar em lugares onde o inimigo não quer que você entre. Não é perfeito e pode ficar preso na fechadura, então, novamente, não o use até que seja necessário.",
"Como saberei quando precisarei utilizar este equipamento?",
"Obrigado. Tenho certeza que isso será muito útil em algum momento.",
"Fornecer equipamentos é meu trabalho. Saber o momento certo de usá-lo é seu. A questão é: não desperdice o equipamento ou você poderá não tê-lo quando realmente precisar dele.",
}
