string DLG_TEXT[19] = {
".....",
".....",
"Você é o Capitão Joaquim de Almeida?",
"Sim eu sou. O que você quer?",
"Sei que é um corsário português e a minha patroa precisa da sua ajuda.",
"Eu costumava trabalhar para governadores e não para particulares...",
"Eu entendo. Mas ela precisa de alguém que lide com situações perigosas. E por isso ela concorda em pagar bem.",
"Isso parece interessante agora. Onde ela está?",
"Desculpe, mas não tenho tempo para esse tipo de trabalho. Encontre outra pessoa. Adeus!",
"Adeus, capitão!",
"Ela não mora nesta ilha. Na verdade, ela mora em #sHavana#.",
"Humm... Isso é irritante. Eu não pretendia ir para #sisland_Cuba# nas próximas semanas.",
"De fato, mas como eu disse você poderia ganhar muito...",
"Espero que sim. Bem, eu concordo em ajudar. Podemos levantar âncora agora, se você quiser.",
"Afinal, não aceitarei ajudar. Desculpe, mas encontre outra pessoa. Adeus!",
"Infelizmente, não posso ir com você agora. O marido dela tem uma empresa comercial onde eu trabalho e devo ficar aqui a negócios atualmente.",
"Onde ela mora em #sHavana#?",
"A casa dela fica bem em frente à prefeitura. O nome dela é Elvira Carranza... Capitão, não perca muito tempo para vê-la. O marido dela está em perigo.",
"Tudo bem, farei o meu melhor. Vê você!",
};
