string DLG_TEXT[69] = {
".....",
".....",
"Quem é você, senhor?",
"Não fale tão alto. Deve haver muitos guardas na casa...",
"Você veio para me libertar?",
"Suponho que você seja o marido de Elvira Carranza?",
"Sim, mas ainda não sei quem você é",
"Eu trabalho para sua esposa. E sim, eu vim para te libertar.",
"Graças a Deus. Quase perdi a fé para ser libertado.",
"Gostaria de explicar melhor a situação mas não tenho tempo para conversar, Fernando. Os sequestradores poderiam entrar na sala a qualquer momento. Siga-me, devemos fugir",
"Acho que agora posso dizer por que queria estar aqui.",
"Espero que sim. Estamos correndo riscos desnecessários atrasando seu retorno.",
"Eu não estava em #sSantiago# por motivos comerciais quando fui sequestrado.",
"O que você quer dizer?",
"É uma longa história. Deixe-me explicar na taberna.",
"Tudo bem. Vamos.",
"Você conhece Bartolomeu o Português?",
"Claro, foi um famoso pirata português. Participou da batalha de Aguadilla e atacou as fortalezas de #sHavana# e #sCartagena#.",
"Certo. Mas também é meu bisavô.",
"O que? Devo dizer que é um pouco irônico. Você é espanhol e ele não era conhecido por ser amigo dos espanhóis.",
"Sim, mas ele amou uma espanhola.",
"Quem?",
"Senhora Lúcia Montavez. Ele a conheceu quando estava em missão em #sCartagena#. Ela era filha do governador de #sCartagena#.",
"Isso é inacreditável... Como o Governador concordou em deixar sua filha se casar com um pirata, inimigo da Espanha?",
"Ele não fez isso. Quase um ano depois dos acontecimentos de #sCartagena#, Lucia Montavez fugiu desta cidade espanhola e pediu proteção ao governador de #sisland_Conceicao#. Ela sabia que Bartolomeu trabalhava para este governador português. Quando Bartolomeu, voltando de uma missão, a conheceu em #sisland_Conceicao#, demorou apenas um mês para se casarem. Claro, seu pai a deserdou...",
"Então, eles moravam em #sisland_Conceicao#?",
"Sim, durante quase 15 anos. Graças ao ouro ganho em suas expedições, comprou muitas terras e se tornou o maior proprietário de #sisland_Conceicao#.",
"Um proprietário de terras de sucesso depois de ser um pirata de sucesso...",
"Infelizmente, a sorte piorou.",
"Como?",
"Na minha família, não sou o único que foi sequestrado por piratas.",
"Bartolomeu foi raptado?",
"Não, ele teve um menino e uma menina com Lúcia. Mas, quando tinha apenas 13 anos, o menino foi sequestrado. Naquela época, Bartolomeu era um homem velho. Ele se recusou a pagar o resgate e decidiu encontrar os piratas, matá-los e libertar seu filho.",
"Uma missão muito perigosa para um velho. Ele não conseguiu, certo?",
"De fato. Ele nunca mais voltou para casa, nem seu filho.",
"O que aconteceu com sua esposa?",
"Apesar da tristeza, ela permaneceu em #sisland_Conceicao# governando os negócios da família, mas não por muito tempo. Seis meses depois, um incêndio queimou sua mansão e todos os estoques de açúcar. O Governador de #sisland_Conceicao# recusou-se a ajudá-la a emprestar dinheiro para que ela pudesse continuar o seu negócio.",
"Bartolomeu morto, o Governador não se importou com o resto da família.",
"Exatamente. Então, ela teve que sair de #sisland_Conceicao# e ir para #sHavana# morar com seu primo. A única pessoa de sua família que não a repudiou depois do casamento.",
"Eu entendo. Mas, por que você me conta tudo isso?",
"Pois bem, há seis meses decidi ir à #sisland_Conceicao# e visitar a mansão onde viveram o Bartolomeu e a Lúcia. Claro, com exceção de algumas paredes, toda a mansão havia desaparecido. Mas, milagrosamente, abaixo dos escombros, encontrei um baú. Dentro dela havia algumas roupas e também um livro. O diário de Bartolomeu para ser mais específico.",
"E?",
"As últimas anotações deste diário são sobre o sequestro de seu filho. Achei que poderia encontrar alguma informação sobre o paradeiro de seu filho.",
"Descobrir onde seu filho estava preso poderia lhe dar a localização do cadáver de Bartolomeu se admitirmos que ele foi morto pelos piratas.",
"Na verdade, também acho que ele morreu ao tentar libertar o filho. Infelizmente não consegui encontrar essa informação no livro. Pelo menos, nada de óbvio. Por isso emprestei o diário para alguém aqui de #sSantiago#. Ele sabe muito sobre a história da pirataria no Caribe. Tive que deixar o livro por um ou dois dias, tempo suficiente para ele encontrar uma pista. Como você deve imaginar, fui sequestrado antes de poder fazer uma nova visita a ele.",
"Tudo bem, não perca mais tempo. Vamos vê-lo.",
"Você acha que o cadáver dele está aí?",
"Talvez. De qualquer forma, não temos ideia de outro local e a ilha não fica muito longe daqui. Nós podemos tentar.",
"Por onde começamos nossa busca?",
"A ilha é pequena. Então, se o cadáver do Bartolomeu estiver aqui, não será muito difícil encontrá-lo. Vamos procurá-lo na selva.",
"Capitão, eu o encontrei! Acabei de pegar a espada dele. Seu nome está gravado na lâmina. Suponho que o outro cadáver pertença a Guillaume Auger.",
"Lâmina impressionante! Sobre o outro cadáver, acho que você está certo. Bartolomeu deve ter matado Guillaume num duelo. No entanto, ele deve ter sido gravemente ferido pelo pirata francês e morreu poucos minutos depois. Triste história! Então, o que você quer fazer agora?",
"Acho que seria correto pegar seu cadáver e enterrá-lo perto do túmulo de sua esposa, no cemitério de Havana.",
"Você tem razão. Ele merece coisa melhor do que estar numa caverna sem sepultura.",
"Sua tripulação carregou o cadáver no navio. Podemos voltar para #sHavana#?",
"Claro. Hora de ir!",
"Durante a viagem, pensei nisso. Você merece ficar com a espada dele.",
"O que? Mas, pertence primeiro à sua família.",
"Sim, mas sem ajuda, poderia estar morto agora em #sTortuga# sem a oportunidade de enterrar Bartolomeu perto da sua mulher.",
"Bem, obrigado por este presente incrível! Nunca esquecerei sua gentileza. Foi uma honra estar com você nesta aventura. Até mais, Fernando!",
"Muito obrigado! Mas antes de partir, gostaria de lhe perguntar mais uma coisa...",
"Claro, o que exatamente?",
"Você poderia me dizer onde fica a mansão dos Bartolomeu na #sisland_Conceicao#?",
"Por que?",
"Eu gostaria de ver sua mansão. Onde ele passou os últimos anos de sua vida.",
"Como eu disse, não sobrou quase nada de sua mansão. E duvido que você encontre mais alguma coisa, exceto o baú que abri.",
"Talvez você esteja certo. No entanto, não ficarei desapontado se não encontrar nada...",
"Tudo bem. Não é muito difícil encontrar a mansão. Encontre uma baía na costa õeste de #sisland_Conceicao#. Só existe uma praia lá. Atraque e entre na selva. Sua mansão fica perto da praia.",
"Obrigado novamente. Irei para lá o mais rápido possível. Até mais, Fernando!",
};
