string DLG_TEXT[25] = {
".....",
".....",
"Me deixe em paz!",
"Você está bem? Quem é você?",
"Porque perguntas? Você é um oficial deste navio. Você deveria saber que sou um prisioneiro?",
"Não, não sou oficial e não trabalho para os ingleses.",
"O que!? Por que você usa esse uniforme? Não me diga que você é um espião?",
"Para falar a verdade, estou trabalhando para o lado americano e para o governador de #sisland_Eleuthera#. Estou aqui para afundar este navio de guerra.",
"O que?! Como?",
"Vou explodir o paiol de pólvora. Se você quer viver, você deveria me seguir.",
"Você está brincando?! Claro, quero fugir deste navio. Tire essas correntes, por favor!",
"Obrigado, capitão. Sou Henri César, ainda era capitão de escuna há alguns dias.",
"O que aconteceu com você?",
"Má sorte! Ataquei um navio mercante britânico e antes de embarcar nele, este navio de guerra apareceu no horizonte. Era tarde demais para partir. Tive que me render para não ser afundado.",
"Você é um pirata?",
"Digamos que eu tento sobreviver. Eu pertenço à Irmandade Pirata de Nevis.",
"Tudo bem, vamos parar de conversar. Devemos deixar o navio o mais rápido possível. Alguns soldados poderiam vir aqui a qualquer momento. Só preciso de um minuto para plantar a bomba e iniciar a contagem regressiva.",
"Obrigado, capitão! Pensei que nunca mais seria livre.",
"De nada. E agora? O que você vai fazer?",
"Eu quero deixar esta ilha do diabo. É muito perigoso para mim",
"Venha comigo para #sEleuthera#. Eu e o Capitão Lafitte devemos informar ao Governador que tivemos sucesso em nossa missão.",
"Ótimo! Certamente encontrarei um navio para voltar a Nevis e reencontrar meus companheiros.",
"Eu penso que sim. Embarque no meu navio!",
"Obrigado, capitão! Estou seguro aqui. Agora posso procurar um navio partindo para Nevis.",
"Como eu disse, não será difícil encontrar um navio. Feliz em te ajudar. Que o vento esteja sempre em suas costas!",
};
