string DLG_TEXT[80] = {
".....",
".....",
"O que você quer?",
"Meu nome é Joaquim de Almeida. Sou Capitão e o Governador de #sisland_Eleuthera# me pediu para entregar esta carta.",
"Humm... Então, parece que você será meu parceiro na missão.",
"Certo. Você encontrou algum homem para sua tripulação?",
"Quase... As pessoas me conhecem no #sTortuga#. Não será difícil encontrar mais alguns homens. Enquanto isso, sente-se, estarei com você em alguns minutos.",
"Feito! Tenho homens suficientes para a missão.",
"Bom. Porém, você já tem um plano?",
"Eu penso que sim. Suponho que você conheça um navio de guerra enviado da Inglaterra atracado em #sisland_Turks# recentemente.",
"Sim, o Governador me disse.",
"A guarnição de #sisland_Turks# não seria suficiente para atacar #sEleuthera#. No entanto, o HMS Endeavour, um navio de guerra que transporta muitas centenas de soldados, está lá preparando o ataque.",
"Eu não esperava tal força. Como podemos derrotá-los? Parece ser uma missão suicida parando-os.",
"Claro, não vamos combatê-los no campo de batalha.",
"Então?",
"O navio de guerra é o seu bem mais importante. Devemos afundá-la.",
"No mar isso é impossível.",
"Você tem razão. Mas no porto temos a oportunidade de fazer isso.",
"Como?",
"Precisamos plantar uma bomba no paiol de pólvora dela. A explosão irá afundá-la em poucos minutos e matar muitos dos soldados.",
"Isso é viável, mas como chegar ao paiol de pólvora sem ser detectado?",
"Sem ser detectado, é realmente impossível. No entanto, alguém vestido como um oficial britânico seria menos suspeito.",
"Você tem razão. Mas não há garantia de que ele não será reconhecido e preso.",
"Eu admito. Mas, não vejo outra maneira.",
"Pelo menos, poderíamos aumentar a chance de criar uma diversão.",
"Como?",
"Vamos que nossos tripulantes ataquem os guardas e os prédios próximos aos portões da cidade para atrair o maior número possível de soldados. Os tripulantes sempre podem correr para a selva para evitá-los. Enquanto isso, será mais fácil embarcar no navio.",
"Talvez. De qualquer forma, antes de executar o plano, precisamos saber como a cidade está protegida.",
"Claro.",
"Não temos tempo a perder. Ainda devo ficar alguns minutos na taverna para conversar com meus novos recrutas. Espere por mim no porto, para que possamos zarpar para #sisland_Turks# o mais rápido possível.",
"Como quiser.",
"Bem. Hora de ir, capitão.",
"Seria melhor evitar o porto #sisland_Turks#', não acham?",
"Na verdade, penso que a costa do Farol é o começo perfeito para a nossa missão.",
"Eu diria: Até aí tudo bem, Capitão!",
"Sim, a parte mais fácil da missão está feita.",
"Exato. Agora, vamos para a cidade e tomemos cuidado com alguns bandidos que podemos encontrar no caminho.",
"Tudo bem, Capitão Lafitte.",
"Devíamos ir ao porto verificar se o navio ainda está lá e quantos guardas o estão protegendo.",
"De fato. Vamos!",
"Aqui está o navio! Bem em frente ao porto.",
"Um grande problema, de fato. Pelo menos não vejo nenhum guarda no porto.",
"Os britânicos estão bastante confiantes na segurança da cidade. Vamos para a taberna conversar sobre o próximo passo.",
"Como eu disse, vestido como oficial da Marinha Real, temos mais chances de plantar a bomba.",
"Esse tipo de roupa não se vende em alfaiataria. Devemos capturar um oficial.",
"Você tem uma ideia?",
"Talvez. Primeiro, devemos encontrar uma prostituta em #sisland_Turks#.",
"O que? estamos aqui com a missão de não aproveitar bons momentos.",
"Eu estava falando sobre nossa missão, é claro. Ela poderia nos ajudar.",
"Como?",
"Ela poderia 'motivá-lo' a passar algum tempo longe dos colegas. Perfeito para atordoá-lo e roubar sua roupa.",
"Bem, isso deve ser feito antes de embarcar no navio.",
"Na verdade, devemos evitar que sua ausência seja notada.",
"Amanhã à noite, o navio deve ser afundado. Não há tempo a perder.",
"Tudo bem, vamos encontrar agora mesmo uma prostituta. Isso não deve ser muito difícil.",
"A garçonete certamente deve nos ajudar.",
"Eu vou falar com ela.",
"Está tarde. Espero que ela faça a parte dela.",
"Eu também. Talvez eu deva ir à taverna... Espere! ela está vindo.",
"Feito! Atordoado",
"Ok, vamos tirar o uniforme dele.",
"Você já pagou a primeira metade. Eu pago-lhe o resto.",
"Obrigado, capitão.",
"Preparar?",
"Sim. Então, onde está a bomba que preciso plantar?",
"Pegue. É pequeno o suficiente para ficar escondido sob seu uniforme.",
"Obrigado. Quanto tempo antes de explodir?",
"Cerca de 10 minutos. Apenas o suficiente para se afastar do navio.",
"E seus homens?",
"Eles estão à tua espera. Eles vão te levar no barco. Embarque no navio discretamente e evite os guardas, é claro. Ninguém pode notar que você não pertence à tripulação.",
"E o desvio?",
"Não se preocupe. Conforme planejado, alguns dos meus tripulantes estão esperando para atacar alguns soldados na cidade e atraí-los para longe do porto.",
"Ótimo. Então, hora de ir.",
"Parabéns capitão, você conseguiu!",
"Obrigado. Voltemos ao farol. Devemos nos afastar desta cidade para evitar os guardas.",
"Hora de partir, capitão?",
"Certo. Agradeço por ser seu parceiro nesta missão em #sisland_Turks#.",
"Eu também. Talvez no futuro façamos mais expedições juntos.",
"Sim, por que não... Apresse-se, Capitão! o governador está esperando que você dê a recompensa. Vê você!",
"Concordo.",
};
