string DLG_TEXT[34] = {
".....",
".....",
"O que você está fazendo na frente da minha casa?",
"Suponho que você seja Laura Cotton. Na verdade, preciso da sua ajuda.",
"Sim, sou Laura Cotton e pela sua ajuda são 50 moedas de ouro pagas antecipadamente.",
"Bem, não é esse tipo de ajuda.",
"Não? Então adeus!",
"Espere! se você me ajudar, receberá muito mais dinheiro. Posso garantir totalmente a você.",
"Explicar!",
"Este trabalho é muito fácil. Você só precisa atrair para sua casa um oficial da Marinha oferecendo seus *serviços*",
"Por que um oficial da Marinha? Qual é a sua ideia no fundo da sua mente?",
"Eu não posso te contar. Mas não se preocupe, não queremos matá-lo. Só queremos o uniforme dele.",
"Eu poderia ter dificuldade em ajudar você.",
"Você acha que ele irá falar com sua hierarquia informando que estava na casa de uma prostituta quando alguns bandidos roubaram sua roupa? Eu não acho.",
"Hummm. No meu caso, posso sempre dizer que não te conheço e que você estava tentando roubar meus pertences.",
"Certo. Então, temos um acordo?",
"Depende do dinheiro que você pode pagar...",
"200 moedas de ouro.",
"Eu não acho. Eu quero o dobro ou nenhum acordo.",
"Isso é caro, você não acha?",
"Tenho a sensação de que é importante para você ter essa roupa. Então, aposto que você pode pagar mais.",
"Tudo bem, você faz uma barganha difícil. Eu concordo em pagar.",
"Espere não tão rápido! São 200 agora e 200 depois que você tiver o uniforme.",
"Tudo bem, pegue essas 200 moedas de ouro, mas não tente me enganar. Eu não seria tão galante.",
"Concordo, mas não tenho essa quantia no momento. Estarei de volta em algumas horas com o dinheiro.",
"Espero que sim, se quiser eu te ajudo. Você vai me encontrar na cidade",
"Então? Você está com meu dinheiro?",
"Sim, finalmente. Pegue essas 200 moedas de ouro, mas não tente me enganar. Eu não seria tão galante.",
"Quase. Eu volto em breve.",
"Obrigado, não se preocupe. Amanhã à noite estarei na taverna. Encontrarei facilmente esse oficial lá. Espere só por mim perto da minha casa",
"Nós faremos.",
"Primeiro, pague-me o resto da minha recompensa.",
"Obrigado. Quando ele acordar, direi a ele que fui atacado e roubado.",
"Eu aprecio. Boa sorte!",
};
