string DLG_TEXT[50] = {
"Alguma ordem, senhor?",
"Nada no momento. Continue, Sr. Bush.",
"Parece muito rum, hein, senhor?",
"Eles são aliados de Sua Majestade, Sr. Bush.",
"Aliados, senhor? Pensei que esta parte do mundo pertencesse à Espanha.",
" foi persuadido pela Inglaterra a se revoltar contra a Espanha.",
"Então a nossa carga de armas é para ele?",
"Se ",
" puder conquistar Cuba, a Espanha terá que tirar navios e soldados de Napoleão para preservar suas colônias.",
"Sr. Bush, aqui estão as chaves da minha caixa de despacho contendo as ordens do Almirantado. Se eu não estiver de volta a bordo até meia-noite, você assumirá o comando.",
"Não voltou a bordo, senhor? Mas você disse que eles estavam do nosso lado",
"A guerra gera aliados estranhos, Sr.",
"Prepare os barcos para armazenar o navio, Sr. Bush. Há provisões suficientes chegando a bordo para nos tornar independentes por dois meses. Nossa carga desembarca.",
"Sim, sim, senhor.",
"Ah, e Sr. Bush, há um navio espanhol com 60 canhões chegando aqui antes do amanhecer. Envie seu melhor vigia ao topo daquela colina para nos avisar da aproximação do inimigo.",
"Estação de vigia informa que 'Natividad' foi avistada, senhor.",
"Oh, obrigado, Sr. Bush, apagaremos as luzes.",
"TODAS AS LUZES APAGADAS!",
"Devo parar o carregamento, senhor?",
"Não, ainda temos algumas horas.",
"Não vamos correr para o mar aberto, senhor?",
"Não, permaneceremos ancorados aqui, sob o sotavento deste ponto.",
"Ah, e Sr. Bush, você, o Sr. Gerard e o Sr. Longley me dariam o prazer de sua companhia no jantar esta noite?",
"Obrigado, senhor! Er - esta noite, senhor?",
"Nosso jovem aspirante pode estar arriscando a vida antes do amanhecer, Sr. Bush. Seu estômago pode ficar melhor com uma refeição.",
"Esse é o espanhol para você. Eu estava apostando que eles fariam exatamente isso.",
"Agora, senhores, eis o que pretendo fazer. Senhor Bush, escolha um esquadrão dos melhores nadadores da tripulação e depois entregue-lhes armas.",
"Sr. Bush, poderia remover os oficiais para o '",
"' e colocá-los em ferros.",
"Ah, ela é uma beleza, senhor. O comissário calcula que ela vale 120 mil guinéus. Isso dá a todos os homens a bordo '",
"'50 guinéus de prêmio em dinheiro.",
"O 'Natividad' não é um navio premiado, Sr. Bush.",
"Peço perdão, senhor?",
"Ela será usada pelo nosso aliado, Don Julian.",
"Você está entregando-a, senhor? Mas a sua própria parte valeria 10.000.",
"Não pedi números.",
"Mas senhor, você mesmo disse que Don Julian estava louco. Você pode confiar nele?",
"Fique tranquilo, Sr. Bush. Só eu terei que responder perante o Almirantado por esta decisão.",
"Don Julian está vindo a bordo, senhor.",
"Uma salva de 11 tiros, Sr. Bush",
"Sim, sim, senhor. FOGO!",
"Sr. Bush, estamos voltando para o ",
"O que ela é, Sr. Bush?",
"Lugger espanhol, senhor. Hasteando uma bandeira branca. Isso significará uma negociação.",
"Use uma arma.",
"Traga os prisioneiros aqui.",
"Senhor Bush, peço-lhe que lembre a todos que este ainda é um navio de guerra!",
"Sinal da capitânia, senhor. Todos os capitães sobem a bordo.",
"Oh, muito bem, Sr. Bush. Reconheça e limpe o caminho trabalhe.",
"RECONHEÇA! LIMPE O CAMINHO DO CAPITãO, TRABALHE!",
}
