string DLG_TEXT[318] = {
"Aportamos no assentamento pirata em #sisland_Quebradas Costillas#. Mandei içar meu Roger pessoal para que ninguém nos cause problemas. Os oficiais e parte de sua tripulação decidiram abrir caminho pela selva em direção a #sCharlestown#. Acho que eles não querem ser caçados pelos ingleses como traidores. Infelizmente você não tem essa opção. Não posso agradecer o suficiente pelo que você fez por minha tripulação e por mim.",
"O capitão Champers era um porco e o que ele pretendia para você era monstruoso. Eu não vi escolha.",
"Cães traiçoeiros. Suponho que previ isso chegando. O que posso fazer por você, capitão?",
"Desculpe, capitão Fletcher, não há tempo para bate-papo. Preciso ir embora antes que a Marinha apareça. Sei que há uma tempestade violenta, mas enfrentarei esse risco e partirei imediatamente. Adeus e boa sorte!",
"Esta vida acabou, mas meus homens precisam de um lar. Eles são bons marinheiros, extremamente leais e devem suas vidas a você. Você faria bem em enfrentá-los. Você deve examiná-los e atribuir-lhes tarefas adequadas às suas habilidades. Sugiro o Sr. Sullivan como primeiro imediato, mas é claro que a escolha é sua. (Abra a janela 'Passageiros' para ver seus novos oficiais)",
"Sim, falei com Sullivan. Ele parece um marinheiro competente e um bom sujeito. Tenho certeza de que todo o seu pessoal sabe o que está fazendo.",
"As autoridades estarão atrás de você com uma vontade poderosa pelo que você fez. Eles estarão procurando sua cabeça, quer precisem levá-la em terra ou no mar.",
"Verdadeiro. Terei que estar atento a assassinos e também à Marinha.",
"Você tem que ficar atento o tempo todo e é melhor levar um guarda-costas com você quando estiver em terra. Kildare é especialmente intimidante e um excelente contramestre.",
"Eu vou tomar cuidado. Há mais alguma coisa, Roberto?",
"Sim, há alguns assuntos que você precisará resolver imediatamente.",
"Tudo bem, vá em frente.",
"Lembro-me de tudo muito bem. Obrigado.",
"Não importa tudo isso, a Marinha pode estar nos atacando agora mesmo! Preciso sair do porto agora, antes que seja pego pelo ataque, seja uma tempestade violenta ou não!",
"Em primeiro lugar, leve o seu equipamento pessoal. Lembre-se, você deve sempre ter sua lâmina, pistola e luneta com você. Quem sabe o que pode acontecer.",
"Onde foi que tudo foi guardado quando me mudei para a cabine do capitão?",
"Todos os seus efeitos estão no grande baú atrás de você. Mandei trazer seu guarda-roupa também.",
" Basta chegar perto dele e você verá o 'ícone de mão' no canto superior esquerdo da tela \nIsso significa que você pode fazer algo lá. Ao ver o ícone, basta pressionar o botão 'Ação'.",
"Eu vejo.",
"Se você usar uma caixa ou um baú dessa maneira, você verá uma interface que lhe permitirá pegar itens do contêiner ou colocá-los nele\nAgora, vá pegar seus pertences, Capitão, e fale comigo novamente quando você acabou.",
"Tudo bem, espere.",
"Você não esqueceu alguma coisa? Parece que você ainda não pegou todos os seus pertences.",
"Ah, sim, como eu poderia esquecer! Um momento, por favor.",
"Muito bom. Antes de continuarmos, devemos cuidar de uma coisa importante que pode determinar a sua sobrevivência durante os embarques. Cada navio possui um armário de armas onde são guardadas as armas utilizadas pelos grupos de embarque, você poderá encontrá-lo na 'Cabana do Capitão'. Este armário tem um símbolo especial, uma faca cruzada com uma pistola, mas você acessa ele como um baú normal. Quanto melhores forem as armas que você colocar lá, mais sucesso sua tripulação terá durante o combate corpo a corpo no convés.",
" Sua tripulação devolverá todas as armas após a ação de abordagem, junto com aquelas que pegaram dos inimigos derrotados. ",
"Sua tripulação levará armas com eles, então você deve se lembrar de reabastecer os suprimentos no armário de armas com frequência. ",
"Quando você estiver na cabine de um navio capturado, você pode inspecionar o armário de armas para encontrar armas adicionais.",
"A propósito, eu poderia te ensinar um pouco sobre esgrima, se você quiser. Basta me pedir.",
"Acho que preciso de algum treinamento. Ensine-me.",
"Não estou interessado nisso, Robert. Vamos continuar.",
"Estou ficando cansado disso. É o bastante.",
"Ótimo! Agora você deve equipar suas armas e luneta. Para fazer isso, pressione a tecla 'Tela de Personagem' (f2) e selecione o ícone 'Inventário' no canto superior direito da tela. Uma vez dentro do seu inventário, você notará algumas categorias na parte inferior da tela, 'Arma', 'Medicamentos', 'Itens', 'Mapas' e 'Itens de missão'. Para equipar sua espada, clique no ícone 'Arma', procure sua espada e clique no ícone 'equipar' para equipá-la ou no ícone 'liberar' para desequipá-la. Faça o mesmo com sua pistola.",
" Quando terminar, clique no ícone 'Itens', escolha sua luneta e equipe-a. Você também pode usar a tecla 'equipamento rápido' do teclado. Observe que sua lâmina deve ser equipada antes de sua pistola. Lembre-se também de que nem todos os itens podem ser equipados. Agora equipe sua espada, pistola e luneta, depois fale comigo novamente.",
"Só um segundo...",
"Você não conseguirá se defender muito bem apenas com os punhos.",
"Tudo bem...",
"Ei, você esqueceu sua pistola. Também deve ser equipado.",
"Por favor, desculpe-me, estou bastante impressionado com todas essas novas informações!",
"Eu vou fazer isso agora.",
"Agora, para ajudar seus pensionistas, coloque aquele monte de ",
" no seu armário de armas.",
"OK.",
"Eu entendi; você os coloca lá e vamos continuar com coisas mais importantes.",
"Parece que você ainda não equipou o armário de armas.",
"Espere um minuto...",
"Sem problemas. Preste atenção por FAVOR. No canto inferior esquerdo você verá o ícone do seu personagem. A barra vermelha acima é a sua saúde. A barra azul representa o status de carregamento da sua arma. E o círculo acima dessas barras mostra quantos tiros você ainda tem na sua pistola.",
"Eu entendo.",
"Bom. Precisamos de algum espaço para nossos exercícios. Me siga; ao se aproximar da porta, você verá o ícone 'Abrir cadeado' no canto superior esquerdo da tela. Pressione a tecla 'Ação' para ir para o próximo local.",
"Continue.",
"Agora, desembainhe sua espada com a tecla 'Draw/Sheathe Sword'. Primeiro você deve se familiarizar com os controles, para não atacar você. Use a tecla 'Ação' para atacar e a tecla 'Pistola de Fogo' para disparar sua pistola.",
"Deixe-me tentar.",
"Só um segundo. Para ganhar rapidamente alguma distância entre você e o inimigo, você pode pular para trás pressionando a tecla 'Dodge'. Observe que você não pode falar com ninguém com sua arma em punho. Portanto, antes de falar, embainhe sua arma pressionando a tecla 'Desenhar/Embainhar Espada' novamente.",
"Eu entendi. Agora deixe-me tentar.",
"Bem, você tem certeza que entendeu tudo até agora?",
"Sim, e obrigado pela instrução Robert",
"Não, acho que vou tentar de novo.",
"Estou farto de todas essas instruções, vamos continuar com outras coisas.",
"Tudo bem, isso é o suficiente. Você está pronto para alguma ação real?",
"Claro, vamos lá!",
"Ainda não. Deixe-me praticar um pouco mais.",
"Sem problemas.",
"Obrigado.",
"Eu vou lutar desta vez. Tenha cuidado e não se esqueça que você pode bloquear golpes com a tecla 'Bloquear'. Se você entrar em combate sem pensar, logo estará alimentando os abutres.",
"Eu entendi. Vamos começar.",
"Nada mal nada mal! Lembre-se de que se você foi ferido em uma briga você pode recuperar um pouco de saúde usando poções, bandagens e outros itens de cura. Para fazer isso você deve pressionar a tecla 'Menu de Comando Rápido' e selecionar o ícone Usar. Em seguida, pressione a tecla 'Ação', selecione o item de cura na lista e pressione a tecla 'Ação' novamente.",
"Eu vejo. Qual é o próximo?",
"Quero treinar mais um pouco. Vamos lutar novamente.",
"Chega dessas lições. Você está demitido.",
"Hmm... Parece que você precisa de mais prática... Lembre-se de que se você foi ferido em uma briga você pode recuperar um pouco de saúde usando poções, bandagens e outros itens de cura. Para fazer isso você deve pressionar a tecla 'Menu de Comando Rápido' e selecionar o ícone Usar. Em seguida, pressione a tecla 'Ação' e selecione o item de cura da lista e pressione a tecla 'Ação' novamente. Agora, vamos tentar de novo.",
"Se você diz. Vamos começar novamente.",
"Vou melhorar minhas habilidades mais tarde. Qual é o próximo?",
"Chega dessas lições confusas.",
"Sempre pronto!",
"Se prepare.",
"Isso é muito melhor. Agora posso deixar você ir para terra firme sem nenhuma preocupação.",
"Qual é o próximo?",
"Ainda acho que preciso de mais prática.",
"Chega dessas lições. Demitido.",
"Não... acho que levará mais algum tempo para lhe ensinar esgrima adequada. Talvez você devesse passar alguns dias treinando a bordo.",
"Podemos tentar mais uma vez?",
"Vou melhorar mais tarde. Qual é o próximo?",
"Multar. Antes de deixarmos o navio, deixe-me falar sobre suas habilidades e habilidades. Como um capitão habilidoso sempre tem mais chances de sobrevivência neste mundo cruel, você deve evoluir seu personagem com sabedoria\nPara lutar contra inimigos e completar missões, seu personagem ganha pontos de experiência. Quando você obtém experiência suficiente, seu personagem ganha uma nova classificação e pontos adicionais de habilidade e habilidade. Ao usar esses pontos em diferentes habilidades e habilidades, você pode melhorar vários aspectos do seu personagem.\nPara obter todas as informações sobre o seu personagem, pressione a tecla 'Tela do Personagem' (F2). Lá você verá a classificação, reputação, dinheiro, habilidades e pontos de vida do seu personagem. Agora você tem alguns pontos de perícia e habilidade\nVocê pode distribuí-los agora ou mais tarde.",
"Como posso distribuir pontos de Habilidade e Habilidade?",
"Multar. Antes de partirmos, deixe-me falar sobre suas habilidades e habilidades. Como um capitão habilidoso sempre tem mais chances de sobrevivência neste mundo cruel, você deve evoluir seu personagem com sabedoria\nPara lutar contra inimigos e completar missões, seu personagem ganha pontos de experiência. Quando você obtém experiência suficiente, seu personagem ganha uma nova classificação e pontos adicionais de habilidade e habilidade. Embora você tenha a opção de decidir qual habilidade deseja melhorar, várias habilidades serão melhoradas de acordo com suas ações.\nPor exemplo, durante o esgrima, sua habilidade corpo a corpo melhorará. Quando a melhoria atingir 100%, você subirá um nível.\nPara obter todas as informações sobre seu personagem, pressione a tecla 'Tela do Personagem' (F2). Lá você verá a classificação, reputação, dinheiro, habilidades e pontos de vida do seu personagem, bem como a porcentagem necessária para atualizar uma determinada habilidade para o próximo nível. Agora você tem um ponto de habilidade\nVocê pode distribuí-lo agora ou mais tarde.",
"Gostaria de saber como ganhar mais pontos de habilidade.",
"Posso obter uma descrição das diferentes habilidades?",
"Esqueça esses pontos de habilidade, vamos continuar com outra coisa.",
"Se quiser fazer isso agora, abra a 'Tela do Personagem' (F2), selecione a habilidade desejada e pressione a tecla 'Ação' para aumentar seu valor\nPara obter uma Habilidade você deve selecionar o ícone de Habilidade na parte inferior da tela. tela e pressione a tecla 'Ação'. Então você verá uma lista de todas as habilidades. Selecione aquela que deseja aprender e pressione a tecla 'Ação' novamente para ler a descrição da habilidade. Para aprender uma habilidade, pressione a tecla 'Ação' uma terceira vez\nAlgumas habilidades não podem ser aprendidas até que você tenha aprendido seus pré-requisitos.",
"Farei isso agora.",
"Esqueça esses pontos, vamos continuar com outra coisa.",
"Fale comigo quando terminar e continuaremos.",
"Claro. Qual é do seu interesse?",
"Liderança.",
"Corpo a corpo.",
"Navegação.",
"Precisão.",
"canhões.",
"Lutando.",
"Reparar.",
"Defesa.",
"Comércio.",
"Sorte.",
"Você pode melhorar a liderança conversando com as pessoas nas cidades, completando missões e pagando sua tripulação regularmente.",
"Obrigado. E quanto aos outros?",
"É o bastante. Conte-me sobre outra coisa.",
"Para melhorar sua habilidade corpo a corpo você obviamente deve praticar bastante com sua lâmina, apenas tome cuidado para não ferir espectadores inocentes!",
"Você melhorará sua habilidade de navegação quanto mais navegar ativamente em seu navio. Aqui, tempestades e tornados também podem ajudar a melhorar sua experiência, embora certamente também danifiquem seu navio.",
"Ao disparar sua pistola ou canhões, você pode ganhar pontos em Precisão. Usar uma pistola é mais eficaz.",
"Para progredir nos canhões, você precisa lutar e atingir outros navios ou fortes durante as batalhas.",
"Você ficará melhor no Grappling toda vez que lançar um gancho.",
"Observe como o construtor naval conserta seus navios e você ganhará experiência em Reparos. Quando você começar a consertar seu navio durante batalhas navais, você também obterá o mesmo efeito.",
"Tornar-se um mestre da Defesa requer experiência em bloquear durante lutas de espadas e consertar navios no estaleiro ou durante uma batalha naval.",
"Se você lida frequentemente com comerciantes, poderá melhorar rapidamente suas habilidades em comércio. Quando o seu comércio estiver baixo, os comerciantes irão tosquiá-lo; quando estiver alto você fará isso com eles!",
"A sorte melhorará quando você jogar cartas em tavernas. Além disso, você irá melhorá-lo ao terminar missões e ao conversar com pessoas encontradas; mas cuidado, capitão, quando sua sorte estiver baixa, alguns deles podem tentar roubar seus pertences.",
"Precisa de alguns conselhos sobre como distribuir seus pontos de habilidade? Coloque alguns em Combate Corpo a Corpo e alguns em Liderança para começar, ou talvez Comércio para quando vendermos nossa carga?\nMas não há pressa com isso, você sempre pode fazer isso em seu próprio tempo mais tarde, conforme a necessidade.",
"Essa habilidade permite que você controle melhor seu pessoal. Se você tiver uma vontade forte, será menos provável que sua tripulação se renda em uma luta. Também vendo você tão confiante e forte, seus inimigos ficarão desmoralizados e poderão se render mais cedo. Esta habilidade é muito útil para o capitão de um navio à vela nessas águas.",
"Acho que vou distribuir meus pontos agora.",
"O dano que você inflige em uma luta com sua lâmina depende dessa habilidade. Também afeta a chance de perfurar blocos inimigos e bloquear ataques inimigos com sucesso.",
"Esta habilidade mostra o quão bom você é em navegar em seu navio. Se esta habilidade for alta, seu navio será mais rápido e ágil.",
"Uma boa mira pode ajudá-lo a vencer uma batalha naval, mesmo contra um inimigo esmagador. Esta habilidade representa a precisão com que seus artilheiros podem disparar bombas e bolas. Lembre-se de que atirar manualmente do convés sempre proporciona melhor precisão.",
"Esta habilidade está relacionada à Precisão e também é importante para batalhas navais. Quanto maior for essa habilidade, mais rápido sua tripulação recarregará os canhões e mais rápido eles dispararão uma salva.",
"Esta habilidade é muito útil para qualquer pirata ou corsário. Ele permite que você lance ganchos de embarque com precisão para pegar um navio inimigo e tentar pegá-lo com seu grupo de embarque.",
"Esta habilidade permite que você conserte seu navio em mar aberto. Quanto maior a habilidade, maior será a porcentagem de dano que você pode reparar. Além disso, você precisará ter algumas pranchas e lonas a bordo de seu navio para realizar qualquer trabalho de reparo.",
"A tripulação é a parte mais frágil e a mais importante do navio. Sem tripulação suficiente, qualquer navio torna-se incontrolável e desajeitado. A habilidade de defesa ajuda a proteger sua tripulação do fogo dos canhões inimigos. Também diminui as perdas de tripulação em batalhas navais.",
"A habilidade Comércio é essencial para comerciantes e comerciantes. Com um comércio alto você consegue preços melhores nas lojas e às vezes pode até conseguir desconto na contratação de um oficial.",
"Bem, estas ilhas são apenas parcialmente civilizadas. As autoridades ainda estão fracas e muitos aventureiros e criminosos vêm aqui para tirar vantagem disso. Portanto, as ruas e tabernas estão cheias de ladrões, contrabandistas, jogadores e assassinos, e você deve ser esperto se quiser lidar com esses tipos e evitar armadilhas e armadilhas. Quer você jogue, lute, contrabandeie ou roube, se tiver muita sorte, terá mais sucesso, sofrerá menos danos e obterá ganhos maiores!",
"Agora devo lembrá-lo sobre o negócio que você precisa cuidar.",
"Prossiga.",
"Em primeiro lugar, há carga para vender, você deve vendê-la no comerciante local aqui, o que não deve ser muito difícil de encontrar.\nAlém disso, o navio sofreu alguns danos na última batalha e precisa ser reparado. O estaleiro local deverá cuidar facilmente dos reparos.\nEm seguida, você precisará contratar novos tripulantes para substituir os que partirão. Converse com o taverneiro local sobre a contratação de mais tripulantes e lembre-se de que você sempre pode pedir informações às pessoas.",
"Isso é tudo?",
"Quase. Sua luneta parece velha e arranhada, não lhe dará a vantagem que você precisa nessas águas perigosas. Talvez você possa comprar um novo? Deve estar disponível para venda em algum lugar da cidade.",
"Mais uma coisa, estas águas estão cheias de navios da Marinha Real, talvez você queira hastear a bandeira inglesa ao sair do porto. Você pode alterar sua bandeira acessando a 'Tela de Personagem' (F2) e depois a tela de 'relações'. Ao hastear a bandeira inglesa, você pode enganar o forte e passar furtivamente por eles, se a sorte estiver do seu lado!",
"Vamos.",
"Se você quiser comprar uma nova luneta, pode fazê-lo agora mesmo. Vejo alguns comerciantes debaixo das suas tendas.",
"Tudo bem, vamos lá.",
"Posso fazer isso mais tarde. Vamos continuar com outra coisa.",
"Você pode ir. Vou encontrar o meu caminho.",
"Precisamos nos mudar para o centro da cidade. Devemos ir até os portões de entrada e depois passar pela próxima porta para a outra parte da cidade. Siga-me até os portões e quando vir o ícone 'Abrir cadeado' no canto superior esquerdo da tela, pressione a tecla 'Ação' para ir para o próximo local.",
"O assentamento pirata está localizado longe da costa, no meio da selva. Para chegar lá, devemos passar por trás daquelas pedras e depois virar à esquerda perto de uma cabana. Mais tarde veremos a paliçada. Aproxime-se do portão de madeira atrás de mim e quando você ver o ícone 'Abrir cadeado' no canto superior esquerdo da tela, pressione a tecla 'Ação' para ir para o próximo local.",
"Não há sequer um comerciante ambulante aqui! Felizmente, descobri que poderíamos comprar uma luneta na loja local. Iremos lá vender nossa carga e ver se eles têm uma luneta nova.",
"Como quiser. Me siga.",
"...",
"Fale com um daqueles homens sob as tendas. Eles estão vendendo produtos diferentes. Você deve poder comprar uma nova luneta deles. Pergunte a eles o que eles têm a oferecer. Você verá 4 categorias no topo da tela, 'Arma', 'Medicamentos', 'Itens' e 'Mapas'. Em cada categoria você verá uma lista de 'Itens', basta clicar no item que você precisa, escolher quantos deseja e clicar em 'OK' para fazer a compra, então pronto, você estará pronto para começar.",
"Você conseguiu. Ótimo. Agora vamos vender as mercadorias que trouxemos para a ilha.",
"Tudo bem. Onde podemos fazer isso?",
"Vou fazer isso sozinho. Volte para o navio.",
"Ei, onde está aquela nova luneta? Eu não vejo isso!",
"Vou comprar agora.",
"Decidi não comprar agora. Vamos continuar.",
"Vou continuar sozinho Robert.",
"Como você diz. Agora vamos vender as mercadorias que trouxemos para a ilha.",
"A loja de comércio local fica no distrito mais distante. Eu vou te guiar até lá.",
"A loja de comércio local deve estar dentro das muralhas da cidade. Siga-me até os portões e quando vir o ícone 'Abrir cadeado' no canto superior esquerdo da tela, pressione a tecla 'Ação' para ir para o próximo local.",
"Eu sei onde fica a loja e você tem algumas mercadorias a bordo que deveria vender para conseguir dinheiro para pagar os reparos do navio e o reabastecimento da tripulação. Para ver quais mercadorias você tem a bordo, você deve pressionar a tecla 'Tela de Personagem' (F2) e selecionar 'Cargo Hold'. Em seguida, escolha um navio dentre aqueles disponíveis para visualização. Você verá uma lista de mercadorias que seu navio possui a bordo. Você pode rolar para a direita ou para a esquerda. Você também pode ver a quantidade de munição que resta em seu navio.",
"Obrigado pela informação. Devemos ir agora?",
"Não preciso mais da sua ajuda.",
"Me siga. Vou lhe mostrar a porta certa e então você estará sozinho. Mas se você tiver alguma dúvida, é só me perguntar.",
"Agora vá falar com o comerciante. Venda o seu ",
" e ",
" Para conseguir uma luneta, diga ao comerciante que você deseja comprar alguns equipamentos pessoais e que ele deve ter uma à venda. Depois disso você deverá vender nossa carga, que é ",
" mas não compre nada, precisamos de dinheiro para consertar nosso navio e contratar mais tripulação. Você precisa de mais detalhes sobre negociação?",
". Podemos usar o dinheiro adquirido no comércio para contratar tripulação e consertar o navio. Precisa de mais esclarecimentos?",
"Sim, isso seria útil.",
"Não, eu posso lidar com isso.",
"É muito simples. Fale com o comerciante e diga-lhe que deseja negociar mercadorias de carga. Em seguida, selecione um navio que será usado para negociação. Depois disso, você verá uma lista de mercadorias. Selecione um produto que deseja vender ou comprar e pressione a tecla 'Ação'. Em seguida, selecione o botão 'Comprar' ou 'Vender' e escolha a quantidade desejada que deseja comprar ou vender. Em seguida, pressione a tecla 'Ação' novamente para confirmar a transação.",
"Obrigada pelo esclarecimento.",
"Te espero do lado de fora da loja. A propósito, se você ainda não atribuiu seus pontos de habilidade, você pode colocá-los em sua habilidade Comércio para obter mais lucro com suas transações.",
"Te espero do lado de fora da loja. Lembre-se de que lidar muito com comerciantes o ajudará a aumentar sua habilidade de 'Comércio', dando-lhe a oportunidade de conseguir um acordo melhor com eles.",
"Tudo bem, obrigado.",
"Você deve vender todos os produtos que possui. Mas está tudo bem por enquanto. A seguir mostrarei como você pode contratar tripulação para seu navio. Isso pode ser feito em uma taverna.",
"Multar.",
"Eu mesmo vou encontrar. Você está livre para ir.",
"Agora que temos dinheiro, podemos contratar uma equipe extra. Para isso vamos à taberna.",
"Me siga. Vou te levar até a taverna.",
"Estou bem atrás de você.",
"Sim. Aqui você pode contratar tripulação. Além disso, às vezes você pode encontrar um bom oficial para o seu navio em uma taverna, conversar com as pessoas e talvez tenha sorte. Para recrutar uma nova tripulação, fale com o taverneiro, ele está no bar, e pergunte sobre o reabastecimento da tripulação. Em seguida, selecione um navio ao qual atribuir a tripulação e selecione o botão 'Contratar'. Depois disso, selecione quantos marinheiros você deseja. Preste atenção ao moral da tripulação, no entanto. Em seguida, pressione a tecla 'Ação' para pagar seu ouro e contratar esses marinheiros.",
"Às vezes acontece que não há tripulação livre em uma ilha... Isso é lamentável, mas você terá que navegar para outra ilha para contratar tripulação\nAgora contrate alguma tripulação. Te espero lá fora",
"Eu estarei lá em breve..",
"Estamos bem. Tudo que você precisa fazer agora é consertar o navio. Enquanto você contratava tripulação, fui e encontrei o estaleiro local.",
"Bom. Vamos lá.",
"Eu sei onde é. Você pode retornar ao navio.",
"Desculpe, mas é melhor contratar o máximo de tripulação possível. Sua nave deve estar sempre sob seu controle total. Mas, como você sempre pode fazer isso mais tarde, podemos consertar nossa nave agora. Encontrei o estaleiro local.",
"Sim, sim! Me siga.",
"Ir.",
"Estamos agora no estaleiro. Aqui você pode consertar sua nave, atualizá-la, vendê-la ou comprar outra. Além disso, em um estaleiro você pode instalar diferentes canhões em seu navio. Você quer que eu lhe dê instruções sobre como consertar seu navio?",
"Sim diz-me.",
"Não, eu posso lidar com isso.",
"Tudo bem. Fale com o construtor naval e peça-lhe para verificar o seu navio. Então escolha um navio que precisa ser consertado, você só tem um no momento. Em seguida, selecione 'Reparar'. Se você tiver dinheiro suficiente, basta pressionar a tecla 'Ação' depois de destacar o botão 'Consertar tudo' e seu navio estará totalmente reparado. Caso contrário, você terá que selecionar uma porcentagem do casco e do cordame a ser reparado. Selecione Casco e defina o valor desejado. Então faça o mesmo com Sails. Em seguida, selecione 'Ok' e pressione a tecla 'Ação' para confirmar os reparos.",
"Ótimo, obrigado.",
"Bem, se for assim, esperarei por você lá fora.",
"Eu acho que isso é tudo. Posso lhe dar algumas sugestões sobre o que fazer, se quiser. De minha parte, estou farto da vida no mar. Perdi uma mão, uma perna e ontem quase perdi a pele. Vou me aposentar aqui, bem, vou me retirar para a taverna! Meus dias são para beber e jogar. Sr. Sullivan e os outros irão atendê-lo bem.",
"Eu acho que isso é tudo. Posso lhe dar algumas sugestões sobre o que fazer se você quiser\nTudo o que sonho é passar minha vida na aposentadoria, navegando pelos mares apenas para relaxar e talvez um pouco de lucro pessoal, aqui e ali. Veja, estou no mar desde que era menino e agora é hora de deixar tudo isso para trás e aproveitar a taberna local!",
"Obrigado por toda sua ajuda Robert.",
"Se você precisar contratar novos oficiais, você os encontrará para contratar na Taverna, e ficarei feliz em ajudá-lo com meus conselhos sempre que você passar por aqui.",
"Você pode me dar algumas sugestões sobre o que fazer a seguir?",
"Conte-me sobre navegar no meu navio.",
"Conte-me sobre disparar canhões.",
"Conte-me sobre embarcar em navios inimigos.",
"Conte-me sobre como pagar meus oficiais e tripulação.",
"Conte-me sobre 'Navegação Direta'.",
"Conte-me sobre a tripulação 'Moral'.",
"Conte-me sobre levantar 'Bandeiras'.",
"Obrigado pela ajuda. Adeus!",
" na colônia de ",
"Bem, da última vez que estive na loja, percebi que eles têm preços bem baixos para ",
". Se eu fosse você, compraria aqui e navegaria para ",
"- você pode conseguir um bom preço por ",
" lá. Você também obterá um grande lucro por ",
"Infelizmente não posso ajudá-lo, capitão.",
"Tudo bem. Mas antes de você ir, devo lembrá-lo de quais negócios você iria tratar enquanto estivesse em terra.",
"Quase. Sua luneta está velha e arranhada. Você deveria comprar um novo. Deve estar disponível para venda em algum lugar da cidade.",
"E mais uma coisa: o aspirante Percy foi leal ao capitão e correu para terra assim que chegamos. Sem dúvida a guarnição do forte está aprendendo o que aconteceu agora mesmo. Aconselho você a pilotar a Union Jack quando sair deste porto .", // KK
"...Se precisar da minha ajuda novamente, estarei na taverna local.",
"Obrigado. Até a próxima.",
"Como quiser. Posso lhe dar algumas sugestões sobre o que fazer se quiser, mas agora devo deixar você \n. Estou cansado da vida no mar. Perdi uma mão, uma perna e ontem quase perdi a pele. Vou me aposentar aqui, bem, vou me retirar para a taverna! Meus dias são para beber e jogar. Sr. Sullivan e os outros irão atendê-lo bem.",
"Você pode me dar algumas sugestões sobre o que fazer a seguir?",
"Bem, dirigir um navio não é tão difícil quanto pode parecer. Os navios se movem com o vento. Quanto mais forte o vento sopra, mais rápido o navio avança. Você pode colocar suas velas em duas posições; Cheio e Batalha, ou ataque-os completamente\nEm posição de batalha, o navio se torna mais manobrável, mas a velocidade máxima é reduzida. Com Full Sails, seu navio se move mais rápido, mas vira mais devagar. Fique sempre de olho no vento, seu navio não irá muito rápido se você estiver navegando contra ele.",
"Disparar no modo de terceira pessoa é simples, basta manter os inimigos dentro do alcance de tiro de seus canhões e pressionar o botão 'Disparar' quando seus canhões estiverem carregados. Seus canhoneiros apontarão automaticamente os canhões para o seu inimigo\nEsteja ciente de que durante o modo de primeira pessoa, você pode usar o disparo 'manual', bem como o disparo automático, mas tenha cuidado se usar o disparo 'manual', independentemente de você mire em um navio amigo ou não, ele atirará nele\nAtirar manualmente do convés é um pouco complicado. Você deve apontar seus canhões para os navios inimigos, mas não como faz com uma pistola ou um mosquete. Não se esqueça que os canhões disparam em trajetória balística e você deve levantar o cursor de mira mais alto se o inimigo estiver longe de você\nOu baixá-lo se o inimigo estiver próximo. Você pode até fazer um tiro direto, mas somente se o seu inimigo estiver muito próximo de você.",
"Para embarcar em um navio inimigo você deve chegar bem perto dele. A velocidade relativa dela e sua também devem ser próximas, a menos que você tenha a habilidade especial ou alta habilidade de Grappling.\nEntão você precisa abrir o 'Menu de Comando Rápido' e selecionar o comando de Embarque. Então você terá que abrir caminho através do convés do navio inimigo com sua tripulação, cortando e matando os marinheiros adversários, saqueando conforme você avança!\nDepois de vencer a batalha de embarque, você pode saquear todos os bens daquele navio ou levá-lo com você se tiver um oficial adequado para designar como capitão do navio capturado.",
"Existem duas maneiras de pagar sua tripulação. Você pode pagá-los com 'Salário' ou 'Assinatura de Artigos' com eles. Esteja ciente de que alguns membros de sua tripulação podem desertar se você tiver baixa liderança ao alternar entre 'Salário' e 'Dividir o saque'.",
"Conte-me sobre o pagamento de 'Salário'.",
"Conte-me sobre 'Assinatura de artigos'.",
"Se você estiver pagando salário, no dia 8 de cada mês aparecerá a janela salarial perguntando se você deseja pagar sua tripulação. Se você decidir não pagar, o moral da tripulação diminuirá. Ele cairá menos se você tiver o privilégio 'Vontade de Ferro'. Se o moral da tripulação ficar baixo o suficiente, eles se amotinarão, e isso é algo que você não quer. O moral ficará mais estável, mas não tão alto como se você tivesse assinado artigos.",
"Para 'assinar artigos' com sua tripulação e oficiais, você deve estar disposto a dividir seu saque. Você pode assinar o artigo usando a 'Tela de Personagem' (F2), indo em 'Navio' e clicando no ícone 'Tripulação', você também pode falar com qualquer membro da tripulação a bordo de seu navio ou com qualquer 'Agiota'. ' quando em terra. Quando você quiser dividir seu saque, volte até o 'Loan Shark' e diga a ele que você quer dividir seu saque, então ele explicará o que fazer.\nAo fazer isso, você terá que dividir seu saque para pagar sua tripulação e mantê-los felizes. Ao dividir o seu saque, você poderá aumentar ainda mais o seu moral (do que com a opção 'Salário'), mas será mais difícil manter o controle. Digamos que se você é ganancioso e ganha muito dinheiro e não o compartilha com sua tripulação, será mais difícil para você manter o moral deles alto; um capitão muito ganancioso sempre consegue uma tripulação rebelde.",
"'Direct Sailing' é simples se você tiver o equipamento correto e um bom senso de orientação. O significado de 'Navegação Direta' é que agora você pode navegar de uma ilha para outra, enquanto estiver na visualização 'Navegação 3D'. Não há mais necessidade de voltar ao mapa mundial para navegar de ilha em ilha\nNo entanto, usar o mapa mundial será mais rápido do que 'Navegação 3D', MAS 'Navegação Direta' lhe dá a oportunidade de apreciar a vista enquanto você navega diretamente de ilha em ilha ilha. Você pode encontrar alguma carga flutuante ou tesouro ao longo do caminho, ou até mesmo encontrar outros navios\nSem uma bússola é difícil se orientar, a menos que você seja um velho marinheiro experiente como eu. Observe que cada hora que você gasta em '3D Sailing' adicionará um dia à sua jornada. Se você achar que o tempo de viagem é muito longo, você pode usar a tecla 'Aceleração' para avançar o tempo mais rapidamente.",
"O 'Moral' da sua tripulação é muito importante. Com um 'Moral' alto, sua tripulação terá um desempenho muito bom, com um Moral baixo, o desempenho de sua tripulação será baixo e você estará sujeito a um possível 'Motim', se você deixar seu 'Moral' cair muito baixo\nExistem alguns maneiras de manter seu moral alto, lutando e vencendo, mantendo alto o status de sua comida e rum, pagar sua tripulação com 'Salário' lhe dará uma boa média em 'Moral', 'Assinar Artigos' aumentará seu Moral mais alto então 'Salário', mas é mais difícil mantê-lo assim\nVocê também pode aumentar o moral dobrando as rações de rum. Há uma chance de uma briga de bêbados!\nSeu 'moral' cairá se você se recusar a pagar sua tripulação, perder muitas lutas, diminuir a ração de comida e rum, ficar sem comida ou rum durante a viagem, contratar mais tripulação na taverna, tendo muito dinheiro para a tripulação consigo (melhor colocar algum no armário de armas do navio) e contratando nova tripulação a partir da captura de um navio inimigo.",
"A bandeira pode ser útil quando usada corretamente. Também representa diferentes nações como; 'Inglaterra', 'França', 'Holanda', 'Espanha', 'Portugal', 'Pirata' e suas 'Cores Pessoais' (sua bandeira). Se você mudar a bandeira de uma nação para outra, isso pode ser muito útil. Digamos que seu inimigo seja a 'França' e que você tenha que atracar em um 'porto francês', mudar para a bandeira 'francesa' irá ajudá-lo a entrar naquele porto sem suspeitas\nEu recomendo que se você hastear outra bandeira porque você tem para entrar num 'Porto Hostil', faça-o antes de avistar a 'Ilha'. Você não quer que os guardas que guardam a 'Cidade' ou o 'Forte' vejam você trocando a 'Bandeira', não é! Esteja ciente da sua 'fama', quanto mais famoso você for, mais difícil será entrar furtivamente. Ser popular tem seus lados bons e ruins, eu acho\nVocê também pode fingir que é um navio 'francês' navegando com a bandeira 'francesa' e procure um alvo 'francês' em potencial e, quando chegar perto dele, levante a 'bandeira' apropriada e enfrente seu inimigo.",
"Até mais, capitão. Espero que você se saia bem no Caribe.",
"Coisa certa. Espero que você esteja feliz em terra firme.",
"Precisa do meu conselho, capitão?",
"Liguei para você porque, como você já deve saber, pretendo deixar essa vida de cachorro-do-mar e me aposentar naquela ilha. Portanto, como compreendo e apoio perfeitamente as suas aspirações, decidi conceder-lhe um navio próprio. Assuma o comando disso ",
" que capturamos recentemente. Eu não preciso dela e até liguei para ela '",
"'para te alegrar.",
"Oh querido... não ESSE navio! Eu esperava obter o comando do seu ",
"Excelente, exatamente o que precisamos para sair do porto sem sermos notados. Tenho certeza de que a tempestade que está chegando não será tão ruim, então vou embora! Boa sorte em se estabelecer.",
"O que você disse? Eu não ouvi.",
"Obrigado, muito obrigado... Cuidarei deste barco como se fosse feito pelas minhas próprias mãos!",
"Robert, gostaria de agradecer por tudo e desejar sorte em terra firme. Agora eu gostaria de visitar a cidade.",
"Para começar melhor, você pode tirar coisas daquele baú, você encontrará armas e uma luneta lá. Você também pode escolher o resto, até mesmo o dinheiro que encontrar lá. Ah, e seu guarda-roupa também foi transferido para cá, caso você queira trocá-lo.",
"Você pode ir para a cidade se desejar; Tenho algumas coisas para fazer aqui. Nos encontraremos na taberna local.",
"Parabéns pela sua promoção, ",
". Você é obrigado e instruído a comandar o navio designado a você e a afundar, queimar ou tomar como prêmio todos os navios inimigos que puder.",
"Sim, sim, senhor!",
"Qualquer navio premiado que você capturar será levado ao porto e leiloado. Você receberá uma parte do dinheiro, assim como seus oficiais e tripulação. Você não tem permissão para renunciar ao comando de seu próprio navio em nenhuma circunstância. Você entende?",
"Sim senhor. Eu entendo.",
"Muito bom. Então que bons ventos e boa sorte naveguem com você ",
"Obrigado, senhor. Partirei assim que chegar ao porto.",
"Capitão, tem certeza que quer fazer isso? Você sabe que o que você fez não foi totalmente honroso.",
"A senhora sabia o que estava fazendo. Se o irmão dela não consegue lidar com isso, então ele pode lidar comigo!",
"Capitão, embora estejamos felizes em servir sob seu comando, não temos má vontade em relação ao nosso comandante anterior. Ele é apenas um homem azarado.",
"Ele me acusou de trapacear! Como ele ousa fazer uma coisa dessas? Vou fazê-lo pagar por isso.",
"Você está, por meio deste, ordenado a se disfarçar nesta cidade hostil e criar o máximo de problemas possível para nossos inimigos. Será perigoso e não espero que nos vejamos novamente.",
"Entendido, senhor. De agora em diante, estarei sozinho.",
"Capitão, tivemos sorte de ter chegado a este porto amigo durante aquela tempestade horrível! O navio sofreu danos substanciais e perdemos muitos tripulantes.",
"Será caro preparar-nos para zarpar novamente. Infelizmente, não temos meios honestos para fazer isso nesta ilha. Precisamos arriscar e ver se conseguimos encontrar um agente de contrabando na taverna.",
"Capitão, tem certeza de que não pode ser convencido a fazer o trabalho que deveríamos fazer? Até que esta maldição seja levantada, nunca poderemos desembarcar! E todo esse visual de peixe também não é tão bom.",
"Transportar as almas perdidas que morreram no mar pela deusa do mar? Nunca! Fui traído e o mundo conhecerá minha ira! Nenhum navio no mar está a salvo de mim.",
"Capitão, todas as moedas que encontramos foram guardadas no armário de armas, conforme você ordenou. Mas parece que faltam alguns, senhor! Um dos tripulantes deve tê-los levado.",
"É assim mesmo? Antes que percebamos, eles estarão espalhados por todo o Caribe e teremos dificuldade em recuperá-los! Irei desembarcar imediatamente para iniciar a busca.",
"Não posso acreditar que o forte #sTortuga# não atirou em nós quando chegávamos ao porto!",
"Não havia nada com que se preocupar. O governador francês aqui é realmente muito indulgente com todos aqueles que arvoram uma bandeira pirata. Você faria bem em lembrar disso!",
"Não havia nada com que se preocupar. A França governa aqui e estamos em paz com a França.",
"Lamento que o movimento do navio esteja deixando você enjoado, mas não temos alojamentos diferentes disponíveis para você. Agora, por favor, saia da minha cabine.",
"Muito bem, então. Vamos apenas esperar que eu não caia no mar nesta tempestade. Você pode ter muitos problemas com seu empregador se perder um de seus passageiros!",
"O cavalheiro sabia o que estava fazendo. Se o irmão dele não consegue lidar com isso, então ele pode lidar comigo!",
"É verdade. Tentaremos sair sem mais problemas. Navegue imediatamente!",
"Boa noite, #schild#.",
"Você... Fique longe de mim!",
"Um pouco tarde para isso. Lindo navio, não é?",
"Por quê você está aqui?",
"Ah, mas eu nunca estive longe ",
" Estive ao seu lado, mesmo no fim do mundo.",
"Foi você... quem me manteve vivo.",
"Não não não, ",
" Estas são as almas a bordo deste navio. Em cada uma de suas batalhas você as colhe, elas obedecem a sua vontade e te protegem. Como eu ordeno. Isso me deixa muito orgulhoso. Os gritos, o cheiro de pólvora e sangue. É como quando você faz um investimento que continua crescendo até o dia em que é realizado. E esse dia chegou, ",
",",
" semear os mortos em seu caminho e estender minha influência neste mundo.",
"Faça Você Mesmo.",
"Não funciona assim. Você está sob contrato, lembra? Um dia, você me verá reaparecer reivindicando as almas a bordo e talvez sua alma seja devolvida para você. Até lá, nunca estarei longe. Vou ficar de olho.",
"Isso está fora de questão.",
"Você não tem escolha. Esqueça sua antiga vida... você é meu ",
".",
" A morte é apenas o começo.",
"Não exatamente sozinho. Procure uma pessoa chamada ",
". ",
" nome verdadeiro é ",
" e ",
" é outro dos nossos agentes que tem trabalhado aqui. ",
" lhe dará mais instruções. Comece procurando na taverna. Se lhe perguntarem sobre o estado do seu navio, diga que ele estava infestado de cupins, mas você se livrou deles e reparou os danos.",
"Muito bem, senhor.",
"Bem, acho que você aprendeu o suficiente para ganhar seu sustento. Veja o que você pode fazer com o ",
".",
"Aquela banheira velha? Bem, suponho que não posso esperar um navio grande na minha primeira viagem. Adeus, mãe.",
"Obrigado por confiar este navio a mim, mãe. Eu não vou te decepcionar.",
"Tenha muito cuidado, jovem Turner. Sempre detestei o mar por uma razão. Eu treinei você bem como ferreiro, mas você não tem experiência como marinheiro, muito menos como capitão...",
"Não se preocupe, Mestre John. Sempre senti o chamado do mar - talvez esteja no meu sangue. Agora, me despeço de você. Prometo uma visita ao ferreiro de vez em quando.",
"O templo acabou de ser concluído, mestre. Aguardamos seus pedidos.",
"Bom. Atracar o navio na baía, preciso colocar meus estudos em dia antes de partirmos para o mar.",
"Capitão, a tripulação está se perguntando o que você planeja fazer agora que Davy Jones está morto e você assumiu o controle do 'Holandês Voador'.",
"No devido tempo, precisaremos cumprir nosso dever para com as almas dos mortos. Mas primeiro precisamos ganhar experiência com o navio. Ela não é mais como era quando foi amaldiçoada.",
"Capitão, encontramos esta baía isolada que podemos configurar como nossa base de operações.",
"Perfeito. Agora ancore o navio. Eu gostaria de fazer uma pesquisa sobre isso.",
"Capitão, agora que chegamos ao Caribe, a tripulação está se perguntando quais são suas intenções. Devemos continuar a servir a Espanha?",
"Manteremos as nossas opções em aberto. Não desistiremos do nosso serviço à Espanha. Mas não antagonizamos os piratas aqui e não o faremos.",
"Não, terminei com a Espanha. Somos piratas agora. Hasteie a bandeira negra!",
"Que tipo de pergunta é essa? Fomos leais à Espanha e continuaremos leais! Agora saia!",
"Posso dizer que adorei aquela perseguição! Aquele capitão se considerava um assassino de piratas? Ele nem consegue escolher um navio com os mastros certos! Então...quando é a nossa próxima viagem?",
"Em vez disso, fique grato por termos pegado o navio certo. Não fique muito animado",
"; Você tem muito a aprender. Este é um negócio mortal. Agora, tenho que ancorar aqui. Tenho algumas coisas para resolver primeiro.",
"Chegamos ao porto, #ssir#.",
"Bom. Vamos ancorar aqui e nos preparar para nossa próxima viagem.",
"Agora que tiramos o resto da tripulação do caminho, vamos para o barco. Precisaremos jogar nossas armas ao mar antes de partirmos, elas só vão deixar o barco mais pesado.",
"Obrigado novamente por me libertar. Quanto às armas, podemos encontrar algo depois de chegarmos à costa.",
"Purpure, finalmente chegamos ao Novo Mundo. É uma terra de oportunidades e estou ansioso para ouvir de você novamente. Infelizmente, não posso mais acompanhá-lo depois disso. Estou envelhecendo.",
"Sentirei muita falta de você, tio! Cuide-se quando voltar para a Inglaterra.",
"Querido tio, aconteceu alguma coisa?",
"Sim, Purpura. O vento está ficando mais forte e temo que uma tempestade esteja a caminho.",
"Acho que vou ficar bem, tio. Não se preocupe comigo. Posso virar uma nova página longe do meu pai, pelo menos.",
}
