string DLG_TEXT[47] = {
"Bom dia, ",
". Você tem algo a relatar?",
"Bom Dia senhor. Nada a relatar, senhor.",
"Ah, ",
", é bom ver você novamente.",
"Parabéns pela sua promoção para ",
"Obrigado, senhor.",
"Por que você ainda esta aqui? Você conhece o seu dever - cumpra-o!",
"Er, sim, senhor.",
"Tenho ordens para você. Você deve pegar uma remessa de mosquetes e munições e entregá-los a um rebelde chamado ",
". Ele assumiu o forte em Playa de Sabana.",
"Conheço aquele forte, senhor. Nós explodimos tudo para evitar que um bando de rebeldes assumisse o controle. Se me permite perguntar, senhor, por que os estamos ajudando agora?",
" está lutando contra os espanhóis, que são nossos inimigos. O velho ditado 'O inimigo do meu inimigo é meu amigo' se aplica. Aparentemente ",
" reparou o forte. E eu aconselharia você a não mencionar sua parte na destruição. Ele é conhecido por ser um homem de temperamento violento.",
"Se me permite perguntar, senhor, por que estamos ajudando um bando de rebeldes?",
" está lutando contra os espanhóis, que são nossos inimigos. O velho ditado 'O inimigo do meu inimigo é meu amigo' se aplica. Mas tenha cuidado ao lidar com ",
" já que ele é conhecido por ser um homem de temperamento violento.",
"Entendo, senhor. Esperançosamente, esse temperamento será desabafado sobre os espanhóis.",
"Essa é a ideia geral, sim. Agora, as armas já estão sendo carregadas em sua nave. Termine de abastecê-la e navegue para Playa de Sabana o mais rápido possível.",
"Sim senhor.",
"Essa é a ideia geral, sim. Mas fui informado que o seu navio já está muito carregado. Libere algum espaço em seu porão e volte aqui. Então ordenarei que a munição seja carregada a bordo do ",
"Sim senhor. Vou à loja agora.",
"Você ainda não tem espaço suficiente para o pó que vai levar. Libere mais espaço, ",
"Muito bom, ",
". Já dei ordens para que a munição fosse transferida para o ",
". Você deve partir para Playa de Sabana o mais rápido possível.",
"Muito bem, senhor. Partirei para Playa de Sabana assim que estiver a bordo do ",
"Que pena se aquele seu relatório não parecesse um romance ",
"! Não consegui largar!",
"Você conhece todo mundo? Leighton, Elliot, Boulton, Keene?",
"Eu conheço o suficiente deles, de qualquer maneira.",
"Bem, ",
", depois daquele cruzeiro, você pode não achar tão emocionante comandar um navio de linha.",
"Um navio de linha, senhor?",
"Estamos lhe dando 74. Um francês que capturamos e rebatizamos de 'Sutherland'. '",
"a tripulação será transferida para ela.",
"Estou extremamente grato, senhor.",
"Você será anexado ao esquadrão de Leighton.",
"Agora, senhores, a maldita guerra. Acho que Napoleão mordeu mais do que pode mastigar no Caribe. Temos uma excelente oportunidade de derrotá-lo e trazer a vitória à Grã-Bretanha, se conseguirmos manter a nossa superioridade naval aqui. Mas nem um único navio francês deve entrar nestas águas. Isso é com você.\n",
"Assim como nossas frotas entram no Caribe em #sSt John's# em #sisland_Antigua#, as frotas francesas chegam em #sMarigot# em #sisland_Saint Martin#. E é aí que você irá detê-los. Você deverá navegar para #sisland_Saint Martin#. Se você chegar lá primeiro, interceptará a frota francesa enquanto ela ainda está exausta após cruzar o Atlântico. Se já chegou, você irá engarrafá-lo em #sMarigot#.\nCapitão ",
", você já navegou nesta área antes sob meu comando, então está familiarizado com os mares. Você guiará o esquadrão, por favor.",
"Mas primeiro, descarte seus navios premiados e depois apresente-os aqui. Quaisquer navios que você ainda tenha serão atribuídos a Leighton.",
"Sim senhor. Irei para o estaleiro agora.",
"Ah, bem-vindo de volta ",
". Presumo que agora você está pronto para se juntar ao esquadrão de Leighton?",
"Sim senhor.",
"Muito bem, senhor.",
}
