string DLG_TEXT[22] = {
"Meu nome é Ammand... o Corsário!",
"Capitão Jack Sparrow.",
"Olá capitão, meu nome é Ammand, o Corsário. Eu sou o Senhor Pirata do Mar Negro, e você é?",
"Capitão Jack Sparrow.",
"Capitão Jack Sparrow, Senhor Pirata do Caribe. Inteligente?",
"Acredito que você foi enviado pela igreja para descobrir se o padre Jerald é culpado. Estou correcto?",
"Sim, isso está correto, Ammand.",
"Tenho informações que me dizem que seu assistente, Gilbert Ballester, tem cartas que mostram que ele é culpado...",
"Obrigado pela informação.",
"Ainda não terminei, capitão Sparrow. Podemos usar esta informação para chantageá-lo para que nos dê dinheiro pelas cartas. Me siga!",
"Uma oferta muito interessante. Vou pensar nisso enquanto vamos à igreja.",
"Capitão, vista essas vestes. Será mais fácil para você ganhar a confiança do Padre Jerald se ele pensar que você é um clérigo. Eu sugiro que você receba primeiro as cartas do assistente também.",
"Obrigado, Ammand. O que você vai fazer agora?",
"Não importa, capitão. Encontrarei você mais tarde para pegar minha metade do dinheiro.",
"Adeus por enquanto, Ammand",
"Então capitão Sparrow, onde está o meu dinheiro?",
"Ammand... eu hum.. eu não acabei chantageando o padre.",
"Então o que você está tentando dizer é que tudo o que ganho com isso é uma estúpida estátua de ouro da igreja??? Você vai pagar por isso, Jack Sparrow!",
"Talvez. Mas hoje não, Ammand!",
"Talvez. Mas hoje não, Ammand! (PENSA: Talvez não tenha sido tão sábio mentir para um Lorde Pirata)",
"Bom dia, capitão. Tenho informações que podem ajudá-lo. Mas não vou compartilhar isso com você até saber que posso confiar em você. Visite o assentamento pirata em #sisland_Quebradas Costillas# para que o chefe de lá possa atestar por você.",
"Talvez eu faça exatamente isso. De qualquer forma, estou pensando em me juntar aos Irmãos da Costa. Até nos encontrarmos novamente!",
"",
};
