string DLG_TEXT[54] = {
"---",
"---",
"Tenho o prazer de conhecê-lo, capitão.",
"Então você deve ser a 'Donzela em Perigo'. Estou correcto?",
"Sim, e espero que você seja o corajoso capitão que possa me ajudar.",
"Isso ainda está para ser visto, senhora, e não saberemos até que você me diga qual é o seu problema, certo? Vamos começar dizendo-me seu nome.",
"Ah! Meu nome é Annabella Brin...kley-Achoo! Desculpe, estou um pouco resfriado. Meu nome é senhorita Annabella Brin.",
"Isso é um começo. Bom dia para você, senhorita Annabella Brin. [PENSA: Brin, esse é um nome que Matthew mencionou.] Eu sou o capitão ",
", a seu serviço. Então, somos apresentados. Agora, qual é o seu problema? ",
"Oh! Capitão, é insignificante no grande esquema das coisas, mas para mim é de grande importância e me causa muita angústia.",
"De fato, de fato. E a questão desta 'Grande Consequência'?",
"Tive uma discussão estúpida com meu pai. Ele me encarregou de cuidar de minhas irmãs e das joias de minha mãe em uma curta viagem até aqui. Eu me separei de minha irmã e não ouso voltar para meu Pai sem ela.",
"Eu vejo. E as joias da sua mãe? [PENSA: Precisamos colocar nossas prioridades em ordem aqui!]",
"Oh! Eles são bastante seguros, eu os tenho comigo, mas tenho medo de ser roubada, de ser uma jovem sozinha. Talvez você se encarregasse deles para mim. Mas é com minha irmã que estou mais preocupada.",
"Muito bem, dê-me as joias se isso fizer você se sentir melhor. Quanto à sua irmã, onde exatamente você a 'perdeu'?",
"Aqui estão as joias. Estou muito aliviado agora que você está encarregado deles. Minha irmã e eu fomos separados na cidade do outro lado da ilha, e não me atrevo a viajar sozinho pela selva para tentar encontrá-la. Capitão, não poderíamos navegar até lá no seu navio para procurá-la?",
"Poderíamos, de fato, Srta. Annabella, poderíamos, de fato. Também poderíamos seguir o caminho terrestre pela selva. Comigo para protegê-lo, teríamos poucos problemas. Deixe-me pensar por um momento sobre qual caminho seguir. [PENSA: Bem, as joias me darão alguma vantagem contra meus custos nesta missão caso a querida senhora e eu nos separemos.]",
"Você decidiu?",
"Sim, senhorita Annabella, eu tenho. Vamos.",
"Bem, nós conseguimos. Devíamos ir à Taverna para ver se minha irmã está lá.",
"Parece lógico. Vamos tentar isso então.",
"Capitão, estou muito feliz em vê-lo novamente. Este é um assunto de grande importância e tínhamos que ter certeza de que tínhamos a pessoa certa.",
"Você saiu há pouco. Você pode me dizer do que se trata",
"Claro, capitão, devo isso a você. Na verdade, estou separado da minha irmã, Bella, mas não a perdi. Ela foi sequestrada por piratas junto com sua empregada.",
"Entendo, então você é realmente Annabella Brin. E as joias da sua mãe? [PENSA: Ninguém parece ter suas prioridades em ordem por aqui.]",
"Ah! As jóias. Receio que tenham sido um teste. Um teste para ver se você iria roubá-los e fugir.",
"Roube-os! Como se... Você difama meu personagem, Srta. Brin.",
"Oh! Não! Capitão, tínhamos certeza de que você era a pessoa certa, mas precisávamos ter certeza dupla de seu caráter.",
"E presumo que agora você é?",
"Sim capitão. A missão exigirá que você se disfarce de pirata e se infiltre na ilha para resgatar minha irmã. Não podemos ir porque seríamos facilmente reconhecidos.",
"Oh! Isso é tudo? Então farei isso logo depois do jantar! .. Senhorita Brin, o que você propoe é uma tarefa muito perigosa.. sem falar que é cara, muito cara.",
"Eu entendo o perigo, capitão, por isso escolhemos você. Quanto às despesas, use as joias que lhe dei, mais estas, para preparar sua expedição. Posso garantir-lhe que meu pai irá recompensá-lo generosamente quando você resgatar minha irmã.",
"Muito bem, assumirei sua missão. Por onde devo começar a procurar sua irmã e a empregada?",
"E se eu recusar o seu pedido?",
"Experimente primeiro a #sisland_Quebradas Costillas# Island. Esse é o último relatório que temos deles.",
"A sua reputação nesta ilha já está em dúvida. Tudo o que o Sr. Brock precisa fazer é confirmar meu 'sequestro' e seu futuro será sombrio. Isto é, se você sair vivo desta sala.",
"Partirei assim que estiver devidamente equipado, Srta. Brin. Deseje-me um bom vento e um mar calmo.",
"Vou arriscar a esse respeito, Srta. Brin. En garde!",
"Então, de fato, desejo-lhe bons ventos, capitão, e espero vê-lo novamente em breve em #sisland_Redmond#.",
"Esperemos que esse dia não esteja muito longe.",
"Ah! Capitão Skull, deixe-me apresentar o corajoso Capitão que me ajudaria a resgatar minha irmã. Ha! Ha!",
"O que? Achei que você não poderia vir aqui? O que está acontecendo?",
"Uma ligeira mudança de plano, meu caro capitão. A senhorita Brin e sua irmã foram de fato sequestradas, mas pelo capitão Skull e por mim. Acontece que eu pareço com Annabella, só isso, mas serviu ao nosso propósito. O que precisávamos era de alguém para transportá-los de volta e cobrar o resgate para nós.",
"E eu fui o idiota que você selecionou? [PENSA] Nem tudo está perdido, posso ver alguma vantagem vindo em minha direção aqui.",
"É verdade, querido capitão. Você levará uma irmã de volta para #sisland_Redmond#, receberá o resgate, trará-o de volta aqui e então libertaremos a outra irmã. Irei junto para ficar de olho nas coisas.",
"E como você sabe que não vou te enganar?",
"Porque também manteremos seu companheiro aqui até você voltar. Se você nos enganar, ela morre! Assim como a irmã. Você entende?",
"Parece que não tenho opção... Muito bem, aceito seus termos.",
"Então... vamos viajar em dois navios, ouvi dizer?",
"Para conforto, senhorita Brinkley. Um navio é pequeno demais para acomodar todos nós. Para o mar então, para o mar. Temos coisas para fazer e lugares para ir.",
"Quando voltaremos para o nosso pai?",
"Em breve, senhorita Brin, em breve.",
"Obrigado por nos resgatar, capitão. O que acontece agora?",
"Nós levamos você de volta para seu pai. Vamos indo.",
"",
};
