string DLG_TEXT[99] = {
"Disseram-me que você fez um grande esforço para solicitar uma audiência. Meu nome é ",
". Agora, por favor, diga-me o propósito da sua visita ",
".",
"Meu nome é ",
".",
"Ah, é você de novo. O que traz você aqui desta vez? ",
"Eu gostaria de conversar com você sobre alguns negócios.",
"Sinto muito, mas há coisas que preciso fazer.",
"Então, por que você me distrai dos assuntos de estado muito importantes?",
"Gostaria de falar com você sobre um pequeno negócio.",
"Só estou aqui para prestar meus respeitos. Nada mais, ",
"Nesse caso, por favor, saia do meu escritório e deixe-me voltar para assuntos mais importantes.",
"Sim claro. Desculpe por ter incomodado você.",
"Estou ouvindo, ",
".",
"Estou aqui para receber minha recompensa pela morte de Dirty Garry.",
"Sinto muito, mas não tenho nada para conversar agora",
"Oh, ouvi sobre o que você fez. Da face de toda a colônia eu lhe mostrarei o nosso apreço.",
"Isso mesmo, gostaria de ver uma recompensa.",
"Você é um brincalhão. Ha ha. Aqui está o seu dinheiro.",
"Obrigado, sou seu humilde servo.",
"Então, sobre a aposta que você fez... depois de obter a aprovação do nosso departamento fiscal, vejo que temos... deixe-me ver... seis mil.",
"O que?! O negócio foi de 10 mil!",
"Eu não posso te ajudar. No futuro, tente ficar mais calmo.",
"O que quer que você diga, senhor. Porco sujo....",
", você está ciente de que é acusado de assassinato? Você foi visto perto do corpo da vítima. O que você diz em resposta a esta acusação?",
"Não tem nada a ver comigo. O homem já estava morto quando entrei na sala! Disseram-me que ele estava apenas ferido e que poderia ter algumas informações importantes para mim.",
", Acabei de saber que um homem foi capturado quando tentava deixar a cidade com uma faca manchada de sangue em sua posse. Ele confessou o assassinato de que você foi acusado. Você pode ficar livre imediatamente.",
"Obrigado. Eu sabia que poderia confiar na justiça aqui em #sisland_Conceicao#.",
"Desejo desertar para Portugal.",
"De fato? Muito bem, agora você é cidadão português.",
"Agradeço sua infinita gentileza, senhor.",
"Oh sim? Tenho uma proposta para você, capitão.",
"De fato?",
"Aprendi que você concluiu a tarefa com sucesso; meus parabéns, capitão! Aqui está sua recompensa.",
"Meus agradecimentos; Foi um prazer ajudá-lo.",
"Você deve destruir o ",
" navio ",
"missão pirata",
" ameaçando o envio ",
". Se você afundá-la, vou recompensá-lo com uma boa quantia de ",
" ouro. O que você diz, capitão?",
"Você não ouvirá falar dela novamente, isso eu prometo.",
"Receio não poder ajudá-lo.",
"Anseio por perdão, Excelência.",
"Estou interessado em aprender sobre as relações holandesas com outras nações.",
"Estou procurando uma Carta de Marca.",
"Ah, ",
", que bom que você passou por aqui. Eu gostaria de apresentar meu ",
". Ela virá assim que terminarmos os negócios.",
"Ouvi dizer que estou pronto para uma promoção.",
"Não posso mais servir ",
", vossa Excelência.",
"Cansei de servir ",
"Como garantia de que você é um capitão competente e para recompensar meu tempo apresentando seu caso a ",
", devo te pedir ",
" ouro.",
"Sem chance.",
"Muito bem.",
" tem sempre o prazer de aceitar novos capitães ao seu serviço. ",
"Estamos atualmente em guerra com ",
"",
"nenhum grande poder, mas ",
". Claro, ",
"Os piratas devem sempre ser afundados à primeira vista.",
" À luz do seu serviço anterior, ",
" concede a você a classificação de ",
"Vou deixá-lo orgulhoso, Excelência.",
"Você prejudicou ",
", e ",
" não esquece seus inimigos. Saia imediatamente, ou os guardas vão te jogar fora!",
"...",
"Você causou ",
" grande dano, capitão, mas ",
" está disposto a ignorar suas transgressões passadas... por um preço: ",
"Muito bem, senhor. Aceito.",
"É um prazer lidar com você, ",
"E você, Excelência.",
"Você é realmente! Excelente trabalho. Sua nova classificação é ",
". Além disso, você é premiado ",
" hectares de terra por ordem de ",
"Obrigado, senhor.",
"Tem certeza, ",
" lamentaremos perder seu serviço.",
"Sim eu sou.",
" não gosta de vira-casacas ",
"Uh, não importa.",
"Muito bem. Mas espero que você reconsidere, com o tempo...",
"Adeus, ",
"Huh?",
"Difícil.",
"Sim capitão? O que você quer?",
"Estou em busca da fragata francesa 'La Foudre'. Ela deveria ter navegado para #sisland_Saint Martin# alguns dias atrás. Você afundou?",
"Nós, holandeses, não gostamos particularmente dos franceses, então posso entender por que você pensaria que o teríamos afundado. Mas não, não vi nenhuma fragata francesa por aqui.",
"Tem certeza? #sHavana# O Almirante do Porto Talicerdor me garantiu que ela partiu para #sisland_Saint Martin#, e também não foi visto do outro lado da ilha.",
"Só posso lhe dizer o que sei: não vi nenhuma fragata aqui. Talvez ela tenha tido que mudar de rumo devido àquela violenta tempestade que assolou aqui há alguns dias.",
"Uma tempestade violenta? Lorde Talicerdor também mencionou o misterioso navio pirata que apareceu em uma tempestade. Eu me pergunto...",
"Navio pirata misterioso? Que navio pirata misterioso?",
"Não importa. Obrigado pela ajuda. Adeus.",
"",
};
