string DLG_TEXT[145] = {
"Ah, capitão ",
", não nos conhecemos. Meu nome é Barbossa - Capitão Barbossa - e não pude deixar de ouvir seu interesse no pirata fugitivo.",
"Prazer em conhecê-lo, capitão. Meu interesse está no enforcamento, não no pirata em si, garanto. [PENSA: Não sei quem você é, ou quem você poderia ser.]",
"Só o enforcamento, né? E aqui estava eu pensando que você era um membro da Irmandade, então talvez o seu interesse seja mesmo MENTIRA?",
"Fraternidade? Que Irmandade? [PENSA: Isso pode ser uma armadilha... Mas, novamente, pode não ser. Um afiado, esse cara. Talvez eu não devesse ter tomado aquela última xícara de rum]",
"Vejo que você é um homem cauteloso, capitão. Muito esperto. Muito bem, sugiro que você navegue até uma das praias locais, ou talvez até uma casa. Ele está se movendo muito, e vou deixar por isso mesmo.",
"Agradeço a sua informação e despeço-me, por enquanto.",
"O que você quer dizer? [PENSA: Ele não sabe que o tesouro está amaldiçoado! Acho que vou brincar com ele por um tempo.]",
"Danielle",
".",
"Você finalmente chegou.",
"Você localizou ",
"Raoul Rheims",
"?",
"Mais uma coisa, capitão",
"Sim?",
"Eu vi dois homens andando por #sTortuga# recentemente, e pelo que descobri, eles já foram canhoneiros da Marinha Real.",
"E quais são os nomes desses homens?",
"Pintel e Ragetti.",
"Excelente...",
"Acho que deveríamos contratar Pintel e Ragetti antes de pegar o tesouro, Capitão",
"Você está apaixonado por Pintel ou algo assim?",
"Vê aquela mesa perto da porta? Aquilo é ",
"Raoul Rheims",
". Sugiro que você fale com ele, antes que ele desapareça... Agora, me desculpe, tenho outros assuntos que precisam da minha atenção.",
"Algo me diz que eu não gostaria de saber o que você está fazendo. De qualquer forma, obrigado pela sua ajuda. Vá em frente, conversaremos mais tarde.",
"Tive contato com ele de vez em quando.",
"E onde foi isso? Onde posso encontrar ",
"Raoul Rheims",
" e por que você decidiu nos ajudar.",
"Bem, para ser mais preciso, capitão, acredito que você e eu deveríamos nos encontrar com ",
"Danielle",
" nestes assuntos. Acho que poderíamos trabalhar bem juntos, ganhando muito dinheiro.",
"Eu vejo. Mas ainda estou curioso sobre Rheims, como você o encontrou?",
"Ah! Capitão, ",
". Somos dois iguais, estou pensando",
"Por favor. Chega de familiaridades. Não sei se você é confiável.",
"Danielle",
" estava certo sobre você - você é muito desconfiado.",
"O que ",
"Danielle",
" pensa ou diz é problema dela. Mas eu realmente preciso saber como você conhece o homem que procuramos e por que decidiu ajudar ",
"Danielle",
", ou você me responderá lâmina!",
"Tudo bem, tudo bem, acalme-se. Eu sei ",
"Raoul Rheims",
" muito bem - já fomos, por assim dizer, vizinhos. Quanto a ",
"Danielle",
", decidi ajudá-la porque uma vez ela me ajudou em uma situação muito desagradável. E como eu disse, capitão, deveríamos trabalhar juntos",
"Convincente. Vou verificar isso. Então, onde você disse ",
"Raoul Rheims",
" Está se escondendo?",
"Eu não disse. Você deveria conversar com ",
"Danielle",
", primeiro - talvez ela tenha outros planos.",
"Tudo bem, vou falar com ela.",
", Espero que você esteja gostando desta bela ilha?",
"Sim, muito obrigada!",
". É hora de unirmos forças, estou pensando",
"Huh! Do que diabos você está falando?",
"Estou falando do Mapa Cortez, aquele tesouro que você procura. Eu tenho a parte que está faltando. Eu lhe darei o mapa se você concordar com uma proposta que tenho.",
"Bem, você tem minha atenção. Qual seria a sua proposta então?",
"Você me aceita como seu primeiro imediato, e nós navegamos em busca do tesouro de Cortez e dividimos o saque entre nós.",
"O que você quer dizer?",
"Capitão, você tem um ótimo navio. Você tem as orientações que nos levarão direto ao tesouro de Cortez. Tenho a parte que falta no mapa e conheço as águas desses mares. Então navegue comigo até o tesouro de Cortez.",
"Quais seriam seus termos?",
"Ah, capitão, cinquenta, cinquenta. Bem no meio. Essa é a minha maneira de trabalhar. Metade para você e metade para mim e depois seguimos nosso caminho. Você pode seguir seu caminho e eu navegarei em direção ao sol. Nós dois livres e desimpedidos, e muito, muito ricos!",
"Você faz com que pareça muito fácil. Eu ganho metade do tesouro Cortez e então estou livre para terminar meus outros assuntos?",
"A vida é simples, capitão, se você pensar bem. Nós dois ganhamos ouro fácil e você pode fazer o que quiser depois. O que você diz então?",
"OK. vamos fazê-lo. Iremos primeiro ao tesouro de Cortez. Mas eu sou o capitão desta aventura. Isso precisa ser entendido.",
"Capitão, capitão. Ficarei feliz em servir como seu oficial, mas para tornar as coisas justas, você deveria me dar a orientação para a Isla de Muerte. Dessa forma podemos confiar uns nos outros porque nenhum deles pode funcionar sem o outro, certo?",
"Entendo o que você está dizendo. Eu sei para onde estamos indo e você tem a parte do mapa que desejo. OK. Eu lhe darei a orientação assim que embarcarmos.",
"Excelente! Capitão. O que você acha de terminarmos a conversa e começarmos a navegar. Precisamos ir para a Isla de Muerte antes que o tempo mude. Aqui está a parte do mapa que você precisa. Ha! Ha! estamos a caminho de sermos ricos, muito ricos mesmo.",
"Muito bem. Vamos embarcar sem mais delongas.",
"Estou pensando que quando você estiver totalmente equipado, com uma bússola adequada, poderemos partir em busca de algum tesouro.",
"Oh! Eu voltarei então, então.",
". Precisamos conversar. Estou pensando que a nossa situação mudou.",
" É hora de sermos uma empresa separada. Não precisarei mais da sua ajuda. Eu tenho sua bússola e preciso de TODO o ouro. É muito melhor do que metade, e este navio vai servir-me muito bem.",
"Seu cão traidor... vou atropelá-lo onde você está.",
"Seu dedo é tão afiado, capitão? Você parece ter deixado suas armas em sua cabine, então você está em certa desvantagem, estou pensando.",
"Maldição! Eu nunca deveria ter confiado em você. Você não tem um osso decente em seu corpo!",
"Agora não seja tão cruel, capitão. Eu não sou de todo ruim. Vou lhe dar uma pistola e uma bala, para que você possa caçar para comer,... ou... estourar seus miolos, se você ficar muito sozinho na linda ilha, vou deixá-lo em . Talvez você possa usá-lo para sinalizar um navio. AH! AH! AH! Enquanto isso, navegarei de volta à Isla de Muerte em busca do tesouro.",
"Não! Acho que vou guardá-lo para passar pelo seu coração maligno quando nos encontrarmos novamente, seu maldito!",
"Não nos encontraremos novamente, capitão, esta ilha está muito longe dos pontos de abastecimento das rotas comerciais. Você verá navios passarem, mas nenhum pousará. Ninguém vai te encontrar, então adeus... e mantenha sua pólvora seca. AH! AH! AH! Navegue para a ilha, homens, não muito perto, ele pode nadar a última milha, estou pensando.",
"Aproveite a vida enquanto você pode cachorro! E tenha certeza que nos encontraremos novamente!",
"Avast Lubber! Você está no meu caminho!",
"Eh? Certamente.",
"Como diabos você saiu daquela ilha?",
"Quando você me abandonou naquele pedaço de terra esquecido por Deus, você esqueceu uma coisa muito importante: eu sou o capitão ",
"Bem, não cometerei esse erro novamente.",
"O que aconteceu enquanto eu estava inconsciente?",
"O amante da senhorita Swann conseguiu libertá-la e eles conseguiram escapar, levando consigo o medalhão. Eles chegaram ao seu navio e então eles e a tripulação do escorbuto partiram. Mas, quando eu tiver matado você, irei persegui-lo no #scursed_ship#.",
"Quando você vai entender que somos imortais e que não tem chance contra nós? Afundámos o Interceptor, capturámos a sua tripulação e temos Miss Elizabeth como nossa prisioneira. E seu amigo ferreiro não está em lugar nenhum. Então agora podemos retornar à Isla de Muerte e acabar com a maldição.",
"Não é possível!",
"Não é provável!",
"Sinto muito, mas não posso atender você agora. Tenho alguns assuntos a tratar primeiro com o Sr. Turner.",
"Você não quer fazer isso?",
"Não, acho que sim.",
"Seu funeral.",
"OK. Por que eu não quero fazer isso?",
"Porque o HMS Dauntless, orgulho da Marinha do Rei, está flutuando no mar esperando por você.",
"Explodir os lubbers!",
"Mas eu tenho uma solução. Ordene aos seus homens que remem até a Audácia, eles fazem o que sabem fazer melhor. Então você terá dois navios. Você tomará o maior como sua nau capitânia e me nomeará Capitão do #scursed_ship#. Você pode se apresentar como Comodoro Barbossa. Inteligente? O que você acha?",
"Huumm..interessante..Agrreeed!",
"O que meus homens estão fazendo? Eles estão demorando muito! Eles já deveriam ter voltado da Audácia. Você está tentando me enganar?",
"Porque você pensaria isso? (você pega uma moeda amaldiçoada)",
"O que você está fazendo? É o bastante! Eu vou te matar, traidor!",
"Ah! ...um plano, de fato, mas tem uma falha.",
"Uma falha, de fato, e o que poderia ser isso?",
"Bem, o sangue da garota não acabou com a maldição, não é? Ela não é quem você quer.",
"Na verdade... repito, e é claro que você saberá de quem é o sangue que preciso.",
"Eu poderia... e então, talvez não. Eu sei que você precisa do medalhão primeiro, e se você me matar, você não terá certeza de quem está atrás agora, não é?",
"Muito esperto, ",
", muito esperto. Que assim seja. Você navegará conosco enquanto perseguimos. Para os homens do navio, para o navio.",
"Agora estamos a falar.",
"Ah! sim, ",
", falando estou, e observando também! Você estará liderando o caminho de volta ao Pearl. Estarei de olho em você durante todo o caminho, então sem truques.",
"Não, sem truques. Precisamos encontrar o Interceptor.",
"Muito bem, Sr. Turner. Aceito seus termos e agora você está vinculado a eles. Liberarei a tripulação do Interceptador em pequenos barcos. Eles são bons marinheiros, então conseguirão desembarcar. Quanto à senhorita Swann e ao querido capitão, conheço um local agradável onde eles podem passar o tempo. AH! AH! HA!",
"Er, Will. Eu gostaria que você tivesse sido um pouco mais específico com seus termos!",
"[Will Turner] ESPERE!",
"Os rolamentos não irão ajudá-lo. Você não encontrará a ilha dessa maneira, precisará de mim para levá-lo até lá. Vamos zarpar e eu o levarei direto até lá. Afinal, nós dois estaremos no mesmo navio, então não vou fugir sem você, certo?",
"Como você disse Capitão. O que você acha de terminarmos a conversa e começarmos a navegar. Precisamos ir para a Isla de Muerte antes que o tempo mude. Aqui está a parte do mapa que você precisa. Ha! Ha! estamos a caminho de sermos ricos, muito ricos mesmo.",
"É isso então? ... A famosa Isla-de-Muerte? ... Então, onde vamos cavar?",
"Ainda não, ainda temos um longo caminho a percorrer para encontrar o tesouro.",
"Que bela visão, Capitão, aquece bastante o meu coração, e é o que acontece.",
"Sim, parece bastante bonito, não é? É melhor chamarmos a tripulação para começar a carregá-lo.",
"Ah! temos um problema aí, capitão. Acho que fomos seguidos por uma esquadra britânica de navios. Eles vão nos afundar com certeza e tudo estará perdido.",
"O QUE! Por que você não disse algo antes de embarcarmos?",
"Eu não queria preocupar você, capitão. Afinal, eu não tinha certeza, mas tenho um plano para nos tirar daqui.",
"É melhor que seja bom. Você nos meteu nessa confusão. Então! O que é?",
"Erguemos a Bandeira Portuguesa antes de zarparmos. Eles não vão atirar nisso, mas podem parar e nos revistar. Então, se deixarmos o tesouro aqui por enquanto e navegarmos para #sGrand Cayman#, sendo um porto britânico, isso dissipará as suspeitas de qualquer maneira.",
"Então deixamos o tesouro por enquanto, navegamos como portugueses, e se formos parados eles não encontram nada e nos deixam ir. Então poderemos voltar mais tarde, quando o esquadrão tiver partido. Certo?",
"Inteligente como sempre, capitão. Inteligente como sempre. Sim, e sendo portugueses podemos aterrar em #sisland_Cayman# sem problemas e voltar dentro de um ou dois dias.",
"OK. Isso soa como um plano. Vamos.",
"Você vê o que eu vejo, capitão?",
"Parece que estamos aqui. Vamos olhar mais de perto.",
" o homem que nos livrou daquele vilão de coração negro, Blunden.",
"Eu esperava que a morte dele pudesse ter sido de maior significado para você pessoalmente.",
"Ha Ha! Parece que você está procurando uma recompensa, querido capitão.",
"Eu er.. bem, er.. não exatamente. Quero dizer, er.. não é dinheiro, eu esperava que você pudesse ter parte de um mapa.. ou algo assim.",
"Capitão, não tenho mapas para vender ou para doar, então lhe ofereço uma navegação justa. Bom dia.",
"É isso?",
"Sim, capitão, como você diz... É isso. Agora deixe-me pensando, se você quiser.",
"Oh! ... Bom dia então.",
"",
};
