string DLG_TEXT[80] = {
"Vamos cantar juntos uma cantiga do mar!",
"...",
"Ah, aí vem nosso ouro, agora! Venha comigo - não iremos longe",
"Tudo bem.",
"Espere aqui, e eu trarei o nosso prisioneiro.",
"Basta ser rápido.",
"Cash and carry - é assim que fazemos negócios aqui!",
"Aqui está o seu ouro, engraçado",
"Engraçado. Não seria uma risada se eu ficasse com o ouro para mim e massacrasse você e seus amigos como os porcos que vocês são?",
"Muito bom lidar com você.",
"Eu ficaria muito feliz se você fosse embora",
"O que?! Você não tem dinheiro suficiente! Tentando nos enganar, hein?! Morrer!",
"Droga!",
"Veja, isso não é tão engraçado. Eu mataria nosso convidado antes que sua espada saísse da bainha. Então ninguém estaria rindo.",
"Tudo bem, tudo bem. Algumas pessoas não tem senso de humor. Aqui está o seu dinheiro.",
"Bom dia! Bom capitão, peço-lhe um centavo, ou uma moeda de ouro fino, ou rum, meio barril.",
"Aqui está seu centavo, meu caro. Espero que ajude.",
"Aqui está uma moeda de ouro, meu caro. Gaste com sabedoria.",
"De alguma forma, não acho que você seja o pobre bêbado que finge ser. Qual é a sua história?",
"Não perca meu tempo, seu malandro, você provavelmente tem mais dinheiro do que eu.",
"---",
"---",
"Ah! Capitão, parece que você é exatamente a pessoa que estou procurando.",
"Bem, agora que senti o seu mau hálito, acho que não estou procurando alguém como você, afinal.",
"Na verdade, e o que te faz pensar isso?",
"Você percebeu que se eu realmente estivesse bêbado, o proprietário já teria me expulsado horas atrás.",
"Hmmm! Algo assim, devo admitir. Então, por que você está procurando por mim em particular?",
"Não foi você, em particular, mas alguém que é astuto e tem inteligência.",
"Bem, acho que posso me encaixar nessa descrição. Então, podemos começar a trabalhar?",
"Muito bem. Se você está disposto a correr riscos, há uma donzela, digamos, 'em perigo' que poderia usar a ajuda de um jovem e forte capitão como você. Você está disposto para isso?",
"Não acho que não. As mulheres sempre parecem me causar problemas. Então eu lhe desejo um bom dia.",
"Donzelas em perigo são uma especialidade minha! O que eu preciso fazer?",
"Como desejar, meu bravo capitão. A senhora em questão está nos ouvindo conversar e acaba de me sinalizar que acha que você poderia ajudá-la. Ela acabou de sair e estará esperando por você atrás da taverna. Vá agora e encontre-se com ela lá.",
"Muito intrigante! Eu irei conhecer essa sua mulher misteriosa. [PENSA: Pode haver alguma vantagem nisso.]",
"Como desejar, meu corajoso capitão. Vou cuidar para que você não falhe. Embarque no navio do contrabandista e para #sTortuga# você navega.",
"Obrigado, sei que isso vai ser rápido. Próxima parada #sTortuga#.",
"A aventura de Jack Sparrow é aquela que você procurava. Basta entrar no seu navio e navegar até aquele porto.",
"Vou navegar para lá a partir daqui. Não vai demorar muito.",
"Uma longa viagem, meu capitão, é uma boa maneira de navegar. Eu te dei comida para que sua missão não falhasse.",
"Ah! Obrigado. Quando eu acordar estarei em #sisland_Turks# Port Jetty.",
"Bom capitão, farei o que você pede. Para #sTortuga# você irá, o que não é tarefa fácil.",
"Então preciso encontrar o Sr. Gibbs quando chegar lá.",
"Parece que você vai precisar da minha ajuda novamente, capitão.",
"Ei! Você se movimenta, não é? O que está acontecendo aqui? Nada faz sentido até agora.",
"Paciência, capitão, paciência... Este não é lugar para conversar. Vamos lá para cima.",
"É melhor que isso seja bom. E você pode parar esse disfarce de mendigo bêbado? Isso irrita, você sabe.",
"Eu sei que você está confuso, mas precisávamos ter certeza de que você era a pessoa certa para o trabalho.",
"Trabalho! Que trabalho? E sim, estou confuso.",
"Você sabe por que estou aqui, companheiro. Podemos começar a trabalhar?",
"Não perca meu tempo, seu malandro, você provavelmente tem mais dinheiro do que eu.",
"Eu sei porque você está aqui, você sabe que sou o melhor. Apenas certifique-se de que você quis dizer isso e não apenas adivinhou. Você predefiniu seus níveis, equipamentos e tudo? Se não, meu querido capitão, você cairá na lama.",
"Ops! Desculpe, não, não era isso que eu queria. Adeus.",
"Sim... estou testando as águas. Se você souber o que quero dizer.",
"Então, meu belo capitão, para onde você irá? Apenas me diga o seu desejo, e eu farei isso",
"Vou ficar aqui, obrigado, e ver o que acontece.",
"Preciso testar o Motim com Barbossa.",
"Quero começar por ir a #sTortuga#, onde encontro a Anamaria.",
"Quero navegar para #sisland_Redmond# para a sequência da 'Grande Entrada'.",
"Quero ir com Norrington para a ilha #sisland_Turks# para a linha de missão alternativa do CotBP.",
"Eu quero #sTortuga#, onde eu pego uma tripulação e encontro o #scursed_ship#.",
"Como deseja, meu corajoso capitão, passe pela frota. Navegue até o Farol, e Barbossa você conhecerá.",
"Obrigado Billy. Vou tentar isso.",
"Como desejar, meu ousado capitão. Vou cuidar para que você não falhe. Embarque no navio do contrabandista e para #sTortuga# você navega.",
"Obrigado, sei que isso vai ser rápido. Próxima parada #sTortuga#.",
"Bem, bem, bem... Capitão ",
" em pessoa. Craca persistente, não é?",
"Digamos apenas que sou uma craca que você não vai raspar, seu pedaço de alga podre.",
"Palavras duras para um jovem tão jovem. Suponho que você veio resgatar essas irmãs encantadoras. Infelizmente é hora da realidade, então desembainhe sua espada.",
"Chegou sua hora, Brock. Diga adeus.",
"Gostaria de ir ao retorno das irmãs em #sisland_Oxbay#.",
"Eu gostaria de testar o Baú do Homem Morto.",
"Quero navegar para #sisland_Redmond# para a sequência da 'Grande Entrada'.",
"A aventura de Jack Sparrow é aquela que você procurava. Basta entrar no seu navio e navegar até aquele porto. Não se esqueça do querido Henry, isso seria ótimo. Para fazer a missão funcionar, você deve falar com ele duas vezes.",
"Eu quero a primeira cena do motim.",
"OK. Espere.",
"Quero testar a cena da tempestade.",
"Em seguida, navegue até Lighthouse Bay a partir daqui.",
"Quero testar Ragetti e Pintel.",
"Ok, então navegue até #sTortuga#.",
"Que tal aquela igreja em Isla Cruces? Deixe-me ver!",
"",
};
