string DLG_TEXT[21] = {
"Sim, senhor!",
"Nada.",
"Acabei de escapar dos traficantes de escravos no naufrágio!",
"Estamos indo nessa direção agora, o que você pode nos dizer?",
"Há três traficantes de escravos no navio e acho que eles irão levar o tesouro em breve. Posso ajudá-lo a combatê-los e peço apenas para poder viajar com você em troca.",
"Cara, qual é o seu nome?",
"Apenas me chame de chefe. Vamos então, capitão.",
"Ok, Bos'un, vamos lá.",
"Apenas me chame de Nigel. Vamos então, capitão.",
"Ok Nigel, vamos lá.",
"Senhor, eu estava no mesmo campo que Gombo, ele vai querer que libertemos mais e mais escravos com uma grande perda para você.",
"O que você sugere que façamos então?",
"Nós salvamos os escravos em #sisland_Eleuthera# e então se ele pedir para você libertar mais nós nocauteamos ele e sua tripulação e recebemos dinheiro como compensação.",
"Parece um bom plano, obrigado Bos'un.",
"Parece um bom plano, obrigado Nigel.",
"Irei agora para o navio e serei apenas um membro da tripulação.",
"Ok, vejo você a bordo.",
"Capitão de 20.000 moedas de ouro.",
"Muito bem, bem-vindo à tripulação.",
"Obrigado por matar meus donos. Desejo navegar para você, de graça!",
"Pronto, posso ter mais utilidade para você mais tarde.",
"",
};
