string DLG_TEXT[42] = {
"Você precisa se mover.",
"Concordo.",
"Mings? O que você tem a ver com Sir Christopher?",
"Foi ele quem me enviou para encontrar o Capitão Petros.",
"Ele realmente fez isso? E qual é a sua mensagem para o Capitão Petros?",
"Só isso. - É um assunto dele, e apenas dele, e não estou preparado para discutir mais o assunto.",
"Você falou comigo pela segunda vez, agora somos contratados para trabalhar juntos em sua missão. A palavra SWIM é apenas parte da informação que você precisa. Precisamos pegar o resto.",
"Sim, capitão, eu não conseguia imaginar como essa parte me levaria a um tesouro.",
"Não era para isso acontecer. Caso a mensagem tenha caído em mãos erradas, ela será dividida em partes.",
"Agora você diz isso, isso é bastante óbvio?",
"Sim, talvez seja. Precisamos descobrir quantas peças e onde elas estão.",
"Oh! E como nós fazemos isso?",
"Ah! Isso é um pouco mais complicado. Seu pai deve ter enviado várias mensagens com o restante das informações. Agora, para quem seu pai poderia ter enviado cartas? Obviamente, dentro da família, ele não teria confiado em mais ninguém. Quem ainda está vivo na sua família?",
"Bem, eu, minha irmã Bonnie.. e.. meu irmão Blaze.",
"Então aí está. Sua irmã não recebeu nada, caso contrário ela teria lhe contado, então é seu irmão Blaze que você precisa encontrar para completar o quebra-cabeça.",
"Hummm! Então, como faço para encontrá-lo? Não tenho ideia de onde ele foi.",
"A última vez que ouvi ele foi em Barbados. O problema é que é uma ilha inglesa e não há como navegarmos lá sob a bandeira pirata, a menos que tenhamos ajuda.",
"Que ajuda é essa então?",
"Conheço um lugar que é uma praia deserta no lado sul da ilha. Acho que este é um caso em que a discrição superará a força. Tudo o que precisamos fazer depois disso é encontrar seu irmão. Faça o que precisar agora, encontro você no cais.",
"Isso parece muito emocionante. Vou me preparar para navegar.",
"Você está pronto para navegar então?",
"Sim, estamos prontos. Vamos.",
"Bem, devo dizer que foi uma viagem e tanto. É melhor continuarmos com o assunto em questão. Não podemos ficar aqui por muito tempo, os navios do Rei logo estarão sobre nós. Vamos para a cidade!",
"Oh! Sim, eu entendo. Suponho que deveríamos ir à Taverna para ver o que podemos descobrir?",
"Esse seria o lugar óbvio para começar.",
"Estamos prontos para ir?",
"Sim, enviei o navio para o mar com ordens de permanecer fora do local de terra e de não enfrentar os navios ingleses. Podemos sinalizar quando retornarmos. ",
"Isso soa bem. Vamos então.",
"Então você finalmente acordou. Você foi atingido na cabeça e capturado na selva. Você já está aqui há dois dias",
"Bem, você respondeu a maioria das minhas perguntas, exceto quem fez isso.",
"Não temos tempo para conversar agora. Os rapazes criaram uma distração e todas as tropas foram chamadas para guarnecer seus postos, mas isso não vai durar muito, então precisamos sair daqui.",
"Para onde vamos?",
"Vá para o porto, embarque no meu navio e siga para a Ilha #sisland_Turks#. Todos concordamos em nos encontrar lá. Eu cuidarei de você enquanto avançamos",
"OK. Vamos indo então.",
"Olá, Capitão Sparrow! O que te traz aqui?",
"Sim, Capitão Drow. Nathan Kell me sugeriu que você é um homem que pode assumir uma grande responsabilidade, concordei. Então, o que você diz?",
"O que é que você quer de mim?",
"Este pedaço de lixo é um dos nove pedaços de oito! Com ele você se tornará o senhor pirata do oceano Atlântico. Devemos honrar o chamado, se isso acontecer você precisará navegar até Shipwreck Cove!",
"Estou realmente muito interessado. Existe algo que eu possa dar em troca.",
"[PENSA: Talvez eu possa receber algo como pagamento enquanto mostro a ele onde fica Shipwreck Cove] Apenas atenda ao chamado, espertinho? É aqui que Shipwreck Cove está localizado",
"Bem-vindo de volta, Sr. Sparrow. O que posso fazer para você?",
"CAPITãO Pardal. Esperava conceder-lhe uma grande honra, Capitão Drow. Se você estiver disposto a fazer o que for necessário para merecer essa honra, isto é.",
"",
};
