string DLG_TEXT[28] = {
"Você está pronto?",
"Falta apenas uma garrafa de rum para ser isso, cara.",
"Capitão, quando chegamos na taverna encontramos o último pedaço do mapa e conseguimos descobrir usando ele também. O mapa mostra a Isla de Muerte.",
"Ah! A Ilha de Muerta. Sim, eu sei um pouco sobre isso, mas melhor que isso, tenho uma bússola que pode nos levar até lá, e com o mapa completo podemos encontrar o tesouro. Mas onde estão os outros?",
"Oh sim! Os outros. Não sei se você notou, mas aquele maldito Tenente Bligh nos seguiu até aqui, então os outros zarparam para fazê-lo segui-los, a fim de conduzi-lo em uma perseguição inútil.",
"Enquanto nós, entretanto, navegamos para a Isla de Muerta, imagino?",
"Exatamente! Precisamos zarpar o mais rápido possível.",
"Tudo bem. Corra então.",
"Acho que ele quer dizer que nós... er... podemos ver através de você!",
"Ver através de mim? AHH! Droga! Minhas mãos! São todos ossos!",
"Isso é o que queríamos dizer! Você pegou algo Jack... Algo desagradável!",
"Eu me sinto bem... eu acho.",
"Jack! O que você está fazendo aqui..? Você parece, er... normal. Estávamos vindo atrás de você, o médico já está a bordo do meu navio.",
"Estou bem. Parece que não estava antes, mas estou agora. O tesouro está amaldiçoado. Se você pegar apenas uma única moeda, você será amaldiçoado. Vai demorar muito para explicar, mas eu anotei, aqui pegue e leve para Sir Christopher.",
"Obrigado Jack. Vou descarregar o médico e depois podemos navegar de volta para #sOxbay# e Sir Christopher.",
"Faça isso. Quero meu navio de volta, então irei para #sisland_Turks#. Presumo que ela ainda esteja lá?",
"Sim, ela é. A propósito, aqui estão as partes do seu mapa. Suponho que isso seja um adeus então?",
"É, até nos encontrarmos novamente. Tem sido divertido, não é? Adeus e bons ventos. Preciso me reformar antes de partir.",
"Capitão, recebemos uma mensagem do Capitão Charles na Plantação. Você lembra que ele tinha parte do mapa, mas foi tirado dele.",
"Aquilo eu faço. Qual é a mensagem, então?",
"Bem, o capitão Charles conseguiu fazer um esboço da peça que tinha de memória e nos enviou. Com esse esboço e as peças que você forneceu, conseguimos identificar a ilha. É a Ilha de Muerta.",
".",
".",
".",
".",
".",
".",
".",
};
