string DLG_TEXT[29] = {
"Estou pronto para o mar.",
"Isso é bom capitão.",
"Quem é você?",
"Um amigo do Capitão Petros e Sir Christopher Mings.",
"Oh! Você é, não é? Então nós dois parecemos estar...?",
"Membros da Irmandade.",
"Bom! Desculpe por isso, mas precisamos ter cuidado. Qual o seu nome? E o que você está fazendo aqui?",
"Eu sou Capitão ",
", e estou procurando pelo Capitão Nathan Kell. Você sabe onde ele está?",
"Ah! Capitão Kell, há alguns aqui que gostariam de vê-lo, e isso não é uma vantagem para ele. E por que você iria querer vê-lo?",
"Eu acredito que ele tem algo que eu preciso.",
"Você precisará ser mais específico, infelizmente. Preciso ter certeza de que você é realmente um de nós.",
"Ele tem parte de um mapa que a Irmandade precisa, companheiro. Satisfeito?",
"Muito bem, vá aonde você iria se estivesse doente, ele tem uma sala secreta lá. Receio não poder ir com você, nós dois entrando ao mesmo tempo atrairemos atenção.",
"E um homem cauteloso como você não aceitaria nada disso agora, não é? Tudo bem então, obrigado pela sua ajuda. Eu irei agora.",
"Capitão Kell, capitão ",
". Cutler Beckett está na cidade e está perguntando sobre você, capitão ",
".",
"Um pouco inconveniente, para dizer o mínimo. Mas eu já o enganei antes.",
"É bom vê-lo novamente, capitão. Você encontrará seu navio no porto todo equipado.",
"Obrigado, Capitão Damski. E agora?",
"Você deveria navegar de volta para Lighthouse Bay. Anamaria irá encontrá-lo lá. Esperamos que Barbossa esteja na área, então ele deve entrar em contato com você.",
"Muito bem, é Lighthouse Bay. Eu prometi a uma certa senhorita Anamaria que voltaria para buscá-la. Oh! E obrigado a todos pela ajuda.",
"Temos uma reunião com o Capitão Boelen. Portanto, ofereceremos a você um vento favorável até nos encontrarmos novamente.",
"E para todos vocês, capitães. Até nos vermos novamente.",
".",
".",
".",
"Que bom ver você, capitão. Vejo que você e o Capitão Drow estão aqui. Tomamos a liberdade de navegar com seu navio até aqui depois que você foi capturado. Você o encontrará no porto.",
};
