string DLG_TEXT[25] = {
"Bom dia capitão.",
"Olá capitão.",
"Olá, vejo que você está viajando com Lucas.",
"E se eu estiver?",
"Algo aconteceu com a filha do governador. Acho que você deveria ir ver o governador Le Moigne.",
"Ok, obrigado pelo conselho.",
"Então, o que há com a filha do governador?",
"Ela desapareceu. Ela foi para #sHavana# e não voltou há dois meses. Uma fragata chamada 'La Foudre' foi enviada para encontrá-la e também não se ouviu falar dela.",
"OK. Bem, estou navegando em direção a #sisland_Cuba# de qualquer maneira, então se você quiser navegar comigo eu ficaria feliz.",
"Obrigado pela oferta. Acho que vou aceitar, só por precaução. Qual navio é o seu?",
"Os 'Van Diemen'.",
"Partiremos em breve.",
"Bem, chegamos a #sHavana#. Eu iria ver o porta-almirante, se fosse você.",
"Obrigado pelo conselho.",
"Foi um prazer navegar com você, capitão, mas devo continuar agora. Posso ver você por aí algum dia.",
"Obrigado por toda a sua ajuda, Capitão Maggee. Até a próxima.",
"Olá novamente capitão, aqui é Tia Dalma. Sugiro que você a acompanhe em sua próxima viagem.",
"Por que é o Capitão Maggee?",
"Apenas confie em mim... Isso pode salvar sua vida!",
"Ok, vou permitir que ela navegue comigo, o que você vai fazer agora?",
"Tenho negócios em outro lugar, então devo ir embora.",
"Adeus novamente, Capitão Maggee.",
"Percebi que o governador tem estado bastante quieto recentemente, talvez você saiba por quê?",
"Sim, tenho... Sua filha desapareceu a caminho de #sHavana# e ele também perdeu uma fragata na busca. Agora me pediram para procurar por ela e pela fragata também... experiente.",
"OK. Bem, estou navegando em direção a #sisland_Cuba# de qualquer maneira, então se você quiser navegar comigo eu ficaria feliz. Ah, a propósito, me chame de Capitão Maggee.",
"",
};
