string DLG_TEXT[117] = {
"Ah! Um novo visitante na minha taverna! Bem-vindo, ",
"! A melhor hospitalidade do arquipélago está à sua disposição!",
"Olá. Meu nome é ",
".",
"Obrigado. Meu nome é ",
".",
"Você é muito bem-vindo. Por favor, sente-se, beba um bom rum, experimente uma das minhas especialidades! Você ficará feliz por ter feito isso.",
"Que bom te ver novamente, ",
". Pegue qualquer uma das mesas livres e descanse.",
"Ah é você! Não vejo você há séculos. Posso começar com uma taça de vinho para molhar o apito?",
"Se não se importar, gostaria de ir direto ao assunto.",
"O tempo é curto, amigo, e tenho assuntos sérios para discutir.",
"Desculpe. Estou muito ocupado para hospitalidade no momento.",
"Estabeleça-se. Acabei de passar para ver quem estava aqui; Eu já estou saindo.",
"Prazer em conhecê-lo, ",
". Meu nome é ",
".",
"Claro, ",
", você é o chefe. Como posso ajudá-lo?",
"Estou querendo aumentar minha equipe. Você poderia me indicar alguém que possa estar procurando trabalho?",
"As batalhas recentes me deixaram com falta de pessoal. Preciso encontrar alguns rapazes que estejam procurando emprego.",
"Eu gostaria de falar de negócios.",
"Você tem um quarto disponível? Eu gostaria de ficar aqui por um tempo",
"Estou procurando um quarto limpo com uma cama limpa. Nada mais nada menos.",
"Não tenho tempo para conversar agora. Eu passo por aqui mais tarde.",
"Desculpe, estou ocupado agora. Mas voltarei para conversar quando estiver livre.",
"De fato! E que negócio é esse?",
"Estou procurando um cavalheiro que você talvez conheça. Receio não saber o nome dele, mas sei que ele tem estudado as línguas nativas locais.",
"Estou procurando um cavalheiro que você talvez conheça. Receio não saber o nome dele, mas sei que ele tem estudado as línguas nativas locais.",
"Estou procurando um homem chamado ",
"Raoul Rheims",
"Raoul Rheims",
". Você sabe se ele esteve na ilha?",
"Tem ",
"Ferro Cerezo",
" esteve aqui recentemente?",
"Eu preciso encontrar ",
"Ferro Cerezo",
". Você o viu?",
"O que dizem sobre o sequestro deste padre local?",
"Gostaria de saber se um certo homem esteve aqui. O nome dele é Nigel Blythe, e ele parece um completo malandro.",
"Eu preciso de algum trabalho. Você não conhece nenhum garoto rico nesta ilha que tenha medo de viajar sozinho?",
"Você sabe, agora que penso nisso, não tenho nenhum negócio.",
"Ha-ha! Parece que ele já te incomodou o suficiente se você falar dele dessa maneira.",
"Isso é verdade. Mas você não respondeu minha pergunta. Ele estava aqui ou não?",
"Sim, apenas algumas horas antes de você chegar. Ele falou com um homem.\nPelo que me lembro, eles discutiram, mas depois encontraram algum interesse em comum.",
"Você ouviu mais alguma coisa? Para onde ele foi?",
"Não sei. Mas o rapaz com quem ele estava conversando é local - já o vi antes.",
"Onde? Onde ele mora?!",
"Acalmar! Ele mora em uma casa logo atrás da minha taverna. Ao sair da taverna você verá portões que levam a um pequeno pátio. E o homem é um rapaz gordo com roupas de couro.",
"Esse é o sujeito que eu preciso! Obrigado.",
"A colônia inteira está falando sobre isso! Imagine invadir uma igreja em plena luz do dia e sequestrar o Padre! E eles desapareceram antes que alguém pudesse fazer alguma coisa.",
"Quem eram eles? Homens mascarados?",
"Não. Pelo que ouvi, eles eram apenas os assassinos de sempre. Mas é engraçado você mencionar máscaras...",
"Engraçado? Por que?",
"Não faz muito tempo, um homem apareceu aqui mascarado.",
"Realmente? O que ele queria?",
"Por que isso é tão importante para você? Não tenho certeza se deveria compartilhar o negócio dele com outros clientes.",
"Acho que ele pode estar ligado ao rapto do padre. Você quer ajudar com isso, não é?",
"Sim, eu acho que sim. Tudo bem, há três semanas, este homem apareceu, vestido com uma máscara. Ele foi muito cortês, especialmente para os padrões de hoje. Nunca disse uma palavra ruim a ninguém. Chamava a si mesmo de garanhão.",
"Garanhão, hein? Prossiga.",
"Bem, os cidadãos daqui não tinham muita certeza sobre ele, mas ele nunca fez nada de errado - apenas passou muito tempo conversando com os jovens locais - e isso não foi tão ruim. Pela primeira vez, eles pareciam menos interessados em se meter em encrencas.",
"E então?",
"E então...algo aconteceu. Agora todos os jovens estão se preparando para deixar a cidade em alguma campanha com ele. O filho do tanoeiro brigou bastante com o pai e saiu de casa. O tanoeiro ficou muito zangado com isso e foi falar com o nosso homem misterioso - mas logo saiu correndo da casa do homem como se mil demônios estivessem atrás dele. Naquela mesma noite o tanoeiro pegou um pouco de rum podre em algum lugar, ficou horrivelmente bêbado e acabou afogado. O que ele estava pensando, passando pelo cais à noite, quando mal conseguia andar?! E você sabe de uma coisa? Seu filho não parecia se importar.",
"Isso é estranho, de fato. Onde posso encontrar esse rapaz?",
"O filho do tanoeiro? Ele estará vagando pela cidade em algum lugar. Ele está perdido desde que o homem mascarado desapareceu.",
"Eu vou encontrá-lo. Qual o nome dele?",
"Jordão",
"é o nome dele. Rapaz bonito, igual ao pai, coitado. Sentiremos falta do tanoeiro; ele era um bom homem.",
"Obrigado.",
"Claro, ",
". Na verdade, ele está sentado à mesa ali.",
"Obrigado.",
"Claro, ",
". Ele esteve aqui, mas navegou recentemente para #sConceicao#.",
"Obrigado.",
"Raoul Rheims",
"? O nome parece familiar, mas já faz um tempo que não o ouço. Desculpe, não posso ajudar mais.",
"Não se preocupe com isso. Vou ter que continuar procurando. Deixe-me perguntar outra coisa.",
"Infelizmente, não posso ajudá-lo.",
"Lamento ouvir isso. Talvez você tenha visto a senhora chamada ",
"Danielle",
"Danielle",
"?",
"Sim, eu tenho. Ela apareceu aqui há poucos minutos. Ela parecia chateada, embora eu não tenha perguntado por quê.",
"Bom. Talvez eu ainda consiga alcançá-la.",
"É um pouco tarde para isso. Você terá mais sorte se voltar pela manhã. Ou talvez você queira passar uma noite na taverna.",
"Talvez eu fizesse isso. Você tem um quarto livre?",
"Talvez eu vá. Mas deixe-me perguntar uma outra coisa primeiro.",
"Eu tenho um quarto disponível. Quanto tempo você pretende ficar?",
"Até de manhã.",
"Só até o anoitecer.",
"Multar. Vai custar 5 moedas de ouro.",
"Tudo bem. Aqui você vai.",
"Nesse caso, temo que minha carteira e eu passaremos uma noite no salão comum.",
"Não, obrigado. Se esse for o preço, economizarei algumas moedas e passarei uma noite no salão comum.",
"Talvez mais tarde. Deixe-me perguntar sobre outra coisa.",
"Multar. Vai custar 5 moedas de ouro.",
"Tudo bem. Aqui você vai.",
"Nesse caso, temo que minha carteira e eu passaremos uma noite no salão comum.",
"Não, obrigado. Se esse for o preço, economizarei algumas moedas e passarei uma noite no salão comum.",
"Vou pensar sobre isso. Obrigado.",
"Por favor! Pare com essa loucura de uma vez! Não me faça chamar os guardas!",
"Tudo bem! Vou.",
"Se existe tal pessoa, ela pode preferir evitar atrair a atenção de tantas consortes - como eu espero que você saiba.",
"Sim, esqueci. Tudo bem, voltarei mais tarde, quando tiver menos navios, ha-ha.",
"Não quero ajudá-lo, com todo o mal que você causou ao meu país.",
"Basta olhar para este patriota. Bem adeus.",
"Suas mãos estão cobertas de sangue. Você realmente acha que alguém viajará com você?",
"Você está certo. Todo mundo tem medo de mim. Que divertido.",
"Você veio na hora certa. Um comerciante aqui estava procurando a companhia certa para viajar. Você deveria falar com ele. Aqui está ele, entrando na taverna.",
"Eu farei isso.",
"Não, não há ninguém em quem eu possa pensar no momento. Talvez na próxima vez.",
"Hum. Então vou esperar.",
"Ouvi dizer que você capturou um pirata. Quando é o enforcamento? Eu sempre gosto de um bom enforcamento. Bebidas por toda parte!",
"Bah! aqueles tolos que se dizem carcereiros! Ele fugiu, mas os soldados o encontrarão em breve.",
"Bem, pelo menos ainda não perdi nada. Guarde essas bebidas para mais tarde, companheiro.",
"",
};
