string DLG_TEXT[278] = {
"Você está procurando capitão de trabalho?",
"Eu poderia ser. O que você tem em mente? E quem pode ser voce?",
"Minhas desculpas...Deixe-me apresentar-me. Sou Sir Cutler Beckett, da East India Trading Company. A seu serviço. E você é?",
"Eu sou Capitão ",
". Então, qual é esse trabalho que você mencionou?",
"Atualmente estou procurando capitães para servir na Companhia das Índias Orientais. Você gostaria de ser um de seus capitães?",
"Parece muito intrigante, Sir Cutler, e o que isso implicaria exatamente? E o mais importante, quanto pagaria?",
"Direto ao ponto, como ouvi, capitão. O pagamento é inicialmente de 5.000 peças de ouro por corrida.",
"Um preço justo. Então, o que constitui 'uma corrida'?",
"Transportando várias cargas de uma ilha para outra. Simples, realmente. Preciso de homens honestos e confiáveis, e eles são difíceis de encontrar nestas águas infestadas de piratas.",
"E navios de escolta?",
"É assim que você ganhará seu dinheiro. Você deve estar preparado para defender a si mesmo, ao seu navio e, claro, à carga. A Companhia não fornece navios de escolta. No entanto, conforme você provar, você receberá um dos navios da própria Companhia. Um investimento considerável da nossa parte, devo acrescentar. Bem, capitão ",
". Você está interessado?",
"Sim, senhor Cutler, estou. Quando eu começo? [PENSA: Não demorarei muito para conseguir um navio da Companhia. Afinal, eu sou, capitão ",
"].",
"Não há tempo como o atual capitão. Aqui estão 5.000 em moedas que você pode usar para reformar seu navio e mais 5.000 que você deve usar para comprar tanta carga quanto seu navio puder transportar. Essa carga deverá ser vendida onde você determinar e o dinheiro entregue a mim nos escritórios da Companhia, que você encontrará em #sRedmond# em #sisland_Redmond#. Negocie como achar melhor, é o retorno do meu investimento que desejo ver. Obviamente você usará suas habilidades para determinar o melhor retorno desse investimento.",
"Compre carga, ou qualquer outra coisa, obtenha o melhor preço e entregue o dinheiro para você no escritório da Empresa em #sisland_Redmond#. Entendi, senhor Cutler. Vejo você em breve.",
"Bom, temos um contrato. Eu investi 10.000 em você, capitão. Vamos ver quanto você pode me devolver em #sRedmond#. Você será julgado por seu desempenho e sua recompensa será solidária com esse desempenho. Quanto melhor seu desempenho, maior será a recompensa.",
"Eu entendo, Sir Cutler. Você está procurando o retorno do seu investimento.",
"Bom. Vejo você em #sRedmond#. Um capitão de ponto final. Caso você se torne um pirata e renegue este contrato. Minha retribuição será severa. Você entende?",
"Eu também entendo isso, Sir Cutler. Você pode ficar tranquilo, não sou pirata. Sou um capitão honesto, disposto a seguir meu próprio caminho no Caribe.",
"Então, bom dia para você, capitão. Até nos encontrarmos novamente, desejo-lhe um vento bom e favorável.",
"Bom dia para você também, senhor.",
"Não, senhor Cutler. Receio não querer me comprometer com nenhum empregador no momento, então desejo-lhe um bom dia.",
"Como desejar, capitão. Talvez nos encontremos novamente e talvez você tenha uma visão diferente das coisas então. Bom dia para o senhor.",
"Nunca se pode saber o que a maré pode trazer. Bom dia para você também, senhor.",
"Você é ",
" por acaso?",
"É o CAPITãO ",
" na verdade. Mas você tem vantagem sobre mim. Por favor, senhor, quem é você? Não acredito que já nos conhecemos?",
"Minhas desculpas, capitão. Deixe-me apresentar-me. Sou Sir Cutler Beckett, da East India Trading Company. A seu serviço.",
"De fato? E o que um homem nobre como você estaria fazendo numa taverna? E por que você me procuraria?",
"Relaxe, meu querido capitão. Preciso de escolta imediata para #sRedmond# em #sisland_Redmond#, e você foi altamente recomendado. Fui informado de que há piratas nestas águas. Meu próprio navio de escolta foi chamado para tratar de assuntos urgentes e tenho uma carga valiosa para transportar, por isso estou temporariamente envergonhado com esse assunto.",
"Isso é muito lisonjeiro, Sir Cutler, mas estou muito ocupado no momento. [PENSA: Um pouco de vantagem para aumentar o preço.]",
"5.000 em ouro aliviariam sua carga de trabalho? Um bom lucro para uma corrida rápida para #sisland_Redmond#, eu acho.",
"Ah! 5.000 em ouro, você diz?",
"A pagar na nossa chegada segura.",
"Muito bem, Sir Cutler, eu farei isso. [PENSA: Acho que desenhei isso bem. 5.000 em ouro! Uma boa soma.]",
"Um excelente capitão de decisão. Quando é que vamos navegar?",
"Tenho algumas coisas para resolver. Mas partiremos em breve. Encontro você no porto.",
"Considerando todas as coisas, uma jornada de sucesso, capitão. Devo atender ao descarregamento da minha carga, por isso transferirei meu navio para o cais da Companhia. Encontrarei você em breve nos apartamentos da Companhia quando efetuarei seu pagamento. Eles estão localizados no grande edifício à direita do portão de entrada na cidade.",
"Sim, senhor Cutler.",
". Para o assunto em questão. Aqui está o pagamento pela escolta que você desempenhou tão bem.",
".",
"Ah! Capitão ",
" Você finalmente chegou. Você viajou sem incidentes, eu confio?",
"Apenas as coisas marítimas habituais, Sir Cutler.",
"Você provou ser um capitão competente. Como você se sentiria em continuar trabalhando com a Empresa?",
"Estou sempre pronto para os negócios, Sir Cutler!",
"Não, senhor Cutler. Acho que preferiria seguir minha própria sorte por enquanto.",
"Bom homem. Aqui estão 10.000 em ouro. Faça negociações, permuta ou o que achar melhor e obtenha lucro para a Empresa. Quando você tiver concluído a tarefa, volte aqui e discutiremos mais detalhadamente seu futuro.",
"Pode haver um limite de tempo para a tarefa em questão?",
"Nenhum capitão, como achar melhor. Quando você achar que tem lucro suficiente, basta voltar aqui. No entanto, você deve saber que não sou conhecido por minha paciência. Portanto, não volte aqui a menos que esteja pronto para o acerto de contas.",
"Sim, senhor Cutler. Eu entendo. Eu irei agora e começarei.",
"Bom. Bom dia para você então capitão.. e boa sorte.",
"Bom dia para você, Sir Cutler.",
"E como foi sua missão? Bem sucedido, eu confio.",
"Acredito que sim, senhor Cutler. Aqui está o dinheiro.",
"Eu entendo. Isso é tudo, senhor Cutler?",
"Bom, veja se você faz isso. Não sou conhecido pela minha paciência... lembre-se, enquanto isso você está com tempo emprestado, e estaremos observando, para garantir que seus esforços sejam os mais diligentes no assunto!",
"Sim, senhor, eu sei o que devo fazer.",
"Obrigado, senhor Cutler. Que navio seria esse?",
"Excelente! Excelente! Você mais que dobrou o investimento da Empresa em você. Você é realmente um ativo para a Empresa. Você não precisa de mais treinamento e está pronto para um navio da Companhia.",
"Ah! Pagamento, sim, Sir Cutler, obrigado.",
"Você está pronto para começar #sisland_Antigua#?",
"Bem, sim, Sir Cutler, estou ansioso para começar a ganhar dinheiro de verdade. Preciso reabastecer meu navio, entre outras coisas, antes de partir.",
"Isso está resolvido então. Aqui está o seu pagamento para esta viagem.",
"Você é ",
" por acaso?",
"Relaxe, meu querido capitão. Você foi altamente recomendado e é exatamente o tipo de capitão que a Companhia está procurando.",
"Isso é muito lisonjeiro, Sir Cutler, mas estou muito ocupado no momento. [PENSA: Um pouco de vantagem para aumentar o preço.]",
"",
"Você precisará reprovisionar seu navio. Uma tarefa de natureza urgente precisa da sua atenção.",
"Um bom resultado capitão. Um lucro de cinquenta por cento será adequado para a Empresa. Você pode ficar com o resto. Mais uma missão e você receberá um navio da Companhia.",
"Que missão seria essa, Sir Cutler? Estou ansioso para conseguir um navio da Companhia.",
"Para um capitão da sua qualidade, simples. Um dos meus oficiais foi capturado pelos espanhóis. Eu preciso que você o resgate.",
"Onde ele pode estar?",
"Ele está em #sisland_Isla Muelle#. O problema, porém, é que não sabemos em que parte da ilha. Você acha que pode realizar o resgate dele?",
"Sim, Sir Cutler, entendo perfeitamente.",
". Eu posso lidar com qualquer coisa.",
"Bom homem. Complete esta missão com sucesso e você terá sua nave. Darei a você 5.000 em ouro para financiar o empreendimento. Desejo-lhe boa velocidade, capitão. Bom dia.",
"Sim capitão ",
". A Simpkins fornecerá a você um uniforme da Empresa quando você sair. A partir de agora você é um tenente interino da Empresa. Isso é tudo. Um vento bom e favorável para você.",
"Bom dia para você, senhor Cutler. Adeus.",
"",
"Capitão ",
"Não é o que eu esperava, capitão. A Companhia espera mais que esse nível de retorno. Receio que você deva repetir a missão. Espero que você se saia melhor desta vez.",
".",
"Muito bem, capitão, não há mais nada a dizer sobre o assunto. Um vento bom e favorável para você.",
"Excelente capitão! Aqui estão 25.000 em ouro. Considere isso, digamos, um avanço. Reajuste e reabasteça assim que puder zarpar para #sisland_Antigua#. Lá você receberá mercadorias que deverá levar e vender em outra ilha pelo melhor preço. Compre ouro com o dinheiro que conseguir e depois volte aqui. Esses papéis garantirão sua passagem segura.",
"",
"",
"",
"Você resgatou Wanderman! Um excelente resultado capitão. Não hesitarei em lhe dar um navio da Companhia e 10.000 em ouro.",
"Uma jornada de sucesso, capitão. Tenho assuntos imediatos, aos quais devo atender. Encontrarei você mais tarde nos apartamentos da Companhia quando efetuarei seu pagamento. Eles estão localizados no grande edifício à direita do portão de entrada na cidade.",
"Agora Capitão, você está interessado em navegar em um de nossos navios para uma carga especial? Será muito lucrativo para você.",
"Você receberá o comando de um navio da Companhia, The Wicked Wench. A Companhia, é claro, manterá seu navio até você retornar.",
"Sim, senhor Cutler.",
"Preciso que você navegue até Muscetto Cove em #sisland_Antigua# e pegue uma carga muito especial. Não fale com ninguém sobre o assunto. Pagarei a você 5.000 agora e 5.000 quando você retornar e entregar a carga na outra margem em #sRedmond#. Estarei lá para te conhecer. Esses papéis garantirão sua passagem segura.",
"É isso? Eu poderia ter obtido um retorno melhor com o agiota.",
"",
".",
"Você é sem dúvida o pior capitão que já conheci. Sair! Não quero mais negociações com você.",
"Er... bem, pensei que seria o suficiente.",
"Então, nos encontramos novamente ",
". Eu confio que você tem meu dinheiro?",
"Então entregue-o ",
"er... Adeus... Senhor Cutler",
"Aqui está.",
"Sim senhor, eu entendo. Em relação à venda da mercadoria no meu retorno. Posso vendê-los em qualquer ilha?",
"Oh! os eventos marítimos habituais!",
"Sim Sim! Os problemas do mar. Você tem o ouro em que confio e mais alguma coisa?",
" E o Victualler me deu um pacote de documentos para você.",
"Contaremos isso como duas viagens, #sisland_Antigua# e Bridgeford, então será o dobro do valor! Mas primeiro, o pacote, por favor.",
"Preciso que você pegue outro pacote. Desta vez, do proprietário do estaleiro em #sOxbay# Town.",
"Muito bem, capitão, muito bem. Apressem-se nesta viagem, o assunto é da maior urgência. Pagarei a você 6.000 em ouro adiantado para acelerar seu retorno.",
"O governador incumbiu-me de afundar um navio de abastecimento francês em Falise de Fluer, meu senhor",
"Muito interessante, muito interessante! Enquanto estiver lá, talvez você possa pegar um pacote para mim do proprietário do estaleiro. Pagarei a você 6.000 em ouro adiantado",
"Preciso que você se prepare para navegar até #sSt John's# em #sisland_Antigua# para carregar mercadorias. Então você deve vendê-los e comprar ouro que você deve entregar para mim aqui.",
"Seu nome e navio prisioneiro, e seja rápido!",
" E eu gostaria de saber por que fui preso injustamente?",
"Eu só sei de você. Nunca nos conhecemos antes. Considere-se sortudo por estar vivo ",
"... Pelo menos por enquanto! Sou Sir Cutler Beckett, da Honorável East India Trading Company, e também atualmente governador em exercício desta bela ilha.",
"Eu sei disso... estou trabalhando para você! ... Você não me reconhece? Leve-me ao Governador imediatamente!",
"Você faria bem em manter uma língua civilizada em sua cabeça ",
" É apenas o fato de o Governador conhecer você e ter falado bem de você que você ainda está vivo. O Governador deixou a ilha por enquanto, então explique-se para mim. AGORA!",
"Estou trabalhando para... er... você... bem, agora olho mais de perto, talvez alguém que se pareça muito com você... er...",
"Isso não faz sentido! ... Guarda! ... Guarda! Leve o prisioneiro para a Residência. Ainda chegaremos ao fundo deste assunto! .",
"Agora ",
", Explique-se antes que minha paciência diminua e seu pescoço fique mais longo.",
"Tenho trabalhado com o Governador para libertar #sOxbay#... e com o homem chamado Beckett para a East India Trading Company. Tenho os documentos da Empresa para provar isso.",
"O Governador falou bem de você e de seus esforços em nome da Coroa, o que é uma vantagem para você. Quanto aos documentos, examinei-os e são reais. Então, estou me perguntando como eles surgiram. Isso nos leva ao 'seu' Beckett... Onde você o conheceu?",
"Aqui, na Taverna.",
"Na Taverna, SIR CUTLER! Preste atenção em como você se dirige a mim... e, por favor, qual era a natureza do seu assunto com ele?",
"Desculpe, senhor Cutler. Eu navegaria para vários lugares, #sisland_Antigua#, #sOxbay#, #sGreenford#, compraria ouro e traria de volta para cá.",
"Aqui atrás? E onde 'aqui' esse negócio foi conduzido?",
"er... na Taverna... er, Sir Cutler.",
"A Taberna! A TAVERNA! Não lhe pareceu estranho... que um oficial da Honorável Companhia Comercial das Índias Orientais fizesse negócios na TAVERNA?",
"Bem... agora que você colocou dessa forma... eu suponho... Sir Cutler.",
"Suponha! ... Talvez, ",
", você teria feito bem em ter 'suposto' antes, quando estava fazendo negócios na Taverna! ... Descreva o homem.",
"Bem, ele se parece muito com você, senhor.",
"De fato. Suponho que isso exclui noventa e nove por cento da população destas ilhas... o que mais?",
"Ele continuou repetindo suas primeiras palavras quando falou.",
"Har! Na verdade ele fez? Interessante! Você encontrará esse homem e o trará de volta aqui, vivo. Veremos se ele é um impostor, ou,..... outra pessoa. Enquanto você faz isso, tenho outra tarefa que você também completará para mim.",
"Que tal manter o comprimento do seu pescoço na dimensão atual?",
"Ah! ... sim, Sir Cutler, isso servirá perfeitamente.",
"Você está começando a ver sentido, sua posição atual é tênue. Somente a recomendação do Governador o manteve vivo até este ponto. Execute bem essas tarefas e você poderá se redimir um pouco comigo. Caso contrário, vou marcá-lo como pirata e depois enforcá-lo.",
"Navegue até o acampamento pirata onde você deverá encontrar um homem chamado Raoul Rheims. Foi ele quem traiu #sOxbay# aos franceses. Capture-o e traga-o de volta aqui... e enquanto você estiver fazendo isso, fique de olho no 'seu' homem, Beckett. Se você pegá-lo, traga-o de volta vivo também. Aqui estão os documentos da sua empresa e seus efeitos. Agora saia e apresse-se com esta missão.",
"Vá em frente, cara!! Não fique aí parado. Você tem coisas para fazer!",
"Meu nome é ",
", e eu sou o capitão do ",
".",
" Isso é ridículo... você sabe quem eu sou!",
"E... e quanto ao pagamento, Sir Cutler?",
"Capitão, não parece haver muitas caixas sendo transportadas. Espero que você não esteja tentando me fraudar. Isso seria muito imprudente! muito imprudente! Eu pagarei desta vez, mas com um valor reduzido. Preciso que você se prepare para navegar até #sSt John's# em #sisland_Antigua# para carregar mercadorias. Então você deveria vendê-los e comprar ouro que você deveria entregar para mim aqui. Mas, Capitão... Preste atenção ao meu aviso! ",
"Garanto-lhe, Sir Cutler, que não é essa a minha intenção. Só tenho esse negócio de invasão em mente, só isso. Obrigado pelo pagamento.",
"Falei com o Governador e ele me deu uma tarefa da mais importante natureza em #sFalaise de Fleur#. Não posso recusar.",
" Onde estão os prisioneiros de Rheims e o 'seu' homem misterioso?",
"Não consegui localizá-los, Sir Cutler. Tentei várias ilhas, mas nenhum sinal delas, exceto este diário pertencente a Rheims. Isso mostra que ele está planejando algum tipo de missão.",
", pensei que você pensasse, você era melhor que isso. Parece que devo me contentar com a decepção com o seu fracasso. No entanto, sendo o homem generoso que sou, pagarei a você os 5.000 ouros que prometi, além de mais 5.000, mas você usará isso para financiar outra tarefa que tenho para você. E desta vez não falhe!",
"Um navio foi capturado por piratas há vários dias, '",
"capitão pirata 06",
", rumo à Europa vindo da New Light. Ao passar pela nossa colônia, os piratas atacaram. \nAlém dos bens comerciais habituais, havia vários ídolos de ouro a bordo. Estes são tesouros astecas raros que encomendei para minha coleção. \nDescobri que o senhor pirata que ordenou a captura é ",
"Alistair Garcilaso",
"Alistair Garcilaso",
". Ele e sua gangue de açougueiros estão escondidos na selva #sDouwesen#, não sei onde exatamente. \nVocê, ",
", vou encontrá-los e trazer minha coleção de volta de alguma forma. \nEu lhe darei mais 10.000 quando a missão for concluída com sucesso. \nVocê entende?",
"Muito bem, siga seu caminho. E lembre-se,... não me falhe nesta missão. O seu futuro... digamos... depende do seu sucesso!",
" Você está demitido.",
", eu estava a caminho das docas. Disseram-me que há muita atividade descarregando seu navio. Isso significa que você recuperou minha coleção?",
"Esta é uma notícia muito agradável, capitão. Você realmente me poupou meses de trabalho e devo lhe mostrar meu agradecimento.",
"Bem... seu Sir Cutler, devo confessar que uma caixa estava vazia, então presumo que faltou um ídolo. Eu poderia continuar procurando por ele, se você desejar.",
"Não, não. Isso não será necessário. Você provou seu valor e tenho uma tarefa muito importante para você em um futuro próximo. Enquanto isso, para sua recompensa. Em primeiro lugar, os 10.000 em ouro que prometi e, em segundo lugar, estou lhe dando a 'Mulher Malvada'. Um belo navio, de fato, ele irá atendê-lo bem.",
"Isso é muito generoso, Sir Cutler. Muito generoso. Mas, e a tarefa que você tem em mente?",
"Ainda não, capitão. Você precisará se acostumar com seu novo navio, colocá-lo à prova e ver como ele se comporta. Quero que você navegue até #sGreenford# e pegue um prisioneiro do Comandante da Prisão e o traga de volta para cá. Esta é a sua carta de autoridade. Quando você retornar, estará pronto para assumir a missão principal.",
"Bom. Em seguida, navegue assim que tiver reabastecido. Estou saindo para examinar minha nova coleção. Vejo você no seu retorno.",
". É bom ver você novamente. Bom te ver. Mesmo nestas circunstâncias infelizes.",
"Senhor Cuthbert! O que você está fazendo aqui?",
"Eu era o prisioneiro que você foi enviado para recolher! Meu 'querido' irmão está cada vez mais perto de me alcançar. \n Felizmente para mim ainda tenho amigos e eles me ajudaram a escapar. Espero que você esteja preparado para me ajudar também.",
"Eu o ajudarei se puder, Sir Cuthbert. O que você precisa?",
"Quais navios estão em Lighthouse Bay? Navios de guerra ingleses, ou algo amigável?",
"Bem, acabei de conhecer Barbossa e Danielle lá. Eles parecem ter informações sobre Rheims e têm um navio. Mas há uma patrulha inglesa na área.",
"Rheims, hein? Bem, isso interessará ao meu irmão. É melhor você voltar e reportar a ele. Eu gostaria de ver o rosto dele quando ele descobrir que eu escapei, mas não conte a ele que você sabe que eu era o prisioneiro. Você tem alguma outra novidade?",
"Claro que não vou mencionar que descobri quem era o prisioneiro. Quanto a outras notícias, acho que Barbossa pode me ajudar a encontrar o tesouro de Cortez.",
"Bom Bom. Mantenha-me informado sobre esse empreendimento. Estou muito interessado em ajudar, muito interessado. Vou me despedir por enquanto e ver se consigo embarcar com seus amigos. Eu vou te encontrar novamente em breve.",
"Adeus, Sir Cuthbert, e tome cuidado.",
", você tem o prisioneiro acorrentado em quem confio?",
"Não, Sir Cutler,... lamento dizer que o Comandante da Prisão o deixou escapar. Eles ainda estão procurando por ele.",
"Bah! O tolo incompetente... vou lidar com ele mais tarde.",
"Tenho boas notícias, Sir Cutler. Encontrei vestígios do traidor Raol Rheims. Eu poderia ir atrás dele se você quiser.",
"Sim, você deveria fazer isso. Mas primeiro, ",
", Tenho uma tarefa de natureza mais importante para você que você deve realizar primeiro.",
"Esta é a tarefa sobre a qual falamos antes de Sir Cutler.?",
"É sim. Preciso que você navegue até Muscetto Cove em #sisland_Antigua# e pegue uma carga muito especial. Não fale com ninguém sobre o assunto. Isso é o mais importante, então pagarei 50.000 agora e 50.000 quando você retornar.",
"Sim, senhor Cutler.",
"Você deve entregar esta carga primeiro. Na outra margem da Jamaica, estarei lá para conhecê-lo. Então você pode continuar a busca por Rheims. A carga é muito grande, por isso certifique-se de que seu porão esteja vazio, exceto pelas provisões necessárias para a viagem. E lembre-se de não falar com ninguém sobre isso. Você entende?",
"Bom, então navegue para #sisland_Antigua# e Cove assim que puder. Aqui está o seu dinheiro para abastecer seu navio e certifique-se de pousar durante o dia.",
"Obrigado, senhor Cutler. Partirei assim que meu navio estiver pronto.",
"O que! Quem! Oh! é você, ",
". Você se atreve a mostrar seu rosto aqui depois de me trair e matar meus homens. Seu idiota!!!",
"Não tanto o tolo. Eu peguei você cochilando, não foi? ... E fique longe desse fogo, o que você está fazendo?",
"Mantendo minha promessa ",
". Eu disse que iria marcá-lo como pirata e mantive o ferro no fogo desde seu ato traiçoeiro em #sisland_Antigua#. Experimente ISTO para ver o tamanho!!!",
" AHHHHHHH! ... SUÍNOS... você vai pagar caro por isso. Marque-me como pirata, sim? Prepare-se para morrer...",
"Eu acho que não! Guardas, Guardas! Pegue esses idiotas... vamos enforcá-los pela manhã.",
"Não sem luta você não vai",
"Seu idiota ",
", você deveria saber que não deve pensar que pode escapar de mim.",
" Como você sabia que eu estaria aqui?",
"Hmph! Insultos vindos de um ladrão de navios! Não importa, ",
", eu tenho você agora e desta vez você não vai escapar. Para ter certeza disso, levei sua amiga sob custódia e meus homens queimaram seu navio. Ela está afundando bem, você não acha? Agora entregue as partes do Mapa Cortez.",
"Beckett, seu cachorro... Você vai pagar por isso! Na verdade você já tem... Veja, as partes do mapa estavam a bordo da minha nave, e você as destruiu, junto com a nave.",
"Ha! Ha! Ha! Palavras tão corajosas. Pelo que me lembro, você os costurou em suas roupas. Não se esqueça, estou com sua namorada e sua tripulação. Se não quiser vê-los todos enforcados agora, embarque no navio dos meus homens e navegue para a Jamaica. Veremos a veracidade do mapa quando chegarmos lá.",
"Parece que não tenho escolha no momento. Mas minha vez chegará. Você também não deve esquecer, eu sou o Capitão Jack Sparrow!",
"Oh! Na verdade, será... a sua vez de ser enforcado! E farei questão de lembrar que era o 'Capitão Jack Sparrow' pendurado no laço. Agora vá para o navio. A vida da sua namorada depende disso.",
"Tudo bem. [PENSA: Eu tenho que fazer alguma coisa. Não posso me voluntariar para ser enforcado assim. Mas Anamaria e a tripulação estão presos e não tenho para onde ir. Melhor seguir em frente por enquanto, tenho que esperar o momento oportuno. Para o navio do cachorro, é isso.]",
", nos encontramos novamente.",
"Senhor Cutler...",
"Sir Cuthbert... Estou feliz em vê-lo. Agora tenho três peças do Mapa Cortez.",
"Nós tinhamos um acordo, ",
". Contratei você para entregar carga em meu nome; você escolheu liberá-lo.",
"Pessoas não são 'carga', cara. ... Espere um minuto! ... Meu navio! ... Em chamas! ... POR QUE meu navio está pegando fogo?",
"Esse é o preço que você paga por quebrar nosso contrato. Parte do preço, isto é.",
"Não, não é meu navio... Nhhh... E minha tripulação! Você vai queimá-los vivos!",
"Oh não! Capitão, a sua tripulação está em segurança a bordo do meu navio. Fechado a sete chaves, é claro.",
"Beckett, seu vira-lata imundo, nojento e sarnento!",
"Oh! isso é rico e tão engraçado! Eu destruo sua nave, e agora recebo as partes do mapa que você tinha e você fez todo o trabalho para mim. Quer você quisesse ou não. Oh! isso é muito rico!",
"Mas eu não era seu inimigo, PODERIAMOS ter chegado a algum tipo de acordo... E esse é o navio da Companhia que você está queimando, não é?",
"Ah! O navio. Achei que você acabou de dizer que era o seu navio? Haha, só estou garantindo que não acabe nas mãos erradas novamente. Fui informado que você se tornaria um problema pouco depois de eu entregá-la a você, mas deixei você brincar com ela mais um pouco.",
"Embora fosse adequado aos seus propósitos malignos e gananciosos. Em toda a história das escórias humildes, você é o mais baixo dos baixos, senhor.",
"Os meus homens indicam que apenas uma quantidade moderada de ouro foi entregue. Não é o retorno do meu investimento que eu esperava, capitão. Não era nada do que eu esperava. De qualquer forma, me dê o pacote. Aqui está o seu dinheiro",
"Meus homens estão me indicando que há pouco ouro na remessa. Um retorno muito fraco do meu investimento, Capitão. Um retorno muito pobre, de fato! Certamente não é digno de pagamento. De qualquer forma, me dê o pacote.",
"Tenho trabalhado com você... bem, com um homem chamado Beckett, para a Companhia Comercial das Índias Orientais. Tenho os documentos da Empresa para provar isso.",
"O Governador conhece você e falou bem de você, o que é uma vantagem para você. Quanto aos documentos, examinei-os e são reais. Então, estou me perguntando como eles surgiram. Isso nos leva ao 'seu' Beckett... Onde você o conheceu?",
", Estou preparado para considerar o passado como passado... SE você estiver preparado para servir esta causa.",
"Ah! a causa. E qual é exatamente a causa? Senhor Cutler.",
"Como afirmou o Governador, os franceses decidiram invadir estas ilhas com a ajuda dos piratas. Devemos evitar que esta aliança aconteça a todo custo. Você está conosco?",
"Sim, senhor Cutler. Eu estou contigo. Qual é a sua estratégia no assunto?",
"Não, senhor Cutler. Eu preferiria seguir meu próprio caminho e, portanto, dizer-lhe adeus.",
"Lamento, Capitão, isso não será possível. Você sabe demais, e como não está conosco, e como um pirata conhecido, você agora é o inimigo. Capitão Norrington, você pode ajudar no que devemos fazer?",
"[Norrington] Certamente, Sir Cutler, seria um prazer... Desembainhe sua espada e prepare-se para conhecer seu criador ",
"Os franceses, vindos da Europa, terão uma linha natural de abordagem a partir do nordeste, que como sabem os levará à ilha #sisland_Turks# ou #sTortuga#, ambas ilhas piratas, onde terão de reabastecer os seus abastecimentos.",
"Sim, Sir Cutler, essa parece ser a linha de abordagem mais lógica.",
"De fato, de fato. O capitão Norrington, portanto, posicionará sua frota a meio caminho entre #sisland_Turks# e #sTortuga#, para não ser detectado, e quando virmos para qual ilha os navios franceses se dirigem, Norrington atacará, antes que eles possam chegar a terra. Eles estarão cansados e fracos da longa viagem e provarão ser uma força de combate menor, e quando Norrington os derrotar, os piratas não ousarão ir ao mar contra nós.",
"E minha parte neste empreendimento? Senhor Cutler.",
"Sua parte, ",
", é navegar para fora das ilhas, localizar a frota francesa, determinar para qual ilha eles se dirigem e então avisar o capitão Norrington para que ele possa atacar o mais rápido possível.",
"Entendo, senhor Cutler. Mas, se me permitem a ousadia, o seu plano tem duas falhas principais.",
"IMPERFEIções! IMPERFEIções! Seu cachorro atrevido! Explique-se!",
"Sim, senhor Cutler. Em primeiro lugar, há muito tráfego entre #sisland_Turks# e #sTortuga# para que a frota do bom capitão passe despercebida. Uma vez avistado, um navio pirata partirá e avisará a frota francesa sobre sua presença. Se você está ciente da chegada iminente dos franceses, pode ter certeza de que os piratas também estão cientes.",
"Hmmm! E seu segundo ponto, capitão.",
"Em segundo lugar, os franceses têm uma marinha experiente, Sir Cutler. Eles não navegarão com toda a frota de uma só vez. Eles terão uma vanguarda à frente da frota principal. É isso que o capitão Norrington atacaria, entregando assim a sua posição à principal frota francesa, que teria então tempo para escolher a ordem da batalha.",
"Ah! Bons pontos, capitão. Você tem um plano melhor, eu presumo?",
"Sim, senhor Cutler. Precisamos formar uma aliança com os piratas e afastá-los dos franceses.",
"Relaxe, meu querido capitão. Faço parte do partido do governador, o governador precisa de tempo para conversar com as filhas depois da provação, então vim aqui para uma bebida tranquila. Ouvi tudo sobre o dramático resgate das filhas dele, foi assim que fiquei sabendo de você.",
"Ah! Eu vejo.",
"Na verdade Capitão. Na verdade, isso me leva a uma proposta que tenho para você e que você achará muito lucrativa.",
"Preciso que você navegue até Muscetto Cove em #sisland_Antigua# e pegue uma carga muito especial. Não fale com ninguém sobre o assunto. Isso é muito importante, então pagarei 50 mil agora e 50 mil quando você entregar na outra costa da Jamaica. Estarei lá para te conhecer. Você está interessado?",
"E leve estes documentos de identidade da Companhia das Índias Orientais. Eles ajudarão você a reprovisionar em #sisland_Antigua# caso seja necessário.",
"Preciso de uma escolta para a Jamaica e poderíamos aproveitar essa viagem para verificar suas habilidades. A Companhia pagará a você 3.000 em ouro quando chegarmos em segurança.",
"Ainda não, capitão, executaremos as formalidades na Jamaica. Tenho certeza de que você tem coisas para fazer, então encontrarei você no porto quando estiver pronto para navegar.",
"Levei a sua tripulação sob custódia a bordo do meu navio. Também estávamos observando a praia, então também estou com a dona Anamaria sob custódia, e agora você completa o cenário.",
"Suas provocações são irrelevantes. Esta noite farei com que você seja rotulado de pirata. Amanhã você será pendurado no meu braço",
"O amanhã ainda está por vir.",
"Então você morrerá, logo seguido pela Srta. Anamaria, depois por cada membro de sua tripulação, de forma muito dolorosa, devo acrescentar.",
"Bem, bem, Capitão Jack Sparrow... Gostaria de vê-lo aqui.",
"Beckett, você finalmente me alcançou.",
"Foi o que fiz, Jack, e tenho medo de pegar seu navio e mandar enforcá-lo. Sem ressentimentos. É apenas um bom negócio...",
"Eu vou te dar negócios!",
"Adeus, Jack Sparrow.",
"Eu poderia ser. O que você tem em mente? Ainda não tenho certeza se quero ingressar na East India Trading Company, Sir Beckett.",
"Sobre o que você ainda está rabiscando? Esteja no seu caminho!",
"Sim senhor. Imediatamente, senhor.",
"Fui informado que você comanda a 'Wicked Wench'. Você deve saber que ela pertence à East India Trading Company. Ela foi capturada pelo governador Brin enquanto cuidava de seus negócios legais. Aparentemente, o governador, embora tolerante com os piratas, não gostou de algumas de nossas práticas comerciais e decidiu ordenar o internamento do navio.\nMas como você é o capitão dela e agora trabalha para a Companhia, o navio está de volta à Companhia. mãos.\nClaro, você entende que, caso deixe o serviço da Empresa, precisará nos devolver o navio.",
"Excelente! Excelente! Você mais que dobrou o investimento da Empresa em você. Você é realmente um ativo para a Empresa. Você não precisa de mais treinamento e está pronto para assumir uma função plena na Empresa.",
"Obrigado, senhor Cutler.",
"Posso viver com esses termos. [PENSA: Porque se eu sair da Companhia, a 'Wicked Wench' vai embora comigo!] Que papel você tem em mente para mim?",
};
