string DLG_TEXT[100] = {
"Olá... Capitão?",
"Capitão ",
"Eu sei perfeitamente o que você está procurando: Senhorita Justine Le Moigne.",
"Certo. Quem te disse isso?",
"O governador de #sPhilipsburg#. Posso dizer que ele trabalha para mim.",
"Eu entendo. Tive a sensação de que ele escondeu a verdade de mim. Mas por que você sequestrou a filha do Governador? Por um resgate?",
"Não sou um pirata como os outros, capitão, estava em busca do amor e o encontrei desde que a conheci.",
"E ela te ama?",
"Humm..humm... não por enquanto, mas ela vai me amar no futuro. Acho que ela não parece apreciar a vida a bordo...",
"Sim? Talvez eu possa resolver seu problema.",
"Como?!",
"Deixe-a temporariamente sob a autoridade do governador de #sPhilipsburg# e em troca convencerei o governador Le Moigne a desistir de trazê-la de volta para #sFalaise De Fleur#. Como prova de boa vontade, deixe-me levá-la para #sPhilipsburg#.",
"É muito arriscado. Eu não confio em você.",
"Por que? Enquanto eu esperava por você, um tripulante me disse que você gosta de jogar dados mentirosos.",
"Sim, mas por que você fala disso agora?",
"Quem vencer levará Justine para #sPhilipsburg#.",
"Aceito sua oferta de deixá-la sob a autoridade do governador de #sPhilipsburg#, mas vou levá-la para lá.",
"Você tem medo de brincar comigo?",
"Você está brincando? Eu me considero o melhor jogador. Pegue a xícara e os dados, vou te dar uma lição.",
"Quantas rodadas?",
"Apenas um. Vamos jogar! Eu lancei quatro quatros.",
"humm...eu lancei quatro cincos.",
"Ah! Sete cincos!",
"Oito cincos!",
"Você mente! Mostre-me seus dados!",
"Eu tenho quatro cincos e você também. Você perdeu.",
"Vá em frente! Ok, você pode levá-la, mas não tente me enganar, senão eu mato você!",
"Entendido, nos vemos em #sPhilipsburg#.",
"Traidor! Você acha que pode me levar para passear?!",
"Desculpe, capitão!",
"E você acha que vou perdoar o que você fez?!",
"Não me arrependo do que fiz, mas sim do que vou fazer.",
"O que você fez?",
"Eu sei perfeitamente o que fiz. Justine me disse que durante a viagem você só pode pisar em terra uma vez a cada dez anos, então quando te vi perto do mar pensei imediatamente em empurrá-lo para dentro da água. Agora, você não pode recapturá-la.",
"MALDITO ",
"Você parece e cheira como um rato afogado! Aqui estão algumas roupas novas. De qualquer forma, você tem sorte de estar vivo... e ainda mais sorte de ter me encontrado.",
"Quem é você? Onde estou?",
"Eu sou Davy Jones, alguns dizem que é o rei do mar, e você pode estar onde eu preferir. Você só está aqui porque atende ao meu propósito.",
"Bem, isso são boas e más notícias. Eu estava a caminho de ser enforcado, então estou salvo disso, mas não tenho navio, ele foi queimado e afundado. Não sei o que fazer a seguir.",
"Uma história triste, de fato, mas eu sei disso. Posso ajudá-lo em sua hora de necessidade... por um preço.",
"Assistência que eu poderia usar. Mas a que preço, quanto dinheiro você quer?",
"Não preciso de dinheiro. Preciso que você navegue comigo. Estou em uma missão e preciso de uma boa tripulação e de homens como você.",
"Eu sei que não estou em posição de negociar aqui, mas sou dono de mim mesmo e tenho assuntos para resolver, então não acho que poderia assinar com você, senhor.",
"Ouça meus termos. Eu levantarei seu navio e lhe darei treze anos para cuidar de seus próprios assuntos. Então você me dará sua alma e navegará comigo por cem anos.",
"Você me permitirá treze anos sozinho, sem interferência?",
"Essa é a minha palavra. Decida agora ou vou deixá-lo aqui... com um destino incerto.",
"Muito bem, aceito seus termos. [PENSA: Treze anos, é tempo mais que suficiente para sair dessas condições.] ",
"Não, isso é um custo muito alto. Vou me defender sozinho e confiar na fortuna da senhora.",
"Que assim seja... Após suas ações, você deve considerar se juntar aos Irmãos da Costa no assentamento pirata em #sisland_Quebradas Costillas#. Você também pode querer se familiarizar novamente com o Capitão Barbossa.",
"Onde posso encontrá-lo e como posso voltar para minha nave?",
"Como qualquer pirata famoso, ele pode ser frequentemente encontrado na taverna de #sTortuga#. Quanto ao seu navio, vire-se e caminhe em direção à costa e depois para o mar. Você encontrará seu navio esperando lá.",
"Muito bem.",
"Então você verá agora o quanto a senhora fortuna pensa de você! Se você reconsiderar, ainda poderá me encontrar em meu esconderijo secreto, perto de um templo nativo.",
"Não chegaremos a esse ponto. Eu faço o meu próprio caminho, isso prometo!",
"Você realmente achou que poderia escapar de mim se continuasse a navegar pelos mares ",
"Hum...",
"Huh Hah... Combinado! Você nunca mais ouvirá falar de mim, capitão ",
", a menos que nosso acordo seja quebrado!",
"Isso é bom de ouvir.",
"Haha... Tudo bem! Eu verei você novamente ",
"Mal posso esperar.",
"Olá novamente Capitão Jack Sparrow, sou eu Davy Jones, voltei para transportar as almas perdidas no mar para o Locker, mas vim aqui porque vejo que você precisa de ajuda.",
"Bem, isso são boas e más notícias. Eu estava a caminho de ser enforcado, então estou salvo disso, mas não tenho navio. Ela estava queimada e afundada. Não sei o que fazer a seguir.",
"Bem, Jack Sparrow, vou levantar seu navio do Armário, isto é um agradecimento por você me trazer Cal.. um Tia Dalma. E leve essas roupas também.",
"Muito obrigado, David Jones.",
"Olá... Capitão Jack Sparrow",
"Como você sabia meu nome... experiente?",
"Você se lembra da dívida que me pagou? Eu levantei seu navio para você! Agora, por que você está aqui agora: eu sei perfeitamente quem você está procurando: Srta. Justine Le Moigne.",
"Ah sim, esse acordo! Quem te disse que eu estava procurando a senhorita Le Moigne?",
"Decidiu que você pode ter cometido um erro quando nos conhecemos? Achou que é hora de conhecer seu destino, afinal?",
"Na verdade, parece que meus esforços não levaram a lugar nenhum.",
"Lembre-se, você tem 13 anos e nem um dia a mais. Depois disso, sua alma pertence a mim!",
"Ah, sim, como eu poderia esquecer. Estarei ansioso por isso com a respiração suspensa.",
"Você teme a morte? Você tem medo desse abismo escuro? Todas as suas ações expostas. Todos os seus pecados punidos. Eu posso te oferecer... uma fuga-uh.. [Fuma um cachimbo usando tentáculos]",
"O último brilho do luar que morre no amanhecer do seu último dia. E então - Julgamento. Todas as suas ações expostas. Seus pecados punidos. Posso oferecer-te uma fuga..",
"Você não teme a morte? [Fuma cachimbo]",
"Para as profundezas com ele.",
"A vida é cruel. Por que a vida após a morte deveria ser diferente? Você se apega à dor da vida e teme a morte. Eu ofereço a você a escolha. Junte-se à minha tripulação... e adie o julgamento. Cem anos antes do mastro.",
"Você vai servir?",
"Você não está morto nem morrendo. Qual é o seu propósito aqui?",
"Jack Sparrow me enviou para saldar sua dívida.",
"De novo. Qual é o seu propósito aqui?",
"Jack Sparrow me enviou... para saldar sua dívida.",
"Ele fez isso agora? Estou extremamente tentado a aceitar essa oferta.",
"Você tem uma dívida a pagar. Você é capitão do Pérola Negra há treze anos. Esse foi o nosso acordo.",
"Tecnicamente, fui capitão apenas por dois anos, depois fui violentamente amotinado.",
"Então você era um pobre capitão. Mas mesmo assim um capitão. Você não se apresentou todo esse tempo como Capitão Jack Sparrow?",
"Não que eu me lembre, por que você pergunta? Você tem meu pagamento. Uma alma, para servir no seu navio. Ele já está lá.",
"Uma alma não é igual a outra.",
"Ah, então estabelecemos que a proposta é sólida em princípio. Agora estamos apenas negociando o preço.",
"Como já aconteceu antes, sinto-me estranhamente compelido a ouvi-lo.",
"Quantas almas você acha que minha alma vale?",
"Cem almas. Três dias.",
"Você é um diamante, cara. Manda-me de volta o rapaz, vou começar já.",
"Eu fico com o menino. Um pagamento de boa fé. Isso deixa-te apenas mais noventa e nove.",
"O que? Você conheceu Will Turner? Ele é nobre e heróico, um excelente soprano... vale pelo menos quatro.",
"Eu fico com o menino. Noventa e nove almas, uh. Mas eu me pergunto, Sparrow, você consegue conviver com isso? Você pode condenar um homem inocente, um amigo, a uma vida inteira de servidão, em seu nome enquanto você anda livre?",
"Sim! Estou bem com isso. Devemos selá-lo com sangue? Quero dizer... mm-mm - tinta?",
"Três dias... Três dias.",
"Eu te abraçaria, mas temo que isso possa persistir.",
};
