string DLG_TEXT[93] = {
"Não acredito que já tenha visto você aqui antes, meu bom homem.",
"Sim, é minha primeira vez aqui. Meu nome é ",
".",
"E daí? Você se lembra do nome e do rosto de todos?",
"Eu sou ",
", o dono desta taberna.",
"Prazer em te conhecer, ",
". O que você tem a oferecer aqui, além de uma caneca e um ouvido atento?",
"Relaxe, não estou querendo lhe causar nenhum problema. Meu nome é ",
", e estou aqui para conversar sobre negócios com você e depois cuidar dos meus.",
"Bem bem. Estou ouvindo.",
"Estou procurando uma tripulação. Talvez você possa me dizer quem está procurando um navio",
"Minha última viagem me deixou com poucos tripulantes. Aponte-me bucha de canhão adequada aqui em sua taverna e eu irei embora.",
"Só preciso de algumas informações, se você tiver um minuto",
"Você tem um berço que eu não preciso dividir com mil insetos?",
"Preciso de um quarto limpo com uma cama. Ênfase na limpeza.",
"Desculpe, não tenho tempo para conversar. Contanto.",
"Isso realmente depende do que você quer dizer ",
".",
"Eu aprendi isso ",
"Raoul Rheims",
" chegou a esta cidade recentemente.",
"Estou procurando um homem chamado ",
"Raoul Rheims",
"Raoul Rheims",
". Você sabe se ele esteve nesta ilha?",
"Estou procurando por ",
"Ferro Cerezo",
"Ferro Cerezo",
". Talvez você saiba onde posso encontrá-lo.",
"Procuro um certo homem que veio para a ilha há pouco tempo. Ele é italiano, um homem mais velho. Isso soa alguma coisa?",
"Estou interessado em alguém chamado Artois Voysey. Ele é um jovem alto com cabelos escuros. Ele apareceu por aqui?",
"Eu preciso de algum trabalho. Você não conhece nenhum garoto rico nesta ilha que tenha medo de viajar sozinho?",
"Vamos mudar de rumo e falar sobre outra coisa.",
"Sim, eu o vi, mas duvido que isso vá te deixar feliz.\nVeja, esse rapaz entrou aqui com algum canalha, e cinco minutos depois a porta se abre e dois vilões com máscaras pretas entram.\ nEles levaram seu Artois com eles e feriram gravemente o amigo dele. Ele está em um dos quartos lá em cima agora.",
"Mil maldições! Eu preciso vê-lo! Talvez ele saiba quem são esses encrenqueiros mascarados.",
"Agora, deixe-me pensar... Ah, mas é claro! Senhor ",
"Vito Leone",
" corresponde bastante à sua descrição. Ele veio há uma semana e alugou um quarto comigo. Ele disse que alguém viria procurá-lo e me pediu para avisar que está esperando por você na igreja.",
"Obrigado!",
"O homem sentado à mesa perto da janela tem esse mesmo nome, se não me engano.",
"Obrigado. Vou dar uma olhada nele.",
"Controle-se! As paredes têm ouvidos, meu amigo.",
"E daí? Não tenho segredos.",
"Tenha cuidado! Dizem que o homem trabalha para ",
"Desmond Ray Beltrop",
"Desmond Ray Beltrop",
" ele mesmo, chefe dos contrabandistas por aqui. Prefiro não ter problemas com ele. Ruim para os negócios.",
"Sim, ",
"Raoul Rheims",
" está na ilha. Você o encontrará com ",
"Desmond Ray Beltrop",
"? Como posso encontrá-lo?",
"Essa é a primeira vez que ouvi falar disso. Talvez você esteja enganado.",
"Tenho certeza de que ele chegou aqui há vários dias. Ele deveria se encontrar com ",
"Desmond Ray Beltrop",
"Desmond Ray Beltrop",
".",
"Quieto! Se você valoriza sua vida, não voltará a dizer esse nome em voz alta. Olhar! Você viu aquele homem que acabou de sair da taverna? Fugir! Vá agora, ou você vai derrubar o céu na minha cabeça!",
"Controle-se, cara! Você está tremendo... e nem sabe de nada útil, não é? Bah. Adeus!",
"Relaxar! Posso ver que você não será útil para mim. Adeus!",
"Desculpe, mas é muito tarde. Todo mundo já encontrou um lugar para passar a noite. Volte pela manhã, se quiser. Ou você pode passar uma noite aqui na taverna.",
"Talvez eu vá. Você tem um quarto?",
"Talvez eu faça exatamente isso. Mas por enquanto, tenho mais algumas perguntas.",
"Acontece que tenho uma vaga. Quanto tempo você planeja ficar?",
"Até de manhã.",
"Só até a noite cair.",
"Vai custar 5 ouro.",
"Multar. Aqui está o seu dinheiro.",
"Infelizmente, parece que uma cama está fora do meu alcance no momento. Vou dormir na taberna.",
"Você quer quanto?! Eu ganho uma cesta de frutas com isso? Obrigado, mas vou dormir na taverna.",
"Vou considerar isso. Enquanto isso, preciso de mais algumas informações.",
"Vai custar 5 ouro.",
"Aqui está o seu dinheiro.",
"Infelizmente, isso é mais do que gostaria de gastar. Vou dormir na taberna.",
"Para que serve isso, um quarto king-size? Não, obrigado, vou dormir na taverna",
"Vou pensar sobre isso.",
"Este é um estabelecimento respeitável! Pare imediatamente, ou chamarei os guardas!",
"Tudo bem, tudo bem. Estou indo embora!",
"Se existe tal pessoa, ela pode preferir evitar atrair a atenção de tantas consortes - como eu espero que você saiba.",
"Sim, esqueci. Tudo bem, voltarei mais tarde, quando tiver menos navios, ha-ha.",
"Não quero ajudá-lo, com todo o mal que você causou ao meu país.",
"Tudo bem. Até a próxima.",
"Suas mãos estão cobertas de sangue. Você acha mesmo que alguém vai viajar na sua companhia?",
"Você está certo, todo mundo tem medo de mim! Ha-ha!",
"Você chegou bem na hora. Um comerciante aqui estava procurando navegar na companhia dos companheiros certos. É melhor você falar com ele. Aqui está ele, entrando na taverna.",
"Eu farei isso.",
"Não, não há ninguém naquele momento, Talvez da próxima vez.",
"Hum. Então vou esperar.",
"Procuro um homem chamado Beckett. Você já viu ou ouviu falar dele?",
"Somente o Governador de #sRedmond#, fora isso... nunca ouvi falar dele.",
"OK. obrigado",
"Você pode tentar falar com aquele monge ali. Eu ouvi alguém mencionar o nome perto dele mais cedo.",
"",
};
