string DLG_TEXT[174] = {
", meu filho! Como este humilde servo de nosso Senhor pode ajudá-lo?",
"Eu sou ",
", capitão e proprietário do navio'",
".",
"Bem-vindo à casa de nosso Senhor, ",
" meu filho. Fico feliz em ver um marinheiro que não descuida da alma.",
"Olá, ",
". Então - você está aqui para se confessar?",
"Meu filho, estou feliz em vê-lo e estou pronto para aceitar sua confissão, se você a der livremente. O Senhor sabe que o pecado é inevitável na vida terrena.",
", Gostaria de dar um presente à Igreja.",
"Preciso falar com você, padre.",
"Obrigado. Talvez na próxima vez.",
"Tenho o prazer de dar as boas-vindas a uma nova ovelha em nosso rebanho",
". ",
"Então, por favor, aceite meu presente.",
"Posso falar com você, padre?",
"Obrigado, padre, mas preciso ir.",
"Isso diz respeito à sua fé, meu filho?",
"Talvez. Não posso deixar de notar que você parece preocupado com alguma coisa. Posso te ajudar de alguma forma?",
"Isto diz respeito ao negócio que você me confiou.",
"Possivelmente. Posso ver em seu rosto que algo o perturba. Talvez eu possa ajudar.",
"Eu tenho uma carta para você.",
"Inconcebível! ",
"Padre Gareth",
", servindo ao Príncipe das Trevas? Quem poderia imaginar? Porque como...",
"Agora sei quem é o culpado pelos meus problemas recentes. Foi ele quem relatou todos os meus movimentos aos monges!",
"Preciso de permissão para libertar um prisioneiro detido em #sisland_Oxbay#.",
"Consegui adquirir a permissão que você pediu. Sugiro também que você leve esse uniforme, vai te ajudar a libertá-lo. Aqui estão eles - e por favor, lembre-se da minha fé em você.",
"Não se preocupe - eu farei certo",
"Não. Vamos conversar sobre outra coisa.",
"Há mais - meus homens e eu destruímos a seita.",
"Não. O problema é que há um homem que gostaria de doar uma certa quantia de ouro para sua igreja. Estou atendendo ao pedido dele.",
"Hum... Não. Vamos mudar de assunto, certo?",
"O Senhor nos proporcionou um milagre! No entanto, ouvi dizer como você atendeu ao meu primeiro pedido e não posso permitir que você se faça passar por um homem de Deus, e também parece que você ainda tem as mulheres com você. Eu acho que você é o sequestrador!",
"Sinto muito, mas tenho que ir a Cingapura para devolver as mulheres e você não pode me impedir. (PENSA: Maldito Ammand, o Corsário, deve ter contado a ele).",
"Suponho que você chamou os guardas, vou escapar porque sou o capitão Jack Sparrow",
"Eu não acredito nisso. Este prisioneiro é um daqueles que você me pediu para destruir.",
"Mas se é assim, então por que libertá-lo?",
"Vou precisar ganhar a confiança dele. Ele sabe onde fica o covil deles e será muito mais provável que me diga se acreditar que estou do lado dele.",
"Eu entendo. Sim, vou ver o que posso fazer. Espere aqui.",
"Tudo bem.",
"São pessoas misteriosas, servos do diabo!",
"Como você diz, padre. Mas todos eles usavam máscaras.",
"É ainda mais fácil ganhar a confiança daqueles que desejam corromper. Devemos encontrar o covil desses demônios! Capitão, você acha que poderia viajar para #sIsla Muelle# para nós e fazer algumas perguntas lá?",
"Sim absolutamente. Ainda estou procurando aquelas mulheres desaparecidas.",
"Que o bom Deus esteja com você, meu filho.",
"Eu não vou falhar com você.",
"Claro, meu filho. Mas espere, antes de ir, há outra coisa que preciso fazer. Eu gostaria de apresentar alguém...",
"Sim?",
"Mas estamos perdendo tempo. Você aceita minha oferta?",
"Pelo que me lembro, você me ofereceu 15.000 peças de ouro pelo fim da seita. Correto?",
"Graças a Deus! Eu me perguntei se você tinha chegado a tempo para ",
"Padre Domingues",
" para passar esta carta para você.",
"Sim, embora esteja se tornando cada vez mais perigoso trabalhar para você, padre. Fui atacado e quase morto por homens com máscaras pretas que queriam tirar-me esta carta. E lamento informar que assassinos sequestraram Padre Domingues.",
"Sim, essa infeliz notícia chegou aqui antes de você. Receio que os nossos piores medos se tenham concretizado.",
"O que você quer dizer?",
"Vários anos atrás, um covil satanista foi destruído na Itália. Infelizmente, o chefe dessa ordem conseguiu escapar, e ultimamente há evidências de que ele se estabeleceu aqui neste arquipélago com alguns dos seus seguidores. Agora, a julgar pelos desaparecimentos de mulheres e agora de um sacerdote de alto escalão, ele está ativo novamente e pretende realizar um certo ritual antigo e profano.\nTodo o arquipélago está em perigo, capitão! Devemos detê-lo!",
"Eu vejo. Esta é a conexão com o 'Sangue Carmesim' e com as mulheres que tenho procurado. Como posso ajudar?",
"Precisamos que você sirva como a espada rápida de nosso Senhor, realizando Sua vingança. Mas pelo que entendi você é um homem de, ah... negócios, ofereço-lhe 15.000 peças de ouro pelo seu serviço à Igreja.",
"Bem, comecei tudo isto para ajudar aquelas mulheres pobres de Singapura. Mas devo admitir, sua oferta não é ruim...",
"É uma bênção do Senhor que você esteja aqui agora. Eu preciso da sua ajuda.",
"Estou ouvindo, padre.",
"Receio que a sua má fama me impeça de pedir a sua ajuda nos assuntos da Igreja.",
"Francamente, isso não me preocupa muito.",
"Ajudarei você em tudo que puder, meu filho. No entanto, preciso alertá-lo: minha nova tarefa é urgente e muito mais complexa do que possa parecer inicialmente.",
"Hm... Talvez você tenha a gentileza de me dar os detalhes?",
"Algumas mulheres foram raptadas da Ásia e trazidas para o Caribe...",
"Incrível. Esse é o assunto da minha investigação. Você sabe alguma coisa sobre isso?",
"Hum. Nós não sabíamos disso. Acho que suas notícias podem explicar algumas coisas. Parece que minha próxima tarefa para você pode nos trazer informações de que todos precisamos.\nGostaria que você entregasse uma mensagem para #sIsla Muelle# e a entregasse a um homem chamado ",
"Padre Domingues",
"Padre Domingues",
".\nEle é um sacerdote graduado da Igreja na Espanha. Ele lhe dará mais instruções, se necessário, para ajudá-lo nessa busca.",
"Isso parece muito simples. O que o torna tão complexo?",
"E foi uma maneira infeliz de descobrir. Nosso acólito era um rapaz bom e decente, e sua morte sem sentido entristece a todos nós.",
"Ah. Então, como seu mensageiro recém-nomeado, alguém pode tentar me matar também, para impedir que esta carta chegue ao seu destino.",
"Receio que isso seja verdade. Nós entenderemos se você recusar.",
"Oh, o dinheiro é bom demais para ser recusado, padre.",
"Você é corajoso e engenhoso, capitão. Isso certamente ajudará. Aqui está a carta. Lembre-se, você deve dar para ",
"Padre Domingues",
", e apenas para ele. E você o encontrará em #sisland_Isla Muelle#.",
"Tudo bem. Isso não deve demorar muito.",
"O que você conseguiu descobrir?",
"Padre Jerald",
"Nada ainda.",
" é culpado dos crimes de que é acusado.",
"Padre Jerald",
"Padre Jerald",
" é inocente dos crimes de que é acusado.",
"De fato! Você tem prova disso?",
"Eu faço. Estas cartas parecem manchar a reputação do padre - mas na verdade foram escritas pelo seu assistente.",
"Que engano cruel! Vou resolver isso imediatamente. Você fez um excelente trabalho a serviço da Igreja e estou feliz em lhe dar esta recompensa como agradecimento.\nPor favor, continue me visitando de vez em quando - estou constantemente precisando da ajuda de alguém com seus talentos particulares.",
"Obrigado pai. Acho que vou agora.",
"De fato! Você tem evidências disso?",
"Sim. Essas cartas contam toda a história.",
"Oh meu Deus, entendo. Eu estava rezando para que não fosse verdade. Mas você fez seu trabalho. Aqui está sua recompensa, capitão.\nPor favor, continue me visitando de vez em quando - tenho certeza de que precisarei de seus serviços novamente mais tarde.",
"Obrigado pai. Acho que vou agora.",
"Não tenho certeza se você consegue, meu filho. Veja, preciso de ajuda em um assunto sério e preferiria encontrar essa ajuda fora da Igreja.",
"Algumas pessoas diriam que estou muito fora da Igreja, Padre. Mas sou capitão de navio; diga-me o que o incomoda e talvez eu possa ajudar.",
"Receio que sua reputação não me permita aceitar sua ajuda.",
"Justo.",
"Tudo bem. Sinto que posso confiar em você. Mas deixe-me ouvir você jurar que ninguém saberá desta conversa.",
"Você pode considerar-se no meu confessionário, Padre.",
"Multar. Então ouça: chegaram até mim rumores de que um de meus irmãos na fé esqueceu seus votos ao Senhor e está atolado em pecado. Infelizmente, não posso deixar meu rebanho para verificar esses rumores sozinho, e isso só levantará suspeitas se eu enviar alguém de nossa irmandade.\nAlém disso, somente eu posso desafiá-lo para tal conversa e examinar sua alma. para ver se ele está me dizendo a verdade...",
"Então... você está me pedindo para reunir provas contra um de seus colegas padres?",
"De jeito nenhum! Não, eu simplesmente desejo saber se ele é ou não culpado dos pecados dos quais é acusado. Se ele é inocente, preciso saber quem manchou sua reputação.",
"Tudo bem, padre. Dê-me o nome dele e verei o que posso descobrir.",
"Ele serve a Igreja em #sGreenford#. O nome dele é ",
"Padre Jerald",
"Padre Jerald",
". Deve ser fácil encontrá-lo quando você chegar lá.",
"Voltarei o mais rápido possível, padre.",
"Que o bom Deus o guie à verdade, meu filho. Venha aqui e aceite minha bênção.",
"Fique tranquilo, pai. Tenho certeza que tudo ficará bem.",
"Muito bem. Mas é meu dever dizer-lhe que tal desrespeito pela sua fé é imprudente.",
"Como você diz. Por favor, aceite meu presente para a Santa Igreja.",
"Sinto muito, padre, mas tenho que ir.",
"Claro, meu filho. Quanto você quer dar à Santa Igreja?",
"Sinto muito, padre, mas acabei de perceber que não posso fazer uma doação no momento.",
"Receio que 100 moedas de ouro sejam tudo o que posso pagar agora.",
"Eu acho que o Senhor olharia com bondade para 1000 moedas de ouro.",
"Estou bem ultimamente, então darei 5.000 peças de ouro.",
"A decisão é sua, meu filho. Nunca é tarde para mudar - e tenha em mente que tudo será levado em conta no momento da sua morte.",
"Minha morte ainda está muito distante, se Deus quiser! Vamos falar sobre outra coisa.",
"Desculpe, padre. Eu tenho que ir.",
"Agradeço-te o teu presente em nome da Santa Igreja, meu filho.",
"Preciso falar com você, padre.",
"Sinto muito, padre, mas preciso ir embora.",
"Agradeço-te o teu presente em nome da Santa Igreja, meu filho.",
"Preciso falar com você, padre.",
"Sinto muito, padre, mas preciso ir embora.",
"Agradeço-te o teu presente em nome da Santa Igreja, meu filho.",
"Preciso falar com você, padre.",
"Sinto muito, padre, mas preciso ir embora.",
"Pai, estou desesperado com a minha luta na vida, gostaria de poder começar tudo de novo...",
"Rezarei por você, meu filho, mas preciso ter certeza de que você está falando sério. Você está disposto a dar ",
" ouro para os pobres e desafortunados deste arquipélago?",
"Oh, filho, o que devo dizer? Rezarei por você novamente, mas desta vez custará mais que ouro. Você vai perder ",
" ponto de habilidade ",
" pontos de habilidade e ",
" habilidade ",
" habilidades ",
"e você tem que dar ",
" ouro para os pobres, para as viúvas e os órfãos! Você aceita?",
"O preço é alto, mas tenho muita certeza de mim mesmo. Eu pagarei, seja qual for o preço.",
"Peço perdão, mas o preço é muito alto. Acho que tenho que aguentar minha vida atual.",
"Senhor, conceda a este homem o poder de começar uma nova vida...",
"Eu te agradeço, Pai! Desta vez terei mais cuidado com as coisas que faço e com o que aprendo. Eu prometo.",
"Meu filho, você não tem o dinheiro necessário para ajudar os pobres. Se realmente é seu desejo começar uma nova vida, você retornará quando tiver merecido ",
" ouro...",
"Voltarei, com certeza...",
"Eu sou ",
". ",
"Só que aconteceu. Estamos todos muito preocupados com isso. O que você descobriu sobre este incidente, meu filho?",
"Eu sei que as mulheres foram embarcadas na corveta pirata 'Crimson Blood' e então ela desapareceu em uma direção desconhecida.",
"Obrigado pai. Estou disponível para ajudá-lo novamente imediatamente, mas também gostaria de receber algumas informações sobre algo que estou investigando pessoalmente. Disseram-me que você pode me ajudar.",
"Obrigado pai. Estou disponível para ajudá-lo novamente imediatamente, mas também gostaria de receber algumas informações sobre algo que estou investigando pessoalmente. Disseram-me que você pode me ajudar.",
"Abençoe você, meu filho, por permanecer corajoso diante do mal e do perigo. Precisamos desesperadamente da sua ajuda.",
"Desesperadamente, Padre?",
"Infelizmente, nosso fiel e jovem mensageiro foi encontrado morrendo nos degraus de sua casa, com um golpe mortal de uma adaga. Sua mãe ficou bastante arrasada, como você pode imaginar. Mas acho que para saber a história completa, você deveria falar com o Padre Gareth, aqui.",
"Muito bem. Padre Gareth?",
"Que o bom Deus vá com você, meu filho. E por favor tenha cuidado.",
"...",
"Estou com medo ",
" ouro é tudo o que posso pagar agora.",
"Eu deveria pensar que o Senhor olharia com bondade ",
"Estou bem ultimamente, então vou dar ",
" peças de ouro.",
"O Senhor nos proporcionou um milagre! No entanto, ouvi como você lidou com meu primeiro pedido e não posso permitir que você se faça passar por um homem de Deus.",
"Estou bastante ciente deste fato.",
"Não tenho nenhuma evidência física. O padre assistente me mostrou cartas que ele alegou terem sido escritas por ",
" para uma jovem, mas descobri que ele os havia forjado. Ele está por trás desses rumores.",
"Não tenho nenhuma evidência física. O padre assistente me deu cartas que ",
" havia escrito para uma jovem. Eles me enojaram tanto que eu os queimei.",
};
