string DLG_TEXT[45] = {
"Oohh... Minha cabeça!",
"O que aconteceu? Você se sente bem?",
"Você não é espanhol?! Quem é você? O que você está fazendo nesta ilha?",
"Não se preocupe! Eu não sou espanhol. Meu companheiro Eduardo Villanueva é, mas é um pirata que saqueia seus navios de tesouro, e esse é o Capitão Chevalle também pirata. Estamos procurando uma mina. Isso teria a prata em #sisland_Battle Rocks#.",
"Você tem razão. Como você sabe disso? Os espanhóis garantem que esta informação permaneça secreta.",
"Parece que eles falharam. E você? Você também está procurando a mina?",
"Essa maldita minha! Foi a origem do meu infortúnio! Quase perdi minha saúde lá..",
"Você poderia explicar melhor?",
"Bem, os espanhóis encontraram a mina há dois anos. Claro, a mina antes pertencia aos índios. Após a descoberta, os espanhóis deportaram dezenas de prisioneiros de suas colônias para trabalharem aqui como escravos. O destino deles é morrer nesta ilha. E acredite que alguns meses desta vida são suficientes para matá-los.",
"Então, você escapou dos espanhóis.",
"Na verdade, ontem à noite. Mas eles não foram os únicos. Pouco tempo depois conheci um grupo de índios e apesar disso também consegui escapar deles, eles me feriram levemente.",
"Humm...Esse pode ser o grupo que lutamos há pouco tempo. Você poderia nos levar para a mina?",
"Você realmente quer ir para lá? A mina é bem defendida por um acampamento militar. E você pode esperar encontrar muitos soldados.",
"Ok, aceito te levar até lá mas com a condição de você liberar meus amigos na mina.",
"Claro, teríamos feito isso de qualquer maneira.",
"Neste caso, siga-me!",
"Muito estranho! Eu esperava mais soldados no acampamento.",
"Mais uma razão para ter cuidado. Diga-me agora onde fica a mina para libertar seus amigos.",
"Está perto do acampamento. Siga-me novamente!",
"Quem é você! O que você está fazendo aqui! Seu nome agora!",
"Meu nome é: VÁ PARA O INFERNO!",
"Ei! François de Hadoque está de volta! Você veio nos libertar?",
"Certo! O tempo para trabalhar nesta mina acabou. Mas eu pensei que você fosse mais...",
"E nós somos! No entanto, muitos de nós tivemos que ir com os soldados ao porto.",
"Que porto?",
"O porto onde a prata é carregada a bordo dos navios, é claro.",
"O que?! Há um trem prateado passando pelo porto?",
"Sim, eles deixaram o acampamento há uma hora.",
"Agora entendo por que lutamos contra poucos soldados. Bem, você e seus companheiros vão para a costa leste. Vou tentar alcançar o trem",
"Espere capitão! Conheço um atalho pela selva para chegar ao porto. Ainda é possível juntar-se a eles.",
"Excelente! Vamos agora.",
"Graças a Deus! Finalmente, estamos livres! Eu sabia que François de Hadoque nos ajudaria depois de escapar do acampamento.",
"Na verdade, seu pesadelo termina. Agora, precisamos sair desta ilha. Qualquer momento pode desembarcar mais espanhóis.",
"Acho que deveríamos sair agora, caso contrário poderemos ser pegos em alguma coisa. Vamos para #sisland_Turks# Island.",
"Eu acho que você pode estar certo. Parece que eles estão prestes a começar a brigar!",
"O que fazemos agora capitão?",
"Leve alguns de seus homens a bordo e mande-os navegar até nossos navios, nós os encontraremos lá. Voltaremos à costa e encontraremos o comboio.",
"Obrigado capitão por navegar comigo para #sisland_Turks#, e também por me dar este lindo navio!",
"Não foi problema, na verdade, François. Como vamos dividir o dinheiro?",
"Bem, existem as 120.000 moedas de ouro que recebemos com a venda da prata. Que tal dividirmos 50-25 entre você e eu, e os outros 25 vão para minha Irmandade para ajudar a montar nossa base?",
"Parece um acordo justo para mim. Então são 60.000 para mim, 30.000 para você e também para sua Irmandade.",
"Sim capitão. Muito obrigado por tudo.",
"Te vejo, François.",
"...",
"...",
"",
};
