string DLG_TEXT[234] = {
"Dê-me um centavo e você me impedirá de chorar ",
" Dê-me um pouco de ouro e você me impedirá de morrer!",
"Eu sei sobre Davy, o Spot e o Kraken. Eu sei sobre os piratas e quem eles estão atacando! Eu poderia contar algumas histórias sobre como os fantasmas podem tocar o homem, sobre o tesouro, a bruxa e o maldito Holandês Voador. Então me dê uma moeda, apenas uma ou diga duas, me faça uma pergunta e veja como eu me saio",
"Oh ",
", ajude um pobre mendigo, você nunca sabe, posso lhe dizer algo que lhe servirá muito bem.",
"Desculpe; Não dou esmolas, principalmente a maus poetas mendigos!",
"Não tenho nada menor que uma peça de ouro. Será que um será suficiente para impedir que você morra de fome por um tempo?",
"Não vou te dar esmola, mas vou deixar você ganhar algum dinheiro se estiver disposto.",
"Obrigado, ",
"! Você será um homem de sorte, veja se não. Cuidado com o velho Davy, o local e o barco!",
"Certo. Você tem sua moeda. Agora, pare com os enigmas e põesias e responda algumas perguntas para mim.",
"Obrigado. Você pode ir agora.",
"Sem dinheiro para Henry ",
"Você é pobre ou mau. Cuidado, nestas águas o Kraken foi visto. ",
"(Retornar.)",
" Henry sabe muito, ele é pobre, mas é inteligente. Ao responder perguntas, ele é o melhor na arte ",
", Faça sua pergunta e até logo. Henry pode falar até tarde da noite.",
"Você conhece muito bem a cidade?",
"Você ouviu alguma palavra do governador de #sRedmond#?",
"Você só pode falar em enigmas? Eu não deveria perder meu tempo fazendo perguntas a um mendigo.",
"Desculpe, ",
" Henry é pobre e não possui muito. O que ele poderia lhe dizer que você não tem? \n Suas perguntas são intrigantes, acho bastante difícil. Para procurar uma resposta, tente perguntar ao guarda.",
"Tu podes estar certo. Eu não deveria perder meu tempo fazendo perguntas a um mendigo.",
"Não estou perguntando a ninguém agora. Estou te pedindo, e pare com a rima, você está brincando com minha mente",
"Sem dinheiro para Henry ",
" você é pobre ou mau, cuidado, nessas águas uma bruxa será vista. ",
"(Retornar.)",
" O conhecimento é meu, é tudo que tenho. Faça-me sua pergunta, vou te contar muita coisa. ",
"?",
"Onde posso encontrar a taberna?",
"Onde fica o estaleiro?",
"Onde posso vender os produtos finos que trouxe comigo?",
"A caridade é uma virtude ",
", sei que com esta resposta você vai achar que sou muito ousado, mas para lhe dar uma resposta vou precisar de mais dinheiro.",
"Você deve estar brincando. Não vou pagar por informações de um mendigo! E PARE com a rima!",
"Quanto?",
"Estou ouvindo,",
"Você conhece muito bem a cidade?",
"Você ouviu alguma palavra sobre o governador de #sRedmond#?",
"Tu podes estar certo. Eu não deveria perder meu tempo fazendo perguntas a um mendigo.",
"Uma bebida para o Capitão? Um pouco de comida e uma música? Direto para o Governador, você não estará muito errado. A Taverna você encontrará à esquerda da praça, e muita gente boa esperando por você lá.",
"Multar. Obrigado.",
"Onde fica o estaleiro?",
"Onde posso conseguir algumas moedas pelos produtos finos que trouxe comigo?",
"O próprio estaleiro, atrás dos portões da cidade na costa - mas o escritório do gerente fica a uma curta caminhada, e nada mais, ",
" à esquerda dos portões. Você verá a placa pendurada, passe pela porta da frente e logo o ouvirá batendo. ",
".",
"Obrigado. E como posso encontrar a taberna?",
"Onde posso vender alguns dos produtos que trouxe comigo?",
"Obrigado pela informação. Isso é tudo que preciso por enquanto.",
"Vá direto para o meio, e isso não é um enigma ",
", na praça, uma bela vista, o prédio que você precisa está ali à sua direita.",
"Onde fica o estaleiro da cidade?",
"Você pode me indicar a taverna?",
"Obrigado. É tudo por agora.",
" ouro, por favor ",
" Minha vida será curta se isso for divulgado. Henry tem inimigos vagando por aí.",
"Tudo bem, aqui está o seu dinheiro. Derrame, e NãO pagarei apenas por mais põesia!",
"Não estou pagando tanto. Estou apenas procurando algumas respostas - você não precisa gravá-las em ouro.",
"Bem bem., ",
" Aproxime-se meu amigo, foi isso que ouvi, o Governador dizem, não é um bom pássaro!",
"É isso? Isso é tudo que você tem para mim? Vou precisar de um reembolso.",
"Diga-me algo que eu não sei. Melhor ainda, pare de desperdiçar meu tempo. Se perder!",
"Desculpe, ",
". Parece que você está com pouco dinheiro no momento.",
"(Retornar.)",
"De jeito nenhum, ",
"! O Governador é ganancioso. Ele esconde isso muito bem, longe das pessoas, mas Henry percebe. Ele é rico e muito poderoso e ainda não está muito velho, não parando diante de nada para conseguir mais ouro! Mas ele não é sua preocupação, não neste belo dia. Há outro mais astuto, é tudo o que direi",
"Até agora não estou impressionado com o retorno do meu investimento, e a põesia também não melhorou!",
"Ótimo. Vou manter isso em mente. Adeus.",
"Os corsários comem caranguejo, os reis também os comem. Preste atenção a estas palavras, enquanto os peixes que você observa voando, quando você quebrar seu código fino, eles lhe dirão de quem está mentindo!",
"Nada além de enigmas e põesia! Põesia e enigmas! Estou começando a suspeitar que você não tem nada de útil para me contar.",
"Dê-me uma moeda só uma, ou diga duas, faça-me uma pergunta e eu responderei por você. ",
"já conversamos antes, uma resposta que dei, sei que pela rima você não estava apto a delirar!",
"Caridade, Caridade é tudo que eu imploro, se eu não comer logo, estarei comendo minha perna!",
", um saco de ouro é pedir demais? Eu não peço mais, você não é um toque suave",
"Esqueceste-te? Não acredito em esmolas, e a rima também não melhorou!",
"Você novamente? Tudo bem, pegue.",
"Vou te dar algum dinheiro, mas você responderá algumas perguntas em troca.",
"Obrigado, ",
"! Sua gentileza em si, uma alegria de se ver, Henry está grato por ter conseguido seu ouro!",
"A propósito, gostaria de saber uma coisa.",
"Obrigado. Você pode ir.",
"Infelizmente ",
", parece que você nem tem dinheiro sobrando para caridade.",
"(Retornar.)",
"Claro, ",
". É o mínimo que posso fazer por alguém tão gentil. Pergunte o que quiser, eu realmente não me importo",
"Você conhece a cidade?",
"O que você ouve sobre o governador de #sRedmond#?",
"Você sabe, não consigo pensar em nenhuma pergunta para você agora, e estou REALMENTE farto dessa põesia lixo!",
"Lamento profundamente, ",
", mas suas perguntas são difíceis, para encontrar o que deseja, tente perguntar ao guarda.",
"Talvez. Mas estou perguntando a você.",
"Acho que você está certo. Você não poderia ter as informações de que preciso.",
"Infelizmente ",
", parece que você nem tem dinheiro sobrando para caridade.",
"(Retornar.)",
"O conhecimento é meu, é tudo que tenho, me dê um pouco de ouro e eu te contarei muito ",
"?",
"Onde posso encontrar uma bebida e conversar?",
"Onde fica o estaleiro?",
"Onde posso obter o melhor preço pelos produtos que trouxe comigo?",
"Desculpe, ",
". Ouro, vou perguntar antes de prosseguirmos, depois de te contar, sei que você irá embora.",
"Você está brincando? Não vou comprar respostas de um mendigo comum! Especialmente aquele que é o pior poeta que já ouvi",
"Quanto?",
"Estou ouvindo.",
"Você conhece a cidade?",
"O que você ouve sobre o governador de #sRedmond#?",
"Acho que você está certo. Você não poderia ter as informações de que preciso.",
"Uma bebida para o Capatain, apenas o melhor rum, bebendo a noite toda até ficar com o nariz dormente. Cheguei à praça principal perto do resort do Governador, a Taverna que você encontrará fica perto do seu porto.",
"Entendi. Obrigado.",
"Onde fica o estaleiro?",
"Onde posso obter o melhor preço pelos produtos que trouxe comigo?",
"O próprio estaleiro fica atrás dos portões da cidade, na costa. Mas o escritório do gerente não existe mais ",
", à esquerda dos portões. Você consegue ver a placa balançando, passe pela porta, logo você o ouvirá cantando, ",
"?",
"Eu vejo. E onde fica a taberna?",
"Onde posso vender os produtos finos que trouxe comigo?",
"Obrigado pela informação. Isso é tudo que vou precisar. Agora que sou um maldito poeta, é melhor ir embora!",
"Vá direto para o meio, isso não é um enigma ",
". Quando você chegar na praça, uma bela vista, a loja que você vai encontrar, fica logo à direita.",
"Como posso chegar à taberna?",
"Onde fica o estaleiro?",
"Obrigado. Isso é tudo que eu queria saber. Já chega de põesia por um dia!",
"Por favor, ",
", Minha vida será curta se isso for divulgado, Henry tem inimigos vagando por aí.",
"Tudo bem, tudo bem. Pegue seu dinheiro e fale!",
"Por esse preço, acho que posso prescindir dos segredos de um mendigo e da põesia lixo!",
"Aproxima-te, ",
". Vou contar o que ouvi, o Governador dizem, não é um bom pássaro! .",
"É isso? Isso é tudo que você tem para mim? Vou precisar de um reembolso.",
"Diga-me algo que eu não sei. Melhor ainda, pare de desperdiçar meu tempo. Se perder!",
"Desculpe, ",
". Parece que você está com pouco dinheiro no momento.",
"(Retornar.)",
"De jeito nenhum, ",
"! O governador é ganancioso, esconde muito bem, mas Henry, ele sabe, sim, Henry sabe. Rico e tão poderoso e ainda não muito velho, mas tudo o que ele quer é conseguir mais ouro! Mas ele não é sua preocupação, não neste belo dia. Tem outro mais astuto, só direi!",
"Até agora, não estou impressionado com o retorno do meu investimento, e também NãO estou impressionado com a põesia",
"Ótimo. Vou manter isso em mente. Adeus.",
"Que tal isto: os corsários comem caranguejos, os reis também os comem. Preste atenção a essas palavras enquanto observa os peixes voando, leia-as novamente e elas lhe dirão de quem está mentindo! ",
"Enigmas e põesia, Põesia e enigmas, isso é tudo que você tem? Estou começando a suspeitar que você não tem nada de útil para me contar.",
"Dê uma moeda a um homem pobre ",
", eu sei sobre bruxas, o Kraken e o ouro, histórias de Davy que não foram contadas!",
"Por favor! Dê-me algum dinheiro, você nunca sabe, posso lhe contar algo que lhe será muito útil!",
"Oh ",
", mostre-me um pouco de misericórdia, não seja tão frio, um pouco de rum ou um pouco de uísque, talvez um pouco de ouro?",
"Desculpe; Eu não dou esmolas e sua põesia não melhorou, não é?",
"Ah, é você de novo. Aqui, pegue.",
"Obrigado, ",
". Sua generosidade não tem fundo, um poço sem fundo, Arrr, senhor, você é tão gentil, Henry pode dizer.",
"Espero que você possa refrescar minha memória de algumas coisas sobre as quais falamos antes.",
"Obrigado. Você pode ir agora.",
"Pode ser, ",
", que você nem tem dinheiro para caridade? Talvez você devesse se juntar a mim no meu, hum, trabalho. ",
"(Retornar.)",
"Com prazer, ",
". O Governador que estou pensando é quem você está falando, chegue um pouco mais perto, você sabe que não posso gritar.",
"Não, não tem nada a ver com o Governador. Estou um pouco perdido no momento.",
"Exatamente. O que você me contou sobre ele?",
"Não tenho nenhuma pergunta para você agora.",
"Tenho certeza que é minha culpa que você tenha esquecido. Sua memória é como a minha, ficando velha e podre ",
", chegue mais perto, gentil senhor, chegue um pouco mais perto, não quero que isso seja ouvido por nenhum velho ouvinte.",
"Sou todo ouvidos.",
"Você está quase tremendo de medo! Vamos falar de outra coisa.",
"Ah! Sem problemas, ",
". Vou apontar você certo, como uma bela bússola da Marinha, direto para onde você está indo, sem barulho e sem bússola.",
"Onde posso encontrar a taberna?",
"Estou procurando o estaleiro de #sRedmond#.",
"Trouxe mercadorias que gostaria de vender. Onde posso fazer isso?",
"Obrigado, ",
". O que mais posso fazer? O que mais você precisa, ou já terminamos?",
"Preciso de algumas orientações. ",
"Não preciso de nada, obrigado, principalmente de mais põesia! . Adeus.",
"Ah, uma bebida para o Capitão, um pouco de comida e um pouco de música. Vá direto pela rua, você não pode errar. Quando você chegar à praça, ao resort do Governador, a taverna que você verá, perto do seu porto.",
"Entendi. Obrigado.",
"Onde fica o estaleiro?",
"Onde posso vender os produtos finos que trouxe comigo?",
"O próprio estaleiro fica atrás dos portões da cidade, na costa. Mas o escritório do gerente não está mais lá ",
", à esquerda dos portões. Você consegue ver a placa balançando? Passe pela porta, você logo o ouvirá cantando. ",
"?",
"Eu vejo. E a taberna?",
"Onde posso vender meus produtos?",
"Eu vejo. Obrigado pela ajuda.",
"Passe pela rua central ",
", e quando você chegar na praça, uma bela vista, a loja que você vai encontrar, logo à sua direita.",
"Onde fica o estaleiro local?",
"Como faço para chegar à taberna?",
"Eu vejo. Isso é tudo que eu queria saber.",
"Lembre-se, o governador é um homem ganancioso, mas não é muito velho, ele fica sentado em seu palácio, apenas sonhando com mais ouro. Mas não é ele quem fica de olho, não está entre os fura-greves, lembre-se do que eu te falei sobre bucaneiros e caranguejos!",
"Isso mesmo, e eu disse que estava farto de toda essa põesia. Qual foi a mordida do caranguejo mesmo?",
"Sim, lembro-me agora. Obrigado.",
"Os corsários comem caranguejos, os reis também os comem! Estudando essas palavras, você dirá de quem é depois de você! Escreva como uma lista, é isso que você deve fazer. Depois leia à esquerda, Ei Presto! sua pista!",
"Sim. Tudo está voltando para mim. Preciso estudar a frase dos bucaneiros e dos reis para saber com quem devo tomar cuidado!",
"Ah! Capitão, você está de volta, mas com a testa franzida. Parece que Henry deve estar ajudando você agora.",
"Henry, ouça, tenho um grande problema. Acabei de conhecer o verdadeiro Cutler Beckett e ele me disse para capturar o impostor, mas não sei por onde começar a procurar, ou se ele é um impostor, ou se devo me preocupar com isso.",
"Pense bem, meu caro capitão, pense bem e pense devagar. O que você faz agora lhe envia para onde você irá. Não há como voltar atrás quando você der a resposta. Sua vida será definida de acordo com como você viverá. Você pode seguir sua busca pelo arco-íris para encontrar ou abandonar essa velha vida e deixá-la para trás. Você pode navegar pelos mares em aventuras muito raras, mas quem sabe que problemas o aguardam lá.",
"Minhas escolhas são então: continuar com essa busca ou esquecê-la e escolher uma nova vida?",
"Corrija meu caro capitão, na encruzilhada você está e como você decide mostrará onde você está pousando.",
"OK. Vou continuar com a missão e encontrar o outro Cutler Beckett.",
"OK. Vou começar uma nova vida, um novo país e encontrar Beckett dessa forma. Preciso de uma mudança.",
"Então conte ao velho amigo Henry o que você sabe, e ele lhe aconselhará sobre onde você deve ir.",
"Bem, eu tenho este documento que era para o outro Beckett. Parece que faz parte de um mapa.",
"Ah! sim, meu querido capitão, será um mapa. Se você achar que faltam peças, então estará inteiro. Isso leva a um vasto tesouro como você nunca viu antes. E as peças a serem concluídas são no total apenas quatro. Vá encontrar o homem Rheims como lhe foi dito, ele tem uma parte do mapa que leva ao ouro. Mas tenha cuidado, querido capitão, nem tudo é o que parece. Siga sua cabeça, não seu coração, nem seus sonhos.",
"O que! outro enigma? Agora não é só a põesia que brinca com minha mente. E o outro Beckett.",
"Um leva ao outro, querido capitão, você verá. Ambos se unem como o céu e o mar. O mapa foi rasgado em partes como vocês sabem, e aquelas que as partes carregam, sabem para onde devem ir. Eles se encontrariam em uma ilha para guardar suas partes, mas então encontrariam o que lhes falta.",
"O que lhes falta? Eu não entendo. ",
"Não se preocupe, querido capitão, você já tem o suficiente para fazer. Apresse-se em zarpar antes que seja tarde demais.",
"Tudo bem, tudo bem. Vou navegar para a ilha pirata.",
"Bem, eu tenho este documento que era para o outro Beckett mas parece estar em código.",
"Ah! sim, meu caro capitão, um código com certeza, de um plano de invasão, de comércio e muito mais. Seu Beckett que você vê tem um plano para fazer o bem, para que o comércio nessas ilhas seja como deveria. A nação que ele serve para negociar faz muito, e para saber mais sobre isso, converse com os holandeses. Os holandeses têm uma empresa que comercializa em lugares distantes e próximos, e esse comércio, meu caro capitão, eles trariam para estar aqui. ",
"Então vou ajudar os holandeses a dominar estas ilhas?",
"Não posso pará-los?",
"A escolha será sua quando seu Beckett for conhecido, em uma ilha que é holandesa e você ainda não chegou lá.",
"Tudo bem, tudo bem, procurarei Beckett em uma das ilhas holandesas.",
"De volta, meu querido capitão, e parecendo muito bem. Se você me pagar 1.000, um segredo eu conto.",
"1.000 em ouro. Você está ficando ganancioso, não é Henry?",
"Oh capitão, isso é cruel, Henry está do seu lado. Este segredo paga bem, mas você pode decidir.",
"OK. aqui está você 1.000. É melhor que seja bom ou você provará minha espada.",
"Obrigado, gentil capitão, não vou fazer piada. Vá direto para o estaleiro e venda seu navio para eles.",
"Venda meu navio! Você é louco e ganancioso?",
"Não Capitão, não, quando o Governador você conhecer. Você descobrirá que o conselho de Henry foi realmente muito gentil. Mas, por favor, não se esqueça de quando esse negócio estiver concluído, do estaleiro, da loja e da taverna para administrar.",
"OK. Então irei vender meu navio e ver o Governador. É melhor que isso funcione bem para mim, ou voltarei!",
"Ah! Capitão, mais uma vez você precisa do conselho de Henry. Se você tiver algum dinheiro sobrando, isso seria ótimo.",
"Henry, você realmente é um velho mendigo que ganha dinheiro! Estou falido e não tenho navio, apenas um velho Tartane furado.",
"Meu Capitão, suas escolhas são poucas, como você verá, e como você é tão pobre, eu as darei de graça.",
"Bem, isso é uma surpresa, devo dizer. Então, o que eu deveria fazer?",
"Há um navio no porto que serviria muito bem para você. Se você foi lá e roubou... bem, você nunca sabe. Ou, Weatherby Swann é o governador atualmente, você poderia ir até ele e ver quanto ele paga. Ou, se o seu sonho é recomeçar a vida, basta passear pela cidade e apreciar a bela vista.",
"OK. Vou dar uma chance ao navio... Há dois soldados lá embaixo guardando-o. Eu vou dar uma olhada.",
"Sim, você está certo, estou cansado de toda essa correria. Irei ver o governador, ver o que ele tem a oferecer. Pelo menos ele paga bem.",
"Uma boa escolha meu capitão, isso levará aos seus sonhos. Fale com aqueles soldados, eles lhe darão os meios.",
"Obrigado Henry, e agradeço o 'sem custo' desta vez!",
"Sim. Acho que vou começar tudo de novo e tentar esquecer o meu passado.",
"",
};
