string DLG_TEXT[37] = {
"Saudações, senhor! Servimos Hot Dogs frescos ou Sea Dogs mofados. O que seria para você ",
"?",
"Nada. Eu estou aqui a negócios.",
"Os negócios são para os empresários! A cozinha é para Hylie, a chef! Eu não vou incomodar você.",
"Não, espere - você não está me incomodando. Na verdade, é com você que preciso falar.",
"Não tão rápido. Quero falar com você.",
"Sou todo olhos e ouvidos, senhor! Cerveja, vinho ou rum?",
"Preciso contratar alguns marinheiros.",
"Estou querendo adicionar minha equipe.",
"Vamos conversar sobre negócios.",
"Eu preciso de um quarto.",
"Você tem um quarto livre neste lugar?",
"Deixa para lá. Eu tenho que ir.",
"Como quiser ",
". O que você tem em mente, senhor?!",
"Supoe-se que esteja aqui o primeiro imediato de Sao Feng que encontrou uma corveta misteriosa.",
"Na verdade, não é nada importante.",
"Você é um bastardo sortudo! Tenho uma sala limpa só para você! Quanto tempo você vai ficar?",
"Vou passar a noite.",
"Só até o pôr do sol.",
"Cinco oitos na luz, senhor!",
"Tudo bem. Aqui você vai.",
"Muito? Parece que vou passar a noite no salão da taverna.",
"Para quê - a residência do governador? Não, obrigado.",
"Vou pensar sobre isso. Deixe-me fazer outra pergunta.",
"Cinco oitos na luz, senhor!",
"Tudo bem. Aqui você vai.",
"Muito? Parece que vou passar a noite no salão da taverna.",
"Para quê - a residência do governador? Não, obrigado.",
"Tudo bem, vou pensar sobre isso.",
"Você está atrasado, senhor! A maior parte da tripulação já subiu a bordo!\nÉ melhor esperar até de manhã! Talvez você pudesse passar a noite em vez disso? ",
"Você tem um quarto livre?",
"Não. Tenho outra pergunta.",
"Deixe a garçonete em paz. As trabalhadoras estão... onde quer que esteja o bordel.",
"Relaxar! Estou indo embora.",
"Sim, esse seria o sujeito chamado Tai Huang! Você tem sorte, ele está sentado ali perto da janela!",
"Obrigado.",
"",
};
