string DLG_TEXT[32] = {
"A minha nave está pronta para a acção.",
"É bom saber capitão.",
"Quem é você, garoto? E o que você quer?",
"Meu nome é Capitão ",
", e estou procurando o Capitão Petros.",
"Capitão! Isso é uma risada! Você não parece ter idade suficiente para ser aspirante!",
"Bem, garanto que sim, e Sir Christopher Mings ficou muito satisfeito com meu trabalho.",
"OK. Capitão. Você tem nossa atenção. Você está dizendo que Sir Christopher o enviou aqui em missão para ver o Capitão Petros?",
"Sim, capitão, estou.",
"Muito bem. Então ele terá lhe dado algo especial para dar ao Petros. Você tem?",
"Quer dizer, como uma bússola?",
"É isso. Então você parece ser quem diz ser. Vá reformar seu navio e nos encontre aqui quando estiver pronto para navegar. Você entende?",
"Sim capitão, irei até a loja, depois voltarei e encontrarei você aqui.",
"Você está pronto para navegar?",
"Sim, só preciso pegar meu contramestre. Sr. Gibbs, por favor, precisamos nos preparar para o mar.",
"Bom, e você tem o 'item' com você?",
"Sim eu faço.",
"Em seguida, navegue até Anse Casse-Bois, do outro lado da ilha. Atraque seu navio e siga para a plantação do Capitão Petros. Ele tem uma casinha lá e está esperando por você.",
"Obrigado capitão. Vou embora imediatamente.",
"Isso parece muito emocionante. Vou me preparar para navegar.",
"Você está pronto para navegar então?",
"Sim, estamos prontos. Vamos.",
"Bem, devo dizer que foi uma viagem e tanto. É melhor continuarmos com o assunto em questão. Não podemos ficar aqui por muito tempo, os navios do Rei logo estarão sobre nós. Vamos para a cidade!",
"Oh! Sim, eu entendo. Suponho que deveríamos ir à Taverna para ver o que podemos descobrir?",
"Esse seria o lugar óbvio para começar.",
"Estamos prontos para ir?",
"Sim, enviei o navio para o mar com ordens de permanecer fora do local de terra e de não enfrentar os navios ingleses. Podemos sinalizar quando retornarmos. ",
"Isso soa bem. Vamos então.",
"Bem, bem, bem! Abençoe-me, velhas cracas. Estamos honrados! Capitães Maximus, Philippe e Sparrow! Isso deve ser importante.",
"Ah! Mas é claro que é... É sobre o tesouro de Cortez. Preciso reabastecer meu navio, então deixarei vocês, senhores, para se reencontrarem e discutirem os detalhes. Volto mais tarde. [PENSA: Bem, o capitão Jack Sparrow não é do tipo que perde uma boa e velha reunião de taverna como essa, não é? Nem o rum que acompanha.]",
"Isso vai funcionar. Há uma sala lateral ao lado da sala principal no andar de cima. Nós usaremos isso. SENHORIO! Mande um pouco de rum.",
"Aqui estão as partes do mapa que tenho. Talvez você possa descobri-los. Vejo todos vocês mais tarde então.",
};
