string DLG_TEXT[26] = {
"Seremos vitoriosos!",
"...",
"Saudações! Ouvi muito sobre você - e, na verdade, sua ajuda foi muito apreciada.",
"Fico feliz em conhecê-lo também. Mas que ajuda você quer dizer? Ah, espere... Você está falando daquela pequena agitação perto da costa de #sisland_Cuba#?",
"Um favor, comandante? E se alguém roubasse seu filho ou filha e algum burocrata exigisse um favor antes de permitir que você salvasse seu filho?! Ultrajante! Esse homem tem coração?",
"",
"Exatamente, ",
". Você foi uma grande ajuda para nós naquela época. Se não fosse por você, suponho que agora estaria na barriga de algum tubarão.",
"E, a menos que eu esteja enganado, você é o misterioso passageiro que desembarcou no porto de #sSantiago#. Correto?",
"Misterioso? Ah, acho que entendi o que você quer dizer. Sim, sou eu.",
"Então talvez você me diga seu nome e como você está conectado aos acontecimentos recentes.",
"Claro. Meu nome é ",
". Sou um cavaleiro maltês. Há alguns anos, participei na destruição de um culto maligno de satanistas na Itália...",
"E agora você veio aqui para terminar o trabalho?",
"Exatamente. E, se não se importa, gostaria de unir forças com você. Acredite em mim, não serei inútil",
"Bem, você conhece a face do inimigo e tenho certeza que pode lutar. Não vejo razão para recusar, então seja bem-vindo a bordo.",
"Você não vai se arrepender disso, capitão. Onde você gostaria que eu te seguisse primeiro?",
"Para #sisland_Isla Muelle#! Precisamos de informações adicionais.",
"Capitão, de qual navio você quer que eu assuma o comando?",
"The Crimson Blood, continuarei navegando minha amada Pearl!",
"Pegue o #scursed_ship# enquanto eu navego no Crimson Blood.",
"Acho que vou afundar o navio, na verdade.",
"Capitão, acho que devemos comandar este navio, posso assumir o comando dele ou do #sship#, o que você diz?",
"Vou pensar sobre isso.",
"Tenho que deixá-lo agora, capitão. Até a próxima.",
"Adeus.",
"",
};
