string DLG_TEXT[50] = {
"Capitão, a sua reputação é uma droga. Não tenho intenção de lidar com você.",
"Essa é sua escolha, suponho. E a sua perda.",
"Permita-me apresentar-me. Eu sou ",
"Joaquim da Saldanha",
"Joaquim da Saldanha",
", almirante da frota espanhola. Fico feliz em conhecê-lo, capitão - o governador o recomendou como um homem capaz de lidar com qualquer problema.",
"O governador me lisonjeia. Embora eu tenha muita experiência com problemas...",
"Capitão, você mudou de ideia sobre me ajudar a encontrar meu filho?",
"Sim, acho que posso ajudá-lo agora. Mas vou precisar de algo para começar. Você pode pelo menos me dar uma ideia geral de onde devo procurar?",
"Sinto muito, almirante, mas não posso ajudá-lo no momento.",
"Capitão! Você encontrou meu garoto?",
"Ainda não, almirante. Mas não se preocupe. Eu vou.",
"Ah, capitão! Bem na hora!",
"Tenho notícias sobre seu filho, almirante...",
"Capitão, você ainda está aqui? O que você está esperando?!",
"Relaxar. Eu vou encontrar seu filho.",
"Capitão, sua ajuda foi inestimável! Eu nunca esquecerei.",
"Estou muito feliz que tudo tenha dado certo.",
"Perfeito. Tenho alguns negócios para você, capitão. Você vê, meu filho ",
"Lucas da Saldanha",
", desapareceu de casa há vários meses, poucos dias antes de se casar. Como você pode imaginar, foi uma grande vergonha para mim.",
"Sim claro.",
"Quando soube que Lucas estava indo para o Novo Mundo, solicitei a designação como almirante da frota das Índias Ocidentais - para que pudesse vir aqui e encontrá-lo.",
"Mas você não conseguiu?",
"Infelizmente, não. Toda vez que penso que descobri o rastro de ",
"Lucas da Saldanha",
", logo perco novamente. Quero que você tente encontrá-lo. Eu ofereço uma recompensa de 10.000 ouro. Isso combina com você?",
"Isso me cai bem. Mas vou precisar de algumas informações...",
"Lamento desapontá-lo, almirante - mas infelizmente não posso assumir esta missão no momento.",
"Eu sei apenas isso ",
"Lucas da Saldanha",
" foi visto pela última vez na taverna #sFalaise de Fleur#. Você pode começar por aí. Não me decepcione, capitão.",
"Farei tudo o que puder. Até a próxima.",
"Eu sei que será difícil encontrá-lo. Mas ainda tenho minhas esperanças. Se você tiver alguma novidade, pode me encontrar aqui.",
"Adeus, almirante.",
"Desculpe a interrupção, mas o tempo é curto. Aqui estão 3.000 ouro pelo seu problema. Agora, ouça com atenção: fui informado de que ",
"Lucas da Saldanha",
" foi capturado por piratas. Eles exigem um resgate de 20.000 ouro.",
"Eu vejo. O que você pretende fazer? ",
"Vou pagar o resgate, é claro! ",
"Lucas da Saldanha",
" vale mais para mim do que mero ouro. Ele é meu filho! Por favor, entregue esse dinheiro aos piratas e traga meu filho aqui ileso. Você receberá os 10.000 ouro que prometi a você.",
"Eu vou fazer isso. Onde posso pegar o resgate?",
"Sinto muito, mas temo que esta missão tenha se tornado muito perigosa para eu continuar. Adeus, almirante.",
"Para #sisland_Conceicao#. Um dos piratas estará esperando por você na taverna do covil dos contrabandistas. Vou lhe mostrar o sinal especial que recebi, para que ele tenha certeza de reconhecê-lo. E lembre-se: se os piratas não receberem o resgate dentro de um mês, eles matarão ",
"Lucas da Saldanha",
".",
"Não se preocupe, almirante. Seu filho estará aqui em breve.",
"Estou feliz em lhe dar esses 10.000 de ouro, capitão. Você certamente mereceu. Eu te desejo sorte!",
"Obrigado, senhor. Adeus.",
"",
};
