string DLG_TEXT[15] = {
"Desaparece, estou ocupado!",
"...",
"Ah, aí vem nosso ouro, agora! Venha comigo - não iremos longe",
"Tudo bem.",
"Espere nas prateleiras e falarei com o meu homem sobre o prisioneiro.",
"Basta ser rápido.",
"Então ainda pensamos em 20.000 moedas de ouro. Pagar!",
"Aqui está o seu ouro, engraçado",
"Engraçado. Não seria uma risada se eu ficasse com o ouro para mim e massacrasse você e seus amigos como os porcos que vocês são?",
"Muito bom lidar com você.",
"Eu ficaria muito feliz se você fosse embora",
"O que?! Você não tem dinheiro suficiente! Tentando nos enganar, hein?! Morrer!",
"Droga!",
"Veja, isso não é tão engraçado. Eu mataria nosso convidado antes que sua espada saísse da bainha. Então ninguém estaria rindo.",
"Tudo bem, tudo bem. Algumas pessoas não tem senso de humor. Aqui está o seu dinheiro.",
"",
};
