string DLG_TEXT[66] = {
"Vá embora agora, seu cachorro-do-mar com escorbuto. Sua espécie não é bem-vinda aqui!",
"...",
"Bem vindo Capitão. Estou em dívida com você por devolver minhas filhas ilesas, e será um grande alívio para sua mãe saber de seu retorno seguro.",
"Estou muito satisfeito por ter prestado serviço, Vossa Senhoria.",
"Vamos, vamos, senhor, você é muito modesto. Você se expoe a um risco considerável para obter a liberdade deles. Minhas filhas mencionaram sua bravura em entrar no acampamento pirata.",
"Como eu disse, Vossa Senhoria, estou feliz por ter prestado serviço.",
"Bem, Capitão, esse serviço não ficará sem recompensa. Você pode escolher: ouro ou um novo navio. Qual é o seu prazer?",
"Vossa Senhoria, não mereço um serviço tão pequeno, mas é sempre agradável receber ouro. [PENSA] Outro dia de pagamento chegando!",
"Vossa Senhoria, meu navio já viu dias melhores, então um novo seria muito benéfico. ",
"Muito bem capitão. Pegue este ouro e vá com meus sinceros agradecimentos.",
"Assim seja Capitão. Aqui estão os documentos que concedem a você o título de seu novo navio, que você encontrará no porto.",
"Agradeço-lhe a sua generosidade, Sua Senhoria.",
"Lamento ter assuntos urgentes de Estado para tratar, por isso devo pedir que você saia.",
"Sim, Vossa Senhoria.",
"Devo preparar a família para uma viagem à Inglaterra agora que estamos reunidos.",
"Eu também tenho outros assuntos para tratar, então me despeço de você, meu Senhor.",
".",
"Aqui está uma moeda de ouro, meu caro. Gaste com sabedoria.",
"De alguma forma, não acho que você seja o pobre bêbado que finge ser. Qual é a sua história?",
"Não perca meu tempo, seu malandro, você provavelmente tem mais dinheiro do que eu.",
"---",
"---",
".",
"Bem, agora que senti o seu mau hálito, acho que não estou procurando alguém como você, afinal",
"Na verdade, e o que te faz pensar isso?",
"Você percebeu que se eu realmente estivesse bêbado, o proprietário já teria me expulsado horas atrás.",
"Hmmm! Algo assim, devo admitir. Então, por que você está procurando por mim em particular?",
"Não foi você, em particular, mas alguém que é astuto e tem inteligência.",
"Bem, acho que posso me encaixar nessa descrição. Então podemos começar a trabalhar?",
"Muito bem. Se você está disposto a correr riscos, há uma donzela, digamos, 'em perigo' que poderia usar a ajuda de um jovem e forte capitão como você. Você está disposto para isso?",
"Não acho que não. As mulheres sempre parecem me causar problemas. Então eu lhe desejo um bom dia.",
"Donzelas em perigo são uma especialidade minha! O que eu preciso fazer? .",
"Como desejar, meu bravo capitão. A senhora em questão está nos ouvindo conversar e acaba de me sinalizar que acha que você poderia ajudá-la. Ela acabou de sair e estará esperando por você atrás da Taverna. Vá agora e encontre-se com ela lá.",
"Muito intrigante! Eu irei conhecer essa sua mulher misteriosa. [PENSA:] Pode haver alguma vantagem nisso.",
"Como desejar, meu ousado capitão. Vou cuidar para que você não falhe. Embarque no navio do contrabandista e para #sTortuga# você navega.",
"Obrigado, sei que isso vai ser rápido. Próxima parada #sTortuga#.",
"A aventura de Jack Sparrow é aquela que você procurava. Basta entrar no seu navio e navegar até aquele porto.",
"Vou navegar para lá a partir daqui. Não vai demorar muito.",
"Uma longa jornada, meu capitão, é uma boa maneira de navegar. Eu te dei comida para que sua missão não falhasse.",
"Ah! Obrigado. Quando eu acordar estarei em #sisland_Turks# Port Jetty.",
"Bom capitão, farei o que você pede. Para #sTortuga# você irá, o que não é tarefa fácil.",
"Então preciso encontrar o Sr. Gibbs quando chegar lá.",
"Parece que você vai precisar da minha ajuda novamente, capitão.",
"Ei! Você se movimenta, não é? O que está acontecendo aqui? Nada faz sentido até agora.",
"Paciência Capitão, paciência... Este não é lugar para conversar. Vamos lá para cima.",
"É melhor que isso seja bom. E você pode parar esse disfarce de mendigo bêbado? Isso irrita, você sabe.",
"Eu sei que você está confuso, mas precisávamos ter certeza de que você era a pessoa certa para o trabalho.",
"Trabalho! Que trabalho? E sim, estou confuso.",
"Você sabe por que estou aqui, Billy. Podemos começar a trabalhar?",
"Não perca meu tempo, seu malandro, você provavelmente tem mais dinheiro do que eu.",
"Eu sei porque você está aqui, você sabe que sou o melhor. Apenas certifique-se de que você quis dizer isso e não apenas adivinhou. Você predefiniu seus níveis, equipamentos e tudo? Se não, meu querido capitão, você cairá na lama.",
"Ops! Desculpe, não, não era isso que eu queria. Adeus.",
"Sim... estou testando as águas. Se você souber o que quero dizer.",
"Então, meu belo capitão, para onde você irá? Apenas me diga o seu desejo, e eu farei isso",
"Vou ficar aqui, obrigado, e ver o que acontece.",
"Preciso testar o Motim com Barbossa.",
"Quero começar por ir a #sTortuga#, onde encontro a Anamaria.",
"Quero navegar para #sRedmond# para a sequência da 'Grande Entrada'.",
"Quero ir com Norrington para a ilha #sisland_Turks# para a linha de missão alternativa do CotBP.",
"Eu quero #sTortuga#, onde eu pego uma tripulação e encontro o #scursed_ship#.",
"Como deseja, meu corajoso capitão, passe pela frota. Navegue até o Farol, e Barbossa você conhecerá.",
"Obrigado Billy. Vou tentar isso.",
"Como desejar, meu ousado capitão. Vou cuidar para que você não falhe. Embarque no navio do contrabandista e para #sTortuga# você navega.",
"Obrigado, sei que isso vai ser rápido. Próxima parada #sTortuga#.",
"Vamos, vamos, senhor, você é muito modesto. Você se expoe a um risco considerável para obter a liberdade deles. Minhas filhas mencionaram sua bravura em entrar no acampamento pirata. E os seus serviços nesta empreitada, Senhora Shaypen, valeram-lhe uma promoção considerável.",
"Bem, Capitão, esse serviço não ficará sem recompensa. Há um belo navio recentemente capturado, cuja propriedade agora lhe concedo em reconhecimento aos seus serviços prestados à coroa. Ela está atracada no porto. Aqui estão os documentos de propriedade.",
"",
};
