string DLG_TEXT[28] = {
"Tanta coisa para fazer... Tanta coisa para fazer...",
"Você parece muito ocupado, cara!",
"Da mesma forma, senhores. É um prazer conhecê-lo. Aguardo sua ajuda com nossos problemas.",
"Parece que todos deveríamos nos dar bem. Então qual é o problema, realmente?",
"Talvez o Tenente Willemões e eu devêssemos discutir a estratégia das defesas do novo local proposto. Se isso for do seu agrado, capitão ",
"Sim, Capitão Konrad, parece uma boa ideia.",
"Olá novamente, capitão ",
". O Tenente Willemões e eu tomamos uma decisão sobre a nova localização da Irmandade, com o acordo do seu Governo, na qualidade de Embaixador.",
"Isso é bom, muito bom! Mas, como isso me afeta?",
"Movermos nossa frota em massa atrairia muita atenção. Você Capitão, dados seus 'problemas' atuais, poderá nos fornecer uma cortina de fumaça.",
"Eu vejo. [PENSA: Por que tenho a sensação de que vou chegar ao limite aqui.]",
"Bom Bom! Bem, o plano é que você, acompanhado pelos capitães Petros, Kell e eu, navegue para a Ilha #sisland_Turks#. Foi para lá que o Capitão Damski levou o seu navio. Você navegará no navio do Capitão Damski, ele está atracado aqui no porto.",
"Tudo bem até agora.",
"Excelente! Quando chegarmos lá, você trocará para seu navio original e navegará de volta aqui para Lighthouse Bay....",
"De volta aqui! Mas isso estará de volta às garras de Beckett! Serei voluntário para ser pego!",
"Não! Não! Capitão, você não está entendendo. Antes de partirmos daqui, você deve reabastecer sua nave. Os espiões de Beckett verão isso e, claro, reportarão a ele.",
"Sim então?",
"E Beckett seguirá a nossa frota. Isso dará ao resto da Irmandade tempo para chegar ao novo local sem impedimentos e, portanto, ao nos seguir, ele não estará nesta ilha.",
"Certo, então deixe-me fazer algumas perguntas. Primeiro, o que acontecerá se Beckett nos alcançar e atacar? E dois, por que preciso voltar aqui?",
"Nos ataca! Bah! Contra a nossa frota! Acho que todos nós gostaríamos muito desse encontro. O que devemos fazer é sair da terra de vista e depois hastear a bandeira pirata. Apenas deixe a nave de Beckett conosco e você ficará fora disso. Quanto a voltar aqui. Barbossa anda por Lighthouse Bay e sem dúvida entrará em contato com você. Isso lhe dará a oportunidade de mudar a caça ao tesouro para ele.",
"Ainda não faz sentido para mim. Como encontro a nova localização da Irmandade após a troca do tesouro?",
"Você se preocupa muito. Um de nós estará seguindo você e, assim que a troca for concluída, se juntará a você para levá-lo para casa.",
"Me seguindo, hein? Tudo bem, eu farei isso. Quando zarpamos?",
"Não há tempo como o presente. Quando você estiver pronto podemos partir, e eu sugiro que quanto mais cedo melhor. Beckett deve saber que você já deixou Bridgetown e estará vindo para cá.",
"Ei, oh! Vamos pegar os suprimentos e navegar então.",
"",
"",
"",
};
