string DLG_TEXT[62] = {
"Bem-vindo, ",
". Não acredito que já nos tenhamos conhecido. Sou Laurence Wellman, capitão do porto.",
"Olá, Laurence. Eu sou ",
", capitão do ",
".",
"Eu te dou as boas-vindas ",
". Você vem até mim a negócios?",
"Olá, ",
". Eu vi seu navio entrando no porto. Eu tinha certeza que você me ligaria em breve.",
"Ah, capitão ",
". O que traz você até mim?",
"Olá, Laurence. Eu gostaria de conversar com você.",
"Estou ao seu dispor, ",
".",
"Onde posso reparar e equipar meu navio em #sRedmond#?",
"É possível encontrar emprego aqui?",
"Conheci um marinheiro no cais que foi banido de seu navio.",
"Logo atrás dos portões da cidade você encontrará o escritório do gerente do estaleiro. A loja local fica na praça da cidade, bem em frente à residência do governador.",
"Eu vejo. E onde fica a taberna?",
"Posso encontrar um emprego aqui?",
"Obrigado. Adeus.",
"A taverna do jovem Windem fica em frente à residência do governador, do outro lado da rua da loja de Thomas O'Reily.",
"Obrigado. Até a próxima.",
"Posso encontrar um emprego aqui?",
"Bem, às vezes os comerciantes fretam seus navios para o transporte de suas mercadorias, mas não recebi nenhum pedido desse tipo recentemente. \nVocê ",
" poderia fazer uma visita ao Governador Silehard; ele pode ter algum trabalho para você. \nOu você pode ir até a taverna e conversar com os próprios comerciantes - normalmente você encontrará alguns lá.",
"Como eu disse, às vezes os comerciantes fretam seus navios para o transporte de suas mercadorias, mas não recebi nenhum pedido desse tipo recentemente.",
" Faça uma visita ao Governador Silehard; ele provavelmente terá alguns conselhos para você. \nE fale com os clientes na taverna - você encontrará todo tipo de gente relaxando lá.",
"Onde posso consertar e equipar minha nave em #sRedmond#?",
"Eu vejo. Obrigado.",
"Conheci um marinheiro no cais que foi banido de seu navio.",
"Pergunte ao taverneiro, Windem, e fale com O'Reily, o comerciante local.",
"Onde posso consertar e equipar minha nave em #sRedmond#?",
"Conheci um marinheiro no cais que foi banido de seu navio.",
"Obrigada pelo Conselho. Adeus.",
"Ah, provavelmente foi Bloom. Ele foi demitido porque agrediu um policial. Ele teve sorte de não o terem enforcado.",
"O que aconteceu?",
"Bem, Bloom parece estar muito arrependido de tudo isso...",
"Eu vejo. Tenho mais algumas perguntas para você.",
"Essa é uma história meio complicada. Para falar a verdade, não posso dizer que Bloom seja culpado. \nVeja, ele veio em defesa da garçonete na taverna quando um navegador bêbado tentou colocar as patas nela. \nIsso foi uma honra da parte dele, é claro - mas Bloom é um sujeito de temperamento explosivo, e quando o navegador o insultou, \nBloom enfeitou o homem.",
"Eu vejo. Bem, Bloom parece estar muito arrependido de tudo isso...",
"Isso é uma vergonha. Obrigado por me contar a história. Adeus.",
"É tarde demais para se arrepender agora. Ele nunca mais trabalhará num navio.",
"Certamente há alguma maneira de sua punição ser suspensa, não é?",
"Isso é ruim. Ele parece um bom homem. Bem, vejo você por aí, Laurence.",
"Você sabe, ",
", talvez haja uma maneira disso. Eu poderia mudar de ideia se algum homem digno atesta Bloom.",
"Você me considera um homem digno?",
"Não parece provável que o pobre sujeito encontre alguém por aqui que faça isso por ele.",
"Eu certamente faço. Você está se oferecendo para atestar por ele? Então reverto minha decisão. \nJá que você está apoiando Bloom, recomendo que você o contrate para poder ficar de olho nele. \nSe ele fizer algo assim novamente, sua reputação será prejudicada.",
"Vou ficar de olho nele. Obrigado e adeus!",
"Deixe-me perguntar-lhe outra coisa, se me permite.",
"Você parece um homem respeitável, mas devo admitir que não o conheço bem o suficiente para permitir que ateste o jovem Bloom. Por favor, não se ofenda ",
", mas\nele terá que encontrar outro patrono.",
"Bem, adeus, Laurence.",
"Deixe-me perguntar-lhe outra coisa, se me permite.",
"Ei! Você! ... Custa um xelim amarrar seu barco aqui,... E... enquanto ele está afundando, precisarei saber seu nome.",
"O que você diria a TRÊS xelins... e esquecemos o barco... e o nome?",
"Bem-vindo ao #sRedmond# Sr. er... Smith. Tenho outros assuntos para tratar agora, então não posso ficar aqui o dia inteiro conversando com você. Então é só fazer o pagamento e eu irei embora.",
"Claro... agora onde está meu dinheiro? ... Ei, o que aqueles marinheiros estão fazendo com aquelas cordas aí em cima?",
"O que! ... até nada de bom, sem dúvida. É melhor eu ir ver o que está acontecendo",
"Sim Sim. Eu te pagarei quando você voltar",
"",
};
