string DLG_TEXT[40] = {
"Mova-se marinheiro.",
"Eu estou indo... e, a propósito, é o Capitão.",
"Acabou de pousar? Por que você não pega o xelim do rei e se junta à Marinha? Isso fará de você um homem, rapaz.",
"Obrigado, Tenente. Vou pensar sobre isso... e, a propósito, é o Capitão.",
"Capitão? Essa sua banheira não precisa de capitão.",
"Pode ser, mas ela me ganha mais do que um xelim!",
"Você parece meio preocupado. Você está procurando alguém?",
"Eu, er... Não. Er... Não, não estou procurando por ninguém. Você nos seguiu até aqui. Eu pensei que você estava morto.",
"Eu não, rapaz. E os 'amigos' que você procura se foram. Eles saíram direto pela porta dos fundos",
"Amigos.. Er.. que amigos? Não sei do que você está falando.",
"Não finja, rapaz. Seus amigos da Irmandade. Eles já se foram. Além do horizonte agora eu não deveria me perguntar, e com seu mapa e tudo",
"Oh!",
"Talvez você devesse ter aceitado o xelim do rei, afinal. Ha! Ha!",
"---",
"Bem, bem, Jack Sparrow!",
"Capitão... Capitão Jack Sparrow.",
"Ah, sim, estou aqui em nome de Cutler Beckett. Eu vi seu navio quando você estava navegando para #sisland_Cuba# para enfrentar aqueles navios com velas vermelhas. Eu vi a bandeira mudar!",
"Ah, e por que isso importa... experiente?",
"Bem, você vê que navegar sob cores falsas é uma ofensa, assim como a pirataria, por isso você será enforcado. Ah, e notei que você deu uma pintura na 'Wicked Wench'.",
"Sim, e um novo nome. Tive que tirar dele o cheiro da Companhia Comercial das Índias Orientais.",
"Ok, então você será levado para a prisão enquanto eu pego Cutler Beckett.",
"Ótimo...",
"Bem, você vê que navegar sob cores falsas é uma ofensa, assim como a pirataria, por isso você será enforcado. Então agora você será levado para a prisão enquanto eu pego Cutler Beckett.",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
};
