string DLG_TEXT[43] = {
"Eu conheço aquele navio, dizem que ninguém pode pegá-lo. Mas há aqueles que dizem que ela não é um navio de verdade",
"Ah! Ela é real, certo, mais ou menos. Mas a Interceptor aqui é muito rápida, não é?",
"Ah, sim, ela é a mais rápida, certo. E não continue se aproximando dela.. você não tem permissão para ir lá, cara.",
"Oh! desculpe... É que ela é um barco tão bonito, er navio.",
"Qual é o seu propósito em #sRedmond#, Sr. Smith?",
"EU..",
"Acho que ele está dizendo a verdade.",
"_",
"Antes, qual é o seu nome então?",
"Smith, ou Smithy, se quiser. ",
"  ",
".",
"Caramba! É um milagre ela ter perdido as pedras.",
"Você vai salvá-la então?",
"Eu não sei nadar.",
"!",
"Não capitão. Você deve libertar os escravos.",
"Como faço isso?",
"Matando os três guardas na esquina da praia. Eles estão bloqueando meu caminho para a prisão onde os escravos estão detidos... e, a propósito, sua tripulação pode não ajudá-lo.",
"Por que tenho a sensação de que você poderia fazer isso sozinho e que não precisa da minha ajuda?",
"A sabedoria levanta a cabeça novamente, capitão. Você está certo, não preciso da sua ajuda, mas preciso que você prove suas palavras por meio de ações.",
"Por que é que?",
"Faça a escritura capitão, depois volte para mim aqui e eu lhe darei a resposta.",
"Estou me metendo em algo profundo aqui, eu sei, mas não gosto da ideia de escravos, então retornarei em breve.",
"Você teve sucesso, capitão.",
"Sim, eu consegui...",
"Isso foi uma afirmação, não uma pergunta, capitão. ",
", você confirmou seu caráter para mim e provou seu valor, então agora tenho algo especial que você deve comprar de mim.",
"Eu mato três homens e você quer me vender alguma coisa?",
"Não, capitão, esta não é uma venda comum. Dê-me 500 em ouro para que eu possa subornar o carcereiro e conseguir passagem para os escravos daqui para um lugar seguro, e você receberá esta bússola.",
"Um compasso! Eu já tenho uma bússola.",
"Não é uma bússola como esta. Este o levará ao que seu coração mais deseja. Siga com cuidado.",
"Você quer dizer como o Baú de Cortez?",
"Se é isso que você mais deseja, então sim.",
"Hmmm. Parece que você sabe algo diferente. ",
"Eu sei, capitão, que você não pode retornar ao seu empregador.",
"Ah! Sim. Isso será um problema. Bem, eu tenho outro lugar para ir.",
"Sim capitão, de volta ao farol em #sOxbay#.",
"Você sabe disso também? Tudo bem, vamos negociar aqui é o meu ouro.",
"E aqui está sua bússola. Seu futuro é muito complexo, capitão, mas você deve ir agora. Outros guardas estão chegando.",
"Sim, eu deveria, mas e você?",
"Não se preocupe comigo, capitão. Eu desaparecerei antes que eles cheguem. Até nos vermos novamente.",
"Você quer dizer 'se' nos encontrarmos de novo... não, não, você já sabe que nos encontraremos, não é?",
"",
};
