string DLG_TEXT[29] = {
"Cavalheiros! Por mais que eu goste de uma boa reunião familiar, não deveríamos ir direto ao assunto?",
"Que negócio em mãos?",
"Agora capitão ",
", devemos ser rápidos. Também não temos muito tempo. O governador estará de volta em breve.",
"Mas pensei que você fosse o governador.",
"Não, eu apenas pareço com ele. Ele gosta, digamos, de uma bebida no almoço e de uma boa soneca depois. Entro aqui e finjo ser ele por mais ou menos uma hora, e consigo coletar alguns fragmentos de informações dos vários visitantes durante esse período e passá-los para seu pai. Foi assim que conseguimos usar o estratagema da prisão para trazer você até aqui.",
"Muito inteligente, mas ainda não sei do que meu pai estava falando, então, até agora, sem sentido. O que você pode me contar? E quem era aquela mulher?",
"Oh! 'Aquela mulher', como você a chama, não lhe diz respeito. O que deveria preocupá-lo mais é que o governador Brin se aposentará em breve e há um novo governador vindo da Inglaterra vindo para cá.",
"Por que isso deveria me preocupar?",
"Por um lado, não acreditamos que ele será tão tolerante com os piratas como Brin é e isso colocaria todo o Caribe em estado de guerra.",
"Isso é um pouco dramático, não é? E por que eu deveria me preocupar com o destino de um bando de piratas?",
"Não é um bando de piratas! É a Irmandade e eles são governados pelo Tribunal de Irmãos.",
"Sim, muito impressionante, mas ainda são bandidos.",
"Você tem muito a aprender ",
", muito para aprender.",
"É o capitão ",
", se você não se importa!",
"Muito bem, capitão ",
", vou me lembrar disso, mas você precisa lembrar que os piratas nesses mares fazem muito para continuar o bem-estar do Caribe.",
"Não estou muito interessado em piratas no momento, obrigado.",
"Eu não deveria ter tanta certeza disso, capitão ",
". Existem alguns bons por aí, você sabe. Na verdade, existem alguns homens considerados honrados que são piores que os piratas, e tenho certeza de que você encontrará alguns deles no Caribe, mais cedo ou mais tarde.",
"Vou acreditar na sua palavra. O que mais?",
"Apenas duas coisas. Seu pai sugere que você navegue até #sOxbay# em #sisland_Oxbay# e pergunte por aí. Não tenho certeza do que você está procurando, mas tenho certeza de que encontrará algo que ajudará seu pai e salvará a Irmandade. E ele deixou esta espada para você. Preciso ir agora, o governador estará de volta em um minuto.",
"Não tenho certeza se estou interessado em ajudar algum deles no momento, mas posso tentar a sorte em #sOxbay# de qualquer maneira. Oh! E obrigado pela espada. Adeus.",
"Obrigado sargento, vamos eliminar o prisioneiro daqui. Você pode retornar ao seu posto. Prisioneiro, apresente-se ao tribunal.",
"[PENSA: Maldito 'descarte'... 'apresente-me'! O que diabos está acontecendo aqui?]",
"Que bom ver você de novo, capitão.. eu acho.",
"Não diga mais!",
};
