string DLG_TEXT[40] = {
"Este pode ser o caminho a percorrer.",
"hum!",
"Obviamente você acabou de chegar, capitão, e isso é uma sorte, pois estou procurando por alguém como você.",
"Você realmente tem? Me diga mais.",
"Não sou o bolinho de trapo comum que você encontra nestas águas. Tenho meu próprio navio e ouro suficiente para equipá-lo.",
"O que você quer dizer?",
"Tenho informações sobre o Tesouro de Cortez e preciso de um parceiro para me ajudar a consegui-las.",
"O Tesouro de Cortez - parece que quase todo mundo está atrás disso.",
"Ah! Na verdade, são capitães, mas estão todos seguindo arranhões em pedaços de pergaminho.",
"Você quer dizer mapas, eu acho.",
"Sim, sim, mapas, mas todos estão perdendo tempo. O tesouro não pode ser encontrado dessa forma.",
"De fato? E você sabe como isso pode ser encontrado?",
"Sim, quero, mas preciso que você se comprometa a se juntar a mim antes de eu lhe contar.",
"Eu não acho. Acho que preciso ganhar mais experiência antes de embarcar nessa aventura.",
"Muito bem, me comprometerei a acompanhá-lo em seu empreendimento.",
"Adeus então capitão.",
"Adeus.",
"Excelente capitão. Faça o que for necessário para equipar você e seu navio e depois me encontre no cais e eu explicarei tudo.",
"Muito bem, encontrarei você no cais em breve.",
"Fico feliz em ver você novamente, mal posso esperar para ir embora. Todo mundo por aqui cheira a algas marinhas ou a biscoitos marinhos!",
"Bem, estou pronto para ir. Então, qual é o plano?",
"Os índios são a chave. Eles já sabem onde está o tesouro.",
"Então por que eles não vão buscá-lo?",
"Eles não querem isso. Eles estão interessados apenas nas caveiras de cristal que usam em seus rituais.",
"Ah! você quer dizer que pegamos os crânios, os entregamos aos nativos e eles nos dizem onde está o tesouro?",
"É sobre isso. Só que não sei quantos e de que cor.",
"Que tal dois de cada cor, vermelho, azul e transparente, para começar?",
"Sim. Podemos tentar isso. Devíamos percorrer as ilhas para encontrá-los. Tenho 5.000 em ouro que irei investir na compra deles. Teremos que viver de nossa inteligência e do dinheiro dos navios premiados para conseguir mais dinheiro.",
"Parece justo. Vamos navegar então e conversar de vez em quando para ver quantos temos. Alguns dos comerciantes aqui podem ter alguns à venda.",
"Olhe se desejar. Quando tivermos o suficiente navegaremos para #sisland_Battle Rocks# para nos encontrarmos com os índios.",
"Vamos em frente então.",
"Precisamos manter nossos recursos separados caso sejamos atacados no mar. Dê-me o dinheiro, eu cuidarei disso, você ficará com o tesouro à medida que o conseguirmos.",
"Muito bem.",
"Bom. Agora prepare-se para morrer capitão. Eu tenho tudo que preciso, o jogo acabou para você. Eu te prendi muito bem, não foi?",
"O QUE?",
"",
"",
"",
"",
"",
};
