string DLG_TEXT[22] = {
"Está na hora de zarparmos.",
"Acordado.",
"A menos que eu esteja enganado, você é o capitão que esperávamos conhecer. Obrigado pela ajuda! Se não fosse por você, eu estaria descansando no fundo do mar com o resto da minha tripulação.",
"Sim. Perdi muitos bons membros da minha própria tripulação. Depois de um de seus ataques, um dos meus homens foi atingido por pedaços de madeira em ambos os braços e no olho.",
"Ele esta ok?",
"Larry perdeu os dois braços e o olho direito, coitado. Seus dias de navegação acabaram. Mas por que você decidiu lançar âncora aqui? Tenho ordens para acompanhá-lo até #sIsla Muelle#.",
"Tive que colocar um passageiro em terra. Eu também tenho ordens, você vê.",
"Não me disseram nada sobre isso - mas é justo. É problema seu, não meu.",
"Isso mesmo, ",
". Cada um de nós tem seus deveres e não precisamos discuti-los.",
"De fato. Podemos partir agora? Gostaria de colocar você e sua nave em segurança o mais rápido possível.",
"Nada me prende aqui agora",
"Ótimo! Não vamos perder mais tempo então!",
"Sim capitão!",
"Temos todos eles, capitão, você está livre para escapar.",
"O que você está fazendo aqui?!",
"Retribuindo o favor. Deixei nosso amigo maltês e vi aquele homem e os soldados esperando por você do lado de fora da igreja. Então decidi seguir e atacar em boa hora.",
"Obrigado, meu amigo. É muito apreciado.",
"Isso não será possível. Não posso entrar na sua frota porque você já tem #snumships# navios.",
"Oh! Espere aqui, então. Vou atracar ou vender um dos meus navios.",
"Agora é possível me juntar a você. Eu gostaria de navegar o mais rápido possível.",
"Você ainda tem muitos navios. Não posso me juntar à sua frota.",
};
