string DLG_TEXT[43] = {
"Ere, o que você está fazendo? Esta doca está fora do alcance de civis.",
"Sinto muito. Eu não sabia. Se eu vir um, irei informá-lo imediatamente. No entanto, estou trabalhando para o governador Lord Beckett, então isso não se aplica a mim. [PENSA: Isso pode me dar alguma vantagem.]",
"Bem, você está desatualizado, companheiro. O governador Weatherby Swann está no comando aqui agora. Lord Beckett voltou para a Companhia das Índias Orientais, então isso faz de você um civil, e esta doca está fora dos limites para eles, o que significa que você.",
"Isso é um pouco duro. Por que está fora dos limites então?",
"Porque o próprio governador disse isso. Há uma grande agitação no Forte e na Residência e ele não quer interrupções navegando entre os dois.",
"É um belo objetivo, com certeza, mas me parece que com todos esses navios aqui, não há muita chance de interrupção. Na verdade, com um navio como o Dauntless lá no porto, isso torna o Interceptor amarrado aqui um pouco supérfluo, na verdade.",
"Oh, o Dauntless é o poder nestas águas, é verdade, mas não há navio que possa se igualar ao Interceptor em velocidade.",
"Eu ouvi falar de um, supostamente muito rápido - quase impossível de ser capturado... o #scursedship#.",
"Antes, qual é o seu nome então?",
"Smith, ou Smithy, se quiser.",
"Sim, e sem mentiras, lembre-se.",
"Bem, então, eu confesso, é minha intenção comandar um desses navios, pegar uma tripulação em #sTortuga#, atacar, pilhar, saquear e de outra forma roubar meu caminho para recuperar meu navio!",
"Eu disse sem mentiras!",
"?",
"Se ele estivesse dizendo a verdade, ele não nos teria contado.",
"A menos, é claro, que eu soubesse que você não acreditaria na verdade, mesmo que eu a contasse a você.",
"[OUVEM-SE UM GRITO E UM RESPINGO DO FORTE]",
"Uma mulher acabou de cair das ameias.",
"Nem eu.",
"Orgulho da Marinha do Rei vocês dois são. Aqui, segure minhas armas. Suponho que terei que fazer a nobre ação.",
"Olha, aí vem o Governador e o Comodoro agora. Pareça esperto, Mullroy",
"Sim, e devolva-me as minhas coisas.",
"",
"Por que é que?",
"Faça a escritura capitão, depois volte para mim aqui e eu lhe darei a resposta.",
"Estou me metendo em algo profundo aqui, eu sei, mas não gosto da ideia de escravos, então retornarei em breve.",
"Você teve sucesso, capitão.",
"Sim, eu consegui...",
"Isso foi uma afirmação, não uma pergunta, capitão. ",
", você confirmou seu caráter para mim e provou seu valor, então agora tenho algo especial que você deve comprar de mim.",
"Eu mato três homens e você quer me vender alguma coisa?",
"Não, capitão, esta não é uma venda comum. Dê-me 500 em ouro para que eu possa subornar o carcereiro e conseguir passagem para os escravos daqui para um lugar seguro, e você receberá esta bússola.",
"Um compasso! Eu já tenho uma bússola.",
"Não é uma bússola como esta. Este o levará ao que seu coração mais deseja. Siga com cuidado.",
"Você quer dizer como o Baú de Cortez?",
"Se é isso que você mais deseja, então sim.",
"Hmmm. Parece que você sabe algo diferente. ",
"Eu sei, capitão, que você não pode retornar ao seu empregador.",
"Ah! Sim. Isso será um problema. Bem, eu tenho outro lugar para ir.",
"Sim capitão, de volta ao farol em #sOxbay#.",
"Você sabe disso também? Tudo bem, vamos negociar aqui é o meu ouro.",
"E aqui está sua bússola. Seu futuro é muito complexo, capitão, mas você deve ir agora. Outros guardas estão chegando.",
"Sim, eu deveria, mas e você?",
"",
};
