string DLG_TEXT[98] = {
"...",
"...",
"ACORDAR!!!",
"Maldito seja por respirar, seu idiota de queixo caído!",
"Você não me conhece, Sr. Gibbs?",
"! Você deveria saber que não deve acordar um homem quando ele está dormindo. É azar.",
"Felizmente, sei como combatê-lo. O homem que acordou compra uma bebida para o homem que estava dormindo. O homem que estava dormindo bebe enquanto ouve uma proposta do homem que acordou.",
"Sim, isso basta.",
"Agora, qual é a natureza deste seu empreendimento?",
"Vou atrás do #scursed_ship#.",
"O que?!",
"Eu sei onde ela vai estar e vou levá-la.",
" é uma tarefa tola. Você conhece melhor do que eu as histórias do #scursed_ship#.",
"É por isso que sei o que Barbossa está tramando. Tudo o que preciso é de uma tripulação.",
"Pelo que ouvi falar do capitão Barbossa, ele não é homem de tolerar tolos nem de fazer acordos com eles.",
"Bem, então eu digo que é uma coisa muito boa, então eu não sou bobo",
"Prove que estou errado. O que faz você pensar que Barbossa vai desistir de seu navio para você?",
"Digamos apenas que é uma questão de alavancagem.",
"Ele está agora! Alavancagem, diz você. Acho que sinto uma mudança no vento, disse eu. Vou encontrar uma tripulação para nós. Deve haver alguns marinheiros loucos como você nesta rocha",
"Só podemos esperar.",
"Pegue o que puder!",
"Não devolva nada!",
"Deleite seus olhos, capitão. Todos eles mãos fiéis diante do mastro. Cada homem vale o seu sal e é louco para arrancar.",
"Humm... Eles parecem... muito bons.",
"Você sabe, dá um azar terrível trazer uma mulher a bordo, senhor.",
"Será muito pior não tê-la. Não perca mais tempo, vamos para a Isla de Muerte.",
"(Sr. Gibbs está dormindo)",
"Bom te ver novamente, ",
"Obrigado, Gibbs. Como você conseguiu o #scursed_ship#?",
"Eu e alguns marinheiros conseguimos escapar de Barbossa e seus homens a bordo de um barco. Depois disso, navegamos para #sisland_Cayman# por cinco dias. Lá encontrei um amigo que concordou em nos levar até a Isla de Muerte para recuperar o Interceptor. Mas ela não estava lá. No entanto, chegamos à Isla de Muerte na mesma noite que The Dauntless. Então, aproveitamos a luta entre a tripulação de Barbossa e os fuzileiros navais a bordo do The Dauntless para capturar o #scursed_ship#.",
"Então, você sabia que eu fui para #sRedmond# como prisioneiro.",
"Na verdade, conheci secretamente Will Turner em #sRedmond# para preparar um plano para sua fuga há alguns dias.",
"Excelente, Sr. Gibbs. Agora, vamos deixar esta ilha. Quero navegar no #scursed_ship# como antigamente.",
"Alguma ordem, Capitão Jack?",
"Sr. Gibbs, vá até a Taverna e tome uma bebida. Você ganhou. Eu irei buscar você quando precisar de você.",
"Prepare o navio para #sisland_Guadeloupe#, Sr. Gibbs. Veremos você a bordo em breve, ou você poderá se juntar a nós novamente quando estiver pronto.",
"Conseguimos, capitão. Agora, você vai querer que a gente te espere aqui, ou que venhamos com você?",
"Provavelmente será melhor se vocês dois ficarem no navio. Na verdade, coloque-a no mar, ao abrigo das colinas. Esse será o lugar mais seguro.",
"Teremos maior probabilidade de sermos atacados em terra. Provavelmente será melhor se ficarmos juntos. Podemos cobrir as costas uns dos outros dessa forma.",
"O que...? O garoto?",
"Esse é filho de Bootstrap Bill Turner. Seu ÚNICO filho, esclarecido?",
"Capitão! Quais são as suas ordens, a tripulação espera para saquear, temos um rumo?",
"Pilhagem você diz... sim... claro! Senhor Gibbs! Partimos para #sisland_Turks#!",
"Você conseguiu o que queria, então?",
"Hum-hmm!",
"Capitão, acho que a tripulação, ou seja, eu também, esperava algo um pouco mais... brilhante. Com a Isla de Muerta toda em forma de pêra, recuperada pelo mar, e o tesouro com ela.",
"Brilhante?",
"Sim, brilhante!",
"É assim que todos vocês estão se sentindo, então? Talvez o querido e velho Jack não esteja servindo aos seus melhores interesses como capitão?",
"E seja o que for que esta chave desbloqueie, *dentro* há algo valioso. Então, estamos nos preparando para descobrir o que esta chave desbloqueia!",
"Não! Se não tivermos a chave, não poderemos abrir o que quer que seja, não temos o que ela desbloqueia. Então, qual seria o propósito de encontrarmos o que quer que precise ser desbloqueado, o que não temos, sem primeiro termos encontrado a chave que o desbloqueia?",
"Então - vamos atrás dessa chave!",
"Você não está fazendo nenhum sentido. Mais alguma pergunta?",
"Então... Temos um rumo?",
"Hah! Um cabeçalho. Navegue em um... mmm... um general... nessa direção.",
"Capitão?",
"Vamos lá, navegue e navegue, você sabe como isso funciona. Vamos!",
"Partindo sem saber sua própria direção? Alguma coisa deixou Jack irritado. Guarde minhas palavras, o que é um mau presságio para Jack Sparrow é um mau presságio para todos nós.",
"...",
"Levante a pele!",
"Todos no convés! Correr! E continue correndo! Corra como se o próprio diabo estivesse sobre nós!",
"Capitão! Temos um rumo?!",
"Ah! Ah! Correr! Terra.",
"Qual porta?",
"Não disse porto. Eu disse terra. Qualquer terra!",
"Aqui estamos, Jack!, qual é o seu plano agora?",
"Bem... Podemos muito bem explorar a ilha, senhor Gibbs! Pode haver algo útil por aqui. [PENSA: Uma chave, por exemplo!] Vamos manter nossos números baixos, assim não chamamos atenção indesejada.",
"Nós caímos em uma emboscada, preparem-se!!",
"Caramba!",
"Capitão, sinto que preciso sentar um pouco...Ou tirar uma soneca aqui...",
"Maldições! Essas flechas devem ter sido envenenadas...e...d...",
"Jack! É tão bom ver você vivo, pensei que você seria morto por eles com certeza!",
"Controle-se, senhor Gibbs! Você terá bastante tempo para pensar na minha grande fuga, agora precisamos sair desta ilha...Deve haver uma saída aqui em algum lugar!",
"Vamos colocar alguma distância entre nós e esta ilha e partir para o mar aberto.",
"Sim ao primeiro, sim ao segundo, mas apenas na medida em que nos mantemos o mais possível nas águas rasas.",
"Uh... Isso parece um pouco contraditório, capitão.",
"Tenho plena fé nas suas habilidades de navegação reconciliatória, Mestre Gibbs!",
"Espero que você conheça o caminho Jack, esta ilha aqui pode ser perigosa se nos perdermos!",
"Não precisa se preocupar, mestre Gibbs, já andei aqui antes, apenas siga-me.",
"O que esta dentro? Ouro! Jóias? Propriedades não reclamadas de natureza valiosa? ",
"Não, não, não, ouvi dizer que foi pelo mar que ele se apaixonou.",
"Deve ter entrado em conflito com o recife..",
"E como você pretende colher essas noventa e nove almas em três dias?",
"Uh, me sinto manchado e incomum. Mas, felizmente, ele ficou calado quanto à condição em que essas almas precisam estar.",
"Ah... Tortuga!",
"Tortuga.",
"Então vamos para a taverna Capitão?",
"Na verdade, senhor Gibbs, vamos ver quem estará disposto a se juntar à nossa *equipe*",
"E o que faz você pensar que é digno de tripular o Pérola Negra? ?",
"Você vai fazer. Faça sua marca. Próximo!",
"É o ninho do corvo para você. Perfeito! Próximo!",
"Mais cedo do que você pensa. Assine a lista.",
"E qual é a sua história?",
"Comodoro?",
"Capitão?",
"Senhor Gibbs! Temos o nosso rumo.",
"Finalmente! Arremate essas linhas, levante âncora e proe essa tela!",
"Senhorita Swann.. ex-Comodoro.. Bem vindo à tripulação!",
};
