string DLG_TEXT[28] = {
"Vi har meget at lave - - Temos muito que fazer, capitão",
"Sim nós fazemos.",
"Preciso preparar meu próprio navio, Capitão Jack, para não atrasar a missão. Te vejo no mar.",
"Sim, capitão Willemões, por favor. [PENSA: Ele fala tão bem, não admira que seja um diplomata.]",
"No que diz respeito à localização, se for adequada para vocês, acredito que posso resolver essa situação. E no que diz respeito ao antagonismo entre os vários bandos de piratas, creio que posso ser de maior ajuda, se assim o desejarem.",
"Quer dizer que você tem tudo sob controle então? [PENSA: Por que os diplomatas usam seis palavras quando apenas uma bastaria?]",
"Não tão rápido capitão ",
". Existe uma alternativa para o seu envolvimento nesta aventura, que terei o prazer de lhe explicar.",
"Oh sério? Bem, vamos ouvir então Tenente Willemões. [PENSA: E isso vai demorar um pouco, imagino. Gostaria que tivéssemos essa reunião tomando uma garrafa de rum.]",
"A alternativa para o seu envolvimento é você se concentrar em financiar esse empreendimento, indo você mesmo atrás do tesouro de Cortez.",
"O tesouro Cortez, hein? Prossiga.",
"O Capitão Konrad junto com os outros irão para a Ilha #sisland_Turks# como ele declarou. Você, entretanto, retornará para #sisland_Guadeloupe# com os capitães Maximus e Philippe e se juntará ao Capitão Drow e ao Capitão Rackham. A partir daí você irá localizar e recuperar o tesouro, o que permitirá à Irmandade cumprir sua obrigação financeira para com meu Governo em relação ao novo assentamento.",
"Mas não tenho o mapa completo.",
"Aí reside a beleza deste plano Capitão ",
". Dada a assistência e conhecimento adicionais dos capitães Maximus, Philippe, Drow e Rackham, será de pouca importância para você conseguir localizar o mapa em pouco tempo. Acrescentou que você também deve ser capaz de se defender contra qualquer eventualidade.",
"E como chego a #sisland_Guadeloupe#?",
"Como o capitão Konrad afirmou, você usará o navio do capitão Damski, que trocará pelo seu quando nos encontrarmos novamente no novo assentamento.",
"Ah! O novo assentamento. Ainda não sei onde fica.",
"Mas o Capitão Maximus sim. Ele o levará até lá assim que o tesouro for encontrado.",
"Bem, você respondeu todas as minhas perguntas. [PENSA: E não demorou tanto quanto eu pensava.]",
"",
"",
"",
"",
"",
"",
"",
"",
};
