string DLG_TEXT[55] = {
"Calma rapazes, calma!",
"Sim, capitão.",
"Então você é o capitão ",
" enviado por Sir Christopher para nos ajudar? E quem é o seu camarada, por favor, diga?",
"Sim, sou Capitão Petros, e este é o Honorável Tenente Peter Willemões, Embaixador do Rei Christian V da Dinamarca.",
"Excelente! Excelente! Vocês dois são muito bem-vindos aqui. Temos muito que discutir, mas esqueço meus modos. Deixe-me apresentar o capitão Konrad Kulczycki, nosso estrategista-chefe.",
"É um prazer conhecê-lo, capitão. Ouvi muito sobre você e seu trabalho.",
"Ah! Sim, nossos problemas. Estamos a descobrir que não podemos concordar com algumas das ações dos nossos irmãos piratas. Na verdade, chegámos a um ponto em que os nossos caminhos devem se separar, no entanto, dada a natureza do nosso negócio, encontrar, digamos, alojamento adequado, está a revelar-se difícil.",
"Difícil encontrar um barraco decente, né? Eu entendo, poucas ilhas permitirão a sua presença, sendo piratas e tudo mais.",
"Uma boa ideia Konrad. Capitão ",
" e posso discutir a situação geral.",
"Oh! E o que é isso?",
"Tivemos três problemas, onde poderíamos realocar o assentamento, o dinheiro e o fato de que nem todos os membros mais antigos da irmandade desejam vir conosco.",
"Parece que Peter Willemões pode resolver seu problema de localização. O dinheiro tem sido um problema desde o início dos tempos e não vejo o que poderia fazer com aqueles que não desejam se juntar a você.",
"Você se subestima, capitão. Você pode realmente resolver nosso problema de dinheiro e fraternidade de uma só vez. Acredito que você esteja carregando uma bússola e parte do mapa para o tesouro de Cortez?",
"Er... Sim, estou, mas que ajuda isso seria para você?",
"Também tenho aqui uma parte do mapa, que você pode levar, e um de nossos membros tem uma terceira parte. Infelizmente, ele atualmente reside em uma prisão na ilha de Porto Rico. Agora, se você o resgatasse, estaríamos muito mais perto do tesouro, e isso atrairia mais membros de volta para nós.",
" Ah! É mais assim! O que você pode me dizer sobre a situação da prisão então?",
"Acho que ainda não estou pronto para tal aventura, então desejo-lhe um bom dia.",
"Não posso te contar muito, estou com medo. Tudo o que você pode fazer é navegar até Porto Rico e perguntar por aí. Porém, tenha cuidado onde você pousa, eles estarão esperando uma tentativa de resgate.",
"Tudo bem então! Eu irei embora em breve.",
"Sim, estamos prontos. Vamos.",
"Bem, devo dizer que foi uma viagem e tanto. É melhor continuarmos com o assunto em questão. Não podemos ficar aqui por muito tempo, os navios do Rei logo estarão sobre nós. Vamos para a cidade!",
"Oh! Sim, eu entendo. Suponho que deveríamos ir à Taverna para ver o que podemos descobrir?",
"Esse seria o lugar óbvio para começar.",
"Estamos prontos para ir?",
"Sim, enviei o navio para o mar com ordens de permanecer fora do local de terra e de não enfrentar os navios ingleses. Podemos sinalizar quando retornarmos. ",
"Isso soa bem. Vamos então.",
"Ah! Capitão ",
", você conseguiu resgatar o Capitão Charles. É um excelente trabalho, muito bem!",
"Bem, nem tudo são boas notícias, o mapa foi tirado dele quando foi capturado. Um homem chamado Barbossa está com ele, mas posso retirá-lo dele.",
"Pequena questão capitão ",
", as coisas progrediram desde que você esteve fora. Parece que o Capitão Kell tem outro pedaço do mapa, porém, apenas Anamaria sabe onde ele está. Agora ela está na praia do farol em #sisland_Oxbay# esperando por você.",
"Esperando por mim? Por mais que eu goste da ideia, uma moça esperando por mim, como ela poderia se nem me conhece?",
"Ha! Ha! Isso é verdade ",
", ela nunca vem aqui porque é uma agente nossa, mas conseguimos enviar uma mensagem para ela para encontrá-lo lá, em vez de na cidade, para que ela soubesse quem você é. Agora, se tiver a gentileza de ir encontrá-la e depois encontrar o Capitão Kell, estaremos mais um passo em frente. Também preciso do Sr. Gibbs para uma tarefa em #sTortuga#, então ele não irá com você.",
"Muito bem, Petros, irei encontrá-la sozinho. O capitão Charles precisa de um descanso por enquanto, eu acho. Ele parece estar perdendo o navio ao qual tem direito pelo nome.",
"É um prazer finalmente conhecê-lo, capitão. É um alívio que você e o Capitão Drow estejam seguros. Depois que o Tenente Willemões e o Sr. Gibbs nos avisaram de sua captura, tomamos a liberdade de trazer seu navio até aqui. Você o encontrará no porto.",
"Obrigado capitão Petros. Lamento não ter conhecido você em sua plantação em Guadalupe. Não tenho certeza do que realmente aconteceu lá.",
"Esse foi o trabalho de um homem chamado Mercer, ele é funcionário da East India Trading Co. e é muito perigoso. Ouvimos dizer que ele estava conversando com o governador, mas não imaginamos que os franceses agiriam tão rapidamente!",
"Entendo, ... bem, se esse Mercer trabalha para o E.I.T.C. então isso significa que Cutler Beckett deve estar procurando por mim, mas acho que posso lidar com isso.",
"Tem certeza, capitão? Cutler Beckett não é alguém que um homem sábio contraria sem pensar cuidadosamente.",
"Sim, ele não é problema. Agora Capitão Petros, já que conheceu o Tenente Peter Willemões, como desejava Sir Christopher, há algo que eu possa fazer para ajudá-lo?",
"Ah, obrigado, esperava que você fosse voluntário, para uma pequena tarefa, gostaríamos que você fosse para #sisland_oxbay#. Acredito que você esteja carregando uma bússola e parte do mapa para o tesouro de Cortez?",
"Er.. Sim, estou, mas como isso ajuda.",
"Bem, capitão ",
" ", as coisas progrediram enquanto você estava na prisão. Parece que o capitão Nathan Kell tem outro pedaço do mapa, porém, apenas Anamaria sabe onde ele está. Agora ela está na praia do farol em #sisland_Oxbay# esperando por você. Também tivemos uma mensagem dela dizendo que ela mesma conseguiu outro pedaço deste mapa. Então precisamos que você vá e colete esses dois pedaços"",
"Esperando por mim? Mas ela não me conhece!",
"Ha! Ha! Isso é verdade ",
", ela nunca vem aqui porque é uma agente nossa, mas conseguimos enviar uma mensagem para ela para encontrá-lo lá, em vez de na cidade, para que ela soubesse quem você é. Agora, se tiver a gentileza de ir encontrá-la e depois encontrar o Capitão Kell, estaremos mais um passo em frente. Também preciso do Sr. Gibbs para uma tarefa em #sTortuga#, então ele não irá com você.",
"Muito bem capitão, irei encontrá-la.",
"Obrigado, desejo-lhe bons ventos e lembro-lhe de estar atento a Cutler Beckett e seus asseclas.",
"Não se preocupe Capitão Petros, eu posso cuidar de Beckett e seus servos! Afinal...Quem sou eu?....",
"Quem!!??....",
"Eu sou o Capitão Jack Sparrow!",
};
