string DLG_TEXT[56] = {
"...",
"...",
"Bom dia para você. Posso perguntar quem você é?",
"Eu sou ",
", capitão do ",
"Sou Pieter Boelen, corsário holandês e capitão do adorável navio 'Amsterdam'. Prazer em conhecê-lo.",
"Então, o que o traz hoje a esta cidade infestada de piratas?",
"Faço questão de ajudar todos os piratas honestos deste arquipélago. Desta vez correm rumores de que o governador de #sSantiago# está planejando algum tipo de ação contra esta colônia. Estou tentando descobrir se há alguma verdade nisso. Você poderia me ajudar se quiser e ganhar algum dinheiro ao longo do caminho também.",
"Dinheiro? Sou todo ouvidos, capitão. O que você quer que eu faça?",
"Não posso sair desta ilha caso o ataque aconteça enquanto eu estiver fora. Devo permanecer aqui para defender meus amigos. No entanto, seria possível visitar #sSantiago# para descobrir se há alguma verdade no boato.",
"Eu precisaria enganar um funcionário do #sSantiago# para que me desse essa informação. Parece uma missão bastante perigosa. Eles poderiam me enforcar por espionagem se eu fosse descoberto.",
"Você decide. Eu lhe darei 20.000 moedas de ouro se você tiver sucesso. É pegar ou largar.",
"Muito bem. Temos um acordo. Não me importo com um pouco de perigo.",
"Desculpe. Isso parece muito perigoso para mim. Desejo-lhe boa sorte na defesa desta colônia.",
"Excelente! Espero ouvir de você em breve. E tenha cuidado.",
"Não se preocupe; Eu vou ser. Vejo você em alguns dias.",
"Ah! Você está aqui! Você descobriu o que o governador espanhol está planejando?",
"Sim eu fiz. Receio que más notícias. O governador de #sSantiago# pretende assumir o controle desta ilha. Seu ataque ocorrerá nos próximos dias.",
"De fato. Por favor, leve seus homens e vá até o farol para evitar que o inimigo pouse lá quando chegar. Cuidarei da defesa do porto com meu navio e tripulação de confiança.",
"OK. Vou sair agora mesmo e preparar uma recepção calorosa aos nossos convidados. Boa sorte para você!",
"AAHH!! Aí está você! Você conseguiu?",
"Na verdade eu tenho! Que isso sirva de lição de espanhol para eles. Os piratas permanecerão livres!",
"Excelente, capitão! Também conseguimos evitar que eles desembarcassem no porto. Infelizmente o meu lindo navio, o 'Amsterdam', foi danificado durante a batalha e não posso arriscar navegar com ele até que tenhamos feito alguns reparos. Não podemos ter certeza se os espanhóis não tentarão novamente, mas PODEMOS ter certeza de que, se tentarem novamente, trarão uma frota muito maior. Vou precisar da ajuda dos piratas #sTortuga#. Você pode me levar lá enquanto meu navio está sendo consertado?",
"Claro. Sem problemas. Ficarei honrado em tê-lo como convidado a bordo do meu navio.",
"Obrigado pela sua ajuda, capitão. Sua ajuda foi decisiva. Não poderíamos ter feito isso sem você. Você fez muito mais do que esperava, então é justo que eu aumente sua recompensa. O que você diria de 40.000 moedas de ouro?",
"Oh! Isso é muito gentil da sua parte. Tenho outras coisas para fazer agora, mas tenho certeza que com a ajuda dos piratas #sTortuga# você conseguirá se defender de qualquer ataque espanhol. Vou me despedir de você agora, mas espero que nos encontremos novamente algum dia. Adeus e boa sorte, Pieter!",
"Bom dia para você capitão. Posso ter a ousadia de perguntar seu nome e por que está na companhia de um oficial inglês?",
"Meu nome é ",
", e este oficial e eu estamos voltando de uma missão na França. E você é o capitão Pieter Boelen, acredito, capitão do 'Amsterdam'.",
"Sim, estou, mas você despertou minha curiosidade, um oficial inglês em missão com os franceses? Isso não parece muito provável, a menos que ele seja um traidor?",
"Ah, não, capitão Boelen, ele não é um traidor. Ele estava representando seu governo em um assunto do maior sigilo. É por isso que, de fato, estamos aqui.",
"Isso soa como uma abertura para um pedido de dinheiro, capitão. ",
", e isso não me agrada.",
"Não é assim, capitão. Longe disso. Veja, eu conheço sua reputação de ajudar piratas honestos e acho que posso ajudar de alguma forma nesse aspecto, sendo eu mesmo um pirata honesto.",
"Seu capitão inglês parece prestes a sufocar. Ele não está bem?",
"Oh! ele está bem. Ele não navegou muito, então pode estar um pouco enjoado por causa da nossa jornada.",
"Muito bem. Então, se o que você procura não é dinheiro, que tipo de assistência você poderia oferecer?",
"Os franceses pagaram aos ingleses para lhes permitir o reabastecimento nas suas ilhas. Acredito que eles pretendem atacar os piratas.",
"Quanto aos franceses se voltarem contra nós, sabíamos que isso iria acontecer. Mas não tão cedo. Que prova você tem de sua reivindicação?",
"Que tal 100.000 em ouro que recebemos dos franceses?",
"Deus do céu! você tem CERTEZA que seu capitão inglês está bem? Ele está ficando bem roxo!",
"Sim, sim... estômagos fracos são comuns em sua família.",
"Hmmm. Então você nos daria 100 mil em ouro e avisaria antecipadamente sobre um ataque francês. O que você quer em troca?",
"Garantir a segurança da ilha natal dos piratas é tudo o que procuro.",
"Muito Nobre Capitão ",
", muito nobre mesmo. Oh céus! Você deveria recorrer ao seu capitão inglês. Ele parece ter desmaiado.",
"Ah! Sim. Suponho que deveria, mas enquanto isso, aqui está o dinheiro. O que você pretende fazer?",
"Oh! Acho que podemos surpreender um pouco os franceses e com o dinheiro podemos ter o melhor equipamento. Não creio que eles consigam entrar no arquipélago.",
"Boa sorte, Capitão Boelen. Esperemos que nos encontremos novamente um dia",
"Ah! Capitão ",
", você está de volta, e em um momento muito oportuno, devo confessar.",
"O que você quer dizer?",
"A nossa principal frota pirata navegou para enfrentar os franceses, graças ao seu aviso. Mas agora recebi a notícia de que o governador de #sSantiago# está planejando algum tipo de ação contra esta colônia. Estou tentando descobrir se há alguma verdade nisso ou não.",
"Deixe-me adivinhar, você precisa que eu navegue até #sSantiago# e encontre algum oficial lá, e veja se é verdade ou não, correto?",
"Você é muito astuto, capitão, como eu havia adivinhado em nosso encontro anterior. Pagaremos a você 20.000 em ouro pelo seu problema. Você assumirá esta missão por nós?",
"Lamento não poder agora. Devo continuar equipando meu navio para estar pronto para o ataque francês.",
"",
};
