string DLG_TEXT[46] = {
"Bom dia para você capitão",
"Bom dia para você também, guarda",
"Ei! Espere aí, marinheiro. Você está preso, você sabe, e tem sorte de não estar acorrentado, no que me diz respeito.",
"Encantador! E é o Capitão, aliás!",
"É assim que pode ser. Espere aqui até ser convocado.",
"Afinal, por que fui preso?",
"Não é preciso muito trabalho no meu livro! Vejo uma mulher lá em cima, muito angustiada, suplicando ao Governador. Vejo um marinheiro atrevido aqui. Agora conte-me.",
"Mas... [PENSA: Se não me engano, esse é meu PAI aí em cima!? O que ELE está fazendo aqui?]",
"Você está no melhor lugar esta noite, a cidade está sob ataque de algum navio pirata. Dizem que é o #scursed_ship#.",
"Pensei ter reconhecido aquelas armas.",
"É assim que pode ser. Recebi ordens de ir ao porto para repelir os piratas se eles tentarem desembarcar.",
"Eu me ofereceria para ajudar, mas, sendo um pirata, não saberia de que lado estou!",
"Quem é você e o que está fazendo aqui?",
"Eu sou Capitão ",
", e acabei de ter o prazer de ficar abandonado aqui.",
"Um capitão, né? Você sabe navegar em um navio, não é? Nosso capitão e navegador morreu de escorbuto e precisamos chegar a #sTortuga#.",
"Ah! Escorbuto! Há muito sobre isso, mas para responder à sua pergunta, sim, eu poderia levar seu navio para #sTortuga# para você. Mas vou precisar de uma espada. Nenhum capitão que se preze navegaria sem ele.",
"Bom, aqui está uma espada. Vamos indo então. O navio está na baía lá em baixo.",
"Lidere McDuff! Ou melhor ainda, siga-me.",
"Conseguimos. Diremos adeus capitão. Temos coisas para fazer.",
"Adeus e obrigado.",
"VOCÊ! Você está trabalhando para aquela maldita Companhia das Índias Orientais. Correto? Não minta! Falei com sua tripulação.",
"Er.. Sim, senhor. Vim discutir um assunto relacionado à Empresa.",
"Discuta, dane-se! Prepare-se para morrer.",
"Huh!",
"Ouvi dizer que Sir Cutler Beckett puxou seu navio para perto do porto para que todos possam ver você pendurado lá amanhã, como um aviso aos outros piratas!",
"Encantador!",
"Você aí! Venha comigo!",
"Bem, eu preferiria ir por outro caminho, mas se você insiste com tanta persistência...",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
};
