string DLG_TEXT[57] = {
"Nos deixe.",
"...",
"Não tão rápido, ",
"! Você não acha que pode nos evitar, não é?!",
"Acho que não quero falar com você",
"Então seja rápido, estou com pressa",
"Eu não acho que você irá a lugar nenhum. Agora dê-nos a carta que você está carregando.",
"Talvez pudéssemos apenas beber uma caneca de cerveja e seguir nosso caminho? Não?",
"O que você quer de mim?!",
"Diga-me onde fica o seu esconderijo e eu deixarei você morrer rapidamente.",
"O que você quer de mim, seu porco?",
"Estamos aqui para te libertar.",
"O que você quer de mim, seu porco?",
"Estamos aqui para te libertar.",
"Estamos nos aproximando da colônia. Até agora, você não pareceu ser alguém muito confiável. Vamos ver se você vai se comportar.",
"Como quiser.",
"Então, você estava dizendo a verdade. Você está realmente familiarizado com nossa irmandade. Ainda não sei quando e como você se juntou a nós, mas por enquanto não importa. O ritual começará em breve. Precisamos chegar à caverna. Tenho certeza de que você não se oporá a acompanhar a mim e a várias pessoas locais ao templo.",
"Claro, apenas me diga para onde estamos indo.",
"Atravesse a selva após pousar na costa dos Recifes Brancos. A caverna está situada lá.",
"Então eu tenho o que precisava. Agora é a sua hora de morrer.",
"O que?! Então você é...",
"...Não é quem você pensa! En garde - irmão.",
"Nesse caso, assim que pousarmos, espero ver você na taverna.",
"Bem.",
"Isso é tão legal. E por que me foi concedida essa honra?",
"Não há tempo para explicar. A qualquer momento eles podem descobrir que seus documentos de liberação são falsos.",
"É assim mesmo? Bem, eu permito que você me acompanhe até a colônia de #sGrand Turk# na ilha #sisland_Turks#. Depois disso irei ao fundo deste assunto e decidiremos o que fazer com você.",
"Como quiser.",
"Você não pode me intimidar! Não tenho medo da morte!",
"Hum...de fato...",
"O que é a morte para mim! Isso me liberará para sentar ao lado do meu mestre!",
"Ok, então você não tem medo da morte. Como a vida nesta cela combina com você?",
"...",
"Talvez esta cela seja confortável demais para você. Talvez você prefira algo mais úmido e escuro.",
"...",
"Talvez pudéssemos inundar o chão com água fria, para que você não consiga descansar...",
"Parar! Eu vou te contar tudo. O que você precisa?",
"Onde fica o seu esconderijo, sua pestilência excremental?",
"Perto da colônia de #sGrand Turk#. Em... tosse... tosse... não-o-o.",
"O que? Ah! A vil narceja-de-fígado-de-lírio!",
"Pare de brincar! Vou contar até três, dá-nos a carta, senão! Um...",
"Três!",
"Você está carregando uma certa carta! Precisamos lê-lo. \nNão se preocupe, temos uma cópia do carimbo com o qual está selado. Eu prometo que o cliente não notará. \nFaça-nos esse favor e nós lhe pagaremos 1.000 ouro. O que você diz?",
"O que eu disse? Hmm, como posso dizer...? NãO! E vá colar seu carimbo em algum lugar quente e aconchegante.",
"Hmm... 1000 ouro... Parece tentador. Acho que temos um acordo. Aqui está a carta.",
"Você é um homem sábio ",
". Aqui está o seu dinheiro. Agora vamos dar uma olhada na carta. \nUh-hum, sim... Achei que sim... Agora, eles estão errados sobre isso... Então, aprendi tudo o que preciso saber. Agora...para selar a carta.... Viu, o carimbo é idêntico? Você pode ir.",
"Tudo bem.",
"Então seremos forçados a matar você",
"Tente!",
"O diretor está morto, então você pertence a mim. Agora venha e me mostre o covil dos Animistas!",
"Hah, vá para a ilha de #sisland_Turks#. Lá meus companheiros irão destruir você!",
"Ok, tanto faz... Apenas venha comigo.",
"Isso é tão legal. E por que me foi concedida essa honra?",
"Não há tempo para explicar. Eu intimidei os guardas por enquanto. Depois que pararem de mijar nas calças, eles poderão reunir coragem suficiente para frustrar nossa tentativa de libertá-lo. Nós temos de ir agora.",
"Ah, água? A água não me assusta nem apaga os fogos sagrados que ardem dentro de mim!",
"Tudo bem, estou cansado disso. Talvez eu devesse apenas fazer cócegas em você com minha lâmina, hein?",
"",
};
