string DLG_TEXT[213] = {
"Sim! Capitão.",
"Nada.",
"Você está vivo? Você deveria se considerar abençoado por sobreviver a tal tempestade. Não vi uma tempestade assim em todos os meus anos!",
"Então, onde estou?",
"#sDouwesen#. Parece que o mar trouxe você aqui.",
"Qualquer sinal da minha nave e tripulação! Onde eles estão?",
"Não. Você deveria agradecer às suas estrelas por eu estar aqui para tirá-lo da água. Se eu fosse você, iria para a cidade. Sua tripulação pode já estar lá procurando por você.",
"Essa é uma boa ideia. Obrigado.",
"REALMENTE DAVY JONES DAQUI PARA BAIXO",
"Você parece um rato afogado! Mas você tem sorte de estar vivo... e ainda mais sorte de ter me encontrado.",
"Quem é você? Onde estou?",
"Eu sou Davy Jones, alguns dizem rei do mar, e você pode estar em #sOxbay# ou #sDouwesen#, o que eu preferir. Você foi lavado como um barril vazio de rum",
"Bem, isso são boas e más notícias. Eu estava a caminho de ser enforcado, então estou salvo disso, mas não tenho navio, ele foi queimado e afundado. Não sei o que fazer a seguir.",
"Realmente uma história triste. Talvez eu possa ajudar... por um preço.",
"Assistência que eu poderia usar. Mas a que preço, quanto dinheiro você quer?",
"Não preciso de dinheiro. Preciso que você navegue comigo. Estou em uma missão e preciso de uma boa tripulação e de homens como você.",
"Eu sei que não estou em posição de negociar aqui, mas sou dono de mim mesmo e tenho assuntos para resolver, então não acho que poderia assinar com você, senhor.",
"Ouça meus termos. Levantarei seu navio e lhe darei treze anos para cuidar de seus assuntos. Então você me dará sua alma e navegará comigo por cem anos.",
"Você me permitirá treze anos sozinho, sem interferência?",
"Essa é a minha palavra. Decida agora ou vou deixá-lo aqui... com um destino incerto.",
"Muito bem, aceito seus termos.",
"Não, isso é um custo muito alto. Vou me defender sozinho e confiar na fortuna da senhora.",
"Assim seja... a senhora que você procura e seus oficiais estão na Ilha de Muelle esperando sua chegada.",
"Como faço para voltar para meu navio?",
"Vire-se e caminhe até a costa. Você encontrará seu barco esperando lá, digamos, com uma tripulação mínima. Ha! Ha! Ha!",
"Muito bem",
"Então nossa conversa termina aqui... agora você vai descobrir o quanto a senhora fortuna pensa de você.",
"Adeus.",
"Olá senhor, você parece um capitão! Talvez você precise de alguns canhoneiros? Meu nome é Ragetti e este é meu tio, Pintel.",
"Sim, sou o capitão Jack Sparrow. Quais qualificações você tem?",
"Bem, nós estávamos...",
"...",
"Eu era o único, mas você e eu voltamos há muito tempo. De qualquer forma, deitado no fundo do mar eu não sabia o que fazer. Eu não podia morrer, então chamei Davy Jones e ele me resgatou. Tive que jurar que me juntaria à sua tripulação e serviria durante 100 anos, mas ele deu-me cinco anos para me recompor antes de entrar no navio, com a condição de não voltar a falar com o meu filho. Ele está na Inglaterra, então isso não é difícil.",
"Ah! Agora eu entendo. Eu também estou em uma situação semelhante. Davy lhe faz um favor e você tem que concordar em servi-lo. Mas por que você não se afogou?",
"Ah! Você vê, o tesouro está amaldiçoado, então é. Você está condenado a caminhar pela terra enquanto a tiver. Você não pode morrer, provar comida ou bebida. Barbossa tem que recuperar tudo e depois levá-lo de volta para a Isla de Meurte e cada homem deve pagar com seu sangue. O problema é que faltam alguns, e tem que ser completo para acabar com a maldição.",
"Isso parece algo que eu meio que conheço.",
"É assim que pode ser. Só descobrimos sobre a maldição quando dois rapazes brigaram. Um matou o outro, só que ele não morreu. É claro que ouvimos rumores, mas não acreditávamos neles até então. Então, quando nos desentendemos, Barbossa me amarrou a um canhão e me jogou ao mar. Ele agora saiu navegando tentando recuperar todo o ouro dos tripulantes, alguns haviam partido quando chegamos ao porto no caminho de volta. Tudo o que sei é que ele não terá sucesso.",
"Por que não?",
"Eu tinha uma moeda na bota quando me jogaram ao mar. Enviei para meu filho, Will, na Inglaterra. Barbossa nunca o encontrará lá. Essa é a minha vingança pelo tratamento que me deram",
"E agora? Preciso de um navio, alguma sugestão?",
"Meu? Só estou tentando pensar em uma maneira de rescindir o contrato com Davy Jones. Sua melhor aposta será conversar com algumas pessoas daqui, para ver se elas sabem de algum navio que está barato.",
"Hum. Acho que deveria começar a conversar, mas esta é uma ilha pirata!",
"Ei! Tendo navegado com Barbossa e com aquela marca no pulso, você agora é um pirata. A palavra terá viajado rápido. Não acho que você será bem recebido em nenhum outro lugar.",
"Tudo bem, parece que não tenho muita opção. Obrigado pela ajuda.",
"Ó capitão ",
"! Estou MUITO feliz por ter encontrado você. Estou com tantos problemas, bem, Will está. Bem, eu também estou.",
"Uau, acalme-se, Bootstrap, enrole suas velas. Agora devagar, qual é o problema?",
"Oh querido, por onde começar! Bem, Barbossa acha que encontrou a última peça do tesouro amaldiçoado. Ele acha que a filha do governador Swann está com isso. Mas isso não pode ser possível, porque mandei para o meu filho, ou assim pensei. Bem, eu fiz, mas ele não tem agora. Parece que ele veio da Inglaterra para tentar me encontrar. Seu navio foi atacado e afundado por piratas, e tragédia das tragédias, provavelmente éramos nós no #scursed_ship#. ",
"Bootstrap um pouco confuso, mas acho que entendi. E...?",
"Bem, parece que Will estava com sua moeda, mas a perdeu quando foi resgatado, o único sobrevivente do ataque. Descobri que foi o navio do governador Swann que o resgatou quando ele veio com a filha para assumir o cargo de governador das ilhas. Parece que eles, a filha dele, devem ter tirado a moeda de Will então.",
"Então, o que isso tem a ver com seu filho? É a filha do Governador que Barbossa procura.",
"Sim, sim, eu sei, Barbossa capturou a filha do governador, Elizabeth, e a levou embora no #scursed_ship#. Mas o jovem Will está perdidamente apaixonado por ela.",
"Ah! amor jovem. Eu também tenho o mesmo problema com membros do sexo oposto se apaixonando por mim. Triste Bootstrap, mas não o fim do mundo.",
"Mas você não entende, o jovem idiota e alguns de seus amigos roubaram um navio da marinha para procurá-la. O garoto estúpido não sabia para onde estava indo e foi capturado por piratas. Eles trouxeram ele e o navio para cá.",
"Então por que você não vai e resgata a liberdade dele? Pirata para pirata, tenho certeza que você poderia fazer um acordo",
"Não, eu não posso fazer isso. Parte do meu acordo com Davy Jones era que eu não voltaria a falar com meu filho, ou Davy o mataria. Você vai me ajudar?",
"Ah! Agora vejo seu problema. Deixa-me ver o que posso fazer. Eu me dou muito bem com a maioria das pessoas daqui.",
"Obrigado ",
", Estarei para sempre em dívida com você.",
"Descanse, velho amigo. Deixe o assunto comigo. É melhor você sair agora, antes que se espalhe a notícia de que você está aqui. Até logo.",
"Oh, amigo, infelizmente estou muito ocupado para falar no momento. Tenho uma ideia nova e estou um pouco distraído.",
"Parece bom. Apenas tome cuidado e não nos exploda",
"Me ajude! Me ajude!",
"Aguentar. Eu estou tentando!",
"Me ajude! Me ajude!",
"Não, obrigado, eu não arriscaria minha vida por você.",
"Oh! Obrigado, muito obrigado, ",
", se não fosse por você, aqueles simplórios teriam me feito em pedaços.",
"De nada.",
"Com licença, amigo, mas tenho um experimento que precisa da minha atenção, então devo me despedir de você agora.\nNão fique chateado. Algumas pessoas muito legais se juntaram a mim em minha casa. Acho que você terá prazer em conversar com eles.",
"Bom, estou interessado em conhecer seus convidados.",
"Estou feliz em ver você, onde está ",
"Danielle",
"?",
"Hmm... pensei que ela já estivesse aqui.",
"Oh não! O que aconteceu com você, ",
"? Você não é você mesmo...olhe suas roupas, e aqueles hematomas, e você está todo molhado!",
"Deixe-me recuperar o fôlego! Traga-me um pouco de vinho, estou morrendo de sede.",
"Aqui está.",
"É isso? Se isso é um iate, então sou um rei! Isso é apenas um barco de pesca!",
"Isso é tudo que posso fazer por você ",
", e não fique chateado comigo.",
"Desculpe. Suponho que não tenho escolha. vou ter que procurar ",
"Danielle",
" com esta banheira.",
"Aqui está o seu vinho. Agora me diga o que aconteceu?",
"É uma longa história. É ",
"Danielle",
" aqui? Não consigo ver o navio dela.",
"Não, ela ainda não veio.",
"Maldição! Aquela garota não consegue ficar no mesmo lugar por mais de um momento. Por sorte, perdi meu navio!",
"Hmm... eu tenho um pequeno iate. Talvez possa ajudá-lo?",
"Um iate? Sua velha raposa, por que não me contou antes?",
"Bem, é um iate muito pequeno...",
"Mostre-me.",
"Não, ela ainda não veio.",
"Maldição! Aquela garota não consegue ficar no mesmo lugar por mais de um momento. Vou precisar encontrá-la.",
"O que você está falando? Devo minha vida a você! Posso saber o seu nome?",
"Meu nome é ",
", eu sou um capitão.",
"Que interessante! Tenho algumas invenções que podem ser instaladas em um navio.\nAh, por que estamos aqui? Estou muito grato a você por me resgatar... Insisto em ir para minha casa agora, quero retribuir sua gentileza. Vem vem.",
"Tudo bem, vamos dar uma olhada em sua casa. Só não faça nada com o meu navio",
"Precisamos voltar para o navio. Temo que a destruição do templo possa causar um terremoto ou até algo pior! Os Incas eram especialistas em fazer armadilhas elaboradas.",
"Armadilhas que podem causar um terremoto? Parece muito rebuscado para mim.",
"Sim Sim! Tudo bem, vamos supor que não haverá um terremoto - mas as inscrições nas paredes do templo mencionam uma penalidade severa que eliminará da face da Terra aqueles que cometem sacrilégios.",
"A queda do templo ao redor de nossas orelhas foi bastante severa. Essa foi provavelmente a penalidade. Ainda devemos tentar procurar o tesouro.",
"Capitão, não! Nenhum tesouro na Terra vale a pena perder a vida!",
"Bem, o terreno parece um pouco instável agora, então talvez devêssemos sair e voltar. Se vai haver uma erupção vulcânica, não quero ficar aqui quando isso acontecer.",
"Sim, acho que não é uma má ideia...",
"Ela poderia ter esperado pela resposta, pelo menos.",
"Vamos seguir o exemplo dela ",
". Eu irei para a direita e você, capitão, irá direto. Se você não se importa.",
"Qual é a diferença!? Apenas tente não se perder.",
"Eu duvido. As inscrições dizem que a armadilha fica na entrada da alcova do deus sol. Parece que é aqui que começa o labirinto.",
"Labirinto?",
"Sim, labirinto. Eu não mencionei isso? Para chegar aos tesouros, você deve passar pelo labirinto. Suponho que apenas uma dessas passagens nos levará até eles.",
"Acho que quem criou este templo gostava de piadas.",
"Tenha cuidado no templo, meus amigos. Está escrito na placa que há uma armadilha na entrada da alcova do deus sol.\nInfelizmente, não há explicação de como desativar a armadilha, mas dizem que você pode encontrar as instruções dentro do templo.",
"Obrigado pelo aviso. Você já terminou a tradução?",
"Sim, mas os papéis estão úmidos e amassados. Não consegui entender tudo o que estava escrito. Havia uma parte sobre a alcova e algum deus que está dormindo agora. Não acho que você deva prestar muita atenção a isso. Com certeza será um conto de fadas nativo.",
"Maldição! Onde estão os tesouros?",
"Suponho que a entrada do tesouro, ou para ser mais preciso, da cripta funerária, esteja na alcova.",
"Vá em frente Então.",
"Espere, o problema é que você só pode entrar no templo quando ele estiver iluminado pela luz do sol! Algum mecanismo complexo, eu realmente não sei...",
"É assim mesmo? Teremos que esperar pelo sol, então. Espero que a estação das chuvas não comece hoje.",
"Se minha memória não me falhou, íamos ao templo.",
"Ah, sim, isso mesmo.",
"Ah, capitão ",
"! O que você está fazendo aqui? Eles também colocaram você na prisão?",
"Não, meu amigo, vim aqui para te resgatar.",
"Salvar-me? Como? Não creio que você consiga persuadir o diretor a me libertar sem uma ordem do governador!",
"Eu já falei com ele sobre isso ",
".",
"Isso é realmente verdade? Você é uma pessoa incrível capitão, mas por que veio aqui me ajudar de repente?",
"Para ser honesto, quero que você me faça um favor em troca.",
"Hmm...estou pronto para fazer isso capitão, mas talvez possamos continuar essa conversa em outro lugar?",
"Claro. Vamos até o farol, e eu te conto tudo no caminho.",
"... Imprudente e imprudente! Não consigo nem acreditar que as pessoas sejam capazes disso...",
"Cada um tem sua noção particular de diversão.",
"Então, você quer que eu traduza o texto nativo deste pedaço de papel? Você está especialmente interessado na parte que descreve como entrar no templo, certo?",
"Sim. Você disse que conhece a língua nativa.",
"Sim, sim... passei muito tempo estudando a população aborígine local... e, ",
", se você estiver partindo em uma expedição em busca daquele templo, eu navegarei com você!",
"...Por que razão?",
"Eu sei o motivo pelo qual você está indo para lá... mas garanto que não preciso disso. Só quero estar lá para ver tudo e quem sabe fazer uma descoberta marcante!",
"Hmmm... eu não quero que você sofra as provações da viagem marítima...",
"Isso não faz sentido! Juro, ",
", se você não concordar em me levar com você, não traduzirei uma única palavra deste texto!",
"Então, está resolvido. Eu vou te levar conosco.",
"Excelente! Estou muito grato a você! Quanto à tradução, preciso de algum tempo. Acho que vou demorar alguns dias. O dialeto é bastante incomum.",
"Vamos consertar o navio e nos preparar para navegar.",
"Ah, é você, capitão! Quase terminei a tradução. Preciso de mais uma semana e pronto.",
"Mal podemos esperar. Por que você não continua traduzindo durante a viagem?",
"Sim, é uma boa ideia, por que não? terei dor de cabeça quando estiver navegando? Acho que não... Fico enjoado? Não, acho que não... Tudo bem, concordo. Mas, agora estou curioso...qual é a pressa?",
"Suponho que a batalha no porto passou despercebida, então talvez eu deva explicar...",
"Uma batalha? Que batalha? Em que porto?",
"...O governador Silehard não vai nos dar a colônia de presente... e suspeito que ele planeja nos enforcar na primeira oportunidade.",
"Pendurar? Ah, entendo. Continuarei meu trabalho durante a viagem. Devo dizer que tivemos sorte em partir nesta época. Dizem que só é possível entrar na baía de #sKhael Roa# duas vezes por ano.",
"Por que os navios não podem se aproximar da ilha em nenhum outro momento?",
"Segundo o texto é um fenômeno natural que afeta as marés.",
"Provavelmente é por isso ",
"Raoul Rheims",
"não consegui chegar ao templo.",
"Talvez. Mas também menciona outros perigos. Perigos que aguardam aqueles que buscam o coração do templo do deus sol.",
"Continue lendo. Você terá os próximos dias para investigar tudo. Vamos para o navio.",
"A propósito, capitão, vou precisar de uma cabine, e seria bom se fosse em algum lugar perto da popa, para que os gritos da tripulação não me distraiam do meu trabalho de tradução.",
"Hum. Tudo bem. Você terá uma cabine.",
"Não se apressem, meus amigos. Estamos no limiar. Em algum lugar por aqui deve haver a entrada secreta para a câmara mortuária.",
"Você acha que deveríamos começar a bater nas paredes?",
"De jeito nenhum. Estas imagens nas paredes devem nos dizer como encontrar a entrada da câmara mortuária e nos alertar sobre possíveis armadilhas.",
"Todos os perigos não estão atrás de nós agora?",
"Não, duvido. Os engenheiros nativos fizeram o possível para proteger seu templo. Tenho certeza de que há muitos perigos esperando por nós.\nBem, veremos em breve. Agora, deixe-me pensar por um minuto.",
"Sim por favor.",
"Oh não! Não toque!",
"Qual é o problema?",
"Isto é uma armadilha... Ah, não! Você já tocou na pedra!",
"Oh não! Diga-me o que aconteceu?",
"Esta é a última armadilha deixada pelos criadores do templo! Por que você não esperou! Eu poderia ter lido as inscrições para saber como evitá-lo, mas não, era preciso tocar em alguma coisa!",
"Se isso é uma armadilha, por que ainda estamos vivos?",
"Se esperarmos mais, estaremos mortos com certeza! A armadilha abre um canal que leva a água do lago da montanha para as cavernas sob o templo. \nA câmara quente do vulcão situada sob o templo ainda está ativa, então você pode imaginar o que acontecerá quando a água atingir a lava quente e ardente!",
"Hmmm. Será...? Você acha que pode ficar um pouco abafado aqui?",
"Abafado? O vapor explodirá o templo! Devemos partir!",
"E o tesouro?",
"Esqueça o tesouro! Eu tenho que sair daqui!",
"Não existe uma maneira? ...",
"Leve-me de volta para casa, capitão. Por favor? Receio que isto seja muito mais aventura do que preciso, na minha idade.",
"Você está certo, vamos zarpar.",
"Por favor, capitão! Nós temos que ir!",
"Tudo bem!",
"Bem, capitão, isso certamente foi uma aventura!",
"Isso é verdade, Bootstrap. Estou feliz que todos nós tenhamos conseguido passar com segurança.",
"É terrível não podermos voltar ao templo para estudar mais sobre essas pessoas perdidas.",
"Lamento não podermos ficar para encontrar o ouro, se é que havia algum.",
"Ah, acho que tem ouro aí, capitão, é só uma questão de descobrir um jeito de consegui-lo....Hmmm...",
"Bootstrap, se alguém pode fazer isso, você pode. Obrigado novamente por sua ajuda.",
"...",
"Inicialização?",
"Desculpe interrompê-lo, capitão, mas não pude deixar de ouvir o que você estava dizendo aí e acho que posso ajudar.",
"Realmente, é rude escutar, você sabe! Enfim, quem é você e como pode ajudar?",
"Meu nome é William Turner. As pessoas me chamam de Bootstrap Bill. Ouvi para qual cidade a sua Srta. Brinkley está navegando.",
"Ah! Nesse caso, posso ignorar a sua pequena indiscrição. Que cidade é então e em que ilha?",
"Tenho uma condição primeiro, capitão. Estou precisando de uma posição a bordo de um bom navio. Você me aceitará como seu oficial?",
"Bem, apesar das botas, você parece bastante capaz. Muito bem então você está contratado. Agora, para onde devemos ir?",
"Obrigado capitão, você não vai se arrepender. Precisamos ir ao acampamento pirata em Nevis.",
"Ah! Bom! Nós nos resolveremos e depois navegaremos.",
"Capitão, não acho que seria uma boa ideia irmos todos juntos para a cidade. Vamos atrair muita atenção.",
"Você está certo, Bootstrap. Vocês dois vão em frente e perguntem para ver o que conseguem descobrir. Preciso reabastecer a nave de qualquer maneira. Nos encontraremos na Taverna mais tarde.",
"Capitão! Parece que Brinkley está aqui, mas não no acampamento. Precisamos encontrar um contrabandista de diamantes chamado Eastwood, ele tem um lugar em algum lugar na selva. Ela supostamente está trabalhando com ele.",
"Bom trabalho, Bootstrap. Vamos encontrá-lo então.",
"É ela! Essa é a mulher Brinkley. Ela foi morta!",
"Bem, ela com certeza não parece que vai a lugar nenhum. Precisamos falar com Eastwood novamente.",
"Capitão, temo que devo deixá-lo. Acabei de ver o capitão Barbossa ali e o navio dele, eu sei, vai para a Inglaterra. Eu realmente quero voltar para lá. Então, com sua permissão...",
"Claro, Bootstrap. Talvez nos encontremos novamente um dia. Boa sorte.",
"",
};
