string DLG_TEXT[134] = {
"Ouvi dizer que você quer me ver. Então, que negócio você tem para mim?",
"Eu gostaria de oferecer meus serviços.",
"Você é um capitão? Qual o seu nome?",
"Meu nome é ",
", capitão do '",
".",
"Bom, vou lembrar seu nome. Agora me diga o que fez você vir até mim",
"Eu gostaria de conversar sobre negócios com você.",
"Nada. Vou me despedir, se você me permitir",
"Você pode sair. Mas não desapareça completamente, é possível que eu tenha planos para você.",
"Como você diz, #saddr#.",
"Sou todo ouvidos. O que fez você vir até mim?",
"Negócios #saddr#.",
"Estou indo embora.",
"Então vamos falar de negócios.",
"Estou aqui em nome daquelas mulheres que estão à sua entrada.",
"Sua missão é um sucesso. As crianças desaparecidas foram devolvidas aos seus pais",
"Quero falar sobre um homem que encontra o favor de sua graça.",
"Sua missão está cumprida, #saddr#.",
"Não tenho nada para discutir com você no momento, #saddr#",
"Sim, eu já sei disso, aqui está sua recompensa. Espero que no futuro possa utilizar seus serviços.",
"A qualquer momento, #saddr#",
"Então, sobre quem você quer discutir.",
"Um bucaneiro, #sBernardo Gamboa#, #saddr#.",
"",
"",
"Ah. Aquele homem?! E o que você quer que eu diga? Pelo que eu sei, a reputação dele é imaculada...",
"Você estaria errado. Pelo que sei, ele sequestrou um homem da sua cidade.",
"Ah, ah, ah. Você tem certeza sobre isso? Não quero insultá-lo injustamente.",
"Se você não se importa, investigarei isso em particular. Ninguém saberá do seu envolvimento. Se ele não sequestrasse este homem, seu relacionamento com ele permaneceria intacto; se ele o fizesse, você mostraria a todos o quão justo e poderoso você é.",
"Hmmm... Isso não é irracional. Na verdade, não arrisco nada neste caso. Você pode descobrir o que está acontecendo. Se sua missão terminar com sucesso, eu recompensarei você. Mas, como esta é uma iniciativa sua, será uma quantia modesta.",
"Obrigado #saddr#.",
"Lembre-me, o que estávamos discutindo?",
"Estávamos falando sobre um homem sequestrado.",
"Ah, sim, eu me lembro. Pelo que entendi, ele realmente foi sequestrado.",
"Sim. O canalha não quis devolver o homem e foi massacrado pelos seus próprios homens.",
"Bem, não há pirata - não há problema. Aqui está sua recompensa. Você pode sair do meu quarto agora...",
"Como queira.",
"Ah, era isso que você queria discutir...",
"Não entendo por que você não leva isso mais a sério. Não é sua responsabilidade garantir a segurança dos cidadãos da colônia?",
"Capitão, vou perdoar sua crítica a mim desta vez. Não faça isso de novo se quiser ser favorecido neste escritório. \nQuanto a essas mulheres... posso dizer que você é um homem inteligente, então vou lhe contar uma coisa.",
"Sou todo ouvidos.",
"Dois soldados foram encontrados mortos hoje. Um deles tinha um pedaço de tecido carmesim na mão. \nVárias horas antes de serem descobertas, uma fragata foi avistada navegando para longe da ilha a todo vapor.",
"E isso interrompe sua investigação?",
"Bem... É óbvio que as crianças sequestradas foram levadas da ilha. Nessas circunstâncias, a busca não vale o dinheiro que será gasto nessa expedição. \nAlém disso, eles poderiam estar em qualquer lugar. Você deveria entender isso, capitão. O mar oferece muitos lugares para se esconder. \nDe qualquer forma, se você está tão emocionado com a dor dessas mulheres, ofereço-lhe o desafio de encontrar seus filhos. \nPrometo que se a busca for bem-sucedida, mostrarei minha gratidão a você.",
"Tudo bem, concordo, mas primeiro gostaria de saber onde posso encontrar uma testemunha que viu a fragata.",
"Não, não quero perder meu tempo com essas bobagens.",
"Você aceita? Perfeito! Você pode encontrar a testemunha na taverna. Foi um capitão mercante quem avistou aquele navio.",
"Obrigado, posso me despedir agora?",
"Desejo servir a Holanda, Excelência.",
"A Holanda sempre tem prazer em aceitar novos capitães ao seu serviço. ",
"Nós somos",
"não",
" atualmente em guerra com ",
"o ",
"qualquer nação",
". Claro,",
" mas",
" Os piratas devem sempre ser afundados à primeira vista.",
"Vou deixá-lo orgulhoso, Excelência.",
"Como estou, senhor?",
"Você afundou ",
" Navios franceses ",
" navios piratas, um total de ",
" navios.",
"Obrigado.",
"Espero que você não tenha problemas com meu serviço, senhor.",
"Na verdade não, capitão! Na verdade, é um prazer conceder-lhe uma comissão na Marinha de Sua Alteza Real. Como oficial, você será recompensado por cada navio que afundar a serviço da Holanda.",
"Sinto-me honrado, Excelência, e esforçar-me-ei por corresponder à confiança que Sua Alteza Real deposita em mim.",
"Eu gostaria de receber meu salário, senhor.",
"Bem, você afundou ",
" Navios franceses ",
" Navios piratas, ",
" navios totais. Seus salários atuais são ",
", então um total de ",
"Obrigado senhor.",
"Escória traidora! Afunde os navios dos seus compatriotas, sim? Você está dispensado do serviço militar e seu nome é retirado da lista; e nunca mais quero ver a tua cara nesta cidade!",
"...",
" desde a última vez, aqui está ",
" ouro",
"Ouvi dizer que estou pronto para uma promoção.",
"Você é realmente! Excelente trabalho. Sua nova classificação é ",
"Obrigado senhor.",
" Navios espanhóis ",
" Navios ingleses, e ",
"Oh sim? Tenho uma proposta para você, capitão.",
"De fato?",
"Aprendi que você concluiu a tarefa com sucesso; meus parabéns, capitão! Aqui está sua recompensa.",
"Meus agradecimentos; Foi um prazer ajudá-lo.",
"Você deve destruir o ",
" navio ",
"missão pirata",
" ameaçando o envio ",
". Se você afundá-la, vou recompensá-lo com uma boa quantia de ",
" ouro. O que você diz, capitão?",
"Você não ouvirá falar dela novamente, isso eu prometo.",
"Receio não poder ajudá-lo.",
"Anseio por perdão, Excelência.",
"Estou interessado em aprender sobre as relações de #sgov_nation# com outras nações.",
"Estou procurando uma Carta de Marca.",
"Ah, ",
", que bom que você passou por aqui. Eu gostaria de apresentar meu ",
". Ela virá assim que terminarmos os negócios.",
"Não posso mais servir ",
", vossa Excelência.",
"Cansei de servir ",
"Como garantia de que você é um capitão competente e para recompensar meu tempo apresentando seu caso a ",
", devo te pedir ",
" ouro.",
"Sem chance.",
"Muito bem.",
" À luz do seu serviço anterior, ",
" concede a você a classificação de ",
"Você prejudicou ",
", e ",
" não esquece seus inimigos. Saia imediatamente, ou os guardas vão te jogar fora!",
"...",
"Você causou ",
" grande dano, capitão, mas ",
" está disposto a ignorar suas transgressões passadas... por um preço: ",
"Muito bem, senhor. Aceito.",
"É um prazer lidar com você, ",
"E você, Excelência.",
". Além disso, você é premiado ",
" hectares de terra por ordem de ",
"Tem certeza, ",
" lamentaremos perder seu serviço.",
"Sim eu sou.",
" não gosta de vira-casacas ",
"Uh, não importa.",
"Muito bem. Mas espero que você reconsidere, com o tempo...",
"Adeus, ",
"Huh?",
"Difícil.",
"",
};
