string DLG_TEXT[18] = {
"Obrigado por nos salvar, Capitão Jack Sparrow.",
"Sem problemas.",
"Você está aqui para nos salvar, capitão?",
"Capitão Jack Sparrow, sim, sou Sao Feng que me contratou para levá-lo para casa novamente.",
"Somos livres para escapar?",
"Não, ainda não, ainda tenho um trabalho a fazer aqui.",
"Somos livres para escapar?",
"Sim, a costa está limpa, pelo menos no covil, de qualquer maneira.",
"Obrigado Capitão Sparrow, qual é o plano agora?",
"Padre Domingues está com as chaves, ele vai te deixar sair enquanto eu vou parar o navio na baía.",
"Minha irmã e eu estamos muito gratos por você Capitão Jack Sparrow, queremos ir com você para a taverna!",
"Ok, para a taberna são as senhoras, e depois para a igreja para ver o Padre.",
"Uau, Capitão Sparrow, devemos a vocês dois agora.",
"Obrigada, senhoras, pela diversão tão boa, vamos para a igreja agora.",
"Minha irmã e eu estamos muito gratos por você Capitão Jack Sparrow, podemos explorar a praia, por favor?",
"Claro e talvez possamos encontrar um local tranquilo para nos deitarmos.",
"Uau, Capitão Sparrow, devemos a vocês dois agora.",
"Obrigada, senhoras, pela diversão tão boa, vamos para a igreja agora.",
"",
};
