string DLG_TEXT[71] = {
"Ah! Foi uma boa soneca. Eu gostei disso.",
"Estou feliz por você.",
"Er... Sim, muito gentil da sua parte, tenho certeza. Sente-se garoto, sente-se. SENHORIO! mais do seu rum, por favor! A propósito, quem é você, rapaz?",
"Meu nome é Capitão ",
", e acabei de chegar a estas ilhas em busca de fortuna. E quem é você, senhor?",
"Acabou de chegar, de fato? Novo nas ilhas, hein? Mmmm.. Você teria interesse em ingressar em um grupo nobre, com uma causa nobre, e ficar rico no processo?",
"Como mencionei, senhor, estou aqui para fazer fortuna, mas você ainda não me disse quem é.",
"Meu nome é Mings, rapaz. Sir Christopher Mings, para ser mais preciso, e eu represento um grupo de, er..., cavalheiros bucaneiros, que pretendem formar uma irmandade e concluir uma nobre aventura neste arquipélago. Então, você estaria interessado em se juntar a nós?",
"Bem, eu gostaria de saber mais sobre isso. Detalhes, quero dizer. Você sabe que existem bucaneiros... e também existem piratas, e não tenho certeza se sei a diferença. Se é que me entende.",
"Aqui não, rapaz, aqui não. Demasiadas orelhas e este rum é como água! Mas posso levá-lo para minha residência e contar tudo lá.",
"Sim, isso parece muito emocionante. Sim, vou me juntar a você.",
"Não, Sir Christopher, acho que recusarei sua oferta por enquanto.",
"Bom rapaz, bom rapaz. Dê-me um minuto para sair daqui e depois vá para a sala no topo da escada, em frente ao estaleiro. É melhor não sermos vistos saindo juntos.",
"Muito bem, senhor Christopher. Eu me juntarei a você em breve.",
"Ah! bem, não pode ser ajudado, suponho. Se você me der licença. Sinto necessidade de cochilar.",
"Oh! sim, claro, senhor Christopher. Bom dia para você. [PENSA Ou talvez eu deva dizer boa noite!].",
"Ah! Jack, rapaz. Você está aqui.",
"CAPITãO Jack, se você não se importa com Sir Christopher. [PENSA: E é claro que estou aqui. Você não poderia falar comigo se eu não estivesse.]",
"Tanto faz, Capitão Jack, rapaz. Agora vamos ao que interessa. Você vai querer falar sobre pagamento, é claro.",
"Bem, sim, mas não deveríamos discutir o que você precisa que eu faça primeiro? [PENSA: Isso poderia afetar o valor que eu precisaria pagar. Não quero parecer barato!]",
"Bom rapaz, Capitão Jack. Então aqui está o plano. Um grupo de nós, bucaneiros, está bastante chateado com a forma como alguns dos piratas por aqui estão ficando gananciosos. Tomando navios para si e não compartilhando o saque. Totalmente antidesportivo, se é que você me entende.",
"Sim, eu pude ver isso, isso poderia ser perturbador.",
"Sim, rapaz. Então concordamos em formar nossa própria irmandade, assim ganhamos força em números. Podemos então lutar em grupo, o que torna tudo mais justo. E vamos montar nossa própria sede onde poderemos trabalhar sem sermos detectados. Todos os piratas sabem onde ficam as outras ilhas.",
"Então, onde eu entro?",
"Você é novo aqui. Ninguém sabe quem você é, então você poderia carregar, er.. itens, para nós, e eles provavelmente não o impedirão.",
"Unid? que itens? Certamente você quer dizer bens?",
"Ah! rapaz. Você é inteligente, você é. Bem, há outra parte do plano.",
"[PENSA: Agora, como eu sabia que haveria.] Sim, Sir Christopher e o que é isso?",
"Não tão rápido, capitão. Precisamos provar seu valor primeiro. Haverá um Sir Cutler Beckett na Taverna, eu mesmo não suporto esse homem. Ele tem uma vingança contra os piratas, mas nós dissemos, para que ele ouvisse, que você é um capitão de primeira classe. Ele lhe oferecerá um emprego, que você aceitará. Será uma corrida para #sisland_Antigua#. Lá você conhecerá uma senhora, o nome dela é Tia Dalma. Ela lhe dirá o que fazer quando chegar lá",
"E se ele não me oferecer essa corrida? [PENSA: Tia Dalma? Agora, de onde eu conheço esse nome?]",
"Ele vai, rapaz, mais cedo ou mais tarde. Ele está com medo de ser atacado por piratas neste momento, e também avisamos que ele será atacado, então estará procurando uma escolta. Nós lhe daremos 2.000 em ouro para lojas e uma equipe, eu sei que Beckett vai investir algum dinheiro em você, então você deve estar bem protegido.",
"O que eu faço quando tiver feito esse trabalho #sisland_Antigua# de Beckett?",
"Apenas me encontre aqui. Não importa o que Beckett lhe diga, apenas volte aqui quando tiver feito aquela corrida, e conversaremos mais.",
"OK. Para a Taverna é isso. Espero ver você em uma ou duas semanas.",
"Ah! Então você está de volta capitão ",
" rapaz, espero que você tenha o documento com você?",
"Sim, senhor Cristóvão. Eu tenho a bússola e o mapa agora.",
"",
"",
"",
"",
"Ah! Capitão Jack, rapaz, você está de volta. Você teve sucesso, eu confio?",
"Essa foi uma corrida SLAVE. Você sabia disso?",
"Eu sabia que você saberia o que fazer, rapaz. Você não teria conseguido os 'itens' se não tivesse, certo?",
"Calma rapaz, você não transportou nenhum escravo, não é?",
"Isso está começando a parecer que você está dando desculpas. Você conseguiu os 'itens' agora, não foi?",
"Bem, eu peguei uma espécie de bússola da mulher Tia Dalma e peguei parte de um mapa antigo do armazém. Era para Cutler Beckett.",
"A mulher Tia Dalma me deu uma bússola velha, mas acho que não está funcionando.",
"Quase fui morto. Era muito perigoso lá. Tive sorte de escapar com vida.",
"Bom rapaz, bom rapaz! Você provou o seu valor. Agora deixe-me apresentar nosso convidado, Tenente Peter Willemões, da Corte Real Dinamarquesa.",
"Apenas a bússola? Isso é tudo que você tem?",
"E você terá sorte de escapar daqui com vida também. Não posso usar você, nem você pode usar a nave que lhe demos. Você encontrará um tartane no porto. Agora vá embora!",
"Prazer em conhecê-lo, senhor.",
"Isso foi tudo que a mulher me deu, Sir Christopher.",
"Sim, senhor Cristóvão. Bom dia. [PENSA: Isso foi um pouco duro]",
"Preciso que você o acompanhe até #sisland_Guadeloupe# e se encontre com o Capitão Petros, que lhe contará mais sobre nossa missão. Nosso Sr. Gibbs está esperando lá fora e ele se juntará ao seu navio e irá com você. Oh! e a propósito, aqui estão 5.000 em ouro pelos seus serviços até agora.",
"Não a mulher, rapaz. Alguém está tentando contrabandear algo muito valioso de #sisland_Antigua# para Cutler Beckett. Volte lá, pergunte por aí e intercepte.",
"Obrigado, senhor Cristóvão. Eu cuidarei disso, então #sisland_Guadeloupe# é isso.",
"Sim, senhor Christopher, partirei assim que tiver reabastecido o navio.",
"Venha aqui, Jack, rapaz. Parece que temos um problema então?",
"Er.. Sim, Sir Christopher, temo que sim.",
"Então, aquele bolinho de trapo, Beckett está enfiando o nariz onde não é desejado, hein!?",
"Você poderia colocar dessa forma, Sir Christopher.",
"Bem, parece que a sorte está sorrindo para nós de qualquer maneira. O capitão Nathan nos contou para onde o capitão Damski levou seu navio, o que se encaixa perfeitamente no plano que o capitão Konrad e o tenente Peter Willemões elaboraram.",
"Sorrir faz bem! Eu gosto disso! E um plano! Eu não esperaria menos da senhora Fortune e de vocês, senhores, de qualquer maneira. Então, qual é esse plano?",
"Vou deixar Konrad explicar, ele é melhor em estratégia do que eu. De qualquer forma, acho que preciso de uma soneca rápida!",
"Muito bem.",
"Bem, aí está, capitão ",
", rapaz. Agora você deve escolher. Com Konrad para #sisland_Turks# pelo seu navio, ou com Philippe e Maximus para #sisland_Guadeloupe# pelo tesouro. Qual será?",
"Vou pegar o tesouro primeiro. Muitas pessoas estão interessadas nele e podemos perder a chance de obtê-lo mais tarde.",
"Eu irei com o Capitão Konrad. Devo ter meu próprio navio se quiser ser mais útil para completar a outra tarefa.",
"",
};
