string DLG_TEXT[45] = {
"Eu vi sua briga com nosso boné. Bem, de acordo com a nossa lei, agora você é nosso novo capitão, e o navio pertence a você.",
"Onde posso encontrá-lo?",
"Ah, fica perto, na baía de Palm Beach. Vire à esquerda ao sair da aldeia e logo você a verá.",
"Perfeito! Comigo por perto, vocês saberão o que significa ser verdadeiros cães do mar, rapazes!",
"Eca. Você deve ser aquele capitão Gombo de quem estava falando. Você está atrasado... Unghh... Se você tivesse chegado apenas cinco minutos antes, eu não teria essa adaga enfiada no meu peito. Ungh...",
"Droga! Alguém esfaqueou este rapaz!",
"Desaparece, otário!",
"Com prazer. Mas não até eu descobrir por que um dos meus homens está inconsciente na grama, e na sua companhia.",
"Este homem é um escravo da plantação.",
"Não, ele não é, tenho os papéis dele aqui mostrando que ele é meu.",
"Oh, erro nosso, certifique-se de que ele não volte aqui.",
"Ok senhor, eu irei. (PENSA: Se vocês tiverem sorte.)",
"Bastante. Peço 2.000 ouro pelos meus serviços.",
"Negócio. A vida do meu oficial é mais importante do que o brilho opaco do ouro.",
"Com preços assim, prefiro deixá-lo morrer!",
"E mais uma coisa. Seu oficial está delirando - ele disse que os ataques podem continuar. Sua recuperação levará duas semanas. Talvez você devesse colocar alguém para protegê-lo durante esse período?",
"Hm... Na verdade, esta não é a primeira tentativa de Artois. Eu mesmo vou protegê-lo.",
"Duas semanas?! De jeito nenhum, vou embora!",
"Sinto muito, capitão, mas não vou mais navegar com você. Você é muito sanguinário para mim. Até a próxima.",
"Desaparece, otário!",
"Estou farto de navegar com um verme covarde como você. Adeus, vou procurar alguém sanguinário o suficiente!",
"Como quiser!",
"O que você quer?",
"Quero que você se junte a mim em minhas jornadas.",
"Muito bem, mas tome cuidado para não repetir o que me fez te abandonar da última vez.",
"Bom.",
"Ouvi dizer que você está procurando emprego.",
"Algo parecido. E ouvi dizer que você está procurando um homem para guiar você e seu navio.",
"Você está certo. Acho que você é exatamente o homem que procuro. Você gostaria de navegar comigo?",
"Quanto dinheiro você vai me pagar?",
"Eu preciso que você me siga até a ilha ",
" e eu vou te pagar ",
" moedas de ouro.",
"Concordo.",
"Eu recuso sua proposta.",
"Obrigado, sinto que meu destino está em boas mãos. Aqui está o seu dinheiro.",
"Obrigado.",
", devo estar em um lugar com nome ",
", para o ",
"Obrigado, Comodoro, por nos preparar para abrir caminho. Teríamos passado por momentos difíceis sozinhos.",
"Comodoro! Ele desativou a corrente do leme, senhor!",
"Esse deve ser o melhor pirata que já vi.",
"Assim parece.",
"",
"Een dah-lah! Eeseepi tan daga!? Wa-diga kohn.",
"Kay-lay lam. Lam piki-piki. Lam eensy weensy. Estou dizendo-diga... eunuco. Recorte. [PENSA: Parece que eles acham que sou algum tipo de deus... Nada bom!]",
};
