string DLG_TEXT[71] = {
"O que você quer?",
"Você pode ver que esse sujeito não está resistindo. Não vou deixar você matar um homem desarmado. Largue sua espada.",
"Você está indo bem. Continuar.",
"Você viu o que aquele escravo tentou fazer comigo? Ele roubou minha arma e tentou usá-la para me matar, obrigado por intervir.",
"Sim. Não foi problema. (PENSA: acabei de matar um escravo, preciso me redimir de alguma forma!)",
"Você viu como Gombo tentou me matar? A escória pegou minha espada e começou a me cortar.\n Ele não vai mais machucar seus donos, vai? haha\nSou um bom oficial - você tem um lugar para mim em seu navio? Preciso ganhar algum dinheiro antes de poder voltar para a plantação de escravos.",
"Desculpe. Não interessado.",
"Veremos como você se sai em ação real. (PENSA: Talvez eu possa libertar esses escravos!)",
"Você não vai se arrepender! Agora a única coisa que resta discutir é meu salário. Eu não vou trabalhar de graça, você sabe",
"Quanto você quer?",
"3.000 ouro, e minha alma é sua.",
"Negócio. Bem-vindo à tripulação.",
"Hum. Você se avalia muito. Vou pensar sobre isso.... Mais tarde.",
"Posso me juntar à sua tripulação? Peço apenas 300 moedas.",
"Desculpe. A minha tripulação está cheia.",
"Claro. Aqui estão seus 300.",
"Quais são as suas ordens, senhor?",
"Estou ouvindo.",
"Só dando uma olhada ao redor.",
"Nada.",
"Capitão, é você?! Que bom que você veio! Acabei de fazer um acordo que nos tornará ricos!",
"Qual negócio?",
"Bom dia, capitão.",
"O que? Por que você saiu do navio?!",
"Bem, eu fiz uma aposta com os habitantes locais de 10.000 ouro que conseguiremos afundar o Harry Malvado.",
"O que você está falando? Você está nisso de novo?!",
"O que você quer dizer, boné? Tudo bem, o negócio do chocolate não foi tão legal, mas estamos falando de 10.000 aqui!",
"É isso. Estou farto dos seus esquemas malucos! Você está demitido!",
"Recuse esta aposta estúpida. Agora mesmo. E já estou farto da sua 'iniciativa'!",
"Conte-me mais sobre isso Harry.",
"É tudo muito fácil, capitão. Temos um mês para afundar o bastardo. Ele deveria estar em algum lugar perto daqui.",
"Eu disse - conte-me SOBRE HARRY!",
"Ah, vamos, capitão, não faça tanto barulho. Então, esse Harry não tem nada mais do que um pequeno navio... talvez uma corveta ou uma fragata, não tenho certeza.\nE o governador local ofereceu 3.000 de ouro por sua cabeça. Receberemos mais 10.000 se o afundarmos dentro de um mês.",
"Uma fragata ou uma corveta?! Nigel, você está completamente louco?! Para o inferno com esta aposta!",
"Hum. É arriscado... mas a recompensa vale a pena. Podemos levar isso, Harry.",
"Eu sabia que você acreditaria nisso, boné! Você vai ver! Você e eu faremos grandes coisas!",
"Meu Deus... Essa última parte da sua declaração é especialmente reconfortante...",
"Ah, é fácil. Entregamos este carregamento de chocolate em #sIsla Muelle# e receberemos 2.000 piastras!",
"O que?! Quem te deu o direito de fazer negócios em meu nome?",
"Relaxar. É um ótimo negócio. Eu mesmo fui capitão por um tempo, então sei negociar.",
"Essa foi sua última façanha. Você está demitido.",
"Tudo bem, você tem meia hora para cancelar o acordo e depois voltar para o navio. Está claro?!",
"Você tem sorte de eu não querer arriscar minha reputação cancelando esse acordo. Mas se você fizer isso de novo, você estará em sérios apuros.",
"Relaxe, boné. Não me olhe assim. Vou explicar tudo.",
"É melhor você fazer isso.",
"A questão é: aquele porco sujo cujo navio eu afundei? Ele me ferrou seriamente há alguns meses.\nEu não poderia simplesmente deixá-lo ir depois disso, poderia! Quer dizer, o rato me vendeu produtos estragados!",
"Oh, Deus, Nigel, quantos desastres mais você vai me trazer?! É isso, você está demitido!",
"Bem, acho que você fez a coisa certa.",
"Conseguimos, capitão! Isso vai mostrar-lhes...",
"Cale a boca, Nigel. Você está demitido!",
"Sim, sim, mas lembre-se, este foi o seu último truque! Entender? Se você fizer isso de novo, eu vou te esfolar vivo!",
"Como você diz, capitão",
"Tudo bem, volte para o navio.",
"Não temos nada para conversar",
"...",
"Você não deveria dizer isso, capitão. Estou apenas zelando pelos nossos melhores interesses...",
"Cale-se! Quantas toneladas de chocolate devemos transportar?",
"Apenas 100 toneladas, cap.",
"Hum. Tudo bem, temos espaço para isso. Agora volte para o navio!",
"Você está louco! Onde vou colocá-lo, na minha cabine?! Você tem meia hora para cancelar este acordo!",
"Você é um traficante de escravos? Se tem uma coisa que não suporto é tráfico de escravos! Prepare-se para morrer!",
"Senhor, esta é a ilha para onde estávamos indo quando você me encontrou em #sisland_Aruba#. Estávamos vindo buscar uma grande quantidade de ouro, era um dos nossos navios que encalhou.",
"E como faço para chegar a esse ouro?",
"Há um caminho que passa por uma cachoeira nos arredores da cidade, que passa por uma caverna até a costa onde está o navio.",
"Vamos então.",
"O tesouro está localizado na frente do navio.",
"Obrigado por me contar.",
"Com esse dinheiro tenho o suficiente para voltar para a Plantação.",
"Onde fica a plantação?",
"Navegue até a ilha #sisland_Eleuthera# e depois atraque em #sEleuthera#. A plantação está localizada fora da cidade.",
"Partiremos então para #sisland_Eleuthera#",
"",
};
