string DLG_TEXT[24] = {
"Já é tarde. É melhor eu encontrar um lugar para passar a noite",
"A taberna deve ficar do lado esquerdo, em um cais. #sTortuga# sempre tem alguns amigos bêbados que brigam entre si, mas eles não deveriam me incomodar.",
"É tudo uma estratégia para vender mais rum! Suponho que vou apenas me ocupar no salão da taverna, então.",
"É melhor eu encontrar um lugar. Vai ser uma longa noite.",
"Olá, amigo! Por que você não se junta a mim para uma xícara de rum e uma boa história de marinheiro?",
"Certamente, bom senhor. Parece que tenho muito tempo de sobra.",
"Ah sim. Tenho uma história realmente incrível para contar a você. Tudo começa com um jovem chamado Jack Sparrow.",
"Pardal, você diz? Ele não é aquele pirata famoso?",
"O mesmo! Mas ele nem sempre foi um pirata, sabe? Ele começou como cartógrafo, na Velha Inglaterra...",
"Mas o pai dele também era um pirata famoso, não era?",
"Sim, ele estava. Mas o jovem Sparrow não ligava muito para a profissão do pai. Ele queria ganhar a vida como uma pessoa honesta.",
"Uma pessoa honesta? Jack Sparrow? Mas ele é o espadachim mais malandro de que já ouvi falar!",
"Na verdade, foi isso que ele se tornou. Mas não foi assim nos primeiros tempos. Ele tinha um escritório tranquilo nas ruas de Southampton, mas a atração do mar revelou-se forte demais. Ele encomendou um navio e partiu em direção ao Novo Mundo.",
"Mas o destino tinha planos diferentes para ele. O jovem Jack acabou em uma história épica que repercutiria para todos que navegam pelos mares! Uma curva errada e quem sabia o que aconteceria a seguir?",
"É assim mesmo? Bem, isso é muito divertido, devo admitir, mas você precisa ser um pouco mais específico para ME impressionar!",
"Você está questionando minha história? Sua chegada ao porto de #sGrand Cayman# colocou em movimento coisas que ninguém teria acreditado se ele não tivesse visto com seus próprios olhos...",
"Agora, 10 anos depois, Jack foi finalmente abordado por Anamaria na taverna.",
"Espere! Capitão Jack Sparrow acaba de ganhar um novo navio, quais são as histórias deste navio?",
"Então nada aconteceu nos próximos 10 anos para Jack?",
"Muito bem, vou te contar. Você deve saber, no entanto, que o Capitão Jack perdeu o navio na próxima vez que navegou para o porto #sTortuga#. Ele então ficou preso em #sTortuga# fazendo uma tarefa estranha, até que um dia Anamaria veio até ele enquanto ele estava sentado no mesmo lugar em que você está agora...",
"É isso mesmo, embora Jack tivesse um navio novo, ele navegou de volta para #sTortuga# e foi roubado enquanto ele estava no porto. Então, mais uma vez, Jack se viu sem navio. Ele então ficou preso em #sTortuga# fazendo uma tarefa estranha, até que um dia Anamaria veio até ele enquanto ele estava sentado no mesmo lugar em que você está agora...",
"É isso mesmo, Jack estava sem navio então ele ficou preso em #sTortuga# fazendo alguma coisa estranha, até que um dia Anamaria veio até ele enquanto ele estava sentado no mesmo assento em que você está agora...",
"... Sim! Está ficando tarde Jack, vejo você por aí.",
"Obrigado pela conversa, Sr. Gibbs, como sempre.",
"",
};
