string DLG_TEXT[39] = {
"Obrigado novamente pelo que você fez ",
".",
"Não mencione isso.",
"Você está perdendo seu tempo, esse é Sri Sumbhajee Angria e ele não fala com ninguém. Se você está procurando companhia, fale com outra pessoa!",
"Como quiser.",
"Essa é uma maneira de cumprimentar um grande capitão do mar como eu?",
"O que você quer?!",
"Nada.",
"Vamos falar sobre seu irmão.",
"Ah, obrigado! Obrigado! Finalmente vi meu irmão! Sinto muito por não ter nada com que recompensá-lo, mas eu e Sri Sumbhajee estamos muito gratos por você nos ajudar...",
"(PENSA: Hmmmm. A arma de Sri Sumbhajee está sobre a mesa, talvez eu possa aceitar isso como pagamento)",
"...Meu irmão e eu temos sido ajudantes de Sri Sumbhajee há muito tempo e nós dois não sabemos o que faríamos sem Pusasn.",
"(Pega a arma durante o discurso) Não foi problema... Sério.",
"Realmente?! Um daqueles capitães do mar empertigados e adequados, então? Não temos negócios com sua espécie.",
"Fique à vontade então. Sou afetado, correto e orgulhoso de ser assim! Vocês dois deveriam ficar sentados sozinhos por um tempo.",
"Tem certeza de que está se referindo a mim? Já fui acusado de muitas coisas, mas ser afetado e correto não era uma delas!",
"Você não pode ser confiável. Nenhum de vocês! Ninguém que sirva lealmente suas respectivas nações sem levar em conta o que realmente importa.",
"Que tipo de conversa é essa? Você está me dizendo que não aprova aqueles que afirmam ser 'respeitáveis'?",
"Na verdade, não! Lidamos apenas com os Irmãos da Costa e mais ninguém.",
"Ainda bem que eu também sou um membro da Irmandade. Você pode confiar em mim tanto quanto em qualquer um deles.",
"Respeitável, de fato! Há muito poucos em quem podemos confiar e mesmo esses podem nos apunhalar pelas costas se tiverem oportunidade. Mas você não é um deles!",
"Isso está começando a parecer muito familiar. Você deve ser membro dos Irmãos da Costa! Estou pensando em me juntar a eles no assentamento pirata em #sisland_Quebradas Costillas#. Você pode ouvir de mim novamente.",
"Muito bem, então. Meu irmão gêmeo e outra ajuda de Sri Sumbhajee ",
"Ajuda Sumbhajee2",
", um homem modesto e confiante que apenas faz o seu trabalho...",
"Deixe-me adivinhar: isso tem algo a ver com os espanhóis?",
"Sim! Um tenente espanhol.",
"Bernardo Gamboa",
" Eles sequestraram meu irmão! Eu disse a ele que me opunha a que ele lidasse com ele, mas ele não me ouviu e há 3 dias ele desapareceu! \nTenho certeza que o Tenente Espanhol o levou! Ele lhes devia um dinheiro que Sri Sumbhajee não podia pagar.",
"Por que você não pede ajuda aos funcionários?",
"Recorrer aos funcionários? Oh, querido garoto, você está enganado. A cobra que levou meu irmão conta todos os funcionários entre seus amigos!",
"Eu vejo. Bem, espero que haja um final feliz para sua história.",
"Talvez eu possa ajudar. Onde posso encontrar esse rapaz?",
"Seu navio está no porto. Você não terá problemas em encontrá-lo.",
"Verei o que posso fazer.",
"Vá embora, eu já te contei tudo! Não me atormente com suas perguntas!",
"Muito bem, vá em frente, beba seu rum e espere que seu irmão volte para você.",
"Fácil fácil. Diga-me onde posso encontrar o homem que sequestrou o seu irmão.",
"Verei o que posso fazer. (PENSA: Talvez eu devesse vestir meu uniforme espanhol e ir para a prisão).",
"",
};
