string DLG_TEXT[101] = {
"Vamos continuar, capitão",
"Tudo bem.",
"Oh! Capitão ",
" Estou muito feliz em conhecê-lo. Espero ter te pegado a tempo!",
"Er.. Também tenho o prazer de conhecê-lo, mas, a tempo para quê?",
"Oh! Capitão, não podemos conversar aqui. Encontre-me na praia de Gray Rock Bay. Certifique-se de vir de navio.",
"Baía de Gray Rock? Onde é isso?",
"Por mais engenhoso que você seja, você descobrirá isso, capitão. Lembre-se, venha de navio.",
"De navio, Gray Rock Bay. O que é isso tudo?",
"Você vai ver. Preciso ir agora.",
"Agora, só um minuto, mocinha... se você acha que eu vou...",
"Você conseguiu então capitão ",
". Tive a sensação de que você poderia não vir",
"Bem, estou aqui, então você poderia ter a gentileza de me explicar o que está acontecendo e por que todo mundo continua desaparecendo?",
"É justo, capitão, mas aviso que fica complicado. Meu nome é Susan Shaypen e sou uma agente fiscal que trabalha para a Coroa.",
"Um agente fiscal! Agora isso é a primeira vez para mim. Então, qual é a sua história?",
"A senhorita Brin é na verdade a senhorita Brinkley. Ela sequestrou a verdadeira Srta. Brin e espera conseguir um grande resgate por ela, para ajudar em seus negócios.",
"Seu negócio? Eu teria pensado que o sequestro era um negócio suficiente por si só. Então, o que é esse negócio?",
"Contrabando de diamantes. Ela implora, rouba e pede diamantes emprestados, que depois envia aos piratas e eles os compram, obtendo um lucro considerável para a nossa senhorita Brinkley. Estou aqui para impedi-la, mas preciso da sua ajuda.",
"Contrabando de diamantes, hein? Uma linha de trabalho muito lucrativa. E por que você precisaria da minha ajuda?",
"Porque eu não tenho um navio no momento, e você tem.",
"Ah! Eu posso ver a lógica nisso.",
"Você vai me ajudar a levar a senhorita Brinkley à justiça e resgatar a senhorita Brin? É claro que haverá uma grande recompensa se tivermos sucesso.",
"Sim eu vou te ajudar. Nunca gostei de sequestradores. [PENSA: E eu gosto de recompensas, especialmente as grandes.]",
"Não, acho que não posso ajudá-lo agora. [PENSA: Se eu resgatá-la sozinho, não terei que dividir a recompensa, e ela disse que seria uma grande recompensa.]",
"Obrigado capitão, você não vai se arrepender. Precisamos navegar para #sTortuga#. É uma ilha pirata, por isso devemos mudar de bandeira quando estivermos fora da vista de terra.",
"Então para o mar é a Srta. Shaypen... er.. Não! Não quero dizer que você seja disforme.. er.. quero dizer.. er.. Srta. Susan Shaypen.",
"Relaxe capitão. Apenas me chame de Susan, é mais fácil",
"Sim, talvez fosse.",
"Isso é decepcionante, capitão, mas tenho certeza de que você tem seus motivos.",
"Er.. Sim, nada pessoal, você entende.",
"Oh! Na verdade, capitão, mas receio ter de comandar o seu navio. Você encontrará um Tartane que pode usar no porto.",
"O que? Huh? Espere um minuto, você não pode fazer isso! Você é um agente fiscal!",
"Digamos apenas que é o imposto devido sobre os diamantes que você tem no bolso. Nada pessoal, você entende.",
"Por que você.. **!**!!!***!",
"Bem, estamos aqui. A Taverna costuma ser o melhor lugar para fofocar, não acha?",
"Sim, mas preciso reabastecer a nave. Então não vamos esquecer disso.",
"Isso restringe um pouco a busca, eu acho. Parece que ela está indo para uma ilha pirata.",
"Sim. Mas qual ilha pirata?",
"Então capitão ",
", você decidiu não vir me encontrar em Gray Rock.",
"Eu tinha um compromisso anterior, do qual tenho certeza que você conhece.",
"Oh! Sim, capitão, estou muito ciente. Consciente também de que você se tornou pirata. E você, como pirata, só pode ter um motivo: dinheiro fácil. Uma escolha muito infeliz.",
"Aquela senhorita... seja qual for o seu nome, foi minha escolha. É o meu motivo que deveria ser mais preocupante para você.",
"Meu nome é Susan Shaypen e sou uma agente fiscal que trabalha para a Coroa. MEU motivo é acabar com a pirataria. E isso... faz de você meu inimigo!",
"Um agente fiscal! Essa nunca seria minha escolha de trabalho! Mas suponho que alguém tem que fazer isso",
"Chega dessa petulância, capitão. Entregue sua espada, você está preso!",
"Você SABE que está em uma ilha pirata, senhorita Shaypen? Você não tem autoridade aqui e tenho certeza de que não há recursos aos quais recorrer.",
"Eu tenho a autoridade da minha espada e sou capaz de lidar com você sozinho. Renda-se agora, Capitão, ou morra!",
"Como quiser, mas você pode acabar muito disforme. Senhorita Shaypen. Desembainhe sua espada.",
", nos encontramos novamente. Você obviamente é muito engenhoso por ter me encontrado aqui.",
"É assim que pode ser. Mas temos que resolver primeiro a questão de você roubar meu navio.",
"Comandante, Capitão, eu comandei seu navio. Sou um Agente Fiscal que trabalha para a Coroa e, como tal, os negócios da Coroa prevalecem sobre os do indivíduo.",
"Este indivíduo não, não. Estarei... reordenando meus navios imediatamente.",
"Capitão! Reitero, estou trabalhando para a Coroa e preciso do seu navio. Tomarei todas as medidas necessárias, e recursos à minha disposição, para mantê-lo. Vou até prendê-lo se continuar a interferir no meu trabalho aqui.",
"Um agente fiscal! ... Bem, não acredito que vou dizer isso, mas parece que estamos do mesmo lado. Estou trabalhando para a Companhia das Índias Orientais. Aqui estão meus papéis.",
"Bem, bem, capitão. Você me surpreende mais uma vez. Então você está preparado para trabalhar comigo agora para resgatar a senhorita Brin?",
"Acho que poderíamos tirar alguma vantagem disso. [PENSA: E há uma recompensa.]",
"Então, o que você sugere que façamos a seguir?",
"Devíamos ir à Taverna. Se houver alguma informação circulando, nós a encontraremos lá.",
"Quem é 'o Grande Homem'?",
"Esse é o líder pirata desta ilha. Precisamos ir vê-lo. Pelo menos sabemos que há alguém lá em cima naquela sala.",
"O QUE! ...",
"As necessidades devem, receio. --- [Você dá a Susan uma piscadela de conhecimento sem ser vista por Skull. --- Ela dá um aceno imperceptível de que entende.]",
"O que você está jogando? Dois navios? Como isso vai ajudar?",
"Simples, minha querida Susan. Quando sairmos para o mar, navegaremos para Bridgetown, não para a Jamaica. Você navega em frente, uma vez lá, você pousará primeiro e entregará a Srta. Brinkley ao Comandante da Prisão. Aí você vende seu navio, que era meu, se você se lembra, me dá o dinheiro, e nos separamos. Devolvo as irmãs Brin ao pai em #sRedmond#.",
"Oh! E você também recebeu o dinheiro do resgate, suponho?",
"Confie em mim, minha querida, confie em mim! Desta forma, a sua profissão como Agente Fiscal permanece em segredo, para que possa continuar os seus 'bons trabalhos' nas ilhas. As meninas chegam em segurança em casa e posso continuar com meus próprios assuntos. Todo mundo ganha!",
"Eu vejo. Bem, isso pode funcionar, mas você ainda não mencionou o dinheiro do resgate, Skull não estará procurando por isso?",
"Não vou pedir resgate. Digamos.. Contarei com a..generosidade do Governador. Skull ficará feliz em ser deixado sozinho para cuidar de seus próprios negócios. Shh! Ele está voltando.",
"Miss Brinkley está sob custódia na prisão. Ela não estava feliz. Aqui está o dinheiro para o seu navio, menos o imposto devido à coroa, é claro. Suponho que isso conclui nosso negócio por enquanto?",
"AH! Um bom dia de trabalho, não acha? Podemos nos encontrar novamente, nunca se sabe. Mas, por enquanto, devo entregar minhas acusações ao pai deles.",
"Não pense que porque você nos tirou de lá eu devo alguma coisa a você! Eu lembro o que você fez comigo!",
"Calma mulher! Você não sabe, mas acabei de salvar sua vida!",
"O que você está falando! Pelo que ouvi, algum ouro mudou de mãos, só isso!",
"Minha querida senhorita Shaypen... Disseram-me que havia apenas uma irmã aqui, e a 'outra' irmã me disse isso! Alguém está tentando me matar e, por associação, você também, esclarecido?",
"Oh! Você quer dizer a Srta. Brinkley e o Sr. Brock? Eu sabia sobre eles há algum tempo. É por isso que eu queria que você me encontrasse em Gray Rock Bay.",
"Você fez! Hmmm! Preciso levar a filha do Governador para casa. Então farei uma visita a eles. Agora, precisamos zarpar o mais rápido possível. Sugiro que nos separemos assim que estivermos no mar.",
"Muito bem, voltarei a Barbados e verei o que posso descobrir.",
"Bom. Irei primeiro para a Jamaica e depois alcançarei você. Agora vamos indo.",
"Espero que Bootstrap saiba o que está fazendo. Tenho quase certeza de que vi aquele homem saindo da cabana.",
"Tenho certeza que sim, e de qualquer forma, precisamos encontrar Billy Brock, então vamos em frente",
"Acho que deveríamos nos separar novamente, capitão. Brock não sabe quem eu sou, mas ele conhece você, então terei mais chances de encontrá-lo sozinho.",
"Boa ideia. Vou dar uma olhada de qualquer maneira. Encontro você no estaleiro mais tarde",
"Conheci o Governador Brin na cidade e vi você entrar aqui, então sugeri ao Governador que o seguissemos.",
"Isso funcionou perfeitamente. Eu matei Brock e as filhas parecem estar bem.",
"Isso funcionou bem para nós dois. Devo me juntar ao Governador quando ele retornar para #sisland_Redmond#.",
"Oh! Então nos separamos? De uma forma engraçada, gostei bastante de trabalhar para a coroa.",
"Sim! certo! De alguma forma, acho que você tem um pouco de pirata em você. De qualquer forma, aqui estão algumas coisas que encontrei no corpo de Brock. Você pode muito bem ficar com eles, pois sendo um agente da coroa, não posso ficar com eles.",
"Obrigado. Boa sorte com sua promoção. Você nunca sabe que poderemos nos encontrar novamente",
"Alguma sorte, capitão?",
"Ainda não. Estou me perguntando se deveríamos atravessar a ilha até #sGreenford#.",
"Bem, se ajudar, um marinheiro me disse que um navio partiu para a ilha #sisland_Turks# ontem à noite, com algumas passageiras.",
"Hmmm... #sisland_Turks# Ilha. Essa é uma ilha pirata, então faz sentido. Talvez devêssemos ir para lá.",
"O que você está fazendo, capitão? Isso não é #sTortuga#! Precisamos sair daqui rápido e voltar para #sTortuga#!",
"Oh céus! Não foi um dos meus melhores dias, admito. Você está certo, deveríamos ir embora.",
"[PENSA: Vejo alguma vantagem aqui...] Muito nobre, muito nobre mesmo. Talvez devêssemos unir forças, afinal.",
"Olá novamente capitão. Acredito que você entregou suas cobranças sem problemas?",
"Sim, obrigado Susan... e como você se saiu com Brock e Brinkley?",
"Brinkley está na prisão. Brock, infelizmente, morreu quando tentamos prendê-lo. O que me lembra, aqui estão alguns itens que tirei do corpo de Brock, que você pode achar úteis. Fui chamado de volta para #sisland_Redmond#, então vou deixá-los agora.",
"Então é um adeus, pelo menos por enquanto. Talvez nos encontremos novamente. Nunca se sabe.",
};
