string DLG_TEXT[47] = {
"A vergonha! Que pena, Jackie!",
"Er, mas...",
"E quanto à senhora apanhada no meio disto tudo... Ela não conta tudo o que sabe. Palavras me falham.",
"Sua mãe está perturbada! Adequado para ser amarrado. Oh, que vergonhoso!",
"Mas não fui eu! O que quer que fosse. ",
"Pronto para ser amarrado, eu te digo! Ela já pegou um navio para Deus sabe onde, só para sair daqui.",
"Jackie, meu garoto, você não está preso. Foi um estratagema para trazer você aqui porque preciso da sua ajuda. Alguém agitou as águas deste arquipélago. Essa é a vergonha, Jackie! A vida era doce... Piratávamos aqui e ali, mas o Código e a Irmandade é o que nos mantinha unidos.",
"Mas eu não fiz nada de errado! Na verdade, ainda não fiz nada... Ouça, acabei de atracar aqui. Os guardas me prenderam sabe Deus por quê e me levaram até este lugar onde encontrei meu pai. Um pai, devo acrescentar, que não vejo desde que era menino. Por que estou aqui?",
"Quero dizer, que coisas que deveriam ter sido deixadas em paz, não foram. Quero dizer, aquele tesouro que deveria ter sido deixado sozinho, não foi. Quero dizer que as pessoas que deveriam ter ficado longe daqui, não o fizeram. Quero dizer...",
"O que você quer dizer?",
"Não, Jackie. Chamei você aqui para me despedir",
"Eu entendo sua ideia. Muitas pessoas têm feito o que não deveriam. Então é por isso que você me ligou aqui?",
"Oh! Adeus então.",
"Ainda não!",
"Oh!",
"Parece-me que o destino trabalhou para nos colocar aqui, Jackie. Já faz muito tempo que não nos vemos. ",
"Sim. Desde que saí de casa, há dez anos, pelo que me lembro",
"Isso seja feito! Nosso encontro aqui, agora, nesta ilha foi determinado pelo destino, ou por poderes maiores do que conhecemos.",
"Ou, então, novamente, por pura coincidência.",
"Há muita coisa acontecendo nessas águas e posso ver problemas surgindo. A vida de pirata não será a mesma.",
"Bem, eu não sou um pirata, pai. Então isso não me incomoda.",
"Isso é outra vergonha, Jackie. Você me decepcionou aí... Você teria tido uma carreira tão boa se tivesse ficado comigo.",
"Bem, eu não fiz. Tenho meu próprio navio e pretendo fazer fortuna, do meu jeito.",
"Vou direto ao assunto, então. Jackie, preciso da sua ajuda. Preciso que você pare o que está acontecendo. Você pode, mas terá que fazer isso sozinho, sem mim. Você não me verá novamente por muito tempo, filho. Eu tenho o Código para me preocupar.",
"Por mim mesmo? O código? Qual código e fazer o quê, exatamente? Você não está fazendo nenhum sentido, pai. Diga-me!",
"Desculpe, Jackie. Não posso. Estou sem tempo e preciso voltar para Shipwreck Cove. Mateus irá ajudá-lo. Adeus, meu menino.",
"Jackie, meu garoto. Isso é você? Oh meu Deus, você foi e fez isso, não foi?",
"Eu me sinto bem. Mas todo mundo reage assim quando me vê. Os homens com quem eu estava navegando foram buscar um médico em #sisland_Cayman#. Mas adivinhe? Encontrei o tesouro de Cortez! Então, apesar de tudo, boas notícias!",
"Um médico não vai te ajudar, Jackie, e encontrar esse tesouro não foi tudo que você fez, não é?",
"Você pegou o tesouro, não foi Jackie?",
"Apenas algumas moedas. E por que um médico não me ajuda?",
"Porque o tesouro está amaldiçoado e é isso que está te deixando doente, por assim dizer. Você não acha que teríamos aceitado se não houvesse algo terrivelmente errado com isso?",
"Mas eu te disse que não me sinto mal. Na verdade, tive uma briga com alguns piratas rebeldes no caminho para cá. Eu me cortei muito, mas não senti nada.",
"Essa é a maldição, Jackie. Você pegou o tesouro e até que ele seja devolvido, você não pode morrer. Você está amaldiçoado a andar pela terra para sempre!",
"Amaldiçoado, você diz? Isso pode ser terrível... Ou talvez não... Mas para sempre é muito tempo... Eu deveria me livrar disso. O que devo fazer então?",
"O que eu disse. Coloque as moedas que você pegou de volta onde as encontrou. Corte seu dedo, limpe primeiro o sangue neles, e quando você os colocar de volta você será mortal.",
"Tudo bem, eu farei isso. A propósito, o que você está fazendo aqui? Pensei que você morasse em Shipwreck Cove.",
"Eu faço. Estou tendo um grande problema com um dos membros da Irmandade, então vim aqui para pensar.",
"Você não vai me dizer quem, né? Muito bem, vou devolver essas moedas. Então preciso encontrar os outros em #sisland_Cayman#. Vejo você de novo, sem dúvida!",
"Fique seguro Jackie.",
"Vou tentar. Você também.",
"Bem, bem, garoto Jackie! Parece que você está fazendo seu nome: vestindo-se como clérigo e tenente britânico? Resgatando donzelas em perigo? Muito pirata da sua parte, Jackie.",
"Suponho que você poderia dizer que estou totalmente na conta agora e gostando muito.",
"Sim, eu posso dizer! Jackie, estou realmente orgulhoso de você. Agora, pegue isso. É muito importante para mim e agora é para você. Mantenha-o sempre com você. É o símbolo que marca você como um Senhor Pirata do Caribe.",
"Meu? Estou honrado! Confuso, mas honrado.",
"Deixe-o entender. Eu comemoraria com você, mas devo zarpar para Shipwreck Cove agora. Verei você novamente, algum dia. Adeus, Jackie.",
"Adeus, pai.",
"",
};
