string DLG_TEXT[92] = {
"Normalmente, eu deveria perguntar quem é você, capitão ",
", mas, como você vê, já estou ciente disso.",
"Muito impressionante, senhora. Eu saúdo você. E não vou perguntar como você sabe, tenho a sensação de que essa é uma das perguntas que um sábio não faria. [PENSA: Especialmente porque me lembro de ter visto você com meu pai, e suspeito que você também se lembra de ter me visto.]",
"Agora é minha vez de ficar impressionado, Capitão ",
". Você não entende que a sabedoria é o começo de todo o conhecimento.",
"Obrigada Senhora. Eu ficaria feliz em saber seu nome. [PENSA: É melhor não deixar ela saber que eu já sei disso.] ",
"Meu nome é Tia Dalma e agora seremos apresentados. Então, o que o traz aqui, capitão?",
"Se você soubesse meu nome Tia Dalma, tenho certeza que sabe por que estou aqui.",
"Ah, sim, capitão. Eu sei por que você está aqui, e também sei que você não sabe.",
"O que! Claro que eu faço! Estou aqui para pegar uma carga.",
"É mesmo, Capitão... e qual seria essa carga?",
"AH! agora você me pegou. Admito que não sei qual é realmente a carga. Acabei de receber ordem de buscá-lo.",
"Por favor, capitão, a carga seja 'dem' e não 'isso'. Você veio buscar escravos.",
"ESCRAVOS! NãO! Eu não sou um traficante de escravos. Nunca!",
"Eu conheço esse capitão, é por isso que estou falando com você.",
"Partirei imediatamente. Não quero nada com o comércio de escravos.",
"Não capitão. Você deve libertar os escravos.",
"Como faço isso?",
"Matando os três guardas perto da praia. Eles estão bloqueando meu caminho para a prisão onde os escravos são mantidos,... e a propósito, sua tripulação pode não ajudá-lo.",
"Por que tenho a sensação de que você poderia fazer isso sozinho e que não precisa da minha ajuda?",
"Wiesdom levanta a cabeça novamente, capitão. Você está certo, não preciso de sua ajuda, mas preciso que você prove seus erros por meio de ações.",
"Por que é que?",
"Faça a ação, capitão, depois volte para mim aqui e eu lhe darei a resposta.",
"Estou me metendo em algo profundo aqui, eu sei, mas não gosto da ideia de escravos, então retornarei em breve.",
"Tenha sucesso, capitão.",
"Sim, eu consegui...",
"Isso foi uma declaração, não uma pergunta, capitão. ",
", você confirmou seu caráter para mim e provou seu valor, então agora tenho algo especial que você deve comprar de mim, e também lhe darei roupas novas para se adequar à sua nova situação.",
"Eu mato três homens e você quer me vender alguma coisa?",
"Não, capitão, esta não é uma venda comum. Dê-me 500 em ouro para que eu possa subornar o jailah e conseguir passagem para os escravos daqui para um lugar seguro, e você receberá essa bússola e as roupas novas.",
"Um compasso! Eu já tenho uma bússola.",
"Não uma bússola como esta. Essa bússola levará alguém ao que seu coração mais deseja. Siga-o com cuidado.",
"Você quer dizer como o Baú de Cortez?",
"Se isso é o que você mais deseja, então sim.",
"Hmmm. Parece que você sabe algo diferente. ",
"Eu sei, capitão, que você não pode retornar ao seu emprego.",
"Ah! Sim. Isso será um problema. Bem, eu tenho outro lugar para ir.",
"Sim capitão, de volta ao farol em #sisland_Oxbay#.",
"Você sabe disso também? Tudo bem, vamos negociar, aqui está meu ouro.",
"E aqui estão a bússola e as roupas novas. Você pode ser muito complexo, capitão, mas você deveria ir agora. Os guardas de Othah estão chegando.",
"Sim, eu deveria, mas e você? [PENSA: UAU! Como ela fez isso?]",
"Não se preocupe comigo, capitão. Eu desapareço antes que eles cheguem. Até nos encontrarmos novamente.",
"Você quer dizer 'se' nos encontrarmos de novo... Na verdade, não, você não, você já sabe que VAMOS nos encontrar, não é?",
"Não uma bússola como esta. Você deve devolvê-lo ao seu funcionário assim que puder.",
"Não posso voltar para Beckett, não depois disso.",
"Sim, mas Beckett não é seu empregado agora, é? Você está trabalhando para 'de Brot'erhwood.",
"Você também sabe disso? Aqui, pegue o dinheiro e me dê a bússola. Você me assusta, você sabe.",
"Você falhou miseravelmente, capitão. Você deve retornar de mãos vazias, estou com medo.",
"Não posso fazer isso, esta é minha primeira missão, ele não vai me empregar e vou perder tudo.",
"Vejo seu dilema, capitão, e eu poderia ajudá-lo, mas isso terá um preço terrível.",
"Eu não me importo, custe o que custar, eu também concordarei.",
"Isso parece ameaçador. Talvez eu volte e enfrente a música, afinal. Adeus.",
"Muito bem Capitão, aqui está a bússola e as roupas que você precisa.",
"Não como aquele que você não gosta. E você concordou com meus termos, então o negócio está feito. Vou precisar de todo o seu dinheiro, capitão.",
"Bem, isso é duro, mas eu não diria que é assustador.",
"O ouro é apenas parte da transação. Você perceberá o resto latah'. Adeus capitão.",
"Ah! isso parece um pouco assustador. Vou embora enquanto posso. Adeus.",
"Deixe esse homem em paz, Davy Jones, leve-me no lugar dele. Eu te imploro!",
"...",
"O que você quer, capitão?",
"Nada no momento.",
"Davy Jones... Deixe esse homem em paz, não é hora dele ir até Lockah'!",
"...",
"Davy Jones estará atrás de você novamente em breve. Se você me levar para um local seguro em #sisland_Antigua#, eu tentarei ajudá-lo.",
"Obrigado. Vamos para #sisland_Antigua# então.",
"Siga-me até a selva Jack, eu o levarei até lá!",
"É justo..lidere então! [PENSA: Espero que não encontremos nenhum animal selvagem ou qualquer outra coisa..]",
"Aqui está, eu em casa, depois de você capitão",
"Parece... adorável, Tia Dalma.",
"Agora temos um pouco de tempo para conversar Capitão! Mas é preciso se apressar, Davy Jones está relutante, sua alma vey está em grande perigo... e pague caro por trazer sua Pearl de volta!.",
"Passar meus dias no armário de Jones não estava em meus planos... existe uma maneira de escapar dele antes que meu tempo acabe?",
"Ah, sim, aí está meu querido capitão, é preciso encontrar um baú onde esteja o coração de Davy Jones, é preciso então perfurar esse coração e se tornar o capitão.",
"Ah, estar no comando do holandês parece que seria adequado para mim. Onde encontro essa... coisa de peito?",
"Oh, não tão rápido, primeiro navegue para #sisland_Turks#, demônio um homem chamado Atwood Paddley, ele terá o que você quer! Nos encontraremos novamente, Capitão...mais do que você pensa.",
"Vou então, obrigado pela ajuda Tia Dalma...",
"Jack Sparrow! Eu sempre soube que o vento iria te levar de volta para mim em breve",
"Tia Dalma! Na verdade, minha aventura em #sisland_Turks# não rendeu nada de útil.",
"Você. Você tem um toque de... destino, William Turner.",
"Você quer me conhecer.",
"Não haverá como saber aqui. Viemos em busca de ajuda e não vamos embora sem ela. Estamos procurando por isso. E para que serve. [Mostra o pano com a impressão da chave.]",
"A bússola que você ganhou de mim. Não pode levar você a isso",
"Talvez. Por que?",
"Ayeee...Jack Sparrow não sabe o que quer! Ou... você sabe, mas detesta reivindicá-lo como seu. Sua chave vai para um baú, e é o que está dentro do baú que você procura.",
"...",
"Você conhece... Davy Jones, certo? Um homem do mar. Um grande marinheiro, até entrar em conflito com aquilo que irrita todos os homens.",
"A mesma história, versões diferentes e todas verdadeiras. Veja, era uma *mulher*, tão mutável, dura e indomável quanto o mar. Ele nunca deixou de amá-la. Mas a dor que isso lhe causou foi demais para viver com ela. Mas não o suficiente para fazê-lo morrer.",
"O que... exatamente ele colocou no baú?",
"Ele coração.",
"Não valia a pena sentir o que... a pequena alegria fugaz que a vida traz, e então... ele esculpiu seu coração, trancou-o em um baú e escondeu o baú do mundo. De chaves, ele fica com ele o tempo todo.",
"Davy Jones não consegue chegar ao porto. Não pode pisar em terra senão uma vez a cada dez anos. A terra é onde você está seguro, Jack Sparrow.",
"Um toque... do destino lhe dará a localização!",
};
