string DLG_TEXT[43] = {
"Não sejamos muito precipitados, Comodoro, afinal o homem salvou minha filha.",
"Sim senhor, um ponto importante. Salvar vidas é um ato nobre.",
"Sim, sim, não devemos ser tão precipitados. Coloque-o na prisão enquanto levo minha filha para a residência para que ela se recupere e troque de roupa. Podemos sempre enforcá-lo amanhã.",
"Não era bem o que eu tinha em mente! ... Acho que é hora de estar em outro lugar! Lembre-se disso como o dia em que você quase pegou o Capitão ",
"Ah! Então este é o famoso Capitão ",
". Acredite ou não, estávamos falando de você",
"Na verdade, sua excelência? Dada a empresa atual, duvido que tenha sido uma boa conversa.",
"Não é assim, capitão. Apesar de todas as suas falhas, você tem exatamente as habilidades das quais precisamos desesperadamente neste momento.",
"Como assim, senhor?",
"A situação na Europa piorou gravemente. Os franceses reuniram uma grande frota e há informações de que estão planejando assumir o controle dessas ilhas.",
"Na verdade, senhor, isso é perturbador, mas por que isso me envolveria?",
"Eles pretendem se aliar aos piratas para aumentar a pressão sobre nós, e com sua história passada, se você estiver disposto, poderá nos ajudar a frustrar esses esforços.",
"Em relação à minha história, sinto que fui muito mal compreendido e gostaria de ter alguma garantia de que meu histórico será eliminado.",
"De minha parte, seu histórico é claro e permitirei que Sir Cutler Beckett fale por si mesmo.",
"Sou todo ouvidos, Senhor.",
"Fique quieto, capitão Norrington. Deixe o homem terminar o que tem a dizer. Prossiga, ",
"Obrigado, Senhor. Como disse o capitão Norrington, você não pode confiar em piratas, MAS, pode-se confiar neles para confiar uns nos outros e, como pirata, posso comandar essa confiança.",
"Na verdade, capitão ",
". E como, por favor, diga, isso seria benéfico para nós?",
"Os franceses não são estúpidos. Eles também acreditam que os piratas não são confiáveis. Eles compraram uma aliança temporária para lhes permitir reabastecer os seus navios, só isso. E por uma grande soma de dinheiro, estarei vinculado. Mas conhecendo os franceses, esse dinheiro não será pago até que os suprimentos sejam carregados.",
"Isso é lógico. Mas e daí? Ainda não ajuda a nossa causa e a defesa destas ilhas.",
"Bem, meu Senhor, tudo o que temos a fazer é mostrar aos piratas que eles não serão pagos e que eles se voltarão contra os franceses, e sabemos que os franceses se voltarão contra os piratas assim que tiverem o que precisam.",
"Vá em frente, capitão, isso está começando a mostrar algum mérito.",
"Se eu contar aos piratas o que os franceses estão tramando, então os piratas atacarão a frota francesa por nós, deixando a esquadra de Norrington livre para subjugar as outras ilhas francesas.",
"[Para Will] Em nosso retorno a Port Royal, concedi-lhe clemência. E é assim que você me agradece? Jogando sua sorte com ele? Ele é um pirata!",
"[Will] E um bom homem. Se tudo o que consegui aqui foi que o carrasco ganhe dois pares de botas em vez de um, que assim seja. Pelo menos a minha consciência estará limpa.",
"Elizabeth... Elizabeth... espere!",
"Você perdeu o companheiro dela. Cupido fez o seu trabalho.",
"E como você executaria esse estratagema para ter certeza de seu sucesso?",
"Meu plano seria este, senhor. Vou navegar para a ilha #sisland_Turks# e espalhar a notícia de que conheci a frota francesa e eles me deram o dinheiro para pagar aos ingleses, para que possam reabastecer seus navios nos portos ingleses.",
"O QUE! Mas, o que isso alcançaria?",
"Ao entregar o dinheiro, como prova, você entende, eu poderia fazê-los acreditar que os franceses estão de fato vindo para assumir o controle de suas ilhas, e não as inglesas, E se o capitão Norrington pudesse me acompanhar como meu primeiro oficial, isso seria de fato adicionar ainda mais credibilidade à missão.",
"Silêncio Norrington! Este plano realmente tem mérito. Quanto dinheiro precisaríamos para este empreendimento, capitão?",
"Eu sugeriria 300.000 em ouro, meu Senhor. Você economizará mais do que isso por não ter que colocar os navios de Norrington no mar, além de manter sua frota intacta para assuntos mais urgentes.",
"Um plano ousado ",
". Muito bem, mandarei entregar os 300.000 em seu navio. Quando você pode navegar?",
"Ah! há um outro pequeno assunto.",
"E isso é?",
"Não tenho neste momento um navio que seja adequado para a viagem, nem que transmita a minha estatura como capaz de representar os ingleses.",
"Hmmm! Muito bem. Capitão Norrington, forneça ao bom capitão uma fragata e acho que você realmente deveria navegar com ele como seu primeiro oficial. Apenas para proteger nosso investimento, você entende. E Sir Cutler, talvez você tenha a gentileza de fornecer escolta no Interceptor até que eles saiam de nossas águas e tenham que içar a bandeira pirata.",
"Err... Obrigado, Senhor, partiremos assim que possível.",
"41",
"42",
"",
};
