string DLG_TEXT[73] = {
"Olá, ",
". Posso perguntar quem você é e o que diabos está fazendo no meu quarto?",
". Estou aqui para te ver.",
". Realmente? Eu nunca teria adivinhado. Então o que você quer, ",
"?",
"Eu sei que você foi contratado para escoltar o barco 'Oiseau'.",
"Talvez... bah! Não vou esconder isso. Estou com pouco dinheiro, por isso concordei em navegar até #sOxbay# e voltar pela bagatela que o mesquinho francês me ofereceu.",
"E se eu pedisse para você me dar a honra de fazer isso?",
"Se você quer esse emprego, deve estar em situação ainda pior do que a minha. Mas por que diabos eu deveria deixar você ficar com isso?",
"Porque se você recusar, eu te mato",
"Pagarei mais a você do que aos franceses. Isso não deve ser difícil.",
"Nós dois sabemos que você realmente não quer navegar para nenhum lugar perigoso.",
"Mil demônios! Vamos ver se você é tão bom quanto pensa!",
"Eu vou te mostrar, canalha!",
"Estou brincando. Pagar-te-ei mais do que aos franceses.",
"Me pague? Afinal, você tem um pouco de ouro, hein? Então, por que você quer o emprego?",
"Não importa... temos um acordo?",
"Isso é verdade, mas eu realmente preciso desse ouro, então que escolha eu tenho?",
"Se o pagamento for tão insignificante como você diz, talvez seja sensato esperar por uma oferta melhor?",
"Eu não sei... Bem, tudo bem, mas vai te custar 3.000 ouro!",
"Olha Você aqui. 3.000 ouro exatamente.",
"3.000 ouro? Você deve estar brincando.",
"Eu não tenho muito comigo.",
"Você sabe algo? Você tem razão. Para o inferno com todos esses soldados e suas guerras coloniais! Algo melhor surgirá antes que eu morra de fome.",
"Então deixe-me fazer esse trabalho para você.",
"Eu tenho um se você estiver interessado.",
"Não, obrigado, ",
". Quem sabe quando conseguirei um emprego novamente? Sou um péssimo comerciante e não pretendo me tornar pirata...",
"Então eu vou ter que te matar",
"Pagar-te-ei mais do que aos franceses.",
"Excelente! Alguém lá em cima me ama de verdade!",
"Certo. Acalme-se, e vamos direto ao ponto.",
"Infelizmente então ",
", não posso te ajudar.",
"Então eu vou ter que te matar",
"Você e eu sabemos que você não quer navegar para nenhum lugar perigoso.",
"Tudo bem, temos um acordo. Aqui está uma nota do Governador ao chefe do porto. Mostre a ele e ele lhe apresentará ",
"Virgile Boon",
"...",
"Virgile Boon",
", capitão do 'Oiseau'.",
"Onde posso encontrar o capitão do porto?",
"Onde posso encontrar o capitão do 'Oiseau'?",
"Obrigado. Adeus.",
"Ele geralmente está no porto supervisionando o carregamento das mercadorias. Você precisará da permissão dele antes de sair.",
"Obrigado, ",
".",
"Ele estará no porto, é claro, preparando o navio para a partida.",
"Obrigado, ",
".",
"Interessante. Qual é a sua oferta?",
"Não quero que o 'Oiseau' chegue a #sOxbay#.",
"Você quer que eu afunde?",
"Ou capture-o, se quiser; isso não me preocupa.",
"Vida de pirata, né? Isso pode servir para mim... E começarei minha carreira de pilhagem com você. \nVou aceitar 10.000 de ouro por este trabalho. Antecipadamente.",
"Sim, você será um pirata, com certeza. Aqui está o seu dinheiro.",
"Maldito, ",
"! Isso é muito ouro para o meu sangue!",
"Eu não tenho tanto dinheiro.",
"Mil demônios! Este é realmente um dia de sorte! Obrigado, ",
"!",
"Uma coisa: traia-me e você desejará que nunca nos tivéssemos conhecido.",
"Você pode confiar em mim, amigo! EU, ",
", juro que ",
"Virgile Boon",
" será comida de peixe em breve!",
"Boa chance, então. Boa sorte para você, ",
".",
"Algo mais, ",
"?",
"Lembre-se: nunca falamos sobre esse acordo.",
"Mas claro, claro! Eu não sou bobo, *slad*!",
"É bom saber. Te vejo em breve.",

};
