string DLG_TEXT[46] = {
"Se perder!",
"...",
"Olá, #slad#! Você parece um verdadeiro lobo do mar. Você gostaria de se juntar à minha tripulação?",
"Em que termos?",
"Isso foi uma performance! Você é melhor do que eu esperava. Você pode valer alguma coisa para mim.",
"Você acredita que sou capitão agora?",
"Admirando o mar, não é? Eu nunca me canso disso.",
"Desde que zarpamos o nosso rumo é ENE, direto para #sisland_Oxbay#. Enquanto isso, para chegar a #sisland_Isla Muelle# devemos ir para N. Parece que você decidiu quebrar nosso acordo, meu velho.",
"Bom palpite. Você pode ser mais inteligente do que parece. Dê-me sua espada e pistola, e nós o levaremos em segurança até as minas #sisland_Oxbay#.",
"Você poderia? E o que sua tripulação pensará disso? ",
"O que me importa o que eles pensam?",
"Talvez você não. Mas não posso deixar de pensar que os seus homens podem não gostar de trabalhar para um cão mentiroso como você. Talvez seja por isso que você teve tanta dificuldade em encontrar marinheiros para sua tripulação.",
"Fale o quanto quiser. Isso não lhe servirá de nada.",
"Talvez você esteja certo. Talvez eu devesse falar com seus homens. O que vocês acham, senhores? Você está feliz com o Captain Small-Time, aqui, ou está pronto para grandes pontuações?",
"Isso é conversa fiada para uma #sperson# condenada. Você realmente espera que alguém caia nessa?",
"Olhe para trás, capitão, e pergunte-me isso de novo.",
"Eu não preciso olhar. Escolhi minha tripulação com muito cuidado. O fato é que a maioria deles nem fala inglês.",
"Escória pirata!",
"O que? Não dêem ouvidos ao #spronoun#, seus idiotas! Eu sou seu capitão!",
"Eles parecem ter outras ideias. Eles podem simplesmente matar você - se eu não chegar antes deles!",
"Preciso de alguns marinheiros com quem possa contar. O pagamento é de 10 ouros agora e mais 200 após o ataque. O que você acha?",
"Nesse preço, não penso muito. Faça de mim um capitão e posso pensar novamente.",
"Se você quiser viver, me diga onde está seu navio e diga à sua tripulação que estou no comando agora.",
"Tenho uma oferta que acho que você vai gostar ainda mais: leve-me para #sIsla Muelle# e pagarei assim que chegarmos.",
"Isso não deveria ser um problema. Em geral, tenho boas relações com os espanhóis.",
"Então é um acordo! Vamos zarpar?",
"Você tem coragem, capitão, e ainda por cima tem bom gosto. Mas, não, ninguém comanda meu navio além de mim.",
"Me desculpe se não fui claro, mas isso não foi um pedido. Se você não desistir, terei que tomá-lo à força.",
"Nem quando aparece alguém que consegue fazer o trabalho muito melhor que você? ",
"Melhor que eu? Olha, #schild#, você pode ter comandado uma frota inteira na banheira de sua mãe na Inglaterra, mas estamos falando de um navio de verdade!",
"E você está olhando para um capitão de verdade. Me teste!",
"Justo. É o seu funeral. Está vendo aquele imbecil ali na mesa? Ganhe uma briga com ele e conversaremos. Ei, ",
"Gervasio Serrao",
", esse sujeito aqui te chamou de minhoca!",
"Muito bem, então vou esmagá-lo como uma minhoca!",
"Estou impressionado. Mas o talento para a esgrima não faz de um #sgender# um capitão.",
"Não? Então me faça outro teste. Diga.",
"Todo aquele suor por nada? Esta bem! Vou só ter que te matar e levar o seu navio",
"Olha, #schild#, isso foi divertido, mas estou ficando entediado. Se você não quer trabalhar para mim como marinheiro, não perca mais meu tempo.",
"Esta bem. Vou tentar a sorte em outro lugar",
"Veremos o quão entediado você ficará quando eu terminar com você!",
"Você está procurando encrenca, não é? Isso pode ser arranjado!",
"Faça o seu pior, velho!",
"Ei! O que você está fazendo aqui?!",
"Essa é a costa ali, entre a terra e o céu? Adeus, capitão!",
"Pegar",
"",
};
