string DLG_TEXT[76] = { 
"#ssir#, você é capitão ",
"?",
"Quem quer saber?",
"Eu sou ",
". Recebi uma missão de Sua Majestade e entendo que você me transportará para #sRedmond#.",
"Sim está certo. Eu confio que você tem um plano?",
"Não precisamente. Eu só tenho que encontrar uma maneira de entrar furtivamente nas fileiras francesas e causar alguns danos.",
"Entendo. Isso é um pouco vago para o meu gosto. Mas talvez eu possa ajudá-lo.",
"Eu apreciaria que. Mas como?",
"Digamos apenas que tenho algumas ligações entre os franceses. Vamos indo, e explicarei quando estivermos no caminho.",
"Peço perdão - devemos partir imediatamente?",
"Você está com tanta pressa para chegar à cova dos leões?",
"O que há de bom esperando aqui? Quanto mais cedo começar, mais cedo terminará!",
"Verdade verdade. Não se preocupe, zarparemos em breve.",
"Quieto! Aquela era a porta? Eu não gosto disso. Cuidado com as escadas e prepare-se!",
"Você está esperando problemas?",
"Quem é você e o que você quer?",
"Mantenha uma língua civilizada em sua boca, ou você a encontrará no chão. Sou do governador.",
"Finalmente! Graças a Deus. Perdoe minha maneira; Devo desempenhar o papel de um soldado francês.",
"Entendo completamente. Sir Robert Christopher Silehard me enviou para ajudá-lo.",
"Então ouça com atenção: descobri recentemente que um capitão francês perdeu uma pequena fortuna no gamão. Você está familiarizado com o jogo?",
"Claro - mas o que isso tem a ver com a sua missão?",
"Conheci esse capitão, certo? Conquistei sua confiança. E ele me disse que havia perdido tanto dinheiro que nunca conseguiria pagá-lo. Na verdade, ele estava preparado para tirar a própria vida quando lhe ofereci outra maneira de sair de sua situação.\nEu me ofereci para pagar sua dívida se ele navegasse em seu navio para #sRedmond# e o entregasse aos nossos soldados. Ele concordou.",
"Incrível! Ele devia estar realmente desesperado para concordar com isso! Quanto ele perdeu?",
"Isso não importa. Combinamos de nos encontrar hoje. Vou dar-lhe o dinheiro e a frota inglesa crescerá em mais um navio.",
"Excelente! Mas o que você precisa de mim?",
"Maldição! Eles me encontraram! Temos que sair daqui imediatamente!",
"Como? Com certeza estarão nos esperando na entrada da cidade!",
"Não vou sair da cidade - meu trabalho aqui ainda não terminou. Mas conheço uma pessoa que pode nos esconder até que as coisas esfriem.",
"Quem?",
"É o dono do estaleiro local - ",
"Oweyn McDorey",
"Oweyn McDorey",
". Devíamos ir para lá imediatamente.",
"Suponho que não temos muita escolha. Vamos.",
"Tente evitar os soldados franceses ao longo do caminho - caso contrário, talvez nunca cheguemos ao estaleiro.",
"Acredite em mim, se houver uma briga, não será porque eu comecei.",
"Devemos chegar ao estaleiro!",
"Eu sei que! Para onde você acha que estou indo?",
"Tenho de manter o acordo com aquele capitão francês: a captura sem derramamento de sangue de um navio francês é boa demais para ser deixada de lado. Mas não consigo imaginar como irei alcançá-lo. Tenho certeza de que há guardas nos portões que levam à selva.",
"Qual é o seu plano?",
"Tenho o dinheiro que prometi ao francês. Mas os guardas agora conhecem meu rosto; Eu não iria longe nas ruas.",
"Onde e quando você deveria encontrá-lo?",
"Ele estará na taverna esta noite, mas não posso ir lá e correr o risco de ser reconhecido.",
"O que podemos fazer então?",
"Temos que avisá-lo para nos encontrar em outro lugar. Em algum lugar seguro. Olha, ninguém te conhece aqui, certo? Você pode ir dizer ao capitão francês que esperarei por ele atrás da taverna, perto da muralha da cidade.",
"Não sei. Não estou exatamente incógnito aqui. Já fui pego em uma briga",
"Não se preocupe com isso. Os outros participantes não estão em condições de falar agora, estão? E quanto a ",
"Everard Gordon",
" ele não vai te entregar. Além disso, meu amigo, se você não for, ficaremos sem opções.",
"Certo. Ótimo. Qual é o nome desse francês?",
"Rabel Iverneau",
"Rabel Iverneau",
". Ele estará sentado na frente do bar, embaixo da escada.",
"Entendi. Vamos tentar descansar um pouco até a noite chegar.",
"Está na hora. Mova-se com cuidado e calma e você não terá problemas com os guardas.",
"Da sua boca aos ouvidos de Deus, meu amigo.",
"Sim, esse é o caminho habitual. A propósito, quase esqueci. Partimos desta ilha no navio francês e acho que seus oficiais deveriam retornar ao seu navio e entregá-lo em #sRedmond#.",
"Não, eu já anotei. Me deseje sorte.",
"Já enviei um dos meus oficiais com ordem de navegar para #sRedmond#.",
"Esperemos que você não precise de sorte. Agora vá!",
"Eu já fui.",
"Olá. Vejo ",
"Rabel Iverneau",
" se juntou a nós.",
"Ok, então o que vem a seguir? Como entramos no navio de ",
"Rabel Iverneau",
"?",
"Aqui está o que faremos: ",
"Rabel Iverneau",
" irá em frente até seu navio - como sempre - e nós simplesmente o seguiremos como cativos ou atendentes.",
"Isso é insano. Pode funcionar.",
"Precisamos ficar perto dele. E vamos rezar para não sermos parados.",
"Claro, caso contrário os franceses estarão em apuros.",
"Esse é o espírito, meu amigo. Mas não acredito que serão um problema. Em breve estaremos fora.",
"Acreditarei quando estivermos a bordo do navio. Até lá, estou de dedos cruzados!",
"",
};
