string DLG_TEXT[600] = {
"Não tenho nada a dizer agora.",
"Muito bem; vamos em frente então...",
"Você está pronto para zarpar, ",
"?",
"Sim, pronto.",
"Olá, ",
"Blaze",
". Eu não esperava ver você aqui.",
"Acredite em mim, estou igualmente surpreso em vê-lo. Parece que não conseguimos ficar longe um do outro ultimamente.",
"Ralph Fawn",
" está morto, e alguém vai pagar!",
"Sinto muito por ouvir isso. ",
"Ralph Fawn",
" era um bom homem.",
"??? O que você está fazendo aqui?",
"??? Você é cheio de surpresas, não é?",
"Você conseguiu as informações de que precisava?",
"Bem, acho que podemos confiar nesse cara. Mas ele não me diz onde ",
"Raoul Rheims",
" está se escondendo.",
"Meu Deus, ",
"! Por que demorou tanto?!",
"Relaxe. Eu disse que tinha outras coisas para fazer.",
", ",
"Vincent Bethune",
" foi na frente para a taverna. Ele disse que deveríamos encontrá-lo lá.",
"Parece que esse cara está aprontando alguma.",
"Onde ",
"Vincent Bethune",
" foi?",
"Ele disse que tinha alguns negócios para cuidar.",
"!!! Parece que alguns palhaços estão nos seguindo. Lide com eles e depois nos alcance. Siga em frente no primeiro cruzamento e depois à esquerda no próximo!",
"Farei isso. Mas lembre-se: preciso de ",
"Raoul Rheims",
" vivo!",
"...",
"O quê? ",
"Raoul Rheims",
" está morto?! O que devo dizer ao governador?",
"?!",
"Sim, estou feliz em ver você também. Que tal um sorriso para alguém que acabou de salvar sua vida?",
"Seria inteligente esperar até o anoitecer. Será mais fácil entrar furtivamente na cidade então.",
"Sim. Boa ideia.",
"O que você está esperando? Precisamos entrar na residência antes do amanhecer!",
"Teremos que encontrar outra maneira de entrar - uma janela, talvez?",
"Pode ser uma boa hora para nos separarmos.",
"Por quê? Formamos um bom time.",
"Vamos ter uma luta de verdade. Preciso de tempo para preparar minha equipe antes de atacarmos essas minas amaldiçoadas.",
"...",
"Homens! Decidi atacar as minas de ouro em #sisland_Oxbay#. É uma proposta perigosa, e alguns de nós podem não sobreviver a essa luta. Mas vale a pena o risco!",
"Pense em todo o ouro esperando lá dentro por uma mão forte para pegá-lo! O que é perigo comparado a isso? Quem está comigo?",
"Aquele rato que o Enrique roubou com meu navio! Maldita seja sua pele escamosa!",
"Agora tenho que começar do zero novamente. É melhor encontrar uma cidade e pedir trabalho.",
"Bem! Pelo menos aquele traidor não estava mentindo quando disse que se livrou daqueles bandidos...",
"Maldita seja sua pele escamosa! Aquele rato ",
"Enrique Forneris",
"fugiu com meu navio!",
"Agora tenho que começar do zero novamente. É melhor eu encontrar uma cidade e pedir trabalho.",
"Agora posso fazer uma visita ao corsário espanhol que supostamente sequestrou a garota.",
"Ir para o navio do pirata.",
"Não, agora não é hora para isso.",
"Agora tenho que encontrar aquela garota. Se ela não estiver por aqui em algum lugar, estou em apuros.",
"...",
"Eu mal escapei daqueles fanáticos! Esse negócio está ficando mais quente do que eu pensava.",
"...",
"Ele quase me matou! Preciso sair daqui!",
"...",
"Você não entende! Escute, a última localização conhecida do ídolo foi #sGreenford#, e não posso dar as caras nas colônias inglesas. Você tem que chegar lá e encontrar o ídolo antes que ",
"Robert Christopher Silehard",
" avise a todos sobre sua 'traição'.\n Eu o dei a um homem chamado ",
"Giraldo Figuiera",
"Giraldo Figuiera",
".\nMas ele já está morto - provavelmente por causa do ídolo. Você terá que perguntar na taverna e ver que pistas você pode encontrar.",
"E o que você estará fazendo? Procurando pela última parte da lenda?",
"Exatamente. Apresse-se - não temos muito tempo!",
"Não se preocupe comigo. Você apenas veja a sua parte do acordo.",
"Oh, ",
", você não pode ser civilizado por um minuto? \nDeixa pra lá - nos encontraremos em #sisland_Oxbay#, na casa daquele velho engraçado. Combinado?",
"Aye-aye, meu adorável capitão.",
"Você está certo. Mas teremos que ir sozinhos. Uma multidão só atrairá atenção desnecessária.",
"Concordo. Vamos lá.",
"O que aconteceu? Quem são essas pessoas?",
"Você não se lembra de nada?",
"Não me empurre, ",
", minha cabeça parece que vai explodir. Por que você não explica o que está fazendo aqui?!",
"Calma! Se alguém tem o direito de ficar bravo, sou eu. Essa sua adaga não fez exatamente cócegas!",
"Eu deveria ter feito isso há muito tempo! Eu sei que você está trabalhando para o governador inglês e que está atrás da minha cabeça. Então vamos resolver isso de uma vez por todas. En garde!",
"Que coisa ridícula, ",
", Eu não estou caçando você. Eu nem sabia ",
"Robert Christopher Silehard",
" queria que você morresse!",
"Você está mentindo! E não é a primeira vez, ",
"! Você mesmo disse que faria qualquer coisa por ouro, não é?!",
"Pelo amor de Deus, ",
", estava apenas interpretando o papel! Você tinha tanta certeza de que eu era um canalha, que não queria te decepcionar!",
"Do que você está falando? Eu sempre pensei que você fosse um #sgender# honesto!",
"Ah, claro! Olha, nós nos conhecemos há muito tempo, e passamos a maior parte do tempo competindo um com o outro. Mas isso não significa que eu esteja atrás do seu sangue! Ou você só tem um problema comigo porque eu sou #sgender#?",
"E daí se eu tiver? #sgender# são bestas sujas, e você não é exceção!",
"Sério? Eu te machuquei de alguma forma? Parece que estou sempre salvando sua pele!",
"Isso é discutível. Mas o fato é que você está trabalhando para um homem que não quer nada mais do que me ver morta!",
"Correção. Eu trabalhei para ele, ",
". Estou... aposentado agora, embora ",
"Robert Christopher Silehard",
" ainda não saiba.",
"Por quê? Ele não te pagou o suficiente?",
"Acredite ou não, ouro não tem nada a ver com isso. Não há dinheiro suficiente no mundo para me manter fazendo recados para alguém como ele.\n E consigo muito mais ouro do que ele me paga saqueando navios.",
"Então por que você está aqui? Se você é um #sgender# livre, então vá!",
"Tudo bem. Posso ver que você não mudou nada. Eu já fui, e você também vai, se souber o que é bom para você. Esses cadáveres vão atrair um monte de problemas antes de atrair a primeira mosca.",
"!!!",
"O que foi agora?",
"...",
"Você tinha mais alguma coisa a dizer ou eu posso ir?",
"... Obrigada, ",
", Eu teria morrido se não fosse por você.",
"Esqueça. Posso ir agora?",
"Espere, ",
"! Para onde você vai agora?",
"Vou fazer algumas perguntas a um certo governador corrupto.",
"Espere um minuto, ok? Você não pode ir lá sozinho. Isso é suicídio! Se ",
"Robert Christopher Silehard",
" suspeitar de alguma coisa, ele vai te matar só para ficar seguro!",
"Obrigado pelo aviso. Vou arriscar.",
"Então eu vou com você!",
"Para quê? Eu posso me virar.",
"Primeiro de tudo, tenho minhas próprias perguntas para o governador. E segundo... segundo...",
"O quê?",
"Eu conheço um lugar em #sisland_Redmond# onde podemos atracar com segurança, sem ninguém para nos incomodar.",
"Tudo bem, tudo bem. Somos parceiros. Temporariamente.",
"Concordo. Uma coisa, no entanto: se você me armar, ",
", Eu juro que te mato.",
"Está bem.",
"Então você está trabalhando para aquele cachorro inglês?",
"Exatamente, querida. Você poderia dizer que sou o braço direito dele.",
"Que negócio? Ele nunca me contou nada sobre isso!",
"Como eu poderia saber? É melhor falarmos com nosso fugitivo.",
"Não consigo deixar de pensar que você está escondendo algo de mim, ",
".",
"Por favor, ",
" você pode confiar em mim pelo menos uma vez?",
"Tudo bem. Falaremos sobre isso mais tarde. ",
"Raoul Rheims",
", ele está aqui, certo?",
"Sim, ele está sentado naquela mesa ali. Vamos pagar uma bebida para ele e bater um papo.",
"Ah, relaxa, ",
"! Ele só foi descobrir se ",
"Raoul Rheims",
" ainda mora aqui. Só isso.",
"Certo, vamos para a taverna.",
"Claro, mas você não disse que ficaria desaparecido por vários dias!",
"É possível que estivesse preocupado comigo, ",
"Danielle",
"?",
"Sim, é possível. Nos seus sonhos mais loucos!",
"Legal. Bem, estou aqui agora. Onde está ",
"Vincent Bethune",
"?",
"Ele está no meu navio, lutando uma batalha corajosa contra um tédio esmagador.",
"Olha, me desculpe pela demora, tudo bem? Para onde vamos agora?",
"Para #sDouwesen#. ",
"Vincent Bethune",
" diz que mora lá.",
"Ótimo. Não vamos perder mais um minuto.",
"Espere. Sua tripulação não é um pouco grande demais?",
"Talvez você esteja certo - vou ver quem posso deixar em terra.",
"Vá para o mar e eu me juntarei a você.",
"Tudo bem.",
"Então você ia encontrá-lo sozinho? Isso não funciona para mim, ",
"!",
"Relaxe - esse nunca foi o plano. Vamos encontrá-lo juntos. Você falará com ele, descobrirá o que precisa e então o levarei ao homem que quer vê-lo.",
"Justo. Mas tenho alguns negócios para cuidar primeiro. O que acha de nos encontrarmos aqui em alguns dias?",
"Tudo bem. Isso me dará tempo de fazer um relatório ao meu empregador.",
"Não estou com humor para suas piadas agora, ",
"- Tive um dia difícil.", 
"Meu dia não foi melhor, acredite em mim. Quem é esse dândi com quem você está? Devo me preocupar?",
"Não seja um porco, ",
"! Ele é apenas... um amigo meu. ",
"Vincent Bethune",
". Ele está me ajudando a procurar um capitão chamado ",
"Raoul Rheims",
"Raoul Rheims",
".",
"Você está brincando! Eu também estou procurando por ele - embora, para ser honesto, pareça que perdi seu rastro.",
"O que você quer com ele?",
"Dinheiro, querida. Me prometeram uma grande quantia para pegá-lo.",
"Cuidado com essa coisa de 'querida', ",
"! Sempre suspeitei que você fosse apenas mais um canalha ganancioso! ",
"Eu nunca fingi ser outra coisa, ",
". Então, você sabe onde ",
"Raoul Rheims",
" está se escondendo?",
"Não, não sei. Mas ",
"Vincent Bethune",
" afirma que sabe onde o cara se estabeleceu.",
"Isso é quase conveniente demais. Você encontrou a única pessoa que sabe onde encontrar o homem que você está procurando?",
"Não seja tão desconfiado, ",
". Nem todo mundo é um canalha como você. ",
"O que isso quer dizer, ",
"? Só estou tentando ver todos os ângulos. Como ",
"Vincent Bethune",
" sabe onde ",
"Raoul Rheims",
" está se escondendo?",
"Por que você mesmo não pergunta a ele?",
"Acho que farei exatamente isso.",
"Não vejo o que é tão engraçado, ",
"Blaze",
". Vá incomodar outra pessoa se não tiver nada melhor para fazer.",
"Ainda escondendo seu profundo e duradouro amor por mim, não é? Tudo bem. Se preferir ficar sozinha, é assim que vou deixá-la.",
"Guarde sua compaixão para si mesmo, ",
"! Não preciso disso. ",
"O que quer que você diga. Mas por que acha que aqueles soldados nos atacaram de repente? Não me lembro de ter tido uma briga com os ingleses. E você?",
"Isso não é da sua conta! De qualquer forma, não vou chegar perto de outra bandeira inglesa por um tempo. Estou saindo desta cidade e aconselho você a fazer o mesmo.",
"Espere!",
"?!? Como você chegou aqui?",
"?!? O que você está fazendo aqui?",
"Eu vim aqui te procurar! Eu estava com medo de que você já estivesse alimentando os tubarões!",
"Você estava realmente preocupanda comigo? Estou comovido.",
"Você?! Eu estava preocupado com o ídolo! Eu teria tido dificuldade em colocar as mãos nele se estivesse no fundo do mar com seu navio.",
"O ídolo está seguro comigo. Mas falando em navios, onde está o seu?",
"Eu tive que trocá-lo por aquela tábua. Mas vai valer a pena quando eu encontrar o tesouro! Ele poderia comprar cem navios de primeira classe!",
"Espero mesmo que tenhas razão. Onde está agora esse pedaço de barro caríssimo?",
"A tábua é pesada demais para carregar. Copiei todo o texto no papel.",
"Hm. ",
", por que tenho a sensação de que você está escondendo algo de mim?",
"Talvez eu esteja, talvez não. De qualquer forma, você ainda terá que se contentar com o que puder obter. Aqui está o texto. Mais alguma pergunta?",
"Só uma. O que fazemos agora?",
"Você tem uma cabine extra para mim no seu navio? Eu odiaria que você tivesse que se mudar para os aposentos da tripulação.",
"Não se preocupe, você terá sua cabine. Enquanto isso, tenho muito a lhe contar.",
"Mais tarde. Quando terminar aqui, suba as escadas. Conversaremos então.",
"Tudo bem.",
"Meu navio foi roubado, e a placa junto com ele. Ainda bem que fiz uma cópia do texto da placa.",
"Não se culpe, ",
". Coisas piores acontecem no mar, sabia.",
"Poupe-me dos clichês, ",
"! Não estou me culpando. Estou furiosa! Mas não ficarei por muito tempo. Terei um novo navio em breve, e então pegarei aquele rato ladrão e o estriparei!",
"Escute você! Você parece um pirata!",
"Eu pareço um capitão, que é o que eu sou. Você quer boas maneiras, vá trabalhar para #sthe Governor#!",
"Não, obrigado. Estou de olho naquele tesouro também.",
"Então vamos pensar no nosso próximo passo. Precisamos encontrar alguém que possa traduzir essa ladainha antiga! Se não quisermos acabar como Rheims, precisaremos ler o texto inteiro.",
"É verdade. Você sabe, se bem me lembro, ",
"Researcher",  // não traduzir
" é conhecido por se gabar de seu conhecimento de línguas antigas...",
"Isso mesmo! Vamos fazer uma visita a ele.",
"Para #sGreenford#, então! Estarei esperando por você a bordo do navio amanhã de manhã.",
"Por que demorou tanto? Estamos prontos para zarpar?",
"Claro. O navio está em perfeitas condições.",
"Vamos partir, então!",
"Não se esqueça de quem é o capitão aqui.",
"Vamos partir, então!",
"Não se esqueça de quem é o capitão aqui.",
"Parece que teremos que libertar ",
"Researcher",  // não traduzir
" da prisão de #sGreenford#.",
"Sim. Ou encontrar outra pessoa que possa ler a lenda.",
"Não acho que encontraremos outro homem com sua educação em um milhão de anos. Não nessas ilhas!",
"Então o que você sugere? Nós apenas entramos furtivamente na cidade e invadimos a prisão?",
"Por que entrar furtivamente na cidade quando podemos capturá-la?",
"Capturá-la?! Você perdeu a cabeça?",
"De jeito nenhum. Você atinge o forte pelo mar, e eu levo minha tripulação pela selva e ataco por terra. Eles nunca saberão o que os atingiu!",
"Tenho certeza de que parece fácil para você. Você não precisa atacar o forte!",
"Você prefere se arrastar por uma selva cheia de vermes venenosos? Sem problemas - eu troco com você num piscar de olhos!",
"Não, não. Isso não seria... justo com você. Eu vou ficar com o mar.",
"Achei que você veria do meu jeito. Precisaremos de algum tempo para planejar o ataque - não será moleza. Quando estivermos prontos, você pode me colocar e minha tripulação em terra no farol.",
"Certo. Vamos voltar para o navio.",
"Por que perder tempo? Vamos atacar agora, antes que tenhamos a chance de mudar de ideia!",
"Tem certeza? Desta vez, lutaremos contra soldados, não contra a tripulação de um comerciante gordo!",
"Temos bastante mão de obra para capturar a colônia!",
"Bem, talvez devêssemos reservar um tempo para nos preparar.",
"Eu daria meu braço com a espada para ver a cara do governador quando ele ouvir sobre isso!",
"Avante!",
"Vamos voltar para o navio, ",
"? Ou você decidiu dar uma volta?",
"Sim, claro que vamos voltar para o navio.",
"Esta é sempre a parte mais difícil - quando o planejamento foi feito e você está apenas esperando o momento certo para se mover.",
"Posso pensar em algumas maneiras de passar o tempo... mas não importa isso.",
"Vamos colocar um pouco de medo nos corações desses marinheiros de água doce!",
"De fato! Vou fazer o governador se arrepender de me usar!",
"Espere! Temos que terminar nossos preparativos primeiro.",
"Por favor, ",
"! Apresse-se!",
"Não me empurre! Não vou me apressar para uma batalha como essa.",
"Quando a fumaça se dissipar, nos encontraremos no centro de #sGreenford#! E não se distraia com pilhagens - não precisaremos do lixo desta cidade quando encontrarmos o tesouro!",
"E não deixe a emoção da luta distraí-lo dos negócios!",
"Não se preocupe comigo! ",
"Apenas tente ficar vivo, tudo bem?",
"Será preciso mais do que esta cidade para me matar! Boa sorte, ",
".",
"Essa foi uma batalha e tanto! Você está bem?",
"Claro! Eu não planejava morrer hoje!",
"Bem, a morte geralmente não marca hora, sabia!",
"Certo. Vamos nos libertar ",
"Researcher",  // não traduzir
".",
", podemos conversar depois. Precisamos libertar o velho primeiro.",
"Concordo.",
"Então, quanto tempo isso vai levar?",
"Researcher",  // não traduzir
" disse que precisaria de vários dias para traduzir o texto.",
"Já faz uma semana! Estou ficando entediado.",
"Continue imaginando essas pilhas e pilhas de ouro. Isso vai curar seu tédio.",
"Mal posso esperar para zarpar! Por que ele não pode fazer sua tradução no caminho para o templo?",
"Não sei... Eu não tinha pensado nisso.",
"É, acho que um pirata não tem muita utilidade para cérebros. Talvez você também não tenha muita utilidade para ouro, ",
"?",
"O quê?",
"Estou perguntando o que você vai fazer com sua parte do tesouro. Me entretenha.",
"Não sei. Vou comprar uma ilha inglesa, suponho, e fazer minhas próprias regras. Ou talvez eu me torne um nobre inglês. Isso pode ter suas recompensas. E você?",
"Não vou contar. É meu segredo.",
"Tudo bem. Seja assim.",
"Você vai enfrentar a frota regular?",
"Não - eu vou esmagá-la!",
"Eu vou comandar o forte! Tente manter a luta ao alcance do canhão.",
"E você só toma cuidado em quem está atirando!",
"Nós vencemos! Eles vão escrever músicas sobre essa batalha, ou eu sou uma velha bruxa do mar! Poderíamos tomar o arquipélago inteiro juntos! Ou o Caribe inteiro!",
"Claro que poderíamos. Mas pode fazer mais sentido bater um papo com ",
"Researcher",  // não traduzir
" primeiro.",
"Escute você, ",
"! Você deveria ter vergonha de si mesmo, esmagando os sonhos de uma doce garota com sua lógica chata!",
"O tesouro sempre vem primeiro, minha querida. Depois, se você ainda quiser conquistar o Caribe, estarei com você. Considere isso uma promessa.",
"Espero que aquele colega estudioso tenha tempo suficiente para examinar aqueles rabiscos. Duvido que possamos resistir a um segundo ataque.",
"Duvido que o governador tenha algum navio de guerra sobrando.",
", o templo parece estar situado em algum lugar no interior. Vamos dar uma volta!",
"Certo, mas não queremos chamar atenção para nós mesmos. Deveríamos deixar a equipe aqui até que tenhamos verificado este templo com nossos próprios olhos.",
"Não acredito que o encontramos! Mais algumas horas e estaremos nadando em ouro!",
"Isso se houver ouro lá.",
"Não diga isso! Não poderíamos ter chegado tão longe à toa!",
"Veremos.",
"Há três passagens aqui, e qualquer uma pode ser a certa. Para onde devemos ir?",
"Não sei. Esta pode ser a armadilha que ",
"Researcher",  // não traduzir
" estava falando.",
"Então deveríamos nos separar. Cobriremos mais terreno dessa forma. Eu vou pegar a passagem da esquerda para mim, e veremos quem encontra o tesouro primeiro!",
"Ei, espere...",
"Parece que podemos ir para Khael Rhoa agora!",
"Algo me diz que não vai ser tão fácil.",
"Talvez devêssemos ir em frente e vasculhar o templo enquanto ele lê aqueles rabiscos.",
"Não sem alguma ideia de para onde estamos indo! O próprio diabo pode se perder naquele labirinto!",
"Faça do seu jeito. Eu vou sozinho. Já vejo a primeira parte da minha parte do saque!",
"O quê?",
"Deve ser a alcova que ",
"Researcher",  // não traduzir
" estava falando. Mas onde está o tesouro?",
"Eu não sei. Mesmo se tirássemos todo o ouro das paredes, não valeria muito...",
"Não podemos perder muito mais tempo procurando, ",
". Eles vão capturar a cidade!",
"Só quero ter certeza de que você não vai me afundar também, depois que cuidarmos da frota inglesa.",
"Agora, isso realmente dói, ",
".",
"Brincadeira! Estou brincando. Boa sorte!",
"Meu Deus! O que foi isso?",
"Não tenho ideia!",
"Três mil demônios, ",
"! Ninguém sobreviveria a isso! Meu tesouro! Podemos tentar pegar parte dele? Só um pouquinho?",
"Ei, tenho certeza de que não é o único tesouro do mundo!",
"Quem se importa! Ainda é uma perda!",
"Não tenho certeza se você se importa tanto com o ouro quanto finge...",
"Eu não deveria voltar para lá. Preciso sair de #sisland_Redmond# rápido!",
"Poor ",
"Ralph Fawn",
"! Juro, o governador vai pagar pela morte dele! Mas por que ele daria uma ordem dessas? Ele pensou que ",
"Brendan Applin",
" me disse mais do que eu preciso saber? Tenho que descobrir o que está acontecendo!",
"Brendan Applin",
" murmurou algo sobre tesouro. E tesouro é uma cura certa para o tédio. Acho que vou fazer uma visita a #sQuebradas Costillas#. ",
"Brendan Applin",
" também mencionou alguém chamado ",
"Raoul Rheims",
"... Talvez eu devesse procurá-lo.",
"Hm... Isso parece ser algum tipo de diário. E o autor é provavelmente este ",
"Raoul Rheims",
", o homem que estou procurando. Droga! A maioria das páginas foi destruída pela água. Apenas as últimas são legíveis: '... os reparos serão feitos em breve,\ne terei que ir a #sRedmond# para informar Sua Graça sobre nosso fracasso... A chave deve estar nas partes da lenda que não consegui ler. Vou procurar todos os vestígios desse mito, e da próxima vez VOU encontrar o templo...'\nHm. E a próxima entrada: 'Deus me ajude, levei um tiro hoje! O rato fugiu, mas acho que o reconheci. Tenho certeza de que o encontrei na residência do governador. Pode ser que ",
"Robert Christopher Silehard",
" ordenou minha morte? Parece que terei que ficar quieto por um tempo.\n",
"Desmond Ray Beltrop",
" não me negará refúgio. Então posso tentar descobrir o que está acontecendo... Odeio deixar meu navegador, ",
"Giraldo Figuiera",
" aqui, mas ele pegou malária e não sobreviveria à viagem. Espero que ele seja inteligente o suficiente para segurar a língua.'",
"(Leia mais.)",
"(Pare de ler.)",
"Deus, não #sisland_Quebradas Costillas# de novo! Mas esta é a única pista que tenho.",
"Partimos hoje. O céu está limpo até agora. Espero que continue assim até chegarmos a #sConceicao#. Os eventos dos últimos dias drenaram meu espírito. Não sei mais o que pensar. Não sei o que fazer. Talvez eu não devesse ter me envolvido nisso...'\nAha - esta entrada foi feita vários dias depois: 'Finalmente me sinto seguro. ",
"Desmond Ray Beltrop",
" me recebeu de braços abertos e me prometeu proteção dentro destas paredes. Isso me deu tempo para pensar.'\nE aqui está a última entrada: 'Tive uma ideia hoje: em vez de perder tempo aqui, eu deveria procurar a fonte da lenda que me levou ao antigo templo. \nComprei uma pequena casa de um dos moradores locais; ela me servirá de base. Partirei amanhã, deixando tudo que não preciso aqui.'",
"Então, ",
", o que você acha que devemos fazer sobre nós?",
"...Nós? Existe um 'nós', #sDanielle#?",
"Pode haver, se você quiser.",
"De fato? Você está realmente deixando isso para mim?",
"Eu sei que esse não é meu estilo, mas também sei que não devo forçá-la a nada. Não quero arriscar perder sua amizade.",
"Amizade? É só isso que tem sido?",
"Eu acho que você sempre soube que poderia ser mais.",
"Poderia muito bem ter sido mais se você não fosse tão cabeça quente, minha querida.",
"Bem, nós formamos um bom time.",
"Então nos separaremos, ",
"?",
"Nós dois somos independentes demais para uma parceria, de qualquer forma. Por enquanto, acho melhor.",
"Talvez você esteja certa.",
"Não fique tão decepcionada, #sDanielle#. Você tem que saber que nos encontraremos novamente.",
"Moi, decepcionado? Você se gaba muito, mon ami!",
"Não consegui resistir à provocação, Babe. Mas como eu disse, temos uma sorte terrível em evitar um ao outro. Não é o fim.",
"Especialmente porque não dividimos nossas partes do saque!",
"Eu estava ahhh...esperando que você esquecesse disso.",
"Vamos para a cidade juntos e ver se há uma recompensa por derrotar Silehard.",
"Certo. E podemos dividir depois.",
"Eu acho que sim. E você prometeu que se eu quisesse conquistar o Caribe, você estaria bem atrás de mim.",
"Com você, minha querida, não atrás de você. Há uma diferença.",
"Bem, você não pode culpar um #skid# por tentar.",
"É o que eu sempre admirei em você, #sDanielle#. Você nunca se rende.",
"Isso, e meus...atributos físicos que você sempre parece estar de olho.",
"Bem, você GERALMENTE parece melhor do que meu primeiro oficial NORMAL.",
"Muito engraçado, ",
". Mas você sabe que eu poderia concordar em me render, no seu caso. Você sempre foi o melhor capitão.",
"Essa é outra coisa que sempre admirei em você, #sDanielle#. Você reconhece um bom marinheiro quando vê #spronoun2#.",
"Você sempre disse que eu tinha um gosto horrível para #sgenders#!",
"Você tem. E eu sou horrível. Então, vamos ficar juntos?",
"Poderíamos ter feito pior.",
"Já fizemos pior. Talvez seja hora de mudar isso.",
"Bem, ",
"?",
"Eles ficaram felizes que pegamos Silehard, vivo ou morto.",
"E o ouro? Houve uma recompensa?",
"Uma quantia irrisória, considerando. Melhor, não precisamos mais nos esgueirar.",
"Pelo menos por enquanto.",
"Verdade. Temos livre arbítrio, podemos fazer o que quisermos.",
"Falando em livre arbítrio, só quero deixar isso claro; é parte para nós ou parceria?",
"Parte, eu acho.",
"Doce parceria, eu acho.",
"Tudo bem. Onde está minha metade dessa recompensa? Preciso de um navio, contratar alguns homens.",
"Sempre sentimental.",
"Você quer fazer isso ou não?",
"...É para o melhor, realmente.",
"...Não, não posso. Fique comigo.",
"Então tenho que ir agora, antes que mudemos de ideia novamente.",
"Tudo bem. Aqui está o ouro. Não gaste tudo em um só lugar.",
"Ventos favoráveis e mares calmos, ",
".",
"Sim, e que você sempre tenha o medidor de tempo.",
"Eu sempre tenho!",
"Heh. Sim, você tem. Fique segura, #sDanielle#.",
"Agora quem está sendo sentimental?",
"Oh, bobagem. Você sempre foi mais rápida com uma lâmina. É melhor ter você do meu lado do que sua faca no meu lado.",
"Se isso fizer você se sentir melhor, vou guardar minha faca na sua cabine.",
"Isso provavelmente será pior do que se você a carregasse!",
"Então estamos juntos.",
"Sim, sim. Você quer assinar artigos?",
"Eu não acho que precisamos deles, você precisa? A menos que você queira ir ver um padre?",
"Hum, não. Não, obrigado. Podemos fazer isso sem... formalidades.",
"Bom. Então, você decide. O que vem depois?",
"Tenho certeza de que algo vai acontecer.",
", Eu tenho guardado um amuleto mágico que acho que me ajuda a permanecer vivo. O que você acha que eu deveria fazer com ele?",
"Você está brincando?! Não seja supersticiosa #sDanielle#, livre-se dele. Você, mais do que ninguém, deveria saber que não é o amuleto, é sua habilidade.",
"Se você acha que ele te mantém vivo, então acho que você deveria ficar com ele. Não posso me dar ao luxo de te perder.",
"Vamos, ",
"! O tempo está passando!",
"Nag, nag, nag!",
"Deixe-o, ",
", ele está em outro mundo.",
"Bem, pelo menos ele está em casa em segurança, então devemos ir. Precisamos chegar a #sRedmond# para ver se há uma recompensa por derrotar Silehard.",
"Gostei do jeito que você pensa!",
"Vamos sair daqui.",
"Muito bem, vou dizer à tripulação para içar ",
"cores.",
"Obrigado.",
"OK.",
"Obrigado.",
"Desculpe, isso não vai funcionar.",
"Ah, bem.",
"Atualmente estamos em ",
"rações de comida e ",
"rações de rum. Temos comida suficiente para ",
"dias e rum suficiente para ",
"dias, com nossas rações atuais. Você quer mudar as rações?",
"Sim, vamos para rações completas de comida e rações normais de rum.",
"Sim, vamos para rações de meia comida e rações normais de rum.",
"Sim, vamos para rações completas de comida e rações duplas de rum.",
"Sim, vamos para rações de meia comida e rações duplas de rum.",
"Muito bem, agora estamos com rações completas de comida e rações normais de rum.",
"Muito bem, agora estamos com rações de meia comida e rações normais de rum.",
"Muito bem, agora estamos com rações completas de comida e rações duplas de rum.",
"Muito bem, agora estamos com rações completas de comida e rações duplas de rum.",
"Você precisará dividir o saque primeiro, capitão.",
"Ah, deixa pra lá.",
"Um salário!? Tem certeza, capitão ",
"? Não foi para isso que a tripulação assinou.",
"Sim, tenho certeza. E não me importa quantos desertos!",
"Assinar artigos!? Tem certeza, capitão ",
"Sim, tenho certeza. E não me importa quantos desertos!",
"Muito bem, informarei a tripulação. Mas esteja avisado - alguns deles podem desertar.",
"Muito bem, informarei a tripulação. Mas esteja avisado - alguns deles podem desertar.",
"Quais cores devemos voar, capitão ",
"Nossas atuais ",
"Deixar minhas próprias cores.",
"Cores piratas.",
"Levantar um ",
"Minhas próprias cores.",
"A seu serviço, ",
". Alguma ordem?",
"Não, fique à vontade.",
"Sobre o navio e a tripulação...",
"Sobre mim...",
"Sobre você...",
"Sim?",
"Qual é o status de nossas provisões?",
"Terminamos com o corso. Agora todos vocês receberão um salário.",
"Vamos assinar artigos.",
"Abaixar nossas cores; estamos hasteando uma nova bandeira.",
"Qual é o status dos nossos navios atracados?",
"Parece que não me encaixo muito bem neste mundo...",
"Preciso trocar de roupa.",
"Da próxima vez que embarcarmos, você vem comigo.",
"Por que você não fica de fora no próximo embarque?",
"Fique aqui!",
"Siga-me e seja rápido!",
"Você precisa de um uniforme melhor.",
", Receio não precisar mais dos seus serviços. Vou mandar trazer seu baú de marinheiro para a costa para você!",
"Você está demitido. Não preciso dos seus serviços!",
"Como você disse, ",
"! Mas olha - se você me demitir, nunca mais voltarei ao seu navio. Então, você decide.",
"Bem. Mudei de ideia. Ainda preciso de você.",
"Ótimo! Sai fora!",
"Tem certeza, ",
"? Eu gostaria de ficar, se você me quisesse!",
"Sim, tenho certeza. Mas, nunca se sabe, eu gostaria de poder te encontrar se eu precisar de você novamente!",
"Que possamos nos encontrar novamente em breve, então. Bons ventos e mares calmos, ",
"E para você, ",
"Eu te disse, ",
", Eu não voltarei. Eu tenho meu próprio orgulho.",
"E eu também não preciso de você!",
"Que tipo de pirata você é, ",
"? Agora você é conhecido como ",
"e atualmente não contamos a você sobre avistamentos a menos que tenhamos uma chance de derrotá-los.",
"e atualmente contamos a você sobre todos os navios que avistamos.",
"Quero mudar as ordens permanentes sobre navios inimigos poderosos.",
"Agora não vamos incomodá-lo com avistamentos muito poderosos.",
"Agora contaremos a você sobre todos os avistamentos.",
"a",
"Um ",
"Um ",
"um ",
"a ",
"Pode apostar!",
"Então está claro.",
"Tudo bem, vou me manter ocupado perseguindo ratos no porão.",
"Parece que vai levar algum tempo até que entendamos este texto antigo. Podemos usar esse tempo para nos preparar para a jornada. Também devemos proteger a baía de #sGreenford# para garantir que ninguém nos interrompa.",
"Farei os reparos e provisões necessários para",
"o navio",
"a frota",
". Também seria um bom momento para colocar o forte em algum estado utilizável.",
"! Você deveria ter vergonha de si mesmo, destruindo os sonhos de um rapaz corajoso com sua lógica chata!",
"Bem, pelo menos ele está em casa em segurança, então devemos ir.",
"O que vamos fazer agora, ",
"A mesma coisa que sempre fazemos, ",
"- tentar dominar o Caribe!",
"Por que estamos parados, ",
"? Esse ouro não virá até nós, temos que ir buscá-lo!",
"É verdade, ",
". Vamos lá!",
"Ah, é você, ",
". O que você está fazendo aqui?",
"Não é da sua conta, ",
". E eu poderia lhe fazer a mesma pergunta - mas estou muito ocupado para isso.",
"Ainda se fazendo de difícil, não é? Justo...",
"Fique quieto, ",
", você vai?",
"O que devemos fazer agora? Não podemos encontrar o tesouro se não pudermos traduzir essa lenda. E temo que o velho...",
"Já nos colocamos contra #sGovernor# e a coroa inglesa. O que temos a perder se capturarmos aquela cidade miserável e libertarmos #sResearcher#?",
"Eu não sabia que você tinha tendências suicidas. Mas se você está falando sério sobre isso, então vamos nos divertir um pouco!",
"Agora você está falando! E eu estou me sentindo como um verdadeiro pirata. Eu atacarei o forte do mar, e você e seus homens podem sitiar a cidade da terra. O que você diz?",
"Eu digo que criei um monstro, ",
".",
"Hah! Um Kraken ambulante, sou eu! Mas estou pronto quando você estiver.",
"Precisaremos de algum tempo para planejar o ataque - não será moleza. Quando estivermos prontos, você pode me colocar e minha equipe em terra no farol.",
"Quando iremos para #sRedmond#? Se não conseguirmos o ouro do templo, pelo menos vamos tentar conseguir algo para Silehard.",
"Tenha um pouco de paciência, ",
"! Não me esqueci disso.",
"O que estou fazendo aqui?",
"Não sei, o que você está fazendo aqui?",
"?! O que você está fazendo aqui?! Embora, conhecendo você, eu não deveria estar surpreso!",
"O que você está fazendo aqui, querida?",
"Bem, eu tenho coisas para fazer, você sabe. Adeus.",
"Espere! Você pode me dizer se o comerciante Jean Maginot está na cidade?",
"Eu?! Bem, quando você desapareceu, eu fiz algumas perguntas... Eu tive que assumir a cidade.",
"Assumir a cidade?! Você está louco?!",
"O quê?! Essa é sua maneira de dizer obrigado?! Tudo bem, fique na sua cela!",
"Desculpe, eu não quis dizer isso. É que eu não esperava que você fosse tão longe por mim...",
"Eu também não esperava... É que... Esqueça, vamos sair daqui.",
"Isso mesmo. Além disso, tenho alguns negócios com um comerciante local.",
"Você quer dizer Jean Maginot? Mas ele está fora da cidade. Acho que ele foi para a selva e não adianta procurá-lo.",
"Oh, o diabo. Tudo bem, abra a cela.",
"Tudo bem, capitão.",
"...",
"Eu? Bem... Acabei de capturar esta colônia e decidi dar uma olhada na prisão para ver quem está sentado aqui.",
"Bem... Como você pode ver, estou sentado aqui.",
"Você roubou alguém de novo?",
"Algo assim. Mas você vai me deixar sair daqui ou não?",
"Oh, pelo amor de Deus!",
"Obrigado por isso.",
"Não. Cobrei um resgate e o deixei ir. Acho que ele já saiu da cidade e está se escondendo em algum lugar na selva.",
"Bem, obrigado.",
};
