string DLG_TEXT[71] = {
"Olá, ",
". Eu sou ",
"Ewan Glover",
"Ewan Glover",
", capitão do brigue naval ligeiro 'Albion'",
"Prazer em conhecê-lo, ",
"Ewan Glover",
".",
"O prazer é meu, capitão. O próprio Silehard me contou como você deixou os franceses sem pólvora ou balas de canhão. E tão habilmente feito! Não me importo de dizer, fiquei muito impressionado.",
"Obrigado, ",
"Ewan Glover",
", você me elogia.",
"De jeito nenhum. Mas tenho certeza de que teremos tempo suficiente para discutir nossas aventuras tomando uma caneca de cerveja em breve. Por enquanto, temos trabalho a fazer.",
"Você está pronto para zarpar?",
"Sim eu sou. Mas, ",
", sua frota é muito grande e pesada para ser eficaz. Deixe uma de suas embarcações aqui em #sRedmond# e eu me juntarei a você quando estiver pronto.",
"Tudo bem, ",
"Estou pronto para abrir caminho. Assim que você zarpar, eu te seguirei.",
"Excelente. Te vejo nos mares!",
"Espero por você na taverna. Perguntar ",
"Carlos Windem",
" sobre mim.",
"É um acordo. Eu vou ligar para você.",
"Desculpe, ",
", mas estou com pressa. Pretendo zarpar em breve.",
"Você está certo, é claro. Não vou te atrasar mais.",
"Olá, ",
". Então, há um lugar livre para mim?",
"Ainda não, receio. Você terá que esperar um pouco mais.",
"Estamos nos preparando para zarpar. Você está pronto?",
"Tão pronto como sempre estarei, embora tenha pena de deixar este porto agradável e o seu rum muito bom.",
"Em breve voltarei.",
"Eu estou sempre pronto. Encontro você no porto",
"Eu vou te ver",
"Devíamos ir agora. Quero acabar com isso o mais rápido possível.",
"Eu também, então vamos navegar",
"Vamos para a taberna, ",
". A melhor forma de esperar o anoitecer é com uma caneca de cerveja boa na sua frente.",
"Difícil argumentar contra isso. Vá em frente!",
"Te encontro mais tarde. Tenho outros assuntos para cuidar primeiro.",
"Justo. Quando terminar, venha para a taverna. Vou pedir ao barman para manter um pouco de vinho quente quente para você!",
"Você é muito gentil. Eu volto em breve.",
"Então, onde está aquele sujeito local que deveria nos encontrar?",
"Vamos ficar um pouco. Ele provavelmente estará aqui em breve.",
"...e então aquela beldade proclamou: 'A menos que você se torne um capitão respeitável, você nem precisa sonhar comigo!'",
"Então você se tornou capitão?",
"Sim. Mas em algum lugar ao longo do caminho, percebi que aquela mulher não significava nada para mim, por mais adorável que fosse. Ela não me queria; ela queria gastar o dinheiro de um capitão! Então por que eu deveria voltar?",
"Faz sentido para mim.",
"Devemos estar em movimento em breve. Já está escuro!",
"A propósito, você já ouviu falar desse oficial arrogante que usou a fragata do rei para seus propósitos pessoais?",
"O que você está falando agora?",
"Eu adoraria ouvir sobre isso - em outra hora. Agora vamos!",
"Uma fragata veio de Glasgow para #sRedmond# recentemente. Era para ser o novo carro-chefe da frota #sisland_Redmond#. Eles tiveram a ideia lá em Londres de que problemas poderiam começar nas colônias...",
"Então?",
"Bem, quando os franceses capturaram #sOxbay#, o capitão da fragata recebeu uma ordem secreta direta do governador Silehard. \nNo dia seguinte, a fragata partiu para o mar, e o governador acabou por ter que comandar navios civis para se defender da frota francesa!",
"Interessante. Mas não há nenhuma razão clara para suspeitar de irregularidades.",
"Nenhuma razão clara? A guerra estava à sua porta e o governador enviou o navio mais poderoso da frota sabe Deus para onde? Talvez ele tenha um acordo com os franceses!",
"Você percebe que é uma acusação mortalmente séria. Mas vou perguntar a Silehard sobre a fragata.",
"Claro. Faça isso. E deixe-me saber o que ele diz. Ficarei muito interessado em ouvir isso.",
"Eu vou. Agora vamos cuidar dos negócios.",
"Você finalmente está aqui, capitão. Sente-se, por favor, ",
". Seu vinho quente está a caminho.",
"Obrigado.",
"Meu trabalho aqui terminou. Estou voltando para #sRedmond#. Vamos navegar juntos? Há segurança nos números.",
"Sinto muito, não. Ainda não posso ir embora.",
"Você tem outra missão para completar, não é? Bem, boa sorte então ",
".",
"Para você também. Te vejo por aí, ",
".",
"Ei! Perdemos o rumo! Precisamos chegar ao porto de #sGreenford#, não a esta praia deserta.",
"Não há erro. Só tenho alguns negócios aqui e, quando terminar, levarei você para #sGreenford#.",
};
