string DLG_TEXT[56] = {
"Olá #saddress#, deixe-me mostrar os pontos turísticos desta cidade por apenas uma peça de ouro! (O simplório levanta dois dedos em vez de um.)",
"Quem é você?",
"Não sou turista e não preciso de guia!",
"Meu nome é ",
", ",
". Sou um marinheiro do 'Oiseau'. Estamos aqui esperando um navio de escolta e pensei em ganhar um pouco de dinheiro extra, para dar à igreja daqui.",
"Entendo... interessante. Você se importaria se eu lhe fizesse algumas perguntas?",
"Tudo bem. Você pode ir, marinheiro.",
"Sim, ",
" capitão. Eu entendo.",
"Você pode ir.",
"Sim, eu tenho ",
"A informação tem um preço...",
"Quanto você quer?",
"Cinco moedas de ouro, esmolas para a igreja, claro ",
".",
"Tudo bem. Aqui está a sua 'esmola para a igreja'.",
"Eu não tenho tanto dinheiro agora",
"Não vou te pagar para responder perguntas!",
"Obrigado, ",
". Realmente é para a igreja, juro por Davy Jones! Agora o que você queria saber?",
"Você disse que era do 'Oiseau'...",
"Desculpe, ",
". mas vou esperar até você trazer o dinheiro, a igreja realmente precisa dele para ajudar os pobres.",
"É um acordo.",
"Sim, ",
". É o meu terceiro ano navegando nela.",
"E você está esperando a chegada de um navio de escolta?",
"Para onde vai o seu navio?",
"Não, ",
", já está no porto. Está sendo carregado com provisões e munições neste momento, mas iremos ao mar a qualquer momento.",
"Que tipo de navio é esse?",
"Onde está o capitão deste navio?",
"Isso é tudo que eu queria saber. Você pode ir.",
"Infelizmente ",
", Não sei. Nós, marinheiros, não fomos informados. Provavelmente é um segredo, suspeito de assuntos militares.",
"E você está esperando por um navio de escolta?",
"Isso é tudo que eu queria saber. Obrigado.",
"É um brigue chamado 'Le Requin'. Não faz parte da frota do rei francês. O capitão é um civil que foi recentemente contratado para proteger nosso navio.",
"Onde está o capitão deste navio?",
"Isso é tudo que preciso. Você pode ir.",
"Não sei, ",
". Mas você pode perguntar na taverna. Eu sei que ele estava lá mais cedo, ele estava hospedado no quarto de cima e ainda pode estar lá?",
"E qual é o nome do capitão de Le Requin?",
"Amiel Berangere",
"Amiel Berangere",
", ",
".",
"Obrigado, ",
".",
"Olá de novo, ",
". Você precisava de Amiel Berangere. Ele estava lá em cima, na taverna, #ssir#.",
"Olá de novo, ",
". Acho que você disse que não precisava dos meus serviços, correto?",
"Na verdade, tenho uma pergunta.",
"Você tem razão. Adeus, marinheiro.",
"",
};
