string DLG_TEXT[98] = {
"Sair! Não tenho vontade de conversar com gente como você!",
"...",
"O que você quer de mim? Você não vê que estou ocupado?",
"Eu tenho que falar com voce, ",
".",
"Você não se conheceu ",
"Ferro Cerezo",
" antes, e você? Agora é a hora de corrigir esse erro.",
"Você diz que seu nome é ",
"? Você é quem eu procuro!",
"Claro! Todo mundo quer um pedaço de mim!",
"Não seja ridículo. Estou aqui para pegar os papéis que você roubou da igreja #sIsla Muelle#.",
"Sim. Eu sabia ",
"Padre Domingues",
" ficaria inquieto quando soubesse que a prova do seu empréstimo de dinheiro havia caído em minhas mãos.",
"Se você leu esses artigos, então a natureza da nossa discussão amigável terá que mudar.",
"Se é isso que esses documentos provam, então você deveria entregá-los ao guarda.",
"Vamos fazer assim: eu compro os papéis de você.",
"O que você quer dizer?",
"Você deve ter ouvido falar de mim, eu sou ",
"Querido Deus! Claro que já ouvi falar do malandro mais sanguinário destas águas!",
"Cale a boca e me dê os papéis. Posso usá-los melhor do que você.",
"Mas... eu ia...",
"Você disse alguma coisa?!",
"Não não! Nada. Aqui, é só pegar!",
"Adeus.",
"Eu não duvido. Foi uma sorte ter conhecido você - meu próprio navio não é capaz de uma viagem longa.\nSe você prometer entregar os papéis à Europa, eu os entregarei a você com prazer.",
"Acordado. Tais delitos devem ser punidos.",
"Você poderia fazer isso - pelo preço baixo de 10.000 peças de ouro.",
"Que tal 5.000?",
"É um acordo.",
"Sem chance. Não perca mais meu tempo - vou embora em breve.",
"Você vai se arrepender de sua tolice!",
"Ah, você gosta de pechinchar? Eu também! 9.000.",
"6000.",
"Está bem! Aqui está o dinheiro.",
"Sem chance. Não perca mais meu tempo - vou embora em breve.",
"Como quiser.",
"Você está tentando me roubar! 8.000 é minha oferta final.",
"Isso é mais do que gostaria de gastar.",
"Tudo bem. Aqui está o seu ouro.",
"Sem chance. Não perca mais meu tempo - vou embora em breve.",
"Justo.",
"Então saia daqui e não me incomode mais! Preciso descansar um pouco antes de navegar.",
"Talvez eu te veja novamente.",
"Espero que você possa lucrar com esta barganha.",
"Isso é problema meu, não seu.",
"Você sabe meu nome, não é? Tudo bem, explique para mim. O que você precisa?",
"Preciso dos papéis que você roubou da igreja #sIsla Muelle#.",
"Então aquela velha raposa ",
"Padre Domingues",
" enviei a você.",
"Não importa quem me enviou. Eu quero esses papéis.",
"Digamos que eu realmente saiba do que você está falando, por que eu daria isso a você? Você ao menos sabe o que há nesses papéis?",
"Não. Só sei que preciso deles.",
"Então o velho hipócrita nem contou sua missão #sboy# como aqueles papéis o desacreditam? Eu sabia que ele ficaria inquieto quando soubesse que a prova do empréstimo de dinheiro havia caído em minhas mãos.",
"Se você sabe o que dizem esses jornais, então suponho que a natureza da nossa conversa terá que mudar.",
"Vamos fazer assim: eu compro os papéis de você.",
"O que você quer dizer?",
"Você deve ter ouvido falar de mim, eu sou ",
".",
"Oh Deus! Claro que já ouvi falar do vira-lata mais sanguinário destas águas!",
" Eu vou te perdoar por me chamar de 'vira-lata' uma vez. Diga de novo e você perderá a língua.",
"Me perdoe! Simplesmente escapou. Por favor - eu não quis dizer isso!",
"Apenas cale a boca e me dê os papéis. Tenho uma ideia de como usá-los.",
"Mas... eu ia...",
"Você disse alguma coisa?!",
"Não não! Nada. Aqui, é só pegar!",
"Adeus.",
"Você poderia fazer isso - pelo preço baixo de 10.000 peças de ouro.",
"Que tal 5.000?",
"É um acordo.",
"Isso é roubo!",
"Eu não estou interessado nisso. Você deveria ir.",
"Bem, já que você percebe o valor desses papéis, suponho que nossa conversa terá que tomar um novo rumo.",
"Você vai se arrepender disso.",
"Eu duvido disso. Olha, se você não quer pagar, então vá embora.",
"Certo. Mas um dia você desejará ter sido mais cooperativo.",
"Gosto do seu estilo, amigo! Que tal 9.000?",
"Acho que 6000 soa melhor.",
"OK. Aqui está o seu dinheiro.",
"Não, isso não vai funcionar. Agora saia e deixe-me cuidar dos meus negócios. Em breve zarparei.",
"Como quiser. Mas você vai se arrepender disso. Breve.",
"Você está tentando me roubar! 8.000, e nem uma moeda a menos.",
"Não. Isso é demais para mim.",
"De acordo. Aqui está o dinheiro.",
"Não, isso não serve. Agora saia e deixe-me cuidar dos meus negócios. Em breve zarparei.",
"Justo. Vejo você mais tarde, e talvez eu tenha vantagem.",
"Então saia daqui e não me incomode mais! Preciso descansar um pouco antes de navegar.",
"Você sabe, não é sensato me decepcionar",
"Isso é uma ameaça?",
"É um fato. Se você não quer que este seja o último dia da sua vida, você entregará esses papéis.",
"Espere um minuto. Eu te reconheço agora - você é quem trabalha para o governador inglês!",
"Isso mesmo. Agora você entende o quão sério eu estou falando?",
"Acho que vou arriscar. Agora saia da minha frente!",
"Eu te avisei.",
"Tudo bem, tudo bem! Leve os papéis - embora eu não tenha ideia de por que seu chefe os desejaria. Pegue-os e vá.",
"Agora estamos a falar!",
"",
};
