string DLG_TEXT[12] = {
"Bom dia, jovem #sgender#!",
"Bom dia. Disseram-me que você sabe muito sobre um navio chamado 'Pérola Negra'.",
"Na verdade, sim. Tive a sorte de servir naquele excelente navio. Mas isso foi há muitos anos e não terminou bem. Na verdade, algo aconteceu durante meu tempo no 'Pérola Negra' que me tirou do mar\n e me levou à vida tranquila que vivo hoje.",
"O que aconteceu?",
"Bem, o 'Pérola Negra' sempre foi um navio pirata. Eu não vou negar isso. Era uma vez, nossa tripulação teve muita sorte. Nosso porão estava sempre cheio de saques\nTanto ouro que gastamos sem pensar duas vezes. Mas entre todas aquelas moedas de ouro estavam algumas das maiores e mais bonitas que você poderia esperar ver. É claro que nós também os gastamos, mal olhando duas vezes para eles. Mas hoje acho que havia muito sangue naquele ouro. E uma verdadeira maldição.",
"...",
"Um por um, isso nos colocou um contra o outro. Logo houve duelos... e assassinatos. Os melhores de nós foram mortos, e eu e vários outros fomos deixados em uma ilha para morrer. De alguma forma, sobrevivemos, mas outros foram condenados pela maldição. Eles se tornaram mortos-vivos. Você pode até rir, #slad#, mas é verdade! De dia, parecem homens, mas o luar revela a sua verdadeira natureza. Esqueletos vivos, eles são! Nem bala nem lâmina podem matá-los! Eles podem orar pela morte. Eu acho que é provável que sim. Mas os seus pecados e a maldição não os deixarão sair deste mundo.",
"Eu acredito em você. Foi exatamente quem eu conheci.",
"Então você tem muita sorte de ainda estar respirando. A única maneira de esses demônios descansarem em paz é recuperar aquelas moedas amaldiçoadas. Isso é quase impossível agora: as moedas serão espalhadas por todo o arquipélago.\n Mas nada impedirá esses esqueletos piratas de tentar.\n E se você adquirir algum desse ouro, eles irão persegui-lo até colocarem as mãos ossudas nele. isto.",
"Essa é uma história incrível.",
"É tudo verdade. Eu já vi o inferno, eu lhe digo. E desde então nunca mais saquei uma arma. Há muito que cansei de velejar e roubar. Hoje sou um homem piedoso. Vou à igreja regularmente. Eu li minha Bíblia. E eu aconselho você a fazer o mesmo, #slad#!",
"Obrigado pelo conselho. Mas temo que seja muito cedo para levar uma vida tranquila. Boa sorte para você.",
"",
};
