string DLG_TEXT[15] = {
"Não se mova! Quem é você?",
"Somos amigos do Capitão ",
"Rabel Iverneau",
"...",
"Ou talvez vocês sejam aqueles espiões ingleses que procuramos...",
"De jeito nenhum! Garanto a você, somos amigos de ",
"Rabel Iverneau",
". Ele está bem aqui. Viu?",
"Bem, sim. Você nos pegou. Somos espiões. O capitão nos prendeu e agora está nos levando ao seu navio para interrogatório.",
"O que o capitão tem a ver com essa turba?",
"Ora, ele é um homem caridoso. Muito mais do que você, ao que parece.",
"É assim mesmo? Então por que você está armado? Algo está errado aqui. Vamos mantê-lo preso até o cavalheiro coronel chegar!",
"Mas...",
"Por que você está me contando essas mentiras?! Saia daqui!",
"Ótimo. Adeus!",
"",
};
