string DLG_TEXT[115] = { 
"É melhor você parar de conversa e começar a trabalhar, amigo. Os guardas estão nos observando - você quer levar o chicote?",
"Você tem razão. Vou precisar da minha energia para a fuga.",
"Desculpe?",
"Nada. Deixa para lá.",
"Ei! Você está acordado, não é? Então comece a trabalhar! Esses condutores de escravos não gostam de ver alguém vadiando.",
"Como eu cheguei aqui?",
"Você não demorou muito para sair do buraco, não é? Não faz muito tempo, você era apenas um trabalhador como eu. Agora você é um mestre",
"Eu não quero discutir com você. Eu só preciso de algumas respostas.",
"Você já voltou? Você conseguiu conquistar minha liberdade?",
"Sim, você está livre agora. Mas gostaria que você respondesse algumas das minhas perguntas antes de ir.",
"O que você quer? Eu te contei tudo que sabia.",
"Prometi libertá-lo assim que respondesse a todas as minhas perguntas e mantive minha palavra. Você está livre agora.",
"Você conseguiu conquistar minha liberdade?",
"Ainda não. Ainda estou trabalhando nisso.",
"Não, desculpe. Eles pediram muito dinheiro para você. Acho que terei que encontrar outra maneira de fazer você responder às minhas perguntas.",
"Olá, capitão. Você decidiu me contratar?",
"É por isso que estou aqui neste pântano. Estou feliz que você ainda não encontrou um emprego.",
"Não. Estou tratando de outros negócios.",
"Ouvi você conversando com um oficial. Você é realmente um capitão?",
"Nenhum de seus negócios.",
"É hora de ir. Aqui, pegue sua espada - e que Deus esteja conosco!",
"Vamos nos encontrar na entrada.",
"Conseguimos! Agora só falta sair da ilha.",
"Não vamos ficar aqui muito tempo. Suba a bordo antes que eles persigam!",
"Desculpe, mas estou indo sozinho agora. Eu não preciso de você.",
"Quem é você e por que me distrai do meu trabalho? É melhor você ter cuidado - esses condutores de escravos não gostam disso.",
"Preciso te fazer uma pergunta sobre algumas placas de argila que foram encontradas nessas minas.",
"Você quer saber sobre aquele rapaz que estava estudando as placas, não é?",
"Sim está certo.",
"Quem é você?",
"Você poderia dizer onde eles guardam os comprimidos indianos?",
"Aquele rapaz copiou os símbolos das placas em pergaminho. Então ele partiu. \nEle estava falando sobre visitar #sIsla Muelle# para estudar os símbolos em profundidade e traduzi-los.",
"Obrigado pela informação.",
"Por que devo responder às suas perguntas?",
"Se você responder de forma satisfatória, vou tirar você daqui.",
"Porque se não o fizer, ordenarei aos soldados que façam você desejar ter feito isso. Você não preferiria uma pequena conversa a uma surra?",
"Ah, seu canalha!",
"Você quer lutar, não é? Fico feliz em atender!",
"Deixe-me colocar desta forma: você quer sair daqui ou não?",
"O que? Você pode me tirar daqui?",
"Isto é uma mina, não uma prisão. Fugir daqui não é um problema. O truque é sair da ilha.",
"Acontece que meu navio está ancorado perto da ilha - então isso também não é um problema.",
"Excelente! Você pode cercar?",
"Que tipo de capitão eu seria se não soubesse esgrimir?",
"É verdade. Então aqui está o plano: um recente deslizamento de terra enterrou dezenas de trabalhadores e quatro soldados.",
"Você conseguiu desenterrar as armas deles?",
"Sim nós fizemos. Agora, ouça, posso enviar mensagens da prisão. Precisaremos que seu navio esteja nos esperando perto do farol.",
"Feito. Leve esta carta aos meus oficiais. Eles terão certeza de que o navio está lá.",
"Temos várias horas antes de podermos fazer a nossa pausa. Descanse um pouco.",
"Espere! Você já ouviu alguma coisa sobre algumas tábuas de barro com símbolos estranhos? Eles seriam mantidos em algum lugar por aqui.",
"Foram eles que te trouxeram aqui? Por que todos estão tão interessados neles?",
"O que você quer dizer com 'todos'?",
"Outro homem veio aqui há alguns meses e fez uma cópia daquelas placas. E há poucos dias, uma senhora veio perguntar por eles também.",
"Interessante... mas você não respondeu à minha pergunta. Eles ainda estão aqui?",
"O que sobrou deles, sim. Eles foram quase completamente destruídos pelo deslizamento de terra.",
"De toda a sorte! E o homem que fez cópias deles em pergaminho? Você sabe para onde ele foi?",
"Ele disse algo sobre a colônia espanhola. Isso é tudo que eu sei.",
"Tudo bem. Descanse um pouco e esteja pronto para se mover quando chegar a hora.",
"O que você quer saber?",
"Não use esse tom comigo. Não tenho culpa de você estar nessas minas",
"Não, a culpa é de outro pirata. Um diabo chamado ",
"Ethilrede Claar",
"Ethilrede Claar",
", que afundou meu navio e me vendeu como escravo.",
"Então você era capitão?",
"Bem, você não é capitão agora. Você é meu escravo, e tudo que quero de você são respostas.",
"Eu estava, sim. Comandei um navio mercante chamado 'Arethuse' até chegar aqui.",
"Ouça, vamos fazer um acordo. Você responde minhas perguntas e eu te tiro daqui.",
"Fascinante. Agora, você já mexeu a língua o suficiente - responda às minhas perguntas.",
"Tenho uma ideia melhor. Você me tira daqui e então responderei às suas perguntas.",
"Você tem um acordo. Espere por mim aqui.",
"O que? Talvez você tenha esquecido quem é o escravo aqui. Eu estabelecerei os termos. Você pode responder minhas perguntas ou pode ficar aqui na mina.",
"Cara durão, não é?",
"Agora estamos a falar.",
"Então, no que você está interessado?",
"Dizem que você ajudou um sujeito que veio aqui estudar algumas tábuas de argila que foram encontradas nas minas.",
"Sim eu fiz. Um jovem - ele veio aqui, fez cópias das placas em pergaminho e foi embora.",
"Suponho que você não saiba para onde ele foi.",
"Bem, ele disse algo sobre a colônia espanhola.",
"Excelente. Talvez eu tenha uma chance de encontrá-lo.",
"Talvez você queira, e talvez não.",
"O que quer dizer com isso?",
"Bem, há poucos dias, uma jovem esperta esteve aqui perguntando sobre o mesmo jovem. Contei tudo o que ela queria saber - ela era muito mais bonita que você! Então ela pode encontrá-lo primeiro.",
"Bem, veremos sobre isso.",
"Espere! Agora que sou um homem livre, gostaria de lhe fazer uma pergunta, para variar!",
"O que é?",
"Eu te disse que era capitão de um navio mercante, não foi?",
"Deixe-me adivinhar - você gostaria de se juntar à minha equipe?",
"Esse é mais ou menos isso.",
"Não é uma má ideia. Estou sempre à procura de marinheiros com uma boa cabeça sobre os ombros.",
"Não acho que seja uma boa ideia.",
"Ótimo! Ficaria honrado em navegar sob a sua bandeira.",
"Não vamos apressar as coisas. Há o seu salário para discutir primeiro.",
"Eu acho que 1.500 de ouro devem servir.",
"Não é um salário ruim para um ex-capitão mercante. Você tem um acordo.",
"Acho que não posso concordar com esses termos.",
"Tudo bem, capitão! Diga-me o nome do seu navio e nos encontraremos lá.",
"Tudo bem. Meu navio é o '",
"'.",
"É uma pena. Bem, estarei procurando trabalho em #sFalaise de Fleur# se você mudar de idéia.",
"Multar. Vou manter isso em mente.",
"Ouvi dizer que traficantes de escravos trouxeram você para cá. Eles se gabaram de ter dado um tapa forte na sua cabeça.",
"E a minha tripulação?",
"Parece que eles conseguiram escapar da captura.",
"Ótimo. Eles estarão aqui para me libertar em breve.",
"Eu não contaria com isso.",
"Talvez você esteja certo. Vou tentar encontrar uma maneira de sair daqui.",
"Então você não conhece minha tripulação. Eles fariam qualquer coisa por mim!",
"Tudo bem - volte ao trabalho! Um guarda está chegando!",
"Então? Onde você quer chegar?",
"...",
"...",
"Um homem veio aqui há alguns meses e fez uma cópia daquelas placas. E há poucos dias, outro homem veio perguntar por eles também.",
"Bem, há poucos dias, um jovem esperto estava aqui perguntando sobre o mesmo sujeito. Contei a ele tudo o que ele queria saber - ele foi muito mais persuasivo que você! Então ele pode encontrar o homem que copiou as placas primeiro.",
"Garota durona, não é?",
};
