string DLG_TEXT[29] = {
"Você não vê outra pessoa com quem possa beber?",
"Você é ",
"?",
"...Sim. Como posso ajudá-lo?",
"Counterspy",
" não poderá vir à taberna.",
"O que? Por que? Quem é você?",
"Eu sou ",
". Trago uma mensagem de ",
"Counterspy",
".",
" Isso não fazia parte do plano. Ele mudou o acordo? Ordenarei sua prisão imediatamente!",
"Não, ele naõ mudou o acordo, tivemos problemas e ele pode ser reconhecido pelos guardas. Tivemos que mudar o local da reunião.",
"Isso é terrível. Isso pode ser uma armadilha! Por que me envolvi com ele?",
"Parece que você está perdendo a coragem.",
"Não! Oh não! Por favor, diga. Que mensagem fez ",
"Counterspy",
" tem para mim?",
"Que ele está pronto e esperando por você atrás da taverna. Perto da muralha da cidade.",
"Por que ele não veio aqui?",
"Há soldados franceses por toda parte.",
"Entendo... Então, suponho que você queira que eu o ajude a sair da cidade.",
"Sim. Quanto antes melhor.",
"O que estamos esperando. Vamos.",
"Vamos vamos.",
"Corra para o navio! Se apresse!",
"Estamos em apuros!",
"Vamos para o navio e partiremos o mais rápido que pudermos. Se o vento for verdadeiro, ninguém deveria ser capaz de nos pegar!",
"Eu gostaria de ter sua confiança.",
"",
};
