string DLG_TEXT[32] = {
"Se você me der licença ",
".",
"Claro.",
"Se você não se importa, estou ocupado agora. Por favor, deixe-me aproveitar minha refeição e então você poderá fazer suas perguntas.",
"...",
"O que vocês, jovens, querem?",
"Você é ",
"?",
"Então, sobre o que vamos conversar? Quem é aquele?!",
"Quem?! Onde?!",
"Tosse, aquele vira-lata finalmente me pegou.",
"Governador Silehard?",
"E o seu bando de bandidos.",
"Por favor, fique quieto e poupe o fôlego. Seus ferimentos são muito sérios... não acho que você conseguirá chegar ao meu navio.",
"Eu sei, #sperson#, eu sei. Tosse, tosse... Você sabe por que ",
"Robert Christopher Silehard",
" queria que eu morresse?",
"Sim, o tesouro inca.",
"De fato. Ele deseja isso desde que ouviu falar. Eu imploro - leve-o bem debaixo do nariz dele. Isso será uma vingança justa pela minha morte... tosse-tosse.",
"Sim, e cuidarei do governador também. Disso você pode ter certeza. Ele enviou seus assassinos atrás de mim desde que soube do tesouro.",
"Não. Não o mate, minha #sperson#. Ele é muito poderoso e muito bem protegido. E é muito mais importante que você guarde o tesouro.",
"Por que?",
"Há muito mais neste tesouro do que parece. A informação que ",
"Robert Christopher Silehard",
" tem não está completo. Só recentemente descobri isso sozinho, mas há muito, muito mais.\nEm minha busca inicial pelo tesouro, encontrei uma lenda que descrevia como encontrar esses artefatos.\nInfelizmente, era uma transcrição incompleta do #sIsla Muelle#.\nTenho certeza que lá você poderá encontrar uma versão completa. E há mais uma coisa. \nEncontre o ídolo Khirucatceliti e ele abrirá a porta...",
"Adeus. Descanse em paz.",
"Sim? Mas quem é você e o que você precisa de mim?",
"Calma, só precisamos conversar com você ",
"Posso dizer pela cara de vocês que nossa conversa não será agradável, mas acho que não tenho escolha.\nVamos para minha casa fora da cidade e conversar lá.",
"Nem pense em tentar escapar!",
"Eu não vou.",
"Tudo bem, então vamos.",
"",
};
