string DLG_TEXT[49] = {
"Por favor, deixe-me só. Estou me divertindo aqui!",
"Eu acabei de...",
"Você é surdo? Eu disse me deixe em paz. Saia agora ou chamarei os soldados para pregar você na porta da taverna!",
"Ei!",
"O que você quer?",
"Meu nome é ",
".",
"Eu não me importo qual é o seu nome. Você está me incomodando. Você precisa de algo? Se não, vá embora.",
"Eu... eu quero trabalhar a bordo de um navio!",
"Pareço um intendente?! Vá para a doca e fale com os homens de lá. Não tenho nada a ver com a turba comum. Agora vá em frente, estou me divertindo aqui!",
"Não, espere! Não estou interessado em me tornar um marinheiro. É por isso que vim até você, capitão.",
"Eu vejo. Bem, que posição você quer?",
"Bem, muitos disseram que sou um excelente navegador.",
"Você não diz? Bem, por que você não disse isso? Isso é uma sorte! Meu navegador foi morto durante o ataque a #sOxbay# e estou procurando um substituto. \nE se você me pagar uma bebida, você estará praticamente contratado!",
"(Para o taverneiro)...Mais uma rodada!",
"E o navegador deve manter mapas precisos de todas as nossas rotas...",
"Com licença, mas podemos discutir os detalhes da postagem mais tarde? Por enquanto talvez você possa me ajudar a comemorar e me contar sobre seu navio?",
"Uma grande ideia! Para o seu novo emprego! Soluço...mais rum! Amanhã de manhã vá ao porto e peça o '",
"'.",
"Então, quando vamos embarcar?",
"Para o mar? Ah...Quando aquele barco com...soluço...munições chegar. Mas cuidado com a língua sobre isso! Ninguém deveria saber sobre aquele navio!",
"Sim, certamente senhor!",
"Agora estamos a falar! Traga-me mais uma caneca de rum! Soluço...Tudo bem, é hora de ir para o navio...Que desperdício de cidade, não tem um único bordel!",
"Senhor! Vamos tomar mais uma bebida e...",
"E o que? ...À sua saúde, navegador! E-então, o que você...soluço...quer dizer?",
"Só que vou sentir falta da minha tia. Ela mora perto, não muito longe da muralha da cidade...",
"Eu vejo. V-você quer se despedir dela... soluço? Você terá que esquecer isso! Acompanhe-me até o navio!",
"E sentirei muita falta de suas filhas. Com certeza elas serão ótimas jovens depois de todo esse tempo.",
"Espere. Er. Talvez você devesse fazer uma visita a eles... Soluço... Sim... soluço... V-vamos agora mesmo!",
"Sim senhor!",
"Soluço! Fora do caminho! Meu amigo e...soluço...vou fazer uma visita às se-senhoras!",
"Conforme mencionei, certo?",
"O que você está esperando? Vamos!",
"Estou chegando!",
"E-espere. Onde estamos indo? Vejo apenas selva aqui!",
"Você tem razão. Vamos parar por aqui.",
"Por que?",
"Então você pode me contar tudo o que sabe sobre o navio que transporta essas munições.",
"O que? Você não é um navegador, é? Você é um espião inglês!",
"Você pega rápido.",
"...Ultrajante! Enganador! Você não aprenderá nada comigo e garantirei que não conte a ninguém. Prepare-se para lutar, covarde!",
"Capitão, contenha-se. Você mal consegue ficar de pé, quanto mais lutar.",
"...E-escute! Você me embebedou de propósito!",
"Conte-me tudo e eu pouparei você. Minta para mim e terei que extrair as informações de você por outros meios.",
"...Sim Sim. Eu vou te dizer. Uma barca chamada 'Oiseau' está programada para trazer armas novas para esta ilha, para que possamos proteger toda a ilha. Ouvi dizer que está no porto de #sFalaise de Fleur#.\nO capitão do Oiseau está esperando no cais por sua escolta.",
"A barca permanecerá no porto até a chegada da escolta?",
"Sim. Acredito que sim... Isso é tudo que sei...",
"Você me disse o que eu preciso saber. Você pode ir.",
"Obrigado pela informação capitão, agora receio que tenho que te matar.",
"",
};
