string DLG_TEXT[28] = {
"Bem, olha quem eu vejo! ",
"!!",
"Me desculpe, eu te conheço?",
"Então, você completou sua tarefa?",
"Sim, ele não vai mais te incomodar.",
"Perfeito!",
"Se precisar de mais alguma coisa, ficarei feliz em ajudar.",
"Tudo bem, eu me lembro de você. Você é o capitão que conseguiu escapar quando os franceses capturaram #sOxbay#!",
"Sim. Mas como você sabia?",
"Um passarinho me contou.",
"Eu vejo. Bem, se você me der licença...",
"Espere, por favor. A julgar pelo seu tom, você já viu dias melhores. Talvez eu possa ajudá-lo?",
"Depende. Por que você me ajudaria?",
"Adoraria acreditar que nestes tempos modernos todas as pessoas deveriam ser amigas, dar-se bem, ter boas maneiras e não recorrer à violência para resolver os seus problemas. Infelizmente, este não é o caso. Preciso de ação e quero que você me ajude.",
"E o que eu teria que fazer?",
"Há um sujeito que atrapalha meus negócios.",
"E você quer se livrar dele? Por que você não faz isso então?",
"Eu gostaria, mas ele mora em #sIsla Muelle#. Sou bem conhecido lá e seria reconhecido.",
"Vamos supor que estou disposto. Qual será a recompensa?",
"Para ser sincero, não tenho muito dinheiro para oferecer. Todas as minhas economias em outro lugar, mantidas por uma pessoa em quem confio, mas...",
"Mas o que?",
"Eu tenho um navio excelente que posso lhe dar.",
"Hmm... parece tentador. Acho que você tem um acordo.",
"Ótimo! Então eu te darei o navio e você cuidará disso ",
"Sidonio Ogarrio",
"Sidonio Ogarrio",
" em #sIsla Muelle#. Ele mora em uma pequena praça atrás da taverna.",
"Tudo bem. Aceito.",
"",
};
