string DLG_TEXT[56] = {
"Você é ",
"?",
"Sim...",
"Eu sou ",
". Eu estive esperando por você. Estou aqui para informar onde ancorar seu navio.",
"Não haverá ancoragem. O transporte está no fundo do mar...",
"Ah, o governador mencionou que haveria alguém aqui para me encontrar. Seria você?",
"Eu acho que sim, ",
". Disseram-me para encontrar um capitão inglês chamado ",
" e para mostrar ao #spronoun2# onde ancorar. \nAssim que a localização for revelada, devo encontrar esse capitão na costa do local de desembarque e levar #spronoun2# a uma caverna.",
"Estou curioso - por que os soldados não podem entrar na caverna daqui?",
"O sigilo mantém o elemento surpresa do nosso lado. Os franceses têm espiões em #sGreenford#. Se partirmos daqui para a caverna, os franceses descobrirão o que estamos fazendo. \nPodemos ser arrastados para uma batalha e, se os franceses vencerem, eles podem decidir tomar #sGreenford# também.",
"Hmm... acho que você está certo. Então, quando e onde podemos desembarcar os soldados?",
"Há uma praia deserta chamada Gray Rock Bay ",
". É o melhor lugar para fazer isso.",
"Como chegamos lá?",
"Siga para norõeste ao sair da baía e depois siga para o sul ao redor da ilha. Você verá uma enorme rocha cinzenta separada da ilha pelo canal. \nHá uma grande baía logo atrás da rocha. Solte a âncora aí ",
".",
"Você vai nos esperar lá?",
"Sim, ",
". Esperarei por você na praia todas as noites. O desembarque deverá ocorrer à noite para evitar navios franceses nas proximidades. Vou sinalizar com uma tocha para marcar o local para lançar âncora.",
"Tudo bem, uma noite destas desembarcaremos.",
"Excelente, ",
". Te espero lá. Tome cuidado. Ninguém deve saber do nosso plano.",
"Boa sorte, ",
".",
"Você deveria escoltá-lo! Por que você deixou afundar?",
"Estávamos em menor número.",
"Oh não! Tudo está perdido! O que devemos fazer agora?",
"Navegue, tenho trabalho a fazer!",
"Algo mais, ",
"? Já discutimos tudo?",
"Sim, terminamos. Até a próxima, ",
".",
"Oh não, ",
", isso é terrível! Os franceses devem ter notado a luz da minha tocha. Isso é horrível!",
"Qual é o problema? O que está errado?",
"Uma patrulha francesa está chegando!",
"Bem, estou sempre pronto para uma luta!",
"Excelente! Que luta! Tem certeza de que todos os soldados franceses foram contabilizados?",
"Não vi nenhuma tentativa de fuga.",
"Ótimo, porque se os franceses souberem do que aconteceu aqui, começarão a vasculhar a selva. \nE se eles encontrarem a caverna? Teremos que lutar.",
"Vejo que você não gosta muito de brandir sua espada.",
"Não peço desculpas ",
". Sou um artesão, não um soldado. Agora, não vamos nos distrair da nossa tarefa.",
"Então o que vem depois?",
"Quando os soldados estiverem em terra, eu os levarei para a caverna ",
". Não há necessidade de você passear pela selva conosco. Conheço muito bem o caminho.",
"Ótimo! Mal posso esperar até ir para o mar",
"Tenha uma boa viagem ",
". E bons ventos.",
"Até a próxima.",
"Estou feliz em vê-lo, capitão! Onde está o transporte?",
"Afundou no caminho para cá... fiz tudo que pude...",
"Não! Tudo está perdido! Precisamos sair daqui, antes que os franceses cheguem.",
"Espere...",
"",
};
 