string DLG_TEXT[24] = { 
"Estou com fome - preciso de proteína.",
"(Melhor ficar fora do caminho)",
"O que você quer?",
"Sr. Pym, estou procurando ferramentas de navegação. Eu tenho esse lindo relógio...",
"Bem... que tal me fazer um favor?",
"Claro, o que você tem em mente, Sr. Pym?",
"A questão é que o alfaiate estúpido saiu de férias e me trancou do lado de fora.",
"E você quer que eu freie?",
"Não, a porta do Alfaiate é impossível, mas há outro caminho para entrar nos meus aposentos.",
"Sim?",
"Quando eu era mais jovem, às vezes subia nos telhados, só por diversão.",
"Que item você troca por uma escalada perigosa como essa, Sr. Pym?",
"Eu tenho um Sextante se você estiver interessado.",
"Tudo bem, mostre-me onde começo a escalada.",
"Costumava haver uma escada no prédio em frente ao escritório daquele detetive.",
"Senhor Dupin, isso é fácil de encontrar. Já estou a caminho...",
"Finalmente, estou morrendo de fome - eu poderia comer um cavalo.",
"(Espero que ele cumpra isso) E quanto ao nosso acordo? Ei senhor...",
"O sextante está na Sala da Torre.",
"OK. (Onde fica isso?)",
"Não tão rápido, senhor, você vai precisar da minha chave reserva do Alfaiate.",
"E onde você guarda essa chave?",
"Está no meu quarto.",
"Ok, até mais tarde então.",
"",
"",
"",
"",
};
