string DLG_TEXT[50] = {
"Bonjour Monsieur, o que posso fazer por você.",
"Como vai você, ehh ahh nada no momento",
"O Sr. Poe recomendou-o para uma investigação privada.",
"Ah, sim, ele é um amigo próximo meu. Agora, por favor, Monsieur, conte-me mais sobre o assunto.",
"Tenho aqui uma cifra que eu, com a ajuda do senhor Poe, resolvi apenas na metade...",
"Cifra, eh...? Quanto você está disposto a pagar, senhor...",
"Legrand. Pague - bem, hrmpff...",
"Talvez você possa me fazer um favor, Monsieur Legrand?",
"O que pode ser isso, senhor Dupin?",
"Eu tenho este kit de investigação de detetive que você vê. Muito útil, devo dizer. De alguma forma, os seis itens foram espalhados e também não consigo encontrar a chave.",
"Tudo bem, senhor Dupin, tentarei ajudá-lo com isso se você estudar este artigo com atenção.",
"Ahh, você encontrou tudo que eu acho...",
"Ah, sim, não há problema e encontrei algumas chaves também. Aqui está você, senhor Dupin. E a cifra, você conseguiu fazer algum avanço?",
"Ah, tudo bem, claro, mas acho que você mesmo poderia preencher uma carta para começar.",
"(gole) Sim, qual?",
"Referindo-nos agora ao início da criptografia, encontramos '5' antes da palavra 'BOM' o que nos garante que a primeira letra é outra palavra e que '5' é...?",
"As únicas duas palavras com apenas uma letra são 'I' e 'A' e aqui é um 'A', sem dúvida!",
"Claro. Quatro letras além da palavra 'graus', percebemos a combinação ;46(;88* . Traduzindo os caracteres conhecidos, e representando o desconhecido por pontos, como antes, lemos assim: 'TH.RTEE.'",
"Parece a palavra 'TREZE' para mim. ",
"Concordo! Talvez fosse mais fácil se você continuasse no papel quadriculado!",
"Ok, vou ver o que posso fazer.",
"Monsieur Legrand, deixe-me ouvir, você descobriu qual deve ser a letra '0'?",
"Bem, eu... não tenho certeza...",
"Talvez você devesse tentar novamente. Não se esqueça de verificar o Questbook.",
"Verei o que posso fazer...",
"Sim, é 'B'",
"Sim, é 'C'",
"Sim, é 'F'",
"Sim, é 'J'",
"Sim, é 'K'",
"Sim, é 'L'",
"Sim, é 'M'",
"Sim, é 'P'",
"Sim, é 'Q'",
"Sim, é 'V'",
"Sim, é 'W'",
"Sim, é 'X'",
"Sim, é 'Y'",
"Sim, é 'Z'",
"Excelente, e o que você descobriu sobre '9'?",
"Sim, dá a palavra 'MINUTOS'. Agora olhe para esta sequência 'LINE.ROMTHETREETHROUHGTHESHOT",
"Não pode ser nada além de 'F' . Então '1' é 'F', não resta muito agora...",
"Não, está quase pronto. Olhe no final do texto, 'FIFT.FEETOUT' você vê o que ':' significa?",
"Por favor, Monsieur Legrand, preencha o Kit e feche-o.",
"Sim, acho que você está certo. Agora você pode preencher facilmente as letras restantes. Só mais uma dica, verifique este lugar 'SE.ENTH'.",
"Tudo bem e obrigado por toda sua ajuda, senhor Dupin.",
"Muito obrigado. Mas agora você terá que me desculpar - tenho clientes esperando...",
"Adeus então. Vou ver se o senhor Poe já voltou.",
"Ah, não foi nada. Aqui está sua cópia da mensagem secreta. Ehhr... Monsieur Legrand, você se importa se eu guardar o pergaminho que você encontrou na praia? Você vê, estou muito interessado nesse tipo de coisa.",
"Claro, por que não? Você tem sido de grande ajuda para mim. Por favor, pegue.",
"",
};
