string DLG_TEXT[38] = {
"Eu não ouço você - estou dormindo.",
"!!",
"Vá embora, você não pertence aqui",
"Olha, não sou ladrão, só quero fazer algumas perguntas.",
"Não, este NãO é o quartel feminino.",
"Hmm... Como ele sabia o que eu estava procurando?",
"Não somos escravos, somos pessoas -",
"- nossa condição é de escravo.",
"E quem é você, senhor?",
"Ah, William Legrand. Lamento incomodá-lo, só quero fazer algumas perguntas.",
"Vá em frente - pedir é grátis.",
"Você já ouviu falar de um lugar chamado Bishops Hostel?",
"Conheço um lugar chamado Castelo de Bessop.",
"Você pode me mostrar o caminho para aquele albergue ou castelo?",
"Você tem que pagar por isso, você sabe",
"Hmm, eu... eu...",
"Me dê aquela coisa que você usa no pescoço se não tem dinheiro.",
"(A bolsa de remédios!) Muito bem - aqui está.",
"Quando você vier da cidade - vire imediatamente à direita.",
"Hmm, pensei que era apenas um beco sem saída para o mar?",
"Não não. Antes do caminho para a água.",
"Tudo bem eu já entendi. E então?",
"Apenas continue, é um longo caminho. Depois da Ponte vire à esquerda sobre a falésia.",
"Vá em frente, estou ouvindo...",
"Agora você chegará a uma região excessivamente selvagem e desolada.",
"E aqui está o Hostel??",
"Na verdade não é um castelo, nem uma taberna, mas sim uma rocha alta.",
"E como posso encontrá-lo?",
"Hmm, é difícil descrever...",
"Talvez você pudesse fazer um esboço daquela rocha.",
"Não tenho papel nem caneta.",
"Não tem problema, tenho tinta aqui e - deixe-me ver - talvez eu possa usar o verso daquela imagem de pássaro...",
"Aqui, seu artigo. Agora, se você me der licença",
"Obrigado senhorita...",
"Ohh, eles estão atrás de você, senhor?",
"Na verdade eles são, desculpe, preciso me apressar agora...",
"Esqueça meu nome... Aqui, pegue isso - você está sangrando, senhor.",
"Bem, obrigado M.. ehrrm... Adeus.",
"",
};
