string DLG_TEXT[429] = {
"Ah é você, ",
". O que você está fazendo aqui?",
"Nenhum de seus negócios ",
". E eu poderia fazer a mesma pergunta - mas estou muito ocupado para isso.\nEntão encontre um lugar para sentar e me deixe em paz.",
"Eu não esperava ver você aqui!",
"Fico feliz em ver você também ",
". Disseram-me que hoje em dia você gasta seu tempo livre salvando pessoas idosas.",
"Agora é minha vez de interrompê-lo. Onde você encontrou um rapaz tão útil ",
"?",
"Esse é o meu segredo ",
". Mas você ouviu o que ele tinha a dizer. Então agora podemos trabalhar juntos, como ofereci antes.",
"Fico feliz em ver que você esperou por mim. Agora podemos ir juntos.",
"Claro. Assim que ",
"Vicente Bethune",
" aqui nos diz para onde estamos indo.",
"É uma emboscada! Vá para a casa dele e tranque-se.\nVou segurá-los o máximo que puder.",
"Cuide-se!",
"O que esta acontecendo aqui?!",
"Ah. ",
"Vicente Bethune",
" me contou sobre você. Você é ",
"Robert Christopher Silehard",
"garoto de recados!",
"Finalmente acordado, não é?",
"O que aconteceu?",
"Chegou a hora de fazer uma visita ao governador e fazer-lhe algumas perguntas pontuais.",
"Estou certo com você. Vamos.",
"Ótimo, mas não podemos invadir a residência em plena luz do dia. Vamos esperar na taberna até a noite cair",
"Pensamento inteligente. E eu poderia tomar uma bebida.",
"Olha, quanto mais cedo obtivermos algumas respostas do governador, mais cedo poderemos confiar uns nos outros novamente.",
"Sim. Suponho que você esteja certo.",
"Em primeiro lugar, vamos sair desta cidade.",
"Acordado.",
"Devíamos nos separar aqui. Podemos ter mais problemas assim.\nVocê rastreia aquele rapaz que copiou a lenda e eu irei atrás do ídolo.",
"Isso funciona para mim. Podemos nos encontrar no farol, onde mora o velho.",
"??? O que você está fazendo aqui?!",
"Eu estava procurando por você! Como pude ser tão estúpido?!",
"Bem, veja o que a maré trouxe. Pensei que tínhamos combinado de nos encontrar no farol.",
"Cansei de esperar.",
"Bem, acho que você concordará que a espera valeu a pena. Encontrei um diário de bordo. Vamos ver, agora... espere... Caramba! Não há nada aqui sobre onde encontrá-lo! Espere - quieto! Juro que ouvi uma porta ranger. Alguém está vindo!",
"Então? Agora posso encontrar aquele corsário espanhol que supostamente sequestrou a garota.",
"Vá para o navio pirata.",
"Ainda não. Não é hora para isso.",
"Agora preciso procurar aquela garota. Se ela não estiver por aqui em algum lugar, estou em apuros.",
"...",
"Eu mal consegui escapar daqueles fanáticos! Este negócio está ficando mais quente do que eu pensava.",
"Eu deveria relatar isso ao Padre Domingues. Mas quem é esse?",
"Os sequestradores de Lucas exigiram que o resgate fosse trazido para esta taverna, mas eles próprios não parecem estar aqui.\nAha, aqueles dois no bar parecem estar esperando por alguém...",
"Não há necessidade de perder tempo. Eles provavelmente são os que eu preciso. (Mostre-lhes o sinal.)",
"Talvez eu devesse escutar um pouco a conversa deles primeiro? (Escutar a conversa.)",
"A sorte sorri para mim hoje. ",
"Pepino Bertillon",
"O navio está atracado, então seu capitão deve estar em algum lugar por perto. A única coisa que resta a fazer é encontrá-lo e fazer alguns buracos em seu peito.\nMas primeiro preciso ter certeza de que é ele que estou matando - os habitantes locais são um bando violento e um erro pode me causar um monte de problemas.",
"...",
"Não se preocupe com isso. Não acredito que você perca tempo, então...\nSuponho que você esteja aqui por causa de um rapaz chamado ",
"Raoul Rheims",
". Goste ou não, eu vou com você",
"Multar, ",
", você pode me acompanhar.",
"Quanto tempo devemos esperar?",
"Investigador",
" disse que poderia levar dias.",
"Já faz uma semana. Eu preciso de ação!",
"Estamos falando de centenas de quilos de ouro. Não vale a pena esperar uma semana?",
"Para você, talvez. Não aguento mais isso. Eu preciso estar em movimento. Por que ele não consegue terminar a tradução no navio?",
"Você sabe, eu nunca pensei nisso.",
"Sim, acho que um pirata não gosta muito de bom senso, não é? Então, que uso você tem para o ouro ",
"?",
"O que?",
"Devo falar mais devagar? O que. Vai. Você. Fazer. Com. Sua parte do tesouro?",
"Comprarei uma ilha inglesa, suponho, e estabelecerei minhas próprias regras. Ou talvez eu me torne um colega inglês. Isso poderia ter suas recompensas. E você?",
"Isso é segredo.",
"Tudo bem. Seja desse jeito.",
"Você vai se opor à frota regular?",
"Não. Vou quebrá-lo!",
"Eu comandarei o forte! Cuidado com o canhão!",
"Basta acertar o que você mira!",
"Nós ganhamos! Eles estarão escrevendo músicas sobre essa batalha, ou eu sou uma velha bruxa do mar! Poderíamos conquistar todo o arquipélago juntos! Ou todo o Caribe!",
"Claro que poderíamos. Mas pode fazer mais sentido conversar com ",
"Investigador",
" primeiro.",
"Ouvir você, ",
"! Você deveria ter vergonha de si mesmo, destruindo os sonhos de uma doce garota com sua lógica chata!",
"O tesouro sempre vem em primeiro lugar, minha querida. Depois, se você ainda quiser conquistar o Caribe, já estarei com você. Considere isso uma promessa.",
"Espero que o estudioso tenha tido tempo suficiente para examinar esses rabiscos. Duvido que possamos resistir a um segundo ataque.",
"Não tenho certeza se o governador tem mais navios de guerra.",
", o templo parece estar situado em algum lugar no interior. Vamos dar um passeio!",
"Certo, mas não queremos chamar atenção para nós mesmos. Devíamos deixar a tripulação aqui até verificarmos este templo com nossos próprios olhos.",
"Não acredito que conseguimos! É apenas uma questão de tempo até que estejamos rolando em ouro antigo!",
"Se houver algum ouro lá",
"Não diga isso! Não poderíamos ter chegado tão longe por nada!",
"Veremos.",
"Há três passagens aqui, e qualquer uma pode ser a correta. Para onde devemos ir?",
"Não sei. Esta poderia ser a armadilha ",
"Investigador",
" estava falando.",
"Então deveríamos nos separar. Cobriremos mais terreno dessa forma. Vou pegar a passagem da esquerda para mim e veremos quem encontra o tesouro primeiro!",
"Ei, espere...",
"Parece que podemos ir para #sisland_Khael Roa# agora!",
"Não tenho certeza se será tão fácil.",
"Talvez devêssemos ir em frente e revistar o templo enquanto ele lê aqueles rabiscos.",
"Não sem alguma ideia de para onde estamos indo! O próprio diabo poderia se perder naquele labirinto!",
"Faça do seu jeito, mas vou dar um passeio. Oh! Eu já vejo algo! Tenha em mente que encontrei primeiro!",
"O que?",
"Essa deve ser a alcova ",
"Investigador",
" estava falando. Mas onde está o tesouro?",
"Não sei. Mesmo que arrancássemos todo o ouro das paredes, não seria muito...",
"Não podemos perder muito mais tempo procurando ",
". Eles vão capturar a cidade!",
"Só quero ter certeza de que você não me afundará também, depois de cuidarmos da frota inglesa.",
"Agora, isso realmente dói ",
".",
"Brincando! Estou brincando. Boa sorte!",
"Bom Deus! O que é que foi isso?",
"Não sei!",
"Três mil demônios ",
"! Ninguém poderia sobreviver a isso! Meu tesouro! Poderíamos apenas tentar fazer parte disso? Só um pouquinho?",
"Não sei. Suponho que não seja o único tesouro do mundo.",
"Qual é a diferença? Oh, esta é uma perda tão amarga!",
"De alguma forma, tenho a sensação de que você não está tão desapontado quanto finge estar.",
"Eu não deveria voltar para lá. Preciso sair de #sRedmond# e rápido!",
"Essa foi difícil, não? Você ainda está inteiro?",
"Bem, acho que não vou morrer hoje, de qualquer maneira.",
"Fico feliz em ouvir isso - embora eu não tenha certeza se a Morte geralmente se importa com o que pessoas como nós pensam.",
"Vamos primavera ",
"Investigador",
" da prisão.",
", Uma coisa de cada vez. Vamos primeiro salvar o pobre velho",
"Qualquer coisa que você diga.",
"O que devemos fazer agora? Não poderemos encontrar o tesouro se não conseguirmos traduzir essa lenda. E temo que o velho...",
"Já nos opusemos ao #sGovernor# e à coroa inglesa. O que temos a perder se simplesmente capturarmos aquela cidade miserável e libertarmos Aurentius?",
"Não sabia que você tinha tendências suicidas. Mas se você está falando sério sobre isso, então vamos nos divertir um pouco!",
"Agora você está falando! E estou me sentindo um verdadeiro pirata. Eu atacarei o forte pelo mar, e você e seus homens poderão sitiar a cidade por terra. O que você diz?",
"Eu digo que criei um monstro ",
". Mas estou pronto quando você estiver!",
"Acalmar! O que aconteceu?",
"O que aconteceu? Disseram-me que você estava morto! Naveguei para #sGreenford# para descobrir o que realmente aconteceu. O dono da taverna me disse que não tinha visto você. Então um rapaz se aproximou de mim do nada e disse que sabia onde você estava. E eu caí nessa como um tolo!",
"Relaxar. Está tudo bem agora. O que aconteceu então?",
"Naveguei até aqui para #sIsla Muelle# com aquele cachorro mentiroso. Ele disse que nos encontraríamos com os piratas que o mantêm prisioneiro. Ele me levou para a selva - e depois fugiu quando fui atacado por dois amigos dele. Quando terminei com eles e voltei para a costa, ele já havia partido. E o meu navio também!",
"Você passou por tudo isso por mim? A fria e arrogante Danielle correu em meu resgate sem pensar duas vezes!",
"Continue falando e você estará resmungando em torno do meu sabre!",
"Eu terminei! Nem mais uma palavra, eu prometo! Então...as placas estão completamente perdidos para nós?",
"Você realmente acha que sou apenas uma garota tola, não é? Não, eu os guardei comigo.",
", minha querida, eu já te disse que você é a pirata mais inteligente que eu conheço?",
"Não. Pelo que me lembro, você ficou extasiado principalmente com minha 'língua afiada incomparável'. Agora me diga: como você chegou aqui?",
"Depois de capturar o navio que foi enviado para entregar o ídolo ao #sGovernor#, estabeleci um rumo para o nosso local de encontro. Mas enfrentei um mau tempo e fui levado ao mar como um marinheiro de água doce. Eu tinha certeza de que estava morto, mas aconteceu que fui levado à costa perto de #sisland_Douwesen#.",
"Sim. A fortuna favorece os tolos.",
"Fácil, agora! Passei por momentos difíceis. Quando recuperei o juízo, entrei cambaleando em #sDouwesen# e consegui um pequeno navio. Não muito tempo depois, acabei aqui. Você pode imaginar como fiquei surpreso ao ver meu antigo navio no porto de Muelle. Ela ainda estava sendo consertada depois daquela tempestade.",
"Incrível! A sorte favorece os tolos, mas nem você é tolo o suficiente para ter tanta sorte!",
"Bem, nesse caso... eu inventei tudo. Sim! Apenas uma história complicada para entretê-lo. De qualquer forma, aqui estou.",
"E aqui estou eu. E agora temos o ídolo. Deveríamos navegar juntos para #sisland_Oxbay# e conversar com Aurentius sobre a tradução dessa lenda.",
"Ah, não me atrevi a sonhar que você diria isso! Navegar juntos - parece tão... fofo!",
", querido, cale a boca!",
"Sim, estou trabalhando para ele.",
"Seu demônio! E você armou uma emboscada para mim no portão da cidade?!",
"eu não...",
"Morrer!",
"Ainda está jogando duro para conseguir, não é? Justo...",
"Apenas fique quieto ",
", você poderia?",
"Parece engraçado para você? Eu gostaria de ver você rindo com uma pilha de gravetos aos seus pés!",
"Então ele estava falando sério? Achei que você o ajudou a carregar comida ou algo assim.",
"Sério, porém - o que você está fazendo aqui?",
"Estou tentando encontrar alguém, mas quanto mais perto chego, mais difíceis as coisas ficam para mim.",
"Também tenho tido muitos problemas.\nE tudo por causa de um rapaz. Ele também é capitão, por acaso. Atende pelo nome de ",
"Raoul Rheims",
"Raoul Rheims",
".",
"Você está falando sério? Procuramos o mesmo homem! Mas por que você está atrás dele?",
"Ouro, é claro! Um homem muito poderoso quer falar com aquele demônio e me prometeu uma boa quantia se eu o prender.",
"Eu vejo. Talvez pudéssemos procurá-lo juntos.",
"Sou totalmente a favor disso, mas vou te dizer desde já que não tenho ideia de onde ele está.",
"Estamos empatados, então - nem eu.",
"Bem, não podemos fazer nada pior juntos do que fizemos separados. E deve ser algum tipo de destino, nosso encontro assim.\nQuando iremos procurar nosso 'amigo' em comum?",
"Bem, eu tenho alguns negócios para resolver aqui...",
"Sem problemas. Na verdade, eu mesmo tenho algumas pontas soltas para resolver.",
"Multar. Vamos nos encontrar aqui em uma semana. O que você diz?",
"Perfeito. Vejo você então.",
"Boa sorte!",
"Você não se lembra de nada?",
"Minha cabeça está dividida ",
". Não me pressione. Por que você não explica o que está fazendo aqui?",
"Ei, se alguém deveria estar bravo, deveria ser eu! Pegar aquela adaga onde peguei não foi a coisa mais agradável que já me aconteceu!",
"Você merece isso! Eu sei que você está me caçando para o governador inglês. Vamos resolver isso agora. Desenhe sua lâmina!",
"Estabeleça-se, ",
". Você entendeu tudo errado. Eu não estou caçando você de jeito nenhum. Eu nem sabia disso ",
"Robert Christopher Silehard",
" queria você morto.",
"Não me venha com isso ",
"! Você sempre disse que faria qualquer coisa por dinheiro!",
"Oh vamos lá, ",
"! Eu estava brincando! Você esperava que eu fosse um canalha. Você gosta de canalhas! Eu não poderia te decepcionar.",
"O que você está falando?! Sempre te considerei um homem honesto!",
"Oh não! Durante todo esse tempo nos conhecíamos e estávamos sempre em desacordo.",
"Isso é verdade! Você estava sempre tentando arrancar os melhores empregos debaixo do meu nariz!",
"Mas quando foi que eu fiz alguma coisa com você? De onde estou, parece que sempre salvei sua pele!",
"Talvez. Mas você ainda está trabalhando para um homem que me quer morto!",
"Sim, eu estava, ",
". Recentemente... me aposentei. Mas ",
"Robert Christopher Silehard",
" ainda não sabe disso.",
"O quê, ele não te pagou o suficiente?",
"Dinheiro não é o problema. Não dessa vez. Acabei de decidir que não queria mais trabalhar para um homem como ele.",
"O que você está dizendo? Você é um homem livre? Então me deixe em paz!",
"Multar! Vejo que você está tão teimoso como sempre. Boa sorte com os três cadáveres que você tem em mãos.",
"?!",
"O que mais você quer?",
"...",
"Você tem mais alguma coisa a dizer ou posso ir?",
"...Obrigado pela ajuda, ",
". Eu estaria morto se não fosse por você",
"Esqueça. Posso ir?",
"Espere, ",
"! O que você vai fazer agora?",
"Vou fazer algumas perguntas a um certo governador sujo.",
"Espere um minuto, sim? Você não pode ir lá sozinho. Isso é suicídio! Se ",
"Robert Christopher Silehard",
" suspeitar de alguma coisa, ele vai te matar só por segurança!",
"Obrigado, mas vou arriscar!",
"Não sem mim, você não vai!",
"Por que? Eu ficarei bem sozinho.",
"Em primeiro lugar, tenho minhas próprias perguntas para fazer a ele. E em segundo lugar - ",
"O que?",
"Conheço um bom lugar para lançar âncora em #sisland_Redmond#, onde ninguém estará esperando por nós.",
"Tudo bem, tudo bem. Vamos unir forças por enquanto.",
"Multar! Mas se você me enganar mais uma vez ",
", eu vou te matar, eu juro!",
"O que está acontecendo? Aqueles soldados estavam tentando nos matar!",
"Não sei, ",
", mas você deveria sair da cidade - é perigoso aqui.",
"Então... onde ele poderia guardar aquele papel? Vamos ver.",
"(Comece a pesquisar)",
"A cidade inteira está em pânico! Estão gritando que o porto está pegando fogo. Não podemos ir por esse caminho.",
"Eu tenho uma ideia. Diremos que há tropas francesas na cidade. Grite a plenos pulmões! Isso vai confundir os guardas!",
"Parece que vejo a figura de Nigel Blythe bem à frente. Interessante. Para onde ele poderia estar indo?",
"...",
"Hm...Talvez eu esteja errado, mas parece que um dos meus tripulantes - Artois Voysey - acabou de entrar na cidade.",
"...",
"O oficial Edgar Attwood acabou de deixar minha nave sem minha permissão.",
"...",
"Inferno! Alguém atirou em Artois! Devo levá-lo a uma taberna e encontrar um médico para ele!",
"...",
"Snorri: ...já estou neste buraco há duas semanas e ainda não há ouro! E você nos disse que o velho certamente pagará!",
"...",
"Billy: Ele vai pagar, com certeza vai. Mas reunir tanto ouro não é uma coisa tão rápida de se fazer.",
"...",
"Snorri: E se ele simplesmente não der a mínima para seu maldito filho?! E se em vez de ouro vier aqui um galeão cheio de espanhóis sedentos de sangue?!",
"...",
"Billy: Já chega! Você já viu um pai que abandonaria o filho numa situação como essa? Não se preocupe, o almirante pagará o resgate. Ele realmente não tem escolha.",
"Já ouvi o suficiente. Estes são os que eu preciso. (Mostre-lhes o sinal)",
"Agora vamos libertar o Padre Domingues!",
"As células estão à direita. Vamos.",
"(Vejo um pequeno monte de pedras)",
"Aposto que há algo enterrado aqui. Eu vou cavar.",
"(Dez minutos depois)",
"Que espada linda! Mas há um nome gravado na lâmina...",
"BARTOLOMEU! ONDE VOCÊ ESTÁ INDO???",
"Hmm... Ele parece não me ouvir mais. É melhor eu segui-lo. Ele parece estar correndo para a loja.",
"(Uma tempestade repentina está rugindo)",
"Estranho. De onde veio aquela tempestade de repente? É melhor eu sair deste lugar rapidamente.",
"(Outra tempestade repentina está rugindo)",
"Outra tempestade repentina? Eu não gosto disso.",
"(Os espanhóis detectam sua presença)",
"MOOOVEEEE!!!!! IRMãOS DA COSTA!!!",
"(Você vê o soldado do porto)",
"É ele de novo! Vamos pegá-lo!",
"(Barbossa conversando com sua equipe)",
"Senhores, chegou a hora! Nosso tormento está chegando ao fim! Durante dez anos fomos testados e experimentados. E cada homem aqui moveu sua coragem cem vezes e cem vezes novamente. Punidos éramos todos nós, desproporcionalmente ao nosso crime. Aqui está! O tesouro amaldiçoado do próprio Cortés. Cada pedaço que se extraviou, nós devolvemos. Economize para isso!",
"Talvez você seja imortal, mas ainda posso nocautear você, idiota! Agora, tenho que me juntar à minha tripulação para inverter a situação na minha nave.",
"Capitão ",
"Você é acusado de crimes contra a Coroa. Os referidos crimes são numerosos em quantidade e de natureza sinistra. Os mais flagrantes deles serão citados aqui: pirataria, contrabando, navegação sob cores falsas, incêndio criminoso, sequestro, saque, caça furtiva, banditismo, furto, depravação, depredação e ilegalidade geral. Por esses crimes, você é condenado a ser enforcado pelo pescoço até morrer. Que Deus tenha piedade de sua alma.",
"... parece que não! ...",
"Ah bem! ... eu mesmo terei que fazer a nobre ação.",
"[A moeda amaldiçoada no colar em volta do pescoço de Elizabeth chama-se #scursed_ship#]",
"Hmm... não foi um dos meus melhores dias!",
"Agora, há uma nave que pode me dar alguma vantagem. Eu deveria ir e dar uma olhada mais de perto.",
"(Vejo que a areia foi movida)",
"Alguém enterrou algo aqui.",
"(Dois minutos depois)",
"UM MAPA! Aposto que o ouro está lá.",
"(Oito caixas de ouro estão na caverna)",
"Encontrei o ouro... mas apenas uma pequena parte do ouro roubado em Aguadilla. Onde está o resto?",
"(Alguns dias depois)",
"Chegou a hora de ver novamente meu informante. Esperemos que ele tenha encontrado alguma coisa.",
"(Dois dias depois na taberna)",
"Esta noite, tenho de ver o tesouro.",
"(Você ouve a conversa desses soldados)",
"Eles pertencem à Frota de Prata... Devo avisar Elting que eles instalaram um acampamento fortificado em frente ao forte.",
"Não encontrei nenhum papel...",
"...mas não importa - este pedaço de pergaminho sujo serve.",
"O que!! A figura de uma caveira exatamente onde fiz o desenho do besouro. Não, meu próprio esboço está no verso, exatamente como eu o fiz.",
"Se a caveira estivesse ali desde o início, é claro que eu não poderia deixar de notá-la. Então de onde veio o crânio???",
"Preciso copiar esse 'texto' antes que ele desapareça novamente -",
"- Júpiter pode ir até a vila de Moultrie e comprar papel lá!",
"Posso jurar que há mais coisas escondidas neste documento. Talvez a camada de sujeira possa ter algo a ver com a falha.",
"Vou tentar enxaguar o pergaminho com água quente!",
"Agora vamos fazer uma coisa mais metódica -",
"- investigação do pergaminho.",
"Agora o crânio desapareceu! Apenas meu esboço do besouro permanece. Deixe-me pensar:",
"Quando desenhei o escaravelho, não havia nenhuma caveira aparente no pergaminho. Quando terminei o desenho, entreguei-o ao Sr. Poe e observei-o atentamente até que ele o devolveu. Ele, portanto, não desenhou o crânio e ninguém mais estava presente para fazê-lo. Então isso não foi feito pela agência humana. E mesmo assim foi feito.",
"O tempo estava frio (oh, acidente raro e feliz!) e um fogo ardia na lareira.",
"Fiquei aquecido com os exercícios e sentei-me na cama, longe da lareira. O senhor Poe, porém, havia puxado um banquinho para perto da chaminé.",
"Quando considero todos esses detalhes, não duvido nem por um momento que o calor tenha sido o agente que trouxe à luz, no pergaminho, a caveira que vi desenhada nele.",
"Existem preparações químicas, e existem desde sempre, por meio das quais é possível escrever, em papel ou pergaminho, de modo que os caracteres só se tornem visíveis quando submetidos à ação do fogo.",
"Eu sabia! Existem algumas figuras dispostas em linhas!",
"Eu fiz tudo que posso por enquanto. Amanhã vou tentar outra coisa, mas agora é hora de dormir.",
"Um novo dia - e vou tentar uma maneira melhor de aquecer esse pergaminho...",
"... mas primeiro: preciso acender o fogo novamente. Está muito frio aqui.",
"Se eu colocar o pergaminho em um prato ou prato limpo e seco naquele caldeirão, talvez o documento fique mais aquecido.",
"Mas não, não sei onde está o refratário e estamos sem lenha. Terei que acordar Júpiter!",
"Preciso me apressar agora e escrever o código completo -",
"- antes que desapareça novamente!",
"Eu tenho todos os seis itens -",
"- agora vamos colocá-los no Kit de Detetive!",
"Estou muito curioso para ver o que o Sr. Poe",
"surgiu com...",
"Hmm, vamos ter cuidado agora Júpiter, estamos chegando perto dos Portões da Plantação -",
"- me pergunto como podemos entrar sem sermos notados...",
"Tudo bem, aí está. ",
"Agora me diga Júpiter, você sabe onde ficam os quartéis dos escravos?",
"Olha Júpiter -",
"- guardas patrulhando por toda parte lá embaixo!",
"Ok, aqui está: tinta, caneta e um pedaço de papel -",
"- agora, por favor, mostre-me o formato daquela rocha.",
"Isso era novo para mim, Júpiter. Eu não tinha ideia sobre suas habilidades de kungfu!?",
"Bem, JRH achou que era hora de algo completamente diferente aqui...",
"Encontrei a alavanca na grama de Júpiter. Mas não adianta colocar de novo...",
"... acho que só vai cair.",
"Eu vi algo - uma caveira em uma grande árvore!?",
"É melhor olhar de novo.",
"Acho que é isso! Agora só me resta encontrar aquela árvore-tulipa.",
"Apenas muito verde - não tenho certeza para que lado olhar...",
"O que devo fazer aqui?",
"Admirar a vista?",
"Ok, encontrei o Assento do Diabo. Vamos voltar para Charleston novamente -",
"- Vou precisar de uma Luneta, uma Bússola e um Sextante para resolver isso.",
"Aí está! E parece exatamente com o esboço",
"agora tenho que encontrar um caminho para subir a Rocha.",
"Eu esperava que eles tivessem ido embora. O que faremos Júpiter -",
"- retornar?",
"Júpiter, por favor, vá ao Forte Moultrie e visite o Tenente G -",
"- pergunte a ele se podemos pegar uma luneta emprestada. Eles devem ter alguns itens desse tipo no Forte!",
"Deixe-me pensar: a janela não, a barreira está quebrada, as lâminas na parede não podem ser movidas. ",
"A única chance que tenho é usar minha pólvora e a caixa de fogo. Talvez eu possa atear fogo a um pedaço de papel e aguardar a explosão da pólvora em um lugar seguro?",
"Tenho que tentar usar o Boom como alavanca -",
"- para abrir a escotilha.",
"Primeiro farei um esboço do esboço da montanha -",
"- então vou enchê-lo com Pólvora!",
"O único lugar onde posso me proteger -",
"- está no canto atrás da estante.",
"Ninguém está aqui!",
"Ok, vou descansar aqui até eles aparecerem.",
"Ah, não, eles removeram os degraus de madeira!",
"Como podemos agora colocar a alavanca?",
"Não! Olhe Júpiter - ",
"- os quilombolas devem ter adivinhado nosso destino.",
"Acho que podemos seguir a costa ao redor do penhasco até aquela jangada.",
"---",
"Você vem Júpiter?",
"Sim, sim, o velho Jup está aqui.",
"Sim, esta deve ser a árvore-tulipa que vi! É o único com caule marrom.",
"Você acha que pode escalar Júpiter?",
"Agora, Jup, quero que você trabalhe nesse galho o máximo que puder -",
"- se você ver algo estranho, me avise.",
"Júpiter, você está me ouvindo?",
"Sim, Massa Will, ouvi você falar tão claramente.",
"Experimente bem a madeira e veja se acha que está muito podre.",
"Ele está podre, cara, com certeza, mas não tão podre quanto deveria estar. Devia aventurar-me pelo caminho mais alto, isso é verdade.",
"Eu sabia! Estamos indo na direção certa, Júpiter.",
"Uhu?",
"Você verá, mas primeiro temos que voltar para Charleston e pegar algumas ferramentas. Acho que deveríamos consultar o Sr. Poe também...",
"Muito bem massa, vamos.",
"Parece que os quilombolas deixaram Júpiter?",
"Hmm, não tenho tanta certeza sobre esse massa Will.",
"Maldito! Eles chegaram aqui antes de nós, Júpiter.",
"!!!",
"Não importa a farinha -",
"- Preciso deles sacos para coisas melhores.",
"Não, não está trancado, mas está preso.",
"Vou precisar de algo afiado para abrir este baú.",
"Ok, então sou o primeiro aqui -",
"- é só esperar o massa Will e o senhor Poe.",
"Aha, Edgar ainda não chegou -",
"- acho que vou tirar uma soneca enquanto espero.",
"Preciso muito da minha Pistola, mas ela ainda está no Ferreiro para reparos -",
"- e não tenho dinheiro para recuperá-lo.",
"Ferramentas de trabalho são outra coisa. Talvez eu possa 'pegar emprestado' alguns na Igreja.",
"Vou procurar o Padre, ele deve saber como entrar lá, mesmo a Igreja hoje em dia estando fechada para reparos.",
"Como o padre achou que poderíamos nos encontrar aqui?",
"Ou talvez...Existe outra maneira de entrar?",
"Hmm, o portão está trancado - ",
"- mas primeiro tenho que reunir todas as coisas que preciso.",
"A munição para esta nova pistola de percussão era um pouco complicada -",
"- mas agora estou pronto para me juntar ao meu amigo William fora da cidade.",
"Júpiter, o que você está fazendo?",
"Você já está no galho com o Caveira?",
"Bem, agora, Júpiter, faça exatamente o que eu lhe digo - você ouviu?",
"Sim, massa.",
"Preste atenção, então! - encontre o olho esquerdo do crânio.",
"Zumbir! hoo! isso é bom! por que ousa não ter nenhum olho esquerdo?",
"Maldita seja sua estupidez! você distingue sua mão direita da esquerda?",
"Sim, eu farejo isso - farejo tudo isso - é com minha mão esquerda que eu corto a madeira.",
"""Com certeza! você é canhoto e seu olho esquerdo está do mesmo lado que sua mão esquerda.
Agora, suponho, você pode encontrar o olho esquerdo do crânio, ou o local onde o olho esquerdo esteve. Você achou?"","
"---",
"Muito bom Júpiter, agora, por favor, abaixe a corda de dois a dois metros!",
"Seis - sete pés abaixo, sim massa.",
"Você está pronto Edgar, para marcar o local quando eu remover o GoldBug?",
"Claro, vou usar uma das estacas que encontrei na Igreja.",
"Seu canalha, fale eu te digo! - responda-me agora mesmo, sem prevaricação! - qual - qual é o seu olho esquerdo?",
"Oh, meu Deus, Massa Will! Não está aqui meu olho esquerdo para Sartain?",
"Eu pensei assim! - Eu sabia! - viva!",
"Júpiter, o crânio foi pregado no membro com a face voltada para fora ou com a face voltada para o membro?",
"O rosto estava no membro massa.",
"Pois bem, foi por este ou aquele olho que você deixou cair o besouro?",
"Era dis eye, massa - de left eye - jis como você me diz.",
"Dá-me aquela Espada Júpiter.",
"Se você diz, massa Will.",
"Júpiter, você trouxe algum Sacks de casa?",
"Claro que sim, massa Will, aqui pega um pouco.",
"Ok, pegue um saco para cada -",
"- não podemos levar tudo para o Barco agora. Voltaremos ao Baú o mais rápido possível.",
"Júpiter, o líder quilombola que você chamou de Herói, ele era próximo de você, é isso?",
"Este foi um dia muito longo -",
"- vamos todos dormir um pouco agora!",
"""Parece, no entanto, apenas uma maneira plausível de explicá-los
 - e ainda assim é terrível acreditar em tal atrocidade como a minha sugestão implicaria.
É claro que Kidd - se Kidd realmente escondeu este tesouro, o que não duvido -
é claro que ele deve ter tido assistência no trabalho de parto."","
"""Mas, concluiu este trabalho, ele pode ter pensado que seria conveniente remover todos os participantes do seu segredo.
Talvez alguns golpes de enxada fossem suficientes, enquanto seus coadjutores estavam ocupados na cova,
talvez tenha sido necessária uma dúzia - quem dirá?"","
"Eu me pergunto se o Tenente G sabe alguma coisa sobre cifra -",
"- isso não significa absolutamente nada para mim.",
"",
};
