string DLG_TEXT[28] = {
"Olá, capitão.",
"!!!",
"Onde capitão?",
"Oh, estou bem aqui, obrigado por esta parte da história.",
"1) Para a CASA DE LEGRAND depois da costa.",
"2) Para CASA DE LEGRAND dia 2.",
"3) Para MOULTRIE VILLAGE (Júpiter).",
"4) Para FORTE MOULTRIE.",
"5) Para CHARLESTON.",
"6) Para CHINATOWN.",
"7) Para a SALA CHINESA.",
"8) Para a PLANTAÇãO.",
"9) Para os MARRONS.",
"10) Para o BISHOP'S HOSTEL, pela primeira vez.",
"11) Para o FORTE (Júpiter) + para PYM (Legrand).",
"12) Para BISHOP'S HOSTEL, segunda vez.",
"13) Para POE'S + BOAT & HUT (Júpiter).",
"14) Para o FORTE (revólver).",
"15) Para a IGREJA (Poe).",
"16) Para o BISHOP'S HOSTEL, da última vez.",
"",
"",
"Tem certeza capitão? O processo pode ser um pouco assustador...",
"Eu não estou assustado!",
"Posso ver as alternativas novamente.",
"Hmm, acho que vou jogar o início da aventura.",
"Esteja avisado então capitão.",
"Tudo bem, tudo bem. Agora vamos!",
"",
};
