string DLG_TEXT[18] = { 
"Quem está aí! O que você quer??",
"Oh, senhorita... eu quero entrar.",
"Você não vê que está fechado!",
"Sim, eu sei. Procuro o Padre - Claude Frollo.",
"Shhh, você é o senhor Poe?",
"De fato, eu sou. Agora você vai me deixar entrar?",
"Aqui, pegue a chave...",
"Obrigado senhorita...",
"Boa noite, senhor Poe. Espero que você tenha trazido os Documentos do Padre.",
"Sim, tenho o Livro de Hinos, completo com sua Carta de Amor.",
"Ahh, senhor Poe, não vamos julgar muito aquele homem.",
"Muito bem - onde ele está?",
"Padre Frollo está ehh um pouco ocupado no momento...",
"Eu vejo (perfeitamente bem o que ele está fazendo).",
"Não é como você pode pensar. De qualquer forma, ele me pediu para entregar este pacote para você.",
"(Sim está bem? Obrigado então senhorita...",
"Sim, há mais alguma coisa que eu possa fazer por você...",
"Bem, eu... hrmpf... só olhando em volta.",
"",
"",
};
