string DLG_TEXT[16] = { 
"Você não vê que estou ocupado!",
"Você queria alguma coisa?",
"A comida é fantástica, você tem que experimentar.",
"Vamos comer e beber.",
"Se você quiser bater um papo, encontre outra pessoa.",
"Eu só estava me perguntando se você está vivo ou não. Você está aqui como uma estátua",
"Conte-me em outra hora. Estou comendo.",
"Vá embora, não me incomode",
"Ok, vamos ficar bêbados.",
"Tome uma bebida comigo.",
"Tudo bem, tudo bem.",
"Não, eu...",
"É assim mesmo.",
"Bem, eu...",
"O que?!",
"Como você diz.",
"",
};
