string DLG_TEXT[251] = {
"Essa foi a minha última chance, companheiro Will.",
"Sim, também estou sem munição. Vamos pegar as galinhas do pântano e voltar para casa.",
"Aqui, deixe-me levar esse saco.",
"Se você diz, Júpiter. Vamos percorrer o naufrágio e passear pela margem, em busca de conchas e exemplares entomológicos.",
"O que importa, companheiro?",
"Oh, nada Jup.",
"O inseto que vejo é um inseto goole, sólido, um pedaço inteiro dele, por dentro e tudo, separe sua asa - nunca me sinto um inseto meio tão pesado em minha vida.",
"Um Bug Dourado, você diz? Hmm, vamos voltar e pesquisar mais de perto!",
"Companheiro Will, você diz nada sobre bug?",
"Talvez você esteja certo, Júpiter. Voltaremos e tentaremos pegá-lo!",
"Cuidado Companheiro Will, alguém em casa!",
"Tem certeza de Júpiter?",
"Vê a fumaça Companheiro? Eu não acendi o fogo, eu continuo contando sobre você.",
"Oh, oh, quem pode ser?",
"Eu levo as armas, companheiro.",
"Sim, obrigado Júpiter.",
"O que importa, companheiro?",
"Você não reconhece nosso amigo, Sr. Poe, Jup?",
"Ele não tem nada nele, Companheiro Will, eu continuo contando para você, o inseto é um inseto goole, sólido, todo pedaço dele, por dentro e tudo, separe as asas dele - nunca me sinto um inseto meio tão pesado na minha vida. ",
"Bem, suponha que sim, Jup, isso é alguma razão para você deixar os pássaros esperarem?",
"Jantar!",
"Muito bem, vamos comer.",
"O que foi isso, companheiro?",
"Um pedaço de papel sujo, eu acho. Mas posso usá-lo para pegar os escaravelhos!",
"Ah, está ficando tarde - vou para a cama agora, senhor Will - tenho a porta trancada durante a noite.",
"Obrigado. Uma coisa Júpiter, você sabe onde fica o grande caldeirão?",
"Andar de baixo.",
"Boa noite então.",
"Jup, quero que você vá até a casa de barcos - acho que ainda temos um pouco de madeira lá.",
"De boothouse você diz. E o Refratário está na adega, companheiro Will.",
"Obrigado Júpiter. (Não me atrevo a perguntar onde ele colocou a chave.)",
"Quero que você vá até a vila de Moultrie e compre algumas folhas de papel.",
"Me dê dinheiro, companheiro Will.",
"Não tenho dinheiro... pegue aquele peixe grande - tenho certeza que a vila pode vendê-lo aos turistas.",
"Ok, Júpiter irá embora",
"Ah, sim, mais uma coisa: você também poderia visitar o Tenente G no Forte e me trazer o Escaravelho Dourado de volta?",
"Estou indo para o Forte Júpiter, preciso da ajuda do Tenente G com essa cifra.",
"Até mais, companheiro Will.",
"Júpiter, o Tenente G deixou alguma senha para mim?",
"Que palavras, companheiro Will?",
"Um papel talvez?",
"Apenas o papel de golebug estava dentro.",
"Mostre-me aquele papel Júpiter.",
"Ok, uma carta ou um bilhete então?",
"Que carta, companheiro Will?",
"Mas é no meio da noite, senhor Will.",
"Sim, é muito cedo. Vamos descansar um pouco antes de ir para Charleston.",
"Mas já é tarde da noite, companheiro Will.",
"Sim, é tarde demais. Vamos esperar até amanhã antes de ir para Charleston.",
"Júpiter, o Sr. Poe mudou, ouvi dizer. Você sabe onde?",
"Júpiter não tenho certeza, companheiro Will.",
"Mas você acompanhou o Sr. Poe para casa outra noite?",
"Estava tão escuro que o Sr. Poe teve dificuldade em encontrar o portão.",
"Um portão. Bem, isso é alguma coisa - vamos procurar!",
"'GRAUS' ??",
"!",
"Júpiter, você já ouviu falar de algum prédio que tenha o nome de Albergue ou Hotel do Bispo?",
"Bessop, sim, eu conheço muito bem essa plantação...",
"Bessop, você diz - hmm, por que não. Júpiter, onde fica essa plantação?",
"Acabamos de sair da cidade pelo lado da selva, companheiro.",
"É assim mesmo?",
"Talvez possamos entrar furtivamente na plantação à noite, senhor Will.",
"Sim, essa é a única chance. Mas precisamos de algo para distrair os guardas...",
"Você quer dizer fogos de artifício ou bombas?",
"Fogos de artifício - é uma boa ideia. Me pergunto quem está vendendo esse tipo de coisa.",
"Os chineses vendem fogos de artifício, companheiro.",
"O chinês? Você quer dizer no restaurante chinês?",
"Sim, espero que a malária tenha desaparecido.",
"Veremos Júpiter.",
"Oh não, você quer que nós façamos ",
"faça um trabalho perigoso hah?",
"Ok, eu faço o Restaurante. Você lê e tal, companheiro Will.",
"Muito bem, então está tudo resolvido. Agora, como eu começo?",
"Companheiro Will, de Chinese mandou mais algumas coisas para você...",
"Deixe-me ver - o que é isso?",
"Carvão.",
"Salpeter.",
"Enxofre.",
"Carvão e salitre.",
"Carvão e Enxofre.",
"Salpetro e Enxofre.",
"Carvão, salitre e enxofre.",
"Muito bem, passe para Jup.",
"Companheiro Will, esta é a última vez que o Chinese pode te ajudar com os ingredientes. Ele ficou sem tudo.",
"É assim mesmo. Bem, deixe-me ver o que você tem aí.",
"Me dê barris de dose, Companheiro - você pega os vazios de Jup.",
"Ahh, muito bom Júpiter.",
"Eu administro o restaurante agora, Companheiro.",
"Subimos a montanha Will e vemos primeiro a plantação de cima.",
"Boa ideia Júpiter, vamos encontrar um caminho para cima!",
"Veja a casa com fumaça - o quartel fica logo atrás dela. Dois quartéis, um para mulheres e outro para escravos.",
"Hmm, a plantação parece estar muito bem guardada...",
"Sim, olhe a torre de vigia ao seu lado, companheiro.",
"Sim, dessa forma é impossível. Eles vão me ver imediatamente, talvez do outro lado?",
"Você entra sozinho, companheiro Will?",
"Na verdade, é muito perigoso para um homem negro entrar neste lugar. Talvez eu consiga escapar disso se for pego.",
"Eu vejo. Jup vai fazer fogos de artifício lá fora, certo? E olhe - eles também têm uma torre de vigia do meu lado.",
"Você está certo Júpiter. Teremos que nos aproximar, manter a cabeça baixa e me seguir",
"O que é isso, companheiro Will?",
"Acho que é melhor esperar até hoje à noite",
"Pois é, você tem que se esconder entre fardos de dose, companheiro Will, quando entrar.",
"(Salvar..? O que ele quer dizer?) Ok, vamos descer.",
"Mantenha-se perto da companheiro ao lado da montanha e espere pelos fogos de artifício antes de pular a cerca.",
"Eu farei isso Júpiter.",
"Me dê o Tinderbox e o Fireworks Chest, companheiro Will.",
"Claro, aqui está você Júpiter. Lembre-se de verificar os números antes de atirar nos Rockets.",
"Você quer que Jup remova essa caixa, companheiro Will?",
"Claro, você pode realmente fazer isso?",
"E se eu fizer a alavanca e mantê-la no lugar enquanto você continua sozinho, companheiro Will?",
"Mas, isso o deixará para trás de Júpiter.",
"E você sozinho para aquele Rock misterioso",
"Hum, tudo bem. Aqui, pegue a alavanca e me dê um segundo para chegar ao portão.",
"Boa sorte então companheiro Will.",
"Até mais Júpiter e cuidado com esses bandidos.",
"Você está bem, senhor Will?",
"Claro, por favor abra o portão novamente. E Júpiter, pegue aquela alavanca quando ela cair no chão. Precisaremos disso mais tarde.",
"Não faço ideia de voltar. Vamos esperar pelo melhor.",
"Mas eles são bandidos?",
"Maroons, companheiro Will, maroons. Deixe-me conversar, talvez ainda tenhamos uma chance",
"Você tem certeza sobre esse Júpiter?",
"Olá herói, sim, sou um homem livre há muito tempo e companheiro Will encontrou um Gole Bug - ",
"- Você pode ver por si mesmo.",
"Para onde vamos agora, senhor Will? ",
"Precisamos de um sextante, uma bússola e uma luneta.",
"Para de Store então.",
"Você sabe onde fica Júpiter?",
"Claro, você me enviou para lá muitas vezes. É ao lado do Sr. Poe.",
"Vamos então.",
"Eles comeram um ao outro.",
"Do que você está falando, você não pode querer dizer...?",
"Claro, Jup irá. Aqui está o tinderbox companheiro Will. E tenha cuidado com aquele Pym... ",
"Apenas rumores de Júpiter, nada com que se preocupar. Vamos nos encontrar na casa do Sr. Poe, Júpiter. ",
"Você está bem Companheiro?",
"Sim, estou bem, obrigado Júpiter. E você tem uma luneta, eu vejo.",
"Aqui está você Companheiro Will...",
"Muito bom!",
"Ah, senhor Will. Jup tem ideia...",
"Vamos aqui Júpiter.",
"Podemos pegar a escada da montanha.",
"Hum, sim, isso é muito bom. (por que não pensei nisso!)",
"Mas companheiro Will, você sabia que isso iria acontecer?",
"Sim, claro, só estou verificando as coisas aqui...",
"Temos que fazer outra coisa aqui.",
"Hmm, sim, eu me pergunto como nós dois poderíamos superar...",
"Precisamos de uma prancha para bloquear o portão quando ele descer Companheiro Will!!",
"SIM! Você está certo, talvez possamos usar uma das tábuas da ponte?",
"Vou buscar uma companheiro Will.",
"Muito bem Júpiter, vou procurar a alavanca novamente.",
"Você viu a jangada embaixo da ponte Companheiro? Talvez possamos navegar em torno dos bandidos.",
"Jangada? Mostre-me Jup, mas nem um som.",
"Aí está, mas como chegamos lá Companheiro Will?",
"Hmm, vou ter que dar uma olhada mais de perto na ponte.",
"Aqui, deixe-me pegar esse boom.",
"Muito bem, vamos.",
"Sim, companheiro, Jup sobe em qualquer árvore que ele possa ver na vida.",
"Então suba com você Júpiter.",
"Até onde devemos subir, companheiro?",
"Suba primeiro no tronco principal e depois direi que caminho seguir. Só me dê um segundo para ver melhor, Júpiter.",
"Que caminho devo seguir agora, Companheiro Will?",
"Continue com o galho maior - aquele deste lado.",
"Quanto fudder é necessário para ir?",
"Quão alto você está?",
"Ebber tão peludo, posso ver o céu do topo da árvore.",
"Não importa o céu, mas preste atenção ao que eu digo. Olhe para baixo no tronco e conte os membros abaixo de você deste lado. Quantos membros você passou?",
"Um, dois, três, quatro, fibe - eu passei fibe big limb, companheiro, pon dis side.",
"Então suba um membro mais alto.",
"Estamos ansiosos para nos aventurar neste membro berry longe - é uma companheiro de membro morto em todo o caminho.",
"Você disse que era um membro morto, Júpiter?",
"Sim, companheiro, ele morreu como um prego - feito para sartain - partiu desta vida.",
"O que em nome do céu devo fazer?",
"Estou bem, Companheiro Will - realmente estou, estou pronto para o fim agora.",
"Até o fim! Você diz que está no fim desse membro?",
"Em breve será o fim, companheiro, - o-o-o-o-oh! Lor-gol-a-marcy! o que é isso aqui na árvore?",
"Bem! O que é?",
"Por que contaminar nada além de uma caveira - alguém o deixou com a cabeça no alto da árvore, e os corvos devoram um pedaço da carne.",
"Uma caveira, você diz! - Muito bem! - Como é fixado ao membro? - O que o segura?",
"Claro, companheiro, preciso olhar. Por que essa sarcunstância curiosa, palavra de honra - ouso há um grande prego no crânio, o que o prende à árvore.",
"Muito bom Júpiter, você pode descer agora.",
"Rápido companheiro, recue para o outro lado do portão...",
"Huh? Você tem um plano?",
"Apresse-se, senhor Will. Temos que chegar à jangada antes que abram o portão novamente.",
"!!!",
"Temos que ficar bem calados agora, companheiro, para que os quilombolas não nos ouçam.",
"Sim, vamos esgueirar-nos por aí, Júpiter.",
"o que você está fazendo aqui? Os quilombolas logo nos encontrarão...",
"Estou procurando a entrada daquela caverna que visitamos anteriormente em julho",
"Oh não! O que vamos fazer agora, senhor Will?",
"Vamos vasculhar esta caverna esquecida por Deus completamente. Talvez possamos encontrar algo útil.",
"Olha, companheiro! Os quilombolas já estão aqui.",
"Vamos continuar Júpiter.",
"Eles se foram, companheiro!?",
"Hmm, é bom demais para ser verdade. Vamos ter muito cuidado, Jup.",
"Sacos em de Grot - sim, eu sei. Eu também ganhei um Musketoon, mas cadê a chave do baú de armas, cara?",
"Também há sacos no sótão, Júpiter. A Chave Acho que concordamos em nos esconder em um dos Jarros.",
"E precisamos do Barco para o grande Tesouro, companheiro Will.",
"Você acha que pode encontrar o caminho navegando em nosso barco até o Bishop's Hostel?",
"Ah, finalmente aí está você.",
"Você trouxe uma Arma e o Barco também, Jup, muito bom mesmo.",
"Eu tenho Pólvora, companheiro Will, mas não há Grapeshots.",
"Hum...",
"Sim, companheiro, Jup sobe em qualquer árvore...",
"Sim, eu conheço Júpiter, desta vez quero que você traga a corda que tenho aqui.",
"Não tem problema - dê para mim.",
"Aqui, pegue também o Goldbug. Use-o como peso na ponta da corda.",
"Oh não! Garras suficientes, companheiro e mouff também. Eu nunca vi esse maldito inseto - ele chuta e morde ebery ting o que goza perto dele.",
"Mas ele está morto agora Jup.",
"Devia me aventurar sozinho, isso é verdade.",
"Por você mesmo! - O que você quer dizer?",
"Por que quero dizer o bug. Este é um inseto da baga. Suponha que eu o deixe cair, e o membro não se quebrará apenas com o peso do velho Júpiter.",
"Seu canalha infernal! O que você quer dizer com me dizer uma bobagem dessas? Tão certo quanto você deixar cair esse besouro eu quebrarei seu pescoço. Olhe aqui, Júpiter, você está me ouvindo?",
"Sim, companheiro, não preciso gritar com o pobre Jup desse estilo.",
"Bem! agora escute! - estamos procurando uma fortuna e você está com medo de um inseto! Por favor, Júpiter, aventure-se no galho e não solte o besouro.",
"Estou indo, Companheiro Will - realmente estou, - estou pronto para terminar agora.",
"Muito bom!",
"O olho esquerdo do crânio também está do mesmo lado que a mão esquerda do crânio? - porque o crânio não tem nem um pouquinho de ajuda - lembre-se! Eu tenho o olho esquerdo agora - aqui está o olho esquerdo! o que devemos fazer com isso?",
"Deixe o besouro cair através dele, até onde o barbante alcançar - mas ele tenha cuidado e não solte o barbante.",
"Tudo feito, Companheiro Will, é muito fácil colocar o bug no buraco - cuidado com ele, ouse abaixo!",
"Sim!!",
"Me dê essa pá, companheiro Will.",
"Obrigado Júpiter.",
"Eu sei eu sei...",
"É feito de metal, companheiro. ",
"Acho que você está certo, Júpiter. Vamos nos apressar agora - talvez este seja o lugar certo!",
"Aqui estão mais sacos vazios...",
"Obrigado Júpiter, vamos voltar ao Baú do Tesouro antes que os marrons apareçam.",
"Sacos sim companheiro. Mas Jup só sobrou dois.",
"Hmm, talvez você seja forte o suficiente para pegar o baú desta vez, Júpiter?",
"O herói sabe o que está fazendo. Ele não nos perderá.",
"Hmm, você parece conhecê-lo muito bem?",
"Entregue a ponta da corda, companheiro Will - eu vou com a jangada ficar de olho no Tesouro.",
"Muito bom Jup.",
"Ele... ele era meu primo.",
"Oh, me desculpe, Jup.",
"Espero que tenham sido os últimos...",
"Na verdade, vamos saqueá-los antes de voltarmos para casa com o Tesouro.",
"Companheiro Will, entregue seu saco. É o último.",
"Obrigado Júpiter.",
"Eu também fico acordado, companheiro - tenho coisas para fazer...",
"Muito bem, boa noite então.",
"E tudo isso cum ob de goole-bug! o putty goole bug! coitado do goole-bug, o que eu bebi naquele estilo sabage kind ob! Você não está envergonhado, Júpiter? - responda-me isso!",
"Você mudou tudo aqui e colocou em alguma ordem também?",
"Claro que sim, companheiro Will, agora dê uma olhada.",
"Que ótimo trabalho você fez aqui, Júpiter! Agora deixe-me ver o que temos",
"Agora só tenho uma última pergunta, companheiro Will: O que devemos fazer com os skellingtons encontrados no buraco?",
"Esta é uma pergunta que não sou mais capaz de responder do que você.",
"O senhor Poe está tão cansado. Ele esteve ocupado escrevendo papéis a noite toda...",
"Sim, ele me disse.",
"E nos canaviais. Talvez eu também consiga encontrar algumas zonas seguras nesses edifícios. Todos os guardas parecem estar patrulhando.",
"Eu estive lá embaixo, então ouça com atenção, você só pode salvar em zonas seguras.",
"'Fogo por números', hein?",
"Ha!",
"",
};
