string DLG_TEXT[18] = {
"Olá Júpiter, o que é isso?",
"Oh noffin, companheiro Will.",
"Ahh, aí está você - e você encontrou a madeira!",
"Hum.",
"Aqui, pegue esta moeda velha - acho que é chinesa.",
"Chinês, eh...?",
"Você finalmente conseguiu algum papel, Júpiter?",
"Júpiter fez isso e de Golebug também! Aqui está você, companheiro Will!",
"Bom trabalho, por favor, leve esta pequena pérola pelos seus esforços.",
"Uma pérola, uau!",
"Agora, outra questão: ficamos sem madeira novamente.",
"Isso é tão companheiro. Vamos à praia e encontramos alguns troncos.",
"Na verdade, nós fazemos, Jup.",
"Você tem sacos, companheiro Will?",
"Aqui estão eles, mostre a saída.",
"---",
"Edgar, finalmente. Eu estava com medo que você tivesse acabado em algum tipo de problema.",
"Ah, bem... não. Eu tenho tudo pronto. Vamos embora?",
"",
"",
};
