string DLG_TEXT[22] = {
"Isso é um roubo, seu dinheiro ou sua vida!",
"!!!",
"Olá, o que vocês dois estão fazendo aqui?",
"Procuro conchas e exemplares entomológicos.",
"E você trouxe seu escravo também...?",
"Júpiter é um homem livre.",
"Eu o conheço -",
"- diga-me Júpiter, algo disso é verdade?",
"Tudo bem, talvez você esteja dizendo a verdade. Eu deixei você passar por Júpiter dos velhos tempos, mas da próxima vez você terá que me dar Ouro de verdade e não um besouro sem valor.",
"Vamos massa Will.",
"Próxima vez...",
"(gole)",
"Muito bem, agora olha quem está aqui. Desta vez você tem que pagar.",
"Tudo bem, quanto?",
"É muito simples - tudo o que você tem. E isso inclui suas roupas também.",
"Você não pode significar tudo!?",
"Bem, acho que posso...",
"Ok, ok, vá com calma.",
"Ei, senhor! Mais um passo para trás e você está morto",
"Eu não estou indo a lugar nenhum. (Ah!)",
"",
};
