string DLG_TEXT[23] = {
"A vida é apenas uma ilusão...",
"Hmm, bem... ah... hmm?",
"Ahh, Sr. Legrand, aí está você.",
"Como você sabe quem eu sou - quem é você?",
"Isso não é importante. Digamos que estou aqui para ajudá-lo.",
"OK? (Ela parece familiar, mas não me lembro quando...)",
"Já nos conhecemos - mas não importa. Eu tenho algo aqui que você vai precisar.",
"Obrigado, senhorita... (O que é isso?)",
"É apenas uma coisa pequena para usar no pescoço, mas espere até chegar em casa para examiná-la!",
"Vou manter isso em mente. (Mas estou tão curioso!)",
"Já nos conhecemos - mas não importa. Primeiro, acho que você deveria examinar o livro que encontrou com mais cuidado. Então eu tenho algo aqui que você vai precisar.",
"Senhor Poe...",
"Você sabe meu nome, quem é você?",
"Eu sei muitas coisas - por exemplo que você está descendo pela Adega.",
"!!",
"Você é um homem corajoso, senhor Poe, mas vai precisar disso.",
"O que é?",
"As cabaças contêm um antídoto. Nas pequenas bolsas Healing Herbs.",
"Vou precisar disso?! Mas eu não tenho dinheiro.",
"Eu sei - veja isso como um presente.",
"Obrigado senhorita..?",
"Agora, por favor, desvie o olhar, senhor Poe.",
"Huh?",
"",
"",
};
