string DLG_TEXT[20] = {
"Sim, o que posso fazer por você, senhor?",
"Oh nada.",
"... mas devo perguntar: quem é você, senhor, e como entrou?",
"Meu nome é William Legrand, Cabo. Usei as chaves da prisão que o sargento me forneceu.",
"É assim mesmo. É melhor você me dar essas chaves.",
"Tudo bem. Também recebi este bilhete do Sargento...",
"Deixe-me dar uma olhada.",
"Claro.",
"Muito bem, um Revólver... Deixe-me ver agora...",
"(Por favor, apresse-se, velho.)",
"Aqui, uma arma muito boa, senhor.",
"Obrigado.",
"E munição também. Onde coloquei esses cartuchos...",
"(Ele é muito lento, aquele antigo cabo.)",
"Ok, 12 cartuchos para o revólver - é tudo que tenho.",
"Hmm, gostaria de ter mais fotos...",
"E uma Corda Longa, tantas coisas...",
"(Vamos - apenas entregue, sim?)",
"E este deve ser o último item da lista - uma corda longa.",
"(Afinal!)",
"",
"",
};
