string DLG_TEXT[174] = {
"William querido amigo, desculpe por esta intrusão. O tempo está muito frio, então acendi uma fogueira, espero que não se importe?",
"Claro que não, seja bem-vindo, velho amigo. Jantaremos em breve.",
"Acho que você esteve caçando o dia todo?",
"Na verdade, nós temos. Aqui está Júpiter agora...",
"Sim, o quê posso fazer por você?",
"Ah, nada por enquanto.",
"O que você tem aí, algumas conchas novas?",
"Sim, e acho que um deles é um bivalve desconhecido, formando um novo gênero! Aqui, por favor, dê uma olhada.",
"Eles são tão lindos, mas você encontrou algo mais. Posso ver isso em seu rosto, William.",
"Na verdade eu fiz. Cacei e consegui, com a ajuda de Júpiter, um escaravelho que acredito ser totalmente novo, mas a respeito do qual desejo receber sua opinião amanhã.",
"E por que não esta noite?",
"Ah, se eu soubesse que você estava aqui! Mas já faz tanto tempo que não te vejo; e como eu poderia prever que você me faria uma visita nesta mesma noite, entre todas as outras? Quando voltava para casa encontrei o tenente G..., do forte, e, muito tolamente, emprestei-lhe a escuta; então será impossível você vê-lo até de manhã. Fique aqui esta noite e mandarei Jup buscá-lo ao nascer do sol. É a coisa mais linda da criação!",
"O que? - nascer do sol?",
"Absurdo! não! - O inseto. É de uma cor dourada brilhante - mais ou menos do tamanho de uma grande noz - com duas manchas pretas perto de uma extremidade do dorso e outra, um pouco mais longa, na outra. As antenas são...",
"Acho que ficaremos sem jantar agora. Mas diga-me, o bug é realmente tão fantástico?",
"Ah, meu amigo é um pouco impulsivo... E sim, a cor é quase suficiente para justificar a ideia de Júpiter. Você nunca viu um brilho metálico mais brilhante do que o emitido pelas escamas - mas isso você não poderá julgar até amanhã. Enquanto isso posso lhe dar uma ideia do formato.",
"O que você está procurando meu amigo?",
"Eu sei que há tinta e uma caneta aqui em algum lugar. Talvez um pouco de papel também.",
"Posso ver...?",
"Claro!",
"Está realmente ficando quente aqui. Você poderia, por favor, diminuir o fogo de alguma forma.",
"Verei o que posso fazer...",
"O tempo está muito frio, então que tal um pouco mais de fogo?",
"O tempo está muito frio, então que tal outro incêndio?",
"Bem! Este é um escaravelho estranho, devo confessar: novo para mim: nunca vi nada parecido antes - a menos que fosse uma caveira ou uma caveira - com o qual se assemelha mais do que qualquer outra coisa que tenha estado sob minha observação.",
"Uma caveira! Ah... sim... bem, tem algo dessa aparência no papel, sem dúvida. As duas manchas pretas superiores parecem olhos, né? e o mais longo na parte inferior, como uma boca - e então a forma do todo é oval.",
"Talvez sim, mas Legrand, temo que você não seja um artista. Devo esperar até ver o besouro em si, se quiser ter alguma idéia de sua aparência pessoal.",
"Bem, eu não sei, eu desenho toleravelmente - deveria fazê-lo pelo menos - tive bons mestres, e me gabo de não ser exatamente um idiota.",
"Mas, meu caro amigo, então você está brincando, este é um crânio muito aceitável - na verdade, posso dizer que é um crânio excelente, de acordo com as noções vulgares sobre tais espécimes de fisiologia - e seu escaravelho deve ser o mais estranho escaravelho no mundo se for parecido com ele. Por que podemos levantar uma superstição muito emocionante com base nessa dica. Presumo que você chamará o inseto de scarabæus caput hominis, ou algo parecido - há muitos títulos semelhantes nas Histórias Naturais. Mas onde estão as antenas de que você falou?",
"A antena! Tenho certeza de que você deve ver as antenas. Eu os tornei tão distintos quanto no inseto original e presumo que isso seja suficiente.",
"Bem, bem, talvez você tenha - ainda não os vejo.",
"---",
"Boa noite meu amigo, vejo que você está cada vez mais absorto em devaneios, dos quais nenhum ataque meu poderia despertá-lo.",
"Bem, eu... o pergaminho... hmm. Júpiter acompanha você no caminho de volta para casa. Até a próxima.",
"Ah, William, seja bem-vindo! Por favor, sente-se. E entre Júpiter, entre.",
"Que bom ver você, Edgar.",
"Agora diga-me, meu velho amigo, o que o traz aqui.",
"Bem, é uma história longa e estranha. Você se lembra do pergaminho que lhe mostrei...",
"Isso existe. Você encontrou as três letras T H E até agora?",
"Sim, mas depois disso fica difícil...",
"Se você for para o segundo THE a partir do final, encontrará esta sequência 'THET EETH'.",
"Sim..?",
"Suponha que o último 'TH' seja o início de uma nova palavra e que descartemos o primeiro 'THE', uma vez que nenhuma palavra pode ser formada da qual este 'TH' possa fazer parte. Somos assim reduzidos à palavra 'T EE'.",
"Essa palavra deve ser 'ÁRVORE' então. Então '(' é a letra R!",
"De fato. Agora olhando além destas palavras, por uma curta distância, temos este arranjo: 'A ÁRVORE THR...H THE'.",
"Sim, eu vejo este lugar...",
"Aqui uma palavra se torna evidente imediatamente. Talvez você devesse dar uma freada (salvar) e consultar aquele papel quadriculado que você tem aí.",
"Ok, mas eu, como...",
"Tenho uma sugestão, velho amigo. Por que você não vai visitar o Sr. Dupin, ele é um velho amigo meu e um investigador muito inteligente.",
"Você quer dizer o famoso detetive? Hmm, onde ele mora?",
"É muito fácil encontrar o William, o escritório dele fica perto dos Portões da Cidade do Porto.",
"Eu vou encontrar isso. Obrigado Edgar e adeus. E, ehh, minha cópia da cifra, se você não se importa...",
"Deixe-me perguntar, você conseguiu descobrir a qual letra corresponde o símbolo 'X'?",
"Não, não tenho a menor ideia.",
"Talvez você devesse tentar novamente. Não se esqueça de verificar o Questbook.",
"Sim, é 'A'",
"Sim, é 'B'",
"Sim, é 'C'",
"Sim, é 'D'",
"Sim, é 'F'",
"Sim, é 'G'",
"Sim, sou 'eu'",
"Sim, é 'J'",
"Sim, é 'K'",
"Sim, é 'L'",
"Sim, é 'M'",
"Sim, é 'N'",
"Sim, é 'O'",
"Sim, é 'P'",
"Sim, é 'Q'",
"Sim, é 'S'",
"Sim, é 'U'",
"Sim, é 'V'",
"Sim, é 'W'",
"Sim, é 'X'",
"Sim, é 'Y'",
"Sim, é 'Z'",
"Muito bom. Talvez você tenha uma ideia sobre o '?' também.",
"Você está realmente indo bem. E '3' qual letra deveria ser essa?",
"Sim, eu também acredito. A palavra deve ser 'THROUGH', esta descoberta nos dá três novas letras. Olhando, agora, de perto, através da cifra, para combinações de caracteres conhecidos, encontramos, não muito longe do início, este 'EGREE'...",
" 'EGRO'?",
"Absolutamente! E mais duas cartas graças a Júpiter. No entanto, sinto muito, querido William, mas tenho que deixá-lo neste exato momento para negócios.",
"Bem-vindo de volta querido amigo! O que posso fazer para você?",
"Obrigado Edgar, você vê que resolvi a criptografia, mas não faz muito sentido...",
"Posso ouvir o que você tem até agora?",
"Aqui está: 'Um bom copo no albergue do bispo, no trono do diabo, quarenta e um graus e treze minutos a nordeste e pelo ramo principal norte, sétimo ramo, lado leste, atire do olho esquerdo da caveira uma linha de abelha da árvore através o tiro a quinze metros de distância.'",
"Hum...",
"Não, o enigma parece ainda estar nas piores condições de sempre. Como é possível extrair um sentido de todo esse jargão sobre 'assentos do diabo', 'caveiras' e 'hotéis episcopais?'",
"Confesso que o assunto ainda assume um aspecto sério, quando encarado com um olhar casual. Meu primeiro esforço é dividir a sentença na divisão natural pretendida pelo criptógrafo.",
"Quer dizer, para pontuar?",
"Por favor, entrem e sentem-se, vocês dois.",
"Obrigado.",
"Algo desse tipo. Você ainda tem um papel limpo?",
"Claro, só um segundo...",
"Refleti que era importante que o escritor reunisse suas palavras sem divisão, de modo a aumentar a dificuldade de solução. Ora, um homem não muito perspicaz, ao perseguir tal objetivo, quase certamente exageraria. Quando, no decorrer de sua composição, ele chegasse a uma ruptura em seu tema que naturalmente exigiria uma pausa, ou um ponto, ele estaria extremamente apto a apresentar seus personagens, neste ponto, mais próximos do que normalmente. Se você observar o MS., no presente caso, você detectará facilmente cinco desses casos de apinhamento incomum.",
"Seguindo essa dica, fiz a divisão assim:",
"Agora, por favor, me dê licença...",
"Claro, e obrigado meu amigo. Eu tenho que pensar sobre isso com muito cuidado.",
"Aha, sejam bem-vindos meus amigos.",
"Edgar, sinto muito por essa intrusão.",
"De jeito nenhum meu amigo. O que eu posso fazer para você hoje?",
"Bem, estamos procurando alguns instrumentos de navegação.",
"A única coisa que tenho é uma bússola velha e pesada...",
"Podemos pegá-lo emprestado por um tempo?",
"Claro, só um segundo...",
"Isso é muito gentil da sua parte, Edgar.",
"Aqui está a Bússola, completa com uma bolsa para carregá-la.",
"Obrigado Edgar.",
"Acho que você está explorando as pistas dessa cifra...",
"Na verdade estamos, por que você não se junta a nós?",
"Parece emocionante, mas hoje tenho um compromisso muito importante.",
"Outro dia então Edgar.",
"E..?",
"Ah, desculpe por essa intrusão, Edgar. Precisamos da sua ajuda...",
"Hmm, só me dê um minuto para me vestir. Talvez você possa esperar lá em cima no meu quarto...",
"Claro. Vamos Júpiter.",
"Deixe-me adivinhar: você descobriu as pistas daquela Cifra e precisa de ajuda para carregar o Tesouro Pirata.",
"!!! Como você pôde adivinhar tudo isso? É ainda mais do que eu sei. Piratas você diz? Por favor, conte-nos mais.",
"O pergaminho que você me mostrou tinha uma figura do que inicialmente imaginei ser uma cabra. Um exame mais minucioso, entretanto, me convenceu de que era destinado a uma criança.",
"Você não encontrará nenhuma ligação especial entre seus piratas e uma cabra - os piratas, você sabe, não têm nada a ver com cabras: eles pertencem ao interesse agrícola.",
"Mas acabei de dizer que a figura não era a de uma cabra.",
"Bem, então uma criança é praticamente a mesma coisa.",
"Praticamente, mas não totalmente. Você já deve ter ouvido falar de um Capitão Kidd?",
"Claro, vá em frente, por favor.",
"Imediatamente considerei a figura do animal como uma espécie de trocadilho ou assinatura hieroglífica. Digo assinatura, porque a sua posição no pergaminho sugeriu esta ideia. A caveira no canto diagonalmente oposto tinha, da mesma maneira, o ar de um selo ou selo.",
"Sim, ouvi muitas histórias sobre o Tesouro do Capitão Kidd. Mas acreditar que eles são verdadeiros..?",
"Você observará que as histórias contadas são todas sobre caçadores de dinheiro, e não sobre caçadores de dinheiro. Se o pirata tivesse recuperado o dinheiro, o caso teria terminado. Tomei como certo, portanto, que a terra ainda os continha e senti uma esperança, quase certa, de que o pergaminho tão estranhamente encontrado envolvia um registro perdido do local de depósito.",
"Você está certo, encontramos algumas coisas estranhas em um lugar chamado Bishop's Hostel. Acontece que isso poderia muito bem ser obra de um pirata.",
"Mas você ainda não pegou o Tesouro?",
"Não, precisamos de mais ferramentas do que uma pá para isso. Há também um problema com um grupo de quilombolas muito hostis. Portanto, também precisamos de armas. E além disso queremos que você se junte a nós nesta caça ao tesouro.",
"Eu te seguirei - isso é tão emocionante. Sobre armas, tenho uma ótima pistola no Ferreiro para reparos. No entanto, não posso pagar por isso...",
"Aqui, pegue sua bússola, talvez você possa trocá-la com o Ferreiro.",
"Obrigado Guilherme. Tenho uma ideia de como podemos encontrar algumas ferramentas sem pagar por elas...",
"Muito bom. Visitarei o Forte em busca de qualquer tipo de arma. Temos alguns sacos velhos vazios em casa, Jup. Você poderia pegá-los, por favor.",
"William, vamos nos encontrar fora dos portões da cidade quando tivermos recolhido todas as coisas.",
"Fora da cidade será.",
"Encontrei estes Pregos na Igreja - talvez você possa usá-los?",
"Sim, por que não Júpiter?",
"Então esta é a Árvore com a Cabeça da Morte?",
"Na verdade é. Agora Júpiter, por favor, faça-nos o favor e suba na Árvore novamente?",
"O que ele está fazendo lá em cima? Está tão silencioso.",
"???",
"Pelo que me lembrei, havia algo sobre ir direto da árvore através do 'tiro'. Mas quanto tempo deveria durar?",
"Tenho que consultar meus papéis.",
"Então, qual deve ser o comprimento da fila?",
"Ehrmm, tenho que verificar novamente...",
"Cinquenta pés.",
"OK. Agora, Júpiter, por favor, pegue a ponta desta fita métrica e se coloque perto da Árvore.",
"Ah",
"Vou esticar a fita métrica quinze metros além da estaca.",
"Muito bom Edgar. Estamos chegando perto agora!",
"Vir! temos que voltar, o jogo ainda não acabou.",
"Isso bastará - devemos tentar novamente.",
"Jup terá que escalar a Árvore das Tulipas novamente.",
"Não, não, vamos apenas colocar outro pino perto do primeiro.",
"Certo, por favor, continue Edgar.",
"O que é isso? O x marca o lugar?",
"Hum, por que não. Vamos mover esses pobres coitados - há algo sob os esqueletos!",
"William, deixe-me tentar com a Picareta.",
"Sim, boa ideia!",
"Sim, isso é estranho, onde estão os quilombolas? Talvez eles tenham perdido a nossa pista?",
"Quem sabe. Temos que ter muito cuidado.",
"Ha, que vitória!",
"O que é Júpiter?",
"Acho que vou sentar um pouco e fazer algumas anotações -",
"- Tive uma ideia da nossa aventura!",
"William, querido amigo, não se preocupe - seja feliz. O Tesouro está seguro, Júpiter apenas o levou para o sótão.",
"Muito bom! E você ainda está acordado Edgar?",
"Sim, me empolguei um pouco com minha escrita. Quando você olhar mais de perto o Tesouro, ficarei muito satisfeito se quiser ouvir meu novo conto.",
"Bem, é claro, Edgar, ficarei feliz em fazê-lo.",
"Ah, e todas as outras coisas que saqueamos dos quilombolas?",
"Júpiter cuidou de tudo. A comida está na caverna, as armas, é claro, no armário de armas e as ferramentas nos baús logo atrás de você.",
"E as coisas mais valiosas?",
"Ele os trouxe junto com o Tesouro para o sótão.",
"",
"",
};
