string DLG_TEXT[110] = {
"Alguma ordem, capitão",
"Nada por enquanto.",
"Estamos felizes em vê-lo, capitão! Pensávamos que todos íamos morrer aqui. Mas pelo menos alguém conseguiu, pelo que vejo",
"Estamos felizes em vê-lo, capitão! Estávamos todos presos aqui esperando para morrer. O pobre e velho Nobby apagou-o esta manhã.",
"Sim, alguns rapazes escaparam, foram pegos e acabaram na mesma prisão que eu. Nós escapamos juntos. De qualquer forma. ",
"Se eu sair desta ilha, precisarei roubar um navio, o que significa que preciso de uma tripulação",
"Você não achou que eu iria te abandonar neste buraco do inferno, não é",
"E agora, capitão?",
"Vocês vão ao porto e encontram algo para roubar para que possamos sair daqui.",
"E o que você vai fazer?",
"Eu estou indo para a taverna. Não, não para ficar bêbado! Deveria haver um navio com folha de pagamento saindo em algum momento e eu quero saber mais sobre isso.",
"Encontramos um navio. Não é muito, mas deve segurar-nos a todos.",
"Muito bem, rapazes! Um navio pequeno é bom, não queremos chamar a atenção na saída. Podemos encontrar algo melhor em #sSantiago#. O que você fez com a tripulação?",
"Nós os amarramos no porão. Podemos libertá-los quando estivermos longe e livres.",
"Cortamos suas gargantas. Vamos jogá-los no mar quando estivermos no mar - não queremos que os corpos sejam lavados e encontrados tão cedo, não é",
"Excelente, exatamente o que eu teria feito.",
"E agora, capitão?",
"Vocês o seguem. Certifique-se de que ele não chegue à taverna, ou pelo menos que não volte.",
"Por que?",
"Porque se ele relatar que a taverna está distribuindo apenas uma bebida grátis para cada homem, não terá o efeito que desejamos, que é toda a tripulação deste navio correndo para se embebedar de graça",
"Há uma multidão passando pelo portão da cidade, vindo nesta direção.",
"Provavelmente a tripulação do navio. Eles ficarão de mau humor por descobrirem que só havia uma bebida grátis para cada um, e também não ficarão felizes em nos ver. É melhor irmos para o mar agora!",
"E agora, capitão?",
"Leve alguém até lá como vigia. No momento em que o 'Siroco' for avistado, precisamos de ir para o mar - não demorará muito a chegar ao porto!",
"'Siroco' à vista, capitão!",
"Certo, rapazes - de volta ao navio, rápido!",
"Quer ajuda, capitão?",
"Não, isso é entre ele e eu. Se ele vencer de forma justa, o navio será dele. Mas se alguém tentar interferir, mate-o!",
"Você fez isso! Você sequestrou a filha do governador!",
"Você fez isso! Você sequestrou o filho do governador!",
"Sim. Agora pegue ",
" para o navio. Intacto! O governador não pagará se",
" for prejudicado de alguma forma, o que significa que se isso acontecer, você terá aulas de natação com tubarões.",
"Bem, quem teria pensado nisso? Você vai se casar? Parabéns meus e dos rapazes, capitão! O rum estará fluindo hoje à noite em sua homenagem, isso é certo!",
"Obrigado. Sim, vá e divirta-se. Eu certamente irei!",
"Sim. Algum gênio colocou a prisão bem perto do portão da cidade. Mova o navio até a praia, então poderemos escapar pela selva e não ter que lutar para abrir caminho pela cidade.",
"O navio está pronto para navegar, capitão.",
"É ",
" já voltou?",
"Não, #spronoun# não se apresentou a bordo.",
"Droga! Provavelmente ainda está na cidade. Preciso voltar e procurar #spronoun2#.",
"Você quer que eu cuide ",
"será enviado até que #spronoun# retorne?",
"Sim por favor. Mas não tente navegar com ele!",
"Nossos navios estão prontos para navegar quando você estiver, capitão",
"Muito bom. Mais navios franceses supostamente estão a caminho daqui. Navegue e siga para #sSanto Domingo#. Mas deixe meu navio onde ela está",
"Você não vem conosco?",
"Ainda não. Não quero deixar os Taíno para enfrentar sozinhos outra invasão francesa.",
"Ainda não. O capitão que capturamos não sabe quantos navios estão chegando, mas se os franceses confiaram em uma única fragata para tomar a ilha, então pode ser apenas outro navio para substituí-la. Se for assim, eu a terei também.",
"E se a nova força francesa for forte demais para você enfrentar?",
"Depois nos vestimos com alguns dos uniformes que capturamos, fingimos ser franceses e saímos daqui sem lutar. Agora vá, saia daqui!",
"Que bom vê-lo novamente, capitão!",
" A frota está aqui, pronta para se juntar a você novamente.",
" Mas você tem estado ocupado, ao que parece. Você tem ",
" envia com você. A frota que você me deixou tem",
". Não posso me juntar a você até que você tenha vendido ou atracado alguns de seus navios atuais.",
"Muito bom, ",
". Obrigado por trazer a frota aqui. Você pode retornar ao seu navio agora.",
"Bom ponto! Vou para o estaleiro agora",
"Você ainda tem muitos navios para mim",
" para me juntar a você, capitão",
"De volta ao estaleiro, então...",
"Tudo bem, capitão. Ordenarei que meus navios se juntem a você imediatamente.",
" Enquanto isso, tenho que convencer os Taíno a lutarem conosco.",
"As tropas francesas estão entrando na passagem que leva ao forte, capitão!",
"Bom, já era hora! Esperemos que os Taíno estejam prontos para fazer a sua parte...",
"Foi uma briga incrível, capitão! Ainda bem que os índios apareceram.",
"Sim, precisarei agradecer ao chefe deles. Mas primeiro vou querer um desses uniformes. Compre um e faça com que toda a tripulação troque também - certamente há muitos uniformes para você escolher!",
"O que nós devemos fazer então?",
"Jogar esses corpos do penhasco - não adianta deixar evidências caso mais franceses vagueiem por aqui. Então volte para o navio. Estarei junto no devido tempo.",
"Olá, capitão! Estávamos indo ver você",
"Oh? Como você evitou acabar na prisão comigo",
"Os soldados estavam mais interessados em você do que em qualquer um de nós. Depois que eles pegaram você, fugimos em direções diferentes - entrei no bordel porque parecia o lugar mais próximo para me esconder.\nQuando anoiteceu, todos nos encontramos. Estávamos prestes a tentar resgatá-lo da prisão, mas ouvimos uma comoção e percebemos que você estava saindo sozinho",
"Bem, um pouco de ajuda teria sido apreciada, mas não importa.",
"Aqui, deixe-me desfazer essas cordas.",
"Pegue esta faca. Consegui nocautear o guarda da escada, mas o da porta está chegando! Mate-o, então poderemos conversar",
"Obrigado...",
"Muito bem, capitão",
"De qualquer modo, quem é você?",
"Assistente de cozinheiro, capitão. Quando ",
"Os homens dele subiram a bordo, pensei comigo mesmo, isso não parece bom, então me escondi em uma caixa. Depois que os barulhos cessaram, saí quieto.\nEles não prestaram muita atenção ao ajudante de cozinheiro. Eu os ouvi dizendo que tinham você no porão, então eu disse a eles que estava vindo aqui para pegar algo para cozinhar. Bati no guarda com a minha frigideira.",
"Por que você não o esfaqueou com a faca",
"Não adianta com uma faca, capitão. Muito bom com uma frigideira.",
"Bem, você não é mais assistente de cozinheiro.",
"Por que não? O que eu fiz errado?",
"Não podemos ter um ajudante de cozinheiro batendo na cabeça das pessoas com uma frigideira. Somente o próprio cozinheiro pode fazer isso. Você acabou de ser promovido.",
"Obrigado, capitão! A propósito, suas coisas foram jogadas perto daquelas caixas.\nEstamos no porto de #sPort au Prince#. ",
" partiu para #sSantiago#. Os outros oficiais e a tripulação foram retirados e estão detidos no forte.\nPosso ajudá-lo a recuperar nosso navio?",
"Não. Quando eu resgatar a tripulação, eles estarão com fome e eu também. Você é o cozinheiro agora - dê uma olhada aqui e veja se consegue encontrar algo para cozinhar.",
"Olá, capitão! Eles pegaram você também?",
"Tipo de. Eu estava preso no meu próprio porão de carga! Mas eu saí, com alguma ajuda, e agora vou tirar você daqui.",
"Como você irá fazer aquilo?",
"Matando qualquer guarda que fique no meu caminho!",
"Tenho um documento forjado que me permite requisitá-los como escravos para trabalharem para mim. Só não conte a ninguém que você já trabalha para mim!",
" Onde todas as suas coisas foram armazenadas?",
"Aquele ladrão #svillain# levou tudo! Provavelmente ainda está em algum lugar do navio.",
"Não se preocupe. Se isso for verdade, você receberá tudo de volta assim que estivermos a bordo.",
"Como planeja nos tirar daqui, capitão? Não podemos ajudar-te a lutar, não temos as nossas armas.",
"Deixe-me lutar. Você observa através daquele portão. Quando eu tiver lidado com os soldados do outro lado, irei para a próxima área. Enquanto isso, você segue até onde acabei de passar. Continuamos assim até sairmos daqui.",
"Estamos felizes por sair daí, capitão! Pensávamos que ficaríamos presos lá pelo resto da vida, o que provavelmente não demoraria muito",
"Eu também tive minhas dúvidas por um tempo. Agora, vamos voltar para o navio e sair daqui!",
"Como você quer fazer isso, capitão",
"Vou jogar uma garrafa de éter naquela caverna. Com alguma sorte, isso derrubará qualquer um na caverna - deve ser mais eficaz em um espaço tão confinado.",
"Me siga. Decidiremos o que fazer quando virmos quem está naquela caverna.",
"Suba lá e veja se há um caminho de volta para a caverna.",
"E então?",
"Se houver, não grite sobre isso! Não queremos alertar quem está lá dentro. Balance sua espada um pouco, isso me dirá que você está pronto. Se você não conseguir encontrar uma maneira de entrar, volte aqui em silêncio.",
"Se eu encontrar uma maneira de entrar, o que vem a seguir?",
"Espere aí até eu entrar. Se você me ouvir gritar 'AGORA' ou se vir a luta começar, entre. Esperançosamente, isso desequilibrará o inimigo o suficiente para impedi-lo de matar a Eleitora. Agora vá, levante-se!",
"Tudo bem, você pode descer agora!",
}
