string DLG_TEXT[28] = {
"Disseram-me que você fez um grande esforço para solicitar uma audiência. Meu nome é ",
". Agora, por favor, diga-me o propósito da sua visita",
".",
"Meu nome é ",
".",
"Então, por que você me distrai dos assuntos de estado muito importantes?",
"Estou aqui apenas para prestar meus respeitos, senhor. Nada mais.",
"Nesse caso, por favor, saia do meu escritório e deixe-me voltar para assuntos mais importantes.",
"Sim claro. Desculpe por ter incomodado você.",
". Você organizou o sequestro de",
", e também providenciou para que eu fosse culpado. Estou aqui para colocá-lo sob prisão. Faça-me um favor e resista à prisão.",
", e também providenciou para que eu fosse culpado. Estou aqui para me vingar do que você fez tanto à Eleitora quanto a mim.",
"Você deseja me prender? Eu sou o governador aqui e você é um pirata desacreditado. É você quem será preso. Guardas!",
"Sua chamada 'vingança' durará pouco, e você também. Você ainda é procurado por sequestro. Guardas!",
"Ah, esqueci de te contar. Estive no seu esconderijo na Península de Zapata. A Eleitora está bastante segura. Eu sei tudo sobre suas relações com ",
".",
". E o mesmo acontece",
". Quanto aos guardas, esses não são seus soldados. Eles são meus.",
"Você deve saber que sou o melhor espadachim de Castela",
".",
"Isso é só porque nunca estive em Castela.",
"Talvez, mas eu sou uma espadachim.",
"E você deve saber que aqui é #sSantiago#.",
"Essa é a sua perda. E agora você nunca vai.",
"Um mero detalhe técnico. Você ainda está na ponta errada da minha espada.",
"Então talvez os melhores e segundos melhores esgrimistas de #sSantiago# estejam agora nesta sala. Somente o primeiro sairá vivo.",
" Saque sua arma e prepare-se para morrer!,",
"Prazer, Dom Emiliano!",
}
