string DLG_TEXT[37] = {
"O que você está fazendo a bordo do meu navio?",
"Desculpe senhor. Voltarei para o meu próprio navio.",
"Não sei quem você é, mas cometeu um erro grave ao embarcar em meu navio.",
"Eu sou ",
", reportando-se conforme ordenado, senhor.",
"Dificilmente. Se você fosse realmente ",
", você estaria com um uniforme adequado.",
"Certamente você não espera que eu acredite nisso ",
" é uma mulher!",
" Guardas! Leve esse espião embora e pendure #spronoun#!",
"Não posso me trocar?",
"Eu sou ",
". Quem é você?",
"Ah, claro. Mas por que o '",
"' aqui não?",
"Enfrentamos vários navios piratas quando chegamos. Afundamos um, capturamos um e um fugiu. Meu navio foi severamente danificado, então eu o enviei ao porto para reparos e assumi o controle do navio que capturamos. Esse é o navio que você viu, senhor.",
"Você não está ciente de que as ordens navais vigentes determinam que o capitão deve permanecer em seu próprio navio? Você deveria ter ficado no 'Joli' e só transferido para o outro navio se o seu estivesse prestes a afundar. Isso terá que ser resolvido quando você chegar ao porto.",
"Desculpe senhor.",
"Agora, vamos aos negócios. Estes são ",
" e ",
". E isso é ",
"Relate suas atividades em #sisland_Isla Mona#, por favor.",
"Sim senhor. Enfrentamos um navio pirata, mas ela fugiu. Em vez de persegui-la ",
"Sim senhor. Após o encontro com os navios piratas ",
"procedemos ao desembarque na ilha. O esquadrão que enviei à aldeia Taíno informou que são pacíficos e não representam qualquer ameaça. Continuamos até o forte, que como você pode imaginar estava em mau estado após décadas de abandono.",
"Na verdade, isso era de se esperar. Continuar.",
"Mandei meus homens começarem a limpar o lugar. Fizemos bons progressos. Então você chegou e entregamos o forte aos seus homens. Minha tripulação já está embarcada e estamos prontos para partir ao seu comando, senhor.",
"Muito bom. Você pode estar se perguntando por que assumimos #sisland_Isla Mona#, uma pequena ilha sem recursos dignos de nota.\n",
"Em breve chegará aos nossos inimigos a notícia de que estamos aqui. Sem interesse comercial nesta ilha, eles concluirão que pretendemos usá-la como base para um ataque a #sSanto Domingo# ou #sIsla Muelle#.\n",
"Eles irão, portanto, movimentar as suas forças para defender essas cidades. E assim, às custas de uma pequena guarnição, fazemos com que o inimigo mova forças muito maiores para o lugar errado. Enquanto isso, nosso verdadeiro ataque será em outro lugar.",
"Podemos saber onde você planeja atacar, senhor? Tenho certeza de que os outros capitães estão tão ansiosos quanto eu para participar desse ataque.",
"Seu entusiasmo deve ser elogiado. Infelizmente nem eu tenho detalhes no momento. A próxima fase está sendo planejada ao mais alto nível. Estou certo de que desempenharemos o nosso papel no devido tempo. Dispensados, senhores, vocês podem retornar aos seus navios.",
"Sim senhor.",
"Seu entusiasmo deve ser elogiado. E é aí que ",
" está envolvido.\nEnquanto a frota segue para #sPort au Prince# para receber suprimentos e novas tropas, ",
" retornará para #sRedmond#. No devido tempo, nossa frota irá para uma praia perto dessa cidade.\n",
" enviaremos homens para emboscar as tropas que guardam o portão de terra e, em seguida, abriremos o portão para permitir que nossas tropas invadam sem que nossos navios tenham que atacar o forte primeiro.\nEm vez disso, nossa força atacará o forte por terra, onde suas defesas são muito mais fracas .\nEm vez de ser um espinho no lado da França, #sRedmond# se tornará uma lança apontada para #sisland_Cuba#.\nDispensados, senhores - vocês podem retornar aos seus navios.",
}
