string DLG_TEXT[18] = {
"É a vida. É a guerra.",
"Isso é uma batata",
"Meu nome é ",
". Seja você quem for, aproveite sua vitória enquanto pode. Será de curta duração. Você também.",
"Eu sou ",
". O que você quer dizer com isso?",
"Somos apenas a guarda avançada. Uma força muito maior está a caminho. Esperamos que chegue em breve. Se você sair agora, você pode evitá-lo.",
"Que tipo de força?",
"Ah, você gostaria de saber, não é? Bem, eu não vou te contar, não importa o quanto você me tortura.",
"Que bom para você, mas não serei eu quem fará a tortura. Ouvi dizer que as mulheres indianas locais têm o costume de untar os corpos das vítimas com mel.",
"Mel? Isso não parece tão ruim - pode até ser divertido!",
"Sim, provavelmente é isso que a população local de formigas também pensa.",
"Formigas? Não por favor! Vou lhe contar o que sei, o que infelizmente não é muito. Sou apenas um capitão de fragata e não sou informado dos movimentos da frota ou da grande estratégia.",
"Então o que você sabe?",
"A força principal é esperada dentro de uma semana - possivelmente até amanhã. Recebi ordens de limpar a ilha dos piratas, pacificar os índios e limpar um pouco da bagunça em torno deste forte abandonado.",
"Sim, obrigado por isso - tornou nossa abordagem muito mais fácil. Mas sobre essa força principal - estou aguardando mais informações e as formigas estão aguardando o almoço. Você vai satisfazer um de nós.",
"Tudo o que sei é que a nau capitânia é um navio de guerra de terceira categoria e que tem uma escolta. Não sei nada sobre a escolta. Não me entregue às formigas, eu imploro!",
"Muito bem. Você será levado para minha nave. Talvez até um capitão de fragata possa pedir um resgate.",
}
