string DLG_TEXT[59] = {
"Arr!",
"Arrr!",
"Bem, bem, veja o que a maré trouxe! Como está a vida do #sbackground# te tratando, ",
"Estou surpreso em ver você de volta aqui ",
". Dizem que você deixou de ser um pirata.",
"Você tem coragem de mostrar seu rosto aqui ",
"! Metade das pessoas aqui iriam roubá-lo com prazer se não estivessem muito ocupadas com seu rum. Eu mesmo faria isso, mas suspeito que você não se arriscou a vir aqui sem motivo, então vá em frente!",
"Não muito mal. Mas preciso da sua ajuda com uma coisa.",
"Isso não me impede de visitar meus antigos amigos, não é? Além disso, espero que você possa me ajudar em alguma coisa.",
"Você está certo aí. Mas não tenho mais para onde recorrer. Eu preciso de ajuda com alguma coisa.",
"Pergunta à vontade!",
"Por que, em nome de todos os demônios do mar, eu iria ajudá-lo?",
"Você me diz. Que razão eu poderia dar para persuadi-lo a me ajudar?",
"Hmm... talvez eu tenha um trabalho para você. Mas primeiro, o que você precisa?",
"O ",
"filha",
"filho",
" do governador de #sSantiago# foi sequestrado. Eu queria saber se você tem alguma ideia de quem pegou #spronoun#.",
"Um #sgovernors_kid#? E você não sequestrou #spronoun# você mesmo?",
"Eu fiz, e você ficaria surpreso com o resultado. Mas agora outra pessoa fez isso e eu tenho a tarefa de recuperar #spronoun#.",
"Tudo bem, vou testar algumas coisas e ver o que consigo descobrir.",
" Enquanto isso, tenho meu próprio favor para lhe pedir. Um dos meus homens ",
", foi pego pelos franceses e está preso na prisão #sPointe a Pitre# em #sisland_Guadeloupe#. E você é o grande fugitivo, a primeira pessoa a sair da prisão de #sHavana# por conta própria. Talvez você consiga ",
" fora também.",
" Em troca, você vai resgatar um dos meus homens ",
", que foi pego pelos franceses e agora está na prisão #sPointe a Pitre# em #sisland_Guadeloupe#. E você é o grande fugitivo, a primeira pessoa a sair da prisão de #sHavana# por conta própria. Então se você tiver ",
" com você na próxima vez que vier aqui, contarei o que descobri sobre a #skid# do seu governador. Caso contrário, você estará procurando um novo rosto.",
"Tudo bem, parece um acordo justo para mim. #sisland_Guadeloupe#, aí vou eu...",
"Paciência, #sladlass#! Vai demorar um pouco até que meus homens me relatem algo útil.",
"Você tem sorte de eu estar de bom humor. Saia antes de mudar isso!",
"Tudo bem, vou continuar com o resgate ",
"Bem vindo de volta! E vejo que você trouxe ",
" com você também. Agora, quanto ao seu problema. Alguém relatou ter visto uma #sperson# que corresponde à descrição do seu #sgovernors_kid# sendo trazida para #sRedmond# por uma gangue de homens armados.",
"Obrigado! Vou ver se alguém em #sRedmond# sabe mais alguma coisa.",
"Bem, você está de volta, e com ",
" também. Bom. Quanto à minha parte do acordo, alguém relatou ter visto uma #sperson# que corresponde à descrição do seu #sgovernors_kid# sendo trazida para #sRedmond# por uma gangue de homens armados.",
"Foi um prazer fazer negócios com você. Vou ver se alguém em #sRedmond# sabe mais alguma coisa.",
"Oi, Maria! Alguém aqui com quem você provavelmente deseja falar!",
"Bela senhora, não é?",
"Olá, ",
"! O que te traz de volta aqui?",
"! Você achou aquele #sgovernors_kid#?",
"Sim, graças à sua ajuda. Na verdade, isso é ",
"<Para ",
"> Prazer em conhecê-lo! <Para você>Agora, o que o traz de volta aqui?",
"Pensei ter deixado claro da última vez que você não é bem-vindo por aqui ",
". Por que você está de volta?",
"Outro sequestro. Alguém capturou o enviado do Sacro Império Romano e preciso descobrir quem. Talvez você saiba?",
"Por que me perguntar? O boato diz que você conseguiu! Muito ousado, devo dizer, embora talvez um pouco ousado demais?",
"Não seja bobo! Se eu a tivesse levado, teria enviado um pedido de resgate pelo maior resgate de que você já ouviu falar.",
"Engraçado você dizer isso. O boato diz que foi exatamente isso que você fez.",
"O boato está errado, então. Eu não a levei, nem enviei nenhum pedido de resgate. Mas estou em apuros, a menos que descubra quem o fez.",
"Desculpe, não posso ajudá-lo nisso. Nenhum dos outros piratas que conheço fez isso, e os piratas que não conheço são pequenos que não ousariam ir atrás de um alvo como esse.",
"Se não foram piratas, então quem?",
"O Sacro Império Romano é o principal membro da Liga de Augsburgo, que basicamente consiste em todos se unindo contra a França. Portanto, apenas a França tem rancor do Império, pelo menos por enquanto.\nTalvez fale com ",
". Ele é o governador por aqui. Oficialmente ele trabalha para a França, então pode ter alguma ideia.",
"Obrigado, vou visitá-lo agora.",
"filha do governador",
"filho do governador",
}
