string DLG_TEXT[45] = {
"Bom dia, ",
"Bom dia.",
"Então, você deve me transportar para #sIsla Muelle#?",
"Sim. A propósito, eu sou ",
"É um prazer conhecê-lo. Agora, quando você chegar em #sIsla Muelle#, não me deixe em terra imediatamente. Você deve encontrar ",
". Mate-o e descarte o corpo para que não seja encontrado. Então irei à terra e tomarei o seu lugar.",
"Quem é ",
"Ele trabalha na área portuária. Você o reconhecerá facilmente, ele é exatamente como eu sou agora. Ele sabe muito, mas tem quase a mesma inteligência de um pombo.",
"Como isso é possível?",
"Bem, por exemplo, ele se lembrará de tudo o que lhe disserem. Se você dissesse a ele quais caixas colocar e onde, ele saberia onde colocá-las. Mas você também precisa dizer a ele para não colocar as caixas grandes em cima das pequenas.",
"Por que precisamos matá-lo? Não posso simplesmente colocá-lo no meu navio e mantê-lo lá?",
"Sim, isso também pode funcionar. Se você conseguir fazer isso sem levantar suspeitas, também significa que não precisa se preocupar em esconder o corpo.",
"E se ele for visto embarcando no navio, será mais fácil deixar o navio. Bom, então é isso que faremos.",
"É ",
" seguro?",
"Sim, ele está seguramente amarrado no meu porão.",
"Bom. Assumirei agora seu nome, seus modos, sua posição aqui. Você pode retornar para #sPort au Prince#. Diga ao governador 'O albatroz está no seu ninho'. Essa é a frase de código que dirá ao #spronoun2# que estou aqui.",
"'O albatroz está em seu ninho'. Muito bem, passarei sua mensagem. Adeus, ",
", ",
", a que devo a honra desta visita?",
"Posso ajudar, ",
"?",
"É sua primeira vez em nossa cidade ",
"? Eu não te vi aqui antes",
"Bom dia. É sua função carregar e descarregar cargas de navios?",
"Sim, ",
". Por apenas 50 moedas de ouro, carregarei ou descarregarei sua carga.",
"Bom. Aqui está o seu dinheiro. Se você me seguir, por favor, mostrarei a carga que gostaria que você descarregasse.",
"Eu conheço você. Foi você quem me trouxe aqui de #sPort au Prince#, certo? Você tem mais pedidos de ",
"?",
"Não, de ",
". Eu sou ",
". Trazer você aqui foi um estratagema necessário, que não é mais necessário. E então você pode voltar comigo para #sHavana#, ou morrer aqui e agora.",
"A hospitalidade da Espanha para com os agentes franceses é bem conhecida. Então lutarei com você aqui.\nNão estou bem armado, então tenho poucas chances, mas uma morte rápida aqui é preferível a uma morte lenta em uma câmara de tortura.",
"Muito bem. Admiro sua coragem. Prepare-se para lutar.",
"Onde está a carga que você deseja que eu descarregue?",
"Não há carga. Você é um espião francês e minha intenção é levá-lo para #sHavana#.",
"Você deve estar enganado, ",
". Eu sou ",
", trabalho aqui como estivador como sempre trabalhei. Se você não tem carga para mim, permita-me retornar ao porto e retomar meu trabalho.",
"Você é ",
". Fui eu quem trouxe você de #sPort au Prince# para cá. 'O albatroz está no ninho', lembra? Bem, o albatroz está prestes a ser retirado do seu ninho.",
"Eu vejo. Mas não tenho intenção de chegar perto de #sHavana#. ",
"Muito esperto! Mas você não vai me pegar vivo. Você não vai me fazer trair meu país. Viva a França! <gole>",
"Tóxico!",
}
