string DLG_TEXT[49] = {
"Bom dia, ",
"Bom dia, Capitão.",
"Bom dia. Você é ",
"Sim. Quem é você e por que me procura?",
"Eu sou ",
". ",
" me mandou aqui. Eu serei sua escolta.",
"Ah bom. Disseram-me que uma escolta me encontraria aqui, mas, para ser sincero, esperava um oficial da marinha espanhola. Sem ofensa.",
"Nenhum levado. Eu disse praticamente a mesma coisa para o ",
". Ele parecia pensar que eu era adequado para a missão, então aqui estou",
"Muito bem. Se você quiser se juntar a mim em minha cabine, apresentarei você ao enviado do Sacro Império Romano e explicarei nossos planos.",
"Vá em frente, então!",
"Bem-vindo a bordo do '",
"'. E posso apresentar ",
".",
"Não apenas uma senhora, Capitão ",
". Compartilhe esta informação com ninguém fora desta cabana. Esta é a filha do imperador Leopoldo. E o endereço correto seria 'Vossa Alteza'.",
"Você entenderá agora o significado da sua missão.",
"Mas o que a filha do Imperador está fazendo no Caribe?",
"Essa não é sua preocupação. Você só precisa saber que se alguma coisa acontecer com Sua Alteza, cabeças vão rolar, começando pela minha. E o seu.",
"Ponto tomado. Para onde vamos navegar?",
"Já é tarde. Volte aqui amanhã de manhã e eu lhe darei suas instruções.",
"Muito bem, vejo você amanhã.",
"Hoje, Sua Alteza conduzirá seus negócios com o governador. Vamos acompanhá-la até a residência.\nQuando ela estiver em segurança lá, você estará livre para cuidar de seus próprios assuntos aqui em #sIsla Muelle#. Quando estiver pronto para navegar, encontre-me novamente no cais. Eu deveria então ser capaz de lhe dizer nosso próximo destino.",
"Muito bem, vamos para a residência.",
"Obrigado por nos trazer aqui, Capitão ",
". Sua Alteza agora verá o governador. Não devemos ser perturbados. Nos encontraremos amanhã no cais. Até então saberei para onde Sua Alteza deseja ir em seguida e lhe direi. Eu gostaria de partir cedo, por favor.",
"Muito bem. Eu mesmo tenho coisas para fazer em #sIsla Muelle#. Vejo você no cais amanhã, então. Pelo menos não houve nenhum problema no caminho até aqui.",
"Ah, aqui está você, capitão. Você fez o que queria fazer aqui?",
"Sim, estou pronto para navegar. Para onde vamos?",
"Nosso próximo destino é #sSanto Domingo# em #sisland_Hispaniola#.",
"Muito bem. Vamos navegar e esperar uma viagem tranquila.",
"De fato. E quando chegarmos em #sSanto Domingo#, você poderia se juntar a mim para escoltar Sua Alteza até a prefeitura?",
"Certamente.",
"Onde está a Eleitora?",
"O que? Ela está desaparecida! Esse ataque deve ter sido uma diversão.",
"E nós caímos nessa. Enquanto lutávamos contra os atacantes iniciais, alguém sequestrou o enviado.\nNão temos escolha. Devemos retornar a #sHavana# e reportar isso a ",
"Muito bem, embora eu suspeite que ele ficará muito infeliz",
"Graças a Deus, Sua Alteza está segura",
"Sim, esse ataque foi apenas uma diversão. Enquanto estávamos ocupados, alguém tentou sequestrá-la. Felizmente, ele falhou.",
"Devemos levar a enviada à prefeitura rapidamente, para que não haja mais tentativas contra ela",
"Concordo.",
"Provavelmente você desejará descansar após sua provação, Alteza?",
"Então navegaremos para #sHavana# daqui a dois dias. Por favor, esteja pronto para navegar de manhã cedo, Capitão ",
"Como quiser, Capitão ",
". Isso me dá tempo para reabastecer os suprimentos do meu navio.",
"Sua missão deveria ser escoltar o '",
"', mas você tem muitos navios em sua frota. Você deve vender ou atracar alguns deles se quiser se juntar a mim.",
"Muito bem, irei visitar o estaleiro.",
}
