string DLG_TEXT[94] = {
"Bom dia, ",
"Olá, ",
"Bem bem. ",
". Você está fazendo negócios com o governador de #sPort au Prince#?",
"Não é o que parece. Enfim, quem é você?",
"Eu sou ",
", enviado por ",
" para prendê-lo pelo sequestro de ",
". E agora também para traição. Renda-se de uma vez!",
"eu não peguei ",
", e não posso ir com você até descobrir quem foi. De qualquer forma, você acha que pode me levar sozinho?",
"Não, mas não estou sozinho. Homens - obtenham #spronoun2#!",
"Mal movimento, ",
"Parar! Eu me rendo!",
"Quem é você? O que está acontecendo?",
"Eu realmente não trabalho par ",
". Trabalho para o governador de #sSantiago#.",
"Absurdo! Eu sei Governador ",
" muito bem. Ele nunca enviaria alguém como você atrás de mim.",
" não é mais governador de Santiago. Você é suspeito de tomar ",
", e como seu relacionamento com ",
" é conhecido, ele também é suspeito. Então ele foi preso e ",
" agora é governador de #sSantiago#.",
"Mas eu não peguei ",
"Não, eu fiz. Depois, certifiquei-me de que havia muitas testemunhas quando disse em voz alta aos meus homens que estava trabalhando para vocês",
"Mas por que? O que ",
" tem contra mim?",
"Você não entende, não é? Isto não é sobre você. Você é apenas uma ferramenta útil.\nQuando ",
" soube da chegada d ",
" nesta região, ele viu uma chance de se tornar governador de #sSantiago# como um passo em direção a uma posição na corte real espanhola.\nEntão, depois que eu capturasse você, ele iria 'resgatar heroicamente' a Eleitora, bem como reivindicar crédito pela sua captura. Ou morte.",
"Eu não gosto de ser usado. Mais especificamente, se você pegou a Eleitora, onde ela está?",
"Os meus homens estão detendo-a numa caverna perto da Península de Zapata.",
" O navio dela também está lá.",
"Obrigado. Isso é o que eu queria saber.",
"O que você vai fazer agora? Você vai me matar?",
"Não, preciso de você vivo para testemunhar tudo isso. Você será levado a bordo do meu navio. Faça qualquer tentativa de escapar e partes de você serão jogadas ao mar para alimentar os tubarões",
"Ah, capitão ",
". Eu me perguntei quem se apresentaria jogando uma garrafa aqui. Felizmente vi a garrafa entrando e fui rápido o suficiente para prender a respiração. Sua presença significa que a fumaça provavelmente se dispersou.",
"Seja você quem for, renda-se! Não há para onde você correr. Nós temos o seu navio.",
"Eu sou ",
". E eu tenho ",
". É você quem vai se render, ou eu a matarei.",
"Eu não posso fazer isso. Todo mundo pensa que eu a levei, então estou em apuros até levá-la para #sHavana#. Se você não se render, terei que tentar da maneira mais difícil. Ou talvez possamos fazer um acordo para que ambos consigamos o que queremos. Que resgate você exige pela libertação dela?",
"Não se trata de resgate. Quase não é sobre você. Meu empregador conhece sua associação com o ex-governador ",
". Ao implicar você no sequestro, nós o desacreditamos, então ele perdeu o cargo, deixando o cargo de governador de #sSantiago# aberto para meu empregador.",
"Muito esperto.",
"Fica melhor. Meu empregador, no devido tempo, levará a Eleitora de volta para #sHavana#, alegando tê-la resgatado. Como herói, sua posição como governador de #sSantiago# será apenas um passo em direção a uma posição na corte real espanhola",
"Oh? Então você está com mais problemas do que eu pensava. Quando eu estiver morto ou totalmente desacreditado, você e sua gangue se tornarão os únicos que poderão contar a verdade a alguém. Seu chefe não vai querer deixá-lo vivo. Ele irá matá-lo durante o 'resgate heróico' ou enviará assassinos atrás de você. Então aqui está o acordo. Você mão ",
" para mim. Eu saio daqui e deixo você ileso.",
"Supondo por um momento que eu considerei tal acordo, que garantia tenho de que, uma vez que você tenha o refém, você não me atacará de qualquer maneira",
"Você parece saber sobre mim, então conhece minha reputação. Eu mantenho minha palavra. Então você tem minha palavra de que se a Eleitora for liberada para mim ilesa, você também não será prejudicado",
"O que você pretende fazer comigo e com meus homens se eu entregar a Eleitora a você?",
"Nada. Ou, se preferir, posso levá-lo a bordo do meu navio. Então eu posso te libertar onde você quiser.",
"Tudo bem. Parece que não tenho muita escolha. Se você me der sua palavra de que me levará para #sTortuga#, eu libertarei a Eleitora para você.",
"Você parece saber sobre mim, então conhece minha reputação. Se você matar a Eleitora, eu mato você, lenta e dolorosamente.",
"E se eu liberasse a Eleitora para você?",
"Eu poderia usar um homem como você. Então junte-se a mim como oficial. Depois que você assinar os artigos, não posso matá-lo sem um bom motivo, caso contrário minha equipe saberia que suas próprias assinaturas nos artigos não valem nada e eu teria um motim naquele dia",
"Parece bom. Quer eu mate a Eleitora ou a entregue a você, estou desempregado. Aceitar um novo emprego com você parece ser minha melhor jogada.",
"Uma escolha sábia. Mais uma coisa: quem é seu empregador? Tenha em mente que ele não ficará satisfeito com você, então provavelmente será do seu interesse se eu souber quem ele é para poder lidar com ele",
"Bom ponto. O nome dele é ",
"Obrigado. Agora, ajude-me a tirar a Eleitora daqui para que eu possa reanimá-la.",
"Você manteve sua palavra, então.",
"Sim. Eu sempre faço.",
"Mesmo assim, é um alívio estar aqui. Sem ressentimentos, espero? Você sabe como é no nosso negócio. Talvez nos encontremos novamente - talvez até estejamos do mesmo lado.",
"Isso é improvável, embora coisas mais estranhas tenham acontecido. Mas por enquanto é um adeus.",
"Olá, capitão ",
"! Que bom que você se juntou a nós.",
"Tal conversa! Parece que você pretende nos trair. Você está deixando os homens nervosos. Devíamos continuar esta conversa lá fora.\n<Para sua gangue> Homens, fiquem aqui. Se eu não voltar em 10 minutos, mate o refém.\n<Para você> Bem? Devemos ir?",
"Muito bem, siga-me.",
"Eu sou ",
". Como você provavelmente já deve ter adivinhado, aquele pequeno show foi para o benefício de ",
". Se você valoriza a vida dela, você deveria ir embora agora.",
"Você percebe que seu empregador provavelmente lhe pagará com um tiro na cabeça? Quando eu estiver morto ou totalmente desacreditado, você será a única pessoa que poderá contar a alguém o que realmente aconteceu, e seu empregador não vai querer arriscar isso. Então aqui está o acordo. Você mão ",
" para mim. Eu vou levá-la e ir embora, e você não será prejudicado",
"Mesmo que eu aceitasse tal oferta, meus homens não aceitariam. Eles vão querer algo para mostrar por todos os seus esforços.",
"Tudo bem. Quanto seu empregador afirma pagar por tudo isso? Eu igualarei esse valor, desde que você me diga o nome dele.",
"Devemos receber 100.000 em ouro. Você consegue igualar isso?",
"Sim, eu tenho isso.",
"Mais uma coisa. Que garantia tenho de que, se eu libertar o refém para você, você não nos atacará",
"Você sabe sobre mim, então conhece minha reputação. Eu mantenho minha palavra. Quando eu tiver a Eleitora, você tem minha palavra de que irei embora. Ou, se preferir, posso levá-lo ao porto de sua preferência.",
"Você sabe sobre mim, então conhece minha reputação. Se você matar a Eleitora, eu mato você, lenta e dolorosamente. Mas se você a libertar, posso lhe oferecer um emprego - um homem como você seria útil para mim",
"Muito bem, temos um acordo. Primeiro me dê o dinheiro e eu lhe direi o nome do meu empregador. Depois voltarei para a caverna e trarei o refém. Depois disso, você me levará para #stortuga#.",
"Muito bem, temos um acordo. Primeiro me dê o dinheiro e eu lhe direi o nome do meu empregador. Depois voltarei para a caverna e trarei o refém. Depois disso, me juntarei a você como oficial.",
"Aqui está o dinheiro. Agora, sobre o seu empregador?",
"O nome dele é ",
". Agora, espere aqui enquanto eu trago o refém.",
"Vou esperar. Não me faça entrar para buscá-la.",
"Isso é demais! Primeiro vou matar você aqui, depois vou entrar e pegar a Eleitora eu mesmo.",
"Você não deveria ter tentado lutar. Prepare-se para morrer!",
"Um de nós está prestes a morrer, e não sou eu!",
"Bem, capitão ",
", aqui está a Eleitora. Você manterá sua parte do acordo?",
"Sim. Siga-me até meu navio e eu o levarei para #sTortuga#.",
"Sim. A partir de agora você é um membro da minha tripulação, com os mesmos direitos e obrigações que qualquer outro.",
}
