string DLG_TEXT[211] = {
"Eu sou ",
" Você tem negócios com a Marinha Espanhola? Se não, por favor saia, pois estou muito ocupado.",
"Desculpe, ",
". Vou embora agora.",
"Sim. Eu sou ",
". Fui questionado por ",
" para trazer isto, que tirei do edifício naval em #sPointe a Pitre#, #sisland_Guadeloupe#.",
"Sim, recebi uma carta sobre você. Quanto ao que você trouxe, o valor militar rende 5.000 piastras. Os documentos",
" diga-me tudo o que preciso saber sobre um próximo ataque francês a #sSantiago#.\nInfelizmente, o ataque será liderado pelo '#swarship#'. Não temos nada disponível que possa corresponder a ela. ",
"\nPor favor, saia agora. Devo considerar o que fazer sobre isso.",
"Muito bem. Adeus e boa sorte, ",
"\nMas presumo que você é o tipo de #sperson# que corre riscos por dinheiro. Se sim, talvez você possa ajudar.",
"Isso dependeria do risco e do dinheiro.",
"Ambos estão altos. Preciso que você volte para #sSantiago# e evacue o governador.",
"\nTenho apenas dois navios disponíveis no momento. Se você concordar, ordenarei que ambos naveguem com você caso encontrem a frota francesa.",
"Então partirei imediatamente para #sSantiago#. É melhor você levar o dinheiro a sério ",
"Desculpe, mas nenhuma quantia de dinheiro vale o risco de enfrentar o #swarship#. Não faz muito sentido ter uma pilha de ouro se você não estiver vivo para gastá-lo",
"Por que você ainda esta aqui?",
". Trouxe isto, que tirei do edifício naval em #sPointe a Pitre#, #sisland_Guadeloupe#.",
"Bom trabalho, ",
"! Como recompensa, aqui estão 5.000 piastras. Os documentos que você trouxe",
" oferecer minha assistência na defesa de #sSantiago#. Ele acredita, assim como eu, que tendo tomado #sRedmond#, os franceses atacarão #sSantiago# em seguida.",
"Essa é a minha avaliação também. Sem dúvida o '#swarship#' liderará o ataque como fez em #sRedmond#. E não temos nada disponível que possa aceitá-la.",
"Então não faz muito sentido eu estar aqui.",
"Não é assim, capitão. Você será bem pago se retornar a #sSantiago# e evacuar o governador.",
"Bom dia, ",
"Ah, ",
", você chegou em um momento especialmente útil. Tenho uma missão para você, se estiver interessado.",
"Sempre interessado, se o dinheiro estiver certo.",
"Sim, bem. Um dos nossos navios entrou recentemente nas Caraíbas, transportando um enviado do Sacro Império Romano. Você deve se encontrar com este navio e escoltá-lo aqui para #sHavana#.",
"Uma simples missão de escolta? Certamente, com toda a força naval espanhola no Caribe para escolher, você poderia encontrar alguém mais adequado?",
"Eu poderia, talvez. Agora escute. Esta missão é da maior importância, pois muitas pessoas, começando pelos franceses, ficariam felizes se o enviado desaparecesse no caminho.\nO governador de #sSantiago# recomendou-te pessoalmente. Você provou sua habilidade e sua lealdade à Espanha. Você pode considerar esta missão uma grande honra.",
"Prefiro considerar isso altamente gratificante. Qual é o pagamento desta missão, se ela é tão importante?",
"50.000 piastras, mais o prêmio em dinheiro de qualquer coisa que você capturar quando tentar atacar o navio.",
"Muito bem, eu aceito. Qual é o nome do navio e onde posso encontrá-lo?",
"Isso é tudo? Posso conseguir mais do que isso como prêmio em dinheiro para o próximo navio inimigo que encontrar",
"Como desejar, embora eu imagine Governador ",
" ficará desapontado com sua reação.",
"Muito bem, odiaria desapontar o governador. Conte-me mais sobre este navio que você quer que eu escolte.",
"Adeus, ",
"Excelente! O navio é o '",
"', comandado por ",
". Você a encontrará em #sIsla Muelle# em #sisland_Isla Muelle#. ",
" lhe dará mais instruções quando você o encontrar. Boa sorte, Capitão!",
"Obrigado, ",
". Partirei para #sIsla Muelle# o mais rápido possível.",
"A morte de ",
" enquanto estiver sob a sua suposta protecção terá consequências importantes, não apenas aqui, mas em toda a Europa. A única forma de evitar uma crise com o Sacro Império Romano é oferecer ao Imperador os chefes dos responsáveis. Isso inclui o seu.",
"Suponho que não poderia pedir desculpas ao Imperador?",
"Sua cabeça morta se desculpará. O chefe do ex-governador ",
" lhe fará companhia. Esperemos que o Imperador aceite as suas 'desculpas'. Adeus.",
"Bom dia, vocês dois! Eu confio nisso ",
" está a caminho em segurança para se encontrar com nosso governador?",
"Infelizmente não. Fomos atacados em #sSanto Domingo#. Enquanto lutávamos contra uma gangue, alguém se esgueirou por trás de nós e a sequestrou. Achamos que você deveria ser informado para que uma busca pudesse começar.",
"Ah, você pode ter certeza que uma busca será realizada. Mas nenhum de vocês fará parte disso.\nVocês dois estão presos. Enquanto estiverem em suas celas, sugiro que vocês orem para que ",
" é encontrado vivo e ileso. Caso contrário, vocês dois pagarão por esse fracasso com suas vidas. Guardas!",
"Talvez não devêssemos ter voltado aqui afinal...",
". Como vai sua missão de proteger ",
"O '",
"' partiu #sSanto Domingo# sem mim. Mas não a vi no porto. Ela foi embora de novo? Se sim, e se você ainda quiser que eu a acompanhe, você precisará me dizer para onde ela foi agora.",
"O '",
"' partiu sem você, você diz? Acho isso difícil de acreditar.",
"Capitão ",
" disse que queria sair mais cedo. Talvez eu não tenha chegado cedo o suficiente.",
"Se isso fosse verdade, ele não teria ido embora. Ele poderia ter batido na porta de sua cabana ou taverna para ver se você estava bêbado. Mas ele não teria partido sem você",
"Então onde está o '",
"'?",
"Essa seria minha próxima pergunta. Essa nave aparentemente desapareceu enquanto estava sob sua proteção. Podemos presumir que a Eleitora estava a bordo naquele momento. Você está preso. Enquanto estiver em sua cela, sugiro que você reze para que ela seja encontrada viva e ilesa. Caso contrário, você pagará por esse fracasso com sua vida. Guardas!",
"Talvez eu não devesse ter voltado aqui afinal...",
"Houve um desenvolvimento no seu caso ",
"Você achou ",
"Não, ainda procuramos por ela. Mas agora há provas de que você não apenas falhou em proteger o '",
"', você foi pessoalmente responsável por roubá-la.",
"Não, ainda procuramos por ela. Mas agora há provas de que você não apenas falhou em proteger a Eleitora, mas também foi pessoalmente responsável pelo seu sequestro",
"Deve haver algum engano!",
"Sim, e era seu. E possivelmente também o erro de ",
". Da sua culpa não há dúvida - uma vez pirata, sempre pirata, ao que parece. Tudo o que resta agora é determinar se Don ",
" foi outra vítima do seu engano ou esteve ativamente envolvido na sua conspiração.\nVocê será interrogado mais tarde. Uma investigação mais aprofundada determinará se Don ",
" perderá a cabeça ou apenas o emprego. Adeus, ",
"Espere! O que é essa evidência contra mim? Voltar!",
"Ah, Capitão ",
", finalmente temos você de volta. Embora eu esteja surpreso que você tenha entrado direto em #sHavana# para ser pego tão facilmente.",
"Estou aqui para limpar meu nome ",
". Como você pode ver, eu trouxe ",
" Comigo.",
"Você realmente acredita que isso irá isentá-lo de sequestrá-la em primeiro lugar",
"Eu não a sequestrei. Você provavelmente já ouviu falar de pessoas que ouviram os sequestradores alegando trabalhar para mim. Eles fizeram questão de dizer isso, em alto e bom som, precisamente para que você acreditasse que fui eu quem levou a Eleitora. A intenção deles era que eu assumisse a culpa.",
"E ainda assim temos aqui um pedido de resgate, assinado por você.",
"Você pode ter um pedido de resgate com meu nome, mas não fui eu que o escrevi",
"Tudo bem, suponha que eu acreditasse em você. Você provavelmente fez muitos inimigos durante sua carreira. Você deseja nomear um deles como responsável pelo sequestro",
"Não, ",
". Você deve se lembrar de que me disse que, por causa de sua associação comigo ",
" também estava sob suspeita. Esse, de fato, foi o motivo do sequestro. E o homem por trás disso é ",
".",
"O governador de #sSantiago#?",
"O governador substituto. Ele planejou toda a trama justamente para assumir o cargo de governador, como um passo em direção a um cargo na corte real espanhola. Se eu não tivesse resgatado a Eleitora, o plano dele era coletá-la, apresentá-la aqui e alegar que ele mesmo a resgatou",
"Você percebe que esta é uma acusação séria? Por que eu deveria acreditar em você? Você parece estar fazendo exatamente a afirmação que diz Don ",
" teria feito.",
"Não faria sentido eu ter feito isso. Eu já tinha status na Espanha; é por isso que você me pediu para escoltar a Eleitora. Eu deveria jogar tudo isso fora e depois voltar aqui só para tentar recuperar o que já tinha? Absurdo!",
"Vossa Alteza defende bem o Capitão ",
". Então, o que você gostaria que eu fizesse?",
"Muito bem, isso parece justo. ",
"Enviarei um esquadrão de soldados para prender ",
", e ",
" será restaurado ao cargo. Enquanto isso, ",
", seu status será restaurado. Seus oficiais ",
"e navio",
"e navios",
" será lançado.",
".",
", Tenho um favor a pedir. Você entenderá que tenho um interesse pessoal em ",
". Posso liderar os soldados que irão prendê-lo?",
"Sim certamente. É mais provável que ele resista à prisão se você estiver lá, o que evitará quaisquer... complicações... em levá-lo a julgamento.",
"Obrigado, ",
". Em breve irei a #sSantiago# para levá-lo à justiça, seja julgamento em tribunal ou julgamento em combate.",
"Você não precisará prender ",
". Já fiz uma visita a ele. Basta organizar um funeral.",
"Fora de questão! Esse navio será necessário para transportar Sua Alteza de volta à Europa.",
"Isso é muito gentil, Alteza.",
"Já que você é tão insistente, Alteza, concordo com seu pedido. Deveria ser possível encontrar outro navio para levá-lo para casa.",
"Próximo, ",
", discutiremos seu pagamento. Originalmente, você receberia 50.000 piastras por escolta ",
". Nisso você falhou, pois ela foi sequestrada enquanto estava sob sua proteção. No entanto, como você também foi responsável pelo resgate dela, e levando em consideração o relato dela sobre sua conduta, estou preparado para pagar-lhe metade desse valor.",
"É justo, suponho.",
"Não! Exijo o pagamento integral!",
"Uma escolha sábia ",
".",
"Estou aliviado por ter meu bom nome de volta ",
". E meus oficiais.",
"Você deseja manter o contrato original? Muito bem. Como eu disse, ",
" foi sequestrado enquanto estava sob sua proteção. Você falhou na missão. Portanto, você não receberá nenhum pagamento. Que isso sirva de lição caso você queira testar minha paciência novamente.",
"<Pensa: é melhor eu não reclamar mais, caso ele decida não devolver meus navios também.>",
"Agora há a questão dos navios. Primeiramente, após sua prisão, você escapou de #sisland_Cuba# em um navio de propriedade de ",
".",
"Então foi daí que veio o navio!",
" ele mesmo me deu aquele navio!",
"Hmm... Bem, você ficará satisfeito em saber disso ",
" não pretende apresentar quaisquer acusações. No entanto, ele gostaria de ter seu navio de volta.\n",
"Como você tem um navio assim em sua frota, seria mais simples trocá-lo pelo seu navio original, o '",
"'.",
"Sim, por mim está tudo bem. Posso reorganizar minha frota mais tarde, se quiser",
"Como você não tem esse navio, seria mais simples comprar um substituto para ele. Ordenarei ao estaleiro que forneça uma embarcação semelhante se você me der 18.500 piastras para cobrir os custos.",
"Muito bem, e por favor dê ",
" meus agradecimentos pelo empréstimo de seu navio.",
"Infelizmente não tenho tanto.",
"Provavelmente o resultado de muitas decisões erradas de sua parte, como recusar minha oferta de pagamento parcial! Se você for um capitão tão malsucedido, sua própria tripulação provavelmente irá puni-lo suficientemente. Então eu mesmo pagarei pelo navio substituto.",
"Obrigado, ",
". Além disso, por favor, dê ",
"Você mesmo estava no comando daquele navio, então sua nau capitânia original, a '#sflagship#', será atribuída a você.",
" estava no comando daquela embarcação e será designado para o comando de sua nau capitânia original, a '#sflagship#'.",
"Sua nau capitânia original, a '#sflagship#', foi transferida para o comando de ",
", um de seus oficiais.",
", que foi colocado no comando daquele navio enquanto ele estava internado e que agora será transferido para o seu comando.",
" No entanto, não há espaço em sua frota para que o '#sflagship#' seja transferido para você agora. Você precisará vender, atracar ou desmantelar um de seus navios primeiro.",
"Você mesmo estava no comando do '#sgalleon#', então sua nau capitânia original, a '#sflagship#', será atribuída a você.",
" estava no comando do '#sgalleon#' e será atribuído o comando de sua nau capitânia original, a '#sflagship#'.",
"Como você optou por desistir do '#sgalleon#', sua nau capitânia original, a '#sflagship#', será transferida de volta para o seu comando pessoal.",
"E o resto dos navios que me foram tirados quando fui preso",
"De acordo com os registros, você tinha ",
" navios antes de sua prisão. ",
" navios antes de sua prisão, incluindo o '#sflagship#' que ainda não foi transferido para você.",
" Você tem atualmente ",
" enviar.",
" navios.",
"apenas o '#sflagship#', que será atribuído de volta a você.",
"apenas o '#sflagship#', que ainda não foi reatribuído a você.",
" Não deverá haver problemas em devolver sua frota original para você.",
"Sua frota atual é muito grande para permitir que seus navios originais sejam devolvidos. Você deve vender ou atracar alguns de seus navios atuais para que seus navios originais possam ser devolvidos.",
"Você precisará vender ou atracar toda a sua frota atual para que seus navios originais sejam devolvidos.",
"Obrigado, ",
". Até logo.",
"Muito bem, ",
". Vou visitar o estaleiro agora.",
"Estou pronto para recuperar minha frota agora ",
".",
"Você nem tem espaço na sua frota atual para receber seu carro-chefe original!",
"Seu carro-chefe original já foi devolvido a você ",
".",
"Sim, agora é possível devolver seus outros navios para você.",
", fui preso ",
". Ele tentou resistir à prisão e eu tive que matá-lo",
"Oficialmente, teria sido melhor se você pudesse levá-lo a julgamento. Extraoficialmente, significa que não preciso providenciar transporte para ele para a Espanha, nem haverá qualquer constrangimento causado por tal julgamento.",
" já foi liberado e está a caminho de #sSantiago# neste momento. Agora, há mais alguma coisa?",
"Não, ",
", isso é tudo que eu queria relatar.",
"Eu queria saber se você tem outra missão para mim ",
".",
"Talvez. Temos motivos para acreditar que os franceses plantaram um espião em #sIsla Muelle# em #sisland_Isla Muelle#, mas não temos ideia da identidade ou localização desse espião. Como você tem associados em lugares incomuns para um servo da marinha espanhola, talvez tivesse mais sucesso em descobrir esse espião?",
"Hum... sim, acho que posso ajudar com isso.",
"Excelente, ",
". Haverá uma pequena recompensa se você puder trazer informações úteis sobre o espião e uma grande recompensa se você mesmo conseguir localizar e neutralizar o espião",
"A pequena recompensa provavelmente não vale meu tempo, então tentarei a grande",
"Você pode precisar disso. Diz a quem lê que você está agindo sob minha autoridade. O governador de #sIsla Muelle# provavelmente será mais cooperativo se você mostrar o documento a ele.",
"Obrigado, ",
". Vou sair agora para começar minha investigação.",
"Ah, ",
", você voltou. Isso significa que você tem algo a relatar sobre o espião em #sIsla Muelle#?",
"Não, ",
". Ainda estou trabalhando nisso.",
"Sim, ",
". O nome do espião era ",
". Ele estava se passando por um estivador chamado ",
". Eu encontrei o verdadeiro ",
" e o trouxe de volta para #sIsla Muelle#. Os soldados tentaram prender ",
" mas ele engoliu veneno antes que pudesse ser levado. Ele está morto.",
". Fingi acreditar que o espião era mesmo o estivador, convidei-o a subir a bordo do meu navio com o pretexto de descarregar a carga e depois disse-lhe que sabia quem ele era. Ele tentou lutar comigo, então tive que matá-lo.",
"Hmm... teria sido melhor se isso ",
" poderia ter sido trazido vivo para nos contar mais sobre as operações de espionagem francesas. No entanto, você fez bem em eliminá-lo. Aqui está sua recompensa.",
"Obrigado, ",
". E agora devo ir embora. Adeus.",
"Seu carro-chefe original, o '#sflagship#', foi devolvido a você.",
}
