string DLG_TEXT[23] = {
"Saia agora se você valoriza sua vida!",
"Engraçado, era isso que eu ia dizer para você.",
"Onde é ",
"? Eu te aviso: um movimento em falso e mataremos o refém.",
" está morto.",
" é meu prisioneiro.",
"Eu não sei onde ",
" é. Mas",
" Eu peguei seu navio. A única maneira de você sair daqui vivo é se você libertar ",
" para mim.",
"Oh? E assim que o fizermos, você vai nos matar de qualquer maneira",
"Se você sabe alguma coisa sobre mim, sabe que mantenho minha palavra. Além disso, até onde eu sei, não há recompensa para nenhum de vocês, então lutar com vocês não me traz nada. Então você tem minha palavra de que se você deixar ",
" saia comigo, eu sairei daqui e te deixarei ileso.",
"Talvez. Mas existem diferentes maneiras de morrer. Se você prejudicar ",
", farei com que você morra lentamente, choramingando e gritando, implorando pelo momento em que eu colocar uma faca em sua garganta e, acima de tudo, desejando que você tivesse se rendido ",
" para mim. Esta é a sua chance de evitar esse destino.",
"Não! Não confiamos em você e, de qualquer forma, podemos enfrentá-lo.",
"Seus tolos! Agora morra como os ratos que você é!",
"Seus tolos! Agora morra como os ratos que você é! AGORA!",
"E então o que acontece conosco? Preso aqui sem saída da praia e sem saída pela selva?",
"Você poderia se juntar à minha tripulação. Eu poderia usar mais algumas mãos, e você está desempregado no momento.",
"<Para o resto da turma> O que vocês dizem, rapazes? Nós nos juntamos a essa #sperson#? <murmúrios de concordância> Tudo bem, nós concordamos. Nós nos juntaremos a você.",
"Muito sensível. Vá para a praia. Seguirei em breve.",
}
