string DLG_TEXT[23] = {
"Para o diabo com você! Estou tentando aproveitar minha bebida e você está no caminho da minha luz.",
"Calma aí! Continue bebendo, tenho outras coisas para fazer.",
"Aguentar! Eu só quero conversar, e pode haver algum dinheiro para você.",
"Bom, sobre o que você quer falar que possa envolver dinheiro?",
"Disseram-me que você viu um templo maia nesta ilha. Isso é verdade?",
"Sim, e eu mal consegui sair vivo disso. Muitos dos meus companheiros de tripulação não o fizeram. Então, se você quer que eu te leve até lá, você está perdendo seu tempo. E meu.",
"Pena, era exatamente por isso que eu ia te pagar. Que tal se você me levar para algum lugar próximo, mas fora da vista dos índios",
"Tudo bem, vou levá-lo a uma curta distância do templo, não mais.",
"Que assim seja. É claro que você não receberá tanto quanto se nos guiasse por todo o caminho. Que tal 100 ouro",
"Que tal 500 ouro, pago antecipadamente, ou você pode encontrar o seu próprio caminho!",
"500 ouro então. Mas esteja avisado, se você nos trair, você desejará estar enfrentando os índios em vez de mim",
"Eu não tenho 500 de ouro comigo agora. Espere aqui, eu vou conseguir de um jeito ou de outro",
"Bem? Você tem 500 ouro para mim",
"Primeiro precisamos navegar até o Cabo Francos. Eu confio que você pode encontrar o caminho até lá?",
"Não se preocupe, nós encontraremos. Esteja pronto para nos guiar para o interior.",
"Tudo bem, esta parece a praia certa. Me siga. Não fuja nem recue, ou você me perderá de vista e se perderá.",
"Entendido. Você lidera, nós seguimos.",
"A partir daqui, basta continuar nesse caminho. Você saberá quando chegar ao templo porque haverá uma flecha espetada em seu peito.",
"Não nos subestime. Mas você fez o que foi combinado. Retorne ao navio. Quando eu voltar, vou te levar para onde você quiser ir.",
"...o idiota está morto com meia dúzia de flechas no #spronoun# peito. O navio está atracado na praia. Só preciso de alguns rapazes fortes para se juntarem a mim, depois nós a levamos e o mar é nosso! Quem está comigo?",
"Estou interessado. Visto que tenho experiência com o navio em questão.",
"Você! Mas você é...",
"Não morto, não. Eu te avisei para não me trair. Nós resolveremos isso do jeito dos piratas! Desembainhe sua espada!",
}
