string DLG_TEXT[25] = {
"Bom dia, ",
"Bom dia, senhor.",
". Estou ocupado e não posso falar com você agora.",
"Sim, posso ver que você está ocupado. Mas gostaria que minha carga fosse descarregada agora mesmo. Se você fizer isso, eu lhe darei 100 piastras.",
"Quanto custa isso?",
"Er... vamos ver... você vê todas as pessoas aqui?",
"Sim?",
"Suponha que eu lhe dê 5 piastras para cada pessoa que você puder ver.",
"Um... dois... umm... muitos?",
"Sim está certo. Vou te dar muitas piastras.",
"Tudo bem. Se você me der muitas piastras, descarregarei sua carga.",
"É o contrário. Você descarrega minha carga, então eu te pago",
"Não, eu não sou estúpido! Se eu descarregar sua carga primeiro, você poderá nem me pagar",
"Posso ver que você é um homem inteligente e não é facilmente enganado. Tudo bem, aqui estão muitas piastras. <Você dá a ele alguns trocados.> Agora, siga-me até meu navio e eu lhe mostrarei a carga.",
"Onde está a carga que você quer que eu descarregue?",
"Receio não ter sido muito honesto com você. Agora, por favor, fique quieto para que eu possa amarrá-lo.",
"Mas como posso descarregar sua carga se estou amarrado?",
"Não preciso de você para descarregar a carga. Eu preciso que você fique aqui. Por muito tempo.",
"Se você não quer que eu descarregue a carga, por que me trouxe aqui? Tenho que devolver o dinheiro?",
"Não, você pode ficar com o dinheiro. Quanto ao motivo de você estar aqui, não posso lhe dizer isso. Só que você precisa ficar aqui.",
"Você vai me desamarrar agora?",
"Não, sinto muito, mas você precisa ficar aqui mais um pouco.",
"Não, só vim aqui para rir de você.",
"Sim! Sinto muito por ter mantido você aqui por tanto tempo, mas agora é hora de você ir para casa.",
"Sim, é seu dia de sorte. Eu não quero mais você sentado em meu poder e não posso me dar ao trabalho de matá-lo.",
}
