string DLG_TEXT[22] = {
"Olá. Quem é você?",
"Eu sou ",
". E preciso da sua ajuda.",
"Desculpe, estou enganado.",
"Então você está precisando da minha ajuda de novo?",
"Essa é a vida de pirata...",
"Graças a Deus, não. Essa ajuda é muito cara.",
"Então você está com problemas com os piratas?",
"Não, com a Espanha. Alguém sequestrou um enviado do Sacro Império Romano. Não fui eu e aparentemente também não foi nenhum outro pirata",
"Então não tenho certeza do que posso fazer. Não tenho influência na Espanha.",
"Não, mas você trabalha para a França. Oficialmente, pelo menos. E como a França está em guerra com o Império, eles são o próximo suspeito mais provável depois dos piratas. Então, você sabe se algum francês é o responsável?",
"Se eu fizesse isso, a informação lhe custaria caro. Portanto, lamento dizer que não.\nComo você disse, oficialmente trabalho para a França. Mas estando preso aqui em uma ilha pirata nos fundos de #sisland_Hispaniola#, não tenho conhecimento do funcionamento da corte francesa.\nVocê sabe de onde o enviado foi levado?",
"Sim, de #sSanto Domingo#. Embora eu também devesse protegê-la, é por isso que estou sendo culpado.",
"Eu vejo. Se a França estivesse realmente envolvida em alguma coisa em #sSanto Domingo#, então ",
" provavelmente saberá disso. Ela é a governadora de #sPort au Prince#.",
"Então eu deveria perguntar a ela?",
"Sim, mas você precisará ser mais discreto do que foi aqui. Se você simplesmente começar a fazer perguntas como fez aqui, provavelmente será preso na hora",
" Principalmente porque a França não gosta muito de você.",
"Sim, entendo seu ponto. Vou precisar inventar uma história de capa. E então visitarei #sPort au Prince#.",
" Obrigado pela ajuda!",
"Você também pode querer um disfarce. O alfaiate local deve ter algo impróprio para um pirata, mas adequado para alguém que deseja visitar um governador",
"Boa ideia. Vou ver o alfaiate imediatamente.",
}
