string DLG_TEXT[79] = {
"Disseram-me que você fez um grande esforço para solicitar uma audiência. Meu nome é ",
"Eu sou ",
"Quem é você e qual é o seu negócio aqui?",
"É muito mais longe do navio?",
"Não muito mais longe, não.",
". Fui enviado pelo #sadmiral# para evacuar você.",
"Graças a Deus! Os franceses já estão atacando. Presumivelmente, o seu navio está ancorado em algum lugar diferente do porto?",
"Sim, estou atracado em ",
"Excelente! Permita-me informar minha esposa, então nos juntaremos a você.",
"Aliás, me disseram que haveria uma recompensa por isso.",
"Sim claro. Se você puder levar minha esposa e eu para um local seguro, você receberá 20.000 moedas de ouro",
"Uma tarifa razoável. Muito bem, chame sua esposa, mas não demore muito - não pretendo esperar a chegada do exército francês.",
"Permita-me apresentar minha esposa, #swife#. Agora, por favor, deixe-nos seguir nosso caminho.",
"Exatamente o que sinto - vamos sair daqui enquanto podemos! Sigam-me, por favor, todos vocês. Fiquem juntos, pode haver bandidos entre aqui e meu navio.",
"Eu estou impressionado, ",
"! Você fez o que a Marinha Real não conseguiu - derrotou o '#swarship#'. Isso exige uma mudança de plano.",
"Que tipo de mudança? Você ainda me deve 20.000 ouro, independentemente de onde você quer que eu o leve",
"A bandeira inglesa ainda tremula sobre o forte, o que significa que as minhas tropas ainda estão a lutar. E você parece ser uma #sperson# de ação.\nEntão aqui está minha proposta. Junte-se à batalha e ajude a acabar com esta invasão de uma vez por todas. Você receberá 200.000 ouro e possivelmente outras recompensas, pois terá sido fundamental para salvar #sRedmond#.",
"Bem, não gosto de deixar um trabalho pela metade e sua oferta é atraente. Muito bem, você está ligado.",
"Excelente! Quando a batalha terminar, minha esposa e eu voltaremos para casa. Quando você se juntar a mim lá, você receberá sua recompensa.",
"Então estou ansioso para vê-lo de volta na residência. E agora devo preparar-me para outra batalha.",
"Ah, ",
", você voltou. Mas por que esses soldados estão com você?",
"Suspeito que o comandante do forte não sabia por que eu estava lá ou se estava agindo sob suas ordens",
"Eu vejo. Soldados, vocês estão dispensados - voltem para o forte.",
"E agora há a questão do meu pagamento, Excelência.",
"Claro - aqui estão as 200.000 moedas de ouro que prometi. Você certamente os mereceu!",
"Também havia uma recompensa por lidar com #svillain#, se você se lembra?",
" Eu matei #spronoun2# em um duelo a bordo do '#swarship#'.",
"De fato? Pois bem, 10.000 moedas adicionais seriam uma recompensa adequada para esse traidor",
"Obrigado, Excelência. Este foi certamente um dia muito lucrativo.",
"Agora devemos discutir o '#swarship#'. Obviamente ela não pode permanecer sob o comando de um capitão particular. Se você entregá-la à Marinha Real, receberá outras 100.000 moedas de ouro",
"Eu poderia conseguir mais do que isso para o '#swarship#' vendendo-o em seu estaleiro. Ou o estaleiro de outra pessoa. Melhor ainda, depois do esforço que fiz para capturar o '#swarship#', acho que vou ficar com ele.",
"Você percebe que eu poderia simplesmente ordenar que meus homens comandassem o '#swarship#' e, se necessário, prendessem você?",
"O que? Oh haha! Você quase me deixou preocupado. Claro, você está apenas brincando.",
"De jeito nenhum...",
"Não é nada sério, tenho certeza que você estava prestes a dizer. E no mesmo espírito de brincadeira, sem ameaças sérias, lembre-se de que sua marinha não conseguiu tomar o '#swarship#', enquanto minha tripulação conseguiu. E então considere para onde as armas do '#swarship#' estão apontadas no momento.",
"Você não ousaria!",
"Claro que não, assim como você não tentaria tomar meu navio à força. Todas essas ameaças são apenas piadas e de mau gosto, então chega de bobagens, tenho certeza que você concordará.",
"Então talvez eu possa interessá-lo por uma Carta de Marca? Considere: você estará livre para navegar como quiser e, quando atacar alvos franceses, estará servindo a si mesmo e à Inglaterra ao mesmo tempo. Você receberá todo o saque que receberia de qualquer maneira, além de recompensas adicionais da Inglaterra",
"Já tenho uma Carta de Marca da Espanha.",
"Esse parece ser o meu tipo de negócio. Aceito.",
"Não, não quero ficar ligado à Inglaterra dessa forma.",
"E daí? Inglaterra e Espanha são aliadas contra a França. Aceitar uma Carta de Marca da Inglaterra significa apenas que você será recompensado pela Inglaterra e pela Espanha por atacar o mesmo alvo. Você não tem nada a perder e muito a ganhar por fazer o que fará de qualquer maneira",
"Excelente! Uma decisão sábia, capitão. Se continuar a lutar bem pela Inglaterra, quem sabe que glória poderá conquistar? Podemos até dar o seu nome a um navio de guerra.",
"Como quiser. Você sempre pode comprar uma Carta de Marca minha, ou de qualquer outro governador inglês, se mudar de ideia.",
"Um bom argumento, bem feito, Excelência. Além disso, ter Cartas de Marca da Inglaterra e da Espanha significa que não estou tão intimamente ligado a nenhuma das nações. Aceito sua oferta.",
"Mesmo assim, não posso aceitar uma Carta de Marca da Inglaterra.",
"E agora devo me despedir. Adeus, Excelência.",
"Bem, talvez não seja tão ruim assim. Você é um corsário a serviço da Inglaterra, então é claro que só usará o '#swarship#' contra os inimigos da Inglaterra.\nDessa forma, desejo-lhe uma boa caçada, capitão. Talvez se você continuar a se distinguir, possamos até nomear um navio de guerra com seu nome",
"Farei tudo o que você pedir! Só não machuque meu ",
"Depois de tudo que #spronoun# fez? Depois que #spronoun# ameaçou minha esposa? Você pede demais!",
"É a única maneira de acabarmos com isto. Sua palavra, ou não posso te ajudar.",
"Muito bem, então. #svillain#, se você matar ",
" então dou minha palavra de que você pode sair com segurança.",
"Obrigado Senhor! Eu prometi que haveria uma recompensa por lidar com o #svillain#. Aqui estão 10.000 moedas de ouro - uma recompensa adequada para esse traidor",
"Você também me deve muito mais por salvar sua cidade. Acredito que você mencionou a soma de ",
"Há também a pequena questão de derrotar a invasão francesa. Presumivelmente, isso também vale alguma coisa",
"Na verdade, sim. A soma de 200.000 moedas de ouro deveria ser uma recompensa adequada por tal heroísmo",
"Você ia deixar o #svillain# me matar e depois roubar meus pertences! E o que você ia fazer com minha esposa?",
"Nada. Isso provocou o #svillain# a lutar comigo, não foi? E você ainda está vivo, o que não estaria se eu tivesse largado minha espada e deixado #spronoun2# fazer o que #spronoun# quisesse.",
"Então você diz. Por que eu deveria confiar em você?",
"Porque não estou tentando matar você e colocar a culpa no #svillain#. Sua esposa está segura, seus bens estão seguros e você está seguro.",
"Suponho que isso seja verdade.",
"E, pelo que me lembro, você mencionou uma recompensa para o #svillain#, vivo ou morto. Bem, #spronoun# está morto.",
"Isso também é verdade. Muito bem, a recompensa é de 10.000 moedas de ouro. Aqui estão eles.",
"E talvez, como mais uma honra, você aceitaria uma Carta de Marca? Considere: você estará livre para navegar como quiser e, quando atacar alvos franceses, estará servindo a si mesmo e à Inglaterra ao mesmo tempo. Você receberá todo o saque que receberia de qualquer maneira, além de recompensas adicionais da Inglaterra",
"Quem é você? O que aconteceu? Os franceses estão invadindo a cidade?",
". Você ficará satisfeito em saber que a invasão francesa foi derrotada.",
"Graças a Deus! Escreverei imediatamente ao #sadmiral# para parabenizá-lo pelo trabalho de sua frota.",
"Não se preocupe. Não foi a sua frota que derrotou os franceses. Se você quiser agradecer a quem derrotou os franceses, aqui estou.",
"Do que você está falando, #sperson#? Você espera que eu acredite que um ",
"pirata",
"corsário",
" derrotou o '#swarship#', o navio mais poderoso da frota francesa?",
"Acredite. A Marinha Real não teve nada a ver com isso. E espero ser bem pago pela ação de hoje.",
"Obrigado, soldado. Demitido. Bem, ",
", isso parece confirmar o que você diz. Isso coloca a mim e a toda a cidade firmemente em dívida com você. Talvez a soma de 200.000 coroas de ouro fosse um pagamento suficiente",
"Um navio de guerra? Se assim for, espero que seja um grande problema. ",
}
