string DLG_TEXT[62] = {
"Disseram-me que você fez um grande esforço para solicitar uma audiência. Meu nome é ",
". Agora, por favor, diga-me o propósito da sua visita ",
"Meu nome é ",
"Então, por que você me distrai dos assuntos de estado muito importantes?",
"Não! Eu reconheço você. Você é o notório pirata ",
"! Guardas - prendam isso ",
"Eu deveria ter usado um disfarce melhor. Mas em breve você precisará contratar mais guardas!",
"Gostaria de oferecer meus serviços à França.",
"Qual é o seu negócio aqui, soldado?",
"Excelência, estou aqui em nome de ",
", o governador de #sFalaise de Fleur#. Ele deseja que eu assuma a custódia de ",
". Sou então instruído a levá-la de volta para a França.",
" está enganado! ",
"É verdade que enviei uma força-tarefa para interceptar o galeão que transportava ",
". Mas infelizmente a força-tarefa foi derrotada pela escolta do galeão.",
" chegou em segurança em #sSanto Domingo# mas foi sequestrado lá. Não sei quem foi o responsável.",
"Talvez outro governador francês tenha ordenado o sequestro?",
"Certamente não. Nada acontece em #sisland_Hispaniola# sem o meu conhecimento, e nada que envolva a França em #sisland_Hispaniola# acontece sem minha autorização.",
"Peço desculpas, Excelência. Quero apenas ter certeza de todos os fatos antes de retornar ",
". E também peço desculpas por tomar seu tempo. Adeus, Excelência.",
"Saia antes que eu chame mais guardas!",
"Não se preocupe, estou indo embora!",
"Há mais alguma coisa que você queira aqui?",
"Não, vou embora agora. Adeus.",
"Você deseja servir a França? Muito bem. Tenho uma tarefa simples para você. Se você fizer isso, será pago e talvez receba um trabalho mais interessante no futuro.",
"Parece o início de uma carreira promissora. Por favor me conte mais.",
"Permita-me apresentar ",
". Seu trabalho é levá-lo para #sIsla Muelle# em #sisland_Isla Muelle#. Ele lhe dará mais detalhes.",
"Me desculpe, mas para que serve isso... cara... para a França?",
"Não se deixe enganar pela aparência dele ",
". O objetivo é enganar os espanhóis em geral e os funcionários de #sIsla Muelle# em particular. ",
" é um dos nossos espiões mais capazes e a aparência que lhe causou tanta diversão é apenas um disfarce.",
"Eu vejo. Ninguém suspeitaria que tal pessoa fosse um espião - o que, claro, é uma grande vantagem para um espião",
"Precisamente. Quando você entregar ",
" para #sIsla Muelle#, retorne aqui para efetuar o pagamento.",
"E possivelmente para trabalhos futuros. Até o meu regresso, então, adeus, Excelência.",
"Eu reconheço você. Você é o notório pirata ",
"Bem vindo de volta, ",
". É ",
" com segurança em #sIsla Muelle#?",
"Sim, Excelência. O albatroz está em seu ninho. E o verdadeiro ",
" está seguramente em meu domínio. Ninguém além de você, eu e ",
" sabe da mudança.",
"O albatroz, você diz? Bom. Aqui está sua recompensa.",
"Obrigado, Excelência. Você tem algum outro trabalho para mim?",
"Sim. Você foi acusado do sequestro de #senvoy#, o enviado do Sacro Império Romano. Gostaríamos de ficar com a custódia dela.",
"Mas eu não a sequestrei!",
"Eu sei que. Nosso agente em #sSanto Domingo# observou os sequestradores alegando trabalhar para você, mas eles não embarcaram em seu navio.",
"Então para onde eles foram?",
"De acordo com o relatório do agente ",
"alguns deles embarcaram no navio em que o #senvoy# estava viajando, provavelmente levando-o ao mesmo tempo. O resto embarcou em seu próprio navio. Ambos os navios foram vistos rumando para #sisland_Cuba#.",
"eles foram vistos embarcando em um navio diferente que parecia definir o rumo para #sisland_Cuba#.",
"Sim. Os espanhóis acreditam que o notório pirata ",
" raptou #senvoy#, o enviado do Sacro Império Romano, de #sSanto Domingo#. Mas embora #spronoun# seja culpado de muitos crimes, não acreditamos que #spronoun# tenha cometido este.",
"Por que não?",
"Nosso agente em #sSanto Domingo# observou os sequestradores alegando trabalhar para ",
", mas eles não embarcaram no navio #spronoun3#. Em vez de, ",
"Muito interessante, Excelência, mas como poderei ajudar neste assunto?",
"Os raptores presumivelmente não trabalham para o governo espanhol, ou pelo menos não trabalham abertamente. Então eles não estarão em #sHavana# ou #sSantiago#.\nMas #sisland_Cuba# tem muitas praias e enseadas. Você irá revistá-los e descobrir onde os sequestradores estão escondidos. Depois você reportará aqui. Podemos então enviar uma força para eliminar os sequestradores e resgatar #senvoy#.",
"Posso perguntar por que você pretende resgatar a Eleitora? Certamente o sequestro dela beneficiará a França?",
"Tê-la como refém beneficiará ainda mais a França. Ela será um contador de negociações útil em qualquer negociação futura com o Sacro Império Romano.",
"Eu entendo. Então partirei para #sisland_Cuba# o mais rápido possível.",
}
