string DLG_TEXT[18] = {
"Posso me apresentar, meu nome é ",
". A seu serviço, ",
".",
"Olá, ",
", É bom ver você novamente. Você precisa do meu serviço hoje?",
". Bem vindo de volta. Deixe-me ver se consigo encontrar mais alguma coisa em meu estoque.",
"Olá, ",
". Acabei de começar a trabalhar como servente na residência do governador. Você tem alguma coisa adequada para eu usar aí",
"Sim, eu tenho exatamente a coisa. Serão 1000 piastras, por favor.",
"Aqui.",
"Eu não tenho tanto comigo.",
"Bem, nesse caso tenho certeza de que seu empregador pagará pelo vestido e retirará o dinheiro do seu salário mais tarde. ",
"Você gostaria de experimentar o vestido?",
"Existe algum lugar privado para eu me mudar?",
"Sim, o vestiário fica naquelas escadas à sua direita.",
"Obrigado.",
"O vestiário fica naquelas escadas à sua direita ",
".",
}
