string DLG_TEXT[551] = {
"Bom dia, ",
"Bom dia para você também.",
"O que você está fazendo no meu quarto?",
"Venha comigo se quiser viver.",
"O que você quer dizer? Quem me ameaça?",
"Eu, se você não fizer o que lhe mandam. Isto é um sequestro. Então MOVA-SE, ou preciso desembainhar minha espada antes que você entenda",
"Muito bem, vou segui-lo. Mas meu pai ouvirá sobre isso.",
"Essa é a ideia, sim.",
"Você não está ansioso pelo seu casamento, está",
"Não, ",
" é insensível e me vê como pouco mais que um troféu e um aquecedor de cama.",
"Então que tal se eu tirar você de tudo isso? Não posso prometer uma vida de luxo, mas pelo menos você não terá que se casar ",
"Você ameaçou ",
"Ele provavelmente não teria cooperado de outra forma. Se o fizesse, amanhã a esta hora ele estaria desempregado e possivelmente pior, dependendo do temperamento de seu pai. Dessa forma, ele poderá alegar, com sinceridade, que eu ameacei matá-lo e, aliás, a você. Seu pai dificilmente pode culpá-lo por me ajudar.",
"Bem, não sei o que você tem em mente, mas tem que ser melhor do que casar ",
". Farei tudo o que você disser.",
"Bom. Agora, quando sairmos, aja com medo. A próxima parte depende de qualquer pessoa que encontrarmos estar convencida de que vou matá-lo se tentarem me impedir. O que não farei, mas eles não devem saber disso.",
"Ajuda! Eles estão tentando me sequestrar!",
"Resposta errada! Eu trato de você mais tarde!",
"É verdade, soldado. Não consegui dormir, então pedi ao meu amigo que me acompanhasse em uma curta caminhada.",
"Você vê? Tudo está bem.",
"Desculpe! Fiquei assustado e entrei em pânico!",
"As mortes desses soldados são de sua responsabilidade. Não faça isso de novo ou mato você antes de matar o próximo soldado",
"O que você pretende fazer comigo agora?",
"Eu ainda não tenho certeza. Por enquanto você será meu convidado a bordo do navio. Talvez possamos encontrar algo para ocupá-lo. Veja como a vida marinha combina com você, depois conversaremos mais.",
"Você será mantido como prisioneiro a bordo do meu navio enquanto eu providencio um resgate. Ore para que uma quantia adequada seja disponibilizada.",
"O QUE?",
"Desculpe, minha querida. Você não teria sido tão útil se eu lhe contasse a verdade.",
"Bem, o porão de um navio pirata não é confortável e vou precisar de um banho demorado quando chegar em casa. Mas fui bem tratado pelo Capitão Ardent e pela tripulação.",
"...",
"Você já tomou uma decisão sobre mim?",
"Estou inclinado a libertar você. Existe algum lugar que você gostaria de ir?",
"Já me acostumei a ter você por perto. Você gostaria de se juntar ao meu navio? Você seria um oficial, é claro.",
"Durante o tempo que estivemos juntos, comecei a gostar muito de você. Você consentiria em se casar comigo?",
"Não, ainda estou pensando nisso.",
"Em algum lugar bem longe de #sRedmond# e ",
". Talvez você esteja disposto a me levar para #sIsla Muelle#?",
"Muito bem, provavelmente posso encontrar algo interessante para fazer lá também",
"Não, infelizmente meus planos de viagem para o futuro próximo não incluem #sisland_Isla Muelle#.",
"Não tenho certeza se posso ser útil em um navio, mas estaria disposto a aprender.",
"O que você pode fazer?",
"Bem como ",
"a filha",
"o filho",
" de governador, estou acostumado a dar ordens aos criados.\nE houve uma época em que minha mãe estava muito doente e eu cuidava dela.\nAh, e às vezes ajudo meu pai a verificar os registros financeiros da cidade.",
"Um bom comandante, então. Muito bem, você será o primeiro imediato.",
"Experiência com medicina e atendimento de doentes? Você se sairá bem como médico do navio.",
"Acostumado a trabalhar com dinheiro, não é? Bom, você acabou de se tornar meu novo intendente.",
"Meu! Isso é um pouco repentino! Pelo que vi, você certamente é melhor do que ",
", mas isso não é difícil. Por favor, deixe-me ter tempo para considerar sua proposta.",
"Por suposto, considere, mas por favor não demore muito!",
"Olá, capitão! Obrigado por me afastar. Sentirei falta da minha família, é claro, mas teria sido eternamente infeliz casada co ",
". Eu estava prestes a escrever uma carta para meu pai explicando que estou bem, para que ele não se preocupe.",
"Essa é uma boa ideia. Adicione algo pessoal, algo que eu não possa saber, para que ele saiba que não o forcei a escrever. Então vou providenciar a entrega.",
"Minha carta está escrita, capitão. Por favor, veja se chega ao meu pai. Eu realmente não quero que ele se preocupe comigo.",
"Entrego pessoalmente. Espero que quando ele souber a verdade ele esteja menos inclinado a me caçar.",
"Bem, é isso. Vou me despedir do papai pela última vez, depois vou embora daqui para sempre.",
"Isso pode não ser uma boa ideia. Se os guardas atacarem, você poderá se machucar ou morrer no fogo cruzado. E não há como saber o que seu pai fará se te ver - ele pode me prender e casar você com ",
" afinal. É melhor você retornar ao navio até que isso seja resolvido de uma forma ou de outra.",
"Não acredito - estou aqui em #sIsla Muelle#, livre de ",
", e tudo graças a você! Provavelmente irei me mudar para algum lugar perto da igreja e da residência. Por que você não me visita na próxima vez que estiver em #sIsla Muelle#?",
"Espero que você encontre a felicidade aqui. E posso muito bem ver você se minhas viagens me trouxerem por aqui novamente.",
"Olá de novo, ",
"É um prazer ver você novamente. Como tem sido a vida em #sIsla Muelle#?",
"Para ser sincero, muito chato comparado ao meu tempo no mar.",
"Então, você gostaria de voltar ao meu navio? Como oficial, é claro.",
"Talvez você prefira voltar para casa? Mas você não precisaria se casar ",
" se você se casar comigo em vez disso.",
"Isso é realmente triste. Mas é aqui que você escolheu estar, então espero que você possa eventualmente encontrar felicidade, ou pelo menos contentamento, aqui",
"Olá! Quem é você e por que está aqui?",
"Eu sou ",
" e me pediram para entregar isso.",
"Oh céus. ",
" fica impaciente - #spronoun# marcou a data do nosso casamento.",
"Um casamento deveria ser o dia mais feliz da sua vida, mas você não parece feliz com isso.",
"Silêncio! Só trouxe a carta para chegar até você. Seu pai pagará bem pelo seu retorno seguro, mas só depois que eu tirar você daqui, então MOVA-SE!",
"Não perca a esperança ainda. A carta me trouxe aqui. Agora vou tirar você daqui, mas você deve fazer a sua parte.",
"Isso não é problema meu. Meu trabalho era entregar a carta. Você tem uma resposta para eu retirar?",
"Não, precisarei de tempo para redigir uma carta de resposta. E devo conversar com meu pai sobre os preparativos.",
"Muito bem. vou contar ",
" que você e seu pai estão fazendo os preparativos para o casamento. Adeus.",
"Isso não é uma piada engraçada. Se você estivesse falando sério, tudo que eu teria que fazer seria gritar e um esquadrão de guardas chegaria para se livrar de você",
"Certamente não é uma piada. Se alguém tentar interferir no meu plano, eu os matarei. Começando por você, se você não começar a cooperar.",
"Bom. Vou embora agora, mas todas as noites, olhe pela sua janela e uma noite você me verá lá fora.",
"O que você vai fazer?",
"Primeiro você abrirá aquela janela - e depois recuará rapidamente! Cerca de dez segundos depois, uma flecha passará. Uma corda será amarrada à flecha e uma corda à corda. Você vai puxar a corda e amarrá-la em algo seguro - aquela cama, por exemplo.",
"Mas não consigo descer por uma corda!",
"Eu não esperava que você pudesse. Vou subir, amarrar a corda em você e baixá-lo, depois descerei novamente. Com sorte podemos ir embora antes que alguém perceba.",
"Parece perigoso. Mas se isso me afastar ",
", estou disposto a tentar qualquer coisa!",
"Esse é o espírito! Apenas mantenha suas esperanças e seus olhos voltados para aquela rua.",
"Você está certo, foi uma piada, talvez de mau gosto. Mas você parece infeliz com seu noivado. Talvez eu possa oferecer uma alternativa?",
"Não é seu dia de sorte, não é? Porque antes que você possa se casar, seu pai terá que me pagar muito dinheiro para que você retorne em segurança. MOVER!",
"É verdade. Quero um bem lindo que vai deixar todo mundo com inveja!",
"Mas também fui instruído a não gastar muito, então não seja muito exigente.",
"Você está realmente procurando minha aliança de casamento?",
"Não. Está vendo aquele navio ali? Corra, AGORA!",
"Você entra no meu quarto novamente ",
"Esperançosamente pela última vez. Agora você está pronto?",
"Mas é claro. Amarre a corda e abaixe!",
"Falado como um pirata! Quem sabe, talvez façamos um de você. Leve esta capa, não queremos que os guardas do porto reconheçam você. E... você desce",
"Isso é emocionante!",
"Shh! Não queremos atrair a atenção dos guardas. Me siga.",
"Apenas um grumete, senhor.",
"Se sim, você tem sido um garoto muito travesso. Você não quer que sua esposa descubra, não é",
"Devemos embarcar em seu navio rapidamente antes que aquele guarda se lembre de onde me ouviu antes",
"Por que? E como você sabia que ele é casado",
"Ele era um dos guardas de plantão em uma festa no jardim organizada por meu pai há algumas semanas. Sua esposa estava lá - algo incomum para um soldado de carreira. Ela provavelmente estava se certificando de que ele não demonstrasse interesse em nenhuma das mulheres presentes",
"Ciúme, ela estava?",
"Digamos apenas que pela aparência dela, aquele guarda provavelmente é um homem com sérios problemas conjugais e não quer mais.",
"E isso foi uma boa reflexão e uma conversa rápida de sua parte! Mas parece que afinal ele se lembrou de você - corra para o cais!",
"Bem, é isso, #sname# - nossa primeira noite de casados. Que íntimo!",
"Sim, querido. Mas não posso deixar de sentir que estamos sendo observados. É como se alguém estivesse olhando por cima do meu ombro...",
"Sinto muito, mas não posso me casar com alguém que é inimigo da Espanha. Mas talvez se você não fosse inimigo da Espanha?",
"Infelizmente, a minha discussão com a Espanha é mais profunda do que o meu amor por você.",
"Bem, se é isso que nos impede, então falarei com um governador para fazer a paz com Espanha. Existem muitas outras nações cujos navios podem ser atacados",
"Estou lisonjeado, mas como posso ter certeza de que você realmente me ama",
"Existem muitas maravilhas no mar. As estrelas cintilantes à noite e o brilho do sol nas ondas durante o dia. Mas nenhum combina com a luz dos seus olhos.",
"Ora, que encantador! Eu não tinha pensado que um capitão de mar violento pudesse ser tão poético.",
"Eu salvei você do casamento ",
". Isso não conta para nada?",
"Você fez isso, mas antes de me comprometer com o casamento, preciso saber que não estou apenas trocando um canalha sem coração por outro",
"Eu salvei você de um casamento trágico. Eu trouxe você para #sIsla Muelle# sem pedir nada em troca. Agora, quando você estiver novamente infeliz, eu volto para buscá-lo.",
"Há um ditado que diz: 'Se você ama algo, liberte-o; se ele retornar, então é seu'. Você me libertou e agora voltou. Meu coração é seu.",
"Talvez um sinal do meu afeto o convença?",
"Aquela coisa inútil? Se isso é o melhor que você pode oferecer, seria melhor eu me casar com um mendigo de rua",
"Ah, que pensativo! Realmente você se importa comigo para me oferecer algo assim.",
"Então agora você vai se casar comigo?",
"Certamente, se você tiver uma aliança de casamento.",
"Este anel da sorte funcionaria?",
"Talvez este anel de prata seja suficiente?",
"Este anel de esmeralda já parece bom e só poderia ficar melhor em seu dedo.",
"Não posso te dar o mar inteiro, mas talvez as safiras deste anel servissem?",
"Esse é o tipo de anel que eu poderia esperar ",
". Eu esperava que você estivesse melhor, mas talvez eu estivesse enganado, afinal.",
"Que lixo patético! Encontre alguém chato que combine com aquela coisa chata!",
"Bem dito! Aguardo ansiosamente o dia em que você o colocará em meu dedo na igreja.",
"Eu não precisaria de todo o mar. Quando nos casarmos, mas você estiver no mar, eu só precisaria olhar para isso para me lembrar de você.",
"Se a decisão fosse apenas minha, eu concordaria imediatamente. Mas só posso me casar com você com a bênção do meu pai.",
"Então voltemos a #sSantiago# e procuremos.",
"Deixe-me explicar, por favor. Padre, fiquei terrivelmente infeliz com a perspectiva de me casar ",
", então quando ",
" se ofereceu para me levar embora, aproveitei a oportunidade imediatamente. Eu estava com medo de ser sequestrado, mas mesmo isso era melhor do que casar ",
"Para ser brutalmente honesto, no começo eu pretendia sequestrar você. Mas quando soube da sua situação, não consegui.",
"Ficamos atraídos um pelo outro e agora ",
" propôs casamento.",
"Com sua permissão, Excelência, isto é.",
"Oh! Seu traidor nojento! E eu pensei que você fosse melhor que o pirata comum, mas você não é melhor que o pior deles!",
"A vida pode ser difícil às vezes. Então eu posso.",
"Você está realmente passando por isso? Eu estou tão feliz!",
"Assim como eu. Vejo você na igreja!",
"Não se atreva a falar comigo novamente. Nem chegue perto de mim!",
"Multar.",
"Você conseguiu fazer as pazes com a Espanha?",
"Sim, então você não precisa se preocupar em trair seu país. ",
"Ainda não.",
"Maravilhoso! Então você vai se casar comigo?",
"Você gostaria de se juntar ao meu navio como oficial?",
"Você me daria a honra de se casar comigo?",
"Então terei que pensar em outra coisa.",
"O que você tem em mente?",
"Que esta cruz lhe traga boa sorte e nos reúna na igreja que ela representa.",
"Talvez este broche de prata ganhe o seu favor e a sua mão?",
"O que tenho em mente é conquistar seu coração fazendo com que você use este broche de ouro perto dele",
"As esmeraldas neste pingente deixarão outras mulheres verdes de inveja quando virem você usando-o.",
"Bem, eu não sei - talvez esta pequena coleção de joias?",
"Que tal este belo cutelo?",
"Essa tizona leve já me acompanhou em diversas batalhas. Imagine o que você poderia fazer com isso.",
"Esta tizona é um excelente exemplo do artesanato de Toledo. Nas tuas mãos só pode levar a ações corajosas.",
"Este florete de punho é uma das espadas mais impressionantes que já vi, e já vi muitas. Você é a única pessoa a quem eu consideraria dá-lo.",
"Desculpe por isso. Talvez eu encontre algo melhor.",
"Você é muito exigente! Esqueça, vou encontrar outra pessoa",
"Se é assim que você se sente, então adeus, e que eu nunca mais te veja enquanto você viver!",
"Se é assim que você se sente, então deixarei seu navio na próxima vez que atracarmos, e você não precisará mais se preocupar com minhas 'exigências'",
"Adeus e boa viagem!",
"Lamento, mas não posso ser oficial de um navio inimigo da Espanha.",
"Isso é compreensível.",
"E obrigado por lidar com o suposto assassino ",
". Agora tenho um favor especial a pedir.",
"Agora que estamos aqui, tenho um favor especial a pedir.",
"Pergunte e se eu puder, eu farei.",
"Quando ",
" estava tentando me cortejar, #spronoun# falava frequentemente de um comboio que tornaria #spronoun2# muito rico.",
"Quando eu estava dentro ",
"na cela de #spronoun# me provocou falando sobre um comboio que tornaria #spronoun2# muito rico.",
" Deve estar em #sOxbay# em breve. Eu gostaria muito que você pegasse aquele comboio ",
", e para eu estar lá quando você fizer isso.",
"Vou ter que pensar sobre isso...",
"Claro, foi errado da minha parte...",
"Tudo bem, já pensei sobre isso. Deixe-me ver se entendi. Posso atingir um comboio. Isso te faz feliz. E pune ",
" pelo que #spronoun# fez com você.",
"Bem, essa é uma maneira de dizer, sim.",
"A melhor oferta que recebi há muito tempo. O único problema é que tive que renunciar à pirataria quando me casei com você.",
"A melhor oferta que recebo há muito tempo.",
"Então você realmente vai me levar na caça ao comboio?",
"Sim. Mas eu não dirijo um navio de passageiros. Você terá que se juntar à tripulação - como oficial, é claro. ",
"Como você pretende levar o comboio ",
"Como ",
"a esposa de ",
"o marido de ",
", você embarcará em um dos navios. Serei seu acompanhante. À noite vou nocautear os guardas do convés, permitindo que nossos homens subam a bordo e assumam o controle do navio.",
"Você veste esta capa e assumirá o papel de inquisidor. Vou fingir ser um oficial espanhol. Vamos persuadir o governador de #sWillemstad# a fornecer tropas para ajudar no resgate de um certo ",
", que se acredita ser um prisioneiro no navio.",
"Estou interessado em ver como você pretende fazer isso! Mas dê-me alguns momentos para me preparar, então me juntarei a você.",
"Não demore muito. Temos um comboio para pegar!",
"Rápido, volte para o navio!",
"Espero que não me tenham visto!",
"Qual é o problema?",
"Reconheci alguns dos homens daquele navio. Foram eles que me sequestraram!",
"Então?",
"Você não vê? Eles saberão que eu não casei ",
" de boa vontade. Eles saberão que algo está errado se me virem aqui.",
"Tudo bem, teremos que tentar outra coisa.",
"O que mais você tem em mente?",
"Senhores, se me permitem? <Para você>Você, fique quieto! Eu trato de você mais tarde.",
"!",
"<Para o governador> Como meu colega estava tentando dizer, de forma um tanto grosseira, o ",
" é de fato considerado responsável pelo sequestro de ",
". Sua Excelência ",
", governador de #sSantiago#, consideraria um favor e uma honra se o senhor fornecesse tropas para realizar a busca e, se necessário, a prisão.",
"Naturalmente. Esta carta deve fornecer a prova que você precisa.",
"?",
"E agora?",
"Agora você tira sua capa, então eu relato ao sargento holandês que acabei de descobrir você a bordo do navio.",
"Precisaremos de uma tripulação para o navio que acabamos de tomar. E você precisa de um dos nossos oficiais para cuidar da nossa nave. Quem tem você em mente?",
"Ainda estou pensando nisso.",
"Eu não, por favor! Não me mande embora quando estamos tão perto de alcançar o que viemos fazer até aqui.",
"Muito bem, vou escolher outra pessoa.",
"Então, quem vai cuidar do nosso navio",
"Se bem entendi, você planeja roubar um dos navios do comboio e depois atacar o resto do comboio por dentro. Nesse caso, precisaremos primeiro atracar ou vender todos os nossos navios de companhia",
"Bom ponto! Vamos para o estaleiro.",
"Ainda não podemos prosseguir até que você se livre de nossos navios ",
"Claro! De volta ao estaleiro, então.",
"É isso, então. Nós nos juntamos ao comboio. Quando estivermos longe de #sisland_Curacao# atacaremos.",
"Correto. Mas sobre algumas coisas lá atrás com o governador. 'Fique quieto, eu trato de você mais tarde'?",
"Sua tentativa parece ter falhado. Foi tudo o que consegui pensar para aplacar o governador.",
" Mas se eu o ofendi, talvez este seja um pagamento adequado? <beijo>",
"Mais do que adequado. Na verdade, devo-lhe alguns trocos. <beijo>",
"Hee-hee-hee!",
"O que é tão engraçado?",
"Aquele governador tomou você por um oficial espanhol e eu por um inquisidor. Imagine ele nos vendo agora!",
"Ha-ha-ha! Mas a outra coisa foi: onde você conseguiu essa carta",
"Justo. Mas onde você conseguiu essa carta?",
"Eu escrevi. Tenho um anel de sinete da família De la Vega, claro. E nunca tivemos contato com #sWillemstad#, então o governador nunca viu a caligrafia do meu pai.",
"Você está se tornando um malandro, não é? Pirataria, ou pelo menos corsário. E agora falsificação. Você certamente está provando seu valor como meu oficial! Agora, vamos continuar com o comboio.",
"Talvez pudéssemos aproveitar essa boa vontade entre você e o governador #sdutch_gov#? Eu iria me casar com #svillain# como parte de um acordo comercial, que agora está perdido. Mas poderíamos criar um acordo com #sWillemstad#?",
"E talvez eu pudesse levar o #sship# para #sWillemstad# para apresentar ao governador #sdutch_gov#? Você pode fornecer uma escolta em seu navio para que eu esteja perfeitamente seguro.",
"Er... sim, claro. Isto é, se você se sentir confiante o suficiente para assumir seu próprio comando",
"Aprendi muito a bordo de sua nave. E ficarei feliz em voltar para ela! Mas esta oportunidade não pode passar despercebida.",
"Você poderia vender ou atracar um de seus navios, por favor? Não posso colocar o #sship# sob sua proteção até que você o faça.",
"Claro! Não tive tempo de visitar o estaleiro antes. Vamos lá agora.",
"Ainda não posso navegar com seu navio até que você me dê espaço em sua frota ",
"É verdade. Muito bem, de volta ao estaleiro.",
" foi bom o suficiente para me acompanhar até aqui, Excelência. Trago agradecimentos de meu pai por sua parte em meu resgate. Em agradecimento, ele lhe envia o navio do qual seus soldados me libertaram.",
"Além dos seus agradecimentos pessoais, esta carta contém uma proposta de acordo comercial entre as nossas duas colónias. Por favor, leia. Espero que tenha sua aprovação.",
"Que bajulação! Mas certamente aprendi muito navegando com você e estou ansioso pela nossa próxima viagem.",
"E eu também estou ansioso para voltar ao mar com você ao meu lado.",
"Sim, há muito ouro por aí para nós dois. Vamos pegar um pouco disso.",
"Percebi que temos uma quantidade de seda. Você se importaria se eu pegasse um pouco disso?",
"De jeito nenhum. O que você quer com isso?",
"Não aceite nada disso! Precisamos manter a carga como está.",
"Você vai ver. Será uma surpresa!",
"Só não desperdice. Isso é algo valioso.",
"Como você gosta dessa roupa? De qualquer forma, é mais prático no convés do que meu vestido",
"Muito legal!",
"Oh, ",
", estou tão feliz em ver você! Você pode abrir esta porta?",
"Infelizmente não tenho chave, então abrir a porta pode demorar um pouco.",
"Esse corredor leva à casa de ",
". Deve haver uma chave em algum lugar",
"Tudo bem, espere aqui - bem, você não tem muita escolha nisso! Mas espero que você não fique preso aqui por muito mais tempo.",
"Essa fechadura não parece muito complexa, eu deveria ser capaz de abri-la com bastante facilidade",
"Você conseguiu uma chave?",
"Não, mas consegui a próxima melhor coisa, uma gazua. E essa fechadura não parece complexa, então devo conseguir abri-la facilmente",
"Obrigado! Agora vamos resolver isso. Me siga!",
"Ei onde você está indo? Bem, provavelmente é melhor do que voltar pela masmorra..",
" enviou uma gangue para me sequestrar! Fui forçado a casar com #spronoun#. Quando eu não dormia com #spronoun#, ",
" me coloque naquela cela. Eu disse que uma vida inteira naquela cela era preferível a uma noite na cama com #spronoun#.",
"E agora, onde está ",
"Devíamos ir à igreja agora. O casamento deveria ser por consentimento, mas não tive escolha. Se explicarmos isso, talvez o padre me liberte do casamento.",
"Muito bem. A igreja está logo ali na esquina.",
"O que pagarei com prazer se ajudar a acabar com este casamento odioso!",
"Era ",
"! Eu pensei que estava seguro ",
"em #sIsla Muelle#",
"sobre ",
"o navio",
" mas ",
"de qualquer maneira, os bandidos me encontraram. Eles me levaram para #sRedmond#, onde fui forçado a me casar com #spronoun#. Quando me recusei a consumar o casamento, fui trancado numa cela de prisão, onde provavelmente ainda estaria se não fosse por isso ",
"Eu tenho uma ideia para isso. Isso exigirá ",
"ajuda.",
"O que você tem em mente ",
"Ver esta ilha me dá vontade de estar novamente entre os espanhóis, mesmo que por pouco tempo. Posso ir sozinho à cidade por um tempo?",
"Não vejo por que não. Volte aqui antes que o navio parta ",
"Não, pai. #spronoun_PC# me resgatou! Eu não suportava a ideia de dormir co ",
", então #spronoun_villain# me trancou em uma cela de prisão. ",
" me libertou e me trouxe para casa.",
"Sério, pai! Em quem você acredita, na sua própria filha ou naquele homem imundo?",
"Sério, pai! Em quem você acredita, no seu próprio filho ou naquela mulher nojenta?",
"Já temos isso em mãos, pai. ",
" e eu vou atacar um comboio pertencente ao #svillain#.",
"Sim, vamos atingir o #svillain# onde vai doer mais, bem na carteira do #spronoun3#.",
"Talvez pudéssemos aproveitar essa boa vontade entre você e o governador #sdutch_gov#? Agora que o #svillain# perdeu a mim e ao comboio, o acordo comercial que deveria ter sido selado pelo casamento está quase certamente perdido. Mas poderíamos criar um acordo com #sWillemstad#?",
"Fiz algo errado? Eu esperava continuar navegando com você.",
"Não, você não fez nada de errado. Mas seu pai não me deixou dúvidas de que se algo desagradável acontecesse com você, algo desagradável aconteceria comigo. Agora que você está em casa e seguro, seria tolice arriscar isso de novo.",
"Muito bem, então desejo-lhe boa sorte em suas futuras viagens. Adeus, ",
"Muito bem, então farei o papel de um #sspouse# zeloso e permanecerei aqui para aguardar histórias de suas futuras aventuras. Adeus, ",
"Adeus, ",
"! Pensei ter reconhecido seu mau cheiro acima dos odores deste lugar. Você veio se gabar de meu infortúnio adicional?",
"O que você está falando? Disseram-me que havia algo valioso aqui. Em vez disso, encontro você. Talvez este não tenha sido um esforço desperdiçado. Haveria uma recompensa por libertá-lo e levá-lo para casa?",
"Se o dinheiro é o que você ama, então é isso que você receberá.",
"Tudo bem, você tem um acordo. ",
"Eu tenho uma confissão. Posso ter enganado você. Você não será recompensado por me levar para casa. Provavelmente serei mandado de volta para o #svillain# e meu pai provavelmente não perdoou você por me sequestrar.",
"O QUE! Eu deveria ter deixado você apodrecer.",
"Mas lembre-se do que eu disse: se dinheiro é o que você ama, então é isso que você receberá. E isso é verdade.",
"Que tipo de truque você está planejando agora?",
"Nenhum - pelo menos não em você. ",
" Você não gostaria que isso o tornasse rico",
"Qual é o truque?",
"Meu. Você me levará com você e eu o ajudarei a encontrar o comboio, começando por lhe dizer onde ele deverá entrar no Caribe. Não estou interessado no dinheiro, apenas em privar o #svillain# dele. Mas eu quero estar lá quando você fizer isso",
"Tudo bem, você tem um acordo. Onde esse comboio deveria estar?",
"Deve chegar em #sOxbay# muito em breve.",
"Isso acabou de lhe garantir um lugar no meu navio. Mas não é um navio de passageiros, você terá que ganhar seu sustento. ",
"Reconheci alguns dos homens daquele navio. Eles fazem parte ",
"a turma!",
" E se você quiser manter seu próprio navio, precisará atracá-lo aqui.",
" Lembre-se de atracar seu próprio navio também.",
"Voltar para você? Prefiro viver como um mendigo de rua do que viver sob o seu teto ",
"Sim, talvez você se lembre de mim dizendo o quanto eu pensava ",
"? E agora #spronoun# é rico, bem-sucedido e está prestes a se tornar governador, enquanto você é um #sbackground# de segunda categoria trancado em seu próprio navio!",
"Mas ",
"! Achei que você estava feliz no meu navio!",
"Hah! O que eu esperava em seu navio e o que posso esperar agora? As coisas só podem melhorar a partir de agora. Adeus, ",
"Então é assim, não é?",
"Deixe-me cortar essas cordas.",
"Rápido, pegue a faca! Eu matei o guarda perto da escada, mas o que está perto da porta está vindo para cá!",
"Obrigado, eu acho...",
"Hah! Eu disse ",
" exatamente o que #spronoun# queria ouvir e o idiota caiu nessa completamente! Tive total liberdade no navio. Claro que você não acreditou em nada disso, não é",
"Claro que não! Eu sei que posso confiar em você ",
"ER não.",
"Na verdade sim. O que você está fazendo e de que lado você está realmente?",
"A primeira coisa que eu disse foi 'talvez você se lembre de mim dizendo o quanto eu tinha em consideração ",
"'. Sempre que falei ",
" para você, sempre foi para dizer o quanto desprezo a fera repugnante. Isso deveria ser uma pista para você!",
"Oh. Desculpe por duvidar de você.",
"Bom. Eu estive esperando por uma chance de libertar você, mas nunca tive essa chance até agora. Seu equipamento está perto dessas caixas. O meu também, e foi por isso que não pude ajudar com o guarda. Eu tenho todas as minhas coisas agora.",
"Obrigado por me dar a faca, de qualquer maneira. Onde estamos?",
"Chegamos a #sPort au Prince#. Os demais oficiais e tripulantes foram retirados do navio e estão detidos no forte.",
"Onde é ",
" partiu no próprio navio #spronoun3# para #sSantiago#.",
"E #spronoun# não te levou com #spronoun2#?",
"Não, #spronoun# provavelmente pensa que se eu chegar a uma distância nadando de minha casa, abandonarei o navio. Eu também faria isso. ",
" deixe escapar que a França vai atacar #sSantiago# e #spronoun# os está ajudando!",
"Hum. Talvez ",
" está testando sua lealdade. Eu deveria estar amarrado. Se eu ainda estivesse amarrado quando #spronoun# retornasse então #spronoun# saberia que você realmente se juntou ao #spronoun2#. Do jeito que está, a tripulação provavelmente tem ordens de matar nós dois se me virem solto",
"Oh? Então você realmente se junto ",
" e só me libertou quando você descobriu que #spronoun# estava envolvido em uma conspiração contra sua casa!",
"Ah, pelo amor de Deus! Sim, preciso da sua ajuda para avisar meu pai sobre o ataque contra #sSantiago#, mas eu pretendia libertar você de qualquer maneira! Eu esperei ",
" cairia no meu engano, mas também esperava que você fosse inteligente o suficiente para saber a verdade!",
"Ainda não tenho certeza, mas por enquanto parece que não tenho escolha a não ser confiar em você. Se a tripulação me ver livre, provavelmente terá ordens para me matar. E, por falar nisso, você.",
"Sim, você está certo. Você se meteu nessa confusão e eu estava planejando escapar sozinho, mas preciso da sua ajuda para chegar a #sSantiago# e avisar meu pai.",
"Pelo menos você está sendo honesto agora. De qualquer forma, estamos nisso juntos, pelo menos por um tempo, porque se a tripulação me ver livre, provavelmente matarão nós dois",
"A maior parte da tripulação está em terra. Se vamos escapar e resgatar sua tripulação, esta é a melhor chance de fazê-lo",
"Certo, vou encontrar minhas coisas, então vamos",
"Você tem alguma ideia sobre como vai resgatar a tripulação ",
"No momento estou pensando em simplesmente marchar até o forte e massacrar qualquer um que ficar no caminho. E você, ",
"Isso não é exatamente sutil! Você poderá ter mais chances de sobreviver se conseguir persuadir os guardas a deixarem você ficar com os prisioneiros",
"Como faço isso? Pergunte-lhes educadamente?",
"Sim. Uma ordem assinada pelo governador provavelmente ajudaria. É claro que o governador provavelmente não dará tal ordem, mas você sabe como sou bom em escrever cartas",
"Você pode falsificar a caligrafia do governador, então? Você se safou disso antes porque a pessoa que o leu nunca viu uma assinatura genuína, mas pode apostar que esses soldados conhecerão a escrita de seu próprio governador",
"É por isso que você terá que me conseguir um espécime.",
"Hmm... posso pensar em algumas maneiras de fazer isso. O que mais gosto envolve encontrar um caminho para a prefeitura à noite e me servir de algo assinado pelo governador",
", é isso que eu penso que é?",
"Se você acha que é uma porta dos fundos para a residência do governador, gosto da sua opinião! Talvez eu possa abri-lo.",
" Mas não antes da noite. É melhor não fazer roubos à luz do dia!",
"Bem, você encontrou um exemplar da caligrafia do governador?",
"Sim. Veja isso!",
"Não. Posso tentar olhar novamente, caso contrário voltaremos a marchar para o forte e enfrentar o regimento",
"Muito bom, ",
"! Agora devíamos arranjar um quarto na taberna.",
"Muito aconchegante, ",
"Negócios primeiro. Tenho algumas coisas para escrever, lembra? O aconchego pode acontecer quando isso terminar.",
"É verdade - a liberação da tripulação depende do que você vai escrever esta noite.",
"Finalmente terminei! É mais difícil falsificar um documento quando você precisa copiar a caligrafia de outra pessoa",
"Mas você acha que isso enganará os guardas do forte?",
"Deveria servir. Eles podem ter visto o escrito do governador, mas provavelmente não o estudaram em detalhes.\nO documento é uma transferência padrão de prisioneiros. Você está autorizado a assumir o comando de um grupo de prisioneiros, ou seja, sua tripulação, para usar como força de trabalho.\nVocê precisará estar uniformizado para que isso funcione. Você tem um uniforme francês?",
"Sim, ainda tenho aquele de #sisland_Isla Mona#. Vou me trocar e depois testarei seu documento.",
"Você já pensou mais sobre minha oferta de forjar a ordem de entregar alguns prisioneiros, ou seja, sua tripulação, para você?",
"Sim. Eu tenho este #sdocument# assinado.",
"Ainda tenho que descobrir uma maneira de fazer com que algo seja assinado pelo governador",
" significa ajudar novamente os franceses, atacar #sSantiago#!",
"Sim eu ouvi. Talvez você também tenha me ouvido dizer que vamos avisar seu pai?",
"Eu fiz e fiquei muito feliz em saber disso! Podemos ir para lá agora?\nSe demorarmos muito, pode ser tarde demais - podemos chegar e encontrar #sSantiago# em mãos francesas, assim como chegamos tarde demais e encontramos #sRedmond# já tomado.",
"Na verdade, navegaremos para #sSantiago# o mais rápido possível, ",
"Não, pai. Foi #svillain# quem me aprisionou e ",
" quem me libertou! Eu odiava #svillain# e me recusei a dormir com #spronoun2#, então #spronoun# me trancou em uma cela de prisão. Eu disse que uma vida inteira naquela cela era melhor do que uma noite na cama do #svillain#. Eu provavelmente ainda estaria naquela cela, mas ",
" me encontrou e me libertou. E também me ajudou a me vingar do #svillain#.",
" me ajudou a atacar e destruir um comboio valioso pertencente ao #svillain#. Se #spronoun# esperava ficar rico com aquele comboio, agora #svillain# pagou caro pelo que #spronoun# fez comigo.",
"Que sugestão! Que continuaria a navegar em tal navio. E mesmo assim... Foi uma experiência interessante... Sim, acredito que gostaria de continuar navegando com vocês.",
"Fico feliz em ouvir isso, #sromance#.",
"Se bem entendi, você planeja roubar um dos navios do comboio e depois atacar o resto do comboio por dentro. Nesse caso, precisaremos primeiro atracar ou vender nosso próprio navio",
"Presumo que você não valoriza seu próprio navio ",
"? Você não pode ficar com ele quando assumir o controle de um dos navios do comboio.",
"Verdadeiro. É melhor voltar para o estaleiro",
"Não, eu não poderia me importar menos com aquela banheira velha. Vou conseguir algo melhor do comboio.",
"Eu não vou embora! Se meu pai permanecer e arriscar a vida para defender nossa cidade, por que eu deveria fazer menos",
"Então vença, pai, pelo bem de todos nós! E se não, tenha certeza que vou te vingar!",
"Esse é o espírito! Agora, vamos seguir nosso caminho.",
"Você me levou a aventuras que eu não poderia ter imaginado antes. E você provou ser um valente capitão e verdadeiro amigo de #sSantiago#. Durante o tempo que estivemos juntos, aprendi a amar você. Então, sim, eu ficaria muito feliz em me casar com você ",
"Fico muito feliz em ouvir isso ",
"Não. Corra para a saída da cidade, AGORA",
"E isso foi uma boa reflexão e uma conversa rápida de sua parte! Mas parece que afinal ele se lembrou de você - corra para a saída da cidade!",
"Ainda não terminei minha carta. Deve estar pronto amanhã.",
"Muito bem, demore o tempo que precisar.",
"Bem, capitão? Você já decidiu meu destino?",
"Não, mas eu sei como evitar que você escape.",
"Como? Você vai me trancar nesta cabana? Ou me colocar no porão, com uma dupla de marinheiros pesados sentados na escotilha?",
"Nenhum. Ali está a porta para a prancha de embarque. Se você quiser voltar para seu pai e ",
", ninguém vai te impedir, então não é uma grande fuga, não é?",
"E se eu não for?",
"Então você está aqui por sua própria escolha e não vai querer escapar.",
"Muito bem, então escolho ficar, por enquanto. Mas não quero que meu pai se preocupe comigo. Gostaria de escrever uma carta para ele, explicando que saí por vontade própria e por quê",
"Mova-se rapidamente! Nós não temos muito tempo.",
"Como você passou pelos guardas ",
"O comerciante do porto me deu algo para colocar nas bebidas. Mas eles não ficarão inconscientes por muito tempo, então temos que sair agora",
"Você tem a chave desta porta?",
"Sim, de um dos guardas. E não se esqueça de recolher o seu equipamento. O comandante está com ele e não está em condições de recusar - por enquanto.",
"Tudo bem, vou pegar minhas coisas na saída. Vamos!",
"Seu navio foi apreendido após sua prisão. Não vamos chegar perto dele agora.",
"Seus navios foram apreendidos após sua prisão. Não vamos chegar perto deles agora.",
" Mas eu 'peguei emprestado' um pequeno navio que agora está atracado em Punta de Maisi. Podemos escapar com isso.",
"Qualquer navio é melhor do que ficar preso aqui. Vamos para a praia!",
"Tudo bem, acho que estamos seguros por enquanto. E você quer saber o que está acontecendo",
"Na verdade eu faço! Primeiro recebo a 'honra' de escoltar um enviado imperial. Ela desaparece misteriosamente e sou preso. E então você me tira da prisão, embora eu não tenha nenhum problema com essa parte",
" Sabe disso ",
" recomendou você para a missão de escolta. O almirante acredita que você o traiu e que meu pai pode estar aliado a você. Então meu pai também foi preso.\nSua única esperança agora é se você descobrir quem realmente o sequestrou ",
". Essa também é sua única esperança de limpar seu nome.",
"Eu vejo. Agora vamos tentar encontrar um enviado desaparecido. Talvez um dos meus antigos 'associados' em #sTortuga# possa ajudar.",
"Como você escapou da captura quando todos os meus outros oficiais foram capturados",
"Por que o comerciante lhe deu tudo o que você colocou nas bebidas dos guardas ",
"Enquanto vocês visitavam o almirante, aproveitei para fazer uma rápida visita a um velho amigo meu em #sHavana#. Então os soldados não me viram quando levaram todos os outros.\nTambém foi aquele amigo que me avisou que meu pai estava sob suspeita.",
"Ela não vende esse tipo de coisa para qualquer um. Mas eu a ajudei a começar seu negócio, então ela me devia um favor.",
"Você se lembrou de recolher seu equipamento?",
"Sim, o comandante deve ter deixado cair tudo quando desmaiou.",
"Não! Obrigado por me lembrar.",
"De qualquer forma, eu não tinha nada importante.",
"Muito bem. Mas não podemos voltar para o porto",
"Por que não?",
"Aquela caverna parece um bom lugar para os sequestradores se esconderem ",
"Verdadeiro. E como acabamos de lidar com o navio deles, eles não terão ido a lugar nenhum. Mas se atacarmos lá, eles podem matar ",
"Ou ela pode ser morta acidentalmente na luta. Talvez pudéssemos colocar algo lá para subjugar os sequestradores primeiro",
"Que tal uma garrafa de éter?",
"Eu tenho um fedorento.",
"Uma granada deveria subjugá-los permanentemente!",
"Você tem alguma sugestão ",
"Sim, isso seria perfeito. Num espaço tão confinado, o seu efeito seria maior.",
"Bom. Afaste-se, não queremos ser nocauteados também.",
"Isso envenenaria os sequestradores, mas também envenenaria a Eleitora",
"Você não está falando sério, espero? Queremos resgatar a Eleitora, não explodi-la em pedaços!",
"Muito bem, você tem alguma ideia melhor",
"Você tem uma garrafa de éter? Isso deveria deixar todos na caverna sem sentido. Sua Alteza poderia objetar mais tarde, mas pelo menos ela estaria viva para fazê-lo",
"Sim, isso funcionaria, e eu tenho um! Agora afaste-se, não queremos ser nocauteados também.",
"Não, não tenho nada disso, e se eu for procurar um, os sequestradores podem fugir",
"Teremos que arriscar. Aquele comerciante em #sHavana# provavelmente tem um, e não demorará muito para navegar até lá e voltar.",
"Muito bem, vamos voltar ao navio e navegar para #sHavana# imediatamente!",
"Deixe-me falar com ",
", por favor. Ela me conhece. Ela não te conhece.",
"Talvez você possa me apresentar? Caso eu precise de algo especial dela no futuro.",
"Ela não funciona assim. Sua confiança é conquistada, não comprada ou compartilhada. Então, se você quiser aquela garrafa de éter, deixe-me buscá-la para você.",
"Tudo bem, ",
". Se você é aquele em quem ela confia, compre uma garrafa de éter. ",
"Aqui está algum dinheiro. Se não for suficiente, eu te darei mais",
"Mas não tenho muito dinheiro no momento. Talvez você seja bom o suficiente para pagar pela garrafa?",
"Obrigado, ",
". Isso deve ser fácil.",
"Que corsário você é! Felizmente eu também tenho dinheiro suficiente.",
"Aqui está a garrafa de éter ",
"Obrigado, ",
". Vamos voltar para a caverna.",
"Você ainda tem aquela garrafa de éter",
"Sim, aqui está. Agora afaste-se, não queremos ser nocauteados também.",
"ER não.",
"Não me diga que você perdeu! Não temos tempo para conseguir outro.",
"Verdadeiro. Teremos que fazer isso da maneira mais difícil.",
"Espere um momento! Deixe o ar limpar antes de entrarmos.",
"Certo. Não queremos nos nocautear tão bem quanto o inimigo.",
"Isso funcionou bem! Todos os sequestradores estão inconscientes.",
"A Eleitora também. Talvez tenhamos que nos desculpar mais tarde. Mas pelo menos podemos tirá-la daqui sem nos preocupar com os sequestradores",
"Navegar daqui para #sHavana# pode levar dias, talvez até semanas, dependendo do vento! Não podemos arriscar que os sequestradores escapem. Teremos apenas que fazer isso sem éter.",
"Muito bem, ",
", como deseja proceder?",
"Veja se você consegue subir até lá ",
". Então procure um caminho de volta para a caverna. Se você encontrar um, não grite! Não queremos alertar quem está lá dentro. Apenas agite sua espada, então saberei que você está pronto.",
"Se eu encontrar outro caminho para entrar na caverna, o que você quer que eu faça",
"Espere até eu entrar. Se você me ouvir gritar 'Agora' ou se vir a luta começar, entre. Com um pouco de sorte, isso desequilibrará os sequestradores e os impedirá de matar a Eleitora. Agora vá em frente, comece a subir!",
"Basta seguir-me e torcer pelo melhor.",
"Sobre embarcar em navios inimigos...",
"Sim, acho que estou me acostumando com essa espada.",
"Sim, você pode contar comigo para cuidar de você!",
"Talvez, mas não quero me preocupar com você. É melhor você ficar a bordo do nosso navio ",
". Pelo menos para o próximo embarque.",
"Não tenho tanta certeza e não quero morrer cuidando de você. Fique em nosso navio.",
"Muito bem, mas se não posso estar ao seu lado, pelo menos lembre-se de levar outra pessoa para ajudar.",
"Como quiser, mas quero voltar à ação logo!",
"Vou manter isso em mente.",
"Sim, tenho certeza disso!",
"Não quero mais ser um passageiro inútil. Deixe-me acompanhá-lo na próxima luta!",
"Você pode estar embarcando, estou entediado! Eu quero ver ação!",
"Sim, acho que você está pronto agora. No próximo navio que eu embarcar, você estará lá comigo",
"Não, você ainda precisa treinar mais.",
"Bom, agora eu sei que você estará seguro comigo ao seu lado.",
"Excelente! Você não vai se arrepender quando me ver em ação.",
"Estou certo disso.",
"Há algo que sempre quis lhe perguntar ",
". Quando você entrou no meu quarto pela primeira vez, há muitos meses, quais eram suas verdadeiras intenções",
"Para ser brutalmente honesto, planejei sequestrar você e pedir resgate. Mas quando soube da sua situação, não consegui. Em vez disso, escolhi levar você para longe ",
".",
"Então, um pirata de coração mole! Mas estou muito feliz com isso!",
"Certamente acabou sendo uma das minhas melhores decisões ",
".",
"Eu já sabia do seu casamento forçado com ",
" e que você não ficou feliz com isso.",
"Infeliz? Eu acreditei que você estava prestes a me sequestrar e ainda assim preferiria ter ido com você do que se submeter àquele casamento odioso",
"Sim, lembro-me do seu desejo de vingança depois que #spronoun# raptou você e se casou com você de qualquer maneira. E o dinheiro que tiramos do comboio #spronoun3# foi muito maior do que qualquer resgate que eu pudesse ter conseguido ao sequestrar você",
"Espero que você não me veja apenas como uma fonte de dinheiro ",
"!",
"Certamente não! Não estaríamos sentados aqui agora se eu fizesse isso, minha querida.",
"O que você planeja fazer quando retornar ao mar ",
"?",
"Eu não tenho certeza, ",
". Posso continuar atacando navios inimigos.",
" Ou até mesmo atacar alguns fortes agora que tenho um homem de guerra.",
" E deve haver oportunidades no Caribe para um capitão experiente com um navio poderoso",
"Hmm... meu pai tem me contado sobre algo que pode ser uma dessas oportunidades. Pai, talvez o que você estava me dizendo antes ",
" chegou interessaria #spronoun2#?",
"Na verdade estamos. Estamos a caminho da alfaiataria.",
"Lidere o caminho, ",
"!",
"Esse vestido certamente fica bem em você ",
".",
"Isso não! Isso me faz parecer um saco de batatas e vou vestir minhas roupas de verdade assim que estiver em minha cabine!",
"Peço desculpas. Eu só queria te fazer um elogio.",
"Obrigado. Mas isso me dá uma ideia. Diga ao guarda que você acha o vestido muito chato e que ele seria melhorado com um broche que você viu à venda no comerciante do porto.",
"Você não precisa de uma bugiganga de um comerciante de rua. Tenho certeza que posso encontrar algo melhor nas joias de nossa família.",
"O broche não importa! Isso nos dá uma desculpa para ir ao porto. E isso nos coloca muito mais perto da minha nave. Vamos, vamos ver o guarda.",
"Esse vestido parece muito sem graça. Acredito que o comerciante do porto tenha um broche que faria você parecer mais adequado como membro da casa do governador. <Para o soldado> Agora iremos ao porto comprar o broche.",
"Você ainda quer que eu compre um broche para você",
"Capitán", // These are used to address you in case "First time".
"my dear", // Renumber them there if more lines are added above here
"my dear", // Alternative line for non-English translations when player character is female
}
