string DLG_TEXT[30] = {
"Hoje é um bom dia para morrer.",
"Hoje é um bom dia para outra pessoa morrer.",
"Você me liberta também?",
"Se você puder ajudar com os guardas",
"O quê, soltar um selvagem? Sem chance!",
"Eu sou um lutador durão. Eu também sei onde estão os escravos. Você quer resgatar seus homens, você precisa de mim.",
"Tudo bem, é um acordo. Eu tiro você daqui e você me ajuda a resgatar meus homens.",
"Eu agradeço pela libertação da prisão. Eu liguei para Two Dogs Fighting.",
"Você certamente é um lutador duro. Eu sou ",
". Provavelmente não teríamos derrotado os guardas sem você. Onde você conseguiu essa faca? Nossas armas foram tiradas de nós.",
"Espada grande fácil de encontrar. Faca pequena fácil de esconder.",
"Por que você estava na prisão?",
"Eu tomado como escravo. Quando os espanhóis me descobriram filho do chefe, me colocaram na prisão como refém. Agora eu tenho um novo acordo. Eu levo-te ao campo de escravos para encontrar tripulação, tu levas-me para casa.",
"Parece bom para mim!",
"O que? O acordo era que você me ajudaria a encontrar meus homens se eu tirasse você da prisão, o que eu fiz. Você está sozinho agora - se perca!",
"Então siga-me.",
"Vamos buscar minha tripulação!",
"Eu mantenho minha palavra, sua tripulação está livre. Agora você mantém sua palavra, me leve para casa",
"Claro que manterei minha palavra. Onde é sua casa?",
"A tribo vive na vila em #sisland_Isla Mona#.",
"Difícil. Eu não preciso mais de você. Se perder!",
"Eu sei como lidar com uma cobra de língua bifurcada.",
"Você deveria ter corrido enquanto teve chance!",
"Por favor, não conte a ninguém sobre isso. Para o resto do mundo ainda sou Two Dogs Fighting, sim?",
"Não se preocupe! Seu segredo está seguro comigo.",
"Você é um herói para Taíno. Sinto-me honrado em me juntar a você e lutar ao seu lado novamente.",
"Você é um guerreiro corajoso e habilidoso, e eu ficaria feliz em tê-lo de volta.",
"Desculpe, mas já tenho companheiros suficientes.",
"Todos os seus baixos pertencem a nós.",
"O que você diz!!",
}
