string DLG_TEXT[137] = {
"Sim? Você tem negócios aqui ",
"Não, devo ter entrado pela porta errada. Eu vou sair.",
"Sair! Você já se desonrou aqui. Vá embora ou preciso que você seja expulso",
"Relaxe, estou indo embora.",
"Veja. Outro vagabundo.",
"Meu nome é ",
" e quero que você saiba que não sou um vagabundo, sou um capitão do mar!",
"Oh, olhe, um vagabundo com um navio. Suponho que você veio pedir emprego?",
"Acontece que sim. Você tem algum trabalho que exija um navio?",
"É o seu dia de sorte, vagabundo. Esta carta precisa ir para ",
" do governador de #sSantiago#. Entregue-o, depois traga-me a resposta e você será pago.",
"Você pode considerar a carta tão boa quanto em ",
"já está nas mãos.",
"Bem? Você entregou a carta?",
"Ainda não. Em breve navegarei para #sSantiago#.",
"Sim. ",
" está ansioso pelo casamento.",
"Não exatamente. Um criado insistiu em pegar a carta e entregá-la ele mesmo",
"Sim, mas você não vai gostar da resposta. ",
" parece não gostar muito de você e teme o dia do casamento.",
"Não, um criado quis tirar-me a carta, o que eu não permiti.",
"Você mente! Não sei o que realmente fez com a carta, mas certamente não a entregou. Vá embora e nunca mais visite esta casa!",
"onde você ouviu isso? Não importa - você certamente não pode ter ouvido isso do meu ",
" em pessoa. Você falhou com minha confiança. Agora sai daqui!",
"Hah! Essa é a única coisa que você poderia ter dito e que mostra que você é confiável. Eu sabia ",
" não deixaria um estranho chegar perto da minha querida ",
". Aqui está sua recompensa. E agora tenho outra carta para você entregar. Além disso, pegue este anel. Isso marca você como meu agente de confiança. Mostre isso para ",
" e ele deixará você passar ou responderá a mim! Entregue este pessoalmente e traga a resposta.",
"Obrigado por confiar em mim esta missão. Você pode confiar na minha discrição.",
"Ah, você voltou ",
". Você conseguiu entregar a carta desta vez?",
"Sim, mas tenho medo ",
" não parece feliz com o casamento.",
"Não importa. Em breve vou persuadir ",
" mudar ",
" mente. Enquanto isso, aqui está sua recompensa. Agora, devolva meu anel e vá embora. Eu não preciso mais de você.",
"Aqui, pegue. De qualquer maneira, não parece tão valioso. Adeus.",
"Seu rosto parece familiar. Já nos encontramos antes?",
"Não, #stitle#.",
"Tenho quase certeza de que te conheço de algum lugar. Onde poderia estar?",
"Não pode ser, #stitle#. Eu certamente me lembraria de ter conhecido uma pessoa tão distinta como você.",
"Calmo e respeitoso! Eu gosto disso! Talvez você se pareça com um dos muitos vagabundos que visitam minha casa em busca de emprego. Mas você não pode ser um deles se for capitão da França.",
"Na verdade não, #stitle#.",
"Bem-vindo à minha nova casa, ",
"! Como você pode ver, a França recompensa bem seus amigos.",
" E meu querido ",
", agora seria um bom momento para deixar esse idiota e voltar para mim, onde você pertence.",
"Então considere isso. O próximo alvo da França é #sSantiago#. Eu poderia ser persuadido a dar refúgio seguro ao seu pai aqui. Cabe a você fazer a persuasão ",
"Obrigado pelo aviso. Teremos certeza de repassá-lo ao governador ",
". Com as defesas alertas, #sSantiago# não será tão fácil de capturar. E você não estará lá para traí-lo. Desembainhe sua espada!",
"Porque eu faria isso? Guardas! Prendam esse vagabundo!",
"Não fique muito confortável. Você não vai morar aqui por muito tempo!",
"Desafiador até o fim, não é? Mas é você quem não estará aqui por muito mais tempo. Guardas!",
"Covarde! Da próxima vez, enfrente-me você mesmo!",
"Bem bem! Se não for o vagabundo que persiste em se intrometer nos meus assuntos. Pensei ter reconhecido você naquele navio francês. ",
", não é? Você não vai impedir meus planos para #sRedmond# e #sSantiago# desta vez! Que travessuras mesquinhas você está fazendo agora?",
"Prendendo você. Há uma recompensa por trazer você, vivo ou morto. Qual caminho você prefere ",
"? Ou devo dizer ",
"Me prendendo? Você parece esquecer onde está. Guardas! Este é um espião inimigo! Prender prisão ",
"Eu vou lidar com você em breve!",
"Bom dia, ",
"! Ouvi dizer que você deu um passeio ontem à noite.",
"Sim, estava ficando chato aqui. Este lugar simplesmente não tem a classe de #sRedmond# ou #sHavana#.",
"#sRedmond#, você diz? Engraçado, isso. Você está conversando com o futuro governador de #sRedmond#. Conversaremos com o governador de #sPointe a Pitre# e transferiremos você para minha guarda.\nGuardas! Certifique-se de que este prisioneiro não escape daqui até a prefeitura.",
"Não sei de onde você tirou a ideia de que alguém em #sRedmond# permitirá que você os governe, mas vou continuar por enquanto. Isso deveria ser interessante, de uma forma ou de outra.",
"Excelência, este prisioneiro tem sido um incômodo para mim e desejo ficar com a custódia de #spronoun#.",
"E terei o prazer de organizar isso como meu primeiro ato como governador de #sRedmond#. Enquanto isso, a humilhação de ser levado para #sRedmond# como prisioneiro no próprio navio de #spronoun# não seria uma punição adicional adequada",
"Venha comigo, ",
". Será uma mudança para você viajar como passageiro em meu mais novo navio.",
"Seu navio?",
"Ah, esqueci de te contar? Meus homens capturaram o '#smyship#' enquanto você estava na prisão. Você será escoltado até lá.\nEntendo que o porão de carga é a acomodação normal para prisioneiros em navios, então nos veremos lá em breve.",
"Então agora você é um pirata e também um traidor",
"Ah, ",
", bem-vindo ao meu mais novo navio.",
"Sim, meus homens capturaram o '#smyship#' enquanto você estava na prisão.\nEntendo que o porão de carga é a acomodação normal para prisioneiros em navios, então nos vemos lá em breve.",
"Acredito que você esteja se sentindo adequadamente desconfortável ",
"Já estive em lugares piores.",
"Sim, você parece estar em casa em lugares desagradáveis. Provavelmente é por isso ",
" mudou de idéia e retomou #spronoun3# lugar de direito ao meu lado.",
"De fato. Mas onde está ",
"? Não vi #spronoun2# entre os outros prisioneiros.",
". E este navio parece familiar. Seria um daqueles que você roubou do meu comboio?",
"Esse comboio foi atacado legalmente sob autoridade do governador de #sSantiago# como retaliação pelo que você fez a ",
"Ah sim. Onde está #spronoun#",
"Isso... não é da sua conta.",
"Ah, mas é. Pela sua expressão, imagino que algo desagradável aconteceu com #spronoun2#. Que pena #spronoun# ter escolhido me deixar e ir embora com você.",
"Foi a escolha do #spronoun3# fazer qualquer coisa em vez de estar com você.",
"E ainda ",
"Então é assim, não é?",
" E agora, ",
", o que você pretende fazer comigo?",
"Depois de concluir meus negócios com o governador e o almirante aqui, navegaremos para #sPort au Prince# para nos encontrarmos com o '#swarship#'. No devido tempo ela invadirá #sRedmond#. Serei o novo governador lá.",
"Você terá uma revolta em suas mãos dentro de uma semana, traidor!",
"Concordo que algumas pessoas de #sRedmond# estão se revoltando, mas em breve aprenderão os costumes da civilização francesa.\nE me aceitarão, um #sperson# inglês nativo, de uma família respeitada localmente, mais prontamente do que um francês.",
"Não tenha tanta certeza. Eles não aceitarão bem uma #sperson# inglesa que trai #spronoun2# seu próprio país. Até o seu próprio pai te renegou.",
"Quem se importa com o que você pensa? Os franceses acreditam em mim, e é por isso que vão me colocar no comando.\nQuanto ao meu pai, ele é velho e não está muito mais neste mundo, depois do qual herdarei o nome da família e o negócio.\nE você terá uma bela visão de tudo isso da forca da cidade.",
"\nEnquanto isso ",
" estará ao meu lado para assistir ao meu triunfo e à sua execução. Venha, minha querida, não vamos mais sofrer com a companhia desse tolo.",
"Au revoir, ",
"Mais uma vez você interfere em meus planos ",
"Sim, ",
". Belo navio que você tem aqui. Acho que vou aceitar.",
"Você acha que pode entrar na cabine de um dos navios mais poderosos da marinha francesa e viver? Guardas! Temos um clandestino!",
"Ligue para quem quiser. O navio já é meu. A tripulação está toda morta ou meus prisioneiros. Você é o próximo.",
"Que assim seja. Você já me atormentou por muito tempo. Pelo menos terei o prazer de acabar com você do meu sofrimento.",
"O prazer será todo meu.",
"Muito bem, governador. Sua esposa ainda está viva. Se você continuar a cooperar, ela continuará assim.",
"E agora, ",
"Bem-vindo, ",
" - larguem suas armas ou matarei o Governador #sgovernor#.",
"Se eu fizer isso, você vai matá-lo de qualquer maneira.",
"Não, não vou. Eu preciso dele vivo para entregar #sRedmond# para mim.",
"Quem vai aceitar tal documento? A invasão é derrotada. Eu já cuidei disso. Não sobrou ninguém para impor sua regra aqui.",
"Maldito, ",
"Esse é o espírito! Sou eu que você quer, então aqui estou - venha e lute!",
"E então o governador #sgovernor# simplesmente ordenará que seus guardas me matem.",
"Não, ele não vai. Excelência, você precisará dar sua palavra de que se #svillain# me derrotar, você dará ao #spronoun2# salvo-conduto de #sRedmond#.",
"Que assim seja. ",
", você me cruzou pela última vez!",
"Como você está certo, #svillain#. De uma forma ou de outra, isso acaba agora!",
"Vá em frente, mate-o. Enquanto sua lâmina estiver presa nele, você estará indefeso. Vou cortar sua mão. Então vou cortar outros pedaços e forçá-los a você.",
"Você ficaria parado e me deixaria matar o governador #sgovernor#?",
"Por que não? Não devo lealdade à Inglaterra. Você o mata, eu mato você e depois saqueio este lugar. Então eu digo a todos que você matou o governador e eu o vinguei.",
"Isso pressupoe que será você quem sairá daqui, o que não acontecerá. Você se opôs a mim muitas vezes. Você não viverá para fazer isso de novo.",
"Não vamos concordar sobre quem vai sair daqui de pé. Então desembainhe sua espada e vamos descobrir!",
"Eu simplesmente não consigo me conter, #svillain#.",
"Eu deveria saber que não podia confiar no #sadmiral#. Se eu quiser que algo seja feito corretamente, terei que fazê-lo sozinho.\nÉ hora de acabar com isso de uma vez por todas. Você gostaria de lutar comigo, um contra um?",
"Eu não aceitaria de outra maneira. Estou ansioso por isso há muito tempo. Desembainhe sua espada!",
"Parar! Eu proíbo isso!",
"Eu sou #svillain#. #sromance# é meu!",
"E eu digo que #sromance# é casado comigo, para o resto de nossas vidas. Se #spronoun# for casar novamente, será por cima do meu cadáver!",
"Posso concordar com isso.",
"Você ouviu o padre. Vamos continuar com isso lá fora?",
"Não! Este é outro de seus truques ",
"! Se quisermos lutar, será aqui! Agora!",
"Aliás, você tinha alguns prisioneiros franceses. Eu os liberei, é claro.",
"Pelo menos não terei que compartilhar meu domínio com eles.",
}
