string DLG_TEXT[14] = {
"Esta é a melhor refeição que você terá pelo resto da vida.",
"Quase me deixa ansioso pelo enforcamento.",
"Coloque isso na sua garganta enquanto você ainda pode engolir alguma coisa.",
"Alguma chance de um pouco de pão?",
"Alguém deve gostar muito de você, para mantê-lo aqui para que você possa comer meu lindo ensopado.",
"Castigo cruel e incomum, eu chamo assim.",
"Aqui está a sua refeição, pirata!",
"Chama isso de comida? Eu não daria isso aos ratos do navio!",
"O que você está fazendo fora da sua cela? Guardas!",
"Cale a boca, a menos que queira outra dor de cabeça!",
"Ah não, você de novo não!",
"Sim, eu de novo.",
"Bem, não se preocupe em me bater de novo. Não carrego mais chave. Aproveite o seu guisado!",
"Oh não, de novo não...",
}
