string DLG_TEXT[32] = {
"Tem rum?",
"Espere até chegarmos a #sTortuga#. Você pode se encher de rum lá.",
"Bem, o que temos aqui? Eu não esperava nenhuma visita.",
"Nem esses guardas, e eles estão prestes a ter outra surpresa",
"Qual é o preço da minha liberdade?",
"Não se preocupe, você não está pagando. Seu chefe está me fazendo um favor, então estou fazendo um por ele, tirando você daqui",
" está preocupado comigo? Tocante. Mas espero que você tenha um plano além de chegar até a porta.",
"Eu quero, e isso não envolve esperar por aqui. Vamos nos mover! Mas primeiro você veste aquele uniforme de soldado.",
"Por que?",
"Porque é improvável que os guardas lá fora nos deixem sair com você parecendo um pirata, não é",
"Fique em pé quando falar comigo, soldado!",
"Não. Fiquem em seus postos. Certifique-se de que o prisioneiro não tente escapar.",
"O que acabei de te dizer? Fique nas suas postagens aqui!",
"Vamos, sargento. Não queremos que os contrabandistas fujam antes que você tenha tempo de chamar seus homens",
"! Não te vejo desde que você me tirou de #sPointe a Pitre#.",
"Como a vida tem sido com você, ",
"No geral, nada mal. Mas tenho uma novidade para você que fica melhor acompanhada de cachaça.",
"Tudo bem, para a taverna então",
"Você parece um capitão livre",
"Sim eu sou ",
"E eu sou ",
". Prazer em conhecê-lo, especialmente porque tenho notícias que são melhor contadas com um pouco de rum.",
"Para negócios.",
"Para os negócios! Saúde!",
"Não foi isso que eu quis dizer, mas de nada. O que eu queria dizer é que #sisland_Isla Mona# não é mais seguro para gente como nós. Os franceses assumiram o controle!",
"O QUE? Que tipo de força eles enviaram?",
"Não fiquei por aqui para descobrir! Mas eu vi uma fragata.",
"Apenas uma fragata?",
"Apenas? Ela é mais que suficiente para enfrentar meu navio. Pelo menos ela não me perseguiu - provavelmente mais preocupada em proteger a ilha",
"Talvez, mas acho que poderia levar uma fragata - talvez até ficar com ela para mim. Obrigado pela mensagem, no entanto.",
"Bom te ver, ",
"Você também, ",
}
