string DLG_TEXT[41] = {
".",
".",

"Sim. Por que você pergunta?",
"Tenho notícias terríveis para você - #spronoun# foi sequestrado! Um dia #spronoun# estava andando por aí e uma gangue de homens agarrou #spronoun2# e fugiu. Como seria de esperar, os soldados não fizeram nada - faz você se perguntar por que alguém paga impostos",
"Alguma ideia de onde eles levaram #spronoun2#?",
"Não, só há uma saída desta área e não consegui ver para onde eles foram em seguida",
"Eu vejo. Bem, obrigado por me avisar de qualquer maneira. Adeus.",
"Ah, mais um visitante da casa do #smerchant#. Você conhece sua história?",
"Não, é interessante?",
"Dizem que quando a Espanha era dona de #sisland_Redmond#, aquela casa pertencia à Inquisição. Não é de surpreender, com a vista por cima do muro.",
"Boa maneira de espionar o governador, então. O que mais eles fizeram?",
"Bem, a história é que a Inquisição tinha a sua prisão algures naquela masmorra vizinha. Pessoas torturadas, eles fizeram. E até hoje a masmorra é assombrada pelos fantasmas de suas vítimas.",
"Fantasmas? Não existem fantasmas!",
"Provavelmente foi o que a gangue que levou aquele jovem #sperson# para lá pensou. Mas ninguém que desce lá sai novamente. Não diga que eu não avisei",
"É verdade. Se eu for até lá e encontrar seus fantasmas, não poderei dizer muita coisa. Obrigado pelo aviso embora!",
"Bem-vindo, capitão! O que você quer?",
"Estou procurando um dos meus oficiais. Um #sperson#, jovem e provavelmente com aparência de nobre, esteve por aqui recentemente",
"Sim. Um grupo de marinheiros também esteve aqui para #spronoun#. No início #spronoun2# parecia disposto a acompanhá-los, depois houve uma discussão, mas #spronoun2# foi com eles mesmo assim. Um deles pode ter uma arma escondida.",
"Eles não podem ter sido minha tripulação. Se eles tivessem trazido meu oficial de volta ao meu navio, eu saberia disso. Obrigado de qualquer maneira.",
"Talvez não. Mas a história também diz que a Inquisição escondeu todo o ouro que tirou das suas vítimas lá embaixo. Então, ocasionalmente, alguém vai procurá-lo. E eles nunca mais voltam",
"Ouro? O que quer que esteja lá embaixo não são fantasmas, mas se houver ouro, será meu. Obrigado pelo aviso sobre os 'fantasmas'!",
". Olá, ",
"Posso te ajudar, ",
"Olá. Talvez você possa me ajudar. Estou procurando por #svillain#, que me disseram que estava navegando aqui no '#sship#' do East Indiaman. Você viu #spronoun2#?",
"Não, não me lembro de ninguém com esse nome.",
"Você viu o '#sship#', então? Ela deveria ter navegado aqui de #sRedmond#.",
"Não, quase todos os navios ingleses que chegaram aqui recentemente vieram de #sCharlestown#. Os navios do õeste são em sua maioria espanhóis.\nEstranho, a Holanda é amiga da Inglaterra e da Espanha - geralmente estamos em guerra com um ou outro.",
"A política não me interessa. Mas eu realmente preciso encontrar #svillain# - #spronoun# tem tentado ajudar os franceses e há uma recompensa por trazer #spronoun2#.",
"Se #spronoun# for amigo da França, talvez você esteja procurando no porto errado. #sMarigot# está do outro lado desta ilha e pertence à França.\nMas não tente caminhar até lá porque estamos sitiando #sMarigot# e os franceses estão sitiando #sPhilipsburg#. Se os soldados não o matarem, uma bala de canhão o matará.\nE o forte francês pode ter visto você quando você se aproximava da ilha, então navegar para #sMarigot# pode ser perigoso. Mas alguns dizem que há um túnel entre #sPhilipsburg# e #sMarigot#. Talvez você possa encontrá-lo.",
"Obrigado, é útil saber disso. Adeus.",
". Bom dia, ",
"Olá.",
"'Olá'? Você parece inglês!",
"Por nascimento, sim. Por opção, amigo da França. Como #svillain# - você viu #spronoun2#?",
"Ah, isso é diferente então. Qualquer amigo da França é um amigo para mim. Sim, #svillain# esteve aqui há alguns dias e depois partiu para #sPointe a Pitre# na ilha de #sisland_Guadeloupe#.",
"Obrigado! Talvez eu consiga alcançar #spronoun2# lá.",
"Vou lhe contar mais uma coisa, pois você é amigo da França. Você vê aquele navio lá fora?",
"O grande com muitas armas?",
"Esse é o único. Esse é o '#sship#'. Ela acabou de chegar. Os ingleses e seus aliados não têm nada parecido com ela. Agora que o '#sship#' está aqui, vamos limpá-los do Caribe!",
"Isso é realmente uma boa notícia. Obrigado novamente e adeus. <Pensa: me pergunto quanto os ingleses pagariam para saber disso. Talvez tente a sorte em #sisland_Antigua#.>",
}
