string DLG_TEXT[46] = {
"O que alguém pode fazer por um?",
"Er, nada. Desculpe incomodá-lo.",
"Capitão. Você está aqui antes de mim, e ",
"Matheus Santos",
" ainda está vivo e bem. Você decepciona um. Terrivelmente!",
"Mantenha sua camisa, sua camisa feminina grande e fofa com babados...",
"De fato. E você?",
"Um amigo de um velho conhecido seu: Mateus Santos.",
"Mateus Santos ainda está vivo? Como isso é possível?",
"É possível porque você contratou um idiota como assassino. Bem, o vento mudou, meu amigo, e a maré mudou.",
"Matheus Santos",
" me fez uma... oferta mais convincente. Você pode orar antes de morrer, mas seja rápido. Sou um homem ocupado.",
"Sim, e você me enganou. O trabalho acabou por ser tudo menos simples. Esse ",
"Matheus Santos",
" Acontece que não é um alvo fácil. Na verdade, ele me ofereceu um bom dinheiro em troca da sua pele mentirosa.",
"Capitão, você poderia dispensar um por um momento? Alguém tem uma tarefa que exige um homem com suas habilidades e... reputação únicas",
"Estou ouvindo, mas não por muito tempo...",
"Se você me conhece de reputação, então já sabe que não tolero tolos de bom grado.",
"Como você fará, mas nunca se pensou que veria o dia em que outro recusaria um bom dinheiro por um empreendimento tão insignificante.",
"Quão insignificante e quanto dinheiro? Você tem toda a minha atenção.",
"Você ainda está falando? Já basta!",
"Ah, é a própria simplicidade, se alguém tiver estômago para isso, e suspeita que você tenha. Há um partido que está ameaçando alguém e alguém quer que isso pare. Já ouvimos dizer que você é o tipo de homem que consegue convencer as pessoas de quase tudo",
"Alguém já está meio convencido, mas teria que ver a cor do ouro do outro antes de poder reunir qualquer sentimento de convicção real ou duradouro",
"Ah, entendi agora. Um trabalho simples, se você não se importa com dinheiro sangrento. Desculpe, mas essa não é minha linha de trabalho. Contanto.",
"Alguém pagaria com prazer 1.500 ouro por este serviço trivial. Requer que você faça uma visita ",
"Matheus Santos",
"Matheus Santos",
"Sim?",
"Você é Ambroz Bricenos?",
"Você deve estar brincando. Não respiro por esse tipo de dinheiro. Já vivi o suficiente para saber que não devo fazer o trabalho de um assassino.",
"Alguém esteve escondido, ou melhor, ficou no seu iate, que se mantém perto da costa em #sisland_Conceicao#. Encontrará alguém em terra perto do acampamento dos contrabandistas.",
"Descobriremos que não devemos esperar muito para ouvir as notícias que queremos ouvir",
"Capitão, eu imploro - poupe minha vida! Eu te dou 1.500 ouro, é tudo que tenho. Pegue, mas por favor não me mate!",
"Desculpa amigo. Negócio é negócio e ",
"Matheus Santos",
" paga mais.",
"Bem... eu sempre fui um fanático por moedas. Dá-me o dinheiro e vai.",
"Não quero o seu ouro, seu idiota. Apenas pare de chorar e corra antes que eu mude de ideia!",
"Não é nada comparado à vida de alguém. Pegue, e eu irei",
"Apenas faça e seja rápido!",
"Seu idiota patético. Não acredito que você caiu nessa! Você é muito estúpido para viver!",
"Você me deixaria ir, simplesmente assim? Eu... eu... não posso acreditar!",
"Tente muito. E faça isso em outro lugar, antes que eu mude de ideia.",
"Sim, é bom demais para ser verdade, não é? Talvez seja porque eu menti. Faça suas orações e faça-as rapidamente!",
"Você é o diabo personificado, posso não ser o melhor espadachim, mas você descobrirá que um homem lutar por sua vida não é um desafio fácil. En garde!",
"Eu vou te matar com a consciência tranquila, tendo lhe dado uma chance justa.",
};
