string DLG_TEXT[28] = {
"......",
"......",
"O que você quer, estranho?",
"Você é o chefe deste acampamento?",
"Sim eu sou.",
"Eu tenho um acordo para você.",
"Que tipo de acordo?",
"Um negócio interessante. Você pode ganhar muito ouro se me ajudar.",
"Você, homem branco, só está interessado em ouro, mas os Arawaks não estão interessados em ganância",
"E liberdade, você está interessado?",
"O que você quer dizer?",
"Eu sei que a relação com os holandeses não é muito boa.",
How that could be in another way with people stealing our land., 
"Eu trabalho para uma nação poderosa que poderia lhe dar mais direitos.",
"Se bem entendi, você é o representante de uma nação que precisa de nossa ajuda.",
"Exatamente.",
"Quais são os direitos que poderíamos ter?",
"Se você nos ajudar a expulsar os holandeses de Aruba, você nunca será oprimido como é agora",
"O que? Você quer que lutemos contra os holandeses?! E se a sua nação não vencer a batalha, você sabe perfeitamente que os holandeses matarão todos os Arawaks da ilha como punição",
"Se você não me ajudar, os Arawaks morrerão de qualquer maneira devido à colonização holandesa... lentamente, mas eles morrem.",
"Não sei por que você quer lutar contra os holandeses em Aruba, mas para mim é uma guerra entre homens brancos na qual os Arawaks não têm interesse em participar",
"Tudo bem, não consigo te convencer. não vou insistir...",
"No entanto, posso ajudá-lo se você quiser.",
"Como?",
"Há uma tribo nas montanhas que aceitaria lutar por você. Pelo menos, eles gostam de ouro.",
"Interessante.",
"Eles não são Arawaks. Eles pertencem a outro grupo étnico.",
"Eu vou para lá. Diga-me exatamente onde posso encontrá-los.",
};
