string DLG_TEXT[46] = {
"......",
"......",
"Capitão Elting?!",
"Você não está feliz em ver seu ex-sargento",
"Não ex-soldados indisciplinados.",
"Na sua opinião, eu era indisciplinado. Na minha opinião, estava apenas criticando suas ordens deploráveis. Nunca entendi como alguém tão incompetente alcançou o posto de capitão do exército holandês",
"Não pense que por não estar sob minhas ordens de agora em diante você pode me insultar",
"Você está certo, não deixe que nossas divergências pessoais atrapalhem minha missão.",
"Sua missão? O que você quer dizer?",
"Você está preso!",
"O que?! Ha-Ha!! Tudo bem, você está louco. Eu teria que adivinhar. Abra o caminho e não perca meu tempo!",
"Não estou brincando, não me force a usar minha lâmina.",
"É o bastante! Você merece uma lição.",
"En garde!",
"Tudo bem, tudo bem... Não me mate! O que você quer exatamente?",
"Isso é melhor. Siga-me até o meu navio, eu te explico",
"E agora?",
"Vou te levar para Havana amanhã.",
"O que?! Havana?",
"Sim, o vice-almirante Benavides quer conhecer em detalhes as defesas de #sisland_Douwesen# para um futuro pouso e para capturar #sDouwesen# é claro.",
"Então, era verdade quando as pessoas disseram que você trabalhava para os espanhóis.",
"Essa é a vida, capitão.",
"Escória de mercenário!",
"Tenha cuidado com a língua, capitão. Caso contrário, sua viagem poderia ser muito dolorosa. Meu oficial irá levá-lo para o porão, você fará companhia aos ratos ha! ah!",
"Capitão Elting?! Como você se atreve a vir aqui? Desta vez, você não vai escapar de mim. Você está preso, traidor!",
"*Tom humorístico* Muito bem, Capitão de Voor. Mais uma vez, graças à sua inteligência, você me encontrou. E devo dizer que não foi fácil; um homem desembarcando no único porto desta ilha. Estou impressionado...",
"Você gosta de me levar para passear, não é? Veremos se você continua se exibindo na presença do Governador. O destino de um traidor como você é a forca, se você não sabe",
"A propósito, conhecer o Governador é o que eu queria fazer",
"(Berend ao Governador) Excelência, eu estava patrulhando quando vi um navio não identificado em Palm Beach.",
"(Governador para Berend) Talvez um navio pertencente aos contrabandistas.",
"Não, governador. Esse é o problema. É um navio de guerra, não um navio mercante.",
"(Você para Berend) Um navio de guerra aí? Suponho que seja um navio inimigo, caso contrário ela teria atracado aqui, no porto.",
"Acho que sim, mesmo que ela não tivesse nenhuma bandeira hasteada.",
"Que tipo de navio de guerra ela é?",
"Um Xebec mas muito bem equipado. Ela tem muitos canhões. Devo dizer que foi a primeira vez que vi um Xebec assim.",
"É ela!",
"Demos-lhes uma boa lição!",
"Acho que matamos a maior parte da tripulação deles. Não pode haver muita gente na nave.",
"Eu penso que sim. Devíamos atacar o navio agora mesmo.",
"De fato. Vamos para Palm Beach!",
"O navio ainda está aqui. Vamos!",
"Eu preferiria que você ficasse na praia.",
"Por que? Deve ser perigoso embarcar sozinho no navio",
"Posso lidar com os poucos homens restantes no navio. Além disso, não sabemos se há outros tripulantes na selva que possam retornar ao navio. Você deveria proteger a costa enquanto eu a bordo.",
"Como você quiser. Mas, se você demorar muito para capturar o navio, eu me juntarei a você.",
"Tudo bem. Minha prioridade é encontrar e matar o capitão deles. Serei rápido.",
};
