string DLG_TEXT[175] = {
"......",
"......",
"Capitão Johan Elting?",
"Certo. Você é meu novo oficial?",
"Sim capitão. Meu nome é Chico Cois. Já fiz os preparativos para a nossa viagem e a tripulação está esperando por você a bordo do navio.",
"Você conhece nossa missão?",
"Sim. Um soldado veio e me deu as instruções. Temos que encontrar um espião em #sGrand Cayman# e trazer um relatório. Eu conheço esse espião, então darei alguns detalhes úteis sobre ele durante a viagem.",
"Tudo bem, só temos um mês para realizar esta tarefa, então vamos parecer animados agora.",
"Quais são as suas ordens capitão?",
"Siga-me, vamos verificar a casa dele.",
"Droga, ele não está em casa?",
"Que má sorte! E agora?",
"Talvez ele ainda esteja no forte. Devíamos esperar por ele.",
"Eu não gosto de esperar. Acho que deveríamos encontrá-lo primeiro, caso ele tenha sido pego.",
"Espere capitão! Você será preso se ele for pego ou o colocará em sério risco se não o fizer.",
"Humm.. Tudo bem, vamos esperar um pouco. Talvez ele esteja apenas atrasado.",
"Você poderia envenená-lo.",
"Como?",
"Tenho duas facas de arremesso envenenadas.",
"Você tem razão. Eu poderia matá-lo antes que ele entrasse na prefeitura. Dê-me as facas!",
"Pegue eles!",
"Enquanto isso, você e Domenico me esperam aqui. Devo voltar logo.",
"Esta é a arma especial que o vice-almirante estava falando: um fedorento.",
"Como funciona?",
"Jogue-o entre um grupo de soldados e eles serão rapidamente mortos pela fumaça.",
"Interessante.",
"Mas tome cuidado com a direção do vento para não ser morto pela fumaça também.",
"Obrigado Chico, vou lembrar. Agora vamos para #sPort au Prince#.",
"O que ele disse?",
"Vamos conversar lá fora. Será mais seguro.",
"Então?",
"Poucas pessoas conhecem a missão do navio.",
"Não será fácil descobrir o que os franceses estão preparando.",
"Não, mas talvez eu tenha uma solução. O capitão de 'La Fougueuse' encontrou-se com o governador logo após a sua chegada, existe a possibilidade de ele lhe ter dado uma ordem de missão.",
"Uma ordem de missão? Quer dizer que existe um documento na Câmara Municipal?",
"De fato. Se eu encontrar, terei provas da traição da França e conhecerei a missão sem alertá-los.",
"Tudo bem, mas a prefeitura é guardada por soldados... Mesmo à noite.",
"Sim. Guardas na porta. Não se preocupe com isso, Chico. Esta noite, encontrarei um caminho para a prefeitura, enquanto isso, vá e espere por mim no navio.",
"Você conseguiu, capitão?",
"Sim, encontrei a ordem da missão, o navio foi ordenado para #sisland_Conceicao#, como suspeitávamos. Os franceses não perderam muito tempo ajudando os portugueses.",
"Então, precisamos impedir que ela vá embora.",
"Exatamente. Se o estalajadeiro estiver certo, amanhã é seu último dia em #sFalaise de Fleur#. Acho que a maneira mais fácil de parar o navio seria capturar ou matar o capitão Aurelien Bergerat. Precisamos saber os movimentos do Capitão até amanhã de manhã e agir rapidamente.",
"Para que possamos preparar uma emboscada?",
"Sim. Mas, vamos descansar esta noite. Amanhã será um dia difícil.",
"Tenho boas noticias.",
"Você voltou, Chico! Bom, me diga o que você descobriu?",
"Não foi fácil, mas descobri que o Capitão verá o alfaiate e o Governador esta manhã.",
"Era provável que ele se encontrasse com o governador antes de partir, mas por que o alfaiate?",
"Ele deixou muitas de suas roupas lá há alguns dias. Ele provavelmente quer recuperá-los antes de ir para #sisland_Conceicao#.",
"Ele deve ser um daqueles capitães pavões, mais preocupados com a vestimenta do que com os navios. Vamos esperar por ele no porto para não sentir falta dele chegando em terra.",
"É ele no cais!",
"Droga!! Dois soldados estão com ele. Não podemos capturá-lo. Teremos que matá-lo e aos seus soldados, precisamos ser discretos e há muita gente por perto.",
"Eu tenho uma maneira de matá-lo - discretamente.",
"Como Chico?",
"Eu tenho uma bomba-relógio.",
"Uma bomba-relógio? O que é?",
"É como uma grande granada com um pavio longo. Eu poderia colocá-lo no caminho dele, fugir e a bomba explodiria alguns segundos depois.",
"Maravilhoso!! [PENSA: Será que isso foi para mim se eu falhei] Vamos seguir o capitão para escolher o momento certo para a emboscada.",
"Seus soldados estão em frente à alfaiataria.",
"Sim. Ele deve estar lá dentro. Em alguns minutos, ele irá para a Câmara Municipal. Siga-me, vamos preparar a emboscada perto do Gabinete do Agiota.",
"Ele deve estar a caminho agora. Qual é o seu plano, capitão?",
"Fique aqui. Ao vê-lo, acenda o pavio da sua bomba-relógio, coloque-a no chão e saia daí. A explosão trará os soldados como moscas para um cadáver. Depois disso, espere por mim em Octopus Bay com nosso navio.",
"Tudo bem.",
"Boa sorte Chico!",
"Estou feliz em ver que você conseguiu.",
"Obrigado Chico. Você teve algum problema para sair da cidade?",
"Não, aproveitei a confusão e saí da cidade escondido pela multidão assustada. Os guardas não sabiam que caminho seguir em meio a toda a confusão. E você?",
"Fui à igreja e esperei silêncio, antes de me certificar de que o capitão francês estava morto. Não pensei que aquela pequena bomba fosse tão poderosa.",
"Usei meu melhor pó. Quais são seus pedidos agora? Já vamos sair da ilha?",
"Ainda não. Ficaremos aqui até amanhã de manhã. Quero ter certeza de que o navio francês não partirá para ajudar #sisland_Conceicao#.",
"Você gostaria que eu descobrisse seus planos amanhã?",
"Sim. Mas tenha cuidado, os guardas suspeitarão de qualquer estrangeiro que faça perguntas.",
"Más notícias, capitão! O navio partiu de #sisland_Falaise de Fleur# durante a noite.",
"O que?! Como isso é possível? Quem está no comando de 'La Fougueuse'?",
"Um oficial do navio foi promovido em campo pelo próprio Governador e é auxiliado por um dos Capitães do próprio Governador.",
"Vá em frente! A emboscada apenas acelerou as coisas. Não temos tempo a perder. Vamos navegar para #sisland_Conceicao# e torcer para alcançar o navio.",
"Você notou que o navio atracado na entrada do porto se parece muito com 'La Fougueuse'?",
"Na verdade ela faz. Mas ela não hasteia a bandeira francesa e seu nome foi alterado se for ela.",
"Você acha que é ela e os franceses a disfarçaram?",
"Tenho certeza disso. A missão deles é secreta e eles não querem que os espanhóis saibam o que estão fazendo. Pelo menos, eles tentaram. Mas vamos para a taberna, talvez possamos encontrar uma prova da nossa teoria para o vice-almirante.",
"Agora, temos as evidências. Há quase um soldado francês em cada canto da #sConceicao#.",
"*tom irônico* Certo. O governador português deveria mudar o nome da sua cidade para Saint-George.",
"Qual é o plano agora?",
"Não creio que tenhamos outra opção senão afundá-la.",
"Não me diga que você quer atacá-la.",
"Com nosso navio? Claro que não. Seu tamanho e o fato de estar sob a proteção do forte impossibilitam o embarque. Mas sabotar o navio é viável.",
"Como podemos nós?",
"Graças às suas bombas-relógio. E muitos dos seus tripulantes estarão em terra.",
"Você cometeu um erro, capitão. Essas bombas podem matar pessoas, mas fazem um buraco no casco de um navio de linha! 'La Fougueuse' não é um barco de brinquedo.",
"Você tem razão. Mas você sabe que os navios de guerra têm um ou dois depósitos de pólvora, entenda.",
"Eu faço agora! Você quer colocar as bombas-relógio perto dessas lojas. Um plano astuto.",
"Sim. Mesmo o casco de um navio de linha não pode resistir a tal explosão.",
"Será perigoso entrar furtivamente a bordo, haverá sentinelas e.....",
"Se você tem uma ideia melhor, sou todo ouvidos.",
"Humm... não, nada melhor vem à mente.",
"Tudo bem, nós resolvemos isso. Esta noite, irei e farei a escritura. Enquanto isso, prepare as bombas-relógio.",
"Aqui estão duas bombas-relógio. Tudo que eu poderia fazer. Eles terão que ser suficientes para sua operação.",
"Obrigado. Se eu não voltar antes do amanhecer, volte para #sHavana# e informe ao Vice-Almirante que falhei na missão.",
"Use uma garrafa de éter, Capitão.",
"O que?",
"Com isso, você pode atordoar qualquer um. Você só precisa esperar até que ela saia do bordel.",
"E terei tempo para procurar a chave entre as roupas dela. Ótima ideia, Chico!",
"Eu irei com você, capitão.",
"Não, Chico. Tenho outra tarefa para você. Enquanto eu cuido das formalidades, você fará o reconhecimento do forte. Quero sabotar os canhões esta noite.",
"Já encontrei uma maneira de sair do porto.",
"Bom. Quando você encontrar a entrada do forte, junte-se a mim na taverna.",
"Achei que ele não iria me libertar. Desculpe capitão pelo problema.",
"Não se desculpe, a culpa é minha. Eu deveria saber - a missão era ambiciosa, para dizer o mínimo.",
"De qualquer forma, mesmo não tendo entrado no forte, encontrei uma maneira de entrar.",
"Realmente? Cadê?",
"Infelizmente. Fui preso antes de chegar ao forte. Mas há um caminho ao longo da cornija. Pelo que vi, parece que há um túnel para entrar no forte.",
"Obrigado pela informação, Chico, já sei o suficiente. Vamos voltar para a taberna.",
"É tarde, capitão. Qual é o seu plano?",
"Vou trocar de roupa no armazém para que ninguém me reconheça. A esta hora, o fornecedor de alimentos já se foi.",
"Você tem as bombas-relógio para os canhões?",
"Sim. Vou colocá-los atrás de cada canhão. Enquanto isso, você sairá do porto com o navio. Se necessário, cuide dos guardas do porto para que não soem o alarme.",
"E onde te encontrarei depois de destruir os canhões?",
"Vá para o forte, mas espere pelas explosões antes de se aproximar dele. Ele disparará contra o navio se vir você navegando à noite.",
"Tudo bem, capitão. Vou preparar minha partida.",
"Boa sorte Chico!",
"Que grandes fogos de artifício!",
"Ha-Ha! Como você disse, Chico. Seus canhões são inúteis agora. Mas eu tive uma luta para chegar até eles. Você teve problemas para sair do porto?",
"Só um pouco! Alguns membros da tripulação e eu tivemos que matar alguns antes de levantar âncora. Os guardas simplesmente não paravam de patrulhar perto do navio.",
"Bom. Muito bem, agora podemos voltar a Havana. Deveríamos ter uma bela recompensa.",
"Qual é o seu plano, capitão?",
"Não posso entrar na cidade, é muito perigoso, as autoridades devem saber que trabalho para as autoridades espanholas. Então, vá lá e tente obter algumas informações sobre Berend de Voor, ele é o capitão do Forte #sisland_Douwesen# e meu ex-capitão.",
"Que tipo de informação você deseja?",
"No passado, de vez em quando, ele patrulhava a selva ao redor da cidade com seus homens. Verifique se ele continua fazendo esse tipo de missão. Se sim, descubra quando será a próxima missão.",
"Tudo bem, eu vou agora.",
"Eu tenho a informação!",
"Como você fez isso?",
"Conversando com alguns soldados na taverna... e pagando algumas bebidas para eles, é claro.",
"Bom. Então, o que eles te disseram?",
"Amanhã ele patrulhará a selva perto da vila dos contrabandistas.",
"Excelente! Temos a nossa oportunidade de capturá-lo.",
"Ele está vindo, capitão!",
"Deixe-me falar com ele.",
"Feito! Ele está trancado no porão.",
"Bom. Esta noite, abra discretamente a porta do porão para que ele possa escapar. Não deixe nenhum membro da tripulação atrapalhar. Estarei na costa para verificar o voo dele.",
"O navio é nosso, Capitão!",
"Obrigado, Chico. Onde está Bartolomeu?",
"Nós não o encontramos. Ele não está no navio.",
"O que? Como isso é possível? Ele não está na cidade ou no navio, então onde ele está?",
"Só encontrei o oficial dele, o homem à sua direita.",
"Vou interrogá-lo.",
"Sim?",
"Leve o oficial para minha nave. Ele será útil para encontrar seu capitão.",
"E a tripulação?",
"Tranque-os no porão deste navio para que possamos sair da ilha sem problemas.",
"Você sozinho? Onde estão meus homens?",
"Chico? Que surpresa! Então você é capitão agora.",
"Certo. O Governador de Havana me promoveu e deu como primeira missão prendê-lo.",
"Uma missão difícil para um primeiro.",
"Sim, mas não sou um lutador inexperiente.",
"Claro, mas um capitão não precisa apenas ser um bom lutador. Ele deve ser um bom líder e tomar as decisões certas. Isto é o que você não fez deixando seus homens serem emboscados.",
"Como você sabia que eu estava procurando por você?",
"Devo dizer que tive sorte. Uma patrulha detectou sua chegada e quando descreveram o navio, eu sabia que este navio era 'El Diablo'.",
"A sorte é um elemento importante nestas missões perigosas.",
"Sim, mas você deveria ter ordenado à sua tripulação que verificasse se havia tropas holandesas me seguindo.",
"Tarde demais para aprender. Agora, diga-me por que você traiu a mim e às autoridades espanholas em #sisland_Eleuthera#.",
"Seus superiores pensaram que, porque eu trabalhava para eles, poderia aceitar todas as suas decisões. Mas não sou espanhol, Chico. Sou holandês e depois do massacre de Oranjestad, sabia que deixaria esta vida de assassino.",
"Se você é holandês, sou espanhol e tenho uma missão a cumprir. Eu não vou desistir. Renda-se, Capitão!",
"Eu esperava evitar esta situação, mas parece que precisamos resolver nossa diferença com um duelo.",
"Vamos ver se o aluno supera o mestre.",
"En garde!",
"Por que você não me matou?",
"Porque ainda te respeito, Chico. Agora você é meu prisioneiro, mas vou deixar você voltar para Havana.",
"Estamos na Bahia de San Antonio, não estamos?",
"Sim, Chico. Agora você está livre, hoje estará em Havana",
"Não pensei que você seria tão generoso depois do que fiz. Não vou esquecer disso.",
"Espero que sim, porque não serei generoso na próxima vez que você me caçar.",
"Juro que recusarei qualquer missão cujo objetivo seja prender ou matar você.",
"É uma atitude corajosa porque você sabe que recusar uma missão pode significar sua demissão ou até mesmo a prisão.",
"Eu sei, mas você merece. Obrigado, capitão.",
"Boa sorte e adeus Chico!",
};
