string DLG_TEXT[23] = {
"......",
"......",
"Reconheço o Chico Cois mas quem é você?",
"Seu novo capitão. Acho que você sabe por que estamos aqui.",
"Sim. Siga-me, tenho algo para você.",
"Aqui está o relatório. Estava escondido na minha casa.",
"Obrigado. Vou entregá-lo ao vice-almirante. Adeus!",
"Espere! Eu tenho um problema. Não tenho certeza se posso continuar meu trabalho em #sisland_Cayman#.",
"Por que?",
"Acho que meu capitão suspeita que sou um espião, mas ainda não sabe para quem.",
"Como você sabe, ele já te questionou?",
"Não, mas ele tem me observado de perto recentemente e tenho sido seguido, mas não muito bem",
"Isso é realmente um problema...",
"Achei que deveria matá-lo, mas seria muito perigoso para mim.",
"Bem, eu poderia matá-lo, mas preciso encontrar esse cara sozinho e não entre seus soldados no forte",
"A situação não é perfeita, mas você pode matá-lo na cidade. No momento ele está no porto verificando o descarregamento das munições e depois precisa conversar com o governador",
"Eu poderia.. mas discretamente.",
"Você o conheceu?",
"Certo. Ele não vai mais te incomodar. Eu o matei.",
"Obrigado! Você acabou de me salvar.",
"*tom irônico* Sim, tenho o mesmo efeito que um padre, exceto que uso meios diferentes.",
"HA-HA! De fato.",
"No futuro, tenha mais cuidado ao espionar. Tenho que ir agora Dominico, até breve!",

};
