string DLG_TEXT[26] = {
"......",
"......",
"O meu capitão não vai gostar do que fizeste.",
"Onde está o seu capitão?",
"Por que você está tão interessado em vê-lo?",
"O seu capitão gosta de irritar as autoridades espanholas. Chegou a hora de pagar por isso.",
"Você está perdendo seu tempo. Você não é o primeiro a querer prendê-lo...",
"Eu acho que sim. É por isso que estou encarregado deste trabalho.",
"*Tom humorístico* Você quer dizer que os espanhóis enviaram seu melhor guerreiro para capturar meu capitão. Pelo menos você é modesto...",
"Não, pragmático. Então, onde ele está?",
"Eu não vou te contar.",
"Você não tem medo da morte?",
"Se você quer me matar, faça isso porque não vou contar nada.",
"Tudo bem. Se você não quiser me ajudar desta forma, você me ajudará de outra.",
"Havana... Qual é o meu destino? A forca?",
"Ainda não. Pelo menos até eu prender Bartolomeu.",
"Você?! Você também prendeu meu capitão? Um dia você vai pagar por isso!",
"Chuuuutttt... Fale baixinho. Vou tirar você desta prisão podre",
"O que você está falando?! Você está de brincadeira agora?",
"Não, decidi ficar do seu lado. Bartolomeu não está preso mas está aqui por te libertar.",
"Capitão?!, você aqui!",
"Olá, Emílio. Bom te ver. Pensei que você não estivesse nesta cidade. Não vi o navio Bartolomeu no porto.",
"Para evitar problemas com as autoridades espanholas, Bartolomeu atracou numa praia deserta perto da cidade. Caso contrário, o que você está fazendo aqui?",
"Não é por acaso que estou aqui. O capitão Morgan me enviou para saber por que Bartolomeu não volta para #sRedmond#.",
"Tivemos alguns incidentes inesperados. Mas você deveria falar com Bartolomeu. Ele está na taberna.",
"Tudo bem. Eu sigo você.",
};
