string DLG_TEXT[58] = {
".....",
".....",
"Não se mova, senhor!",
"Ele tentou roubar meus bens! Acabei de me defender.",
"Não estou aqui para determinar quem estava certo ou errado. Vejo que você matou um homem e há produtos contrabandeados na costa. Não preciso ser um gênio para saber que você é um contrabandista. Então, tenho provas suficientes para prender você e sua tripulação.",
"Você está feliz em sua cela?",
"*tom irônico* Claro, estou apodrecendo há três dias sem saber se passarei o resto da minha vida aqui.",
"Você vai me seguir. Alguém quer ver você.",
"Quem? e para onde você está me levando, tenho o direito de saber?",
"Você saberá tudo em breve",
"Você está na residência do vice-almirante. É uma honra conversar com ele, falar e agir com respeito ou então quebrarei suas pernas. Está claro!",
"[PENSA: Cara legal!] Perfeitamente.",
"O navio deles deve estar perto da aldeia.",
"Suponho que esteja atracado em Playa de Sabana, é a costa mais próxima.",
"Eu penso que sim. Vamos lá...",
"O navio deles parece sair da ilha.",
"Sim, eles não achavam que poderíamos ser tão rápidos no nosso contra-ataque",
"Voltemos a Havana e vejamos o vice-almirante Benavides. Ele enviará alguns galeões aqui para garantir que esta área seja segura",
"Ha! Capitão, acabei de dar as instruções ao chefe índio.",
"O que os índios farão?",
"Quando os soldados holandeses deixarem a cidade para nos combater, irão atacá-los pela retaguarda. Os holandeses cercados não terão chance de vencer a batalha.",
"E onde estão os civis?",
"Os civis? O que você quer dizer?",
"Há civis na cidade, não apenas soldados. Você os deixou sair da cidade antes de começar a batalha?",
"Você acha que tenho tempo para preocupações secundárias?",
"O que?! Você deixou os civis entrarem?! Mas eles serão massacrados pelos nossos canhões!",
"Essa é a guerra, capitão! Você não sabe o que é uma guerra?",
"Mesmo numa guerra, devemos respeitar algumas regras, Capitão Padilha!",
"Não me diga o que devo fazer. Eu sou o chefe desta missão! Fique aqui e não estrague a batalha.",
"[PENSA: Bastardo!]......",
"O que?",
"Seus soldados estão loucos?! Acabaram de matar um civil.",
"Você de novo com seus gemidos? Ele foi o último. Agora, a cidade está 'limpa'.",
"Estes são crimes de guerra! Informarei o vice-almirante Benavides sobre o seu comportamento.",
"Você acha que, por ser o mercenário mais valioso dele, ele ouvirá seus protestos",
"Tenho certeza de que ele não aceita crimes de guerra em seu exército.",
"Pense o que quiser, Capitão Elting. Sua presença é inútil em Aruba, você pode voltar para Cuba. Vou ficar aqui com minhas tropas nas próximas semanas. Devo reforçar a nossa posição para evitar um contra-ataque holandês.",
"Como quiser, já vi o suficiente.",
"Capitão Elting? O que você está fazendo aqui ? Você pode explicar quem são essas pessoas que te acompanham?",
"Deixe-me dizer: este é Bartolomeu o Portugues e a mulher é Roxanne Lalliere.",
"O que eles estão fazendo de graça na selva? Bartolomeu deveria estar preso como Roxanne!",
"Isso é vida. Houve uma pequena mudança no plano. Agora estou com eles.",
"Eu sabia que não poderíamos contar com a lealdade de um holandês. Todos traidores!",
"*tom irônico* Não seja tão desagradável. Suponho que você não nos deixará ir para a cidade de Alice.",
"*tom irônico* Devo te responder?",
"Eu não acho. Deixe que nossas armas façam isso.",
"Capitão Elting! O que diabos aconteceu no forte? O governador de Puerto la Cruz me disse que você estava aqui, mas não, também haveria um monte de soldados mortos.",
"Bartolomeu o Português é quem os matou. Quando cheguei ao forte, ele estava prestes a libertar Roxanne Lalliere.",
"É ele? este corpo?",
"Sim, acabei de matá-lo.",
"Bem, parece que você fez um ótimo trabalho, Capitão Elting. O vice-almirante Benavides saberá recompensá-lo.",
"O que fazemos agora?",
"Devemos deixar o forte agora. Não sabemos se mais piratas poderiam vir para libertar mais uma vez esta mulher pirata. Meus homens estão esperando lá fora, vamos voltar para Puerto la Cruz.",
"Acabei de informar ao Governador que saímos da ilha.",
"Vamos para Havana?",
"Sim, o capitão Lalliere já está a bordo como o cadáver do Bartolomeu. Vamos imediatamente!",
"Capitão Elting, acabei de ser informado que o vice-almirante Benavides está esperando por você na Câmara Municipal. Parece que ele tem boas notícias para você.",
"Eu vou lá, agora mesmo.",
};
