string DLG_TEXT[123] = {
"......",
"......",
"Quem é você? Você não vê que eu estava conversando com o Governador?",
"Desculpe. Você é o Capitão Morgan, não é?",
"Sim eu sou. O que você quer?",
"Sei que normalmente você prepara uma expedição de vez em quando e eu gostaria de participar.",
"Você é capitão ou marinheiro? Se você é marinheiro, fale com meu oficial, ele encontrará um posto para você.",
"Sou o capitão Johan Elting, não um marinheiro.",
"Elting? Os holandeses que trabalharam para os espanhóis?",
"Sim. Como você sabe?",
"O capitão Bartolomeu falou de você há pouco.",
"Bartolomeu? Ele está em #sRedmond#?",
"Não, ele está em uma missão por mim. Mas, siga-me até a taverna, tenho algumas perguntas para você.",
"Claro, capitão.",
"A vida às vezes é estranha, não é?",
"Por que você diz isso?",
"Se eu tivesse te conhecido há alguns meses, teria que te matar... E agora, você quer trabalhar para mim.",
"De fato. Mas nunca pensei que pudesse trabalhar para as autoridades espanholas. A vida é cheia de surpresas.",
"Bartolomeu disse que você matou o vice-almirante Benavides. É verdade?",
"Sim. Ele mereceu.",
"Não direi o contrário. Os Irmãos da Costa agradecem por terem feito isso. Ele era uma ameaça para nós.",
"Isso significa que você me deixou trabalhar para você?",
"Claro. Bartolomeu afirmou que você é um excelente Capitão e preciso deles para minhas próximas expedições.",
"Aliás, na prefeitura você disse que Bartolomeu estava em missão por você. Onde ele está?",
"Longe daqui, em Vera Cruz.",
"Na Nova Espanha? Por que?",
"Há alguns rumores de que os espanhóis encontraram um tesouro asteca há alguns meses.",
"Como eles descobriram isso?",
"Não sabemos exatamente. Suponho que estava escondido em um templo porque o encontraram em algum lugar da selva.",
"Já encontrei um templo em #sisland_Khael Roa#.",
"Não estou surpreso. Existem muitos templos nesta parte do mundo. No entanto, cada templo não possui um tesouro. Este deve ter pertencido a um rei.",
"Se você estiver certo, deve ser valioso.",
"Eu penso que sim. Por isso mandei o Bartolomeu para Vera Cruz. Ele deve confirmar que os espanhóis transportaram o tesouro para lá.",
"Por que aquela cidade?",
"O tesouro será enviado para Espanha graças à Frota de Prata.",
"Humm... E como todos sabem, a frota vai para Vera Cruz todos os anos.",
"Certo. É também o porto de escala mais próximo onde o tesouro foi encontrado.",
"Então, você está aguardando a confirmação do Bartolomeu antes de ir para lá?",
"Sim. Estou preparando uma expedição para atacar Vera Cruz. Mas precisamos atacar a cidade antes que a Frota de Prata chegue. Caso contrário, não teremos forças suficientes para combater os espanhóis.",
"Eu entendo.",
"No entanto, há um problema...",
"O que?",
"Pelos meus planos, Bartolomeu deveria ter voltado por um mês. Esse atraso é preocupante.",
"O que você pensa em fazer?",
"Pensei em mandar alguém a Vera Cruz para saber se Bartolomeu está com problemas.",
"Você quer que eu vá lá?",
"Você pode? Vendo que você o conhece, você é o homem certo para esta missão.",
"Se você quiser, posso ir agora mesmo.",
"Excelente! Lembre-se, capitão! Seja qual for a situação em Vera Cruz, quero você de volta o mais rápido possível. Não quero que o tesouro saia do Caribe.",
"Lembrarei. Vou preparar minha partida hoje. Até mais, capitão!",
"Vocês estão de volta, Elting e Bartolomeu! Quais são as novidades?",
"Não atacaremos Vera Cruz, Capitão.",
"O que? Não me diga que o tesouro desapareceu ou saiu do Caribe.",
"Não, ainda está no Caribe, mas em Cuba.",
"O que está fazendo aí?",
"A Frota de Prata deixou Vera Cruz mais cedo do que o esperado.",
"Senhores, devemos ir rapidamente para Havana. Não sabemos quanto tempo durará sua estadia. Pode ser o nosso último golpe de sorte para roubar o tesouro. Preparem seus navios, nós levantamos âncora!",
"Sim capitão.",
"Tudo bem, a frota ainda está em Havana. Mas devemos saber se o tesouro está nos navios ou em terra e quanto tempo a frota ficará, esperando que tenhamos tempo suficiente para o roubo. Vocês dois podem obter essas informações?",
"Eu penso que sim. Com o capitão Bartolomeu encontraremos um estratagema.",
"Seja rápido! Não podemos deixar nossos navios perto de Havana indefinidamente. Isso seria muito perigoso.",
"Entendido.",
"O que um padre está fazendo no meu navio?",
"Ele não é padre. Vestimos-lhe um roupão só para sair de Havana. Na verdade, ele é o capitão da Frota de Prata. Só encontramos esta solução para saber onde está o tesouro.",
"Você o questionou?",
"Ainda não. Preferimos que você faça isso.",
"Farei isso, mas a ausência dele em Havana alarmará as autoridades. Não teremos muito tempo para obter as informações.",
"Feito! Ele entendeu que eu não estava com vontade de brincar e disse onde estava o tesouro.",
"Nos navios?",
"Não, está no forte El Morro.",
"Não é melhor que os navios.",
"Pior, eu diria. Essa é a razão pela qual eles deixaram lá durante a estadia.",
"Você quer dizer que devemos desistir?",
"Não, eu não. Vamos atacar o forte.",
"Tem certeza que conseguiremos? Você acabou de insinuar que o forte é um grande desafio.",
"Sim, mas isso não é impossível. Com um bom plano, podemos fazer isso. O único problema é prepará-lo o mais rápido possível. Amanhã à noite, devemos agir. Descanse até amanhã ao meio-dia, te ligo para explicar o plano.",
"Senhores, tenho um trabalho para vocês!",
"O plano está pronto?",
"Sim, atacaremos o forte pelos dois lados. Comandarei as tropas em frente à entrada principal. Meu objetivo será atrair a atenção dos guardas. Entretanto, você e Bartolomeu com alguns dos seus tripulantes irão penetrar no forte pelo lado oposto para combatê-los nas costas.",
"*Tom de espanto* Capitão, há um penhasco daquele lado.",
"Eu sei. Você se aproximará do penhasco com um pequeno navio para não ser detectado pelos guardas. Chegando ao fundo da falésia, você subirá graças aos arpéus. Os guardas não vão esperar que o inimigo venha daquele lado.",
"Eu os entendo.",
"Claro, é perigoso, mas não tenho outro plano. Se quisermos vencer a batalha, devemos surpreendê-los. Caso contrário, não teremos chance.",
"Tudo bem, faremos o melhor que pudermos.",
"Obrigado, eu sabia que posso contar com você. Tenha certeza, teremos sucesso.",
"Elting?! Foi você quem destruiu os canhões?",
"Sim capitão. Bartolomeu me contou que você foi parado pelos canhões. Mas, sem tempo para conversa, os espanhóis devem preparar uma surtida. Você deveria atacar o forte!",
"Estou indo agora mesmo para a entrada principal. Enquanto isso, junte-se a Bartolomeu.",
"Muito bem, Elting! Agora que este andar está 'limpo' podemos ir para o armazém.",
"Olhar! O trono asteca está aqui.",
"Este trono deve valer uma fortuna.",
"De fato. E ainda não vimos o que as caixas contêm.",
"Vamos levar rapidamente o tesouro para a praia. Os soldados de Havana devem ser avisados do nosso ataque.",
"Tudo bem, quase terminamos o carregamento. Depois de embarcar em nossos navios, iremos para #sRedmond#.",
"Consegui vender a maior parte do saque, mas há um problema...",
"O que você quer dizer?",
"O trono asteca é valioso demais para ser vendido no Caribe. O lojista de #sRedmond# era nossa única possibilidade, mas ele não tem dinheiro suficiente para isso.",
"O que vamos fazer agora?",
"Na minha opinião, deve ser vendido a um joalheiro rico de Londres. Somente essas pessoas poderiam nos pagar o preço certo.",
"Então, deveríamos ir para a Inglaterra?",
"Desnecessário. O Governador poderia enviá-lo para Inglaterra num dos seus navios de guerra. Receberemos o dinheiro quando o navio de guerra voltar.",
"Claro, teremos que pagar ao Governador pelo 'serviço'...",
"De fato. Ainda preciso falar com ele, mas aposto um quarto da venda.",
"hum...",
"Acho que é a melhor solução. O trono estará mais seguro num navio de guerra britânico e não precisamos de perder tempo indo para Inglaterra. Você concorda?",
"Concordo. O que pensa Bartolomeu?",
"Eu vou falar com ele. Se ele concordar, falarei com o Governador.",
"Boas notícias! O governador tem um de seus navios de guerra que deve ir para a Inglaterra no próximo mês.",
"E o preço do serviço?",
"No início, ele queria um terço da venda, mas eu o convenci a reduzir sua parte para um quarto.",
"Como você pensou.",
"Sim. Agora, devemos esperar seis meses ou mais para receber o dinheiro. Até lá, podemos desperdiçar o dinheiro dado pelo lojista.",
"Quanto?",
"450.000 moedas de ouro. Então, 150 mil para cada um. Pegue seu dinheiro!",
"Nada mal.",
"E é só o começo porque o trono vale mais do que esse valor. Espero 250.000 para cada um quando vendido.",
"Deus! Isso é uma grande soma!",
"Sim capitão. Mas há muito que esperar até recebermos o dinheiro.",
"Enquanto isso, o que você fará?",
"Vou descansar em #sRedmond# nas próximas semanas. Depois, não sei... não tenho novas expedições agendadas.",
"Nesse caso, vejo você daqui a meio ano para compartilhar o saque.",
"Obrigado por tudo capitão. Boa sorte!",
"Adeus!",
};
