string DLG_TEXT[24] = {
"......",
"......",
"Quem é você e como encontrou minha aldeia?",
"O chefe Arawak me disse para ver você. Ele disse que você poderia me ajudar",
"Ajuda? Que tipo de ajuda?",
"Quero a sua ajuda para lutar contra os holandeses da ilha. Pagarei bem por este trabalho.",
"Ouro?",
"Sim, tenho ouro para sua tribo. Muito ouro...",
"Interessante... Poderíamos ajudá-lo, mas não somos numerosos o suficiente para atacar os holandeses.",
"Não se preocupe, irei com um exército. Eu só preciso de uma força adicional para não dar chance às tropas holandesas.",
"Tudo bem. Pague-nos agora e nós o ajudaremos. Queremos 100.000 moedas de ouro.",
"O que? Isso é demais.",
"Não morreremos por nada, homem branco.",
"50.000 moedas de ouro são suficientes.",
"Não, são 100.000 ou saia da nossa aldeia.",
"Bem, eu tenho 50.000 moedas de ouro comigo. Eu te dou esse dinheiro e pagarei o resto depois da batalha.",
"Tudo bem. Quando seu exército estará aqui?",
"Nas próximas semanas. Vejo você pouco antes do cerco de Oranjestad. Vê você!",
"Você voltou. Isso significa que a batalha começará em breve?",
"Sim, os soldados estão cercando Oranjestad.",
"E meu dinheiro?",
"Eu trouxe o ouro.",
"Tudo bem. O que você quer que façamos?",
"O capitão Padilla, chefe da expedição, lhe dará as ordens. Reúna seus guerreiros, vamos para Oranjestad.",
};
