string DLG_TEXT[30] = {
"......",
"......",
"Quem é você?",
"Você é Pelágio?",
"Humm... não entendo o que você pergunta.",
"E se eu falar do Vice-Almirante, você entende melhor agora?",
"Você trabalha para Benavides?",
"Certo. Vim te levar de volta para #sHavana#. Mas talvez você queira apodrecer neste esgoto com os ladrões.",
"Nunca! Eles me sequestraram para me venderem como escravo em outra ilha.",
"Agora você está sob minha proteção, siga-me!",
"Capitão Elting!",
"Que bom ver você de novo.",
"Você deve estar aqui por causa dos canhões de #sisland_Isla Mona#.",
"Sim. O vice-almirante parece estar preocupado com eles.",
"Não só ele, mas todas as autoridades espanholas.",
"Preciso ser contratado pelo Almirante de Antígua. Você tem algumas dicas antes de eu conhecê-lo?",
"Ele não gosta de contratar corsários e não contratará você de jeito nenhum, a menos que você tenha uma Carta de Marca da Inglaterra. Então, se você ainda não tem essa Carta, adquira uma o mais rápido possível. Então você deve insistir se ele recusar no início.",
"Tudo bem. Você acha que em breve terei uma missão para #sisland_Isla Mona#?",
"Apenas uma missão de escolta, eu acho. A guarnição inglesa de #sisland_Isla Mona# deve receber novos suprimentos a cada seis meses. Portanto, o almirante envia um navio mercante com escolta.",
"Quando ele enviou o último navio mercante?",
"Quatro meses atrás.",
"Então, preciso trabalhar para ele pelos próximos dois meses, pelo menos.",
"Não se preocupe. Quando ele preparar uma nova missão para #sisland_Isla Mona# eu lhe direi para que você possa sugerir sua ajuda.",
"Obrigado. Bem, preciso falar com ele. Vejo você em breve.",
"Capitão! Espere um minuto.",
"O que acontece, Pelágio?",
"O Portadmiral está prestes a enviar um navio para #sisland_Isla Mona#.",
"Finalmente, tive a oportunidade de ir para lá.",
"Sim. Não perca esta oportunidade. Como já lhe disse, apenas uma vez por semestre um navio vai para lá.",
"Obrigado. Volte ao seu post, vou tratar do assunto.",
};
