string DLG_TEXT[108] = {
"Bem-vindo à minha taverna, estranho. Meu nome é ",
". O que o traz ao meu humilde estabelecimento? Você precisa de um lugar para descansar?",
"Obrigado. Meu nome é ",
". Eu estou aqui a negócios.",
"Meu nome é ",
", e você pode poupar sua hospitalidade. Eu estou aqui a negócios.",
"Bem vindo senhor! O que você quer?",
"Preciso de algumas informações e acho que o estalajadeiro local geralmente é a pessoa certa para perguntar.",
"Estou procurando contratar alguns marinheiros para meu navio.",
"Aponte-me os clientes aqui que podem estar procurando emprego. Preciso aumentar minha equipe e não me importo se eles forem assassinos.",
"Você tem um quarto? Eu gostaria de ficar aqui por um tempo",
"Você tem uma cama grátis neste casebre?",
"Não tenho nenhum negócio com você agora. Adeus.",
"Isso é verdade. Eu ouço quase tudo. O que você quer saber?",
"Dizem que existe um forte pirata em algum lugar da selva. Preciso saber o caminho até lá.",
"Estou me perguntando se o navio chamado '",
"armazenamento de navios",
"' esteve no porto.",
"Estou procurando um homem chamado ",
"Raoul Rheims",
"Raoul Rheims",
". Você sabe se ele esteve na ilha?",
"Disseram-me que piratas apareceram na ilha. Isso é verdade?",
"Procuro um homem chamado Rheims. Você o viu?",
"O que - meu ouro não te trouxe sorte?",
"Eu preciso de um emprego. Você não conhece nenhum garoto rico nesta ilha que tenha medo de viajar sozinho?",
"Não tenho perguntas no momento. Vamos falar sobre outra coisa.",
"Talvez eles tenham. Existem muitos rumores por aí.",
"Tenho a sensação de que você sabe mais do que apenas rumores. Como a localização do esconderijo dos piratas!",
"Sinto muito, você tem alguma dúvida? Minha audição não é tão boa.\nMas 3.000 moedas de ouro podem curar isso.",
"Aqui está a sua cura - exatamente 3.000.",
"Não é muito dinheiro por um pouco de informação?",
"Bom Bom. Você queria encontrar o esconderijo do pirata? Está nas profundezas da selva, bem escondido de olhares indiscretos. ",
"Eu já sabia disso. É melhor você continuar falando",
"E eu peço que você continue ouvindo, meu amigo. A estrada que sai do portão da cidade leva direto para a selva. Em breve você verá um caminho que leva à esquerda. Não aceite isso - vá direto. Na próxima bifurcação, vire à direita.\nNa terceira, vire à esquerda e logo você estará onde precisa estar.",
"Obrigado. Não foi muito trabalho para tanto dinheiro, foi?",
"Bem, isso é com você. Mas duvido que você encontre isso sozinho.",
"Tudo bem, eu pago. Falar.",
"Veremos.",
"Ah, me desculpe ",
"! Por favor me perdoe. Não sabia que você estava... aqui, vou devolver tudo. Vou até te pagar mais!",
"Bem, obrigado.",
"Você está com sorte, meu amigo. É ele perto da mesa perto da janela.",
"Obrigado!",
"Ele ligou aqui várias vezes, mas isso foi há muito tempo. Só me lembro dele porque me pagou com moedas indianas feitas de ouro puro.",
"Bem, obrigado de qualquer maneira. Algumas informações são melhores do que nenhuma. Deixe-me perguntar outra coisa.",
"Desculpe. Eu não sei nada sobre isso.",
"Isso é ruim. E não tenho dinheiro para alugar um navio...",
"Então você precisa de um emprego, não é? Para falar a verdade, você não encontrará muita coisa aqui. Mas dizem que há piratas em algum lugar da nossa ilha que aceitam qualquer pessoa em suas fileiras.",
"Suponho que não tenho outra escolha senão trabalhar para eles.",
"Importa-se se eu perguntar por que você quer ir para lá?",
"Eu preciso conversar com ",
"Alistair Garcilaso",
"Alistair Garcilaso",
". Eu gostaria de comprar algo dele.",
"Pelo que entendi, você está falando sobre...",
"Verificando minha história, não é? Ok, vou jogar seu jogo. Estou falando de algumas bugigangas indianas.",
"Não leve isso para o lado pessoal. Tenho que verificar todos nestes tempos difíceis. Espere por mim aqui e verei o que posso fazer por você.",
"Eu não vou a lugar nenhum tão cedo",
"Pressa. Sou um homem ocupado.",
"É um pouco tarde para encontrar bons marinheiros. Eles já estarão todos dormindo ou desmaiados. Volte de manhã - ou você pode passar a noite aqui na taverna.",
"Tudo bem. Você tem um quarto?",
"Não preciso de um quarto no momento. Vamos falar sobre outra coisa.",
"Eu tenho uma vaga. Quanto tempo você vai ficar?",
"Durante a noite.",
"Só até escurecer.",
"Multar. Serão 5 peças de ouro.",
"Tudo bem. Aqui você vai.",
"Infelizmente, acho que não posso pagar nada melhor do que uma noite no salão da taverna.",
"O que isso vem com uma equipe pessoal? Eu vou passar.",
"Vou pensar sobre isso.",
"Multar. Serão 5 peças de ouro.",
"Tudo bem. Aqui você vai.",
"Infelizmente, acho que não posso pagar nada melhor do que uma noite no salão da taverna.",
"Isso é demais. Eu vou ficar no salão da taverna",
"Vou pensar sobre isso.",
"Caros visitantes! Por favor, pare com essa indignação! Não me obrigue a chamar os guardas!",
"Tudo bem, tudo bem! Eu já fui!",
"Se for, eles preferem navegar com menos satélites, você sabe disso",
"Sim, esqueci. Tudo bem, voltarei mais tarde, quando tiver menos navios, ha-ha.",
"Eu não quero ajudar você. Você causou muitos problemas ao meu país",
"Basta olhar para este patriota. Bem adeus.",
"Suas mãos estão cobertas de sangue. Você não acha seriamente que alguém viajaria com você, não é?",
"Você está certo, todo mundo tem medo de mim! Ha-ha!",
"Você chegou bem na hora. Um comerciante aqui estava procurando a companhia certa para viajar. Você deveria falar com ele. Lá está ele, acabando de entrar na taverna.",
"Eu farei isso.",
"Não, não há ninguém assim no momento, Talvez da próxima vez.",
"Hmm, então vou esperar.",
"Deveria haver um capitão mercante aqui que encontrou uma fragata misteriosa.",
"Ah, esse é Drabbe. Você o encontrará roncando na mesa perto da janela.",
"Obrigado.",
"Quero saber se o pirata Roche Brasiliano está em #sisland_Curacao#?",
"Fique quieto, a maioria das pessoas evita falar dele, senhor. Acho que você quer esquecer que já ouviu falar desse homem?",
"Parece que um pirata deixou todo mundo assustado, como isso pôde acontecer aqui?",
"Se Gherarde de Jongh ainda estivesse vivo, ele não deixaria esse pirata viver na ilha?",
"Quem é Gherarde de Jongh?",
"Ele foi o ex-diretor da Companhia Holandesa das Índias Ocidentais. Foi morto por Bartolomeu o Português há alguns meses.",
"Aquele famoso pirata português o matou?",
"Sim, eles atacaram o navio dele não muito longe desta ilha.",
"Eu não sabia. De qualquer forma, você tem um Governador que deveria proteger a colônia contra os piratas.",
"Você não o conhece se disser isso. Ele não fará nada contra a Roche. Muito perigoso para ele. Ele prefere 'fechar os olhos'.",
"Você está me dizendo que Roche tem controle total da cidade?",
"Não neste momento. Ele não tem permissão para atracar no porto, mas o deixa morar em uma vila próxima à cidade.",
"Há quanto tempo Roche mora na ilha?",
"por dois meses...",
"Interessante. Tenho informações suficientes sobre a Roche Brasiliano para meu propósito, obrigado.",
"Não conte a ninguém que lhe dei essa informação.",
"Não se preocupe, será nosso segredo. Obrigado por ajudar.",
};
