stringDLG_TEXT[18] = {
"......",
"......",
"O que você quer?",
"Renouart Baumont?",
"Certo. Quem é você?",
"Sou o capitão Elting. Eu sei que você trabalhou na Roche Brasiliano.",
"Como você disse, eu 'trabalhei' para os porcos, Roche. Agora, se você é amigo dele, me despeço de você.",
"Espere, você entendeu tudo errado, não sou amigo dele, estou rastreando-o para as autoridades, preciso saber onde posso encontrá-lo.",
"OK, mas não tenho ideia, capitão. Ele se move regularmente entre #sTortuga#, #sRedmond#, #sisland_Cayman# ou muitos outros lugares. A única coisa que tenho certeza é que ele não está em #sisland_Guadalupe#.",
"Talvez haja um lugar que ele visita com mais frequência do que os outros?",
"Você poderia tentar #sCharlestown#.",
"Porque lá?",
"Digamos que ele tivesse um gosto especial por uma mulher que trabalhava no bordel. Ela pode ser capaz de ajudá-lo.",
"Entendo, um bom ponto de partida. Você se lembra do nome dela?",
"O nome dela é Lady Gaga. De qualquer forma, não sei se ela ainda mora lá, mas vale a pena tentar.",
"Obrigado, vou verificar isso.",
"Espero que esta seja a última vez que ouço o nome dele e que ele entenda o que merece.",
"Se eu o encontrar, tenho certeza de que a única coisa que você ouvirá é como ele morreu. Obrigado e adeus!",
};
