string DLG_TEXT[128] = { 
"Disseram-me que você fez um grande esforço para solicitar uma audiência. Meu nome é ",
". Agora, por favor, diga-me o propósito da sua visita ",
".",
"Meu nome é ",
".",
"Ah, é você de novo. O que traz você aqui desta vez? ",
"Eu gostaria de conversar com você sobre alguns negócios.",
"Sinto muito, mas há coisas que preciso fazer.",
"Então, por que você me distrai dos assuntos de estado muito importantes?",
"Gostaria de falar com você sobre um pequeno negócio.",
"Estou aqui apenas para prestar meus respeitos, #saddr#. Nada mais.",
"Nesse caso, por favor, saia do meu escritório e deixe-me voltar para assuntos mais importantes.",
"Sim claro. Desculpe por ter incomodado você.",
"Sinto muito, mas não tenho nada para conversar agora",
"Oh sim? Tenho uma proposta para você, capitão.",
"De fato?",
"Aprendi que você concluiu a tarefa com sucesso; meus parabéns, capitão! Aqui está sua recompensa.",
"Meus agradecimentos; Foi um prazer ajudá-lo.",
"Você deve destruir o ",
" navio ",
"missão pirata",
" ameaçando o envio ",
". Se você afundá-la, vou recompensá-lo com uma boa quantia de ",
" ouro. O que você diz, capitão?",
"Você não ouvirá falar dela novamente, isso eu prometo.",
"Receio não poder ajudá-lo.",
"Anseio por perdão, Excelência.",
"Estou interessado em aprender sobre as relações de #sgov_nation# com outras nações.",
"Estou procurando uma Carta de Marca.",
"Ouvi dizer que estou pronto para uma promoção.",
"Não posso mais servir ",
", vossa Excelência.",
"Cansei de servir ",
"Como garantia de que você é um capitão competente e para recompensar meu tempo apresentando seu caso a ",
", devo te pedir ",
" ouro.",
"Sem chance.",
"Muito bem.",
"#sgov_nation# tem sempre o prazer de aceitar novos capitães ao seu serviço. ",
"Estamos atualmente em guerra com ",
"",
"nenhum grande poder, mas ",
". Claro, ",
"Os piratas devem sempre ser afundados à primeira vista.",
" À luz do seu serviço anterior, ",
" concede a você a classificação de ",
"Vou deixá-lo orgulhoso, Excelência.",
"Você prejudicou ",
", e ",
" não esquece seus inimigos. Saia imediatamente, ou os guardas vão te jogar fora!",
"...",
"Você causou ",
" grande dano, capitão, mas ",
" está disposto a ignorar suas transgressões passadas... por um preço: ",
"Muito bem, senhor. Aceito.",
"É um prazer lidar com você, ",
"E você, Excelência.",
"Você é realmente! Excelente trabalho. Sua nova classificação é ",
". Além disso, você é premiado ",
" hectares de terra por ordem de ",
"Obrigado, senhor.",
"Tem certeza, ",
" lamentaremos perder seu serviço.",
"Sim eu sou.",
" não gosta de vira-casacas ",
"Uh, não importa.",
"Muito bem. Mas espero que você reconsidere, com o tempo...",
"Adeus, ",
"Huh?",
"Difícil.",
"Quais são suas ordens, #saddr#?",
"Devo administrar esta colônia.",
"Você sabe sobre algumas hostilidades em águas próximas, #saddr#?",
"Há coisas que tenho que fazer.",
"Capitão Elting, espero que tenha uma boa explicação para o que fez contra os holandeses recentemente. Por que você trabalhou para os espanhóis? Nosso inimigo mais perigoso!",
"Fui forçado a trabalhar para eles, Excelência. Caso contrário, eles teriam me enforcado.",
"É um pouco fácil como desculpa. Pelo que sei, você trabalhou para eles durante muito tempo. Tente outra coisa!",
"Você está certo, Governador. Eu poderia ter desertado antes. Pensei nisso nesses últimos dias. Suponho que a vida de mercenário foi mais emocionante do que a anterior... Pelo menos, até o cerco de Oranjestad.",
"Na verdade, Oranjestad! Como você poderia lutar contra seus próprios compatriotas? Você ainda é holandês?",
"Achei que a guarnição teria se rendido antes da luta...",
"Os espanhóis não tiveram piedade. Eles mataram todo mundo!",
"Protestei contra a morte dos civis.",
"Isso não evitou suas mortes.",
"Eu sei, Excelência. Mas, eu os vinguei...",
"O que você quer dizer?",
"Matei os líderes desta operação, o capitão Padilla e seu superior: o vice-almirante Benavides.",
"Eu não sabia. Humm... Por que você veio aqui? Pedindo perdão?",
"Sim, governador. Quero começar uma nova vida e esquecer para sempre meu passado espanhol.",
"Você está me perguntando muito, capitão. A sua participação no cerco de Oranjestad é demasiado séria. No entanto, se eu tiver a confirmação de que você realmente matou os líderes daquela operação, poderia reconsiderar minha opinião sobre você. Enquanto isso, você ficará na prisão.",
"Na cadeia?",
"Sim capitão. Não confio em você neste momento. Guardas! leve-o para a prisão!",
"....",
"Você tem sorte, capitão! Um informante de Havana chegou mais cedo do que o esperado trazendo notícias daquela cidade espanhola. Ele confirmou que você realmente matou o Capitão Padilla e o Vice-Almirante Benavides. Parece que você deixou o serviço espanhol.",
"Claro. Eu disse a verdade em nossa última conversa.",
"Tomei minha decisão: agora você é um homem livre. Você pode morar na minha cidade se quiser.",
"Obrigado, Governador. Eu sabia que você era justo.",
"O que você pensa em fazer agora?",
"Quero continuar lutando contra os espanhóis. Mas preciso de um navio de verdade... Não de um barco para isso.",
"O que você quer dizer, capitão?",
"Aposto que aquele navio é 'El Diablo'?",
"'El Diablo'?",
"Sim, meu antigo navio quando trabalhava para os espanhóis. Eles são os únicos que constroem esse tipo de Xebec.",
"Talvez eles tenham vindo para espionar. #sisland_Douwesen# pode ser o próximo alvo depois de Oranjestad...",
"Sim... Ou estão me procurando para me matar depois do que fiz em Havana.",
"Essa poderia ser uma possibilidade. Precisamos saber suas intenções antes de qualquer operação militar.",
"Quaisquer que sejam suas intenções, eles enviarão primeiro um espião à cidade para obter as informações desejadas.",
"Eu penso que sim. Eu deveria deixar meus soldados encontrarem e prenderem aquele espião quando ele estiver na cidade. Poderíamos questioná-lo.",
"Se você fizer isso, eles poderão ser avisados e deixar a ilha antes de capturar seu navio... E eu gostaria de recuperar meu antigo navio.",
"O que você sugere como alternativa?",
"Deixe um de seus homens encontrar e contatar o espião nesta cidade. Caso ele esteja me procurando, ele deve dizer que estou aqui e trabalho para você como capitão do exército holandês e amanhã patrulharei a selva com alguns soldados.",
"Sua ideia é emboscá-los?",
"De fato. Depois, capturar o navio será uma formalidade.",
"Tudo bem, fique no forte até darmos a informação errada ao espião. Eu irei informá-lo quando terminar.",
"Capitão! Meu agente já passou informações erradas ao espião deles ontem.",
"O espião estava procurando por mim?",
"Na verdade, chegou a hora de me juntar aos meus soldados. O inimigo deve estar em Crab Cliffs esperando por você.",
"Então a luta vai acontecer lá... Quantos homens vão me acompanhar?",
"Com você apenas alguns, eles estão do lado de fora. Mas muitos mais irão segui-lo. Quando os espanhóis atacarem você, meus soldados lutarão contra eles pelas costas.",
"Bom, vou encontrá-los agora mesmo.",
"Parabéns! O capitão de Voor disse que você capturou seu antigo navio.",
"Sim, governador. Depois da luta em Crab Cliffs, só tive que matar o capitão a bordo do navio.",
"Quem era esse capitão?",
"[PENSA: Vamos mentir!] Eu não o conhecia. Certamente um novo mercenário contratado pelo Governador de Havana.",
"Eu entendo. Bom, acho que agora você recuperou o navio que quer sair da ilha e caçar os espanhóis.",
"De fato. Vou levantar âncora hoje.",
"Como quiser, capitão. Desejo-lhe boa sorte nas suas próximas expedições.",
"Obrigado. Adeus Governador!",
"Como quiser, capitão. E agora que sei que posso confiar em você, deixe-me entregar esta Carta de Marca para legalizar suas ações em meu nome. Desejo-lhe boa sorte nas suas próximas expedições.",
};
