string DLG_TEXT[20] = {
"......",
"......",
"O que?",
"Olá, boneco!",
"Você é um mercenário, não é? Você fala espanhol com sotaque estrangeiro.",
"Sou holandês, capitão Lalliere.",
"Devo confessar que você parece ter preparado um plano detalhado para me capturar.",
"Finalmente, encontro um adversário que admite minhas habilidades.",
"Não pensei que fosse uma ameaça importante para os espanhóis.",
"É claro que a sua expedição a Santiago não foi apreciada pelas autoridades espanholas. Mesmo que esse não tenha sido o principal motivo da sua prisão.",
"O que você quer dizer?",
"Você conhecerá melhor Havana quando vir Emilio Soares.",
"Emílio? O oficial de Bartolomeu?!",
"Certo. Bem, tenho mais o que fazer, então aproveite sua estadia nesta prisão.",
"Você demorou muito. Eu estava ficando preocupado.",
"Fizemos isso o mais rápido possível. Agora, temos que sair de Cuba. Havana deve ser cercada por soldados depois do que fizemos lá.",
"O que você fez, assassino! Você matou meu melhor amigo",
"Eu fiz o que eu tinha que fazer. A vida de pirata não é solução para mim... E para você porque seu fim chegará em breve.",
"Maldito seja o dia, sua mãe te deu à luz!",
"(Você ouve a porta da prisão abrindo) Cale a boca! Alguém está vindo. Espero que não seja outro amigo seu.",
};
