string DLG_TEXT[18] = {
"......",
"......",
"O que?",
"William Cotter?",
"Sim o que você quer?",
"O governador de Puerto la Cruz disse para vê-lo.",
"Eu sabia que você viria. Quem é a pessoa que você quer sequestrar?",
"Uma corsária francesa chamada Roxanne Lalliere. Você a viu?",
"Humm... A única capitã que vi chegando nesses últimos dias é uma comerciante holandesa.",
"Ela deve ser ela. Vendo as relações entre Inglaterra e França, ela usa a bandeira holandesa como cobertura. Onde ela está?",
"Ela está na taverna com seu oficial",
"À noite ela dorme na taberna?",
"Não, ela geralmente retorna para seu navio.",
"Tudo bem, teremos a oportunidade de fazer uma emboscada quando ela voltar ao navio. O único problema são os guardas que patrulham a cidade...",
"Não se preocupe, posso atraí-los temporariamente para fora da cidade durante sua operação.",
"Como?",
"Direi a eles que vi uma patrulha espanhola na selva perto dos portões e os levarei até lá.",
"Bom. Só preciso esperar que ela saia da taverna esta noite.",
};
