string DLG_TEXT[101] = {
"Bom dia, jovem. E quem você é, e de qual navio você é?",
"Bom dia para o senhor. Eu sou ",
"aspirante ",
"Tenente ",
"Capitão ",
", do navio do rei ",
".",
"Um belo navio ",
". Eu não sabia que ela estava nessas águas. O que você vai exigir desta visita?",
"",
"Nada hoje, senhor. Eu estava sentindo a ilha e onde ficam os lugares.",
"Preciso de alguns suprimentos, por favor, senhor.",
"Muito bem. Você estaria querendo provisões de navio ou equipamentos pessoais? .",
"Lojas do navio, por favor. Estamos prestes a partir em uma longa patrulha.",
"Itens pessoais, por favor. Eu quero algo melhor do que o equipamento padrão.",
"[15].",
"[16]",
"[17]",
"[18].",
"[19]",
"[20]",
"[21]",
"[22]",
"DLG_TEXT[23]",
"DLG_TEXT[24]",
"DLG_TEXT[25]",
"DLG_TEXT[26]",
"DLG_TEXT[27]",
"DLG_TEXT[28]",
"DLG_TEXT[29]",
"DLG_TEXT[30]",
"DLG_TEXT[31]",
"DLG_TEXT[32]",
"DLG_TEXT[33]",
"DLG_TEXT[34]",
"DLG_TEXT[35]",
"DLG_TEXT[36]",
"DLG_TEXT[37]",
"Gostaria de ver o que tenho em estoque?",
"Claro. Vamos dar uma olhada.",
"Mais tarde. Agora preciso conversar.",
"Em alguma outra hora.",
"Vamos fazer um acordo ou você só quer comprar alguns suprimentos?",
"Eu quero vender alguns produtos.",
"Eu gostaria de comprar alguns equipamentos.",
"Nada, obrigado. Tchau!",
"Sobre o que você quer falar?",
"Estou ouvindo.",
"Pediram-me para entregar uma carga para você.",
"Você precisa de um capitão, senhor? Tenho um navio excelente e posso entregar qualquer carga, onde você quiser.",
"Não tenho tempo para conversar agora",
"Não, não preciso dos seus serviços. Não enquanto você estiver afundando navios ingleses.",
"Nesse caso, adeus.",
"Sinto muito, mas não tenho nada para você no momento.",
"Voltarei mais tarde, então.",
"Sinto muito, mas seu navio não é grande o suficiente para que você possa fazer o trabalho que tenho em mente.",
"Voltarei mais tarde, então.",
"Oh! Eu só ia pedir que você me fizesse um favor. O problema é que preciso que alguma carga seja entregue em ",
", e o mais rápido possível. Se você conseguir fazer isso dentro de um mês, receberá ",
" ouro quando você chegar. Isso parece justo?",
"Eu definitivamente gosto disso.",
"Eu não posso aceitar isso.",
"Já te disse hoje que não tenho nada para você.",
"Oh, desculpe.",
"Você se lembrou da sua tarefa um pouco tarde demais, não acha? Vou levar a mercadoria de qualquer maneira, mas não espere ser pago. Preste mais atenção na próxima vez! Adeus.",
"Até a próxima.",
"Oh! Estou esperando por isso há muito tempo. Aqui está a sua recompensa, jovem.",
"Sempre bem-vindo.",
"DLG_TEXT[68]",
"DLG_TEXT[69]",
"DLG_TEXT[70]",
"DLG_TEXT[71]",
"DLG_TEXT[72]",
"DLG_TEXT[73]",
"DLG_TEXT[74]",
"DLG_TEXT[75]",
"DLG_TEXT[76]",
"DLG_TEXT[77]",
"DLG_TEXT[78]",
"DLG_TEXT[79]",
"DLG_TEXT[80]",
"DLG_TEXT[81]",
"DLG_TEXT[82]",
"DLG_TEXT[83]",
"DLG_TEXT[84]",
"DLG_TEXT[85]",
"DLG_TEXT[86]",
"DLG_TEXT[87]",
"DLG_TEXT[88]",
"DLG_TEXT[89]",
"DLG_TEXT[90]",
"DLG_TEXT[91]",
"DLG_TEXT[92]",
"DLG_TEXT[93]",
"DLG_TEXT[94]",
"DLG_TEXT[95]",
"DLG_TEXT[96]",
"DLG_TEXT[97]",
"DLG_TEXT[98]",
"DLG_TEXT[99]",
"DLG_TEXT[100]",
"",
};
