string DLG_TEXT[46] = {
"Bom dia aspirante. Posso ver seus documentos e, por favor, diga-me de qual navio você é.",
"Bom Dia senhor. Eu sou aspirante ",
". Estou servindo no ",
"Bom dia Tenente. Posso ver seus documentos e, por favor, diga-me de qual navio você é.",
"Bom Dia senhor. Eu sou tenente ",
". Estou servindo no ",
"Obrigado aspirante. Precisamos ter mais cuidado hoje em dia. Com a situação francesa e espanhola.",
"Eu entendo. Vou continuar com meus negócios. Bom dia para você.",
"Bem, agora que esclarecemos o assunto, você poderia me contar um pouco sobre este porto.",
"Sim senhor. O que você gostaria de saber?",
"Onde encontro o Estaleiro Naval?",
"É o grande edifício no final do cais principal.",
"De onde consigo as provisões do navio?",
"Ao olhar para a cidade, no cais, encontra-se o grande edifício à direita.",
"Onde fica o Quartel-General Naval?",
"Descendo a rua principal até chegar ao jardim circular. Está simplesmente lá.",
"Obrigado. Bom dia.",
"Obrigado Tenente. Precisamos ter mais cuidado hoje em dia. Com a situação francesa e espanhola.",
"Bom dia comandante. Posso ver seus documentos e, por favor, diga-me de qual navio você é.",
"Bom Dia senhor. Eu sou Comandante ",
"Obrigado comandante. Precisamos ter mais cuidado hoje em dia. Com a situação francesa e espanhola.",
".",
".",
".",
".",
".",
".",
".",
".",
"?",
".",
"?",
".",
".",
"",
".",
".",
"",
"",
"",
"",
"",
"",
"",
"",
"",
};
