string DLG_TEXT[84] = {
"Tudo bem.. você é Horácio?",
"Acho que sim.",
"Horácio. Você.. er.. tem algumas.. er.. coisas na manga.",
"Oh! Obrigado Archie. O que fazemos agora?",
"Você ouviu o Tenente. Coloque o navio em movimento. Vamos.. para o tombadilho.",
"Estou bem atrás de você.",
"! O Tenente Bracegirdle está contando a todos como você matou Simpson com apenas um golpe! E olhe para você com seu lindo uniforme novo. Posso perguntar ao tenente, que bunda linda você teve que beijar para isso?",
"Calma Archie! Foram dois golpes! Ha! Ha! Parece que vou ficar para trás enquanto o 'Indy' vai para #sisland_Antigua#. Só me resta o barco alegre!",
"Ah! Um novo tenente. Um novo navio. E um novo carregamento de problemas estarei vinculado. Vou navegar com o 'Indy', então devemos nos separar por enquanto.",
"Archie! Pare com isso! Pelo menos Simpson não estará lá para incomodar você. Boa sorte. Vou dormir um pouco, estou exausto. Então devo encontrar o Sr. Hunter.",
"Sim, temos, mas o que vamos fazer a respeito?",
"Neste momento, Archie, vamos seguir ordens. Vá para o Quartel-General da Marinha. Acho que é aqui perto do jardim redondo",
"Parar! Parar! O capitão está vindo a bordo.",
"Eu não comecei!",
"Isso não importa quando o capitão chegar aqui.",
"Entendido.",
"! O que você está fazendo aqui?",
"Uma longa história, Archie. O que você tem? Você não parece bem?",
"Me deixe em paz ",
". Você não sabe como é aqui. Eles vão te esmagar até que você não seja nada.",
"Archie! Controle-se. Vamos fazer planos para escapar.",
"Escapar! Escapar! Você não acha que eu não tentei isso? Quatro vezes eu fugi. Cada vez fui capturado novamente. Da última vez, me colocaram em um buraco no chão onde não consegui sentar nem ficar em pé por um mês. Já estou farto.",
"Será diferente desta vez, Archie. Estamos todos juntos nisso desta vez.",
"Me deixe em paz. Apenas me deixe em paz.",
"Não se preocupe Archie. Voce vai ficar melhor. Você vai ver.",
". Ainda estou fraco, mas estou me sentindo mais como eu era antes.",
"Bom homem. Pelo menos você está de pé novamente.",
"Me deixe em paz. Me deixe em paz.",
"Archie! Descanse cara. Descansar.",
"Tua graça? Tua graça? Ela não é duquesa ",
". Ela é uma atriz de Drury Lane. Eu costumava vê-la lá o tempo todo",
"O que! Você deve estar enganado, Archie.",
"Eu acho que não ",
". O teatro era um dos meus passatempos favoritos. Eu a vi em muitas peças.",
"Não não. Você ainda está um pouco delirante, Archie.",
"O nome dela é Catherine Cobham. Ela é uma atriz, eu te digo.",
"Ela é uma duquesa Archie. Eu a conheci em #sRedmond#.",
"O navio espanhol está se partindo no recife ",
". O que podemos fazer?",
"Todos para o barco e remem como loucos até ela. Podemos salvar pelo menos alguns deles.",
"Capitão. Falei com a tripulação, e se a liberdade condicional for válida para o Sr. ",
", então também representa para nós. Todos nós.",
"...",
"É como nos velhos tempos ",
". Assim como nos velhos tempos. Suponho que poderíamos planejar uma fuga.",
"Sim, poderíamos. Afinal, é nosso dever.",
"Simplesmente não parece certo de certa forma. Quero dizer, com Don Masseredo nos tratando de forma tão razoável.",
"As brumas da guerra Archie. As brumas da guerra. As coisas tendem a ficar muito confusas às vezes.",
", bom te ver de novo. Ouvi dizer que foi uma batalha e tanto com os franceses.",
"Sim, Archie. Foi por pouco, mas você sabe sobre nossos novos pedidos para se juntar ao 'Renome'?",
"Sim, Capitão James Sawyer e o Renome. Que sorte temos? Um dos capitães mais famosos de toda a marinha. Devemos ir para #sGreenford# para embarcar no navio, pelo que entendi. Como chegamos lá?",
"Andar.",
"Andar? Agora NãO foi por isso que entrei para a Marinha.",
"Não importa Archie. O exercício nos fará bem. Venha na próxima parada #sGreenford# é melhor irmos. O capitão Sawyer não gosta de ficar esperando, ouvi dizer.",
"Nunca passaremos por lá ",
". Os espanhóis viram o navio E os EUA! Eles obviamente têm suas armas apontadas para a passagem. Faremos melhor tentando a velha ponte de corda.",
"Sim, Archie, você está certo. Vamos lá.",
"Como vamos tomar o forte ",
"Usarei a pólvora para explodir a porta. Quando acabar... todos para o forte. Não deveria haver tantos guardas.",
"Os comentários do tenente Quelp sobre um exército escravo parecem verdadeiros. Quase não há comida neste lugar. Os espanhóis não teriam durado mais do que alguns dias com o que lhes restava.",
"Teremos que nos preocupar com isso mais tarde, Archie. Agora temos que pensar em explodir este lugar. Você encontrou alguma pólvora?",
"Bastante! Isso eles tinham. Apenas sem comida. Há muito disso empilhado aqui no pátio.",
"Muito bem. Vamos nos separar e fazer as acusações, depois nos encontraremos do lado de fora do portão.",
"Levei um tiro no estômago ",
"Precisamos levá-lo ao cirurgião Archie",
"Bem, ESSA não foi a recepção que eu esperava!",
"Eu conheço Archie, mas ele parecia estar sob muita pressão. Talvez as coisas melhorem quando chegarmos ao mar.",
"Espero que sim.",
"Vamos embarcar então.",
"Há um barco vindo ao lado de Horácio.",
"É o capitão?",
"Não, mas é um oficial.",
"Muito bem, eu cuidarei disso. Vá e verifique o tombadilho Archie. Vou verificar o timoneiro.",
"O capitão não parece ser o homem que pensei que fosse.",
"Agora, agora, Archie. Ele tem muito em que pensar.",
"Talvez seja assim, Horácio. Mas ele perde o controle rápido demais para o meu gosto.",
"Archie! É o bastante.",
"Como está o Sr. Wellard?",
"Ele ficará bem pela manhã, Archie.",
"Ele estava apenas cumprindo seu dever, Horácio. O capitão ficou furioso e não havia necessidade nem justificativa para isso.",
"Calma, Archie, o Sr. Bush está chegando.",
"O Capitão é pior ",
"Eu conheço Archie e isso me preocupa.",
"Senhor... Fui eu... Empurrei o Capitão Sawyer para o porão.",
};
