string DLG_TEXT[77] = {
"Bom dia Tenente.",
"Bom dia, senhor Artur.",
"Então Pellew, por que a ligação para se juntar a você? Parece que algo está acontecendo?",
"[PENSA: Que garota linda! E ela é irmã do major.]",
"Capitão. Acredito que faremos mais se Sharpe, Harper e eu formos para a prisão e interrogarmos o outro prisioneiro, enquanto você continua sua discussão. Podemos nos encontrar na Academia mais tarde. Bom Dia senhor. E você, tenente.",
"Oh! Sim. Bom dia major.",
"Seu Sr. Quelp mal podia esperar para ir até a casa do contrabandista para preparar as coisas para mim, não é? E pelo que aprendemos com o prisioneiro, sou de fato a mim que os franceses desejam eliminar.",
"Então, o que fazemos agora, senhor?",
"Temos duas escolhas. O Sr. Quelp sem dúvida estará correndo ao longo do túnel enquanto conversamos, para alertar os franceses de que estarei em casa hoje mais tarde.",
"Sem dúvida, senhor.",
"Então o Sr. Sharpe aqui pode pegar seu destacamento e esperar que eles saiam do túnel e então lidar com eles de acordo, ou poderíamos aproveitar o tempo que Quelp e os franceses levarão para se organizar, e usar o túnel da praia para chegar para o seu navio e navegue para #sRedmond#.",
"Então é lutar ou fugir, então senhor.",
"Se quiser colocar dessa forma, sim, Tenente, lute ou fuja. Qual é o seu prazer?",
"Com respeito, eu preferiria ambos, senhor. Lute ENTãO voo.",
"Explique-se, Tenente.",
"Bem, senhor, se o Sr. Sharpe organizar sua tropa na sala principal, eu poderia ir para a sala dos fundos e atrair Quelp e os franceses quando eles chegarem. Sharpe e seus homens irão então despachá-los.",
"Essa é a parte da luta resolvida. E o voo?",
"Quando os franceses estiverem resolvidos, você e eu poderíamos usar o túnel da praia, chegar ao meu navio e seguir para #sRedmond#. Sem mais ninguém vivo, os franceses no acampamento pirata não saberão o que aconteceu ou para onde você foi.",
"Condenação! Eles não eram apenas soldados de infantaria comuns. Eles eram tropas de elite. Higgins, cuide de nossos homens. Acho que eles estão apenas feridos. Nenhum sinal de Quelp, isso parece estranho? Precisamos chegar ao seu navio ",
"Sim, major. É realmente estranho, mas temo que precisemos sair daqui rapidamente. Por aqui até o túnel.",
". Nos preocuparemos com o Quelp mais tarde.",
"Você fez um ótimo trabalho. Vocês dois. Acabaram de trazer Edrington e ele me contou como você derrotou os franceses.",
"Obrigado, Sir Arthur, mas não sabemos se os franceses pretendem desembarcar reforços na praia ainda.",
"Senhor",
"Isso não vai acontecer. Conseguimos contornar o navio que desembarcou nossas tropas e ela expulsou o navio francês, então não haverá mais desembarque de tropas.",
"[PENSA: Então por que nossas tropas não voltaram para nós? Eles devem ter ouvido o canhão.]",
"De qualquer forma, tenho uma tarefa mais agradável para você. Você deve levar esses documentos para #sGreenford#, para o QG Naval. lá. Com toda velocidade, lembre-se. Você entende?",
"Obrigado senhor Artur.",
"Bom... Tenente Sharpe. Quero que você assuma o comando do Segundo Batalhão enquanto Edrington se recupera. Isso será tudo, senhores. Bom dia.",
".",
"Minha vez de fazer apresentações, Tenente. À sua esquerda está o tenente William Chumley, à sua direita, o fuzileiro Sharpe do 33rd Foot.",
"Cavalheiros.",
"O Tenente Chumley estará no comando do destacamento principal, e Sharpe, os escaramuçadores.",
"Escaramuçadores, senhor? Eu pensei que isso seria uma batalha?",
"Tenente. Os escaramuçadores são um tanto incomuns porque são todos atiradores excelentes. Estamos pensando em colocá-los em seu próprio destacamento, mas isso é outro assunto.",
"Eu vejo senhor.",
"Bom. O capitão Pellew me disse que levar o Indefatigable para a costa em tal missão atrairia muita atenção dos franceses antes que pudéssemos chegar perto da costa e correr o risco de atrair sua frota sobre nós.",
"Eu posso ver isso, senhor. Ficaríamos presos na baía em águas rasas. O que significaria pouco espaço de manobra e colocaria a 'Indy' em grande desvantagem.",
"Hummm. Pois bem, seu tenente comandará uma embarcação menor que transportará as tropas e você as desembarcará na praia. Obviamente, você fornecerá os meios para extraí-los após a batalha. Você entende?",
"Sim, major. Completamente.",
"Bom dia comandante. Lamentei saber do jovem Kennedy. Um homem corajoso. Mas devo me preocupar com o assunto em questão. Estou prestes a lançar uma ofensiva para expulsar os franceses do Caribe.",
"Na verdade, Senhor Arthur?",
"Sim. Pretendemos começar por expulsar os destruidores de Guadalupe. Mas estou tendo um pequeno problema, que acho que você e Sharpe aqui podem resolver para mim.",
"Sim. Desde aquele maldito túnel em Charlestown, alguém tem vazado meus planos e tentado me matar. Agora, Sharpe aqui tem algumas ideias, mas precisa de um navio para segui-las, e o Comodoro Pellew ofereceu seus serviços. Você está pronto para isso, comandante?",
"Por que... Er... Sim, senhor, claro, mas não tenho certeza se posso ajudar muito no assunto.",
"Homem poppycock! Você é exatamente o homem de que preciso e, com Sharpe e seus rifles, sei que não preciso mais ter medo. Desejo-lhes um bom dia, senhores, e deixo que vocês resolvam os detalhes.",
"Ah! Comandante Hornblower, é bom ver que está ileso. Como vão as coisas com os franceses?",
"Até agora, senhor, estamos nos segurando. Os fuzileiros de Sharpe os mantêm afastados e conseguimos destruir um de seus canhões.",
"Hornblower Capital! Capital!",
"Sim, senhor, mas não sei quanto tempo poderemos aguentar até que os franceses percebam que tudo o que temos são alguns marinheiros e fuzileiros e lancem um ataque completo contra nós. Não poderíamos resistir a tal força, senhor.",
"Não se preocupe, Hornblower. O navio que transportava o resto do Segundo Batalhão foi avistado rumo ao porto. Você acha que consegue segurar os franceses por mais uma hora?",
"Faremos o nosso melhor, senhor.",
"Bom homem! Então voltarei e transmitirei a palavra de que os reforços deverão vir direto para cá quando desembarcarem.",
"Obrigado, senhor.",
"Muito bem atirar nisso.",
"Qual o seu nome?",
"Sharpe... Sargento. 95º Rifles do Segundo Batalhão, Senhor.",
"Estou muito grato a você. Você me fez um favor muito bom. Agora vou fazer uma coisa muito ruim para você. Estou lhe dando uma comissão de campo, Sharpe. A partir deste momento você é tenente do 95º.",
"Obrigado senhor.",
"Edrington, você informará esta promoção e sugiro que permita que o Tenente Sharpe use sua tropa como achar adequado no próximo combate. Isso será tudo.",
"Soprador de chifre! Sharpe! Você é realmente um colírio para os olhos! Estamos sob ataque dos franceses da praia. Não posso retirar tropas do forte com medo de que isso seja um estratagema e que eles realmente pretendam invadir o porto.",
"O que você precisa que façamos, Sir Arthur?",
"Você e Sharpe levam seus homens para a periferia e impedem que os franceses entrem na cidade.",
"Sim, sim, senhor Arthur... Matthews! pegue Oldroyd e Styles e vá ver o que está acontecendo.",
"Isso vai ser uma coisa difícil, senhores. O corpo principal das tropas está em um navio a caminho de #sisland_Guadeloupe# para estabelecer uma base para meu ataque iminente. Enviei uma nave de perseguição para fazê-los retornar, mas isso levará tempo.",
"Iremos para a periferia e manteremos essa posição para proteger seu flanco, Sir Arthur.",
"Bom homem. Devo ficar aqui e organizar as poucas tropas que me restam. Agora saiam daqui, não temos muito tempo, mas sei que posso contar com vocês.",
"Que bom ver você novamente, Hornblower.",
"Da mesma forma, senhor. Bom te ver.",
"Quanto ao plano, Almirante, duvido que esta paz temporária com os franceses dure muito, por isso precisamos de estar um passo à frente deles.",
"...",
"Temos esse aspecto da operação coberto, Capitão Hornblower. Você se lembra do Tenente Sharpe do 95º?",
"Sim, coronel, muito bem.",
"Bom. Bem, ele e o Major Hogan trabalham, digamos, juntos. Sharpe o levará até Hogan. Sharpe está atualmente servindo na Companhia do Major Dunnitt do 95º.",
"Aqui estão as ordens de libertação de Sharpe, destacando ele e seus homens para você. Entregue-os ao Capitão Murray quando chegar ao 95º.",
"Er, coronel. Onde estão os 95?",
"Eles estão na Ilha Cayman.",
"",
"",
};
