string DLG_TEXT[51] = {
"Ah! ... Buzina.",
"Capitão Hammond.",
"Bem, senhor? Denuncie-se, não temos tempo a perder.",
"H.. H.. Hornblower, senhor. H.. Horatio Hornblower, aspirante. Quero dizer, Tenente Interino, 'Infatigável'.",
"Certificados, por favor.",
"A esta altura você está desmamado... Desmamado senhor... Penhascos de Dover sob sua liderança... Você está com sérios problemas, Sr.... Hornblower.",
"Você estava no convés quando o Capitão Sawyer foi empurrado para o porão, não estava?",
"Sim, senhor, eu estava no convés, mas ele não foi empurrado, senhor, ele caiu.",
"Na verdade, Tenente? Mas só temos a sua palavra para isso, não é?",
"Só posso repetir, senhor, ele não foi empurrado, ele caiu.",
".",
"Comandante Hornblower. Seu navio será desativado imediatamente. Ela será levada para #sOxbay# e trabalhada lá. Você receberá metade do salário até que seus serviços sejam solicitados novamente. E claro, sem um navio para capitão, você voltará ao posto de tenente.",
"Sim capitão, eu entendo, mas onde me alojo agora?",
"Meu Deus, cara! Você espera que a Marinha o mime? Você deve ir à cidade e encontrar alojamento em algum lugar. Bom Dia senhor.",
"Oh! ...",
"Claro que o país não pode continuar a manter uma marinha em tempo de guerra. Caso contrário estaremos pagando esse maldito imposto de renda todos os anos.",
"Oh! Sim. Bom dia para você capitão.",
"?",
"Ah! ... Buzina.",
"Boa noite, Capitão Hammond.",
"Cavalheiros. Meu sobrinho, Jack Hammond. Bem, dê um passo à frente, rapaz. Passo acima. Em sua primeira visita às carnes. Na esperança de ser enviado para um navio.",
"...",
"O que você está insinuando, senhor?",
"Considero isso uma observação ofensiva, senhor.",
"Você gostaria de retirar sua declaração... COM um pedido de desculpas?",
"Muito bem.. Continuaremos com isso.",
"Por Deus, senhor! Eu não vou tolerar isso. Serei recompensado em um duelo ao amanhecer.",
"Vou mandar um amigo para esperar por você!",
"Portanto, apesar de todo o heroísmo de Hornblower, não temos ideia de quais são os planos franceses.",
"Almirante Pellew, senhor. Acredito que existe uma maneira de superar esse problema.",
"Deus nos salve dos jovens aqui para a glória... Senhor, devo insistir que envie um oficial mais experiente.",
"Você incluirá meu sobrinho em sua festa na costa, sem dúvida? Confio que você permitirá que ele tempere seu aço no fogo do combate.",
"Oh! Certamente irei considerá-lo, senhor.",
"...",
"Capitão Hammond. Entregue sua espada e diga a seus homens para deporem as armas, ou você prefere vê-los todos massacrados?",
"Somos homens em menor número. Abaixe os braços.",
"Leve-os para a prisão, tenente.",
"Que bom ver você de novo, Wolfe. Isso foi fácil, não havia tropas com que se preocupar agora. Você tem Hornblower?",
"Tudo trancado com segurança. Agora, vamos enviar os sinalizadores e observar Pellew e a frota navegarem rumo à destruição.",
"SEM NEGÓCIOS, Hornblower!",
"Capitão Hammond!",
"E você pensou que seu inimigo era de nível júnior! Que tolo você é, Hornblower.",
"E que traidor você é, senhor.",
"Basta disso. Wolfe! Esses homens foram pegos tentando escapar. Lide com eles.",
"Oh não! Jack rapaz... você não.",
"Ele está morto, senhor. Ele morreu lutando por seu país.",
"Eu queria que ele fosse preso com você, Hornblower. Fora do caminho com segurança.",
"E ele queria provar que era um oficial corajoso. O que ele fez.",
"Oh Deus! O que eu fiz.",
"Você traiu seu país, seus camaradas e até causou a morte de seu sobrinho. Você não é muito homem, não é?",
"Pare, senhor... Capitão Hammond! Não me faça atirar em você, senhor!",
};
