string DLG_TEXT[40] = {
"Bom dia, Hornblower. Bom te ver de novo.",
"E é bom ver você também, capitão.",
"Tenente ",
"Comandante ",
". Este é realmente um encontro fortuito.",
"Capitão Harvey, senhor. De que forma fortuita?",
"Tenho um certo dilema para resolver. Recebi despachos que exigem que eu retorne a #sRedmond# rapidamente. No entanto, o Tenente Quelp tem ordens para ir ao #sSt John's# em #sisland_Antigua#. Vou designá-lo para o seu navio Hornblower e você pode levá-lo para lá.",
"Certamente Capitão.",
"Excelente Hornblower. Bem, tendo resolvido esse problema, voltarei ao meu navio e navegarei para #sisland_Redmond#. Desejo-lhes bom dia, senhores.",
"Bom Dia senhor.",
"",
".",
".",
"",
"",
"",
".",
"",
".",
"",
".",
".",
"",
"",
".",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
};
