string DLG_TEXT[46] = {
"Capitão Murray, Segundo Batalhão, 95º Rifles, senhor.",
"Continuar.",
"Capitão Murray, Segundo Batalhão, 95º Rifles, senhor.",
"Continuar.",
"Comandante, senhor. A que devemos o prazer da presença de um oficial da Marinha de tão alta patente.",
"Tenho ordens do Almirante Pellew e do Coronel Wellesley relativamente ao seu batalhão. Onde eu encontraria seu comandante?",
"Bem, eu sou o Capitão Murray. O Major Dunnitt está no comando. Ele está na cabana ali. Vou levá-lo até ele, senhor.",
"Obrigado capitão. Vou te seguir.",
"Esses papéis estão em ordem, senhor. Eles transferem Sharpe para o comandante para tarefas especiais.",
"...",
"Eu não... vou... conseguir. Dê a Sharpe,... minha espada. Deixe-me. Tire... os homens... daqui.",
"Capitão....",
"[tosse] Tire os homens [tosse] daqui. Isso é uma ordem. [tosse] Diga a Sharpe para assumir.",
"Sim capitão.",
"?",
".",
".",
".",
"",
".",
"?",
".",
".",
".",
".",
".",
".",
".",
".",
"?",
".",
"?",
".",
".",
"",
".",
".",
"",
"",
"",
"",
"",
"",
"",
"",
"",
};
