string DLG_TEXT[59] = {
"Você deve ser Hornblower?",
"Sim capitão.",
"Que bom vê-lo novamente, Pellew, e você, Sr. Bracegirdle. E você deve ser o aspirante de quem tanto ouço falar.",
"Aspirante Hornblower, capitão. A seu serviço.",
"Exatamente, Sr. Hornblower. Tenho aqui um relatório de que o 'Infatigável' interferiu desnecessariamente no ataque de Justiniano ao Téméraire. E o Sr. Simpson aqui, me informou que você estava no comando do leme na época.",
"Er, sim, mas...",
"Meu querido Pellew, não tenho dúvidas da situação durante a batalha. O que me preocupa é o que o Sr. Simpson está fazendo me dando um sinal que foi dirigido a você, Pellew? Sua reação me diz que você não sabia de nada.",
"Na verdade, Pellew, concordo com a sua avaliação do Sr. Hornblower. Isso nos deixa com o Sr. Simpson, e um ato que, na melhor das hipóteses, considero uma insubordinação grosseira e, na pior, uma intenção de ajudar o inimigo, interferindo na comunicação com um oficial superior. O que você tem a dizer, Sr. Simpson?",
"Hmmm. Belo giro da lâmina, Hornblower. Essa é uma maçã podre com a qual não precisamos mais nos preocupar. Sr. Bracegirdle, poderia fazer a gentileza de encontrar alguns fuzileiros navais para resolver esta bagunça.",
"Acho que funcionou muito bem. Você não concorda, Pellew?",
"Jogou fora...?",
"Agora que o Sr. Hornblower finalmente chegou, podemos prosseguir com o assunto em questão.",
"Desculpe capitão.",
"Aspirantes Clayton, Kennedy e Hornblower, ouvi dizer que sua jornada da Inglaterra ao Caribe foi tranquila. Um cruzeiro tranquilo às custas do Rei! Ha ha! O que!",
"Sim senhor, mas..",
"QUIETO! Soprador de chifre. Isso não foi uma pergunta. Por mais monótono que tenha sido, garanto-vos que os assuntos terão muito mais consequências aqui. Estamos rodeados pelos nossos inimigos que estão determinados e determinados a dominar este arquipélago. NÓS, senhores, devemos detê-los.",
"[PENSA: E existem piratas.]",
"E há piratas com os quais lidar. Vocês, cavalheiros, cumprirão seu dever. Você continuará servindo no Justinian sob a competente capitania do Capitão Keene.",
"[PENSA: AH NãO! Já sofri intimidação suficiente na jornada até aqui.]",
"Capitão Keene, você tem algumas palavras para estes senhores, tenho certeza?",
"--",
"Muito bom trabalho, senhores! Que Pellew! Nelson! Você não concorda?",
"Capitão francês, tripulação francesa e um navio francês. Tudo em um dia! E tudo feito por um sargento e um tenente interino! Esse é para o diário do Almirante. O que!",
"Obrigado senhor.",
"Vamos, garoto... Não vamos comer você.",
"Tenente Hornblower. Nos encontramos novamente... Disseram-me que terei o prazer de sua companhia como meu terceiro-tenente no 'Renome'.",
"A honra é toda minha Capitão Sawyer.",
"Honra! Honra senhor! ... Ouvi falar de suas façanhas, SR. HORNBLOWER. Subindo rapidamente na hierarquia, segundo me disseram. A cada navio uma promoção. Tenha certeza, senhor, que as coisas não serão tão fáceis para o 'Renome'.",
"Senhor?",
"Conheço o seu tipo, Sr. Hornblower... abrindo caminho para o sucesso nas costas de seus camaradas e superiores. Só o caminho deles servirá.",
"Capitão, eu protesto!",
"Ouviu aquele doutor Clive? Ele já protesta contra minha autoridade!",
"Capitão!",
"Chega de Hornblower! ... E quem são esses 'senhores' que você traz consigo?",
"Tenente interino Archie Kennedy e aspirante Henry Wellard, senhor",
"Henry Wellard... Ele não parece capaz de lutar contra um biscoito de navio, muito menos contra um francês. Subam a bordo e preparem-se para o mar. Você, Sr. Hornblower, será o oficial de guarda.",
"Aye Aye capitão.",
"Você veio na minha ausência, não é?",
"Você se reportou ao primeiro-tenente?",
"Não senhor.",
"Na minha ausência, você deveria ter se reportado ao Sr. Buckland... Sr. Buckland, por que o Sr. Bush não se reportou a você?",
"Bem, Sr. Bush, você é realmente bem-vindo. Com o tempo você pode realmente me agradecer. Muito bem.",
"Agora vamos colocar este navio em movimento. Curso Norte por Leste.",
"Aye Aye capitão. Norte por Leste é.",
"Solte as velas superiores. Solte a vela grande. Transporte nas linhas principais. Saltem para lá, retardatários, ou vou arrancar a pele de vocês!",
"Sim, senhor. Solte as velas superiores. Solte a vela grande. Transporte nas linhas principais.",
"Então você quer navegar com ela, Sr. Bush?",
"Sim senhor... Com sua permissão.",
"Muito bem.... Todos. Todas as mãos para as velas superiores do recife! Leve o equipamento de recife! Transporte!",
"Que é aquele! Quem é aquele que se atreve a revogar minhas ordens?",
"Sr. Wellard! ... Eu deveria saber. DESÇA AQUI SR. BEM-ESTAR! Eu vou te ensinar a me desobedecer",
"Mas senhor, houve um bloco rasgando a vela!",
"O Sr. Wellard é um dos seus, creio eu. Bem, veremos o que uma dúzia de golpes com o rattan do Sr. Matthews fará para dissuadi-lo de me desobedecer.",
"Senhores.. Fomos encarregados de tomar o forte espanhol em Playa de Sabana.",
"Capitão, o Sr. Kennedy e eu ficamos presos lá por um tempo, então conhecemos a área.",
"Ah! Sr. Hornblower. Bem, é claro que podemos contar com você para obter as informações mais recentes, não podemos?",
"Não brinque comigo, senhor! Eu conheço o seu tipo. Sempre ouvindo, sempre conspirando.",
"Você também, Sr. Bush? Sim.. tudo faz sentido, vi todos vocês conspirando contra mim. Conspirando contra mim... Conspirando..",
"Eu sei que você está aqui embaixo. Conspirando contra mim. Sair. Saia maldito!",
};
