string DLG_TEXT[19] = {
"Fique atento quando falar comigo.",
"Sim capitão.",
"Isso é melhor. Agora, Sr. ",
"Sim senhor. Quais são seus pedidos?",
"Você será transferido para o Infatigável sob o comando do Capitão Sir Edward Pellew.",
"Mas capitão, eu preferiria ficar a bordo de seu navio servindo sob seu comando.",
"É uma oportunidade certa de progresso. Para distinção. É para o bem do serviço que tenho em mente, Sr. Hornblower, e insisto que você assuma este cargo.",
"Sim, capitão, imediatamente.",
".",
"Aspirantes! Seu desempenho demonstrado durante a viagem desde a Inglaterra precisa melhorar muito. Você continuará se reportando à divisão do Sr. Simpson.",
"[PENSA: Gemido. Fica cada vez melhor.]",
"Temos a missão de entregar suprimentos aos agentes que trabalham para nós em #sisland_Guadeloupe#. Desembarcaremos em Anse Casse Bois e avisarei, senhores, que esta é uma missão perigosa e de extrema importância. Sr. Simpson, uma palavra, por favor. O restante de vocês se apresenta ao Quartel-General da Marinha para mais instruções.",
"[PENSA: Bem, pelo menos ação. Espero estar à altura.]",
"Atenção no convés!",
"Suas ordens, capitão.",
"Sr. Clayton, levante âncora. Sr. Simpson, Sr. Kennedy içou as velas, por favor. Sr. Hornblower assuma o comando, senhor. Curso, Sudõeste enquanto saímos do porto, então mantemos esse rumo para #sisland_Guadeloupe# assim que saímos da ilha.",
"Sim capitão",
"Obedeça às ordens... Cumpra o seu dever... E nenhum mal lhe acontecerá.",
"Isso basta.",
}
