string DLG_TEXT[67] = {
"Bom dia Tenente.",
"Bom dia, Dom Masseredo.",
"Eu sou Dom Masseredo. Comandante da Prisão da Fortaleza. Vocês agora são prisioneiros da Espanha.",
"Eu sou tenente ",
", do navio Infatigável de Sua Majestade Britânica. Ao seu serviço, senhor.",
"Tenente. Você e seus homens serão levados para o forte marítimo, onde passarão o resto da guerra. Se você mostrar respeito por mim e pelos guardas como seus captores, você será bem tratado.",
"Obrigado Vossa Excelência. Isso será muito apreciado.",
"No entanto, se você tentar escapar, seu tratamento será drasticamente alterado.",
"Escapar, Excelência, é dever de todo oficial britânico.",
"Tenente. Já disse tudo o que pretendo dizer sobre o assunto. Guardas! Leve-os embora.",
"...",
"Tenente ",
". Sua Graça me informou que vocês são velhos conhecidos.",
"Er.. Sim, Excelência. É isso mesmo.",
"Ah! Então. E ela também me informa que está precisando de companhia em suas caminhadas diárias.",
"De fato? Vossa Excelência.",
"Você e seus homens se comportaram bem durante seu cativeiro, Tenente. Então, se você me der liberdade condicional para não tentar escapar, permitirei que você a acompanhe em suas excursões diárias. Você concorda Tenente?",
"Dom Masseredo. Eu lhe darei minha liberdade condicional de que não tentarei escapar enquanto caminhava com sua Graça.",
"Isso é bom tenente.",
"No entanto, senhor, devo avisá-lo que fora desse horário, considero meu dever, como oficial britânico, tentar escapar.",
"Na verdade, Tenente. Bem, desde que você não tente me matar na minha cama, desejo-lhe boa sorte em sua tentativa. Entretanto, o portão no canto leva às falésias. Aproveite sua caminhada.",
"Obrigado Vossa Excelência.",
", ficaria honrado com sua presença no jantar desta noite. Eu tenho um convidado. Coronel Etienne de Vergasse do exército francês.",
"Obrigado Vossa Excelência. Será um prazer.",
". Apresento-lhe o Coronel Etienne de Vergasse.",
"É um prazer conhecê-lo, Coronel.",
"Venha, coronel! Uma trégua prevalece aqui, a neblina e o vento podem fazer qualquer homem de bobo.",
"É verdade que houve um noivado em #sisland_Hispaniola# recentemente, senhor?",
"Houve? Você deseja envergonhar um cavalheiro espanhol na frente de seus convidados?",
"Tenho más notícias para nós dois, Sr. ",
". A Duquesa partiu num saveiro, o Almaria, com destino a Portugal. Então nossos dias serão mais longos de agora em diante, infelizmente.",
"Na verdade Vossa Excelência. Na verdade eles irão.",
"Porém, para aliviar um pouco os dias, estou permitindo que seus homens se juntem a você na praia para suas caminhadas.",
"Obrigado Vossa Excelência. Tenho certeza que eles ficarão muito gratos.",
" Ouvi dizer que há uma batalha acontecendo entre um de seus navios e um dos nossos. Por favor, diga-me senhor, qual é o nome do navio britânico?",
"É o Infatigável Vossa Excelência. É o meu antigo navio.",
"Seu navio perseguiu o nosso bem perto da costa, mas ela não a está alcançando, eu vejo.",
"Não, senhor, mas o seu está carregando velas demais e deve virar logo. A 'Indy' a terá então.",
"O Almaria é um bom marinheiro. Ela será difícil de pegar.",
"A Almaria?",
"Não se preocupe, ela teve tempo de navegar até um porto e descarregar sua carga.",
"Ela perdeu a vela superior! Meu Deus, ela está indo para o recife.",
"Ela vai limpar o recife?",
"Não sem as velas superiores",
"O Diabo a pegou, ela atingiu o recife.",
"Devemos lançar barcos e tentar salvá-la. Dê-me um barco e meus próprios homens e pelo menos poderemos salvar a tripulação dela.",
"Claro... e isso lhe daria a oportunidade perfeita para escapar.",
"Senhor, aqueles homens lá fora estão morrendo. Se pudermos pegar um barco, podemos salvá-los.",
"Mas eles são seus inimigos.",
"Senhor, o mar não toma partido. Dá-me um barco, eu te imploro.",
"Você me dará sua liberdade condicional e a de seus homens dos quais não escapará.",
"Dou-lhe minha palavra, senhor.",
"Ir. Há um barco na próxima baía. Siga a praia de onde vieram seus homens, você a encontrará. E Deus esteja com você.",
"E com os homens lá fora",
"Você não é apenas um homem corajoso, Tenente ",
", mas você também é um homem de honra. Tentarei tornar a sua estadia conosco tão agradável quanto as circunstâncias permitirem.",
", chegou uma carta a seu respeito, de Suas Excelências em Madrid.",
"Sim senhor?",
"O primeiro-ministro informou-me que, em reconhecimento à sua coragem em salvar vidas correndo perigo, você e a tripulação do seu navio serão postos em liberdade.",
"Estamos livres para ir?",
"Isso é o que geralmente entendo como liberdade.",
"Obrigado senhor. Sinto-me honrado pela consideração de suas Excelências.",
"Mmmm... Eu me pergunto se suas Excelências percebem que estão libertando um homem que sem dúvida será um espinho em seu sapato por muitos anos.",
"Tentarei não decepcioná-los, senhor.",
"Mmmm... Bem, é adeus, Sr. ",
". Seu navio recebeu permissão para atracar na baía. Você sabe onde fica. Pegue sua tripulação e vá.",
"Adeus, Excelência.",
"",
};
