string DLG_TEXT[40] = {
"Olá Hornblower. Está tudo bem com você, eu confio?",
"Sim, obrigado, Tenente.",
"Então, senhor Hornblower, Sua Graça me disse que você foi descuidado o suficiente para navegar seu navio direto para o meio da frota espanhola.",
"...",
"Na verdade, não quis ofender o Sr. ",
" vossa Excelência. Na verdade eu ia agradecer a ele. Se não fosse pelo seu infeliz encontro, não teríamos o prazer da companhia de Sua Graça esta noite. Na verdade, senhora, já se passaram alguns anos desde que estive em Londres, mas tenho a sensação de que já nos conhecemos.",
"De certa forma. Devo confessar que depois de Paris achei tudo sujo, e a comida boa... Mas o seu teatro, por outro lado, é incomparável.",
"Senhora dos Rivais. Essa foi uma das peças que vi.",
"Oh não, senhora, é uma comédia. Na verdade, é mais que uma comédia. É uma peça sobre engano.",
"Você faz dois prisioneiros muito interessantes. A atriz que finge ser duquesa. O menino que finge ser capitão.",
"Eu me ofendi, senhor.",
"É claro que é uma excelente forma de recolher informações. A Duquesa e o oficial da marinha inglesa, cujo navio por acaso navega para a frota espanhola.",
"Eu me pergunto qual é a penalidade para espionagem aqui. Morte para você certamente. E para você, senhorita Cobham, temo um fim semelhante.",
".",
".",
"",
".",
"!",
".",
".",
".",
".",
".",
".",
".",
"!",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
};
