string DLG_TEXT[40] = {
"Sou o Coronel Francisco Manuel Ortega ao seu serviço.",
"Bom dia Coronel.",
"É meu triste dever entregar o forte, suas tropas e a ilha a você...?",
"Tenente Horatio Hornblower, do renomado navio de Sua Majestade, coronel, e eu aceitamos sua rendição.",
"Obrigado Tenente.",
"Eu ficaria satisfeito se você nos acompanhasse enquanto inspecionamos o forte.",
"Claro, Tenente. Por aqui, por favor.",
"Obrigado Coronel.",
"Como vê, Tenente, o que resta da minha guarnição está reunido sob suas ordens, e há um oficial da marinha britânica que foi prisioneiro aqui, a quem vou libertar para você.",
"Obrigado Coronel. Você poderia fazer a gentileza de libertar o oficial e se juntar às suas tropas, por favor.",
"",
".",
".",
".",
".",
"!",
".",
"!",
".",
".",
".",
".",
".",
".",
".",
"",
".",
"",
"",
"..",
".",
"",
"",
"",
"",
"",
"",
"",
"",
"",
};
