string DLG_TEXT[40] = {
"Bom Dia senhor.",
"Bom dia.",
"Com licença, Tenente. Você poderia me ajudar por favor? Disseram-me para me apresentar ao Renome na divisão do Tenente Hornblower. Você sabe onde posso encontrá-lo?",
"Eu sou ele. E quem é você?",
"Aspirante Henry Wellard, senhor, e prazer em conhecê-lo. Eu ouvi muito sobre você.",
"Prazer em conhecê-lo também, Sr. Wellard. Este é o tenente interino Archie Kennedy. Precisamos ir ao QG Naval. agora mesmo para reportar ao Capitão Sawyer. Você deveria vir conosco.",
"Sim, sim, senhor.",
"Vamos então.",
"Alguma ordem, Tenente Hornblower?",
"Sim, Wellard. Vá e verifique os cabos de ancoragem. Precisamos estar prontos para levantar âncora quando o capitão chegar aqui.",
"Atrasar o transporte! Adie o lance!",
"Sou eu, senhor... Wellard... Há um bloco preso e rasgando a vela.",
"Queria agradecer-lhe, senhor, por falar por mim com o capitão.",
"Aqui não, Wellard. Acho que ouvi a porta da cabine do Capitão abrir.",
".",
"!",
".",
"!",
".",
".",
".",
".",
".",
".",
".",
"",
".",
"",
"",
"..",
".",
"",
"",
"",
"",
"",
"",
"",
"",
"",
};
