string DLG_TEXT[23] = {
"Ei, meninos! Veja o que a maré trouxe. Horatio Hornblower, Sr.",
"Simpson, você simplesmente não aprende, não é?",
"Chame-me de Sr. Simpson, garoto... se você sabe o que é bom para você. Sou o aspirante sênior aqui. ",
"Senhor Simpson. Você simplesmente não aprende, não é?",
"Pelo que me lembro, eu me segurei quando você e Clayton tentaram me atacar.",
"Não foi assim, Simpson, e bem, você sabe disso.",
"Então, quer tentar de novo, um a um, por assim dizer?",
"Seria um prazer.",
"Explodir seus olhos ",
"Já é hora de as coisas finalmente serem resolvidas com você, Sr. Simpson, prepare-se.",
"Eu sou o aspirante sênior.",
"Como se pudéssemos esquecer!",
"! Sou o aspirante sênior. Se alguém for promovido, deveria ser eu! Vou interromper sua promoção.",
"Aí estão vocês, preguiçosos. Ande, o capitão está esperando para navegar.",
"Simpson, estamos organizando as lojas e as novas armas!",
"Organizado! Organizado! Talvez isso o organize mais rápido.",
"O que?!",
"Poderíamos ter estado no mar há horas, rapazes. Hornblower e seus amiguinhos se perderam no estaleiro! Ha! Ha!",
"Simpson.. ",
"Que craca você realmente é, Hornblower. Agora o Capitão vai ficar furioso porque não chegamos a tempo.",
"Simpson, você estava no comando do alegre barco. Você escolheu desembarcar pelo caminho mais longo. É hora de você ser chamado para prestar contas. Eu desafio você para um duelo. Aqui agora.",
"O Tenente, Hornblower e Clayton me atacaram totalmente sem provocação. Eu só tive que me defender. Eu nocauteei Hornblower, mas Clayton..",
"Simpson! Não foi assim!",
}
