string DLG_TEXT[46] = {
"Aspirante Hammond, senhor.",
"Continuar.",
"Aspirante Hammond, senhor.",
"Continuar.",
"Bem... há um homem, senhor... mas ele não é capitão. Eu li muitas de suas façanhas, senhor.",
"Oh! Sinto muito, não estou em posição de lhe oferecer nada.",
"Sr. Hornblower, por que você é tenente novamente e não mais comandante?",
"Porque minha promoção não foi permitida quando a Retribuição foi encerrada.",
"Comandante Hornblower, senhor. Há um sinal da Nave Capitânia, senhor. Você deve se apresentar a bordo.",
"Obrigado, Sr.",
"Eu também gostaria de ser voluntário, senhor.",
"Muito bem, Sr. Hammond. É hora, homens, de irem para os barcos e para a costa, e ficarem o mais quietos que puderem.",
"Capitão! O operador do semáforo está parado ali no penhasco. Ele pode nos ver.",
"Acalme-se, Sr. Hammond... Styles, você sabe o que precisa fazer. Ele não vai ouvir você até que seja tarde demais. Ele tem o vento soprando em seus ouvidos ali em cima. Seguiremos logo atrás de você.",
"Precisamos ser rápidos, senhor. Acho que ouvi uma trombeta de alarme francesa soar.",
"Não vamos demorar muito, Sr. Hammond. Você fica aqui e vigia. O resto de vocês coloca as cargas dentro da torre.",
"Isso vai demorar muito, senhor. Ouvi a trombeta novamente. Nós... ficaremos presos aqui.",
"Fique firme, Sr. Hammond! Volte para a praia e diga ao Sr. Matthews que estamos atrasados e que se prepare com os fuzileiros navais para um combate a incêndio quando retornarmos.",
"...",
"Ele ordenou que você retirasse os fuzileiros navais?",
"Ele viu os reforços franceses avançando no posto de sinalização, senhor. Ele me disse para correr na frente e evacuar o cais. Mas queríamos esperar por ele, senhor.",
"Obrigado, Sr. Volte às suas funções.",
"Sr.",
"Tudo pronto, senhor? Não há para onde correr agora.",
"Uma palavra, por favor. Para que você saiba, Matthews, não me importo muito com o seu tom.",
"Bem, senhor, devo dizer que não dou a mínima para o que você gosta. O Capitão Hornblower nunca lhe ordenou que passasse por aquele cais. [Você não estava lá.] Ele nunca teria desistido tão fácil. Embora você possa.",
"Você não sabe o que aconteceu.",
"Eu sei que ele lhe deu uma chance de provar seu valor. Ele fez isso por muitos homens. Eu, Styles e ninguém nunca o decepcionamos, até agora. Se isso é tudo que tem a dizer, senhor, tenho trabalho a fazer.",
"Esperemos poder contar com o seu tio, senhor.",
"Sinalização emblemática, senhor. Todos os navios... então... retirem-se, senhor.",
"Tem certeza?",
"Sim senhor.",
"Melhor verificar. Procure no livro.",
"Sim, sim, senhor... mas... tenho certeza, senhor.",
"",
"",
".",
"",
"",
"",
"",
"",
"",
"",
"",
"",
};
