string DLG_TEXT[63] = {
"Você parece confuso, está tudo bem com você?",
"Oh! Err... Sim, senhora.",
"Aham..hem...hem...",
"Nos encontramos novamente, ",
". Você se lembra de mim, não é? ",
"Err... sim. Claro, ",
"Tenho lido sobre suas façanhas desde que nos conhecemos em #sisland_Quebradas Costillas#, mas não esperava encontrá-lo novamente, ",
"Mas o que você está fazendo a bordo de um lugger espanhol?",
"Há febre amarela em #sIsla Muelle#. Quando Capitão ",
" partiu em busca de você, ele foi bom o suficiente para...",
"<Você ouve gritos vindos da área de embarque.>",
"Me perdoe, ",
", mas eu estava prestes a lhe dizer que preciso de passagem para #sGreenford# para mim e minha empregada.",
"Não no ",
"Que outro navio britânico está nestas águas, senhor? Você sugere que nademos para casa?",
"Sugiro que Vossa Senhoria retorne a #sIsla Muelle# e embarque em um navio que tenha enfeites e fantasias suficientes para mulheres passageiras.",
"Mil pessoas morreram em #sIsla Muelle# esta semana.",
"Posso perguntar por que você estava em #sIsla Muelle# em primeiro lugar?",
"Porque, senhor, o pacote britânico em que navegava foi capturado há meses pelos espanhóis. Fui prisioneiro deles até a aliança. E devo dizer que fui tratado pelo inimigo com mais cortesia do que recebi até agora do capitão do navio de Sua Majestade ",
"Aham... aham...",
"Exatamente!",
"Isto elimina qualquer possibilidade de Vossa Senhoria permanecer a bordo.",
"De fato?",
"Estamos a caminho de combater um navio com o dobro da nossa força. Se formos derrotados, você estará nas mãos de um maníaco carniceiro!",
"Se eu voltar para #sIsla Muelle#, provavelmente morrerei de febre. E como há uma boa chance de morte em ambos os casos, devo insistir em fazer eu mesmo a escolha.",
"E agora, se Vossa Senhoria acompanhar o Sr. ",
", talvez você se arrependa de sua insistência.",
"Espero não estar atrapalhando a rotina do navio, Sr. ",
"Ah, não, nem um pouco, senhora.",
"Estou com medo ",
" Hornblower pensa o contrário.",
"Bem, ele tem muita coisa em mente agora, senhora. Se ele não retomar a 'Natividad', terá sérios problemas.",
"Certamente não é culpa dele se a Espanha mudou de lado na guerra?",
"Receio que o Almirantado não pare para considerar isso, senhora.",
"Você gosta de ",
", não é?",
"Gosta, senhora? Ora, ele é o melhor oficial da Força! Ele é um marinheiro melhor que o Sr. Bush, um artilheiro melhor que o Sr. Gerard, e quando se trata de navegação, o Sr.",
"Gentil e caloroso. Eu entendo o que ele quer dizer!",
"<Grito de cima> SR. ",
"Sim, querido. Você voltou para mim.",
"Oh sim. Sim, meu querido.",
"Se eu soubesse como!",
"Nos olhos e na boca, Vossa Senhoria.",
"<Beija Longley conforme as instruções.>",
"Como você sabia?",
"Foi a maneira como ela se despediu dele em #sGreenford#. Como se ela estivesse lhe dando um beijo de boa noite.",
"E ela estava...",
"Isso foi gentil da sua parte.",
"Adeus, ",
". Obrigado pela sua gentileza.",
"Adeus, Senhora Bárbara.",
"Capitão ",
"?",
"Bárbara!",
"Eu esperava que nos encontrássemos. Queria te dizer o quanto sinto muito pela notícia que você recebeu em casa.",
"Obrigado.",
"Ouvi dizer que você tem um filho.",
"Sim! Um menino para se orgulhar.",
"Tenho certeza que ele está.",
"Bem, devo me despedir agora. Desejo-lhe toda felicidade.",
"Obrigado. Adeus, ",
".",
"Adeus, Bárbara.",
}
