string DLG_TEXT[55] = {
"Olá Hornblower. Está tudo bem com você, eu confio?",
"Sim, obrigado, Tenente.",
".",
"Vejo que o forte é nosso, acho que meu plano deu muito certo, muito bem mesmo... Esse é o tenente Quelp, se não me engano? Como ele veio parar aqui?",
"Sim, Tenente. Ele era um prisioneiro aqui, senhor. É uma longa história, mas sem dúvida ele lhe contará quando estiver a bordo.",
"Bom. Bom. Bem ",
", peço-lhe que apresente o Comandante do Forte para que eu possa receber sua rendição formal como Capitão do 'Renome'.",
"Será um prazer, Capitão Sawyer.",
"...",
"Vá até o senhor do tombadilho. #sCharlestown# fica na ilha de #sisland_Quebradas Costillas#. Quando sairmos do porto, dê ao timoneiro um curso de Leste para Sul.",
"Leste por Sul. Sim, sim, tenente. [PENSA: Oh querido! O navio está se movendo. Já estou começando a sentir enjôo!]",
"Qual é o problema, cara? Você ficou bastante verde.",
"Bluuurk....",
"Ah! Hornblower, aí está você. O Capitão Pellew quer que coloquemos a nova tripulação à prova. Ele quer ter certeza de que eles estão prontos para a batalha antes de partirmos. Devemos navegar para #sGreenford# em #sisland_Oxbay#, pegar dois oficiais, depois retornar aqui e embarcar no capitão para que ele possa inspecionar a tripulação.",
"Sim, tenente.",
"Serei capitão interino, então espero muito trabalho de sua parte. Pelo menos pode proporcionar alguma distração do seu vômito contínuo! Ha! Ha!",
"Divertido. Muito divertido, tenente. Vamos em frente então.",
"Meu Deus, cara! Que bagunça. Senhor Kennedy! Talvez você pudesse fazer a gentileza de ajudar o Sr. Hornblower em suas abluções!",
"Eu ficarei bem, senhor.",
"O que os manteve, senhores? Já temos a mercadoria entregue. Esse deve ser um barco muito lento que você tem.",
"Não importa, o trabalho está feito agora. Não espere muito. Há um forte francês no próximo vale, então precisamos voltar a bordo.",
"Oh! Er... sim, tenente. Voltaremos para o navio.",
"O que diabos aconteceu aqui? Ouvimos a agitação vinda da praia quando estávamos prestes a embarcar no barco do navio.",
"Não tenho certeza, Tenente. Eu estava... inconsciente.",
"Esta é uma bela bagunça, e um bom homem para começar. É cada um de vocês, a palavra de um homem contra o outro. O Capitão terá que decidir o seu destino. Voltem a bordo do navio e considerem-se presos.",
"Kennedy, chame alguns homens e leve o corpo de Clayton de volta a bordo. Teremos que enterrá-lo no mar. O agente nos deu ordens que dizem que devemos navegar diretamente para #sRedmond#, então não podemos mais ficar aqui. Eu disse para embarcarem, vocês dois. AGORA!",
"Estou nervoso por deixar o navio, sendo capitão interino. Você deve reunir os oficiais por conta própria. Você precisa ir ao QG Naval. Fica perto da prisão na cidade principal.",
"Sim, tenente.",
"Aye Aye capitão. Vou chamá-lo... Coronel Ortega, por favor, senhor.",
"Bom dia Coronel. Eu sou o Capitão Buckland do Navio 'Renome' de Sua Majestade e aceito sua rendição formal.",
"Agora, Sr. Sharpe, faça a gentileza de acompanhar o Tenente Quelp e os prisioneiros até o navio.",
", vou exigir que você fique para trás e exploda o forte.",
"Explodir o forte, senhor?",
" Conversando com a tripulação na baía parece que toda a ilha foi tomada por escravos fugitivos. Eles estão com o forte sitiado há semanas e não poderíamos enfrentá-los.",
"Entendo, senhor. Muito bem, encontrar-me-ei contigo na baía distante quando tudo estiver pronto.",
"Esperaremos por você o máximo que pudermos, mas, se o exército de escravos aparecer, talvez eu tenha que embarcar. Você entende minha posição, tenho certeza?",
"Aye Aye capitão.",
"Que calamidade! Que calamidade!",
"Você está ferido, senhor?",
"Você consegue ver algum sangue?",
"O 'Renome' foi recuperado Senhor.",
"Posso ver que está recuperado e posso ver quem o recuperou!",
"Sinto muito, senhor, eu não sabia que o Sr. Bush havia subido a bordo. Ele deveria ter se dado a conhecer senhor, eu estava na frente, inspecionando os cabos da âncora.",
"Não é de surpreender. O Doutor Clive o toma com Laudanum quase continuamente.",
"Quer dizer que ele está drogado? Então ele não está apto para comandar o navio, certamente?",
"Isso não cabe a nós dizer. A decisão é do Doutor Clive.",
"Mas estamos nos aproximando de #sisland_Cuba# e do inimigo. Não podemos continuar assim. Precisamos de um comandante capaz.",
"Bem, senhores, estou satisfeito que o Capitão esteja vivo, mas devo agora assumir o manto de comando.",
"Acho que seria melhor se você me chamasse de Capitão, Sr. Hornblower.",
"Bom Bom. Agora vamos ao meu plano. Chegamos à Playa de Sabana. Pretendo que destruamos o forte para o reino vindo daqui da baía.",
"Capitão... O forte fica no alto de um penhasco. Não seremos capazes de elevar as armas suficientemente alto.",
"Oh! E o que você sugeriria, Sr. Hornblower?",
"Que levemos um grupo de desembarque para terra e façamos um ataque terrestre. Assim não arriscamos o navio... Capitão.",
"Sim Sim. Isso é o que eu estava prestes a propor. Então prepare-se. Senhor Bush, senhor Hornblower, senhor Kennedy, preparem os homens, lançaremos os barcos imediatamente.",
"Senhor, eu protesto! Eu tinha acabado de sentir o peso de comandar o navio sobre mim. Eu tive que planejar o ataque ao forte. Tudo isso não teria acontecido se o Capitão não tivesse sido empurrado pelo Tenente Horatio Hornblower!",
};
