string DLG_TEXT[40] = {
"Olá Hornblower. Está tudo bem com você, eu confio?",
"Sim, obrigado, Tenente.",
"Bom Dia senhor. Posso perguntar sobre a natureza do seu negócio?",
"Estou aqui para os exames de tenente, tenente.",
"Ah! você é o último candidato. Você encontrará os capitães no escritório no topo da escada. Você deve entrar direto.",
"Obrigado, Tenente.",
"Bom dia aspirante. Posso perguntar sobre a natureza do seu negócio?",
"Bom Dia senhor. Estou aqui para reunir alguns oficiais que se juntam ao Infatigável. Aqui estão as ordens para esse efeito.",
"Certamente aspirante, está tudo em ordem. Você os encontrará no topo da escada à sua frente.",
"É um alarme geral! O forte está soando um Alarme Geral. Há um navio de bombeiros espanhol chegando ao porto!",
"Minha nossa! Devemos chegar aos navios!",
"Sim Comandante, em que posso ajudá-lo?",
"Você mantém os registros de todos os navios que entram e saem do porto e dos oficiais designados para eles, não é?",
"Sim comandante. O Comodoro Pellew é muito rigoroso com relação a esses assuntos. Ele gosta de saber onde estão seus navios e seus oficiais o tempo todo.",
"Bom. Então você poderia fazer a gentileza de me dizer em qual navio a Tenente Quelp está servindo e onde ela está atualmente?",
"Oh! Não preciso procurar isso, senhor. O tenente Quelp estava desaparecido em combate, mas foi considerado prisioneiro dos espanhóis. O Renome o resgatou... mas você estava naquele navio, Comandante?",
"Sim, sim, eu conheço o Tenente, mas em que navio ele está agora e onde ela está?",
"Oh! Seu navio, The Hound. HMS Hound sob o comando do capitão Harvey. Ele esteve aqui para a Corte Marcial... Oh! Desculpe senhor.",
"Não importa, Sr. Chadd. Prossiga.",
"O Cão de Caça partiu para #sisland_Cayman# na maré da noite passada, senhor.... Isso é tudo?",
"Sim, Tenente. Obrigado. Isso será tudo.",
"Ordens senhor?",
"Sinal para a Nau capitânia. Capitão em ação em terra, relatório a seguir. [Sim, sim, senhor].",
"Ele está certo, senhor.",
"Sim, eu sei que ele está certo, mas, quando ele pesquisou no livro...",
"Com licença senhor. Você deve se reportar ao QG Naval para novos pedidos.",
"Obrigado, Sr. Isso será tudo.",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
};
