string DLG_TEXT[194] = {
"Olá Hornblower. Está tudo bem com você, eu confio?",
"Sim, obrigado, Tenente.",
"Sou o segundo-tenente William Bush apresentando-se ao serviço. Onde posso encontrar o Capitão?",
"Ele ainda não está a bordo, Tenente. Sou o terceiro-tenente Horatio Hornblower. Talvez você queira guardar seu material enquanto esperamos por ele? Preciso chegar ao convés das rodas.",
"Prazer em conhecê-lo, Sr. Hornblower. Sim, farei isso.",
"Podemos conversar mais tarde, senhor.",
"Ah! Obrigado, Tenente. Sim senhor.",
".",
"...",
"Há mais deles chegando. Vá para o convés da roda ",
", Pegue o volante. Precisamos ter certeza de que temos o navio. Archie, verifique abaixo. Os homens de Sharpe devem estar lá embaixo. E encontre o Tenente Buckland e o Capitão Sawyer.",
"Capitão Hornblower! Pensei que eras tu.",
"Senhor Bush! Mas não sou mais capitão, não tenho navio... nem dragonas, então também sou tenente. Enfim, o que você está fazendo aqui?",
"Venho aqui todo mês para receber minha metade do salário e fico onde é barato.",
"Sim, tenente.",
"Bem, venha e fique em meus alojamentos. Garanto que lá é barato.",
"Não me importo de pagar adiantado, senhora.",
"Você tem um admirador. A filha da sua senhoria. Eu vi o jeito que ela olhou para você",
"MARIA? Não! Não não não. Absurdo.",
"Veremos Horácio. Vamos ver.",
"Venha comigo. Vou te mostrar como complemento meu escasso salário na casa do boticário.",
"Do boticário? Você entrou em medicina?",
"Não. O boticário apenas nos deixa usar o quarto. Há um jogo de cartas particular lá à noite, e eu me saio muito bem nisso. Me siga.",
"O que você acha que ele quer?",
"Bem... duvido que ele queira jogar whist.",
".",
"Não parece que precisaremos explodir a porta.",
"O que você quer dizer com Sr. Bush?",
"Dê uma olhada ",
". Se não me engano, o comandante do forte acaba de se render.",
"Isso é muito estranho. Muito estranho, de fato. Precisamos ver o que está acontecendo aqui.",
"Algo não está certo aqui ",
". Os espanhóis renderam-se com demasiada facilidade. Espere aqui enquanto o Sr. Kennedy e eu damos uma olhada.",
"Sim, sim, Sr. Bush.",
"Estamos todos prontos então? Todos os fusíveis ajustados?",
"Então vamos tirar as chamas daqui. Atravesse a ponte o mais rápido que puder.",
"Preparem-se, senhores. A qualquer momento.",
"Bem feito! Muito bem, senhores. Acho que podemos considerar essa missão cumprida.",
"Acho que sim, Sr. Bush.",
"É hora de voltar para o navio, senhores.",
"Sr. Kennedy e eu terminamos aqui. Se você estiver pronto, podemos sair e acender os fusíveis.",
"Eu levei um corte feio na barriga, infelizmente ",
"Precisamos levá-lo para a enfermaria.",
"Tenente Bush, suba a bordo, senhor.",
"Cheguei apenas alguns minutos antes de você, senhor. Queria me apresentar pessoalmente. E posso dizer, senhor, que honra é servir sob o comando de um capitão com um histórico tão distinto.",
"Do que vocês dois estão falando?",
"Er... o tempo, Sr. Bush. Parece que está explodindo um pouco.",
"Sim, está explodindo agora. Teremos que tirar alguma vela dela.",
"Sim, sim, Sr. Bush.",
"Precisamos recifar a gávea.",
"O capitão deve ser informado primeiro, senhor. Ordens Permanentes.",
"Muito bem. Sr. Kennedy, por favor",
"Cavalheiros. Somos obrigados a atender o Capitão em sua cabine.",
"Senhor.. Acredito que o Sr. Hornblower estava apenas fazendo uma observação.",
"Senhores... prestem atenção às suas palavras. O que você está sugerindo aqui é um motim! E não preciso lembrá-lo da pena por essa ofensa.",
"Mas a opção, Sr. Bush, é arriscar o navio e a tripulação diante do inimigo.",
"Pode ser que seja assim, Sr. Hornblower, mas como o Sr. Buckland apontou, cabe ao Doutor Clive decidir.",
"Parece que não estamos sozinhos, senhores!",
"Eles devem fazer parte do exército rebelde de que Buckland estava falando.",
"É o que pode acontecer, Sr. Hornblower, mas eles não vão nos deixar passar, e há muitos deles para nós enfrentarmos. O que você sugere que façamos?",
"Muito simples, Sr. Bush... Archie... Dispare aquele canhão, por favor.",
"Horácio muito engenhoso. Muito engenhoso. Mas como você sabia que o canhão estaria carregado?",
"Eu não... Parecia lógico que os espanhóis não tivessem um canhão tripulado aqui para proteger a ponte, se não estivesse carregado.",
"Hmmm. Sua lógica, ou talvez sorte, nunca deixa de me surpreender, Horácio. Mas voltando a assuntos mais urgentes. Todos os fusíveis estão ajustados?",
"O que o almirante queria?",
"Um Comandante... do 'Hotspur'.",
"Parabéns Horatio, er, senhor. Ele não poderia ter escolhido um homem melhor.",
"Obrigado, mas ela dificilmente é o 'Renome'.",
"Mas ela é um ótimo navio, senhor.",
"Você acha?",
"Acho que sim.",
"Você também acha, Sr. Bush, que um tenente que serviu em um setenta e quatro ficaria feliz em servir como tenente em um mero saveiro?",
"Se você fosse capitão, senhor, acredito que ele o faria.",
"Então você me daria a honra de ser meu primeiro-tenente?",
"Sou eu quem ficaria honrado, senhor.",
"Tive medo que você não quisesse.",
"Tive medo que você não perguntasse",
"Bem, temos um navio para equipar.",
"Aye Aye capitão.",
"Primeiro precisamos ir à taverna para contratar uma tripulação.",
"Sempre podemos encontrar um lugar para Matthews, senhor.",
"Você quer aumentar nossos problemas, não é, Styles? [Senhor?] Styles, você nunca deixa de me surpreender. [Obrigado, senhor].",
"Experiência?",
"O que o traz ao porto?",
"Assine aqui, Wolfe.",
"Bem, isso enche a tripulação, senhor. Suponho que deveríamos voltar para a casa da Sra. Mason e arrumar nossos baús?",
"Sim, você está certo, William. Vamos seguir em frente, ou não dormiremos esta noite.",
"Capitão, terminei de fazer as malas e com sua permissão, senhor. Gostaria de dormir a bordo do 'Hotspur' esta noite para preparar a tripulação para a manhã.",
"Muito bem, Sr. Bush. Permissão concedida, vejo você a bordo pela manhã.",
"Sim senhor. Vou te desejar boa noite então.",
"Boa noite, Sr. Bush.",
"Sobre o que era tudo isso?",
"Não sei, William, mas me sinto desconfortável com isso e não sei por quê.",
"O que não entendo é por que ele lhe pediria um contramestre, quando poderia ir à taverna local e muito provavelmente encontrar um lá?",
"Vamos deixar de assunto por enquanto, William. Quelp e eu voltamos há um tempo e nunca foi bom. Preciso de tempo para pensar. Vamos seguir em frente e encontrar o 95º.",
"Sim capitão. Desculpe senhor. Poderíamos tentar a taverna. O Sr. Chadd está cuidando do navio, então dei licença para parte da tripulação em terra. Eles provavelmente já estão lá e podem ter ouvido alguma coisa.",
"Sim, vamos fazer isso.",
"Você acha que é sensato se juntar a um bando de guerrilheiros, senhor?",
"Temos ordens para encontrar o Major Hogan e é a nossa única opção neste momento. Vamos, William, precisamos dormir um pouco. Vou conseguir um quarto com o dono do bar.",
"Bom Dia senhor. O navio e a tripulação estão prontos e os fuzileiros estão a bordo.",
"Muito bem, Sr. Bush. Vamos ver se nossos companheiros 'guerrilheiros' estão prontos.",
"Suas ordens, capitão?",
"Leve o 'Hotspur' para o mar. Não quero que ela seja pega aqui na baía. Fique fora da vista de terra por um dia e depois aproxime-se. A essa altura já deveremos estar de volta aqui no navio do Commadante. Se não estivermos aqui, você deverá pegar o 'Hotspur' e apresentar-se ao Almirante Pellew.",
"Obrigado, Sr. Bush. ",
"E lembre-se, não envolva os franceses. Ainda estamos em paz, pelo que sabemos.",
"Graças a Deus você está de volta, senhor. Estávamos começando a nos preocupar, os fuzileiros estão a bordo, mas há muitos navios franceses por perto. Precisamos embarcar imediatamente.",
"Acalme-se, Sr. Bush. Você se encontrou com o navio do Commadante Moreno?",
"Sim senhor. É por isso que tomei a liberdade de trazer o 'Hotspur' para a costa.",
"Bom. Precisamos chegar a #sGreenford# e ao Almirante Pellew o mais rápido possível. Embarque e levante a âncora, Sr. Bush. Contarei tudo a você no caminho.",
"O almirante obviamente leu o seu relatório, senhor.",
"Sim, Sr. Bush. Eu me pergunto o que ele achou disso.",
"Ele valoriza a sua opinião, senhor. Sem dúvida ele quer discutir seus planos futuros com você.",
"Veremos, Sr. Bush. Vamos ver. Certifique-se de que a nave seja reabastecida enquanto eu estiver fora. Tenho a sensação de que não ficaremos aqui por muito tempo.",
"Capitão, o navio está abastecido e pronto para o mar, e Wolfe foi libertado do Sophie, então ele está de volta conosco.",
"Obrigado, Sr. Bush. Wolfe, suba a bordo. Para o mar, Sr. Bush. Devemos navegar até Anse Casse Bois em #sisland_Guadeloupe#, depois cruzar a ilha, até o chamado farol, e destruir o semáforo.",
"Parece mais assim, Capitão.",
"É maior que isso. O Capitão Hammond deve atacar e destruir a bateria do forte, para que o Almirante Pellew possa navegar e destruir a frota francesa.",
"Isso impedirá os franceses de prosseguirem com os seus planos de invasão.",
"Exatamente, Sr. Bush. Exatamente. Agora vamos ao navio, espera-se que o 'Hotspur' se dê bem nesta empreitada.",
"Olhe senhor, lá estão o Capitão Hammond e o Tenente Quelp. Talvez se nos apressarmos possamos compartilhar um barco com eles de volta ao navio?",
"Não tenha pressa, Sr. Bush. Nosso barco também está lá. Vejo que Wolfe também está no cais. Eu me pergunto por que ele simplesmente não entra em nosso barco? Talvez ele esteja esperando por nós. De qualquer forma, vamos para o mar, Sr. Bush. Temos um semáforo para explodir",
"Tudo pronto para desembarcar, Sr. Bush.",
"Deixe os homens no chão, Matthews. O Almirante tem outros planos para nós.",
"Mas senhor, poderíamos ir e voltar antes mesmo que ele soubesse disso.",
"Você está sugerindo um motim, cara?",
"Não senhor! Eu só desejo...",
"Eu também, Matheus. Apoiaremos a ação. Prepare-se para entrar com o esquadrão. [Sim, sim, senhor.]",
"Sr. Hammond, Sr. Matthews, apresentem-se no tombadilho.",
"Sim, sim, senhor.",
"Temos um sinal para navegar na popa da Nave Capitânia. Estaremos em postos de ação em breve.",
"Eu não gosto muito disso, senhor.",
"Calma Matheus. O Capitão Hammond cuidou das armas.",
"Altere o curso para bombordo!",
"Se o fizermos, encalharemos, senhor.",
"Se não o fizermos, seremos despedaçados! Altere o curso. Vamos correr sob as armas e atacar em terra nos barcos.",
"Sim, sim, senhor! APORTO DURO!",
"Fizemos a nossa parte, senhor. Agora cabe ao Almirante Pellew.",
"Sim, William, e pelo som daquelas armas, ele está fazendo um bom trabalho.",
"O 'Hotspur' levou uma surra, senhor, mas poderíamos voltar ao esquadrão e à luta.",
"Não, William, como você disse, fizemos a nossa parte. Precisamos levar o 'Hotspur' de volta a #sGreenford# para reparos. Vamos esperar o esquadrão lá.",
"Senhor, Wolfe está na prisão.",
"Bom. Esse traidor finalmente receberá a recompensa adequada.",
"E senhor, conheci o Tenente Sharpe. Ele gostaria de participar do interrogatório. Ele te encontrará na prisão.",
"Obrigado, Sr. Bush. Isso será tudo por enquanto.",
"Obrigado por me permitir estar aqui, senhor. E posso ser o primeiro a parabenizar vocês dois e desejar um casamento longo e feliz.",
"Obrigado, Sr. Bush.",
"Parece muito rum, hein, senhor?",
"Eles são aliados de Sua Majestade, Sr. Bush.",
"Aliados, senhor? Pensei que esta parte do mundo pertencesse à Espanha.",
" foi persuadido pela Inglaterra a se revoltar contra a Espanha.",
"Então a nossa carga de armas é para ele?",
"Se ",
" puder conquistar Cuba, a Espanha terá que tirar navios e soldados de Napoleão para preservar suas colônias.",
"Sr. Bush, aqui estão as chaves da minha caixa de despacho contendo as ordens do Almirantado. Se eu não estiver de volta a bordo até meia-noite, você assumirá o comando.",
"Não voltou a bordo, senhor? Mas você disse que eles estavam do nosso lado",
"A guerra gera aliados estranhos, Sr.",
"Prepare os barcos para armazenar o navio, Sr. Bush. Há provisões suficientes chegando a bordo para nos tornar independentes por dois meses. Nossa carga desembarca.",
"Sim, sim, senhor.",
"Ah, e Sr. Bush, há um navio espanhol com 60 canhões chegando aqui antes do amanhecer. Envie seu melhor vigia ao topo daquela colina para nos avisar da aproximação do inimigo.",
"Estação de vigia informa que 'Natividad' foi avistada, senhor.",
"Oh, obrigado, Sr. Bush, apagaremos as luzes.",
"TODAS AS LUZES APAGADAS!",
"Devo parar o carregamento, senhor?",
"Não, ainda temos algumas horas.",
"Não vamos correr para o mar aberto, senhor?",
"Não, permaneceremos ancorados aqui, sob o sotavento deste ponto.",
"Ah, e Sr. Bush, você, o Sr. Gerard e o Sr. Longley me dariam o prazer de sua companhia no jantar esta noite?",
"Obrigado, senhor! Er - esta noite, senhor?",
"Nosso jovem aspirante pode estar arriscando a vida antes do amanhecer, Sr. Bush. Seu estômago pode ficar melhor com uma refeição.",
"Esse é o espanhol para você. Eu estava apostando que eles fariam exatamente isso.",
"Agora, senhores, eis o que pretendo fazer. Senhor Bush, escolha um esquadrão dos melhores nadadores da tripulação e depois entregue-lhes armas.",
"Sr. Bush, poderia remover os oficiais para o '",
" e colocá-los em ferros.",
"Ah, ela é uma beleza, senhor. O comissário calcula que ela vale 120 mil guinéus. Isso dá a todos os homens a bordo '",
" Prêmio em dinheiro de 50 guinéus.",
"O 'Natividad' não é um navio premiado, Sr. Bush.",
"Peço perdão, senhor?",
"Ela será usada pelo nosso aliado, Don Julian.",
"Você está entregando-a, senhor? Mas a sua própria parte valeria 10.000.",
"Não pedi números.",
"Mas senhor, você mesmo disse que Don Julian estava louco. Você pode confiar nele?",
"Fique tranquilo, Sr. Bush. Só eu terei que responder perante o Almirantado por esta decisão.",
"Don Julian está vindo a bordo, senhor.",
"Uma salva de 11 tiros, Sr. Bush",
"Sim, sim, senhor. FOGO!",
"Sr. Bush, estamos voltando para o ",
"O que ela é, Sr. Bush?",
"Lugger espanhol, senhor. Hasteando uma bandeira branca. Isso significará uma negociação.",
"Use uma arma.",
"Traga os prisioneiros aqui.",
"Senhor Bush, peço-lhe que lembre a todos que este ainda é um navio de guerra!",
"Sinal da capitânia, senhor. Todos os capitães sobem a bordo.",
"Oh, muito bem, Sr. Bush. Reconheça e desobstrua o caminho para o bote.",
"RECONHEÇA! LIMPE O CAMINHO PARA O BOTE DO CAPITãO!",
};
