string DLG_TEXT[46] = {
"Que bom ver você, Comandante.",
"Que bom ver você também, major.",
"Ah! Richard, meu filho, e Teresa. E quem é esse com você?",
"Comandante Hornblower, Major, com uma missiva de Sir Arthur Wellesley e Almirante Pellew. Acredito que isso confirmará minhas credenciais.",
"Credenciais é isso? Estar na companhia de Richard e Teresa são credenciais suficientes para mim, Comandante. Mas é melhor eu lê-los de qualquer maneira.",
"Aqui está você, major.",
"Hmmm, Sir Arthur ainda é a mesma velha raposa. Ele sempre manteve um olhar atento sobre seus amigos. Especialmente se ele pensasse que eles poderiam se tornar seus inimigos.",
"Principal?",
"Não se preocupe, Comandante. Acontece que eu mesmo tenho estado de olho em nossos aliados recentes. Anotei tudo, número de tropas, navios e armamento. Está tudo aqui, leve isso para Sir Arthur e o Almirante.",
"Major, pelos movimentos de tropas que tenho visto, no pouco tempo que estou aqui, parece que os franceses estão a formar uma força de invasão.",
"Força de invasão é isso? Agora, isso é apenas metade da resposta. O importante é: onde eles pretendem invadir? E isso está no meu relatório.",
"Eu vejo.",
"Você precisará ver muito bem no dia seguinte ou depois. Você precisará sair desta ilha e receber este relatório rapidamente.",
"Sim, major. Acredito que meu negócio aqui está encerrado.",
"Ah! a relíquia sagrada sem dúvida, Teresa. Eu estava esquecendo que estava aqui. Comandante, você precisará ajudar Teresa a coletar isso antes de partir.",
"Mas os seus despachos, major?",
"Eles vão durar um pouco mais. A relíquia também é importante. De qualquer forma, algumas horas na igreja provavelmente lhe farão bem, Comandante, mas você não pode ir vestido assim.",
"Temos roupas civis para mim e para o Sr. Sharpe, major.",
"Bom. Bom. Você pode se trocar no quarto ali. Mas Richard não irá com você.",
"Ricardo. Seu antigo comandante, Major Dunnitt, e sua tropa estão acampados atrás da casa. O tolo pensa que vai defender este lugar contra os franceses. Preciso que você tire o máximo de homens possível antes que isso aconteça.",
"Mas isso significa que você deve vir conosco, Major.",
"Descanse em paz Comandante. Sou aceito aqui como morador local. Por mais ocupados que estejam, os franceses vão querer que ele saia daqui muito em breve. Eles virão em meu 'resgate' em breve.",
"Mas Major... Dunnitt e seus homens serão mortos.",
"Dunnitt não recebeu ordem de vir aqui. Ele ouviu uma conversa em algum lugar que eu estava aqui e decidiu vir aqui e obter alguma glória rápida para si mesmo.",
"Mas os seus homens, senhor?",
"Dunnitt terá matado eles ao tentar tirá-los de volta da ilha, se não daqui. Esperançosamente, Sharpe conseguirá tirar alguns deles antes que isso aconteça.",
"A névoa da guerra.",
"A névoa da guerra é Comandante. Richard, quando o comandante mudar, reporte-se a Dunnitt. ",
"Eu poderia levar dois dos homens comigo para a igreja. Mas ainda acho que você deveria vir conosco, Major.",
"Não se preocupe, comandante, estou bem protegido. Os 'escravos' que você vê por aí são na verdade soldados do Regimento das Índias Ocidentais e eles conhecem esta ilha de trás para frente. Iremos fundir-nos com a paisagem antes da chegada dos franceses. ",
"Bom. Isso basta por enquanto, eu acho. Eu vou trocar de roupa.",
"O terno masculino de Teresa fica bem em você, Hornblower. Agora, vão para Dunnitt. Saindo de casa, vire à direita e passe pela passarela. Sharpe saberá o que fazer a partir daí.",
"Sim, major.",
"Seus homens estão prontos, comandante. Boa sorte.",
"Obrigado major.",
"Bem-vindo de volta, Comandante.",
"Bom dia, Major. Vejo que sua capa aqui ainda está boa.",
"Sim, ainda estou aqui. Agradeci ao comandante do forte por defender heroicamente a minha plantação contra os ataques britânicos e, como essa é a única honra que ele está recebendo de todo o caso, ele não questionou muito. Agora, o que posso fazer por você?",
"O aspirante Wolfe revelou-se um traidor e estou à procura dele. Ele foi visto pela última vez fugindo de uma batalha na praia com uniforme francês.",
"A praia, não é? Um dos meus homens viu um oficial francês, ou o que parecia ser um, fugindo pela selva naquele dia, então o seguiu. O referido oficial chegou ao porto, embarcou em uma chalupa chamada 'Loup-Garou' e começou a gritar ordens. Meu rapaz não conseguiu entender muito, mas ouviu '#sisland_Falaise de Fleur#', então acho que foi para lá que seu homem foi.",
"Obrigado, major. Vou ver se encontro aquele saveiro em algum lugar perto de #sisland_Falaise de Fleur#.",
"",
"",
"",
"",
"",
};
