string DLG_TEXT[40] = {
"Quem é você, garoto? E o que você quer comigo?",
"Eu sou aspirante ",
"Bem, aspirante, você deve estar ciente de que não perco meu tempo com patentes juniores. Vá levar seu problema a um dos meus oficiais.",
"Desculpe tê-lo incomodado, Major.",
"O que você quer, Tenente? .",
"Oh! Peço desculpas major. Pensei que você fosse outra pessoa. Eu lhe desejo um bom dia.",
"Será que você viu o Tenente Sharpe Major? Ele é do 95º, eu acredito.",
"Isso pulou rag-a-muffin. Ele não é um oficial adequado, você sabe. Não é um oficial adequado.",
"Na verdade, senhor! Ouvi dizer que o próprio Wellesley o promoveu.",
"Wellesley! Pah! Há dúvidas de que ele próprio saiba dirigir um exército de maneira adequada.",
"Parece que essa discussão não leva a lugar nenhum, Major. Eu lhe desejo um bom dia.",
"Posso servir, Comandante? O 95º está sempre pronto para auxiliar a Marinha de Sua Majestade.",
"Obrigado Major Dunnitt.",
"Sim comandante. Major Dunnitt, Comandante do Segundo Batalhão, 95º Rifles, ao seu serviço.",
"Fico feliz em conhecê-lo, Major, mas tenho alguns assuntos urgentes para resolver, então lhe desejo um bom dia.",
"Irei preparar a tropa para o embarque, Capitão.",
"Muito bem major. Irei procurar o Tenente Bush.",
"Obrigado senhor. Tenho aqui ordens do Almirante Pellew e do Coronel Wellesley para sua atenção.",
"Sharpe? O sujeito que Wellesley levantou na hierarquia? Voce quer ele?",
"Sim, major. Ele é vital para minha missão.",
"Se você diz. Leve-o e vá. Ele e sua tropa estarão lá fora.",
"Tenente! Dispense os homens, eles precisarão descansar antes da batalha de amanhã.",
"...",
"Você não, Sharpe! Leve seus homens e veja como será o terreno amanhã. ",
"Temos padrões aqui. Um oficial deve comportar-se como um cavalheiro. Mesmo que ele não seja um cavalheiro.",
"?",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
};
