string DLG_TEXT[60] = {
"Anime-se Horácio. Você terá outro navio em breve.",
"Espero que sim, Maria. Eu espero que sim.",
"Eu sou Maria. A mãe foi dormir.",
"Ah! Sou Horatio, Horatio Hornblower, falecido na Marinha de Sua Majestade.",
"Você não está feliz por ter sido desativado, está?",
"Não saberei o que fazer comigo mesmo. Só conheço uma vida no mar.",
"Não se preocupe, farei companhia a você e você pode usar o velho tartane do meu pai, está atracado no porto. Ele costumava usá-lo para pescar quando estava em casa. Mas não é bom para o mar aberto.",
"Obrigado. Eu poderia fazer isso. Vou ter muito tempo disponível.",
"Um centavo pelo seu pensamento Horácio.",
"Oh! ... Olá Maria. Eu só queria que a frota chegasse e eu pudesse conseguir uma posição em um navio novamente.",
"Horácio! Quer dizer que você já está cansado da minha companhia?",
"Não! Não! Maria. Só que estou aqui há três meses e estou muito atrasado com o aluguel. Preciso de um emprego para ganhar algum dinheiro.",
"Eu estava apenas brincando com Horatio. E não se preocupe, paguei o aluguel desta semana para você. Mamãe não estará atrás de você por enquanto. A propósito, notei que você penhorou sua espada. Você não conseguirá uma posição sem ele. Aqui está você, pegue isso.",
"Maria... Você é uma boa amiga.",
"Espero ser mais do que isso Horácio.",
"Maria... Er...",
"De qualquer forma, tenho algumas novidades que devem animá-lo.",
"Realmente? E o que poderia ser isso?",
"Há alguns soldados na cidade que dizem que serviram com você. Riflers, acho que eles disseram. Eu disse a eles que iria encontrar você. Eles estão na taberna.",
"Fuzileiros! Maria. E obrigado, eu gostaria de vê-los novamente. Por favor, com licença, irei para a taverna agora.",
"Er! Desculpe mãe, esqueci. O Sr. Hornblower deu-me meia coroa esta manhã. Está no meu quarto.",
"Ela não quer ser tão dura com você.",
"Acho que ela gosta de Maria, e com razão. Não sou um bom inquilino, de forma alguma.",
"Eu acho que você é um verdadeiro cavalheiro, Horatio.",
"Preciso ir para a cidade agora, Maria. Acho que tenho uma maneira de conseguir algum dinheiro para o aluguel. Eu te vejo mais tarde.",
"Sr. Hornblower. Você não vai nos deixar, senhor, certo? A língua da minha mãe às vezes foge com ela... ",
"Recebi o comando de um navio. Eu navego amanhã.",
"Então deixe-me fazer as malas para você, senhor.",
"Isso é muito gentil, mas eu já fiz isso.",
"Mas nunca mais o verei, senhor.",
"Sinto muito, mas tenho o meu dever.",
"Sr. Hornblower, senhor. Estou envergonhado, senhor, por nos ver assim. Aconteceu tão rapidamente. Eu não sabia que estávamos em atraso, e os oficiais de justiça não ouviram e agora não podemos obter a nossa libertação.",
"Você foi minha amiga em um momento de necessidade, Maria, permita-me ser sua.",
"Não, senhor, você não deve.",
"Já é tarde Maria. Está feito.",
"Obrigado senhor. Eu não sei o que dizer.",
"Não diga nada Maria. Basta ir e pagar suas dívidas. Devo voltar para o mar agora, mas voltarei novamente.",
"Sr. Hornblower, senhor. Eu vi o Hotspur, senhor, no porto. Eu esperava que isso pudesse sinalizar seu retorno.",
"Deve ser bom para você estar em casa novamente.",
"...",
"Isso é. Obrigado, senhor, e também é bom vê-lo. Entre.",
"Você.. er.. tem o suficiente para o aluguel?",
"Espero conseguir um cargo de governanta e não posso ser um fardo para sua caridade.",
"Você não é um fardo, eu lhe garanto.",
"Não, Sr. Hornblower, não posso. Existe uma palavra para uma mulher que aceita dinheiro de um homem.",
"Sim, e essa palavra é amigo.",
"Eu valorizo sua amizade. Mas não posso ficar com o seu dinheiro e a minha reputação.",
"Minhas desculpas... claro... eu deveria ter...",
"Maria, por favor, não chore. Se eu perguntasse, Maria... você faria.",
"Será que eu...?",
"Você quer se casar comigo?",
"Ó Horácio!",
"Horrível! Estou tão feliz que você está de volta e seguro! Espero que você fique muito tempo.",
"(Pensa: 'Horry'? <estremecimento>) Estou feliz por estar de volta com você também, Maria. Mas receio que os meus deveres no mar não me permitam ficar muito tempo.",
"Olá, querido! Estou tão feliz que você veio. Parece que faz uma eternidade desde a última vez que te vi!",
"Me conta, ",
", o que está acontecendo por aqui?",
"((( ",
" diz que nada de muito importante aconteceu. )))",
"...",
};
