string DLG_TEXT[65] = {
"Alguma ordem, Sr. Hornblower?",
"No momento não, Matthews.",
"Senhor. ",
", Senhor. Há dois navios lutando lá fora. Parece o senhor 'Indy' e um espanhol.",
"Sim, Sr. Matthews, eu os vejo. Obrigado.",
", Senhor. O caminho para o forte é aqui. Mas se o Sr. Buckland não levar o 'Renome' para o mar em breve, temo que os espanhóis o vejam.",
"Você está certo, Matthews, e perderemos o elemento surpresa. Vamos andando então. Vamos lá, homens.",
", Senhor. Notícias terríveis. Os espanhóis conquistaram o 'renome'. Eles tinham outras tropas escondidas na passagem e depois que o Sr. Buckland embarcou, eles remaram e abordaram ela. Ainda estávamos descendo a praia, então era tarde demais para interceptá-los.",
"Então é melhor fazermos algo a respeito, Sr. Matthews. Eles abandonaram um barco, então saltem para ele, homens. Vamos recuperar o renome.",
"Estamos um pouco confusos aqui, senhor. Os soldados estavam tentando usar este velho canhão aqui, mas não conseguiram carregá-lo rápido o suficiente.",
"Mas seus homens podem carregar muito rápido!",
"Sim, senhor, podemos e temos. Está carregado agora. Só precisamos esperar pela próxima saraivada e, enquanto eles estiverem cegos pela fumaça, poderemos atirar e recarregar. Eles estão recarregando seus canhões agora, então estamos bastante seguros no momento.",
"Bom. Muito bem, Matheus. Eu vou disparar, você e os outros se preparem para recarregar.",
"Sim, senhor. Apenas espere pelo próximo voleio. Serão três tiros. Então você pode correr e atirar. Os mosquetes deles não nos atingem muito bem de onde estão, mas há sempre o risco de um tiro de sorte, senhor.",
"Bom, é isso que faremos então. Espere pelo próximo voleio.",
"Quando estiver pronto, senhor, vá até o final e espere os três canhões franceses dispararem, então dê um passo à frente para disparar o nosso.",
"Muito bem, Matthews, esteja pronto para recarregar. Quero dar um segundo tiro o mais rápido que pudermos.",
"Vamos, Oldroyd, Styles! Coloque suas costas nisso! ... Nós os mandamos vencer, Senhor! Você está carregado e eles ainda não estão prontos",
"Bom trabalho, homens!",
"Dispare quando estiver pronto, senhor!",
"Certo! Todos claros!",
"Um sucesso, senhor! Um acerto! Eles estão quebrando a linha. Venha dar uma olhada, senhor! Mas tome cuidado para não passar por mim.",
"Não vamos nos precipitar muito, Sr. Matthews. Recarregue.... Apenas por precaução.",
"Olha senhor! Harper e Tongue avançaram em direção às armas, e o Sr. Sharpe e os outros estão por perto.",
"E o oficial francês transformou os seus homens. Eles estão voltando.",
"Devemos cobrar do senhor francês? Para ajudar Harper e Tongue?",
"Não, Matthews, Sharpe e Harper sabem o que estão fazendo. Teremos apenas que observar a situação por um minuto.",
"Os franceses quebraram novamente, senhor!",
"Sim.... Eles não sabiam de onde vieram aqueles tiros.",
"Senhor?",
"Eles sabem que poderíamos acertar um deles com um tiro de sorte daqui, mas dois tiros, duas mortes, eles sabem que devemos estar perto deles.",
"E agora, senhor?",
"Mantenha a arma em punho, apenas por precaução. Fora isso, consolide sua posição aqui. Os franceses estarão traçando um plano, disso você pode ter certeza.",
"Sim, sim, senhor. Você seguirá em frente sozinho, senhor?",
"Não, Matthews, preciso ir descobrir onde estão os reforços. Irei ver o Coronel no QG Naval. Voltarei assim que puder.",
"Eu não acho que você precisará disso, senhor. O Coronel acaba de chegar aqui.",
"O que?",
"Isso muda nossas ordens, senhor?",
"Não, Matheus. Mantenha a posição aqui como eu disse e veja se consegue apagar alguns desses incêndios. Vou ver o que Sharpe e o Tenente Quelp estão tramando. Eles alcançaram a posição da arma francesa.",
"Sr. Hornblower, senhor, conseguimos recuperar dois canhões franceses e os colocamos em posição defensiva. Mas não temos homens suficientes para tripulá-los, senhor. Talvez os soldados pudessem ajudar. Mesmo assim, talvez só tenhamos tempo para disparar cada um uma vez.",
"Boa ideia, Matheus. É melhor que nada. Você concorda, Milorde?",
"Você não vai gostar disso, Sr. Hornblower, mas os franceses trouxeram mais canhões.",
"Oh! Não! Então foi ISSO que eles esconderam no vale. Isso vai ser mais difícil do que eu pensava... Não atire até vermos o que eles estão fazendo.",
"Parece que eles pegaram um dos nossos e nós pegamos um deles. Suas armas estão acabadas. Eles não vão atirar novamente. Deveríamos ser capazes de disparar mais uma saraivada. Desta vez, porém, nas tropas.",
"Nosso terceiro canhão parece estar recarregando, mas a infantaria francesa parece estar prestes a avançar. Preparem-se, pessoal. É isso!",
"Temos uma das armas deles, Sr. Hornblower. Isso os fará pensar por um momento, pelo menos.",
"Isso pode significar que eles começarão seu avanço. Embora eu achasse que eles iriam tentar nos derrubar um pouco mais primeiro. Eles estão recarregando.",
"Capitão Hornblower, senhor! Que bom ver você de volta ao comando.",
"...",
"O grupo de desembarque está pronto, capitão.",
"Sr. Você ficará no barco com os fuzileiros navais, assim que desembarcarmos, para cobrir nossa retirada. Agora precisamos de um voluntário para carregar os explosivos.",
"Esperaremos aqui por você, senhor.",
"Muito bem, Matheus. Esteja preparado, estabeleça uma linha defensiva com os fuzileiros navais. Tenho certeza de que os franceses não estarão muito atrás de nós quando ouvirem o estrondo.",
"Você pode confiar em nós, capitão.",
"Eu sei que posso, Matthews. Bem, é melhor irmos para o farol.",
"Onde está o capitão, senhor?",
"Eles.. Eles foram cortados.",
"Dê-me seis homens. Diga-lhes para consertarem as baionetas.",
"Há uma companhia de soldados indo para lá e mais a caminho.",
"Devemos fazer o que pudermos, senhor.",
"Oh não! Devemos nos retirar. Se permanecermos nesta praia, seremos abatidos onde estamos.",
"Não podemos partir sem o Capitão, senhor.",
"Pelo amor de Deus, Matthews, o capitão foi isolado. Coloque os homens no barco.",
"Não sem uma ordem, senhor.",
"Essas são as ordens dele. Maldito!",
};
