string DLG_TEXT[49] = {
"Você está com o dinheiro do meu aluguel, Sr. Hornblower?",
"Devo recebê-lo em breve, Sra. Mason.",
"Você precisará de um lugar para ficar, senhor? ",
"Er,... Sim, parece que sim.",
"Cobro menos do que o Almirantado recomenda, café da manhã e jantar, e lençóis limpos uma vez por semana.",
"Oh! ... Er... Sim, parece que atenderia às minhas necessidades.",
"Você não encontrará nenhum outro lugar tão barato, e minha comida também não é para ser desprezada.",
"Oh! ... Er... Sim, obrigado. Cadê?",
"O nome é Mason. Sra. Mason, embora o Sr. Mason tenha falecido há alguns anos... Siga-me.",
"Oh! ... Er... Hornblower... Horatio Hornblower. Sim Sim claro. Er... Sra. Mason.",
"Esta é minha filha, Maria. Tenho coisas para fazer, então vou deixar vocês se apresentarem.",
"Oh! ... Er... Sim, obrigado Sra. Mason.",
"Oh! é você.",
"Tenente Bush, Sra. Mason, a senhora da Câmara. O senhor Bush será meu convidado esta noite.",
"Você é muito generoso com sua hospitalidade, Sr. Hornblower, para alguém cujo aluguel está atrasado.",
"Será um xelim pela cama. Não posso lavar os lençóis por menos do que isso, não com sabão como está. E isso só deixa os QUINZE que o Sr. Hornblower nos deve.",
"Se você passasse menos tempo sonhando acordado. Você é exatamente como seu pai, cabeça nas nuvens e veja onde isso o levou. Quero o saldo até o final da semana. Por aqui.",
"Estarei de pé agora.",
"Bem bem. Se não for o grande capitão do mar. Venha zombar do nosso infortúnio.",
"Senhora!",
"Você não está morto então senhor?",
"Parece que não, senhora.",
"Ela chorou quando você se foi, senhor, minha Maria. Eu odiaria pensar o quanto ela choraria se você não voltasse.",
"Ela chorou.",
"Ela chorou por você, senhor. Embora por que ela se incomodou, eu não sei",
"Terei que fazer alguns preparativos para um casamento, então. Quem devo convidar como seu padrinho?",
"Se estiver tudo bem para você, gostaria que o tenente William Bush fizesse as honras.",
"O oficial que você convidou para ficar aqui? Ele parece legal o suficiente. E agora é melhor você dormir um pouco, você tem um dia agitado pela frente! Nos vemos na igreja amanhã",
"Boa noite, Sra. Mason.",
"Bem, não foi legal? E agora estou exausto. Você nos levaria para casa?",
"Certamente, Sra. Mason.",
"Agora que somos uma família, você não precisa ser tão formal. Você pode me chamar de Ellen.",
"Muito bem, Ellen. E eu sou Horácio.",
"Ei você! Você não, Horatio - VOCÊ, a pessoa do outro lado da tela! Dê um pouco de paz a um casal recém-casado, sim? Você os verá novamente amanhã.",
"...",
"Oh senhor, finalmente é você!",
"Sra. Onde está minha esposa?",
"Se ao menos você pudesse ter voltado para casa mais cedo, capitão, para chegar aqui a tempo.",
"O que aconteceu?",
"Ela está morta, senhor! Morreu no parto, dando-lhe um filho. Ela queria tanto viver, senhor. Pelo menos até você voltar.\nEla deixou isto para você, senhor. Foi no leito de morte que ela escreveu.",
"Onde está a criança?",
"Lá em cima, senhor. Ele é um rapaz forte, com uma voz vigorosa quando está acordado.",
"Ótimo garoto.",
"Vou deixar você ler a carta de Maria agora, senhor.",
"Você não deveria estar no escuro assim, senhor. E estou começando a achar que você não gosta tanto da minha comida quanto da comida do navio. Você não fez mais do que mordiscar. Isso vai te animar. É sobre a senhora que você trouxe com você. Um lindo casamento, deve ter sido. <Dá-lhe um jornal>",
"<Artigo de jornal: 'Ao meio-dia de ontem ocorreu na capela de #sGreenford# um casamento unindo duas das maiores e mais nobres famílias da Inglaterra. Lady Barbara Wellesley, irmã de Sua Graça o Duque de Wellington, uniu-se no Santo Matrimônio ao Contra-Almirante Sir Rodney Leighton, KB, cujos deveres e façanhas a serviço da Marinha de Sua Majestade são amplamente conhecidos nesta terra e nos mares além.'>",
"Por mensageiro especial, senhor. Do QG Naval. <lhe entrega uma carta> Espero que não seja o mar de novo, senhor.",
"<Você leu a carta> Estarei me apresentando ao QG Naval pela manhã.",
"Você teve tão pouco tempo com o rapaz",
};
