string DLG_TEXT[51] = {
"Bom dia Tenente.",
"Bom dia Harper.",
"Haverá apenas um, senhor.",
"Um? Um o que?",
"Corpo, senhor. Haverá apenas um cadáver. Este aqui está simplesmente inconsciente, então ele está.",
"Inconsciente?",
"Sim, senhor. Depois que conversamos, eu bati nele com minha espada. Apagou-se como uma luz. Bastante surpreendente para um homem tão grande.",
"Ele te contou alguma coisa que poderia nos ajudar? Antes de ele ficar inconsciente?",
"Isso ele fez, senhor. Que ele fez.",
"E?",
"Haverá outro túnel ali nos fundos. Isso leva à Academia e ao acampamento pirata. É assim que eles movimentam as mercadorias.",
"?",
"Você estaria olhando para isso agora, Tenente.",
"Olhando para o quê? Tudo o que vejo é mar.",
"Ah! Sua honra! Mas é o que navega naquele mar. A partir daqui, você terá uma bela visão de todos os navios que entram e saem de #sCharlestown#, com certeza.",
"Eu vejo o que você quer dizer.",
"Bem, este é o acampamento dos piratas, com certeza, e se meus olhos não estão me enganando, dois oficiais franceses entraram na casa ali.",
"Oficiais franceses? Aqui? Definitivamente algo está acontecendo. Mas o que? ",
"Talvez descubramos algo mais quando chegarmos à Academia.",
"É hora de sair daqui, eu acho. De volta por onde viemos.",
"Você estará querendo instruções para o túnel, Tenente.",
"Sim, Harper, isso ajudaria.",
"Para a Academia, ele disse apenas seguir pelo túnel. Não desligue em lugar nenhum.",
"E o acampamento pirata?",
"Para o Acampamento Pirata ele disse para ir direto até chegarmos a uma tocha acesa. Vire à direita. Então continue até chegarmos a outra tocha acesa. Depois vire à direita novamente. Então siga em frente.",
"Espero poder lembrar disso. E a entrada do túnel?",
"Isso está atrás da estante no canto, senhor.",
"Muito bem. Vamos indo.",
"Senhores, há um velho mineiro ali. Perguntei-lhe o que ele viu ou ouviu. Ele disse que pensou ter ouvido tiros quando estava no poço e subiu para olhar. Mas quando ele subiu não viu nada. Ele não viu os corpos.",
"Obrigado Harper.",
"Se não se importar com você, Comandante, Cooper e eu preferiríamos voltar para o 95º. Não parece certo estarmos aqui, enquanto o resto dos rapazes está sob ataque.",
"Eu entendo Harper. Vá embora então... e boa sorte.",
"Devo admitir que sinto o mesmo. Eu voltarei com você.",
"Não pretendo apressá-lo, senhor. Mas seríamos mais úteis com os nossos homens agora. Uma companhia de tropas francesas acabou de sair pelos portões da cidade.",
"Claro, Harper. Esperemos que não seja tarde demais. Me siga.",
"Ficarei aqui e vigiarei, senhor. Você sabe, só por precaução.",
"Boa ideia, Harper. Não vamos demorar.",
"Enquanto eu estava aqui, notei muitos navios grandes no porto, e as tropas que vimos também estavam acampadas lá.",
"Tropas no acampamento? Isso confirma a ideia da invasão. Eu me pergunto se deveríamos ir e olhar?",
"Ele está ocupado consertando as fechaduras dos portões da cidade. Isso deve interromper qualquer reforço por um tempo.",
"...",
"Até agora, tudo bem, senhor.",
"Fique atento. Ainda não estamos em casa.",
"Eu esperava pegar você. Você precisa vir ver isso, senhor. Eu e Cooper pegamos o caminho errado, mas você não vai acreditar no que encontramos.",
"Vá em frente então, nós seguiremos.",
"Devíamos ir ver como está o capitão Murray, senhor.",
"Concordo. Precisamos ver se ele pode ser movido.",
"É melhor eu ir em frente e fazer um pouco de reconhecimento, senhores.",
"Boa ideia, Harper. Vamos esperar aqui.",
"Eles estão lá, tudo bem. Mas há todo um esquadrão deles.",
"Mais do que nós três podemos suportar. Devíamos voltar para a clareira. Com alguma sorte os outros fuzileiros estarão lá.",
};
