string DLG_TEXT[350] = {
"Parece um problema.",
"Hmm.. Sim, é verdade, Sr. Sharpe.",
"De onde você veio, Tenente? E quem é você... Senhor?",
"Um túnel, sem tempo para explicar. Sou o Tenente Horatio Hornblower do 'Infatigável'. Quem é você, soldado, e o que está fazendo aqui?",
"Sharpe, Senhor do Segundo Batalhão. Fuzileiro, 33º Regimento de Infantaria... Estou no comando de um destacamento para proteger a nascente e parece que veremos alguma ação em breve.",
"Destacamento? Onde estão seus homens? E seus oficiais?",
"Não há oficiais, senhor. O sargento Wilkins está no comando, mas por enquanto voltou à cidade. Há dois atrás de você, senhor. O resto está no vale atrás de mim. Mais do que suficiente para acabar com estes Franceses, quando aqui chegarem. Eles certamente remam devagar.",
"Do que você está falando cara? Não vejo ninguém.",
"Isso é bom então, senhor. Porque se você pudesse vê-los, então os franceses também poderiam, e então o navio deles se abriria sobre nós, e isso não seria agradável, seria?",
"Desculpe Sharpe, você está certo, é claro. Viemos parar os franceses também. Mas agora você me deu uma ideia melhor",
"Não consigo pensar em uma ideia muito melhor do que derrotar os franceses... senhor. E as minhas ordens são para proteger o abastecimento de água.",
"Acho que minha ideia irá satisfazer a nós dois, Sharpe.",
"Estou ouvindo, Tenente?",
"Se você permitir que a tripulação francesa entre no vale. Depois é só capturá-los, sem atirar.",
"E qual é o objetivo disso, Tenente?",
"Isso dará ao Sr. Hunter tempo para voltar à cidade e trazer a tripulação de volta aqui. Nós nos vestimos como os franceses, navegamos e pegamos o navio também.",
"Uma ideia inteligente, tenente. Eu gosto disso.",
"Lá vai você, Caçador. O mais rápido que puder e sem barulho quando voltar para a praia.",
"Eles estão vindo. Você está pronto?",
"Sim! Vamos.",
"Isso foi tranquilo o suficiente para você, Tenente? Nem um tiro disparado.",
"Eles estão desarmados! Mas obrigado de qualquer maneira, Sharpe, isso foi bastante tranquilo. Você pode mantê-los aqui até que seu alívio chegue?",
"Sim senhor. O Sargento Wilkins deve voltar em breve.",
"Bom. Devo ir ver como capturar um navio.",
"Ele não tinha faca. Quando Harper e eu voltamos para cá, decidimos tentar negociar um pouco com nossos amigos daqui. Descobrimos que eles estavam vendendo lojas do governo, então os desarmamos e estávamos conversando, quando você entrou.",
"Como eu disse, foi tudo muito rápido para eu ver.",
"Precisamos manter este vivo, capitão. Seu outro tenente foi um pouco rápido em me 'proteger' para o meu gosto. Higgins, quando o 'amigo' aqui acordar, leve-o para a prisão e proteja-o você mesmo.",
"...",
"Tenente, estes são desenhos de navios britânicos e, se não me engano, este é do 'Indy'. Agora, o que isso estaria fazendo aqui?",
"Você está certo, Sharpe. E precisamos confirmar que este é o acampamento pirata e, se pudermos, por que eles estariam interessados na 'Indy'.",
"Isso significa passar pela porta ali. Depois de você, tenente.",
"Ah! Sim, suponho que sim.",
"Tenente, temos duas opções agora, a meu ver. Podemos ir e encontrar a entrada da Academia, ou voltar para a Casa do Contrabandista. Quais são as suas ordens, senhor?",
"Acho que deveríamos procurar a entrada da Academia, que nos dará uma visão completa de como os túneis se conectam. Então poderemos relatar tudo o que vimos. Vamos.",
"Precisamos nos reagrupar no vale. Siga-me, Tenente.",
"Estou bem atrás de você, Sharpe.",
"Uma missão bem-sucedida, tenente. Entre nós, capturamos toda a companhia do navio e o próprio navio. Devemos reportar-nos à Academia Naval. Imediatamente, foi a palavra usada, acredito.",
"Essa é a maneira educada de dizer isso de uma vez. Receberemos nossos próximos pedidos por lá.",
"Espero ser transferido de volta para a Europa. Preciso voltar para a guerra real.",
"Veremos muito em breve, sargento. Vamos para a Academia, certo?",
"Acho que deveríamos voltar à Casa do Contrabandista e informar que vimos os franceses aqui. Vamos.",
"É isso, Tenente. Este é o depósito da Academia.",
"Portanto, existe de fato uma ligação entre a Casa do Contrabandista, o Acampamento Pirata e a Academia. Precisamos voltar e relatar, embora eu não esteja ansioso para passar por aqueles túneis novamente.",
"Não há necessidade, senhor. Podemos subir para a Academia e voltar para a casa do outro lado da cidade. Me siga.",
"Isso faz parte do quebra-cabeça feito. Precisamos voltar agora e encontrar a entrada do acampamento pirata.",
"Tenente, acho que já vimos mais do que suficiente por enquanto. Quais são as suas ordens, senhor?",
"Devemos voltar à Casa do Contrabandista e ao Capitão Pellew para fazer nosso relatório. Vamos.",
"Ouvi tudo isso, Tenente, e embora não seja minha função falar sobre o assunto, agradeço o que você está fazendo pelas tropas.",
"Você está correto Sharpe. Não é sua função falar... Mas, obrigado de qualquer maneira. Só espero estar fazendo a coisa certa.",
"Tchau, tchau. Olhei para os mortos. Não há sinal de que o seu Tenente Quelp esteja aqui.",
"Eu não sei o que fazer com ele. Amigo ou inimigo? De qualquer forma, precisamos chegar ao navio, aqueles tambores estão cada vez mais próximos. Encontraremos o 'Indy' assim que estivermos no mar.",
"Que ponte de corda é essa?",
"Está na próxima baía. Leva ao forte, já fomos presos lá uma vez, mas há dois guardas em cada extremidade da ponte.",
"Vamos dar uma olhada então. Quatro guardas não parecem representar um grande problema.",
"Muito bem. Vamos dar uma olhada. Existem dois caminhos até a ponte. Precisamos ir para aquele onde os guardas têm menos chance de nos ver. Me siga.",
"Ah! Eu vejo eles. Eles acham que ainda estamos na outra praia, estou pensando. Isso não deve ser muito difícil... Haggman, Tongue, calmamente agora.",
"Eles têm um canhão do outro lado. Isso não existia antes. O que você pretende fazer?",
"Simples, Haggman e Tongue atiram nos dois do outro lado para evitar que disparem o canhão. Então cuide dos dois deste lado. Vamos sair do caminho deles.",
"OK. Sharpe, estou pronto.",
"Espere, Tenente. Seria melhor se Haggman, Tongue e eu subíssemos primeiro. Você deveria nos seguir.",
"Temos a ponte... Rifles! Garanta a posição, passe pelo outro lado e guarde aquele canhão, caso alguém saia do forte. Tenente, traga o resto da tripulação.",
"Sim, Sharpe... Archie! Matheus! Traga o tripulante, rápido agora!",
"O Coronel está morto e parece que o navio é nosso.",
"CUIDADO, SHARPE!",
"O que....",
"Ele estava tentando matar você. O Tenente Quelp salvou sua vida, Sharpe.",
"Muito obrigado, Sr. Quelp. Muito grato.",
"Qual é a situação, Sr. Quelp? Você sabe?",
"Só não sei o que pensar daquele homem, Tenente.",
"Você está se lembrando do incidente com Larr em #sCharlestown#, presumo.",
"Sim.... Depois pensámos que ele estava a trabalhar para os franceses, e depois ele apareceu numa prisão espanhola, e depois salvou-me a vida.",
"É difícil duvidar de um homem que salvou sua vida, talvez duas vezes, Sharpe.",
"Talvez... Como ele foi parar naquela prisão de novo?",
"Ele disse que os franceses o trocaram por um dos oficiais que os espanhóis mantinham.",
"Hmmm.... E o que disse o Coronel Espanhol?",
"Er... nada na verdade, ele não estava lá no momento em que o Sr. Quelp falou comigo. O Coronel acabou de dizer que era um prisioneiro.",
"Preciso pensar mais sobre isso e tentar esclarecer as coisas em minha mente.",
"E preciso ver a festa do enterro em terra. Coloque guardas em todos os conveses, Sharpe. Voltaremos assim que possível.",
"Esta vai ser uma aventura agradável para mim.",
"O que você quer dizer?",
"Preciso resolver a situação com o Tenente Quelp. Ele é meu principal suspeito. Esse homem simplesmente não se sente bem comigo.",
"Mas ele salvou sua vida!",
"Talvez. Talvez eu esteja errado sobre ele, mas se puder falar diretamente com ele, descobrirei o que preciso saber. Ele não está na cidade agora, então precisamos encontrá-lo, mas não sei para onde ele foi.",
"Você pode não saber onde ele está, mas eu sei quem sabe... Tenente Chadd! Um momento, por favor.",
"Isso foi bastante fácil. #sisland_Cayman# é isso. Reunirei meus homens e então poderemos zarpar.",
"Quem era aquele?",
"Quem foi quem?",
"Aquele aspirante que acabou de sair correndo da sala",
"Não sei. Provavelmente alguém que saiu do navio para tomar uma bebida rápida e não queria ser pego na taverna quando não deveria.",
"Parecia que ele conhecia pelo menos um de nós, e acho que já o vi antes em algum lugar.",
"Bem, ele não era tenente, e é um tenente que procuramos.",
"Eu não tenho certeza. Não parecia certo.",
"Bem, não há oficiais aqui. Vamos voltar para fora.",
"Se nos apressarmos podemos fazer a próxima maré alta.",
"Não demorará muito para estarmos prontos. Viajamos com pouca bagagem.",
"Sharpe... Sargento... Segundo Batalhão, 95º Rifles. Senhor.",
"Bem, bem, bem. Promovido a sargento Eh! Sharpe?",
"Não só isso, Tenente, mas fomos formados em nosso próprio destacamento de rifles por causa de nossa precisão.",
"Sim, percebi como você era bom com aqueles mosquetes.",
"Não usamos mosquetes. Usamos rifles. Meus homens são todos excelentes atiradores, nós os chamamos de Homens Escolhidos. Eles nunca erram.",
"Eu estou corrigido Sargento.",
"Acredito, senhor, que devemos continuar servindo juntos no 'Renome'.",
"Você vai se juntar a ela também?",
"Sim senhor. Estamos prestes a embarcar nela agora.",
"Então nos encontraremos novamente com o Sargento Sharpe. Estarei ansioso por isso.",
"Droga! Eles nos viram! Preparem-se para lutar, rapazes!",
"Eles têm um canhão ali e está apontando para cá.",
"Isso não estava lá da última vez que estive aqui",
"Talvez eles só consigam nos pegar com um tiro de sorte, usando mosquetes, mas podemos começar a abater os artilheiros com nossos rifles, senhor.",
"Boa ideia Sharpe.",
"Certo então... Patrick, você e Tongue vão até a colina lá atrás e vejam o que podem fazer. Seguirei com o resto dos homens em breve.",
"Onde quer que os franceses estejam, eles certamente prenderam nossos meninos nesta área.",
"Você está certo, Sharpe. Olha, está o Matthews ali. Vamos obter um relatório dele sobre a situação.",
"Observe como você vai até lá. Os franceses têm canhão, lembre-se.",
"Eu conheço Sargento. Vamos para Matthews.",
"Aspirante? ... Eu disse que vi um aspirante em #sisland_Cayman#.",
"Sim, Sharpe, você fez. Mas temos assuntos mais urgentes neste momento. O Coronel Wellesley disse-me que os reforços estarão aqui dentro de uma hora, por isso precisamos de ver o que os franceses estão a fazer.",
"Archer e Evans avançaram para explorá-los. Poderíamos segui-los.",
"Sim nós deveríamos. Quanto mais longe os franceses estiverem, menos hipóteses teremos de perder a nossa posição nos arredores da cidade e, nessa altura, os reforços estarão aqui e poderemos contra-atacar.",
"E as armas aqui? Devemos apimentá-los?",
"Não, ainda não. Se formos forçados a retirar-nos, podemos pelo menos virá-los e usá-los contra os franceses. Isso nos dará um pouco de tempo. Vamos conversar com Archer e Evans.",
"Eu não acredito! Olhe para isso! ... Fuzileiros em frente! Retaguarda, vá para a cobertura! Mantenha seus olhos abertos!",
"Eles levaram um tiro nas costas!",
"Então certamente eles estavam fugindo de alguém?",
"Estes são os 'Homens Escolhidos'. Eles sabem que não devem correr juntos! Eles teriam se separado se alguém os estivesse perseguindo! Um deles teria caído para se proteger para responder ao fogo.",
"Todos cometemos erros de vez em quando, Sharpe.",
"Depois explique como eles levaram um tiro nas costas ao mesmo tempo e caíram EXATAMENTE no mesmo lugar, se estivessem correndo?",
"Ah! Você tem razão, Sharpe. Isso é muito improvável. Você tem alguma ideia?",
"Sim... mas você não vai gostar.",
"Prossiga.",
"Eles sabiam quem foi que atirou neles, ou mais provavelmente quem foi que os matou.",
"Como você chega a essa conclusão?",
"Simples... Se Haggman e Tongue disparassem agora, você e o Tenente Quelp cairiam aqui, exatamente onde estão. Porque você está aqui conversando comigo e não em uma briga.",
"Então quem poderia ser? ... Oh não! Não é esse aspirante misterioso de novo?",
"Teria que ser algum tipo de oficial britânico. Quem mais eles veriam como amigo quando eles próprios seguissem os franceses?",
"Estou começando a ter uma sensação desconfortável com tudo isso.",
"Patrick... leve os homens e enterre Archer e Evans. Tenha sempre um homem de guarda... e não confie em ninguém. Vamos dar uma olhada na baía. Siga-nos quando estiver pronto.",
"O que diabos está acontecendo aqui? Eu esperava ter que procurar abrigo assim que chegássemos aqui, e o que encontramos? Nada!",
"Isso também não é o que eu esperava. Vamos ver se Quelp viu alguma coisa.",
"Archer e Evans.",
"O que você quer dizer com Archer e Evans?",
"Estive pensando no que diria se Haggman e Tongue tivessem atirado em você e no Tenente Quelp.",
"Sim... mas o que isso tem a ver com Archer e Evans?",
"Você não teria caído lado a lado. Cada um de vocês teria caído de maneira um pouco diferente. Então...",
"Os corpos de Evans e Archer foram colocados lado a lado...",
"O que significava que eles foram colocados ali assim para nos fazer pensar que eles estavam vindo da praia.",
"O que responde a como chegamos aqui. Então agora o 'porquê' aqui?",
"Eu entendo isso, mas acho que ainda podemos tirar vantagem da situação.",
"O que você quer dizer com Sharpe?",
"Eles certamente deixaram algum tipo de retaguarda no vale lá atrás. Sugiro que não usemos armas, apenas espadas. Dessa forma, o som dos tiros não alertará a força principal de que estamos chegando.",
"Boa ideia, faremos isso. Entrem na briga mais uma vez, senhores. Temos uma cidade para aliviar.",
"Só um minuto, Tenente... Acho que nosso Sr. Quelp está com muita pressa para nos levar à praia",
"Sargento Sharpe! Eu sou o oficial sênior aqui! Você é apenas um sargento e eu digo para irmos à praia. Agora venha.",
"Sharpe! Você suspeita do Tenente Quelp desde o caso Larr. Acho que são uvas verdes porque ele viu uma faca que Larr tinha e que você perdeu.",
"Você viu uma faca então?",
"Bem... Não, mas eu não estava procurando por um. Tínhamos questões mais importantes na época, se você se lembra.",
"Pode ser, mas VOCÊ não viu uma faca. Harper e eu revistamos os dois. Não havia faca.",
"Talvez seja verdade, mas eu vi o Sr. Quelp salvar sua vida a bordo do 'Renome'. Então vamos parar com essas bobagens e ir para a praia. Isso é uma ordem.",
"O que você quer dizer com Sharpe?",
"Então você acha que estaríamos caindo em uma armadilha? É melhor ligarmos de volta ao Sr. Quelp antes que ele entre no assunto.",
"Não, não é uma armadilha. Alguém simplesmente nos quer fora deste vale. Só estou dizendo que não deveríamos ir à praia. Sugiro que encontraremos o que procuramos se formos para o outro vale.",
"Sr. Quelp! Volte aqui. O Sargento Sharpe tem algumas ideias. Precisamos conversar sobre algo.",
"O que diabos você está falando sobre Sharpe?",
"Eu sei que duvidamos dele naquela época, mas o Sr. Quelp salvou sua vida na casa do contrabandista quando Larr tentou esfaqueá-la.",
"Sim, você fez. E o que foi que ele disse? 'Eu libertei nossos oficiais e tripulação do brigue onde estavam detidos.' Se fosse esse o caso, a OMS libertou o Sr. Quelp? E já que estou nisso, por que ele não ficou chocado ao ver os corpos de Archer e Evans?",
"Você tem razão, Sharpe. Mas ele ATIROU no espanhol agora, não foi? Como você explica isso?",
"Talvez o soldado fosse nos contar algo sobre o Sr. Quelp para negociar sua própria vida ou liberdade. Que talvez o Sr. Quelp estivesse com eles na captura do navio. Alguém teve que libertar os prisioneiros em primeiro lugar para que eles tomassem o navio.",
"Isso está ficando muito complicado. Iremos à praia confrontar o Tenente Quelp com estes assuntos e ver o que ele tem a dizer. Venha, vamos.",
"Mas o que isso tem a ver com o Sr. Quelp? Ele esteve conosco o tempo todo.",
"Porque quando ele está por perto a informação sempre fica um pouco distorcida.",
"Você está falando sobre o incidente com Larr e a faca, não é?",
"Talvez seja verdade, mas eu vi o Sr. Quelp salvar sua vida a bordo do 'Renome' quando atirou no soldado espanhol.",
"Isso nos dá outro problema.",
"Os franceses devem ter deixado alguns batedores para trás para poder informar quando fomos à praia.",
"Você quer dizer que estamos sendo vigiados neste exato momento?",
"Sim, mas eles não estarão muito próximos por medo de serem descobertos. Eu tenho um plano, no entanto. Iremos à praia como eles esperam que façamos.",
"Mas é isso que eles querem que façamos. Como isso nos ajudará?",
"Porque quando partirmos, os batedores deles irão se proteger. Já tenho dois fuzileiros atrás de nós, protegidos, para o caso de sermos atacados aqui. Eles cuidarão dos batedores quando eles quebrarem a cobertura.",
"Então podemos voltar e ir para o outro vale, e eles não estarão nos esperando?",
"Exatamente. Devíamos ir em direção à praia agora. Teremos que deixar os enterros para mais tarde.",
"Não teremos que esperar muito",
"Nós apenas esperamos pelo som de tiros então?",
"Não, não haverá nenhum tiroteio. Se pudemos ouvir, os franceses também poderiam. Será um negócio tranquilo. Se houver algum tiroteio, isso significará que algo deu errado.",
"Sharpe... Sargento. 95º Rifles do Segundo Batalhão. Senhor.",
"Isso foi uma coisa difícil.",
"Sim... Sorte que você tinha duas pistolas!",
"Os franceses estavam escondidos na mina. Eu vi a porta se mover e adivinhei o que estava para acontecer.",
"Parece cada vez mais provável que eles estejam atrás de Sir Arthur... Aí vem ele agora.",
"Vai ser uma corrida acirrada, mas me sinto muito mais feliz com três canhões. É uma pena que só possamos demiti-los uma vez.",
"Tudo depende do tempo que temos para recarregar antes que a infantaria francesa nos ataque, mas já estivemos em situações mais difíceis antes de Sharpe... Espere! ... Aí vêm os franceses! Precisamos voltar.",
"Foi por pouco, e temos muitos feridos.",
"Sim, foi. Matthews, você e a tripulação cuidam dos feridos e mandam alguém de volta para ver o que está acontecendo com as tropas na praia. É melhor que o Tenente Sharpe e eu nos apresentemos ao Coronel.",
"Então, se o nosso navio afugentou os franceses, porque é que as nossas tropas não voltaram?",
"Eu estava pensando a mesma coisa.",
"Bem, como oficial comandante por enquanto, farei algumas investigações sérias sobre o assunto. É melhor eu voltar para ver o que está acontecendo. Enviarei seus tripulantes para se reportarem ao seu navio.",
"Obrigado Sharpe. Adeus por enquanto, mas tenho a sensação de que nos encontraremos novamente.",
"Então, por onde começamos a procurar, Sr. Hornblower?",
"A taberna é sempre um bom lugar para começar. Nós iremos lá.",
"Suponho que isso deveria me fazer sentir melhor?",
"Vamos Sharpe! Ele não precisava nos contar tudo isso agora, não é?",
"Não... Mas e o aspirante que vimos. Por que não mencionou isso, se acredita tanto no Tenente Quelp?",
"Porque eu não o vi. Agora vamos, é um longo caminho até #sisland_Antigua#. Precisamos voltar para o navio.",
"Horácio! Bom te ver de novo.",
"E ver você, Richard. O que te traz aqui?",
"Você faz! Lembra que não conseguimos entender por que o resto de nossas tropas não retornou durante a batalha com os franceses?",
"Claro que eu faço. O que aconteceu?",
"Parece que quando o nosso tenente Quelp e a tropa chegaram à praia foram recebidos por alguém que os levou a um ponto onde, disse ele, teriam uma visão melhor do navio francês, caso este regressasse.",
"Mas como isso os impediu de voltar?",
"Porque o local para onde ele os levou era muito longe da praia e fora do alcance da voz do vale.",
"Então eles não ouviram a batalha acontecendo?",
"Foi o que disse o tenente Quelp, e nossas tropas confirmaram que não ouviram nada, mas o interessante é o homem que os conheceu. E lembre-se que as tropas também o viram.",
"Era um aspirante!",
"Um aspirante! Mas quem poderia ser?",
"É isso que vamos descobrir. O tenente Quelp também foi encalhado e estamos de olho nele, porque ainda não tenho certeza sobre ele. De qualquer forma, ele está aqui em #sOxbay#, e sugiro que vamos lá e vejamos o que ele está fazendo.",
"Bem, devo admitir que não tenho mais nada para fazer.",
"Bom! Eu sabia que você estaria disposto a isso. Se Quelp estiver envolvido, mais cedo ou mais tarde ele entrará em contato com o aspirante, e eu quero estar presente. E então o jogo terminará.",
"Bem pensado. Vamos para #sOxbay#.",
"Precisamos ir então, antes que ele fuja novamente.",
"Podemos passar pelo canyon, ou tenho um pequeno barco e podemos navegar até lá.",
"Mas se usarmos um barco ele poderá nos ver chegando à costa.",
"Exceto que este barco é um barco de pesca local, ninguém notará isso.",
"Muito bem, temos uma escolha, Canyon ou Barco.",
"Eles estão todos mortos! E onde está Hunter? ... Patrick, Língua, dê uma olhada ao redor.",
"O que diabos está acontecendo aqui?",
"Isto não faz sentido nenhum e, mais uma vez, se o nosso Sr. Quelp estiver envolvido, as coisas não correm conforme o planeado.",
"Bem, não vamos encontrar nenhuma resposta aqui.",
"Não, e neste momento não temos recursos para prosseguir. Teremos que esperar por tempos melhores. Devo levar meus homens de volta ou estaremos sujeitos à deserção! Ficarei de olho no Sr. Quelp. Vejo você novamente em algum momento Horatio.",
"Sim, tome cuidado. Suponho que deveria voltar para #sGreenford#, mas parece que o jogo acabou por enquanto.",
"Isso é alguma retaguarda! Parece que os subestimamos. Então, o que você acha?",
"Poderíamos tentar pegar a arma ou nos render.",
"Qual é?",
"Vamos buscar a arma.",
"Acredito que a rendição seria o melhor curso de ação nessas circunstâncias.",
"Você sabe onde estamos, comandante?",
"Em uma das ilhas francesas, e eu acho que #sisland_Guadeloupe#, não ficamos tanto tempo no mar.",
"O que fazemos agora?",
"Nada. Receio que o jogo tenha acabado para nós. Teremos que esperar pela próxima atualização!!!!!",
"Aí vem Mansfield agora.",
"Presumo que isto significa que apanharam os franceses que estavam escondidos.",
"Comandante Hornblower! O que te traz a este sertão?",
"Você e sua tropa. Você foi transferido para minha nave por enquanto. Precisamos encontrar o seu Major Hogan.",
"Hogan? Isso significa que há problemas em andamento se ele estiver envolvido. A última vez que ouvi dizer que ele estava em #sisland_Guadeloupe#",
"#sisland_Guadeloupe#. Isso é francês. Teremos que pousar em Anse Casse Bois para ter alguma esperança de não sermos vistos.",
"É pior que isso. Ele finge ser fazendeiro enquanto está lá e mora em uma plantação, que fica perto do porto.",
"Maldição! não teríamos chance de entrar no porto, nem mesmo de chegar perto dele, e de Anse Casse Bois significaria cruzar toda a ilha sem sermos descobertos.",
"Eu sei como podemos atravessar a ilha sem sermos detectados.",
"O que você quer dizer?",
"Navegaremos para #sCharlestown# onde buscaremos alguns amigos meus.",
"#sCharlestown#!? Espero que você saiba o que estamos fazendo, Richard.",
"Digamos apenas que conheci algumas pessoas interessantes, que conhecem o seu negócio.",
"Muito bem, #sCharlestown# é isso. Vamos. É uma longa jornada.",
"Mandei Patrick alojar os homens. Vamos conhecer a Commadante Moreno, ela lidera um bando de guerrilheiros contra os franceses.",
"Guerrilhas!? Aqui? O que você quer dizer?",
"É uma longa história, que não tenho tempo de contar agora, mas posso garantir que ela é confiável.",
"Você terá que me contar mais do que isso, Richard. Tenho o meu navio e os meus homens a considerar.",
"Rapidamente então. Ela foi forçada a assistir sua família sendo assassinada pelo exército francês. Desde então, ela prometeu matar todos os soldados franceses que encontrar e derrotar a causa francesa.",
"Eu vejo. Isso lança uma luz diferente sobre as coisas. Mas por que ela não está trabalhando conosco?",
"Ela o faz, de vez em quando, mas acha que estamos demorando muito para derrotar os franceses, e esta trégua que temos com eles agora não ajudou em nada.",
"Então, por que ela nos ajudaria agora?",
"Teresa e eu nos conhecemos muito bem e ela também conhece o Major Hogan. Se eu contar a ela o que estamos fazendo, ela concordará em nos ajudar.",
"Muito bem. Onde devemos ir para encontrar o Comandante?",
"Não longe. Ela está aqui no porto",
"No porto? Onde?",
"Ela e seu bando assumiram o controle da casa e dos negócios do contrabandista. Eles administram isso como uma pequena loja. É uma boa cobertura e uma boa maneira de mantê-los abastecidos.",
"Isso é o suficiente por enquanto. Vamos para a casa do contrabandista... quero dizer, loja. Vá em frente. Isso lhe dará a chance de prepará-la para o encontro.",
"Teresa, posso apresentar o Comandante Horatio Hornblower.... Comandante Hornblower, Commadante Teresa Moreno.",
"Um prazer comandante.",
"Capitão, será melhor que os rifles avancem primeiro. Eles sabem viajar por esse tipo de país e não serem vistos. Os homens de Teresa podem mostrar-lhes o caminho.",
"Muito bem. Nós os seguiremos.",
"Rapidamente!! Entre nos arbustos!",
"Felizmente eu os vi chegando. É melhor não sermos vistos, pensei. Havia muitos deles também, pelo menos uma empresa.",
"Sim, e não creio que estejam aqui para a troca da guarda. Há algo acontecendo, mas não consigo definir o que é agora.",
"Vamos continuar. As tropas do forte serão dispensadas em breve, e aposto que muitas delas irão direto para a praia para nadar.",
"Você tem razão. E estamos bem no caminho deles. Vamos para o próximo vale, e rápido.",
"Bem, parece que chegamos à plantação.",
"Sim, é verdade e bem na hora... olhe para isso, atrás de você.",
"Ele não te reconheceu com aquelas roupas. Ele acha que eu estava voltando ao seu comando.",
"Eu pensei isso também. E agora?",
"Harper, Cooper. Vá para a Casa da Plantação. O Major tem algumas roupas para você vestir. Espere lá pelo Comandante. Você trabalhará com ele e o Comandante.",
"O que você vai fazer?",
"Estamos em desvantagem numérica de pelo menos dez para um, então será suicídio ficar aqui. Eu levarei o resto da tropa e nos esconderemos nas rochas e tentaremos abater alguns dos franceses quando eles passarem.",
"E então?",
"Se conseguirmos, tentaremos voltar para a praia.",
"Vou cuidar de você na praia, mas agora é melhor voltar para casa e pegar Harper e Cooper.",
"Fico feliz em ver vocês dois. Onde está Cooper?",
"Se nossas costas estiverem seguras, é hora de seguir em frente e terminar isso. Patrick e eu ficaremos nos fundos da plantação. Você ajuda os rapazes da frente aqui.",
"Avante é",
"Língua. Cuide do capitão. Bem, temos as nossas ordens, temos de sair daqui.",
"O capitão Murray precisa de cuidados. Enquanto isso, Harper, Cooper e eu iremos buscar nossos uniformes. Prefiro ser baleado como oficial e não como espião.",
"Seja rápido então. Enquanto isso, podemos fazer algo com os corpos aqui. Mas, duplique o tempo, se não se importa. Comandante. Não nos resta muito tempo antes que abram os portões da cidade.",
"Harper, Cooper. Vamos.",
"Devemos sair agora, senhor. Não sobrou um número suficiente de nós para adiar um novo ataque, mas mover o capitão Murray com os ferimentos que ele tem me preocupa.",
"Teremos que nos contentar. Não podemos deixá-lo. Dê a ordem para sair.",
"Droga! Ele era um bom homem. Harris, o Haggman fica para trás e enterra o Capitão, depois alcança-nos. O resto de vocês saia em grupos. Nos encontramos na praia.",
"Eles deveriam passar. Quando os franceses chegarem, vão pensar que ainda estamos escondidos em algum lugar aqui, então vão perder muito tempo nos procurando.",
"Eu espero que você esteja certo. Não apenas exaustos, os homens estão desanimados com a morte do capitão Murray.",
"Engraçado. Eles não pareciam preocupados com Dunnitt.",
"Hmmm... É melhor irmos embora.",
"Até agora, tudo bem, Comandante.",
"Fique atento. Ainda não estamos em casa.",
"Devo levar as tropas de volta ao quartel e reportar.",
"Muito bem, Tenente.",
"Harper, volte para a nave... Já vi um desses antes. É uma torre de sinalização. Tem um semáforo no topo e sinaliza ao forte sobre os navios que vê vindo em direção ao forte.",
"Assim, à medida que os nossos navios se aproximassem, isso sinalizaria o forte e eles estariam prontos para tirar os nossos navios da água. ",
"É sobre isso. Nenhum navio pode chegar perto do porto sem que o forte esteja pronto para recebê-lo. ",
"Parece um farol.",
"Essa é a parte inteligente. A menos que você saiba sobre isso, você nunca saberia o que era. Você poderia assumir que era apenas um farol.",
"Devemos voltar e relatar isso.",
"Você sempre teve um bom olho, Teresa. Que bom que você conseguiu, capitão. Estávamos começando a pensar que estávamos presos aqui. Ficamos muito felizes quando vimos o navio de Teresa.",
"Ficarei mais feliz quando o 'Hotspur' aparecer.",
"Esperamos, suponho. Como foi a batalha?",
"Não é bom. Repulsamos os franceses no momento, mas o major Dunnitt, o capitão Murray e muitos rapazes foram mortos.",
"É triste ouvir isso.",
"Há algumas boas notícias. Harper e Cooper encontraram algo que você deveria dar uma olhada.",
"Mas não podemos sair da praia. O 'Hotspur' sentirá nossa falta.",
"Haggman, Cooper e o resto podem esperar pelo 'Hotspur'. Você, eu e Harper iremos dar uma olhada no que encontramos. Não vai demorar muito, e Harper está com seu uniforme, então você pode se trocar enquanto avançamos. Siga-nos.",
"Aí está você, Horácio. Vamos ver Wolfe. Eu estava ansioso por isso.",
"Continue.",
"Deixe-o comigo, Horácio. Cinco minutos com Haggman e ele vai desejar que o tivéssemos enforcado.",
"Tenho certeza de que Wolfe desejará evitar tais aborrecimentos. Não vai, Wolfe?",
"Apenas lembre-se, Wolfe. Você não é um falcão, é mais um rato. Faça qualquer coisa engraçada e Haggman fará você desejar que tivéssemos te enforcado.",
".",
"Trouxe Harper e Haggman. Caso o Quelp tenha mais surpresas para nós.",
"Boa ideia, Tenente. Wolfe, onde você deveria encontrar Quelp?",
"Harper, Haggman - protejam-se e mantenham os olhos abertos.",
"Aí está o Quelp. Vamos descobrir o que ele tem a dizer.",
"Harpista! Hagman! Esses não são soldados britânicos, são franceses disfarçados!",
"Vá e cuide dos Voltigeurs, Tenente. Eu vou lidar com Quelp",
"E Haggman, diga ao resto dos Homens Escolhidos para se juntarem a nós aqui. Provavelmente há mais desses Voltigeurs por aqui em algum lugar.",
"O que o faz dizer isso, Tenente?",
"Os Sapos não deixariam tropas assim sob o comando de um vira-casaca como Quelp. Eles iriam querer seu próprio oficial no comando. E ele não está aqui",
"Portanto, pode haver mais mais adiante. Mas eles não gostariam de usar uniformes britânicos na cidade. Contar à guarnição por que eles estão usando uniforme britânico seria um risco à segurança, e não contar a eles causaria problemas.",
"Então eles terão que trocar de uniforme em outro lugar. Se tivermos sorte, podemos pegá-los fazendo isso.",
"Vamos.",
"Não creio que encontraremos os Voltigeurs aqui, Horatio. Esta é apenas uma pequena aldeia.",
"E se todas essas pessoas vissem os Voltigeurs, então seu segredo seria completamente revelado. Muito bem, vamos olhar mais perto da cidade.",
"Parece que Haggman conseguiu mais alguns fuzileiros para se juntarem a nós.",
"Bom. Quando eles chegarem aqui poderemos atacar os Voltigeurs.",
"Ali estão eles. Homens Escolhidos, ATAQUE!",
"Deixe um pouco para mim!",
"Com sua permissão, meus homens irão escoltar o oficial até o navio.",
"Isso seria muito útil, Tenente. A propósito, há algo que queria lhe perguntar. Quando estávamos interrogando Wolfe, você disse: 'Cinco minutos com Haggman e ele vai desejar que o tivéssemos enforcado'. O que Haggman iria fazer com ele?",
"Cantar.",
"Cantar? Ele é tão ruim assim?",
"Não, ele é tão bom. Cinco minutos de Haggman cantando sobre a vida após a morte e você gostaria que eles te enforcassem só para descobrir sobre o que ele está cantando.",
"Então espero que ele cante algo mais alegre quando estiver a bordo do meu navio!",
"Foi bom servir com você mais uma vez, Horácio. Mas os 95º deverão partir para a Europa a qualquer momento. Iremos juntar-nos a Sir Arthur Wellesley em Portugal.",
"O prazer foi meu, Richard. Boa sorte na Europa. Apresente meus cumprimentos a Sir Arthur Wellesley. Por falar nisso, envie lembranças a Napoleão também!",
"Eu farei isso. Adeus, Horácio.",
"Adeus, Ricardo.",
};
