string DLG_TEXT[46] = {
"Senhor da língua. 33º Regimento de Infantaria.",
"Continuar.",
"Língua de Isias. Homem Escolhido, Senhor.",
"Continuar.",
"Sr. Sharpe, Sr. Hornblower, senhores. Estou feliz por ter conversado com você. Houve um desenvolvimento.",
"Olá Língua. O que aconteceu?",
"Ouvimos o Sr. Quelp perguntando onde ficava o farol #sisland_Oxbay#. A próxima coisa que ele se foi. Então é aí que pensamos que ele se foi",
"O farol! Esse seria um bom lugar para realizar uma reunião secreta.",
"SENHOR! É o Capitão Murray. Ele está gravemente ferido.",
"...",
"?",
".",
"?",
"?",
"?",
".",
".",
".",
"",
".",
"?",
".",
".",
".",
".",
".",
".",
".",
".",
"?",
".",
"?",
".",
".",
"",
".",
".",
"",
"",
"",
"",
"",
"",
"",
"",
"",
};
