string DLG_TEXT[46] = {
"Senhor Cooper. 33º Regimento de Infantaria.",
"Continuar.",
"Senhor Cooper. 95ª Fuzis.",
"Continuar.",
"Parece que está trancado, senhor.",
"Dá-me uma gazua Cooper.",
"Gazua, senhor? Apanharam-me com uma gazua!",
"Eles mataram Cooper, lembra? Mas quando você saiu da prisão de Newgate, você conseguiu outro, e é esse que eu quero.",
"Posso recuperá-lo, senhor?",
"Confie em mim.",
"É muito difícil confiar num homem que quer pegar emprestada a sua gazua, senhor.",
"COOPER! Não me faça perguntar de novo.",
"Não sei muito francês, senhor, mas acho que fomos enganados. Eles não parecem querer se juntar a nós em oração, não é, senhor?",
"Cale a boca Cooper!",
"Acho que é isso que estamos prestes a ser, senhor.",
"...",
"Até agora, tudo bem, senhor.",
"Fique atento. Ainda não estamos em casa.",
"Haggman disse que talvez você precise de ajuda, senhor.",
"Nós fazemos. Estaremos lutando contra tropas francesas disfarçadas de britânicas, então se você vir alguém com uniforme vermelho, ele é o inimigo.",
"?",
".",
".",
".",
".",
".",
".",
".",
".",
"?",
".",
"?",
".",
".",
"",
".",
".",
"",
"",
"",
"",
"",
"",
"",
"",
"",
};
