string DLG_TEXT[290] = {
"Você está pronto?",
"Sim capitão.",
"O que está acontecendo aqui? ",
"Er... Sr. Simpson e eu estávamos praticando esgrima, capitão.",
"Harrumf! Você estava mesmo. Você é o novo aspirante, não é? ",
"Sim capitão. Eu sou aspirante ",
"Eu vejo. Bem, vamos ver se você é bom. Assuma o comando e navegue para #sCharlestown#, Sr. ",
"Aye Aye capitão.",
"Harrumf! Bem, você nos trouxe aqui, Sr. ",
"Você retornou em um momento muito fortuito e histórico ",
"Isso deveria enfraquecer um pouco os franceses! Um sucesso em sua revista a afundou. Harrumf! .. Você fez um ótimo trabalho lá ",
"Obrigado Capitão, mas perdemos muitos homens bons. Eu estava tentando o meu melhor, senhor.",
"A primeira batalha é sempre a pior. O capitão Keene agradeceu à 'Indy' por sua ajuda na batalha. Terá regressado a Antígua para fazer o seu relatório.",
"Sim capitão, eu vi o sinal. Pelo menos tivemos a chance de cuidar dos feridos no caminho para cá, senhor.",
"O capitão Keene também enviou um pacote em um barco longo, presumo que confirme seu agradecimento. O Sr. Simpson recolheu-os, mas ainda não os recebi.",
"Eu não o vejo desde que a batalha começou, senhor.",
"Recebemos um sinal de que a França declarou guerra à Grã-Bretanha. Por sorte, ela tem um de seus navios capitais em nossa região, o Téméraire. O Justiniano é encarregado de encontrá-la e afundá-la. Ela está tentando se juntar à principal frota francesa e devemos detê-la. O Infatigável é encarregado de atuar como vanguarda do Justiniano e batedor para ela. Devemos navegar para #sisland_Falaise de Fleur#. Nossa tarefa é localizar a Téméraire e avisar o Justiniano para que ela possa derrubá-la. Podemos prestar assistência, mas o ataque principal deve ser deixado para ela.",
"Eu entendo, capitão.",
"Faça o que fizer, NãO tente embarcar nela. Ela nos supera em número em mão de obra. Talvez possamos estar mais empenhados em derrubar os seus mastros. É claro que as condições de batalha prevalecerão e influenciarão nosso curso de ação final.",
"Navegaremos para o lado norte de Guadalupe. Em seguida, defina um curso de SSW à medida que passamos. Esse título nos colocará no caminho de #sisland_Falaise de Fleur#. Deveríamos então ser capazes de localizar o Téméraire.",
"Sim Capitão, lado norte de Guadalupe, então navegue SSW.",
"Precisamos ter certeza de pegar a luz do dia em #sisland_Falaise de Fleur#. Receio que será uma longa batalha e precisamos dar um bom espetáculo diante do capitão Keene. Agora, leve-me de volta ao navio. Preciso reunir a tripulação para estar pronta para a ação.",
"Você não tem. Vejo que o 'Renome' está aqui. Isso é uma boa notícia. Leve os feridos para as diversas casas ao redor para que possam ser atendidos. Iremos reportar-nos ao Capitão Sawyer na Academia. É aí que ele estabelecerá sua base costeira. Ele terá os últimos relatórios e nossos próximos pedidos.",
"Aye Aye capitão! Já estou cuidando dos feridos, então podemos prosseguir para a Academia quando você estiver pronto.",
"Harrumf! .. Você realmente... E onde ESTÁ aquele Sr. Simpson? Ele não estava ferido, estava?",
"Disseram-me que ele deixou o navio assim que atracamos, senhor. Presumi que ele estava seguindo suas ordens.",
"Explodir o homem! Eu não dei ordens! Ele está precisando ser vigiado, aquele. Fora para seus próprios fins, sem dúvida. Bem, devemos ir para a Academia. Ele terá que se atualizar mais tarde. Siga-me Sr. ",
"Vamos ",
"Sim senhor. Só estou me certificando de obter os suprimentos corretos.",
"Capitão Sawyer! Devo protestar! ",
"...",
"Certamente, senhor, não o fiz! Nem, devo acrescentar, que o Sr. ",
"Na verdade, capitão Sawyer, eu recomendaria sua promoção a tenente interino.",
"Sim, capitão Sawyer, foi o que aconteceu, e Keene desempenhou bem seu papel ao enviar a mensagem para Simpson interceptar.",
"Mensagem? ... Interceptar? Capitães, o que está acontecendo aqui, não entendo?",
"Sabíamos que Simpson era um cara mau, intimidando os outros aspirantes e afins. Ele não era o tipo que queremos na marinha deste homem. Então elaboramos um plano para que ele mostrasse sua mão.",
"Então você pediu ao Capitão Keene para enviar uma mensagem para ver se Simpson interferiria nisso?",
"Sim, e de fato Simpson forjou a mensagem do Capitão Keene para fazer com que parecesse ruim para o 'Infatigável' e, claro, para sua parte na batalha.",
"Mas como você sabe que ele mudou?",
"Se você lembrar ",
"Ah! Eu vejo. Então a parte da minha promoção também fez parte do estratagema?",
"Não. Essa parte era verdade. A partir de agora você está atuando como terceiro-tenente. A promoção precisará ser confirmada, é claro, mas isso será apenas uma questão de tempo. Você receberá seu uniforme ao sair. Por enquanto, Hornblower, você cuidará dos feridos enquanto eles se recuperam.",
"Sim, capitão. Obrigado, senhor. Partirei assim que tiver o navio pronto.",
", não é?",
". O capitão Keene me deu ordens para me juntar a você e ao seu navio. Aqui estão meus papéis.",
". Vamos contratar uma nova tripulação lá. E você, Sr. Simpson, me acompanhará até minha cabine. Tenho algumas palavras de sabedoria que desejo transmitir. Tenente Buckland. Dê ao Sr. ",
". Apesar de passar tanto tempo em seus aposentos enjoado. Agora estamos em terra firme novamente, vamos ver se você consegue reformar o navio. Precisamos de mais pólvora para navegar nestas águas. Aqui está um pouco de ouro para permitir a compra. Enquanto isso, irei verificar as mensagens e ver se a nova tripulação embarcou.",
", continue.",
", vá em frente.",
" estava cumprindo minhas ordens expressas. O 'Justiniano' foi, digamos, um pouco lento...",
"Suas ações foram nada menos do que altamente elogiáveis.",
", o capitão Keene sinalizou suas ordens com bandeira, como de costume. E se Simpson tivesse se incomodado em ler esse sinal, teria visto que o capitão Keene agradeceu ao 'Indy' e sua tripulação por seus esforços. Mudar a mensagem escrita foi um grande erro. Assim como estava atacando você. Mas ao matá-lo você nos poupou muitos problemas.",
"Então você abandonaria o navio para evitar seus deveres! ",
". Você não me deixa nenhuma opção. Você será levado para a prisão e mantido durante a noite. Amanhã, você será enforcado na verga do navio, por deserção.",
", o curso, por favor.",
"Depois da batalha voltaremos aqui, e o 'Justiniano' irá para Antígua, para continuar a confundir nossos inimigos.",
"Sim, Inglaterra, rapaz. Uma ilha grande, úmida e nebulosa, a nordeste de Ushant. Acha que pode encontrá-lo?",
"Er.. Sim, capitão, claro.",
"Encorajador, muito encorajador, Hornblower. Ainda há esperança para nós! Aqui estão os documentos. Proteja-os bem, o futuro da nação no Caribe depende deles.",
"Há mais uma coisa, Hornblower. Harrumf! .. Exigiremos que você acompanhe a Duquesa de Wharfedale de volta à Inglaterra com você.",
"Mas.. mas.. Capitão..",
"Sem 'mas' Hornblower. Como eu disse, este é um assunto de importância nacional. Mantenha esses documentos seguros. Quando você retornar, siga pela rota sul ao longo da África até Antígua.",
"Seja grato pelas pequenas misericórdias, Hornblower. E ainda mais grato pelos grandes. Agora, apresse-se em sua partida. Boa Sorte Vá com Deus.",
"Sim capitão. Suponho que isso significa que não farei o exame de tenente?",
"Não. Essa parte era verdade. A partir de agora você está atuando como terceiro-tenente. A promoção precisará ser confirmada, é claro, mas isso será apenas uma questão de tempo. Você receberá seu uniforme ao sair. Você também encontrará Le Rêve no porto, é um navio premiado francês. Você deve levá-la para #sRedmond#, em #sisland_Redmond#. Você se reportará ao chefe da estação #sisland_Redmond#, almirante Sir Peter Parker, ele lhe dará seu exame formal de tenente. Eu te encontrarei lá.",
"Senhor? Isso significa que estamos aqui? A guerra acabou de começar, certamente deveríamos estar em patrulha à procura dos franceses e espanhóis?",
"Soprador de chifre. O 'Indy' sofreu danos graves demais para este estaleiro realizar reparos. Vou levá-la para Antígua e para o estaleiro naval de lá. O 'Renome' e o 'Agamenon' nos acompanharão. Enquanto isso, você permanecerá aqui e manterá seus olhos e ouvidos atentos aos movimentos do navio e informará sobre nosso retorno.",
"Bom! Você encontrará Midshipman Hunter pela cidade. Ele foi designado para o seu turno. Você está demitido, cumpra seus deveres, Hornblower.",
"Sim Sawyer, concordo totalmente, um ótimo trabalho. Os franceses ficarão doloridos agora. Quanto a vocês dois senhores. Hornblower, você deve levar seu novo navio para #sRedmond# e apresentar-se a Sir Peter Parker para o exame de tenente. Sargento Sharpe, você e seu destacamento navegarão com o Capitão Nelson. Por favor, permaneça aqui para novos pedidos.",
" Navegarei separadamente e encontrarei você em #sRedmond#, Hornblower. Apressem-se, senhores. Dispensado, e er, Harrumph! ... Parabéns. Um ótimo trabalho.",
". Parece que parabéns estão em ordem! Estou prestes a atacar o navio francês, quando suas cores aparecem, bem diante dos meus olhos. Você se importaria de explicar o que aconteceu aqui?",
"Capitão, os franceses bloquearam #sCharlestown#. Eu estava tentando fazer com que eles movessem seus navios, cortando-lhes o abastecimento de água. Com a ajuda do Escolhido Sharpe e seus homens, conseguimos tomar o lugar da tripulação francesa quando eles desembarcaram em busca de água. Pudemos então remar e assumir o controle do navio.",
"De fato! Harrumf! O que você estava fazendo aqui em primeiro lugar? Minhas ordens eram para cuidar dos feridos, não é? E o que dizer da cidade? Vítimas? Dano? Denuncie cara!",
"Sim capitão. É exatamente isso. Quando os franceses bloquearam a cidade, eles não tentaram pousar, apenas dispararam tiros ocasionais em direção ao cais. Então eu sabia que eles estavam esperando o retorno do 'Indy' para atacá-lo e afundá-lo.",
"Hmmm! De fato! .. De fato! .. Algo não está certo aqui. Senhor Bush! .. Por favor, sinalize para o Major Wellesley e sua irmã se juntarem a nós aqui. Então prepare-se para levar o 'Indy' para o mar, encontre o 'Agamemnon' e o 'Justinian' e avise-os sobre a situação em #sCharlestown#. É claro que você manterá o 'Indy' fora de quaisquer hostilidades.",
"Sr. Quelp! Lembre-se do seu lugar, senhor! Se eu precisar de seu conselho sobre estratégia, eu o pedirei. Até esse momento, cuide gentilmente de seus deveres. Senhor Bush! Você tem suas ordens. Soprador de chifre. Este é o seu soldado?",
"Túnel? Que túnel é esse ",
"? Não me diga que a mineração também é um dos seus talentos latentes.",
"Não capitão! É um antigo túnel de contrabandistas que vai daqui até à cidade. É mais rápido do que atravessar a selva.",
"Hmmm! E quão seguro é este seu túnel?",
"Eu só usei uma vez, senhor, mas Hunter usou duas vezes e até trouxe a tripulação através dele.",
"Ah! Principal. Deixe-me apresentar o tenente ",
". Foi ele quem capturou 'Le Rêve'. Parece que os franceses bloquearam #sCharlestown# mas tenho algumas ideias sobre isso que explicarei no caminho. ",
" também nos encontrou um caminho de volta para a cidade, então sugiro que nos apressemos. Continue ",
"Aye Aye capitão. O túnel está logo aqui.",
"Cavalheiros! Gostaria de lembrar que há uma senhora presente e este não é o lugar para ela estar. Major, faça a gentileza de levar sua irmã à Taverna. Senhor Quelp, você os acompanhará e permanecerá com eles de guarda.",
"Precisamos rever a situação, senhores. Algo não está certo aqui, não está nada certo. Uma rede de contrabando na própria cidade, cadáveres por todo lado..",
"Dado o que sabemos no momento, meus pensamentos são os seguintes. O bloqueio era de facto destinado à 'Indy', mas porquê? Certamente o 'Renome' e o 'Agamenon' seriam alvos melhores? E por que não invadir a cidade?",
"Poderia ser uma vingança por termos afundado o 'Téméraire', Capitão?",
"Não, eu não penso assim. O bloqueio sem pouso sugere que eles estavam esperando por algo que a 'Indy' tem.",
"Ou alguém, senhor.",
"Agora há um pensamento... acho que você pode ter a resposta aí ",
". Acho que descobriremos mais se vocês, cavalheiros, vasculharem este outro túnel e encontrarem o caminho para a Academia e o Forte dos Piratas. Encontre-me aqui na sala dos fundos quando tiver essas respostas.",
"! Afinal! O que você descobriu? Alguma verdade nas histórias dos nossos amigos contrabandistas?",
"Sim, capitão e muito mais! Os franceses parecem estar aliados aos piratas, senhor.",
"O QUE! Detalhes cara. Detalhes! O que exatamente você encontrou?",
"Bem, senhor, encontramos...",
"Prossiga ",
", O que você descobriu?",
"O túnel realmente conecta esta sala ao Acampamento Pirata e à Academia, mas o mais importante é que vimos que os oficiais franceses se movimentam livremente por lá.",
"Hmmm.. Os franceses não estariam interessados em contrabando, não em tão pequena escala. Então, no que você acha que eles estariam interessados?",
"Eu não sei, senhor. Um ataque da retaguarda em #sCharlestown#, através do túnel?",
"Dificilmente isso, eles não seriam capazes de mover tropas suficientes através de um espaço tão pequeno no tempo. Poderíamos acabar com eles nas saídas, aqui ou na Academia com apenas um pelotão de soldados.",
"Então eu não sei senhor.",
"Pense cara, pense! O que aconteceu quando atravessamos o túnel vindo da praia?",
"Bem, o Tenente Quelp impediu Larr de atacar Sharpe.",
"Ele fez isso? Ou ele calou Larr? Lembre-se de que Sharpe disse que Larr foi desarmado antes de chegarmos.",
"Para impedi-lo de nos contar algo que não sabíamos?",
"Você está se aproximando do vento ",
". Agora pegue o vento em suas velas e pense a partir daí.",
"Acho que entendi, capitão. O tenente Quelp sabia que eu acabara de encontrar o túnel que vinha da praia e, portanto, não sabia do outro túnel que levava ao acampamento. Ele pensou que Bryan estava morto, então matando Larr não descobriríamos.",
"Bom homem. O outro túnel é a chave. Acrescente a isso os franceses estarem no acampamento pirata e não atacarem a cidade com seus navios, o que você acha que eles procuram?",
"A 'Indy'?",
"Eles não vão afundar um navio do homem do túnel! Pensar!",
"O senhor? Eles estão atrás de você?",
"Perto, mas não, eu não, Wellesley. Ele comprou sua comissão ao Tenente Coronel do 33º Regimento de Infantaria, que assumirá quando chegar à Holanda.",
"Onde ele lutará seriamente contra os franceses?",
"Exatamente, e dada a sua reputação, os franceses estariam muito interessados em que ele não chegasse aos Países Baixos.",
"O que significa que eles vão tentar matá-lo aqui.",
"É isso que vamos impedir que aconteça ",
"Como exatamente capitão?",
"Enfrentaremos nosso Tenente Quelp em seu próprio jogo. Iremos para a Academia, onde colocaremos as coisas em movimento. Basta seguir minha liderança ",
"! Afinal! O que você descobriu? Alguma verdade nas histórias dos nossos amigos contrabandistas?",
"Capitão, os franceses estão aliados aos piratas. Eles estão andando abertamente no Acampamento Pirata.",
"Minha nossa! E o que dizer da Academia? Eles também têm um caminho para lá?",
"Não encontramos essa entrada, Capitão. Nós, er.., eu decidi voltar direto para cá depois de ver os franceses.",
"Maldição! Precisamos saber se essa entrada existe ",
". Volte e veja se consegue encontrá-lo e depois relate. Não podemos planejar nosso próximo passo sem todas as informações.",
", você está de volta, e pela expressão em seu rosto você encontrou a entrada da Academia.",
"Sim capitão. É tudo verdade, o Acampamento Pirata, a Academia, esta sala. Eles estão todos ligados pelo túnel.",
"Então... precisamos discutir o que sabemos agora.",
"Sim, capitão, é o .. ",
"Buckland, Quelp. É bom ver que vocês, senhores, estão aqui. Com todos os nossos navios no mar, estamos com falta de oficiais no momento, e aquele maldito túnel da praia me preocupa. Você não concorda ",
"Sim, capitão.",
"O Major Wellesley vai fazer daquela casa o seu quartel-general por enquanto. Então, Sr. Quelp, traga um dos guardas aqui e guarde a entrada do túnel na casa do contrabandista. Não queremos visitantes inesperados vindos da praia.",
"Isso está resolvido então. Senhores, vocês sabem o que devem fazer. Sharpe, você deveria colocar seus homens em posição primeiro, eu acho.",
"Bom. Sharpe não demorará muito para se organizar. O Sr. Buckland e eu esperaremos pela 'Indy' e defenderemos o forte aqui. Então iremos para #sRedmond#. Boa sorte, senhores. Vejo você em #sRedmond#.",
"Desçam e vistam roupas secas. Nos encontraremos em minha cabana pela manhã, depois que você estiver descansado.",
"Bom dia, Vossa Graça. Espero que você esteja totalmente descansado após sua provação.",
"Ha Ha! Muito engraçado, Vossa Graça. Bem, iremos para #sisland_Redmond# imediatamente. Você deverá estar em #sRedmond# em um ou dois dias. Lá você pegará um navio para a Inglaterra.",
"Você sobrecarregou sua Graça com isso?",
"São os documentos que você me deu, senhor. Eu pensei que eles eram importantes.",
"Eu sei que eles são importantes, cara! O Almirantado me fez procurar por eles em metade do Caribe depois que você decidiu desaparecer.",
"Receio Sr. ",
" não é mais meu tenente interino.",
"Com efeito imediato, e após reunião onde foi acordado por três capitães. Devo dizer que são três capitães que normalmente não concordariam com a cor de uma laranja, Sr. ",
" agora é tenente comissionado. Parabéns Tenente.",
"Obrigado, Capitão Pellew.",
"Bom. Então partiremos para #sisland_Redmond#.",
"Receio que eu e a minha tripulação tenhamos de regressar ao capitão da prisão espanhola. Dei a minha liberdade condicional e a dos meus homens.",
"Você realmente fez isso! Bem, você é responsável por suas próprias ações, mas seus homens podem não ser tão meticulosos quanto você, e eu não os culparia por isso. Vamos ver o que eles têm a dizer sobre o assunto.",
"Senhor. ",
" tem sido muito cruel com vocês, homens. Ele concedeu-lhe liberdade condicional para regressar à prisão espanhola. No entanto, essa liberdade condicional não é vinculativa para você.",
"Você pode ficar aqui com seus companheiros, se desejar. A liberdade condicional não é vinculativa para você, então o assunto será concluído. O que você diz?",
"Muito bem. Que assim seja. Navegaremos de volta sob uma bandeira de trégua e devolveremos você aos Dons.",
". Espero que você esteja bem descansado. Surgiu um assunto que requer as habilidades do Major Wellesley e suas tropas, e devemos prestar assistência.",
"Você se lembra dos soldados que atacaram a casa com os túneis em #sCharlestown#?",
"O major notou que eram tropas de elite de uma companhia especial. A inteligência descobriu que eles estão se agrupando em Octopus Bay em #sisland_Falaise de Fleur#.",
"A intenção deles é lançar um ataque em #sCharlestown#. O Major acredita que podemos surpreendê-los atacando-os na Baía Octopus antes de embarcarem. Precisamos chegar a #sRedmond# o mais rápido possível para recolher suas tropas. Nos encontraremos lá no Quartel-General da Marinha. Liderar o Tenente ",
"Ah! ",
", você chegou, bom. Senhores, para aqueles de vocês que ainda não o conheceram, apresento-lhes o Tenente ",
"Cavalheiros.",
"Estamos aqui para lhe dar ordens para enfrentar as tropas francesas em Octopus Bay em #sisland_Falaise de Fleur#.",
"Para impedir o ataque a #sCharlestown#, senhor?",
"Sim, Sr. ",
". Esse é o plano, pelo menos. Você, senhor, deverá transportar as tropas e a 'Indy' fornecerá apoio naval, mas permaneça bem no mar. Mas eu deveria deixar o Major explicar.",
". Você encontrará a 'Magicienne' no porto. Ela é uma francesa capturada e isso pode causar alguma confusão ao inimigo, pois eles podem ainda não saber de sua captura. Ela está abastecida e armada e as tropas estão embarcando neste momento. Boa sorte para todos vocês. Dispensados, senhores.",
". Pelo que entendi você teve o prazer da companhia do Capitão Foster na viagem até aqui?",
"Bem, sem dúvida você ficará satisfeito em saber que ele será um dos seus examinadores para o exame de tenente?",
"Uma resposta muito diplomática... Tenho mais más notícias. Kennedy foi destacado para aquela fatídica missão do navio de abastecimento.",
"Quer dizer que ele está morto, capitão?",
"Não não. Parece que o capitão Foster não foi o único sobrevivente do ataque espanhol. Conseguimos resgatar alguns tripulantes a caminho daqui. Disseram-nos que o Sr. Kennedy foi recolhido pelos espanhóis depois que o navio naufragou.",
"Você quer dizer Archie... O Sr. Kennedy é um prisioneiro dos espanhóis?",
"Temo que sim. E não sabemos onde. Mas vamos ao assunto em questão. Você deve se apresentar para seu exame hoje. Na verdade, agora. Será realizado no Quartel-General da Marinha, logo ali, do outro lado da rua. Bem.. vai, cara.",
"Você está encharcado, Hornblower. Vamos levá-lo de volta a bordo do 'Indy'.",
"Em todos os meus anos no mar, testemunhei muitos atos de coragem, mas ESSE senhor, deve estar entre os mais memoráveis... Meus homens lhe devem suas vidas... e eu lhe devo meu navio. Esses eventos serão anotados em seu registro.",
"Obrigado, senhor... Posso perguntar sobre meu exame, senhor?",
"Essa banca examinadora em particular talvez nunca mais se reúna, imagino. Agora olhe aqui, Hornblower, pelo que Harvey me contou, você estava de costas, prestes a perder seus mastros e os penhascos de Dover sob seu domínio. Mais um minuto e você teria falhado. Hmm, foi a arma de advertência que te salvou, não foi?",
"Sim senhor.",
"Acho que nas últimas semanas vimos você enfrentar e passar por um exame muito mais rigoroso. Acho que você já provou a bebida amarga que é a vida de um capitão. Acho que da próxima vez, senhor, você estará melhor preparado. Sr. Hornblower, foi uma honra servir com você.",
"E com você, senhor.",
"Seu plano foi bom. Sua execução excelente. No entanto, antes de escorregar, Sr. Hornblower. Acho que você encontrará aqui um teste muito mais severo. Suas Excelências, Major General Sir Hew e Lady Dalrymple solicitam o prazer de Sir Edward Pellew e...",
"...Tenente em exercício Horácio... Jantar... Casa do Governo... Jantar.",
"Aposto que você gostaria de ter um uniforme novo agora. Ei, Sr. Hornblower?",
"Um excelente jantar, Sir Hew.... Você não concorda, Sr. Hornblower?",
", feliz por ter pego você. Você será transferido para o 'Renome' sob o comando do Capitão Sawyer com efeito imediato. Você encontrará o Sr. Kennedy na taverna. Recolha-o e apresente-se ao QG Naval. em #sGreenford# para novos pedidos.",
"Mas e o senhor ferido?",
"Eles retornarão comigo na 'Indy' para #sRedmond#. Não perca tempo, cara. Vá embora.",
"Cavalheiros. Você é formalmente acusado de motim ao arrancar o comando do 'Renome' do Capitão Sawyer e por esse ato permitir que o 'Renome' fosse capturado pelos espanhóis, resultando na morte do Capitão Sawyer. Como você se declara?",
"Inocente, senhor. Tudo o que fiz foi para o bem dos homens, do navio e da marinha.",
"Mas você não estava a bordo quando o navio foi capturado pelos prisioneiros espanhóis. Isso está correto?",
"Sim senhor, isso está correto. Bush, o Sr. Kennedy e eu levamos um grupo de desembarque em terra para atacar o forte, senhor.",
"Ah! sim. Um plano engenhoso, Sr. Hornblower, que terminou com a destruição do forte e a privação de uso dos nossos inimigos.",
"E foram vocês, Sr. Bush e Sr. Kennedy, que foram fundamentais para retomar o 'renome' dos prisioneiros espanhóis, não foram?",
"Enquanto você,... Sr. Buckland estava amarrado em sua cama?",
"Acredito que você cometeu perjúrio, Sr. Buckland. Senhor Kennedy, avance, por favor, e diga a este tribunal quem você sabe ter empurrado o capitão Sawyer para o porão.",
"Bem, estou feliz que isso tenha acabado. Tivemos alguns momentos desagradáveis na discussão sobre o assunto, mas graças a Deus pela intervenção oportuna do Sr. Kennedy.",
"Mas senhor, Archie NãO pressionou o capitão. Ninguém fez isso! Ele caiu.",
"Ambos sabemos disso, Hornblower, mas o Almirantado precisava de um final claro para o assunto. A carreira de Buckland como oficial de vela acabou. Ele será colocado em uma posição em terra agora, mas Buckland não pressionou o capitão.",
"Por que Archie? Meu Deus, ele morreu esta manhã! Por que ele precisou confessar algo que não fez?",
"O Sr. Kennedy sabia o que estava fazendo. Ele sabia que estava prestes a morrer e sabia que se alguém não fosse identificado pelo 'crime', a suspeita sempre recairia sobre você.",
"Então foi por isso que ele confessou?",
"Sim, e agora que ele morreu, o assunto logo será esquecido. Você e eu, entretanto, nunca o esqueceremos. Os registros mostrarão que o Capitão Sawyer morreu em batalha e o Sr. Kennedy morreu devido aos ferimentos recebidos em batalha, e isso encerrará o assunto.",
"Agora, vamos para coisas mais alegres. Você foi promovido a Comandante e recebeu a 'Retribuição' como seu navio.",
"Eu, senhor? Mas o Sr. Bush era o oficial superior.",
"Mas você mostrou toda a iniciativa, Hornblower. Você foi destacado para o Major Wellesley, ele estará aqui em breve. Nos encontraremos novamente Comandante Hornblower, entretanto desejo-lhe uma boa viagem.",
"Obrigado, senhor.",
"Comandante Horatio Hornblower. Você foi considerado culpado de traição no assassinato doloso do Tenente Uriah Quelp e do Sargento Richard Sharpe. Você será imediatamente retirado deste lugar e pendurado pelo pescoço até morrer.",
"Ah! Sr. Hornblower! Você está bem, senhor?",
"Almirante Pellew, senhor. Sim, muito bem, obrigado. Você se lembra do Tenente William Bush, nós, er, servimos juntos no 'Renome'.",
"Com grande efeito, pelo que me lembro. [Bush - Obrigado, senhor.] Você está se juntando a nós para jogar cartas, Sr.",
"Bush é apenas um espectador esta noite, mas ficarei honrado, como sempre.",
"Então permita-me apresentar à mesa um velho conhecido. Acho que você achará este concurso muito estimulante.",
"Então, Sr. Hammond, se pudesse escolher, com quem você serviria? Embora, naturalmente, não possa fazer promessas.",
"Bem, se ele quiser ir para a batalha com o Sr. Hornblower, há sempre a mesa de cartas, mas aviso-o, Sr. Hammond, o tenente é um jogador excepcionalmente talentoso.",
"Bem, senhores, esta noite foi bastante educativa. Aqui estão seus ganhos. Use-os com sabedoria. Vejo você a bordo do Flagship às duas badaladas, amanhã ao meio-dia. Senhor Bush.",
"Ah! Soprador de chifre. [Almirante Pellew, senhor.] Como está seu chefe? Você passou a noite comemorando sua boa sorte?",
"Infelizmente, não, senhor. Eu tinha algumas dívidas para saldar.",
"Você reconhece aquela chalupa de vinte e quatro canhões? ['Hotspur' Senhor?] Mmm! Precisa de um capitão. Um homem de inteligência e capacidade. Eu queria saber se você poderia sugerir alguém adequado. Como você era. Sua promoção a Comandante foi confirmada. Você agora é capitão do 'Hotspur'. Ela deve estar pronta para navegar em dois dias.",
"Obrigado, senhor.",
"Isto não é favoritismo inútil, Hornblower. Você precisa ser meus olhos e ouvidos... ENTRE!",
"Exatamente! Assim, nós, o Coronel e eu, formulamos um plano para descobrir o que nossos 'amigos' estão tramando, para que possamos estar preparados para eles.",
"Na verdade, almirante. Sempre vale a pena saber o que os inimigos, ou inimigos em potencial, estão tramando.",
"Bom Bom! Bem, senhores, a razão pela qual os trouxe aqui, Hornblower, é para uma missão especial. Uma missão especial que deve ser realizada no maior sigilo.",
"Senhor?",
"O Coronel tem um agente em território inimigo que acompanha os acontecimentos com muito cuidado. Precisamos obter suas informações mais recentes.",
"Como isso me afeta, senhor?",
"O que exigimos que você faça, Hornblower, é se encontrar com o agente, um Major Hogan, que lhe fornecerá as informações mais recentes que você trará para cá.",
"Mas como vou encontrá-lo, senhor? E como vou conhecê-lo?",
"Bom. Isso está resolvido então. Designei o aspirante Hammond para o seu navio, pois ele parecia muito ansioso para servir com você. Você pode, neste caso, selecionar seu próprio primeiro-tenente, o tenente Chadd será o segundo. Você precisará de uma tripulação. Pelo que sei, há muitos homens bons procurando emprego na taverna. Além disso, o Tenente Quelp e o 'Recurso' irão acompanhá-lo como escolta até Cayman.",
"Sim, almirante. Eu entendo.",
"E lembre-se. Não faça nada para provocar a guerra, antes que a guerra seja declarada. Sua missão é vital para a Inglaterra.",
"Ah! Coronel Wellesley! Excelente momento. Eu estava prestes a explicar ao capitão Hornblower nosso plano de continuar a frustrar os franceses.",
"Ah! Soprador de chifre. Li os seus relatórios e os do Major Hogan. Agora, por favor, dê-me sua análise da situação.",
"Almirante Pellew, senhor. Acredito que os franceses estão prestes a lançar uma grande invasão numa das nossas ilhas.",
"Isso, capitão, é óbvio, mas qual ilha? Essa é a questão. Se reunirmos as nossas tropas e navios para defender uma ilha, e não for aquela que os franceses invadem... não preciso dizer mais nada.",
"Por favor, continue Capitão Hornblower. Eu ficaria muito interessado em ouvir sua resolução para esse dilema.",
"Almirante. Não sabemos que ilha os franceses pretendem atacar, por isso devemos posicionar os nossos navios no mar, para podermos seguir e atacar os navios franceses quando virmos para que lado se dirigem... ",
"Não há tempo para organizar um bloqueio. A guerra contra a França recomeçou e devemos agir rapidamente. Um ataque preventivo à frota francesa. Sem navios, as tropas que os franceses possuem tornar-se-ão ineficazes, pois não terão navios para transportá-las.",
"Seus navios estão atracados no porto principal, senhor, mas são protegidos por uma torre de sinalização com semáforo, que sinaliza qualquer movimento do navio, e claro, lá está o forte principal.",
"Ah sim! O forte. Hogan forneceu detalhes sobre isso. Parece que há uma grande bateria lá em cima. Mas impedir que os navios franceses deixem o porto é o meu principal objectivo. Levarei a frota para o porto principal e destruirei a frota francesa.",
"Você terá que fazer algo sobre o semáforo e a bateria primeiro, senhor. Posso ser voluntário no 'Hotspur'...",
"Insistir Capitão Hammond? Não senhor, sou eu quem insisto que você ouça o plano. O capitão Hornblower irá de fato atacar o semáforo com um pequeno grupo e sinalizar seu sucesso com um foguete azul.",
"Posso sugerir que eu lance o ataque ao anoitecer aproveitando ao máximo a neblina noturna? [Bom]",
"Então, ao amanhecer, Capitão Hammond, você liderará um grupo de fuzileiros navais e atacará a bateria e indicará que ela foi tomada por dois foguetes vermelhos. [Será uma honra, senhor.]",
"Bom. Isso conclui nosso negócio por enquanto. Capitão Hammond, pode regressar ao seu navio. Hornblower, uma palavra, por favor.",
"Sim, almirante.",
"O Major Hogan relata que sente que nossos planos estão sendo entregues aos franceses. Isso sugere que um dos nossos oficiais é um espião. Acho isso difícil de acreditar.",
"No entanto, sinto que devemos duvidar de alguém, senhor. Na verdade, se temos agentes familiarizados com os planos dos nossos inimigos, parece razoável supor que o inimigo também os tenha.",
"Hum! Farei algumas perguntas discretas. Enquanto isso você navega na maré da manhã, primeiro da vazante",
"Sim, sim, senhor.",
"Senhor, eu poderia enviar um grupo a terra para procurá-lo.",
"Não, Sr. Bush. Hornblower pode ter destruído suas comunicações, mas o Capitão Hammond ainda precisa paralisar suas defesas pegando a bateria, e NADA deve interferir em sua missão.",
"Mas senhor, só precisa ser uma pequena festa. Poderíamos até criar uma diversão. Senhor, devo isso a ele. Devemos isso a ele.",
"Maldito Bush! Você acha que eu não sei disso? Hornblower pode estar perdido, mas a guerra continua. Você assumirá o comando do 'Hotspur' e estará pronto para apoiar a ação.",
"Sim, sim, senhor.",
"Você diz no seu relatório que o capitão Hammond se culpou pelo fracasso do ataque à bateria. [Sim senhor] E, apesar de suas súplicas, ele insistiu em morrer com honra.",
"Você sabe que falei com o Sr. Bush?",
"Imaginei que você teria, senhor.",
"Houve um tempo, Hornblower, em que você precisaria de algum convencimento sobre os méritos de qualquer economia com a verdade.",
"Sim senhor. Mas estes são tempos incertos.",
"Hmm... E a verdade sobre Hammond poderia espalhar o descontentamento. Hmm.. A Inglaterra tem o direito de exigir lealdade.",
"Sim, senhor, embora.. [heh?] Talvez seja melhor ganhar lealdade do que exigi-la.",
"Quando eu era criança, falava como criança, entendia como criança, pensava como criança, depois me tornei homem e deixei de lado as coisas de criança. Você conhece Hornblower.. erm.. É muito difícil para um pai ver seus filhos crescerem.",
"Não tenho certeza se entendi, senhor?",
"Ouso dizer que você vai.",
"Que bom ver você de novo, Hornblower.",
"Mais uma vez, parabéns.",
"Senhor? Como você sabia? Maria e eu acabamos de nos casar.",
"Casado? Você tem estado ocupado, não é? Então, parabéns duplos são necessários, porque não foi isso que eu quis dizer.",
"Posso perguntar suas intenções para mim então, senhor?",
"Você está comprando outro navio. A fragata 'Atropos'. Suas ordens são para enfrentar o inimigo onde quer que ele esteja. Se você não conseguir encontrá-lo, um de nossos governadores provavelmente terá trabalho para você, ou sempre haverá navios em Antígua precisando de escolta. Você entende suas ordens?",
"Bom. Agora, de acordo com o seu relatório, o aspirante Wolfe era um traidor e escapou da luta em Anse Casse-Bois.",
"Muito bem. É possível que o Major Hogan possa ajudá-lo a encontrar Wolfe. Ou a associada portuguesa de Sharpe, Teresa Moreno, pode saber de alguma coisa, se você conseguir encontrá-la. Mas isso não é uma ordem, é não oficial. Tenho certeza de que você encontrará uma maneira de se tornar útil ao rei e ao país, Hornblower.",
"Disseram-me que você tem novidades para mim.",
"Bem, pare com isso, cara!",
"Senhor, acredito que lidei com os traidores que nos causaram tanta preocupação.",
"Harrumf! Você realmente tem? Hammond deu um tiro em si mesmo, pelo que me lembro, e Wolfe escapou.",
"Wolfe roubou um navio francês, senhor. Nós o localizamos em #sisland_Falaise de Fleur# e o capturamos. Ele foi muito útil quando confrontado com a perspectiva de um laço.",
"E então?",
"Ele nos levou a #sisland_Hispaniola# onde se encontraria com o Tenente Quelp.",
"Que ajuda? Suspeitamos dele, mas nunca pudemos provar nada. Vá em frente, por favor.",
"Ele estava planejando levar uma companhia de Voltigeurs para atacar #sEleuthera#. Eles deveriam estar disfarçados com uniformes britânicos. A América acreditaria então que havíamos lançado um ataque furtivo e declararia guerra contra nós.",
"E provavelmente você estragou o plano deles?",
"Sim senhor. O próprio Quelp atirou em Wolfe depois de saber que Wolfe o havia traído. Eu matei Quelp, enquanto o Tenente Sharpe e seus Homens Escolhidos foram inestimáveis na derrota dos Voltigeurs.",
"Você está de parabéns pelo trabalho bem executado, Comandante. E escreverei ao comandante do Tenente Sharpe expressando os meus agradecimentos pela sua ajuda. Teremos também de contar aos Americanos. Você tem alguma prova que possamos dar a eles?",
"Sim senhor. O comandante dos Voltigeurs é meu prisioneiro. Vou transferi-lo para sua custódia e então você poderá apresentá-lo aos americanos.",
"Excelente trabalho, Hornblower. Isso irá adicionar bem ao seu registro. Mas a guerra continua e imagino que em breve vocês terão mais façanhas para relatar. Que a sorte continue a sorrir para você, Hornblower.",
}
