string DLG_TEXT[46] = {
"Você precisa da minha ajuda, senhor?",
"Hmm.. tosse.. Er.. Sim.",
"Então você é o corajoso Tenente que o Sr. Hunter tem me falado.",
"Tenente interino Horatio Hornblower. Ao seu serviço, senhor.",
"Sim. Bem, Tenente Interino, o que posso fazer por você neste belo dia?",
"O Sr. Hunter me disse que talvez você conheça um atalho para a praia.",
"Sim, tenente interino, mas isso tem um custo.",
"Eu esperei isso. Quanto?",
"100 moedas de ouro.",
"Por pessoa. Tenho que considerar o salário do Sr. Bryan.",
"De alguma forma, eu também esperava isso. Aqui está o seu dinheiro. O que agora?",
"Basta passar pela porta à minha direita. Você encontrará um túnel. Leva direto para a praia. Bryan, vá embora.",
"Obrigado.",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
};
