string DLG_TEXT[50] = {
"Você parece tão forte, Sr. Haitch.",
"Hmm.. tosse.. Sua Senhoria!",
"Estarei seguro com este tenente, capitão Pellew? Ele não parece nada mais que um menino!",
"Eu Er.. garanto-lhe que farei o meu melhor, Vossa Graça.",
"Estou em suas mãos agora, Sr. Haitch. Posso chamá-lo de Sr. Haitch, não posso?",
"Er... Sim, Vossa Graça. Eu er.. Acho que devemos nos preparar para o mar. Bom dia, senhores.",
"Como chegaremos à Inglaterra, tenente? Que caminho devemos seguir?",
"Navegaremos nem para leste em direção à ilha #sisland_Turks# e depois nem para leste até Inglaterra.",
"Olá novamente Tenente. Venha comigo. Tenho alguém que quero que você conheça.",
"Tua graça? O que você está fazendo aqui?",
"Sr. Você parece um pouco distraído. Aconteceu alguma coisa?",
"Como você chegou aqui, Sua Graça?",
"Ha! o capitão espanhol viu um navio com bandeira britânica e voltou para cá o mais rápido que pôde. Ele me largou como um barril de carne estragada.",
"E os despachos Vossa Graça?",
"Oh! Eu desisti deles por um bom quarto.",
"O QUE!",
"Acalme-se, Sr. Haitch, acalme-se. Seus despachos são bastante seguros. Eu os tenho comigo. Agora vamos, é melhor voltarmos",
"Obrigado, Vossa Graça.",
"Olá Tenente. Só vim ver como o Sr. Kennedy está hoje.",
"Ele parece estar se recuperando, Vossa Graça.",
"É bom ouvir isso. Bem, acabei de passar por aqui. Vejo você mais tarde, Sr. Haitch.",
"Sim, Vossa Graça.",
"Devo protestar, senhor. Essas não foram minhas palavras.",
"...",
"Não me lembro, senhor... Achou Londres agradável?",
"Ouvi dizer que é uma peça triste.",
"Você saberia melhor do que eu. Não estou frequentemente em Londres.",
"Eu não gostei daquele francês. De jeito nenhum.",
"Por que não? Ele parecia gostar de você. Mas talvez seja porque você participou de uma peça que ele viu. Os Rivais, não foi? Ou talvez tenha sido Macbeth... Srta. Cobham. Você nega?",
"Por que eu deveria?",
"Mas por que essa charada? A coisa toda da Duquesa?",
"Porque eu quero chegar em casa.",
"Onde estão meus despachos?",
"Escondido.",
"Dê-me eles.",
"Por que? De repente, não sou confiável porque não sou uma duquesa?",
"Não. Porque você mentiu.",
"Confesso senhor. Confesso minha tolice em confiar nesse garoto. Se eu soubesse que ele navegaria para um ninho de Dons, garanto que ainda estaria descansando confortavelmente em #sredmond#.",
"Do jeito que está, estou aqui preso neste posto monótono, sem ninguém por companhia, exceto um velho aristocrata e um jovem inexperiente. Faz-me tão bem finalmente falar com um homem.",
"Talvez devêssemos retirar-nos para os meus aposentos, Coronel, onde poderemos conversar mais.",
"O que você quer?",
"Sua falta de civilidade não lhe dá nenhum crédito, senhor.",
"Como foi sua noite com o coronel?",
"Fiz o que foi necessário para proteger meu pseudônimo E seus preciosos despachos. Foi uma sorte para você que ontem à noite eu tivesse outra carta para jogar.",
"Vossa Graça... Srta. Cobham, sinto muito. Falei apressadamente. Agora que conheço você, ficaria muito grato se você os guardasse para mim.",
"O que! Você espera que eu carregue essas malditas coisas de cueca de novo?",
"Se Vossa Graça fosse tão gentil.",
"Depois de uma noite no barco a remo do Sr. Hornblower, acho que poderia dormir no poleiro da gaiola de um papagaio!",
"Nesse caso, Capitão Pellew, você deverá levar estes documentos. O Sr. Hornblower me deu-os para guardá-los em segurança quando fomos capturados pelos espanhóis.",
"Não seja tão duro com seu tenente interino, capitão. Se não fosse pela sua bravura não estaríamos aqui hoje.",
"",
};
