string DLG_TEXT[40] = {
"Tchau, tchau. Talvez fosse melhor se você me chamasse de Milord. Na verdade, sou o Conde de Edrington.",
"Sim, Milorde.",
"Tenha cuidado, Sr. Hornblower. Fique onde está, ou vou mandar atirar em você.",
"Major... Não é o que parece.",
"Tchau, tchau. Talvez fosse melhor se você me chamasse de Milord. Na verdade, sou o Conde de Edrington, comandante do Segundo Batalhão.",
"E encontro você aqui acabando de atirar em um sargento e um tenente. Você está preso.",
"Mas Milord, o tenente atirou no sargento. Eu só atirei no tenente. Quero dizer...",
"Condenado pela sua própria boca. Levem embora o traidor, homens.",
"Milorde!",
"Quem está no comando aqui?",
"Eu sou major. Comandante Horatio Hornblower do...",
"Bom. Bem, estou aqui com os reforços e parece que não é cedo demais. Não podemos ter o exército circulando por todos os lados sob o comando de um oficial da Marinha. Sargento! Você e seus homens se juntarão à coluna. Tenente, cuide deles.",
"Milorde! Estávamos perseguindo os franceses. Tínhamos acabado de expulsá-los de suas posições de armas fora da cidade e os seguimos até aqui. Não tivemos tempo de espetar as armas nem de enterrar os nossos mortos, mas localizámos a sua força principal.",
"Então é ainda mais vantajoso que eu tenha chegado naquele momento. Seremos pelo menos capazes de levar a cabo esta parte da batalha de forma militar.",
"Agora, onde estão essas tropas francesas?",
"No vale ali, Milord.",
"Bom. Então lidere o Comandante, entraremos no vale e então assumiremos nossa linha de batalha.",
"O comandante, o próprio coronel Sir Arthur, me levou para fora do barco para proteger os arredores da cidade, onde descobri que você havia deixado o canhão francês desprotegido. Então segui você até este vale e encontrei nossos homens mortos e insepultos. É claro que os enterrei. Parece que estou esclarecendo bastante a sua situação, Comandante.",
"Mas Milorde, ainda não tivemos oportunidade de reconhecer a posição inimiga. Eu sugeriria que Vossa Senhoria e eu fizéssemos isso primeiro. Também deveríamos levar o Sargento Sharpe junto.",
"Obviamente você pensou mais no assunto do que eu... Sargento! Encaminhe por favor. Chumley! Assuma o comando da coluna e prepare-se para o avanço em nosso retorno.",
"Abençoada seja minha alma se não for o próprio Sir Arthur ali. Venha me ver derrotar os franceses, sem dúvida.",
"Sem dúvida, Milorde.",
"Mas senhor... er, Milorde, há alguns soldados franceses escondidos aqui neste vale, estávamos tentando expulsá-los.",
"Expulse-os! Da praia! Você realmente precisa que eu lhe mostre como travar uma batalha. Aqueles franceses terão saído daqui assim que nos ouviram chegar. Agora, onde estão as tropas francesas?",
"Os sons daquele tiroteio obviamente alertaram os franceses, então teremos apenas que fazer um ataque frontal agora.",
"Se me permite sugerir, Milorde?",
"Sugerir o quê?",
"O pequeno elemento de surpresa que tínhamos desapareceu. Portanto, eu respeitosamente sugeriria, Milord, que você colocasse parte de sua Companhia na praia para impedir que o navio francês desembarcasse qualquer apoio, caso retornasse.",
"Isso faz sentido.",
"Então o resto de nós deveria retornar à cidade e tomar posição lá. Certamente perderemos muitos homens se entrarmos no vale agora, pois há um gargalo e os homens não conseguiram se espalhar o suficiente para evitar serem baleados.",
"Concordo, mas reduzirá o número de homens que temos para essa defesa com o resto deles na praia.",
"Sim, Milorde, mas quando eles ouvirem o início da luta, se não conseguirem ver o navio francês, então terão tempo de vir por trás dos franceses e nós os teremos presos entre nós.",
"Mas como saberão que terão tempo suficiente para deixar a costa se o navio francês estiver à vista?",
"Se o Tenente Quelp for com eles, Milorde, ele saberá quanto tempo o navio francês levará para desembarcar mais tropas e poderá aconselhar seus homens adequadamente.",
"Muito bem... Tenente Chumley! Forme uma coluna com o Tenente Quelp e assuma uma posição defensiva na praia. Voltaremos para a cidade. Vamos agir rapidamente.",
"Empresa! ... Sobre o rosto! ... Marche para a cidade.",
"Concordo. Precisamos de tanto poder de fogo quanto pudermos reunir, não temos homens suficientes para formar uma linha. Será uma batalha puramente defensiva. Pelo menos até o resto do Batalhão aparecer.",
"Bom. Tenente Sharpe, envie os seus fuzileiros para cobrir o nosso flanco. Todos... em posição.",
"Precisamos voltar para lá também, e rápido.",
"",
};
