string DLG_TEXT[46] = {
"Senhor Wolfe. Thomas Wolfe.",
"Continuar.",
"...",
"Cinco anos como timoneiro nos comboios do norte.",
"Uma jovem em Leeds, senhor, com a barriga inchada e um pai zangado.",
"Eu ficaria feliz em senhor.",
"Bom homem.",
"?",
"Soprador de chifre. Hora de se render, eu acho.",
"LOBO!",
"Espero que estejam todos confortáveis, senhores. Vou agora capturar seus fuzileiros navais, que pensam que vão capturar a bateria.",
"Você é um traidor Wolfe..",
"Eu deveria ter esticado seu pescoço quando tive a chance.",
"Eu me renderei, se você garantir que meus homens não serão feridos.",
"Bem, isso é uma reviravolta. Eu sendo seu prisioneiro.",
"De fato. Como você conseguiu aquele saveiro?",
"Cheguei a #sPointe a Pitre#, que estava um caos total graças ao seu ataque.",
"E então?",
"A tripulação do saveiro estava em pânico e desesperada por alguém que lhes desse ordens. Então eu fiz. Eu disse a eles que iríamos ao #sFalaise de Fleur# para denunciar o ataque. Algum capitão britânico fez o mesmo quando #sOxbay# foi atacado há cerca de 50 anos.",
"E agora você pode pendurar",
"Se você fizer isso, você nunca conhecerá meu chefe.",
"Nós já temos. O Capitão Hammond está morto.",
"Charlie Negro? Ele pode ter sido um grande barulho na sua marinha, mas não era o chefe.",
"Então quem é o chefe?",
"Posso muito bem lhe contar, já que você vai arrancar isso de mim de uma forma ou de outra. Você está atrás de Uriah Quelp. Mas você não vai pegá-lo, exceto me deixando sair daqui.",
"E por que deveríamos fazer isso?",
"Devo encontrá-lo em algum lugar perto de #sSanto Domingo#. E não me pergunte o que ele planeja fazer porque ele nunca me contou.",
"Talvez ele não confie em você por algum motivo.",
"Sarcasmo não vai te pegar Quelp. Nem eu, a menos que você me tire daqui.",
"Tudo bem, mas primeiro preciso falar com o comandante da prisão.",
"Vamos para o interior. Ele deveria estar perto de um moinho de vento.",
"Tudo bem vamos.",
".",
".",
"",
".",
".",
"",
"",
"",
"",
"",
"",
"",
"",
"",
};
