string DLG_TEXT[28] = {
".....",
".....",
"Capitão Bartolomeu? Posso falar com você?",
"Claro, Capitão Dierman.",
"Há um problema. O Capitão Elting ainda não voltou.",
"O que? É impossível gastar tanto tempo indo e voltando do claustro.",
"Sem dúvida.",
"Vou procurá-lo na cidade. Esperemos que ele não tenha sido preso pelos guardas. Obrigado por me avisar.",
"Ha! Capitão! Hummm... Você está sozinho. Aconteceu alguma coisa errada com o Capitão Elting?",
"Más notícias. O capitão Elting foi preso no claustro pelos espanhóis.",
"Onde ele está?",
"Não na prisão, mas num lugar secreto debaixo da igreja. E há outro problema, o governador Montavez sabe seu nome e o que fez em Havana.",
"Então, eles vão matá-lo.",
"Na verdade, se nada for feito, amanhã ele será enforcado.",
"Vá em frente! Eu deveria libertá-lo.",
"Não, a culpa é minha se ele foi preso. Eu pedi para ele ir até lá. Esta noite, vou libertá-lo.",
"Você precisa de alguns dos meus homens para isso?",
"Não, obrigado. Será uma missão sorrateira. Não quero alertar todos os guardas desta cidade. Lembre-se, ainda temos uma missão a cumprir aqui.",
"Eu sei, capitão. É por isso que você não deveria ir lá. Se você for preso, a operação contra o forte de San Felipe acabou.",
"Você tem razão. Mas, devo correr o risco. Não tenho escolha e tenho certeza que posso ter sucesso.",
"Como desejar, capitão. Vou esperar até amanhã ao meio-dia. Depois, eu e meus homens retornaremos para Curaçao.",
"Eu entendo.",
"Parabéns Capitão! Você fez isso.",
"Obrigado. Felizmente, tudo correu sem grandes incidentes.",
"E para mim e para os meus homens?",
"Você e suas tropas desembarcarão no forte à beira-mar sem serem detectados, é claro. Prepare o assalto à espera das forças portuguesas no lado oposto do forte. Lembre-se que os ataques portugueses e holandeses devem ser simultâneos para desorganizar a defesa espanhola. Ambos os ataques devem chegar rapidamente ao topo do forte para ter sucesso na operação.",
"Conseguimos! Agora o forte é nosso.",
"Sim, mas por pouco tempo. A guarnição da cidade deve chegar em breve. Vamos instalar um fusível longo no armazém de pólvora. Quero o forte sem pólvora para proteger nossos navios.",
};
