string DLG_TEXT[28] = {
".....",
".....",
"Acho que o Governador Ogeron me apresentou, Capitão Bartolomeu.",
"Sim. Você é o capitão dele, o próprio Arnaud Fontaines.",
"Exatamente. Pronto para atacar o forte?",
"Antes de ir para #sisland_Isla Muelle# precisamos ir para #sFalaise De Fleur#.",
"Porquê este desvio?",
"O capitão Lalliere também participará desta expedição.",
"Notícias muito boas. Será mais fácil com ela também. Ela é muito competente nesse tipo de missão.",
"Verdadeiro. Já notei sua habilidade durante uma expedição em Santiago, em Cuba.",
"Podemos ir?",
"Sim, não há necessidade de perder mais tempo em #sTortuga#.",
"Aaahhhh...",
"Alguém te nocauteou. Deixe-me ajudá-lo.",
"Obrigado, capitão. Ele atacou de surpresa.",
"Quem?",
"Montbars.",
"O que?! Por que ele fez isso?",
"Quando vi a explosão no forte, pousei imediatamente para ajudá-lo. Encontrei Montbars aqui dizendo que pediria ajuda à sua tripulação. Eu estava indo para o forte, quando ele me surpreendeu.",
"Eu entendo agora. Ele deve ter roubado o ouro com a ajuda de sua tripulação.",
"Ele foi estúpido porque os Irmãos da Costa nunca o perdoarão.",
"Claro. Mas, por enquanto, ele tem o nosso ouro.",
"Temos que voltar para #sTortuga# e informar o Governador Ogeron.",
"De fato. Seria impossível encontrar Montbars agora. Ele deve estar escondido, esperando que as coisas esfriem.",
"Se eu soubesse, teria matado Montbars na costa do Aguadilla.",
"Não pense mais, não podemos mudar o passado. Talvez surja uma nova oportunidade.",
"Você tem razão. Adeus capitão!",
"Vê você.",
};
