string DLG_TEXT[124] = {
".....",
".....",
"Capitão Bartolomeu?",
"Sim... Capitão Queiroz, presumo.",
"Você aceitou a missão?",
"Eu fiz. Seu navio está pronto para navegar?",
"Sim capitão. Podemos sair da ilha agora mesmo.",
"Obrigado. Deixe-me falar com meu oficial antes de embarcarmos.",
"Podemos embarcar no navio agora?",
"Sim, vamos lá.",
"Então você acha que os soldados espanhóis estão na selva?",
"Sim, com o capitão Arturo Campos vendo que não estava no navio.",
"Vamos esperar e emboscá-los nesta costa?",
"Não. Como você sabe, a melhor defesa é o ataque. Vamos para a selva, encontrar e matar todos eles. ",
"Feito! Ele está morto.",
"Cumprimos nossa missão. Não há necessidade de ficar mais nesta ilha infestada de piratas e parasitas. Voltemos a #sConceicao#.",
"Vou deixar você ver o Governador sozinho. Agora comando 'A Faisca' novamente, preciso prepará-la para minha próxima missão.",
"Claro. Você não precisa me acompanhar até a Câmara Municipal, eu irei relatar suas boas ações.",
"Foi uma honra trabalhar com você. Adeus capitão.",
"Obrigado, vejo você novamente algum dia, espero.",
"Capitão Bartolomeu!",
"Que bom ver você, Capitão Queiroz. Muito tempo se passou desde nosso último encontro.",
"De fato. Agora, nossa nova missão é muito mais importante.",
"Sem dúvida. Você conhece os detalhes da missão?",
"Sim. Conversei muitas vezes com o Governador nestes últimos dias. Eu e meus homens ficaremos escondidos no navio até iniciar o ataque.",
"Certo. Também serei ajudado por um amigo holandês, o capitão Elting; você pode vê-lo por perto. Ele nos seguirá até Cartagena.",
"Bom de se ouvir. Mas o governador Barreto me disse que poderíamos contar também com a ajuda de soldados holandeses. É verdade?",
"Eu confirmo. Se tivermos a possibilidade de uma ação militar, os holandeses nos ajudarão.",
"Bem, acho que estamos prontos para iniciar a missão. Vamos agora?",
"Sim, vamos lá. Nós temos muito o que fazer.",
"O que aconteceu com o Governador?",
"Tudo está bem. Ele me convidou para uma festa hoje à noite em sua residência.",
"(Tom irônico) Muito melhor que a minha situação.",
"Desculpe, se você precisa ficar no navio. Tentarei encontrar uma maneira de atacar a cidade o mais rápido possível para reduzir sua espera.",
"Finalmente, o Governador está de volta. Essa espera foi interminável, estou ansioso para que a operação comece.",
"Ainda devemos esperar a volta do Capitão Elting. Espero que nada de grave tenha acontecido com ele.",
"O que você vai fazer hoje?",
"Claro, preciso falar com o Governador. Quero saber se a missão dele falhou como desejo. Não se preocupe capitão, sua espera está prestes a terminar. Tenho certeza que nossa operação começará em alguns dias.",
"E a operação?",
"Amanhã à noite a operação começará. Os detalhes serão explicados aqui, logo após minha visita ao Governador.",
"Muito bem, todos esperam impacientemente por este momento.",
"Eu sei. Amanhã o que faremos será lembrado como a maior batalha contra os espanhóis.",
"Então você quer dizer que eu e meus homens atacaremos o forte perto do túnel?",
"Certo. Antes disso, mate todos os guardas entre o porto e a praça. Seja discreto e esconda os cadáveres, não quero que a vila seja avisada pelas tropas portuguesas. Se possível, tentarei pegar você na praça depois de capturar o navio de guerra.",
"Graças a Deus. Olha Você aqui! Você capturou o navio?",
"Claro, capitão Queiroz. Mas pensei que você já estaria no túnel. Onde está Emílio?",
"Esse é o problema. Ele ainda não trouxe a chave da porta. Espere! Ele acabou de entrar na praça.",
"Então, vamos procurar a chave no escritório do almirante.",
"Certo.",
"Quase meia hora perdida e impossível encontrá-la. A situação é muito ruim.",
"Ainda temos a possibilidade de encontrar a chave. A casa da filha dele também fica na praça. Talvez ele tenha ido lá para verificar se está tudo bem, visto que sua filha estará em casa logo depois que eu sair de Cartagena.",
"Você tem razão. Há uma chance de encontrar a chave lá.",
"Fique aqui. Vou verificar isso e volto logo.",
"Então?",
"Eu tenho uma chave!",
"Ótimo! Capitão.",
"Espere, espere... O problema é que esta chave não parece ser uma chave para abrir a porta do túnel, mas para outra coisa.",
"Não me diga que não é a chave certa...",
"Humm... Talvez seja usado para uma espécie de sistema mecânico que abre a porta. Dê-me alguns minutos, vou tentar algo.",
"Você tem razão. Nunca pensei que os espanhóis pudessem fazer tal coisa para proteger o túnel.",
"Uma ideia inteligente, de fato. O Governador e o Almirante nunca disseram que existia um sistema no relógio que permitisse abrir a porta.",
"Agora, só precisamos encontrar o caminho certo para o forte.",
"Sim, siga-me e tenha cuidado. Não sabemos se há guardas neste local.",
"Eu não esperava uma briga aqui",
"É por isso que eu disse que deveríamos ter cuidado. Vamos Capitão Queiroz, suspeito que já estamos perto do forte.",
"O túnel parecia um labirinto.",
"Sim. Pelo menos estamos dentro do forte. Agora, devemos agir rapidamente. Vamos!",
"O que?",
"A porta está trancada.",
"De novo! Não me diga que existe outro sistema para abrir esta porta como o do escritório do almirante.",
"Espero que não.",
"Tenho uma ideia, mas não tenho certeza se é boa. O que você acha de colocar uma granada com pavio longo para destruir a fechadura?",
"Isso funcionaria, é claro. Porém, não sabemos se há soldados neste local. E se a nossa presença for detectada, a nossa operação termina.",
"Então o que você sugere?",
"Vou procurar aqui qualquer coisa que possa me ajudar a abrir a porta. Espere um pouco...",
"Parabéns mais uma vez, Capitão!",
"Obrigado. Felizmente, o espanhol não sabe proteger os seus próprios sistemas de segurança. Vamos em nossa missão.",
"Que sorte! Vimos este antes de ele avisar seus companheiros.",
"De fato. Como você disse, temos sorte. Deveríamos estar perto da saída. Siga-me, Capitão Queiroz.",
"Só vejo um soldado deste lado.",
"Hum...",
"Mesmo dois não é um problema para mim. Eu só preciso usar minhas facas envenenadas para matá-los discretamente. Depois, verificarei se o capitão Elting e as tropas holandesas estão prontos para atacar.",
"Isso soa bem. Eu e meus soldados esperaremos aqui até seu retorno. Boa sorte.",
"Eles estão atirando em nós!",
"VOLTE PARA ONDE ESTÁMOS! ESTAMOS EXPOSTOS AQUI!",
"Você viu de qual local eles estão filmando?",
"Sim, do alto do forte.",
"Você não me disse que os espanhóis instalaram canhões lá.",
"Porque da última vez que visitei o forte eles não estavam. De qualquer forma, não acho que sejam canhões. Eu não os vejo.",
"Argamassa?",
"Eu penso que sim. Uma argamassa pode ser instalada de forma fácil e rápida.",
"Perdemos o efeito surpresa. A situação é pior para nós agora.",
"O Capitão Elting e Dierman certamente iniciaram o ataque, então devemos contra-atacar. O problema é que não temos armas poderosas para aniquilar rapidamente o máximo de soldados.",
"Não se preocupe. Eu tenho uma solução para isso. Alguns dos meus homens têm uma arma-foguete que pode matar pessoas instantaneamente.",
"Excelente! Peça aos seus soldados para equiparem os foguetes. Devemos chegar ao outro lado deste local o mais rápido possível para evitar os tiros dos morteiros.",
"ACORDA, CAPITãO! Você está bem?!",
"O que aconteceu?",
"Uma explosão ocorreu perto de você.",
"Devemos destruir a argamassa o mais rápido possível",
"De fato. Vamos agora. Novas tropas inimigas estão chegando.",
"Esta seção está 'limpa'.",
"Vamos continuar nosso caminho.",
"Agora, estão a disparar contra as tropas holandesas!",
"Eles devem ter um segundo morteiro e não apenas um como pensávamos. Vamos agir rapidamente.",
"E agora o topo do forte?",
"Sim, siga-me. Vamos fazer com que definitivamente os morteiros fiquem quietos.",
"Capitão Elting e Dierman estão lá embaixo.",
"Bom! Vamos vê-los para comemorar nossa vitória.",
"Espere! Ainda não. Eles ainda estão lutando contra os espanhóis.",
"O que?! nós não matamos todos eles nesta área?!",
"Eu também não entendo, mas devemos ajudá-los rapidamente.",
"Com que rapidez? Se precisarmos de alguns minutos para nos juntarmos a eles.",
"Pegue este mosquete. É uma arma poderosa e você poderá matar os soldados da parede.",
"Obrigado! Eu vou agora.",
"Podemos levantar âncora e voltar para #sConceicao#?",
"Dê-me meia hora antes de sair de Cartagena, preciso falar com alguém. Claro, você navegará no navio enviado espanhol, agora tenho meu novo navio de guerra.",
"Finalmente em casa!",
"De fato. A propósito, esqueci de fazer isso em Cartagena, mas aqui está seu mosquete de volta.",
"Não, fique com ele.",
"O que?! Mas esta arma é muito cara.",
"Sim, mas você merece pelo que fez lá. Considere isso como um sinal de nossa amizade.",
"Obrigado capitão Queiroz. Não vou esquecer disso.",
"Vou agora mesmo à Câmara Municipal trazer boas notícias ao Governador.",
"Excelente. Estarei aí em alguns minutos.",
};
