string DLG_TEXT[30] = {
"Algum problema, senhor?",
"Não. Não importa.",
"Obrigado, capitão! Não reconhecemos seu novo amigo, mas sabíamos que estaríamos livres assim que o vissemos aqui. Que alívio, pensamos que estávamos a caminho de conhecer nosso criador!",
"Obrigado William. Eu nem estaria aqui se ele não tivesse concordado em ajudar a resgatar você.",
"Acho que estamos seguros agora",
"Certo! Então o que aconteceu com Emilio, onde ele está?",
"Ele escapou para a selva a caminho da prisão.",
"Eu vejo. Você sabe para onde ele foi?",
"Ele me disse que precisava chegar a #sSantiago#, encontrar um navio e escapar de #sisland_Cuba#.",
"Obrigado Javier pela informação.",
"Capitão! Como você chegou aqui? Então é verdade. Você realmente escapou deste navio e está vivo, e os guardas nos disseram que mataram e jogaram vocês no mar - bastardos mentirosos!",
"Sim meus amigos. Fiquei feliz por fugir, mas não suportaria deixar você apodrecendo neste porão. HA-HA! Que dia! Agora preparem o navio, ela é a nossa salvação, vou verificar se ainda está tudo sob controle no cais.",
"Quais são as ordens capitão?",
"Descarregue o açúcar, a canela e as frutas. Vou pechinchar com Eugene um preço justo para esses produtos.",
"Capitão! Somos atacados!",
"O que você está falando? Atacámos aqui, como, não havia vela no horizonte quando atracamos!",
"Piratas vieram da selva e capturaram o 'Santiago'. Fomos pegos de surpresa e não fomos suficientes para defender o navio.",
"Arrase tudo! Eles já saíram da costa?",
"Ainda não. Eu escapei quando eles estavam pegando nossas mercadorias descarregadas e recarregando-as. Maldita seja a sua pele arrependida!",
"Vamos pegá-los antes que possam levantar âncora.",
"Para para! Nós nos rendemos!",
"Parabéns, seu bando de escória, vocês me seguraram por tempo suficiente para meu navio escapar. Diga-me quem é o seu chefe, se você quiser viver!",
"É Pedro Rivera. Ele já está embarcando no navio, nos deixou para morrer, o filho podre do macaco.",
"Pedro Rivera?! Essa é a escória que funcionou para mim, me custou muitas moedas e quase nos matou a todos.",
"Sim, ele nos contou e que foi uma retribuição porque você aceitou o emprego dele quando ele estava preso. Ele viu você atracar o navio e decidiu emboscar os poucos tripulantes que restavam aqui.",
"Eu deveria ter matado aquele desgraçado depois do ataque aos armazéns em #sisland_Cuba#. Diga-me para onde ele está indo?",
"Nós não sabemos.",
"Não me leve para passear. Não tenho mais paciência nem piedade.",
"Juro! Não temos ideia. Ele não tem nenhum outro refúgio fora desta ilha. Não podemos dizer o que não sabemos, por favor, poupe-nos.",
"Limpar! Se eu te ver de novo eu abro suas gargantas!",
};
