string DLG_TEXT[53] = {
".....",
".....",
"Sim?",
"Capitão Damski?",
"Certo. O que você quer?",
"O vice-almirante me enviou. Você deve me fornecer algum novo tipo de Xebec.",
"O navio é para você!!?",
"De fato. Por que você pergunta?",
"Eu entendi que ela seria dada a um capitão espanhol de alta patente. Você não é espanhol, é? Este é um navio especial!",
"Sou holandês, meu nome é Johan Elting. Seu nome também não é espanhol, não é?",
"É verdade que não sou espanhol. Fui capitão pirata até há poucos anos.",
"O que você está fazendo em #sHavana#?",
"Fui capturado e preso pelos espanhóis.",
"Parece que partilhamos o mesmo destino.",
"O Vice-Almirante, de alguma forma ele sabia que eu era um bom construtor naval antes de me tornar um pirata, me pressionou para o serviço em vez da forca, eu não discuti.",
"Eu entendo e simpatizo.",
"Mas não estou aqui para contar a história da minha vida, vamos ao que interessa - tenho que explicar as características do meu último trabalho.",
"Ela deve ser um navio muito especial!",
"Sim, de fato, ela excede o padrão em todos os aspectos. O porão de carga é o dobro do normal, mais canhões de maior calibre.",
"Ela deve ser mais pesada e mais lenta.",
"Não, porque o casco foi feito com uma madeira recém-descoberta, encontrada apenas aqui no Caribe. Esta madeira é mais forte e mais leve do que qualquer outra usada na Europa.",
"Estou impressionado.",
"Você deveria estar... e também, ela é rápida e ágil. Nas mãos certas, ela levará surpresa e morte a muitos inimigos desavisados e trará glória e fama ao seu capitão e à tripulação.",
"Mal posso esperar para vê-la. Sua fé nela é contagiante.",
"Ela está no porto esperando por você, capitão. Trate-a bem.",
"Meu oficial designado também estará lá, sem dúvida. Obrigado pelo navio. Adeus Capitão Damski!",
"Boa noite, padre. Acho que você cometeu um erro, eu não pedi para você vir",
"(Elting para Damski) Não somos padres, Capitão Damski. Você não reconhece minha voz?",
"Sim, já ouvi mas não me lembro onde.",
"(Elting para Damski) Falei com você no estaleiro quando você me deu o 'El Diablo'.",
"Capitão Elting?!",
"(Elting para Damski) Ele mesmo e a pessoa que está comigo é o Capitão Bartolomeu.",
"Pensei que as autoridades o tivessem matado depois da sua deserção.",
"(Elting para Damski) Eles tentaram muitas vezes, mas falharam, como você pode ver.",
"O que você está fazendo aqui?",
"(Elting para Damski) Preciso da sua ajuda.",
"O que exatamente você quer?",
"(Elting para Damski) Você sabe alguma coisa sobre um tesouro asteca que a Frota de Prata transmitiu?",
"Um tesouro? Não, nada. Como você sabe disso?",
"(Elting para Damski) Uma história muito longa, explico outro dia. Nada sobre o que poderia ter sido descarregado dos navios?",
"Se no porto um tesouro fosse descarregado, certifique-se de que as pessoas falariam sobre isso.",
"Espere! Eu poderia te ajudar.",
"(Elting para Damski) Como?",
"Sei que o Capitão da Frota, Capitão Villalobos, deve ver o Governador amanhã de manhã. Também estarei na Câmara Municipal. Alguns dos navios precisam ser reparados antes de saírem de Havana. Parece que eles encontraram uma tempestade durante a viagem.",
"Podemos confirmar. Tivemos até que ligar para #sisland_Khael Roa#.",
"Ainda preciso de uma confirmação dos danos, mas aposto duas semanas para a sua estadia.",
"(Elting para Damski) Humm... A melhor solução seria sequestrá-lo após a reunião e antes que ele se juntasse à tripulação no porto. Sem esquecer, precisamos ser discretos se não quisermos que todos os guardas desta cidade nos ataquem.",
"Sairei da Câmara Municipal antes dele, visto que ele terá outros assuntos para conversar com o Governador. Eu poderia estar com você para avisar sobre sua chegada.",
"(Elting para Damski) Tudo bem, acho que temos um plano. Podemos ficar na sua casa até amanhã de manhã?",
"Claro.",
"Obrigado!",
"Capitão! Ele está vindo, mas há dois guardas com ele.",
"(Elting para Damski) Não se preocupe. Eu e Bartolomeu cuidaremos deles. Agora, volte ao seu trabalho antes que ele te veja conosco.",
};
