string DLG_TEXT[54] = {
".....",
".....",
"Capitão Bartolomeu, ouvi muito dos seus feitos.",
"Obrigado, Capitão Montbars. A sua reputação também é conhecida em todo o arquipélago.",
"Então, somos parceiros segundo o Governador Ogeron.",
"Sim. Estou interessado naquela história das reservas de ouro em #sisland_Isla Muelle#.",
"HA-HA! Que pirata não estaria interessado em ouro?!",
"Você tem razão. Caso contrário, você conhece nossa missão Capitão Montbars?",
"Sim. Temos que sequestrar um ex-pagador espanhol detido na Base Naval Britânica de Antígua.",
"De fato. Acho que uma maneira de fazer isso é infiltrar-se na cidade à noite, quando tudo está tranquilo.",
"A única maneira, concordo, é ver a cidade cheia de soldados durante o dia, mas ainda não isenta de riscos à noite.",
"Sem risco - sem ganho. Vamos, capitão. Não podemos permitir que o tesoureiro seja libertado antes do nosso 'resgate'.",
"Aqui estamos! E agora Capitão?",
"Claro, não podemos entrar na cidade pelos portões. Perigoso demais...",
"Conheço um caminho que é seguro.",
"Como?",
"Perto da cachoeira existe uma passagem subterrânea que leva ao centro da cidade.",
"Excelente.",
"Porém, é usado como esconderijo pelos bandidos da ilha.",
"Não é um problema. Acho que podemos lidar com eles.",
"Tudo bem, vamos então.",
"Siga-me, capitão. Estamos perto da passagem.",
"Esta é a entrada, vamos entrar.",
"Eu irei sozinho.",
"O que?",
"É melhor que eu cumpra esta parte da missão sozinho, dois serão notados onde um não será.",
"Tem certeza, capitão?",
"Sim, acredite em mim. Fique aqui e proteja a entrada. Se eu não voltar aqui dentro de uma hora, venha me buscar.",
"Como você quiser.",
"Caramba! Uma patrulha está chegando.",
"Nós não temos escolha. Vamos combatê-los!",
"Parabéns Capitão, você libertou o espanhol. No entanto, o jogo acabou - precisamos sair de Antígua agora.",
"Sim, estamos em perigo. Vamos voltar aos nossos navios e seguir para #sTortuga#.",
"Devíamos torturá-lo em vez de interrogá-lo. Estamos apenas perdendo nosso tempo!",
"Eu não concordo. Ele pode morrer se o torturarmos.",
"Eu tive uma ideia.",
"Humm.. Concordo com Roxanne, mesmo que eu ache que poderíamos fazer isso sem mais ajuda.",
"O navio de Roxanne está no porto.",
"Ela deve estar em algum lugar da cidade. Vamos começar a pesquisa.",
"Todos os canhões são destruídos.",
"Os canhões do forte, sim. Mas ainda não estamos seguros. Uma pequena companhia espanhola acaba de colocar um canhão de campanha do outro lado da praia... Talvez o Capitão Fontaines consiga acertá-lo a partir do seu navio.",
"Talvez. Mas, um ataque rápido a esse canhão pode evitar muitas mortes do nosso lado.",
"Você tem razão. Não deixe que eles atinjam você, mova-se rapidamente e não em linha reta. Vamos!",
"MOOOVEEE!!!",
"Olha essas caixas! deve haver uma fortuna em ouro. Somos todos RICOS, muito, muito RICOS!",
"Fantástico, estaremos rolando nele. Porém, antes de carregar as caixas, é melhor verificarmos se não há outros soldados dentro ou ao redor do forte, não queremos ser pegos de calças abaixadas.",
"O que? VOCÊ AQUI?!",
"Surpreso, não é? Você achou que eu simplesmente ficaria sentado e deixaria você gastar minha parte do ouro sem fazer nada?",
"No Caribe, apenas os mais inteligentes serão ricos.",
"Para mim, inteligente não é sinônimo de traiçoeiro. Onde está o ouro, canalha?",
"Você ainda é ingênuo. Você acha que vou te contar, só porque você pergunta?",
"Talvez você esteja disposto a falar com minha lâmina.",
"Você precisa de uma boa aula de esgrima.",
"Como você diz em seu país: En garde!",
 
};
