string DLG_TEXT[110] = {
".....",
".....",
"Acabou Capitão! A cerveja foi carregada.",
"Excelente! Embarque no navio que partiremos para #sisland_Cuba# em alguns minutos.",
"Espere um pouco! Este soldado é um desertor.",
"Não, capitão. Ele foi sequestrado por alguns bandidos; Eu o libertei.",
"Se você contar a verdade, receberá uma recompensa. Mas por enquanto siga-me, tenho que te levar ao forte para que meu comandante te questione.",
"Eu vou mais tarde.",
"Claro que não. Até que esta questão seja resolvida, vocês são meus prisioneiros.",
"Eu não vou te obedecer. Então esqueça-nos, capitão.",
"Vou te ensinar a obediência.",
"Eu vi você matando essa mulher. Não se mova!",
"Parabéns Capitão! Ouvi dizer que você afundou o 'Joyeuse'.",
"Agora você acredita nas minhas habilidades?",
"Devo dizer que sim. Pegue o dinheiro: 20.000 moedas de ouro para esse trabalho. Tenho o hábito de ver quase todos os dias um Capitão que quer trabalhar para mim. Então, é difícil para mim distinguir os bons.",
"Eu entendo. Caso contrário, você tem uma nova missão para mim?",
"Sim. Agora posso confiar em você, gostaria que você fosse com um dos meus capitães para #sisland_Khael Roa#.",
"Por que #sisland_Khael Roa#? É uma ilha deserta.",
"Na verdade, mas a Coroa Britânica quer que construamos um assentamento lá. A localização estratégica daquela ilha é importante para as autoridades.",
"Então, é uma missão exploratória?",
"Sim. Mas deixe-me apresentar o capitão que você acompanhará. Aqui está o Capitão Tripper, um dos meus melhores capitães.",
"Ha! Olha Você aqui. O Capitão Tripper veio há poucos minutos e contou o que aconteceu em #sisland_Khael Roa#.",
"Os franceses já estão lá. Tivemos até que lutar contra um de seus navios de guerra para deixar a ilha.",
"Eu sei. Isso é realmente irritante! Terei que preparar uma pequena frota nas próximas semanas para expulsar definitivamente os franceses de #sisland_Khael Roa#. E conto com a sua ajuda para essa missão. Caso contrário, pegue essas 20.000 moedas de ouro. O capitão Tripper disse que você foi muito eficiente.",
"Obrigado Almirante. Até que a frota esteja pronta, talvez eu possa fazer algumas missões para você.",
"Bom, no momento não tenho nada realmente interessante...",
"Tem certeza? Mesmo em uma missão de escolta, por exemplo, minha tripulação não gosta de ficar parada por muito tempo?",
"Bem, vou ver o que posso fazer, ah, tenho uma, mas não achei que você estaria interessado nesse tipo de missão.",
"Por que não?",
"Preciso enviar um navio mercante para #sisland_Isla Mona#. Eu estava pensando em pedir a um dos meus capitães juniores para escoltá-lo..",
"Estou interessado. Deixe-me acompanhar o navio.",
"Realmente?! Mas você ganhará pouco pela missão. Apenas 5.000 moedas de ouro.",
"Isso não é um problema. Isso permitirá que eu e minha equipe trabalhemos até a nova missão em #sisland_Khael Roa#.",
"Como você quiser. O capitão do navio mercante estará no cais finalizando o carregamento, basta falar com ele lá. Mas antes de conhecê-lo, você precisará deste passe livre que lhe permite permanecer em #sisland_Isla Mona#.",
"Obrigado Almirante. Vou encontrá-lo no cais!",
"Espere um pouco, capitão!",
"Sim? O que você quer?",
"Preciso informá-lo que um de seus homens foi preso.",
"O que? Onde ele está? Por que as autoridades o prenderam, se ele estiver bêbado de novo, eu vou arrastá-lo?",
"Ele está na Casa do Comandante com o Capitão Wilfred Burman. Ele explicará detalhadamente os motivos de sua custódia.",
"Como chego à casa do Comandante?",
"Fora do porto. Você tem um caminho a percorrer para chegar lá.",
"Obrigado. [PENSA: esse ato correu bem, precisamos ter mais cuidado.]",
"VOCÊ AQUI ?! TRAIDOR!",
"(Soldado conversando com o vice-almirante Benavides)",
"Excelência, estamos sob ataque!",
"Eu estava com a minha companhia na aldeia perto de #sHavana#, verificando se os contrabandistas não escondiam alguma mercadoria naquele local quando muitos soldados holandeses nos atacaram. Eu sou o único que conseguiu escapar.",
"Não se preocupe, Capitão Elting, seu prisioneiro não poderá escapar. Guardarei no bolso do meu uniforme as chaves da prisão. Ninguém vai libertar esta mulher.",
"Obrigado, capitão. Ela só ficará no forte por alguns dias. Vendo a quantidade de soldados neste lugar, concordo que ela não pode fugir.",
"Ninguém aqui, capitão! Tem certeza que eles tiveram que vir aqui?",
"Sim... Pelo menos pelo que o seu Governador disse. Talvez eles tenham visto as tropas nos seguindo e tenham fugido. Vamos esperar um pouco e se eles não vierem iremos direto para o navio deles.",
"Obrigado, capitão! Esses cães estavam prestes a nos executar.",
"Sem problemas...",
"Morgan, Bartolomeu e o traidor Elting... Que bela fila de bastardos!",
"(Elting para Cáceres) Noto que eu e meus camaradas somos suficientemente famosos para sermos reconhecidos à primeira vista. Porém, vendo as palavras que você usa para nos definir, parece que você sabe receber visitantes. Essa deve ser a conhecida hospitalidade espanhola.",
"(Cáceres para Elting) Você certamente está aqui para roubar o tesouro asteca, mas não vou deixar você sair vivo do meu forte, pequeno excremento de mosquito.",
"(Em direção a Cáceres) É uma pena manchar de sangue um terno tão fino, mas é isso que você quer. En garde!",
"Sim, quem é você?",
"Deixe-me apresentar-me, sou Dom Guillermo, o enviado do nosso rei...",
"Ah, eu sei, eu sei... Dom Guilherme. Suponho que você esteja aqui para obter algumas informações para o seu relatório.",
"Certo, onde está o almirante?",
"Ele não está aqui. Ele está em missão com o Governador e sua frota.",
"Claro, eu deveria ter pensado que ele estaria com o governador na missão em Willemstad. Vou deixar, mas pouco antes vi no Porto um navio de guerra chamado San Martin. Você pode me dizer quem é o capitão dela?",
"É o navio de Ortega.",
"Sebastião Ortega? O pretendente de Lúcia Montavez?",
"Sim senhor. O pretendente da filha do Governador.",
"Humm.. Muito bem... Estarei aqui novamente depois que o Almirante voltar. Obrigado pela ajuda.",
"Meu amigo, você deveria se mudar desta casa.",
"Quem é você para falar assim comigo? Você não sabe quem sou eu?",
"Sim, eu sei quem você é. Você é um criador de problemas desde que veio para Cartagena. Repito pela última vez, saia deste quadrado imediatamente, caso contrário sua saúde poderá 'deteriorar-se' rapidamente.",
"Chega dessa palhaçada! Ninguém pode me ameaçar. En garde!",
"Você está ferido? O que está acontecendo ?",
"Finalmente você veio. É assim que os soldados defendem as pessoas atacadas por bandidos em Cartagena?",
"Desculpe senhor. É a primeira vez que algo tão sério acontece na praça.",
"Fique mais atento para a próxima vez e fique feliz por eu não denunciar seu comportamento ao Governador quando ele voltar.",
"Minhas desculpas, senhor. Não cometerei tal erro novamente.",
"Sim?",
"É a Casa de Dom Ortega?",
"Sim senhor. Você veio falar com ele?",
"Sim, você poderia anunciar minha vinda?",
"Infelizmente, ele não está aqui. Ele me disse que precisava ver algumas pessoas na Câmara Municipal.",
"Ah.. Muito bem, estou indo para lá. Obrigado pela ajuda.",
"Senhor, pare a luta. Dom Ortega está caído.",
"Eu não luto contra as pessoas. Ele pode ficar feliz por estar levemente ferido. Nossa disputa acabou.",
"Senhor?! É um prazer vê-lo novamente.",
"Obrigado, soldado. Então não houve problema aqui desde a última vez?",
"Não, Dom Guilherme. Calmo e quieto como sempre.",
"E... Nada no resto da cidade?",
"Bem, ouvi dizer que um pirata holandês foi preso no claustro.",
"[PENSA: Droga!] O que você quer dizer?! Isso é uma piada? O que um pirata pode fazer num claustro?",
"Este é o mesmo pensamento que tive quando soube disso.",
"Você não tem mais informações sobre a prisão?",
"Nada mais. Ouvi a história de um dos meus companheiros esta manhã, mas não sei os detalhes.",
"Humm... Bem, gostei de falar com você, mas devo ir embora agora. Tenha um bom dia, soldado.",
"O que temos que fazer agora?",
"Verifique dentro do navio de guerra se há mais soldados. Não acredito que lidamos com todos eles.",
"Caramba!! Olhe para suas costas!!",
"Feito! Capitão. O navio é nosso. Foi um duelo incrível na jarda",
"Obrigado. Fiquem aqui com os vossos companheiros, vou juntar-me às forças portuguesas na praça. Quando a batalha começar no forte, afunde todos os navios espanhóis que se aproximam do porto. Não quero um navio atirando no forte enquanto luta contra a guarnição do forte.",
"Você! Siga-me, preciso da sua ajuda para a luta no forte.",
"Errado. Outro fica do lado do Porto.",
"Obrigado pela informação.",
"ALARME!! ALARME!!",
"Caramba!",
"Capitão! Há mais soldados deste lado. Eu estou indo ai.",
"NãO! ESPERE POR MIM!",
"Aaarrgg... Desculpe, capitão. Eu teria esperado por você antes de lutar contra esses soldados.",
"Esquecer! Você está gravemente ferido?",
"Não muito. Mas acho que não posso mais ajudá-lo esta noite.",
"Não se preocupe. Quase terminamos a luta. Descanse um pouco aqui. Depois de capturar o forte, vou levá-lo ao nosso novo navio de guerra.",
};
