string DLG_TEXT[18] = {
"....",
"....",
"Olá capitão! Prazer em conhecê-lo.",
"Olá Capitão Mansveldt. Seu nome é familiar.",
"Talvez você tenha ouvido alguém falando sobre minhas expedições. Ataquei as colônias espanholas muitas vezes e tive muita sorte com meus esforços.",
"Claro, agora me lembro! Você é conhecido como o líder pirata de #sisland_Redmond#, sua fama se espalhou por toda parte.",
"Na verdade, mas sou um velho pirata. E muito provavelmente, o Capitão Morgan me sucederá.",
"É claro que eu entendo.",
"Capitão, seria melhor não perder tempo com conversa fiada. Por favor, vá para o seu navio. Iremos acompanhá-lo no devido tempo.",
"Muito bem, vejo você a bordo.",
"Agora sabemos que a ilha não está deserta.",
"Sim e é perigoso. Temos que estar em guarda. Mantenha os olhos abertos e as armas em mãos, siga em frente.",
"O porto parece calmo. Mesmo a frota espanhola não tem tripulação no momento.",
"Muito estranho...A única coisa que temos certeza é que o trem prateado ainda não chegou...",
"A prata está carregada Capitão.",
"Ótimo! Vamos navegar para #sTortuga#. Temos muitos negócios para fazer lá.",
"Capitão, tive o prazer de trabalhar com você, mais uma missão bem-sucedida. Talvez nos encontremos novamente..",
"Talvez. Adeus Capitão Mansveldt.",
"",
};
