stringDLG_TEXT[26] = {
".....",
".....",
"Capitão Elting? O que você está fazendo aqui?",
"Você pode explicar, Elting, quem são essas pessoas que te acompanham?",
"Deixa eu te contar: eu sou Bartolomeu o Portugues e essa mulher é Roxanne Lalliere.",
"O que você está fazendo na selva? Você deveria estar em uma prisão como Roxanne!",
"Isso é vida. Houve uma pequena mudança no plano. Agora, o capitão Elting está conosco.",
"Eu sabia que não poderíamos contar com a lealdade de um holandês. Todos traidores!",
"*tom irônico* Não seja tão desagradável. Suponho que você não nos deixará ir para a cidade de Alice.",
"*tom irônico* Devo te responder?",
"Eu não acho. Deixe que nossas armas façam isso.",
"Parar! O que você está fazendo aqui?",
"Estamos tentando encontrar um pedaço confortável de grama macia para rolar... alguma privacidade seria apreciada..",
"Perto de uma área militar a esta hora, não acredito em você. Eu prendo vocês dois, podemos descobrir a verdade mais tarde.",
"O que? Você está louco?!",
"Louco!!! Insultar um oficial da coroa espanhola é uma ofensa, vocês só estão piorando a situação para si mesmos.",
"Não me importo se você acha que eu te insultei. Ninguém prende Bartolomeu o Português.",
"Bartolomeu? O pirata?",
"Claro, o pirata. O que você estava pensando?",
"Você veio libertar Roxanne Lalliere tal como o vice-almirante Benavides previu. A propósito, aposto que Roxanne é a mulher que acompanha você.",
"Sim, Roxanne em toda a sua glória. Eu sei que você estava preparando uma armadilha para me prender. Elting já explicou isso.",
"E onde está Elting?",
"Ele está dormindo na prisão... um sono eterno.",
"Desgraçado! Chegou a hora de você e seu amigo morrerem.",
"Você não é o primeiro a dizer isso e não será o último.",
"Filho de um sapo, em breve provarei que você está errado...",
};
