stringDLG_TEXT[110] = {
"Olá amigo! O que você quer?",
"Olá senhor, você é Eugene Martin?",
"Ah sim, sim! Como você sabe meu nome? Por quê você está aqui?",
"Conheci Pierre Delacroix em #sPort au Prince#. Ele disse que talvez você estivesse procurando contratar capitães adequados para seus navios.",
"Aquele Pierre, um homem bom, sempre atento às novidades do arquipélago para mim, tenho alguns cargos, que experiência você tem como Capitão?",
"Fui capitão de um navio mercante durante anos em Portugal, desisti daquela vida miserável para fazer fortuna aqui.",
"Humm..experiência anterior e desejo de ganhar dinheiro rápido. Você percebe, meu amigo, eu não vendo bens legais....",
"Eu entendo. Mas você paga de acordo com o alto risco desse trabalho, não é?",
"Claro. O pagamento depende das mercadorias que você deve entregar. Quanto mais valiosos forem os produtos, maior será a sua comissão.",
"Isso é o que eu queria ouvir. Então... você tem um navio para mim?",
"Mais frontal que um rato de esgoto com dente de ouro, você pode ser exatamente o que eu preciso. Há poucos dias, o capitão de um dos meus navios foi preso pelas autoridades francesas em #sPort au Prince#..",
"Espero que não por causa do seu ofício, não quero ir para a prisão antes de começar.",
"Não. Esse imbecil brigou na taverna e agora está preso há dez dias, minha reputação de pronta entrega está em jogo. Não posso me dar ao luxo de aceitá-lo de volta após sua libertação, ele é muito 'problemático'... você pode ficar com o emprego dele.",
"Excelente! Faço um novo amigo, consigo uma posição adequada e um inimigo em potencial - se aquele capitão descobrir que aceitei o emprego dele - tudo em um dia. Eu amo esse lugar. Quando eu começo?",
"Agora mesmo! Encomendei a entrega de uma carga de sândalo para #sisland_Falaise de Fleur# com entrega prevista para as próximas semanas. Minha barca está atracada em Boca de Hubon. Vá até a taberna deste acampamento e procure Emilio Soares. Ele será seu oficial durante a viagem. Entretanto, enviarei um mensageiro a Boca de Hubon, para dizer à tripulação que você é o novo capitão.",
"Muito bem. Vou procurar o Emilio.",
"Desacelere por um minuto! Tenho que te avisar: não me traia nem tente roubar meu navio e minha carga porque mesmo que a tripulação não te mate, enviarei alguns homens atrás de você para lhe dar uma lição. Inteligente?",
"Não se preocupe. Você pode confiar em mim, eu preciso de você tanto quanto você precisa de mim, e nunca esqueço um favor ou ajuda que recebo.",
"Você tem dois meses para cumprir esta missão ou perderá seu salário. Não se esqueça. Se você tiver sucesso, pagarei 10.000 moedas de ouro. E antes que eu me esqueça, pegue este mapa que vai te ajudar a conhecer esse arquipélago.",
"Entendido. Vejo você em breve!",
"Ah! Olha Você aqui. A viagem correu bem?",
"Sim, sem grandes problemas, e ele me deu a seda.",
"Excelente, aqui está sua comissão: 10.000 moedas de ouro. Observe bem, esse dinheiro não é só para você, mas também para pagar a tripulação e comprar provisões, qualquer outra coisa que você ganhar é sua.",
"Obrigado. Isso é bom, moeda conforme prometido e sem negociação de pagamento, gosto desse trabalho!",
"Fico feliz em saber disso, porque já está de volta ao trabalho, você tem que ir para #sisland_Douwesen#.",
"Agora?! Vou buscar provisões no caminho, e quem devo encontrar desta vez?",
"Outro contrabandista... Pegue o mapa da ilha porque ele mora no Forte dos Piratas e não é fácil encontrá-lo. Ele lhe dará um carregamento de cerveja pela minha roupa. Claro, você só tem dois meses para voltar com a Ale.",
"Bem, espero que tudo corra bem. Vê você!",
"Finalmente você está de volta!",
"Como você pode ver, tenho a cerveja conforme planejado.",
"Bom trabalho. Aqui estão suas 8.000 moedas de ouro.",
"AH! se esse trabalho continuar, eu poderia comprar sua barca.",
"Realmente? você está interessado naquele velho navio, muitas palavras verdadeiras foram ditas em tom de brincadeira?",
"Eu estava brincando. Mas por que não, o futuro seria meu?! Quanto custaria para você se separar dela, ela é velha, mas saudável?",
"Eu poderia deixá-la ir pela pequena quantia de 35.000 moedas de ouro, estava pensando que poderia usar uma capacidade de carga maior ultimamente. É um bom preço. Em um estaleiro, você pagaria muito mais por uma barca dessas. É uma pena que você já queira seguir em frente? Estou um pouco irritado, você é um bom capitão.",
"Obrigado, gostaria de ter meu próprio navio e tripulação, poderíamos trabalhar mais e ganhar muito mais.",
"Isso é compreensível, você tem ambição. Você quer uma nova missão ou quer renunciar agora?",
"Não, eu gostaria de ter outra missão. Preciso aprender e ganhar mais antes de te deixar.",
"Bem, eu tenho uma missão simples: entregar uma carga de canela para Jean Maginot, o lojista da #sMarigot#.",
"O que? Eu não sabia que um lojista pudesse comprar contrabando.",
"HA-HA! Normalmente ele não pode... Mas ele paga aos soldados para olharem para o outro lado e todos nós ficamos mais ricos.",
"Esse é o Caribe! HA-HA! Não vou perder tempo. Antes de dois meses, estarei de volta aqui para comprar sua barca. Confio que você cumprirá sua palavra!",
"Aqui está você! O que aconteceu?",
"Eu não tive nenhum problema. Eu tenho o tabaco em troca. Este é um ótimo negócio. Ah, e Jean manda cumprimentos.",
"Maravilhoso! Receba sua comissão: 7.000 moedas de ouro. Agora, você ainda tem interesse em comprar minha barca?",
"Sim, economizei 35.000 moedas de ouro. Pegue o dinheiro.",
"Sim, mas preciso de alguns dias para conseguir as 35.000 moedas de ouro necessárias.",
"Não tenho missões nos próximos 10 dias. Então se você quiser comprar a barca, quero esse valor antes dessa data. Inteligente?",
"Sim, você terá o dinheiro antes de 10 dias. Vejo você em breve!",
"Bartolomeu! Você tem o dinheiro, encomendei o novo navio e mantenho sua palavra?",
"Obrigado Bartolomeu. Esse dinheiro vai me ajudar a pagar o novo. Tem certeza de que deseja deixar meu emprego? Devo avisar que existem muitos perigos por aí.",
"Na verdade, eu irei. Foi um prazer trabalhar para você. Talvez eu possa te ver novamente no futuro.",
"Quem sabe posso ter trabalho para você! Volte quando quiser, mesmo que seja apenas para descansar. Tenho orgulho de você ter trabalhado para mim, minha reputação está intacta, você sempre estará seguro aqui.",
"Obrigado. Adeus Eugênio!",
"O que você está fazendo aqui?",
"Desculpe meu erro.",
"Você está bem, Bartolomeu! Você recuperou seu navio?!",
"Infelizmente não. Cheguei tarde demais, o 'Santiago' estava levantando âncora.",
"E você não sabe para onde ela está indo?",
"Nenhuma idéia. Consegui prender alguns homens de Pedro Rivera, mas eles não sabiam para onde ia o capitão.",
"Aquele maldito Rivera, você sabe, ele já trabalhou para mim - eu o demiti - tão arrogante, zangado e sádico quando ele está tomando rum. O que você vai fazer agora?",
"Sim, Emilio me falou dele, um pouco tarde, mas antes tarde do que nunca. De qualquer forma, quero recuperar meu navio, mas primeiro tenho que encontrar um temporário, mesmo que pequeno, ou morrerei na água.",
"Humm.. Deixe-me ajudá-lo. Eu tenho um ketch velho, posso emprestá-lo para você até que você compre ou roube um maior.",
Thanks Eugene! It's really kind of you. You're right. I'll go in search of a bigger one and I'll bring back your ketch., 
"Bom. Como de costume, o navio estará atracado em Boca de Hubon. Espero que você encontre o 'Santiago' no futuro.",
"Espero que sim. Obrigado mais uma vez e até breve!",
"Bartolomeu! Como vai? Você veio devolver meu ketch?",
"Não, tenho ainda mais más notícias. Consegui roubar um galeão em #sisland_Isla Muelle# há algum tempo, mas os espanhóis nos pegaram e prenderam a mim e minha tripulação em #sisland_Redmond#. Eu escapei deles em #sSanto Domingo#. Eu poderia usar sua ajuda para recuperar o galeão.",
"Não se preocupe com aquele velho ketch, ela já estava para se aposentar de qualquer maneira. O galeão ainda está no Porto #sSanto Domingo#, e os seus homens?",
"Sim, ela ainda está lá, minha tripulação está presa a bordo!",
"É uma tarefa perigosa roubar um navio num porto espanhol. Tem certeza de que quer fazer isso?",
"Sim eu sou. Tenho um plano para entrar na cidade sem ser reconhecido.",
"Como posso ajudar?",
"Eu só preciso de alguns piratas experientes para me ajudar neste trabalho.",
"Bem, posso ter parte da solução. Conheço dois piratas muito bons. Talvez você esperasse mais, mas no momento não posso fazer melhor.",
"É verdade que eu esperava mais, mas algo é sempre melhor que nada. Posso conhecê-los agora, o tempo é curto?",
"Claro, siga-me, eles moram aqui no acampamento.",
"Vamos.",
"Aqui estão os 'seus' homens. Adriance Blind e Benoit Belcour.",
"Muito obrigado.",
"Eugene disse que você quer levar seu navio de volta ao porto de #sSanto Domingo#.",
"Certo. Mas não se preocupe, correremos o mínimo de riscos.",
"Somente com algum truque isso poderia ser feito.",
"Sim, foi exatamente isso que planejei fazer, enganar os soldados.",
"Espero que tudo corra como esperado,.",
"Muito obrigado pela sua ajuda. Eu tenho que ir agora. Obrigado mais uma vez, Eugene, até breve!",
"Você quer que a gente vá com você agora",
"Não, você e Benoit ficam aqui e protegem minhas costas. Eu não gostaria de ser pego por trás se alguns soldados aparecessem.",
"Como você foi?",
"Ótimo, liberamos a tripulação. E você, algum soldado veio?",
"Não, no momento eles não notaram nossa presença.",
"Excelente, até agora uma surpresa completa.",
"Você se saiu bem, eu e Benoit, não trabalhamos para ninguém. Se conseguirmos tomar o seu navio, queremos ser seus oficiais, como recompensa. Você concorda?",
"Temos um acordo, sei que posso confiar em você, como Eugene atestou por você.",
"Bartolomeu! É bom te ver! O que você fez desde a sua última estadia aqui no acampamento?",
"É uma longa história, Eugene.",
"Ouvi dizer que você atacou os armazéns do #sSantiago#.",
"Isso é verdade com a pirata francesa Roxanne Lalliere.",
"Ela é uma boa pirata.",
"É verdade, legal também, tivemos um ótimo caso, tive sorte de conhecê-la. Ela ainda mora em #sisland_Hispaniola#?",
"Eu não acho. Ouvi dizer que ela se mudou para #sPointe a Pitre#. Mas, diga-me o que mais aconteceu.",
"Muitas coisas. O mais importante foi que capturamos Charles Baxter.",
"Carlos Baxter?! O famoso pirata? Como isso é possível?",
"O Governador de #sisland_Conceicao# deu-me a missão de o prender para impedir os seus ataques à colónia portuguesa. Eu o rastreei até #sCharlestown#, peguei-o e levei-o ao Governador.",
"Ele tem uma má reputação, um verdadeiro pirata negro.",
"Parece que sim, observe o pretérito, ele não é mais um problema. Vamos falar sobre outra coisa. Tenho alguns produtos que gostaria de vender.",
"O que exatamente você tem?",
"Açúcar, canela e frutas. Você está interessado?",
"Claro, quais são as quantidades?",
"250 para o açúcar, 200 para....",
"",
};
