stringDLG_TEXT[74] = {
"Então você é parceiro da Roxanne?",
"Sim eu sou. E você é François l'Ollonais.",
"Ele mesmo. Qual é o seu nome, capitão? Roxanne não me contou.",
"Eu sou Jorge Coelho.",
"Não ouvi falar de pirata com esse nome no arquipélago...",
"Porque estou aqui há muito pouco tempo.",
"Humm.. Normalmente, eu só escolho piratas experientes como parceiros. Eu não gosto desta situação. No entanto, confio em Roxanne e se ela escolher você como parceiro, então, tudo bem.",
"E quais são os termos do nosso acordo?",
"Se encontrarmos o ídolo, quero metade do preço de venda.",
"Isso é demais. Somos três capitães. Isso deveria ser apenas um terço.",
"Não deixarei um capitão inexperiente ganhar tanto quanto eu. Eu acho que você sonha. Você parece não saber quem eu sou, capitão. De qualquer forma, você parece ser um para mim",
"Tudo bem, aceito 25 centavos. Você também deveria aceitar a oferta.",
"Tudo bem, temos um acordo.",
"Isso é mais razoável. Mas para a venda, todos devemos concordar sobre quem pode comprá-lo.",
"Por que?",
"Se o ídolo realmente tem poderes mágicos, não podemos vendê-lo para qualquer um.",
"Esses poderes mágicos são muito provavelmente um mito. Só espero que o comprador acredite neles para que possamos vender a estatueta por um preço mais alto.",
"Veremos. Agora que todos os detalhes estão resolvidos, você poderia nos contar se encontrou alguma informação sobre o ídolo?",
"Não, nenhum no momento. Acho que apenas o governador e seus dirigentes mais importantes possuem a informação.",
"*Tom irônico* Não me diga que você pensa em interrogar o governador..",
"Não o governador, mas o seu braço direito, o comandante da guarnição, Luis Perdiguero.",
"Esta tarefa é extremamente perigosa.",
"Eu não disse que não era. Na verdade, o comandante mora num prédio ao lado da Câmara Municipal. Nossa vantagem é que ele não é guardado por soldados.",
"Sim, mas sempre há soldados patrulhando a Praça Townhall.",
"Claro, mas menos durante a noite, e então é mais fácil alguém entrar furtivamente no prédio.",
"Se ele for avistado, não há possibilidade de fuga.",
"Eu admito isso. Mas não temos homens suficientes para capturá-lo à força. Lembre-se, #sIsla Muelle# possui uma das maiores guarnições do arquipélago.",
"Tudo bem. Diga-me como chegaremos à Praça da Câmara Municipal. A cidade inteira é guardada por patrulhas.",
"Atravessar a cidade seria muito perigoso, por isso meus homens vão instalar uma corda logo atrás da Igreja permitindo escalar o muro. A distância entre a Igreja e o edifício é curta.",
"Bem, parece ser um bom plano. Quem vai questionar o comandante?",
"Não consigo lidar com tudo. Então, se vocês querem ser meus parceiros, mostrem-me que estão dispostos a fazer isso.",
"Vendo que esta questão está resolvida, esperarei por você esta noite perto da parede.",
"Tudo bem.",
"A corda está instalada, você só precisa subir.",
"Não se preocupe, devo ser rápido em obter as informações, quanto mais tempo ficar lá, mais perigoso será.",
"Então o que aconteceu?",
"Primeiro, ao contrário do que você disse, havia um guarda na frente da casa do comandante. Porém, entrei e falei com ele e tenho a informação. O ídolo está na área inexplorada de Curaçao.",
"Tem certeza?",
"Sim, foi o que ele disse. Mas temos que nos apressar porque o governador já mandou um navio de guerra para lá.. sem esquecer dos guardas que estão chegando agora. Fui visto depois da minha conversinha com o comandante.",
"Nossos navios estão ancorados na praia de Oyster. Vamos agora, talvez ainda tenhamos uma chance de encontrar a estatueta antes deles.",
"De fato.",
"E agora, Capitão?",
"Precisamos saber como chegar à área onde o ídolo está. Vamos começar a conversar com o pessoal de #sWillemstad#.",
"Não podemos perder mais tempo. Vamos agora.",
"Tudo bem.",
"Inacreditável, há um navio de guerra espanhol encalhado na costa!",
"O que?! Tenho certeza de que é o navio que o governador de #sisland_Isla Muelle# enviou para cá.",
"Tem que ser esse. Ela deve ter sido atingida por um tornado. Para este tipo de navio, uma simples tempestade não pode causar tais danos.",
"Você tem razão. Agora, os espanhóis não podem impedir-nos de levar a estatueta. Vamos em nossa busca.",
"Vá em frente! Os índios atacaram de todos os lados.",
"Os Dariens, aposto. Devemos estar perto do acampamento deles.",
"Sim?",
"Olhar! Acho que encontrei o templo deles ou algo semelhante. Logo atrás das árvores, há uma porta. Vamos entrar.",
"Espere! Eu vou ficar lá fora.",
"O que você está falando?! Você está com medo?",
"Você está brincando, capitão? Meu nome é François l'Ollonais. Você esqueceu?! Não, ficarei aqui para repelir qualquer novo ataque dos índios. Eu não gostaria de ficar preso dentro do templo.",
"Como você quiser. Vou verificar se o ídolo está dentro.",
"Então?",
"SIM! Eu entendi! ....mas espere! quem são esses homens que estão com você?",
"Alguns membros da tripulação da minha nave. Eu disse a eles para nos seguirem discretamente.",
"Por que? Eu não entendo.",
"Bem, Capitão ou eu deveria chamá-lo de Bartolomeu o Português.. Chegou a hora de me dar o ídolo.",
"Como você sabia meu nome?",
"Eu não sou totalmente estúpido. Não acreditei naquela história de fadas de que você era um pirata que chegou recentemente ao Caribe. Então, pedi ao meu oficial para obter algumas informações sobre você. Ele questionou um dos membros da sua tripulação, ajudado por algumas garrafas de rum. E descobri quem você realmente era",
"Vá em frente! Eu gostaria de transportar aquele tripulante.",
"Isso não é importante... Agora, me dê o ídolo!",
"Eu não acho.",
"Se você me der o ídolo, você viverá, caso contrário meus homens irão matá-lo, sua escolha.",
"Pegue, traidor!",
"Desculpe, mas tenho coisas melhores para fazer agora. Então, é um adeus... para sempre!",
"Você não é muito inteligente, capitão. Você acha que meu capitão o deixaria viver, especialmente depois do que você fez ao amigo dele, Charles Baxter?",
"Eu sou um pouco lento. Parece que o clima do Caribe muda rapidamente.",
"Tarde demais para você descobrir agora que foi manipulado quase desde que chegou, mas nunca viu o quadro geral.",
"Fale com a mão, não tenho mais palavras nem piedade!",
"",
};
