stringDLG_TEXT[31] = {
".....",
".....",
"Bartolomeu o Português?",
"Sim, eu te conheço?",
"Sou oficial de Roxanne Lalliere. Também participei da missão de Santiago, não lembra?",
"Ohh... Desculpe, não me lembro de você. Prazer em conhecê-lo, er... de novo. Estou procurando Roxanne, preciso contar a ela algo importante.",
"Algo terrível aconteceu. Eu e sua equipe não sabemos onde ela está agora.",
"O que você quer dizer com o que aconteceu?!",
"Ontem, Roxanne foi sequestrada!! Um pequeno grupo de homens a carregou para a selva. Eu estava com ela, brigamos muito. Infelizmente, fiquei atordoado e não consegui detê-los.",
"Caramba! Eu sabia que isso iria acontecer, mas não tão cedo.",
"Eu não entendo. O que você sabia?",
"Tenho certeza de que esses bandidos não estavam interessados no seu capitão.",
"E se eles não estivessem interessados nela, eles não a teriam levado - você não está fazendo nenhum sentido!!?",
"Sim, entendo, acredito que eram mercenários espanhóis e estavam me procurando.",
"Isso ainda não explica, o que os espanhóis têm a ver com isso?",
"Estes homens trabalham para as autoridades espanholas e foram enviados para me prender. Eles sequestraram sua capitã porque ela é minha melhor amiga. Eles provavelmente pensam que ela pode dizer onde estou.",
"Você talvez esteja certo sobre aqueles homens, capitão. Agora que penso nisso, notei que alguns dos sequestradores tinham sotaque espanhol.",
"Não há tempo a perder. Preciso começar minha busca agora mesmo, ela está em um perigo terrível. Esses mercenários usarão todos os meios para persuadi-la a falar. Tortura, estupro, uma mulher é uma presa muito fácil para gente como eles.",
"Já estava preparando a tripulação para a busca e resgate do nosso bom Capitão. Nós podemos ajudar você.",
"Obrigado, mas não desta vez. Eu vou lidar com isso sozinho. Um homem tem muito mais chances de salvá-la do que uma equipe. Eles simplesmente vão matá-la se tiverem a chance. Aguarde meu retorno aqui na cidade.",
"Qual é o seu plano, precisamos saber para que se você não voltar, iremos atacá-los e nos vingarmos, lenta e dolorosamente?",
"Você disse que eles a levaram para a selva. Imagino que devam estar em Puerto la Cruz, a única cidade espanhola desta ilha.",
"Concordo. Essa cidade oferece-lhes a melhor proteção. Mas, você estará em perigo lá, será reconhecido?",
"Não se preocupe, já tenho um plano. Vejo você em breve!",
"Bartolomeu e Roxanne, Graças aos Deuses, vocês estão de volta!",
"De fato. Foi uma luta difícil, mas vencemos no final.",
"MAS, este é o homem que me atacou, deixe-me atacá-lo, devo a ele alguns cortes e hematomas e talvez alguns ossos quebrados, pelo menos!!!!",
"Na verdade, o próprio capitão Elting. Nós o convencemos a se juntar a nós, então não... ele está do nosso lado agora.",
"É uma pena que ele não tenha mudado de lado antes da nossa luta, minha cabeça estaria muito melhor agora. Eu ainda gostaria de dar-lhe alguma atenção. Enfim, para onde vamos a partir daqui, qual é o seu plano?",
"Ainda temos que finalizar isso com Roxanne e Elting, e não de novo... deixe o capitão Elting em paz, ele é muito mais útil para nós com boa saúde.",
"De fato. Não foi fácil, mas conseguimos. Agora preciso encontrar o Emilio.",
};
