stringDLG_TEXT[143] = {
"....",
"....",
"Você não vê, estou ocupado?",
"Desculpe, mas estou ",
" Capitão do '",
" Ouvi dizer que você está preparando uma expedição e precisa de um parceiro.",
"É verdade, e você acha que é bom o suficiente para participar dessa aventura?",
"Sim. Mas, gostaria de saber mais alguns detalhes sobre isso, antes de me comprometer. Não tenho tempo para perseguições de gansos selvagens.",
"Bem, eu sei que os espanhóis descobriram uma grande jazida de prata algures no arquipélago há dois anos...",
"Nunca ouvi falar disso antes, algo tão importante certamente seria falado. Como é que você descobriu isso?",
"Capturei um galeão espanhol há algumas semanas. A bordo estava um funcionário de #sSantiago#. Ele me deu essa informação em troca de sua vida.",
"E você acreditou nele?! Talvez ele só tenha inventado essa história para que você o deixasse ir.",
"Você me acha um idiota, garoto... é claro que não o libertei. Ele agora está preso em #sTortuga# e só vou deixá-lo ir depois de confirmar se a informação está correta...talvez.",
"E onde está o depósito de prata?",
"Bem, ele me disse que era numa ilha deserta no meio do arquipélago.",
"Poderia ser #sisland_Battle Rocks#...",
"Você sabe onde encontrar esta ilha?",
"Sim, eu poderia te levar até lá. Eu nunca parei por aí. Parece ser bastante inóspito e sem boas ancoragens. A costa é composta principalmente por rochas irregulares.",
"Se os espanhóis colonizaram a ilha, acho que devem ter encontrado um ancoradouro, ou feito um, podemos usá-lo, não podemos?",
"Sim claro. E se o seu prisioneiro estiver certo sobre o saque e nós colocarmos as mãos nele, o que acontecerá...?",
"A prata roubada será vendida em #sTortuga# e dividiremos os lucros de forma justa. Temos um acordo?",
"Na verdade, poderíamos ganhar muito... Sim, temos um acordo. Quando você estará pronto para sair de #sTortuga#?",
"Tenho a sensação de que a expedição é muito arriscada. Você deveria procurar outra pessoa.",
"Bem, capitão, talvez um dia eu te veja novamente",
"Talvez, adeus!",
"Excelente! Já fiz os preparativos para que possamos ir agora. Mas antes de fazermos isso, deixe-me apresentar-lhe nosso terceiro parceiro, meu velho e famoso amigo Edwaert, Capitão Mansveldt. Ele nos ajudará durante a expedição.",
"Finalmente, encontramos um ancoradouro seguro.",
"Na verdade, eu estava certo quando disse que a costa era rochosa e recortada, muito perigosa para os nossos navios. Vamos explorar a selva, precisamos determinar se e onde os espanhóis colonizaram a ilha.",
"Nem eu!",
"Agora estamos tão perto da meta que não estou disposto a desistir.",
"Vá em frente! Ele escapou.",
"NãO É BOM! Ele avisará o comboio...",
"A brincadeira acabou. Não temos escolha senão atacar o comboio... agora.",
"Concordo. Vamos.",
"Verifiquei as caixas... estão todas cheias de prata. Que sorte. Que lanço.",
"Adoro receber notícias como essa! Vamos para os navios. Quero a prata sob a proteção dos nossos canhões, o mais rápido possível, não podemos perdê-la agora.",
"A venda da prata rendeu 150 mil moedas de ouro. Normalmente, seriam 75.000 para cada um. Mas seria justo dar uma parte a Konrad Kulczycki e seus companheiros, certo?",
"Exatamente, Capitão Morgan. Eles merecem isso. A ajuda deles foi decisiva. O que você acha de 30.000 moedas de ouro para eles?",
"Concordo. Portanto, serão 60 mil para cada sócio, uma quantia realmente bela. Esse funcionário espanhol mereceu a sua libertação. Devo estar de bom humor.",
"Excelente! Esta expedição foi muito proveitosa, um sucesso total para todos.",
"Capitão Bartolomeu?! É bom te ver.",
"Obrigado, senhor. É um prazer conhecê-lo novamente. Eu sabia que você estava trabalhando para o Governador.",
"Na verdade, ele me dá muitas tarefas e paga bem por isso.",
"Bom para você! Não tenho nenhuma nova expedição em mente. Você acha que ele estaria interessado em meus serviços?",
"Claro. Mas, na verdade, eu estaria interessado primeiro.",
"O que você quer dizer?",
"Existe a possibilidade de eu fazer uma expedição nos próximos dois ou três meses.",
"Qual é o objetivo da expedição?",
"Aproveite um tesouro asteca.",
"Hum...",
"Você não parece estar cheio de entusiasmo Ha! Ha! Talvez eu não tivesse falado sobre isso.",
"Digamos que a última vez que procurei um tesouro indiano, só ganhei problemas... não ouro.",
"Não se preocupe, capitão. Só iniciarei a expedição se tiver certeza de que será lucrativa.",
"Quer dizer que ainda precisa de mais informações sobre esse tesouro antes de embarcar na expedição?",
"Certo e você poderia me ajudar com isso.",
"De que maneira?",
"Siga-me até minha cabana para que eu possa lhe contar os detalhes da história.",
"Aqui estão os detalhes. Eu sabia que os espanhóis encontraram recentemente um tesouro em uma cidade asteca abandonada, perdida na selva.",
"Onde exatamente?",
"Perto de Vera Cruz.",
"Tem certeza?",
"Infelizmente não. Preciso de uma confirmação. Por isso quero enviar alguém a Vera Cruz para saber se o tesouro realmente existe, quais são os objetos que compoem o tesouro e se o destino desse tesouro é a Espanha.",
"Você acha que o tesouro será enviado para a Espanha?",
"Sim, se o tesouro for tão valioso como ouvi, irá diretamente para a Coroa Espanhola. Neste caso, o tesouro ficará guardado em Vera Cruz antes de ser...",
"carregado na Frota de Prata.",
"Vejo que você sabe que Vera Cruz é um dos portos do Caribe que a Frota de Prata atraca.",
"Não é difícil. Não há muitos portos onde a Frota de Prata pare.",
"Certo. Você está interessado nesta missão?",
"Sim capitão. Consigo trazer de volta as informações.",
"Bom! Assim que você conseguir, volte rapidamente. Devemos atacar Vera Cruz antes que a Frota Prateada chegue. Caso contrário, poderemos perder a nossa oportunidade única.",
"Eu entendo. Eu vou agora.",
"Vocês estão de volta, Elting e Bartolomeu! Quais são as novidades?",
"Não atacaremos Vera Cruz, Capitão.",
"O que? Não me diga que o tesouro desapareceu ou saiu do Caribe.",
"Não, ainda está no Caribe, mas em Cuba.",
"O que está fazendo aí?",
"A Frota de Prata deixou Vera Cruz mais cedo do que o esperado, talvez porque quisesse fazer escala em Havana antes de seguir para a Espanha.",
"Caramba! Senhores, devemos ir rapidamente para Havana. Não sabemos quanto tempo durará sua estadia. Pode ser o nosso último golpe de sorte para roubar o tesouro. Preparem seus navios, nós levantamos âncora!",
"Sim capitão.",
"Tudo bem, a frota ainda está em Havana. Mas devemos saber se o tesouro está nos navios ou em terra e quanto tempo a frota ficará, esperando que tenhamos tempo suficiente para o roubo. Vocês dois podem obter essas informações?",
"Eu penso que sim. Com o Capitão Elting, encontraremos um estratagema.",
"Seja rápido! Não podemos deixar nossos navios perto de Havana indefinidamente. Isso seria muito perigoso.",
"Entendido.",
"O que um padre está fazendo no meu navio?",
"Ele não é padre. Vestimos-lhe um roupão só para sair de Havana. Na verdade, ele é o capitão da Frota de Prata. Só encontramos esta solução para saber onde está o tesouro.",
"Você o questionou?",
"Ainda não. Preferimos que você faça isso.",
"Farei isso, mas a ausência dele em Havana alarmará as autoridades. Não teremos muito tempo para obter as informações.",
"Feito! Ele entendeu que eu não estava com vontade de brincar e disse onde estava o tesouro.",
"Nos navios?",
"Não, está no forte El Morro.",
"Não é melhor que os navios.",
"Pior, eu diria. Essa é a razão pela qual eles deixaram lá durante a estadia.",
"Você quer dizer que devemos desistir?",
"Não, eu não. Vamos atacar o forte.",
"Tem certeza que conseguiremos? Você acabou de insinuar que o forte é um grande desafio.",
"Sim, mas isso não é impossível. Com um bom plano, podemos fazer isso. O único problema é prepará-lo o mais rápido possível. Amanhã à noite, devemos agir. Descanse até amanhã ao meio-dia, te ligo para explicar o plano.",
"Senhores, tenho um trabalho para vocês!",
"O plano está pronto?",
"Sim, atacaremos o forte pelos dois lados. Comandarei as tropas em frente à entrada principal. Meu objetivo será atrair a atenção dos guardas. Enquanto isso, você e Elting com alguns de seus tripulantes irão penetrar no forte pelo lado oposto para combatê-los nas costas.",
"*Tom de espanto* Capitão, há um penhasco daquele lado.",
"Eu sei. Você se aproximará do penhasco com um pequeno navio para não ser detectado pelos guardas. Chegando ao fundo da falésia, você subirá graças aos arpéus. Os guardas não vão esperar que o inimigo venha daquele lado.",
"Eu os entendo.",
"Claro, é perigoso, mas não tenho outro plano. Se quisermos vencer a batalha, devemos surpreendê-los. Caso contrário, não teremos chance.",
"Tudo bem, faremos o melhor que pudermos.",
"Obrigado, eu sabia que posso contar com você. Tenha certeza, teremos sucesso.",
"Elting?! Foi você quem destruiu os canhões?",
"Sim capitão. Bartolomeu me contou que você foi parado pelos canhões. Mas, sem tempo para conversa, os espanhóis devem preparar uma surtida. Você deveria atacar o forte!",
"Estou indo agora mesmo para a entrada principal. Enquanto isso, junte-se a Bartolomeu.",
"Bom trabalho! Agora que este andar está 'limpo' podemos ir para o armazém.",
"Olhar! O trono asteca está aqui.",
"É o trono que vi no forte de Vera Cruz.",
"Deve valer uma fortuna e ainda não vimos o que as caixas contêm. Vamos levar rapidamente o tesouro para a praia. Os soldados de Havana devem ser avisados do nosso ataque.",
"Tudo bem, quase terminamos o carregamento. Depois de embarcar em nossos navios, iremos para #sRedmond#.",
"Consegui vender a maior parte do saque, mas há um problema...",
"O que você quer dizer?",
"O trono asteca é valioso demais para ser vendido no Caribe. O lojista de #sRedmond# era nossa única possibilidade, mas ele não tem dinheiro suficiente para isso.",
"O que vamos fazer agora?",
"Na minha opinião, deve ser vendido a um joalheiro rico de Londres. Somente essas pessoas poderiam nos pagar o preço certo.",
"Então, deveríamos ir para a Inglaterra?",
"Desnecessário. O Governador poderia enviá-lo para Inglaterra num dos seus navios de guerra. Receberemos o dinheiro quando o navio de guerra voltar.",
"Claro, teremos que pagar ao Governador pelo 'serviço'...",
"De fato. Ainda preciso falar com ele, mas aposto um quarto da venda.",
"hum...",
"Acho que é a melhor solução. O trono estará mais seguro num navio de guerra britânico e não precisamos de perder tempo indo para Inglaterra. Você concorda?",
"Concordo. O que Elting pensa?",
"Eu vou falar com ele. Se ele concordar, falarei com o Governador.",
"Boas notícias! O governador tem um de seus navios de guerra que deve ir para a Inglaterra no próximo mês.",
"E o preço do serviço?",
"No início, ele queria um terço da venda, mas eu o convenci a reduzir sua parte para um quarto.",
"Como você pensou.",
"Sim. Agora, devemos esperar seis meses ou mais para receber o dinheiro. Até lá, podemos desperdiçar o dinheiro dado pelo lojista.",
"Quanto?",
"450.000 moedas de ouro. Então, 150 mil para cada um. Pegue seu dinheiro!",
"Nada mal.",
"E é só o começo porque o trono vale mais do que esse valor. Espero 250.000 para cada um quando vendido.",
"Deus! Isso é uma grande soma!",
"Sim capitão. Mas há muito que esperar até recebermos o dinheiro.",
"Enquanto isso, o que você fará?",
"Vou descansar em #sRedmond# nas próximas semanas. Depois, não sei... não tenho novas expedições agendadas.",
"Nesse caso, vejo você daqui a meio ano para compartilhar o saque.",
"Obrigado por tudo capitão. Boa sorte!",
"Adeus!",
};
