string DLG_TEXT[40] = {
"Bem-vindo! Sente-se na mesa livre. O que você gostaria de pedir, ",
"?",
"Nada. Eu estou aqui a negócios.",
"Oh! Eu sinto muito. Eu não queria incomodar você. Voltarei ao meu trabalho.",
"Não, espere - você não está me incomodando. Na verdade, é com você que preciso falar.",
"Não tão rápido. Quero falar com você.",
"Sou todo ouvidos. Como posso ajudá-lo?",
"Preciso contratar alguns marinheiros.",
"Estou querendo aumentar minha equipe.",
"Vamos conversar sobre negócios.",
"Eu queria um quarto.",
"Você tem um quarto livre neste lugar?",
"Deixa para lá. Eu tenho que ir.",
"Certamente, ",
". O que está em sua mente?",
"Diga-me: quem é o dono da casa perto da sua taverna?",
"Na verdade, não é nada importante.",
"Eu tenho uma vaga. Quanto tempo você planejava ficar conosco?",
"Vou passar a noite.",
"Só até o pôr do sol.",
"Multar. Vai custar-lhe cinco moedas de ouro.",
"Tudo bem. Aqui você vai.",
"Muito? Parece que vou passar a noite no salão da taverna.",
"Para quê - a residência do governador? Não, obrigado.",
"Vou pensar sobre isso. Por enquanto, deixe-me fazer outra pergunta.",
"Vai custar-lhe cinco moedas de ouro.",
"Tudo bem. Aqui você vai.",
"Muito? Parece que vou passar a noite no salão da taverna.",
"Para quê - a residência do governador? Não, obrigado.",
"Tudo bem, vou pensar sobre isso.",
"Bem, é bem tarde. Todos que você contratar terão encontrado um lugar para passar a noite.\nÉ melhor esperar até de manhã. Talvez eu possa alugar um quarto para você? ",
"Você tem um quarto livre?",
"Não. Tenho outra pergunta.",
"Amigos, por favor! Chega dessa loucura. Não me faça chamar o guarda!",
"Relaxar! Estou indo embora.",
"Estou procurando trabalho. Você sabe se alguém precisa de um capitão?",
"Você é sortudo! O famoso pirata Henry Morgan está se preparando para uma expedição e gostaria de ter um parceiro.",
"Para onde ele quer ir?",
"Não tenho ideia, capitão... Você deveria falar com ele. No momento, ele deve estar no #sTortuga# Townhall, você pode encontrá-lo lá se se apressar.",
"Obrigado, já saí [Wink:].",
"",
};
