string DLG_TEXT[13] = {
"Olá senhor.",
"Posso te fazer uma pergunta? Procuro um homem chamado Emilio Soares. Você o viu?",
"Talvez. Quem é você?",
"Eu sou ",
"e meu amigo aqui é William Klein.",
"Bartolomeu? Você é o capitão do Emilio, não é?",
"Então você conhece Emílio!",
"De fato sim. Sinto muito por ser tão cauteloso. Emilio chegou aqui há alguns dias, depois de passar várias semanas na selva, tentando encontrar a cidade. Ele não está muito acostumado a estar em terra.",
"Então, onde ele está agora? Ele conseguiu encontrar um navio para levá-lo daqui?",
"Não, ele não fez isso. Não há muitos navios que partem daqui para #sRedmond#, considerando que os espanhóis estão em guerra com os ingleses. Emilio insistiu em encontrar um navio para #sRedmond# ou ficar aqui. Ele geralmente mora na minha casa, mas no momento está passeando fora da cidade. É arriscado, considerando que ele é procurado pelas autoridades, mas não consegui impedi-lo de ir.",
"Obrigado por nos ajudar a encontrá-lo. E também um grande agradecimento por ajudar Emilio.",
"Não gosto muito do governo, por isso fico feliz com cada oportunidade de ajudar piratas e contrabandistas.",
"Isso é muito bom da sua parte. Muito obrigado.",
"",
};
