string DLG_TEXT[71] = {
"....",
"....",
"Sim?",
"Olá, sou Dom Guillermo de la Rosa, enviado do Rei. Cheguei hoje da Espanha. Posso saber o seu nome?",
"Meu nome é Lúcia Montavez.",
"Montávez? Você pertence à família do Governador?",
"Eu sou filha dele.",
"É realmente um prazer conhecê-lo. Eu não tinha ideia de que ele tinha uma filha tão linda.",
"(Ela cora) Obrigada. Você me lisonjeia.",
"Eu só falo a verdade. Não pude deixar de notar que você parece menos encantado com a festa.",
"Estas funções são sobretudo para os homens. Discutir sobre política, guerras e assim por diante não são tópicos que me interessam.",
"Eu entendo. Certamente há coisas mais agradáveis para conversar.",
"Dom Guillermo, conversamos tanto que nem percebi a hora. Já é tarde, preciso ir",
"Sinto muito, você está certo. Perdi completamente a noção do tempo. Deve ter sido a companhia encantadora.",
"Bem, gostei da sua companhia esta noite. Talvez, se seus deveres de enviado permitirem, você possa me ver amanhã?",
"Seu pai quer me mostrar a cidade. Não tenho ideia de quanto tempo isso pode levar.",
"Estarei no jardim da residência à tarde. Tente estar lá se puder.",
"Farei o meu melhor. Boa noite, senhora Montavez.",
"Dom Guilherme! Graças a Deus é você.",
"Boa tarde, senhora Montavez. Este homem está lhe causando problemas? Eu ficaria feliz em vê-lo sair para você.",
"Senhores, por favor. Não quero briga aqui. Dom Ortega estava prestes a sair. Não foi, Dom Ortega?",
"Obrigado, Dom Guilherme. Agradeço sua chegada oportuna.",
"Perdoe-me por interromper sua conversa, mas não me importei com a maneira como ele falou com você. Quem é ele?",
"Dom Sebastian Ortega, jovem fidalgo de Cartagena. Sua família comanda o comércio de escravos nesta colônia e é uma das mais ricas do Caribe.",
"Comércio de escravos, hein? Eu senti que havia algo desagradável nele.",
"Também não me importo com o comércio da família dele. Infelizmente, ele acredita que eu poderia ser sua futura esposa.",
"Isso é algo que você está considerando?",
"Não nunca. Porém, meu pai é a favor do casamento entre nossa família e os Ortegas.",
"E ele poderia forçar você a se casar com ele, eu acho.",
"Infelizmente sim. Eu faria qualquer coisa para evitar isso, mas sinto que o 'prazo' está se aproximando.",
"Sempre há espaço para otimismo, Lady Montavez. As coisas podem mudar.",
"Espero que sim. Estou realmente feliz que você decidiu vir me visitar.",
"Infelizmente, estou aqui para conhecer seu pai. Ele está esperando por mim. Ele quer continuar o passeio pela cidade.",
"Como você disse, as coisas podem mudar. Surgiu algum assunto urgente que requer a atenção total de meu pai.",
"Espero que não seja nada sério.",
"Durante o almoço, ele disse algo sobre um problema com os holandeses. Isso pareceu perturbá-lo.",
"Ele disse mais alguma coisa?",
"Não. Ele geralmente não compartilha os detalhes de seu trabalho.",
"Talvez eu possa ajudá-lo. Peço desculpas, Lady Montavez, mas preciso ver seu pai imediatamente.",
"Claro, Dom Guilherme. Espero vê-lo novamente em breve.",
"Eu também, Lady Montavez. Eu não gostaria de nada melhor.",
"Dom Guilherme? Isso é você?",
"Lady Montavez, espero não tê-la incomodado.",
"De jeito nenhum. A que devo o prazer da sua visita?",
"Tive algum tempo livre esta manhã e me perguntei se poderia convencê-lo a me mostrar Cartagena. Seu pai me apresentou os sites comerciais, mas eu esperava que você pudesse me mostrar coisas mais interessantes.",
"[Sorrindo timidamente] Ora, Dom Guillermo! Somente pretendentes podem me convidar. Você é meu novo pretendente?",
"[Envergonhado] Ah! Eu não percebi... Por mais agradável que fosse, eu não pensaria em quebrar o protocolo. Já entrei em conflito com Dom Ortega uma vez.",
"Só nos sonhos de Dom Ortega eu me casaria com ele! Eu gostaria que ele nunca tivesse ouvido meu nome",
"[PENSA: Boas notícias!] Mas, os desejos do seu pai...",
"São apenas os desejos do meu pai. Simplesmente terei que fazê-lo mudar de ideia sobre qualquer casamento. Otimismo, como você sugeriu. Mas chega de falar de Dom Ortega. Espere aqui. Há algumas coisas que preciso fazer antes de caminharmos juntos.",
"Então você aceita... Maravilhoso! Prometo não sair deste lugar até o seu retorno.",
"OH MEU DEUS! O que aconteceu com você?",
"Parece pior do que é, Lady Montavez. Fui atacado por bandidos. Acredite em mim, eles levaram a pior.",
"Bandidos, aqui? Estou chocado. Esta é a parte mais pacífica de Cartagena.",
"Bem, há uma primeira vez para tudo. Mas não importa. Você gostaria de dar aquele passeio comigo agora?",
"Ainda podemos fazer isso. Vou pedir ao capitão da guarda que designe alguns de seus homens para nos proteger.",
"Como quiser.",
"Obrigado, Dom Guillermo, pelo agradável passeio. Eu gostei de estar com você.",
"Foi um prazer para mim também. Espero que tenhamos a chance de fazer isso novamente em breve.",
"Claro, por que não amanhã de manhã no mesmo horário?",
"Maravilhoso! Verei você amanhã. Até então, Lady Montavez.",
"O que aconteceu, Dom Guilherme? Ouvi uma explosão na cidade e logo depois vi o forte pegando fogo.",
"Preciso te contar a verdade. Não sou Dom Guillermo, o enviado do Rei. Sou Bartolomeu o Português. Um pirata.",
"O que você está dizendo essas coisas? Isso é alguma piada cruel às minhas custas?",
"Não, estou sendo honesto com você. Usei a identidade do enviado do Rei para me infiltrar em Cartagena, para causar o máximo de danos possível.",
"Você não passa de um criminoso. E você me usou como um peão. Por que?",
"Não sou mais criminoso do que as autoridades espanholas aqui no Caribe. Mas, Lúcia, eu não te usei. Eu não consegui. Você deve acreditar nisso. E- preciso saber se você consideraria deixar Cartagena para ficar comigo.",
"Você percebe o que está me pedindo? Se eu concordar, significa trair meu pai e minha família.",
"Estou pedindo que você arrisque tudo, assim como estou arriscando tudo agora por você. Eu me apaixonei por você, Lúcia. Estou rezando para que você sinta o mesmo por mim.",
"Não sei... Está tudo acontecendo tão rápido. Preciso de tempo para pensar.",
"Eu estava com medo exatamente disso. Mas eu entendo. E sinto muito, não posso mais ficar em Cartagena e devo navegar com a maré. Instruirei minha tripulação para vigiá-lo, se você decidir ir comigo. Rezo a Deus para que esta não seja a última vez que vejo você. Não importa o que aconteça, saiba que sempre valorizarei nosso tempo juntos. Adeus, Lúcia.",
};
