string DLG_TEXT[27] = {
".....",
".....",
"Quem é você?",
"Eu vim para te libertar.",
"Você trabalha para o governador de #sIsla Muelle#?",
"[PENSA: Vamos mentir!] Certo. Em breve você estará em #sisland_Isla Muelle#.",
"Obrigado! Eu sabia que a Coroa Espanhola não me deixaria nas mãos do Exército Britânico.",
"Quem é a pessoa que está com você?",
"Ele é meu valete.",
"Ele deve ficar aqui. Ele poderia complicar nossa fuga se vier conosco.",
"De jeito nenhum, capitão! Ele trabalha para mim há anos. Não vou abandoná-lo.",
"Como quiser, mas não conte comigo para salvá-lo se ele estiver em apuros. Minha missão é libertar você, não seu valete. Siga-me e não faça barulho",
"Mas estamos em #sTortuga#?! Você mentiu. Você não trabalha para as autoridades espanholas.",
"HA-HA! Você demorou para entender. Sua ingenuidade é infinita. Agora cale a boca, o Governador Ogeron está chegando.",
"O que você fez com meu servo?! Vocês são bárbaros!",
"Você é estúpido, senhor. Por causa do seu comportamento, o manobrista morreu. Conte-nos tudo ou aposto que Montbars vai estourar sua cabeça!",
"Tudo bem! Tudo bem! O ouro está escondido em um forte construído há pouco tempo em #sisland_Isla Muelle#.",
"Um novo forte em #sisland_Isla Muelle#? Eu nunca ouvi isso.",
"Porque o forte foi construído longe da população.",
"O que você quer dizer?",
"Está construído na baía de Aguadilla.",
"Aguadilha? Onde é a localização?",
"Na costa norõeste.",
"Uma ideia inteligente. Essa região é desabitada. O forte está bem protegido?",
"Uma guarnição inteira vive lá dentro, os soldados são trazidos diretamente da Espanha e abastecidos diretamente, então apenas alguns nobres da ilha sabem de sua existência.",
"E os canhões, quantos, de que tipo?",
"Esse é o problema. Os canhões originais do forte foram perdidos no trânsito durante uma tempestade. Existem alguns canhões reais, mas em número reduzido, o resto é falso para assustar qualquer atacante.",
};
