string DLG_TEXT[36] = {
"......",
"......",
"Capitão, espere um segundo!",
"O que você quer? Não posso mais ficar aqui",
"Humm.. Desculpe, mas ouvi sua conversa e pensei que você pode precisar de outro oficial para esta expedição.",
"Bem, é a minha primeira participação numa expedição deste tipo, então talvez eu precise de mais um oficial. Você é um bom lutador?",
"Sim, participei de algumas operações.",
"Realmente? Estou interessado. Quais foram essas operações?",
"Humm.. Bem.. Humm.. Eu não gostaria de atrasar você. Eu poderia explicar isso mais tarde..",
"Você tem razão. Eu não deveria perder tempo agora. Siga-me, eu aceito você como meu oficial.",
"Obrigado capitão! Você não ficará desapontado.",
"Espero que não.",
"TEMOS DE IR! OS SOLDADOS ESTãO VINDO!",
"O que você fez! IDIOTA!",
"Desculpe capitão... não pensei que seria detectado...",
"Você acha que sou um completo idiota, não posso simplesmente esquecer o que você fez? Ordenei que você ficasse perto dos armazéns, protegendo-nos. E você, em vez de fazer o seu trabalho, 'visitou' a cidade. O que aconteceu dentro da sua cabeça?",
".........",
"Você perdeu a língua? Eu vou te contar o que aconteceu. Você foi em busca de ouro ou outros bens valiosos nas casas. A tua ganância custou-nos a todos.",
"Isso é injusto! Só fui buscar um pouco de rum, não demorei muito, na verdade.",
"CALE A BOCA, RUM... Isso é pior - você foi visto! Você merece ser enforcado agora mesmo! ... Mas como sou JUSTO, aplicarei o código dos piratas para a desobediência: o abandono.",
"O que! você quer me deixar nesta ilha... entre o inimigo?",
"E você deveria estar feliz. Normalmente eu te deixaria em uma ilha deserta com apenas uma pistola e um tiro.",
"Capitão, por favor! reconsidere - era apenas um rum!",
"Você é totalmente imprevisível e uma ameaça para o resto da companhia do navio! Não vou voltar atrás na minha decisão.",
"Então é sua última palavra. Tudo bem, juro que não vou esquecer o que você fez. Você vai pagar por me deixar aqui... e por pegar meu emprego - não sei o que Eugene viu em você.",
"Não me provoque mais. Agora saia da minha frente antes que eu mude de ideia e te mate agora.",
"Quem está fazendo tanto barulho?",
"Sinto muito, capitão. Nós te acordamos, espero que você tenha feito suas orações de boa noite?",
"Muito engraçado. Que sorte, vejo que meu velho 'amigo' Bartolomeu veio até mim. Posso estar procurando por aquele SANGUINHO Pieter Boelen, mas os espanhóis ficarão muito felizes quando eu levar você para #sHavana# também. Ouvi falar de suas façanhas salvando sua tripulação. Os espanhóis não ficaram nada satisfeitos.",
"Você gosta de sonhar, não é? Mas não estamos aqui para ouvir seus discursos e delírios. O que queremos é...",
"O navio, é claro. Você acha que vou me afastar e deixar você navegar com MEU navio?",
"Se você quiser viver, sim.",
"Você parece muito confiante. Você ainda é tão habilidoso com a espada?",
"Você esqueceu...?",
"Você já decidiu quem de vocês vai lutar comigo? Ou você quer que EU escolha qual de vocês morrerá primeiro?",
"Você nunca ouviu o ditado 'A única coisa melhor que uma espada portuguesa é um espadachim português'? De todos os piratas, devo ser um dos mais legais. É preciso muito para me deixar louco. Mas minha raiva é terrível de se ver. Agora está liberado em você!",
"",
};
