string DLG_TEXT[35] = {
"Ooh... Minha cabeça!",
"O que aconteceu? Você está bem?",
"Você não é espanhol?! Quem é você? O que você está fazendo aqui nesta ilha?",
"Não se preocupe! Não somos espanhóis. Estamos procurando uma mina. Deveria haver uma mina de prata em #sisland_Battle Rocks#.",
"Sim, você está certo, mas como você descobriu? Os espanhóis garantem que esta informação seja totalmente secreta.",
"Parece que eles falharam. E você? Você também está procurando a mina?",
"Esse maldito meu! Foi a origem do meu infortúnio! Quase perdi minha vida lá...",
"Você poderia explicar isso um pouco mais, não entendi muito bem?",
"Bem, os espanhóis encontraram a mina há dois anos. Claro, a mina antes disso pertencia aos índios. Desde então, os espanhóis deportaram dezenas de prisioneiros das suas colónias para trabalharem como escravos. O destino deles é trabalhar e morrer aqui. E acredite em mim, apenas alguns meses desta vida são suficientes para matá-los.",
"Então, você escapou dos espanhóis.",
"Na verdade, ontem à noite. Mas eles não eram meu único problema. Conheci um grupo de índios pouco tempo depois e só consegui escapar deles, mas eles me feriram.",
"Humm...Esse pode ser o grupo que lutamos há pouco tempo. Você poderia nos levar para a mina?",
"Você realmente quer ir para lá? A mina é bem defendida por um acampamento militar. Eles têm muitos soldados.",
"Ok, concordo em levá-lo até lá, mas com uma condição... que você libere meus amigos na mina.",
"Claro, teríamos feito isso de qualquer maneira.",
"Nesse caso, siga-me!",
"Muito estranho! Eu esperava mais soldados no acampamento.",
"Mais uma razão para ter cuidado. Diga-me, onde está a mina, deveríamos libertar seus amigos enquanto há tão poucos inimigos por perto.",
"Está perto do acampamento. Siga-me novamente!",
"Quem é você! O que você está fazendo aqui! Seu nome agora!",
"Meu nome é: VÁ PARA O INFERNO!",
"Ei! Konrad Kulczycki está de volta! Você veio nos libertar?",
"Sim! Seus dias de trabalho nesta mina acabaram. Mas, onde estão o resto dos prisioneiros...",
"Eles foram levados ao porto pelos soldados espanhóis.",
"Porta? Que porto?",
"O único porto - onde a prata é carregada a bordo dos navios, é claro.",
"O que?! Há um trem prateado indo para o porto, agora?",
"Sim, eles deixaram o acampamento há uma hora.",
"Agora entendo por que havia tão poucos soldados. Bem, você e seus companheiros vão para a costa leste. Vou tentar alcançar o trem",
"Espere capitão! Conheço um atalho pela selva para chegar ao porto. Ainda é possível capturá-los antes que cheguem ao porto.",
"Excelente! Vamos.",
"Graças a Deus! Finalmente, estamos livres! Eu sabia que Konrad Kulczycki nos ajudaria depois de escapar do acampamento.",
"Na verdade, o seu pesadelo aqui acabou. Mas ainda não somos livres, precisamos sair desta ilha. Mais espanhóis podem chegar a qualquer momento.",
"Obrigado por tudo! Nunca esquecerei o que você fez por mim e por meus amigos.",
"Foi um prazer. Este ouro será um bom começo para uma nova carreira. Até mais, Konrad Kulczycki!",
" ",
};
