string DLG_TEXT[52] = {
"!",
"...",
"Finalmente você voltou para mim! Como vai ",
"Muito melhor agora que te encontrei de novo! Roxane! Quais são as suas novidades desde a última vez que nos encontramos?",
"Você não é bom o suficiente para estar aqui conversando comigo, seu canalha. Saia da minha frente se quiser viver!",
"Tudo bem, não torça a calcinha. Vou voltar mais tarde.",
"Nada realmente importante. Continuo trabalhando para meu adorável Governador. Meu negócio está melhorando a cada dia e ele dá ótimas festas.",
"Isso é uma boa notícia. Talvez você substitua seu governador em alguns anos Ha-Ha!",
"Talvez pudéssemos unir forças para fazer expedições juntos. Com nossos dois navios poderíamos realizar grandes coisas e passar algum tempo juntos!",
"Ah, possivelmente? Continue falando.",
"Por enquanto, não estou interessado. Mas estou muito feliz em ver você novamente.",
"Bem! Aqui estão os termos! Você não precisa fornecer mercadorias para minha tripulação durante nossa associação, mas realiza quaisquer reparos em meu navio. A propósito, você não precisa fornecer pranchas, lonas e munições para meu navio, pois cada vez que passarmos alguns dias aqui, minha tripulação irá reabastecer meu navio!",
"Terei que pagar salário para você e sua tripulação?",
"Não, claro que não, e a minha tripulação não necessitará de comida das suas rações no mar; mas... Tome nota! Se e quando cessarmos a nossa parceria, todo o saque deverá ser dividido em duas partes iguais e o total não deverá ser inferior a ",
"Bom! Temos um acordo. Quando podemos zarpar?",
"Desculpe, mas acho que tenho condições de fazer expedições sem companheiro, não preciso de sua importunação agora!",
"O mais breve possível! Quero sentir o lindo perfume de pólvora e sangue! Ah, ah! e o toque de elegância e jóias",
"Er.. bom, se precisarmos conversar ou quisermos encerrar nossa parceria? Como procedemos, não quero acabar tendo que brigar com você?",
"Nos encontraremos aqui na cidade em um lugar neutro, o rompimento é sempre emocionante. Esta porta oferece boa proteção contra nossos inimigos. ",
"Sim! Espero que a nossa associação permaneça gravada na memória das nações como um dos piores mares do Caribe!",
"Aqui está uma boa ancoragem segura. Se passarmos alguns dias aqui, reabastecerei minha nave e farei alguns reparos!",
"Seria bom passar um tempo juntos aqui com você.",
"Não podemos ficar aqui! Temos que partir!",
"Chegou a hora de seguirmos caminhos separados. Nossa parceria termina agora, meu amigo",
"Quantos dias passaremos aqui?",
"1 dia será suficiente",
"5 dias passados em local seguro serão muito bons para a moral da nossa tripulação!",
"Eu mudei de ideia!",
"Tudo bem, nesse caso chegou a hora de dividir nosso ouro em 2 partes iguais!",
"É hora de seguir em frente, capitão!",
"Você sabe, acho que vou ficar com todo o saque para mim!",
"Mudei de ideia.. não precisamos nos separar ainda, há mais a ser feito!",
". Você é meu amante, capitão e estarei aqui caso queira navegar em er... comigo de novo!",
"Vou pensar nisso meu amigo. Já estou com saudades e rezo para te ver novamente, em breve!",
"Filho da puta! você já está morto!",
"Vamos ver",
"Garoto amante! Que prazer ver você vivo! Um bom vento trouxe você de volta para mim!",
"Apenas uma visita amigável para conversar com você, Roxanne!",
"Quero organizar uma expedição com você capitão! Tenho muitos inimigos nessas águas, então seu navio e sua experiência vão ajudar e o saque vai ser bom, sem falar em passar um tempo com você!",
"Com os mesmos termos da expedição anterior! Cinquenta e cinquenta com um saque de ",
"Claro, temos um acordo e nossos inimigos vão tremer nas botas!",
"considerando todas as coisas, terá que ser em outro momento. Eu vou pensar sobre isso",
"Viva, meu amigo! Vamos tomar uma bebida na nossa nova expedição! Estou ficando velho neste porto!",
"Vamos beber ao nosso ouro!",
"Você está me traindo, meu amigo! Você escondeu algum ouro? Se isso é tudo que você tem para compartilhar, vou ficar com todo o saque para mim e matar você por sua incompetência!",
"Você acredita que vai me matar tão facilmente, minha linda!",
"Todos os espanhóis vivos neste mundo são meus inimigos e ouvi dizer que você é amigo da coroa espanhola! Você tem sorte de estar aqui! Enquanto você for aceito nos portos espanhóis, não terei nada a lhe dizer!",
" Sim! Um dia talvez!",
" Mínimo de ouro, vou cortar sua garganta, amor!",
" Para você e ",
" para mim",
" mínimo de ouro para ser compartilhado!",
"",
};
