string DLG_TEXT[26] = {
".....",
".....",
"Sim senhor?",
"Desculpe incomodá-lo, mas estamos procurando um capitão.",
"Tudo bem, eu já estava saindo de qualquer maneira. Este capitão tem nome?",
"Carlos Baxter. Você conhece ele?",
"Conhecê-lo!?! Você é amigo daquele porco assassino?",
"Parece que você o conhece. Não se preocupe, não somos amigos dele.",
"Tenho boas razões para odiar aquele filho da puta sujo e vil... pirata negro!",
"O que ele fez com você?",
"Ele matou meu filho há alguns dias. Ele estava bêbado quando conheceu meu filho na rua. Ele começou a provocar meu filho. Meu filho acabou de dizer para deixá-lo em paz. Baxter não gostou disso e o matou a sangue frio, sem remorso ou outra palavra.",
"Aposto que o governador também não o prendeu.",
"Claro que não, nosso bom Governador é propriedade de Charles Baxter.",
"Como já disse antes, este pirata não tem limites. Porém, eu poderia vingar seu filho, se você me ajudar.",
"Eu não deveria lhe contar isso na igreja, mas tenho orado para que alguém ajude a consertar as coisas, para dar a esse Baxter o que ele merece e um pouco mais. O bom Deus ouviu minhas orações.",
"Sim, sim, o Senhor me enviou [Pensa: e alguém que pague], mas primeiro preciso saber se a caravela atracada no porto é o navio dele?",
"Sim. Por que você pergunta?",
"Eu quero agarrá-la também.",
"Isso deve ser fácil no momento! O forte está em reparos. Ocorreu uma explosão no paiol de pólvora há uma semana. O forte levará alguns dias até estar operacional novamente.",
"Excelente! Somos sortudos.",
"Rezarei pelo seu sucesso.",
"Obrigado. Pouco antes de eu ir, você poderia me dizer onde Charles está?",
"Difícil de dizer. Você visitou a casa dele?",
"Não. Onde está?",
"É a casa perto da taberna.",
"Obrigado. Eu vingarei a morte do seu filho. Isso não o trará de volta, mas Charles não fará mais mães chorarem.",
"",
};
