string DLG_TEXT[27] = {
".....",
".....",
"'Esse homem', como você me chama, tem nome, senhor... E acho que ela não precisa da sua ajuda.",
"'E eu acho' que ela tem idade suficiente para responder às minhas perguntas.",
"(Falando com Lady Montavez)",
"eu estava? Muito bem, continuaremos nosso encontro mais tarde e desta vez sem sermos interrompidos.",
"Você? O que você quer?",
"Preciso da verdade sobre um evento. Quero saber se você pagou aos homens com quem lutei em frente à casa de Lady Montavez?",
"Aprendi essa história de briga na praça do Palácio. Mas não entendo por que você me culpa por estar envolvido neste evento. Parece que você gosta de provocar as pessoas. Você deveria ser mais sábio em seu comportamento.",
"Não sou estúpido, Don Sebastian. Eles não queriam roubar meu dinheiro, não eram ladrões. Eles me queriam longe de Lady Montavez. E só conheço uma pessoa em Cartagena que teve um motivo para me ver longe dela.",
"Você me incomoda com suas acusações. Talvez você seja tolo, mas isso é problema seu, então me deixe em paz antes que eu perca a paciência.",
"Melhor ser um tolo do que um mentiroso e covarde.",
"O que?! Apresente suas desculpas imediatamente ou defenderei minha honra com um duelo.",
"Um duelo? Por que não. Eu nunca me afastei de uma briga",
"Você é realmente arrogante, não é? En garde!",
"Não acredito... Dom Guilherme?!",
"Erro seu, não sou enviado do Rei, foi apenas um disfarce para a minha missão, sou Bartolomeu o Português.",
"O próprio famoso pirata. É uma pena não ter te matado se eu soubesse antes.",
"O que você diz disso? Você não foi capaz de me matar nem no jardim da prefeitura nem quando enviou seus mercenários para a praça.",
"Em ambos os casos, não era minha intenção matá-lo, mas sim dar uma boa lição para deixá-lo longe de Lúcia.",
"Ela não ama homens como você. Você não tem honra.",
"Essas palavras de um pirata são um pouco engraçadas, não é?",
"Meus amigos sabem quem eu sou realmente e isso é o mais importante. Eu não me importo com sua opinião. Então, vamos direto ao que importa. Renda-se e eu deixo você vivo.",
"Bem... Parece que você é um bom lutador pelo que vi da última vez e não tenho certeza se conseguirei vencer um duelo contra você. Então, eu aceito...",
"Pelo menos você é realista. Eu gosto disso. Larguem suas armas e desçam ao convés para ordenar que seus soldados se rendam.",
"Talvez você tenha esquecido, mas eu não sou marinheiro. Pertenço à nobreza espanhola. Eu apenas me renderei dando-lhe minhas armas. Mão a mão...",
"Tudo bem, não vou perder meu tempo discutindo como você deseja se render. Então, vou até você para me dar as armas e rapidamente ordeno que seus homens se rendam. Tenho mais para fazer esta noite.",
};
