string DLG_TEXT[36] = {
"......",
"......",
"Espere um momento meu 'amigo', o que você está fazendo aqui?",
"E você? o que você está fazendo com todas essas mercadorias?",
"*Tom ameaçador* Você está trabalhando para as autoridades espanholas? Porque se estiver, posso dizer que você está com problemas.",
"Eu entendo. Você é contrabandista, não é? Não se preocupe, não estou trabalhando para eles. Mas você está certo, estou com problemas.",
"Agora é a minha vez de não entender...",
"Eu explico. Sou capitão e meu navio afundou durante a tempestade. Alguns membros da minha tripulação e eu estávamos na selva quando encontramos uma patrulha espanhola.",
"E você pediu ajuda, certo?",
"Acho que não, não teria sido a melhor solução no meu caso.",
"HA-HA! Aposto que você é PIRATA!",
"Sim e procurado pelos espanhóis. Consegui escapar da patrulha, mas não da minha tripulação.",
"Qual o seu nome?",
"Bartolomeu o Português.",
"Claro! Você atacou os armazéns do #sSantiago# há algum tempo. Os espanhóis não gostaram nem um pouco do seu desafio descarado.",
"Na verdade, fiz isso quando trabalhei com um pirata francês.",
"Sim, posso confirmar que você está na lista dos mais procurados. Até mandaram um mercenário atrás de você... Pedro Rivera.",
"Pedro Rivera?! Ele uma vez trabalhou para mim! Ele até roubou meu navio.",
"HA-HA! Não sei porquê, mas agora ele trabalha para as autoridades espanholas.",
"Eu sei o motivo. Essa escória é uma oportunista!",
"Sem dúvida você está na sopa e eles estão colocando mais lenha no fogo!",
"Você está disposto a me ajudar?",
"Depende do que você quer que eu faça.",
"Gostaria que você me ajudasse a atacar a patrulha antes que ela chegue a #sHavana#.",
"Espere! Estou disposto a ajudá-lo, mas não a morrer por você!",
"Eu juro que vou te dar uma recompensa...",
"Não, com ou sem recompensa, é muito perigoso! Contrabandear é uma coisa, matar soldados é outra.",
"Bem, eu tenho que libertar meus homens... mas como, não posso fazer isso sozinho",
"Eu tenho uma opção, posso te levar comigo para #sisland_Cayman#. Eu tenho que ir lá para vender algumas mercadorias. Talvez você pudesse encontrar um capitão inglês para ajudar a salvar sua tripulação, eles também não gostam dos espanhóis?",
"Parece um bom plano, de qualquer forma não tenho outras opções. Só espero voltar a tempo de salvar minha tripulação.",
"Isso é feito. Carreguei minhas mercadorias, a maré está subindo e o tempo está bom, estamos prontos para partir. Vou deixar você navegar em meu navio se quiser, tenho certeza de que aprenderei muito com você.",
"Obrigado. Não tenho tempo a perder.",
"Chegamos ao nosso destino. Lamento não poder ajudar mais, mas você entende minha situação?",
"Não se preocupe, você me ajudou o suficiente. Agora, meu trabalho é encontrar uma solução.",
"Boa sorte capitão, bons ventos e que Netuno esteja com você!",
"Obrigado novamente. Vê você!",
};
