string DLG_TEXT[80] = {
"......",
"......",
"Bem, bem, bem... Bem-vindo a bordo da minha nave. Sou Alfonso Galindez, comandante desta pequena frota espanhola. E você, quem é você?",
"Sou Jorge Coelho, um simples comerciante. Por que você parou meu navio?",
"Comerciante simples. Claro, você está brincando, não é? Você acha que sou tão estúpido por não reconhecer piratas!",
"Piratas? Eu acho que você comete um erro. Tenha certeza de que sou um...",
"Parar! apesar de suas modificações neste navio, tenho certeza de que este navio é espanhol. Meus soldados vão inspecionar sua carga. Se você transportar bens roubados, irei prendê-lo e você será acusado de pirataria em #sSanto Domingo#.",
"Há um mal-entendido.",
"Algum problema, senhor?",
"Olá meu amigo, você tem navio ou barco?",
"Sim eu faço. Sou pescador. Por que você pergunta?",
"Eu preciso de transporte. Eu gostaria de ir a Boca de Hubon encontrar alguns amigos no Buccaneer Camp.",
"Hum. E quanto você paga por isso?",
"500 moedas de ouro por nos levar até lá e nos trazer de volta aqui?",
"Insuficiente. Eu quero o dobro disso...!",
"Bem, isso parece um preço alto por algum trabalho de transporte.",
"Certo. Mas aposto que você está disposto a pagar essa quantia. Parece que vocês estão fugindo ou fazendo algo ruim e isso significa risco extra e pagamento extra?",
"Você é esperto. Ok, 1000 moedas de ouro por este trabalho.",
"Junte-se a mim em Boca de Yuman. Enquanto isso, navegarei meu Tartane até lá.",
"Tudo bem.",
"Pronto para ir?",
"Sim. Não temos tempo a perder!",
"Espere!",
"Qual é o problema?",
"Eu quero meu dinheiro agora.",
"Por que não esperar até voltarmos? Você só fez metade do trabalho.",
"Sim, mas não confio totalmente em você. Então, se você quiser voltar para Boca de Yuman, me dê todo o dinheiro agora.",
"Aqui está o dinheiro. Você é muito desconfiado.",
"Hum. Não tenho esse dinheiro agora. Então espere por mim aqui, recebo seu pagamento de #sPort au Prince#.",
"Você está com meu dinheiro?",
"Obrigado, espero por você aqui. Mas, não fique muito tempo no acampamento.",
"Não se preocupe. Eu volto em breve. Só um pensamento: não tente me deixar aqui agora que paguei. Inteligente?",
"Absolutamente.",
"Tudo bem.",
"Podemos ir?",
"Sim, vamos levantar âncora.",
"Ok, eu fiz meu trabalho. Adeus e obrigado!",
"Obrigado! E da próxima vez seja menos... suspeito. ",
"Olá meu filho, você é novo na minha paróquia? Você precisa da ajuda de Deus?",
"Não imediatamente. Primeiro, preciso da sua ajuda.",
"O que você quer dizer?",
"Dê-me o que você tem?",
"O QUE! Não me diga que vocês são ladrões! Roubar é pecado.",
"Realmente? Que vergonha! Repito: Dê-me o que você tem!",
"Mas não sou um homem rico. Tudo o que tenho são minhas roupas.",
"Perfeito! Isso é exatamente o que eu quero. AMÉM!",
"Espere um momento! Oh, desculpe Pai, eu não o reconheci. O que você está fazendo aqui a esta hora?",
"Boa noite meu filho. Fui convocado por um velho da cidade, ele está prestes a morrer. Viemos orar em sua casa entre sua família.",
"Que triste, acho que todos nós devemos partir desta vida algum dia! Por favor, perdoe-me, pai, não vou mais mantê-lo. E peço desculpas, temos ordens de verificar todos que entram na cidade.",
"Eu entendo. Obrigado meu filho. Deus o abençoe!",
"Ei! Você está escondendo uma espada sob seu manto? O que um Padre quer com isso?!",
"Vim te dar minha benção!!",
"Piratas?!",
"E ORGULHOSO disso!",
"Parar! Ninguém pode entrar a esta hora.",
"Como você ousa me impedir! Você é tão cego que não consegue reconhecer um oficial do seu próprio exército?",
"Ah... Desculpe, capitão. Claro, esta medida é apenas para civis. Não reconheci seu uniforme no escuro.",
"Assim é melhor, particular. Acabei de dar um passeio fora dos muros. A noite está muito quente e tenho tido dificuldade em dormir.",
"Capitão, é a primeira vez que o vejo. Quando você chegou na cidade?",
"Humm.. Há alguns dias a bordo de um navio vindo de Havana. Bem, agora não tenho tempo para mais explicações, ou terei que dar outro passeio. Volte para sua postagem.",
"Ao seu comando, Capitão!",
"Parar! O que você quer?",
"Você não vê? Estou trazendo um prisioneiro.",
"Nesta hora?",
"Claro, ele foi preso na taverna há poucos minutos após iniciar uma briga.",
"Outro bêbado.. Tudo bem, entre!",
"Claro, ela foi presa há poucos minutos após iniciar uma briga.",
"Isso é o que acontece quando damos arma e rum para uma mulher, Haha!! Tudo bem, entre!",
"Olá amigo! O que você quer beber?",
"Na verdade, quero uma informação. Gostaria de saber se neste momento há alguém na sua taberna que trabalhe no forte.",
"Um soldado, você quer dizer?",
"Não, um civil. Certamente, há pessoas não militares trabalhando no forte.",
"Sim claro. Conheço Agilo Casamayor, ele é cozinheiro. Mas ele acabou de sair da minha taverna.",
"Onde ele foi?",
"Ele foi para casa.",
"Você pode me dizer onde ele mora?",
"No primeiro andar de uma casa em frente aos portões do porto...",
"Obrigado, vou falar com ele.",
"ALARME!!! ALARME!!!",
"Caramba!",
};
