string DLG_TEXT[27] = {
".....",
".....",
"Você não sabe bater na porta antes de entrar, Capitão!",
"Primeiro, não entrei pela porta. Em segundo lugar, não sou um capitão espanhol, mas sim um capitão pirata.",
"O que você está falando???!",
"Sou Bartolomeu o Português. Suponho que você já ouviu meu nome no passado.",
"Caramba! Guaarr..",
"CALE-SE! ou eu te mato onde você está.. Não faça barulho.",
"Tudo bem, serei rápido. Onde está Roxanne Lalliere?",
"O que você quer dizer?",
"Quero dizer que você está desperdiçando meu tempo, Governador. Você sabe que alguns mercenários a sequestraram e a trouxeram de volta para esta cidade, mas você está tentando me levar pelo caminho do jardim. Dou-te uma segunda e última oportunidade: onde ela está?",
"Tudo bem, não se preocupe... Ela não está aqui na cidade, mas foi transferida para o forte.",
"Por que o forte?",
"Porque é mais seguro que a prisão da cidade.",
"Agora, me dê o nome desses mercenários.",
"Johan Elting e Nicholas Butcher.",
"Ambos estão aqui?",
"Não, apenas Elting. Butcher já partiu para Havana.",
"Você sabe se Emilio Soares, meu oficial, está com Roxanne?",
"Não, ela está sozinha.",
"Veja, minhas perguntas são fáceis. Então, tem uma prisão no forte?",
"Sim, sob o forte.",
"Quem tem as chaves da prisão?",
"O capitão do forte. No entanto, há muitos soldados lá, você não pode libertá-la. É uma missão impossível, você deveria se entregar.",
"MISSãO IMPOSSÍVEL, você diz. Acho que não, você me subestima. Elting está lá também?",
"Eu suponho que sim. Ele me disse que queria cuidar do capitão Lalliere até que os reforços chegassem de Havana. Você sabe que não tem chance",
"Bem, eu sei o suficiente agora. Boa noite, Governador!",
};
