string DLG_TEXT[29] = {
"....",
"....",
"Olá, Capitão!",
"Eu conheço você. Você estava na Residência.",
"Certo. Estou trabalhando para Gilroy.",
"O que você quer exatamente? Seu chefe decidiu me dizer onde Charles está?",
"Não, ele não vai te contar, você está sonhando. Mas eu, você poderia ter mais chance, esclarecido?",
"Você parece ser mais inteligente. O que você quer em troca de informações.",
"Ouro, é claro. Na verdade, 4.000 moedas de ouro.",
"O que?! 4.000 por uma pequena informação? Acho que você está sonhando, não eu",
"Como quiser, amigo. Tenha um bom dia!",
"Espere! Podemos discutir a soma, não podemos?",
"Não. Não sei por que você quer conhecer Charles. Mas sei que terei problemas se meu chefe descobrir que revelei essa informação. Então, não vou vendê-lo por menos.",
"Ok, eu aceito. Aqui está o dinheiro.",
"Ok, aceito, mas me dê mais tempo para encontrar o dinheiro.",
"Tudo bem, volte aqui com o dinheiro da próxima vez.",
"Eu farei isso.",
"Obrigado! É um prazer lidar com você.",
"Talvez. Agora, eu quero a informação.",
"Claro. No momento, você pode encontrar Charles em #sCharlestown#.",
"#sCharlestown#?! O que ele faz aqui?",
"É um lugar seguro para ele. Ele corrompeu o governador. Para que ele possa morar lá com calma.",
"Este pirata não tem limites.",
"De fato. Bem, seria suspeito ficar aqui com você por mais tempo. Meu chefe tem amigos em todos os lugares desta ilha, então adeus amigo!",
"Espere! Que garantias tenho que esta informação é verdadeira.",
"Eu te contei o que sei. Meu chefe tem as mesmas informações que você. Então, se você não acredita em mim, o problema é seu!",
"Tudo bem. Esperemos encontrar Charles em #sCharlestown#.",
"Você tem o dinheiro?",
"Sim, pegue!",
};
