string DLG_TEXT[36] = {
"E você está fazendo o que no meu quarto...?",
"Eu não sou um ladrão, Vossa Reverência.",
"Aha, um intruso educado. E um mentiroso. Você é mais do que um ladrão. Talvez o Capitão dos ladrões.",
"Reverenda Madre, eu sou um Capitão mercante - isso é tudo.",
"Eu já fui um corsário, isso é verdade. Mas era guerra.",
"Apenas rumores - rumores ruins. Acho que é por causa da pintura.",
"Tudo bem, Reverenda Madre, sim, eu sou um pirata.",
"Fui abandonado por uma tripulação pirata - isso é verdade. Dões que me tornam um pirata?",
"Pena que você escolheu continuar mentindo. Tente de novo!",
"Corsário é verdade. Mas isso não é tudo. Diga a verdade!",
"Mas você é retratado como um pirata. Com nome e tudo! É melhor você dizer a verdade!",
"Assim é melhor. E você quer tanto esse pedaço de mapa porque espera que ele mostre o caminho para tesouros enormes?",
"Não a parte do abandono, mas você não me conta tudo. Tente de novo!",
"Você está disposto a vendê-lo, Sua Reverência?",
"Hmm, eu queria saber se você poderia me fazer um favor em vez disso. Mas é perigoso.",
"Eu não estou com medo. Diga-me o que fazer.",
"Eu quero que você colete os itens que preciso para o serviço de hoje. Devolva-os para mim e eu lhe darei a outra metade do mapa.",
"Sem problemas, Reverenda Madre. Onde encontro esses itens?",
"Você tem que procurar nas Criptas e na Capela Pequena no Cemitério, Capitão.",
"Quais são os itens?",
"Uma bíblia, velas de cera, pão de altar, um incensário, uma cruz de prata, um rosário, um ícone e uma relíquia. Um total de oito itens.",
"(Puh!!) Muito bem, logo volto, Vossa Reverência.",
"Ahh Capitão, você trouxe todos os meus itens preciosos?",
"De fato, eu trouxe, Reverenda Madre.",
"Muito bem. Se você apenas mudasse seus hábitos, meu caro Capitão. O caminho da pirataria leva apenas à condenação, meu filho.",
"Hrmpff...",
"Agora, para minha parte do acordo - aqui, pegue o pedaço do mapa. Bons ventos para você, Capitão.",
"Muito obrigado, Vossa Reverência. Adeus.",
"Graças a Deus, todos nós sobrevivemos! E obrigado, Capitão Pyle, por sua ajuda.",
"De nada, Reverenda Madre.",
"E agora, Irmã Richards, você poderia, por favor, destrancar o Portão do Claustro para o Capitão Pyle.",
"---",
"Agora não, por favor, vá embora.",
"Oh, desculpe, Vossa Reverência.",
"Sim, mas por que você o rasgou e onde está a outra metade?",
"Eu precisava de um pedaço de papel para uma nota. Mas eu tenho a outra parte também.",

};
