string DLG_TEXT[106] = {
"O caminho da pirataria leva apenas à condenação, meu filho!",
"Umm... err... Entendo. Desculpe por ter incomodado você. Adeus.",
"Bem-vindo, meu filho, eu estava esperando por você.",
"Eu já o vi aqui antes, quem diabos é VOCÊ?",
"Cuidado com a língua, capitão, eu sou apenas um simples marinheiro que encontrou Deus.",
"Você é o homem que foi abandonado e foi salvo depois de anos e anos naquela ilha sozinho, certo?",
"De fato eu estava, mas encontrei companhia na Bíblia, meu filho. Então o governador Woodes Rogers chegou com os navios Duke e Duchess depois de 4 anos.",
"Eu ouvi sobre você, não há um romance baseado em sua aventura?",
"Ainda não, mas dizem que o escritor Daniel De Foe está trabalhando em algo. Outra coisa, eu não fiquei abandonado...",
"Mas mas é verdade que você ficou lá, naquela ilha?",
"É, mas foi tudo voluntário. O Comandante Dampier (aquele suposto piloto, hmm hmm) e eu discutimos sobre a navegabilidade de 'Cinque Ports'.",
"William Dampier é outro autor famoso também. 'A New Voyage Round the World'.",
"Ele é um pouco mais do que um escritor, de qualquer forma o Governador não só me resgatou, ele também deixa eu e meu amigo ficarmos aqui em seu... err... err depósito.",
"Sim, há muitos bens aqui, de onde eles vêm?",
"Sou totalmente leal ao Governador e seus amigos, não a seus oficiais (como Dampier, por exemplo).",
"Entendo! O Governador realmente parece ser um homem rico...",
"O caminho da pirataria leva apenas à condenação, meu filho!",
"Sim, eu sei... Foi bom falar com você, Selkirk, adeus.",
"Tah chaed um-rahkya sah-idi' significa 'a jovem voltou' capitão!",
"Tudo bem, chega disso, vou procurar Caroline.",
"Ahh, você chegou bem a tempo de me ajudar, Capitão.",
"Claro, Selkirk, o que posso fazer por você?",
"O Governador me deu a responsabilidade por esta biblioteca, sabia...",
"Ohh! (Eu nem sabia que ele sabia ler!)",
"Você não esperava que eu soubesse ler ou escrever, não é, garoto?",
"Bem, eu...",
"Talvez você não saiba que eu já fui um mestre de vela!",
"É mesmo?!",
"Agora, Capitão, para o meu pequeno problema aqui.",
"Vá em frente, Navegador!",
"Perdi meus óculos e sem eles não tenho chance de ler os textos menores. Os livros foram movidos e as coisas não funcionam mais direito. Por favor, Capitão, devolva esses livros aos seus devidos lugares.",
"Sem problemas, apenas entregue-os. (Não é um desafio para um Capitão Pirata!)",
"E melhor ainda se você conseguir encontrar meus óculos!",
"Vou ver o que posso fazer aqui!",
"Olá meu amigo, como você está aqui?",
"Olá novamente, Sr. Selkirk. Estou bem, obrigado - tenho algo para você!",
"Oh, um par de óculos - agora posso retomar a profissão de bibliotecário. Obrigado por toda a ajuda aqui. Deixe-me dar um conselho antes que você termine aqui, Capitão.",
"Claro, o que é?",
"Você é um jovem Capitão inteligente - por que não pega todos os livros que puder carregar? Aqui está algo que pode ser útil!",
"Obrigado - vou seguir esse conselho.",
"Ahoy, Capitão! Mude seus maus hábitos e não acabe na cadeia, ou mais provavelmente, seja enforcado.",
"Mas Selkirk, eu não sou um pirata, não importa o que você acredite.",
"No dever do Governador, há muitos homens - homens inescrupulosos com uma péssima reputação.",
"Sim, eu conheci alguns de seus homens e eles parecem durões - mas, afinal, eles são caçadores de piratas.",
"Aventureiros, Exploradores, Caçadores de Piratas, Receptores, Donos de lojas de antiguidades, cidadãos muito respeitados... muitos são os nomes!",
"Ah, vamos lá Selkirk, você não pode estar falando sério...",
"Só deixe-me lhe dar este aviso: Existem criaturas realmente más nos túneis, mas elas só têm medo de uma coisa, Capitão...",
"Mudou de assunto, hein? Ok, e o que pode ser?",
"Abra fogo, Capitão!",
"Tudo bem, terei cuidado lá embaixo, e obrigado Selkirk!",
"Ah, sim, Fried-Egg me lembra que eles não enxergam muito bem!",
"Fried-Egg??! Que horrível se dirigir ao seu suposto amigo de uma forma assim só por causa da cor de...",
"Escute, seu jovem capitão inteligente, o famoso Daniel De Foe escreveu sobre nossa estadia naquela ilha e como tínhamos carne de cabra e pão assado para sobreviver!!!",
"Sim, estou ouvindo, por favor, continue.",
"Bem, nada poderia estar mais errado, a única coisa que encontramos para comer foram ovos de pássaros, então aí está você com seus preconceitos!",
"Hmm, desculpe Selkirk.",
"Dizem que o autor é mantido como prisioneiro entre outros. Posso garantir que estamos fazendo de tudo para lhe trazer os medicamentos exigidos.",
"Fico feliz em ouvir isso.",
"Os cidadãos de Port Royal foram ordenados a entregar tudo o que puderem de curas e drogas. Coloquei o (chamado) Oficial Sr. Cook no comando para supervisionar isso.",
"Onde posso buscar essa coleção?",
"As pessoas estão reunidas perto dos sinos da igreja.",
"Vou cuidar disso imediatamente, Selkirk!",
"Sinto muito, mas não uso remédios - mas tenho certeza de que Fried-Egg tem algumas curas estranhas - onde quer que ele esteja agora.",
"Tentarei visitá-lo mais tarde.",
"Oh, você está procurando meu amigo e seus remédios, eu acho.",
"Isso mesmo, Selkirk.",
"Sim, tenho que avisá-lo também, Capitão. Cuidado com Dampier, ele é muito cruel - você sabe que foi ele quem me abandonou!",
"Oh, é mesmo?",
"A única proteção que você vai precisar, meu filho.",
"Bem, obrigado Selkirk, eu vou embora de novo. (Ah, não, agora são livros de novo!)",
"Capitão, você conseguiu! Você está seguro aqui.",
"Onde estou, Selkirk?",
"Este é o quarto secreto do Governador - os Oficiais não sabem sobre ele. Fried-Egg dorme aqui.",
"O Governador Rogers está morto?",
"Meu amigo pergunta se você sabe nadar, Capitão?",
"O quê?! Claro que sei - por que ele está perguntando sobre isso agora?",
"Estranho o suficiente, não há muitos marinheiros que sabem nadar, Capitão - eles vão se afogar como ratos se caírem no mar.",
"Tudo bem, tudo bem, eu gosto de nadar, como eu saio daqui?",
"Capitão, antes de você ir - eu tenho algo para você...",
"Ah, sim? O que pode ser?",
"Agora, o que é isso, Capitão?! O Governador foi morto, Caroline desapareceu e estamos sendo sequestrados por esse bando de...",
"Calma, Selkirk, esses cavalheiros decidiram nos ajudar com Dampier e os outros assassinos.",
"Hmm, essa é outra coisa. Os oficiais e seus homens foram embora. Eles pegaram as naves. Podemos nos juntar a essa companhia?",
"Claro, você e seu amigo são bem-vindos.",
"Muito bem! E como saímos daqui, Capitão? -",
"- todas as saídas estão trancadas ...",
"... exceto por uma janela em seu quarto Fried-Egg diz.",
"Hmm, isso é muito, muito alto, mas parece que não tenho escolha ...",
"Olha Capitão, eu encontrei esta chave ...",
"Bom trabalho - você encontrou mais alguma coisa?",
"Ei Capitão, este canhão está carregado!",
"Tudo bem, esteja pronto para atirar, Sr. Selkirk.",
"Não, ele está apenas atordoado -",
"- é um milagre: minha bíblia o salvou!",
"Fried-Egg encontrou uma escotilha aberta!",
"Vamos tentar então Selkirk!",
"Mas vovó, não temos tripulação -",
"- os únicos leais são a tripulação do canhão surdo!",
"Tem alguém no telhado -",
"- diz Fried-Egg.",
"Um mapa do tesouro mostrando uma porta e duas letras? E nenhuma informação adicional...",
"Não, isso é tudo (exceto o caderno). Acho que precisamos de mais mapas, este não é o suficiente.",
"O tesouro do Barba Negra - você está falando sério?",
"É, como ele poderia ter alguma riqueza escondida de Hornigold?",
"De fato, eu tinha, Capitão. Olha, aqui está Pólvora seca e um Sabre!",
"Lidere o caminho para fora, Senhor Selkirk.",

};
