string DLG_TEXT[30] = {
"Não ouse se dirigir a um Carpinteiro dessa maneira novamente, seu mercenário insolente!",
"Umm... err... Entendo. Adeus.",
"Ei, você aí! Você parece suspeito para mim. Quem diabos é você? Mostre-me seus papéis!",
"Quem diabos é VOCÊ? Identifique-se e seja rápido!",
"Alto! Nunca o vi antes, mas você tem cara de pirata! Você pode provar que não é nenhum?",
"Eu sou ",
", e aqui estão minha comissão de capitão e meus papéis de navio para provar isso. Isso foi rápido o suficiente para seu temperamento explosivo?",
"Seu navio foi completamente revisado. Não que eu achasse necessário, mas essas foram as ordens do Governador.",
"Você encontrou algum dano?",
"Nenhum dano, e se houvesse algum - por que eu deveria me importar?! ",
"Todos os danos, tanto no casco quanto no mastro, foram reparados, assim como Rogers quer, não eu - eu posso te dizer!",
"Todos os danos no casco foram reparados, assim como Rogers quer, não eu - eu posso te dizer!",
"Todos os danos no mastro foram reparados, assim como Rogers quer, não eu - eu posso te dizer!",
"Ah sim - aqui está outro cara legal!",
"Eu também forneci tábuas e lona para seu navio. Agora, para aquele seu baú...",
"Huh?",
"Incrível como você conseguiu destruir as duas portas. Entregue-o, garoto, e seja rápido!",
"Tudo bem, pegue-o então - mas cuidado com sua língua, reparador!",
"Sr. Fry para você - Eu sou o Carpinteiro, um Oficial! Vá embora por um tempo e deixe-me trabalhar. Dê uma olhada no estaleiro se quiser ou vá para o inferno - eu não me importo.",
"Só conserte, ok?",
"O baú está consertado - saia da minha vista agora. Você já tem muito - é o que todos nós pensamos!",
"É, é o que você pensa, hein? Lembre-se, carpinteiro, que o Governador Rogers é quem está no comando por aqui - não você ou seus colegas oficiais!",
"Fale, fale e fale. Ele nunca deveria ter lhe dado aquelas pistolas - elas pertencem a nós - seus leais tripulantes!",
"O que há de tão importante com essas armas, afinal?",
"Eu também forneci tábuas para seu navio. Agora, para aquele seu baú...",
"Eu também forneci lona para seu navio. Agora, para aquele seu baú...",
"Por que diabos você não trouxe? Eu deveria consertá-lo - estúpido!",
"Bem, eu ... (Ele está certo, eu tenho que pegar o baú de remédios.)",
"Agora, para aquele seu baú...",
"O que tem isso?",

};