string DLG_TEXT[65] = {
"Senhor Hands!",
"?",
"Senhor Hands e Senhor Pell!",
"O Governador Eden me salvou no último minuto. Mas quem é o novo Capitão?",
"Sou Howard Pyle. Por que Eden deixou você viver?",
"Cale a boca, Hennington -",
"- isso não é da sua conta!",
"O Governador imaginou que eu também tinha um mapa de Teach. Ele me pressionou para descobrir onde ele estava.",
"E você o revelou?",
"Não. Eu o perdi durante a batalha final. E essa é a verdade.",
"Entendo. Você já reparou onde o Governador guardava seu próprio mapa?",
"Não, talvez em seu escritório. Nós, servos, nunca tínhamos permissão para entrar.",
"Estou interessado em comprar a propriedade. Posso dar uma olhada lá dentro?",
"Este homem é um ladrão, Sra. Pough. Se não acredita em mim",
" - pergunte a ele o que estava fazendo no escritório do Governador.",
"Hah, estou saindo daqui",
"- junto com meus amigos!",
"Vou te seguir.",
"Muito bem.",
"Ok, vamos falar sobre o mapa, Capitão Pyle.",
"Conseguiu?! Estamos um passo mais perto, então.",
"Quero uma parte do tesouro se você o encontrar.",
"Claro - partes iguais para todos. Agora me entregue.",
"Bem, Capitão Pyle, o que você descobriu até agora?",
"Encontrei os destroços do último saveiro de Teach.",
"Você vasculhou o Porão?",
"Sim, e até mesmo o Depósito de Pólvora, se você o tivesse escondido lá.",
"Mas eu vasculhei. O que você encontrou?",
"Nada além de pólvora.",
"Hmm, talvez ainda esteja lá embaixo da pólvora.",
"Vamos para Turks então!",
"Eu sei que a chalupa do Teach foi vendida para um comerciante em Turks.",
"E mais...?",
"Falei com ele, mas ainda não encontrei os destroços.",
"Coloquei o mapa no depósito de pólvora. Talvez ainda esteja lá.",
"Ainda não encontrei os destroços em Turks.",
"O Tenente Maynard recebeu a chalupa como recompensa. Ele mora em Citadel Rock, na ilha de Eleuthera.",
"Vamos para Eleuthera então!",
"Talvez Samuel Odel, do Covil dos Contrabandistas, em La Grenade, saiba o que aconteceu com o saveiro.",
"Vamos para La Grenade então!",
"E não tem outro jeito de entrar no escritório?",
"Tem alguém vindo para cá, Capitão.",
"De fato, e com muita pressa também.",
"Ele é um bom corredor, esse cara.",
"Sim, para alguém com uma perna de pau. ",
"Perna de pau - espere um minuto, parece que...",
"... Israel Hands!",
"Bem-vindo de volta, Senhor Hands. Aqui, temos armas para você. Agora somos três sobreviventes!",
"Quatro Césares, quatro! O Contramestre também está aqui.",
"Senhor Pell? Onde ele está?",
"Ele achou que viu algo no mar, então subiu na Torre para ver melhor.",
"A propósito, veja o que eu encontrei na areia, Capitão.",
"Meu Cinto e a Pintura também!!",
"Rico como trolls, essa foi nova. Mostre o caminho, Capitão, para o Tesouro na montanha.",
"Hmm, não podemos entrar por ali. Seremos mortos por uma armadilha mortal. Mas há uma entrada secreta do mar para a caverna de Teach.",
"Os últimos sacos estão a bordo. Temos que nos apressar, Capitão. O Sr. Hands está preocupado com o tempo...",
"Sim, sim. Vamos lá.",
"Capitão, está aberto para o convés dos escravos!",
"Muito bem, César. Você e o Rei, vão e peguem todas as armas que puderem carregar.",
"Não adianta, Capitão - as tábuas estão pregadas no convés.",
"Certo - teremos que encontrar outra maneira de entrar então.",
"Temos as armas, Capitão.",
"Essa foi rápida.",
"Certo, mas não sei dizer qual ilha é, Capitão.",
"Como assim? Deixe-me dar uma olhada mais de perto.",

};
