string DLG_TEXT[165] = {
"Sou eu quem manda nestas águas -",
"- e NUNCA aceitarei um perdão, nem mesmo um 'Woodes-Rogers'!",
"... e como chegou aqui?!",
"Sou o Capitão Pyle, às suas ordens, Senhor. Foi um acidente na velha mina, de repente pedras começaram a cair e finalmente o túnel inteiro desabou.",
"Jovem Capitão educado, hein? E o que diabos você estava fazendo naquela mina?",
"Bem, é uma longa história...",
"Olhe bem ao seu redor - você certamente não é um membro daqui. Conte a história se quiser continuar vivo!",
"!!!",
"Então, por favor, Capitão...",
"Tudo começou há algum tempo, quando concordei em ajudar Woodes Rogers a encontrar...",
"Sua história tem que ser realmente boa depois de mencionar esse nome!",
"Bem, a filha dele foi sequestrada e eu descobri que ela tinha sido vendida para um bordel em ...................................",
"...................................................... e depois disso você caiu pelo chão do túnel direto para a nossa caverna?",
"Sim, essa é toda a minha história verdadeira!",
"Bem, meus Capitães, o que faremos com este cavalheiro?",
"(engoli em seco)",
"Esperem um minuto, tenho uma ideia melhor...",
"(Acho que estou em sérios apuros agora)",
"Por que não deixar que este Capitão desconhecido seja aquele que coleta ",
"o resgate pelos nossos queridos 'hóspedes' lá no porão?",
"Bem, então, o que você diz, Capitão Pyle - interessado em uma pequena missão?",
"Nunca - eu não sou pirata!",
"Hmm, o que isso traz? eu?",
"Parece que não tenho escolha!?",
"Tudo bem, eu faço isso.",
"Livre-se dele!",
"Não, espere!!!",
"Você é ganancioso, Capitão? Que sorte a gente não te matar. Pegue o ouro e todos os itens dele!",
"(Ah, não, aqui vão meu ouro e minha coleção de pistolas - tanto trabalho para nada!)",
"O que você é, carpinteiro ou Capitão!? Essas ferramentas não servem para mim - por favor, tire-as daqui.",
"Bem, obrigado, Capitão Vane - e minhas pistolas...?",
"Sim, suas pistolas - elas me parecem um pouco familiares - dê uma olhada, Calico Jack - você não acha que já vimos essas antes...?",
"(Interessante - mas do que ele está falando?)",
"Eu pensei que você fosse um homem do meu tipo, a tarefa é simples. Já enviamos nossas exigências para Port Royal, você só precisa pegar as coisas!",
"Como volto para a cidade e quem devo encontrar lá?",
"Nós o levaremos até lá, bem, vá até aquele maldito governador Rogers - e sobre suas pistolas - você as recuperará após uma missão bem-sucedida.",
"Quero ver os prisioneiros antes de partir!",
"Realmente não consigo entender o porquê, mas tudo bem então.",
"Agora me deixe sair daqui.",
"Só uma coisa, jovem e inteligente capitão. Não tentem ser espertos demais e levar alguém até nós - se for o caso, os prisioneiros estão mortos!",
"Entendo.",
"Primeiro, entreguem seu ouro e aquelas armas que vocês têm aí - elas me parecem um pouco familiares - dêem uma olhada, Calico Jack - vocês não acham que já vimos essas antes...?",
"(Ah, não, aqui vão meu ouro e minha coleção de pistolas - tanto trabalho para nada!) E a missão?",
"Calem a boca, seus desgraçados - ",
"- ou eu atiro no próximo que estiver me perturbando!",
"Se vocês se acalmarem - ",
"- Vou deixar todos vocês usarem os remédios.",
"Ah, o jovem Capitão de novo - ",
"- por favor, sentem-se e falaremos de negócios!",
"Eu sabia que você era um jovem confiável desde o primeiro momento -",
"- por favor, Sr. Rackham, devolva os pertences do Capitão Pyle.",
"Vocês cumpriram sua missão e recuperaram suas pistolas de curiosidade. Não receberam mais nada pertencente a essas armas? Agora, para outro assunto...",
"Sim, o quê. (O que mais tem com as pistolas?)",
"Você cumpriu sua missão e recuperou suas pistolas Curious. Não recebeu mais nada pertencente a essas armas? Gostaríamos de lhe oferecer uma recompensa...",
"Estou ouvindo... (O que mais tem com as pistolas?)",
"Os capitães aqui são marinheiros muito experientes e concordaram em lhe ensinar uma nova habilidade.",
"Os capitães aqui são marinheiros muito experientes e concordaram em lhe ensinar duas novas habilidades.",
"Os capitães aqui são marinheiros muito experientes e concordaram em lhe ensinar três novas habilidades.",
"Bem, isso foi incrível!",
"Posso treinar sua habilidade de Defesa Básica.",
"Eu certamente digo sim a isso!",
"Os capitães têm você em alta conta e talvez você tenha a chance de ser um membro deste grupo. ",
"Bem, não parece interessante... (Direto para a forca, eu suponho)",
"Nós discutimos sua história e há um detalhe interessante sobre os Costbrothers - eles tinham capuzes pretos de monge, você disse!?",
"Claro, parecia um monastério - à primeira vista.",
"Consiga algo parecido e você terá ajuda desses 'irmãos' sempre que precisar.",
"(Engula outra missão) Tudo bem, vou ver o que posso fazer a respeito. Mas primeiro, você prometeu deixar os prisioneiros saírem!",
"Eu sempre cumpro minha palavra, vá em frente e tire-os daqui - ",
"- tivemos que movê-los para um lugar mais seguro, no entanto.",
"Quem está aí, e seja rápido - monge!",
"Sou eu, Howard Pyle, Capitão Vane!",
"Pyle, você voltou!",
"Sim, mas eu pensei que todos por aqui estivessem bêbados de morte.",
"Nem todos, na verdade, mas você tem algo para mim. Certo?",
"Sim, aqui mesmo - talvez essas roupas possam ser úteis para os 'irmãos'?",
"Deixe-me ver - entregue-as ao Capitão Pyle.",
"(Agora é Capitão!!) Claro.",
"Excelente trabalho - os irmãos vão votar em você para isso, Capitão!",
"Hmm, eles parecem um pouco... cansados?",
"Vou acordá-los - isso vai ser muito engraçado -",
"- veja você mesmo por aquela janela...",
"Bem feito para eles! Agora, para outro assunto, Capitão.",
"(Capitão quer dizer que quer algo de mim de novo...) Capitão Vane, vim aqui porque preciso de ajuda. Eles mataram o Governador Rogers!",
"Quem fez isso - e acho que você está preocupado com seus amigos?",
"Os oficiais dele o assassinaram - um bando de amotinados!",
"Hmm, vou te ajudar, mas primeiro, com este meu probleminha...",
"O que foi, Capitão?",
"Estamos trancados aqui. A porta da caverna está trancada - não me pergunte como.",
"Não tem nenhuma porta dos fundos?",
"Vamos descer e eu te mostro...",
"Certo.",
"Cavalheiros da fortuna - ",
"- Tenho uma pergunta muito importante.",
"Dois já saíram!? Para o resto de vocês:",
"Quem pegou as moedas da caixa de coleta???",
"Já ouvimos falar de suas 'riquezas' centenas de vezes - ",
"- e as MOEDAS!?",
"Por favor, Capitão Pyle, veja como as coisas são por aqui... Tente encontrar as moedas certas e coloque-as na caixa de coleta.",
"(Capitão de novo - deve ser difícil ser um Almirante Pirata com tantos colegas) Vou ver o que posso fazer!",
"Mostrem-me suas mercadorias.",
"Muito bem.",
"Ah, sim, quase me esqueci - talvez vocês tenham alguma utilidade para isso, Capitão...",
"Hã? (O que ele está aprontando agora.)",
"Conseguiu, Capitão! Agora vamos sair daqui.",
"Muito bem. (Agora, o que é essa coisa na cabeça dele!?",
"Certo, cavalheiros, ouçam com atenção:",
"Vamos fazer um ataque noturno - e tomar um ou dois navios!",
"O Sr. Exquemelin está no comando da defesa aqui. O Capitão Roberts segue o caminho pela cripta e limpa as adegas - o ponto de encontro é a mina. ",
"Escolha seus homens!",
"Agora, Capitão Pyle, mostre-nos como você chegou aqui da primeira vez...",
"Siga-me então.",
"Precisamos de uma escada aqui...",
"... ESCADA!!!",
"Parem com essa conversa idiota -",
"- e peguem suas roupas novas!",
"Agora, se não se importam, deixem a escada aqui -",
"- e voltem para a costa. Mantenham os olhos abertos e vocês receberão suas partes do saque!",
"Agora vamos expulsá-los como ratos - ",
"- os encontraremos onde quer que estejam escondidos.",
"Taylor, você fica com a loja, La Buze com a residência -",
"- e Calico Jack com a cozinha. Vamos lá!!",
"... mas desta vez vou abrir uma exceção:",
"Selkirk tem um ótimo motivo para se juntar a nós, Capitães - ele é o único que foi abandonado por Dampier!",
"Ouçam com atenção agora: Calico Jack leva seu grupo para o outro lado do galeão - ",
"- vocês devem ficar na água e não fazer nenhum barulho até que tenhamos dado uma rajada de corveta neles!",
"Ah, CALEM A BOCA! Vocês vão estragar tudo com esse barulho? -",
"- coloquem suas máscaras e vão embora!!",
"Capitão, os canhões estão carregados, mas vocês precisam remover o elevador antes que possamos atacar!",
"Vou ver o que posso fazer. (Sempre eu para fazer as partes difíceis!) Onde estão todos?",
"Eles estão a bordo do galeão, ocupados se embebedando - mas cuidado, pode haver guardas nos dois navios!",
"Tudo bem, vou levar Selkirk como companhia!",
"Depressa, Selkirk já começou a revistar a corveta.",
"Estou a caminho.",
"Capitão Quelch, leve alguns homens e revista aquela casa da fazenda -",
"- depois guarde a costa e mate todos que tentarem escapar por aqui!",
"Rápido, tire as roupas dele -",
"- e veja como ele está ferido!",
"........ caso contrário, capitães, despachem-se e revistam o galeão -",
"- vejam se há alguma porta aberta para aqueles covardes escondidos!",
"Ela está afundando, soltem-na rápido -",
"- se quiserem salvar a corveta!",
"Malditos idiotas! Do que estão reclamando -",
"- vamos pegar este navio: uma CORVETA!!! Um dos melhores navios de todo o Caribe.",
"Cuidado com a língua, Sr. Quelch -",
"- ou você a perde!",
"Vamos sair daqui agora - então, se não se importa, Capitão Pyle...",
"Meus inimigos foram derrotados e você pegou sua corveta, então acho que é adeus...",
"A menos que não queira se juntar a nós, Capitão. Um 'Cavalheiro da Fortuna' - o que me diz?",
"Obrigado, mas ainda tenho alguns negócios com a família Rogers. Mas parece muito tentador...",
"Ah, sim, Capitão, isto é para o senhor. Um pombo-correio trouxe aqui. É algum tipo de código?",
"Hmm, não tenho certeza (do que dizer a ele...), deixe-me examiná-lo de perto. (algo escondido no próprio jogo??) ",
"Vamos lá, Capitão, você está indo muito bem.",
"Ahh, obrigado, Capitão Vane.",
"Só um detalhe: pode me entregar as moedas extras agora.",
"Certo, aqui está... (Eu pensei que fossem minhas!)",
"O que foi desta vez, Pyle?",
"Edward Teach visitou você pouco antes da última luta dele, certo?",
"O que tem?",
"Esse tal Richards o acompanhou? Ele era o tenente do Teach.",
"Jack, cuide dessa máquina antes que você mande todos nós para o inferno!",
"!!!",
"Navegamos com você por anos",
"e conquistamos muitos prêmios excelentes também.",
"Voltem aos seus postos, homens -",
"- Calico Jack está de volta!",

};
