string DLG_TEXT[26] = {
"Sim, sim, sim. Mas você precisa entender que há -",
" - muitos problemas relacionados a este navio.",
"Em primeiro lugar: ",
"o navio foi tomado em tempos de paz!",
"Sim -",
" - você leu livros demais; Professor.",
"Em segundo lugar: ",
"aquele navio pertencia a mercadores ingleses!",
"...ou ele nos mandará todos para a forca. Em terceiro lugar:",
"você nunca recebeu nenhuma comissão na vida, Professor.",
"É...",
"...é o que eu acho que pode ser?",
"Muito bem! Mas mesmo que eu vote na sua sugestão -",
" - o tribunal jamais aceitará esse seu prêmio.",
"Hmm, isso depende do tipo de carga -",
" - e do tamanho da parte; Capitão Teach.",
"Acho melhor guardá-lo no celeiro da minha secretária. -",
"- Por favor, mostre o caminho, Senhor Cavaleiro.",
"Agora, sobre o navio em si...",
"Sim...",
"Queime-o, Teach, queime-o até a quilha.",
"Certo. Senhor Richards, descarregue a carga e você, Senhor Morton, cuide da queima!",
"Pronto, Teach, para ver o navio em chamas?",
"Só mais uma coisa, Governador. Entregue essa sua pistola.",
"Claro, mas por quê, Capitão?",
"Você verá um dia...",

};
