string DLG_TEXT[30] = {
"Tirem-nos daqui!",
"Shhh! Estou a trabalhar nisso.",
"Sou um cirurgião experiente.",
"O quê? Você é um condenado! (Ele lembra-me alguém...)",
"Não me reconhece, Capitão?",
"Bem, eu... (onde é que eu já vi um tipo como ele?)",
"Tentou matar-me em Citadel Rock!",
"De novo. Um bandido!!",
"E talvez seja... um Capitão mercante?",
"Grrr... (outro personagem irritante a bordo)",
"Sangue. Peter Blood, às suas ordens.",
"!!!",
"Sim, sou uma pessoa bem conhecida. E quanto à máscara -",
"- não queira saber.",
"Desculpe, Capitão, mas não temos água.",
"Hmm, e a margem mais próxima é...",
"Desculpe-me, mas sou italiano, não espanhol.",
"Ok, então o que está a fazer no exército espanhol?",
"Não tive escolha, Senhor. Fui forçado a servir em espanhol.",
"Tudo bem, seja bem-vindo, meu amigo. Mas é muito arriscado desertar aqui em um porto espanhol.",
"Gunnar às suas ordens, Capitão.",
"Diga-me, o nome do nosso navio - o que significa?",
"Le navigateur suedois d'Islande.",
"Exatamente o que eu pensava.",
"Sim, é o mesmo nome. Mas aquela fragata estava ancorada em Gotemburgo da última vez que a vi. -",
"- Nossa corveta leva o nome dela, em homenagem a 'Lasse i gatan', o famoso corsário.",
"Muito bem.",
"Sergio às suas ordens, Capitão.",
"Capitão, meu nome é Gunnar e falo sueco, se for do seu interesse.",
"De fato é. Gunnar, você também me seguirá até a costa. Alguém fala espanhol?",


};
