string DLG_TEXT[49] = {
"Ah, você deve ser o jovem e corajoso capitão que salvou a pobre Caroline?",
"De fato sou, agora me diga que tipo de lugar é este! (E por que você está vestido desse jeito engraçado)",
"Este gentil senhor é a melhor loja de todo o arquipélago - vendemos todos os tipos de armas, móveis e pinturas aqui.",
"Entendo, bem, talvez outro dia... (É uma mulher de bigode ou...)",
"Mesmo que a loja ainda não esteja aberta, pegue estas chaves e dê uma olhada por um tempo. Se encontrar algo interessante, por favor, guarde. Veja como um presente da loja do Governador Rogers!",
"Ok, obrigado então! (Ou um homem com...?)",
"Bem-vindo de volta, viajante, você veio pelo baú de remédios, eu acho.",
"Olá, Dave, é verdade - o que você tem?",
"Ah, nós temos um baú, sem problemas - eu o coloquei na loja para você. Mas remédios, desculpe, isso é outra coisa...",
"Tudo bem, vou dar uma olhada então.",
"Sim, capitão, você veio ao lugar certo: posso lhe dar um violino.",
"Agora, isso parece bom! Onde está?",
"Só tem uma coisinha, gentil senhor... O instrumento é meu.",
"E você não quer vendê-lo, certo?",
"Pelo contrário, capitão, mas você pode pagar?",
"Quanto custa, Dave?",
"2000 pelo violino e é um preço bem amigável. O que você me diz?",
"Você deve estar brincando - posso conseguir uma lâmina por isso!",
"Vejo que você não sabe o valor certo de nada além de armas. Faça o que quiser - mas é o melhor instrumento de todo o Caribe, posso lhe garantir - e o único violino também.",
"Tudo bem, me dê esse violino.",
"Você tem razão, eu não tenho o dinheiro... ainda. Já volto.",
"Você tem que pegar o instrumento no meu quarto. Não posso sair da loja.",
"Aqui está seu 2000, Dave.",
"Ahh, ficaremos felizes em ajudá-lo, Capitão. Agora você pode nos ajudar...",
"Claro, Dave, o que posso fazer por você?",
"Se encontrar alguma lâmina, por favor, entregue-a para nós. Podemos vendê-la facilmente na loja.",
"Claro. E agora? Como saímos daqui?",
"E Courtney e Cook, sem esquecer daquele médico assustador. Agora vá ajudar Caroline, Capitão.",
"Sim, eu já devo ir.",
"Mas, Capitão Rogers, os navios não estão totalmente equipados.",
"Ainda precisamos de muitas coisas!",
"Benjamin Hornigold, o famoso pirata. Ou seria o famoso caçador de piratas? De qualquer forma, isso é algo que podemos vender facilmente na Loja.",
"Ok, acho que vou guardar como curiosidade. (nunca se sabe...)",
"Lembra que Teach foi quem procurou em 'La Concorde', talvez ele tenha encontrado alguma coisa?",
"Nunca saberemos. Agora, vamos a outro assunto: as pistolas. Onde o Governador Rogers as conseguiu?",
"Vendemos todos os tipos de armas, móveis e pinturas.",
"Que bom saber, Dave.",
"... mas desta vez vou abrir uma exceção: Capitão, aqui estão suas pistolas...",
"Ah, muito obrigado, Dave. (Ops, esqueci de pegá-las!)",
"Ah, a propósito, Capitão, você já visitou o pobre marinheiro Selkirk?",
"Não, onde ele está?",
"Ele está morando no Quarto de Botas do Governador.",
"Certo. (Eu sei onde fica)",
"Esta assinatura aqui... FH 1634. Você sabe o que significa?",
"Por favor, nos ilumine, Dave.",
"Significa o pintor holandês Frans Hals e o ano também é muito bom, então acredito que seja genuíno.",
"E de algum valor, talvez?",
"Algum valor...? Senhorita Rogers, -",
"- vale uma fortuna!!!",



};
