string DLG_TEXT[122] = {
"Disseram-me que o senhor se esforçou muito para solicitar uma audiência. Meu nome é ",
". Agora, por favor, diga-me o motivo da sua visita, ",
".",
"Meu nome é ",
".",
"Ah, é o senhor de novo. O que o traz aqui desta vez? ",
"Gostaria de falar com o senhor sobre alguns negócios.",
"Desculpe, mas tenho coisas para fazer.",
"Então, por que o senhor me distrai dos assuntos de Estado tão importantes?",
"Gostaria de falar com o senhor sobre um pequeno assunto.",
"Estou aqui apenas para prestar minhas homenagens. Nada mais, ",
"Nesse caso, por favor, saia do meu escritório e deixe-me voltar a assuntos mais importantes.",
"Sim, claro. Desculpe por ter incomodado.",
"Estou ouvindo. ",
"",
"Estou aqui para receber minha recompensa pela morte do Garry Sujo.",
"Desculpe, mas não tenho nada para falar agora.",
"Ah, eu soube do que você fez. Da face de toda a colônia, mostrarei nossa gratidão.",
"Isso mesmo, eu gostaria de ver uma recompensa.",
"Você é um palhaço. Ha ha. Aqui está seu dinheiro.",
"Obrigado, sou seu humilde servo.",
"Então, sobre a aposta que você fez... depois de obter a aprovação do nosso departamento de impostos, vejo que temos... deixe-me ver... seis mil.",
"O quê?! O acordo foi de 10 mil!",
"Não posso ajudá-lo. No futuro, tente ficar mais calmo.",
"Como quiser, senhor. Porco imundo...",
", você está ciente de que é acusado de assassinato? Você foi visto perto do corpo da vítima. O que você diz em resposta a esta acusação?",
"Não tem nada a ver comigo. O homem já estava morto quando entrei na sala! Disseram-me que ele estava apenas ferido e que poderia ter alguma informação importante para mim.",
"Acabei de saber que um homem foi capturado enquanto tentava sair da cidade com uma faca manchada de sangue em sua posse. Ele confessou o assassinato do qual você foi acusado. Você pode ser libertado imediatamente.",
"Obrigado. Eu sabia que podia confiar na justiça aqui em #sConceicao#.",
"Desejo desertar para Portugal.",
"De fato? Muito bem, agora você é um cidadão português.",
"Agradeço sua infinita gentileza, senhor.",
"Ah, sim? Tenho uma proposta para você, capitão.",
"De fato?",
"Soube que você concluiu a tarefa com sucesso; meus parabéns, capitão! Aqui está sua recompensa.",
"Meus agradecimentos; Foi um prazer ajudá-lo.",
"Você deve destruir o ",
"navio ",
"pirata de busca",
"ameaçando a navegação ",
"Se afundá-lo, eu o recompensarei com a grande soma de ",
"ouro. O que diz, capitão?",
"Você nunca mais ouvirá falar dela, isso eu prometo.",
"Receio não poder ajudá-lo.",
"Peço perdão, Excelência.",
"Estou interessado em aprender sobre as relações inglesas com outras nações.",
"Estou procurando uma Carta de Corso.",
"Ah, ",
", que gentileza sua passar por aqui. Gostaria de apresentar minha ",
". Ela virá assim que terminarmos o negócio.",
"Ouvi dizer que estou concorrendo a uma promoção.",
"Não posso mais servir ",
", Excelência.",
"Terminei de servir ",
"Como garantia de que você é um capitão capaz e para recompensar meu tempo apresentando seu caso a ",
", preciso lhe pedir ",
"ouro.",
"",
"Sem chance.",
"Muito bem. ",
"sempre tem o prazer de aceitar novos capitães a seu serviço. ",
"Estamos atualmente em guerra com ",
" ",
"nenhuma grande potência, mas ",
". É claro, ",
"Piratas devem ser sempre afundados à vista. ",
"Em vista de seus serviços anteriores, ",
"concede-lhe a patente de ",
"Eu o deixarei orgulhoso, Vossa Excelência. ",
"Você prejudicou ",
", e ",
"não se esquece de seus inimigos. Saia imediatamente, ou os guardas o expulsarão!",
"... ",
"Você causou ",
"grande dano, capitão, mas ",
"está disposto a ignorar suas transgressões passadas... por um preço: ",
"Muito bem, Senhor. Eu aceito. ",
"É um prazer lidar com você, ",
"E você, Vossa Excelência. ",
"Você é mesmo! Excelente trabalho. Sua nova patente é ",
". Além disso, você é premiado com ",
"acres de terra por ordem de",
" ",
"Obrigado, senhor.",
"Tem certeza de que",
" ",
"lamentará perder seu serviço.",
"Sim, tenho.",
"Os dões não gostam de traidores ",
"",
"Ah, deixa pra lá.",
"Muito bem. Mas espero que reconsidere, com o tempo...",
"Adeus",
"Hã?",
"Difícil.",
"Bem, tenho uma missão, se estiver interessado.",
"Talvez. Qual é exatamente?",
"Há dois meses, um comboio de navios mercantes britânicos partiu de #sisland_Antigua# para navegar para #sisland_Cayman#. Minha filha, Elizabeth, estava a bordo de um dos navios. O comboio nunca chegou. Depois de um mês, enviei meu melhor capitão para procurá-la. Mas não tive notícias do 'Lightning' desde então.",
"Então você quer que eu procure a fragata e o comboio? Por que não envia outro navio seu?",
"Infelizmente, não tenho recursos militares para dispensar outro dos meus navios. Como #sisland_Cayman# é uma colônia pequena, eu seria menosprezado pelo meu povo se comprometesse a segurança da colônia por uma causa pessoal.",
"Muito bem, senhor. Agora, vamos ao que importa. Quanto me pagará se eu trouxer sua filha de volta?",
"Não posso pagar mais do que 40.000 moedas de ouro.",
"Parece-me muito bom. Aceito sua oferta. Aguarde notícias minhas em breve.",
"Desculpe, Governador, mas tenho que recusar. Não posso perder o tempo necessário para tal empreitada.",
"Muito obrigado! Por favor, faça de encontrar minha filha sua maior prioridade, capitão.",
"De fato, Governador, mas o pirata que sequestrou sua filha também veio aqui!",
"Um oficial me informou da chegada do navio pirata há alguns minutos. Por favor, Capitão, ajude meus soldados a repelir o inimigo. Enquanto o senhor os combate, vou esconder Elizabeth em uma sala secreta da residência.",
"Sábia decisão, Senhor. Estou indo para o porto agora mesmo!",
"Parabéns, Capitão! O senhor fez um trabalho fantástico.",
"Obrigado, senhor, foi uma missão perigosa.",
"De fato! Elizabeth me falou de Davy Jones. Aquele Pirata parece ser o Diabo. Felizmente, graças ao senhor, ele não voltará tão cedo.",
"Espero que sim, Governador. Agora que a missão foi cumprida, tenho outras coisas para fazer, mas primeiro podemos falar sobre a recompensa que foi prometida.",
"Sim, claro. Conforme combinado, aqui estão as 40.000 moedas de ouro! Obrigado novamente e adeus, Capitão.",
"Adeus, Governador.",
"Tenho uma pergunta, Excelência.",
"Sim...?",
"Seu antecessor, o Governador Charles Eden, tinha uma propriedade nesta ilha.",
"O senhor sabe onde ela fica?",
"Sei sim. E ouvi dizer que também está à venda.",
"Aha, muito interessante. Agora, como faço para encontrá-la, Excelência?",
"É muito fácil, Capitão, porque está aqui!",
"Obrigado, Governador.",


};
