string DLG_TEXT[58] = {
"Quem é o senhor?",
"Desculpe a intromissão. Meu nome é Howard Pyle. O senhor é um dos cirurgiões de La Concorde?",
"Ah, não, esse negócio do Barba Negra de novo. Todos nós fomos a tribunal e fomos absolvidos.",
"Entendo, mas tenho outra pergunta. O que o senhor se lembra do tenente de Teach, 'Richards'?",
"Não muito, mas um cara muito durão, com certeza.",
"Talvez o senhor o tenha medicado?",
"Não. Eu era o segundo cirurgião e responsável por todas as cirurgias, não pelos remédios.",
"O senhor sabe onde posso encontrar os outros cirurgiões de La Concorde?",
"Tente o armeiro - ele serviu como terceiro cirurgião.",
"Onde está o armeiro?",
"Chega de perguntas agora. Por favor, saia da minha casa.",
"Muito bem. Adeus.",
"Bem-vindo, senhor. Talvez precise de ajuda com uma pistola ou um mosquete?",
"Nenhuma, só preciso de algumas informações, por favor.",
"Hmm, sou um homem muito ocupado.",
"Só uma pergunta rápida, então. Fiquei sabendo que o senhor foi forçado a integrar a tripulação do Teach, senhor.",
"Ah, ah, lá vamos nós de novo...",
"Só estou interessado no tenente do Teach, 'Richards'.",
"Sim, eu me lembro dele. Ele estava doente, mas não o operei.",
"Do que ele sofria?",
"Como eu poderia saber? Só via ossos de vez em quando.",
"Ouvi falar de três ou quatro cirurgiões. Sabe onde os outros podem ser encontrados?",
"O primeiro cirurgião mora em cima da oficina do fabricante de velas.",
"E onde é isso?",
"O que é isso? Um roubo?",
"De jeito nenhum. Só quero falar com o senhor.",
"Muito bem, o que foi?",
"O senhor foi o primeiro cirurgião do La Concorde?",
"Não acredito. Repetindo essa história infeliz. Eu não sou e nunca fui pirata!!",
"Não, não, não. Só quero lhe fazer uma pergunta sobre um tal de 'Richards' da tripulação do Barba Negra.",
"O que tem ele?",
"Ele estava doente, é mesmo?",
"De fato, estava. Sífilis, como muitos daqueles desgraçados.",
"E o senhor o tratou, senhor?",
"Encomendei alguns remédios para aqueles caras, sim.",
"O senhor falou com ele? Sabe o que aconteceu com ele depois?",
"Certamente que não, senhor. Como cirurgião-mor, deixei tudo isso para o meu assistente.",
"E talvez o senhor saiba onde posso encontrá-lo?",
"A última vez que ouvi falar dele, ele dormia em uma carruagem em algum lugar da cidade.",
"Sou muito grato pela sua paciência, senhor.",
"Aha, uma visita. E quem é o senhor?",
"Desculpe a intromissão, Governador, meu nome é Howard Pyle.",
"O pirata!!",
"De jeito nenhum, senhor - deve ser coincidência. Estou procurando o cirurgião 'Nicholas'.",
"Nicholas Gautrain, ao seu dispor, senhor.",
"Tenho algumas perguntas sobre a época em que o senhor serviu sob o comando do Capitão Teach.",
"Ah, pelo amor de Deus, fomos forçados a nos juntar à tripulação dele.",
"Monsieur Gautrain, só estou interessado no tenente de Teach, 'Richards'.",
"Sim, aquele mesmo.",
"O senhor falou com ele?",
"Claro. Sendo um dos piratas muito doentes, ele era meu paciente.",
"O senhor sabe o que aconteceu com ele?",
"Não tenho certeza, mas ele falou em deixar a companhia.",
"Entendo... Ele lhe contou mais sobre seus planos?",
"Ele tinha uma irmã, senhor. Uma irmã que era freira em uma abadia.",
"Por favor, continue, pode ser isso! Onde ficava aquela Abadia?",
"Acho que ele mencionou Cartagena.",
"Muito obrigado, senhor, pelo seu tempo.",
};
