string DLG_TEXT[69] = {
"Talvez você precise de um oficial, capitão?",
"Um oficial? E o que você sabe fazer?",
"Ouvi dizer que você precisa de marinheiros.",
"Talvez, algum motivo especial para contratá-lo?",
"Bem... Você está contratado. Encontro você a bordo do navio.",
"Bem, sou um excelente carpinteiro.",
"Se você é tão habilidoso, por que tão ruim então?",
"Que azar, capitão, azar e nada mais.",
"Servi como artilheiro no exército francês.",
"Você me parece muito um desertor.",
"Garanto-lhe, capitão, só esqueci de devolver o uniforme.",
"Servi como fuzileiro naval na marinha inglesa e posso lhe dizer como reduzir o tempo de recarga dos seus canhoes.",
"Servi como mosqueteiro no exército espanhol e posso lhe dizer como reduzir o tempo de recarga dos seus canhoes.",
"Bem, sou um excelente contramestre.",
"Ah, não, eu o reconheço como o carrasco em Port Royal!",
"Deixei aquele emprego, capitão, talvez eu não fosse tão durão.",
"Sei ler e escrever, capitão, e trabalhei como contador. Esgrima é outra habilidade minha! Em outras palavras, eu seria o intendente perfeito.",
"Bem, sou um excelente veleiro e posso ensinar sua tripulação a consertar o navio mais rápido.",
"Você parece velho demais para isso, meu bom homem...",
"Velho não é a palavra certa. Experiente, Capitão... Experiente.",
"Você também sabe fazer bandeiras e roupas?",
"Claro que sim, Capitão.",
"Bem, sou um excelente Doutor.",
"Nesse caso, o que você está fazendo aqui?",
"Ah, um probleminha na Inglaterra, nada que possa lhe interessar, Capitão.",
"Bem, sou um Guerreiro de Convés muito útil.",
"Provavelmente um escravo fugitivo.",
"O que realmente importa no meu caso, Capitão?",
"Sou um Capitão Bravo de Darien e vou lhe mostrar alguns truques para derrotar qualquer um em uma luta corpo a corpo.",
"Muito longe de casa, eu acho, o que você está fazendo aqui?",
"Fui sequestrado por piratas e vendido como escravo para uma plantação. Agora busco vingança!",
"Sou um marinheiro habilidoso e não quero ficar em terra firme, além disso, trarei sorte, Capitão.",
"Sorte talvez, mas ainda muito jovem!",
"Servi sob o comando do Capitão Black Sam Bellamy e fui o único, além do Capitão, a sobreviver quando o Whydah afundou em uma tempestade!",
"Bem, sou um comerciante chinês e posso lhe contar alguns truques comerciais que o ajudarão a aumentar seus lucros em todas as suas transaçoes.",
"Estou cansado da vida em terra, vamos buscar aventuras e riquezas em alto-mar, Capitão!",
"Sou um Grande espanhol e um Espadachim magnífico.",
"Matei o homem errado, Capitão.",
"Tenho uma visão muito boa, Capitão, o que significa que posso lhe ensinar a calcular a trajetória de uma bala de canhão e a acertar seu alvo todas as vezes.",
"Bem, sou um Lutador muito durão e posso lhe contar muitas histórias sobre a arte da luta corpo a corpo.",
"Bem, sou um bucaneiro muito experiente e posso lhe contar Muitas histórias sobre a arte da luta corpo a corpo.",
"E isso significa?",
"Conheço muitos navios de abordagem e sei fazer boucan, carne para viagens longas, Capitão.",
"Sou um excelente açougueiro.",
"Não preciso disso no mar, infelizmente.",
"Mas, Capitão, posso ser assistente do Doutor e isso reduzirá as perdas da tripulação em uma batalha naval.",
"Sou um Capitão mercante português.",
"Fui parado por piratas, eles levaram tudo de mim, inclusive meu navio. Posso assumir o comando dos seus navios premiados, Capitão.",
"",
"Eu caí no mar durante uma tempestade, Capitão.",
"Sou um excelente astrônomo.",
"Isso também significa que posso navegar, Capitão.",
"Sou um monge jesuíta e marinheiros são sempre muito supersticiosos...",
"Marinheiros talvez, padres... não, acho que não.",
"Sou um excelente barrista e marinheiro e compartilharei meus segredos que ajudarão você a guiar melhor seu navio.",
"Me convença!",
"Hmm, ainda não tenho certeza...",
"Então, o que você diz, Capitão...?",
"Diga-me, por que uma garota linda como você está aqui?",
"Eu pensei que os bucaneiros ficassem em terra, ocupados defumando sua carne.",
"Não, fazemos incursoes em pequenas embarcaçoes de vez em quando. E sim, Capitão, eu também sei fazer boucan!",
"Posso te contar muita coisa sobre como gerenciar a tripulação do seu navio.",
"Sou um excelente marinheiro e compartilharei meus segredos que te ajudarão a guiar melhor o seu navio.",
"Não importa, Capitão - você também vai ganhar um músico!",
"Capitão Pyle!",
"Eu te conheço - do recrutamento da tripulação da vovó Rogers. O que você está fazendo aqui, filho?",
"Aqui - uma carta para você.",
"Certo? Você não deveria estar na escola?",
"Ao seu dispor, Capitão.",

};
