string DLG_TEXT[113] = {
"Não se atreva a se dirigir a um superior dessa maneira novamente, seu mercenário insolente!",
"Umm... err... Entendo. Desculpe por incomodá-lo, senhor. Adeus.",
"Ei, você aí! Você me parece suspeito. Quem diabos é você? Mostre-me seus documentos!",
"Quem diabos é VOCÊ? Identifique-se e seja rápido!",
"Alto! Nunca o vi antes, mas você tem cara de pirata! Pode provar que não é um?",
"Eu sou ",
", e aqui estão minha patente de capitão e meus documentos de embarque para provar. Foi rápido o suficiente para seu temperamento explosivo?",
"Ahoy, camarada.",
"Ahoy, hein, Capitão?",
"Capitão, isso foi legal, mas Srta. Rogers para você. Primeiro, deixe-me agradecer por sua corajosa expedição de resgate.",
"Ah, nada mais para falar.",
"Talvez você não saiba da sua reputação no arquipélago?",
"Bem, o que as pessoas dizem então?",
"Ahh, jovem Capitão, você já encontrou algum remédio?",
"Vovó... Srta. Rogers, só este baú trancado até agora.",
"Mandei chamar o boticário de Bridgetown, mas pode levar algum tempo para ele chegar. O contramestre, Sr. Pope, está no porto para encontrá-lo.",
"Entendo...",
"Pode haver algumas curas e medicamentos no meu quarto - não tive tempo de verificar. Talvez você devesse voltar mais tarde!",
"Eu farei isso - adeus, Srta. Rogers.",
"Por que você não visita o Sr. Stretton? Talvez ele consiga abrir aquele baú.",
"Ah, não, aquele maníaco não - ele poderia me explodir em pedaços.",
"Você tem alguma ideia melhor, Capitão?",
"Bem, hmm, eu...",
"Capitão, eles assassinaram meu filho - estamos todos em grande perigo.",
"Srta. Rogers, eu já lutei com eles - mas agora estou sem munição!",
"Desculpe, Capitão, não há mais munição aqui - mas você pode usar suas pistolas de outra maneira...",
"Como assim?",
"Jogue-as em seus inimigos! E Capitão, assim que Dave chegar com nossas armas, nós iremos ajudá-lo.",
"Eu certamente digo sim a isso! Jogue-as, você disse...",
"Essa foi uma luta e tanto! Pegamos alguns daqueles bastardos.",
"Sim, você apareceu no último minuto, Srta. Rogers.",
"Como assim? Você deveria ser grato, Capitão - você poderia ter morrido!",
"Quero agradecer a vocês dois. Eram muitos para mim.",
"Continue sozinho, Capitão - temos que defender a loja. Ainda existem alguns caras realmente maus na vida...",
"Sim, me disseram - Dampier entre outros.",
"Agora ouça com atenção, Capitão! Nestas águas, é nosso costume dividir o saque pl... ehrr entre nós.",
"Bem, hmm, eu... (Merda!)",
"Decidi que você terá três partes, então, escolha três itens daquele baú com calma.",
"Ah, quero dizer, obrigado, Srta. Rogers! (Sim, sim, sim!)",
"O que você escolhe, Capitão?",
"Primeiro, eu gostaria de ficar com o Mapa.",
"O Ouro, por favor.",
"O Cutelo, por favor.",
"A Luneta, por favor.",
"O Kit de Costura, por favor.",
"O Tabaco, por favor.",
"A Canivete, por favor.",
"A Bússola, por favor.",
"A Caixa de Fogo, por favor.",
"O Sextante, por favor.",
"A Jarra de Lata, por favor.",
"O Par de Pistolas, por favor.",
"A Barra de Prata, por favor.",
"O Relógio, por favor.",
"A Coleção de Itens Estrangeiros, por favor.",
"O Kit de Desenho, por favor.",
"As Conchas Estranhas, por favor.",
"Agora, sobre o futuro. Continuaremos nossos negócios no Caribe como antes, com as seguintes promoçoes:",
"Assumo o comando do "Duke" com Caroline como minha Primeira Oficial, Selkirk como Navegador, Carpinteiro de Sexta-Feira e Dave como Intendente.",
"Usaremos apenas o "Duke" e, além disso, Dave -",
"- agora é seu trabalho como Intendente reformar os navios!",
"Deixe-me examinar esses itens novamente.",
"Acredito que Minerva seja totalmente capaz de administrar a Loja -",
"- o que você acha, garota?",
"Pode ficar com isso de qualquer maneira -",
"- agora, por favor, faça uma nova escolha, Capitão!",
"Claire prometeu cuidar do recrutamento de uma nova tripulação -",
"- ahh, aqui está ela!",
"Essa é uma boa escolha -",
"Hmm, ...muito bem, se essa é sua escolha -",
"- agora faça outra, Capitão!",
"- e essas seriam suas três açoes, Capitão.",
"Agora, Capitão, sente-se, por favor. Talvez você nos deixe ver o mapa que causou a morte do meu filho.",
"Muito bem, aqui está.",
"Agora, por favor, podemos ver o mapa!",
"Deve ser um mapa do tesouro com todo esse segredo.",
"... e Maynard ofereceu o cinto de pistolas a Spotswood. Faz sentido!",
"Ok, mas por que Teach se deu ao trabalho de aceitar pistolas em troca dos mapas?",
"... e espero que você não tenha problemas com isso!?",
"Claro que não, Srta. Rogers.",
"De fato, Caroline, além disso, também lhe oferecerei o Capitão para escolher dois oficiais.",
"Bem, isso foi muito generoso!",
"Prefiro não, Sr. Pyle - entregue-o imediatamente! Está tentando ficar com mais itens para si?",
"Claro que não, Srta. Rogers, não era minha intenção... Ehrmm, e quanto a Hornigold?",
"O Traje Vermelho, por favor.",
"Agora, para a Fazenda. Como um símbolo da nossa gratidão, estamos dando-o ao Capitão Pyle.",
"Ohh. Eu - um dono de casa!",
"Os mesmos goes para o Marquês. Pode ficar com o saveiro.",
"A Srta. Rogers é realmente muito generosa.",
"Também vamos consertar e reformar completamente o navio. Se a senhora esperar na Fazenda, nós o levaremos até lá.",
"Nossa, obrigada novamente.",
"Não, Capitão Pyle! Somos TODOS ricos - como eu já disse antes.",
"(engole em seco) Claro! É o suficiente para todos - fiz uma grande descoberta!",
"Certo, vamos dividir as riquezas que você nos trouxe. Deixe-me ver... somos oito.",
"...e meu grupo, quatro.",
"13 açoes, quero dizer. Então você encontrou o segredo com aquelas barras de metal?",
"De fato, eu descobri. Você já sabia disso?",
"Foi Claire quem nos contou tudo.",
"Hmm, não me surpreende que ela também conheça bem a Alquimia.",
"Alquimia? Eu não chamaria assim.",
"Não?!",
"Agora, Capitão Pyle, vamos ouvir mais sobre sua grande descoberta!",
"!!!",
"Isso dá 12 açoes.",
"Sim.",
"Vamos ouvir mais sobre isso depois. Primeiro: em que mais do que um livro danificado consistia o tesouro de Teach?",
"Primeiro, havia um baú com armas muito valiosas. Depois, dois baús com barras de prata.",
"E...?",
"Doze sacos com pó de ouro e dois baús com moedas de ouro.",
"Mais alguma coisa...?",
"Só quatro baús com barras de ouro e uma estátua de ouro maciço!",
"Parece ótimo, Capitão! E um navio novo também!",
"Bem, veja bem... houve uma tempestade...",

};
