string DLG_TEXT[69] = {
"O que você quer, Capitão?",
"Ah, nada.",
"O que você quer de mim?",
"Capitão Howard Pyle, você talvez tenha passado um tempo na prisão com o Major Stede Bonnet?",
"Pyle... é!! Ouvi falar do motim. Não tem a melhor reputação para um Capitão Pirata.",
"Foi tudo um mal-entendido. Agora, vamos ao caso Bonnet. Você serviu sob o comando dele, Sr. Pell?",
"E se servi, quanto você está disposto a pagar, Capitão?",
"Só me conte a história e veremos.",
"Não, não é assim que funciona. Tire-me daqui e eu lhe contarei tudo sobre os notórios Cavalheiros da Fortuna.",
"Tudo bem, concordo então. (como vou fazer isso?)",
"Talvez eu possa confiar em você mesmo que tenha a aparência de um pirata. Foi isso que aconteceu...",
"Sim...?",
"Essa foi realmente uma jogada inteligente, Capitão. "Took" é muito viciado em bebida. Se tivermos sorte, ele vai dormir logo.",
"Essa é a minha chance! Enquanto isso, você poderia me contar a história do Bonnet.",
"O que exatamente você quer saber, Capitão? Servi por muito tempo sob o comando do Major Stede Bonnet.",
"Sei que você foi preso pela primeira vez em Charleston, nas celas dos Maltains. E o resto da tripulação?",
"Fomos separados deles porque concordamos em testemunhar contra eles.",
"Você concordou, é?! E por "nós" você quer dizer Bonnet e você?",
"... e David Herriot, o Navegador. Você precisa entender: era nossa última chance de sobreviver.",
"Tudo bem. E então você foi transferido para cá. O que aconteceu quando Stede Bonnet tentou escapar?",
"O Major subornou nosso "amigo" Tookerman aqui. Ele, Herriot e outros dois homens conseguiram escapar deste lugar.",
"Como ele pôde fazer isso? Ele não poderia ter ouro consigo na prisão?",
"Você tem razão, mas ele tinha um pequeno pedaço de papel que Took pegou (hah) como pagamento.",
"(SIM SIM SIM, pode ser isso.) Você viu que tipo de papel era aquele, senhor Pell?",
"Capitão Pyle. Eu não sei ler nem escrever, eu era apenas o Contramestre.",
"Muito bem. Então Tookerman os ajudou a sair daqui, mas eles foram pegos. Certo?",
"Stede Bonnet foi pego na Ilha Sullivan. Herriot, o índio e o negro foram mortos.",
"(Então talvez o pedaço do mapa ainda esteja aqui?) Por que você não os seguiu?",
"Eu pensei que minhas chances de sobreviver seriam maiores se eu ficasse. E como você vê, sou um dos poucos que ainda estão vivos. 30 dos 35 homens de Bonnet foram enforcados.",
"E os outros quatro?",
"Na cela ao lado, o tribunal não conseguiu provar que eram piratas, apenas quilombolas.",
"Quem está com as chaves da cela, Sr. Pell?",
"Tookerman está com elas. Mas você ainda precisa derrotar os quatro guardas.",
"Hmm... ",
"Finalmente! Você tem alguma arma e roupa para mim, Capitão?",
"Sim, tenho. Só um segundo...",
"Sem roupas, mas armas, sim. Só um segundo...",
"Capitão, que bom vê-lo. Encontrei sua bolsa de munição e a enchi. Você viu César?",
"Sim, ele também sobreviveu. Aqui, armas para você. Agora, onde está o navio? (E que cheiro é esse?)",
"Olha, lá está ela de novo!",
"Uma corveta... (Esse odor terrível é do Contramestre?)",
"Com 30 canhoes e as cores britânicas! Ela é uma traficante de escravos fedorenta, Capitão.",
"Isso não parece nada bom. Uma traficante de escravos, exatamente o que eu pensava, Sr. Pell. (hmm...)",
"Acho que ela vai se virar a qualquer momento para outro ataque!",
"Vamos ver se conseguimos causar algum dano também desta vez.",
"Capitão, você ficou fora por tanto tempo que pensamos que estava morto!",
"Hmm... (eu também pensei) O que está acontecendo?",
"Más notícias, Capitão. O saveiro está completamente destruído!",
"E a Corveta?",
"Nossa, praia - um barco foi atingido, mas não afundou!",
"Tudo bem. Isso não é o suficiente.",
"Nossa, praia - dois barcos foram atingidos e destruídos! E quatro dos nossos homens foram abatidos, Capitão!!",
"Desça dessa torre agora, Sr. Pell.",
"Aqui está seu chapéu, Capitão.",
"Ahh, muito bom. Eles danificaram nosso saveiro?",
"Aquele esqueleto - foi realmente assustador. O que aconteceu, Capitão?",
"É uma longa história. Digamos que eu sobrevivi.",
"Não, você não pode, Capitão. É a tripulação que decide isso.",
"Você também vai começar agora!",
"O que vamos fazer com os prisioneiros? Matá-los?",
"Não, colocá-los em um barco. Eles podem aproveitar a praia por um tempo.",
"Esse foi o último barril, Capitão.",
"Então o que estamos esperando?",
"O Músico e o Padre ainda não voltaram.",
"Chame-os de volta, Senhor Pell! (Músicos! Padres! Somos PIRATAS ou o quê?)",
"Então você encontrou um instrumento! Quanto custou?",
"É... nada. Como você disse, Sr. Pell, eu encontrei.",
"Capitão, soldados suecos estão vindo para cá com pressa!",
"Oh oh...",

};
