string DLG_TEXT[59] = {
"César!!",
"Mas... mas... pensei que você tivesse sido enforcado em Williamsburg?",
"O que você quer, Capitão?",
"Ah, nada.",
"Ah, sim. Você pode chegar lá pelas adegas.",
"Como você sabe disso?",
"Eu segui Teach até o Governador Eden muitas vezes.",
"Ele queria visitar o Governador incógnito, é claro. Pode me mostrar o caminho, Sr. Hands?",
"Claro que posso. Sempre começávamos da casa do próprio Teach.",
"Aha, deve ser a grande mansão no topo da colina.",
"Siga-me, Capitão.",
"Vamos então! Sr. Pell, por favor, guarde a porta do Escritório se houver alguém lá dentro.",
"Vamos então!",
"O Escritório fica à esquerda, subindo as escadas -",
"- mas foi um pouco complicado com o elevador abrir aquela porta.",
"Não, Capitão, isso nunca vai funcionar. A água vai bloquear a porta das Adegas.",
"Vamos esperar em casa pela maré baixa, então.",
"Estou ouvindo...",
"Usamos o riacho para encontrar o caminho no escuro entre a costa e a entrada da adega.",
"Dê uma moeda a um pobre ",
"e ela retornará dez vezes mais!",
"Mas sim, eu sou Israel Hands. O que você sabe sobre mim?",
"Você navegou com Barba Negra como seu navegador para começar. E também que você foi perdoado no último momento.",
"É verdade, e eu tenho documentos para provar o veredito do tribunal.",
"Tenho certeza que sim. Não, quero te perguntar sobre outra coisa...",
"Que tal uma moeda para suas perguntas?",
"Primeiro, descobri que você recebeu um mapa do Barba Negra. Segundo, ofereço-lhe uma parte se você contribuir.",
"Mas eu não a tenho mais.",
"Não...?",
"Uma noite, na cabine do Queen Anne's Revenge, eu estava bebendo com o Capitão Teach, o "Major" Stede Bonnet, o piloto muito bêbado e um Capitão mercante.",
"Sim...?",
"Bem, como você vê, estou vivo enquanto todos os outros estão mortos e enterrados.",
"Mas você perdeu a perna. Apesar de todos os cirurgioes?",
"Sim, eu tive gangrena, então eles tiveram que amputar a perna. Mas eu perdi mais do que isso.",
"Seu mapa. E foi Stede Bonnet quem o roubou. Isso sim é algo para acompanhar.",
"Não é. Ele também foi enforcado.",
"Você sabe quando e onde?",
"Nada neste mundo é de graça. Mas por essa parte que você ofereceu, eu lhe darei a cidade.",
"Claro. É uma promessa.",
"Tudo bem então. Bonnet foi enforcado em 1718 em Charleston por Sir William Stapleton, o governador.",
"Aha, isso é alguma coisa. Vamos lá, o que estão esperando?",
"Capitão e César! Vocês também estão vivos. Quem são esses cavalheiros?",
"Ah... digamos, um velho conhecido. Esse chapéu que você tem aí, Sr. Hands?",
"Sim, Capitão, eu o encontrei na água.",
"Obrigado. Mas vejo que você também encontrou outra coisa...?",
"O tesouro está perdido, Capitão, a única coisa que encontrei foi este livro antigo...",
"(SIM SIM e SIM!!) Nada mal, nada mal mesmo.",
"É o Pell. Ele avistou alguma coisa.",
"Certo. Assumo o comando da torre. Intendente, você está no comando das armas!",
"Que bom ver! Uma pintura e um livro danificado, foi só isso que você encontrou, Capitão?",
"Não sei como dizer, mas...",
"É melhor corrermos para o navio, Capitão, o tempo está muito ruim chegando.",
"Tem certeza? Não vejo nada...",
"E quanto às armas, Capitão? Armas de fogo estão fora de questão...",
"Discutirei isso com os nadadores.",
"Olha, Capitão, aí vem o Músico correndo.",
"Hmm, ele causou problemas no porto?",
"Aí vem outro problema - o Padre.",
"Sim, e ele está sendo perseguido por um soldado espanhol. A postos, homens!",

};
