string DLG_TEXT[55] = {
"Não ouse se dirigir a um Contramestre dessa maneira de novo, seu mercenário insolente!",
"Umm... err... Entendo. Adeus.",
"Ei, você aí! Você me parece suspeito. Quem diabos é você? Mostre-me seus documentos!",
"Quem diabos é VOCÊ? Identifique-se e seja rápido!",
"Alto! Nunca o vi antes, mas você tem cara de pirata! Pode provar que não é?",
"Eu sou ",
", e aqui estão minha patente de capitão e meus documentos de embarque para provar. Foi rápido o suficiente para seu temperamento explosivo?",
"Tudo bem, não sei quem você é ou o que anda fazendo... mas sua tripulação foi tratada com todo o rum que eles conseguiram beber em uma semana.",
"Bem, obrigado, senhor...?",
"Hah, essas foram ordens do governador, não ideia minha. Talvez você queira visitar a antiga mina, jovem Capitão?",
"Conte-me mais sobre a mina.",
"Não, não tenho interesse em mineração.",
"A Mina Port Royal foi o ponto de partida para a cidade que você vê hoje. Os donos da primeira empresa obtiveram riquezas além de qualquer sonho. Era uma mina de ouro e uma das melhores.",
"Por que eu nunca tinha ouvido falar dessa mina antes? Por que eles pararam de minerar?",
"Mesmo tendo extraído uma quantidade enorme de ouro de lá, logo se depararam com todos os tipos de problemas. Havia um boato de que a própria montanha era amaldiçoada.",
"O que aconteceu?",
"Na primeira mina, o teto caiu, matando muitos mineiros que trabalhavam com um novo sistema de iluminação - algo com "gás".",
"Gás, como?",
"Não tenho ideia de como funcionava - mas algumas pessoas achavam que foi o sistema de iluminação, não a maldição, que causou o acidente.",
"Hmm, e isso fechou a mina?",
"Escute, se você quiser ver a mina, terá que pagar por ela. E então você pode ficar com o resto da história...",
"Quanto, Capitão? (Acho que serve?)",
"Só aceito ouro puro, garoto, dinheiro não serve!",
"Concordo, pegue esta pepita. (Que idiota eu devo ser...) Agora me conte o resto...",
"Não tenho nenhuma pepita de ouro no momento.",
"Não, a mina não estava fechada. Eles começaram a cavar a montanha em outra direção, mas os problemas continuaram...",
"Conte-me mais - isso foi interessante.",
"Eles cavaram muito fundo e outra catástrofe maior ocorreu. O mar rompeu e centenas de mineiros se afogaram.",
"Que acidente terrível! Agora acho que a mineração estava acabada.",
"De jeito nenhum. Os túneis só ficavam inundados na maré alta e ainda ficam. Não, eles cavaram ainda mais fundo e foi aí que o verdadeiro problema começou...",
"Você realmente pode contar uma história, sabia!",
"Bem, eu... Onde eu estava?... Sim, eles encontraram uma espécie de caverna antiga no fundo do mar. Os trabalhadores - tornaram-se estranhos a partir daquele momento e recusaram-se a descer novamente. AGORA ISSO fechou a mina finalmente!",
"Que história. (Se for verdade) Agora mostre-me a mina!",
"Por aqui - se não tem medo do que ainda pode haver na mina...!",
"Com medo de mim?! (Bem - um pouco talvez)",
"Hah, você vai voltar, acredite em mim. Agora saia da minha vista!",
"Mesmo que eu tivesse algum ouro, não o gastaria com esta sua história de viagem!",
"Talvez você queira visitar a antiga mina, afinal?!",
"Se encontrar algo interessante, entregue-o para mim. E isso é uma ordem!",
"Sim, sim, senhor. (Melhor mantê-lo calmo)",
"E NãO toque naquela única alavanca à direita, jovem. Já tive muita dificuldade em ligar este sistema!",
"Tudo bem, vou ter cuidado, Capitão. (mais provavelmente contramestre...)",
"Se você se divertiu o suficiente na mina, marinheiro, entregue as ferramentas que você tem aí.",
"Certo, aí está.",
"Agora deixe-me perguntar: você encontrou alguma coisa aqui embaixo? Talvez algo valioso?",
"Não, não encontrei, Capitão. (Ok, é um truque, tentando bajular aquele velho idiota um pouco)",
"Foi muito triste ouvir isso. Você sabe que não posso deixá-lo sair daqui a menos que me pague algum ouro. E eu quero dizer pepitas de OURO!",
"Ah, você quer dizer este pedacinho de ouro?",
"Desnecessário ficar aqui apodrecendo? NãO, o boticário ainda não apareceu.",
"Sim, sim, senhor.",
"Certo, não sei quem você é ou o que andou fazendo... mas sua tripulação foi tratada com todo o rum que eles conseguiram beber em uma semana. Seu navio também recebeu rum e comida.",
"Certo, não sei quem você é nem o que anda fazendo... mas sua tripulação foi presenteada com todo o rum que conseguia beber em uma semana. Seu navio também recebeu rum.",
"Certo, não sei quem você é nem o que anda fazendo... mas sua tripulação foi presenteada com todo o rum que conseguia beber em uma semana. Seu navio também recebeu comida.",
"Você pode levar qualquer rum que encontrar aqui, mas precisa se munir de uma garrafa ou um barril.",
"Vou me lembrar de que tem rum para encontrar nesta adega!",


};
