string DLG_TEXT[55] = {
"Sou novo aqui?",
"Sou mesmo. Posso fazer uma pergunta?",
"Com certeza. Você está perdido em Kristiania?",
"Sim, você já ouviu falar de um lugar chamado "Torre do Barba Negra"?",
"Há! Todo mundo conhece.",
"É mesmo. Poderia me dar algumas instruçoes então...",
"Claro. É muito fácil. A saída fica perto da única casa de tijolos no centro da cidade.",
"(Parece fácil demais. Talvez já tenha sido explorada há anos.) Ahh... certo. E obrigado.",
"O leilão acabou. Você quase perdeu.",
"Muito bem, não me interesso por antiguidades.",
"Você encontrou a entrada para a Torre do Barba Negra, você disse. E sim, todos nós já estivemos lá tentando abrir a porta.",
"Parecia que uma alavanca deveria ser colocada para destrancá-la.",
"Que pena que você perdeu o leilão de hoje. Muitos itens raros foram vendidos. Itens que podem ter pertencido ao próprio Barba Negra.",
"(Se eu conseguisse encontrar os compradores, talvez um acordo fosse possível.) Entendi, você sabe quem comprou esses itens?",
"Foram algumas das figuras mais proeminentes desta colônia.",
"Você quer dizer ricos?",
"Claro, os itens foram vendidos por preços altíssimos.",
"Ok, obrigado. (O leiloeiro deve saber quem comprou os itens!)",
"Sim, Capitão, o que aconteceu agora?",
"Será que você pode me dar algumas instruçoes?",
"Eu te ajudo, para onde você quer ir?",
"Onde encontro o Governador Walter?",
"Você sabe a senha do Forte?",
"Onde fica o Estaleiro em Kristiania?",
"Onde encontro a Igreja?",
"E o Alfaiate, onde o encontro?",
"Você conhece um prédio chamado Casa Vermelha?",
"A Prefeitura é o grande prédio de pedra no centro da cidade. É sempre guardado por dragoes.",
"Obrigado.",
"O governador Hinrich Adolph Walter mora no prédio da Prefeitura.",
"Ele é alemão?",
"Ele nasceu na Alemanha, mas sua linda esposa, Anna Helena Trafvenfeldt, é sueca.",
"Ok, onde encontro a Prefeitura?",
"Não, não encontro. Desculpe.",
"Muito bem, vou perguntar a outra pessoa.",
"É um navio! Um navio sueco!",
"Sério. (Não me importo nem um pouco - estou muito ocupado com coisas mais importantes!)",
"O Estaleiro fica na Cidade Baixa de Nueva Suecia.",
"Nueva Suecia - a parte espanhola da cidade?",
"De fato, é o Capitão e o Estaleiro se chama "Astillero".",
"Sim, temos a Capela no centro de Kristiania e a Catedral em Nueva Suecia.",
"Protestante ou católica?",
"Há mais de uma igreja em Kristiania?",
"A loja dele fica na Cidade Alta de Nueva Suecia. A sala privativa dele é aquela com um altar.",
"Parece fácil. Adeus.",
"Não é. Dizem que é preciso subir nos telhados para chegar lá. Mas por onde começar?",
"Sim, já ouvi falar - em algum lugar da selva...",
"Poderia ser mais preciso?",
"Não é a mesma saída da selva que a da Torre do Barba Negra. Mas ainda do centro de Kristiania.",
"Acho que já é alguma coisa.",
"Sim, mas cuidado - a selva é como um labirinto e pode haver índios hostis.",
"Obrigado pelo aviso.",
"Você sabe o caminho para o Forte?",
"Claro. Você encontra o portão no final do centro da cidade.",
"Ah, deixa pra lá, acho que vou encontrar o caminho.",

};
