string DLG_TEXT[51] = {
"Quem está aí?!!",
"Hum... err... Fui eu quem hasteou as bandeiras.",
"Talvez seja você. Você o pegou?",
"Do que você está falando? Por que não me deixa entrar?",
"O livro! Você está com o diário de bordo dele?",
"Você quer dizer o Barba Negra? Sim, eu o peguei. Bem aqui.",
"Jogue-o para mim então.",
"Pela chaminé? Isso é muito estranho...",
"Simplesmente faça isso, ou não posso te ajudar.",
"Muito bem. Cuidado, aí vem!",
"Não, eu não tenho diário de bordo nenhum.",
"Então não posso te ajudar. Adeus.",
"!!! (Suspiro)",
"Sim! Finalmente o peguei!",
"Que bom ouvir isso, talvez possamos conversar agora?",
"Ehh sim... claro... só um segundo. Vou abrir a porta.",
"Estou a caminho.",
"Louis Arot, às suas ordens, Monsieur...",
"Pyle. Capitão Howard Pyle.",
"Claro, um pirata!! O que eu esperava de um negócio como este?",
"Você tem algum problema com isso? (Sou famoso?)",
"Piratas foram a razão pela qual acabei nesta ilhota miserável. Mas sou um homem livre a partir de hoje!",
"Porque um navio chegou?",
"Já vi muitos navios. Não, porque coloquei as mãos naquele maldito diário de bordo!",
"Como assim?",
"Sete anos atrás, eu era grumete no navio negreiro francês La Concorde...",
"O navio que Hornigold e Teach capturaram.",
"Sim, era o navio que Teach mudou para Queen Anne's Revenge.",
"Deixe-me adivinhar: você foi forçado a se juntar aos piratas?",
"Não. Alguns dos cremembers mais úteis foram. Não, foi pior...",
"Você se voluntariou. E se tornou um pirata.",
"Sim. Você precisa entender: o Capitão Dosset e seus oficiais eram homens muito cruéis.",
"Então você preferia a companhia dos piratas.",
"Na época, sim.",
"Mas saiu pela culatra. Teach tinha seu nome como pirata voluntário no diário de bordo.",
"Sim. Quando eu quis deixar os piratas, Teach teve essa "solução".",
"Colocá-lo aqui. Estranho ele ter deixado alguém ir...",
"Ele se lembrou de que fui eu quem mostrou a eles onde o ouro em pó estava escondido em La Concorde.",
"Ele tinha outro motivo para deixá-lo aqui. Para guardar algo para ele?",
"O baú, sim.",
"O baú para um diário de bordo, certo?",
"Era esse o acordo. Espero que você consiga abri-lo...",
"Sem problemas, agora me mostre o baú.",
"Está no "andar" superior. Mais uma coisa, Capitão Pyle, quero ficar com o Tartane.",
"Leve-o.",
"Também vou precisar das bandeiras que você tem. Não é possível navegar pelo arquipélago com as cores do Barba Negra!",
"Certo, aqui está.",
"Por favor, apresse-se, Capitão, para que possamos sair daqui.",
"Certo, só um minuto.",
"As novas cores são melhores, hein, Capitão?",
"Sueco - por que não, nestas águas?",

};
