string DLG_TEXT[32] = {
"Quem é você? E o que está fazendo na minha casa? ",
"Ahh, desculpe a intromissão, Madame. Meu nome é Howard Pyle e estou interessado em comprar a propriedade.",
"Prazer em conhecê-lo, Sr. Pyle. Sou a Sra. Margaret Pough - a proprietária.",
"A senhora conhecia bem o governador Eden, Sra. Pough?",
"Na verdade, sou sobrinha dele.",
"Sra. Pough, não consegui inspecionar nenhum dos cômodos - todas as portas estavam trancadas?",
"Estamos com um problema para encontrar as chaves de todos os cômodos. Vamos voltar ao prédio principal agora e verei o que posso fazer.",
"Obrigada, Sra. Pough.",
"Ahh, aí está o Sr. Pyle. Por que demorou tanto?",
"(Aquele labirinto maldito!) Ah, nada - acabei de aproveitar o jardim. (e suas criaturas)",
"Muito bem. Abri um dos quartos para a senhora. Talvez consiga chegar aos outros cômodos de lá, Sr. Pyle.",
"Espero que sim. Até mais, Sra. Pough.",
"Sim, Sr. Pyle, o que posso fazer por você?",
"Ah, desculpe incomodá-la, Sra. Pough.",
"Sr. Pyle, acho que o senhor já visitou todos os cômodos da propriedade. Até a Capela! Então, o que me diz?",
"Hmm, ainda não visitou todos os cômodos. Ainda falta o Escritório (para explorar). Como entro lá?",
"Desculpe, não tenho a mínima ideia. Meu tio tinha a chave dele, é claro, mas ela desapareceu.",
"Talvez haja outra maneira de entrar no escritório dele?",
"De jeito nenhum. Esta é a residência de Tobias Knight, o Secretário do meu tio.",
"Ok, o Sr. Hands lidera a saída.",
"Mais uma coisa, Capitão... Se espera encontrar algo para roubar nos quartos, posso garantir que tudo de valor foi removido.",
"O quê... Como... Eu não sou ladrão, Sra. Pough (bem...)",
"Como ousa? Este é Tobias Knight, o secretário do Governador -",
"- você será punido por isso, escravo!",
"Entregue esse papel imediatamente -",
"- ou eu o vendo o mais rápido possível!",
"Pare-os -",
"- pare os Piratas!",
"Saia daqui! Saia daqui -",
"- e nunca mais volte.",
"Não que eu saiba.",
"Hmm, talvez eu tenha que voltar mais tarde para uma exploração mais completa. Será que algum dos ex-oficiais de Teach sabe de algo de valor?",

};
