string DLG_TEXT[100] = {
"O que posso fazer por você, Capitão?",
"Desculpe incomodá-lo.",
"Como monto o aparato da destilaria?",
"Não tenho certeza sobre o processo de destilaria...",
"Conte-me mais sobre a solução de Cobre!",
"Todas as peças necessárias estão no Despensa e na Cozinha.",
"Entendo.",
"Há uma imagem no Quarto de Rogers. E, Capitão, por favor, tome cuidado com o oxigênio!",
"Vou verificar essa imagem.",
"Você precisa de mais informações. Talvez haja mais documentos nesta casa.",
"Tudo bem, vou dar uma olhada mais de perto então.",
"Rumores dizem que o autor entende de metais.",
"Hmm, esse seria De Foe, preciso visitar sua cabine no estaleiro.",
"Capitão, você ainda não tem os ingredientes certos.",
"Parabéns, você conseguiu, Capitão!!",
"Então, vamos direto para os navios!",
"Você está quase lá, Capitão. Mas acho que você precisa consultar seus livros e documentos um pouco mais...",
"Fale mais sobre como resolver a Prata!",
"Tudo bem, vou continuar meu trabalho.",
"Primeiro você precisa produzir Ácido Sulfúrico.",
"Primeiro você precisa produzir Ácido Nítrico.",
"Fale mais sobre como resolver o Ouro!",
"Primeiro você precisa produzir Ácido Clorídrico.",
"Capitão, o barco já chegou.",
"Barco? Bem, obrigado.",
"É mesmo?!",
"Ahh, aí está você, Capitão. Vamos todos voltar para a residência do Governador.",
"Olá, Minerva, onde o corpo dele foi encontrado?",
"Ele estava trabalhando no escritório quando o mataram.",
"Entendo, agora vamos embora.",
"Ah, eu adoraria cuidar da Loja, Srta. Rogers -",
"- muito obrigada!",
"É o 'Artilheiro' -",
"- havia mais um membro leal da tripulação!",
"Abri todos os baús para você, Capitão - mas você precisa montar o Aparato da Destilaria sozinho.",
"O que aconteceu, Capitão?",
"Eu... não sei... explodiu... bem na minha cara!!",
"Você encheu o caldeirão com água, Capitão?",
"Hmm, acho que perdi isso, Minerva.",
"Você encheu a retorta com algum líquido, Capitão?",
"Capitão, você precisa ter mais cuidado com o oxigênio. Dois passos naquela prancha são suficientes!",
"Bem-vindo à casa da fazenda do Governador Rogers. Sou Minerva e estou aqui para ajudá-lo em seus experimentos de alquimia.",
"Ah, eu vou fazer isso...?",
"Sim, Capitão Pyle, e sua primeira tarefa é localizar o laboratório de alquimia de Rogers - sem a minha ajuda.",
"Hmm, entendi, os enigmas do Governador continuam...",
"Sim, então acho que posso ajudá-lo nisso, Capitão: Itens da mão direita usam F3 + F3, Itens da mão esquerda usam F3 + disparar pistola.",
"Obrigada, Minerva, vou anotar isso.",
"Capitão, estou esperando por você há tanto tempo.",
"Olá, Minerva, você ainda está aqui?",
"Tenho as misturas que você produziu antes.",
"Muito bem!",
"Aqui está, Capitão Pyle. Eu também destranquei o depósito secreto de Rogers.",
"Sim, você encontrou a chave! Agora posso continuar meu trabalho aqui.",
"Posso ficar de vigia, mas não tenho armas, senhor.",
"Aqui, pegue as minhas.",
"Devo levar seu chapéu e cinto, capitão?",
"Sim, por favor.",
"Como posso ajudá-lo, capitão?",
"Quero saber mais sobre o Cadinho.",
"Pode ser mais preciso, por favor?",
"Como o encho?",
"Olá, capitão, espero que não se importe com a intromissão. Estou aqui de férias.",
"Aha, pensei que estivesse na oficina.",
"Não sei como funciona a moagem.",
"Como filtro um líquido?",
"Quanta lenha devo usar?",
"A roda na lateral da lareira. Para que serve?",
"Como transfiro os ingredientes processados do Cadinho para uma garrafa?",
"Se o Cadinho estiver inclinado, use a roda na lateral do forno. Caso contrário, não há problema.",
"Obrigado, entendi.",
"O número de triângulos na receita de alquimia é igual à quantidade de lenha que você deve adicionar.",
"A roda serve para inclinar o Cadinho.",
"Coloque uma garrafa pequena e um funil no chão antes de inclinar o Cadinho com a roda.",
"Onde coloco os ingredientes que quero moer?",
"Como faço a moagem propriamente dita?",
"E, finalmente, como tirar o material do moedor?",
"Há uma abertura na parte superior do cilindro.",
"Gire a manivela grande.",
"Coloque uma garrafa pequena no chão, embaixo do cano, antes de puxar a corda.",
"Lembre-se de colocar um filtro limpo na grade antes de despejar o líquido sobre ele.",
"Ehrr... Não sei por onde começar com tudo isso...",
"O Governador Rogers tinha um livro antigo que costumava estudar. Você já encontrou?",
"Não, onde está?",
"No andar de baixo, na parede perto do estoque de madeira.",
"Onde encontro isso?",
"Em um baú aqui perto.",
"Onde encontro todos os ingredientes?",
"Você tem que procurar nos baús em vários cômodos. Tanto nos laboratórios quanto nos depósitos. Até na cozinha e no meu quarto pessoal.",
"Ah, desculpe, mudei de ideia.",
"Onde encontro esta receita de alquimia?",
"Há frascos de tamanhos diferentes na mesa de mistura. Qual devo usar?",
"Sem problemas, você verá qual é o correto.",
"Há uma porta trancada no novo laboratório. Pode abri-la, por favor?",
"Desculpe, Capitão Pyle, mas não posso. A chave desapareceu.",
"O que mais preciso saber?",
"Salve com frequência, Capitão! Meu conselho é fazer isso após cada sucesso, em qualquer estação de trabalho.",
"Você sabe como encontrar o 'Covil do Contrabandista' na ilha de La Grenade?",
"Não importa onde você pouse em La Grenade. Você tem que atravessar a selva de qualquer maneira para encontrar o Covil do Contrabandista.",
"Não me lembro como se faz ácido sulfúrico.",
"Não precisa. Há um tanque na escada no andar térreo do laboratório secreto.",



};
