string DLG_TEXT[23] = {
"Bem-vindo ao meu bordel! Meu nome é ",
"e eu administro este estabelecimento. Posso ajudar em algo?",
"Na verdade, sim, estou querendo me aventurar.",
"Não, este é o lugar mais sujo do Caribe! Bem, hum, fiquei permanentemente incapacitada, se é que você me entende. Veja, fiquei incapacitada nas mãos de um tubarão. Acredito que foi um tubarão-branco, sim. De qualquer forma, não há nada aqui para mim, porque 'isso' foi substituído por um pino de madeira.",
"Hum, poderia me contar um pouco sobre este lugar, senhora?",
"Bem, quando esta cidade foi formada, eu comecei este pequeno lugar, desde então ele cresceu e se tornou o melhor bordel de todo o arquipélago, é só isso que você queria saber?",
"Bem, não, eu só estava curioso, vamos falar de negócios mais 'importantes'...",
"Sim, obrigado pela informação, com certeza te vejo por aí.",
"Tenho algumas garotas disponíveis, você ainda está interessado?",
"Sim, senhora, eu acredito que sim",
"Sim, senhora, eu acredito que sim",
"Então você quer uma garota, hein? Bem, vai custar 50 de ouro. Um pouco caro, talvez, mas não é negociável.",
"É um preço perfeito, estou dentro!",
"Desculpe, não vou poder pagar isso...",
"Então você quer uma garota, hein? Bem, vai custar 50 de ouro. Um pouco caro, talvez, mas não é negociável.",
"É um preço perfeito, eu topo!",
"Desculpe, mas não vou poder pagar isso...",
"Qual garota você prefere: Natalia, Celia, Serena ou Caroline K?",
"Natalia, Senhora",
"Celia, Senhora",
"Serena, Senhora",
"Caroline K, Senhora",
"Qual garota você prefere: Natalia, Celia ou Serena?",

};
