string DLG_TEXT[113] = {
"Você não, Capitão: Você foi eliminado, Sr. Pyle!",
"!!!",
"Primeiro, você nos disse para deixarmos a comida para trás - 'para manter o porão vazio para todos os tesouros'. Estamos famintos, Capitão!",
"A tripulação já bebeu rum!!",
"E então você se recusou a embarcar naquele belo navio - só porque ele 'parecia britânico'!!",
"Em breve encontraremos outro prêmio...",
"Calma aí, Sr. Pyle. Antes de partir para sua nova ilha, entregue todos os seus pertences!",
"O quê? Você não pode estar falando sério...",
"Já que você parece pensar que podemos viver só de rum, tome uma garrafa.",
"Sem armas, nada mais?",
"Você pode levar uma arma com você, com UM tiro!",
"(suspiro)",
"Este é o MEU navio agora - ",
"- e não pretendo adicionar mais tripulantes!",
"Uma tripulação faminta e bêbada -",
"- é uma coisa muito perigosa!",
"Piratas atacam navios -",
"- de TODAS as nações!",
"Esta será uma nova experiência para você, 'Capitão'. Sem tripulação para empurrar, você tem que vasculhar todos os locais rigorosamente em busca de dicas, itens, novas saídas ou qualquer coisa interativa.",
"Sim, e sem nós, Oficiais, você tem que confiar na sua própria capacidade de resolver problemas e quebra-cabeças.",
"E Pyle, faça-nos um favor e pare com essa conversa idiota sobre reencarnação - ela simplesmente não existe!",
"---",
"Não pode ser verdade - você tem coragem de nos fazer uma visita, Pyle!",
"Então... 'O tesouro está dividido'?",
"Está! E nada de dividir para você, Pyle.",
"Bem, eu tenho outra opinião...",
"Sabe o que há de errado com você, Pyle? Você não tem sorte!!",
"Eu escapei da ilha esquecida por Deus onde você me abandonou, não é? E também sou o único sobrevivente da tempestade!",
"Mas agora vocês perderam a sorte, isso é certo!!",
"É mesmo?",
"Voltem para a outra margem e nós os mataremos.",
"É um duelo que vocês estão propondo?",
"Com certeza. Com a nossa árvore!",
"(engula, isso não está indo nada bem)",
"Isto é um duelo -",
"- há algum problema, tripulação?!!",
"Três contra um, hein, Capitão -",
"- não é assim que os artigos chamam um duelo.",
"Parece que temos um novo Capitão...",
"...ou o que vocês dizem, homens?",
"Mas este não é um novo -",
"- é o antigo!",
"Aquele que vocês abandonaram -",
"- vocês têm certeza disso??",
"Pyle, vocês servem. Mas nada de dividir o nosso saque com vocês ou seus amigos.",
"Muito bem. E eu também não vou compartilhar meus tesouros com você!!",
"Você não tem nada, Pyle. Um livro e uma pintura danificados!! Você naufragou!!",
"Veremos, veremos.",
"E os oficiais?",
"Israel Hands será o Navegador, Ignatius Pell na torre como Contramestre e César Carpinteiro.",
"Homens do Barba Negra, hein? Eu me ofereço como Intendente -",
"- por ser o mais qualificado.",
"Não se preocupe, Capitão - ",
"- da próxima vez, vamos mirar mais alto!",
"... está ancorado. Mas cinco barcos estão a caminho!",
"Não há tempo a perder então. O que é isso que você tem aí? Parece pesado.",
"É a arma giratória da Torre, acho que você deveria ficar com ela, Capitão. E o Sr. Pell, por favor, entre no penhasco para nos manter informados.",
"Muito bom. Vamos atirar nos barcos agora com tudo o que temos, intendente!",
"RETIREM-SE PARA A TRIPULAÇÃO DO FORTIGÃO!! Antes que nos matem a todos com essas armas giratórias.",
"(Ele está certo, mas sou eu quem dá as ordens aqui!!!) ",
"Estamos sem munição no telhado, capitão. Temos que lutar contra eles em campo aberto!",
"Eu vou primeiro com o canhão e o bacamarte, siga-me!",
"Sim! Estão todos mortos. E agora, capitão?",
"Esperamos até escurecer, pegamos os uniformes deles e tentamos enganar a tripulação restante na corveta. Então...!!!",
"Mas, capitão. Mesmo se matássemos esses soldados, poderia haver muitos, muitos marinheiros a bordo.",
"Claro. E se não tivermos sorte, mais soldados também.",
"Hmm... então...?",
"O navio é um navio negreiro, certo? Se pudéssemos libertar os escravos e atacar do porão também, nós a pegaríamos!",
"Eu também sei nadar. Sou o único...?",
"Hmm, muito bem, 'Rei David'.",
"Só um detalhe, Capitão. Os escravos estão algemados, com certeza. Como você vai lidar com isso?",
"Bem, eu... (Por que não pensei nisso antes?!) Eu... é...",
"Não se lembra, Capitão? Temos uma excelente arrombadora de fechaduras a bordo.",
"A garota que você quer? Mas eu não a vejo por aqui.",
"Ah, Capitão, faz tempo que não vejo o mar.",
"Muito engraçado. Não te vi antes... (Pirata Carmesim!! Pensei que era eu que me chamavam assim.)",
"Não, eu estava alimentando o cachorro. O que você quer?",
"Precisamos das suas habilidades de arrombamento. A corveta tem escravos a bordo...",
"Sem problemas, Capitão. Quando partimos?",
"Ao anoitecer. Mas primeiro, você sabe nadar, garota?",
"Não me trate com condescendência. Claro que sei nadar — já aprendi isso na escola.",
"Certo, Pirata Carmesim. (Que difícil, hein?) Você deve ser o único pirata que já visitou uma escola.",
"Não precisamos de educação. É mesmo? Vou te dizer uma coisa, Pyle. Além de arrombar fechaduras, sei fazer tudo o que você faz —",
"- além disso, aprendi a ler e escrever três línguas e a navegar. Também matemática, então posso ser Intendente e Capitão a qualquer momento! GRAÇAS À ESCOLA!!!",
"Eu vou primeiro com o canhão, o bacamarte e a pistola de metralha, sigam-me!",
"Não nos perturbem — eles atacarão de novo em breve!",
"É... Eu só...",
"Mas você tem certeza de que vai conseguir, Capitão? Quero dizer, só vocês quatro contra...",
"Terei músculos e inteligência no meu grupo!",
"E qual dessas opções você defende?",
"Vou te dizer uma coisa, francês, eu não te fiz intendente para questionar tudo o que eu fizer. Posso te fazer um marinheiro comum de novo agora mesmo! Não se esqueça disso!",
"Só mais uma coisa: como você vai nos avisar quando os escravos estiverem prontos para atacar?",
"Não se preocupe. Eu vou resolver isso. (E começar a ficar muito, muito cansado de você) Mesmo que eu tenha que mandar um nadador para a praia!",
"Sim, o que foi agora?",
"Ehh... nada.",
"Eu ainda estou aqui.",
"Bom saber.",
"Vou começar com as algemas então...",
"Sim, muito bem.",
"E agora, Capitão? Todos os prisioneiros estão livres.",
"Excelente, Pirata Carmesim (hmm!). Agora é hora de você nadar até a praia. Por favor, apresse-se.",
"Vejo que você encontrou a munição, Capitão, mas como vamos organizar o ataque?",
"Só um segundo, Rei...",
"Olhe para nós. Você realmente acha que iríamos trabalhar com um traficante de escravos?",
"- meu amigo negro César aqui é até um Oficial!",
"Agora temos todos os oficiais que precisamos -",
"- exceto por um serrote.",
"",
"",
"Parece familiar de alguma forma... mas me diga -",
"- por que você está usando essa máscara?",
"Deve ser Isla Mona, Capitão.",
"!!!",

};
