string DLG_TEXT[105] = {
"Prazer em conhecê-lo, ",
". Meu nome é ",
", e estou às suas ordens.",
"Obrigado. Sou o Capitão ",
".",
"Que bom vê-lo novamente, ",
".",
"Você! Eu esperava que você nunca mais aparecesse na minha porta.",
"Bom dia, ",
".",
"Desculpe por isso, ",
"Quer ver meus produtos?",
"Claro. Mostre-me o que você tem em estoque.",
"Agora não. Vamos conversar.",
"Não, obrigado. Talvez na próxima vez.",
"Você está querendo comprar ou vender?",
"Tenho alguns produtos que quero vender.",
"Gostaria de comprar alguns equipamentos.",
"Nenhum dos dois, obrigado. Até mais.",
"Sou todo ouvidos. O que você tem em mente?",
"Estou procurando trabalho para meu navio e minha tripulação.",
"Estou interessado em um funcionário seu, Clauss. Gostaria de pagar a dívida dele.",
"Pagar por ele? Claro, você pode fazer isso. Ele já pagou parte da dívida...",
"Chega. Diga-me só quanto dinheiro tenho para lhe dar.",
"Deixe-me verificar meus documentos... aha... sim... Sim, aqui está. O Clauss me deve 2632 de ouro.",
"Hmm, o rapaz gastou bastante. Aqui está o seu dinheiro. Agora me diga, onde posso encontrar o Clauss?",
"Acho que vou atrasar um pouco o pagamento.",
"Mandei-o à taverna buscar um barril de cerveja. Você o encontrará lá.",
"Obrigado.",
"Receio não precisar dos seus serviços agora.",
"Que pena. Vamos falar de outra coisa.",
"Recuso-me a negociar com uma pessoa com a sua reputação e parentesco. Agora saia ",
", antes que eu chame os guardas.",
"Muito bem.",
"Olha quem está aqui! O jovem Capitão e a moça fugitiva do bordel.",
"Se você fizer barulho, essa é a última coisa que você fará, lojista!",
"Você não tem a mínima chance se me matar, Capitão. Eles já cercaram a loja.",
"Acho que você está blefando.",
"Talvez pudéssemos chegar a um acordo, Capitão. Seu ouro é sempre bem-vindo!",
"Não acredito em você, vamos tentar a porta e correr para o portão.",
"Que acordo, lojista?",
"Acho que preferimos tentar outro salto.",
"Talvez seja melhor sairmos pelo mesmo caminho que chegamos.",
"Você não receberá ouro de mim, mas concordo em matá-lo!",
"Seu bastão insignificante não vai te ajudar aqui.",
"Prepare-se para morrer, lojista!",
"Claro, encontre os bandidos do bordel do lado de fora das janelas do quarto.",
"Ah, cale a boca, velho.",
"O portão é muito longe, Capitão, sem falar nos caras sanguinários do bordel esperando do lado de fora da porta.",
"Vamos ver por nós mesmos, certo?!",
"Vá em frente, pule e quebre seus ossos, Capitão.",
"Cuidado agora ou eu quebro SEUS ossos, comerciante!",
"Eu posso te mostrar a única saída segura daqui, Capitão.",
"Se eu acreditasse em você, qual é o seu prêmio por aquele lojista?",
"Você parece estar um #sgender# razoável, Capitão. Pelo baixo custo de metade do seu ouro, vocês dois podem sobreviver a este pequeno incidente.",
"Você deve estar brincando! Esqueça, pegue!",
"Você quer metade do meu dinheiro? Diga-me, como posso saber que você não vai alarmar os garotos lá fora logo depois que sairmos?",
"Eu não sou um assassino como os outros na cidade. Só estou tentando administrar um negócio decente, bem, hmm, sim, nesta cidade suja.",
"Bem, eu não confio em você, assassino ou não.",
"Mas precisa confiar, Capitão, eles vão quebrar a porta a qualquer momento!",
"Não, faremos assim: Você vai nos fazer companhia por um tempo, gordo!",
"Se me der o dinheiro primeiro, Capitão, eu o seguirei até a saída.",
"Calma, lojista, primeiro você vai nos dizer como escapar desta cidade.",
"Você realmente gosta de fazer negócios, não é, Capitão?",
"Pela última vez, desembucha ou eu te atropelo!",
"Muito bem, então, tenho uma chave aqui no meu bolso. É a chave do telhado, de lá de cima você não terá problema em pular para o telhado do estaleiro.",
"Aqui, pegue o ouro. Depressa e nos mostre o caminho!",
"Hmm, só tem uma coisa, Capitão...",
"Espero que não haja mais negócios.",
"Receio que sim, Capitão. Infelizmente, você ainda não pagou pela arma que 'comprou' aqui mais cedo...",
"Rápido, mercador, quanto custa?",
"É uma arma excelente, Capitão. Digamos... o resto do seu ouro?",
"Não acredito!!",
"Por esse preço razoável, consigo munição nova para você também.",
"Muito generoso mesmo. Pegue o dinheiro, pelo amor de Deus, e mexa-se!",
"Ah, a propósito, Capitão, há uma conferência no salão de cima e...",
"Chega de conversa, por favor!",
"Isso é muito importante, gentil #ssir#. Não tenho certeza se a reunião nos deixará passar.",
"Paguei (uma fortuna) pela saída, então cuide disso ou eu...",
"O melhor seria usar becas, como os Irmãos fazem.",
"Não tenho medo de monges inofensivos!",
"Inofensivos? É a reunião anual dos Irmãos de...",
"Realmente não me importa de que monastério eles vêm. AGORA SE LEVANTA, HOMEM!",
"Não precisa ficar chateado, jovem Capitão. Tenho algumas roupas prontas para você e a garota, se quiser, #ssir#.",
"Ah, vamos levá-las, talvez isso ponha fim a esta conversa.",
"Levar? Eu não usaria essa palavra, Capitão, aluguel é mais apropriado, eu acho. Afinal, esta é uma Loja.",
"É fácil lembrar que você sabe.",
"Temos um acordo então, Capitão?",
"Só uma coisa... QUANTO?",
"Eu forneço estas roupas finas como garantia para sua segurança, meu Capitão. Por que não me dá as SUAS roupas em troca?",
"Não! Chega disso! Para o telhado imediatamente.",
"Ok, ok, ok, troco meu uniforme de Capitão por um par de vestes.",
"Lembra que eu avisei, Capitão...",
"Ah, cale a boca agora.",
"Muito sábio mesmo, #ssir#. Há um vestido no quarto, na parede atrás da porta.",
"Caroline, por favor, troque de roupa enquanto eu fico de olho neste 'cavalheiro'.",
"Capitão, por favor, dê uma olhada no guarda-roupa atrás de você, enquanto eu troco de roupa também.",
"Certo.",
"Depressa, Capitão, os Irmãos podem chegar a qualquer momento!",
"Calma, lojista, você está bem, Caroline?",
"Capitão, garanto que é perfeitamente seguro para você e a garota.",
"Nem uma única palavra sua, gordo...",
"Mas Capitão, eu...",
"PULE AGORA!",
"Acordo, você disse - o que exatamente você tem em mente?",

};
