string DLG_TEXT[25] = {
"Capitão, não tenho tempo para falar com você agora.",
"Vejo você mais tarde então.",
"Capitão, não tenho tempo para falar com você agora.",
"Vejo você mais tarde então.",
"Capitão, não tenho tempo para falar com você agora.",
"Vejo você mais tarde então.",
"Deixe-me mostrar o que é um Lobo do Mar.",
"Posso treiná-lo para se tornar um Timoneiro de Tempestades.",
"Posso lhe ensinar a habilidade Sentir Fairway.",
"Sei como obter um Aumento de Velocidade.",
"Sei como aumentar a Manobrabilidade do navio.",
"Posso lhe ensinar a habilidade Sentir Fairway ou treiná-lo para se tornar um Timoneiro de Tempestades.",
"Sei como obter um Aumento de Velocidade ou treiná-lo para se tornar um Timoneiro de Tempestades.",
"Sei como aumentar a Manobrabilidade do navio ou treiná-lo para se tornar um Timoneiro de Tempestades.",
"Sei como obter um Aumento de Velocidade ou melhorar a Manobrabilidade.",
"Eu sei como obter um Aumento de Velocidade, melhorar a Manobrabilidade ou treiná-lo para se tornar um Timoneiro de Tempestade.",
"Quero aprender mais sobre o Sense Fairway.",
"Quero ser um Timoneiro de Tempestade.",
"Quero aprender mais sobre Aumento de Velocidade.",
"Quero aumentar a Manobrabilidade do navio.",
"Eu certamente digo sim para isso!",
"Talvez mais tarde.",
"Posso mostrar como executar um Giro Rápido com seu navio.",
"Posso mostrar como executar um Giro Rápido com seu navio ou treiná-lo para se tornar um Timoneiro de Tempestade.",
"Mostre-me o Giro Rápido.",

};
