string DLG_TEXT[25] = {
"Capitão, não tenho tempo para falar com você agora.",
"Até logo, então.",
"Capitão, não tenho tempo para falar com você agora.",
"Até logo, então.",
"Eu sei muito sobre Comércio Avançado, e também como me tornar um Proprietário de Terras ou um Rapaz de Confiança.",
"Eu sei muito sobre Comércio Avançado, e também como me tornar um Proprietário de Terras.",
"Eu sei muito sobre Comércio Avançado, e também como me tornar um Rapaz de Confiança.",
"Eu sei como me tornar um Proprietário de Terras ou um Rapaz de Confiança.",
"Eu sei muito sobre Comércio Básico, e também como me tornar um Rapaz de Confiança.",
"Eu sei muito sobre Comércio Avançado.",
"Eu sei muito sobre Comércio Básico.",
"Eu sei como me tornar um Proprietário de Terras.",
"Eu sei como me tornar um Rapaz de Confiança.",
"Eu quero aprender mais sobre Comércio Avançado.",
"Eu quero aprender mais sobre Comércio Básico.",
"Eu quero ser um Proprietário de Terras.",
"Quero ser um Rapaz de Confiança.",
"Claro que sim!",
"Talvez mais tarde.",
"As moedas são todas de nações diferentes.",
"Gostaria de saber de quantas nações existem moedas?",
"Se quiser saber mais sobre a Caixa de Coleta",
"- pergunte a outra pessoa.",
"Capitão, agora você sabe tanto quanto nós sobre a Caixa de Coleta!",
"Ok, tenho tudo no meu Livro de Missões.",

};
