string DLG_TEXT[31] = {
"Poderia ser pior, jovem Capitão - afinal, estamos na casa de Deus.",
"Bem, fico feliz em ouvir isso - tente encorajar os outros também!",
"Graças a Deus, estamos salvos. Se houver algo que eu possa fazer por você, Capitão, por favor, me avise.",
"Obrigado, Pai, mas ainda não descobri como abrir todas as portas...",
"Ahh, Capitão, bem-vindo à igreja, meu filho. Mas deixe-me perguntar - o que você estava fazendo na sala do coral?",
"Há um coral?! Hmm, como eles estão vestidos?",
"Sim, temos muito orgulho do Coro da Igreja de Port Royal. Se você me perguntar, eles parecem monges - monges vermelhos.",
"Estou precisando desesperadamente de roupas assim. O que você quer por eles, Padre?",
"Pode começar com o que tiver de armas sobrando...",
"Concordo com isso!",
"... e pague o resto quando tiver recolhido as mercadorias.",
"E isso seria...?",
"Bem, acho que podemos dizer que você fez uma (enorme) doação para a igreja. Que tal o seu ouro para eles, Capitão?",
"Todo o meu ouro!!?? Hmm, vou pensar nisso...",
"Se você se interessa tanto por música",
"- por que não volta para a sala do Coro e toca uma música você mesmo, Capitão?",
"Vejo que você decidiu comprar as roupas do coro, afinal, Capitão!",
"Certo, pegue o dinheiro, Padre. (aquele padre que negociava astuto)",
"Agora deixe-me perguntar: o senhor não tem mais nada que pertença à igreja?",
"(engula em seco, não era isso que eu esperava) Claro que não, padre!",
"O que tem nesse saco que o senhor tem aí...?",
"Só pertences pessoais.",
"Tipo o quê...?",
"(Ah, qual é) Saco de dormir, escova de dentes e tudo mais...",
"Acho que o senhor está mentindo - quem já ouviu falar de 'escova de dentes'!? Não, são os tesouros da igreja que o senhor tem aí, né, Capitão!",
"Tudo bem, padre, mas foi por uma boa causa. Pode salvar a vida dos meus amigos!",
"Hmm, nesse caso, talvez eu devesse deixá-los ficar com o senhor...? E o senhor nos resgatou antes também.",
"Obrigado, Padre Bernard, e adeus.",
"Vá em frente, Capitão, antes que eu mude de ideia!",
"Aqui, pegue esta como amostra.",
"Nossa, gostei!",


};
