string DLG_TEXT[34] = {
"Ahoy, camarada, você gostaria de encontrar um bumbum DE VERDADE",
"Arrr.",
"Ei, marinheiro, o que está acontecendo?",
"Eu tenho um chapéu.",
"Você gostaria de olhar entre as minhas pernas e ver meus pulmões?",
"É, me arrepie, e arrepie outra coisa se você me entende...",
"Você já viu Jesus Cristo Caçador de Vampiros?",
"Abra as pernas.",
"Eu sou uma prostituta!",
"Eu sou um pirata!",
"Estou aqui para desentupir seus canos.",
"Meus canos estão REALMENTE bagunçados.",
"A Disney vai cagar na sua cama enquanto você dorme.",
"Eles com certeza...",
"Eu posso não ser o Fred Flinstone, mas com certeza posso fazer sua cama balançar.",
"Isso é um barril na sua calça? Porque eu queria dar um tapinha nessa bunda.",
"Que carga linda você tem aí embaixo, querida.",
"Eu adoraria saquear sua vila.",
"Vem cá, garota, eu quero limpar esse convés. ",
"Eu quero navegar pelos seus sete mares.",
"Você realmente içou minha vela principal.",
"Me fode na bunda!",
"Ahoy, Capitão, talvez eu tenha algo para você...",
"Ok, quanto e o que você oferece?",
"Primeiro é de graça e NÃO é o que você parece estar sonhando...",
"Ah, desculpe, não era minha intenção, Srta. Issalini.",
"Senhorita, que legal. Não, eu herdei algumas receitas da minha tia - elas descrevem curas, remédios antigos e todo tipo de tratamento caseiro.",
"Bem, isso é realmente alguma coisa e agora você está me oferecendo isso?",
"Aqui, pegue-as, Capitão. Talvez eu também esteja preocupado em resgatar os cidadãos ilesos.",
"Claro, obrigado, senhorita.",
"Estou um pouco ocupado agora...",
"Muito bem, então.",
"Tudo bem, eu abro para você, Capitão.",
"Obrigado, senhorita...",

};
