string DLG_TEXT[32] = {
"Sim...?",
"Desculpe incomodá-la, Irmã. Meu nome é Howard Pyle e...",
"Ah, não - finalmente aconteceu.",
"Algum problema, Irmã Richards?",
"Eu sei por que você veio aqui, Capitão Pyle. E também o que você é!",
"Sou apenas um marinheiro comum e honesto...",
"Pare com isso!! Você é um pirata, assim como meu irmão era. E você está aqui pelo mapa! Certo?",
"Bem, se você coloca dessa forma, Irmã.",
"Quantas vidas você teve que tirar para chegar aqui. Todos os outros cinco bandidos?",
"Escute, eu não matei uma única pessoa. (por causa disso) É verdade que ele pegou do próprio Barba Negra?",
"Muito bem então. Foi o que aconteceu: o pirata Teach bloqueou a cidade de Charles Town com sua flotilha.",
"Acho que o Queen Anne's Revenge e alguns saveiros?",
"Sim, o Queen Anne's Revenge era seu grande navio almirante. Israel Hands era o capitão do saveiro Adventure, o Major Stede Bonnet e meu irmão no saveiro Revenge. E um quarto saveiro pequeno adicional servindo como bote.",
"Ouvi dizer que suas exigências à cidade eram muito humildes.",
"Não para essas pessoas. Você deve se lembrar de que todos estavam mais ou menos infectados com a 'doença francesa'.",
"Sífilis, sim. Será que eles conseguiram o que tanto precisavam?",
"A entrada de Charles Town era protegida por um forte no alto de um penhasco. Um forte que poderia afundar todos os navios a qualquer minuto...",
"Sim...",
"Os remédios não ajudaram meu irmão...",
"Sinto muito por isso, irmã. Você está disposta a trocar o mapa comigo?",
"Certamente que não.",
"Por que não?",
"Porque eu não o tenho mais.",
"O quê??!! Então, onde está?",
"A abadessa o pegou. Ela guarda todos os nossos pertences pessoais.",
"Você acha que ela está disposta a vendê-lo?",
"A decisão é dela. Não tenho interesse no pedaço de papel do meu irmão.",
"Onde está a abadessa? Posso falar com ela?",
"Tente o quarto dela, é no andar de cima.",
"Muito obrigada pelo seu tempo, Irmã Richards.",
"Antes de ir embora, Capitão, tenho algo para você...",
"Bem, obrigada, Irmã!",


};
