string DLG_TEXT[22] = {
"O que você quer que eu faça?",
"Leve três homens e vigie a porta certa no convés de dormir!",
"E eu faço o mesmo e vigie as escadas, certo, Capitão.",
"De fato, arme-se e vá para suas posições! César e Rei, sigam-me quando estiverem prontos.",
"Capitão, este sujeito quer se juntar ao nosso grupo.",
"Um soldado espanhol se juntando a bucaneiros ingleses?",
"Tenho uma ideia, Capitão - vamos trocar de roupa.",
"Vá em frente. E seja rápido!",
"Você está me acusando de ser um ladrão - mas não é roubado...",
"Então, como você conseguiu essa roupa tão boa?",
"Comprei em um mercado de pulgas!",
"Grrr.",
"Soldado às suas ordens, Capitão.",
"Padre às suas ordens, Capitão.",
"Músico às suas ordens, Capitão.",
"Muito bem.",
"Sou apenas um músico e não falo espanhol. Mas o Padre dões, Capitão.",
"Quem é o Padre?",
"O monge vermelho. Capitão, eu também quero desembarcar.",
"Por quê?",
"Quero procurar um instrumento - a música alegra a tripulação, Capitão.",
"Certo, então você e o padre vão para a praia.",

};
