string DLG_TEXT[54] = {
"Você não vê que estou de serviço! Não me incomode.",
"Tudo bem, tudo bem.",
"Você queria denunciar algum crime?",
"Não, claro. Sou capitão, afinal... mas vejo que você não está ouvindo.",
"Lembre-se: não permitimos brigas nas ruas. Você pode se defender, é claro, se alguém te atacar.",
"Certo, vou considerar essa informação.",
"Que tempo insuportável... e eu tenho que ficar aqui parado. Você pode não acreditar em mim, mas meu único passatempo é lutar contra as moscas que tentam pousar no meu rosto.",
"É uma pena, mas não posso te ajudar. É seu dever.",
"Se quiser conversar, encontre outra pessoa. Tenho meu dever a cumprir, e não é meu dever falar com você.",
"Eu só estava me perguntando se você está vivo ou não. Você está parado aqui como uma estátua.",
"Acha que é fácil proteger nossa cidade? De jeito nenhum! É um trabalho muito importante e perigoso. Lembro-me de uma vez...",
"Me diga outra hora. Preciso ir.",
"Vá embora, não me incomode.",
"Como quiser, soldado.",
"Ei! Pode me trazer um copo de rum da taverna?",
"Talvez. Mas não vão me enforcar por ajudar um soldado a ficar bêbado em serviço? Não, espere até trocarem a guarda, e aí você pode beber o quanto quiser.",
"Por que tem que ser um marinheiro de aparência rude como você tentando falar comigo?! Não há mulheres bonitas nesta cidade?",
"E você chama isso de cumprir seu dever? Olha, você não ia querer perder a captura de um criminoso perigoso como eu, ia? Ha-ha!",
"Você parece bem saudável. Não quer se juntar ao nosso exército? Temos bastante espaço no nosso quartel, boa comida, rum de graça.",
"Parece bom, mas terei que recusar sua oferta. A disciplina do exército não me cai bem.",
"Este calor... Eu daria tudo para voltar para a Europa, para a civilização...",
"Sim, este clima não parece lhe cair bem.",
"Alto! Nunca o vi antes, mas você tem cara de pirata! Pode provar que não é nada disso?",
"Sou o Capitão Howard Pyle e aqui estão meus documentos de comissão e do navio para provar.",
"Documentos... hah. Pode estar tudo bem - ou não. Esse nome soa muito pirata... pirata... pirata... ehh...",
"Sim...? (Quão difícil pode ser)",
"Qual é o seu negócio no Forte, 'Capitão'?",
"Estou apenas passando o Forte para a Prisão. Estou fazendo uma pesquisa...",
"Não. Você não pode fazer isso sem um Passe!",
"Entendo. Mas é só isso que eu tenho aqui, soldado. Assinado pelo próprio Sir William Stapleton!!",
"Mais papéis, hah. Dê uma olhada nisso, Frank... Melhor ter certeza.",
"Há algo errado?",
"Bem... ehh... ehh, acho que é um documento correto. Mas... o Passe é só para você, Capitão.",
"Tudo bem então.",
"Abra o portão, Beefheart, você tem as chaves.",
"(Vamos lá)",
"Calma aí. Mostre-me seus papéis, se tiver algum. Se não tiver...",
"Bem, claro, senhor.",
"Hmm, talvez este documento seja genuíno, afinal. Siga em frente antes que eu mude de ideia.",
"Ehh... meu documento, por favor.",
"O que tem ele?",
"Posso devolvê-lo, por favor?",
"Certamente que não. Você o usou e eu o aceitei. Agora saia da minha vista.",
"Mas vou precisar dele no meu caminho de volta pelo Forte. ",
"Vou te dizer uma coisa: eu realmente não me importo.",
"Sem isso, os soldados vão me atacar!",
"Se você quiser sobreviver, não tente roubar ou tocar em nada!",
"Claro que não. (Hmm, veremos...)",
"Eu ouvi alguma coisa. Tem alguém aí em cima?",
"(oh oh)",
"Interessante o suficiente quando o Took descobre -",
"- anda logo!!!",
"Você acabou de matar outro visitante nesta prisão. Sai fora ou VOCÊ será atacado!!",
"--- (oh oh)",

};
