string DLG_TEXT[54] = {
"Olá, Capitão. Em qual parte você está interessado?",
"!!!",
"Para onde, Capitão?",
"Ah, estou bem aqui, obrigado por esta parte da história.",
"1) Para Port Royal e Governador Rogers, onde a missão começa.",
"2) Para o Bordel no Assentamento Pirata. Vou resgatar Caroline K.",
"3) Para Port Royal depois da parte do Bordel: TAVERNA. (pistola 1)",
"4) Para Port Royal: ARMÁRIO. (pistola 3)",
"5) Para Port Royal: COZINHA. (pistola 4)",
"6) Para Port Royal: TERRAÇO para BIBLIOTECA. (pistola 5)",
"7) Para Port Royal depois da destilaria: LOJA para PONTE.",
"8) Para Port Royal: DEPÓSITO DA TAVERNA. (pistola 6)",
"9) Para Port Royal, do lado de fora do estaleiro: pronto para o BAÚ DE REMÉDIOS.",
"10) Para Cave Shore: MEDICAMENTOS COLETADOS.",
"11) Para Port Royal: DO ESTALEIRO para a FAZENDA.",
"12) Para os Navios de Prêmio: longa viagem até o ESCONDERIJO DO VANE.",
"14) Para a sala do Coro da Igreja: longa viagem até o ESCONDERIJO DO VANE.",
"15) Para a Igreja dos Piratas, antes das MOEDAS.",
"16) Para Cave Shore: antes da TORRE DE MADEIRA",
"17) Para a Caverna Azul: VINGANÇA.",
"18) Para a Corveta: VINGANÇA.",
"20) Para Port Royal: DO ESTUDO para o SEGREDO.",
"Tem certeza, Capitão? O processo pode ser um pouco assustador...",
"Não estou com medo!",
"Posso ver as alternativas novamente?",
"Hmm, acho que vou jogar o início da aventura.",
"Então fique avisado, Capitão.",
"Certo, certo. Agora vamos lá!",
"21) Para Port Royal e o início da PARTE 2.",
"22) Para a Fazenda: depois de ALQUIMIA 1.",
"Parte um.",
"Parte dois.",
"Mudei de ideia, leve-me para a parte um.",
"Mudei de ideia, leve-me para a parte dois.",
"23) Para Cave Shore: depois de VANE.",
"24) Para Curaçao: depois de MÃOS.",
"25) Para La Grenade: depois de ODEL.",
"26) Para Tortuga: depois de CIRURGIÕES.",
"27) Para Charlestown: depois de MALTAINS.",
"28) Para Cayman Estate: depois de LABIRINTO e QUARTOS.",
"29) Para Eleuthera: depois de CIDADELA.",
"30) Para Cartagena: depois de MONASTÉRIO.",
"31) Para Antígua: depois de PRISÃO.",
"32) Para Cayman: depois de ADEGA DA PROPRIEDADE.",
"33) Para os turcos: depois de MAPA ENCONTRADO.",
"34) Para Cartagena: depois de TODAS AS QUATRO MISSÕES.",
"35) Para Kristiania: depois de TODOS OS SEIS ITENS ENCONTRADOS.",
"36) Para a Costa de Careen: depois da TORRE DO BARBA NEGRA.",
"37) Para Corvette: depois de COSTA DE CAREN.",
"38) Para Isla Mona: depois de CORVETTE.",
"Posso te levar a qualquer parte da missão. Mas lembre-se de que tem um preço.",
"Hmm, quanto vai me custar?",
"Se você terminar a missão sem usar nenhum jump start, terá acesso ao capítulo bônus.",
"Eu não me importo com isso. Por favor, continue.",

};
