string DLG_TEXT[25] = {
"Não ouse se dirigir a um Intendente dessa maneira novamente, seu mercenário insolente!",
"Umm... err... Entendo. Adeus.",
"Ei, você aí! Você me parece suspeito. Quem diabos é você? Mostre-me seus documentos!",
"Quem diabos é VOCÊ? Identifique-se e seja rápido!",
"Alto! Nunca o vi antes, mas você tem cara de pirata! Pode provar que não é nenhum?",
"Eu sou ",
", e aqui estão minha patente de capitão e meus documentos de embarque para provar. Foi rápido o suficiente para seu temperamento explosivo?",
"Então aí está você, finalmente, jovem arrogante. Você já aprendeu demais com Rogers - é o que todos nós pensamos!",
"É, eu percebi isso! Por favor, pule todas as frases gentis - acho que você também está me oferecendo algo, goste ou não...",
"Rogers decidiu transferir algumas mercadorias para o seu navio, como um presente.",
"Isso foi muito gentil da parte dele - você não concorda?! E é Governador Rogers para você!",
"Espere um minuto, seu marinheiro nojento...",
"O quê?",
"Esse cinto que você tem aí - só me entregue!",
"Certamente não! O Governador Rogers me deu.",
"Quem você pensa que é, garoto? Essa coisa pertence a nós, os oficiais -",
"- e nós vamos tirá-la de você!",
"Aqui está outra coisa boa demais para você - mas acho que você vai precisar dela, pirata!",
"Isso foi muito gentil da sua parte.",
"Calma, seu canalha - você tem que me fazer um favor em troca.",
"Muito bem...",
"A porta da cozinha está bloqueada - estamos aqui parados!",
"E onde fica a cozinha? Como eu vou...",
"Está na proa do Galeão que pegamos. Você pode começar seu trabalho a bordo consertando o mecanismo de ancoragem da Corveta.",
"Hmm, eu...",

};
