string DLG_TEXT[38] = {
"Não ouse se dirigir a um Artilheiro dessa maneira novamente, seu mercenário insolente!",
"Umm... err... Entendo. Adeus.",
"Ei, você aí! Você me parece suspeito. Quem diabos é você? Mostre-me seus documentos!",
"Quem diabos é VOCÊ? Identifique-se e seja rápido!",
"Alto! Nunca o vi antes, mas você tem cara de pirata! Pode provar que não é nenhum?",
"Eu sou ",
", e aqui está minha patente de capitão e meus documentos de embarque para provar. Foi rápido o suficiente para seu temperamento explosivo?",
"Não vê que estou ocupado testando esta peça. Você tem que encontrar a munição sozinho, macaco da pólvora.",
"Essa não é uma maneira apropriada de se dirigir a um Capitão, seu bandido simplório.",
"Não me importa quem você finge ser, mas vou te dizer uma coisa: quando eu terminar de recarregar, é melhor você sair do caminho...",
"Você está completamente louco? Disparando um canhão dentro do prédio?!!",
"Então agora você também é especialista em canhões? Juro que você nem carregou uma bala de canhão, 'Senhor'.",
"Mais uma palavra rude e eu vou te estripar como um peixe!",
"Pegue esta lâmina e saia da minha frente agora!",
"----",
"O que você está fazendo aqui, garoto!",
"Eu poderia te perguntar a mesma coisa, 'Senhor'.",
"Bem, estou estudando balística, nada de estranho nisso!",
"Para mim, parece poesia...",
"Chega disso, Capitão, me dê o livro que você tem e eu te farei um favor.",
"É apenas uma coleção de poemas, nada que possa lhe interessar e que tipo de favor seria esse?",
"Tudo bem, eu aceito mesmo assim. Há uma saída daqui, deixe-me mostrar.",
"Então, concordo, Sr. Stretton!",
"Recebi ordens para ajudá-lo, então deixe-me abrir esse baú completamente agora.",
"Hmm, espero que você não vá usar nenhum tipo de ferramenta - quase destruiu o baú antes!",
"Sem ferramentas - eu prometo. Então, se você se virar...",
"(Por que não tenho certeza disso?) E nenhum dano também!?",
"Se tem medo, deveria ter ficado no seu barco, senhor!",
"Tudo bem, abra então.",
"Qual é o problema, jovem? Abri o baú e também encontrei algo escondido atrás dele. Verifique você mesmo!",
"Hã?",
"Acho que não, garoto, escute: sua nave foi reformada com novos canhões e munição também - e agora, macaco da pólvora!?",
"Acho que não, garoto, escute: sua nave foi reformada com novos canhões - e agora, macaco da pólvora!?",
"Acho que não, garoto, escute: seus canhões foram consertados e munição adicionada também - e agora, macaco da pólvora!?",
"Acho que não, garoto, escute: seus canhões foram consertados - e agora, macaco da pólvora!?",
"Acho que não, garoto, escute: munição foi adicionada à sua nave - e agora, macaco da pólvora!?",
"Sou um homem muito ocupado, volte quando tiver feito um trabalho melhor coletando aqueles remédios!",
"Hã?",

};
