string DLG_TEXT[142] = {
"Havia governadores corruptos por toda a Costa Atlântica. Eles colaboraram com os piratas em vez de exterminá-los. Mas você não tem experiência suficiente para valer a pena falar mais!",
"Hã?",
"Eu nunca o conheci pessoalmente, mas me disseram que ele tinha uma Vontade de Ferro e lutava como um Pistoleiro Profissional! Vejo que você está um pouco mais experiente desde a última vez, talvez até tenha ido para a cadeia!?",
"De quem você está falando e como sabe que me jogaram na prisão, velho?",
"Olá, jovem Capitão, talvez eu possa lhe dar um breve resumo da sua carreira se você vier aqui.",
"Claro, por que não?",
"Rumores dizem que ele tomou mais de 40 navios. Ele usou um arsenal menor que só um Mestre Pistoleiro poderia controlar.",
"Talvez eu volte um dia, apesar desta conversa sem sentido.",
"Capitão, tenho algo muito importante para lhe contar. Venha aqui imediatamente, por favor!",
"Olá, já estou a caminho.",
"Foi o Tenente Maynard quem finalmente pôs fim à sua vida inútil. Mas chega de velhos tempos. Tenho um favor a lhe pedir, meu promissor jovem Capitão.",
"O que foi? Como posso ajudar? (Ele NÃO vai me enforcar!!??)",
"Minha querida filha desapareceu. Estou velho demais para navegar pelo arquipélago em busca da minha amada.",
"Então...?",
"Encontre-a para mim e serei muito grato pelo resto da minha vida.",
"Hmm, não tenho certeza se quero arriscar minha vida por isso...",
"Na verdade, você não tem muita escolha, Capitão Pyle, mas eu lhe darei um item extraordinário se você conseguir me ajudar.",
"Bem, isso pode acabar sendo uma aventura, afinal.",
"Você realmente é um aventureiro do meu gosto, Capitão.",
"Preciso saber um pouco mais sobre o desaparecimento dela.",
"Ela estava indo para Antígua quando o navio foi abordado por piratas.",
"Onde ocorreu o ataque?",
"O navio havia sido levado por uma tempestade dois dias antes e estava em algum lugar ao norte de Guadalupe.",
"É só isso que você sabe?",
"Um dos sobreviventes viu os piratas a levando como prisioneira.",
"Será que eles a levaram para pedir resgate? Você não é um anônimo. Governador?",
"Não, não ouvi nada dos sequestradores dela, ela jamais revelaria seu nome verdadeiro.",
"A filha do homem que pôs fim à era da pirataria não vale muito...?",
"Sim, Capitão, por favor, localize esses bandidos antes que seja tarde demais e traga minha filha de volta.",
"Como ela é?",
"Ela é uma morena bem alta e sempre usa calças como um homem!",
"Hábito estranho, mas farei o meu melhor para encontrá-la viva.",
"Eu sabia que podia contar com você, Capitão!",
"Tudo bem, Governador, zarparei imediatamente...",
"Eu sabia que você conseguiria! Mais tarde, expressarei minha gratidão de uma maneira melhor, mas primeiro, Capitão, deixe meu médico cuidar de seus ferimentos.",
"Vamos acabar logo com isso então.",
"Quero lhe dar, Capitão, um item muito raro.",
"Isso certamente seria uma honra, Governador.",
"Você realmente provou sua coragem salvando minha querida Caroline K dos piratas.",
"Nada para falar.",
"No entanto, para conseguir essa coisa especial, você também terá que provar que é inteligente.",
"Estou todo ouvidos...",
"Está no meu quarto e não é tão difícil de encontrar. Ah, e a propósito, Capitão, meus aposentos são um pouco espalhados.",
"Então, vou embora, Senhor! (Vamos lá, como isso pode ser difícil!).",
"Vejo que você encontrou a primeira pistola. Agora, para outro assunto: estou lhe oferecendo um pedaço de terra. O que me diz, Capitão?",
"Sou muito grato, Governador.",
"Agora, por favor, vá até meu Tenente, ele tem os documentos prontos para você.",
"Proprietário de terras! Eu!",
"Vamos continuar? Espero que os reparos em andamento aqui não estejam te incomodando na busca pela próxima pistola.",
"Outra pistola? Bem, ok, estou a caminho novamente.",
"Certifique-se de encontrar a chave da cozinha antes de sair para pegar a próxima pistola.",
"Certo, também há uma chave para encontrar.",
"Fico feliz em ver que você sobreviveu aos experimentos daquele maníaco lá embaixo.",
"Olá novamente, Governador, este terraço é realmente um lugar agradável.",
"De fato é. Agora, vamos aos nossos próximos negócios, jovem Capitão. Vou te dar uma dica para encontrar a próxima pistola.",
"(Ainda mais armas!?) Acho que preciso disso.",
"Passe pelo escritório do agiota e o resto será fácil.",
"(Ele está vendendo armas ou o quê?) Ok, muito obrigado, senhor.",
"Veja bem, eu troco com pistolas, entre muitas outras coisas, mas essas armas são um extra. Você verá!",
"(Hah! Eu estava certo) Ao agiota então!",
"Ahh, bem-vindo, Capitão. Acho que você conheceu o pobre Selkirk?",
"Ah, sim, ele parece ser um homem muito religioso e, ehh... um pouco estranho também, Governador.",
"Sabe, quando o encontramos, ele mal conseguia falar. Agora, para sua próxima tarefa...",
"(O que é desta vez!) Sim, Governador!?",
"Este você encontrará no quarto da minha mãe, em cima da loja. Agora, isso será quase fácil demais...",
"(Ele está realmente se divertindo com essas charadas) Muito obrigado por isso, Governador, estou a caminho de novo!",
"Então, finalmente você está aqui. Equipe-o com alguns instrumentos de navegação adequados, Sr. Dampier!",
"Ah, sim, levou algum tempo.",
"Tenho madeira e um par de garrafas de melaço no meu escritório. Veja o que você consegue encontrar.",
"(Há muitos pedidos agora!!) Claro, Governador, vou ver o que posso fazer.",
"Por favor, Capitão, não se incomode com a grosseria dos oficiais - são todos bons homens com quem navego há anos. Deixe-me cuidar daquele livro do Dampier.",
"Sem problemas, Senhor. (Que bando de valentões fanfarrões - é o que eu acho!)",
"Muito bem, Capitão, e se não se importar, tenho mais alguns livros aqui...",
"(Ah, qual é o problema, por que você me toma? Um bibliotecário?!) Ok, vou consertar os livros. (Será que tenho algum problema sério para dizer NÃO?)",
"E mais uma coisa...",
"(NÃO, NÃO, NÃO) Bem, Governador, eu...",
"Há alguns dias cometi um erro estúpido. Uma noite, talvez depois de um ou dois copos de rum, perdi uma das chaves da porta - deixei cair no tanque de melaço.",
"Entendo. E agora quer que eu tire de lá?",
"Seria muito gentil da sua parte. Mas não é fácil, o tanque está completamente fechado.",
"Tudo bem, acho que consigo lidar com isso. (Será que eu?)",
"Ahh, você me trouxe 'Piratas Notórios...'. Como você deve ter adivinhado, há outra pistola - e eu te dou uma dica: Vá até o Escritório da Loja!",
"Vou pegar um arsenal completo, Governador! (Talvez eu consiga viver vendendo armas!)",
"Essa é a ideia, sim! E eu não as venderia se fosse você...",
"(Ele está lendo minha mente?) Certo - as pistolas estão ótimas, talvez um pouco gastas e pelo menos uma delas tenha pertencido a uma pessoa famosa!",
"Talvez todas tenham pertencido. Chega de papo agora - vá, jovem Capitão.",
"Adeus, Governador.",
"Capitão, antes de ir buscar a última pistola - posso lhe oferecer uma ou duas bebidas? Os aposentos da tripulação estão prestes a abrir!",
"(Ah, não!! Mais uma!!) Bem, obrigado, Governador, onde encontro aquela taverna?",
"Bem na sua frente, Capitão - espero que este meu joguinho não esteja te incomodando!?",
"De jeito nenhum, Senhor! (Pelo amor de Deus - Me deixe sair daqui!)",
"Já está indo embora, jovem Capitão?! Por que não toma um ou dois copos?",
"Bem, eu só...",
"Entre naquela taverna e não volte se ainda estiver sóbrio - você está entre amigos aqui.",
"Certo, (ainda fazendo exatamente o que ele quer?)",
"... e decidi te dar uma ajudinha extra.",
"Bem, eu certamente digo sim a isso!",
"No entanto, deixe-me deixar isso bem claro.",
"Eu só pensei que talvez seus produtos 'importados' viessem de...",
"Posso estar aposentado, mas ainda sou totalmente capaz de...",
"Bem, fique tranquilo, Governador - foi só algo que ouvi por acaso.",
"Você está suspeitando que eu seja um pirata??!!",
"---",
"Você encontrou a última pistola que consigo ver, mas tudo isso tem que esperar. Veja, esta colônia enfrentou problemas sérios e inesperados...",
"Eu sei - vários cidadãos foram feitos reféns.",
"Como assim, o que você sabe sobre esse negócio - você já conheceu os piratas?",
"Tive o azar de encontrá-los, sim.",
"Então talvez você saiba onde esses bandidos estão se escondendo!?",
"Olha, Governador - eles vão matar os reféns se eu te contar - não, eles me enviaram aqui para coletar o que eles querem em riquezas!",
"Hmm - ok, aqui está a lista e mesmo que não haja tesouros que eles exijam - pode ser complicado o suficiente encontrar todos os remédios e drogas aqui em Port Royal!",
"O quê? Remédios - só isso?!",
"Cale a boca e ouça com atenção. Fiz alguns preparativos - todas as pessoas na minha residência, familiares, amigos e oficiais, foram instruídos a revistar seus quartos em busca de remédios que possam ter.",
"E eu sou quem vai pegar.",
"De fato, você é. Aqui estão dois frascos que encontrei no meu quarto para começar. Posso sugerir que você primeiro procure uma Caixa de Remédios - talvez tenhamos uma na loja - Dave saberia.",
"Certo - vou ver o que posso fazer. (Os piratas trocam os reféns por xarope para tosse???)",
"Muito importante também é encontrar meu médico - se alguém deveria estar aqui cuidando desse negócio de remédios - talvez o navegador tenha visto o Sr. Dover.",
"Vou tentar encontrá-lo, então governador.",
"Você questiona minhas ordens, Carpinteiro - ",
"- Vou mostrar quem manda aqui!!",
"Ganhosos, é isso que eles são - todos eles. Não posso mais confiar na minha própria tripulação!",
"São as pistolas, certo? Acho que adivinhei a quem elas pertenciam... Mas há algo mais, certo, Governador?",
"Rumores, Capitão. Muitos rumores por todo o Caribe. Estou orgulhoso de ver que você encheu a Caixa de Remédios. Talvez você devesse ir embora imediatamente!",
"Rumores, Capitão. Muitos rumores por todo o Caribe. Estou orgulhoso de ver que você encheu o Baú de Remédios. Você tem remédios suficientes ou quer coletar mais?",
"Já estou a caminho do esconderijo dos piratas, Governador.",
"Acho que ainda pode haver algumas drogas na cidade para eu pegar.",
"Boa sorte então. Quando você voltar daquele desgraçado do Vane, não deixe de me encontrar aqui no estaleiro para receber sua recompensa final!",
"(Ah, mal posso esperar - será que é uma PISTOLA?!!!) Estou ansioso por isso, Governador.",
"Antes de mais nada, deixe-me agradecer por todos os seus problemas com o Baú de Remédios. Se você passar por esta porta atrás de mim, receberá a última recompensa. Encontre o caminho para minha casa na fazenda - isso será um começo.",
"O que pode ser, Governador? (Não é uma pistola, pelo amor de Deus!) (Ele também é fazendeiro agora?)",
"Não se preocupe, não é uma arma desta vez. Mas será útil COM as armas! Foi o Tenente Maynard quem primeiro cuidou desses itens.",
"Maynard - o famoso caçador de piratas?! Foi ele quem perseguiu e finalmente matou... ",
"Acho que você poderia chamá-lo assim. Foi por ordem de Alexander Spotswood, Governador da Virgínia - e ele me deu como uma lembrança antipirataria.",
"Bem, sou um honrado Governador. (Antipirata!! É mesmo?!)",
"Ah, qual é, eles são homens durões, só isso - tenho certeza de que nunca machucariam nenhum de nós. Agora, vá embora! Ah, quase esqueci, se ficar preso, peça ajuda à serva Minerva.",
"Não tenho medo, Governador. Vejo vocês mais tarde, então.",
"Você está indo muito bem, Capitão!",
"Ah, obrigado, Governador.",
"Só há um problema, Governador: eu não tenho navio!",
"Pode usar um dos meus, Capitão Pyle, o 'Marquis' está pronto no porto. Mas, por favor, navegue sob a bandeira britânica...",
"Bem, isso foi incrível!",
"Na Cabine você encontrará os itens que precisa. Boa sorte na sua jornada, Capitão!",
"Calma, Capitão! Tem certeza de que pegou todas as ferramentas necessárias?",
"Hmm, eu... (talvez eu não tenha, já que ele está perguntando)",

};
