string DLG_TEXT[20] = {
"Dê uma moeda a um pobre infeliz, minha querida",
"e Deus lhe dará sorte por sua gentileza!",
"Por favor! Dê-me algum dinheiro para comida -- e, hum, talvez alguma bebida!",
"Eu imploro!",
"Oh,",
"mostre um pouco de caridade a alguém menos afortunado do que você. Por favor?",
"Será que, ",
"você nem tem dinheiro? Talvez você devesse se juntar a mim no meu, hum, trabalho.",
"Caridade é uma virtude, ",
"mas vou precisar de mais moedas.",
"Desculpe, ",
"parece que você está com pouco dinheiro agora?",
"Generosidade combina com você,",
"que a sorte sempre o favoreça!",
"Infelizmente, ",
"parece que você nem tem dinheiro sobrando para caridade?",
"Desculpe,",
"caridade é uma virtude, mas negócios são negócios. Vou precisar de dinheiro.",
"Dê uma moeda a um pobre",
"e ela retornará dez vezes mais!",

};
