string DLG_TEXT[43] = {
"Você veio para nos libertar, capitão?",
"Hmm, claro, por que não? Mas quem é você e por que está trancado aqui?",
"Somos a tripulação do canhão, um pouco surdos talvez, mas muito leais ao governador Rogers e sua família.",
"E os oficiais não são homens confiáveis, é isso que você quer dizer?",
"Não, de jeito nenhum. Eles estão planejando remover Woodes Rogers do comando!",
"Qual o motivo disso? Eles não estão felizes com a parte que receberam do saque?",
"Não, eles acreditam que Rogers tem um segredo escondido em algum lugar...",
"E o que é isso? Um item ou são apenas boatos?",
"Tem algo a ver com aquelas pistolas que o Governador lhe ofereceu.",
"Estas pistolas... pensei que fossem só um pouco de nostalgia dos velhos?",
"Fique avisado, Capitão: eles com certeza querem se apoderar dessas armas, além daquela outra coisa.",
"Certo, obrigado. Vou tomar cuidado!",
"Mais uma coisa: tente destrancar o convés de munição para nós.",
"Vou ver o que posso fazer a respeito disso. Onde fica?",
"É bem acima de nós, e, Capitão, se precisar de nossos serviços, é só tocar a campainha no tombadilho!",
"Vou me lembrar disso, talvez nos encontremos de novo!",
"Suas ordens, Capitão?",
"Batalhão!",
"Aríete!",
"Esponja!",
"Pólvora!",
"Tiro!",
"Virar!",
"Dispensar!",
"Sim Sim",
"Capitão.",
"Mas Capitão, é impossível, o canhão está muito alto!",
"Certo (Hmm, devia ter pensado nisso.)",
"Mas Capitão, é impossível, o canhão é muito pesado para virar!",
"Mas Capitão, o convés de munição ainda está travado!",
"Atire!",
"Mas Capitão, esse é o seu trabalho!",
"Mova-se!",
"Mas Capitão, não há mais balas de canhão!",
"É mesmo?!",
"Obrigado por nos salvar de afogar o Capitão. Agora vamos remover essa coisa para você.",
"Vá em frente!",
"Deixa pra lá.",
"Mas Capitão, você ainda não encontrou seu Chifre de Pólvora!",
"Ainda não decidi! (Não sei bem o que fazer a seguir...)",
"Talvez você precise de um manual de Exercícios com Canhão, Capitão?",
"Talvez precise - onde posso conseguir um?",
"Tente o Quartel-General Militar - fica perto das Docas.",

};
