string DLG_TEXT[50] = {
"Pai!",
"...",
"Pai, ouça! Há um navio estrangeiro perto da ilha!",
"Oh, esse é apenas o meu navio. Quero dizer... o navio da minha irmã.",
"Ela está navegando em direção à costa, parece que quer pousar na baía!",
"Ou é o navio da minha irmã? Esse já deveria estar na baía.",
"E ela está voando com as cores dos corsários!",
"Definitivamente não é o navio da minha irmã.",
"Enquanto isso, voltarei furtivamente para a costa e observarei o que o navio pirata está fazendo.",
"Apenas tome cuidado, garota. Seu pai não pode se dar ao luxo de perder você.",
"Não seja bobo, senhor. Vou me esconder nos arbustos. A única vantagem que temos aqui é que conheço o terreno e todos os seus atalhos melhor do que ninguém!",
"Tudo bem, então todos nos encontraremos aqui depois que eu conversei com aquele governador.",
"Pai! Senhor Blaze! Os corsários desembarcaram em Punta el Ron. Eles enviaram um barco a remo com alguns homens para terra, provavelmente para explorar a área ou até mesmo montar um acampamento!",
"É a mesma baía onde meu... quero dizer, o navio da minha irmã está ancorado?",
"Não exatamente. Mas está perto. Perto demais para o meu gosto. Você tem um plano? Alguma ideia do que poderíamos fazer?",
"Não se preocupe. Na minha experiência, os piratas franceses são bastante estúpidos por natureza. Aposto que posso fazê-los sair da ilha com apenas alguns truques simples.",
"Já tive terra seca suficiente sob meus pés. Chegarei ao navio e deixarei os canhões falarem!",
"Oh, você realmente arriscaria sua vida assim por nós? Se você estiver certo e puder assustá-los, papai e eu ficaríamos em dívida com você para sempre!",
"Não é nada demais. Você tem alguma ideia de onde eles podem montar seu acampamento?",
"Há um pequeno forte abandonado, não muito longe daqui. Ouvi dizer que foi construído pelos homens de Colombo em sua quarta viagem ao novo mundo, quando descobriram #sisland_Cayman#.",
"Então é aí que vou armar minha emboscada.",
"Posso ir com você? Eu poderia ajudar!",
"Perigoso demais. Você fica aqui e cuida do seu pai.",
"*Suspiro* Se você diz",
"Fique seguro e não saia de casa. Vou avisar minha irmã, ela deveria afastar o navio antes que os piratas percebam. Depois disso, vou jogar um joguinho com os corsários!",
"Tudo bem. Pode ser perigoso, mas se você insistir...",
"Ótimo! Como começamos?",
"Primeiro, vamos avisar minha irmã, ela deveria levar nosso navio embora, antes que os piratas percebam. Depois disso, armaremos uma emboscada...",
"Sim? Devo atirar em alguma coisa?",
"Ainda não. Espere pelo meu sinal!",
"Que luta, senhor Blaze! Nós com certeza mostramos a eles, não foi?",
"Sim, e você lutou bem, Annie. Mas as coisas vão ficar um pouco mais complicadas agora. Obrigado pela ajuda, mas agora você deve voltar para seu pai para ter certeza de que ele está seguro. Eu vou levar as coisas daqui.",
"Hmm, se você diz. Boa sorte, nos encontramos mais tarde em nossa casa!",
"Adeus, Annie.",
"Espere! Há mais uma coisa.",
"O que é isso, Annie?",
"Você me levaria com você? Quero navegar pelos mares e viver uma vida de aventuras!",
"Hm, mas e o seu pai!",
"Por favor, senhor Blaze!",
"Tudo bem, vou apresentá-lo à minha irmã. Ela é quem está de calça. Mas agora, realmente deveríamos ir.",
"Sinto muito, mas não é uma boa ideia.",
"Hum, é uma pena. Bem, você me encontrará aqui caso mude de ideia.",
"Adeus.",
"Ótimo! Muito obrigado!",
"Vamos!",
"Tudo bem, por que não. Bem vinda a bordo, Annie!",
"Uma batalha naval contra piratas? Se você pudesse fazer isso e derrotá-los ou expulsá-los, papai e eu estaríamos em dívida com você para sempre!",
"Não é nada demais. Só vou ter que pegar emprestado o navio da minha irmã.",
"Boa sorte e bons ventos para você, Senhor Blaze!",
"Isso não vai demorar muito!",
}
