string DLG_TEXT[40] = {
"Bem-vindo.",
"Obrigado.",
"Sim, conte comigo também! Tenho estado tão entediado ultimamente. Eu sei que Skull não pode sair da Ilha, e quanto ao John Paul de lá, ele gosta muito de sua independência.",
"Isso nos torna quatro navios.",
"Estou feliz em conhecê-la também, Bonnie. Mas o que é essa parte da irmã mais velha? Eu pensei que éramos gêmeos? .",
"Nós somos, nós somos! Mas você nasceu um minuto antes de mim! Então isso faz de você minha irmã mais velha! Ha! Ha! .",
"Ah! Eu vejo. Estou feliz por termos resolvido isso. Isso então me torna no comando. Ha! Ha! Portanto, temos um tesouro para encontrar. Você está pronto para a aventura?",
"Oh! Sim. Estou esperando há dias você chegar aqui. Quando partimos e para onde vamos?",
"Bem.. diz no mapa que devemos navegar até a ilha #sisland_Turks# e procurar o pirata Short Jack Gold, e perguntar se ele quer nadar! Isso parece um pouco estranho.",
"É código, é código! Tem que estar em código. Vai dar certo quando chegarmos lá você verá.",
"Espero que você esteja certo, ou vamos parecer muito estúpidos, indo até um pirata e perguntando se ele quer nadar!",
"Não se preocupe tanto ",
" tudo vai dar certo, sempre dá. Quando é que vamos navegar?",
"Assim que eu verificar as provisões e equipamentos, poderemos partir. Assim que estivermos fora da vista de terra, devemos lembrar de hastear a bandeira pirata para podermos pousar na Ilha #sisland_Turks#.",
"Olhe olhe! Eu disse que era código. Oh! isso está ficando mais emocionante a cada minuto! E veremos Blaze novamente!",
"Acalme-se, acalme-se! Ainda não o encontramos. [PENSA:] Irmãzinhas!",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
};
