string DLG_TEXT[87] = {
"Então, qual é o próximo passo? Está fazendo uma pausa, se você me perguntar, irmã.",
"Tudo a seu tempo, querido irmão.",
"*RONCO ALTO*",
"Ele! Chama! Levante-se, seu patife preguiçoso!",
"O que.. Quem é? Não tão alto! Mas... Beatriz? Isso é você?",
"CLARO QUE SOU EU, SEU BARRIL DE RUM INÚTIL DE UM IRMãO! LEVANTAR!",
"Pelo amor de Deus, Bea, pare de gritar! Estou com uma dor de cabeça terrível... estou vendo em dobro!",
"Você não está vendo o dobro, seu bêbado horrível, você está saindo com minha irmã gêmea!",
"Irmã gêmea? Mas como? Onde? O que?",
"Sim, eu também não sabia sobre ela até duas semanas atrás.",
"Ooh... Minha cabeça está girando. Bem, pelo menos uma irmã que me trata bem! O que você está dizendo sobre um mapa do tesouro?",
"Esqueça o mapa do tesouro por um momento, você roubou rum daqueles piratas na... Ilha da Neve!",
"Ilha de neve? Ah, você quer dizer Nevis.",
"Neves?",
"Sim, ninguém consegue se lembrar daquele trava-língua espanhol, exceto o espanhol. Eu chamo-lhe 'Nevis' e acredito que isso vai durar.",
"Qualquer que seja. Eles estão furiosos. Por que você não entregou a remessa?",
"Doces, lindas moedas, pequena Bea! Encontrei um comprador melhor! Um oficial da #sisland_Falaise de Fleur# pediu rum para o casamento de seu filho. Paga um bom preço.",
"Não me chame de Bia! E como você pretende entregar a cachaça se você mesmo bebeu metade durante a viagem?",
"Só um gole para molhar o apito!",
"Claro... Tudo bem, entregamos o rum restante para #sisland_Falaise de Fleur# para que você possa manter pelo menos um pouco da sua dignidade como 'Comerciante'. Mas deixamos para trás aquela resumida que você chama de barco, ele está prestes a afundar de qualquer maneira. Você vem a bordo conosco e carregaremos o rum!",
"Aqui estamos, a propriedade espanhola em #sisland_Falaise de Fleur#! Vamos vender o rum a um dos comandantes da guarnição. Oh, já posso ouvir aquelas moedas doces tilintarem!",
"Apenas um de nós precisa ir ver aquele oficial, o resto do grupo pode ficar para trás.",
"Claro, por que não. Quem você acha que deveria ir, pequena Bea?",
"Vou fazer isso sozinho. Vocês dois só causariam mais problemas!",
"Você nos colocou nessa situação, Blaze, você mesmo lida com isso!",
"Bonnie deveria ir, para que você e eu possamos nos encontrar.",
"...",
"Chama?",
"Hum...",
"Eu não acredito! Não me diga que você perdeu seu pedaço do mapa!",
"Bem... Não 'perdido' como em 'Não consigo encontrar', mas sim 'perdido' como em 'Joguei um joguinho de cartas'...!",
"UM JOGO DE CARTAS? EU DEVERIA SABER, SEU JOGADOR INÚTIL, CHAPADO E PREGUIÇOSO!",
"Este oficial do navio queria aumentar as apostas e este papel era a única coisa que eu poderia oferecer a ele. Um mensageiro tinha me dado isso mais cedo, não achei que fosse importante...",
"Não é importante?! Este mapa do tesouro é herança da nossa família! O que devemos fazer com apenas meio mapa? Acender uma fogueira aconchegante?!",
"Olha, sinto muito, Bia. Não pensei nisso, não depois de tomar uma xícara de rum. Ou dois.",
"Não me chame assim! Você pelo menos se lembra quando e onde PERDEU o mapa?",
"Não deve ter passado muito tempo antes de eu te conhecer... E certamente foi na taverna de #sGreenford# em #sisland_Oxbay#. Foi o navegador de um navio do tesouro espanhol que ganhou de mim o pedaço do mapa.",
"Agora... Você pode, por favor, lembrar o nome deste navio para que possamos pelo menos ter a sombra de uma pista?",
"Claro, o nome do navio era...",
"'Villa de Málaga' era o seu nome! Agora eu me lembro disso.",
"Bem então. Não nos resta mais nada a fazer do que ir a #sGreenford# e perguntar sobre a 'Villa de Málaga'. É a única pista que temos... Talvez não seja tarde demais para encontrar aquele navio e seu maldito navegador. Vamos navegar!",
"Você olha só, afinal você não é um mau navegador! Chegamos a #sisland_Cuba#. Ou 'Cuba' como também é chamada. A joia da coroa dos espanhóis!",
"Parece que você já esteve aqui antes, Blaze.",
"Bem, eu tenho. Mas os espanhóis não aceitam piadas quando se trata de contrabando... Passei alguns dias e noites nas celas de prisão das guaritas locais.",
"Posso imaginar isso... Mas do jeito que você disse, eles devem estar vigiando esta ilha como se fosse o globo ocular do rei Filipe II.",
"Eles certamente fazem. Afinal, é a sua principal base de operações no novo mundo, o local onde a frota do tesouro se reúne para regressar à Europa e o local onde os exploradores partem para as conquistas do continente. E onde quer que você vá, Diego Velázquez de Cuellar, o homem que primeiro reivindicou e colonizou a ilha para a Espanha há cerca de 50 anos, é um herói nacional.",
"Mas ele não teve muita concorrência em suas façanhas, teve?",
"Não da Europa naquela época. Mas você está esquecendo as pessoas que viveram aqui antes, as tribos Taíno. Seu chefe, um sujeito chamado Hatuey, lutou contra os intrusos espanhóis da melhor maneira que pôde, mas foi derrotado e executado. Se você me perguntar, ele é o verdadeiro herói da história, enfrentando os espanhóis com paus e pedras ou algo assim!",
"Parece um homem corajoso.",
"Ha! Ele certamente estava. Quando ele estava prestes a ser executado, lhe perguntaram mais uma vez se ele queria ir para o céu. Hatuey perguntou, se os espanhóis vão para o céu, o padre espanhol disse que sim. Então Hatuey respondeu que preferia ir para o inferno, para fugir dos espanhóis! Esse é o meu tipo de cara...",
"Ha-ha, sim, eu pude ver você se dando bem com ele!",
"De qualquer forma, desde então, #sisland_Cuba# tornou-se a potência espanhola que é hoje. Especialmente depois que os corsários franceses atacaram, queimaram e saquearam #sSantiago# e #sHavana# consecutivamente há cerca de vinte anos. Os espanhóis reconstruíram as suas fortalezas, duplicaram as suas tropas e têm estado muito vigilantes e sem humor desde então.",
"Quer dizer, é melhor tentarmos nos dar bem com os habitantes locais quando ancorarmos em #sSantiago#.",
"Exatamente. E não queremos tentar fazer desvios por terra. Se a 'Villa de Málaga' estiver no porto, é melhor não perder tempo e ir para lá o mais rápido possível.",
"Entendo... E Blaze?",
"Sim?",
"Você é um grande historiador, ha-ha!",
"Talvez eu seja. Mas para você, serei sempre o mesmo velho bêbado e canalha podre, pequena Bea!",
"Não me ligue...!",
"Mas a 'Villa de Málaga' está, pelo menos, no porto. Agora só precisamos encontrar o navegador dela e pegar o mapa de volta!",
"Instruí um membro da tripulação a bisbilhotar um pouco. Onde ele está, afinal? Ele já deveria estar de volta.",
"Vamos então para a taverna e encontrar aquele desgraçado!",
"Espere um minuto, Blaze. Se nós três o confrontássemos, levantaríamos suspeitas, ou até mesmo nos colocaríamos em apuros. Acho que dois de nós deveríamos ficar aqui.",
"Hum, se você pensa assim. Devemos tirar palitinhos?",
"Eu mesmo faço isso!",
"É sua culpa que estejamos aqui, Blaze! Você vai.",
"Bonnie provavelmente tem um truque na manga para fazê-lo entregar o mapa.",
"Felicidades por isso!",
"Blaze, guarde o rum agora mesmo! Não foi isso que eu quis dizer quando disse 'celebrar'.",
"Acalme-se, Capitão Spoilsport, nós... Ei! Essa garrafa é minha!",
"Você recupera mais tarde!",
"Pequena Bea, sente-se e entre no jogo! Mas estou avisando, estou com sorte agora. Ha Ha!",
"Não me chame assim! O que você pensa que está fazendo, jogando fora o dinheiro do nosso navio?!",
"Irmã - Por que você sempre assume o pior de mim? Acabei de te dizer: estou com sorte!",
"Oh sim?",
"Ver? Afinal, não é um cara tão mau!",
"Oh. Quanto você ganhou?",
"20.000 moedas de ouro espanholas! Isso deve ser suficiente para reabastecer o navio antes da nossa próxima viagem. Mas para ser justo, quando se trata de cartas esses dois não sabem a diferença entre a frente e o verso. Ha Ha!",
"Muito bem. Você venceu desta vez, Blaze. Mas percam os idiotas, temos coisas para discutir. Vou convidar você e nossa irmãzinha vestida para matar para uma bebida.",
"'Capitão E'... Você acha que era o próprio nosso pai?",
"Parece que sim para mim. É uma história estranha e mostra quão pouco sabemos sobre ele e o que aconteceu depois que ele partiu.",
"Mas eu me lembro quando ele foi embora. Éramos crianças, parados no cais, acenando para nosso pai a bordo de um navio em que ele embarcou com promessas de dinheiro para nossa pobre família. Então ele foi engolido pela névoa do mar e nunca mais ouvimos falar dele.",
"Eu me lembro disso também. É parte da razão pela qual fui a Lisboa e me juntei a esta expedição. Para descobrir o que aconteceu com ele no novo mundo. Mal sabia eu que em breve estaria envolvido até o pescoço em enigmas e vagos mapas do tesouro!",
"Bem, é parte da razão pela qual eu vim aqui também...",
"Chama! Você me surpreende! Sempre pensei que você fosse para o mar por dinheiro fácil e mulheres rápidas!",
"Garotas! Típica! Obviamente, isso é assunto de homem. Por que vocês dois não aproveitam um tempo de garotas com café e torta enquanto eu vou para a selva e encontro o eremita. Não há problema para mim!",
"Ah, entendo, você é muito corajoso e prestativo, Blaze. Tudo bem, já que você sabe tudo e pode fazer tudo, deixamos tudo com você. Estamos tão aliviados por nos conhecermos em segurança em suas mãos viris. Vamos, Bonnie.",
}
