string DLG_TEXT[66] = {
"Isso tudo é tão emocionante!",
"Oh! É isso?",
"Oh! ",
" Estou muito feliz em finalmente conhecê-lo. Papai me contou muito sobre você. Minha irmã mais velha, finalmente aqui!",
"Estou feliz em conhecê-la também, Bonnie. Mas o que é essa parte da irmã mais velha? Eu pensei que éramos gêmeos?",
"Nós somos, nós somos! Mas você nasceu um minuto antes de mim! Então isso faz de você minha irmã mais velha! Ha! Ha!",
"Ah! Eu vejo. Estou feliz por termos resolvido isso. Isso então me coloca no comando. Ha! Ha! Então temos um tesouro para encontrar... Você está pronto para a aventura?",
"Oh! Sim. Estou esperando há dias você chegar aqui. Quando partimos e para onde vamos?",
"Bem... aqui diz no mapa que devemos navegar até a ilha #sisland_Turks# e procurar o pirata Short Jack Gold, e perguntar se ele sabe alguma coisa sobre a neve suja! Isso parece um pouco estranho.",
"É código, é código! Tem que estar em código. Vai dar certo quando chegarmos lá você verá.",
"Espero que você esteja certo, ou vamos parecer muito estúpidos, indo até um pirata e perguntando sobre neve!",
"Não se preocupe tanto ",
"! Tudo vai dar certo, sempre dá. Quando é que vamos navegar?",
"Assim que eu verificar as provisões e equipamentos, poderemos partir. Assim que estivermos fora da vista de terra, devemos lembrar de hastear a bandeira pirata para podermos pousar na Ilha #sisland_Turks#.",
"Olhe olhe! Eu disse que era código. Oh! Isso está ficando mais emocionante a cada minuto! E veremos Blaze!",
"Acalme-se, acalme-se! Ainda não o encontramos. [PENSA:] Irmãzinhas!",
"Aqui estamos - #sisland_Turks# Ilha! Rapaz, que emocionante é isso! Aposto que podemos encontrar alguns piratas de verdade aqui.",
"Sim, é por isso que precisamos tomar cuidado, Bonnie. Enviei um membro da tripulação na frente para descobrir onde está aquele Short Jack Gold.",
"Enquanto esperamos por ele - Conte-me como você foi parar no novo mundo, Beatrice!",
"Bem, essa é uma história bastante complicada, Bonnie. Mas vou contar. Tudo começou há cerca de um ano, eu estava no cais de Bristol, quando de repente...",
"Nossa, esse deve ser o paraíso dos piratas sobre o qual Short Jack Gold nos contou. Pelo menos não há neve...",
"Perguntaremos se alguém viu Blaze, mas com cuidado.",
"Você acha que é o navio de Blaze, Beatrice?",
"Parece um barco de contrabandista... Vamos remar e examiná-lo.",
"É um barco de contrabandistas! Aí está a carga empilhada: Barris de cachaça! Mas parece que alguns deles foram abertos... E nem uma alma no convés!",
"Tenho a sensação de onde isso vai levar. Siga-me abaixo do convés, Bonnie! Acho que você pode conhecer nosso irmão.",
"Olá Blaze, é verdade! Eu sou sua irmã Bonnie! Estou feliz em conhecê-lo, desculpe por não estar se sentindo bem hoje!...",
"Não o encoraje, Bonnie...",
"...Beatrice e eu estávamos procurando por você por causa do tesouro! Temos uma parte do mapa e gostamos que você participe da nossa busca!",
"...",
"Isso correu suave como a seda! Nosso porão de carga está vazio e nossa carteira cheia!",
"Exatamente, e isso significa que podemos nos concentrar no que é realmente importante: O mapa do tesouro! Blaze, entregue seu pedaço do mapa para que possamos juntá-los e ver aonde o mapa nos leva!",
"Não se preocupe, Beatriz! Vamos encontrar aquele oficial do navio e recuperar o mapa!",
"Seu otimismo está à venda, Bonnie? E você, Blaze, você realmente fez seu próprio cérebro andar na prancha, o quê?",
"Nossa, essa cidade é... Grande!",
"Eu sei direito? Uma viagem por todo este lugar levaria um século!",
"Lembra da última vez que esperamos por um tripulante? Você estava prestes a me contar como foi parar no Caribe!",
"Certo, não consegui terminar a história. Como eu disse, eu estava no cais em Bristol, cuidando da minha vida, e então, do nada... Deixa pra lá, acho que aí vem nosso tripulante!",
"Nós temos o mapa! Nós temos o mapa!",
"Sim, temos, Bonnie, e é um motivo para comemorar. Mas não há razão para gritar tão alto que desperte metade da cidade!",
"Ah, vamos juntar as duas peças do mapa e ver onde podemos encontrar o tesouro do Pai!",
"Essa é a minha maneira de comemorar também! Vejamos, tenho um pouco de cola aqui...",
"O que isso diz? Existe um grande 'X' vermelho que marca onde encontramos o tesouro?",
"Bem, na verdade... Existem vários X's grandes e vermelhos, todos em ilhas diferentes! Vejo um em #sisland_Hispaniola#, este aqui fica em uma pequena ilha aparentemente chamada #sisland_Cayman#... Ah, e o terceiro fica perto do continente, em uma ilha chamada #sisland_Aruba#. E todos eles têm um nome próximo a eles!",
"O que?! Três 'X's? O que isto significa? Apenas um deles é o local do tesouro? O que há com os nomes?",
"Não sei, mas só descobriremos se formos lá! E talvez procure as pessoas nomeadas no mapa... A mais próxima fica em #sisland_Hispaniola#, perto da cidade de #sSanto Domingo# como parece. Vamos começar nossa busca por aí!",
"Mais um dia, mais uma aventura, mais uma grande cidade no Reino da Nova Espanha!",
"Sim, o primeiro assentamento europeu no novo mundo, como se costuma dizer. Encontrar um homem chamado Marcel Jauri neste lugar poderia ser difícil. Aliás, nome estranho. E estranhamente familiar. Vamos torcer para que ele seja bem conhecido por aqui.",
"Por onde começamos?",
"Na taberna, claro! E não, Blaze, não vamos parar para tomar uma bebida!",
"Boa sorte, Beatriz! Esperaremos aqui por você!",
"Obrigado, Bonnie. Estarei de volta antes que você perceba!",
"Olá Beatrice, você gostou do novo visual? Fui fazer compras com a Lorena e encontramos uma coisa chamada 'tintura de cabelo'...",
"Muito bom, Bonnie. Mas, por favor, não saia assim!",
"Sinto muito, mas você ficou lá por muito tempo e ficou chato! Ei! Como foi? Você descobriu algo novo sobre o tesouro?",
"Espere aí - não quero explicar tudo duas vezes. Então, onde está aquela mancha de rum na nossa árvore genealógica?",
"Na taberna!",
"Onde mais?",
"Outro mapa com ainda MAIS marcadores? Cinco deles? Não faz sentido para mim!",
"Devo admitir que parece um jogo complicado o que se joga aqui...",
"Eu gostaria de estar com vocês dois naquela época! Só ouvi histórias do tio Manny. Sobre você, sobre nosso pai. Mas o que devemos fazer com todos esses mapas agora? Qual é o plano?",
"'Para encontrar o lugar você pesquisa o mais rápido possível'... Isso não ajuda muito. Acho que a nossa melhor pista ainda é perseguir os nomes do nosso mapa do tesouro combinado. Encontramos Marcel Jauri, então por que não encontraríamos os outros dois também? Talvez eles possam trazer alguma clareza a todo este assunto.",
"Isso também parece um plano para mim! Vamos fazer isso e ver que tipo de aventura nos espera desta vez!",
"Eu também acho. Vamos fazer uma visita aqui: O mapa mostra o nome Killian O'Byrne em #sisland_Cayman#. Esta será a nossa próxima parada. O marcador não é muito preciso num mapa desta escala, acho que deveríamos encontrar primeiro um mapa de toda a ilha e compará-lo com aquele com os nomes.",
"Eeeh, cobras! Nós realmente temos que fuçar na selva? Este homem não pode vir até nós de alguma forma?",
"Devo admitir que não parece particularmente convidativo. Talvez este eremita seja um pouco... estranho, depois de viver sozinho na floresta por tanto tempo.",
};
