string DLG_TEXT[18] = {
"Capitão! Aquele Short Jack Gold que você está procurando? Bem, perguntei por aí e disseram que ele está na Câmara Municipal.",
"Obrigado, marinheiro.",
"Também dizem que ele está em uma reunião importante e...",
"Não quer ser incomodado? Pois bem, vamos esperar.",
"Ah, não, eles dizem que ele definitivamente quer ser incomodado e agradece qualquer distração daquela reunião!",
"Tudo bem então, iremos vê-lo.",
"Navio à vista, Capitão! Há um pequeno veleiro à deriva perto da costa daquela ilha. Parece-me bastante abandonado.",
"Muito bem, marinheiro, pode voltar ao seu posto.",
"Apresentando-se para o serviço, Capitão.",
"Por que demorou tanto?",
"Perdoe-me por dizer isso, capitão, mas este lugar não é exatamente uma vila de pescadores.",
"Certo, certo, vejo que você está sem fôlego... Mas você ouviu alguma coisa sobre a tripulação do 'Villa de Málaga'?",
"Eu tenho, capitão. A tripulação está de licença, é o que dizem, e se você está procurando um oficial, seu melhor endereço seria a taverna.",
"Muito bem, marinheiro. Vá tomar um grogue ou algo assim.",
"Apresentando-se para o serviço, capitão.",
"Marinheiro! Onde estão meus irmãos?",
"Eles voltaram para a cidade, senhora. Senhorita Bonnie disse algo sobre comprar roupas. E o senhor Blaze encontrou algumas pessoas num jogo de cartas.",
"Aaarrgh, típico! Não posso deixar esses dois sozinhos por cinco minutos! Muito bem, vou encontrá-los. Volte para o navio, marinheiro. Eehm... Limpe minha cabana, ou algo assim!",
}
