string DLG_TEXT[27] = {
"Espere - posso saber quem você é e o que faz no meu quarto, Señorita?",
"Espere - posso saber o que VOCÊ está fazendo aqui? Você não é o noivo?",
"Bem, sim...",
"Então por que você está aqui, sozinho? Por que você não está com seus convidados?",
"Isso... eu não... Por que você não me pergunta? Não é...",
"Vamos, você pode me dizer.",
"É... Você é linda.",
"Obrigado! Mas você está mudando de assunto...",
"Por favor. Vamos esquecer isso. Tome uma taça de vinho comigo enquanto estiver aqui, certo?",
"Olha, senhor, eu realmente não o conheço. Caramba, eu nem sei como acabei aqui. Mas talvez eu possa ajudá-lo. Por que você não tenta?",
"Uma taça de vinho? Bem, não posso dizer não a isso!",
"...e então prendi os dois na hora e disse 'Você mexeu com o espanhol errado, perros sarnosos!'",
"Parece emocionante! Posso reabastecer?",
"Aí está, querido. Agora me conte sobre você. Conte-me sobre os navios em que navegou, as ilhas que explorou, as batalhas que travou... Os homens que você amou.",
"Uau! Você está com ciúmes, jovem espanhol?",
"Não! De jeito nenhum! O ciúme não é algo que um orgulhoso guerreiro espanhol permita! Talvez com um pouco de ciúme... Mas só dos homens.",
"Oi, oi... Se estou corando agora, a culpa é do vinho!",
"Você é um pequenino convincente, não é? Pois bem, para ser sincero: não gosto deste casamento. Não gosto da rapidez com que tudo aconteceu entre mim e Isabel. Não gosto de como meu pai se orgulha disso, como se eu fosse seu cavalo de circo. E não gosto da maioria dos meus convidados. Kofi Macchiato é o pior.",
"Você já tentou conversar com seu pai sobre isso? Ou sua esposa?",
"Bem... Não. Não parecia que eu tivesse muito a dizer em tudo isso. E tive medo de desagradar Isabel. Ela parece tão feliz com tudo.",
"Se me permite dar um conselho: abandone as pretensões. Isto deve ser sobre a sua felicidade em primeiro lugar. Se você se sentir desconfortável com alguma coisa, converse com seu pai. E fale com Isabel! Seu pai não deveria ditar suas ações, mas ela também está envolvida neste casamento.",
"Talvez você esteja certo...",
"E mesmo que você sinta que não gosta dela o suficiente - fale! Pode doer no início, mas seria a coisa certa e honesta a fazer.",
"Ah, eu gosto dela! É só que... As circunstâncias parecem um pouco erradas no momento. Quase parece que preciso conhecê-la melhor primeiro.",
"E tenho certeza que ela respeitará isso!",
"Obrigado, moça. Você falou com sabedoria. Sinto-me muito melhor agora!",
"Então não vou mais incomodar você. Pense no que eu te disse! Desejo a todos o melhor.",
}
