string DLG_TEXT[20] = {
"Disseram-me que você fez um grande esforço para solicitar uma audiência. Meu nome é ",
". Agora, por favor, diga-me o propósito da sua visita ",
".",
"Na verdade, simplesmente entrei pela porta da frente. Meu nome é Blaze Devlin.",
"Ah, ah, ah. E qual é o seu pedido?",
"Um navio pirata francês foi avistado, circulando pela ilha.",
"Eu vejo. Seu relatório é devidamente anotado e apreciado. Aproveite ainda mais sua estadia em #sGrand Cayman#. Bom dia.",
"Isso é tudo? O que você vai fazer a respeito da ameaça?",
"Isto não é exatamente uma ameaça, meu jovem. Pela nossa experiência, os piratas não demonstram muito interesse na colônia de #sGrand Cayman# ou em seu transporte. Provavelmente apenas fazem uma parada no outro lado da ilha para reabastecer o abastecimento de água. As pessoas do nosso assentamento não estão ameaçadas por isso.",
"Mas muito provavelmente irão saquear os navios espanhóis mais ricos da região!",
"Isso, por outro lado, pode ser, e é por isso que enviarei um mensageiro de emergência para #sRedmond# e #sHavana# para ficarmos particularmente vigilantes. Mas a segurança da nossa colónia não está ameaçada.",
"E Killian O'Byrne? Ele e sua filha moram no deserto de #sisland_Cayman#. Eles podem ser ameaçados pelos piratas.",
"Meu jovem, esta aqui é uma colônia espanhola, pela qual sou responsável. Nem estes... O'Byrne e sua filha bastarda são cidadãos espanhóis, nem vivem na colônia. O que significa que a segurança deles é problema deles. Eles recusam minha proteção vivendo por conta própria, e não há mais nada que eu possa fazer a respeito.",
"Engraçado, pelo que ouvi, você e seu povo os expulsaram da colônia. Parece que você tem uma relação frouxa com a verdade, não é?",
"Meu jovem, minha paciência está acabando! Eu não sou - repito - NãO sou responsável pelos selvagens que vivem nos arbustos com as formigas e os macacos selvagens! E isso é tudo que tenho a dizer sobre o assunto.",
"Engraçado de novo, porque até agora o único macaco que vi em #sisland_Cayman# está usando uma peruca e gritando na prefeitura.",
"Como ousa me insultar assim! Saia do meu escritório imediatamente!",
"Adeus.",
"Fora fora! Vou chamar os guardas! Fora!",
"Você parece um cachorro latindo.",
}
