string DLG_TEXT[47] = {
"Então você é o selvagem que matou meus homens? Isso é corajoso da sua parte. Corajoso e suicida. Sou o capitão Godefroi Bonamy do 'Pastenague'. Como você gostaria de morrer? Devemos derrubá-lo ou simplesmente atirar em você aqui mesmo?",
"Eu sou Blaze Devlin. Olha, sinto muito por ter matado seus homens. Eu simplesmente odeio todos os tipos de amotinados, e é por isso que perdi a paciência.",
"Com licença? O que você está falando?",
"* Suspiro * Veja, sou um corsário como você. Eu era capitão do 'Porky Pie' e partimos do porto de Birmingham para capturar navios espanhóis entre #sisland_Cuba# e a Flórida...",
"...",
"...então, de repente, minha tripulação decidiu se amotinar e me deixou nesta ilha esquecida por Deus. Estou morando na floresta há quase três meses.",
"Quando espionei seus homens, como qualquer um faria, e os ouvi falar sobre motim, fiquei com muita raiva! Agarrei na minha espada, o resto é história.",
"Eu não entendo nada! Por que eles deveriam falar sobre motim? Meus homens não são amotinados, senhor!",
"Acredite no que quiser, mas ouvi esses três falarem alto e bom som sobre motim.",
"Então, então! É verdade? Se for assim, então você me ajudou aqui! Ha! Eu já queria cortar você, então descobri que você se livrou dos amotinados para mim! Ha!",
"Bem, alguns dos amotinados, mas apenas três...",
"O que?! Quer dizer que há mais homens na minha tripulação planejando um motim?",
"Eles falaram sobre outros, então entendi que há mais amotinados. Não consegui ouvir nomes ou detalhes, mas pareciam mencionar um oficial encarregado da conspiração.",
"Então, então! Um oficial é o líder dos amotinados?! Isso é inacreditável! Mas quem poderia ser? É o primeiro imediato, Mad Kay Hubecher? Ou é o contramestre, Crazy Luc Helveur?",
"Como eu disse, não consegui ouvir nenhum nome.",
"Sacré Bleu! Como posso pegar os amotinados então?",
"Se me permite fazer uma sugestão: você poderia separar os dois oficiais e deixá-los trabalhar com seus marinheiros mais próximos. Em seguida, observe os grupos e veja onde um motim pode estar se formando.",
"Esta é uma excelente ideia! E você vai me ajudar! A menos que você ainda queira ser rebocado pela quilha\nVolte para a ilha, onde o primeiro imediato e seus homens já estão trabalhando no acampamento base. Veja se você consegue descobrir alguma coisa!\nEnquanto isso, ficarei no navio e ficarei de olho no contramestre e em sua parte da tripulação.",
"Entendido, pegarei um dos barcos a remo e voltarei, assim que tiver novas informações. [PENSA:] Ele é ainda mais burro do que eu imaginava!",
"Isso demorou bastante! Quase acreditei que você fugiu. Agora, você encontrou alguma coisa no acampamento?",
"Eu estava observando de perto o primeiro imediato e seus homens e não consegui perceber nenhum sinal de traição. Eles me parecem leais até os ossos, falaram muito bem de você e, para ainda mais boas notícias, encontraram um pequeno baú de ouro semienterrado no acampamento!",
"Ouro? Isso é realmente uma boa notícia. Mas comecemos pelo princípio: se o primeiro imediato é leal aos ossos, como você diz, isso não significa que o contramestre é o líder dos amotinados?",
"Essa é a minha conclusão também. Onde ele está?",
"Ele está supervisionando o trabalho no porão de carga. Eles estão deixando de lado os barris de pólvora para abrir mais espaço para a pilhagem!",
"Sem dúvida ele escolheria alguns de seus companheiros amotinados para este trabalho, para que pudessem secretamente planejar sua traição! Você tem mais homens leais a bordo?",
"Sim, meus dois servos passariam pelo inferno por minha causa. Podemos contar com eles!",
"Então pegue esses dois servos, armados e prontos! Então vamos fazer uma pequena visita aos amotinados no compartimento de carga...",
"Maluco Luc Helveur, você é um traidor e um amotinado! Agora baixem as armas ou iremos cortá-los como os porcos que vocês são!",
"...",
"Pareço que estou brincando? Homens, desembainhem suas espadas!",
"Você vai cair, maluco Luc Helveur! En garde, cochon!",
"HA-HA! Os amotinados não existem mais! O louco Luc Helveur pode apodrecer no inferno!",
"Boa luta, capitão! Isto servirá como um aviso para quaisquer futuros amotinados!",
"Agora, para a próxima coisa, você mencionou que o primeiro imediato encontrou algum ouro em terra?",
"É verdade, eles descobriram um baú semienterrado de moedas espanholas no forte abandonado.",
"Quero ver isso e felicitar o primeiro imediato pela sua descoberta, antes de receber a minha parte razoavelmente grande! Vamos desembarcar, onde você me levará a este forte!",
"Tudo bem, capitão. Me siga!",
"Leve-nos ao acampamento agora!",
"Estou tentando! Esta selva é difícil de navegar...",
"Sagrado Azul! Por que o primeiro imediato e seus homens simplesmente nos atacaram? Você me garantiu que eles não estavam com os amotinados!",
"E você acreditou em tudo que eu disse, cinco minutos depois de me conhecer? Você realmente é o rei dos idiotas, Capitão Bonamy!",
"O que? Você mentiu para mim? Cochon! Inglês imundo!",
"Você não está em uma boa posição, capitão. Todos os seus tripulantes mais valiosos faleceram em poucas horas e agora você está aqui, à mercê da minha lâmina. Mas você é o culpado por isso.",
"Você vai pagar por isso, Devlin! Desembainhe sua espada!",
"Com prazer, Capitão!",
"Onde estamos indo? Acredito que este caminho leva ao assentamento espanhol! Você deveria nos levar ao acampamento!",
"Você está certo, pegamos o caminho errado. Vamos para o outro lado.",
}
