string DLG_TEXT[50] = {
"Isso é uma surpresa, eu certamente não esperava nenhum visitante hoje. Na verdade, não espero visitas em momento algum. Mas é uma agradável surpresa.",
"Você é O'Byrne?",
"Esse é o meu nome com certeza, rapaz. Mas quem você seria, se eu não conheço nenhum rapaz ou moça por aqui que eu não conheça, mas quem me conhece? Se você sabe o que quero dizer. Você não parece um colono espanhol. Sim, você é um homem do mar, posso ver! E ainda por cima um inglês!",
"Meu nome é Blaze. E se você não conhece ninguém, talvez seja porque você vive no deserto de uma ilha espanhola esquecida por Deus?",
"Sim, você é um rapaz inteligente. Mas se você está me procurando, sabe quem eu sou, certo?\nSou um marinheiro irlandês que se ofereceu como voluntário para uma expedição espanhola! Sim, quem pensa que tal criatura existe? São mais raros que um duende, mas aqui estou! Estou com uma lesão no joelho, cortesia de um estilhaço que levei perto de #sisland_Redmond#, e foi aí que chegou a hora de me acalmar. Não me resta muito no velho país, então mais uma vez: Aqui estou!",
"Essa é uma história interessante e parece quase tão maluca quanto parece. Então você realmente é um eremita? Você mora aqui sozinho?",
"Isso deve responder à sua pergunta, rapaz! Blaze, esta aqui sou minha filha Annie, meu querido tesouro. Ela está caçando, então temos mais para morder do que peixe e aveia! Annie, diga olá para Blaze. Ele é marinheiro e se interessa por velhos eremitas, ha ha!",
"Filha, hein? Eu posso ver a semelhança.",
"Piratas franceses! Agora estamos em apuros!",
"Que negócios os piratas franceses teriam aqui?",
"Esconda-se e planeje sua próxima trapaça, eu digo! Sim, eles não estão de olho em #sGrand Cayman#, não há muito a ganhar naquela cidade idiota. Mas a costa com as suas enseadas e ilhotas é o esconderijo perfeito para atacar a navegação entre o continente e portos como #sHavana# e #sRedmond#. Talvez os franceses não sejam tão estúpidos como normalmente parecem!",
"...",
"O problema é que se eles desembarcarem na baía e montarem acampamento aqui em algum lugar, não estaremos salvos, Annie e eu. Você não acha que piratas fedorentos seriam nossos vizinhos pacíficos? Eles nos matariam de alegria ou pior! Não poderíamos sair para caçar e cortar lenha, teríamos que nos esconder aqui tremendo, esperando que não nos descobrissem. Sim, Annie e eu, podemos lutar, mas não vamos durar. Mal consigo andar com este meu joelho partido.",
"Já aconteceu algo assim antes, O'Byrne?",
"Sim, mas naquela época os piratas deixaram a ilha depois de três dias, quando uma forte tempestade veio por aqui. Mas aqueles três dias foram um inferno, vivendo à beira de ficar à mercê dos canalhas franceses. Eu digo que não teremos tanta sorte sempre",
"Mas os colonos espanhóis no assentamento não iriam acolher você? Eles não fariam nada contra os corsários?",
"Você é engraçado, rapaz. Talvez eles estejam tremendo como nós. Talvez eles acreditem que não é da conta deles, desde que os franceses não ataquem #sGrand Cayman#. E não, eles não vão nos acolher. Eles nos odeiam demais. Por que você acha que moramos aqui? Por causa do ar fresco, claro. Mas também porque os espanhóis riem de mim mancando e rejeitam minha herança irlandesa. Se há uma coisa que eles odeiam mais do que eu, é Annie. A mãe dela era uma moça espanhola da cidade, de quem zombaram desde o momento em que sua barriga começou a crescer. Quando a maldita febre a tomou, Annie e eu fomos expulsos. Preferimos não ir a esta cidade horrível.",
"Isso é terrível. Mas essas pessoas devem ter algum tipo de governador ou como chamam o figurão local. Eu vou lá agora e falo com ele.",
"Você é um bom rapaz. Francamente, não acredito que você possa convencê-lo a levantar a bunda para nós. Mas estamos felizes por você nos ajudar.",
"Eu volto em breve.",
"Você encontra o governador na prefeitura de #sGrand Cayman#. Se há alguém que pode convencê-lo, é aquele homem, Blaze!",
"Verei o que posso fazer.",
"Chama! Você teve alguma sorte?",
"Receio que o chamado governador seja tão útil quanto um buraco no casco. Estamos por nossa conta.",
"Exploda-o! Bem, pelo menos, estou feliz que você diga 'nós'. Presumo que você esteja tentando nos ajudar aqui?",
"Você está certo, vovô! Maldito seja, antes de deixar alguns piratas franceses fazerem o que e onde quiserem. Estou planejando ensinar-lhes uma pequena lição.",
"Tenha cuidado com os piratas por aí, rapaz.",
"Estarei fazendo o meu melhor!",
"Chama! Você está ausente há algum tempo! O que aconteceu?",
"Os corsários não vão mais te incomodar, isso aconteceu.",
"Rasgue-me as velas e afunde-me o navio! Eu sabia que você conseguiria! É melhor eu não perguntar como você fez isso, hein?",
"Isso é com você, velho. Mas agora podemos descobrir por que vim aqui em primeiro lugar. Seu nome está neste mapa. Espero que você tenha algumas informações para mim em troca?",
"Eu vou ficar nervoso! Sim, eu sei o que isso significa!",
"Desembucha!",
"Eu já te contei que naveguei com os espanhóis, hein?\nBem, eu estava servindo em um navio de guerra de #sRedmond#. Um pirata acabava de embarcar num navio mercante com uma carga de seda, rum e açúcar. Nossa missão era capturar esse pirata\nNós os alcançamos perto de #sisland_Redmond#, bem no momento em que uma tempestade estava se formando, e os enfrentamos na batalha. Um estilhaço atingiu minha perna. Dói demais e dói até hoje. A tempestade piorou, os piratas fugiram e eu fui levado ao mar. Quando recuperei os sentidos, fui pescado na água pelos mesmos piratas contra quem lutamos! Eles me salvaram a vida. Eu tinha certeza que eles iriam me matar! Mas vendo que eu era irlandês, eles não o fizeram. Mesmo quando descobriram, eu era da nave espanhola. Os serradores trataram-me das feridas, o intendente alimentou-me com um pouco do rum roubado. Eles cuidaram de mim até que eu recuperasse a saúde, da melhor maneira que puderam. Eu disse que queria me estabelecer em terra firme e eles concordaram. Me deixou em #sisland_Cayman# com um mosquete e suprimentos suficientes para ganhar a vida. Eles navegaram e nunca mais os vi.",
"...",
"Mas o capitão me deu um papel lacrado. Ele me fez jurar que não abriria e só entregaria quando alguém estivesse procurando. Este seria o caso quando meu nome aparecesse em um mapa. Agora suponho que esse dia chegou, né? Então aqui está. Este documento está comigo há muitos anos. Hoje você tem mais do que merecido.",
"Então suponho que todos nós saímos vencedores hoje. Obrigado pelo artigo e pela história, O'Byrne. Eu tenho que levar isso de volta para minha irmã.",
"Não seja bobo! Você acha que eu quero que minha filha passe o resto dos dias brincando na selva? Se ela tiver a oportunidade de se aventurar e fazer algo de sua vida, ela deveria aproveitá-la!",
"...",
"Sempre bons ventos para você, amigo.",
"Da mesma forma, velho!",
"Você chegou nem um segundo antes, Blaze! Se não fosse por você, esses bárbaros imundos teriam me acabado com certeza!",
"Eu fui ótimo, como sempre, mas Annie também fez a parte dela nisso, não vamos esquecer disso. Boa tentativa, Annie! Bem entre os olhos de uma posição estratégica, gosto disso!",
"É verdade então? Você lidou com o navio pirata?",
"Eu fiz, e foi uma carnificina gloriosa! Os corsários não te incomodarão mais.",
"Você se saiu muito bem, Blaze! Ai! Meu joelho! Estou ficando velho demais para esse tipo de aventura!",
"Vamos entrar então, vovô.",
"Aah, assim é melhor!",
"Mas agora podemos descobrir por que vim aqui em primeiro lugar. Seu nome está neste mapa. Espero que você tenha algumas informações para mim em troca?",
}
