string DLG_TEXT[22] = {
"Bem-vindo à nossa ilha. Por favor, diga-me seu nome.",
"Meu nome é ",
"E o que o traz à nossa bela ilha neste belo dia?",
"Senhor, estou procurando meu irmão. Ouvi dizer que ele estava aqui. Você pode me ajudar a encontrá-lo?",
"Infelizmente, querida senhora, estou na cadeira errada, no lugar errado e na hora errada. Você precisa falar com o Capitão Skull ali.",
"Oh! Eu vejo. Pensando bem, você tem um sotaque engraçado.",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
" ",
}
