string DLG_TEXT[18] = {
"Mon Dieu! Não admira que nossos batedores não tenham retornado! Esta salaud deve ter matado todos eles! Les gars, agarrem-no e nós o levaremos ao Capitão para punição!",
"...",
"Veja só, le salaud voltou! Não me diga que você agora faz parte da tripulação, assassino!",
"Você não está tão longe, na verdade. O seu capitão prometeu-me uma passagem para fora desta ilha, se eu lhe fizer um favor. Mas chegando aqui no acampamento, decidi que não posso continuar com esse esquema.",
"Do que, em nome de le Dieu, você está falando?",
"Seu capitão me pediu para garantir que você ainda esteja ocupado com o acampamento, enquanto o resto da tripulação prepara o navio. Eles querem zarpar e deixar você aqui. Mas eu não sou tão cruel, eu só tinha que te contar!",
"O que? Ele quer nos deixar aqui? Bem desse jeito? Por que ele iria querer fazer isso?",
"'Menos homens a bordo, uma parcela maior do saque para todos.' Essas foram suas palavras. Então ele me mandou desembarcar para ficar de olho em você.",
"Bordel! Para o inferno com esse bastardo! Homens, voltemos para a costa, le Capitaine nos deve uma explicação!",
"Não, pense nisso! Se te virem na costa, partirão imediatamente!",
"Hum, você pode estar certo. Mas você acha que não deveríamos fazer nada? Aceitar o nosso destino?",
"Você poderia atrair o Capitão para uma armadilha, aqui em terra. Que tal isto: eu o convenço a vir aqui mesmo, para este forte. Você e seus homens preparam uma emboscada. Você consegue sua vingança e depois o lugar dele como capitão. E porque eu te disse, você me tiraria desta ilha",
"Isso pode funcionar. Mas como convencê-lo a vir aqui, direto para essa nossa armadilha?",
"Eu poderia simplesmente dizer a ele que você encontrou um baú de ouro enterrado neste acampamento. Ele iria querer vir e procurar por si mesmo, não é?",
"Suponho que sim... Aquele bastardo ganancioso! Filho da puta! Tudo bem, temos um acordo.",
"Então você arma aquela pequena emboscada e eu trarei o Capitão Bonamy até aqui para você atacar. Não vou demorar! [PENSA:] Eles são todos tão estúpidos assim?",
"O que você está esperando? Leve le Capitaine a este acampamento e iremos emboscá-lo!",
"Paciência, meu amigo. Estou a caminho.",
}
