string DLG_TEXT[28] = {
"Ocupado, ocupado, ocupado... Ocupado, ocupado, ocupado...",
"Você parece muito ocupado!",
"Então, você acha que posso ajudá-lo em sua busca? Devo ser franco com você. Estou muito ocupado, mas acho que posso encontrar tempo para acompanhá-lo em sua busca.",
"Sim, capitão, entendo o que você está dizendo. Se eu aceitar sua ajuda com a missão, terei que pensar na maior parte.",
"Então você deve contratar comigo para conseguir minha ajuda. Lembre-se que posso ir com você. Pense bem ou fale primeiro com alguns dos outros, mas se você falar comigo novamente, estaremos contratados.",
"Sim, capitão, eu entendo.",
"Você falou comigo pela segunda vez, agora somos contratados para trabalhar juntos em sua missão. A palavra SWIM está, no código que usamos, ao contrário.",
"Quer dizer que assim como caminhar é correr, nadar seria afundar? .",
"Não, não esse tipo de reverso. Na verdade, isso seria o oposto. No SWIM reverso torna-se MIWS. Essa é a palavra codificada que devemos examinar.",
"Agora você diz isso, isso é bastante óbvio?",
"Sim, talvez seja.",
"Então, como examinamos o MIWS?",
"NÓS não. Você precisa saber o código, o que é claro que eu sei. Conheço a maioria dos códigos na hora.",
"Ah! Isso está se tornando aparente. Então, qual é o código?",
"Bem, consultando meu livro de códigos pessoal, obtemos M que significa Maximus, que significa maior. I é Interrelatus, Westus e S é Southus.",
"Maximus Intrigueus Westus Sailus... O que isso significa?",
"Isso significa, querida moça, que devemos navegar para uma grande ilha no extremo sudõeste daqui, onde encontraremos um parente seu. Um parente próximo, pelo uso da palavra 'maximus' no código.",
"Mas poderia ser qualquer uma das ilhas ocidentais. Como sabemos qual e qual parente? Eu tenho um irmão, Blaze, mas não sei onde ele está.",
"Seu pai sabia o que estava fazendo, disso tenho certeza. Por enquanto sugiro que naveguemos para #sisland_Conceicao#, onde talvez encontremos seu irmão.",
"Isso parece bastante lógico. Estaremos prontos para navegar.",
"Você está pronto para navegar então?",
"Sim, estamos prontos. Vamos para o mar.",
"Uma jornada e tanto. Certamente varreu as teias de aranha.",
"Sim, foi. O que fazemos agora?",
"Deixe-me testar minhas habilidades diplomáticas. Iremos ver o Governador.",
"Oh! Você quer dizer começar no topo e descer. Isso deve ser interessante.",
"",
"",
};
