string DLG_TEXT[28] = {
"Não dê trégua... Não faça prisioneiros...",
"Você é um pouco impiedoso, não é?",
"Então, você acha que posso ajudá-lo em sua missão?",
"Sim, capitão, por favor",
"Então você deve contratar comigo para conseguir minha ajuda. Lembre-se de que não mostro piedade. Portanto, haverá muita luta. Pense bem ou fale primeiro com alguns dos outros, mas se você falar comigo novamente, estaremos contratados.",
"Sim, capitão, eu entendo.",
"Você falou comigo pela segunda vez, agora somos contratados para trabalhar juntos em sua missão. A palavra SWIM é deliberadamente confusa. Deveria ser MWSI.",
"MWSI... mas isso não faz sentido?",
"Sim, se você souber o que significa.",
"E... presumo que sim. Isso está correto?",
"Sim, talvez eu esteja. Significa: Faça Guerra em uma Ilha Espanhola.",
"Oh! E como nós fazemos isso?",
"Ah! Não por conta própria. Precisaremos de alguns dos membros mais sedentos de sangue da irmandade para se juntarem a nós.",
"Parece que está ficando perigoso.",
"Não com o esquadrão de navios que proponho, Srta. Devlin.",
"Mas como isso nos levará ao tesouro? .",
"Isso eu não sei, mas sei que seu pai sabia o que estava fazendo. Portanto, as coisas devem vir à tona à medida que avançamos.",
"Você tem certeza sobre isso?",
"Oh sim! Muita certeza. Seu pai era um homem inteligente. Ele tinha tudo planejado, eu sei. Faça o que precisar agora, nos encontraremos no cais.",
"Isso parece muito emocionante. Vou me preparar para navegar.",
"Você está pronto para navegar então?",
"Sim, estamos prontos. Vamos.",
"Bem, devo dizer que foi uma viagem e tanto. É melhor continuarmos com o assunto em questão. Não podemos ficar aqui por muito tempo, os navios do Rei logo estarão sobre nós. Você está por si mesmo agora. Boa sorte!",
"Oh! Sim, eu entendo. Suponho que deveríamos ir à Taverna para ver o que podemos descobrir?",
"Não não! Eu tenho contatos aqui, você sabe. Fazemos parte do mesmo grupo de irmãos, por assim dizer. Você precisa encontrar XXXXXXXXXXX e mencionar meu nome.",
"Oh! Eu vejo. Bem, espero que todos vocês voltem em segurança.",
"Vamos.",
"Adeus e obrigado.",
};
