string DLG_TEXT[13] = {
"É um lindo navio, você não acha?",
"Você não é Paolo, o carpinteiro da 'Villa de Málaga'? Você precisa voltar para o seu navio, ordens do seu navegador!",
"Eu sei eu sei! Já estou atrasado... Mas só preciso estudar esta nave aqui mais um minuto. Você não vê as proporções brilhantes dos mastros?",
"Isso é um destroço, cara!",
"É, mas o design ainda é extraordinário e, como carpinteiro, posso aprender muito olhando para ele e aplicar esse conhecimento em meus próprios trabalhos no futuro.",
"Pode ser, mas você não tem tempo para isso agora.",
"Se eu tivesse algum papel comigo! Eu poderia fazer um esboço e estudar depois...",
"Tudo bem, se isso fizer você retornar ao navio mais rápido, vou pegar alguns papéis para você! [PENSA:] Onde?",
"...",
"Você encontrou um pedaço de papel!",
"Sim, agora faça o seu esboço estúpido",
"Maravilhoso, consegui fazer um esboço muito bom!",
"Parabéns. Agora volte para o navio, chop-chop!",
"",
}
