string DLG_TEXT[75] = {
"Bem-vindo à igreja, #saddr#.",
"Você não é meu pai. Não me fale assim novamente",
"Bom dia, pai.",
"Ora, seu pagão desrespeitoso! Sair! Você contamina a casa de Deus com a sua presença!",
"De qualquer forma, eu não estava planejando ficar muito tempo.",
"Que Deus abençoe você e suas ações. Você veio até mim com algum propósito?",
"Eu gostaria de fazer uma doação.",
"Estou aqui para me confessar",
"Desculpe. Eu devo ir.",
"Na verdade. Como está a paróquia?",
"Acho que a mulher de quem falamos logo voltará para a igreja.",
"A mulher de quem falámos... não consegui fazê-la mudar de ideias. Sinto muito, pai.",
"Oh! Esta é uma grande ação que você fez, #saddr#. Fico feliz em conhecer um jovem marinheiro que não se afunda no pecado como os outros.",
"Sinto muito, pai. Acontece que não tenho dinheiro.",
"Aqui estão 100 ouro pelo seu bom trabalho.",
"Eu deveria pensar que o Senhor olharia gentilmente para 1.000 moedas de ouro.",
"Estou indo bem atualmente, então darei 5.000 ouro.",
"A decisão é sua, meu #saddr#. Nunca é tarde para mudar - e tenha em mente que suas boas obras serão levadas em consideração no momento de sua morte.",
"Minha morte ainda está muito distante, se Deus quiser! Vamos falar sobre outra coisa.",
"Desculpe, pai. Eu tenho que ir.",
"Agradeço-lhe o seu presente em nome da Santa Igreja, #saddr#.",
"Preciso falar com você, pai.",
"Sinto muito, pai, mas tenho que ir",
"Agradeço-lhe o seu presente em nome da Santa Igreja, #saddr#.",
"Preciso falar com você, pai.",
"Sinto muito, pai, mas tenho que ir",
"Agradeço-lhe o seu presente em nome da Santa Igreja, #saddr#.",
"Preciso falar com você, pai.",
"Sinto muito, pai, mas tenho que ir",
"Claro, #saddr#. Estou ouvindo.",
"Eu mudei de ideia. Talvez outra hora.",
"Eu pequei, santo padre...",
"É da natureza do homem pecar, #saddr#. Mas pedir perdão é divino.",
"Sim, mas eu... saqueei navios e mandei alguns para o fundo do oceano. Eu saquei minha espada com raiva e tirei vidas....",
"Mas não havia franceses entre eles, pois não?",
"Claro que não, pai.",
"Sim, santo padre. Até os franceses.",
"Então Deus perdoa seus pecados, #saddr#.",
"Obrigado pai. Eu vou agora.",
"O que?! Deus nunca perdoará tal pecado! Saia de Sua casa imediatamente!",
"Adeus, pai.",
"Está tudo bem, #saddr#.",
"Obrigado pai. Eu vou agora.",
"O que você está dizendo? Existe alguém que não vem à igreja?",
"Está tudo bem, #saddr#.",
"Nesse caso, pai, eu irei.",
"Infelizmente, há uma garota rebelde - ela leva uma vida solitária e é impossível convencê-la a ir à igreja.",
"É uma pena, pai - mas tenho certeza que mais cedo ou mais tarde você a fará mudar de ideia.",
"Talvez seja possível conversar com essa garota e convencê-la a voltar para o rebanho.",
"Já tentei muitas vezes, #saddr#, mas sem sucesso.",
"Bem, se você não consegue convencê-la, imagino que ninguém consiga. Até a próxima.",
"Eu poderia tentar, se você quiser. Às vezes, as pessoas falam com estranhos de uma forma que nunca falariam, mesmo com o seu padre.",
"Eu ficaria muito grato se você tentasse. Essa garota mora perto dos portões que levam ao centro da cidade. O nome dela é ",
"Elzire Ayarai",
"Elzire Ayarai",
".",
"Farei o meu melhor, pai.",
"Não, #saddr#. Eu não acredito que você possa mudar alguma coisa",
"Muito bem. Adeus, então, pai.",
"Isso é uma pena, #saddr#. Para ser honesto, eu realmente esperava que você pudesse ajudar.",
"Até a próxima.",
"Ah, ela já esteve aqui. Ela até me fez anotar sua confissão e pediu perdão. E ela falou muito bem de você.",
"Estou feliz que tudo tenha corrido tão bem, pai. Até a próxima.",
"Estou com medo ",
" ouro é tudo o que posso pagar agora.",
"Eu deveria pensar que o Senhor olharia com bondade ",
" peças de ouro.",
"Estou bem ultimamente, então vou dar ",
"Mas não havia espanhóis entre eles, não é?",
"Sim, santo padre. Até os espanhóis.",
"Bom dia, pai. Ouvi dizer que um homem chamado Bonto doou um livro de põesia para a igreja. Este livro foi perdido devido a uma série de acontecimentos infelizes, pertence a um nomeado da colônia e devo devolvê-lo a ele.",
"Receio não poder ajudá-lo aqui, meu filho. Eu sei a que livro você se refere, li dele em um funeral. Gostei muito e por isso dei-o a um membro da paróquia que gostou do seu conteúdo.",
"Qual era o membro da paróquia? Preciso encontrar o livro, pai.",
"Não me lembro, criança. Por que você não pergunta à infeliz viúva sobre aquele funeral? Ela é uma mulher idosa, muitas vezes você a verá pegando água no poço perto do armazém da cidade.",
"Obrigado pai.",
};
