string DLG_TEXT[28] = {
"Tanta coisa para fazer... Tanta coisa para fazer...",
"Você parece muito ocupado!",
"Então, você acha que posso ajudá-lo em sua busca? Devo ser franco com você. Estou muito ocupado, então posso lhe dizer o que fazer, mas não posso ir com você. Você deve lidar com a missão sozinho.",
"Sim, capitão, entendo o que você está dizendo. Se eu aceitar sua ajuda com a missão, estarei sozinho em sua execução.",
"Então você deve contratar comigo para conseguir minha ajuda. Lembre-se de que não posso ir com você. Pense bem ou fale primeiro com alguns dos outros, mas se você falar comigo novamente, estaremos contratados.",
"Sim, capitão, eu entendo.",
"Você falou comigo pela segunda vez, agora somos contratados para trabalhar juntos em sua missão. A palavra SWIM está, no código que usamos, ao contrário.",
"Você quer dizer que assim como caminhar é correr, nadar seria se afogar?",
"Não, não esse tipo de reverso. Na verdade, isso seria o oposto. No SWIM reverso torna-se MIWS. Essa é a palavra codificada que devemos examinar.",
"Agora você diz isso, isso é bastante óbvio?",
"Sim, talvez seja.",
"Então, como examinamos o MIWS?",
"NÓS não. Você precisa saber o código, o que é claro que eu sei. Conheço a maioria dos códigos na hora.",
"Ah! Isso está se tornando aparente. Então, qual é o código?",
"MI significa Inscrição Memorial e WS é o nome do falecido.",
"ESTE? Poderia ser qualquer um. William Smith, por exemplo, e deve haver centenas deles nos cemitérios da ilha.",
"Ninguém. Será uma pessoa proeminente. E o único que me vem à mente é Weatherby Swann, mas é claro que ele não está morto. Ele é atualmente o Governador das Ilhas Inglesas.",
"Se ele não está morto, então que ajuda é essa?",
"Seu pai tinha um bom motivo para enviar isto, mas não sei qual é. Tudo o que posso dizer é: vá para #sisland_Redmond# e descubra tudo o que puder sobre Weatherby Swann. Você encontrará sua resposta lá, tenho certeza. Seu pai sabia o que estava fazendo, disso tenho certeza.",
"Isso parece muito emocionante. Vou me preparar para navegar.",
"Você está pronto para navegar então?",
"Sim, estamos prontos. Nós lhe daremos agradecimentos e adeus.",
"",
"",
"",
"",
"",
"",
};
