string DLG_TEXT[107] = {
"E o que você quer? Você não vê que estou tentando me divertir?",
"Sou uma mulher que vai direto ao ponto, #sSenor#...",
"Rocoso Balboa, primeiro navegador da 'Villa de Málaga'",
"...#sSenor# Balboa. Você está de posse de um fragmento de um mapa do tesouro, que ganhou em um jogo em #sGreenford#. Eu gostaria de ter isso. Como entramos no negócio?",
"Você está muito bem informado, #sSenorita#...",
"Beatrice Devlin, capitã do '",
".",
"...Capitão Devlin. Suas informações estão corretas. Não sei como você soube disso, mas sim, possuo esse documento. E isso pode ser generoso, na verdade muito generoso da minha parte, mas pode ser o seu dia de sorte.",
"Como assim?",
"Porque, considerando todas as coisas, não tenho muita utilidade para este mapa. Primeiro: está despedaçado e incompleto, como você já sabe. Segundo: sou oficial de um navio de tesouro, como você também sabe. Isto significa que não tenho tempo, recursos ou liberdade em geral para ir à caça de tesouros com base em informações tão vagas e fragmentadas. Então, sim, podemos entrar no negócio.",
"Ligue para o preço então, #sSenor# Balboa.",
"Um homem sábio obviamente exigiria uma parte do tesouro no futuro. Mas não tenho nenhuma garantia aqui, provavelmente nunca mais verei você e, pelo que sei, tal tesouro pode até nem existir. Então, se você quiser aquele pedaço de papel que ganhei daquele bêbado em #sGreenford#, tudo que peço é um simples favor. Algo que me seja útil neste momento.",
"Fale então, #sSenor# Balboa.",
"Nossa licença em terra está quase acabando e sou responsável por levar cada homem de volta ao navio a tempo. Mas ainda há cinco marinheiros à solta em algum lugar. Não consigo encontrá-los e afinal quero terminar esta taça de vinho no tempo que resta. Se você encontrar todos os cinco marinheiros desaparecidos e mandá-los de volta ao navio, você receberá seu pedaço de papel. Eles poderiam estar em qualquer lugar da cidade ou área portuária.",
"Isso parece bastante fácil. Apresentarei um relatório a você assim que amarrar seus homens.",
"Posso obter uma descrição dos marinheiros desaparecidos?",
"Bem, lá está o Juan, ele é um bebedor e um malandro, estou surpreso que ele não esteja aqui na taverna. Jorge, por outro lado, costuma ser um bom homem, dócil e temente a Deus. Pedros é um sedutor, um mulherengo. Ricardo adora aventura e atividades ao ar livre, é botânico amador. E claro Paolo, o carpinteiro do navio.",
"Você já encontrou todos os marinheiros?",
"Não, estou trabalhando nisso.",
"Todos os marinheiros foram presos e mandados de volta ao navio!",
"Excelente! Onde quer que eles estivessem vagando... De qualquer forma, você me salvou de muitos problemas.",
"Agora não esqueça que temos um acordo!",
"Certo... O mapa do tesouro. Bem, você verá que sou um homem que mantém sua palavra! Aqui, pegue este pedaço de papel... Desejo-lhe boa sorte com isso.",
"Tenho certeza que vou querer isso!",
"Olá! Eu sou Bonnie. Você não é...?",
"Certo! Bem, na verdade estou tentando me divertir também! Você se importa se eu tomar uma taça daquele vinho com cheiro delicioso?",
"Não de todo querida! Como oficial, não quero me juntar aos marinheiros comuns na taverna. Mas a companhia de uma senhora é sempre bem vinda!",
"Estalajadeiro, vou querer o que ele tem!",
"...você deve saber, Diego Velázquez de Cuellar veio para o novo mundo com Colombo. Mas ele ficou para se tornar um herói por direito próprio!",
"Você quer dizer quando ele se tornou o fundador desta cidade?",
"Esta é certamente uma razão. Na verdade, cada vez que chegamos a #sSantiago#, sinto que a presença dele ainda persiste. Imagine: há cinquenta anos, toda a ilha era selvagem e vazia. Foi a expedição de Velázquez de Cuellar que derrotou os Taíno, explorou as terras e construiu os primeiros assentamentos. Um dos quais logo se transformou nesta bela cidade que vemos hoje!\nPortanto, são homens como ele, e suas realizações, que me deixam orgulhoso de ser espanhol e especialmente orgulhoso de servir a coroa espanhola!",
"Isso inclui homens como Hernan Cortes?",
"Cortes acabou se tornando dono de si também, mas quando a presença espanhola foi estabelecida em #sisland_Cuba#, ele era apenas um assessor de Velázquez de Cuellar. A expedição de Cortés ao continente é outro assunto, mas esta noite é o grande conquistador e governador Velázquez de Cuellar que quero comemorar!",
"Vamos levantar nossas taças então! Para Diego Velázquez de Cuéllar!",
"Para ele! E à coroa da Espanha e a todos os homens que a servem bravamente! Para aqueles que dão o seu sangue e suor na conquista do novo mundo!",
"Saúde!",
"Eu normalmente não bebo... Soluço! Muito. Mas p-pssst, é um segredo!",
"Quem poderia resistir a este delicioso vinho?",
"Você deve saber que ganhei este mapa do tesouro aqui de um homem que estava consideravelmente mais bêbado! Mas falta uma parte do mapa. É tão inútil como um marinheiro português!",
"Uma última recarga?",
"[CANTANDO:] ...mas antes que você morra, meu querido!...",
"[CANTANDO:] ...tome um último copo de cerveja!...",
"Soluço! Agora estou farto! Devo voltar para o navio. Me ajude... Soluço! Encontre-o. Está no oceano och-oshe!",
"Eu sei onde é, eu vou junto!",
"[CANTANDO:] Quinze baús em uma garrafa de rum, Yo-Ho-Ho...! N-não, não é assim que a música diz!",
"Calma aí, amigo. Deixa eu te ajudar, você mal consegue andar, oi-oi!",
"O-obrigado, você é muito gentil... Talvez Alchristy! Esse é o meu C-capitão ali! Ele não deve... Soluço! Veja-me assim!",
"Tarde demais, ele está vindo para cá!",
"Rápido, entre lá antes que ele te veja!",
"Cometi o pior erro da minha vida! Eu nunca deveria ter bebido! Nem uma gota de vinho!",
"Calma, meu rapaz! Nós nos divertimos muito esta noite, não foi? Trazendo um pouco de vida para a taverna, incomodando os guardas, cantando canções do mar... E para deixar o melhor para o final: Você nem será punido!",
"Eu... eu não vou? Mas a lei exige que eu seja enforcado na forca de #sSantiago# a qualquer momento!",
"Digamos apenas que convenci Dom Evaristo a lhe dar outra chance.",
"Você fez? Garota, você salvou minha vida! E eu quero dizer isso! Como posso retribuir-te?",
"Oh! Calma aí, grandalhão! Você está me esmagando.",
"Perdoe-me, estou tão animado! Há um minuto eu estava preparado para ver o rosto do meu criador!\nQuer saber? Pegue isso. Este papel me foi dado por um marinheiro bêbado em #sGreenford#, ele alegou que fazia parte de um mapa do tesouro. Talvez isso o leve a um verdadeiro tesouro. E se não der, leve como lembrança de ter salvado uma vida!",
"Isso é muito gentil da sua parte, amigo. Agora vou deixar você em paz. Você não enfrentará seu criador amanhã, mas certamente enfrentará uma ressaca, ha ha! [PENSA:] Eu tenho o mapa! Os outros ficarão emocionados!",
"Cometi o maior erro da minha vida! Assim que o Capitão me encontrar, vou enforcar!",
"Ele, quem diria que os escritórios do estaleiro ainda ficam abertos até tão tarde? O chefe dos trabalhadores provavelmente se esqueceu de trancar.",
"Você não vê o quão desesperado estou? Estou tremendo nas botas aqui! Não consigo mais sentir aquele temido vinho, que eu nunca deveria ter tocado!",
"Respire fundo. Tudo o que você precisa fazer é voltar furtivamente para o navio sem que ninguém perceba! Eles não podem provar que você bebeu. Contanto que você esteja na sua rede da próxima vez que alguém te ver, você está seguro!",
"E como devo conseguir fazer isso? É um longo caminho até o navio e certamente estão me procurando por todos os lados!",
"Você está certo, seu capitão disse algo sobre colocar guardas na estrada. Espere aqui, vou lá fora e ver se consigo encontrar uma maneira segura de você embarcar.",
"O que vou fazer, o que vou fazer...",
"Você apenas fica parado e espera por mim!",
"Você vai voltar furtivamente para sua nave. Não se preocupe, a costa está limpa. Enviei seus companheiros de tripulação em uma busca inútil.",
"Você fez? Muito obrigado! Você pode ter salvado minha vida, e não digo isso levianamente.",
"Não perca tempo, não sabemos quanto tempo esses cães de guarda irão embora.",
"Isso tudo é um pouco embaraçoso para mim, você sabe. Você me vendo entrando nessa situação. Apenas lembre-se de que estou verdadeiramente grato. Quer saber? Pegue isso. Este papel me foi dado por um marinheiro bêbado em #sGreenford#, ele alegou que fazia parte de um mapa do tesouro. Talvez isso o leve a um verdadeiro tesouro. E se não der, leve como lembrança de ter salvado uma vida!",
"Obrigado por isso, estou muito curioso sobre isso. [PENSA:] Eu consegui! Eu tenho o mapa! Mal posso esperar para mostrar Beatrice e Blaze!",
"Você vai vestir esta capa que encontrei! Vamos, coloque-o!",
"Não vou parecer ridículo com essa coisa?",
"Olha, #sSenor#: Primeiro, paguei 25 moedas de oito por isso, segundo, é para ser muito confortável e, terceiro, é o disfarce perfeito para passar despercebido pelos cães de guarda que seu capitão colocou na estrada do porto. Então, espero um pouco mais de entusiasmo aqui.",
"Tudo bem, tudo bem. Acho que não tenho nada a perder.",
"Experimente!",
"Bem, como estou?",
"Bonito e confortável! Esses cães de guarda não irão reconhecê-lo. Vamos, vamos levá-lo para o navio!",
"Nem é tão confortável, você sabe.",
"Psiu! Fique quieto.",
"Ha! O estratagema funcionou! Esses dois nunca foram os mais brilhantes. Tudo o que podem fazer é beber e seduzir mulheres!",
"Sim, isso foi surpreendentemente fácil. Agora você pode entrar furtivamente a bordo e fingir que nada aconteceu.",
"Farei isso imediatamente, mas primeiro deixe-me dizer o quanto estou grato por você me ajudar! O Capitão teria me massacrado!\nQuer saber? Pegue isso. Este papel me foi dado por um marinheiro bêbado em #sGreenford#, ele alegou que fazia parte de um mapa do tesouro. Talvez isso o leve a um verdadeiro tesouro. E se não der, leve como lembrança de ter salvado uma vida!",
"Balboa é o nome, certo? Lembre de mim?",
"Não, eu não. O que é isso? Você está procurando aluguel? Nesse caso você não irá longe, posso garantir isso.",
"Resposta errada, covarde. Tente novamente. Desta vez, dê uma boa olhada em mim primeiro e pense bem.",
"Espere um minuto! #sGreenford#, certo?",
"Demorou bastante!",
"E o que você quer?",
"O que você acha? Quero minha propriedade legítima de volta. Agora mesmo, por favor",
"Ha! Você está nervoso! Você é um inglês obviamente desempregado que vem para a Nova Espanha. Bêbado e mal conseguindo ficar em pé, você começa a convencer um oficial da coroa a jogar cartas, oferecendo apenas um pedaço de papel que você chama de 'mapa do tesouro da sua família'. Você tenta trapacear, mas ainda perde\nE agora aparece aqui em #sSantiago#, exigindo aquela coisa de volta? Ha! Sua audácia quase me impressiona! Agora saia, antes que eu chame os guardas!",
"Olhe, senhor, podemos resolver isso da maneira mais fácil ou mais difícil. Você prefere um duelo honroso para decidir quem fica com a satisfação... e o mapa?",
"Um duelo? Hum... claro! Ehm... Em nome da Espanha defenderei minha honra com esta lâmina aqui!",
"Finalmente! Pague e saia!",
"Bem, ehm... acho que este lugar serve. Você ainda quer fazer isso? Quero dizer...",
"Você quer desistir? Você já está com medo?",
"Não, claro que não! Eu só... Aaah, esqueça! Pelo poder da Espanha e em nome de ",
", vou te ensinar uma lição! Você vai ceder, Devlin!",
"Mal posso esperar... Desembainhe sua espada, covarde!",
"Isso é um grande NãO da minha parte!",
"Ei! O que você pensa que está fazendo? Volte aqui! Covarde! COVARDE!!!",
"Você... Você salvou minha vida!",
"Não voluntariamente. Ainda não terminamos, Balboa!",
"Ah, sim, estamos, por favor! Pegue seu mapa. Aqui, pegue. Mas não me machuque! Você estava certo, eu sou um covarde. Sou o maior covarde da frota do tesouro! E cansei de lutar, e por isso cansei de fingir ser algo que não sou!",
"Nunca acreditei por um segundo que você fosse outra coisa senão um covarde miserável, Balboa!",
"Eu sei. Eu não sou um lutador. Tenho medo de espadas, medo de lutar. Mas eu não ousei admitir isso, e só esperava que você de alguma forma deixasse isso acontecer\nMas quando percebi que era tarde demais e o duelo começou, e então quando aqueles bandidos apareceram, fiquei com tanto medo! Você pode pensar em mim como um verme e estaria certo.\nMas, por favor, vamos esquecer tudo, você pega o mapa e seguimos caminhos separados. Isso é constrangedor para mim, mas não me importo. Eu só quero viver!",
"Tudo bem, seu bebê chorão. Entregue-o e saia da minha vista neste instante.",
"Você me deixa doente, Balboa. Você fala alto, fala o nome do seu rei, mas não merece se chamar de homem, seu verme covarde. Vou aliviar este mundo da sua existência miserável!",
}
