string DLG_TEXT[24] = {
"Bem-vindo à nossa ilha. Por favor, diga-me seu nome.",
"Meu nome é ",
"E a que devemos o prazer da sua companhia neste belo dia?",
"Estou à procura do Capitão Short Jack Gold, senhor. Você pode me ajudar a encontrá-lo?",
"É assim mesmo? E por que você estaria procurando por ele? Você não o conhece, conhece?",
"Não, senhor, não tenho, mas tenho uma carta do meu pai que diz que o Capitão Gold poderia me ajudar em um assunto de alguma importância.",
"Entendo.. E quem é seu pai?",
"Meu pai faleceu. Seu nome era Eugene Devlin.",
"Ah! Eugene Devlin.. Sim, eu o conheço, ou melhor, o conheci. Bem, capitão, isso muda as coisas. Eu sou o Short Jack Gold que você está procurando, em que posso ajudar?",
"Capitão Gold, isso vai parecer muito bobo, mas a carta do meu pai me diz para perguntar se você poderia me mostrar um pouco de neve suja. Aqui você pode ler.",
"Ha! Ha! Ha! Realmente faz isso! Aquela velha raposa Eugene, tão astuta como sempre! Mas fiel à sua palavra.",
"Senhor! É do meu pai que você fala, e eu pediria que você mostrasse mais respeito.",
"Acalmar. Não quero desrespeitar seu pai. Na verdade, honro a sua habilidade em transmitir uma mensagem tão importante de uma forma tão simples.",
"Mensagem importante? O que você quer dizer?",
"Há muitos anos, seu pai encontrou um vasto tesouro... Parece que ele lhe enviou a localização, escondida neste mapa.",
"Mas o mapa está rasgado! Onde está a outra parte?",
"Seu pai deve ter enviado uma segunda mensagem com o restante das informações, então se uma mensagem fosse interceptada, não ajudaria sem a outra. Agora, para quem seu pai poderia ter enviado cartas? Obviamente, dentro da família, ele não teria confiado em mais ninguém.",
"Bem, eu, minha irmã Bonnie... e... meu irmão Blaze...",
"Então aí está. Sua irmã não recebeu nada, caso contrário ela teria lhe contado, então é seu irmão Blaze que você precisa encontrar para completar o quebra-cabeça. E esta nota aqui diz onde você deve procurá-lo.",
"Como assim?",
"A neve! Existe uma pequena ilha nas Pequenas Antilhas, que os espanhóis chamam de #sisland_Quebradas Costillas#. Significa 'Nossa Senhora das Neves'. E o seu lado 'sujo' fica na costa õeste, que é um notório esconderijo de contrabandistas e piratas...",
"Quando soube como era simples... acho que tenho muito que aprender! Obrigado, Capitão Ouro!",
"Não há nada a agradecer, senhorita Devlin. Não, vá procurar seu irmão e boa sorte para você.",
"Ah, eu vou, Capitão Gold!",
}
