string DLG_TEXT[41] = {
"Sinto que te conheço desde sempre",
"Er... Obrigado. Eu penso...",
"Eu ouvi, eu ouvi. Eu não estava dormindo. Então você precisa saber o significado de SWIM, não é?",
"Sim, senhor Christopher, por favor",
"Então você deve contratar comigo para conseguir minha ajuda. Pense bem ou fale primeiro com alguns dos outros, mas se você falar comigo novamente, estaremos contratados.",
"Sim, senhor Christopher, eu entendo.",
"Você falou comigo pela segunda vez, agora somos contratados para trabalhar juntos em sua missão. Em primeiro lugar a questão da palavra SWIM. Essa é a sua preocupação inicial, correto?",
"Sim, senhor Christopher, não consigo imaginar como isso me levaria a um tesouro.",
"É a parte da ilha que você deve procurar. As duas primeiras letras 'SW' significam Sudõeste.",
"Agora que você diz isso, isso é bastante óbvio. E o que significa IM?",
"Ilha da Morte",
"Oh! E onde é isso?",
"Ah! Isso é um pouco mais complicado, querido. Essa ilha sempre esteve envolta em algum mistério. Seu pai deve ter enviado uma segunda mensagem com o restante das informações, então se uma mensagem fosse interceptada, não ajudaria sem a outra. Agora, para quem seu pai poderia ter enviado cartas? Obviamente, dentro da família, ele não teria confiado em mais ninguém.",
"Bem, eu, minha irmã Bonnie.. e.. meu irmão Blaze.",
"Então aí está. Sua irmã não recebeu nada, caso contrário ela teria lhe contado, então é seu irmão Blaze que você precisa encontrar para completar o quebra-cabeça.",
"Hummm! Então, como faço para encontrá-lo? Não tenho ideia de onde ele foi.",
"A última vez que ouvi ele foi em #sisland_Quebradas Costillas#. Eu tentaria lá primeiro, na verdade estou precisando de um pouco de ar marinho, então eu mesmo irei acompanhá-lo até lá.",
"Entendo, obrigado, Sir Christopher. Tem mais uma coisa.",
"Agora não, querido! Agora não. Estou precisando de uma soneca. Você vai e se reforma ou o que quer que precise fazer, e eu me encontrarei com você no porto quando estiver pronto para partir.",
"Oh! Bem, obrigado de qualquer maneira.",
"Uau! Quase cochilei lá! Você está pronto para navegar então?",
"Sim, estamos prontos. Vamos.",
"Bem, devo dizer que foi uma viagem bastante revigorante. Sempre durmo melhor no mar.",
"Estou feliz que você gostou. Suponho que deveríamos ir à Taverna para ver o que podemos descobrir?",
"Não não! Eu tenho contatos aqui, você sabe. Fazemos parte do mesmo grupo de irmãos, por assim dizer. Iremos direto ao chefe da residência.",
"Oh! Isso soa bem. Deveríamos obter informações melhores lá, pelo menos.",
"Precisamos de avançar, temos trabalho a fazer.",
"Você não precisa de uma soneca primeiro?",
"Deixe-me ajudar, querido, afinal conheço esses senhores pessoalmente.",
"Sim mas..",
"Cavalheiros! Eu anseio por sua indulgência. Por uma questão de honra, a Irmandade tem a obrigação de ajudar esta jovem na procura do seu irmão.",
"Fomos levados a acreditar que ele está aqui na sua ilha.",
"Mas o que! Eu, querida?",
"Você não disse a eles o nome dele!",
"Oh! Tenho certeza que fiz isso, querido, tenho certeza que sim",
"Você não fez isso! O nome dele é Blaze Devlin, senhores.",
"#sisland_Redmond# você diz! Droga e explosão!, (desculpe, querido), Essa é uma ilha espanhola!",
"Oh céus!",
"E, por melhor que seja a minha velha banheira, ela estaria fortemente pressionada contra uma frota de navios da marinha de Sua Majestade Católica!",
"Bem, meus queridos! Eu acho que isso vai resolver. Vamos organizar nossos navios e seguir para #sisland_Redmond#. Com esta frota poderemos enfrentar qualquer patrulha espanhola que encontrarmos e conheço uma praia onde podemos desembarcar, não muito longe da cidade.",
"Parece uma boa ideia!",
};
