string DLG_TEXT[31] = {
"Você não vê que estou de plantão! Não me incomode.",
"Tudo bem, tudo bem.",
"Você queria denunciar algum crime?",
"Claro que não. Afinal, sou um capitão... mas vejo que você não está ouvindo.",
"Lembre-se: não permitimos brigas nas ruas. Você pode se defender, é claro, se alguém te atacar.",
"Certo, vou considerar essa informação.",
"Um tempo tão insuportável... e eu tenho que ficar aqui nele. Você pode não acreditar, mas meu único passatempo é lutar contra as moscas que tentam pousar no meu rosto.",
"Isso é muito lamentável, mas não posso ajudá-lo. É seu dever.",
"Se você quiser conversar, encontre outra pessoa. Tenho o meu dever a cumprir e não é meu dever falar contigo.",
"Eu só estava me perguntando se você está vivo ou não. Você está aqui como uma estátua",
"Você acha que é fácil proteger nossa cidade? De jeito nenhum! É um trabalho muito importante e perigoso. Lembro-me de uma vez...",
"Conte-me em outra hora. Eu tenho que ir.",
"Siga seu caminho, não me incomode",
"Como você diz, soldado.",
"Ei! Você pode me trazer uma xícara de rum da taverna?",
"Talvez. Mas não vão me enforcar por ajudar um soldado a ficar bêbado em serviço? Não, espere até eles trocarem a guarda, e então você poderá beber o quanto quiser.",
"Por que deve ser um marinheiro rude como você tentando falar comigo?! Não há mulheres bonitas nesta cidade?",
"E você chama isso de cumprir seu dever? Olha, você não gostaria de perder a captura de um criminoso perigoso como eu, não é? Ha-ha!",
"Você parece muito saudável. Você não quer se juntar ao nosso exército? Temos muito espaço no quartel, boa comida, rum de graça.",
"Parece bom, mas terei que recusar sua oferta. A disciplina do exército não combina comigo.",
"Este calor.... Daria tudo para voltar à Europa, à civilização...",
"Sim, parece que este clima não combina com você.",
"Vou fingir que não ouvi isso, senão posso me sentir ofendido.",
"Ah, sinto muito, senhora. Minha mente estava em outro lugar. Não foi de forma alguma minha intenção ofendê-lo.",
"Está tudo bem, soldado. Só não cometa o mesmo erro quando minha irmã passar por aqui.",
"Bem, eu tenho duas irmãs. Mas aproximar-se de qualquer um deles prejudicaria sua saúde.",
"Isso foi uma ameaça, marinheiro?",
"Não, um aviso. Bea e Bonnie não toleram tolos de bom grado... Você está ouvindo?",
"COM LICENÇA?!",
"Ah, pelo contrário, minha querida. Por favor, perdoe essa minha tolice. Posso lhe oferecer uma bebida depois do meu turno?",
"Nos seus sonhos, nerd!",
"",
};
