string DLG_TEXT[28] = {
"Que lindo esquema de cores e textura...",
"Sim, um belo navio.",
"Então, você acha que posso ajudá-lo em sua missão?",
"Sim, Capitão Terror, por favor",
"Então você deve contratar comigo para conseguir minha ajuda. Lembre-se de que sou furtivo e não uso a força quando não é necessária, mas posso dar um soco quando necessário. Pense bem ou fale primeiro com alguns dos outros, mas se você falar comigo novamente, estaremos contratados.",
"Sim, capitão, eu entendo.",
"Você falou comigo pela segunda vez, agora somos contratados para trabalhar juntos em sua missão. A palavra SWIM é apenas parte da informação que você precisa. Precisamos pegar o resto.",
"Sim, capitão, eu não conseguia imaginar como essa parte me levaria a um tesouro.",
"Não era para isso acontecer. Caso a mensagem tenha caído em mãos erradas, ela será dividida em partes.",
"Agora você diz isso, isso é bastante óbvio?",
"Sim, talvez seja. Precisamos descobrir quantas peças e onde elas estão.",
"Oh! E como nós fazemos isso?",
"Ah! Isso é um pouco mais complicado. Seu pai deve ter enviado várias mensagens com o restante das informações. Agora, para quem seu pai poderia ter enviado cartas? Obviamente, dentro da família, ele não teria confiado em mais ninguém. Quem ainda está vivo na sua família?",
"Bem, eu, minha irmã Bonnie.. e.. Minha outra irmã, Beatrice.",
"Então aí está. Sua irmã Bonnie não recebeu nada, caso contrário ela teria lhe contado, então é sua outra irmã, Beatrice, que você precisa encontrar para completar o quebra-cabeça.",
"Hummm! Então, como faço para encontrá-la? Não tenho ideia de onde ela foi.",
"A última vez que ouvi ela foi em #sisland_Oxbay#. O problema é que é uma ilha inglesa e não há como navegarmos lá sob a bandeira pirata, a menos que tenhamos ajuda.",
"Que ajuda é essa então?",
"Conheço um lugar que é uma praia deserta no lado sul da ilha. Acho que este é um caso em que a discrição superará a força. Tudo o que precisamos fazer depois disso é encontrar sua irmã. Faça o que precisar agora, encontro você no cais.",
"Isso parece bastante lógico. Vou me preparar para navegar.",
"Você está pronto para navegar então?",
"Sim, estamos prontos. Vamos.",
"Bem, devo dizer que foi uma viagem e tanto. É melhor continuarmos com o assunto em questão. Não podemos ficar aqui por muito tempo, os navios do Rei logo estarão sobre nós. Vamos para a cidade!",
"Oh! Sim, eu entendo. Suponho que deveríamos ir à Taverna para ver o que podemos descobrir?",
"Esse seria o lugar óbvio para começar.",
"Estamos prontos para ir?",
"Sim, enviei o navio para o mar com ordens de permanecer fora do local de terra e de não enfrentar os navios ingleses. Podemos sinalizar quando retornarmos. ",
"Isso soa bem. Vamos então.",
};
